### ISSUE TITLE
Year View with 12 Mini-Calendars

### ISSUE THREAD

**Issue by arshaw** [fullcalendar/fullcalendar#1140]
Originally reported on Google Code with ID 871

```
The attach file is a year view sample.
I made it by fullcalendar version.


```

Reported by `kebin.liu` on 2011-03-28 09:10:48

<hr>
- _Attachment: [fullCalendar15.rar](https://storage.googleapis.com/google-code-attachments/fullcalendar/issue-871/comment-0/fullCalendar15.rar)_

Imported with **51** stars.

**Comment by piyushchauhan2011** [comment]
:+1:

**Comment by phammer** [comment]
@arshaw : Any more or less official plan to release such a year view in the official release? We started to prototype with tanguy.pruvot's year view.

**Comment by valteraki** [comment]
Hello!  I am using this and till now all went smooth ... But now i encountered a problem  .. is it possible to choose a event  by yearview (considering there will always only be 1 event for 1 day) and for example go to a page or get the title (url:) all this only on the yearview...

**Comment by LorenGr** [comment]
Hi all, tanguy's addition to fullcalendar is absolutely great, fullcalendar however is moving forward in versions and year view is getting outdated. Please help me update tanguy's yearview with the latest fullcalendar version. I already did work to adapt to the updated fullcalendar grid and view api's. Please find it here : http://plnkr.co/edit/5U6vua
I am not managing to get the renderSelection mechanism working. And the css is missing, but most of yearview is now working with the latest fullcalendar version, check out the plunker above.

**Comment by freshman21** [comment]
Hi, any luck on putting this to work on the newer version? I'm trying to adapt the plnkr example LorenGr posted but i keep getting an error on this line:

dayGrid.coordMap.containerEl = dayGrid.scrollerEl; // constrain clicks/etc to the dimensions of the scroller

it says coordMap is undefined, what am i missing? I'm not very experienced in this kind of stuff

**Comment by G89Angel** [comment]
Would be great to have this in the new 3.0.1 version. Any plans of implementing it anytime soon?

**Comment by espen** [comment]
@G89Angel 3.0.1 is already released. https://github.com/fullcalendar/fullcalendar/releases/tag/v3.0.1

**Comment by arshaw** [comment]
A year view can be created via a **list view** but I believe this ticket is concerned with rendering a year as 12 tiled mini month-view calendars.

**Comment by spookycookie27** [comment]
What would be the correct way to get the year view to start on the current month, rather than defaulting to January ?

**Comment by meoz** [comment]
Is there any update on this request ? Is the full-year calendar still worked ?

**Comment by StudioJunkyard** [comment]
Hi @arshaw , Adam this I believe would be a very welcome addition. As it is, I've had to implement a view changer in my CMS for my client's that switches between the Calendar, and a table showing previous months events. Will the year view show events placed into the calendar, and be able to switch to that month chosen, and render the placed events?

**Comment by senzaikenn** [comment]
+1

**Comment by dusanm65** [comment]
I have modified above metioned plunker and added dragging, resizing and selection, please have a look: http://plnkr.co/edit/1I9qfzuHSsoZnQq4lzz5?p=preview

**Comment by koganei** [comment]
Hi @arshaw, do you have some sort of ETA on when we can expect this to be in an official release?
Thank you

**Comment by dusanm65** [comment]
Hi @koganei ,
I am happy to see that you're interested in this feature.
In the mean time while it's on its way to the main release,
is there anything you would like to see there that would improve the functionality?

Thanks in advance

**Comment by MaddHatters** [comment]
Hi @arshaw @dusanm65. I just wanted to add my support for the mini calendar addition. I think it will really be a nice asset. If I have any suggestions or comments, is this issue the best place to leave them?

**Comment by espen** [comment]
@MaddHatters yes, suggestions and comments are much welcome here :) Also make sure you [vote for this issue as explained here](https://fullcalendar.io/wiki/Requesting-Features/)

**Comment by cansozeri** [comment]
When will this feature release ??

**Comment by jfranpino** [comment]
Excuse me but I do not understand something.
In the official version 3.7.0 you have the view of the year with 12 months?

**Comment by acerix** [comment]
The calendar does not yet have a built-in view with 12 mini calendars as described in this feature request.

It's hard to say when this will be added, there are many other open requests, but this one is at the [top of the list](https://fullcalendar.io/issues/) by popularity.

**Comment by jfranpino** [comment]
ok, thank you acerix.

**Comment by marc-khoury-kronos** [comment]
Hi @acerix, any update on when this could be available? We would love to buy the Scheduler plugin, but since we're using a custom year view, we can't upgrade our fullcalendar from v2 to v3 to use the Scheduler plugin.

**Comment by gowsikk** [comment]
this.calendarOptions = {
        editable: true,
        eventLimit: false,
        header: {
          left: 'prev,today,next',
          center: 'title',
          right: 'year,month,basicWeek'
        },
         views: {
      month:{
        
      },
       basicWeek: {
         
        },
      year: {
        type:'agenda',
        
        }
      },
        events: []
      };
  }

This is my typescript code .In year, what type i need to gave except agenda.Because no other type is working.

**Comment by Lynn-cc** [comment]
The fullCalendar version of the year view version is very old so that methods and events are different with the docuement. I have to fixed bugs by myself. Could this publish a version for us.

**Comment by Lynn-cc** [comment]
@devsullo yes, I've modified a few code. And I've found that some fullCalendar's new features in the recent version didn't support or didn't effective because of bugs.
I think I could give you some of the modifies and problems I found:
1. `columnHeader` param didn't support.
2. `removeEventSource` didn't effective, I can't clear the events so that I have to rebuild the calendar.
3. `.fc-year-monthly-header` class of the `localMonthNames`  dom didn't wrap with a `<th>` so that I can't add styles for the text.
4. classes start with `.fc-day-` didn't reset when the year changes.
5. I can't hide the `.fc-other-month` days.
6. The `className` of the event param didn't add to the day dom, so that I can't add style for them. I don't how recent version do with the param, probably there is some other better way to add styles for the days with events.
7. Mouse events functions didn't effective.

**Comment by devsullo** [comment]
@Lynn-cc I've created year view based on current version, you can checkout here [fullcalendar-year-view](https://github.com/devsullo/fullcalendar-year-view)
But it still needs **testing**
You can install it via npm `i fullcalendar-year-view`

**Comment by wojciechlampa** [comment]
@acerix Do you plan to include year view for v4 of fullcalendar?

**Comment by CalvinWu4** [comment]
> @Lynn-cc I've created year view based on current version, you can checkout here [fullcalendar-year-view](https://github.com/devsullo/fullcalendar-year-view)
> But it still needs **testing**
> You can install it via `npm i fullcalendar-year-view`

Can you provide a screenshot of what it looks like?

**Comment by sfarzoso** [comment]
I would like to buy the premium version of FullCalendar, but I need the year view, will this feature implemented soon?

**Comment by shreyas-agrawal** [comment]
By when we can expect this feature of having year view with 12 mini calendars to be released in fullcalendar?

**Comment by lovecoding-git** [comment]
Hi I would like to get year view function even theough it would be expensive. When could you release it?

**Comment by cressije** [comment]
Maybe here : https://year-calendar.github.io/v-year-calendar/getstarted

**Comment by Nandishju** [comment]
> ```
> This would be a valuable addition to fullCalendar, please merge :)
> 
> It has issues of it's own: moving an event (from a different view) doesn't update the
> year view; and it would be nice to be able to drill down by clicking month's name.
> 
> Keep up the great work!
> ```
> 
> Reported by `corin.lawson` on 2011-06-26 03:11:20

Can you please give me a repo link? I want to use year view ..please

**Comment by pamgaiguer** [comment]
Any idea when the Year view will be available?!

**Comment by dusanm65** [comment]
Never the owner of the repo is useless and never merged my work

**Comment by spookycookie27** [comment]
I used this full Calender in year view by copying the approach used by someone else higher up the comments. I think it was basically 12 mini calendars but from what I remember it worked fine and was easy to implement. Its been a few years since I worked on it. Pretty sure its still live and working. But there are much newer Calendars if you search around and ones that are still actively maintained. It looks like this one isnt maintained anymore. But Kudos must be given to the guy that created it @dusanm65 .
If you have commits that could have been merged in, you could easily fork this repo and release your updates, Im sure loads of ppl will be thankful. :)

**Comment by SimonBrazell** [comment]
Could try [this](https://year-calendar.github.io/), worked well for me in the past.

**Comment by pamgaiguer** [comment]
thanks @SimonBrazell but i need the angular version :/

**Comment by srinipatha** [comment]
I am unable to use this feature (year view), is there any specific subscription required, if yes please let me know.

**Comment by arshaw** [comment]
This feature has been implemented:

- docs: [Multi-Month Grid](https://fullcalendar.io/docs/multimonth-grid)
- github release: [v6.1.0](https://github.com/fullcalendar/fullcalendar/releases/tag/v6.1.0)
- blog post: [Multi-Month and more in v6.1](https://fullcalendar.io/blog/2023/01/multimonth-and-more)
