### ISSUE TITLE
More easily toggle event visibility

### ISSUE THREAD

**Issue by arshaw** [fullcalendar/fullcalendar#1147]
Originally reported on Google Code with ID 878

```
Hey,

It would be nice to toggle specific events without removing them from the source. 
or/and adding a "visible" property to the event object. if set to false the event is
not visible in the calendar, and i could do sth like;

$('#calendar').fullCalendar({
  eventClick: function(calEvent, jsEvent, view) {
    calEvent.visible = false;
    $('#calendar').fullCalendar('updateEvent', calEvent);
  }
});

which would hide the event, and reposition the surrounding elements. 

its similar to the Google Calendar where i can toggle specific calendars...

great work by the way....

```

Reported by `kalle.saas` on 2011-03-31 12:57:59

Imported with **6** stars.

**Comment by jamesdixon** [comment]
@arshaw any update on this? looking for an optimal way to do filtering that:

- is applied immediately to the existing event source
- stays applied when switching views
- can be cleared and restore the original event source

Is there a current solution you'd recommend to achieve the above?

Thanks for the great piece of software!

**Comment by vooxo** [comment]
I've found a way to make this working on my project:
For example, group events by using the `className` event object property:
    var events = [
        {
            'title' : 'Event 1',
            'className' : 'group-1'
        },
        {
            'title' : 'Event 2',
            'className' : 'group-1'
        }
    ];
And then you can toggle the visibility using that class:
`$('.group-1').toggle();`

**Comment by arshaw** [comment]
toggling classnames is one solution.

also, dynamically setting the `display` property with `setProp` is another:

```js
let event = calendar.getEventById('a')
event.setProp('display', 'none' ) // hide
event.setProp('display', 'auto') // return to normal
```

More info on the `display` property: https://fullcalendar.io/docs/eventDisplay

**Comment by ketna11** [comment]
How to achieve the same effect using event class (assigned in json to event)?
Something like this does not work:
`let event = calendar.getElementsByClassName('a');
event.setProp('display', 'none' );

**Comment by vooxo** [comment]
I think `getElementsByClassName` returns an array, so you must loop through it and set the property on each element.

[https://developer.mozilla.org/en-US/docs/Web/API/Document/getElementsByClassName](https://developer.mozilla.org/en-US/docs/Web/API/Document/getElementsByClassName)

**Comment by superjojo140** [comment]
My workaround to change a property for all events from one specific eventSource:

````javascript
    let allEvents = fullCalendarInstance.getEvents();
    for (let ev of allEvents) {
        if (ev.source.id == EVENT_SOURCE_ID) {
            ev.setProp("propertyName", newValue); //see: https://fullcalendar.io/docs/Event-setProp
            ev.setProp("display", "none"); //For example hide all theese events
        }
    }
````
