### ISSUE TITLE
Prevent dragging an event to different day, only allow dragging time

### ISSUE THREAD

**Issue by arshaw** [fullcalendar/fullcalendar#1153]
Originally reported on Google Code with ID 884
```
...in agenda view.
```

Reported by `adamrshaw` on 2011-04-03 23:11:28

Imported with **2** stars.

**Comment by TejasCMehta** [comment]
is there any way to make it work on FullCalendar 1.6.4?

**Comment by arshaw** [comment]
rather than making this a separate setting, i'd prefer [eventAllow](https://github.com/fullcalendar/fullcalendar/issues/2740) to be used
https://github.com/fullcalendar/fullcalendar/issues/2740
&uarr;
Could you please visit the link, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates?

@TejasCMehta unfortunately a solution won't be implemented on a 1.x version

**Comment by ariadnimac** [comment]
For anyone looking to implement this, it works perfectly as follows with eventAllow:

eventAllow: function(dropInfo, draggedEvent) {
	const start = dropInfo.start;
	const end = dropInfo.end;

	const startDay = start.getDate();
	const endDay = end.getDate();

	return startDay == endDay;
},
