### ISSUE TITLE
equal width of each day

### ISSUE THREAD

**Issue by arshaw** [fullcalendar/fullcalendar#1175]
Originally reported on Google Code with ID 906

```
how do you set the width of each column equally, as of the moment the width of each
columns are different in size especially saturday and sunday
```

Reported by `hvillacruz` on 2011-04-13 15:34:26

**Comment by StefanoGitHub** [comment]
Hello,
would it be possible to add the option to have different, e.g. smaller, widths for non-business days (when displayed), at least in agenda week view? 
It would be a nice way to give more emphasis to generally busier week days compared to weekends.
I tried to use CSS to  resize the columns, but I found out events are placed after the week grid is rendered, so they are all messed up.
Thanks

**Comment by arshaw** [comment]
@StefanoGitHub this issue captures what you're asking for, albeit in a more vague way:
https://github.com/fullcalendar/fullcalendar/issues/1603
&uarr;
Could you please visit the link, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates?

We'll use that issue to track demand
