### ISSUE TITLE
is it possible to use hijri calender

### ISSUE THREAD

**Issue by arshaw** [fullcalendar/fullcalendar#1263]
Originally reported on Google Code with ID 996

```
is it possible to use hijri calender
```

Reported by `iman.amirdarabi` on 2011-06-14 18:36:52

**Comment by VickyPatel09** [comment]
Is it possible to change calendar to Hijri?

**Comment by AhemdHegazy** [comment]
i want to use Hijri calender

**Comment by zahraHonarvar** [comment]
Is it possible to change calendar to Hijri in version 5.9 fullcalnder ?
