### ISSUE TITLE
Prevent multi-day events being moved from allday section to hours slots section

### ISSUE THREAD

**Issue by arshaw** [fullcalendar/fullcalendar#1406]
Originally reported on Google Code with ID 1139

```
As per image.

With google calendar, if there is a multi-day event it goes to the "All Day" events
section when looking at Day or Weekly agenda views.  It also cannot be moved into the
time slot section as well.

Can we have this similar functionality with FC?  As currently, I can mimick the same
functionality with GC.  As any multiday events will have the allday flag by default.
 But I cannot prevent the event from being moved into the timeslot section.

Thanks


```

Reported by `no1youknowz` on 2011-10-07 10:19:58

<hr>
- _Attachment: Screenshot - 071011 - 11:15:43.png<br>![Screenshot - 071011 - 11:15:43.png](https://storage.googleapis.com/google-code-attachments/fullcalendar/issue-1139/comment-0/Screenshot - 071011 - 11:15:43.png)_

Imported with **2** stars.

**Comment by bruceyue** [comment]
https://fullcalendar.io/docs/external-dragging-demo
Check this link, if we drag event from left side to calendar, if event number more than 3, only first two events can be dragged, the remaining can not. But I need it. Is it a bug?

**Comment by arshaw** [comment]
this feature should be possible by implementing a custom `eventAllow` function
https://fullcalendar.io/docs/eventAllow
