### ISSUE TITLE
Select Box for Year and Month in Header

### ISSUE THREAD

**Issue by arshaw** [fullcalendar/fullcalendar#1528]
Originally reported on Google Code with ID 1261

```
Hi all, 
I've just made small modification for fullcalendar and added option to display selectbox
of year and month in header. 

You just simply use text 'select-my' in header specification.

Also you can specify how many years to show forward in the selectbox using options
selectMY: { years: n }.

Maybe someone will use it.

Because it is not possible to attach files now, patch can be found here: http://horinek.net/~dal/fullcalendar-1.5.2-selectmy.patch
```

Reported by `dalibor.horinek` on 2012-01-25 00:21:59

**Comment by bigfootcreative** [comment]
Tried to see the demo 
Demo can be found here: http://horinek.net/~dal/fullcalendar-demo/, packed version including
the code: http://horinek.net/~dal/fullcalendar-demo.zip

Is there any chance I can see how the year and month dropdown was programmed. 

Thank you
