### ISSUE TITLE
Linking full calendar to datepicker and datepicker to fullcalendar

### ISSUE THREAD

**Issue by arshaw** [fullcalendar/fullcalendar#1652]
Originally reported on Google Code with ID 1385

```
Hello,

I'm working on a project that has a calendar function. I use full calendar for the
calendar function, and I use datepicker to navigate through the calendar. That works
fine.

But when i go to a next dag in full calendar I want my datepicker to select the selected
date of my full calendar.

Does anyone know how to solve this?

```

Reported by `hans@st.fenj.nl` on 2012-04-25 08:17:25

**Comment by bigossz** [comment]
> Originally reported on Google Code with ID 1385
> 
> ```
> Hello,
> 
> I'm working on a project that has a calendar function. I use full calendar for the
> calendar function, and I use datepicker to navigate through the calendar. That works
> fine.
> 
> But when i go to a next dag in full calendar I want my datepicker to select the selected
> date of my full calendar.
> 
> Does anyone know how to solve this?
> ```
> 
> Reported by `hans@st.fenj.nl` on 2012-04-25 08:17:25

I'm trying to solve the same issue, did you manage it?
