### ISSUE TITLE
Render event sources asynchronous, as they are fetched

### ISSUE THREAD

**Issue by arshaw** [fullcalendar/fullcalendar#1672]
Originally reported on Google Code with ID 1405

```
Currently, fetchEventSource method checks if all pending sources have their events normalized
before calling reportEvents, which will then clean the complete view.

Since multiple sources can be defined, it makes sense to normalize and display their
events asynchronously instead of waiting for all sources to be fully processed before
continuing. I think that source should not delay all other.







```

Reported by `marco@zoqui.com` on 2012-05-15 12:17:27

Imported with **9** stars.

**Comment by kirs** [comment]
@arshaw any updates on this side?

**Comment by mitomm** [comment]
Any updates on this one? I would really like to have such an option too.

Thanks in advance.

**Comment by Jules2010** [comment]
+1

**Comment by georgehrke** [comment]
I guess it makes sense to have a configuration switch for that, because otherwise if all your event sources are fast, it will create a huge overhead for rendering. 

I'd be very happy to help implementing this. 
Any pointers where to begin or what to pay attention to?

**Comment by arshaw** [comment]
This issue has been addressed in the latest alpha release (4.0.0-alpha.2)
[See the blog post &raquo;](https://fullcalendar.io/blog/2018/10/release-v4-alpha2)

https://fullcalendar.io/docs/v4/progressiveEventRendering

**Comment by arshaw** [comment]
I'm closing this issue to signify that it's implemented (since v4-alpha2). I'll comment on this thread again when v4 is officially released.

**Comment by arshaw** [comment]
[V4 was officially released a few days ago!](https://fullcalendar.io/blog/2019/03/v4-officially-released)
