### ISSUE TITLE
A new view, like Agenda view, but with axis flipped

### ISSUE THREAD

**Issue by arshaw** [fullcalendar/fullcalendar#1753]
Originally reported on Google Code with ID 1486
```
Hi 
Just wondering if it possible to have a time picker styled calender similar to the
week view but the times on the x axis and the days on the y axis.  Requiring  a control
that is similar to the Windows 7 parental user control.  There doesnt seem to be any
out there for the jquery framework

Cheers


Andrew
```

Reported by `andrewnmunro` on 2012-08-02 12:53:36

**Comment by arshaw** [comment]
This has been implemented in the newly released Timeline view, which is part of the Scheduler add-on:

http://fullcalendar.io/scheduler/

By the way, Timeline will work even without resources. Simply do not specify resources and you will get a timeline events going left-to-right.

**Comment by rhysturner** [comment]
Can the scheduler event flow/drag over multiple days like in the calendar (but switched x and y axis)? Or is the scheduler just for resources?

**Comment by arshaw** [comment]
No, timeline view's events can only span horizontally across a line, they do no wrap in any way
