### ISSUE TITLE
Swap x and y axis on Week view

### ISSUE THREAD

**Issue by arshaw** [fullcalendar/fullcalendar#1808]
Originally reported on Google Code with ID 1541

```
The calendar is incredible... and I'm truly hoping I'm not missing something that's
already available. Can there be a way for (week view) to swap x and y? Meaning, allowing
the dates to be on the left, and the times to be at the top?



```

Reported by `pryan@reflectmediagroup.com` on 2012-09-19 19:22:55

**Comment by nmittapalli** [comment]
Do we have this in "agendaWeek" ?Could we swap x and y axis

**Comment by arshaw** [comment]
What you're describing is essentially [timeline view](https://fullcalendar.io/scheduler/) I think.
