### ISSUE TITLE
Jalali Date

### ISSUE THREAD

**Issue by arshaw** [fullcalendar/fullcalendar#1874]
Originally reported on Google Code with ID 1607

```
Hi,
Please add Jalali Date to fullcalendar,for irainian users.

http://en.wikipedia.org/wiki/Jalali_calendar
```

Reported by `bahramisoft` on 2012-11-12 19:47:05

**Comment by ehsandanesh** [comment]
Hi everybody I added Jalaali calendar to version 2.6.0 and solved previous issues in this update you can find it from here:
https://github.com/ehsandanesh/fullcalendar
