### ISSUE TITLE
call to updateEvent force rerender of all events

### ISSUE THREAD

**Issue by arshaw** [fullcalendar/fullcalendar#2065]
Originally reported on Google Code with ID 1798

```
currently all events are cleaned and are rendered again in case of update at one single
event.
i have to display a big amount of events in a week view and rerender takes ~10 seconds
on every single update :(.
is there a way to rerender only one modified event?
```

Reported by `Maksim.Yakavenka` on 2013-04-19 12:11:12

**Comment by adheus** [comment]
Hi, arshaw. Can this be done by calling the function with an array of updated events than rendering? If i call this multiple times in a for it hangs for a while.

**Comment by arshaw** [comment]
@adheus the best workaround i can think of to avoid the rerendering of all the events is `addEventSource` / `removeEventSource`
