### ISSUE TITLE
Lunch break

### ISSUE THREAD

**Issue by arshaw** [fullcalendar/fullcalendar#2219]
Originally reported on Google Code with ID 1952

```
First of all, i'd like to thank you for this wonderful job - making so powerful tool.

So, didn't found any info about implementation of lunch breaks. If employee must be
unavailable 12am till 1pm, what to do? for example, this period's gray-colored every
day monday-friday.

Thank you.
```

Reported by `elpassport@meta.ua` on 2013-08-07 20:46:16

**Comment by Goddard** [comment]
Is this a documented and completed feature?

Only thing I can find is this and a stackoverflow question https://stackoverflow.com/questions/40116791/how-to-put-interval-of-time-for-lunch-using-fullcalendar
