### ISSUE TITLE
Select Box for Year and Month in Header

### ISSUE THREAD

**Issue by arshaw** [fullcalendar/fullcalendar#2280]
Originally reported on Google Code with ID 2015

```
The possibilty for user to choose current year and month in header in month view (currently
there are only previous and next month arrows) should be very useful.

There was a pull request some time ago to implement it (http://code.google.com/p/fullcalendar/issues/detail?id=1261,
http://code.google.com/p/fullcalendar/issues/detail?id=514) but it was not accepted,
I suppose...

A demo can be seen here: http://horinek.net/~dal/fullcalendar-demo/
```

Reported by `marcosolari` on 2013-10-10 20:54:23

**Comment by scottknoblesmith** [comment]
I can't tell if this was implemented or not.   It would be very useful, to have a pulldown of resources to select from

**Comment by arshaw** [comment]
a dropdown for year/month has NOT been implemented yet. the ticket to track is here: https://github.com/fullcalendar/fullcalendar/issues/784

however, you're asking for a dropdown of *resources* ? could you open up a new ticket on the [fullcalendar-scheduler issue tracker](https://github.com/fullcalendar/fullcalendar-scheduler/issues) to discuss that?
