### ISSUE TITLE
Export calendar to PDF

### ISSUE THREAD

**Issue by arshaw** [fullcalendar/fullcalendar#2301]
Originally reported on Google Code with ID 2036
```
Hi,

I don't know where is the place to post this tip so i use a new issue.

For my website, I want to export my calendar to pdf. Ther is the way to obtain that
:)

Hope That Help You !

----
1 : download external files

JSPDF : use to generate a PDF file (http://parall.ax/products/jspdf)
html2canvas : use to generate a JPEG file of your #div calendar (http://html2canvas.hertzen.com/)

----
2 : install only the files needed
html2canvas.min.js
jspdf.js
jspdf.plugin.addimage.js

---
3 : now the code :)

3.1 : the pdf button

We add a new button in the header 

$("td.fc-header-left").append('<span id="AE_btn_pdf" class="cal-button"><input type="hidden"
id="zz_pdf" value="" />' + AEFC.translate("Pdf") + '</span>');

3.2 : the code to have a ui like button

   $("#AE_btn_pdf").button({
      icons: {
         primary: "ui-icon-image"
      },
      text: false
   }); // $("#AE_btn_pdf").button(

3.3 : the code to have the pdf... Yes it's very simple but usefull code :)

   $("#AE_btn_pdf").click(function () {
      //#AEFC is my div for FullCalendar
      html2canvas($('#AEFC'), {
         logging: true,
         useCORS: true,
         onrendered: function (canvas) {
            var imgData = canvas.toDataURL("image/jpeg");
            var doc = new jsPDF();      
            doc.addImage(imgData, 'JPEG', 15, 40, 180, 160);
            download(doc.output(), "AEFC.pdf", "text/pdf");                       
 
         }
      }) ;      
   }); // $("#AE_btn_pdf").click(function ()

--
4 JS : download function

function download(strData, strFileName, strMimeType) {
    var D = document,
        A = arguments,
        a = D.createElement("a"),
        d = A[0],
        n = A[1],
        t = A[2] || "text/plain";

    //build download link:
    a.href = "data:" + strMimeType + "," + escape(strData);

    if (window.MSBlobBuilder) {
        var bb = new MSBlobBuilder();
        bb.append(strData);
        return navigator.msSaveBlob(bb, strFileName);
    } /* end if(window.MSBlobBuilder) */

    if ('download' in a) {
        a.setAttribute("download", n);
        a.innerHTML = "downloading...";
        D.body.appendChild(a);
        setTimeout(function() {
            var e = D.createEvent("MouseEvents");
            e.initMouseEvent("click", true, false, window, 0, 0, 0, 0, 0, false, false,
false, false, 0, null);
            a.dispatchEvent(e);
            D.body.removeChild(a);
        }, 66);
        return true;
    } /* end if('download' in a) */    

    //do iframe dataURL download:
    var f = D.createElement("iframe");
    D.body.appendChild(f);
    f.src = "data:" + (A[2] ? A[2] : "application/octet-stream") + (window.btoa ? ";base64"
: "") + "," + (window.btoa ? window.btoa : escape)(strData);
    setTimeout(function() {
        D.body.removeChild(f);
    }, 333);
    return true;
} /* end download() */
```

Reported by `elecoest` on 2013-11-17 17:13:34

Imported with **5** stars.

**Comment by pravinbhosale01** [comment]
Great! really easy way to get PDF. Just curious to know (Universal worry)Which versions of IE are supported here?

**Comment by espen** [comment]
@pravinbhosale01  please see https://parall.ax/products/jspdf "jsPDF will work in IE6+*, Firefox 3+, Chrome, Safari 3+, Opera. For IE9 and below, we lazily load a Flash shim called Downloadify which enables the files to be downloaded. (Current build does not have IE6-9 shim enabled)"

**Comment by arshaw** [comment]
I declare that this feature is out of the scope of the FullCalendar project. It's tech stack is sufficiently different from FullCalendar's where I feel it should be a separate project.

**Comment by maestrojosiah** [comment]
I achieved the same using this code in May 2021 using jspdf.debug.js and html2canvas.js:
`        $(document).on('click', '[id="pdf"]', function(){
            
            var pdf = new jsPDF('p', 'pt', 'letter');
            pdf.setFont("helvetica");
            pdf.setFontType("bold");
            pdf.setFontSize(9);
            pdf.addHTML($('#f-cal')[0], function () {
                pdf.save('Test.pdf');
            });

        })
`

**Comment by iamandreadompe** [comment]
I use this code
`                    html2canvas($("#calendar")[0]).then((canvas) => {
                        var imgData = canvas.toDataURL("image/jpeg");
                        var doc = new jsPDF();
                        doc.addImage(imgData, 'JPEG', 15, 40, 180, 160);
                        download(doc.output(), filename, "text/pdf");
                    });`

but the pdf doesnt render the calendar event colors
[AEFC.pdf](https://github.com/fullcalendar/fullcalendar/files/6736839/AEFC.pdf)

**Comment by xespinos** [comment]
> 

Were you able to achieve this? I am facing the same problem.

**Comment by xespinos** [comment]
> ```
> Hi thanks you for your work, but do you have a solution to convert as a pdf a calendar
> but with a scrollbar, because when i use you method it converts only what is display
> on the browser screen and not what is hide
> ```
> 
> Reported by `test.logograph` on 2014-05-21 12:40:34

Were you able to achieve it? I am facing the same problem with a calendar that has scrollbar

**Comment by Khawer-31** [comment]
> > ```
> > Hi thanks you for your work, but do you have a solution to convert as a pdf a calendar
> > but with a scrollbar, because when i use you method it converts only what is display
> > on the browser screen and not what is hide
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Reported by `test.logograph` on 2014-05-21 12:40:34
> 
> Were you able to achieve it? I am facing the same problem with a calendar that has scrollbar



> > ```
> > Hi thanks you for your work, but do you have a solution to convert as a pdf a calendar
> > but with a scrollbar, because when i use you method it converts only what is display
> > on the browser screen and not what is hide
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Reported by `test.logograph` on 2014-05-21 12:40:34
> 
> Were you able to achieve it? I am facing the same problem with a calendar that has scrollbar

Facing the same problem, any luck?

**Comment by itajackass** [comment]
hi, the code works great. but i've a request. My calendar has horizontal scroll when my view is set to timelineWeek... is it possible to create a pdf ( a multi pdf in this case) for calendar than overflow the page?
