### ISSUE TITLE
 create custom view year

### ISSUE THREAD

**Issue by arshaw** [fullcalendar/fullcalendar#2380]
Originally reported on Google Code with ID 2115

```
Dear;

how can create custom view to show all month in 12 box only
From January  to December  just name of month in box and in top show year

thanks

```

Reported by `khalid@wireless-marketer.com` on 2014-03-13 06:31:45

**Comment by gowsikk** [comment]
how can create custom view to show all month in 12 box only
From January  to December  just name of month in box and in top show year .this is what i  exactly want
