### ISSUE TITLE
Reorganize Events / Sources with ids to be more flexible

### ISSUE THREAD

**Issue by arshaw** [fullcalendar/fullcalendar#2384]
Originally reported on Google Code with ID 2119
```
I would like to suggest a slight extension of existing event and eventsource classes,
to be more flexible. What about putting an id to the eventsource and connecting the
both entities with a hasmany relationship. Example:

{
  events:[
    {
      id:1,
      title:'Event1',
      start:'2011-04-04',
      source:1
    },
    {
      id:2,
      title:'Event2',
      start:'2011-05-05',
      source:2,

    },
    {
      id:3,
      title:'Event3',
      start:'2011-05-05',
      source:1,
    }
  ],
  eventsources:[
    {
      id:1,
      name:'First Source',
      url:'http://mysource.com/?source=1',
      color:'#000',
      className:'eventsource1'
    },
    {
      id:2,
      name:'Seconds Source',
      url:'http://mysource.com/?source=2',
      color:'#FFF',
      className:'eventsource2'
    }
  ]
}

Benefits:
- The existing structure follows the jsonapi.org standards
- Applications based on relational databases would be easier to implement

```

Reported by `andreas.schroden` on 2014-03-19 08:07:02

Imported with **1** stars.

**Comment by jdhorner** [comment]
I landed here while searching the docs and codebase for a solution to a similar problem, that _might_ be solved by this? I have three `eventSource` objects for one calendar, as you can see here: 
```
myEventSources = {
  activity: {
    url: "/Activities/Edit/GetEvents",
    type: "GET",
    data: {
      id: 943292
    },
    traditional: true,
    color: "#46aaf8"
  },
  staff202: {
    url: "/StoreAdmin/Resources/GetEvents",
    type: "GET",
    data: {
      id: 202
    },
    traditional: true,
    color: "green"
  },
  staff102: {
    url: "/StoreAdmin/Resources/GetEvents",
    type: "GET",
    data: {
      id: 102
    },
    traditional: true,
    color: "green"
  }
};
```
However, `$('.cal').fullCalendar(removeEventSource, myEventSources.staff102)` also removes "staff202"... Is it because they have the same URL?? Is there no internal type of index kept?

**Comment by jdhorner** [comment]
Yeah, it appears that even if two different evenSource entries have the same URL, they are erroneously matched as equal: 
```
function getSourcePrimitive(source) {
    return (
        (typeof source === 'object') ? // a normalized event source?
            (source.origArray || source.googleCalendarId || source.url || source.events) : // get the primitive
            null
    ) ||
    source; // the given argument *is* the primitive
}
```

**Comment by caseyjhol** [comment]
Allowing event sources to have IDs would be worth it, even if just for the ability to remove an event source by its ID, but technically all we would need is a rewrite of the removeEventSource function to allow for filters (similar to removeEvents).

**Comment by arshaw** [comment]
@jdhorner, i made a separate issue for the bug you describe
https://github.com/fullcalendar/fullcalendar/issues/3209
&uarr;
Could you please visit the link, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates?

@caseyjhol let's isolate discussion about event source IDs to https://github.com/fullcalendar/fullcalendar/issues/2433

the original proposal on this ticket: defeats the point of event sources. event sources are supposed to be a way to define how events get delivered to the client. if events are all jumbled in the same array, can't be delivered independently. they're not some sort of general-purpose grouping.

For general-purpose grouping util, see #1147
