### ISSUE TITLE
dragScroll with outside draggables

### ISSUE THREAD

**Issue by juanmaia** [fullcalendar/fullcalendar#242]
Hey guys, not sure if it's a bug or expected behavior, but when I'm dragging one event that is in the calendar already, the scroll works just fine (as expected here: "Whether to automatically move scroll containers during event drag-and-drop or while selecting." - dragScroll).

But when I'm dragging an event from outside into the calendar, then the scroll doesnt work.

Thanks!

**Comment by owenmecham** [comment]
Adding this feature would be extremely helpful for me as well. Currently, you have to drop an external event on the calendar first, before you can drag it to the calendar boundary to activate the scroll.

**Comment by arshaw** [comment]
Are you guys using jquery-ui for dragging the external element?

**Comment by owenmecham** [comment]
Sorry for the late reply @arshaw, we are using jquery-ui

**Comment by Gingol** [comment]
Hi,
are there any news about this issue?
Best regards

--
Mauro

**Comment by ryantehbaker** [comment]
I am also in need of this feature. Any news or workarounds would be wonderful!

**Comment by arshaw** [comment]
This issue has been addressed in the latest alpha release (4.0.0-alpha.2)
[See the blog post &raquo;](https://fullcalendar.io/blog/2018/10/release-v4-alpha2)

this works well now the built-in draggables api:
https://fullcalendar.io/docs/v4/external-dragging

**Comment by arshaw** [comment]
I'm closing this issue to signify that it's implemented (since v4-alpha2). I'll comment on this thread again when v4 is officially released.

**Comment by arshaw** [comment]
[V4 was officially released a few days ago!](https://fullcalendar.io/blog/2019/03/v4-officially-released)
