### ISSUE TITLE
Increment version on npmjs.org

### ISSUE THREAD

**Issue by timwis** [fullcalendar/fullcalendar#243]
`npm install fullcalendar` still installs v2.3.1. I got around this by using `npm install arshaw/fullcalendar`

![screen shot 2015-07-20 at 06 13 09](https://cloud.githubusercontent.com/assets/761444/8773938/7a85a116-2ea6-11e5-90bf-864816706040.png)

**Comment by arshaw** [comment]
npm has been updated with all the newest versions and the project will be better about keeping it updated in the future

**Comment by timwis** [comment]
Thanks @arshaw!
