### ISSUE TITLE
eventSourceDataTransform to preprocess event data (such as JSON)

### ISSUE THREAD

**Issue by arshaw** [fullcalendar/fullcalendar#2431]
Originally reported on Google Code with ID 2166

```
Similare to eventDataTransform:
http://arshaw.com/fullcalendar/docs/event_data/eventDataTransform/

...but given the root object (be it an array of events, or some higher-level object),
and will return an array of events for fullcalendar to use.

Will be a robust solution for solving problems such as Issue 1733
```

Reported by `adamrshaw` on 2014-06-05 21:38:30

Imported with **4** stars.

**Comment by eljefedelrodeodeljefe** [comment]
This seems to be stale. Do you require help with it? I see this as very useful, since it's a doubful API style to return JSON arrays.

**Comment by kristiansp** [comment]
I would love to see this added

**Comment by arshaw** [comment]
This issue has been addressed in the latest alpha release (4.0.0-alpha.2)
[See the blog post &raquo;](https://fullcalendar.io/blog/2018/10/release-v4-alpha2)

https://fullcalendar.io/docs/v4/eventSourceSuccess

**Comment by arshaw** [comment]
I'm closing this issue to signify that it's implemented (since v4-alpha2). I'll comment on this thread again when v4 is officially released.

**Comment by arshaw** [comment]
[V4 was officially released a few days ago!](https://fullcalendar.io/blog/2019/03/v4-officially-released)
