### ISSUE TITLE
Google Calendar Integration Issue

### ISSUE THREAD

**Issue by oninross** [fullcalendar/fullcalendar#245]
I followed your instructions as per documentation.  However I'm receiving an error.

`Uncaught ReferenceError: moment is not defined`

![image](https://cloud.githubusercontent.com/assets/2233813/8798742/263ec5ba-2fd7-11e5-991a-6a95747e736a.png)

**Comment by espen** [comment]
You probably haven't included moment.js then. See http://fullcalendar.io/docs/usage/

Also please see http://fullcalendar.io/wiki/Support/ and close this issue. Thanks.
