### ISSUE TITLE
When weekNumberCalculation is ISO, default firstDay to 1

### ISSUE THREAD

**Issue by arshaw** [fullcalendar/fullcalendar#2458]
Originally reported on Google Code with ID 2193

```
Correct ISO Calculation: http://jsfiddle.net/x68507/4DvUD/
Wrong ISO Calculation: http://jsfiddle.net/x68507/KmdBF/

When dealing with ISO week calculations (weekNumberCalculation:'ISO') and having a
week start of Sunday (firstDay:0), the week number calculation is off by 1 week.  Technically,
the ISO standard is for a week starting on Monday.  December 28, 2015 should be WEEK
53 and it is correct when "firstDay:1" but is incorrect when "firstDay:0".
```

Reported by `michael.r.humphreys` on 2014-06-26 17:19:13

Imported with **1** stars.

**Comment by peternowee** [comment]
I don't think this is really a bug. You choose ISO 8601 for week number *calculation*, which as you said defines Monday as the first day of the week. However, you then choose to *display* your weeks in rows with columns Sunday through Saturday. As a result, each row will cover two partial ISO weeks and no week number can ever be correct for all days in that row. While you are expecting the week number to be that of the Monday (the second day from the left in your example), others may be expecting the week number to be that of the closest day column (Sunday in your example). This becomes more obvious if you set firstDay to Thursday, for example.

Anyway, I am working on an option to display the week number in the top left of a day cell, and for this use case it would be best if that would be the top left of the first day of the week according to the week number calculation method. In this case, that would be the top left of Monday, even if the displayed week starts on Sunday. See fullcalendar/fullcalendar#2941.

**Comment by arshaw** [comment]
thanks for the explanation of this @peternowee

**Comment by arshaw** [comment]
reviving this issue because i see it has some duplicates, indicating demand i didn't realize
#2168 #2328

**Comment by arshaw** [comment]
i feel the most straight forward solution here is to detect if `weekNumberCalculation` is set to `'ISO'` and if so, default `firstDay` to `1` if it hasn't been explicitly specified.

**Comment by arshaw** [comment]
forgot to close this issue. implemented in https://github.com/fullcalendar/fullcalendar/pull/3255
