### ISSUE TITLE
jspdf landscape

### ISSUE THREAD

**Issue by nitin0708** [fullcalendar/fullcalendar#246]
Hi

Can we increase the height of landscape page without change in width.

I tried -
 var doc = new jsPDF('l', 'mm', [297, h]);

here width is also change according to height.
http://jsfiddle.net/xzZ7n/2751/

Thanks

Nitin

**Comment by espen** [comment]
Looks like you are in the wrong repo. This is Fullcalendar, not jsPDF. Please close this issue.

**Comment by arshaw** [comment]
wrong issue tracker
