### ISSUE TITLE
scheduler "eventResourceField" not working

### ISSUE THREAD

**Issue by bluffrockstar** [fullcalendar/fullcalendar#250]
Hi there.
This option doesn't appear to be working. The event still renders in week and month view, but not rendering on a timeline view with relevant resource.

I have used the 'simple. html' demo available to test. 
The only amendment made was including the eventResourceField option set to 'userid'.
I added the userid key in each event object of the simple demo with the original resourceId as the value. I also removed the resourceId key value form the event object.
Please see below image

![image](https://cloud.githubusercontent.com/assets/13571809/8984016/fcaf081e-36ce-11e5-9ed3-696dae8ca941.png)

Script versions used as per the demo files
FullCalendar v2.3.2
jQuery v2.1.4
jQuery UI - v1.11.4
moment.js v2.10.3
Scheduler v1.0.0-beta

**Comment by arshaw** [comment]
this is most likely fixed in v1.0.0. though i will briefly investigate when i tackle https://github.com/fullcalendar/fullcalendar-scheduler/issues/18
