### ISSUE TITLE
Using moment.format() when appending start and end parameters does not work well when a language is set

### ISSUE THREAD

**Issue by arshaw** [fullcalendar/fullcalendar#2516]
Originally reported on Google Code with ID 2251
```
I am experiencing this with 2.1.0 beta 3. I _fetchEventSource, lines 1646 and 1467,
there are calls to format on a moment object with no parameters. This causes moment
to return the localized string for the date when a language is set. The format call
should be hardcoded with YYYY-MM-DD.
```

Reported by `chitoiup` on 2014-08-22 02:28:00

Imported with **1** stars.

**Comment by bbalet** [comment]
Hi,

I'm adding Persian language to my OSS project (https://github.com/bbalet/jorani) and I'm facing exactly the same bug. Any update? Is it an unexpected behaviour from momentjs ?
Where can I apply the suggested patch that forces the date formatting ? What is the source file ?
Or can I implement a hook in the JS that loads Fullcalendar ?

FYI these are the parameters sent by Fullcalendar:
start:۲۰۱۵-۱۱-۲۸
end:۲۰۱۶-۰۱-۰۹
_:1450358966815

**Comment by arshaw** [comment]
hi @bbalet this is unexpected behavior from moment-js. the [format()](http://momentjs.com/docs/#/displaying/format/) method should always return an ISO8601 date string. not sure what it's not.

if this bug is still in existence, could someone please alert the momentjs team? Post a recreation JSFiddle to them?
https://github.com/moment/moment/issues
