### ISSUE TITLE
Incomplete bottom border in Firefox

### ISSUE THREAD

**Issue by tsaiid** [fullcalendar/fullcalendar#252]
I use FullCalendar 2.3.2. I found that if I enable jquery UI theme without setting `eventLimit: true` in init FullCalendar, the bottom border will disappear in Firefox. This does not occur in Chrome or Safari. 

Here is a [demo jsFiddle](https://jsfiddle.net/tsaiid/8gss88c9/2/).

**Comment by mdxs** [comment]
I can confirm that the old JSFiddle of @tsaiid (using FC 2.3.2) still shows the issue in FF 46.0.1

When I tried to reproduce with FC 2.7.1 (and also updating all other dependencies) in my JSFiddle: https://jsfiddle.net/wijgerden/9x8yf6uv/ it doesn't show the bottom border issue anymore (in FF). So from that point of view this issue could be considered closed.

There is however still a difference between FF and Chrome/IE with this example (see  https://jsfiddle.net/wijgerden/9x8yf6uv/ fiddle): in FF, even if the height fits correctly, it shows a right hand side scroll bar; which is not seen in Chrome or IE when height fits. You may need to drag the panes to make the FullCalendar pane show the whole month (fitting the whole calendar in view).

**Comment by arshaw** [comment]
i believe this was a problem with jqui theming, which is no longer supported, so closing...
