### ISSUE TITLE
Performance decrease in 2.x

### ISSUE THREAD

**Issue by arshaw** [fullcalendar/fullcalendar#2524]
Originally reported on Google Code with ID 2259

```
The following jsFiddles use the same code, only switching from 2.0.0 to 2.1.0 versions
of FullCalendar.  On a Core i7 FireFox the 2.0.0 versions loads 1500 events in under
a second, the 2.1.0 version takes 3 - 4 seconds.  Also the removeEventSource is extremely
slow.


2.0.0 - http://jsfiddle.net/indexic/u6youn1b/
2.1.0 - http://jsfiddle.net/indexic/L9z2Lbur/
```

Reported by `google@indexic.net` on 2014-08-27 20:55:20

Imported with **14** stars.

**Comment by xxAtrain223** [comment]
I'm sure you already know this, but i've done some digging and at least one of the issues is with displayEvents, specifically how it [clears and renders events](https://github.com/fullcalendar/fullcalendar/blob/master/src/common/View.js#L614-L615). This is the brute force approach, and breaks down when there are about 50 events, causing about half a second delay per update event. With one update, it's not that bad, but with several updates...

Again, i'm sure you already know all of this.

Funny thing, this made me write more efficient, optimized code.

**Comment by arshaw** [comment]
hi @xxAtrain223, using `debounce` is the leading proposed solution to this:
https://github.com/fullcalendar/fullcalendar/issues/2938 (not yet implemented)
&uarr;
Could you please visit the link, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates?

essentially throttling rerenders. you'll likely want to implement this logic on your app's end in the meantime. (sounds like you might have already)

**Comment by rwwagner90** [comment]
@arshaw could you tell us how to implement the debouncing? I see in the issue that it's supposed to go in reportEvents I think, but that doesn't seem to be a function, do I define that on my side?

**Comment by Manuweb2** [comment]
Hi @arshaw,

Thanks for the amazing job on fullcalendar.
We also noticed that using more than 600 events on a week calendar (yes we have clients with buzy weeks...) it took the calendar about 4s second to display the elements.
We are using a single source with an ajax call for the source using event: url and the ajax return a json.
The ajax call is returned in about 200ms, then we can count to 4s until the elements appear on the calendar... we were using the 2.0.0beta until now and we thought updating to 3 would change that but it has no effect and still 4s until the elements appear. 
Just discovered this post and tryed the debounce method but no effect on performance.
When less that 100 elements it appears in less thant 100ms which is great.
We are using chrome and safari in our tests.
Are you thinking working on performance on the next 3.0.1 releases ?

Thanks for the update, and congrats for the good work.
Manu

**Comment by Manuweb2** [comment]
Just for you to know, i've installed the chrome new version (55 dev) and the event rendering is much better.
A calendar with 1000 events tooks about 6s to appear. It take now less that 2s
The release date of chrome 55 is 6 of december
Best,
Manu

**Comment by jamesdixon** [comment]
Any update on this? Events are still painfully slow to render in addition to switching views. Note that I'm using v.3.x and rendering approximately 200 events. 

I've also implemented caching, so events are being reloaded on view changes, but again, very slow (1-2s)

**Comment by arshaw** [comment]
there have been some new developments on this initiative.

`eventRenderWait` has been released in [v3.1.0](https://github.com/fullcalendar/fullcalendar/releases/tag/v3.1.0)
https://fullcalendar.io/docs/event_rendering/eventRenderWait/
(aka "debounce")

if you do not want to opt into eventRenderWait, you can use the following new methods:
- https://fullcalendar.io/docs/event_rendering/renderEvents/
- https://fullcalendar.io/docs/event_data/updateEvents/

**Comment by arshaw** [comment]
yes @Manuweb2, I totally understand. That approach will be very necessary if/when [Continuous scrolling of months](#2276) is implemented.

**Comment by arshaw** [comment]
@Manuweb2 the following issue requests fetching-while-scrolling:
https://github.com/fullcalendar/fullcalendar/issues/3087
&uarr;
Could you please visit the link, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates?

**Comment by Sujay-shetty** [comment]
@arshaw 
I'm using fullcalendar in my application. it is really a nice library build for calendar view.

But I have an issue in terms of performance, where in month view I have around 500 events per day and which are going to repeat every week. It is taking too long time to render those events and some time it freezes the screen as well.

Could you please help me how the performance can be improved in this scenario.

Thanks,
Sujay

**Comment by eabhijith** [comment]
Hi, 

We are currently facing the same issue, Any quick fix available that some is aware of?

BR,
Abhijith

**Comment by arshaw** [comment]
I just retested this. Various version of FullCalendar tested on FF 68.0.1 (64-bit, MacOS):

1.6.4: http://jsfiddle.net/yqj4rsnL/1/
  Run 1: Milliseconds to setup: 298  Remove source: 13  Add source: 173
  Run 2: Milliseconds to setup: 323  Remove source: 14  Add source: 184
2.1.0: http://jsfiddle.net/indexic/L9z2Lbur/
  Run 1: Milliseconds to setup: 687  Remove source: 612  Add source: 1108
  Run 2: Milliseconds to setup: 682  Remove source: 610  Add source: 1109
4.2.0: http://jsfiddle.net/0auk6ecv/5/
  Run 1: Milliseconds to setup: 491  Remove source: 116  Add source: 335
  Run 2: Milliseconds to setup: 456  Remove source: 109  Add source: 349

The problems we had in v2 are no longer an issue in v4, so closing this issue. We'll be continually working on performance improvements of course.
