### ISSUE TITLE
easily add an event (via renderEvent) to a specific event source

### ISSUE THREAD

**Issue by arshaw** [fullcalendar/fullcalendar#2537]
Originally reported on Google Code with ID 2272
```
Hi everyone !
First I would like to thank all of you for this amazing plugin !
I am facing the following issue :
I would like to dynamically add an event to a source, and I am wondering if it is even
possible.

Let us take the following example :
http://jsfiddle.net/88562sxa/
I have a source : v with one event inside.
I also have an event ev. Its source references v.
When I add the event source to the calendar, everything is fine.
However, when I want to render the ev event, it does not appear on the calendar. The
source v -even when referenced in source attribute of ev- does not change at all.
Is it normal ?
Is there an other way to dynamically add an event to a source ?

Thanks in advance !
Regards,
Julien Orain





```

Reported by `julien.orain` on 2014-09-01 22:32:47

Imported with **1** stars.

**Comment by JobaDiniz** [comment]
It would be *really* nice to accept no an *event object*, but any obj and then use the **eventDataTransform** function.

```
var source = {
                id: agenda.id,
                events: function (start, end, timezone, callback) {
                    Appointment.all(agenda.id, start, end)
                        .then(function (appointments) {
                            callback(appointments);
                        })
                        .catch(function (error) {
                            callback([]);
                        });
                },
                eventDataTransform: eventDataTransform,
                backgroundColor: agenda.backgroundColor,
                textColor: agenda.textColor,
                borderColor: agenda.borderColor
            };
```

Now, I want to add an *appointment*. It would call *eventDataTransform* and everything would work.

**Comment by arshaw** [comment]
@JobaDiniz if you already have a handle to your `eventDataTransform` function, why not run your raw event data through it before passing it to `renderEvents`? Would achieve the same thing but without having to run it through FullCalendar's API.

**Comment by raghav-khunger** [comment]
Hi Arshaw,

Any estimated date when this feature will be implemented in core?

I want to add events to eventsource dynamically i.e after the calendar is rendered and event sources are already set.

Removing event source and re-adding it just to add one new event to event source doesn't look good and practical.
