### ISSUE TITLE
no flicker on refretchEvents

### ISSUE THREAD

**Issue by arshaw** [fullcalendar/fullcalendar#2558]
Originally reported on Google Code with ID 2293
```
Currently we have available only the refetchEvents, which destroys all the events and
then trigger the ajax that catches all events and renders them all again.

This is not the best way to implement an auto update, because the events are "flickering".

The ideal would be to have an option that only UPDATE events. In other words, performs
the Ajax and, according to the result, renders a new event that did not exist, update
an event already rendered or removes an event that no longer exists.
```

Reported by `thiago@thiagomt.com` on 2014-09-23 21:20:57

Imported with **4** stars.

**Comment by neeonline** [comment]
Any news on that?

In my point of view the API should have a updateEvents methods, calls refetch first, than destroy and render.

**Comment by cndreiter** [comment]
+1

**Comment by caseyjhol** [comment]
@arshaw I've developed a fix for this issue that only adds a few lines of code. Rather than instantly destroying the events when refetchEvents is called and then rendering the events again, it waits to destroy the original events until the new events are rendered (after the events are rendered, there is a trigger to destroy the originals). It seems to be just as fast as the original refetchEvents, except without the flicker. If you'd like, I can submit a pull request.

**Comment by arshaw** [comment]
@caseyjhol if it's not too much work, can you create a PR so others can see?

**Comment by caseyjhol** [comment]
@arshaw Sure thing - I'll see if I can get one ready today.

**Comment by caseyjhol** [comment]
@arshaw PR submitted.

**Comment by arshaw** [comment]
thanks @caseyjhol. no promises on when i can get it reviewed/integrated give current priorities, but others who are hoping for a solution the meantime will be thankful for this

**Comment by caseyjhol** [comment]
@arshaw I implemented the fix discussed by diogoalexfranco and helge.sverre, and submitted PR #3123. This PR supersedes #3094, and only removes 1 line of code.

**Comment by skipperbent** [comment]
+1 for this! We're using FullCalendar for a small setup were node.js or Ratchet would be overkill.

@caseyjhol PR #3123 works great; hacked the bower install with your fix, thanks! Hope they'll approve the PR soon.

**Comment by RinkAttendant6** [comment]
@arshaw Any plans on merging in PR #3123 for the next release? We're using npm and it is not feasible to hack the file in `node_modules` with the fix.

**Comment by RinkAttendant6** [comment]
@arshaw Any plans on merging in PR #3123 for the next release? We're using npm and it is not feasible to hack the file in `node_modules` with the fix.

**Comment by arshaw** [comment]
[Code complete](https://github.com/fullcalendar/fullcalendar/commits/v2.8.0-dev) and [docs written](https://github.com/fullcalendar/fullcalendar/commits/docs-2.0) but not yet released. Will update this thread when released.

**Comment by arshaw** [comment]
Released in [v2.8.0](https://github.com/fullcalendar/fullcalendar/releases/tag/v2.8.0). Thank you @caseyjhol !

**Comment by rapito** [comment]
@arshaw Can I request this issue to be reopened, it seems like it's present on 5.8.0+
```
	function refetchEvents() { // can be called as an API method
		destroyEvents(); // so that events are cleared before user starts waiting for AJAX
		fetchAndRenderEvents();
	}
```
Flickering is back and it just looks really bad, the workaround using fullcalendar/react is uglier since it's harder to override default behavior.

**Comment by sseemmiin** [comment]
same as me

**Comment by patrickcash1** [comment]
Was this ever fixed? We really need it not to flicker. I would gladly pay for this.

**Comment by AdityaPainuli** [comment]
@arshaw I am working with full calendar + google API for getting events and using refetchevent() function when performed some particular action on the calendar itself. but look like the flickering is happening on that . can you please help me out .
