### ISSUE TITLE
Missing one day at event end

### ISSUE THREAD

**Issue by arshaw** [fullcalendar/fullcalendar#2587]
Originally reported on Google Code with ID 2322

```
here is example http://jsfiddle.net/nfgttg14/1/

it renders from 2 Oct to 4 Oct, should end on 5 Oct.
```

Reported by `sl.bug.sl` on 2014-10-19 13:36:30

**Comment by Nekle** [comment]
Hi,
if I have an event from 2016-03-12 12:00:00 to 2016-03-15 05:00:00. it is missing end date.

http://jsbin.com/joluticasu/edit?html,output

![snip20160323_1](https://cloud.githubusercontent.com/assets/1272353/13974501/80cd39e4-f0ac-11e5-8e30-9889a6be6f2a.png)

**Comment by arshaw** [comment]
please see the discussion on https://github.com/fullcalendar/fullcalendar/issues/2985 as to why this is happening

**Comment by kavyajanardhan** [comment]
In CS FILE:
//HolidayList is class with attributes ID, description,start and end

                SqlDataReader reader = SqlHelper.ExecuteReader(ConnStr, CommandType.StoredProcedure, "NameOfStoredProcedure");
                if (reader.HasRows)
                {
                    Holiday_List itemObj = null;
                    DateTime start, end;
                    while (reader.Read())
                    {
                        itemObj = new Holiday_List();
                        itemObj.holiday_Id = Convert.ToInt16(reader["holidayID"]);
                        itemObj.description = reader["description1"].ToString();
                        if (reader["date1"] != DBNull.Value)
                        {
                            start = Convert.ToDateTime(reader["date1"]);//read from db
                            start = start.AddDays(1);
                            end = start.AddDays(1);
                            itemObj.startdate= start.ToShortDateString();
                            itemObj.enddate = end.ToShortDateString();
                        }
                        result.Add(itemObj);
                    }
                }
                return result;

IN CSHTML:

        $.ajax({
            type: "POST",
            url: '@Url.Action("ActionMethodName", "Controller")',
            contentType: false,
            processData: false,
            success: function (result) {
                
                if (result != null) {
                    $.each(result, function (index, optiondata) {
                        alert(optiondata.date1 + '   ' + optiondata.enddate)
                        holidayList.push({
                            "title": optiondata.description,
                            "start": optiondata.startdate,
                            "end": optiondata.enddate,
                        });
                    });
                    if (holidayList.length > 0) {
                        $('#calendar').fullCalendar({
                            header: {
                                left: 'prev,next today',
                                center: 'title',
                                right: 'month,basicWeek'
                            },
                            navLinks: true, // can click day/week names to navigate views
                            editable: true,
                            eventLimit: true, // allow "more" link when too many events                            
                            events: holidayList,
                            displayEventTime: false
                        });
                    }
                }
            }
        });
