### ISSUE TITLE
more day-specific classNames on header cells

### ISSUE THREAD

**Issue by arshaw** [fullcalendar/fullcalendar#2589]
Originally reported on Google Code with ID 2324

```
For more styling options I'd like to set DayClasses to headCellHTML so I can style the
head according to what kind of day the head belongs to.

Please seehttps://github.com/arshaw/fullcalendar/pull/186

```

Reported by `jens.fahnenbruck` on 2014-10-20 05:56:43

Imported with **1** stars.

**Comment by arshaw** [comment]
the reason i'm not crazy about this idea and the implementation in #186 is that these classes contain values like `'fc-today fc-past fc-future` which indicate facts about specific days. the header area *above* the days that contain the week names is not linked to specific days.

**Comment by jigfox** [comment]
Sorry to here that, what would be your suggesting to get a highlighting like this for the current day:
<img width="643" alt="cal" src="https://cloud.githubusercontent.com/assets/110414/15887494/dfe214ca-2d62-11e6-9d56-2ba4bdbbb48a.png">

**Comment by arshaw** [comment]
my concern was mainly when there are multiple rows of days, like in **month** view.

but i understand this change would be step forward for when there's only one row of days, like in basicWeek/agendaWeek, or any of the custom views with one row.

adjusting the ticket title to reflect an reopening

**Comment by arshaw** [comment]
in v5, the day headers have all sort of classnames, including about day of week. please inspect the DOM to learn more
