### ISSUE TITLE
Event popup position problem when calendar height is fixed

### ISSUE THREAD

**Issue by wilzo** [fullcalendar/fullcalendar#259]
http://jsbin.com/suyekahure/edit?html,js,output
1. set height:400,eventLimit: true 
2. put calendar in middle of page, 
3. click more event
4. the popup display in wrong position

**Comment by arshaw** [comment]
i could only get the "more" link to appear in FF (which is another problem, possibly related to #252), but even when it did appear, in every scenario, it seems to be in the correct place.

<img width="412" alt="screen shot 2015-10-10 at 11 46 34 pm" src="https://cloud.githubusercontent.com/assets/56520/10414576/2e08a4d4-6fa9-11e5-9134-858a2335f3c8.png">

**Comment by arshaw** [comment]
maybe it was fixed with a recent update. if not, could you post a screenshot to aid in debugging? will keep it closed until then
