### ISSUE TITLE
dayClick doesn't work when using fastclick (github.com/ftlabs/fastclick)

### ISSUE THREAD

**Issue by invalidusernam3** [fullcalendar/fullcalendar#260]
The dayClick event in the fullCalendar configuration stops working when using fastclick (github.com/ftlabs/fastclick) on iOS safari. The next/previous month clicks work fine, but the dayClick event stops working

**Comment by mlumbroso** [comment]
+1 was able to reproduce too.

**Comment by mlumbroso** [comment]
For the record, was having the same problem with a datepicker, here is the solution they came with : https://github.com/dbushell/Pikaday/issues/101

Any chance this is similar? I will try to look in the source and tell if that is the case.

**Comment by mlumbroso** [comment]
So a quick look told me this is definitely the same issue : 
Here is the pull request : #2839

**Comment by arshaw** [comment]
i am nearly certain this is fixed since v2.7.0 introduced official touch support. can someone verify? i will repoen this ticket if issues still exist
