### ISSUE TITLE
How to change the axis in full calendar? I mean I want to invert the x axis to y axis and y to x axis.

### ISSUE THREAD

**Issue by arshaw** [fullcalendar/fullcalendar#2631]
Originally reported on Google Code with ID 2366

```
# You must follow these instructions when entering an issue:
#
#    http://fullcalendar.io/wiki/Reporting-Bugs/
#    http://fullcalendar.io/wiki/Requesting-Features/
#
# Issues that do not follow these guidelines will be deleted without
# explanation.
#
# Please erase this text and start typing :)
How to change the axis in full calendar? I mean I want to invert the x axis to y axis.
days should come to y axis and time should go to x axis in week view? I am not able
to do it, even the fullcalendar.min JS plugin is not readable format. kindly help.
```

Reported by `anujit17` on 2014-11-20 09:37:22

**Comment by ApekshaKatariya** [comment]
> Originally reported on Google Code with ID 2366
> 
> ```
> # You must follow these instructions when entering an issue:
> #
> #    http://fullcalendar.io/wiki/Reporting-Bugs/
> #    http://fullcalendar.io/wiki/Requesting-Features/
> #
> # Issues that do not follow these guidelines will be deleted without
> # explanation.
> #
> # Please erase this text and start typing :)
> How to change the axis in full calendar? I mean I want to invert the x axis to y axis.
> days should come to y axis and time should go to x axis in week view? I am not able
> to do it, even the fullcalendar.min JS plugin is not readable format. kindly help.
> ```
> 
> Reported by `anujit17` on 2014-11-20 09:37:22

can you please share the link
