### ISSUE TITLE
How to change the axis in full calendar? I mean I want to invert the x axis to y axis and y to x axis.

### ISSUE THREAD

**Issue by arshaw** [fullcalendar/fullcalendar#2632]
Originally reported on Google Code with ID 2367

```

How to change the axis in full calendar? I mean I want to invert the x axis to y axis.
days should come to y axis and time should go to x axis in week view? I am not able
to do it, even the fullcalendar.min JS plugin is not readable format. kindly help.
```

Reported by `anujit17` on 2014-11-20 09:38:46

**Comment by smadatha** [comment]
Hi,

**Comment by smadatha** [comment]
How to modifying view on fullcalendar to have days on y axis and times on x axis in the style of agendaWeek view.
I want to change the fullcalendar view look like bellow screenshot

![image](https://user-images.githubusercontent.com/38938025/39565798-49846182-4eb1-11e8-9cdf-998727fdb9bc.png)

Please help me out.
Thanks

**Comment by yukepeter** [comment]
I have the same question! Anyone up to an solution?

**Comment by ayatif** [comment]
I also need solution to it can anyone help on it?

**Comment by gd-euss** [comment]
+1 need this view for task scheduler

**Comment by ApekshaKatariya** [comment]
I also have the same question. Please help me
Thank you
