### ISSUE TITLE
Basic day view

### ISSUE THREAD

**Issue by linuslagerhjelm** [fullcalendar/fullcalendar#264]
There seems to be no default option to prevent the calendar from switching into the basic day view on resize when we're dealing with small and x-small devices. This would be appreciated since the basic day view makes big changes to the callendar that might not be wanted.

**Comment by arshaw** [comment]
i do not know of this behavior you speak of: behavior that forces the calendar into basicDay view when the device is small. could you elaborate on how to create this scenario? maybe it is a bug. screenshots would be very helpful. thanks!

**Comment by arshaw** [comment]
duplicate of #2845. someone else is having this problem apparently. plz resume discussion over there
