### ISSUE TITLE
Passing data to background event object

### ISSUE THREAD

**Issue by drugoi** [fullcalendar/fullcalendar#266]
Hi all,
Is there a way to get a data that I passed to eventObj when user clicks on background event?
My sample background event looks like this:
```javascript
{
      id: 'availableForMeeting',
      title: 'Test Background Event #1',
      start: '2015-08-13T07:30:00',
      end: '2015-08-13T12:30:00',
      rendering: 'background',
      sampleId: 214,
      color: 'red'
}
```

But I can't get **sampleId** field, 'cause it doesn't exist in jsEvent.

**Comment by espen** [comment]
Please see http://fullcalendar.io/wiki/Support/
