### ISSUE TITLE
allDay on last version does it works?

### ISSUE THREAD

**Issue by Surt** [fullcalendar/fullcalendar#267]
I can't find a way to set an allDay event, it always takes the start and end dates with time. (on agenda view). I'm looking for the event to fill all the day, not from start to end.
I found an example here http://jsfiddle.net/slicedtoad/886pmtxs/1/
the lonely event is set for all day, why is showing only for a period of time?

**Comment by espen** [comment]
1) Check the docs: http://fullcalendar.io/docs/event_data/Event_Object/ "If either the start or end value has a "T" as part of the ISO8601 date string, allDay will become false."

2) See working example: http://jsfiddle.net/kLh2m7ao/

3) Read http://fullcalendar.io/wiki/Support/ and close this issue.
