### ISSUE TITLE
All-day background events over time slots

### ISSUE THREAD

**Issue by arshaw** [fullcalendar/fullcalendar#2691]
Originally reported on Google Code with ID 2426

```
Is there any way to make allDay background events cover the whole day in agendaWeek
and agendaDay views instead of just the all day section at the top of the page?

Here is the current functionality, I'd hope for the event to extend down the whole
column for the day instead.

http://jsfiddle.net/hc2g7p0t/
```

Reported by `smiffy0sm` on 2015-01-18 20:37:32

Imported with **1** stars.

**Comment by arshaw** [comment]
as of v5 (or maybe even v4), this happens by default: https://codepen.io/arshaw/pen/VwebBNG?editable=true&editors=001

**Comment by alltonp** [comment]
Is this configurable in any way? 

I'd really like the the opposite behaviour... I only want the event appearing in the all day section?
