### ISSUE TITLE
IE8 monthView broken

### ISSUE THREAD

**Issue by arshaw** [fullcalendar/fullcalendar#2693]
Originally reported on Google Code with ID 2428

```
Hello

Fullcalendar (v2+), monthView seems to be broken on IE8 even on a minimal install from
your demonstration pages.

See this fiddle for reproduction : http://jsfiddle.net/pn6u3oa7/embedded/result/

And a rendering capture attached here.

Maybe I am missing something ?

Thanks
```

Reported by `bixibu` on 2015-01-23 10:57:19

<hr>
- _Attachment: ie8-month-bug.png<br>![ie8-month-bug.png](https://storage.googleapis.com/google-code-attachments/fullcalendar/issue-2428/comment-0/ie8-month-bug.png)_

**Comment by Y6717** [comment]
I download your source code, but in the calendar presentation, the monthly calendar still can not show normally, I read the submission code notes, said that has been fixed, please ask in addition to downloading the source code, also need other operations?
