### ISSUE TITLE
Option to set calendar height to height of parent element

### ISSUE THREAD

**Issue by arshaw** [fullcalendar/fullcalendar#2704]
Originally reported on Google Code with ID 2439

```
It would be helpful if there was an option to have the calendar fill the height of the
containing div. This is useful if you would like a full screen calendar without scrolling
or if the calendar overflows the div then the div will scroll.

Here is my implementation:

https://github.com/arshaw/fullcalendar/pull/206

Here is another implementation that is implemented in almost the same way:

https://github.com/arshaw/fullcalendar/pull/215
```

Reported by `mmarcucio` on 2015-02-10 16:05:07

Imported with **1** stars.

**Comment by arshaw** [comment]
a PR from @aharpervc addressing this issue: https://github.com/fullcalendar/fullcalendar/pull/3040

**Comment by arshaw** [comment]
err, @aharpervc's above issue doesn't actually address this issue. The most elegant API for this issue is to specify `height:'parent'` as opposed to providing a function

**Comment by aharpervc** [comment]
`height: parent` is a special case implementation of #3040

**Comment by arshaw** [comment]
this is now possible in v5. you can set height to `'100%'`. it accepts any css value
