### ISSUE TITLE
Method to force fresh rerendering of view

### ISSUE THREAD

**Issue by arshaw** [fullcalendar/fullcalendar#2709]
Originally reported on Google Code with ID 2444

```
There doesn't seem to be a way to ensure that the dayRender is re-run on all days. I've
asked a StackOverflow question <http://stackoverflow.com/questions/28401749/redrawing-a-fullcalendar-so-that-the-dayrender-callback-is-called>
that highlights how `render` doesn't always do this. The workaround of recreating the
entire calendar produces visual issues.

This is useful in my case where I am trying to change the appearance of days on the
fly (applying arbitrary CSS and HTML changes to day cells). I need to be able to refresh
the table (and thus calling `dayRender` again) when the source I'm watching changes
(which is the same source that `dayRender` uses to determine how to render each day).
```

Reported by `mike@updex.ca` on 2015-02-17 18:48:18

Imported with **3** stars.

**Comment by davidthornton** [comment]
Okay, weird tip but -- if you were waiting on this in order to re-render the background, don't! I didn't catch the background events method in the docs until now -- which work perfectly for this use-case.

Just remember that on Safari (and probably other browsers) you set your table width to x where x + 1 === 0 mod d where d is the number of days you're rendering! (It has to be a multiple of the number of days or else background events will render with a slight gap. This isn't a bug, it's a bug in math/geometry!)

**Comment by shenlong** [comment]
so, what is the best way to rerender the color code? Destroy and recreate?

**Comment by shenlong** [comment]
Meantime, I found that I can refresh if I can the previous and next view.

    $('#calendar').fullCalendar('prev');
    $('#calendar').fullCalendar('next');

Do take note on performance issue if you have events in the calendar.

**Comment by arshaw** [comment]
there's a [rerenderEvents](http://fullcalendar.io/docs/event_rendering/rerenderEvents/) method

**Comment by shenlong** [comment]
@arshaw I am using changing the cells color using dayRender
rerenderEvents method is not working. Is that the right method?

**Comment by arshaw** [comment]
i misread your comment and mistakenly closed this ticket. apparently the `render` method will not re-render the cells unfortunately, which is what you would want. im now understanding that's the point of this bug request tickets.

In the meantime, your best bet is to destroy/render the calendar yourself.

**Comment by antoinebrault** [comment]
+1 I'm trying to make a "zoom" feature for timeline view and I need to refresh the table/cells for that. (basically dynamic slotWidth)

**Comment by antoinebrault** [comment]
found it... 

Still hacky but it works..

.fullCalendar('getView').timeGrid.slotWidth += 7;
.fullCalendar('getView').updateWidth();

**Comment by shenlong** [comment]
@arshaw Hi, destroying and rerender the view seems quite bad for the calendar. I just wanna color code the days of the viewed month.

Any better ways?

**Comment by dckkk** [comment]
@arshaw Hi, why i always get "uncaught TypeError: Cannot read property 'hasTime' of undefined". Im using ReactJS. Can you help me?

**Comment by SimonNegrin** [comment]
Hi, i found a solution but it is necessary to modify a little the source. Find the "Calendar_constructor" in the source file and in the exports section ad the line:

`t.reinitView = reinitView;`

After that you can do:

`$("#calendar").fullCalendar("reinitView");`

**Comment by drugoi** [comment]
Is any updates on this feature?

**Comment by devarashetty** [comment]
I am facing the same issue , would like to know if any work advancement has been made on this.Thanks

**Comment by Reskov** [comment]
Another workaround is 
```js
  let view = container.fullCalendar('getView');
  view.unrenderDates();
  view.renderDates();
```

**Comment by rossjcooper** [comment]
Thank you @Reskov that worked brilliantly.

**Comment by trquoccuong** [comment]
@rossjcooper You can call rerenderEvents. It works great.
```
let view = container.fullCalendar('getView');
view.unrenderDates();
view.renderDates();
container.fullCalendar('rerenderEvents');
```

**Comment by stepanzarubin** [comment]
why not just call?

`
fullCalendar('rerenderEvents');
`

looks like it works.

**Comment by jrz** [comment]
For the month-view, this seems to do the trick: 
myCalendar.fullCalendar('getView').dayGrid.renderGrid();
Unfortunately, it will still re-render the complete grid, which causes blinking

**Comment by arshaw** [comment]
This issue has been somewhat addressed in the latest alpha release (4.0.0-alpha.2)
[See the blog post &raquo;](https://fullcalendar.io/blog/2018/10/release-v4-alpha2)

The render method will rerender the whole calendar conveniently
https://fullcalendar.io/docs/v4/render

But still no way to rerender JUST the dates

**Comment by arshaw** [comment]
I'm closing this issue to signify that it's implemented (since v4-alpha2). I'll comment on this thread again when v4 is officially released.

**Comment by arshaw** [comment]
[V4 was officially released a few days ago!](https://fullcalendar.io/blog/2019/03/v4-officially-released)

**Comment by magicmb** [comment]
We are still on fullcalendar v3 and some time away from looking at v4 upgrade path. Is this issue resolved in v4 only?

**Comment by M1ing** [comment]
In what way Refresh the calendar after the eventClick event is triggered,

**Comment by Herz3h** [comment]
Any way to rerender the events in v3 rerenderEvents doesn't work...............

**Comment by thargenediad** [comment]
I have a similar problem but with the `dayCellClassNames` hook.  It doesn't fire when the events change.  It only fires when the entire calendar redraws.
