### ISSUE TITLE
Change the language after initialization

### ISSUE THREAD

**Issue by danny-toi** [fullcalendar/fullcalendar#271]
Is it possible to change the language after initializing the fullcalendar? I want to localize the fullcalendar depending on the user selection of language drop-down.

Looking at the demo (http://fullcalendar.io/js/fullcalendar-2.4.0/demos/languages.html), the fullcalendar is destroyed before changing to another language, which is not what I need.

**Comment by arshaw** [comment]
will be solved by the umbrella issue #564
