### ISSUE TITLE
height: 'auto' in month view is squished

### ISSUE THREAD

**Issue by arshaw** [fullcalendar/fullcalendar#2714]
Originally reported on Google Code with ID 2449

```
Migrated from 2.2.2 to 2.3.0 and noticed that the month view is vertically squished
when using the height: auto option.  Removing this option fixes the view.  Easy to
recreate in JSBin - just add the option and watch it change.

```

Reported by `afurman@twolikeyou.com` on 2015-02-23 18:59:31

Imported with **1** stars.

**Comment by kaljak** [comment]
This issue can be reproduced here: https://jsfiddle.net/kaljak/9fxxc5ed/3/

As far as I can see this code is the problem:
`	// Overrides the default BasicView behavior to have special multi-week auto-height logic
	setGridHeight: function(height, isAuto) {

		isAuto = isAuto || this.opt('weekMode') === 'variable'; // LEGACY: weekMode is deprecated

		// if auto, make the height of each row the height that it would be if there were 6 weeks
		if (isAuto) {
			height *= this.rowCnt / 6;
		}

		distributeHeight(this.dayGrid.rowEls, height, !isAuto); // if auto, don't compensate for height-hogging rows
	},`

--> `this.rowCnt` is not set and so height becomes NaN

**Comment by chrisjmccrum** [comment]
any workaround for this at the moment?

**Comment by arshaw** [comment]
i believe the bug only revealed itself when `eventLimit: true`, but I'd have to check. setting it to `false` might help

**Comment by arshaw** [comment]
condensing the height of the month-view rows when the height is 'auto' is actually intended behavior. the CSS of the divs within each cell are what's preventing the height from completely collapsing. if you want to increase the height, write custom CSS properties to make this height larger
