### ISSUE TITLE
eventLimit: auto, calculates row height before eventRender

### ISSUE THREAD

**Issue by arshaw** [fullcalendar/fullcalendar#2717]
Originally reported on Google Code with ID 2452
```
Hi,

I have noticed that when eventLimit is set to auto, calendar will calculate number
of visible events before eventRender callback.

This is a problem if you change the height of event in the eventRender callback. After
rendering visible events will overlap the "+n more" link.

Am i missing something or is this a bug?

Thank you,
Svetozar Belic.
```

Reported by `d7trx@yahoo.com` on 2015-03-01 12:01:14

Imported with **1** stars.

**Comment by jamesdixon** [comment]
@arshaw I'm having the same issue. Essentially, I'm doing filtering in the `eventRender` callback. I have a number of checkboxes used as filters and when those filters are checked, the `rerenderEvents` method is called, which triggers `eventRender`. The filtering works -- events show and display as they should, but on days where there were a lot of events and `eventLimit` is set, if a filter is applied that removes elements from a day where there is `more` link, the link stays even though the events are removed from the calendar. I tried to reproduce this with a JSBin, but cannot seem to do so. Here's my `eventRender` method for reference:

```javascript
eventRender(event, element, view) {

          const isFiltering = this.get('isFiltering'),
                staffFilter = this.get('staffFilter') ? this.get('staffFilter').id : undefined,
                customerFilter = this.get('customerFilter') ? this.get('customerFilter').get('id') : undefined;

          // if recurring, add recurring icon
          if (event.recurrencePattern) {
            element.find('div').prepend("<i class=\"fa fa-repeat\"></i> ");
          }

          // add lightning icon if auto_approved
          if (event.requestStatus === 'auto_approved') {
            element.find('div').prepend("<i class=\"fa fa-bolt\"></i> ");
          }

          // if filtering is enabled, determine whether or not to
          // exlcude an event based on criteria
          if (isFiltering) {

            const filters = [

              // filters by staff member
              [event.resourceId, staffFilter],

              // filters by customer
              [event.customerId, customerFilter],

              // shows only recurring appointments
              [event.recurrencePattern != null, this.get('recurringFilter')],

              // shows only non-recurring (one-off) appointments
              [!event.recurrencePattern, this.get('oneOffFilter')],

              // shows only auto approved appointments
              [event.requestStatus == 'auto_approved', this.get('autoApprovedFilter')]
            ];

            // if any of the above filters are true, remove the event
            const filter = _.filter(filters, (x) => {
              return x[1] && x[0] != x[1];
            });

            if (filter.length > 0) {
              element.remove();
            }

            // apply any status filters
            const statusFilters = this.get('appliedStatusFilters');

            if (statusFilters.length > 0) {
              if (!statusFilters.isAny('status', event.apptStatus)) {
                element.remove();
              }
            }
          }
        }
```

Note that I'm using `element.remove()` as `return false` was causing errors when using this in Ember. 

Is `eventRender` definitely called before the code that calculates the more link?

Thanks!

**Comment by jamesdixon** [comment]
Here's a demo of the behavior I'm seeing: http://quick.as/wxr0H3oQl

**Comment by arshaw** [comment]
thanks @jamesdixon . This would be infinitely easier for me if there was a runnable reproduction. Could you please create a [Reduced Test Case](http://fullcalendar.io/wiki/Reduced-Test-Cases/)? This will save a great deal of time, and is very appreciated.

**Comment by arshaw** [comment]
actually, one sec, lemme wrap my head around this more...

**Comment by arshaw** [comment]
@jamesdixon i bet the bug you are describing is a bit different than the one originally. anyway, a runnable example (made as minimally as possible w/ as much of your app-specific code removed) would be very helpful in diagnosing the root problem.

**Comment by arshaw** [comment]
will reopen when there's a reduced test case
