### ISSUE TITLE
Only allow events on certain ranges via a callback (eventAllow)

### ISSUE THREAD

**Issue by arshaw** [fullcalendar/fullcalendar#2740]
Originally reported on Google Code with ID 2475
```
Currently, eventConstraint and selectConstraint can only be set with

    an event ID, "businessHours", object

as per the [http://fullcalendar.io/docs/event_ui/eventConstraint/ Docs].

It would be nice to be able to specify a function in the same way many other options
work.

Example usage might look like

    {{{
    eventConstraint: function(start,end,fcevent){
        if( start.isBefore(moment()) ){ // if the start is in the past
            return false;
        }else{
            return true;
        }
    }
    }}}
```

Reported by `dmacdonald@bibliofiche.com` on 2015-03-30 13:59:00

Imported with **2** stars.

**Comment by tjphippen** [comment]
I'd like the ability to set constraints to match a background event(which can currently do) however I am not able to change those constraints if the event were moved to a different resource. The end result would constrain an event to 09:00-17:00 on Resource1 & 11:00-15:00 on Resource2. I believe this feature would enable me to accomplish it.
![screen shot 2015-11-27 at 2 54 16 pm](https://cloud.githubusercontent.com/assets/8011699/11449196/4095b4fa-9521-11e5-9e57-f74e5a9fa15f.png)
*attachment shows what should not be possible

**Comment by ejacevedo** [comment]
Hi. tjphippen


Example:
//select allowable range
 selectConstraint:{
          start: '02:00', // a start time  
          end: '23:59', // an end time 
        }, 
//select allowable range
        eventConstraint:{
          start: '02:00', // a start time 
          end: '24:00', // an end time 
        },

**Comment by akivajgordon** [comment]
After inspection of the code, it looks like it _is_ possible to pass `eventConstraint` and `selectConstraint` a function. In fact, it works exactly the same as the `idOrFilter` argument that you would pass to the [`clientEvents`](http://fullcalendar.io/docs/event_data/clientEvents/) method.

Maybe this feature was put in but intentionally undocumented?

**Comment by ejacevedo** [comment]
clientEvents
displays all existing events

idOrFilter, it is to filter by id ...

**Comment by arshaw** [comment]
@akivajgordon, if you pass in a function for `eventConstraint` or `selectConstraint`, it seems that it will constrain your dragged event to the event windows created by existing events within that constraint window.
https://github.com/fullcalendar/fullcalendar/blob/master/src/EventManager.js#L1021

Somewhat obscure behavior that most likely nobody will want. Would have been cool though!

**Comment by arshaw** [comment]
I'm proposing this be a new setting called `eventAllow` that is a callback function that gets executed for every possible time window an event is dragged over:

```
eventAllow: function(event, start, end, resource) {
    return true; // or false
}
```

`true` will allow a drop, `false` will not.

I'm choosing to name this differently from `eventConstraint`, even though it does similar things, because it is easier to comprehend.

**Comment by arshaw** [comment]
`eventAllow` should be attachable to event sources, but probably not event objects

**Comment by arshaw** [comment]
should consider [eventResourceEditable](https://github.com/fullcalendar/fullcalendar-scheduler/issues/140) first, and short-circuit if can't change resource

**Comment by arshaw** [comment]
implemented in v3: https://fullcalendar.io/blog/2016/09/feature-packed-releases/

[eventAllow](https://fullcalendar.io/docs/event_ui/eventAllow/)

**Comment by ariadnimac** [comment]
For anyone looking to implement this, it works perfectly as follows with `eventAllow`:

```
eventAllow: function(dropInfo, draggedEvent) {
	const start = dropInfo.start;
	const end = dropInfo.end;

	const startDay = start.getDate();
	const endDay = end.getDate();

	return startDay == endDay;
},
```
