### ISSUE TITLE
Support an optional title on background events

### ISSUE THREAD

**Issue by arshaw** [fullcalendar/fullcalendar#2746]
Originally reported on Google Code with ID 2481

```
It appears that if your 'rendering' is 'background' or 'inverse-background', the title
does not display. It seems like this is by design right now, but it'd be really useful
to optionally support this.

I feel that the rendering style and whether or not the text displays on the event are
mutually exclusive. In my use case, which I feel is quite common, I need to block off
time slots, and also make it very explicit to a user that these are "Unavailable",
or moreso, why they are unavailable.
```

Reported by `ipalka` on 2015-04-11 17:44:34

Imported with **1** stars.

**Comment by flack** [comment]
An alternative solution would be to just render the background event's title as the `title` attribute on the cells like this:

![bgtitle](https://cloud.githubusercontent.com/assets/425166/12901011/73da0efc-ceb9-11e5-8476-f49ae12873f1.png)

**Comment by lorinkoz** [comment]
This would be a nice feature.

**Comment by trollepierre** [comment]
up?

**Comment by mad134** [comment]
I know this is old, but with 4.3.1, you can use eventRender:

```
eventRender : function(info) {

       const props = info.event.extendedProps,
          rendering = info.event.rendering;

       if(rendering == "background") {
		$(info.el).text(info.event.title);
     }
}
```
This assumes your events have `{ rendering : "background" }` defined within.

**Comment by bhavin32** [comment]
StacyMader Thank you very much i solved this issue 12hr but i don't set this

**Comment by arshaw** [comment]
this actually happens by default in v5. [see a demo](https://codepen.io/arshaw/pen/OJyyNzP?editable=true&editors=001%3Dhttps%3A%2F%2Ffullcalendar.io%2Fdocs%2Fv5%2Fbackground-events-demo)

[please read the latest blog post about the v5 beta](https://fullcalendar.io/blog/2020/04/new-ui-features-beta)

**Comment by arshaw** [comment]
[released in v5](https://fullcalendar.io/blog/2020/06/v5-official)

**Comment by reservemycourt** [comment]
Can you please expand on how this happens "by default" in V5?  I have installed V5, have events that are set as background and have a title property set but that does not display.  Should I be setting a different property?  Thanks.

**Comment by arshaw** [comment]
@reservemycourt , please see the "All Day Event" in this demo: https://codepen.io/arshaw/pen/zYrEWaY?editable=true&editors=001
