### ISSUE TITLE
setting to retain end date/time when DnD from allDay to timed

### ISSUE THREAD

**Issue by arshaw** [fullcalendar/fullcalendar#2764]
Originally reported on Google Code with ID 2499

```
I found that in agendaWeek view. An all-day event spanning more than one day is shortened
duration to one day long when it was drag and drop to timed event.
May it be good if there is an option to support this case?
You can view an example from my attachment.

Thanks you! :)
```

Reported by `pawarit.s@codium.co` on 2015-05-06 04:49:41

<hr>
- _Attachment: Pasted_Image_5_6_15__11_38.png<br>![Pasted_Image_5_6_15__11_38.png](https://storage.googleapis.com/google-code-attachments/fullcalendar/issue-2499/comment-0/Pasted_Image_5_6_15__11_38.png)_

Imported with **1** stars.

**Comment by arshaw** [comment]
i understand the need for this. should remain off by default

**Comment by pateldipak** [comment]
hello arshaw am suffering form one problem i have created one event without start time and end time now i am moving on the week view at there i have drag my event and drop it on some time slots at that time i am getting event.end null so thats i am not able to update that event in database please assist me on this issue
 
my event drop function is as following
  eventDrop: function (event, delta, minuteDelta, allDay, revertFunc)
        {                     
                var newEndDate = new moment(event.end).subtract(1, "days");

                var objEventUpdate = {
                    EVENT_ID: event.EVENT_ID,
                    START_DATE: event.start,
                    END_DATE: newEndDate
                };

                $.ajax({
                    async: false,
                    url: updateEventByIdUrl,
                    type: "POST",
                    dataType: "json",
                    data: JSON.stringify(objEventUpdate),
                    contentType: "application/json; charset=utf-8",
                    success: function (data)
                    {
                    },
                   
                });
}

**Comment by arshaw** [comment]
@pateldipak please post your question on StackOverflow. More info:
https://fullcalendar.io/support/

It will be really useful if you post a [Reduced Test Case](https://fullcalendar.io/wiki/Reduced-Test-Cases/) when you post on StackOverflow.

**Comment by arshaw** [comment]
This issue has been addressed in the latest alpha release (4.0.0-alpha.2)
[See the blog post &raquo;](https://fullcalendar.io/blog/2018/10/release-v4-alpha2)

https://fullcalendar.io/docs/v4/allDayMaintainDuration

**Comment by arshaw** [comment]
I'm closing this issue to signify that it's implemented (since v4-alpha2). I'll comment on this thread again when v4 is officially released.

**Comment by arshaw** [comment]
[V4 was officially released a few days ago!](https://fullcalendar.io/blog/2019/03/v4-officially-released)
