### ISSUE TITLE
Improve CDN example on downloads page

### ISSUE THREAD

**Issue by arshaw** [fullcalendar/fullcalendar#2773]
Originally reported on Google Code with ID 2508

```
from Andrew:

On the download page for fullcalendar.js, you list an option for using a CDN. Since
cloudflare also hosts moment.js (https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.10.2/moment.min.js),
I would recommend adding a script tag for it as well so that people copying those tags
will end up with something that works.
```

Reported by `adamrshaw` on 2015-05-22 05:12:05

Imported with **0** stars.

**Comment by dakala** [comment]
@arshaw Looks like there's no longer a section for installing/initializing older FC versions. Do we want to do this for at least v3?

**Comment by arshaw** [comment]
no need to modify v3. no action required here.

@dakala my github notifications were a bit messed up, so I didn't receive comments you made on issues like this. please ping me again on issues where you haven't gotten a response from me.
