### ISSUE TITLE
agendaDay does not respect scrollTime when contentHeight is 'auto'

### ISSUE THREAD

**Issue by arshaw** [fullcalendar/fullcalendar#2774]
Originally reported on Google Code with ID 2509
```
I expected the agendaDay view to be scrolled to the appropriate time. However, this
is not the case when contentHeight is 'auto'.

I did not see anything in the documentation saying you cannot use these two features
together.

JSFiddle: http://jsfiddle.net/patmalt/1eLah65p/
```

Reported by `patmalt` on 2015-05-22 15:57:12

Imported with **2** stars.

**Comment by auroras** [comment]
I thought exactly the same - how I found this issue.

I can understand why you'd only want to scoll within the calendar container, however, I have my calendar within a Bootstrap `.container` with a fixed navigation bar on the top of the screen (`.navbar-fixed-top`).

Maybe we could have an option to scroll callendar container or the `document` and default to the calendar container?


Regards,

Rich

**Comment by auroras** [comment]
for those who want an immediate solution I have a work-around (merged from a few stackoverflow comments):


```
var myCalendar = {
	defaultView: 'agendaDay',
	contentHeight: 'auto'
};

// add your events here
myCalendar.events = [..];

// if events are not sorted then add this line
myCalendar.events.sort(function (a, b) { return new Date(a.start) - new Date(b.start) });

// append a CSS classname to the first event
myCalendar.events[0].className += ' cal-scrollTime';

// after all events have finished rendering scroll to the first event
myCalendar.eventAfterAllRender = function (view) {
	$('html, body').animate({
		scrollTop: $('.cal-scrollTime').offset().top
	}, {
		duration: 0
	});
};

// invoke calendar
$('#calendar').fullCalendar(myCalendar);
```


Regards,

Rich

**Comment by arshaw** [comment]
thanks for the workaround @auroras 

this is a duplicate of another ticket. will concern itself with an official fix for this:
#2761
&uarr;
Could you please visit the link, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates?
