### ISSUE TITLE
Skip custom holidays

### ISSUE THREAD

**Issue by arshaw** [fullcalendar/fullcalendar#2777]
Originally reported on Google Code with ID 2512
```
During implementation of fullcalendar I found that there is no way we can skip custom
holidays in fullcalendar. 

For example- We have an event which starts on 1 June 2015 and ends on 31 Oct 2015.
No I want to define 15th June as holiday , there is no way I can define holidays in
event object as is accepts only start date and end date. 

Please implement this feature.


```

Reported by `abvaibhav` on 2015-06-02 10:42:37

Imported with **1** stars.

**Comment by dfoxxdfoxx** [comment]
I would also like the option to add an json feed with holidays.
It is than not possible to click, move or drag/drop on these days.
I think it is best to show the days but with a different color so it is clear that they are blocked.

**Comment by arshaw** [comment]
most of what u want can be achieved with:
http://fullcalendar.io/docs/event_rendering/Background_Events/
in tandem with
http://fullcalendar.io/docs/event_ui/eventOverlap/ set as `false`

conveniently ignoring *clicks* is harder. #2722 will make this easier.

if enough people demand this, and aren't able to achieve this through the previously mentioned more granular options, i'll open this back up for discussion.

**Comment by ArunEzhikode** [comment]
Hey @arshaw ,
```I tried this, but its still displaying events. 
 events: function (fetchInfo, successCallback, failureCallback) {
          successCallback(events);
        },
  eventOverlap:false,
```
Do get back regarding the same

**Comment by riteshthakur** [comment]
I also want the Holiday list to Skip from Fullcalendar.
Whether it can be US holiday or a custom list of array provided.
