### ISSUE TITLE
Timezone is lost when the event is changed programmatically

### ISSUE THREAD

**Issue by arshaw** [fullcalendar/fullcalendar#2780]
Originally reported on Google Code with ID 2515

```
http://jsbin.com/quzame/3/edit?html,js,console,output

When I edit the date (event.start = '2015-06-12T09:30:00-05:00') and update the event
($('#calendar').fullCalendar('updateEvent', event)), the new rendered event loses the
timezone ('2015-06-12T09:30:00+00:00')
```

Reported by `ronny.cuadrado` on 2015-06-08 18:10:36

Imported with **1** stars.

**Comment by Jaicob** [comment]
+1

**Comment by arshaw** [comment]
@Jaicob would you mind posting a [JSBin](http://fullcalendar.io/wiki/Reporting-Bugs/)? I'm having trouble understand if/how this relates to the currently set `timezone`

**Comment by Jaicob** [comment]
The code is definitely working as documented, but I saw these as related because when timezone is set to false or via a timezone string, the docs feel a little contradictory since they state both

> The timezone offset that was originally in the string will be preserved / Once the dates are parsed, they will have a forced zone:

and 
> when an event is modified, whether through user dragging/resizing or updateEvent, the dates will
> become ambiguously-zoned.

It would be convenient if the offset was preserved even after updates.

[Here's](http://jsbin.com/wubunadefa/edit?js,console,output) a JSBin but its more or less the same as the original one posted in this thread

**Comment by arshaw** [comment]
keeping the given timezone when an updateEvent happens might be a good idea, because at that point we are putting trust in the developer who is reassigning the start/end dates to have the correct timezone offset, but for dragging/resizing, I am still in favor of stripping it, as is will be impossible to compute the timezone offset of an arbitrary time in an arbitrary timezone in JavaScript, and I'd rather have no timezone than a wrong one.

PS- the original example posted on this thread definitely *should* have a timezone because it is made explicit in the ISO8601 string

**Comment by arshaw** [comment]
I'm planning for v4 and made a proposal for overhauling the date system. Can you all take a look? Please make relevant comments on this thread.

[Wiki: Date System Revamp](https://github.com/fullcalendar/fullcalendar/wiki/Date-System-Revamp-Proposal)

**Comment by arshaw** [comment]
This issue has been addressed in the latest alpha release (4.0.0-alpha.2)
[See the blog post &raquo;](https://fullcalendar.io/blog/2018/10/release-v4-alpha2)

**Comment by arshaw** [comment]
I'm closing this issue to signify that it's implemented (since v4-alpha2). I'll comment on this thread again when v4 is officially released.

**Comment by arshaw** [comment]
[V4 was officially released a few days ago!](https://fullcalendar.io/blog/2019/03/v4-officially-released)

**Comment by andrew-svirin** [comment]
I have found that if update Event with end date is shifted to TimeZone, then dateInterval does not change.
