### ISSUE TITLE
method to refetch resources

### ISSUE THREAD

**Issue by arshaw** [fullcalendar/fullcalendar#2788]
Originally reported on Google Code with ID 2523
```
Hi,

i'm just playing around with the new Scheduler. 

int the actual beta version (1.0.0), the resources will only be loaded on the first
init of the calendar. 
i think there should be a feature to refetch/update the resources. this could be done
manually or when clicking on the header-buttons 'next', 'last', ...

in my app, the resources will change on every month.




```

Reported by `philippk123` on 2015-06-17 19:46:03

**Comment by arshaw** [comment]
this has been implemented in the v1 official release of Scheduler
http://fullcalendar.io/docs/resource_data/refetchResources/

thanks!

**Comment by r1chl** [comment]
Is it possible to invoke this in a way that won't cause a second redraw?  I have different resources per day, so when the user clicks the next or previous day buttons we redraw then I invoke refetchResources and it redraws again with the correct resources.  On busy days this can be quite slow and causes a lot of flickering.  Thanks for the great library by the way - my purchase order for a dev license is working its way through approval.

**Comment by arshaw** [comment]
@r1chl , ahhh i understand. could you follow this issue instead (on the fullcalendar-scheduler project):
https://github.com/fullcalendar/fullcalendar-scheduler/issues/12

it is exactly what you are requesting. thanks

**Comment by r1chl** [comment]
Thanks @arshaw.  I will follow that issue.  I also have other requirements where I keep the same date but need to refresh both the events and resources at the same time (due to a change in an external filter value), so some kind of refetchEventsAndResources method would be very handy as well as being able to configure a refetch of resources on change of date range.

**Comment by arshaw** [comment]
@r1chl got it. would you mind making an issue on the [Scheduler Issue Tracker](https://github.com/fullcalendar/fullcalendar-scheduler/issues) about refetchEventsAndResources?
