### ISSUE TITLE
Full Calender - Events duplicate after ajax call.

### ISSUE THREAD

**Issue by arshaw** [fullcalendar/fullcalendar#2791]
Originally reported on Google Code with ID 2526

```
I am using a json event source for my calendar. Each time after ajax call when navigating
among weeks or days or months events binding multiple times.
i am using below code in ajax

 var events = {
            url: "/Appointment/BookAppointment/",
            type: 'POST',
            data: {
                room: roomid, doctor: doctorid, Appdate: appDate, AppEndDate: appEndDateTime,
ID: 0, WalkIn: walkin
            }
        }
        // $('#calendar').fullCalendar('removeEventSource', events);
        $('#calendar').fullCalendar('removeEvents');
        $('#calendar').fullCalendar('addEventSource', events);

Please help me.
I am using fullcalender2.0.2.

Thank You,
Ram.

```

Reported by `ramug10` on 2015-06-20 09:42:53

<hr>
- _Attachment: calender.PNG<br>![calender.PNG](https://storage.googleapis.com/google-code-attachments/fullcalendar/issue-2526/comment-0/calender.PNG)_

**Comment by jaghnikiran** [comment]
Hi,  Is this issue fixed? even i am facing same issue. This issue occurs when user navigates from Day view to Week view.issue occurs only when user navigates immediately from Day view to Week view.  we are using full calendar version 2.3.1. 

Thanks
Kiran J
