### ISSUE TITLE
allow event elements to be focused. if not, causes bootstrap popover malfunction

### ISSUE THREAD

**Issue by arshaw** [fullcalendar/fullcalendar#2804]
Originally reported on Google Code with ID 2539

```
event not getting focused on clicking it because of that the bootstrap popover is not
working

https://github.com/twbs/bootstrap/issues/16749

actual functionality -- on click of event bootstrap popover should open and clicking
anywhere outside the popover should close

https://jsfiddle.net/kd7e2xpc/5/

but the event is not getting closed raised a bug in bootstrap they closed saying that
the div is not getting focused
```

Reported by `aditya.tagirisa@healthgraph.in` on 2015-07-02 12:44:22

Imported with **1** stars.

**Comment by arshaw** [comment]
I've modified your JSBin to get a little closer to the mark:
https://jsfiddle.net/kd7e2xpc/23/

In it, I used `eventRender` instead of `eventClick` to avoid any event-lifecycle race conditions.

Still not working because fullcalendar fc-event elements seem unfocusable with the mouse. You can focus them with the *keyboard* as an experiment. Click somewhere on the page, they hit tab, and you'll see the desired behavior.

The reason FC is swallowing the mouse focus is here:
https://github.com/fullcalendar/fullcalendar/blob/master/src/common/Grid.events.js#L182
-> https://github.com/fullcalendar/fullcalendar/blob/master/src/common/DragListener.js#L57

**Comment by arshaw** [comment]
nearly the same issue as: https://github.com/fullcalendar/fullcalendar/issues/2053

**Comment by theit8514** [comment]
I can reproduce this in version 4, but I found a workaround for the use case of popover.

https://jsfiddle.net/47fz5r9n/3/

Attach an event handler to the document to check to see if the popover needs to close, then add a click handler for the event element.

**Comment by arshaw** [comment]
@theit8514 thank you for posting a workaround.

I've created a new ticket that supersedes this one:
https://github.com/fullcalendar/fullcalendar/issues/3364
&uarr;
Could you please visit the link, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates?
