### ISSUE TITLE
option to set a day break time for TimeGrid

### ISSUE THREAD

**Issue by arshaw** [fullcalendar/fullcalendar#2806]
Originally reported on Google Code with ID 2541

```
Setting the new option dayBreak to for example "07:00" or "7:00 AM" will make the day
columns in TimeGrid views start at 7 am in the morning and extend past midnight, ending
7 am the following day. This can be useful for TV-listings or concert/club event scheduling
were it's common to have "days" ending past midnight.

This is accomplished with two small code changes.

1) Make sure we actually use the seg column date as the startOfDayDate property in
computeSegVerticals() instead of the seg event start date. [2 changed lines in TimeGrid.events.js]

2) Add a dayBreak option which overrides the minTime and maxTime values to make the
columns render past midnight. [3 added lines and 2 changed lines in TimeGrid.js]

(We can of course manually set minTime to "07:00" and maxTime to "31:00" if we don't
want to add the dayBreak option, but I think this will be clearer for fullcalendar
users)

Example;

$('#calendar').fullCalendar({
   header: {
      left: 'prev,next today',
      center: 'title',
      right: 'month,agendaWeek,agendaDay'
   },
   defaultView: 'agendaWeek',
   dayBreakTime: "07:00",
   ...
});
```

Reported by `matiasnu` on 2015-07-06 13:31:18

Imported with **1** stars.

**Comment by arshaw** [comment]
reminder to self: this feature seems to be about shifting the perceived start/end of a day. so hours would be removed from the start of the day and added on to the end of the day, all in the same column. not 100% sure of the usability of this, so moving back to "discussing"

**Comment by skurvish** [comment]
I have a client interested in this feature. Where are you with it please? Thanks.

**Comment by arshaw** [comment]
This feature will essentially be a shortcut for minTime/maxTime. For example, if day break is `08:00`, then that would imply `{ minTime: '08:00', maxTime: '32:00' }`.

There are two bug tickets stopping the effective use of minTime/maxTime:
https://github.com/fullcalendar/fullcalendar/issues/3055
https://github.com/fullcalendar/fullcalendar/issues/2530
&uarr;
Could you please visit the links, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates?

Will accept this issue to make the `dayBreakTime` shortcut after those two are implemented.

**Comment by panfanky** [comment]
Using { minTime: '08:00', maxTime: '32:00' } now works! Thanks!

**Comment by arshaw** [comment]
yup, seems fixed!
