### ISSUE TITLE
firing event-click for bg events

### ISSUE THREAD

**Issue by arshaw** [fullcalendar/fullcalendar#2808]
Originally reported on Google Code with ID 2543

```
In some cases it's useful to detect clicks on background events (not currently supported).

The small fix is divided into two parts;

1) Make sure we connect the seg to the fillSeg by fc-seg data in renderFillSegEls()
in Grid.js, just like we do for ordinary event segs. [1 line added]

2) Detect click events on .fc-bgevent-container elements and trigger bgEventClick in
a new bindBgSegHandlers method. [1 line + 1 method added]

We could extend the bindSegHandlers method to support bg events too, but the new method
felt cleaner since we don't want to resize the background events.

Example;

$('#calendar').fullCalendar({
   header: {
      left: 'prev,next today',
      center: 'title',
      right: 'month,agendaWeek,agendaDay'
   },
   defaultView: 'agendaWeek',
   bgEventClick: function(calEvent, jsEvent, view) {
      alert(calEvent.title);    
   },
   ...
});
```

Reported by `matiasnu` on 2015-07-07 11:12:47

Imported with **1** stars.

**Comment by benbarnett** [comment]
Would be great to get this in at some point, our project could really benefit from it too

**Comment by MartijnWelker** [comment]
Are there currently any intentions to implement this short-term ? Otherwise I'll make a pull request for it.

**Comment by arshaw** [comment]
@MartijnWelker it ranks relatively low, so if you want to see it materialize, a PR is probably good.

**Comment by massmediagroup-49** [comment]
@arshaw, Is it possible to implement this feature in short term? It will be very useful for simple booking/blocking system.

**Comment by arshaw** [comment]
This issue has been addressed in the latest alpha release (4.0.0-alpha.2)
[See the blog post &raquo;](https://fullcalendar.io/blog/2018/10/release-v4-alpha2)

https://fullcalendar.io/docs/v4/release-notes#event-clicking--hovering

**Comment by arshaw** [comment]
I'm closing this issue to signify that it's implemented (since v4-alpha2). I'll comment on this thread again when v4 is officially released.

**Comment by arshaw** [comment]
[V4 was officially released a few days ago!](https://fullcalendar.io/blog/2019/03/v4-officially-released)

**Comment by saimAbdullah** [comment]
I am using the v4 latest release till date but still, it is not firing for background event
