### ISSUE TITLE
how to create drop down list for select month and year

### ISSUE THREAD

**Issue by arshaw** [fullcalendar/fullcalendar#2821]
Originally reported on Google Code with ID 2556

```
How to create drop down list for select month and year in full calendar by using jquery
...
```

Reported by `santoshsp.777` on 2015-08-03 19:44:31

<hr>
- _Attachment: Untitled.png<br>![Untitled.png](https://storage.googleapis.com/google-code-attachments/fullcalendar/issue-2556/comment-0/Untitled.png)_

**Comment by sudarshan13** [comment]
Can anybody provide a working fiddle, plunker or codepen link? because full calendar is now updated to 2.7 version and the requirement of month and year in dropdown list is still not added, please somebody provide working demo for it thank you.

**Comment by bigfootcreative** [comment]
Any working demo of this yet?
