### ISSUE TITLE
Scheduler drag-n-drop: eventDrop should show previous resourceId

### ISSUE THREAD

**Issue by danielsmacdonald** [fullcalendar/fullcalendar#2830]
The eventDrop callback has these arguments: `(event, delta, revertFunc, jsEvent, ui, view)`. When used with Scheduler, `event.resourceId` represents the new location of the event. Could we have something to represent the old location (`resourceId` before the move)?

Maybe replace `delta` with `prevEvent` object? Or just add a property to `event`, something like `event.prevResourceId` or `event.prevLocation`.

Currently I'm adding the `resourceId` to the event in duplicate (one with a different name) so only one gets overridden and I can still read the old one. But this is messy and error prone.

**Comment by arshaw** [comment]
moved this feature request over here: https://github.com/fullcalendar/fullcalendar-scheduler/issues/39
