### ISSUE TITLE
Update NPM with version 2.4.0

### ISSUE THREAD

**Issue by candrews** [fullcalendar/fullcalendar#2831]
Can you please update [NPM](https://www.npmjs.com/package/fullcalendar) with version 2.4.0?

I can see you've updated [Bower](https://libraries.io/bower/fullcalendar) already :)

Thanks!

**Comment by rachellcarbone** [comment]
So our choices are, start using another dependency manager just for this plugin or don't use the full set of features available? Why not just push updates to NPM?

**Comment by espen** [comment]
Another choice is not to be so passive-aggressive.

**Comment by arshaw** [comment]
npm has been update with all the latest versions. i've put in place more reminders for me to do this with each version release and i plan on automating it in the future

**Comment by rachellcarbone** [comment]
Thank you for the update!
