### ISSUE TITLE
eventReceive problem

### ISSUE THREAD

**Issue by fatimazaheer** [fullcalendar/fullcalendar#2835]
Hi @arshaw 
I have a problem with eventReceive, when i drag an event from external source onto the calendar the eventReceive does not fire, am i missing something. Here is my code

```
eventReceive : function(event){
		console.log('finally event dropped');
		console.log(event);
},
```
Thanks in advance.

**Comment by arshaw** [comment]
could you please post a JSBin demo of what you have? http://fullcalendar.io/wiki/Reporting-Bugs/

PS- eventReceive only works with events that originated from outside the calendar, through jQuery UI draggable
