### ISSUE TITLE
Full Calendar Material Design Theme

### ISSUE THREAD

**Issue by jackyliang** [fullcalendar/fullcalendar#2836]
Hey all.

I made a Material Design-like theme for Full Calendar which I've opened sourced under my [repo](https://github.com/jackyliang/Material-Design-For-Full-Calendar)

<img src="http://i.imgur.com/TH3VsJU.gif">

What the actual Android Material Design calendar looks like:
<img src="http://dab1nmslvvntp.cloudfront.net/wp-content/uploads/2014/09/1410153384GIF2.gif">

While FullCalendar is pretty awesome, it looks pretty terrible without any styling. I was inspired by Google's Material Design, while coincidentally I needed a fitting theme for my Drexel [Schedulizer](http://loop.tf/schedulizer) service. Doing some basic research, it didn't seem like there were any Material Design calendar plugins or themes that were as flexible as FullCalendar's functionality, so I took matters to my own hands and put this together. 

Currently it only supports the `agendaWeekly` view since that was my context of use. Feel free to contribute if you desire more usages.

**Comment by StudioJunkyard** [comment]
Nice, I believe Bootstrap v4, is implementing a few Material type components as well.

**Comment by jackyliang** [comment]
@StudioJunkyard Sweet. If you can't wait, [this](http://fezvrasta.github.io/bootstrap-material-design/bootstrap-elements.html) is what I currently use for Bootstrap Material Design. I would say the results are fairly good. Angular.js itself also has Google's official Material theme which is incredibly done.

**Comment by StudioJunkyard** [comment]
+1

**Comment by dtmonterrey** [comment]
Very nice...

**Comment by tomvlk** [comment]
:+1:

**Comment by piyushchauhan2011** [comment]
:+1:

**Comment by kanpinar** [comment]
+5

**Comment by espen** [comment]
Looks great. And it's really nice to see community addons to Fullcalendar. Perhaps there should be a section in the readme with links to this and other plugins/themes @arshaw ? Would probably encourage more open source addons instead of private development like I'm sure many have done to customize Fullcalendar.

**Comment by jackyliang** [comment]
@espen Love this idea! Finding other themes for FullCalendar was very hard, if not non-existent. I think adding this theme alongside other private/public themes will spur development more!

**Comment by arshaw** [comment]
This looks reaaally nice.

You were able to achieve this [entirely through CSS](https://github.com/jackyliang/Material-Design-For-Full-Calendar/blob/master/_materialFullCalendar.scss) it looks like? Even that day-expand animation?

I'm normally afraid to officially sanctioning other fullcalendar-related projects for fear of taking on additional support load, but if it's just CSS, I'm not as worried.

Anyway, I can circle back on making any decisions here once I get further with other initiatives.

Good work!

**Comment by jackyliang** [comment]
@arshaw There's no expanding - the expanding is Android's Calendar. The first GIF is what my theme looks like :)

**Comment by arshaw** [comment]
@jackyliang as mentioned in #3566, a new theme system internals will be released soon along with Bootstrap support. You can start here: https://github.com/fullcalendar/fullcalendar/tree/master/src/theme

**Comment by arshaw** [comment]
I'm further triaging this issue...

FYI, the default theme in v4 was made more "flat".

Most of the attractiveness of this is related to the colors of the events, which I wouldn't say is part of the "theme". It is customized via the JS API.

The theme does nicely style the various lines in timeGrid view, however.

@jackyliang, if you develop your CSS further to look good in all of FullCalendar's views, I will post a link to it on your site. Or better yet, you'd post it as an NPM package.
