### ISSUE TITLE
Date range with time start and end

### ISSUE THREAD

**Issue by Surt** [fullcalendar/fullcalendar#2837]
I'm triying to show a date range bussiness hours using the ```rendering background``` but I still don't get the way to replicate the next behaviour:

http://jsfiddle.net/97dcazbq/5/

What I want is to render those events only between a date range (on the example from 2015-08-27 to 2015-08-29. Is there a way to specify a day for start and a day for end for the events to render?
Notice that could be other events with diferent date ranges, so maxDate etc does not work.

**Comment by arshaw** [comment]
`dow` is essentially a hack I introduced, but the solution you described will be encompassed by the Recurring Events feature (#387)
