### ISSUE TITLE
scrollTime not behaving like expected

### ISSUE THREAD

**Issue by xlthor** [fullcalendar/fullcalendar#2840]
Setting scrollTime to any value doesn't ave effect in current Agenda views. It always scrolls to the start of the business hours (8 am in my case).
Turning on or off business hours entirely doesn't have an effect as well.

**Comment by arshaw** [comment]
would you mind posting a JSBin recreation? would help a lot
http://fullcalendar.io/wiki/Reporting-Bugs/

will keep closed until u do
