### ISSUE TITLE
dayClick should trigger when user clicks bg events

### ISSUE THREAD

**Issue by mrbscott** [fullcalendar/fullcalendar#2843]
I found that dayRender was not being called in month view on a week where a background event was present. I am using dayRender to identify a double click. 

I have prepared a simple jsfiddle to demonstrate this issue: https://jsfiddle.net/89msdjrg/2/

If there is a simple work-around or fix, I would greatly appreciate your insight and help.

**Comment by mrbscott** [comment]
Unsure of whether the below pull request is a solution?
https://github.com/fullcalendar/fullcalendar/pull/258

**Comment by arshaw** [comment]
this is because the background event covers the day cell and intercepts the click/dblclick.

we want to keep clicking behavior consistent w/ how events work, so not sure what the best solution is here.

**Comment by arshaw** [comment]
I feel like dayClick *should* be triggered when user clicks on a background event. Because there is no available surface for the user to click, which is a UX issue.

There should be a param in `dayClick` that signals that a bg event has been clicked. Somewhat touched upon in #2722

**Comment by arshaw** [comment]
the original ticket mentions dayRender, but I believe that was an attempt to attach manual mouse handlers, which is awkward for the reasons mentioned in #2718. The goal of this ticket is to make any *built-in* mouse/touch event like, `dayClick` or others (`dayDblClick` has been proposed I think) get fired when the user clicks on a bg event.

**Comment by arshaw** [comment]
I'm closing this issue to signify that it's implemented (since v4-alpha2). I'll comment on this thread again when v4 is officially released.

**Comment by arshaw** [comment]
reopening this because I haven't actually verified this with an automated test.

note to self: write a test and document this in the V4 Release notes

**Comment by arshaw** [comment]
this is fixed. 9b999226b77d2fb77af407299531516bb835b88f

will comment on this issue again when v4 is officially released.

**Comment by arshaw** [comment]
[V4 was officially released a few days ago!](https://fullcalendar.io/blog/2019/03/v4-officially-released)

**Comment by maxwellt** [comment]
> I feel like dayClick _should_ be triggered when user clicks on a background event. Because there is no available surface for the user to click, which is a UX issue.
> 
> There should be a param in `dayClick` that signals that a bg event has been clicked. Somewhat touched upon in #2722

I can't find it in the documentation so I guess it's not implemented that way, but is there a parameter in `dateClick` that tells me a bg event has been clicked? In my use case I have a series of bg events which only occupy maybe 10% of the cell width, which means I would like to handle a click on that bg event differently from a click on any of the remaining 90% of the cell, which I wanted to do using the `eventClick` and `dateClick`, but currently both handlers are fired.
