### ISSUE TITLE
Basic day view

### ISSUE THREAD

**Issue by empouras** [fullcalendar/fullcalendar#2845]
Hi,

Is there any way to avoid a "jump" to the basic day view when resizing to very small devices for the fullCalendar?

Thanks in advance

**Comment by jdonaldson10** [comment]
You could perhaps use the [windowResize](http://fullcalendar.io/docs/display/windowResize/) callback for window resizing.  Something like this perhaps?

``` js
$('#calendar').fullCalendar({
  windowResize: function(view) {
    if($(this).outterWidth() < 768){
      $(this).fullCalendar( 'changeView', 'agendaDay')
    }
  }
});
```

Similarly you could employ this with the [viewRender](http://fullcalendar.io/docs/display/viewRender/) callback for your smaller devices and not just window resizing.

**Comment by empouras** [comment]
Hi James and thanks for the response.

If I remember well I tried that one but it leads to a "jumpy" behavior!
I will give it one more try but if i remember well it jumps to the basic day view and then changes to the agenda Day. What i need is to prevent totally the jump! :(

**Comment by arshaw** [comment]
@empouras you are saying you get this undesired 'jump' behavior by default, unintentionally? can you maybe post a JSBin ([instructions](http://fullcalendar.io/wiki/Reporting-Bugs/)) or describe how to reproduce this behavior? this behavior was never implemented so i am confused as to how it i happening. screenshots would be very helpful.

**Comment by empouras** [comment]
Hi Adam,
Thank you for your response. The difference in our application is that we want the page to be responsive and not have to scroll when we look at the calendar in xs devices. The demo that you have in your site is not made that way. It is a bit responsive at the begining but after that you just have to scroll and you don't see much of the calendar whithout scrolling in a cell phone. What we need is everything to be in the same page whithout scrolling. I attach a picture of how it looks when in normal view and how it becomes when we shrink to a xs device! Hope you can help me!
Thank you for your time. 
P.S Maybe you can reproduce it by making responsive your demo by taking away the overflow to scroll.
![full](https://cloud.githubusercontent.com/assets/14050336/10422423/79b2824e-70ba-11e5-926e-1cb7500b0da8.JPG)
![basic](https://cloud.githubusercontent.com/assets/14050336/10422424/79b6843e-70ba-11e5-857a-7dfe78116549.JPG)

**Comment by arshaw** [comment]
So, in your application, you wrote code to switch to views based on screen size, which is triggered on a window resize?

If that's the case, yes, I expect you will experience some sort of jump when you make that switch. I wouldn't consider this a bug.

At some point each calendar view will be truly responsive; no view-switch necessary. Tracking ticket:
https://github.com/fullcalendar/fullcalendar/issues/3187
&uarr;
Please visit the link, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates.
