### ISSUE TITLE
Set Scheduler nested TreeView default to collapse

### ISSUE THREAD

**Issue by projectfuturism** [fullcalendar/fullcalendar#2846]
As per the SO thread here:

http://stackoverflow.com/questions/32265394/fullcalendar-scheduler-set-to-collapse-by-default

**Comment by espen** [comment]
Should be moved to https://github.com/fullcalendar/fullcalendar-scheduler/issues

**Comment by arshaw** [comment]
moved here: https://github.com/fullcalendar/fullcalendar-scheduler/issues/40
