### ISSUE TITLE
Drop callback don't get the event but a moment object

### ISSUE THREAD

**Issue by pascoual** [fullcalendar/fullcalendar#2848]
The event param is not the event but a momentjs object:
```
drop: function(event, delta, revertFunc, jsEvent, ui, view) {
  console.log(event);
}
```

Get a MomentJS object.

**Comment by arshaw** [comment]
this is intended behavior:
http://fullcalendar.io/docs/dropping/drop/

you might be wanting the `eventDrop` callback, which is different

**Comment by arshaw** [comment]
you might be needing `eventReceive` as well
