### ISSUE TITLE
Export all View classes

### ISSUE THREAD

**Issue by KillerCodeMonkey** [fullcalendar/fullcalendar#2851]
Hey,

would it be possible to export all default view classes?
There is only the base View-Class on the $.fullCalendar-object, yet.

But i need to customize the MonthView a little bit, but thats a mess.

So i am not a fan, but i changed the fullcalendar source and exported the MonthView to overWrite some methods in my customMonthView.

Thank you and Greetz.

**Comment by arshaw** [comment]
queued up for release:
https://github.com/fullcalendar/fullcalendar/commit/468cedaccc5ff4811825c326a7a7c28f2a0a0cd8

**Comment by arshaw** [comment]
Released in [v3.6.0](https://github.com/fullcalendar/fullcalendar/releases/tag/v3.6.0)
