### ISSUE TITLE
prev and next buttonIcons not working in Microsoft Edge Browser

### ISSUE THREAD

**Issue by newq** [fullcalendar/fullcalendar#2852]
In Microsoft Edge (on Windows 10) the buttonIcons for prev / next in the fullcalendar header are not displayed. For some reasons Edge ignores the CSS for ::after content.

Also happens on fullcalendar.io. 
To test I used the modern.ie Windows 10 + Edge Image.

**Comment by KLuuKer** [comment]
i tested it and when i removed overflow: hidden; from .fc-icon the prev\next buttons are visible

**Comment by RunningDog54** [comment]
For me the fix was to change the margins in .fc-icon:after from margin: 0 -1em to margin: 0 0
This appears to work in Edge, Chrome and IE10 without changing the positioning

**Comment by jamessharp** [comment]
Yup, the fix by @RunningDog54 seems to be good.

**Comment by soisme** [comment]
@RunningDog54 's fix works for Edge but the same issue is still occuring with the latest Chrome Version 47.0.2526.106
Any other fix?

**Comment by emielmolenaar** [comment]
Same issue here, the workaround posted by @soisme fixes the problem for me while keeping everything OK in Chrome (Version 49.0.2623.110).

**Comment by lukeaus** [comment]
@soisme good solution.
Why don't you submit a PR?

**Comment by arshaw** [comment]
fixed and released in v2.7.1
https://github.com/fullcalendar/fullcalendar/releases/tag/v2.7.1
