### ISSUE TITLE
Change how month-view events are positioned. Avoid gaps.

### ISSUE THREAD

**Issue by joshualambert** [fullcalendar/fullcalendar#2853]
I'm in the process of implementing an activity calendar for a nursing home that will be printed on sheets of LEGAL sized paper. I'm having a difficult time making everything fit into the calendar, but this is because in the new versions of FullCalendar, it renders events on a row-by-row basis for each week inside of tables instead of the DIV method that worked so much better for events that needed to word-wrap. This new feature is resulting in a ton of whitespace as seen in my image example below:

![2015-09-02_1304](https://cloud.githubusercontent.com/assets/1421842/9662359/ca43dd3e-5224-11e5-88e8-fc710b37346d.png)

Does anybody know if it's possible to force FullCalendar to render like it did back in 2.0.0? I'd like to use the latest version, but this change using tables is terrible for longer events, and may require me to use an older version of the library.

**Comment by joshualambert** [comment]
Here's a JS fiddle example of this problem in action:
http://jsfiddle.net/ho4ccfmv/3/

Notice the 2nd and 3rd events on the 17th have white space causing this cell to be taller than it should.

**Comment by arshaw** [comment]
See the really old changelog entry:
https://github.com/fullcalendar/fullcalendar/blob/master/CHANGELOG.md#v210-2014-08-25

> Events are styled to be one line by default ([1992]). Can be undone through custom CSS, but not recommended (might get gaps [like this][111] in certain situations).

**Comment by arshaw** [comment]
so, in a way, known behavior. but keeping this open to discuss potential solutions/workarounds

**Comment by arshaw** [comment]
but the quick fix it keep the default behavior of having the events be one line

**Comment by joshualambert** [comment]
One thought I had was to why not have each DAY CELL in a row contain a child table, where each row inside the child table could contain an event. I think this is the happy medium that avoids using floats, and leverages tables to solve this problem. Thoughts?

**Comment by joshualambert** [comment]
My current approach is really dirty, but I haven't been able to find another way-- I combine all the events for a day together, and pass only a single event to each day from my API with the API layer adding the timestamps as part of the event title. Not the cleanest thing, but at least I got the results I was after. See here: 

<img width="1426" alt="2015-10-11_0850" src="https://cloud.githubusercontent.com/assets/1421842/10417073/25dc87ca-6ff5-11e5-8cdc-de4a9b1cd3e2.png">

**Comment by arshaw** [comment]
the reason I changed the DOM structure in the first place was to make fullcalendar render much better when being printed (my a paper+ink printer). the horizontal positioning of events needed to be liquid and dynamic (and not use JS) because the width of the document would change without warning when being formatted for print. there was no cross-browser workaround for this at the time, but i will reevaluate now that browsers have come a long way since

**Comment by joshualambert** [comment]
Good to know. I'm doing printing in this use case, so if this is something you decide to take action on, let me know and I'll see how I can help.

**Comment by arshaw** [comment]
I'm thinking about reversing the current behavior to become more in line with the behavior desired in this ticket. Though not any time soon.

Here's my rationale. [responsive views](https://github.com/fullcalendar/fullcalendar/issues/3187) calls for events to be rendered as "color dots", which means each event must render on each day, requiring a distinct DOM node. If we're going this far, we might as well display a distinct event element for each day when in print view, though as a somewhat normal text rendering, not as a dot. The whole reason for doing the current table-cell-based event positioning was to solve the printing problem. If that constraint is loosened, we have the freedom to go back to coordinate-based positioning.

**Comment by Neuron144** [comment]
@arshaw  With all the respect to this plugin, I would say that changing the DOM to be like this was a bad idea!

**Comment by joshualambert** [comment]
Did anybody following this ticket come up with a way to solve this problem? I got an email from someone last night asking if I ever did, and sadly, I'm still using the approach designed above. (Combining everything into a single event on the API side.)

**Comment by edik-simonian** [comment]
@arshaw any chance we switch the month/week views back to div structure instead of tables like it is now?

**Comment by LeaTark** [comment]
If anyone's still following this, I made a change that has this effect but for accessibility purposes, to make events render in a logical tab order.  Please not that this does also remove the ability for events to span days but we aren't using that feature.


In function DayGridEventRenderer.prototype.renderSegRow, around line 14325

Find

`        for (i = 0; i < levelCnt; i++) {`
`            levelSegs = segLevels[i];`
`            col = 0;`
`            tr = $('<tr/>');`
`            segMatrix.push([]);`
`            cellMatrix.push([]);`
`            loneCellMatrix.push([]);`
`            // levelCnt might be 1 even though there are no actual levels. protect against this.`
`            // this single empty row is useful for styling.`
`            if (levelSegs) {`
`                for (j = 0; j < levelSegs.length; j++) {`
`                    seg = levelSegs[j];`
`                    emptyCellsUntil(seg.leftCol);`
`                    // create a container that occupies or more columns. append the event element.`
`                    td = $('<td class="fc-event-container"/>').append(seg.el);`
`                    if (seg.leftCol !== seg.rightCol) {`
`                        td.attr('colspan', seg.rightCol - seg.leftCol + 1);`
`                    }`
`                    else {`
`                        loneCellMatrix[i][col] = td;`
`                    }`
`                    while (col <= seg.rightCol) {`
`                        cellMatrix[i][col] = td;`
`                        segMatrix[i][col] = seg;`
`                        col++;`
`                    }`
`                    tr.append(td);`
`                }`
`            }`
`            emptyCellsUntil(colCnt); // finish off the row`
`            this.dayGrid.bookendCells(tr);`
`            tbody.append(tr);`
`        }`

and replace with

`        col = 0;`
    `        tr = $('<tr/>');`
`        while (col < colCnt) {`
`            td = $('<td class="fc-event-container"/>');`
`            for (i = 0; i < segLevels.length; i++) {`
`                for (j = 0; j < segLevels[i].length; j++) {`
`                    if (segLevels[i][j].leftCol == col) {`
`                        td.append(segLevels[i][j].el);`
`                    }`
`                }`
`            }`
`            tr.append(td);`
`            col++;`
`        }`


This is really rough with more looping than I'd like but it works for what we want.

I'd welcome any suggested optimisation.

**Comment by mitzihazel** [comment]
@LeaTark  Okay this works. You need to add `tbody.append(tr);` at the end of the line for it to render the events.

**Comment by LeaTark** [comment]
> @LeaTark Okay this works. You need to add `tbody.append(tr);` at the end of the line for it to render the events.

You're absolutely right.  I missed that line when I copied it.

Updated now.  Thank you.

**Comment by arshaw** [comment]
If you're curious to know, this will be included in v5 (currently in-development)
**blog post:** https://fullcalendar.io/blog/2020/02/changes-in-the-upcoming-v5

**Comment by arshaw** [comment]
there have been two v5-beta releases. they contain this fix. [please see the latest blog post](https://fullcalendar.io/blog/2020/04/new-ui-features-beta)

**Comment by arshaw** [comment]
but please note, print-view is currently not very good. this fix only exists when viewing in a normal browser.

**Comment by arshaw** [comment]
this is no longer the case in v5 ([just released](https://fullcalendar.io/blog/2020/06/v5-official))
