### ISSUE TITLE
Show month with a day per line

### ISSUE THREAD

**Issue by Soufraz** [fullcalendar/fullcalendar#2854]
Hello,
Is there some issue about show the fullcalendar in vertical orientation?
In my case, for mobile aplications. Current month with all days and events per day.
Something like this:

```
-----------------1-
|      event1     |
|      event2     |
|      event3     |
-------------------
-----------------2-
|      event1     |
|      event2     |
|      event3     |
-------------------
-----------------3-
|      event1     |
|      event2     |
|      event3     |
-------------------
-----------------4-
|      event1     |
|      event2     |
|      event3     |
-------------------
```
...
Till last month day. 
Thank you..

**Comment by espen** [comment]
What is the issue? Can you provide a screenshot with the problem?

**Comment by Soufraz** [comment]
Isn't a problem. I wonder to view the calendar in vertical list. One day
per line. Is that possible?

**Comment by espen** [comment]
If it is not a problem then please do not open a issue. See http://fullcalendar.io/support/

I don't think it is possible but it is possible to create a custom view. See http://fullcalendar.io/docs/views/Custom_Views/

**Comment by Soufraz** [comment]
Ok. Thank you for support.

**Comment by arshaw** [comment]
hi @Soufraz you might be hoping for #560 (please subscribe)
