### ISSUE TITLE
Scheduler: gotoDate function doen't work properly

### ISSUE THREAD

**Issue by e-nemo** [fullcalendar/fullcalendar#2857]
When using fullcalendar with scheduler plugin, the gotoDate function to force display of a date range doen't work properly. The date range is correct but the header is not (it display's the current date) and fullcalendar try to fetch events for the current date instead of the selected date range.
Strange effect, if I try to display the selected date in a javascript alert before calling gotoDate, it works correctly (header, and events) ???

**Comment by arshaw** [comment]
hi @e-nemo , would you be able to make a jsbin recreation? http://fullcalendar.io/wiki/Reporting-Bugs/

would really help me in debugging. thanks so much

**Comment by intared** [comment]
Hi @arshaw, this still seems to be a problem.

Check this out - http://jsbin.com/zutukoxuno/1/edit?console,output. Just hit the "Go to 01/01/2016" button.

It tries with both a string date, a moment and finally as per v1 docs http://fullcalendar.io/docs1/current_date/gotoDate/.

None have an impact.

**Comment by intared** [comment]
incrementDate works fine - so I'm using that to work around for now, but it'd be cool (and simpler) to use the goToDate method.

Code (pseudo, not tested) in case it helps anyone (@e-nemo?).

`var newDate = new moment( <dateHere> ),
	newDiff = new moment.duration( newDate.diff( $( '#schedular' ).fullCalendar( 'getDate' ) ) );
$( '#schedular' ).fullCalendar( 'incrementDate', newDiff );`

**Comment by arshaw** [comment]
`gotoDate`. NOT `goToDate`:
http://jsbin.com/dudukorexu/1/edit?js,output

**Comment by intared** [comment]
Now I feel stupid. I obviously misread the docs.

Thanks
