### ISSUE TITLE
Incorrect display of scale events weekly and daily

### ISSUE THREAD

**Issue by alex-danieli** [fullcalendar/fullcalendar#2859]
events: [
         			{
					title: '8:14 Entrata / 12:03 Uscita',
					start: new Date(2015, 8, 27, 8 ,14),
					end: new Date(2015, 8, 27, 12 ,3),
					backgroundColor: Theme.colors.green,
				},
				{
					title: '12:30 Entrata / 17:45 Uscita',
					start: new Date(2015, 8, 27, 12 ,30),
					end: new Date(2015, 8, 27, 17 ,45),
					backgroundColor: Theme.colors.green,
				},			
				{
					title: '8:30 Entrata / Uscita 17:30',
					start: new Date(2015, 8, 28, 8 ,30),
					end: new Date(2015, 8, 28, 17 ,30),
					url: 'javascript:alert("Errore Manca Pausa Pranzo")',
					backgroundColor: Theme.colors.orange,
				}
			]

Month: <b>OK</b>
Week: <b>KO</b>
Day: <b>KO</b>

![month](https://cloud.githubusercontent.com/assets/6577970/9719387/15b4aafc-5584-11e5-8c75-7184f0d9740c.jpg)
![week](https://cloud.githubusercontent.com/assets/6577970/9719388/15ea754c-5584-11e5-924b-eab4718589b4.jpg)
![day1](https://cloud.githubusercontent.com/assets/6577970/9719385/15b3883e-5584-11e5-810b-9e49d4785281.jpg)
![day2](https://cloud.githubusercontent.com/assets/6577970/9719386/15b3fd6e-5584-11e5-8174-0d1d1b413347.jpg)
![day3](https://cloud.githubusercontent.com/assets/6577970/9719384/15b33c9e-5584-11e5-8f3a-dbef474ee1d7.jpg)

**Comment by espen** [comment]
Can you explain/point out the problem?

**Comment by alex-danieli** [comment]
As you can see I have included three events , two in the same day and one the next day. The view is perfect on a monthly , weekly and daily in that there are anomalies , the most obvious is that I have not included events for the day 26 but those appear the day 27. For the day 27 I only two events but is displayed superimposed also that of 28. I have attached some screenshots to better understand the problem . Thank you

**Comment by espen** [comment]
Can you put up an example on JSFiddle? Have you tried defining datetimes using Moment?

**Comment by alex-danieli** [comment]
Right now I do not have much time to load on jsfiddle.net code, I do my best to do it this evening, tomorrow at the latest . However screenshots attachments I think are clear

**Comment by espen** [comment]
Yeah but I don't have those issues with my calendar, so it is probably related to how events are defined or some other settings. Just my guess.

**Comment by alex-danieli** [comment]
Ok thx i'll take a look

**Comment by alex-danieli** [comment]
I'm updating a template configured with version 1.6.4 and probably many things have changed since then ... (work in progress :D)

**Comment by alex-danieli** [comment]
Ok , I checked out and actually upgrade does not maintain backward compatibility and so I'll have to rewrite everything compatible to version 2.4 ( I'll have to study the new documents ) . Thanks anyway assistance that you gave me , you can close the issue. 
Alex D.

**Comment by espen** [comment]
Yeah 2.x is a breaking change. See http://fullcalendar.io/wiki/Upgrading-to-v2/

**Comment by espen** [comment]
Also, can you please close this issue?

**Comment by alex-danieli** [comment]
Yeah :D
