### ISSUE TITLE
multiple events on 1 day not shown correct

### ISSUE THREAD

**Issue by arshaw** [fullcalendar/fullcalendar#286]
Originally reported on Google Code with ID 15

```
What steps will reproduce the problem?
1. set multiple events starting on same date
2.
3.

What is the expected output? What do you see instead?
events beneath eachother, instead the events are on top of each other

What version of the product are you using? On what operating system?
1.1
Windows Vista

Please provide any additional information below.

```

Reported by `paul.wolbers` on 2009-05-18 11:33:13

**Comment by arshaw-test** [comment]
this is a test
&uarr;
Please visit the link, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates.

**Comment by arshaw-test** [comment]
&uarr;
Please visit the link, **give a** 👍 **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈 **Subscribe** button to receive updates.
