### ISSUE TITLE
Height of view ignores minTime and maxTime attributes

### ISSUE THREAD

**Issue by crazymao** [fullcalendar/fullcalendar#2862]
**Code:**
```html
<!DOCTYPE html>
<html>
<head>
	
<link href="fullcalendar-2.4.0/fullcalendar.css" rel="stylesheet" />
<link href="fullcalendar-2.4.0/fullcalendar.print.css" rel="stylesheet" media="print" />

</head>
<body>

<div id="calendar"></div>
			
<script src="fullcalendar-2.4.0/lib/moment.min.js"></script>
<script src="fullcalendar-2.4.0/lib/jquery.min.js"></script>
<script src="fullcalendar-2.4.0/fullcalendar.min.js"></script>

<script>
$(document).ready(function() {
    $('#calendar').fullCalendar({
    	defaultView: 'agendaWeek',
    	defaultDate: '2015-09-12',
    	minTime: '17:00:00',
    	maxTime: '23:00:00',
    	timeFormat: 'H:mm',
		allDaySlot: false,
		eventLimit: true,
		editable: true,
		snapDuration: '01:00:00',
		defaultTimedEventDuration: '01:00:00',
		eventDurationEditable: false
	});
});
</script>
</body>
</html>
```

**Problem:**
The height of the view doesn't seem to take into account the `minTime` and `maxTime` attributes, it always sets it to max. When the time range is smaller than the max height of the view it still fills in that height regardless of the difference between `minTime` and `maxTime`.

<img width="1280" alt="screen shot 2015-09-12 at 5 04 27 pm" src="https://cloud.githubusercontent.com/assets/770255/9834255/5d1bc1c4-5970-11e5-9118-2e04535ff294.png">

**Comment by arshaw** [comment]
If you set the height to `auto`, you should get the behavior you want ([more info](http://fullcalendar.io/docs/display/height/))

if you want the calendar to be the normal height, but you want the slots to *expand* to fill the available space, that is a different feature request: #265

**Comment by fredan16** [comment]
what if you wanna do the opposite and make the inner container cover whole page?
by using this you can get container to fit window but events doesnt align. If I do a refetch events manually, that makes the events align properly, but there should be a better option.

        var height = $('#calendar').find('.fc-time-grid-container').height();
        //$('#calendar').find('.fc-slats').css('height', height + 'px');
        //$('#calendar').find('.fc-slats>table').css('height', height - 30 + 'px');

//Mikael
