### ISSUE TITLE
Special charaters in calendar

### ISSUE THREAD

**Issue by kusj** [fullcalendar/fullcalendar#2863]
Hello,

Can we allow special characters line "..., é, è " etc in the content ?

Thanks,

**Comment by espen** [comment]
Are you saying this is not working? If please provide a failing example.

BTW: i have no problems with using special characters in FullCalendar.

**Comment by kusj** [comment]
Ex : Modern and past sea-level&hellip;

**Comment by kusj** [comment]
Modern and past sea-level &hellip;

**Comment by kusj** [comment]
Modern and past sea-level &hellip;
![image](https://cloud.githubusercontent.com/assets/14090284/9849531/dca0b16a-5afc-11e5-94b6-3a55d07a132e.png)

**Comment by espen** [comment]
I think the problem is with your encoding or server output - not with fullcalendar. That text is working in my code.

**Comment by arshaw** [comment]
you special characters need to be encoded into the string as real UTF8 characters, NOT as html entities.
