### ISSUE TITLE
Is there a way to write a custom scrolltime function?

### ISSUE THREAD

**Issue by alanirudh** [fullcalendar/fullcalendar#2865]
I need current time to be in the center of the view instead of being on the top. I have tried to override the scroll top value of "fc-time-grid-container" but for some reason the top most slot is always set to 6:00am. I know the default value for scrollTime is 6:00am due to which even though I try to set the scroll top in my viewRender method the scrolltop value always remain the same.

Is there any work around to override the scroll position ?

Here is fiddle link- http://jsfiddle.net/anirudhladha/233mqf1w/1/

**Comment by arshaw** [comment]
there are plans to do this. could you subscribe to the following issues?
https://github.com/fullcalendar/fullcalendar/issues/1037
https://github.com/fullcalendar/fullcalendar/issues/861
