### ISSUE TITLE
Is there a way to get a date's events?

### ISSUE THREAD

**Issue by Djokal** [fullcalendar/fullcalendar#2867]
I was wondering if there is a way to get events per day without having to go through the events json.
I am asking for this because I am using recurring events with dow and ranges, I would like to get all event div's or objects per day.
Any ideas?

**Comment by espen** [comment]
You can fetch local events manually using http://fullcalendar.io/docs/event_data/clientEvents/

Also please see http://fullcalendar.io/support/
