### ISSUE TITLE
header button z-index on top of popover

### ISSUE THREAD

**Issue by jenaymarbury** [fullcalendar/fullcalendar#2869]
recreate on jsbin, here http://jsbin.com/minilu/edit?html,css,js,output .

On the calendar view with <month><week><day> header buttons. For a particular date that appears almost exactly below the header buttons (Friday, Feb 6, 2015 of the example), if there are a large number of events for that date and 'eventLimit' is true, when you click on the <+## more> link, the resulting pop-up listing of events does not fully overlap the header buttons. In the example, the 'month' button appears on top of the event listing window. See images, below.
![image1](https://cloud.githubusercontent.com/assets/12914978/9912431/9af116e0-5c75-11e5-9334-1f4d6833de2e.PNG)
![image2](https://cloud.githubusercontent.com/assets/12914978/9912432/a0ac4ec4-5c75-11e5-8127-3cf03bf296ad.PNG)

**Comment by arshaw** [comment]
thanks for the recreation.

**ALSO:** i noticed that if there are scrollbars on the content area, the popover is attached within the scrolling region. it should be attached outside of that

**Comment by jenaymarbury** [comment]
Any updates?

**Comment by arshaw** [comment]
fixed in v5 (and probably v4 as well)

https://codepen.io/arshaw/pen/rNxwVzR?editable=true&editors=001
