### ISSUE TITLE
How to show an accusative month name form in view title for russian locale?

### ISSUE THREAD

**Issue by sw-** [fullcalendar/fullcalendar#2870]
I'm using fullcalendar with lang: 'ru' option and in a view title I can see a month name in russian like '14 - 20 сентябрь 2015'.

But according to russian grammar it should be '14 - 20 сентября 2015' - accusative month name form.

I see fullcalendar lang-all.js file has accusative month name forms for russian locale. Is there any way to show them in view title?

It's reproducible on the example page http://fullcalendar.io/js/fullcalendar-2.4.0/demos/languages.html - chose ru language and click day(День) view

**Comment by kotkota** [comment]
The same thing here. There is correct month name form in Agenda view in day headings (`.fc-list-heading-main`), but when you click it and swith to a Day view, there is wrong form in title (`.fc-center`)

**Comment by arshaw** [comment]
this bug was due to moment's formatting, but now that moment isn't used at all in v4 and 5, it would be the fault of the Intl API.

I bet it's fixed tho. https://fullcalendar.io/docs/locale-demo
