### ISSUE TITLE
Display Full Text

### ISSUE THREAD

**Issue by tareq-halaby** [fullcalendar/fullcalendar#2871]
How can I make fullcalendar display full text in week view? 

I Was able to fix this for month view by adjusting CSS as following:

```
.fc-day-grid-event .fc-content {
	white-space: normal !important;
}
```

but looks like in the week view it's being added as divs  with absolute positions which means if I change things it will fall-out of the specified time.

![events](https://cloud.githubusercontent.com/assets/1264607/9976426/4f42a8b6-5eec-11e5-9c66-c585b9dc82c6.png)

**Comment by arshaw** [comment]
when #961 is solved, this will be solved as well. plz subscribe to that issue
