### ISSUE TITLE
Events for removed event source appearing on calendar

### ISSUE THREAD

**Issue by woodlandhunter** [fullcalendar/fullcalendar#2873]
See fiddle: http://jsfiddle.net/uzhfnd8L/

I would expect that only the event with title "TWO" remains on the calendar.

`removeEventSource` should cancel pending AJAX request or otherwise check that the event source is not removed, if possible.

(This is a contrived example, but I've run into the problem on a real calendar as a result of user action/slight delay in event endpoint response.)

**Comment by woodlandhunter** [comment]
@arshaw Do you need more information or help from me?

**Comment by arshaw** [comment]
hi @woodlandhunter i haven't had time to run the demo and dig around, but will try to get to it soon. thanks for the jsfiddle. no further action required.

**Comment by arshaw** [comment]
reproduced. thank you.

just for kicks i added a setTimeout between the calls, and things work okay, so the bug must be a race condition:
http://jsfiddle.net/uzhfnd8L/1/

**Comment by arshaw** [comment]
[Code complete](https://github.com/fullcalendar/fullcalendar/commits/v2.8.0-dev) and [docs written](https://github.com/fullcalendar/fullcalendar/commits/docs-2.0) but not yet released. Will update this thread when released.
