### ISSUE TITLE
Can't create past events to calendar

### ISSUE THREAD

**Issue by giaidieu** [fullcalendar/fullcalendar#2874]
Hi,

I try to add a list of past and future events to the calendar and realize that past events are not added. Is it possible to add past events please?

Thanks and best regards,

**Comment by espen** [comment]
Can you please provide an example of this problem? I don't have any issues with adding events in the past in my calendar.

**Comment by giaidieu** [comment]
Hi Espen,

It was my fault, I could now get it working properly. Sorry for the false report.

Regards,

**Comment by espen** [comment]
Good you sorted it out. Can you please close this issue?

**Comment by tm01xx** [comment]
Yes, may you show me how to close it? I can't find where to do so.
