### ISSUE TITLE
Add fc-past/fc-today/fc-future classes to event tds

### ISSUE THREAD

**Issue by xNufarx** [fullcalendar/fullcalendar#2875]
Hi,

I'm trying to change the mouse cursor for days that are in past, but when there is an event's row she change the cursor to default. And i'm unable for event row's tds to know if she is in the past, today or in the future.

So i think that it could be useful if we add, as for fc-bg rows, fc-past/fc-today/fc-future classes for event tds.

Thanks and best regards.

Sorry for my english I'm french :)

**Comment by arshaw** [comment]
similar to #2695 

but a bit more complicated because event TDs can span multiple days, in which case they might be past/today/future all at the same time :(

**Comment by arshaw** [comment]
Especially considering the edge case of events spanning multiple days, thus not having a clear past/future/today, i'm tempted to let the developer handle this behavior by introducing custom logic in `eventRender`, where they can use momentJS and the event's dates to apply whatever classnames they want.
