### ISSUE TITLE
Add ac Class to data-date attribute if a date has an event

### ISSUE THREAD

**Issue by amitabhaghosh197** [fullcalendar/fullcalendar#2876]
I am using your plugin. I want to add a class to the data-date attribute if any day has an event exist. Can anyone please help me how to do that?
Thanks in advance.

**Comment by espen** [comment]
Please see http://fullcalendar.io/support/ for questions.

**Comment by amitabhaghosh197** [comment]
Thanks espen

**Comment by arshaw** [comment]
duplicate of #345
