### ISSUE TITLE
When refreshing events when calendar is in an iScroll div, the events are incorrectly placed

### ISSUE THREAD

**Issue by GeekCentral** [fullcalendar/fullcalendar#2877]
I've got a fullcalendar in a div that has an iScroll (v5, with zoom) applied to it. This causes the event start/end times to be incorrectly positioned. eg 10 event will show at 9:30

I have to reset the zoom of the iScroll before updating events as a work around.

**Comment by arshaw** [comment]
what's an iScroll?

could you make an online demo of the bug using jsbin?
http://fullcalendar.io/wiki/Reporting-Bugs/

would be very helpful. thank you!
