### ISSUE TITLE
TypeError: key.toUpperCase is not a function

### ISSUE THREAD

**Issue by lordgreg** [fullcalendar/fullcalendar#2880]
I'm getting this error when trying to use latest FullCalendar installed using bower:

```
TypeError: key.toUpperCase is not a function
    at Locale.longDateFormat (moment.js:2635)
    at formatRange (fullcalendar.js:1564)
    at fc.View.Class.extend.formatRange (fullcalendar.js:7067)
    at fc.View.Class.extend.computeTitle (fullcalendar.js:7032)
    at fc.View.Class.extend.updateTitle (fullcalendar.js:7026)
    at fc.View.Class.extend.setRange (fullcalendar.js:6948)
    at View.extend.setRange (fullcalendar.js:10796)
    at fc.View.Class.extend.setDate (fullcalendar.js:6940)
    at fc.View.Class.extend.displayView (fullcalendar.js:7156)
    at fullcalendar.js:7118
```

Can someone explain me, why this is happening?

Thank you :+1:

**Comment by arshaw** [comment]
would you be able to post an online demo of this bug? http://fullcalendar.io/wiki/Reporting-Bugs/

**Comment by victorcarvalhosp** [comment]
I'm getting the same error...

**Comment by arshaw** [comment]
could someone post a jsbin? https://fullcalendar.io/wiki/Reduced-Test-Cases/

**Comment by jeremymcminn** [comment]
Also getting this error - will get a jsbin to you as soon as I can @arshaw

**Comment by kreiach** [comment]
We received the same error after upgrading to the latest version. 

Tracked it down to titleFormat. The new version uses a single string with View-Specific Options, while the previous version used View Option Hashes. We needed to change how we were initializing the Calendar.

https://fullcalendar.io/docs/views/View-Specific-Options/
https://fullcalendar.io/docs/views/View_Option_Hash/

The error itself was triggered via moment.js's longDateFormat function attempting to upper case the Option Hash object.

**Comment by Nuvolect** [comment]
@kreiach, @arshaw, I'm getting the same error, with version v3.3.1. Is there a fix or workaround?

**Comment by arshaw** [comment]
Can someone post the versions of `fullcalendar` and `moment` that your bower environment has? 

This problem might be related to a bower/composer bug: #3632

**Comment by zainulhassan4** [comment]
I tried it with the mix of following versions:

jquery 1.11.1, 3.2.1
moment 2.9, 2.18
fullcalendar 1.5.4 onwards, 3.2.1

full calendar worked till 2.9 with any moment or jquery, however fc version 3 onwards failed for me.
im not using composer to download it, only bower.

**Comment by Silviusconcept** [comment]
Same problem here:
- jquery 3.1.0
- moment 2.18.1
- fullcalendar 3.4.0

**Comment by shyamneosoft111** [comment]
@kreiach, I'm getting the same error, with version v3.3.1 of fc.

**Comment by kalimerre** [comment]
I'm getting the same, is there any fix ?

**Comment by Silviusconcept** [comment]
@shyamneosoft111 @kalimerre ff you did the library update check the configuration options, in my case I had to change "titleFormat" to -> 
`views:{
    week:{
      titleFormat: "DD MMMM YYYY"
  }
}`

**Comment by kalimerre** [comment]
Indeed it seems to works like a charm

You rock @Silviusconcept

**Comment by forestallers** [comment]
Removing titleFormat worked for me.

**Comment by silasrm** [comment]
In my case, I'm using `noMeridiemTimeFormat : true` and it crash the momentjs longDateFormat.
