### ISSUE TITLE
hover menu

### ISSUE THREAD

**Issue by ambicoder** [fullcalendar/fullcalendar#2886]
I am trying to make a  menu that will hover over the calendar just like menus in facebook when top bar icons are clicked...the problem though is that this menu tends to be below the calendar...I tried adjusting the z-index of the menu but I could not achieve what I want.

What can I do?

**Comment by espen** [comment]
This is not really a Fullcalendar issue. I suggest that you ask on StackOverflow. Also see http://fullcalendar.io/support/

**Comment by ambicoder** [comment]
thanks...for the clarification...I found a solution after all...
