### ISSUE TITLE
When dragging from an all day date to a timed event the end date remains NULL.

### ISSUE THREAD

**Issue by mikem29** [fullcalendar/fullcalendar#2889]
on the eventDrop: function end date is null and it seems it should be start date + defaultTimedEventDuration

Drag an all day date from the week view into a timed event notice how it 'should' say 7:00PM - 9:00PM but it just says 7:00PM

![end date empty when dragging from all day event to a timed event fw](https://cloud.githubusercontent.com/assets/10246059/10373598/47dcab4c-6da3-11e5-92a5-3c7a1f57e09c.png)

**Comment by arshaw** [comment]
if you set `forceEventDuration` to `true`, you will get this behavior
http://fullcalendar.io/docs/event_data/forceEventDuration/

however, that will force an event end time for *every* event, even ones that lack an event on initial load of the calendar. is this okay for you

**Comment by mikem29** [comment]
Yes it does my solution was to just clone the start date and add an hour to
the newly dragged timed event... thanks.
