### ISSUE TITLE
timelineWeek vs timelineDay

### ISSUE THREAD

**Issue by Patatou** [fullcalendar/fullcalendar#2892]
Hi there,

When i put slotDuration: '00:05:00', slotWidth:30 and slotLabelInterval: '00:30' : 
- In timelineDay i've this http://hpics.li/9d59a2b
- In timelineWeek  i've this http://hpics.li/22d31f5

Option slotDuration and slotWidth is no longer taken in consideration when i'm on timelineWeek view.

I've try to simply modify your example with timelineThreeDays with simply put days:7, and i've same effect.

Any solution ?

Ty

**Comment by arshaw** [comment]
discussion moved to fullcalendar-scheduler:
https://github.com/fullcalendar/fullcalendar-scheduler/issues/47
