### ISSUE TITLE
Fullcalendar for Angular JS

### ISSUE THREAD

**Issue by sivaraj-mindze** [fullcalendar/fullcalendar#2893]
We are evaluating the use of fullcalendar (timelineday view) for our angular js application.

Found there is a problem with this jquery calendar to work on angular js enviornment.

Also, I should be able to add / edit the events in external form by clicking the cell for each time slots.

Any help will be highly appreciated.

**Comment by arshaw** [comment]
Can you be much more specific about the problems? Please post a bug recreation: http://fullcalendar.io/wiki/Reporting-Bugs/
