### ISSUE TITLE
Adding icon with Custom callback for JavaScript event in date header

### ISSUE THREAD

**Issue by kishorIntelligrape** [fullcalendar/fullcalendar#2894]
Hi,

I want to add a print icon in the date header. To achieve this I will be creating a new view which will extend agendaDay view (for only this view I want my changes). However I am unable to figure out how to create a callback with event ( similar to eventLimitClick, or eventClick). 
Is there any ref. I can use will be much appreciated

Note: I am using fullcalendarjs with angular-ui calender (http://angular-ui.github.io/ui-calendar). 

Thanks.

**Comment by arshaw** [comment]
"creating views from scratch" might help you get started:
http://fullcalendar.io/docs/views/Custom_Views/

somewhat related: https://github.com/fullcalendar/fullcalendar/issues/1806
