### ISSUE TITLE
The time for each day in Agenda view

### ISSUE THREAD

**Issue by noras666** [fullcalendar/fullcalendar#2896]
Hello,
You can display anything in the time slot for each day of the week view functions.
I do not want to use the axis from the side view. I would like to get the 11:15, 11:30 for each day in this view. I did not find this data in the documentation for that functionality. 

You are able to do to help?

**Comment by arshaw** [comment]
"getting help"
http://fullcalendar.io/support/

**Comment by noras666** [comment]
Okay, I do not understand. Can I get this effect?

http://prntscr.com/8rh87e

**Comment by arshaw** [comment]
that is currently not possible. i'm not sure that would be very usable however, if there are too many events, they would cover up the text of the time, and you couldn't see the times anymore.

if you are feeling adventurous you could try to code up your own view plugin from scratch (hard):
http://fullcalendar.io/docs/views/Custom_Views/
