### ISSUE TITLE
Eventsources start and end get parameters wrong date format

### ISSUE THREAD

**Issue by krfa1** [fullcalendar/fullcalendar#2897]
Hello,

In the event source, the start and end parameters are automatically added with the date format yyyy-mm-dd. There is no way to globaly set the date format as something different like dd.mm.yyyy or whatever?

Thank you.

Fabrice

**Comment by krfa1** [comment]
I've maybe found a workaround but aren't able to access to the calendar start / end value during the initial setup. I'd like to do something like that :

eventSources: [
	{
	//add the availability source, including only the background type selectable
	url: '/mypage/?',
	startParam: false,
	endParam: false,
	data: {
		start: my_starting_calendar_day,
		end: my_ending_calendar_day
	},

Would it be a good way?

**Comment by arshaw** [comment]
if the default json feed implementation doesn't suite your needs, you can always write your own fetching function: http://fullcalendar.io/docs/event_data/events_function/
