### ISSUE TITLE
Previous and Next button arrows don't appear in Edge on Windows 10

### ISSUE THREAD

**Issue by masteroleary** [fullcalendar/fullcalendar#2898]
Looking at the calendar from the home page http://fullcalendar.io/ in Edge you will see the left and right arrow icons don't appear. I have tried to fix. By removing text-shadow I got the arrows to appear but they are misaligned. Edge seems to be inconsistent when changing styles from the developer tools so I have been unsuccessful centering the icons.

**Comment by arshaw** [comment]
duplicate of #2852. please subscribe to that
