### ISSUE TITLE
Error when running `npm install`. peerinvalid The package karma does not satisfy its siblings' peerDependencies requirements!

### ISSUE THREAD

**Issue by WizzieP** [fullcalendar/fullcalendar#2901]
Hello, I get this error when running `npm install`:

    114 error peerinvalid The package karma does not satisfy its siblings' peerDependencies requirements!
    114 error peerinvalid Peer karma-jasmine@0.2.3 wants karma@>=0.9
    114 error peerinvalid Peer grunt-karma@0.8.3 wants karma@~0.12.0
    114 error peerinvalid Peer karma-phantomjs-launcher@0.1.4 wants karma@>=0.9

Full log: http://pastebin.com/Zb4xRErc

Same errors when running through `./build/init.sh`. I'm using Win10 if it matters (it shouldn't).

**Comment by derekm** [comment]
I'm also seeing this. I'm running Fedora 23, node v0.10.36 and npm 1.3.6.

**Comment by peternowee** [comment]
Workaround is to add "karma": "~0.12.0" to package.json.

See karma-runner/grunt-karma#167 for the upstream issue and karma-runner/karma#873 for the workaround.

**Comment by arshaw** [comment]
fixed by 6143c35fd0f4f6fcd0c5c0c923a038016fa07f13 and other commits in v2.7.1, just released
