### ISSUE TITLE
event.dow + event.start + event.allDay breaks allDay rendering in week view

### ISSUE THREAD

**Issue by sebastienratez** [fullcalendar/fullcalendar#2903]
http://jsbin.com/dazonutoko/edit?js,output

Go to week view: observe that all day event is not rendered on top of each column as usual. 

Remove either start or dow property and notice how rendering is back to normal.

**Comment by arshaw** [comment]
allDay: true should cause the `start` time to be disregarded

**Comment by arshaw** [comment]
the `dow` on event objects is not officially supported, and a new solution will be developed for [Recurring Events](#387), so going to close this one out
