### ISSUE TITLE
renderEvent + event.dow + prev/next week/month/year multiplies events all over the place

### ISSUE THREAD

**Issue by sebastienratez** [fullcalendar/fullcalendar#2904]
Please check:
http://jsbin.com/xisubawuli/edit?js,output

Then change week/month/year, then come back. You'll notice events are multiplied.

This does not happen if you provide an event list directly during initialization phase.

**Comment by arshaw** [comment]
this is because when an event is `dow`, it disregards the date within the `start` and only uses the time. the API will be better for this when recurring events (#387) is officially supported. until then, this `dow` is not officially supported for normal events

**Comment by sebastienratez** [comment]
When do you plan on supporting dow officially? I didn't find any other alternative to implement recurring events.

**Comment by arshaw** [comment]
i apologize for the discussion on #387 being lengthy, but most people implement repeating events on the server side. more info on google/stackoverflow probably

**Comment by sebastienratez** [comment]
Server side management of these events means db denormalization and I'm against it unless last resort. A recurring event is only one event instance and I'd like to keep it that way... Anyway, I'll stick around #387 from now on. Thanks

**Comment by sebastienratez** [comment]
For now, I avoid a problem with this little hack:

var m_arrRenderedEventsHashes = [];

	var m_arrRenderedEventsHashes = [];
	
	$("#calendar").fullCalendar({
		viewRender: function (view) {
			m_arrRenderedEventsHashes = [];
		}
		eventRender: function (e,element,view) {
			var eventHash = sha2((isset(e.id) ? e.id : e._id) + e.start);
			if (eventHash in m_arrRenderedEventsHashes) return false;
			m_arrRenderedEventsHashes[eventHash] = true;
			return true;
		}
	}

I store a hash for each rendered event. If the hash exists already, I don't render it. That's probably not very optimized but it works so far.

**Comment by arshaw** [comment]
glad you got something to work.

supporting recurring events on the server doesn't necessarily mean DB denormalization. what people normally do is *expand* a recurring event into multiple instances before sending it over AJAX. it can still be normalized in the DB. it gets expanded after being pulled out of the DB.
