### ISSUE TITLE
addEventSource fails on nonvisible calendars.

### ISSUE THREAD

**Issue by troelslenda** [fullcalendar/fullcalendar#2905]
I'm implementing a two-month calendar view with two seperate instances of fullCalendar, binding them together with this
```js
viewRender: function (view, element) {
  // Let the second calendar change based on the first one.
  var cur = view.intervalStart;
  var d = moment(cur).add(1, 'month');
  cal.next.selector.fullCalendar('gotoDate', d);
}
```
The calendars are current and next month.

On mobile devices I only want to show current month, which works nicely because of ```elementVisible()``` used in ```renderView()```

The problem however is that when I later on add a new source to calendars ```addEventSource()```seems to fail throwing following error.

 ```Uncaught TypeError: Cannot read property 'format' of undefined on line 9447```

As of right now I simply by adding ```:visible``` to the selector before adding the new source.
```js
$('.full_calendar_monthly_view:visible').fullCalendar('addEventSource', {});
```
I'm unsure if it's expected behaviour or if addEventSource/fetchEventSource should be aware of the rendered state of the calendar?

**Comment by arshaw** [comment]
would you be able to create a reduced test case and post it online as a JSBin?
http://fullcalendar.io/wiki/Reporting-Bugs/

**Comment by aa21** [comment]
Same error for me when using `addEventSource() `method inside` viewRender()` callback. I'm adding urls as event sources. 

Traced the error to this function: `_fetchEventSource(source, callback)`. By the time this function is called, `rangeStart` & `rangeEnd` have not been initiated yet. 

My fix was to change these lines:
````
	function _fetchEventSource(source, callback) {
		var i;
		var fetchers = FC.sourceFetchers;
		var res;
`````

to 
````
	function _fetchEventSource(source, callback) {
		var i;
		var fetchers = FC.sourceFetchers;
		var res;
      
                // Initialize rangeStart and rangeEnd if undefined
		rangeStart = rangeStart ? rangeStart : t.view.start;
		rangeEnd = rangeEnd ? rangeEnd : t.view.end;
````

**Comment by cormip** [comment]
That fix did not work for me. t.view.start is null. There does appear to be a race condition regarding calendar visibility. It's the currentView.setDate() function below which sets off the chain that will initialize rangeStart and rangeEnd. If elementVisible() is false, that never occurs.

`
	function renderView(viewType, forcedScroll) {
		if (elementVisible()) {
			currentView.setDate(date, forcedScroll);
		}
	}
`
