### ISSUE TITLE
add event on last day of the month takes wrong endTime

### ISSUE THREAD

**Issue by jparmar** [fullcalendar/fullcalendar#2906]
Hi, 

I have added an event on 31st September (9:00 am to 10:00 am) from the month view of the calendar and found that the endTime parameter takes wrong end time as  2015-12-01. 

endTime should take 2015-10-31.

The issue is happening on 31st date only, otherwise it works fine

**Comment by arshaw** [comment]
would you be able to create a reduced test case and post a JSBin demo?
http://fullcalendar.io/wiki/Reporting-Bugs/
