### ISSUE TITLE
CoordMap not up to date when making calendar visible during external item drag

### ISSUE THREAD

**Issue by jkorri** [fullcalendar/fullcalendar#2910]
Hi, and thanks for an awesome library!

I have a use case where I have a list of external elements on tab A, and calendar on tab B. User can get stuff on the calendar by first dragging an event from tab A on tab B header, which activates tab B and makes the calendar visible, after which the element can be placed on the calendar.

The issue I'm having is that the calendar's CoordMap is built when the drag starts. As the calendar is not visible at time, the dimensions are not correct and calendar cannot recognize which cell the dragged element is on.

I was able to fix this by including CoordMap rebuilding in the renderView function, which then gets executed when I call fullCalendar('render') after making the calendar visible.

Does the above approach make sense, or would there be a better way of addressing this issue?

**Comment by arshaw** [comment]
oh jeez, this is a pretty advanced usecase. but i do understand why it'd be useful. can try to make this work, but it stacks up pretty low against other bugs/features.

**Comment by arshaw** [comment]
seems like you figured this by calling the [render method](http://fullcalendar.io/docs/display/render/), which is exactly what I'd recommend. I can't think of a way of making fullcalendar smart enough to know that it has been shown after previously being hidden, so you need to help it out by explicitly telling it to adjust.
