### ISSUE TITLE
('getView').start) return wrong hour

### ISSUE THREAD

**Issue by JackIlPAZZO** [fullcalendar/fullcalendar#2911]
I'm using the last version of moment.js and also I'm using the FullCalendar plugin 2.3.1. (I've also tried with the last version)-
The problem's that when I get the start date of the calendar:

               console.log($calendar.fullCalendar('getView').start);

this is what returns:

Fri Oct 23 2015 02:00:00 GMT+0200 (ora legale Europa occidentale)

instead of this:

Fri Oct 23 2015 00:00:00 GMT+0200 (ora legale Europa occidentale)

the incorrect hours bug my render events and this is a big problem for me. Is this a bug of moment.js or perphaps I doing something wrong?

NB: With 1.6.1 version of FullCalendar I get the correct result

**Comment by arshaw** [comment]
which view are you using? would you mind posting a simplified JSBin demo? http://fullcalendar.io/wiki/Reporting-Bugs/
