### ISSUE TITLE
Timezone settings not working

### ISSUE THREAD

**Issue by JobaDiniz** [fullcalendar/fullcalendar#2912]
I set `timezone` to **false** or **local** and *fullcalendar* returns me a moment with `utc` flag set to **true**. Because of that, when I call `start.format()` only the date is outputted, but not the time.

I got `2015-10-10` instead of `2015-10-10T00:00:00`.

Any insights?

**Comment by arshaw** [comment]
it's an "ambiguous" moment, by design:
http://fullcalendar.io/docs/utilities/Moment/
