### ISSUE TITLE
FullCalendar not rendering properly

### ISSUE THREAD

**Issue by rePhat** [fullcalendar/fullcalendar#2915]
I've came across some very strange bug, which I didnt make out to either solve or replicate, however the issue still persists.

This is how fullcalendar renders.
![before](https://cloud.githubusercontent.com/assets/12444708/10762194/41299766-7cc5-11e5-969c-dc36e0a79d9d.PNG)
And after clicking any of theese buttons
![after](https://cloud.githubusercontent.com/assets/12444708/10762193/4124b5de-7cc5-11e5-8c51-124c077f0593.PNG)

No errors in console or anything like that, however when I tried to set fullcalendar height, this came up.
![vystrizek3](https://cloud.githubusercontent.com/assets/12444708/10762350/08b04d98-7cc6-11e5-96a9-5b1b4db14419.png)

Any insights of what may be happening?

**Comment by arshaw** [comment]
you're probably initializing it dynamically before DOM is sized, so you'll have to call `render` method yourself: http://fullcalendar.io/docs/display/render/
