### ISSUE TITLE
Header elements are not always equally spaced

### ISSUE THREAD

**Issue by derekm** [fullcalendar/fullcalendar#2921]
FullCalendar CSS gives all header elements a left margin of 0.75em.

With a header config of:

```
header: {
    left: '',
    center: 'prev title next',
    right: ''
},
```

the title is an `<h2>`, giving a calculated font-size of 1.5em, while the prev and next buttons have a .fc button font-size of 1em.

Having differing left margins causes displeasing, uncentered layouts:

![selection_047](https://cloud.githubusercontent.com/assets/379469/10821607/363c5be2-7e21-11e5-9833-1ed1e63f73ce.png)

Where the layout should be symmetrical:

![selection_046](https://cloud.githubusercontent.com/assets/379469/10821636/57ec5d82-7e21-11e5-8f42-8f8c531f48b7.png)

@arshaw has rejected the idea of changing the left/right/center toolbar header element style from "`margin-left: .75em;`" to "`margin-left: .75rem;`" due to IE8 compatibility.

**Comment by derekm** [comment]
Something like this works, and is IE8-compatible... This solution would need additional styles should there ever be support for `customTitle`s like there is support for `customButton`s.

    .fc .fc-toolbar > * > button ~ h2 {
            margin: 0 .75em;
    }
    .fc .fc-toolbar > * > h2 ~ button {
            margin-left: 0;
    }
    .fc .fc-toolbar > * > h2:first-child {
            margin-right: .75em;
    }
    .fc .fc-toolbar > * > h2:last-child {
            margin-right: 0;
    }

**Comment by arshaw** [comment]
dup of #2917

**Comment by arshaw** [comment]
correction, this is not a dup of #2917 (which is a PR), it is merely the github issue for it.

**Comment by arshaw** [comment]
this is fixed in v5 because v5 uses flexbox for this
