### ISSUE TITLE
Timezone property is not working with permanent values

### ISSUE THREAD

**Issue by PavelBrokhman** [fullcalendar/fullcalendar#2922]
Here is the scenario:
I have used sample provided on your site and connected to the JS Bin to test it. I have removed everything except of the 1 event. Also I have added 2 settings: timezone and ignoreTimezone. In addition, I have replaced the start and end time to the proper ISO format. After I have done all of that "local" option have started to work. However, when I have tried to use "America/Chicago" as sample from Docs it didn't work.
$(function() { // document ready
  
  $('#calendar').fullCalendar({
    header: {
      left: 'prev,next today',
      center: 'title',
      right: 'month'
    },
    defaultDate: '2014-11-12',
    editable: true,
    eventLimit: true, // allow "more" link when too many events
    timezone: 'local',
    ignoreTimezone: false,
    events: [
      {
        title: 'Meeting',
        start: '2014-11-12T10:30:00.000Z',
        end: '2014-11-12T12:30:00.000Z'
      }
    ]
  });
});

**Comment by arshaw** [comment]
would you mind creating a JSBin recreation?
http://fullcalendar.io/wiki/Reporting-Bugs/
