### ISSUE TITLE
Row Grouping Feature Request

### ISSUE THREAD

**Issue by riadgaffar** [fullcalendar/fullcalendar#2924]
Hi,

Great work with the FullCalendar! I have a little problem that I have been wrestling with - I need to group rows by certain group header like in the examples/demo shown in the http://ui-grid.info/docs/#/tutorial/209_grouping. They don't necessarily need to be expandable/collapsible but simple row grouping would suffice. Would it be possible or completely out of the paradigm/design?

Thanks!

**Comment by espen** [comment]
You mean like this? http://fullcalendar.io/js/fullcalendar-scheduler-1.0.2/demos/column-grouping.html

**Comment by riadgaffar** [comment]
That's dayView. I am looking for horizontal row grouping in weekly view
kind of like this.

http://i.stack.imgur.com/mUT7I.png

On Saturday, October 31, 2015, Espen Antonsen <notifications@github.com>
wrote:

> You mean like this?
> http://fullcalendar.io/js/fullcalendar-scheduler-1.0.2/demos/column-grouping.html
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/fullcalendar/fullcalendar/issues/2924#issuecomment-152698686>
> .
>


-- 
Sent from Gmail Mobile

**Comment by arshaw** [comment]
is this what you want?
http://fullcalendar.io/js/fullcalendar-scheduler-1.0.2/demos/grouping.html

**Comment by riadgaffar** [comment]
I realize it might be irrelevant but is that or any kind of row grouping
possible in weekly view?

On Monday, November 2, 2015, Adam Shaw <notifications@github.com> wrote:

> is this what you want?
> http://fullcalendar.io/js/fullcalendar-scheduler-1.0.2/demos/grouping.html
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/fullcalendar/fullcalendar/issues/2924#issuecomment-153219922>
> .
>


-- 
Sent from Gmail Mobile

**Comment by arshaw** [comment]
in timelineWeek, yes, but in agendaWeek, no, because agendaWeek does support displaying resource columns yet. See https://github.com/fullcalendar/fullcalendar-scheduler/issues/5

**Comment by Raguking** [comment]
I need row grouping without using scheduler.
