### ISSUE TITLE
FullCalendar event.columnData return wrong column id

### ISSUE THREAD

**Issue by JackIlPAZZO** [fullcalendar/fullcalendar#2929]
I'm using FullCalendar 2.3.1 with fullcalendar multicolumn exstension. Now the problem's that if I'm in week view mode and try to drop an event the event.columnData return a correct number but if I'm in agenda view and try to drop an event I get a wrong result but the code is the same! Now I'm trying to replicate the issue on jsfiddle but seems that in jsFiddle all working good. I don't know why in my project the columnData parameter is returned wrong and in jsFiddle all is correct.
See the console of your browser. 
There's something that I can do for fix this? Something that can cause this bug related to:

moment js
fullcalendar version?
I don't know but if I for example drop the event on the column 0 (the same column of start dropping) I get event.columnData: 1 and should be 0 not 1. 
I'm sorry that in jsfiddle I can't reproduce the bug, but this is also a good thing 'cause there's something that 'cause this bug (only for the agenda view). An example image:

http://i.stack.imgur.com/FF2eL.png

http://i.stack.imgur.com/Zpapg.png

stackoverflow question:

http://stackoverflow.com/questions/33550701/fullcalendar-event-columndata-return-wrong-column-id

**Comment by arshaw** [comment]
either this issue was solved along with this one: https://github.com/fullcalendar/fullcalendar-scheduler/issues/67

but if not, i'm not going to take action anyway, as this feature will be officially supported very soon: https://github.com/fullcalendar/fullcalendar-scheduler/issues/5
