### ISSUE TITLE
Update events after change option in a dropdown

### ISSUE THREAD

**Issue by Jeanbf** [fullcalendar/fullcalendar#2930]
Every time that I changed a option in a dropdown, I call new events to the calendar , but the calendar always works with the first events that I call , I don't know how refresh completely the fullcalendar with the new events.

Code when I select a option.

`actionChangeUsuario: function(data){`

        var self = this;
        var rut = '';
        var subData = 0;
        $("#span_msj_id").hide();

        $("#combo_usuarios_id").change(function() {
                
                $.each(data, function(index,value){ 
                    if(value.Id == $("#combo_usuarios_id").val()){
                        rut = value.rut;
                        nombre = value.nombre_trabajador+" "+value.apellido_trabajador;
                    } 
                });
                $("#panel_calendar_id").show();
                if($("#combo_usuarios_id").val() == 0){
                    $('#calendar').fullCalendar('removeEvents');
                }else{ 
                    self.callTareasDatos(rut,nombre);
                }
        });

    },

Code where I call the new events:

`allTareasDatos : function(rut,nombre){`
        `var self = this;`
        
        self.ajaxCall('../../sistema/api/sistemaTareas/v1/'+"calendarioHoras", "POST", rut).then(function(results) {
            if(results != 1){
              if(results != null){

                 self.calendar(results,rut,nombre);

                }else{
                    $("#span_msj_id").fadeIn(1000);
                    $("#span_msj_id").fadeOut(2500);
                    $('#calendar').fullCalendar('removeEvents');
                }   
            }else{
                window.location.href = "login.html"; 
            }
        });
    },

And here I receive the events:

calendar: function(datos,rut,nombre){

    var self = this;
    console.info(datos);   

    $('#calendar').fullCalendar({
        height: 500,
        events: datos,
        editable: false,
            header: {
                left: '',
                center: 'prev title next',
                right: '',
            },
        eventRender: function (event, element) {
            var self = this;
            element.find('.fc-title').append(" (<strong>"+ event.estado +"</strong>)");
            
        },
        dayRender: function (date, cell) {
            var theDate = $(cell).data('date');
            var fcDaySkel = $("#calendar div.fc-content-skeleton td[data-date='"+theDate+"'].fc-day-number");
            fcDaySkel.prepend("<button type='button' style='margin-right:5px; padding:0; border: none; background: none;' id ='editar_"+theDate+"_control_id' class='btn btn-default addButton' title='Ver/Editar/Agregar'><i class='fa fa-eye'></i></button>");
            self.actionBtnCalendar(theDate,rut,nombre,datos); 
            console.info(datos);
        }

    })

        $('#calendar').fullCalendar('removeEvents');
        $('#calendar').fullCalendar('addEventSource', datos);         
        $('#calendar').fullCalendar('rerenderEvents'); 
`},`

How can I fix this? sorry my english.

Here is my question too in stack:

http://stackoverflow.com/questions/33556640/how-i-can-update-the-source-events-in-fullcalendar-jquery

**Comment by arshaw** [comment]
this is a question rather than a bug report, so not going to solve this here.

you might have better luck if you post a JSBin reduced test case of your bug. "Getting Help":
http://fullcalendar.io/support/

**Comment by Jeanbf** [comment]
I did it using this : $('#calendar').fullCalendar( 'destroy' ); when I select other option in the dropdown, I don't know if is elegant but works! thanks
