### ISSUE TITLE
Event title cut off in month view

### ISSUE THREAD

**Issue by jeremyj11** [fullcalendar/fullcalendar#2931]
Long event titles are cut off in month view from V2 onwards.
It would be great to have an option to specify whether they should be cut off or to wrap to a new line.

I modified the fullcalendar.css to allow this, but this presented another problem - subsequent events in the same row will have a space between them if they do not have a long title.

For more detail and JSFiddle see:
http://stackoverflow.com/questions/33406697/fullcalendar-v2-event-title-cut-off-in-month-view

**Comment by arshaw** [comment]
please read the discussion on #2853 . duplicate
