### ISSUE TITLE
Misordering of the events with the same title in Chrome

### ISSUE THREAD

**Issue by alexhampu** [fullcalendar/fullcalendar#2933]
Hello,
When there are lots of events imported, and in a day there is an event at different hours, the event is in the wrong order. For example:

Example event - 11:00AM
Example event - 04:00PM
Another event - 06:30PM
Example event - 09:00AM

Instead of:
Example event - 09:00AM
Example event - 11:00AM
Example event - 04:00PM
Another event - 06:30PM

A live example is here:
http://www.tnb.ro/ro/calendar?year=2015&month=10 (October 5th, 12th, 26th, 30th)

This really changes things up, but only on Chrome. On Firefox it works normally.

**Comment by espen** [comment]
I don't see the issue (Chrome/OSX). Can you provide a screenshot? Also it would be easier to debug if you provide a jsbin with a limited set of events that cause this issue.

**Comment by alexhampu** [comment]
![fullcalendar-issue](https://cloud.githubusercontent.com/assets/749023/11086507/76fd257e-885a-11e5-8011-e994ae66e460.png)
This happens when there are lots of events, and only at one event in the list and that happens if that event has multiple representations in one day, the time ordering gets wrong. This happens on Chrome with Windows 7 / 8 and 10, of course, on different computers.

**Comment by alexhampu** [comment]
![fullcalendar-issue2](https://cloud.githubusercontent.com/assets/749023/11086564/06ed409c-885b-11e5-8dfd-59a5f0853cbb.png)
Another screenshot with the same issue. This happens on multiple dates.

**Comment by arshaw** [comment]
thank you for the bug report, but would you be able to go a little further and make a whittled down JSBin recreation of this? http://fullcalendar.io/wiki/Reporting-Bugs/

as it stands, there's a chance some of your other code is interfering, and also, i'll be able to verify much more easily that any type of fix is working if I have a JSBin.

**Comment by arshaw** [comment]
to get started follow "FullCalendar Standard" > "JSON feed template"

**Comment by alexhampu** [comment]
I can't paste the code on JSBin, because I can't access the JSON data from there (Control-Allow-Origin error). I have isolated the code and uploaded it here: http://hampu.net/_sandbox/tnb/ The problem still exists on Chrome (October 5th, 12, 26). I've checked the JSON too for ordering error, but the order there is good.

**Comment by arshaw** [comment]
Thanks @alexhampu but can I bother you to go a step further. It is actually possible to simulate the JSON feed... the "JSON feed template" I linked to above has instructions on how to do it. You'll have to copy and paste the JSON data received from your network tab into JSBin.

This is important for me because it allows me to debug the Javascript without having access to the static asset files on your server.

**Comment by alexhampu** [comment]
http://output.jsbin.com/fowiyuxodu/1.js

**Comment by arshaw** [comment]
thank you! but can you link this json feed up to the calendar initialization code, which you also host on jsbin? the i really appreciate it. i'm hoping for a runninable jsbin demo that i can open up and see the bug immediately.

**Comment by alexhampu** [comment]
http://jsbin.com/detecuyiqo/edit?html,output

On Fri, Nov 13, 2015 at 8:22 PM, Adam Shaw <notifications@github.com> wrote:

> thank you! but can you link this json feed up to the calendar
> initialization code, which you also host on jsbin? the i really appreciate
> it. i'm hoping for a runninable jsbin demo that i can open up and see the
> bug immediately.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/fullcalendar/fullcalendar/issues/2933#issuecomment-156508230>
> .
>



-- 
Alex Hampu, Web developer
www.cheapyway.ro <http://cheapyway.ro>
Phone number: +4 074 582 2899

**Comment by arshaw** [comment]
in that example, could you strip out http://tnb.ro/js/fullcalendar/intro.js in favor of an official distributed JS file from https://cdnjs.com/libraries/fullcalendar ? as it stands its hard to tell what version you are using (it looks custom built by you).

**Comment by alexhampu** [comment]
It's using v1, not 2. If I replace it with v2, it's not working at all.

**Comment by alexhampu** [comment]
I will try to update the plugin to the version 2, tomorrow. I hope it works, if not, I will come with a reply here. Fingers crossed :D

**Comment by alexhampu** [comment]
Hi again,
The problem was with v1, I finally managed to update to v2 after 2 days of annoying problems with the source code of the website. I don't get that problem anymore, but still there are lots of other problems from the migration.

Thank you for your support and for your plugin. Have a great day!
