### ISSUE TITLE
eventClick triggering on resize of event to the same size

### ISSUE THREAD

**Issue by vuoriliikaluoma** [fullcalendar/fullcalendar#2934]
When you start resizing a event and then return it to it's original size `eventClick` is triggered.
I think `eventResize` should trigger in this case since the user was trying to resize the event.

---

We have `eventClick` bound to a modal asking if you want to delete the event, so It's a bit awkward.

Any suggestions on workarounds in the current version? (2.4.0)

**Comment by arshaw** [comment]
I agree, an `eventClick` event should not fire in this case.

JSBin: http://jsbin.com/vanisihihi/edit?js,output

I like `eventResize`'s current behavior of only firing on an actual value change, but if you want to know about a resize unconditionally, [eventResizeStop](http://fullcalendar.io/docs/event_ui/eventResizeStop/) is for you.

**Comment by rossnorvell** [comment]
Any chance this has a workout around that can be used in the meantime?

**Comment by arshaw** [comment]
no longer an issue. see: https://codepen.io/arshaw/pen/MWKowzx?editors=0010
