### ISSUE TITLE
events storage

### ISSUE THREAD

**Issue by ambicoder** [fullcalendar/fullcalendar#2935]
I read in the docs that FC stores the event in local cache....from where I can actually verify this?

Using chrome dev tools for example,I do not see any events listed in session or local storage.

I am talking about the events here http://fullcalendar.io/

**Comment by espen** [comment]
It's just a variable, not stored in local storage. So events are not persisted locally. See http://fullcalendar.io/docs/event_data/clientEvents/

**Comment by arshaw** [comment]
yup. doesn't persist across browser sessions. but stored within a JS variable.

**Comment by ambicoder** [comment]
thanks....

**Comment by ambicoder** [comment]
would it be much trouble if you could tell me which JS variable is this()...please....thanks in advance.

Setting breakpoints and studying the call stack in so many lines of code is not the easiest thing to do.

**Comment by arshaw** [comment]
https://github.com/fullcalendar/fullcalendar/blob/master/src/EventManager.js#L102-L105

**Comment by ambicoder** [comment]
thanks
