### ISSUE TITLE
click on today button doesn't bubble-up mouse event

### ISSUE THREAD

**Issue by zhangsanshi** [fullcalendar/fullcalendar#2939]
this  is  a  demo.
http://plnkr.co/edit/ZYh6EINRbgSfc4c6tRlK?p=preview
I addListener prev, next and today , but  today  never work.
I found  the code  at 
https://github.com/fullcalendar/fullcalendar/blob/master/dist/fullcalendar.js#L9234
look like  disabled button before the event  work

**Comment by arshaw** [comment]
If the today button is NOT already disabled at the moment when the user clicks the today button, then this should be considered a legit bug. a `setTimeout` will probably solve it

**Comment by KinkiWu** [comment]
@arshaw Where sholud i add the setTimeout function to solve the today button not trigger event issue.
now my code as following:
`element.find('.fc-today-button').click(function(){
                console.info("today");
                var view = element.fullCalendar('getView');
                scope.trigger({start:view.start._d.getFullYear(),end:view.end._d.getFullYear()});
            });`

**Comment by arshaw** [comment]
nevermind, setTimeout probably won't work. the button is being disabled before the event is able to bubble up to the document, so event delegation probably won't work. i'd try doing what you're doing in that last snipped you posted.. attaching the handler directly to the element (probably via viewRender). tho i can't guarantee it will work

**Comment by surinderrawat1987** [comment]
@arshaw Any update on this ?

**Comment by arshaw** [comment]
fixed in v5: https://codepen.io/arshaw/pen/vYLZOMZ?editable=true&editors=001
