### ISSUE TITLE
Incorrect RTL in event title 

### ISSUE THREAD

**Issue by jsuares** [fullcalendar/fullcalendar#2940]
In RTL mode, when using Hebrew/Arabic characters in the title of an event, the order is flipped so that the time is on the left and the title text is on the right:
08:00 XXXXXXXX
This is not correct. When using an English title, everything works and the title is displayed correctly:
XXXXXXXXX 08:00
This problem did not occur in the 1.6 version but does in the latest 2 version.

See: https://jsfiddle.net/jsuares/sxnm15yz/5/  for example of correct and incorrect title on Fri 13.

**Comment by arshaw** [comment]
the `direction:rtl` should be changed to be on the top-level calendar element. thanks

**Comment by jsuares** [comment]
This does not solve the issue. You can solve it by adding the following:

eventRender: function(event, element) {
	element.find(".fc-title").remove();
	element.find(".fc-time").remove();
	var new_description =   '<div dir=rtl>'+
	moment(event.start).format("HH:mm") +' '+ event.title +'</div>'
	element.append(new_description);
}

**Comment by arshaw** [comment]
this should no longer be an issue with v4/v5 because they use the built-in Intl API
