### ISSUE TITLE
Option to display week number in day cell

### ISSUE THREAD

**Issue by peternowee** [fullcalendar/fullcalendar#2941]
This is a feature request/discussion starter for an option for FullCalendar (basicDay, basicWeek and month views) to display the week number in an existing first column, such as in the top left of the first day of the week, similar to this image from OS X's calendar app:

![Image from OS X's calendar app, from https://github.com/owncloud/calendar/issues/157#issuecomment-25627615](https://camo.githubusercontent.com/e307344f60d02209e2dd717197c8ad2cd560358f/68747470733a2f2f662e636c6f75642e6769746875622e636f6d2f6173736574732f313235303534302f313236323231362f31303033643130302d326333632d313165332d386461632d3134366135383530323665612e706e67)

This feature would benefit users of the downstream ownCloud calendar app. The current display of week numbers in a separate column is not acceptable for @jancborchardt (ownCloud design lead) and @georgehrke (ownCloud software engineer), and therefore any implementation of week numbers in ownCloud is currently blocked. See owncloud/calendar#929.

I suggest a new option `basicViewWeekNrPosition`, with (for now) two possible values:

* `weekNrSeparateColumnLeft` (default): Display week numbers in a separate column on the left. This is the current behavior, and therefore should remain default.
* `weekNrExistingFirstColumn`: Display week numbers in an existing first column. In case of month and basicWeek views, week number(s) will be in the top left of the cell(s) of the first day(s) of the week. In case of basicDay view, the week number will be in the top left of the day shown.

The option should not have any effect on the agendaDay and agendaWeek views, which currently show the week number in the column of the time slots, meaning it is not taking up any extra room.

I am willing to do more, though I must say my time is limited. This is just a ticket for discussing the feature's specs before coding, as requested in the [guidelines for contributing](https://github.com/fullcalendar/fullcalendar/blob/master/CONTRIBUTING.md#contributing-features).

Hope to hear from you soon.

**Comment by arshaw** [comment]
I really appreciate the thorough feature request. I wish there was more time, but this doesn't quite stack up against many of the other bugfixes/feature-requests in terms of priority, so doing work to reach an agreement and implement and eventually merge will likely take a while. If I were you, I'd take full ownership on your end to get it good-enough for your specific project, and then we can take it from there.

**Comment by peternowee** [comment]
Ok, I will give it a try and let you know once I have a working version. Perhaps you can assign this issue to me?

**Comment by peternowee** [comment]
Oh, sorry, I see that that would mean you would first have to add me as collaborator. No need for that.

**Comment by jancborchardt** [comment]
@peternowee great to hear you’re working on it! If it looks similar to the proposal above we will definitely add that to ownCloud. Thanks a lot!

**Comment by peternowee** [comment]
Ok, I ran into something. Hope to hear your thoughts before I continue.

### Problem
The use of the `firstDay` option in combination with `weekNumberCalculation: iso` or a custom function, may cause a *displayed* week row to contain days of two different week numbers.

For example, in fullcalendar/fullcalendar#2458 a user combines ISO 8601 (which defines Monday as the first day of the week) with Sunday-Saturday week display.

For such cases, it would make more sense to display the week number in the top left of the cell in which the week actually changes (in the above example, Monday).

### Proposed change to my earlier proposal
I propose to replace my earlier proposed option `weekNrExistingFirstColumn` with:
- `weekNrDayCell`: Display week number in a day cell. In case of month and basicWeek views, week numbers will be in the top left of the cells of the first day of the week **according to the calculation method**. In case of basicDay view, the week number will be in the top left of the day shown, regardless of the day of the week.

Of course, in most normal use cases the displayed week range matches the week range of the calculation method and the week number will still end up in the first column.

### Implementation
To implement the above, I need a variable that contains the first day of the week according to the week number *calculation*, not the week *display*.

I considered using `localeData._week.dow`, but that is already set to `firstDay` option and used in determining the display range.

I therefore propose to create a new variable `localeData._fullCalendar_weekCalcFirstDoW`, to be set in `Calendar.js` to a value based on `localeData._fullCalendar_weekCalc` and `localeData._week.dow`:
  - With `ISO`: Always 1 (Monday). Is not influenced by the `firstDay` option.
  - With custom function: Test a sequence of 7 days with the custom function to determine on which day of the week the week number changes. Is not influenced by the `firstDay` option.
  - With `local`: Set to the value of `localeData._week.dow`, which will contain the value of `firstDay`, or else will return the `dow` value from a protype, such as the locale or moment's Locale object default 0 (Sunday).

An alternative would be to create separate options for the first day of the week *display* and the week *calculation*, but I think that would affect many parts of the code and require much more effort.

Please let me know your thoughts.

**Comment by peternowee** [comment]
@arshaw I did not hear from you, so I will start coding according to my proposal. Feel free to comment later on.

**Comment by arshaw** [comment]
sounds good. when i have time i will try to fully understand what's going on here

**Comment by peternowee** [comment]
Ok, thanks.

**Comment by peternowee** [comment]
Continued in fullcalendar/fullcalendar#3024.
