### ISSUE TITLE
Event resizing (isResizableFromStart && isResizableFromEnd)

### ISSUE THREAD

**Issue by MartijnWelker** [fullcalendar/fullcalendar#2942]
Hello,

I noticed strange behaviour in the event resize handling (line 5287 version 2.4.0)

    var isResizableFromStart = !disableResizing && event.allDay && seg.isStart && view.isEventResizableFromStart(event);

It sets the variable isResizableFromStart but one of the called functions returns undefined:

    view.isEventResizableFromStart(event) 

calls 

    this.opt('eventResizableFromStart') 

which is undefined. 

event.allDay is also called, but shouldn't this be !event.allDay? (if event.allDay is not set it makes it impossible to resize the event)

Thanks for your time and the great plugin !

**Comment by arshaw** [comment]
the result of that function may be undefined, but it is treated as false, which is as designed. views that want to enable this functionality need to override what the default is for that value (timeline view does this).

You would probably be interested in the discussion on #2441 about what to do from a user-experience

**Comment by TejasCMehta** [comment]
@arshaw `eventResizableFromStart ` do we have any working demo, I havent seen any thing working from dragged from start.

https://github.com/fullcalendar/fullcalendar-angular/issues/273
