### ISSUE TITLE
Noticeable delay 

### ISSUE THREAD

**Issue by jbeja** [fullcalendar/fullcalendar#2943]
There is a noticeable delay when clicking the header's buttons and changing through views.

**Comment by arshaw** [comment]
can you give specs on your computer... os, browser, browser version, fullcalendar version...

**Comment by arshaw** [comment]
type/speed of cpu

**Comment by jbeja** [comment]
Here:

```
Intel Celeron 1000M
1.8GHZ
2RAM
Windows 7, Firefox latest
```

**Comment by arshaw** [comment]
your concerns will be addressed when progress is made on the following two:
https://github.com/fullcalendar/fullcalendar/issues/2524
https://github.com/fullcalendar/fullcalendar/issues/2938
&uarr;
Please visit the link, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates.
