### ISSUE TITLE
On click of time slot wrong time selected

### ISSUE THREAD

**Issue by dhara15101991** [fullcalendar/fullcalendar#2945]
In week view when click in between 5pm to 6pm(Date:21-11-2015) timeslot, it gives perfect time slot timing with 21-11-2015 5:00pm to 6:00pm.But when i click on 7pm to 8pm(Date:21-11-2015) timeslot it gives me wrong time with 22-11-2015 7:00pm to 8:00pm.

I don't know how date change to next day. Actual date must be 21-11-2015 7:00pm to 8:00pm.

My timezone is Asia/Kolkata (GMT+05:30).

**Comment by arshaw** [comment]
almost definitely related to #2396 . hoping to get a fix out soon

**Comment by dhara15101991** [comment]
Please refer this link

http://stackoverflow.com/questions/33772961/full-calendar-on-click-of-time-slot-wrong-time-selected

**Comment by arshaw** [comment]
what type/version of browser/OS are you using? important for me to recreate

**Comment by arshaw** [comment]
also, are you using the `timezone` setting? would be very helpful to get a jsbin online demo, as it might have something to do with your configuration settings. http://fullcalendar.io/wiki/Reporting-Bugs/

**Comment by arshaw** [comment]
This is what it looks for me when I change my computer's timezone to Calcutta, on Mac OSX Yosemite, Safari 8, `timezone: "local"`. Works for me.

<img width="604" alt="screen shot 2015-11-22 at 1 26 11 am" src="https://cloud.githubusercontent.com/assets/56520/11320236/0fa2ba0e-90b8-11e5-92b4-e97ae8731c78.png">

**Comment by dhara15101991** [comment]
i am using OS ubuntu 12.04 LTS. Browser mozila filrefox 37.0. And yes i have set timezone setting.
in my system Asia/Kolkata timezone selected. in my project timezone is UTC. in fullcalendar setting

`ignoreTimezone: false, 
timezone:'Asia/Kolkata',`

Which calculation i have done works in mozila,crome and safari also.
i have set timezone still it gives me `Sat Nov 21 2015 19:00:00 GMT+0000`. so i have to calculate timezone.

**Comment by arshaw** [comment]
this has been fixed in a beta release. please try it out!
https://github.com/fullcalendar/fullcalendar/releases/tag/v2.5.0-beta2

@dhara15101991 looks like you are using fullcalendar v1, which is no longer supported. to get this fix, you'll have to upgrade to v2

**Comment by dhara15101991** [comment]
Hi @arshaw. Thanks for your kind efforts.  i have used beta release but still i have same issue.
![fullcalendernew2 5 0](https://cloud.githubusercontent.com/assets/14217908/11358821/2f395a68-929c-11e5-851c-81f136cc32de.png)

You can see here. when i clicked on 10 pm to 11 pm. it gives me `Sat Feb 14 2015 22:00:00 GMT+0000`. and in console when i set `console.log(date)` it gives me whole moment object. in which you can see `_d Date {Sun Feb 15 2015 03:30:00 GMT+0530 (IST)}`.

Note: i have added property 
`ignoreTimezone: false, 
timezone:'Asia/Kolkata',`

**Comment by arshaw** [comment]
@dhara15101991 `ignoreTimezone` is no longer an option in v2. you are setting `timezone`, which is a good option, however, when you set it to a TZ string like that, all the moments internally in the api are "ambiguously-zoned" as mentioned in the final option on this article: http://fullcalendar.io/docs/timezone/timezone/

then you are logging the date, it is showing in your local time. you should disregard what it displays in this case. the date's zone is 00:00 (UTC) and it only makes sense when displayed in this zone

**Comment by arshaw** [comment]
when receiving the date via `dayClick`, which is a moment, i would use the moment's `.format()` method, which will correctly omit the timezone indicator.
