### ISSUE TITLE
Vue.js and Fullcalendar

### ISSUE THREAD

**Issue by Smeaven** [fullcalendar/fullcalendar#2948]
My javascript file (using Vue.js and Webpack)
```javascript
module.exports = {
    ready: function () {
        $('#fullcalendar').fullCalendar({
            // put your options and callbacks here
        });
    }
}
$(function () {
    new Vue(module.exports).$mount('#calendar');
});
```
My markup:
```html
<div id="calendar">
	<div id="fullcalendar"></div>
</div>
```
I included all dependecies (moment.js and jquery.js), but fullcalender does not render anything. there are also no warnings and errors thrown in my dev tools console.

**Comment by arshaw** [comment]
this is related to your setup, not related to fullcalendar. the only bugs that are solved on this issue tracker are ones that are reproducible: http://fullcalendar.io/wiki/Reporting-Bugs/
