### ISSUE TITLE
Show location (where) of Google Calendar events

### ISSUE THREAD

**Issue by tjorim** [fullcalendar/fullcalendar#2949]
It could be useful to show the location of events (added via the Google Calendar plugin).
This would be the 'Where' as it's show in Google Calendar itself.

When viewing the events using a Google Calendar, no location is shown, to view this info you need to click it which redirects you to the detailed event info.
When using an <iframe> as Google suggests it isn't shown either, however, clicking it brings up an pop-up. I wouldn't go for this approach because it's not handy on mobile devices,
I would rather think of an extra setting (with a default to show) in the FullCalendar initialization code.

**Comment by arshaw** [comment]
The location should be available in the Event Object, which you can then use in the `eventRender` callback to do any arbitrary rendering
