### ISSUE TITLE
Previous and Next event handlers

### ISSUE THREAD

**Issue by VigneshVaidyanathan** [fullcalendar/fullcalendar#2950]
I am trying to handle a condition when the user clicks the Next or Previous buttons in the AgendaDay view. I want to save the data the user has added in that day and then load the data for the next/previous day from the database.

While using the button click event handler and then next method in the Calendar, the next function is getting called twice. One for the default behavior and then once for the next method I call in the custom code. The default next function is called before the custom handler gets executed so I am not able to get the events because I have already set new events from the database.

Can you help me to either suppress the default behavior of the next/previous method or the event handler to specify explicitly what should happen during the event?

thanks
vignesh

**Comment by arshaw** [comment]
http://fullcalendar.io/support/
"Getting Help"

**Comment by ahmedali5530** [comment]
is there any callback for next/previous buttons?
