### ISSUE TITLE
Some strings are translated and some are not

### ISSUE THREAD

**Issue by simPod** [fullcalendar/fullcalendar#2951]
I'm using czech locale using cs.js. However, some strings are not translated. What could be the cause of this issue? Thanks
<img width="780" alt="screen shot 2015-11-27 at 15 11 24" src="https://cloud.githubusercontent.com/assets/327717/11442885/355ca498-9519-11e5-8cef-86c70680095b.png">

**Comment by arshaw** [comment]
Hmm, when I visit http://fullcalendar.io/js/fullcalendar-2.4.0/demos/languages.html and change language to `cs` it works fine: 

![screen shot 2015-11-27 at 1 05 13 pm](https://cloud.githubusercontent.com/assets/56520/11448161/8728e226-9507-11e5-94ff-2bb11fa2ef06.png)

Could you post a recreation?
http://fullcalendar.io/wiki/Reporting-Bugs/

**Comment by simPod** [comment]
Ok my bad. Thanks. Had buttonText attribute set
