### ISSUE TITLE
Distributing the Core of Fullcalendar

### ISSUE THREAD

**Issue by omidkh68** [fullcalendar/fullcalendar#2953]
Hi,
Thank you for your complete and useful calendar plugin. We have searched a lot for a complete calendar and yours was the best.
I wanted to know if the support of Jalali calendar will be possible and how that can be done. 
We have read all the issues and it seems that someone has added Jalali calendar with changing the core, which is not useful for us because it can't be updated anymore and won't work properly. 
Issue number: #1813
Is it possible to add Jalali calendar without making changes in the Core, for example adding a layer? If this is possible, could you please give us some guidance on how to do it. We are a team of developers and are able to add a layer if you give us some guidance. We would be grateful if you could help us.

**Comment by arshaw** [comment]
you will likely want to make a [Custom View](http://fullcalendar.io/docs/views/Custom_Views/) ("Coding From Scratch") along with using the jalali plugin for momentjs.

can you please resume all discussion on ticket #1813 ?

**Comment by ehsandanesh** [comment]
Hi omidkh68 I added Jalaali calendar to version 2.6.0 and solved previous issues in this update you can find it from here:
https://github.com/ehsandanesh/fullcalendar
