### ISSUE TITLE
Drag event to next month

### ISSUE THREAD

**Issue by davilera** [fullcalendar/fullcalendar#2957]
I created a FullCalendar instance and made the events draggable. Then, I created an HTML div area for switching from one month to the other (using `$calendar.fullCallendar( 'next|prev' )`). When I drag an event to that area, I set a timeout that calls said function, so that I can move events from one month to the other by just hovering a certain area in my page.

The solution I described works, but it has some issues:

1. When hovering the "next/previous month" area, I have to wait for fullCalendar to actually change the month (that's normal; I'm using an interval function). When the interval executes `$calendar.fullCallendar( 'next|prev' )`, fullCalendar shows the next month, but the event I was dragging "disappears".
2. After 1, if I move the mouse back over the calendar, the event reappears, but it does no longer follow the mouse. It simply appears in the specific day I'm hovering.

Is it possible to "easily" extend fullCalendar to permit this feature? I think it'd make things much easier to all users.

**Comment by arshaw** [comment]
same feature request as #2542 i believe

**Comment by curbsaleem** [comment]
+1

I have the same requirement. During drag of event in month view, i have to change the month of calendar to Next|Prev based upon location. Is there any way to do that.
