### ISSUE TITLE
Month view - Different heights for different events.

### ISSUE THREAD

**Issue by davilera** [fullcalendar/fullcalendar#2958]
When using the Month view, all events have the exact same height. I'd like some of them to be bigger than the others.

I inspected the generated HTML and I realized you use tables and rows for displaying events, which explains why all of them have the same height.

One possible solution would be to define the size of an event in terms of how many rows it takes:

```
var e1 = { id : 1, title : 'Normal event', date : 'monday' };
var e2 = { id : 2, title : 'Another example', monthSize : 1, date : 'monday' };
var e3 = { id : 3, title : 'Big event', monthSize : 2, date : 'tuesday' };
var e4 = { id : 4, title : 'Biggest event', monthSize : 3, date : 'wednesday' };
```

Which would look similar to this:

```
+----+----+----+----+----+----+----+
| S  | M  | T  | W  | T  | F  | S  |
+----+----+----+----+----+----+----+
|    | e1 | e3 | e4 |    |    |    |
|    |----| .  | .  |    |    |    |
|    | e2 |    |    |    |    |    |
|    |----|----| .  |    |    |    |
|    |    |    |    |    |    |    |
|    |    |    |----|    |    |    |
+----+----+----+----+----+----+----+
```

I tried to simulate that behavior as follows:

* I added "fake" events with a special type "fake" after the original events.

```
+----+----+----+----+----+----+----+
| S  | M  | T  | W  | T  | F  | S  |
+----+----+----+----+----+----+----+
|    | e1 | e3 | e4 |    |    |    |
|    |----| .  | .  |    |    |    |
|    | e2 | f3 | f4 |    |    |    |
|    |----|----| .  |    |    |    |
|    |    |    | f4 |    |    |    |
|    |    |    |----|    |    |    |
+----+----+----+----+----+----+----+
```

* Then, using jQuery in `eventAfterAllRender`, I removed the `td` containing the fake events and added `rowspan`s to the original ones.
* Finally, I added a CSS rule to the original, bigger events, so that they fill their `td` container (the one with the newly added `rowspan`s.

Unfortunately, this solution doesn't work completely. When I move events around, things get messy...

**Comment by davilera** [comment]
I fixed my workaround. Let's assume I want to create one big event, this is what I do:

```
events = [
   { 'id' : 1, title : 'Big Event', start : '2015-02-01T15:04:00', type : 'real' },
   { 'id' : 1, title : 'Big Event', start : '2015-02-01T15:04:00', type : 'fake' },
   { 'id' : 1, title : 'Big Event', start : '2015-02-01T15:04:00', type : 'fake' }
];
```

As you can see, there's only one event (`id=1`). Only the first one is _"real"_. The other two are _"fake"_, and I use them so that I can expand the first one.

During `eventRender`:

```
eventRender: function( event, element ) {
   if ( event.mode === 'real' ) {
      element.addClass( 'real' );
      element.data( 'event-id', event.id );
   }
   if ( event.mode === 'fake' ) {
      element.addClass( 'fake-' + event.id );
   }
},
```

Finally, once the calendar has been rendered, I simply need to fix the `rowspan` properties:

```
eventAfterAllRender: function( view ) {
   jQuery( '.fc-event.real' ).each( function() {
      var eventId = jQuery( this ).data( 'event-id' );
      var $realTd = jQuery( this ).parent();
      var rowspan = 1;
      jQuery( '.fc-event.extension-' + eventId ).parent().each( function() {
         var rs = jQuery( this ).attr( 'rowspan' );
         if ( typeof rs === 'undefined' ) {
            rs = 1;
         }
         rowspan += rs;
         jQuery( this ).remove();
      });
      $realTd.attr( 'rowspan', rowspan );
   });
},
```

To make this work, you have to make sure that fake events appear after real events... therefore, I also implemented a custom `eventOrder` function:

```
eventOrder: function( a, b ) {
   if ( a.type === b.type ) {
      return a.id - b.id;
   } else if ( a.type === 'real' ) {
      return -1;
   } else if ( b.type === 'real' ) {
      return 1;
   } else {
      return 0;
   }
}
```

And this basically does the trick!

**Comment by davilera** [comment]
Oops! Click on _Close_ inadvertently. I'm reopening the issue, just in case you want to work on it.

**Comment by arshaw** [comment]
please see the discussion on #2853. please resume discussion there. this behavior change is being considered.

i plan to change the way event element layout/positioning works in the future to make this more flexible
