### ISSUE TITLE
Disabling past dates navigation

### ISSUE THREAD

**Issue by ambicoder** [fullcalendar/fullcalendar#2960]
Currently the user can navigate to previous and next months(I am always talking here about month view) using the arrow buttons.

I want to throw away the ability of navigating to past months(in relation to the current date).
The user must be able to navigate only to future months and of course back to the current date.

In the docs I did not see any feature that might help me in that.
Having said that...it seems the only option is to hack the source code.

I want to hear what you think about it.

**Comment by ambicoder** [comment]
I found it...

**Comment by arkuuu** [comment]
@ambicoder could you please tell me how you solved it?

**Comment by arkuuu** [comment]
in case anyone may have the same question in future, this was the solution I found:

Use the `viewRender` callback

```javascript
viewRender: function (view) {                                        
                                                                     
    var minDate = $.fullCalendar.moment('2016-10-01');               
    // view.end seems to be +1 day than the displayed, hence the "<="
    if (view.end <= minDate) {                                       
        $('#calendar').fullCalendar('gotoDate', minDate);            
    }                                                                
                                                                     
    var maxDate = $.fullCalendar.moment('2016-12-31');               
    if (view.start > maxDate) {                                      
        $('#calendar').fullCalendar('gotoDate', maxDate);            
    }                                                                
},                                                                                                                                        
```
