### ISSUE TITLE
Extra Space at bottom of Calendar

### ISSUE THREAD

**Issue by SajjadGit** [fullcalendar/fullcalendar#2961]
can anyone help me what to do inorder to remove the extra space(<td>).

![screenshot-localhost 2015-12-07 10-33-57 1](https://cloud.githubusercontent.com/assets/15094809/11621546/6a053ce8-9cce-11e5-9832-730880779590.png)

**Comment by arshaw** [comment]
if you set [height](http://fullcalendar.io/docs/display/height/) or contentHeight to auto, it should remove

**Comment by ambicoder** [comment]
I am a similar problem with empty space in the right of the calendar...what to do?
[https://1drv.ms/u/s!AjCBrCpLQye-hRoNZM1dmvpfdhSl](url)

**Comment by ambicoder** [comment]
I have the same problem with empty space in the right of the calendar.....
[https://1drv.ms/u/s!AjCBrCpLQye-hRoNZM1dmvpfdhSl](url)

**Comment by ambicoder** [comment]
nevermind...I found the cause of it
