### ISSUE TITLE
Fullcalendar only work for drag and drop action in Fastclick with iOS9

### ISSUE THREAD

**Issue by gmunumel** [fullcalendar/fullcalendar#2962]
Hello guys.

When I use fastclick and fullcalendar in IOS9 the tap action is not working. Only works if I simulated a drag&drop action. I was using dayClick listener on fullcalendar (http://fullcalendar.io/docs/mouse/dayClick/).

If I don't use Fastclick everything is working as expected. Is there is a way to bypass fastclick or maybe try another workaround?  

I'm using: Fastclick 1.0 and FullCalendar 2.5.0.

**Comment by arshaw** [comment]
i'm not sure what fastclick is doing internally. could you consult that project's forum or docs to see if its possible to disable on a per-element basis.

FYI, `dayClick` needs a real `mousedown`/`mouseup` to fire correctly. this will change with issue #994
