### ISSUE TITLE
header...problem with tilte

### ISSUE THREAD

**Issue by ambicoder** [fullcalendar/fullcalendar#2963]
My problem is with the header....In the site http://fullcalendar.io/ you will see that when in  month view....only the name of the current month is shown.

In my case the current month is shown followed by a dash and the next month....
How can I prevent this?
I cannot find what in my code(the options passed on calendar initialization) causes the above thing.

**Comment by arshaw** [comment]
this is probably a stackoverflow-worthy issue, but in case this is a real bug, can you make a JSBin to show a recreation? http://fullcalendar.io/wiki/Reporting-Bugs/
