### ISSUE TITLE
Add .fc-other-month to TDs in tbody for corresponding TDs in thead

### ISSUE THREAD

**Issue by Fisiu** [fullcalendar/fullcalendar#2964]
When I use basic month view, sometimes days from other (past and next) month are also visible.
For those days, day number is greyed out (in default theme) and `<td>` in `<thead>` contains `.fc-other-month`. Could You add the same class to correspongind `<td>` in `<tbody>`?

Or maybe there is another way to adjust css for events, that belong to other month?

**Comment by arshaw** [comment]
fc-other-month is also on the td in the tbody. see screenshot...
<img width="676" alt="screen shot 2015-12-08 at 7 32 37 pm" src="https://cloud.githubusercontent.com/assets/56520/11675905/7d4a6c8c-9de2-11e5-8977-f6a2084c02d2.png">
