### ISSUE TITLE
Events not displayed when setting "firstDay: 1"

### ISSUE THREAD

**Issue by cknieling** [fullcalendar/fullcalendar#2968]
Dear all,

I've trouble some trouble with the current (also with 2.4.0 and probably before) fc release. You can review my settings under the URL http://jsbin.com/gaguwibova/edit?js,output
But I have to state that somehow on jsbin the error is NOT reproducable. So initially I'll explain how to reproduce the faulty rendering of event.

0. download the current fullcalendar release fullcalendar-2.5.0.zip
1. unzip fullcalendar-2.5.0.zip somewhere under htdocs
2. replace <fc-root>/demos/json/events.json with this
[
  {
    "title": "Test",
    "start": "2015-06-01",
    "end": "2015-06-01"
  }
]
3. call <fc-root>/demos/json.html in your browser and assure that the event will be shown correctly in the view "May 2015" and also in "June 2015"
4. edit file <fc-root>/demos/json.html and set the option "firstDay" with the value "1" by inserting the line "firstDay: 1,", for example right before the "header: {" line.
5. hit F5 in your browser for a refresh and go 'back in time' to view "May 2015" and "June 2015". You'll see the event will be renderer only in the "May 2015" view and NOT in "June 2015". Bazinga.

You can also try an event on February 1st in 2016. The same problem will occur. But setting firstDay to 1 is crucial here, any other value doesn't reveal this behavior (for those months at least).

**Comment by cknieling** [comment]
I recently tested an event for "December 1st, 2015" and setting "firstDay: 2", then the same behavior will occur, i.e. missing the event in "December 2015" view, but shown in "November 2015" view.
Also I'm remembering that I have seen something similiar before. It was a missing event from the month before, but this I graded not as harmful as a missing event in the current month view.

**Comment by arshaw** [comment]
I've attempted to recreate your problem with the latest version of FC and with the JSON feed template from the [Reduced Test Cases](http://fullcalendar.io/wiki/Reduced-Test-Cases/) page.

http://jsbin.com/jafiyojafe/edit?js,output

Can't reproduce. Could you try again with the latest version of FC?

The fact that this can only be reproduced in your environment indicates that a wonky caching setup on your local server or whatever ((`htdocs`?) might be responsible.
