### ISSUE TITLE
refetchEvents

### ISSUE THREAD

**Issue by tiwessel** [fullcalendar/fullcalendar#2970]
Hi, after .fullCalendar( 'refetchEvents' ) scroll the window to top!
can i stop this?

**Comment by arshaw** [comment]
Can you try to make a demoable recreation with JSBin?
http://fullcalendar.io/wiki/Reporting-Bugs/

Would be great if you could force the initial scroll of the document to be further down. then have a button that triggers the refetchEvents call. this should demo the bug
