### ISSUE TITLE
problem with the google calendar integration

### ISSUE THREAD

**Issue by jmaparisi** [fullcalendar/fullcalendar#2972]
Hi,

I need to integrate google calendar with fullcalendar.
I have read an try lot of guides that requires to get the api's keys but doesn't work. I have tried with different accounts.
I try codes that are for getting the events of a google calendar to later integrate the events on fullcalendar, but this doesn't work neither.

I am so stucked and need some functional code if anybody have this working.
I have follow step by stem fullcalendar.io guide for fullcalendar. I get the keys, the calendar on public mode but does not work.

Please, someone share a functional code.

Thanks!

**Comment by arshaw** [comment]
Since this is an issue tracker, not a support forum, could you try [Getting Help](http://fullcalendar.io/support/) ?

Posting a JSBin of what you have will be invaluable in diagnosing your problem.
