### ISSUE TITLE
eventAfterRenderPopover and eventAfterAllRenderPopover

### ISSUE THREAD

**Issue by danielemams** [fullcalendar/fullcalendar#2973]
Hi all,
i don't know if it is just possible,
but i have modified source code of fullcalendar to have two function handlers:
1) after each event is rendered in the "popover"
2) after all events are rendered in the "popover".

here code:
http://pastebin.com/mPdG607e

in line: 5691, after:

``` javascript
DayGrid.mixin({
```

put:

``` javascript
// Signals that all events have been rendered in Popover
triggerEventRenderPopover: function(seg) {
    var _this = this;

    jQuery(seg).each(function() {
        var seg = this;

        _this.view.trigger('eventAfterRenderPopover', seg.event, seg.event, seg.el);
    });

    _this.view.trigger('eventAfterAllRenderPopover');
},
```

and here:

``` javascript
// Reveals the popover that displays all events within a cell
showSegPopover: function(row, col, moreLink, segs) {
```

put at the end of the function:

``` javascript
this.segPopover = new Popover(options);
this.segPopover.show();
this.triggerEventRenderPopover(segs);
```

Now in your code you can use:

``` javascript
    $(document).ready(function() {
        $('#calendar').fullCalendar({
            events: [
                {
                    title: 'Conference',
                    start: '2015-12-11',
                    end: '2015-12-13'
                },
                {
                    title: 'Meeting',
                    start: '2015-12-12T10:30:00',
                    end: '2015-12-12T12:30:00'
                },
                {
                    title: 'Lunch',
                    start: '2015-12-12T12:00:00'
                },
                {
                    title: 'Meeting',
                    start: '2015-12-12T14:30:00'
                },
                {
                    title: 'Happy Hour',
                    start: '2015-12-12T17:30:00'
                },
                {
                    title: 'Dinner',
                    start: '2015-12-12T20:00:00'
                }
            ],
            eventLimit: true,
            eventAfterRender: function(event, element, view) {
                element.attr("title", "i_am_an_normal_event!");
            },
            eventAfterAllRender: function(view) {
                console.log("eventAfterAllRender");
            },
            eventAfterRenderPopover: function(event, element, view) {
                element.attr("title", "i_am_an_event_only_in_the_popover!");
            },
            eventAfterAllRenderPopover: function(view) {
                console.log("eventAfterAllRenderPopover");
            }
        });
    });
```

I hope this will help someone else.

Daniele.

**Comment by arshaw** [comment]
i'm having trouble understanding what the bug is. can you post a *runnable* demo (JSBin, [instructions](http://fullcalendar.io/wiki/Reporting-Bugs/)) and describe what i should look for?

**Comment by danielemams** [comment]
Hi arshaw.
It is not a bug!
It is an extension of the fullcalendar plugin.
With this extension in the source code you can link a function after every event is rendered in the Popover, and after all events are rendered in the Popover.
I'm a newbie in github, and I don't know where i can write this.
So i write it on a new "issues".

**Comment by danielemams** [comment]
i have just added a jsbin here: http://jsbin.com/heyafuquta/edit?html,js,output

**Comment by Braunson** [comment]
This is exactly what I'm looking for, being able to trigger an event when clicking the `+ 9 more` popover.

**Comment by Braunson** [comment]
Put @danielemams's code in a proper PR! Hoping to get this merged soon :+1:

**Comment by arshaw** [comment]
as of v5 (and similarly in v4), all events, even ones in the popover, are run through the [event render hooks](https://fullcalendar.io/docs/event-render-hooks)

If you want information from within one of those hooks about whether an event lives in the popover, you'd want an extra argument in one of those hooks (like `arg.isWithinPopover`). Please open another issue for that if you need it.
