### ISSUE TITLE
for custom buttons with icons, set text as the title attribute

### ISSUE THREAD

**Issue by jplevene** [fullcalendar/fullcalendar#2976]
Just to add a little extra help for the end user, a custom button, or maybe any button, set the tag title (hint context) to the text value.

For example a refresh button:

`customButtons: {
                    refreshBtn: {
                        themeIcon: "refresh",
                        text: "Refresh",
                        click: function() {
                            cal.fullCalendar( 'refetchEvents' );
                            }
                        }
                    }`

This will show the caption "Refresh" when the user hovers their mouse over the refresh button that only displays an icon to the user.

**Comment by arshaw** [comment]
Superseded by:
https://github.com/fullcalendar/fullcalendar/issues/6521
&uarr;
Could you please visit the link, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates?
