### ISSUE TITLE
Polymer support, shadow DOM

### ISSUE THREAD

**Issue by TimvdLippe** [fullcalendar/fullcalendar#2977]
We are using Polymer together with FullCalendar. We have succesfully imported FullCalendar with the polymer `style-modules`, but enabling shadow dom results in unexpected behaviour.

All styling is correct, however the height of the events are very small.

Actual result:
![image](https://cloud.githubusercontent.com/assets/5948271/11940905/f892947a-a82b-11e5-8515-7a80fe0a69f4.png)

Expected result:
![image](https://cloud.githubusercontent.com/assets/5948271/11940864/a40d0d90-a82b-11e5-8259-bd978a01a5cb.png)

Inspecting the events shows:
![image](https://cloud.githubusercontent.com/assets/5948271/11940931/1b7e0a82-a82c-11e5-8238-54dc44ef6ab6.png)

whereas an event rendered in non-shadow dom has values like
![image](https://cloud.githubusercontent.com/assets/5948271/11940947/3f5b9186-a82c-11e5-84d3-f776a8e806f6.png)

Therefore the top and bottom css properties of the events are incorrectly calculated under shadow dom.

**Comment by arshaw** [comment]
if the shadow DOM implementation does not have the same exact output as a normal DOM would, I consider this bug the fault of Polymer. Regardless, I realistically won't have time to debug this so some proactive investigation on your end might be helpful.

**Comment by TimvdLippe** [comment]
Thank you for your reply @arshaw ,

The Shadow dom is a [W3C working draft](http://www.w3.org/TR/shadow-dom/). Chrome has native support, whereas FireFox and Webkit are implementing this feature (see http://caniuse.com/#feat=shadowdom).

Polymer is a library that allows developers to utilize the features of the shadow dom, while maintaining compatibility with browsers that did not implement shadow dom (yet). If a browser does not support shadow dom, Polymer creates a so called shadydom. Shadydom is a polyfil of the shadow dom. The expected result screenshots are taken while using shadydom, the actual results are taken with enabling shadow dom in Chrome.

Therefore the shadydom implementation of Polymer is not the problem, as FullCalendar behaves as expected. However when using native shadow dom in Chrome, FullCalendar breaks.

I understand you are short on time and of course I want to help investigating (and maybe even solving) this issue. Therefore I would like to see this issue to be reopend to continue the investigation.

**Comment by TimvdLippe** [comment]
P.S. Initial googling of this issue and browsing the code of FullCalendar, I think this issue can be fixed by using jQuery 3.0.0. This is currently in alpha, but I will try to make this work locally later today. Ref https://github.com/jquery/jquery/issues/1784 as fixed in https://github.com/jquery/jquery/pull/2043

**Comment by arshaw** [comment]
thanks for the hard work!

**Comment by TimvdLippe** [comment]
Sadly the major version upgrade of jQuery is justified. Simply using jQuery-3.0.0-alpha1 breaks FullCalendar in various ways. I have to dig deeper to find what is going wrong.

The first error that occurred was performing `rangeStart.clone()` when fetching event sources.

**Comment by arshaw** [comment]
hmm, bizarre, especially since that line is only related to moment-js, not jquery

**Comment by TimvdLippe** [comment]
Yes that was boggling me too. I will have some time this weekend and will clone the project to run the tests. Hopefully the upgrade results in isolated failing tests that I could presumably fix.

**Comment by TimvdLippe** [comment]
All right, started investigating this issue. I have cloned the repository. Initially I was unable to install, due to #2901 . I submitted a PR for that in #3010 

Now when I run the tests with `grunt karma:headless` or `grunt karma:url`, 9 tests fail. I develop on Linux, so I am not sure if that is related to this.

Back to the actual issue: upgrading to jQuery 3.0.0. Running the automated test suite does not show any indication that a jQuery upgrade actually breaks anything. The same 9 tests fail. I need to manually dig deeper into why it fails in shadow dom.

**Comment by arshaw** [comment]
@TimvdLippe thanks for the hard work and all the PRs. i'll get them merged soon

**Comment by TimvdLippe** [comment]
@arshaw Friendly ping on the pull requests. I want to see them merged first before creating too many pull requests at once. (saves me wasted time :smile: )

**Comment by arshaw** [comment]
@TimvdLippe , you talking about #2901/ #3010 ? hoping to get to merging this into the next minor release

**Comment by TimvdLippe** [comment]
#3009, #3010, #3011 are the pull requests.

**Comment by arshaw** [comment]
@TimvdLippe is there anything else blocking you here? Is jquery-3 support blocking you? #3124 #3197

**Comment by TimvdLippe** [comment]
@arshaw yes jQuery 3 is a requirement. Thanks for the ping, I have been extremely busy with my study. This should be resolved soon so I can work on my other pull requests. I can take a look soon :)

**Comment by TimvdLippe** [comment]
I will soon be working on the application that uses FullCalendar and therefore also fix this issue. So it is on my radar, but we have to prioritize some other issues/features for that application first.

**Comment by TimvdLippe** [comment]
This is once again on my todo list, currently working on getting the application to production which includes shadow dom. Hopefully jQuery 3 fixed most of the issues.

**Comment by TimvdLippe** [comment]
Finally had the time to investigate this issue and happy to say: jQuery 3.0 fixed the shadow dom issues and therefore `fullCalendar` is working correctly in shadow dom :tada:
