### ISSUE TITLE
timezone handling 

### ISSUE THREAD

**Issue by lukasz-karolewski** [fullcalendar/fullcalendar#2981]
Hi I'd like to start off by saying how much i appreciate fullcalendar. It's very important component for and saves a bunch of us a lot of hassle.

For past couple of days I was working with fullcalendar. One of important features I wanted to use was timezones switching and I have some feedback around that I'd like to share to contribute to web community.

It just happens that I have 4+ years experience working on software internationalization  for one of major corps from mountain view and what struck me was the concept of `ambiguously-zoned` datetime and `timezone: false` option as there is no such thing as time without timezone... timezone is always there, it might be implied but it's always there. 

docs make a note that `Because the browser does not know the timezone offset for every time in every timezone, when an event is modified` but with moment.timezone it's not true, this information is available to you.

I seems to me that that concept had impact on design of callback signatures and make it a nightmare to work with. 

I ended up using timezone: 'local' option which behaves correctly, but i still have to fight with extended moment objects.

I'd like to open a discussion how we could improve this situation 

My proposal would be to 
- remove timezone: false option - docs make a case where one would want to render events irrespectively from timezone - just hardcode it to `utc` and result will be exactly the same. 
- make the timezone: 'local' the new default, utc would be equally good, depends which use case we want to promote (global user vs render my stuff same way for everybody)
- remove all moment.js extensions and use vanilla moment.js objects - this one makes coding unpredictable as modified object behaves differently and concept of `ambiguously-zoned` datetime is flawed and redundant.
- `start` and `end` fullcalendar callbacks params would be moment.js objects 
- do not pass timezone as separate param to event source callback - it's redundant

This would solve issues like #2780 

I'd like to get some feedback on my proposal and work out a consensus on conceptual level before we head out and start implementing stuff. 

Looking forward to hearing from you.

Regards and thanks again for your work !

**Comment by Jaicob** [comment]
I've been working with timezones in full calendar a good bit the last couple weeks and I think you bring up some good points here.

I'd like to contribute by pointing out that I am using `timezone: false` more so as if it were `timezone:manual` (Which may be the wrong way to think about it) This is because I will always know the correct timezone before my data gets to full calendar so I'd prefer to handle it myself. So for that reason I think it is a useful feature to keep around, but could use some reworking.

The biggest problem I've had with this though is what is experienced in #2780

**Comment by sylvainbx** [comment]
+100 to remove this concept of `ambiguously-zoned` moments, as there is no easy way to "zone" a moment.

**Comment by MartijnWelker** [comment]
+1

**Comment by arshaw** [comment]
Before disputing whether FullCalendar should use ambiguous dates to represent timezones, and before moving on to *any other points*, I would really like to understand why you feel the ambiguous-timezone extension, on the date utility level, is flawed. There are other date libraries in this world that have this same concept and I am unaware of any strife around them.

@kether667
"but i still have to fight with extended moment objects" - how are you fighting with them?
"makes coding unpredictable as modified object behaves differently" - why are they unpredictable?

@sylvainbx
"there is no easy way to "zone" a moment" - what about the `zone()` method? what do you mean?

**Comment by kether667** [comment]
i.e.: 

when event source is a function:
    loadEvents = function (start, end, timezone, callback) {
      // console.log(start.toISOString())
      // returns "2016-02-28" 
    } 

Problem is that if one mixes regular object and `ambiguously zoned` moment objects it's impossible to tell how code will behave without debugging (regular object will return time) 

So i'm fight that by converting `ambiguously zoned` moment objects to regular objects and it's just some boiler plate that should not be required 

That makes this component unnecessarily difficult to work with.

**Comment by MartijnWelker** [comment]
@lukasz-karolewski May I ask how you solved this? I'm still struggling with this. (I need normal moment objects, not the `ambiguously zoned` ones)

**Comment by arshaw** [comment]
@MartijnWelker, if your calendar has a `timezone` of `"UTC"`, you can convert like this: `start.utc()`

If your calendar has a `timezone` of `"local"`, you can convert like this: `start.local()`. But be aware that if the user is in a timezone that has DST over midnight, there's a chance they might get kicked back to the previous day, or get a time like `1:00`.

If you calendar has `timezone` of `false`, convert like this: `start.time(0)`

I'll contribute to the larger discussion soon...

**Comment by evanjmg** [comment]
+ 1 - Please send the timezone in dragging and dropping, sending different time data is wrong. Is there a really clean way to convert the time back using moment timezone? The moment docs don't go into detail enough on the subject.

**Comment by rafalyesware** [comment]
I second the comments everyone here has made, here are some examples where this makes a mess for users of FullCalendar:

1. I want to prevent users from creating events in the past... great, we have the `selectAllow` callback, I can compare the start/end times of the selection vs the current time (using `moment()` to build a new moment for that).  But oops, the `start` / `end` args of the `selectInfo` are ambiguously-zoned, so I need to make sure I create that timestamp using the FC-enhanced moment implementation and make sure I call `.stripZone` on it.

2. Ditto for moving an event -- when an even is first created, it appears to have standard moments for `start` / `end` dates, and in fact there's even this gem of a comment in the source:

```
/*
GENERAL NOTE on moments throughout the *entire rest* of the codebase:
All moments are assumed to be ambiguously-zoned unless otherwise noted,
with the NOTABLE EXCEOPTION of start/end dates that live on *Event Objects*.
Ambiguously-TIMED moments are assumed to be ambiguously-zoned by nature.
*/
```

But drag that event around, and somehow the `start` / `end` become ambiguously zoned.  Try and update the timezone of those events when you switch the calendar TZ and those events jump around like hot-cakes.

All of this is just one big hassle!

**Comment by arshaw** [comment]
written by @jessedvrs :

> @arshaw
> Just wondering: how is an allDay-event ambiguously timed? The time being 00:00 till 23:59 doesn't mean the time doesn't matter. It still does, since 00:00-23:59 in > timezone A is still different in timezone B. In my opinion, allDay events are only allDay events because they're timed 00:00-23:59 within the current timezone. Not > because they have an 'allDay'-flag.
> 
> Real world example:
> I am in Amsterdam. In an availability-calendar, I want to create an all day-event. So, what I'm actually saying, is: I am available on July 11th 2017 from 0:00:00 until > 23:59:59 (time in Amsterdam).
> Another person, living in London, wants to check my availability. On his screen, the website will show my availability as July 11th 2017 from 0:00:00 until 23:59:59 > too!!! This is incorrect. This should be from July 10th 2017 at 22:00:00 until July 11th 2017 at 21:59:59, because it should be converted to his timezone. From his eyes, > my event should not be visible in the allDay-bar, but as a timed event.
> 
> To fix this, we should get rid of the allDay flag entirely (when communicating with events). It's allDay when start is timed 00:00:00 and end is timed 23:59:50 (based on > times).

**Comment by arshaw** [comment]
I'm planning for v4 and made a proposal for overhauling the date system. Can you all take a look? Please make relevant comments on this thread.

[Wiki: Date System Revamp](https://github.com/fullcalendar/fullcalendar/wiki/Date-System-Revamp-Proposal)

**Comment by arshaw** [comment]
This issue has been addressed in the latest alpha release (4.0.0-alpha.2)
[See the blog post &raquo;](https://fullcalendar.io/blog/2018/10/release-v4-alpha2)

https://fullcalendar.io/docs/v4/release-notes#date-library

**Comment by arshaw** [comment]
I'm closing this issue to signify that it's implemented (since v4-alpha2). I'll comment on this thread again when v4 is officially released.

**Comment by arshaw** [comment]
[V4 was officially released a few days ago!](https://fullcalendar.io/blog/2019/03/v4-officially-released)
