### ISSUE TITLE
Is it really necessary to bind stuff to 'this' in event handlers?

### ISSUE THREAD

**Issue by DominikDitoIvosevic** [fullcalendar/fullcalendar#2987]
I'm using fullcalendar as a part of angular app and I have http://angular-ui.github.io/ui-calendar/ for using it with angular.

I'm providing the evend handlers from my service and what really bothers me is that since I'm passing the event handlers to fullcalendar via settings and in the meantime their 'this' get overriden.

How am I supposed to continue my workflow normally if I can't access my service's other functions because the event handler has 'this' bind to some html for example like in eventclick?

Why can't things simply be passed as arguments instead of being bind to this?

**Comment by arshaw** [comment]
in a future version of fullcalendar, i want to move away from relying on `this` for important data in arguments, so i agree.

however, if your handlers are relying on a certain `this` context, why don't you `bind` them on your own before passing them to fullcalendar? this will ensure your desired this context is always executed.

**Comment by arshaw** [comment]
fyi, as per issue #2699 , the `this` context in the future will probably be the calendar object.

**Comment by arshaw** [comment]
if you have further comments on this, a jsbin example might be  very helpful to illustrate what you're trying to achieve

**Comment by arshaw** [comment]
fyi, if fullcalendar doesn't do a bind, then the `this` context will always be the `window`. would you want that instead? i'm not sure how that's any better.

**Comment by DominikDitoIvosevic** [comment]
I'm using fullcalendar in my angularjs application. I'm using https://github.com/angular-ui/ui-calendar for binding it to my application.
I have a service which I use to provide eventHandlers.

    .service('FullCalendar', function (EventsService, AddEventPopup) {

      // FullCalendar event handlers
      // BEGIN
      this.doubleClickHandler = function (oldCalendarEvent) {
        console.log('eventDoubleClickHandler');
        console.log(AddEventPopup);

        EventsService.copyEventDTO(oldCalendarEvent, AddEventPopup);

        AddEventPopup.activate("edit");
      };

      this.dragCreateHandler = function (start, end) {
        console.log('dragCreateHandler');
        console.log(this);

        EventsService.copyEventDTO(EventsService.createEmptyEventDTO(), AddEventPopup);
        AddEventPopup.StartTime = moment(start);
        AddEventPopup.EndTime = moment(end);

        AddEventPopup.activate("create");
      };

      this.getSettings = function () {
        console.log('getSettings');

        return {
         // lalalalal some code
         // lala
          eventDoubleClick: this.doubleClickHandler,

          selectable: true,
          selectHelper: true,
          select: this.dragCreateHandler,
        }
      };
    }

What bothers me is that I can not access `AddEventPopup` inside my `dragCreateHandler` because it's `this` has been overriden and now I have to use a hack to do


    .controller('CalendarCtrl', function ($window, $scope, FullCalendar, AddEventPopup, lalalla) {

      window.AddEventPopup = $scope.AddEventPopup = AddEventPopup;
    }

to access it.

I can't bind to it before the fullcalendar script runs and I do not think it is a good idea to overbind them later (after fullcalendar does the .apply)

**Comment by arshaw** [comment]
`AddEventPopup` should be accessible from your `doubleClickHandler` function regardless of the `this` context. You are mixing up the `this` context with the concept of [JS's lexical scoping](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Closures). There must be some other forces at work.
