### ISSUE TITLE
Demos require dist folder

### ISSUE THREAD

**Issue by UziTech** [fullcalendar/fullcalendar#2989]
Why was the /dist folder removed in commit 6e5e5cf1e818b7e708c719f2ebf5c400b4b225e2 

The demos reference the files in that folder

**Comment by arshaw** [comment]
the idea is that the `dist` folder is generated from the build process (see the gruntfile's "dist" command) but not committed to version control. it *is* however committed to version control for tagged releases. this has become convention for projects like this. You can either run the build script yourself, or check out a tagged release.
