### ISSUE TITLE
amelioration of eventConstrain

### ISSUE THREAD

**Issue by sulian** [fullcalendar/fullcalendar#2996]
Hello

Do you think it's a good idea to update eventConstrain in order to support period AND day ("dow") ?

for example, limit the creation of an event for two years after today and only for business day.

Sulian

**Comment by arshaw** [comment]
i'd rather implement [client-side recurring events](https://github.com/fullcalendar/fullcalendar/issues/387) the proper way before considering this. `dow` is sort of a hack to get businessHours to work at the moment

**Comment by arshaw** [comment]
i will remember to make this happen when that is implemented
