### ISSUE TITLE
rendering calendar header

### ISSUE THREAD

**Issue by locito54** [fullcalendar/fullcalendar#2998]
In my implementation the header columns are not rendered correct (see attached screenshot).

any idea?

<img width="1209" alt="bildschirmfoto 2016-01-12 um 17 18 50" src="https://cloud.githubusercontent.com/assets/876995/12269268/e59ac820-b950-11e5-946b-52074d758fa4.png">

**Comment by arshaw** [comment]
this is a CSS issue on your end. plz at least post a JSBin and please consult "Getting Help" http://fullcalendar.io/support/
