### ISSUE TITLE
Official version of FullCalendar via Packagist

### ISSUE THREAD

**Issue by marclaporte** [fullcalendar/fullcalendar#2999]
Hi!

There are many FullCalendar sources here:
https://packagist.org/search/?q=fullcalendar

Would be nice to have the official one.

Thanks!

**Comment by espen** [comment]
Why? It's a JavaScript lib, not PHP.

**Comment by arshaw** [comment]
Packagist seems like a Composer package directory, and Composer is PHP package, so I'm very hesitant to go down this route. However, I have seem other front-end projects (just momentjs i guess) define a `composer.json`

**Comment by marclaporte** [comment]
It's common to have packages that have JavaScript but no PHP. This represents millions of downloads.

Some notable ones:
https://packagist.org/packages/twbs/bootstrap
https://packagist.org/packages/components/jquery
https://packagist.org/packages/components/jqueryui
https://packagist.org/packages/blueimp/jquery-file-upload
https://packagist.org/packages/ckeditor/ckeditor
https://packagist.org/packages/mbostock/d3
https://packagist.org/packages/tinymce/tinymce
https://packagist.org/packages/moment/moment

Tiki gets dozens of them:
http://sourceforge.net/p/tikiwiki/code/HEAD/tree/trunk/composer.json

Thanks!

**Comment by arshaw** [comment]
noted. will try to get this in there when there's a spare moment

**Comment by marclaporte** [comment]
Also hoping for FullCalendar Scheduler at the same time. Thanks!

**Comment by arshaw** [comment]
having problems with this, as mentioned in this comment: https://github.com/fullcalendar/fullcalendar/pull/3617#issuecomment-298708728

**Comment by arshaw** [comment]
still having trouble with this. see my latest comment: https://github.com/fullcalendar/fullcalendar/pull/3617#issuecomment-315505318

**Comment by arshaw** [comment]
queued for release, for real this time

**Comment by arshaw** [comment]
Released in v3.5.0 ([blog post](https://fullcalendar.io/blog/2017/08/bootstrap-support-and-future-developments/#more-257))
