### ISSUE TITLE
Upgrading Version from 1.5.4 to latest

### ISSUE THREAD

**Issue by BattyGrrl7** [fullcalendar/fullcalendar#3000]
Hello - 
This is not an issue, per say, this is a quick inquiry to see if there are any issues that are known with upgrading the full calendar to the latest version. 

The current version I am working with is: 1.5.4, in a MVC framework, and its currently being used. I was wondering  if I upgrade would any issues occur such as, designs not lining up, span bars not loading, calendar not loading properly, etc. Also, I would like to know if the attribute, data-date, is in the latest or any version after 1.5.4. I am not sure if modifications were made to the current one I am working with, but I did not see the option to have this attribute. 

Thanks

**Comment by espen** [comment]
If it's not an issue then why are you opening a new issue? (http://fullcalendar.io/support/)

Please see http://fullcalendar.io/wiki/Upgrading-to-v2/ for upgrading from 1.5.4 to latest.

**Comment by arshaw** [comment]
or look at the changelog
