### ISSUE TITLE
renderEvent bottleneck

### ISSUE THREAD

**Issue by MartijnWelker** [fullcalendar/fullcalendar#3002]
Whenever `renderEvent` is called it will call `reportEvents(cache)`, which is a huge bottleneck if you create multiple events, maybe this could be switched (or added) for a mass-render function which only calls `reportEvents(cache)` once.

**Comment by arshaw** [comment]
we probably still need to rerender ALL the events when only one is changed (because one event might affect the layout of the others), but limiting the number of repeat calls would be good. #2938 is a solution for that
