### ISSUE TITLE
eventMouseover & eventMouseout for background events

### ISSUE THREAD

**Issue by dfoxxdfoxx** [fullcalendar/fullcalendar#3005]
Is it possible to have an eventMouseover & eventMouseout for background events so i can easily show a div with extra information?
This is currently only working for normal events.

**Comment by arshaw** [comment]
yes, this would be a good idea

JSBin demonstrating how this is currently not the case: http://jsbin.com/leniyajoko/1/edit?js,output

**Comment by duetempi** [comment]
The link is wrong.
Is it possible to have an eventMouseover & eventMouseout for background events so i can easily show a div with extra information?
Thanks

**Comment by acerix** [comment]
@duetempi What do you mean by "link is wrong"?

Please **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates if you are waiting for this feature.

P.S. I'm working with @arshaw at fullcalendar, helping to triage tickets.

**Comment by arshaw** [comment]
This issue has been addressed in the latest alpha release (4.0.0-alpha.2)
[See the blog post &raquo;](https://fullcalendar.io/blog/2018/10/release-v4-alpha2)

https://fullcalendar.io/docs/v4/release-notes#event-clicking--hovering

**Comment by arshaw** [comment]
I'm closing this issue to signify that it's implemented (since v4-alpha2). I'll comment on this thread again when v4 is officially released.

**Comment by arshaw** [comment]
[V4 was officially released a few days ago!](https://fullcalendar.io/blog/2019/03/v4-officially-released)
