### ISSUE TITLE
eventLimitClick  titles not sorted out alphabetically 

### ISSUE THREAD

**Issue by redabenjli** [fullcalendar/fullcalendar#3006]
On the + more link on the calendar, once clicked the events do not show sorted in an alphabetical manner, is there any hotfix/quickfix for that ? or it could be a new feature.

Thanks in advance

**Comment by arshaw** [comment]
would you mind cooking up a quick JSBin? http://fullcalendar.io/wiki/Reporting-Bugs/

**Comment by arshaw** [comment]
events in the popover should be respecting [eventOrder](http://fullcalendar.io/docs/event_rendering/eventOrder/)
