### ISSUE TITLE
Event Shape

### ISSUE THREAD

**Issue by pgiani** [fullcalendar/fullcalendar#3007]
Some one know if is possible to change the event shape from a square to a parallelogram, see image below
![2016-01-15_1849](https://cloud.githubusercontent.com/assets/5713173/12368389/05258774-bbb9-11e5-804a-a2f7529f8903.png)

**Comment by arshaw** [comment]
you'll have to write your own custom CSS targeting `.fc-event.fc-start` and `.fc-event.fc-end`

**Comment by arshaw** [comment]
(responding to your email): instead of trying to do any geometric transforming, i would use pseudo elements to create [css triangles](https://css-tricks.com/snippets/css/css-triangle/).
