### ISSUE TITLE
Drag And Drop External Event with DOW

### ISSUE THREAD

**Issue by halomoan** [fullcalendar/fullcalendar#3008]
Hi

I use the latest Full Calendar v2.60 and hoping the Drag and Drop External Event with dow (repeating event) would works as expected but it is not.

If you do Drag and Drop External Event with dow, it works nice until we click next month, the event fully fill up the days in the repeating dates. Is it a bug or I missed something ?

 function ini_events(ele) {
        ele.each(function () {        
            var eventObject = {
                title: $.trim($(this).text()),
                dow: [1,2] // The culprit
            };

            // store the Event Object in the DOM element so we can get to it later
            $(this).data('eventObject', eventObject);

            // make the event draggable using jQuery UI
            $(this).draggable({
                zIndex: 1070,
                revert: true, // will cause the event to go back to its
                revertDuration: 0  //  original position after the drag
            });

        });
    }

![image](https://cloud.githubusercontent.com/assets/4265377/12373332/037e0916-bcb1-11e5-8727-419439d62716.png)

**Comment by arshaw** [comment]
right now, `dow` is not officially supported on events, and even if it were, it's unclear to me what it would mean if the user drops the event on a *different* day of the week, so not going to take any action here. when [recurring events](https://github.com/fullcalendar/fullcalendar/issues/387) is officially supported, will revisit this.
