### ISSUE TITLE
Too many columns problem

### ISSUE THREAD

**Issue by sarunas0919** [fullcalendar/fullcalendar#3012]
Hi,

We have a problem on day view. When there are many columns, then time column leap on first data column. How to solve this problem? Thanks.

Screenshot: http://oi65.tinypic.com/29x7m04.jpg

Calendar version: 1.5.4

**Comment by arshaw** [comment]
could you post a JSBin? http://fullcalendar.io/wiki/Reporting-Bugs/

**Comment by sarunas0919** [comment]
I can't post whole code into JSBin because code is very big, separated through many files, etc.

**Comment by arshaw** [comment]
@sarunas0919 it would be very helpful if you could put in the work to strip away as much code as possible and build a self-contained runnable demo. This is a great technique for diagnosing bugs and verifying bugfixes. https://css-tricks.com/reduced-test-cases/
