### ISSUE TITLE
Disabling a particular days from month calender and prevent from selecting.

### ISSUE THREAD

**Issue by smartkid77** [fullcalendar/fullcalendar#3013]
Hi @arshaw,

I am really excited that I overcome some issues with your help. This is a last one I believe, I want to disable some dates from month calendar. And also the the dates should be non-selectable. If is there any solution for this please let me know. I am really happy to get your advice. 

Regards
Dina

**Comment by arshaw** [comment]
http://fullcalendar.io/docs/event_rendering/Background_Events/
in combo with
http://fullcalendar.io/docs/selection/selectConstraint/
