### ISSUE TITLE
Week numbers are wrong when using momentjs 2.11.0 and providing 'firstDay' as a string

### ISSUE THREAD

**Issue by farlop** [fullcalendar/fullcalendar#3014]
Take a look at this code: https://jsfiddle.net/xwyqq4rg/4/

If 'firstDay' is provided as a string, week numbers are wrong. If it is provided as a number, it works fine. This occurs when using wit momentjs 2.11.0, but not wit 2.10.6

**Comment by mj1856** [comment]
It would seem from the fullcalendar source that it is manipulating the `dow` value of the existing locale's week.

```javascript
if (options.firstDay != null) {
    var _week = createObject(localeData._week); // _week: { dow: # }
    _week.dow = options.firstDay;
    localeData._week = _week;
}
```

Not exactly a public API, but that's fine.  However if it's desired for string input to be supported, then the value should be coerced to a number before setting it in the locale.

I'm really not sure why moment 2.10.x supported a string here.  It probably shouldn't have.

**Comment by peternowee** [comment]
Solved by using a unary plus `_week.dow = +options.firstDay;`

**Comment by arshaw** [comment]
it should be up to the caller to make sure the value is coerced into a number beforehand. If momentjs doesn't do any sanitization, and momentjs is the underlying date library, i don't think fc should either.
