### ISSUE TITLE
Number of day displayed are wrong when use hiddenDays option

### ISSUE THREAD

**Issue by Patatou** [fullcalendar/fullcalendar#3015]
Hi there,

I've an simple issue, but can't solve it for the moment. Simple example : 
Create a custom view like this : 
agendaThreeDay: {
					type: 'agendaDay',
					duration: { days: 3 },
					// views that are more than a day will NOT do this behavior by default
					// so, we need to explicitly enable it
					//groupByResource: true,

					//// uncomment this line to group by day FIRST with resources underneath
					groupByDateAndResource: true
				}		

Then, if you're Monday and HiddenDays ('2','3'), then calendar display only one day... but I want 3 days. In this cas, i wish calendar display Monday, Thursday and Firday....
Careful, solution must consider that title must specify the right interval of days displayed.

Any solution ? 

Ty.

**Comment by arshaw** [comment]
sorry for the delay in responding, but could you please post a runnable demonstration of what you describe? with JSBin or similar: http://fullcalendar.io/wiki/Reporting-Bugs/
