### ISSUE TITLE
Override compareEventSegs

### ISSUE THREAD

**Issue by Shamonator** [fullcalendar/fullcalendar#3017]
Event order is respected last yet, this is what is declaratively specified in configuration hence I do not want to order by the following that is hard-coded in compareEventSegs.

E.g.
seg1.eventStartMS - seg2.eventStartMS || // earlier events go first
seg2.eventDurationMS - seg1.eventDurationMS || // tie? longer events go first
seg2.event.allDay - seg1.event.allDay || // tie? put all-day events first (booleans cast to 0/1)

Our use case requires events to not be ordered by duration (longer events go first) but by event order.

How can we override compareEventSegs without forking the fullcalendar implementation?

Ideally, the sorting based on earlier events followed by longer events should be configurable, as eventOrder is configurable.

**Comment by aqibmushtaq** [comment]
+1

**Comment by arshaw** [comment]
thanks for the input here. this is a duplicate; please subscribe to #2907 . thanks
