### ISSUE TITLE
Date format on week view day title

### ISSUE THREAD

**Issue by jparmar** [fullcalendar/fullcalendar#3018]
Hello,

I have gone through many calendar configuration options but din't find any option to change the date format of day title on week/Agenda week view.
please refer to attached screen capture and suggest how can I control the date format in highlighted area.

http://prntscr.com/9vst99

at present, it displays "month/date" but country like UK uses "date/month" format.

**Comment by espen** [comment]
Please see http://fullcalendar.io/docs/text/lang/

Also please see http://fullcalendar.io/support/ for any other questions you have.
