### ISSUE TITLE
Last day period does not appear

### ISSUE THREAD

**Issue by nikkyb8** [fullcalendar/fullcalendar#3021]
Hello,

On your demo page http://fullcalendar.io/js/fullcalendar-2.6.0/demos/basic-views.html

Take the Conference item, it must be the 11au 13 but it appears the 12 11au

How to fix this?

**Comment by arshaw** [comment]
this is because the end date is exclusive
see `end` in http://fullcalendar.io/docs/event_data/Event_Object/
