### ISSUE TITLE
Select across day option

### ISSUE THREAD

**Issue by xxAtrain223** [fullcalendar/fullcalendar#3025]
My customer would like the ability to drag across days, but instead of making one event spanning start and end, they would like to have have several events spanning that time range on each day.

For example: You click on 7am on Monday (2/1) and drag to 9am on Friday (2/5). Right now, it'll make one event spanning 2/1:7am---2/5:9am. The intended effect is to have 5 events: {(2/1:7am--2/1:9am), (2/2:7am--2/2:9am), (2/3:7am--2/3:9am), (2/4:7am--2/4:9am), (2/5:7am--2/5:9am)}. 

So basically they want Excel style selecting.
I've been able to hack this up by using the select callback:
```Javascript
select: function (start, end, jsEvent, view) {
	while (start.isBefore(end)) {
		var eventData = {
			start: start.clone(),
			end: end.clone().date(start.date()).month(start.month()).year(start.year())
		}
		start.add(1, 'd');
		$('#calendar').fullCalendar('renderEvent', eventData);
	}

	$('#calendar').fullCalendar('unselect');
}
```

But in order to prevent confusion, I had to remove the fc-highlight background color (because it still shows the one event from start to end).

**Comment by xxAtrain223** [comment]
This is for agenda week

**Comment by xxAtrain223** [comment]
![multipleevents](https://cloud.githubusercontent.com/assets/7133510/12727951/70b1ae82-c8ed-11e5-96f0-08a0c73fa2b2.png)
vs.
![oneevent](https://cloud.githubusercontent.com/assets/7133510/12727956/73daad5c-c8ed-11e5-8bb6-cc55ee37f124.png)

**Comment by xxAtrain223** [comment]
I'm fine with my solution, but not having highlighting is a little off-putting. Is there a way that I can hack in some highlighting for this task? I've looked around, but it just seems too magical to me.

I'd be happy to implement this to the library, but i'm not sure where to get started.

**Comment by arshaw** [comment]
this is a little edge-casey to put in the core lib. but if [this feature](https://github.com/fullcalendar/fullcalendar/issues/2722) were implemented, meaning you could listen to the mousedown/mouseup of cell selecting, as well as having an exposed helper-render function (to render the fake events), this could be possible. plz follow that 2722 ticket

**Comment by arshaw** [comment]
eek, wrong link. one sec..

**Comment by arshaw** [comment]
#2718 is the right one

**Comment by xxAtrain223** [comment]
Ok, I agree, it is a bit of a edge case.
