### ISSUE TITLE
whole year view

### ISSUE THREAD

**Issue by wheelq** [fullcalendar/fullcalendar#3027]
is it possible to display whole year, all months on one page?
if yes then how can this be achieved?

**Comment by arshaw** [comment]
there are a few year view requests, this being the most popular: https://github.com/fullcalendar/fullcalendar/issues/1140

**Comment by sureshmss2007** [comment]
I am looking for yearview in 2.6.0

**Comment by simkimsia** [comment]
So how do we activate the year view in the latest 2.6.1?

**Comment by espen** [comment]
@simkimsia you can create a custom view (see the docs). Year view is not included in Fullcalendar. But please follow #1140 for updates.

**Comment by simkimsia** [comment]
@espen can give the actual link to the docs?

**Comment by espen** [comment]
@simkimsia there is no year view. You have to create a custom view yourself. See http://fullcalendar.io/docs/views/Custom_Views/
