### ISSUE TITLE
NowIndicator specific timezone

### ISSUE THREAD

**Issue by johnnyhertogs2** [fullcalendar/fullcalendar#3028]
I realy like the nowIndicator. I want to develop a calendarview with a now indicator, in a specific timezone. So I want to show the nowindicator for all users worldwide at the same time. So I set:

`timezone: 'America/Chicago'`

That's not changing the place of the indicator, but 

`timezone: 'America/Chicago'`

does change it to UTC. But I want to display all the users a red line at the current Chicago time.

**Comment by arshaw** [comment]
that is because the JS doesn't know how to calculate the current time in chicago. however, you can achieve it with the `now` setting...
http://fullcalendar.io/docs/timezone/now/
