### ISSUE TITLE
Updating An Event By Dragging/Dropping FullCalendar

### ISSUE THREAD

**Issue by garden786** [fullcalendar/fullcalendar#3030]
Hello I am trying to implement drag and drop feature which is available in fullcalendar. It is working but I'm facing a problem that whenever I try to drag and drop and event it moves that event to the new location but it also moves all the other ahead to. I don't know why I am facing this error.Here is my code

```
 $('#calendar').fullCalendar({
        // put your options and callbacks here
        // droppable: true,
        editable: true,
		eventDrop: function(event, delta, revertFunc) {
	        alert(event.title + " was dropped on " + event.start.format());

	        // if (!confirm("Are you sure about this change?")) {
	        //     revertFunc();
	        // }
    	},        
     //    drop: function(date) {
     //    	alert("Dropped on " + date.format());
    	// },
        viewRender: function (view) {
				debugger;
			    $.ajax({
	          	type: "POST",
	          	url: base_url +"/apps/calendar/getByMonth",
	          	async : false,
	          	dataType: 'html',
	          	data: {'type': $('#formName').val() },
	          	success: function(mark_up){
	          	  debugger;
	              mark_up = JSON.parse(mark_up);
	              my_events = mark_up["task"];
	              $('#calendar').fullCalendar( 'removeEvents');
    			  $('#calendar').fullCalendar('addEventSource', my_events);
	          	}
	      	});
		},
		eventClick: function(calEvent, jsEvent, view) {
						
	        // alert('Event: ' + calEvent.title);
	        // alert('Coordinates: ' + jsEvent.pageX + ',' + jsEvent.pageY);
	        // alert('View: ' + view.name);
	        $('#eventId').val(calEvent._id.$id);
	        $('#editStarts').val(calEvent.start._i);
	        if (calEvent.end == null){
	        	$('#editEnds').val(calEvent.start._i);
	        }else{
	        	$('#editEnds').val(calEvent.end._i);
	        }
	        $('#editTitle').val(calEvent.title);
	        $('#editDescription').val(calEvent.description);
	        $('#editNewEvent').modal('show')
	        // change the border color just for fun
	        // $(this).css('border-color', 'red');

    	},
    	 dayClick: function(date, allDay, jsEvent, view) {
    	 	
    	 	// var p = date.month()+'/'+date.day()+'/'+date.year()
    	 	 $('#addNewEvent').modal('show');
        	// alert('a day has been clicked!');
    	}
```

Here is a small video clip I have made of the error I am facing hope it helps[Drag Problem](http://screencast.com/t/IHDSYgj9b)

**Comment by arshaw** [comment]
things are likely breaking down because you using an non-standard technique for fetching and putting events on the calendar. please attempt to do something like this: http://fullcalendar.io/docs/event_data/events_json_feed/

**Comment by quentinfasquel** [comment]
I was facing the same issue. I have a local event source initialized with an empty array of events. Creating a new event gets the actual EventSourceObject and adds (.push) it to the source's array of events. Then calling refetchEventSources with the local event source's id to render the event.
Unfortunately, later on while dragging/dropping, that same issue happens.

To solve it, I replaced "refetchEventSources" by "removeEventSource + addEventSource"...which in my opinion is what refetchEventSources should behave like for local data.

**Comment by rahulmalhotra** [comment]
I too was facing the same issue, I checked that in my single event json, I have same values for **id:** key like:-
`
{
id: 1,
name: name,
title: title,
start: startDate
}
`
As shown in the above json, each event object was having the same id that was causing problems and moving all the events together to the new location.
