### ISSUE TITLE
rendering events problem

### ISSUE THREAD

**Issue by ambicoder** [fullcalendar/fullcalendar#3031]
I have initialized the calendar and I have set up an event source...a php file.... to bring the events with an ajax GET request.
My question has to do with the rendering of the calendar....**first** the cells are rendered and **then** the events(after the ajax request is made).
Is not nice from a design point of view.

Is there a way to prevent this and have them both render at the same time

**Comment by arshaw** [comment]
i don't see how this would be an improvement. during the time the events are loading, the calendar wouldn't be rendered at all. might feel award to the end-user. i would need more convincing

**Comment by ambicoder** [comment]
Ok...then...one last question,,,I suppose I could make an effect so that the events fade in view gradually...for example.
