### ISSUE TITLE
Firefox set scroll to content but Chrome not

### ISSUE THREAD

**Issue by vertisan** [fullcalendar/fullcalendar#3032]
Hi!
I have somethink like this:
**Chrome 48**
http://i.imgur.com/8orD1jf.png
**Firefox 44**
http://i.imgur.com/0ihynry.png

I unlinked all CSS/JS without FC and problem stayed (Chrome works fine)

**Comment by arshaw** [comment]
please post a JSBin http://fullcalendar.io/wiki/Reporting-Bugs/
