### ISSUE TITLE
rename eventLimit to maxEventRows. achieve true max events?

### ISSUE THREAD

**Issue by jasonEXA** [fullcalendar/fullcalendar#3035]
Issue created with reference to the 2nd part of [#128](https://github.com/fullcalendar/fullcalendar-scheduler/issues/128).

One other UI issue I encountered (demonstrated in above jsBin link) is when there are multiple events, one of which extends over multiple days and the other is present for a single day for the same resource. The one that extends over multiple days, overlaps the one on the single day. There is no visual indication to the user if there is an event present on that single day.

jsBin output link - http://output.jsbin.com/dunojoqome/

E.g
![image](https://cloud.githubusercontent.com/assets/9958408/12879104/9218ece0-ce54-11e5-9134-e13d137a2989.png)

**Comment by arshaw** [comment]
this looks like some sort of malfunction of the `eventLimit` setting, which you have turned on. does setting it to `false` give you the desired behavior?

**Comment by arshaw** [comment]
you actually have `eventLimit: 3` on basicWeek view, so it's not a malfunction. The number `3` means 3 lines of content, and if there are more that 3 events, then the first two are displayed and the rest are put into the "more" link

**Comment by arshaw** [comment]
I propose the `eventLimit` setting be renamed to `maxEventRows`

**Comment by p-ob** [comment]
Hmm yes that does sound like the same issue (although multi-day events are not required). So to always show just x events per day with the additional events hidden is not the intended purpose? It is always "try to show x, if there are more than x show x-1 as the +n more counts as an event row"?  And if this is the case, the desired effect is a piece of functionality that does not exist for fullcalendar?

**Comment by arshaw** [comment]
@p-ob, you accurately describe the current behavior.

i'll proposed that the current option be renamed to `maxEventRows` and your desired new behavior be called `dailyEventLimit` or something

**Comment by imransmy** [comment]
Hello, I'm using fullcalender in my application. I have created customweek and timelineday as per my client's request. Everything is fine, but i have more than 20 events per day may be it will be more over 100 or 200. In month view im able to view that much of events using view more. In day and week view im not able to add view more. I have added "eventLimit" also tried "maxEventRows " as well as "dailyEventLimit" too. But in week and timeline view it was showing all the events. Please help me.

**Comment by arshaw** [comment]
@imransmy , what you are talking about is a different feature than this ticket. essentially you want eventlimit for the time slots in agenda views, which is currently not possible, nor do I understand how the UI would look for this. could you open a new ticket and explain more?

**Comment by imransmy** [comment]
Thank you @arshaw

**Comment by morawcik** [comment]
I have similar problem: when I set eventLimit to 2 and I have 3 events in one day I can see only 1 event and link +2 more, but when I change eventLimit to 3 then I see all 3 events. I tried fix it myself and when I changed in `DayGrid.prototype.limitRow` line `levelSegs = rowStruct.segLevels[levelLimit - 1];` to `levelSegs = rowStruct.segLevels.slice(levelLimit);` then it works

**Comment by ovidiua2003** [comment]
Why isn.t this already fixed. The proposed solution clearly works. Subscribing to this as I had the exact same problem.

**Comment by GeriSoft** [comment]
For me, maxEventRows: 4, and eventLimit: 4, reperesent the same issue. Not solved the problem when I have 15-25 events a day, and loaded to month view.

**Comment by Idkw13** [comment]
@morawcik 

when I change on your decision
![image](https://user-images.githubusercontent.com/32147727/61949852-cb391280-afb4-11e9-8db2-fd087fd69531.png)
 it turns out so

**Comment by arshaw** [comment]
this has been implemented in v5 (in beta). please read the [latest blog post](https://fullcalendar.io/blog/2020/04/new-ui-features-beta).

There are two settings now. `dayMaxEventRows` and `dayMaxEvents`. Please read [the section in the upgrade guide](https://fullcalendar.io/docs/v5/upgrading-from-v4#more-events-popover) to lean more.

**Comment by arshaw** [comment]
officially released: https://fullcalendar.io/blog/2020/06/v5-official

**Comment by arngrim** [comment]
Hi, I'm using Fullcalendar V5, but I have a question, how can I limit the creation of events?, I need that the user only be able to create a maximum of 2 events per day, I tried with dayMaxEvents, but this only hides them, and what I need is after creating 2 events in a day, the calendar blocks that day and do not allow to create more events for that day.

**Comment by hoSaMShoukry** [comment]
can you give me an example for maxEventRows in nuxt or vue3 please @arshaw
