### ISSUE TITLE
Any way to fill parent element?

### ISSUE THREAD

**Issue by aharpervc** [fullcalendar/fullcalendar#3039]
I'm using the scheduler plugin and trying to get it to fill its parent element, which is absolutely positioned to fill _its_ parent. Currently I'm seeing that if I don't specify `height` or `contentHeight` with a numeric value, it'll use the `aspectRatio` property to come up with a height. Is that correct? Is there any way to say "please fill the height of the parent"?

https://github.com/fullcalendar/fullcalendar/blob/master/src/Calendar.js#L669

**Comment by arshaw** [comment]
please follow #2704
