### ISSUE TITLE
en-us missing from lang directory

### ISSUE THREAD

**Issue by gigilsu** [fullcalendar/fullcalendar#3041]
On bower install, en-us.js is missing from lang directory. It does not cause any errors but fullcalendar looks for it.

**Comment by arshaw** [comment]
fullcalendar, the AMD module, never explicitly requests any of the language files. what do you mean fullcalendar looks for it? it is somehow dependent on how your calling-JS operates, or your script tags in your HTML file?

**Comment by gigilsu** [comment]
I am using Phillip Frenzel's module for Yii Framework, so perhaps the problem is there. I know there is a lang directory on the bower install and it has many languages, but en-us isn't one of them. The yii module uses en-us as a language by default, and it looks for it in that directory.

**Comment by arshaw** [comment]
yeah, it's a shortcoming with Yii in that case.
