### ISSUE TITLE
Events with "end" date, are not displayed the first day, with defaultView: agendaWeek

### ISSUE THREAD

**Issue by myn01** [fullcalendar/fullcalendar#3046]
**Events in the first day, WITH END datetime set, are NOT displayed** with defaultView: 'agendaWeek'.
This just happens in the first day, even if you change the "firstDay" parameter.
If you click on Month View and go back to Week View, those "hidden" events are displayed.
To verify it, just add the following changes in the **JSON example** included in the download files:

**JSON.HTML:**
header: {
left: 'prev,next today',
center: 'title',
right: 'month,agendaWeek,agendaDay'
},
defaultView: 'agendaWeek', 

**EVENTS.JSON:**
  {
    "title": "MY HIDDEN TITLE",
    "start": "2016-01-10T10:30:00-05:00",
    "end": "2016-01-10T12:30:00-05:00"
  },

Then, try the same **deleting **the "END" line from events.json file, refresh the page, and the event will be displayed

Obviously, this will happen replacing json file with a database module.

Any idea to solve this?

**Comment by arshaw** [comment]
would you mind posting a JSBin with a recreation of the bug? instructions:
http://fullcalendar.io/wiki/Reporting-Bugs/

**Comment by myn01** [comment]
I couldn't find at JSBin or JSFiddle the way to add PHP files (the ones included in Fullcalendar examples)
You just need to make the following changes in the examples included:

In **JSON.HTML:   add** 
defaultView: 'agendaWeek',

**In events.json, add**
"title": "MY HIDDEN TITLE",
"start": "2016-01-10T10:30:00-05:00",
"end": "2016-01-10T12:30:00-05:00",
"backgroundColor": "#ff0000"
},

When you execute the json.html page, the event added will not appear in the first day (2016-01-10) in the agendaweek view. If you push on MONTH button, it will appear and then if you pass to WEEK again, it will appear for the first time in this view.
If this is not enough for you to duplicate the issue, let me know and I can send you an URL for you to verify it, or tell me if I'm able to upload PHP files on the platforms that you mentioned.
Thank you!
[issue.zip](https://github.com/fullcalendar/fullcalendar/files/139691/issue.zip)
