### ISSUE TITLE
Bug: Moment's isAfter method appears to be broken

### ISSUE THREAD

**Issue by daniel-nagy** [fullcalendar/fullcalendar#3047]
Calling `view.calendar.getNow().isAfter(view.start)` returns `false`.

[moment-ext.js: 389](https://github.com/fullcalendar/fullcalendar/blob/3a464732a77eac8999875525549d19be0c423d5f/src/moment-ext.js#L389)

[CodePen](http://codepen.io/anon/pen/yeZqza?editors=1010) (see developer console)

<img width="302" alt="screen shot 2016-02-13 at 2 22 48 pm" src="https://cloud.githubusercontent.com/assets/1622446/13029548/58eefa60-d25d-11e5-9656-a72bcaf5385e.png">

**Comment by arshaw** [comment]
As weird as it might sound, this is intended behavior. I'll try to explain...

if you simply call `.format()` on the two dates:
```
now = 2016-02-21T13:06:07
view.start = 2016-02-21
```

the lack of time part to the `view.start` indicates that it is an [ambiguous-timed](http://fullcalendar.io/docs/utilities/Moment/#ambiguously-timed) moment.

An ambigously-timed moment doesn't have time 00:00 for which to compare with other moments. It is considered to be "all-day". Thus, 13:06 isn't considered to be after the all-day period. It's considered to be *within* it.

However, I can understand why this might be confusing, so if I get more inquiries, I will consider changing it.

**Comment by daniel-nagy** [comment]
Thank you for the explanation.
