### ISSUE TITLE
Event end time not displayed when duration is one slot (agenda)

### ISSUE THREAD

**Issue by gailsteiger** [fullcalendar/fullcalendar#3049]
with option slotDuration set to '00:30:00', an event such as start 9:00, end 9:30 displays '9:00AM -', even if displayEventEnd is set to true.

Works fine for events with duration of 1 hour

see 
https://jsbin.com/vewoxo/edit?html,output

**Comment by arshaw** [comment]
thanks

**Comment by paulocastellano** [comment]
+1

**Comment by actorius** [comment]
Same issue... +1

**Comment by espen** [comment]
["Please remember, the best way to express your interest is to make a  reaction on the description of the issue"](https://fullcalendar.io/blog/2016/07/renovated-issue-tracker/)

**Comment by arshaw** [comment]
This bug is noticeable only when the event's title is empty. Otherwise, it is desirable behavior because the event's title is placed next to the start time like this:
<img width="133" alt="screen shot 2017-07-14 at 6 43 19 pm" src="https://user-images.githubusercontent.com/56520/28233382-614b079a-68c4-11e7-9d24-2f82d8a021d4.png">

**Comment by jamesdixon** [comment]
@arshaw I'm not sure what you mean by "This bug is noticeable only when the event's title is empty." In your screenshot, the event title isn't empty :-)

**Comment by arshaw** [comment]
my little screenshot is demonstrating the desirable behavior, in other words, trying explain why I implemented it this way. When the event gets too short, it displays "(time) - (title)", like the screenshot, but when there is no title, it just looks like "(time) - "

**Comment by arshaw** [comment]
the solution: don't do that when there is a blank title

**Comment by arshaw** [comment]
(which would need to be implemented internally)

**Comment by EoghanH** [comment]
+1

**Comment by beingprasi** [comment]
+1

**Comment by shruthikj** [comment]
+1

**Comment by noveweb** [comment]
+1

**Comment by judsonabraham301** [comment]
even I'm facing the same issue

**Comment by SkunkyDu52** [comment]
👍

**Comment by andrija29** [comment]
Same here

**Comment by arshaw** [comment]
fixed by e879c430013ed9b5c644473f3573f0c6453c29ca (not yet released)

**Comment by arshaw** [comment]
released in [3.10.0](https://github.com/fullcalendar/fullcalendar/releases/tag/v3.10.0)
