### ISSUE TITLE
Feature: Customization of dayNumbers

### ISSUE THREAD

**Issue by jigargandhi** [fullcalendar/fullcalendar#3050]
At certain places users might want to show additional information along with `dayNumbers` (for holidays, or some othere event).
For example for 1st March, I would like to show 
![image](https://cloud.githubusercontent.com/assets/380721/13068098/c3973b4c-d49d-11e5-9342-ce572b2c6a87.png)

A feature is required which support dayNumber customization. 

Sample spec could be:

``` dayNumber : function(obj){} /// obj is a moment instance ```

Default could be
```dayNumber: function(obj){ return obj.date() } ```

**Comment by arshaw** [comment]
this type of custom rendering behavior could theoretically be achieved with `dayRender`
http://fullcalendar.io/docs/display/dayRender/
