### ISSUE TITLE
Time on event is wrong for multi-day events

### ISSUE THREAD

**Issue by feketegy** [fullcalendar/fullcalendar#3051]
Issue replicated here: http://jsbin.com/yuremegape/edit?html,js,output

Test Event
* start date: 2016-02-19 15:00:00'
* end date: 2016-02-20 08:30:00

On the calendar in the `agendaWeek` view the time on the Test Event should be the following:

On 2016-02-19 the time should be 3:00 - 12:00
On 2016-02-20 the time should be: 12:00 - 8:30

Interestingly enough if I change the end date to "2016-02-20 9:30:00" it works as expected...

My browser timezone is GMT+2, maybe the timezone is calculated incorrectly.

**Comment by arshaw** [comment]
this seems to be the same discussion that's happening on #3038. please subscribe to that issue, thanks
