### ISSUE TITLE
Feature request: More control over event sorting

### ISSUE THREAD

**Issue by jmcarp** [fullcalendar/fullcalendar#3056]
The `eventOrder` option is useful for breaking ties between events with the same time, duration, and all-day-ness, but sometimes even more customization is needed. For example, a client asked for all-day events to be ordered last, but they're always set to go first in https://github.com/fullcalendar/fullcalendar/blob/master/src/common/Grid.events.js#L942-L948. I got around the issue by globally monkey-patching `compareEventSegs`, but this isn't an elegant solution. Would you be open to allowing users to overriding all sorting behavior? I'd be happy to submit a patch if so.

cc @noahmanger

**Comment by arshaw** [comment]
would you mind subscribing to #2907?

**Comment by jmcarp** [comment]
Thanks, I hadn't seen that issue--subscribed!
