### ISSUE TITLE
Issue in horizontal scrolling when using vertical Resource View

### ISSUE THREAD

**Issue by Shakthivakeeswaran** [fullcalendar/fullcalendar#3057]
I've been working with full calendar for custom events and task handling.
I need to show all the resource(Users who are having events) in a vertical resource view. i've hundreds of users so when i gave them to Resource Object, the calendar collide with every other Users column without scrolling enabled. 
![fullcell](https://cloud.githubusercontent.com/assets/17403912/13215535/02bf9096-d924-11e5-8e0d-4837100c67c1.png)

when i applied overflow attribute to class view-container, it is ok. 
!(https://cloud.githubusercontent.com/assets/17403912/13219373/a3030ace-d93d-11e5-8fa0-db1a06a3cb19.jpg)

but when scrolling we need the calendar time column to follow the scroll but it gets hidden like below. 
![screen shot 2016-02-22 at 5 15 53 am]![screen shot 2016-02-22 at 5 16 48 am](https://cloud.githubusercontent.com/assets/17403912/13219381/b513ac5a-d93d-11e5-86b4-947c40070241.jpg)

I should be able to scroll to users till end with time must follow. Kindly help me to resolve this issue. i have added the screen shots for the above words which will explain you if my words are not understandable. I am a beginner in full calendar.io kindly help me to resolve this issue.

**Comment by arshaw** [comment]
would you be able to subscribe to #3022 ? I just approved that one and will use it instead.
