### ISSUE TITLE
Document array return value of eventSource.success

### ISSUE THREAD

**Issue by jmcarp** [fullcalendar/fullcalendar#3058]
JSON event sources pass success, error, and complete options to `$.ajax`, which the documentation explains well. But there's an additional undocumented behavior which is useful, and that I think should be added to the docs: if a `success` callback is passed, and returns an array, that array replaces the return value of the AJAX response. I'd send a patch to document this myself, but I'm not sure where the docs live. Sorry if I missed this in the docs, but I looked around for a bit and didn't see anything.

See https://github.com/fullcalendar/fullcalendar/blob/3a464732a77eac8999875525549d19be0c423d5f/src/EventManager.js#L205-L208.

**Comment by arshaw** [comment]
oh wow, I forgot I wrote that. I'll make a note to document it

**Comment by dakala** [comment]
This is a v3 issue. In v4 we now have `eventSourceSuccess` which is well-documented https://fullcalendar.io/docs/eventSourceSuccess
