### ISSUE TITLE
Scrolling issue with FullCalendar and IE 10/11

### ISSUE THREAD

**Issue by Mariick** [fullcalendar/fullcalendar#3059]
Hi everyone,

I noticed that i cannot scroll on tactile devices (under IE 10/11 as usual..)  a FullCalendar with option selectable enabled (selectabled=true), IE fire 'mousedown' event on scrolling and thus run the callback function set in FullCalendar init Object.
This is really annoying because for scrolling under IE10/11 users need to scroll on the empty space on the right or left side...

Is this normal or does a fix exist ?

Thanks

**Comment by arshaw** [comment]
could you try using the latest version of FC? they officially support touch now
