### ISSUE TITLE
All day event span issue 

### ISSUE THREAD

**Issue by vapandya** [fullcalendar/fullcalendar#3060]
JSBIN : http://jsbin.com/huyoja/1/edit?js,output

Issue : the event has startdate "2016-02-23T08:00:00" and enddate "2016-02-24T22:00:00"  and allDay porperty has been ticked ideally event should span for two days as it is well above default "nextDayThreshold" but as you may see in the JSbin example it is not.

Hint : I tried looking into the code: "computeDayRange" function seems to have some issue 
current line of code: endTimeMS = +end.time(); // # of milliseconds into `endDay`
my change which works in the case : endTimeMS = end.time(); // # of milliseconds into `endDay`

I Thnik = + is causing the issue and makeing the condition false, thus a day is not being added, by removing + sign it works like a champ.

**Comment by arshaw** [comment]
this is because the time part of the date string is thrown out when `allDay:true`, as mentioned in #2985 (could you subscribe to that issue?)

enough ppl have been confused by this behavior where I now want to change the behavior...
