### ISSUE TITLE
View.prototype.render.apply(this, arguments); is not working!

### ISSUE THREAD

**Issue by hnp-play** [fullcalendar/fullcalendar#3064]
CustomView = View.extend({

    // clears the view's rendering and executes other cleanup tasks
    render: function() {

        // <my custom code here>

        // call the super-class's method, forwarding all arguments
        View.prototype.render.apply(this, arguments);
    }

});

It's not working.
How to use render function in CustomView coding?

ownDobuments error occurs.

**Comment by hnp-play** [comment]
I used console.log().
View.prototype doesn't have render.
So, Errors happen.
It has 'renderSkeletonHtml' and etc.

Which do I use?
But fullcalendar source contains a function of 'render'.
How to use?

**Comment by zaherkassem** [comment]
I have the same issue and i get this error: 

 TypeError: Cannot read property 'apply' of undefined(…)

**Comment by arshaw** [comment]
http://fullcalendar.io/wiki/Reporting-Bugs/
