### ISSUE TITLE
Incorrect date in drop function.

### ISSUE THREAD

**Issue by rosieks** [fullcalendar/fullcalendar#3065]
I found issue with dropping external element. In drop function the first element supposed to date of the dropped event. Unfortunately it's something different.

This JSBin shows this trouble: http://jsbin.com/hiverobena/edit?js,output

When you drag red box to 8AM, the date in first parameter of drop function is 9AM.

**Comment by tobya** [comment]
Hi  I tried your jsbin and it works for me.

Wed Nov 12 2014 08:00:00 GMT+0000 (GMT Standard Time)

I wonder does it only show if you are not in GMT.  Perhaps aer you +1 hour and its doing GMT hours?

**Comment by rosieks** [comment]
@tobya That can be the reason - when I changed my time zone to GMT it works fine, when I went through few others then the time was moved according to time zone.

**Comment by tobya** [comment]
I guess its still a bug but might help narrow down where the error is occuring.

**Comment by arshaw** [comment]
if you use `.format()` instead of `.toDate()` you'll see the correct results. Calling `toDate()` queries the internal date object used by the moment, and the calendar has an ambiguous timezone, so it will look somewhat meaningless.

**Comment by LasithaPrabodha** [comment]
Why do I still get this error in version 4.0.1?

**Comment by LasithaPrabodha** [comment]
Why do I still get this error in v4.0.1?
