### ISSUE TITLE
Content scrollbar isn't rendered properly after events are pulled in (or height is adjusted) - Chrome only

### ISSUE THREAD

**Issue by caseyjhol** [fullcalendar/fullcalendar#3067]
![fullcalendar_bug](https://cloud.githubusercontent.com/assets/2874325/13367673/775aac08-dca1-11e5-9007-8cf14353f229.gif)
Example: http://jsbin.com/zeyayo/edit?js,output

Scenario: The calendar has a set height of 500px. FullCalendar is initiated on page load, and events are pulled in via an Ajax request (a 3 second setTimeout is used in this case to simulate the Ajax request). All day events are pulled in, increasing the height of dayGrid, and decreasing the height of timeGrid to maintain the 500px height. Due to what appears to be a rendering bug in Chrome, the height of timeGrid resizes properly, but the scrollbar remains the same size (meaning part of it is cut off). I've only been able to reproduce this in Chrome (using Chrome 48 on Windows 10).

Reduced test case example: https://jsfiddle.net/caseyjhol/mk0g9nxm/4/

Scenario: I pinpointed the relevant functions, and made a reduced test case without the rest of the FullCalendar code. For simplicity, rather than calculate the scrollerHeight for timeGrid, I'm using the same values that FullCalendar used in the earlier example (392px and then 329px after the events are loaded).

Removing `unsetScroller($scrollerEl)` from the setHeight function resolves the problem. I'd submit a pull request, but I'm sure there's a specific reason that's in there.

**Comment by arshaw** [comment]
Bizarre. The scroll pane is otherwise perfect. It's just the visual appearance of the scrollbars that's screwed up.

I have some changes coming in the next release that involve a rewrite of that scroller code, so might want to hold off. a quick `.hide().show()` or something of that nature might be a fix as well.

**Comment by caseyjhol** [comment]
Cool - I realize this a bit of an edge case, but figured it was worth reporting anyway. Might even be worth reporting to Google too, since other browsers don't have any issues dealing with this.

**Comment by caseyjhol** [comment]
@arshaw I just tested this again in Chrome 51, and this issue appears to have been resolved.

**Comment by arshaw** [comment]
great. i will close
