### ISSUE TITLE
Event Bar only on End Data Full Calendar

### ISSUE THREAD

**Issue by Gardezi1** [fullcalendar/fullcalendar#3069]
Hello guys. Currently when I'm rendering all of my events I get a long bar which starts from the starting date and go upto the ending date. But due to some requirements I do not want that long bar on the starting and covering all of the boxes that comes in between the starting and ending date. I just want that bar on the ending date. I can't figure out how to do it. Can you guys help me out

**Comment by arshaw** [comment]
"Getting Help"
http://fullcalendar.io/support/
