### ISSUE TITLE
By Default Calendar not coming on Partial Page of MVC

### ISSUE THREAD

**Issue by dhawkKD** [fullcalendar/fullcalendar#3070]
Hi,

When I am trying to call fullcalendar from the partial view it is not coming until m clicking on the Today button of the Calendar and the same code is working for the view page.
Is it the issue with partial page?

Thanks 
Kapil

**Comment by DominikDitoIvosevic** [comment]
We have fc on a partial and it works as expected. How do you mean it is not "comming"?

**Comment by slepit** [comment]
I have a similar issue.
When I include the calendar in a multi tab page (hidden tabs until clicked): When I click on the tab where the calendar is, only the header (today, next, prev) is present. When I click on today, the calendar get's displayed.

If I try to display the calendar anywhere else in my web page all is fine.

**Comment by arturmamedov** [comment]
I have the same problem, after update to last version it solved.

**Comment by ayyash** [comment]
This is not resolved, how do we force the calendar to show? if it were inside a hidden element by default it never renders until we interact with it
