### ISSUE TITLE
eventDrop should have a counterpart

### ISSUE THREAD

**Issue by DominikDitoIvosevic** [fullcalendar/fullcalendar#3071]
Event drop triggers only when there has been a change in the time of the event after repositionion.
DragEnd does not contain direct information whether the event has been repositioned or the repositioning has been cancelled (the new time is the same as the old one).

What we are using in our modified script:

line 3837:

                           // has been here in the original script
					if (dropLocation) {
						view.reportEventDrop(event, dropLocation, this.largeUnit, el, ev);
					}
                                        // what we added
					else { 
            // For when the event has been dropped to the same position
					  view.reportEventDropOnSame(event);
					}

**Comment by DominikDitoIvosevic** [comment]
Why do you close issues without any comment?

**Comment by arshaw** [comment]
https://raw.githubusercontent.com/fullcalendar/fullcalendar/master/.github/ISSUE_TEMPLATE.md
