### ISSUE TITLE
feat: Events as a JSON feed should allow customization of variables sent in URL

### ISSUE THREAD

**Issue by diosney** [fullcalendar/fullcalendar#3073]
**This can be done backwards compatible since adds two new options and doesn't breaks old functionality (I think :D)**

Right now the URL where fullcalendar will search for events is:

```
/myfeed.php?start=2013-12-01&end=2014-01-12&_=1386054751381
```

All before the `?` can be customized via the `events` property, but `start` and `end` URL variables not.

It could be great that something like the following could be done:

```js
$('#calendar').fullCalendar({
    events:            '/api/events',
   startVariable:   'filter[where][date][$gte]',
   endVariable:    'filter[where][date][$lte]',
});
```

Which should convert to:

`/api/events?filter[where][date][$gte]'=2013-12-01&filter[where][date][$lte]=2014-01-12&_=1386054751381`.

That will be really awesome since will enable support for really dynamic and specific JSON APIs.

Documentation reference: http://fullcalendar.io/docs/event_data/events_json_feed/

**Comment by diosney** [comment]
Sorry, didn't found the `startParam` and `endParam` options while screening the API.

http://fullcalendar.io/docs/event_data/startParam/
http://fullcalendar.io/docs/event_data/endParam/

Maybe you can add them to http://fullcalendar.io/docs/event_data/events_json_feed/ so this doesn't happen with other people too? :)

**Comment by arshaw** [comment]
they're mentioned in the third paragraph. maybe ill bump it up
