### ISSUE TITLE
Event end date and display end date inconsistency

### ISSUE THREAD

**Issue by yuanjingxp** [fullcalendar/fullcalendar#3081]
hi arshaw:

Thank you very much to provide such a good assembly, I found this component has a display error.
Event end date and display end date inconsistency.
Specifically look at pictures!

browser: chrome 48.0.2564.109 m
os: win8.1
language region: chinese (zh-cn)

![bug](https://cloud.githubusercontent.com/assets/13447106/13600437/c298511e-e563-11e5-8afc-e7b71322be16.png)

**Comment by SirDre** [comment]
Ref: #3038

Otherwise: Try this solution -  http://www.cifullcalendar.com/v2/

**Comment by yuanjingxp** [comment]
thx!
