### ISSUE TITLE
DayGrid issue, each of null breaks scripts

### ISSUE THREAD

**Issue by hipio** [fullcalendar/fullcalendar#3082]
When I setup a very basic calendar I get a "_Uncaught TypeError: Cannot read property 'each' of null_"-error. This issue is ***not*** solved when I add events and it prevents the display of events, so I would say it's a pretty big bug. 

As requested I've made a JSFiddle containing everything I used (which is almost nothing): https://jsfiddle.net/nj5wk86g/1/

**Comment by hipio** [comment]
Alright, apparently this happend because I was using the latest of jQuery (3.0.0-beta1). I've reverted my webpage back to jQuery 2.1.4 and now everything works fine. It might be a good idea to add a warning to your Download/Get started page about this.

**Comment by arshaw** [comment]
thanks for the research. we'll reassess when jq 3.0 gets a little further along
