### ISSUE TITLE
Z-index issue for dragging external events from calendar back to 'external-events' list

### ISSUE THREAD

**Issue by mitomm** [fullcalendar/fullcalendar#3083]
Hi,

I'm trying to drag events from the calendar back to a list which has a z-index of 10.

I recreated the issue in the following codepen:
http://codepen.io/anon/pen/vGGBOE

Dragging an event from the list to the calendar works fine. However, while dragging it from the calendar back to the list, the event disappears behind the list (until released). Note that I set the z-index:10 of the events list on purpose (since that is required in my setting).

However, I wonder how I can influence the z-index of the events that are being dragged from the calendar back to the list (to a value higher than 10)?

Any help would be greatly appreciated.

Best regards,

Tom

**Comment by arshaw** [comment]
if you set `#calendar`'s css to `position:relative; z-index: 11`, it will work

**Comment by LonerganOnline** [comment]
I had the same issue but it was fixed by setting `position:relative; z-index: 11`  on the external dragable event and not the calendar container. I ahve eddited the above pen https://codepen.io/pen/vdLLgx
