### ISSUE TITLE
label slot times of agenda view not showed

### ISSUE THREAD

**Issue by WilliamPeralta** [fullcalendar/fullcalendar#3088]
I upgraded from 2.3.1 to the latest version, and now I do not see more labels of the boxes with the schedules , when I put "minTime: 08: 20 and maxTime: 23: 20" works well, but when I put "minTime: 08 : 10 and maxTime: 23: 10 "does not work anymore, I put as the interval "00:50:00 ",

With the previous version works well.

**the labels of slot times are not showed, sorry for my bad english ;)**
https://jsbin.com/xuwaqe/3/edit?html,output

**a simple solution **
https://github.com/fullcalendar/fullcalendar/pull/3075

**Comment by arshaw** [comment]
thank you. i re-opened #3088, and we'll use that issue

**Comment by arshaw** [comment]
sorry, i meant #3074
