### ISSUE TITLE
fullcalender stopped allowing custom function calls?

### ISSUE THREAD

**Issue by patilharshal16** [fullcalendar/fullcalendar#3089]
I wanted to add my custom click event on day but fullcalender won't allowing to fired my custom event.
Somehow i have added my custom checkboxes for every day like below.
`viewDisplay: function(view) {
	        $("#calendar .fc-view-month td").prepend('<input type="checkbox" class="myhtml"/>')
}`

While i am handling my event on click on class `myhtml` but it wont invoke.
For workaround i have removed dayClick and eventClick but still it won't able to get call.

**Comment by arshaw** [comment]
could you post a JSBin demonstration of why `dayClick` won't work?:
http://fullcalendar.io/wiki/Reporting-Bugs/

**Comment by patilharshal16** [comment]
I wanted to add custom call with including checkbox and on click of particular checkbox i wanted to block call execution of `evenclick/dayClick`.

Anyways somehow i manged to do this by appending my custom call using `dayRender.`

Thank You.
