### ISSUE TITLE
agenda event overlap consider computed width

### ISSUE THREAD

**Issue by lorinkoz** [fullcalendar/fullcalendar#3090]
As of now, when two or more events overlap in time, fullcalendar calculates the event width based on how many events are on parallel, using percentage widths. I'm doing a project where I must display a generic "availability" event along with actual events, so that a scheduler person may know when someone is available. I was trying to make the availability event 10px width, so that it doesn't interfere with actual events, but then, even if I managed to set the width of the target events, the overlapping events do not adjust the left property based on that and are displayed as if the former event was full width. Background events are not working for me here, as I have to move and resize availability.

![example](https://cloud.githubusercontent.com/assets/3628106/13744696/d2abdbd8-e9bf-11e5-94b8-1d3d07f0c6d4.png)

**Comment by arshaw** [comment]
will `slotEventOverlap:false` help you?
http://fullcalendar.io/docs/agenda/slotEventOverlap/

**Comment by lorinkoz** [comment]
Nope, I already have `slotEventOVerlap:false`, I just want to be able to set the width of events or eventSources and have the overlapping events adjust their `left` according to the width of the first event. In the picture, the event 8am-8.30am is still displayed with `left:50%` despite the overlapping event is not using 50% of the width.

**Comment by arshaw** [comment]
I see. How would you ideally like to set that 10px width? via CSS or through JS?

I'll keep this issue open in case others have the same need. Somewhat similar to #961 in that the event positioning internals need to be aware of compute dimensions.

**Comment by lorinkoz** [comment]
Ideally, this would be configured in an event or eventSource basis, including some `width` property in the object, such as:

    {
        ...
        width: '10px', // or '10%'
        ...
    }

Thank you so much for considering this :)

**Comment by lorinkoz** [comment]
Is there any way to contact you to discuss several tweaks for a custom version?

**Comment by lorinkoz** [comment]
Nevermind, someone posted an answer on my stackoverflow question that seems to be working as of now. https://stackoverflow.com/questions/35579749/increase-clickable-area-of-slots-behind-fullcalendar-event
