### ISSUE TITLE
feat: events should have appended same state classes like the day numbers

### ISSUE THREAD

**Issue by diosney** [fullcalendar/fullcalendar#3091]
For instance, fc-past, fc-future, fc-other-month, and so on.

This would help to style events in the same way as the day numbers.

Right now I have to add those classes manually in a custom `getEvents` source  and process each event to check it status.

**Comment by arshaw** [comment]
Would you expect multi-day events that are in the past AND future to have both classnames?

PS- your logic might be more appropriate in `eventRender`
http://fullcalendar.io/docs/event_rendering/eventRender/

**Comment by arshaw** [comment]
dup of #2875, and closing for the reasons mentioned in my [latest comment](https://github.com/fullcalendar/fullcalendar/issues/2875#issuecomment-225391209)
