### ISSUE TITLE
Display 24 hour time as 13:00 instead of 13.

### ISSUE THREAD

**Issue by enoch85** [fullcalendar/fullcalendar#3093]
As of today at least on the German locale and the Swedish locale (that uses 24 hour format) the time of whole hours are displayed as "13" instead of "13:00".

I would prefer it to be shown as 13:00 instead of how it's shown today. https://github.com/owncloud/calendar/issues/301#issuecomment-196498004

**Comment by hyperking** [comment]
@enoch85 did you try `timeFormat: 'H' `?
also see [documentation here](http://fullcalendar.io/docs/text/timeFormat/)

**Comment by georgehrke** [comment]
@hyperking The point is that we use the fullcalendar lang feature. So overwriting it is not really an option, as we would loose the localization feature.

**Comment by hyperking** [comment]
@georgehrke  perhaps using the options to define the time output would be of use. 
Not sure how overriding the time display format changes the localization. 
```js
$('#calendar').fullCalendar({
views:{
  month:{
    timeFormat: 'H:mm' //this will return 23:00 time format
     }
 }
});
```

**Comment by georgehrke** [comment]
Ah, sorry. I always presumed all the local files contained a custom time format, but they actually don't.
Sorry for the noise then :/

**Comment by georgehrke** [comment]
This issue can be closed from my pov then

**Comment by georgehrke** [comment]
but how does it now to use `h` for english and `H` for german then?

**Comment by arshaw** [comment]
you can override it for german specifically like this:

```
$.fullCalendar.lang("da", {
    timeFormat: 'H'
});
```

**Comment by georgehrke** [comment]
Thx :)
I appreciate your support!

**Comment by carlossavch** [comment]
on React you can do this:
slotLabelFormat={e => `${e.date.hour}:${e.date.minute <= 9 ? `0${e.date.minute}` : e.date.minute}`}

**Comment by Alireza-Mohammadhossein** [comment]
> on React you can do this: `` slotLabelFormat={e => `${e.date.hour}:${e.date.minute <= 9 ? `0${e.date.minute}` : e.date.minute}`} ``

you save my life man
