### ISSUE TITLE
Issue in Displaying events in FullCalendar in IE-11

### ISSUE THREAD

**Issue by dhawkKD** [fullcalendar/fullcalendar#3097]
Hi,

I am currently using FullCalendar in one of my project, By default I am showing Fullcalendar and its events, which is working as per expectation.
I have few filters on which I am filtering out the events, In IE-9 it is working, In chrome and Fire fox it is working.
When I upgrade things to IE-11, by default events are coming as expected but after filtering it with checkbox, events are not coming. I have dropdown also for filtering and it is also not working in IE-11. When clicking on Checkbox I am able to call my functions to fetch events and it is returning few records but not displaying it on Calendar, Same for dropdown and dropdown got hanged also.

I am able to get events on IE-9 but not on IE-11 when filtering data. Main issue is coming in month view.

Please help me in this.

Also I am trying to show tooltip on events it gets truncated in IE but in chrome and firefox it is working.

**Comment by arshaw** [comment]
https://github.com/fullcalendar/fullcalendar/blob/master/.github/ISSUE_TEMPLATE.md
