### ISSUE TITLE
2.7.0 beta doesn't allow event creation on touch devices

### ISSUE THREAD

**Issue by mooreds** [fullcalendar/fullcalendar#3104]
Hi folks,

This very well may be user error, but I am unable to get the demo below to work fully:

http://fullcalendar.io/js/fullcalendar-2.7.0-beta/demos/agenda-views.html

I can switch views, scroll around, and click the `<`, `>` and `today` buttons, but am unable to create an event, or edit an event using a touch device.

Here are the actions I tried:

* tapping on a blank space 
* tapping on an event
* pressing and holding on a blank space

All of the above do nothing.  I tested on safari on an ipad touch, on ios 7, usage agent string: "Mozilla/5.0 (iPad; CPU OS 7_1_2 like Mac OS X) AppleWebKit/537.51.2 (KHTML, like Gecko) Version/7.0 Mobile/11D257 Safari/9537.53" and chrome version 49.2623.105 on android 5.1.0 on a MotoX.

I reviewed the release notes and I believe that these are all supported actions, but again maybe I misread.

Thanks, am really excited about full mobile support.

**Comment by arshaw** [comment]
This is a better URL to demo: http://fullcalendar.io/js/fullcalendar-2.7.0-beta/demos/selectable.html
(i've updated the blog post)

Basically, what you can do in the demo is tap+hold to select regions of time and you can tap+hold to select existing events, which you can then drag and resize.

The demos currently do not offer a way to add new events similar to [this "External events" 2.6.1 demo](http://fullcalendar.io/js/fullcalendar-2.6.1/demos/external-dragging.html), but I might want to incorporate that.

**Comment by arshaw** [comment]
Please see my latest comment: http://fullcalendar.io/blog/2016/03/touch-support/#comment-2590774332
