### ISSUE TITLE
Define view's time window relative to natural start/end

### ISSUE THREAD

**Issue by Goddard** [fullcalendar/fullcalendar#3105]
It would be nice if you could create a calendar that had a rolling view.  So basically it could show like 2 or 3 weeks before and after the current date rather then just a fixed month.  

If I could just set startOfMonth and endOfMonth that would work as well.  Does something like this already exist?

Thanks

**Comment by arshaw** [comment]
Not currently possible, but will consider it for the API.

You might want to look at https://github.com/fullcalendar/fullcalendar/issues/2276 as well.

**Comment by arshaw** [comment]
API might looks like:

```
views: {
    customView: {
        type: 'month',
        startDate: { weeks: -1 },
        endDate: { weeks: 1 }
    }
}
```

or just

```
startDateTransform: { weeks: -1 },
endDateTransform: { weeks: 1 }
```

**Comment by arshaw** [comment]
if/when this is implemented, any calls to `gotoDate` should change the focal date of the view.

**Comment by frlinw** [comment]
It would be awesome if it were possible to override the start and end date with a moment object
```
views: {
    customView: {
        type: 'list',
        startDate: moment(),
        endDate: moment().add(1, 'year')
    }
}
```
Can be a solution for https://github.com/fullcalendar/fullcalendar/issues/3340

**Comment by arshaw** [comment]
This is now very possible in **v3.3.0**
Blog post: https://fullcalendar.io/blog/2017/03/fullcalendar-33-and-scheduler-16/

See [visibleRange](https://fullcalendar.io/docs/current_date/visibleRange/)
