### ISSUE TITLE
how to update event from external click event in fullcalendar

### ISSUE THREAD

**Issue by iamhimateja** [fullcalendar/fullcalendar#3107]
how to update the Event from an external click event..?

i have tried with default clickClick callback of fullcalendar, it worked,
but when i tried this returns an error

> fullcalendar.js:10549 Uncaught TypeError: Cannot read property 'clone' of undefined

i've found some questions and issues regarding the same error, but they didn't helped me..

for reference take a look at the code at http://codepen.io/himateja_hmtest/pen/dMzPZL

Here is the Javascript code

    var date = new Date();
    var d = date.getDate();
    var m = date.getMonth();
    var y = date.getFullYear();
    
    $('#calendar').fullCalendar({
        eventClick: function(calEvent, jsEvent) {
            var title = prompt('Event Title:', calEvent.title, {
                buttons: {
                    Ok: true,
                    Cancel: false
                }
            });
    
            if (title) {
                calEvent.title = title;
                $('#calendar').fullCalendar('updateEvent', calEvent);
            }
        },
      defaultView: 'agendaDay',
        header: {
            left: 'prev,next today',
            center: 'title',
            right: 'month,agendaWeek,agendaDay'
        },
        editable: true,
        events: [
        {
            id: 999,
            title: 'Some Title',
            start: '2016-03-29T09:00:00',
            end: '2016-03-29T10:00:00',
            allDay: false,
            status: 'checked in'
        }
        ]
    });
    
    $('button.tt').click(function() {
      var item = $("#calendar").fullCalendar( 'clientEvents', 999 );
      console.log(item[0].title);
      item.status = 'checked out';
      $('#calendar').fullCalendar('updateEvent',item);
    });

thank you..

**Comment by iamhimateja** [comment]
issue resolved..

by changing `item` to `item[0]`

My bad.. :D

**Comment by alyssa19** [comment]
@iamhimateja I'm using fullcalendar in my angular project but to be honest I'm having a hard time in jQuery to update and to get the ID. Can you help me with this one?

**Comment by mui-le** [comment]
> issue resolved..
> 
> by changing `item` to `item[0]`
> 
> My bad.. :D

Thanks, I also get it!
