### ISSUE TITLE
Undefined instead of month name in Russian translation

### ISSUE THREAD

**Issue by panda1111** [fullcalendar/fullcalendar#3108]
If I apply Russian translation, I see "undefined" instead of month name in             
header: { center: 'title'}

Demo: http://jsbin.com/huzakovoje/edit?html,js,output

**Comment by arshaw** [comment]
thanks

**Comment by arshaw** [comment]
this seems to be fixed upon upgrading moment and fullcalendar to the latest versions:
http://jsbin.com/bolemimomu/1/edit?html,output
