### ISSUE TITLE
Double color for single event

### ISSUE THREAD

**Issue by loreberti89** [fullcalendar/fullcalendar#3109]
I've been used full calendar for registering appointments. 

But now, I have a problem: Can I set a double color for single event? Because I've to register a "extra start time" to event but the color needs to be different.

Example:

If i have an event that starts at 10.pm , I need to do start that event at 8.pm but 2 hour of difference need to be different color.

**Comment by arshaw** [comment]
im not sure i understand. it would be really helpful if you could post mockups

**Comment by loreberti89** [comment]
This is what I wanted to do.
I have resolved in this way.
I have created a new event above the "real" event, with same Id.
But my Questions was:
Can I fill  SINGLE event with 2 color as below?

![travel](https://cloud.githubusercontent.com/assets/16079475/14527940/3f34dbf6-024d-11e6-8738-eeb82717071b.png)

**Comment by arshaw** [comment]
oh, so you want to fill the "empty" "available" space with something visual?

the way you are going about it, doing two events, is the best workaround.

the API could be modified to somehow make this more convenient, but i'll wait to see if other people also need this before taking any further action

**Comment by loreberti89** [comment]
in reality, the empty space above "real" event, in this moment is a calculation by gps distance (by google api) from 2 event that have an gps property .
But the idea is can set one color from hour and set another color for another hour for the same event.
Maybe this mockup is more clear.

however thank's for your attention!

![travel](https://cloud.githubusercontent.com/assets/16079475/14528784/8c339448-0251-11e6-837f-c7192b621712.png)

**Comment by MartijnWelker** [comment]
+1, i would like this introduced in background events for ex. when you're on the month view and a person has 2 background events on a day you could give it both background event's colors.

**Comment by kazelsama** [comment]
+1

**Comment by arshaw** [comment]
@loreberti89 et al, I'm nearly certain you are asking for the same thing as #3174. I'm going to use that ticket for the convo.  Could you please visit #3174, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates? This will help be determine overall demand. Thanks!

**Comment by mikository** [comment]
The best workaround would be to apply css3 gradient with needed colors

**Comment by Edwardiv1** [comment]
> The best workaround would be to apply css3 gradient with needed colors

@mikository Sounds like a good approach while we wait for this to be implemented natively. Any code examples of how to go about doing what you suggest?
