### ISSUE TITLE
eventResize blocks if start date of event is before start date of background event

### ISSUE THREAD

**Issue by dfoxxdfoxx** [fullcalendar/fullcalendar#3111]
When i try to resize an event that is on top of a background but the startdate of the event is before that of the background it is not possible to resize the event.
It also does not apear in the eventOverlap function.

For example:
See the events in the week view, Wed 1/13 of Jan 10 — 16, 2016
[http://jsbin.com/pagicojeli/edit?js,output](http://jsbin.com/pagicojeli/edit?js,output)

**Comment by arshaw** [comment]
the problem is that the event is starting out on an invalid span of time because of the `constraint: 'availableForMeeting'` you have made... the solution is to ensure no events start out like this
