### ISSUE TITLE
Multiple BusinessHours (not work)

### ISSUE THREAD

**Issue by kleytonbarcelos** [fullcalendar/fullcalendar#3112]
I would like to report a problem in FullCalendar. When you insert a multiple businesshours ex.

businesshours:
[{
start: '09: 00 '
end: '13: 00 '
dow: [1,5]
},
{
start: '12: 00 '
end: '13: 00 '
dow: [3]
}]

It is not working on the latest version of FullCalendar (2.6.0 and 2.7.0-beta), marks every day with the values of the Object [0]. Please see the complaint proceeds and fix the bug.

Att, Kleyton - IT Analyst - Esp. Santo, Brazil.

**Comment by espen** [comment]
It's not working because it is not supported. See http://fullcalendar.io/docs/display/businessHours/

Please follow #2686 for this feature request.

**Comment by kleytonbarcelos** [comment]
In version 2.3.1 and 2.5.0 (works). Only in the other part of the code font that comes to receiving the BusinessHour data, is not receiving object: [{}], only gets one Object {}.

This has no solution in the new versions?

**Comment by matheusjardimb** [comment]
I'd like to see that too :)

**Comment by arshaw** [comment]
plz subscribe to #2686
