### ISSUE TITLE
Demos aren't working

### ISSUE THREAD

**Issue by davidkhasikyan** [fullcalendar/fullcalendar#3114]
Demo files are not working because of broken links in head section. They're linking to the folder "dist" which doesn't exist.

**Comment by arshaw** [comment]
can you point me to the link where you are seeing this?

**Comment by alejosv** [comment]
I have the same issue, when "basic-views.html" loading the next files:

`<link href='../dist/fullcalendar.css' rel='stylesheet' />`
`<link href='../dist/fullcalendar.css' rel='stylesheet' />`
`<link href='../dist/fullcalendar.print.css' rel='stylesheet' media='print' />`
`<script src='../lib/moment/moment.js'></script>`
`<script src='../lib/jquery/dist/jquery.js'></script>`
`<script src='../dist/fullcalendar.js'></script>`

Attach image
![fullcalendar-error](https://cloud.githubusercontent.com/assets/14202497/14827819/68925bce-0ba1-11e6-8e3b-6b8fd88cc926.png)

**Comment by davidkhasikyan** [comment]
Yes demo files don't work becuse dist folder doesn't exist so the only solution is use cdn.

http://fullcalendar.io/download/

**Comment by arshaw** [comment]
yes, use the built download, or if you want to use the dev repo, you'll need to run the build scripts to build the dist folder
