### ISSUE TITLE
Showing tooltip in Android

### ISSUE THREAD

**Issue by jjorge01** [fullcalendar/fullcalendar#3116]
Hi, i'm facing a problem using fullcalendar at mobile.
When i first touch a task it shows the tooltip but automatically enters task detail.

Expected behaviour
(@Iphone works great)
At first touch shows tooltip, at second redirects for data detail.

Thanks,

**Comment by arshaw** [comment]
Fullcalendar does not support a "tooltip" feature, nor a "task detail" feature out-of-the-box, so I'm wondering where/how you are seeing this
