### ISSUE TITLE
Dynamically change firstDay

### ISSUE THREAD

**Issue by lorinkoz** [fullcalendar/fullcalendar#3120]
A popular view for calendars nowadays is "next seven days" week view style, where you can check the upcoming events for the next week with today as the leftmost column. This can be achieved by re-rendering the calendar with `firstDay` equal today's day code, however, a full `destroy` operation is required and one needs to recreate the calendar after that, reloading all event sources, etc.

Is there a way to implement a dynamic change for `firstDay`? One could do something like `$("#calendar").fullcalendar("option", "firstDay", 4)`

**Comment by arshaw** [comment]
the solution presented in #3105 would probably be better from an API perspective. plz subcribe

**Comment by arshaw** [comment]
#564 would also be a solution
