### ISSUE TITLE
Enable and Disable cells for specific dates in fullcalendar

### ISSUE THREAD

**Issue by Anithacld** [fullcalendar/fullcalendar#3125]
Hi,

I need to enable and disable cells for specific dates in resource view. Means i want to enable or disable cells depending upon my resource availability. 

If my resource available, i want to enable and create event.

If my resource not available, i should disable click option and also need to change background color to identify its disabled.

Kindly provide me the solution to do above mentioned. Thanks in advance.

**Comment by arshaw** [comment]
http://fullcalendar.io/docs/event_rendering/Background_Events/
http://fullcalendar.io/docs/event_ui/eventOverlap/

**Comment by ATouhou** [comment]
Hey Anithacid  did you complete what you were making?

**Comment by urmamb** [comment]
If `selectable` is set to `true`, Background_events are still selectable.

**Comment by santoscarlo** [comment]
how can i integrate to disable a date cell in full calendar. when reach the limit of the appointment. example the appoinmeny number is 5 when slot is accomodate. the date cell is turn into disable. thanks a lot

**Comment by Damercy** [comment]
I know this issue is closed but since nobody seems to have answered concretely, I'm commenting a solution I found on the fullcalendar docs. Seems like we need to use `validRange` object property to specify those dates that will **not** be disabled (which just means that the dates that are invalid will be disabled). Check [this out](https://fullcalendar.io/docs/validRange)!

Hope this helps! 👍

**Comment by erikkubica** [comment]
> I know this issue is closed but since nobody seems to have answered concretely, I'm commenting a solution I found on the fullcalendar docs. Seems like we need to use `validRange` object property to specify those dates that will **not** be disabled (which just means that the dates that are invalid will be disabled). Check [this out](https://fullcalendar.io/docs/validRange)!
> 
> Hope this helps! 👍

@Damercy this is not corrent naswer. validRange allows to select dates only in range of continuous dates. for example from X to Y. But it cannot block dates selectively, ex.: April 1., February 5 are not allowed but anything else is.

**Comment by AnkitSemwal007** [comment]
> how can i integrate to disable a date cell in full calendar. when reach the limit of the appointment. example the appoinmeny number is 5 when slot is accomodate. the date cell is turn into disable. thanks a lot

did you have find how to disable dateClick  for particular date like you were saying when slots are full that date will be disable

**Comment by techwebdev** [comment]
> > how can i integrate to disable a date cell in full calendar. when reach the limit of the appointment. example the appoinmeny number is 5 when slot is accomodate. the date cell is turn into disable. thanks a lot
> 
> did you have find how to disable dateClick for particular date like you were saying when slots are full that date will be disable

any solution ?

**Comment by zahoor-avion** [comment]
is there any solution for this problem...?
i also need to display only some unique multiple dates on calendar and hide/disable all other dates.
like to show availability for dates some specific dates Aug-1,Aug-3, Aug-6, Aug-8.

is this feature available in premium version ..?

**Comment by DanB-dev** [comment]
Hi, I'm not sure how much this helps you but inside of my Next.js + Typescript Calendar I'm using this function to check if the date is between two dates.
```typescript
const checkForBreak = (
  selectInfo: DateSelectArg,
  handleShow: (addEvent: string, selectInfo?: DateSelectArg) => void
) => {
  const daysAfter = new Date(
    selectInfo.end.getFullYear(),
    selectInfo.end.getMonth(),
    selectInfo.end.getDate() - 1
  );

  const daysBefore = new Date(
    selectInfo.start.getFullYear(),
    selectInfo.start.getMonth(),
    selectInfo.start.getDate() + 1
  );
  if (daysBefore < new Date('2022-08-05') || daysAfter > new Date('2022-08-10'))
    handleShow('addEvent', selectInfo);
};```

I'm then Defining an event that matched those dates and using that as the visual indicator the days aren't choosable.
```typescript
  {
    id: createEventId(), //Function to generate an auto_incremented Id.
    title: 'Break',
    start: '2022-08-05',
    end: '2022-08-11',
    constraint: {
      start: '2022-08-05',
      end: '2022-08-11',
    },
    overlap: false,

    color: '#257e4a',
    extendedProps: {
      content: 'Break',
    },
  },
```

To be clear this is my first attempt at this and I'm very new to the fullCalendar docs so this may be really dumb, but it does work.

**Comment by prasath0908** [comment]
Venthu thaninthathu kadu.... full calenderku vanakatha podu

**Comment by Blur4** [comment]
> Hey Anithacid did you complete what you were making?





https://lnkr.fun/d6602b7
