### ISSUE TITLE
Inconsistent behaviour of gotoDate with custom view

### ISSUE THREAD

**Issue by Nilpferdschaf** [fullcalendar/fullcalendar#3126]
http://jsbin.com/warokikama/1/edit?js,output

I have set a custom view to display a time range of 10 days. In the JSFiddle, I call a function every second that moves the calendar forward by one day using gotoDate. As you can see, nothing happens for the first 10 seconds, then the calendar jumps the full 10 days.

It's not exactly expected behaviour, but what is worse is, if you replace the i++ with i--, fullcalendar jumps back a single day every second. 

You can also jump fowards in chunks of 11 days without problem. It only doesn't work if it's 9 days or less.

What I think should happen is that you can jump forwards and backwards by single days every time, however, it would also make sense if you could only jump back in multiples of 10 days. In any case, it should be consistent.

**Comment by arshaw** [comment]
whenever you want to jump forward, you should be jumping by intervals of 10 days because the duration of the view is 10 days. updated fiddle: http://jsbin.com/quyakunoya/1/edit?js,output

**Comment by Nilpferdschaf** [comment]
But why is it possible to go back in decrements of single days?

**Comment by arshaw** [comment]
Because the "current day" is the *first* day in your view, and if you move back a single day, there are no more days before it currently visible, so it needs to iterate to the previous week.

**Comment by arshaw** [comment]
FYI, when u change the current day, and it is already within the currently displayed view, it doesn't do anything
