### ISSUE TITLE
agenda view has extra space at bottom due to explicit height on fc-time-grid-container

### ISSUE THREAD

**Issue by mmmmmrob** [fullcalendar/fullcalendar#3128]
http://jsbin.com/pedobacemu/2/edit?js,output

div class="fc-time-grid-container" style="height: 884px; overflow: hidden;"

fc-time-grid-container is given extra height than necessary for the calendar view, leading to an extra area of calendar space below timed slots.

**Comment by arshaw** [comment]
if you do `height: 'auto'`, you should get the desired behavior.

if you want the slots to be variable-height in order to expand to fill the space, see https://github.com/fullcalendar/fullcalendar/issues/265

**Comment by peio72** [comment]
I have same problem: little vertical scroll bar on month view with height:auto
I fixed this with: 
.fc-scroller.fc-day-grid-container {
    overflow-y: hidden !important;
}
waiting for a better upgrade.
