### ISSUE TITLE
Purge function not removing events from all views, could be me, is there a better option to do the same?

### ISSUE THREAD

**Issue by StudioJunkyard** [fullcalendar/fullcalendar#3131]
Not sure if this is a Bug, or just me.

Using purge(event.id,"content"); removes event from current view, but if you switch to another view, i.e. week, or day. The event is still present, and shows as still present when going back to the view the event was originally removed from.

Is there a better function to use to remove events from all views, or do they need to be removed from each view individually.

**Comment by arshaw** [comment]
what is this `purge` function? i've ever heard of it

**Comment by StudioJunkyard** [comment]
WOW, nice support there brother.

I think purge could be a jquery function, I'm using it within FC to remove events from the Calendar without refreshing, if it's not an FC function then that would explain why it's not doing what I need.

Should I be using eventDestroy() function instead?

**Comment by StudioJunkyard** [comment]
For those that would like a proper answer to this:

`$('#calendar').fullCalendar('removeEvents', event.id);`
