### ISSUE TITLE
Remove the word "fuck" from JS comments

### ISSUE THREAD

**Issue by eddielee6** [fullcalendar/fullcalendar#3132]
Content filters block loading of fullcalendar.js due to it containing the phrase "fuckin IE8" in a comment.

This comment is a new addition in v2.7.0

DeviantART actually had this exact problem a few years ago http://dt.deviantart.com/journal/We-Give-a-F-How-the-Site-Loads-392679726

**Comment by rahulrulez** [comment]
Wow, that's a good find.. Sonicwall you have? I am assuming..

**Comment by arshaw** [comment]
released via 2864289061ca5ed761695aaf8d1132bb8dfd19a5
