### ISSUE TITLE
Last chrome update breaks eventMouseover and eventMouseout

### ISSUE THREAD

**Issue by vagyriag** [fullcalendar/fullcalendar#3134]
[jsBin](http://jsbin.com/wiketu/5/edit?js,console,output)

the eventMouseover and eventMouseout just doesn't fire anything, everything was working just fine until the update 

I already filled an issue in chrome but... don't know 

The update is v 50.0.2661.87, from april 20
[release](http://googlechromereleases.blogspot.com.co/2016/04/stable-channel-update_20.html)

not sure if should post this here but I'm having troubles with that... thanks

**Comment by StudioJunkyard** [comment]
OS might help. Mine updated today in Linux Mint 17.3, no such issue's here.

**Comment by vagyriag** [comment]
I'm on Windows 10 V 10.0.10586 Build 10586, last update

**Comment by arshaw** [comment]
working okay for me. probably fixed in 2.7.2
https://github.com/fullcalendar/fullcalendar/releases/tag/v2.7.2
