### ISSUE TITLE
Single quote in title breaks calendar

### ISSUE THREAD

**Issue by s3am** [fullcalendar/fullcalendar#3135]
Hi there

Noticed that single quotes in title break  the calendar : http://jsbin.com/xuxamohoyu/edit?js,output

I'm actualy using a php rule to replace single quotes with apostrophes. Any chance to get that fixed out of the box.

Best regards

**Comment by mdxs** [comment]
Issue can be closed, the `title: 'All Day's Event',` in the provided example is simply invalid Javascript syntax. Change it to `title: "All Day's Event",` or `title: 'All Day\'s Event',` and it works just fine.
