### ISSUE TITLE
popover for +more, positioned incorrectly when scrolled down

### ISSUE THREAD

**Issue by virtualvoid** [fullcalendar/fullcalendar#3137]
Here is jsbin: http://jsbin.com/fujusa/1

and screenshots (in case you don't have MS Edge) :

edge (incorrect)
![fc_popover_edge](https://cloud.githubusercontent.com/assets/234315/14817590/8e8d8cf6-0bb8-11e6-8328-776e6bf11e06.png)

ff (correct)
![fc_popover_latest_ff](https://cloud.githubusercontent.com/assets/234315/14817591/8e92119a-0bb8-11e6-90ac-f3ccf373fc2d.png)

**Comment by caseyjhol** [comment]
It's rendering the same in Google Chrome 49.0.2623.112 (Windows 10) as it is in Microsoft Edge.

**Comment by virtualvoid** [comment]
I haven't tested Chrome yet, but as you can see on the screenshots, there are differences between edge and ff.

**Comment by virtualvoid** [comment]
Well, I think I've figured it out but still unsure if it's correct solution.

I've played with CSS styles of the **div.fc-scroller.fc-day-grid-container**, and changed the inline style from:

overflow-x: hidden;
overflow-y: hidden;

to:

overflow-x: auto;
overflow-y: auto;

and the popovers are now displaying correctly inside MS Edge. Please see attached screenshots.

![fc2_popover_edge_01](https://cloud.githubusercontent.com/assets/234315/14844283/aa130674-0c56-11e6-8ffc-29a98917e1d2.png)
![fc2_popover_edge_02](https://cloud.githubusercontent.com/assets/234315/14844284/aa133644-0c56-11e6-8767-2550a2f26eac.png)

how can be this fixed in code ?

**Comment by virtualvoid** [comment]
Allright, here are more details:

1) if you open this link http://output.jsbin.com/fujusa/1 in maximized browser window, the bug can be seen - popover is cut from bottom.

2) now resize browser window bit, just to show vertical scrollbar and press "+16 more" button again. the popover will be displayed correctly.

If that's not enough, i've created video : https://youtu.be/KP02OBmZrTU

**Comment by arshaw** [comment]
thanks for the extensive bug report

**Comment by arshaw** [comment]
to fix this bug, the best solution is to have the popover div NOT be within the scroll container, unlike it is now. however, making that happen is a bit complicated, esp considering event delegation is used to capture actions on the events within the popover. will address this with a proper bugfix in the future, but your workaround works, however it disables the ability to scroll vertically if the calendar's height is squished, which is somewhat uncommon

**Comment by arshaw** [comment]
note to self: this was easy to make happen in Google Chrome for me

**Comment by virtualvoid** [comment]
For anyone who came across this issue, the workaround is this :

in fullcalendar source find this method and put **return** statement before any calculations are made.

`lockOverflow: function(scrollbarWidths) { return;`

that's should do the trick.

**Comment by arshaw** [comment]
thanks for the work @virtualvoid

**Comment by zhangwei900808** [comment]
Hi 
I dont understand how to solve the problem
please tell me thanks

**Comment by zhangwei900808** [comment]
I was wirte the code lockOverflow: function(scrollbarWidths) { return;}
but not solve my problem

**Comment by virtualvoid** [comment]
@zhangwei900808 That's not the right place. Open up `fullcalendar.js` and find the method called `lockOverflow`, if I recall correctly, it should be around the line 8881.

**Comment by arshaw** [comment]
this has been fixed and release in [v2.9.1](https://github.com/fullcalendar/fullcalendar/releases/tag/v2.9.1).

Was fixed for free while attacking #3232

**Comment by bhaumikgithub** [comment]
Hi
I have checked with all solution but it did't work for me
![calendar-popover](https://cloud.githubusercontent.com/assets/20111383/17361823/faabe8d6-598f-11e6-9d4f-7c10f745d64c.png)

I was selected 1st aug and popover is displaying at bottom of calendar, and strange is that click again on 1st aug popover is not showing

**Comment by arshaw** [comment]
@bhaumikgithub could you post a [Reduced Test Case Recreation](http://fullcalendar.io/wiki/Reduced-Test-Cases/) in another ticket?

**Comment by kaynami** [comment]
Class ".fc-controller" is the issue:
force css overflow to visible under eventRender();
solution:
$('.fc-scroller').css('overflow','visible');

**Comment by bhaumikgithub** [comment]
@kaynami 
This is not solution, i want to show popover at same place from where i click more events.

**Comment by sathyaprakash94** [comment]
One more issue, I need to drag and drop the fc-more-popover window anywhere inside calendar window. I tried to enable 'draggable: true;' but it applies to the full-calendar not only popover window. 

anypne pls help to solve this.

**Comment by sathyaprakash94** [comment]
Hi there,
How to make .fc-popover window draggable. Pls anyone help me.

**Comment by grandhisubrahmanyam35** [comment]
I am using fullcalendar v3.2.0. 

Tried all above approaches but not working any of the above solutions.

**Comment by bwaghmare** [comment]
@arshaw I am using version 2.91, still not working above issue
