### ISSUE TITLE
dayClick on touch devices not firing

### ISSUE THREAD

**Issue by arshaw** [fullcalendar/fullcalendar#3138]
From Dan:

> I think I found an issue with the latest version of FullCalendar. I grabbed your latest official release and was testing it on my iPad (and iPhone). The touch features look amazing, but I think the "dayClick" event is not firing on touch devices with this new version.
>
> I've created a demo here (it should open an alert box when the day is clicked, but nothing happens on iOS). Can you confirm and let me know if this is something that you are able to solve?

http://jsbin.com/zimepupago/edit?js,output
http://output.jsbin.com/qibonuxoru/1

I can confirm this.

the delay is wrongfully required for dayClick interaction on touch
https://github.com/fullcalendar/fullcalendar/blob/master/src/common/Grid.js#L266

**Comment by arshaw** [comment]
fixed and released in v2.7.1
https://github.com/fullcalendar/fullcalendar/releases/tag/v2.7.1

**Comment by gigmaps** [comment]
unfortunately dayClick still does _NOT_ appear to be working in version 2.7.1 - at least on iOS devices

please try dayClick on the following jsfiddle which use the latest 2.7.1 from cdnjs.cloudflare.com:
https://jsfiddle.net/goredwards/92ftf0j4/

Note that when testing the jsfiddle, the other fullcalendar buttons work (today, month+1, month-1 etc) on mobile and in browser emulators

Note also  dayClick is not working in mobile / touch emulators (any device type) for either Chrome or Firefox (again, test the jsfiddle in either browser's emulator)
...makes dev rather difficult.
