### ISSUE TITLE
Click events error on background events 

### ISSUE THREAD

**Issue by spikeon** [fullcalendar/fullcalendar#3148]
http://jsbin.com/layozolaxu/edit?css,js,output

When using click handlers on background events, only the last background event will fire.  This is due to the stacked tables.  I have implemented a fix on my site, but it's not working in the fiddle, i don't know why. 

You'll notice that if you click on the first background event the alert will not fire, but it will on the second background event. 

I have included the code that worked on my site in the CSS.  It's not working in the fiddle, but It's probably still good for reference.

**Comment by spikeon** [comment]
You can see my fix working here: http://www.5ppdev.com/web/englishlessonhub/teacher.php?id=19

**Comment by arshaw** [comment]
are you proposing that when the user clicks, ALL background events underneath should have their `eventClick` fire, or would you like more control over which event is considered the "top" event that will receive the clicks (similar to #2895)?

**Comment by spikeon** [comment]
This was a while ago, but I believe that the days were stacking on top of each other; so you'd go to click monday but friday would be covering it up and would instead get the click

**Comment by arshaw** [comment]
i'm realizing this new issue is the same thing:
https://github.com/fullcalendar/fullcalendar/issues/4750
&uarr;
Could you please visit the link, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates?
