### ISSUE TITLE
dayClick's jsEvent object doesn't populate "pageX" and "pageY" properties on touch devices

### ISSUE THREAD

**Issue by dancintony** [fullcalendar/fullcalendar#3150]
On touch devices when the dayClick event is fired, the "jsEvent" object's "pageX" and "pageY" properties are undefined. See jsbin below for a working example, just click on any day to see a popup with the issue. (Tested on both iOS 9.3 and Android Chrome)

This issue does NOT affect non-touch devices.

**Version:** 2.7.1
**Demo:** http://jsbin.com/gowabejexe/edit?js,output

**Comment by arshaw** [comment]
Hello, this is because the jQuery event is getting bubbled up, which doesn't support that property, but here is a workaround you can use: http://stackoverflow.com/a/7251175/96342

**Comment by dancintony** [comment]
For anyone else who runs into this, here's the snippet that got me around this problem (so you can get the pageX and pageY for both touch and non-touch devices):

```
var pageX;
var pageY;

if (jsEvent.pageX != undefined) 
{
    pageX = jsEvent.pageX;
    pageY = jsEvent.pageY;
} 
else if (jsEvent.originalEvent.changedTouches != undefined)
{                            
    pageX = jsEvent.originalEvent.changedTouches[0].pageX;
    pageY = jsEvent.originalEvent.changedTouches[0].pageY;
} 
```
