### ISSUE TITLE
refetchEvents triggers scroll reset in month view

### ISSUE THREAD

**Issue by fongandrew** [fullcalendar/fullcalendar#3153]
Calling `fullCalendar('refetchEvents')` causes the `.fc-scroller` container to loses its scroll position. This looks like the same issue reported at https://github.com/fullcalendar/fullcalendar/issues/2970. This appears to only affect the `month` view and not `agendaWeek`.

JSFiddle repro: https://jsfiddle.net/fongandrew/zramLyqu/3/

Just scroll down in the main calendar view and then click the "refresh" button at the bottom.

**Comment by fongandrew** [comment]
Poking around some more -- it appears that the refetch is clearing all of the events inside the month view, which in turn affects the scroll position of the `.fc-scroller` container. When refetch adds new events, the scroll position is now set at whatever `scrollTop` was when the events were cleared.

I guess the fix would be to remember the `scrollTop` *before* the events are cleared and then reset it after the event fetch callback is triggered.

Alternatively, maybe I should be using the `updateEvent` call rather than `refetchEvents`? It's not quite as nice as just refetching a new list of events though since I have to diff the lists and match the old events with the new ones.

**Comment by caseyjhol** [comment]
Implementing my PR (#3123) that removes the call to destroyEvents looks like it fixes this issue. See http://plnkr.co/edit/m5Qd0HdkyeYMc40CvuEO?p=preview

**Comment by arshaw** [comment]
this must have been fixed in recent versions. i plugged in v3.3.1 and it works:
https://jsfiddle.net/zramLyqu/5/
(i needed to adjust the event function slightly, but that's beside the point)

**Comment by caseyjhol** [comment]
Yea, this was fixed back in 2.8.0.
