### ISSUE TITLE
control formatting of text on day cells

### ISSUE THREAD

**Issue by gbcox** [fullcalendar/fullcalendar#3155]
There is no option to display ordinal date (day of year).  It can be calculated via Method:
http://fullcalendar.io/docs/utilities/Moment/
http://momentjs.com/docs/#/displaying/

Thanks!

**Comment by arshaw** [comment]
the `DDD` and `DDDD` formatters? I would expect this to work in FullCalendar with no work required (simply gets passed on to moment). Could you post a JSBin example of this not working? http://fullcalendar.io/wiki/Reporting-Bugs/

**Comment by jasonsavard** [comment]
I think what @gbcox is asking is where is the option in FullCalendar to display the day of the year instead of the date (or maybe alongside the date) in each day cell within the month view etc.

**Comment by mdxs** [comment]
See https://jsfiddle.net/wijgerden/n7cmf5jm/ which basically uses:
```
var cal = $('#calendar').fullCalendar({
  dayRender: function( date, cell ) {
    cell.html(date.format('\#DDDD'));
  }
});
```
to put the ISO Day of Year ordinal in each day cell as well.

**Comment by jasonsavard** [comment]
Awesome @mdxs thank you very much.

**Comment by arshaw** [comment]
Thanks for the workaround @mdxs. @gbcox et al, let me propose a more universal universal API. Some new settings:

- `dayFormat` - which could be set to formatting strings like `DDDD`
- `dayText` - which will accept a function, to programmatically generate text. Useful if you want to include the month name on only the first day of the month.

**Comment by Kvodnon** [comment]
Same here.

**Comment by arshaw** [comment]
v4/v5 use the Intl API now. I'm not sure if the Intl API has this functionality or not: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/DateTimeFormat/DateTimeFormat

If it doesn't you'll need to compute the day-of-year yourself and then return it as text in the `dayCellContent` hook. https://fullcalendar.io/docs/day-cell-render-hooks
