### ISSUE TITLE
Is it possible to show the events one below the other like the image?

### ISSUE THREAD

**Issue by cesaryamil** [fullcalendar/fullcalendar#3158]
### Bug Reports
I arshaw.
Thaks for your answer, fullcalendar it is good job congratulations. Arshaw i need show events in 
agendaWeek similar basicWeek. events display vertical not horizontal .it's possible? 
View image please,
Sorry my english is not perfet. 

Instructions: http://fullcalendar.io/wiki/Reporting-Bugs/
![calendar events deseado](https://cloud.githubusercontent.com/assets/856841/15190267/9d504bd0-1774-11e6-84bd-a542eac0ef24.png)

### Feature Requests
Search the issue tracker for an existing ticket before creating a new one.
Instructions: http://fullcalendar.io/wiki/Requesting-Features/

(Please erase the above text and begin typing. Thanks!)

**Comment by cesaryamil** [comment]
Hi im prepared for paid for it.

**Comment by caseyjhol** [comment]
How would this work? You would have to expand the row height, as your current example shows a 12:25 event as occurring at 13:00. So then you would have rows of random heights. Seems like it would be confusing. You'd probably be better off using Timeline view (https://github.com/fullcalendar/fullcalendar-scheduler).

**Comment by cesaryamil** [comment]
the height of the event would same , but the size slot would increment.

**Comment by cesaryamil** [comment]
Hi.
Thanks for your answer.
The events should have the same height, what we want is to increment the width of the event and the next ones should appear one below the other. The container should increment its size on the week view.
![calendar deseado increment](https://cloud.githubusercontent.com/assets/856841/15231472/081456ae-1861-11e6-91bb-34258f3f4a69.png)

**Comment by arshaw** [comment]
this is currently not possible, and as @caseyjhol brings up, there are UX concerns here
