### ISSUE TITLE
event dragging wrongfully begins upon scrolling document

### ISSUE THREAD

**Issue by dancintony** [fullcalendar/fullcalendar#3160]
In our application we change the height mode manually depending on the view being displayed. When the following code is called:
$('#calendar').fullCalendar('option', 'height', 'auto');
It causes the events to 'drag' when a scroll action is initiated by touching an event first. This is an issue for users who are trying to scroll their calendar as they are accidentally moving their events after the 1st second.

I was able to verify this issue on both iOS and Chrome (desktop browser in 'Device' mode). If the calendar is set to auto height on initialization it works as expected.

Jsbin demo is located here (you might need to resize your browser so that the calendar pane scrolls):
http://jsbin.com/bekehuvago/edit?js,output

**Comment by arshaw** [comment]
I'm able to reproduce, even with setting `height: 'auto'` on initialization (w/o using the method).

This wasn't the case upon release. Might have been a Chrome update.

Always accompanied by the following errors:

![screen shot 2016-05-18 at 9 08 40 pm](https://cloud.githubusercontent.com/assets/56520/15382206/bcc52a44-1d3c-11e6-82f0-e1e68a06ae58.png)

**Comment by arshaw** [comment]
this is fixed in [v2.7.2](https://github.com/fullcalendar/fullcalendar/releases/tag/v2.7.2). could you please verify?

**Comment by dancintony** [comment]
Just did some initial testing and it looks good! Thanks for the speedy fix.
