### ISSUE TITLE
more显示不全

### ISSUE THREAD

**Issue by zhangwei900808** [fullcalendar/fullcalendar#3161]
![image](https://cloud.githubusercontent.com/assets/4385154/15237304/273a579c-18ff-11e6-83c6-5d989c12285a.png)

这个怎么解决啊

**Comment by arshaw** [comment]
duplicate of #3137; could you please vote for it ( 👍 ) and press the **Subscribe**  button to receive future updates?

**Comment by zhangwei900808** [comment]
![image](https://cloud.githubusercontent.com/assets/4385154/15279429/eafc3f8e-1b56-11e6-862f-6baa73c73681.png)
its OK，I set the parent postion:absolute!
Thanks

**Comment by arshaw** [comment]
@zhangwei900808 could you please give a 👍  on #3137, NOT on this issue or any of the comments in this issue.
