### ISSUE TITLE
how can I add image to the event?

### ISSUE THREAD

**Issue by zhangwei900808** [fullcalendar/fullcalendar#3166]
eg:
![image](https://cloud.githubusercontent.com/assets/4385154/15283939/b8fb375e-1b80-11e6-9833-fcde3f76d602.png)

**Comment by zhangwei900808** [comment]
Hi，
I implement the features，you can see it！

![image](https://cloud.githubusercontent.com/assets/4385154/15391948/ace1616e-1df6-11e6-8f33-00805bcf063f.png)

**Comment by arshaw** [comment]
http://fullcalendar.io/support/
"Getting Help"

**Comment by sandeepsparity** [comment]
Can some one tell me how to display the background images based on the json data on full calender?
