### ISSUE TITLE
Extend event horizontally beyond resource column

### ISSUE THREAD

**Issue by jeremymcminn** [fullcalendar/fullcalendar#3169]
I'm not sure if this is too specific as a feature request, but would like to be able to extend an event beyond the resource that it is attached to (i.e so it covers two columns instead of the one - see mockup attached)

If too specific, possible hacks to make it happen?

![screenshot from 2016-05-17 14 03 16](https://cloud.githubusercontent.com/assets/6614789/15323107/3cfeb46a-1c38-11e6-9e78-6bed4f100751.png)

**Comment by jeremymcminn** [comment]
Some simple jquery with eventAfterRender does the trick here in case anyone else requies this.

```
eventAfterRender: function (event, element) {
    width = element.closest('td').width();
    columns = event.columns;
    total_width = width * columns;
    element.css('width', total_width + 'px');
}
```

**Comment by arshaw** [comment]
glad you figured it out.

ya, this is too specific for general use. closing
