### ISSUE TITLE
Date decrement by clicking the evento.

### ISSUE THREAD

**Issue by GiovaniSantos93** [fullcalendar/fullcalendar#3172]
Hi,

Every time the eventClick and fired it decrements day event object. FullCalendar v2.7.1

![image](https://cloud.githubusercontent.com/assets/13335171/15395581/b950250e-1dae-11e6-8e13-6a554dc54411.png)

![image](https://cloud.githubusercontent.com/assets/13335171/15395664/06c1f592-1daf-11e6-83d5-55bfa05553c9.png)

**Comment by arshaw** [comment]
http://fullcalendar.io/wiki/Reporting-Bugs/

please include a jsbin
