### ISSUE TITLE
Selectable not working at all in Chrome (v. 2.7.0 and later)

### ISSUE THREAD

**Issue by FG96** [fullcalendar/fullcalendar#3173]
Hello Fullcalendar community,
I have recently tested the new Version of Fullcalendar (2.7.0 and 2.7.1) and experienced, that the selectable Option is not working in chrome. I have checked the examples template for selectable and the issue is the same. It's working fine in Firefox and Edge. I'm sure it's because of thew new touch functionality. Here is a live example:

http://jsbin.com/piwuwuweha/edit?js,output

Best regards
Florian

**Comment by FG96** [comment]
I have to add that I am using a surface pro 3.

**Comment by thanhtran1259** [comment]
@FG96  I also faced same issue.

**Comment by MartijnWelker** [comment]
possible duplicate #3154

**Comment by FG96** [comment]
ok, it's fixed now in 2.7.2! But the event creation throgh touch on the calendar has stopped working.
