### ISSUE TITLE
fcViews[newViewName] is not a constructor

### ISSUE THREAD

**Issue by dhavalrd** [fullcalendar/fullcalendar#3176]
Please please help me. I have not attached JSBin recreation. I could not get how to attach Fullcalendar.js file. So please help me.

I am trying to get events in FullCalendar from database and convert it to JSon result. When I use $(document).ready function, this does not call the function in backend file. But using ajax call it calls the method. But after that, it does not load events in FullCalendar. This is the code. 

        $.ajax({
                type: 'POST',
                //contentType: "application/json; charset=utf-8",
                url: '@Url.Action("GetEvents", "Booking")',
                success: function (responseData) {
                    $("#calendar").fullCalendar('removeEvents');
                    var events = responseData;
                    alert(responseData);
                    $('#calendar').fullCalendar(
                    {
                        header:
                        {
                            left: 'prev,next today',
                            center: 'title',
                            right: 'month,agendaWeek,agendaDay'
                        },
                        defaultView: 'basic',
                        events: events
                    });
                },
                error: function () { alert(Error); }
            });

public JsonResult GetEvents()
        {
            DateTime StartOfWeek = DateTime.Today.AddDays(-(int)DateTime.Today.DayOfWeek);
            int endOfMonth = DateTime.DaysInMonth(DateTime.Today.Year, DateTime.Today.Month);
            DateTime EndOfMonth = Convert.ToDateTime(endOfMonth + "/" + DateTime.Today.Month.ToString() + "/" + DateTime.Today.Year.ToString());
                string query = "query";
                    SqlConnection connection = new SqlConnection("connectionString");
                    connection.Open();                    
                    SqlCommand command = new SqlCommand(query, connection);
                    SqlDataReader events = command.ExecuteReader();                    
                    DataTable dt = new DataTable();
                    dt.Load(events);
                    string result = DataTableToJSONWithStringBuilder(dt);
                    connection.Close();                    
                    return Json(result, JsonRequestBehavior.AllowGet);
            return Json(string.Empty, JsonRequestBehavior.AllowGet);
}

        public string DataTableToJSONWithStringBuilder(DataTable table)
        {
            var JSONString = new StringBuilder();
            if (table.Rows.Count > 0)
            {
                JSONString.Append("[");
                for (int i = 0; i < table.Rows.Count; i++)
                {
                    JSONString.Append("{");
                    for (int j = 0; j < table.Columns.Count; j++)
                    {
                        if (j < table.Columns.Count - 1)
                        {
                            JSONString.Append("\"" + table.Columns[j].ColumnName.ToString() + "\":" + "\"" + table.Rows[i][j].ToString() + "\",");
                        }
                        else if (j == table.Columns.Count - 1)
                        {
                            JSONString.Append("\"" + table.Columns[j].ColumnName.ToString() + "\":" + "\"" + table.Rows[i][j].ToString() + "\"");
                        }
                    }
                    if (i == table.Rows.Count - 1)
                    {
                        JSONString.Append("}");
                    }
                    else
                    {
                        JSONString.Append("},");
                    }
                }
                JSONString.Append("]");
            }
            return JSONString.ToString();
        }

**Comment by arshaw** [comment]
i cant debug unless there is a jsbin recreation, sorry
http://fullcalendar.io/wiki/Reporting-Bugs/
