### ISSUE TITLE
Alternating interval

### ISSUE THREAD

**Issue by ilicmarko** [fullcalendar/fullcalendar#3178]
Hi, i have been fiddling with the plugin for 2-3 hours and I can't get the result I am looking for. I played arround with `slotDuratation` and `slotLabelInteval` and still can't figure it out.

Here is the effect I am looking for: http://i.imgur.com/tUUaYRr.png

My day starts at: `08:15:00`
Every event finishes on the round clock, `HH:00:00`
Every event start quarter pass an hour: `HH:15:00`

Is it even possible to achieve and effect I want?

Thanks in advanced!

**Comment by arshaw** [comment]
the proposed solution in this issue might be somewhat useful to you
https://github.com/fullcalendar/fullcalendar/issues/3164
&uarr;
Please visit the link, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates.
