### ISSUE TITLE
How to make td cell width 100px without effecting the events place...

### ISSUE THREAD

**Issue by aftabsharif** [fullcalendar/fullcalendar#3179]
i have searched too much about that and tried several methods but failed.
can you please help me out here..
i am using resource view . how to make td and th width of 100px without effecting the events place. is there any fullcalendar option there?
also when i use table-layout : fixed then i can apply the width to cells but then another issue rise the events starting from one month and end to another shows like that
![cdn](https://cloud.githubusercontent.com/assets/4891217/15529664/56cc004c-2268-11e6-89f7-b9435b3900aa.PNG)

js fiddle
http://jsfiddle.net/kcxPp/36/
Please help.....

**Comment by arshaw** [comment]
event position is done in a very different way in fc 2.x, so this bug will probably fixed when the lib is upgraded
