### ISSUE TITLE
touch move conflic dayClick event

### ISSUE THREAD

**Issue by erichow** [fullcalendar/fullcalendar#3180]
at mobile ,
 If mobile not scroll , i touch move down/up ,will emit dayClick event,

if mobile have scroll,  I scroll move end ,then continue to move down , will emit dayClick event.

I try to fix this bug ,but failed.....

**Comment by foxalfabravo** [comment]
I conccur

On IOS I have a eventDragStop with touchEnd, followed by a dayClick

Not on Android  (no dayclick)

**Comment by arshaw** [comment]
sounds like this issue
https://github.com/fullcalendar/fullcalendar/issues/3152

but that was fixed in the most recent release. could you please upgrade?
