### ISSUE TITLE
Can split single day in column (one for every resource) in fullcalendar using  week view?

### ISSUE THREAD

**Issue by falinsin** [fullcalendar/fullcalendar#3181]
We are about to chosse fullcalendar  for use in a big development and even if it is  needed We could purchase features. But we need to clarify a doubt.

Can fullcalendar show in week view a  simultaneous schedule for several resources. But We need every resource in separated column but not in separated row.

So Split every column day in subcolumns when using the Week View and every subcolumn is for a resource.

Thanks in advance

**Comment by caseyjhol** [comment]
See: https://github.com/fullcalendar/fullcalendar-scheduler.

http://fullcalendar.io/js/fullcalendar-scheduler-1.3.1/demos/vertical-resource-view.html
