### ISSUE TITLE
Enable all day events to be rendered side by side

### ISSUE THREAD

**Issue by thestumonkey** [fullcalendar/fullcalendar#3183]
I would like to render events side by side instead of each line.  I have overridden the CSS to display the user's icon next to an event they are attending instead of the text, but I can't get it to render side by side, until the end of the cell is reached, and then a newline.

**Comment by arshaw** [comment]
could you please post a screenshot or something visual. im having a hard time understanding what side-by-side means in this context

**Comment by thestumonkey** [comment]
<img width="984" alt="screen shot 2016-05-29 at 17 15 47" src="https://cloud.githubusercontent.com/assets/435874/15634649/1720b5b2-25c1-11e6-9dfa-ba322f16b232.png">

So here I am displaying a user icon for each event in a day (In this case the event is actually a person attending).  I want to display them side by side then go to the next line when the cell is full horizontally.

**Comment by arshaw** [comment]
This will currently be very hard given how events are rendered an laid out. What you describe is mutually exclusive with multi-day events that span multiple cells.

However, I do plan to explore how to make the calendar more responsive, likely displaying dots on each day when the displays get small enough. The dots will hypothetically be side-by-side. Once that is implemented, you could theoretically force the calendar into that type of event-display mode, then override the dots with images. Here is the ticket for responsiveness:

https://github.com/fullcalendar/fullcalendar/issues/3187
&uarr;
Please visit the link, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates.
