### ISSUE TITLE
event dragging with maxTime greater than 24:00

### ISSUE THREAD

**Issue by parrillas** [fullcalendar/fullcalendar#3186]
Hi, i just want to share our custom code to improve fullcalendar.

It just 1 line modified on 2.7.2 release, line 7033 on computeTimeTop. 
just added before:
if(time < this.minTime ) time.add(1, 'd');

This fix issue when you are working with calendar higer than 24h, events will be rendered on the correct segment this way.

**Comment by arshaw** [comment]
thanks for the submission, but im having a hard time understanding the original bug you are trying to solve. could you please post a jsbin? http://fullcalendar.io/wiki/Reporting-Bugs/

**Comment by parrillas** [comment]
http://jsbin.com/xuhamavute/edit?js,output

With a calendar not limited to 24h, on the agendaWeek view, try to drag the event to start on an hour greater than 00:00. Event will dissapear.

The problem is comming from TimeGrid, computeTimeTop function, line 326 https://github.com/fullcalendar/fullcalendar/blob/master/src/common/TimeGrid.js

adding before:
if(time < this.minTime ) time.add(1, 'd');
will solve the problem, letting events work in a non 24h limit.
Very usefull for agendas in a common timetables of night workers, to don't break at 24:00

**Comment by arshaw** [comment]
ah i see. thanks for the explanation and demo.

minTime's greater than 24:00 are not officially supported, tho as you demonstrate they work in many regards. Getting it to work with dragging will be a bit of extra work.

I like your solution I would also like to come up with a more universal solution that is able to deal with maxTimes beyond 48hours, in addition to negative minTimes.

**Comment by arshaw** [comment]
@parrillas I discovered another ticket that is essentially the same as your reported issue, but with maxTime. I'm going to treat them as the same, and fix them together.
#3055
&uarr;
Could you please visit the link, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates?
