### ISSUE TITLE
moment-timezone support

### ISSUE THREAD

**Issue by arshaw** [fullcalendar/fullcalendar#3188]
Find a way to integrate with [moment-timezone](http://momentjs.com/timezone/).

If a timezone string like `"America/Chicago"` is specified in the [timezone](http://fullcalendar.io/docs/timezone/timezone/) option, and moment-timezone is detected, then the `.tz()` method should be leveraged to ensure that every datetime throughout the API is in the calendar's timezone.

Currently, the recommended way to compute timezone offset from timezone names it to use the server-side (as recommended in the last entry of the [timezone docs](http://fullcalendar.io/docs/timezone/timezone/)), which is still a superior method for a number of reasons, but people might prefer to compute this in the client-side instead.

**Comment by xxAtrain223** [comment]
I hate to ask, but do you know when we can expect this to be added?

**Comment by tobiasmuehl** [comment]
It's possible to process dates one the client side by passing a function instead of an URL. In that function you can do the AJAX call and then process the dates on the client-side using moment-timezone

**Comment by peterver** [comment]
+1

**Comment by ZeldaIsThePrincess** [comment]
+1

**Comment by espen** [comment]
Please stop the +1. It just creates more emails to people subscribed here. Use the GitHub reaction to vote for issues. 

See https://fullcalendar.io/blog/2016/07/renovated-issue-tracker/

> Comments such as +1 or “when will this be ready” will not only receive a penalty in the ranking system, they will spam other watchers of the thread

**Comment by arshaw** [comment]
I'm planning for v4 and made a proposal for overhauling the date system. Can you all take a look? Please make relevant comments on this thread.

[Wiki: Date System Revamp](https://github.com/fullcalendar/fullcalendar/wiki/Date-System-Revamp-Proposal)

**Comment by arshaw** [comment]
This issue has been addressed in the latest alpha release (4.0.0-alpha.2)
[See the blog post &raquo;](https://fullcalendar.io/blog/2018/10/release-v4-alpha2)

https://fullcalendar.io/docs/v4/moment-plugins#fullcalendar-moment-timezone

**Comment by arshaw** [comment]
I'm closing this issue to signify that it's implemented (since v4-alpha2). I'll comment on this thread again when v4 is officially released.

**Comment by arshaw** [comment]
[V4 was officially released a few days ago!](https://fullcalendar.io/blog/2019/03/v4-officially-released)
