### ISSUE TITLE
Touch Support for Windows Phone (Windows 10 Mobile)

### ISSUE THREAD

**Issue by joejoe87577** [fullcalendar/fullcalendar#3189]
When using the touch support for dragging and editing events in fullcalendar on windows mobile devices (windows edge browser) the long touch is not recognized by the calendar. Instead the device shows a small popup with "select all" that selects all text on the page.
This seems to be a windows edge feature that breaks the touch support functionality.

To reproduce the bug open [simple Template](http://fullcalendar.io/playground/jsbin.php/) on a Windows 10 Mobile Device with Windows Edge and long click an event.

**Comment by J3QQ4** [comment]
This solved the issue for me:

```
.fc-timeline-event,
.fc-event {
    -ms-touch-action: none; /* otherwise drag and drop not working in IE on touchscreen */
}
```

**Comment by lahdekorpi** [comment]
@J3QQ4 
Long press somewhat works but doesn't allow dragging to select with your workaround.

**Comment by arshaw** [comment]
since Window Phone has been discontinued, I don't plan on putting much development effort into this
