### ISSUE TITLE
Adding event for multiple days for specific time slot

### ISSUE THREAD

**Issue by vijay7790** [fullcalendar/fullcalendar#3191]
I want to add event in week view for multiple days. selecting event period horizontally only for that specific time range( like from 01-06-2016 to 03-06-2016 for time 2pm to 2.30 pm for all selected days ), when try to do this it select time from 01-06-2016 2pm to 03-06-2016 2.30 pm and covers all the aria between these two dates. i want only 2pm to 2.30 pm selected aria for 01,02,03 date

**Comment by arshaw** [comment]
could you please include screenshots?
