### ISSUE TITLE
locale files as CJS modules

### ISSUE THREAD

**Issue by starf** [fullcalendar/fullcalendar#3192]
Because the languages are already defined by moment.js, we get the following warning when including the fullcalendar languages.

> Deprecation warning: use moment.updateLocale(localeName, config) to change an existing locale. moment.defineLocale(localeName, config) should only be used for creating a new locale

I'm not a very active github user so excuse me if i'm incorrect, this has already been mentioned or i shouldn't have posted this here. Thanks

**Comment by arshaw** [comment]
Hmm, we don't ever want both the moment.js AND fullcalendar translations to load together. The FullCalendar translations *include* the moment ones. They are a superset.

However, you do bring up a good point.. the ability to include the fullcalendar-only translations so that you can include the pure momentjs translations separately. Please let me know if you'd want that feature.

**Comment by starf** [comment]
Ok, that wasn't totally clear for me.
The translations being included in fullcalendar is not a problem right now because fullcalendar is updated frequently. You adding or not adding this "decoupling" feature is your decision.
Thanks again for your work on this plugin.

**Comment by Tol1** [comment]
I'd like to have ability to include fullcalendar-only translations. 
We use Webpack to build our js, and moment is included and locale is defined on main.js on root level. When Fullcalendar and Fullcalendar locale is required, Webpack loads and uses the _same_ moment instance as already defined on root level, and thus moment locale ends "overwritten" and deprecation warning is shown on console.
Moment.js is "global module", `require('moment')` always returns same instance with same global settings, no matter how many times you call it on app.

**Comment by arshaw** [comment]
once fc internally [moves over to webpack + cjs modules](https://github.com/fullcalendar/fullcalendar/issues/3297), this will be much more possible. each fc locale file should require moment's individual locale files. then, your project could reference the `src` files (might be relocated) and everything would compile without duplication.

**Comment by anurbol** [comment]
+1 not overriding moment original locale definitions would be a proper package behavior, imo.

**Comment by arshaw** [comment]
in v4, locales are proper modules now
