### ISSUE TITLE
eventSource not update url ajax dinamyc

### ISSUE THREAD

**Issue by fsobarzo** [fullcalendar/fullcalendar#3193]
I have a problem with update the url from eventSource in fullCalendar. for example..
```

evtSources = function(){
var evtSources = [];

var evtRestrictions = {
        url: 'people/'+ $("#account_id").val() +'/restrictions',
        ...

    };

var evtShifts = {
        url: 'shifts/calendar',
        data:{
            tag_name: function(){
                return $('#group_shift').val();
            }
        },
        ...
};

evtSources.push(evtRestrictions);

if(['admin','manager'].indexOf($('body').data('role')) === 0){
    evtSources.push(evtShifts);
}

return evtSources;
};
jQuery(document).ready(function() {
    $('#availability-calendar').fullCalendar({
        ...
        eventSources: evtSources(),
        ...
    });
    $('.selectpicker').selectpicker({
      style: 'btn-info',
      width: '100%'
    });

    $('.selectpicker').on('changed.bs.select', function(e){
      $('#availability-calendar').fullCalendar( 'refetchEvents' );
    });
});
```

So, when I changed the select input #group_shift it's work, $(#group_shift).val() was change and tag_name in data changed with $(#group_shift).val().

But, when I changed the select input #account_id this not change. $('#account_id') in url: 'people/'+ $("#account_id").val() +'/restrictions' always is a same value.

I dont know why in data: {tag_name: } change the value but in url: not.

any idea?

thank!

**Comment by arshaw** [comment]
http://fullcalendar.io/wiki/Reporting-Bugs/
http://fullcalendar.io/wiki/Reduced-Test-Cases/
