### ISSUE TITLE
goToDate on Safari shows as Invalid date

### ISSUE THREAD

**Issue by jeremymcminn** [fullcalendar/fullcalendar#3195]
I have a datepicker that changes the date of the calendar when navigating on it.

This seems to work in all browsers apart from Safari, it shows as "Invalid date".  I've tried various different combinations of setting the date format with moment, but it still throws up the same issue.

```
$('.datepicker-side').datepicker().on('changeDate', function(e) {
       var d = new Date(e.date);
       $('#calendar').fullCalendar('gotoDate', d);
});
```

**Comment by arshaw** [comment]
Thanks for your submission. A bug can only be fixed if it be can reproduce in a minimal test environment. Could you please create a runnable [Reduced Test Case](http://fullcalendar.io/wiki/Reduced-Test-Cases/)? This will save a great deal of time, and is very appreciated.
