### ISSUE TITLE
Specifying days of week causes spillover of events into next/previous months

### ISSUE THREAD

**Issue by Ragspur** [fullcalendar/fullcalendar#3203]
I have created a calendar on my website using cold fusion to populate the calendar from a mysql table.  Everything works as planned with the exception of events that span a time frame but exclude specific days.    

For example, an event that runs from June 1st to June 26th but only on Wednesday through Sunday.  By using the DOW directive it shows correctly for the current month. However on the bottom of the calendar when it shows the first few days of the next month, the event begins again.

If you click to the next month (i.e.. July), the event appears there, even though the end date clearly states June 26th.  If you scroll back (i.e.. May) the event also appears there.

My JS Bin:   http://jsbin.com/zovopu/2/edit?html,js,output

**Comment by arshaw** [comment]
the `dow` property is not officially supported in events, and won't work if you plan to have the daily event start/end at specific points in the year.

if you'd like proper recurring event support:
https://github.com/fullcalendar/fullcalendar/issues/387
&uarr;
Could you please visit the link, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates?
