### ISSUE TITLE
Google Calendar - Business Account Event Title Problem

### ISSUE THREAD

**Issue by mstojanovv** [fullcalendar/fullcalendar#3204]
Hi.

I have some problem with the google calendar events using business account.
The events are fetched but not displayed good.
The event title is blank (Check screenshot)
http://postimg.org/image/4a2wjcbbf/

When using normal gmail account everything works good. What can cause this issue?

Thanks

**Comment by arshaw** [comment]
probably because of this:

http://fullcalendar.io/docs/google_calendar/

> Make sure "Share only my free/busy information" is unchecked.
