### ISSUE TITLE
Crowd translation

### ISSUE THREAD

**Issue by laoneo** [fullcalendar/fullcalendar#3206]
Did you ever consider to move the translation process to a localization platform like https://crowdin.com or https://www.transifex.com. I'm sure it will attract more translators.

**Comment by arshaw** [comment]
Hi @laoneo that's a cool suggestion. Right now, there are a sufficiently small number of strings where the manual method is fine, but will check that out if it becomes necessary

**Comment by arshaw** [comment]
im afraid this might be automated spam. im removing the links in the post unless you speak up

**Comment by laoneo** [comment]
No it's not spam. I'm not affiliated with these companies either. I'm involved in Joomla where we use these two platforms and got a lot of help from translators which are not technical versed. Just thought that fullcalendar would get available in more languages.

**Comment by arshaw** [comment]
ah ok thanks. sorry for the comment misclassification. i'll check these out if fullcalendar's i18n efforts scale up. thanks!

PS- right now we rely heavily on momentjs's translations

**Comment by laoneo** [comment]
Saw it just now, because of the few strings to translate, I would not do the effort for crowd translating. Keep up the good work and hope to get the list view soon :speak_no_evil:
