### ISSUE TITLE
Example of how to highlight another cell when hovering on an event.

### ISSUE THREAD

**Issue by StudioJunkyard** [fullcalendar/fullcalendar#3208]
The reason behind this, was having a client that had a lot of Events in the calendar as bookings. Many of them having an `event.end` being longer than 1 day, and as such displaying the event across multiple cells. This made the calendar hard to read for them, and having many events on one day, just made the calendar awkward to use. So I came up with a way, to indicate an events end day, and restraining that event to it's start cell.

Essentially, I have an extra option added `event.eventend`, to replace the `event.end` option, which restrained the event to it's `event.start` cell.

Next, was to create the `eventMouseover` callback, and have the script target the cell using the data from the `event.eventend` option. Upon inspecting the generated tabled cells using Chrome's Dev Tools, I noticed that the relevant cell uses a `data-date="2016-01-01"`, which is how I worked out I could use the date to target the cell needed to highlight. Then using the `eventMouseout` callback, to remove the highlight from the cell.

As the title says, this is an Example of how this can be accomplished, to give rise to more idea's.

````css
    .eventEndHighlight{
        background-color:#f00; // Red
    }
````
````javascript
$('#calendar').fullCalendar({
    header:{
        left:'prev,next',
        center:'title',
        right:'month,basicWeek,basicDay'
    },
    events:[
       {
            id:'yourEventID',
            title:'yourEventTitle',
            start:'<yourEventStart>', // I use php date("Y-m-d H:i:s",<timestamp>)
           eventend:'<yourEventEndDate>', // I use php's date("Y-m-d H:i:s",<timestamp>)
            allDay:false,
       },
    ],
    eventMouseover:function(event,domEvent,view){
        $('[data-date="'+moment(event.eventend).format('YYYY-MM-DD')+'"]').addClass('highlightEndClass');
    },
    eventMouseout:function(event){
        $('[data-date="'+moment(event.eventend).format('YYYY-MM-DD')+'"]').removeClass('highlightEndClass');
    }
)};
````

**Comment by arshaw** [comment]
that's pretty clever, thanks for sharing.

hope you won't mind if i close this out (as it's not actionable as a bugfix ticket or whatnot), but this page will still be accessible via google and the issue tracker index.

**Comment by StudioJunkyard** [comment]
All good, that was the intention, hopefully others find it useful.
