### ISSUE TITLE
Custom view and other views  renderEvents collision.

### ISSUE THREAD

**Issue by avinashramireddy-rapidd** [fullcalendar/fullcalendar#3213]
Hi,
I am trying to implement custom view which is basically a list of events shown as table as opposed to in-built views which have time grid and date grid.So I rendered my events in extended view in the function **renderEvents:function(){......}**

Problem is that,
1. I am setting my **custom view as default view but I notice that it is triggering in-built events url also** (yeah,in built and custom view events ajax url are different because I have some extra columns to show in table).
2.Also when default view is custom view and when I try to switch to other views like month then the view is filled with empty grid without events.
3.It is triggering every time when loaded.I checked it is going through cache in following code.

 ```
 getViewSpec: function (viewType) {
            //console.log(viewType);
            var cache = this.viewSpecCache;

            return cache[viewType] || (cache[viewType] = this.buildViewSpec(viewType));
        },

```
Here console is showing viewType as agendaList.So I am assuming it is going through cache for storing.So I am doing nothing to store events in my custom view.

Please find jsfilddle link [here](https://jsfiddle.net/avinashramireddy24/bx3kf4as/3/) **for problem 1**
 
What is the best way to render events for all views.

**Comment by arshaw** [comment]
the `renderEvents` method *receives* the array of events as it's first parameter, so you should use those instead of fetching your own (it will be too late to display after fetching). 

use a normal [json feed event source](http://fullcalendar.io/docs/resource_data/resources_json_feed/) or a [custom event function](http://fullcalendar.io/docs/resource_data/resources_function/) to worry about event data transfer

**Comment by avinashramireddy-rapidd** [comment]
Ok. But problem is not about fetching actually.
It's way of showing the events.

I have table which has filters , grouping,calculating duaration by group,accordion and some other filters which render dynamically.
In-built view are more focused on day and time grids,right? 
That's why I am putting my logic in renderEvents of custom view by passing events and settting markup in extended js file.
**If I am going wrong direction,what is good solution for this kind of approach?**

Also I notice that it's not destroying old events(from other views) by putting in console.log
