### ISSUE TITLE
Set cursor style over calendar cells doesn't work well

### ISSUE THREAD

**Issue by pedrodelgado81** [fullcalendar/fullcalendar#3215]
Hi, I posted this issue in stackoverflow: http://stackoverflow.com/questions/37724369/set-cursor-style-doesnt-work-well

The main problem is that if I change the cursor style if a day is before or after today, works well except when I have events. You can see the example: http://jsbin.com/qekajezepu/1/edit?js,output
If you put the mouse over day 5 and move from top to bottom you can see that the pointer changes from "no-wrap", to default value in an area that is of the same height of the area that is used to paint events in other days of the week.

Better explanation in stackoverflow post linked at the begining.
Thanks

**Comment by arshaw** [comment]
looks like your stackoverflow question got answered

your question reminds me of this feature request:
https://github.com/fullcalendar/fullcalendar/issues/2430 (would also apply to hover, like in your situation)
&uarr;
If it interests you, please visit the link, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates?

**Comment by pedrodelgado81** [comment]
Yes, I readed the response and worked fine.
I saw that your request has been closed.
Thank for the reply.
