### ISSUE TITLE
External events doesn't work in mobile devices

### ISSUE THREAD

**Issue by myn01** [fullcalendar/fullcalendar#3216]
On Android devices external events can't be dragged

**Comment by arshaw** [comment]
if you are doing what's in this demos: http://fullcalendar.io/js/fullcalendar-2.7.3/demos/external-dragging.html

... that uses jquery UI draggables for the elements on the left, which does not natively support drag n drop on touch, so if you want it to work, you'll need to use [touchpunch](http://touchpunch.furf.com/)
