### ISSUE TITLE
Issue on mobiles: No interaction on click, how to bring back the standard behaviour?

### ISSUE THREAD

**Issue by q2apro** [fullcalendar/fullcalendar#3220]
JSFiddle with the ability to add events (on click not working on mobiles): https://jsfiddle.net/8fn7v2mh/ (2.7.3)

I allow my users to add an event by clicking on the calendar. However, with the new version that does not work anymore. 

I just found in the release logs [over here](https://github.com/fullcalendar/fullcalendar/releases/tag/v2.7.0) that the user now must hold the finger onto the calendar so that it will interact.

I have tried this new implementation with 5 users, none of them understood what was going on. So I conclude that this new "feature" is misleading and not helpful. It appears to the users as a non-functioning calendar. 

My urgent question: How can I disable this behaviour? And get back the old one: One click onto the calendar results in a response of the calendar (resp. triggers `select`). Thanks.

**Comment by arshaw** [comment]
if you want an event to fire on click, you should use the `dayClick` callback instead. in your example, you are using the `select` callback, which is on a delay. As another option, you can turn down the delay to much smaller value: http://fullcalendar.io/docs/event_ui/longPressDelay/

**Comment by q2apro** [comment]
Thanks for your help. I have tried `longPressDelay: 0` which brings a direct reaction. However, there is still one issue: 

When using `$('#calendar').fullCalendar('unselect')` after an event got placed, the event appears for a moment and then disappears again (in my production mode). Strange enough, the fiddle works correctly: https://jsfiddle.net/4mbLyeqq/3/

On my site, I am disabling the unselect for mobiles as a workaround. 

In case I find the culprit, I will post the solution here.
