### ISSUE TITLE
Ability to highlight slot in calendar (with certain duration) under mouse point

### ISSUE THREAD

**Issue by akhramovichleverx** [fullcalendar/fullcalendar#3221]
Is it possible to add ability to highlight slot in calendar (with certain duration) under mouse point?

User will be able to kind of simulate schedule event without clicking on calendar.

**Comment by arshaw** [comment]
dup of:
https://github.com/fullcalendar/fullcalendar/issues/2513
&uarr;
Could you please visit the link, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates?
