### ISSUE TITLE
how to change agendaDay view to make the timeline on the top

### ISSUE THREAD

**Issue by mjm88132** [fullcalendar/fullcalendar#3222]
### Bug Reports
You MUST have a JSBin recreation, or else your issue will be CLOSED without explanation.
Instructions: http://fullcalendar.io/wiki/Reporting-Bugs/

### Feature Requests
Search the issue tracker for an existing ticket before creating a new one.
Instructions: http://fullcalendar.io/wiki/Requesting-Features/

(Please erase the above text and begin typing. Thanks!)

**Comment by mjm88132** [comment]
![image](https://cloud.githubusercontent.com/assets/19622936/16034114/770ad2b8-3242-11e6-8e53-93f26af8b377.png)  
like this 
![image](https://cloud.githubusercontent.com/assets/19622936/16034139/a4f85a92-3242-11e6-8222-df4b31589520.png)

**Comment by alan1o** [comment]
Might want to take a look at Schedulers timeline view. http://fullcalendar.io/scheduler/

**Comment by mjm88132** [comment]
thanks very much
