### ISSUE TITLE
might a bug?

### ISSUE THREAD

**Issue by mjm88132** [fullcalendar/fullcalendar#3224]
### Bug Reports
You MUST have a JSBin recreation, or else your issue will be CLOSED without explanation.
Instructions: http://fullcalendar.io/wiki/Reporting-Bugs/

### Feature Requests
Search the issue tracker for an existing ticket before creating a new one.
Instructions: http://fullcalendar.io/wiki/Requesting-Features/

(Please erase the above text and begin typing. Thanks!)

**Comment by mjm88132** [comment]
![image](https://cloud.githubusercontent.com/assets/19622936/16072811/4f8f5a14-3315-11e6-9d5f-731e7e5876cb.png)
bug pic looks like:
![image](https://cloud.githubusercontent.com/assets/19622936/16072887/c8a04580-3315-11e6-90a0-38946217050a.png)
normal pic when scroll bar at right position
![image](https://cloud.githubusercontent.com/assets/19622936/16072913/f043c83c-3315-11e6-812d-56acf56c46a7.png)

**Comment by arshaw** [comment]
Would you be able to post a [runnable, stripped-down demonstration of the bug](http://fullcalendar.io/wiki/Reduced-Test-Cases/)? Would really appreciate it because the time saved reproducing will be time spent fixing.
