### ISSUE TITLE
Allow dynamic movement of nowIndicator

### ISSUE THREAD

**Issue by sedouard** [fullcalendar/fullcalendar#3229]
Allow nowIndicator to be moved after initialization.

There are internal methods int he FC.View class to [un-render](https://github.com/fullcalendar/fullcalendar/blob/9cf342a10be131909cfd4a3e04f904b9902c3744/src/common/View.js#L480) and [re-render](startNowIndicator) the nowIndicator. Why not expose those publicly so that apps can move the nowIndicator. For my application I need this because when the use selects a timezone, the nowIndicator should adjust according to the timezone selected by the user, not just the timezone of the local browser.

I do this today by calling the `destroy` method every time the user changes the timezone, which is not efficient.

**Comment by arshaw** [comment]
I'm hoping to allow for dynamic setting of the `now` option when this feature is implemented:
[Setters for all options #564](#564)
&uarr;
Could you please visit the link, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates?

**Comment by arshaw** [comment]
updated the above link
