### ISSUE TITLE
Day click does not work on devices

### ISSUE THREAD

**Issue by pinksharpii** [fullcalendar/fullcalendar#3231]
I just updated my full calendar to the latest version (have been using 2.6.1) and we have the function
dayClick: function(date, e, v) in our code for the fullCalendar. And for some reason on iphone and ipad (have not tested android phones), the e element is returning undefined instead of the element object.

**Comment by arshaw** [comment]
Would you be able to post a [runnable, stripped-down demonstration of the bug](http://fullcalendar.io/wiki/Reduced-Test-Cases/)? Would really appreciate it because the time saved reproducing will be time spent fixing.
