### ISSUE TITLE
Changing events with Date range picker(custom button) in custom view

### ISSUE THREAD

**Issue by avinashramireddy-rapidd** [fullcalendar/fullcalendar#3233]
Hi,
I posted few other issues.So far,I am able to work around with the help.I will update my answer when I get time.

Now,I got a problem with date range picker button in custom view.

Basically,I have a custom view with events shown as a list.
I want to add date range picker as custom button in my custom view only.

I am able to do this by following some steps as below.

1.Created custom view with renderEvents function(design goes here by fetching events).
2.In my viewRender function,I am show/hiding based on my view.
3.**Added date range picker  as a button between prev and next icons for custom view.**
4.Wrote some code to trigger datepicker on custom button click.

Now **my problem is how to load(or change )my custom view with events within this date-range
**Ex:last 2 months 15 days or so**

When I searched for it,I found only **gotoDate** but not range of dates.
I want to change view with events on selecting date 

Can I use setRange in custom view to fetch details or is there any other way to achieve this.

**Comment by avinashramireddy-rapidd** [comment]
@arshaw 
_**Updated after debugging and fixing issues**_

I am working on **custom view which has custom button(daterangepicker)** shown. When I change date range,I want to **call function which is written via using signalR.** This signalR is new concept to me which was already implemented by one of my colleagues.(tried taking help,but he doesn't know about extending views which was done by me only)

Now I am **unable to understand whether this **signalR functions are called when date range is changed or not.**Because in custom agenda view,**renderEvents is called more than once with different data.**

I am quite sure something has to  do with the signalR(Reason behind using signalR is that,I don't want to refresh page or calendar when events are updated or removed or added.The signalR will do just fine in this situation.)

Please help me.**Seriously stuck **.I feel that I have complicated problem. Didn't get any decent solution with this scenario.

**Comment by arshaw** [comment]
Would you be able to post a [runnable, stripped-down demonstration of the bug](http://fullcalendar.io/wiki/Reduced-Test-Cases/)? Would really appreciate it because the time saved reproducing will be time spent fixing.

**Comment by avinashramireddy-rapidd** [comment]
Hi,
I have produced my scenario below.
 [<a class="jsbin-embed" href="http://jsbin.com/wifiva/embed?html,js,console,output"> Changing events with Date range picker(custom button) in custom view </a><script src="http://static.jsbin.com/js/embed.min.js?3.35.13"></script>](url)

Please ignore about signalR for now.I will deal with it later.
