### ISSUE TITLE
Fix failing Travis CI tests

### ISSUE THREAD

**Issue by arshaw** [fullcalendar/fullcalendar#3236]
https://travis-ci.org/fullcalendar/fullcalendar/builds/139375455

```
PhantomJS 2.1.1 (Linux 0.0.0) weekMode when weekMode is set to liquid should increase height when moving from 6 week to 5 weeks FAILED
	Expected 52 to be greater than 52.
	/home/travis/build/fullcalendar/fullcalendar/tests/automated/weekMode.js:91:42
PhantomJS 2.1.1 (Linux 0.0.0) weekMode when weekMode is set to liquid should reduce height when moving from 5 weeks to 6 weeks FAILED
	Expected 52 to be greater than 52.
	/home/travis/build/fullcalendar/fullcalendar/tests/automated/weekMode.js:98:42
```

**Comment by arshaw** [comment]
would also be great to get the little image badge thing in the repo's readme

**Comment by avindra** [comment]
PR for badge made in #3239

**Comment by arshaw** [comment]
done

**Comment by mlandmann** [comment]
For the love of God Adam, would you make a decent list view (agenda view) option for the calendar.

As someone mentioned it has been asked for - for years, and the various attempts are less then adequate.

Make it a premium option if needed – I’m in!

 

Mark Landmann
