### ISSUE TITLE
How to get event date in dow events

### ISSUE THREAD

**Issue by Veerakrishna** [fullcalendar/fullcalendar#3238]
Actually  I am new to this and I am displaying dow events in full calendar. Here I want events dates when  click on events. here is my code like this 

> events[{start: '10:00',   end: '18:00',   dow: [ 1, 2, 3, 4 ]}],

> element.bind('click', function() {
            $('#modal    #pick_date').val(event.star);});

but there is no start date here what i do now please give a solution for my problem.

**Comment by arshaw** [comment]
Would you be able to post a [runnable, stripped-down demonstration of the bug](http://fullcalendar.io/wiki/Reduced-Test-Cases/)? Would really appreciate it because the time saved reproducing will be time spent fixing.
