### ISSUE TITLE
Calendar Rendering

### ISSUE THREAD

**Issue by hartjo** [fullcalendar/fullcalendar#3240]
Is there a way to view calendar example from june 1,2016 to july 9, 2016 only?

i dont want to show other dates from my date range only from june 1,2016 to july 9, 2016

![screenshot from 2016-06-23 15-54-01](https://cloud.githubusercontent.com/assets/8595930/16295835/bb1a0094-395b-11e6-9888-123957076d9b.png)

**Comment by arshaw** [comment]
http://fullcalendar.io/docs/views/Custom_Views/
