### ISSUE TITLE
Clear select-helper-events upon event render/rerender

### ISSUE THREAD

**Issue by tonykchan** [fullcalendar/fullcalendar#3241]
BUG - The renderEvent (method) doesn't refresh the Calendar UI when newly added events are added to a Calendar that is in agendaWeek or agendaDay view.  Adding new events when in Month view, seems to behave properly.

Please review the following JSBin example of the issue.  

1.) Clicking days or a selection of days when in Month view, adds new "test" events to the calendar with Title, etc...

2.) Switch to agendaWeek or agendaDay view.  Clicking a selection of time to add new "test" events doesn't behave the same as in Month view.  You have to either switch the view mode back & forth or click on the newly added timeslot or add another event for the previous event to render properly onto the calendar.

JSBin:  http://jsbin.com/kafeku/7/edit?js,output

**Comment by arshaw** [comment]
the behavior you're seeing is related to [renderEvent](http://fullcalendar.io/docs/event_rendering/renderEvent/) behavior... those events stick around until the next *refetch*. Switching from a large time window (month view) to a smaller time window (week view) doesn't trigger a refetch. If you don't like this behavior, you can turn [lazyFetching](http://fullcalendar.io/docs/event_data/lazyFetching/) to `false`.

demo w/ alert when refetch happens
http://jsbin.com/daritaqire/1/edit?js,output

**Comment by arshaw** [comment]
another option, if you always want your events to stick around, is to use the `stick` flag of the `renderEvent` method

**Comment by tonykchan** [comment]
I tried lazyFetching and stick options, but it doesn't seem to have resolved my issue.  The issue is the renderEvent behavior is not fully rendering the full event details to the calendar when it is in agendaWeek or agendaDay view mode.

If you check out the JSBin below, you'll notice that when in month view mode, I can click on each day on the month and an event with "test" title is rendered immediately on the 1st click.

If you try the same thing in agendaWeek or agendaDay view mode and start clicking on timeslots, the "test" title doesn't get rendered on the 1st click.  It only seems to refresh/update on the 2nd click.

JSBin: http://jsbin.com/jahahowogo/edit?js,output

**Comment by caseyjhol** [comment]
The problem has to do with `selectHelper`. The placeholder event isn't being removed from the calendar. Basically, the event with the title is there, but it's hidden by the selectHelper placeholder. A quick look at the source reveals:

```html
<div class="fc-content-col">
	<div class="fc-event-container fc-helper-container">
		<a class="fc-time-grid-event fc-v-event fc-event fc-start fc-end fc-helper fc-short" style="top: 395px; bottom: -417px; z-index: 1; left: 0%; right: 0%;">
			<div class="fc-content">
				<div class="fc-time" data-start="9:00" data-full="9:00 AM - 9:30 AM">
					<span>9:00 - 9:30</span>
				</div>
			</div>
			<div class="fc-bg"></div>
		</a>
	</div>
	<div class="fc-event-container">
		<a class="fc-time-grid-event fc-v-event fc-event fc-start fc-end fc-draggable fc-resizable fc-short" style="top: 395px; bottom: -417px; z-index: 1; left: 0%; right: 0%;">
			<div class="fc-content">
				<div class="fc-time" data-start="9:00" data-full="9:00 AM - 9:30 AM">
					<span>9:00 - 9:30</span>
				</div>
				<div class="fc-title">test</div>
			</div>
			<div class="fc-bg"></div>
			<div class="fc-resizer fc-end-resizer"></div>
		</a>
	</div>
	<div class="fc-highlight-container"></div>
	<div class="fc-bgevent-container"></div>
	<div class="fc-business-container"></div>
</div>
```

I changed the color of the helper to red and made it transparent to make it easier to see:

http://jsbin.com/fihoducira/edit?css,js,output

**Comment by arshaw** [comment]
ah ok. thanks @caseyjhol. the likely solution is to clear all select helpers (events that masquerade as selections) when any event render/rerender happens.

**Comment by arshaw** [comment]
@tonykchan the workaround is to set [selectHelper](http://fullcalendar.io/docs/selection/selectHelper/) to `false`.

**Comment by arshaw** [comment]
updated recreation: https://codepen.io/arshaw/pen/pogwjZJ?editable=true&editors=001

i don't really want to change the API to automatically clear the selection upon event add. i can imagine scenarios where people would want to keep the selection.

the solution is to call `calendar.unselect()` before or shortly after creating the event (as in the updated recreation)
