### ISSUE TITLE
fullcalendar doesn't render in angular material tabs

### ISSUE THREAD

**Issue by sexobert** [fullcalendar/fullcalendar#3243]
fullcalendar doesn't render in angular material tabs

**Comment by arshaw** [comment]
Would you be able to post a [runnable, stripped-down demonstration of the bug](http://fullcalendar.io/wiki/Reduced-Test-Cases/)? Would really appreciate it because the time saved reproducing will be time spent fixing.

**Comment by sexobert** [comment]
Thanks for your rep

**Comment by sexobert** [comment]
Thanks you, I start a new project and I noticed that the calendar didn’t because of the ’ng-cloak’ from angular.
Now  the  calendar render in  angular material, but no calendar’s button works in  the tab, but as soon I  remove the calendar from the tab(angular material tab) ,all  works fine.
I’ve attached an example.
Thank you.
