### ISSUE TITLE
always display time on the left side

### ISSUE THREAD

**Issue by richardrails** [fullcalendar/fullcalendar#3244]
We have fullcalendar in our app and we limit start time and end time like in this picture:
https://s32.postimg.org/ioh698o45/screen.png

As you see, we do not have any title hours in the first column because we start calendar view at 8:30 and end at 11:30. The slot is 1 hour so no times are displayed. Is there any chance to always display times in any single period?

**Comment by arshaw** [comment]
here is an existing ticket addressing your problem:
https://github.com/fullcalendar/fullcalendar/issues/2786
&uarr;
Could you please visit the link, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates?

**Comment by link2pk** [comment]
hi @arshaw , (ref http://imgur.com/a/wV1ki ) Is there any way by which I could have week days on left and time on top ? I mean, just the reversed view of this screen.

Thanks
