### ISSUE TITLE
Conveniently set a view's arbitrary date range

### ISSUE THREAD

**Issue by avinashramireddy-rapidd** [fullcalendar/fullcalendar#3245]
Hi,
I have produced my scenario below.
[Changing events with Date range picker(custom button) in custom view](http://jsbin.com/wifiva/embed?html,js,console,output)

When I searched for solution ,I found only gotoDate but not for range of dates.
(This is already posted in the issue#3233.But it was closed(Please accept anyone.I am new to issue github issues.))

**Problem:**
I want to change view(agenda) with events on selecting date range and it should not affect other views(more like my agenda view is behaving independently).

**Comment by arshaw** [comment]
Thanks for the JSBin, but it's really hard for me to understand what is going on, and difficult for me to understand what the problem is.

Can you further isolate the problem in the JSBin? Make the code smaller...
1. remove the datepicker
2. remove the custom "agendaAll" view

**Comment by avinashramireddy-rapidd** [comment]
Hi,
My actual **problem is with datepicker inside custom "agendaAll" view.**.

**I want to load  agendaAll events only within the range selected.**

I tried different possibilites like addEventSource,removeEventSource,removeEventSources, rerenderevent., etc.

In best case,I am able to load same in all views including agendaAll.

I want agendaAll to be independent view which contains list of events.

**Comment by arshaw** [comment]
Ok I understand a bit better. Thank you. You want a datepicker to decide the range of dates within a custom view. This is currently somewhat difficult. I assumed your bug report was a problem with current existing working behavior, thus the confusion.

Workaround:
- set a `defaultDate` as your start date
- create a [custom view](http://fullcalendar.io/docs/views/Custom_Views/) with a `duration` as your end date minus your start date
- whenever you want to change the date range reinitialize the whole calendar. this is a workaround until [dynamic option setting](https://github.com/fullcalendar/fullcalendar/issues/564) is available

I will keep this issue open to discuss ways to make this more convenient.

Potential solution # 1:
introduce new `start`/`end` parameters. make these [dynamically settable](https://github.com/fullcalendar/fullcalendar/issues/564).

Potential solution # 1:
have `start` and `duration` parameters in the same vein.
(`start` can essentially already be achieved via `defaultDate` and `duration` probably already works even tho it is documented as a custom-view option only)

**Comment by luser** [comment]
I've been trying to create a calendar that displays a few days' worth of events where the first day is always today. I very nearly got this to work by extending `AgendaView`, and overriding `computeRange` to always return `intervalUnit: 'days'`, which is not really a bad solution except I got stuck trying to make the calendar update when the day changes (using ``), because the check here in `renderView` skips the rendering:
https://github.com/fullcalendar/fullcalendar/blob/5ef561d16943f5a8583dd6d9784d2d1c4b9e26ac/src/Calendar.js#L642

A simple fix might be to call `currentView.computeRange(date)` there and see if it returns a different interval than the view's current interval.

**Comment by luser** [comment]
I used a horrible workaround for the time being, but it did the trick:
https://github.com/luser/calendarview/blob/26737c49b8ee45536180b772b0a733da98766554/calendarview.js#L93

**Comment by arshaw** [comment]
This is now very possible in **v3.3.0**
Blog post: https://fullcalendar.io/blog/2017/03/fullcalendar-33-and-scheduler-16/

See [visibleRange](https://fullcalendar.io/docs/current_date/visibleRange/)
