### ISSUE TITLE
Vertical Resource View in agendaDay hide empty resources

### ISSUE THREAD

**Issue by tufanayd** [fullcalendar/fullcalendar#3247]
Hi,

How can I hide the resources which doesn't have any events based on the day change?

**Comment by arshaw** [comment]
duplicate of:
https://github.com/fullcalendar/fullcalendar-scheduler/issues/98
&uarr;
Could you please visit the link, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates?
