### ISSUE TITLE
timeFormat failing on 'tt'

### ISSUE THREAD

**Issue by Eric81235** [fullcalendar/fullcalendar#3249]
### Bug Reports
When using the timeFormat option, if I want to display the time like  06:45 am - 01:30 pm I used to be able to use the double letter 't'.  Using   timeFormat:'hh:mm tt'   will display the letter tt instead of am and pm.  using a single letter 't' will work, but display  06:45 a - 01:30 p, missing the letter 'm'
Using Version 2.8.0

**Comment by arshaw** [comment]
you should use `'a'` or `'A'` to get a two-letter am/pm. it's just a normal moment formatting command: http://momentjs.com/docs/#/displaying/format/

**Comment by Eric81235** [comment]
Thank you !
