### ISSUE TITLE
FullCalendar Event full height in Month View

### ISSUE THREAD

**Issue by Eric81235** [fullcalendar/fullcalendar#3250]
### Feature Requests
While converting from Fullcalendar 1.5.4 to 2.8.0 it seems that the ability to display the events in full size was lost in Month View. Now the events are collapsed to a single line.
![fullcalendarmonthview](https://cloud.githubusercontent.com/assets/1626266/16374981/e27b2776-3c0d-11e6-9e30-3a41f838c44d.png)

**Comment by arshaw** [comment]
hi Eric, please see the discussion here:
https://github.com/fullcalendar/fullcalendar/issues/2853
&uarr;
Could you please visit the link, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates?

**Comment by Eric81235** [comment]
Thanks for the link info. I understand now that a choice was made to limit the events to one line. Following the links it mentions we could use some CSS to recreate the previous behavior. But I could not figure out the CSS needed. An option would have been much easier to deal with this. So for now I was thinking to make it easier for users to go in week mode. For that reason I added a Feature Enhancement request # 3254. But most of all thank you so much for your fantastic jQuery plugin !
