### ISSUE TITLE
external event dropping revert function

### ISSUE THREAD

**Issue by demobiel** [fullcalendar/fullcalendar#3252]
Hi
not sure how it should work, but I am looking for a way that I can revert the drop of an external event.

I don't understand the documentation either, because it says that "eventReceive" is only called after the drop event and after the event has been rendered to fullcalendar, but also during the "drop" callback the event is already on the calendar, so I don't really understand why there is this difference.

My goal is that I can call my API when an external event is dropped, if there is an error returned by the API that I can revert the event.

**Comment by arshaw** [comment]
You could try listening to [drop](http://fullcalendar.io/docs/dropping/drop/), which happens before the new event is created. Don't put in anything in the [Associated Event Data](http://fullcalendar.io/docs/dropping/eventReceive/)... will avoid eventReceive. Then, add the event manually via [renderEvent](http://fullcalendar.io/docs/event_rendering/renderEvent/).

But this is awkward. This ticket will explore finding a proper solution.

**Comment by demobiel** [comment]
hi

Thanks for your quick reply, and sorry for my delay!

So as I understand there is no embedded way right now. I need to implement this only next week, and willing to share my experiences, or how I did it in the end.

I will keep you posted.

Andries

**Comment by willstdueswissen** [comment]
any new about it?
or an simple example how revert an external drop?

it would be awesome to get this feature.
what about a function like:
`afterDrop: function(event, delta, revertFunc) {`

**Comment by arshaw** [comment]
jsbin of workaround:
http://jsbin.com/zocurejupa/1/edit?js,output
(see the `drop` callback at the bottom)

**Comment by ebejko** [comment]
The solution works, but I tried it with the extra property `overlap: false`, and it still drops the event if the condition is met. Do I have to manually check for overlaps with the provided solution, or is there an additional workaround?

**Comment by arshaw** [comment]
eek, yes you'd need to also take responsibility of checking for the overlap.

**Comment by MinhNguyen41092** [comment]
Hi @arshaw, I have a question. After reading your workaround I still can't find where did you remove Associated Event Data? I'm trying to implement this feature but I can't find any idea from the docs. Hope you can help me in this matter.

**Comment by dneuschaefer-rube** [comment]
I was about to create an issue for this, but found this one instead. I think `eventReceive` should work just like `eventDrop` does, in that the drop info includes a revert function, which a) removes the dropped event from the calendar and b) re-adds it to the source calendar, in case the event was dragged from another fullcalendar instance. If this kind of interaction is out of scope, how about also adding a `revert` function for the `eventLeave` hook?

**Comment by Anubarak** [comment]
Are there any updates for this? We need the premium version of fullcalendar for a project, the only thing left is to cancel a drag event because we need server side validation and cancel the drop

**Comment by arshaw** [comment]
`eventReceive` now has a `revert` function: https://fullcalendar.io/docs/eventReceive

**Comment by nicolascousin** [comment]
In v5.1.0, I don't have the `revert` function or the `relatedEvents` array mentioned in the doc.
Is this something comming up ?

**Comment by arshaw** [comment]
@nicolascousin , that's actually a bug and there's a ticket for it: https://github.com/fullcalendar/fullcalendar/issues/5610

**Comment by ErickTucto** [comment]
`revert` function to `eventDragStop` ???
