### ISSUE TITLE
weekClick event

### ISSUE THREAD

**Issue by EricLendvai** [fullcalendar/fullcalendar#3254]
Could we have a weekClick event so we can switch to the week view for the selected week. Thanks.
![fullcalendarenhancementrequest_2016_06_29_1](https://cloud.githubusercontent.com/assets/1626266/16444113/4d590d72-3d91-11e6-9fca-ac41f7fe80ca.png)

**Comment by arshaw** [comment]
similar to #2314

**Comment by Eric81235** [comment]
Hello Adam,
I don't believe it is similar to 2314. It is not a question of double click, but a single click in the cell with the week number.

**Comment by arshaw** [comment]
Thanks Eric. Yes, this issue is different enough where it warrants its own ticket for sure, but I will likely tackle it at the same time as #2314 because they are similar enough.

**Comment by Eric81235** [comment]
Great thank you, looking forward for the new features. Your calendar is wonderful!

**Comment by arshaw** [comment]
as of v5, week number are rendered as little squares at the top-left corners of the row-of-days. They no longer own their own columns. thus, there's nowhere to click other than the link, in which case [navLinkWeekClick](https://fullcalendar.io/docs/navLinkWeekClick) is now sufficient
