### ISSUE TITLE
Display events in two columns in a day in Month View

### ISSUE THREAD

**Issue by joe11joe** [fullcalendar/fullcalendar#3256]
I am using the fullcalendar month view to display my time slots as events. Following is the current view of my Month view with events
![day view original](https://cloud.githubusercontent.com/assets/17080934/16485174/02faf042-3edb-11e6-9ff8-9ff4ea5afaae.jpg)

I want to display events in two columns in a day like the following screen.
![month view](https://cloud.githubusercontent.com/assets/17080934/16485189/20fea5ac-3edb-11e6-8549-ec952404d662.jpg)

Can anyone help me in this regard. Thank you in advance.

**Comment by arshaw** [comment]
this is currently not possible. i will close this ticket and reopen it if there is sufficient demand. thanks

**Comment by joe11joe** [comment]
Thank you @arshaw
