### ISSUE TITLE
Background event rendering on IE10

### ISSUE THREAD

**Issue by siliconalchemy** [fullcalendar/fullcalendar#3257]
The background events example on the fullcalendar website doesn't display correctly on IE10:
http://fullcalendar.io/js/fullcalendar-2.8.0/demos/background-events.html
![fullcalendar-ie10](https://cloud.githubusercontent.com/assets/4799996/16519007/0e86d504-3f7e-11e6-8c89-8c83e70ed33c.png)

**Comment by arshaw** [comment]
this bug has come up a number of times but it was really hard to recreate, and thusly been closed.

what version of Windows are you using?

if you refresh the screen, does it correct the dsplay?

**Comment by siliconalchemy** [comment]
Windows 7, IE 10.  I've just loaded it again to check and now it's correct :(  Well :) it's correct but :( I can't reproduce it..

**Comment by siliconalchemy** [comment]
It's now working on all my other fullcalendar pages as well.  How odd.  If I see it again I'll try and reproduce or diagnose at the time.
