### ISSUE TITLE
removeEvents is not working properly

### ISSUE THREAD

**Issue by kinsbrunner** [fullcalendar/fullcalendar#3258]
Hi Adam,

I have been facing several issues while trying to removeEvents. I am currently working with externally dragged events. Issues are not happening when events are read from DB. Based on this last comment, I believe issues could be related to [this](https://github.com/fullcalendar/fullcalendar/issues/2928) other open issue but, I am not completelly sure.

I could write down 2 scenarios where I am facing issues:
1. When dragging and dropping an external event into the calendar, I am making a uniqueness check and if it does not fail, I will update the event with the ID inserted into the DB. When this uniqueness check fails (as expected), event should be removed but, then trying to remove this new event, it is not possible. I also tried to update ID with -1 when it fails and then trying to remove event with ID = -1 but could not make it work.  I believe this issue could be solved once [this](https://github.com/fullcalendar/fullcalendar/issues/3252) other issue is implemented as it could perfectly be a solution for me. When could we expect to have it in place?

2.Second scenario is when I drag and drop an external event into the calendar, it gets created in DB, ID of the event gets updated with the ID inserted on the DB and, when trying to remove that event, it is not working. In case I would refresh page and try deleting it, it would work perfectly fine. 

Part of my personal implemented code is on [this](http://stackoverflow.com/questions/38132920/fullcalendar-not-able-to-remove-non-saved-events) link. For being honest, it sounds to me that both issues are strongly related.

Could you please let me know how to handle this in case you already find any temp workaround?

Really thanks in advance and I strongly appreciate the huge effort you are all doing to manage this wonderful plugin. 

Regards.
Alejandro.

**Comment by arshaw** [comment]
to work around this, i would have two separate ID systems: a "client" ID and a "backend" ID. the `id` on the fullCalendar event objects would be considered a client ID.

Sorry i can't go into more depth. #2928 will help you with this when implemented. also, #3252 might help, but in the meantime, use the advice from the [last comment](https://github.com/fullcalendar/fullcalendar/issues/3252#issuecomment-229272541) as a workaround.

**Comment by kinsbrunner** [comment]
Thanks for your answer. The point is that events are not getting deleted unless I refresh the page so events get an ID set....
Any idea?

**Comment by arshaw** [comment]
If you use [renderEvent](http://fullcalendar.io/docs/event_rendering/renderEvent/) as mentioned in [my comment](https://github.com/fullcalendar/fullcalendar/issues/3252#issuecomment-229272541) you likely won't have this problem anymore, assuming you set the stick flag to `false`.

**Comment by laikaboo** [comment]
$(this).remove() can be used instead of removeEvents. its working.
