### ISSUE TITLE
Different longPressDelay according to the type of interaction

### ISSUE THREAD

**Issue by Marco-Guido** [fullcalendar/fullcalendar#3259]
It would be very nice to have a way to differentiate the longPressDelay according to the type of interaction on touch devices.
We would like to update to 2.7+ and enable drag-n-drop and resize but can't because our users are used to short delays when selecting a time-range.

**Comment by arshaw** [comment]
thanks for the request. this shouldn't be very hard to implement

**Comment by jorisvh** [comment]
Would you have any time frame in mind to implement this? I'm working with Marco and, as he said, we can't update to the latest versions (we tried and had to rollback because our users are so used to different delays for different actions). If time is the constraining resource, we might be able to help, with a bit of guidance from your side.

**Comment by caseyjhol** [comment]
Could possibly even just add support for an array or object with the same longPressDelay attribute for backwards compatibility. If just a number is used, the same delay is used for all interactions.

**Comment by arshaw** [comment]
hey @caseyjhol i'd rather create new properties altogether, `eventLongPressDelay` and `selectLongPressDelay`, similar to how the `*Constraint` properties are named.

**Comment by jorisvh** [comment]
Hey guys, any news regarding this? @caseyjhol if you already have some code (v2 or v3 are both fine), I'd have no problem patching my files.

**Comment by caseyjhol** [comment]
@arshaw Do you want to keep the longPressDelay property, and have eventLongPressDelay and selectLongPressDelay default to that value? Or do you want to completely remove the longPressDelay property?

**Comment by arshaw** [comment]
@caseyjhol, the former: `eventLongPressDelay` and `selectLongPressDelay` should default to `longPressDelay` if not defined.

**Comment by toxaq** [comment]
I just upgraded to 2.9 from 2.3 after purchasing the scheduler and this long hold was an unexpected change for me. The new properties @arshaw has suggested sound great.

**Comment by arshaw** [comment]
released in [v3.1.0](https://github.com/fullcalendar/fullcalendar/releases/tag/v3.1.0)
https://fullcalendar.io/docs/event_ui/eventLongPressDelay/
https://fullcalendar.io/docs/event_ui/selectLongPressDelay/

**Comment by toxaq** [comment]
For future visitors, that second link is broken, instead: https://fullcalendar.io/docs/selection/selectLongPressDelay/
