### ISSUE TITLE
If I want  to apply Fullcalendar Scheduler to the DNN platform.

### ISSUE THREAD

**Issue by poonchunkit** [fullcalendar/fullcalendar#3261]
Can i apply the scheduler in it?
My error:
Uncaught TypeError: Cannot set property 'schedulerVersion' of undefined

Uncaught TypeError: $.widget is not a function

**Comment by espen** [comment]
Please see http://fullcalendar.io/support/. Any questions should be asked on StackedOverflow.

**Comment by arshaw** [comment]
it's probably the order of your script tags. please see the order here: view-source:http://fullcalendar.io/js/fullcalendar-scheduler-1.3.2/demos/scale.html
