### ISSUE TITLE
Found this Calendar on Reddit...

### ISSUE THREAD

**Issue by StudioJunkyard** [fullcalendar/fullcalendar#3263]
Found this link to another Calendar on Reddit, thought I'd share it here, as there are some nice ideas.
Apologies, if you've seen it already.

https://www.ganttology.com/chart/shared/2625/1662695519/

**Comment by arshaw** [comment]
Awesome! I have not seen it yet. Some other feature requests that i see in this demo:

https://github.com/fullcalendar/fullcalendar/issues/2276
https://github.com/fullcalendar/fullcalendar/issues/433
