### ISSUE TITLE
allDayText with localization

### ISSUE THREAD

**Issue by phillylovepark** [fullcalendar/fullcalendar#3265]
When trying to set the allDayText property with a localized calendar, it seems that the translated string overwrites the property.

[Here is the jsbin for testing](http://jsbin.com/soxeramewa/edit?html,js,output). If you remove the translation script file, the custom text is displayed.

**Comment by arshaw** [comment]
reproduced.

the bug is caused by the language defining the text with allDayHtml (an undocumented option) and allDayText does not have the power to override it. if you set `allDayHtml` instead you can probably make it work

**Comment by phillylovepark** [comment]
Yes, setting `allDayHtml` makes it work. Many thanks!

**Comment by arshaw** [comment]
fixed in v5 (and maybe even v4)
