### ISSUE TITLE
Use other types of calendars, ex. Persian Jalali calendar

### ISSUE THREAD

**Issue by Emad4000** [fullcalendar/fullcalendar#3267]
I'm using your calendar component, in one of my projects, but my users are Persian and use Jalali calendar in their culture.
Is it possible to add a feature to change the calendar type, or add an alternative calendar type to the main calendar?
Google Calendar uses the 2nd method, mean we can add a new calendar type to the default Gregorian calendar.

**Comment by arshaw** [comment]
please see existing tickets:
https://github.com/fullcalendar/fullcalendar/issues/2105 (Hijri)
https://github.com/fullcalendar/fullcalendar/issues/1813 (Jalali)
&uarr;
Could you please visit the links, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates?
