### ISSUE TITLE
Miscalculation of height if the change is border-width

### ISSUE THREAD

**Issue by pinin** [fullcalendar/fullcalendar#3268]
if it sets a different border width than height 1px badly calculated.
The scroll bar is always displayed. It should not be.
I can not get rid of it in any way.

```
.fc th,
.fc td {
    border-width: 6px;
    color: #fff
}
.fc-body {
    background-color: #ededed;
}
```

sorry if i wrote the wrong comment.
Thanks
/---------------
Supplement: When used scrollbar. He should have .fc-widget-header also filler.
Something like:
```
.fc-row.fc-widget-header {
    margin-right: 17px;
}
```

**Comment by arshaw** [comment]
Would you be able to post a [runnable, stripped-down demonstration of the bug](http://fullcalendar.io/wiki/Reduced-Test-Cases/)? Would really appreciate it because the time saved reproducing will be time spent fixing.
