### ISSUE TITLE
Prevent Duplicate jQuery Instances

### ISSUE THREAD

**Issue by mikebronner** [fullcalendar/fullcalendar#3272]
__No JSBIN example added, because this issue is relevant mainly when browserifying the library, which can't be done in JSBIN.__

To prevent duplicate loading of jquery libraries, perhaps implement the fullcalendar factory something like this:

```js
(function(factory) {
	if (typeof define === 'function' && define.amd) {
		define([ 'jquery', 'moment' ], factory);
	}
	else if (typeof jQuery !== 'function' && typeof exports === 'object') { // Node/CommonJS
		module.exports = factory(require('jquery'), require('moment'));
	}
	else {
		factory(jQuery, moment);
	}
})(function($, moment) {
// ...
};
```

**Comment by arshaw** [comment]
Is the `typeof jQuery !== 'function'` part your only addition?

In a Browserify environment, this will likely force fullcalendar to use the browser global of jQuery if it is available. but why is this better that doing `require('jquery')` a second time? Browserify should be smart about returning the same reference as before. that's one if its primary duties.

**Comment by mikebronner** [comment]
Sorry, I forgot to explain that this is of importance for external query that isn't pulled in through browserify.

**Comment by arshaw** [comment]
the best solution for that is to use [browserify-shim](https://github.com/thlorenz/browserify-shim)
