### ISSUE TITLE
Immutable Moment RFC

### ISSUE THREAD

**Issue by maggiepint** [fullcalendar/fullcalendar#3274]
Hi,

This is not really an issue, but it's the easiest way to get in contact with you - sorry about that :-).

I am one of the maintainers of Moment.js.
I want to make you aware of moment/moment-rfcs#2. This proposes adding a second immutable API to Moment.js for V3. We are quite serious about moving forward with this one, and are already in the process of prototyping code and seeing up the repo for this kind of change. Because being able to have both immutable and mutable objects coming from Moment will affect libraries that depend on it, like this one, I want to give you a heads up and ask you to add any comments you feel would be helpful.

There's also an executive summary of what's going on on my blog, if you don't want to read the whole thing: https://maggiepint.com/2016/07/16/immutability-its-happening/

We would greatly appreciate hearing what you think.

Maggie

**Comment by arshaw** [comment]
Thanks @maggiepint. I'm going to see how this plays out. I'm in a similar boat as @icambron with Twix... FullCalendar is a plugin that uses moments internally, and also spews out moments in many parts of the API, and caller of my API might want to receive immutable OR mutable.. and I should I support both? Whatever you decide, I can make it possible.

**Comment by arshaw** [comment]
since v4 won't have moment as a dependency anymore, i'm closing this issue
