### ISSUE TITLE
Priblem with eventlimit and fullcalendar in Bootstrap modal

### ISSUE THREAD

**Issue by Emad4000** [fullcalendar/fullcalendar#3276]
Hi
I use fullcalendar component in my web application. It placed it in a bootstrap modal. meanwhile I set it's eventlimit config to true. But when I open the modal and click on "more events" link, the sub dialog doesn't appear.

**Comment by arshaw** [comment]
Would you be able to post a [runnable, stripped-down demonstration of the bug](http://fullcalendar.io/wiki/Reduced-Test-Cases/)? Would really appreciate it because the time saved reproducing will be time spent fixing.
