### ISSUE TITLE
Internet Explorer 11 doesn't work

### ISSUE THREAD

**Issue by marcdebus** [fullcalendar/fullcalendar#3280]
I get some javascript error messages in internet explorer 11, also in your demo-pages. (version 2.9.0)

`basic-views.html (12,2): The value of the property '$' is null or undefined, not a Function object

fullcalendar.min.js (6,161): 'jQuery' is undefined

jquery.min.js (2,29842): Object doesn't support property or method 'addEventListener'`

In Edge, Google Chrome and Firefox it works.

**Comment by arshaw** [comment]
you probably have IE 11 stuck in an old document mode. that error is common for older version of IE that do not support jQuery 2 and above
