### ISSUE TITLE
AllDay with EndTIME dosn't show the Last Day in Month and WeekView

### ISSUE THREAD

**Issue by NiklasKamenisch** [fullcalendar/fullcalendar#3281]
http://jsbin.com/lefapu/edit?js,output
If i set Event like this: 
        title: 'Conference',
        start: '2014-11-11T08:00:00',
        end: '2014-11-13T16:00:00',
        allDay: true

The last Day will not be show on the Week and MonthView. I need the Flag "allDay" to cleanup the other Views. Without the Flag i have the correct Range in the Month.

**Comment by arshaw** [comment]
you problem is the same problem as this ticket:
https://github.com/fullcalendar/fullcalendar/issues/2985
&uarr;
Could you please visit the link, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates?
