### ISSUE TITLE
Create re sizable event on cell select event in weekview.

### ISSUE THREAD

**Issue by TejasCMehta** [fullcalendar/fullcalendar#3283]
Hi,

I am trying to create re sizable event when any user click on cell it should be automatically created with resistible icon. I did that but when I try to resize event with it end time it give error.

fullcalendar.js:9596 Uncaught TypeError: Cannot read property 'clone' of undefined

Please let me know how to create re sizable event on cell select.

**Comment by arshaw** [comment]
Would you be able to post a [runnable, stripped-down demonstration of the bug](http://fullcalendar.io/wiki/Reduced-Test-Cases/)? Would really appreciate it because the time saved reproducing will be time spent fixing.
