### ISSUE TITLE
[FR] continuous scrolling

### ISSUE THREAD

**Issue by georgehrke** [fullcalendar/fullcalendar#3284]
We are interested in having continuous scrolling in the calendar views.

Users should be able to move forward/backward by simply scrolling.
Something like: https://www.youtube.com/watch?v=qCqJzUSo_Us

Is this something you would merge into fullcalendar?
(If not I would simply implement custom views for my use case)

Ref: https://github.com/owncloud/calendar/issues/49

**Comment by arshaw** [comment]
yes, that is really cool. i'd love it to be implemented. it is rather challenging. there's already a ticket for it:
https://github.com/fullcalendar/fullcalendar/issues/2276
&uarr;
Could you please visit the link, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates?
