### ISSUE TITLE
isAnimating JS error with jQuery (UI?)

### ISSUE THREAD

**Issue by arshaw** [fullcalendar/fullcalendar#3285]
A customer reported that they are receiving a JS error related to `this.isAnimating` being undefined.

I have not been able to nail down recreation steps, but it is clear that this area of the code needs reworking:

https://github.com/fullcalendar/fullcalendar/blob/v2.9.0/src/common/MouseFollower.js#L66-L75

That callback should use `_this` across the board. It is fed into jQuery's animate, which has the power to change the `this` context, so we cannot trust it.

**Comment by papaloizouc** [comment]
if you fix animating the error happens on:
```
top: this.top0,
left: this.left0
```
and then on
```
this.largeUnit
```

**Comment by arshaw** [comment]
@papaloizouc could you give me more info on the environment i need to run this in to recreate? is this Locker Services that we've been talking about?

**Comment by papaloizouc** [comment]
hi it seemed to be working fine when using the un-minified version,
after minify, i was getting `Cannot read property 'isAnimating' of undefined` on every drag event.

i changed `this.isAnimating to _this.isAnimating`, same for `top0 left0 and largeUnit` and now it works fine.

**Comment by papaloizouc** [comment]
if it helps i'm on version FullCalendar v2.3.1

**Comment by arshaw** [comment]
this has been fixed and release in [v2.9.1](https://github.com/fullcalendar/fullcalendar/releases/tag/v2.9.1).
