### ISSUE TITLE
custom time slot

### ISSUE THREAD

**Issue by avanti-technologies** [fullcalendar/fullcalendar#3287]
Hello,

# **Introduction**
I will have to use fullcalendar and the scheduler plugin with some advanced configuration abilities. One of them is the use of custom time slot.
Our users will be given the possibility to create an array of time range and it should be displayed in the calendar.

As an example, they will want the calendar to be displayed from 8am to 12pm, and to from 12pm to 2pm.
They should also be able to set up more complex range like 8am-10am-12pm-2pm-7pm etc...

# **Restrictions**

- The view option name will be **customTimeSlot**

- The input array will be a **javascript array of moment duration**

- **minTime** will be used as it is used currently, to indicate where the customTimeSlot should be applied.

- **maxTime** will be calculated automatically by the plugin when in custom time slot mode. It will be equal to minTime + the sum of the moment durations input. It will prevent event which are not in the provided range to be displayed.

# **Developpement**
The different part of code will mainly take place in the following functions :
### For fullcalendar
- renderSlatRowHtml
- computeTimeTop

### For fullcalendar-scheduler
- rangeUpdated
- updateGridDates
- computeDateSnapCoverage

For each project, a "custom-range.html" example will be created and automated test case should be written.

# **Current state of developpement**
The functionality has been developed for both plugin. It is currently under a debugging and stabilisation process before openning a pullrequest.
The automated test case and documentation hasn't been written yet.

![fc1](https://cloud.githubusercontent.com/assets/20341279/17207854/ad4adc88-54b6-11e6-92d4-5802f757bf11.png)

![fc2](https://cloud.githubusercontent.com/assets/20341279/17208566/89ee0a3c-54b9-11e6-87c0-f2b424662e2e.png)

# **Known bugs**

- [ ] Re-arrange the event width rendering calculation for the scheduler since it is incorrect.
- [x] _In the scheduler, if I set the view has more than one, we can't scroll to the other days._

**Comment by arshaw** [comment]
hi @avanti-technologies, thanks for the submission. the feature you describe was original entered here:
https://github.com/fullcalendar/fullcalendar/issues/472
&uarr;
Could you please visit the link, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates?

I will close this ticket, but will reference it in the future, leveraging the details you've provided.

Sounds you you've began development. Have you thought about submitting a PR?

**Comment by avanti-technologies** [comment]
Hi Adam,

Sorry for the double, didn't used the right term to find the one provided.

I started the developement and the first phase is almost done. After this and some debugging, i'll create a PR to make sure you get a pretty clean and bug-less version :)

Thanks for the fast reply !
