### ISSUE TITLE
Event progress background color

### ISSUE THREAD

**Issue by Kirigetov** [fullcalendar/fullcalendar#3288]
Hi!
How can I customize the library to get a progress bar as http://take.ms/LtkO1?

**Comment by arshaw** [comment]
please see a possible solution in this ticket:
https://github.com/fullcalendar/fullcalendar-scheduler/issues/199
&uarr;
Could you please visit the link, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates?
