### ISSUE TITLE
Unwanted month view scrollbars with jQuery UI theme

### ISSUE THREAD

**Issue by snooopcatt** [fullcalendar/fullcalendar#3289]
Hey.
In you JQuery ui theme example http://fullcalendar.io/js/fullcalendar-2.9.0/demos/theme.html you have small UI problem - dates are hidden under scrollbar. refer to the attachment. Chrome 52/ windows 10
![calbug](https://cloud.githubusercontent.com/assets/1575279/17219045/9b86ecb2-54f2-11e6-989a-e1944463e8b4.PNG)

**Comment by arshaw** [comment]
jquery ui theming has been removed in v4
