### ISSUE TITLE
not renders event if source property of Event Object is set 

### ISSUE THREAD

**Issue by memboc** [fullcalendar/fullcalendar#3290]
I use {Event Object}.source for ajax request to update events (specifically event.source.url / .type)
And i nett to add new evets with this property, but it not renders. 

```
$("#calendar").fullCalendar({
    defaultView: 'month',
    events: [{
        title: 'hi!',
        start: moment(),
        allDay: false
    }],
    select: function(start, end) {
       var event = {
            title: 'new',
            start: start,
            end: end,
            source: { // if remove source it works
            	url: '/someurl',
                type: 'POST'
           }
        }
    	$("#calendar").fullCalendar('renderEvent', event);
    },
    selectable: true,
    scrollTime: moment(),
    allDaySlot: false
});
```
https://jsfiddle.net/gw0m39h4/1/

PS: I tried to use addEventSource, but it not suitable for me, because it "stick" event, and when prev/next is clicked calendar render new event twice (sticked event + loaded from url in general property events)

**Comment by arshaw** [comment]
forcing an event's source that is passed in via `renderEvent` won't work unfortunately.

if i were you, upon the select callback firing, i'd call `renderEvent` like you're doing (without the stick flag, which is what you're doing), but also update your backend to be aware of the newly create event. Then, when the user navigates away, and navigates back, a refetch will happen, and the event will be fetched from the server this time.
