### ISSUE TITLE
built JS, version: "<%= meta.version %>"

### ISSUE THREAD

**Issue by zhimin** [fullcalendar/fullcalendar#3292]
The new version (2.9.1, the enhancement on businessHours is great!) on Cloudflare: 
https://cdnjs.cloudflare.com/ajax/libs/fullcalendar/2.9.1/fullcalendar.js

/*!
 * <%= meta.title %> v<%= meta.version %>
 * Docs & License: <%= meta.homepage %>
 * (c) <%= meta.copyright %>
 */

var FC = $.fullCalendar = {
	version: "<%= meta.version %>",
	internalApiVersion: 5
};
var fcViews = FC.views = {};

**Comment by KrunchMuffin** [comment]
It's not Cloudflare, it's the original scripts

![image](https://cloud.githubusercontent.com/assets/1037197/17305193/5229d856-57f7-11e6-8b86-5d334389192f.png)

**Comment by arshaw** [comment]
@zhimin yes im seeing this in 2.9.1 (the newest)

@KrunchMuffin i'm not seeing this in v2.7.3. https://github.com/fullcalendar/fullcalendar/blob/v2.7.3/dist/fullcalendar.js

regardless, I know why this is happening. a race condition of sorts, during the build process. ill get it fixed for the next release.

**Comment by KrunchMuffin** [comment]
I was just showing a diff

**Comment by arshaw** [comment]
fixed in [v3](https://fullcalendar.io/blog/2016/09/feature-packed-releases/). thanks
