### ISSUE TITLE
Problem in placing fullCalendar in a modal dialog

### ISSUE THREAD

**Issue by Emad4000** [fullcalendar/fullcalendar#3295]
Hi
When I place my fullCalendar DOM element in a jQueryUI dialog or a Bootstrap modal, all things are OK, except "eventLimit" option. If I set "eventLimit" to true, "more" link will be appear in day cells that are busy, but when I click on "more" link, the opened window will be appear in bottom of the page, but when it's out of a dailog or modal, it will be stocked to the mentioned day cell.

**Comment by caseyjhol** [comment]
> ### Bug Reports
> You MUST have a JSBin recreation, or else your issue will be CLOSED without explanation.
> Instructions: http://fullcalendar.io/wiki/Reporting-Bugs/
