### ISSUE TITLE
Create Event with defined UTC time on "start" and "end" causes "allDay" true

### ISSUE THREAD

**Issue by jota0222** [fullcalendar/fullcalendar#3296]
HI everyone.
I found that when I create a new event with defined UTC time (like the start time on view) on "start" and "end" causes "allDay" be true. 

[http://jsbin.com/bexijuhaxa/1/edit?html,js,console](http://jsbin.com/bexijuhaxa/1/edit?html,js,console)

and, if I set allDay to false, erases the dates I set previously, setting it in time 0

[http://jsbin.com/juyujasizu/1/edit?html,js,console](http://jsbin.com/juyujasizu/1/edit?html,js,console )

I need create events based on the view, is an easy to reproduce bug when you  think on that..

**Comment by arshaw** [comment]
fortunately or unfortunately, the `startDate` you get from the view's start date is an "ambiguously-timed" moment. http://fullcalendar.io/docs/utilities/Moment/

If you call `.time(0)` on it, you'll force it to be timed.

I understand the API could be better for this.

**Comment by jota0222** [comment]
Thanks for the explanation, now I understand. However, I think that the method "hasTime()" should recognize when the time is not longer ambiguous..
