### ISSUE TITLE
Infinite loop with slotDuration undefined

### ISSUE THREAD

**Issue by MartijnWelker** [fullcalendar/fullcalendar#3298]
When setting the `slotDuration` property to something else then a duration switching views will cause 

```
while (slotTime < this.maxTime)
```

in `renderSlatRowHtml` to become an infinite loop.

http://jsbin.com/viyujokuqa/1/edit?js,output

Steps to reproduce:
- Switch to week view

Result:
- The browser locks in an infinite loop

Expected result:
- Fullcalendar falls back to a default value

**Comment by arshaw** [comment]
thanks. confirmed.

**Comment by arshaw** [comment]
now gives a JS error, which is probably more appropriate: https://codepen.io/arshaw/pen/gOPRaZq?editors=0010
