### ISSUE TITLE
Reacurring event do not show up in time line view but shows up in monthly view. (with video example)

### ISSUE THREAD

**Issue by roulendz** [fullcalendar/fullcalendar#3301]
Here is my JSbin demo
http://jsbin.com/jozidukiba/edit?js,output

Event with ID  1 has 
```
"dow": [1, 3, 4, 5, 6, 0],
```
And it disappears from timeline view but repeats shows up in monthly vies

but event with empty
```
"dow": "",
```
works

Here is video there I home is better explanation
[Youtube video explanation](https://www.youtube.com/watch?v=SdgH56t5zyU)

**Comment by arshaw** [comment]
hi @roulendz, right now, the `dow` option is not meant to work with normal events. `dow` is intended to only work for `businessHours`.

Once there is more official support for recurring events, this case will be solved:
https://github.com/fullcalendar/fullcalendar/issues/387
&uarr;
Could you please visit the link, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates?
