### ISSUE TITLE
Clip events with "..." instead of not showing

### ISSUE THREAD

**Issue by avinashramireddy-rapidd** [fullcalendar/fullcalendar#3302]
Hi,
I am using fullcalendar from past two months or so.Finally module went for testing.
They found some design issues. 

PFA 
![before 2](https://cloud.githubusercontent.com/assets/16798757/17456424/555460d0-5bd7-11e6-9690-55813bd2b74f.png)
![now 2](https://cloud.githubusercontent.com/assets/16798757/17456425/5554c2b4-5bd7-11e6-9722-3cbfc52fc542.png)

**As you see,events are coming in next line first and then clipped**.I want it to display "..." when it exceeds the length.

I wrote 
   ```
eventAfterRender: function(event, element) {
                            clipEvents();
                            colorToevents();
}; 
function clipEvents() {
                    //Clip events which exceeds cell length
                    $("#calendar a").each(function() {
                        var colspan = $(this).closest('td').attr("colspan");
                        var timespan = $(this).closest('td').find(".fc-event-container .fc-time").text();
                        var textlimit = 34+ timespan.length;//I have set aspect ratio as 2
                        var val = $(this).text();
                        var cellTextLimit = colspan == undefined ? textlimit : (textlimit * colspan);

                        console.log(val+" " +" length "+val.length +" Limit "+cellTextLimit);

                        if (val.length > cellTextLimit) {
                            $(this).text(clip($(this).text()));
                        }

                        function clip(string) {
                            return string.substr(0, cellTextLimit-4) + "...";
                        }
                    });
                }
```

**I don't want to override events(when clipped,I noticed they are overridden) because when I click event I have data coming from database.**.

Is there any work around to fix this

**Comment by avinashramireddy-rapidd** [comment]
Hi,
I made it work using

 
.fc-day-grid-event > .fc-content {
    /*white-space: inherit;*/
    text-overflow: ellipsis;
}

**Comment by arshaw** [comment]
glad you figured it out @avinashramireddy-rapidd 

here is a ticket capturing what you might have originally wanted:
https://github.com/fullcalendar/fullcalendar/issues/2853
&uarr;
Could you please visit the link, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates?
