### ISSUE TITLE
All-Day label is overlapped and half-hidden when all day events are present.

### ISSUE THREAD

**Issue by aa21** [fullcalendar/fullcalendar#3304]
Hi @arshaw, first off great work! 

Started to trial the Scheduler (v1.3.3) today, and upgraded from FullCalendar v2.8.0 to v2.9.1 to match. 

I'm seeing an issue now that wasn't happening before with v2.8.0 of FullCalendar, where the all-day label is getting horizontally cut off when there is an all-day event.

With All-Day Event:
![screen shot 2016-08-11 at 1 41 48 pm](https://cloud.githubusercontent.com/assets/486730/17579610/f403badc-5fc9-11e6-91cb-8d770c1cd6d6.png)

Without All-Day Event:
![screen shot 2016-08-11 at 1 41 44 pm](https://cloud.githubusercontent.com/assets/486730/17579611/f40799fe-5fc9-11e6-8a91-5e3aa3b2fdf7.png)

System: Chrome browser, El Capitan / OSX

Cheers
Alex

**Comment by arshaw** [comment]
Would you be able to post a [runnable, stripped-down demonstration of the bug](http://fullcalendar.io/wiki/Reduced-Test-Cases/)? Would really appreciate it because the time saved reproducing will be time spent fixing. Will reopen this ticket when you do. Thanks!

**Comment by aa21** [comment]
At the moment don't have the time, when I do I'll put up a demo for the bug or anyone else facing this is welcome to do so also.
