### ISSUE TITLE
Preserve calendar dates for the user

### ISSUE THREAD

**Issue by rahulthewall** [fullcalendar/fullcalendar#3305]
Assume the following scenario:

* The calendar is presented to the user in the weekly view. 
* The current weekly view is 8th August - 14th August. 
* The user presses the `prev` button and goes to the weekly view of 1st August - 7th August. 
* The user then navigates to a link from the calendar and then uses the browser back button to come back to the calendar page. 
* The calendar view is now reset to 8th August - 14th August. 

How would I go about preserving the calendar view. 

A possible solution would be to keep track of `defaultDate` when user presses `next` or `previous` on the calendar. I can always add/subtract a week from the current date depending on the button pressed. 

However, I currently don't know if there is a callback for `next` and `previous` currently implemented (and unforutnately I could not find anything like it in the documentation). Any idea as to how I would go about implementing this? 

Thanks!

**Comment by Tirke** [comment]
There is in fact a callback typically used when you want to do an action when the user changes dates and it is _viewRender_.
[Click for more informations](http://fullcalendar.io/docs/display/viewRender/)

**Comment by rahulthewall** [comment]
Thanks, that is exactly what I needed!
