### ISSUE TITLE
More events in cell is cut 

### ISSUE THREAD

**Issue by avinashramireddy-rapidd** [fullcalendar/fullcalendar#3306]
Hi,
PFA
![screenshot 16](https://cloud.githubusercontent.com/assets/16798757/17587286/9723ecb2-5fc7-11e6-8163-2f7270e22cfc.png)

I tried setting 

> 
> a.fc-more {
>     z-index: 9999;
> }

but it didn't do anything..

**Comment by arshaw** [comment]
Would you be able to post a [runnable, stripped-down demonstration of the bug](http://fullcalendar.io/wiki/Reduced-Test-Cases/)? Would really appreciate it because the time saved reproducing will be time spent fixing. Will reopen when you do. Thanks!
