### ISSUE TITLE
Remove/hide time slot ranges

### ISSUE THREAD

**Issue by jeremymcminn** [fullcalendar/fullcalendar#3307]
I've been able to remove time slot ranges based on background events created by my users (see below), this is all working great and looks fine on the calendar.

9AM - 12PM Visible
12PM - 5PM Removed
5PM - 8PM Visible

```
loading: function(bool) {
    if (!bool){
        var start = $(".fc-slats").find("[data-time='12:00:00']");
        var end = $(".fc-slats").find("[data-time='17:00:00']");
        $('#calendar').fullCalendar( 'removeEvents', appt_break_id);
        $(start).nextUntil(end, 'tr').remove();
    }
}
```

This works great when the calendar is empty, or there are events in the time range 9AM- 12PM, however if there are events in the 5PM - 8PM slot, they render in a position as if the .fc-slat tr rows are still there (see attached).

Is there someway I can force a windowResize method (as resizing the window causes the events to fall in place correctly) or something else?

![screenshot from 2016-08-12 09 43 23](https://cloud.githubusercontent.com/assets/6614789/17617321/63d9160c-6071-11e6-86f3-782dbc8e204e.png)

![screenshot from 2016-08-12 09 44 59](https://cloud.githubusercontent.com/assets/6614789/17617330/78debe80-6071-11e6-877d-78a12399343b.png)

**Comment by jeremymcminn** [comment]
$(window).resize() did the trick at the end of the above code, the only thing is it makes it a wee bit "jumpy".

**Comment by arshaw** [comment]
hi @jeremymcminn this is a cool trick. if you are interested, there is another ticket for doing official support for this (not yet implemented):
https://github.com/fullcalendar/fullcalendar/issues/472
&uarr;
Could you please visit the link, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates?

**Comment by jeremymcminn** [comment]
Thanks @arshaw - I'll monitor that development closely, for the time being this seems to work well enough as limited users are using this function for the time being.

**Comment by samipadwani** [comment]
Hello @jeremymcminn $(window).resize() is not working for me.
