### ISSUE TITLE
display minTime and maxTime by first event

### ISSUE THREAD

**Issue by paulocastellano** [fullcalendar/fullcalendar#3308]
Hi,

I searched the documentation but not found.

I want make this:

minTime: 09:00
maxTime: 18:00

Ok no problem, but if i have any event on 08:00, i want change minTime to 08:00.

Its possible?

Thanks

**Comment by arshaw** [comment]
Hi @paulocastellano i think you'd be interested in this conversation:
https://github.com/fullcalendar/fullcalendar/issues/3212
&uarr;
Could you please visit the link, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates?
