### ISSUE TITLE
How to disable external event droping outside businessHours?

### ISSUE THREAD

**Issue by roulendz** [fullcalendar/fullcalendar#3309]
Hello,
I was wondering, how to disable drooping events outside bussinesHours.

Can you give me some guidance?

I was trying but no success 
```
$(document).on('mouseover', '.fc-nonbusiness' , function(){
    disableCursor();
}); 
$(document).on('mouseleav',  '.fc-nonbusiness' , function(){ 
    $('body').removeClass('fc-not-allowed');
});
```
Any help would be appreciated.

**Comment by arshaw** [comment]
`eventConstraint: "businessHours"` should work

http://fullcalendar.io/docs/event_ui/eventConstraint/

**Comment by roulendz** [comment]
Thanks, it worked like a charm!
