### ISSUE TITLE
eventRender should know if segment is the start/end

### ISSUE THREAD

**Issue by svenkatesh-nyros** [fullcalendar/fullcalendar#3311]
How to disable the events fc-title showing its name in the next row first column if the events end date is in next week day.
Ex: start_date: 2016-08-19 end_date: 2016-08-29 the title is displaying in the following dates of week first column like in 21st and 28th day in the calendar.How to stop this.
Please give me suggestion regarding this.Any help would be appreciated.

**Comment by arshaw** [comment]
You can use [eventRender](http://fullcalendar.io/docs/event_rendering/eventRender/) to achieve this but unfortunately there is no clean API for determining if the segment is the starting or ending span of an event, you'll need to query the DOM:

```js
eventRender: function(event, el) {
	if (!el.hasClass('fc-start') && !el.hasClass('fc-end')) {
		el.find('.fc-title').remove();
	}
}
```

leaving this open for discussion on how to improve this.

**Comment by ChazyTheBest** [comment]
Also, if you append an element (like a delete button) inside the `element` (or even deeper `.fc-content`), it will be shown in all weeks.

I think this should be fixed, the default behavior. And the possibility of knowing if segment is start/end could as well be discussed, but it fits better in a PR.

I mean, the default behavior should be to not repeat the element on each week, and if it's long enough it could be displayed in the next weeks, like if the weeks were lines (that could be added as an option).

That's my suggestion. The button, as it's a custom element, we should do the check to show it wherever we want (the logic tell me it should be at the end of the element).

**Comment by arshaw** [comment]
This issue has been addressed in the latest alpha release (4.0.0-alpha.2)
[See the blog post &raquo;](https://fullcalendar.io/blog/2018/10/release-v4-alpha2)

https://fullcalendar.io/docs/v4/eventRender

`isStart` and `isEnd`

**Comment by arshaw** [comment]
I'm closing this issue to signify that it's implemented (since v4-alpha2). I'll comment on this thread again when v4 is officially released.

**Comment by arshaw** [comment]
[V4 was officially released a few days ago!](https://fullcalendar.io/blog/2019/03/v4-officially-released)
