### ISSUE TITLE
Events longer then current view are not displayed when using JSON

### ISSUE THREAD

**Issue by vklaus** [fullcalendar/fullcalendar#3313]
Hello,

When I add an event (for example) from Friday to Monday and have "week view", I don't see such an event. I have to go to "month view" (event is visible probably via refetching) and then to week or day view. Event is still visible. When I add event longer then month it's impossible to see it since there is no "year view"...

I load my events from database and in JSON format more then one year without any problem.

When I add "hard-coded" long events, everyhing is OK, so probably some optimization of fetching data should be the problematic place.

I'd like to prepare some example but it's a little bit hard for me right now.

Vladimír

**Comment by arshaw** [comment]
Would you be able to post a [runnable, stripped-down demonstration of the bug](http://fullcalendar.io/wiki/Reduced-Test-Cases/)? Would really appreciate it because the time saved reproducing will be time spent fixing.

**Comment by vklaus** [comment]
Hello Adam,
it was very special problem on my side :-( Your component works perfectly!
Vladimír

**Comment by MindaugasR** [comment]
@vklaus can you tell what issues was and you fixed? I have the same issue here, after updating to newest fullcalendar (3.4.0) just stop showing events. I need to go next month (in month view) and go back to see this month events.
