### ISSUE TITLE
switch sides: calendar navigation (Today, <, >) and calendar views (Month, Week, Day)

### ISSUE THREAD

**Issue by bobbyfielding** [fullcalendar/fullcalendar#3315]
The calendar app has the calendar navigation items (Today, <, and >) to the right of the date or date range and the calendar views (Month, Week, and Day) to the left (see image Cal1.jpg). 
![cal1](https://cloud.githubusercontent.com/assets/21125529/17811169/4db4d7de-65ef-11e6-90bf-a436bbfc24e8.JPG)
I request that these items switch sides (and order) to improve navigation.

The problem occurs on the Day view when the short date format is long. The calendar navigation items spill off to the right by a distance that is dependant on the length of the name of the day (see image Cal3.jpg). 
![cal3](https://cloud.githubusercontent.com/assets/21125529/17811170/4db43d74-65ef-11e6-8370-52a75a260e22.JPG)
This causes difficulty in navigation when attempting to go next day (>) mutilple times, as the next day button (>) moves constantly to the left or to the right and does not stay under the mouse cursor.

The problem also occurs on the Month view when in French since the translation of "Today" is "Aujourd'hui", which is much longer than the English word. The calendar navigation items move left and right depending on the length of the word for the month (See image Cal2.jpg).
![cal2](https://cloud.githubusercontent.com/assets/21125529/17811168/4daf944a-65ef-11e6-8cf4-5c398186ea21.JPG)

I suggest that the order of the items change to:
 <, >, Today, "Date or date range", Day, Week, Month
 from:
 Month, Week, Day, "Date or date range", Today, <, >

**Comment by arshaw** [comment]
I will think about changing the defaults for this.

But did you know the `header` setting give you unlimited control over this?
http://fullcalendar.io/docs/display/header/
