### ISSUE TITLE
date format Bug (space between numbers)

### ISSUE THREAD

**Issue by krosoftware** [fullcalendar/fullcalendar#3317]
Hello
when using Croatian language, date contain spaces.
Here is preview:
http://code.reloado.com/oeasyrik1/35/edit#preview
here is source code:
http://code.reloado.com/oeasyrik1/35/edit#source

Just run preview, click on "Event1" and you will see space in the date, for example:
16. 06. 2016
instead of
16.06.2016

**Comment by arshaw** [comment]
@krosoftware the fullcalendar projects defers to momentjs translations for this. could you please comment on this ticket? https://github.com/moment/moment/issues/2070
