### ISSUE TITLE
Horizontal scroller (fc-scroller-clip) from the bottom to the top.

### ISSUE THREAD

**Issue by AlikKosarevskiy** [fullcalendar/fullcalendar#3320]
Does it possible in timelineMonth to change the position of the horizontal scroller from the bottom to the top with some option as shown on the picture?  
![image](https://cloud.githubusercontent.com/assets/19498683/17971696/9555f57e-6ae4-11e6-8c60-937efa92a091.png)
It is useful when we have to much resources and need to searching for the scroller somewhere from the bottom to move few days right.

**Comment by AlikKosarevskiy** [comment]
I found the answer [HERE.](http://stackoverflow.com/questions/39148723/horizontal-scroller-fc-scroller-clip-from-the-bottom-to-the-top-of-fullcalenda)

**Comment by AlikKosarevskiy** [comment]
I try to get the value width:
`var wer = $('.fc-time-area .fc-scroller-canvas').css('width'); 
console.log(wer);`
but I have the consol message 'Undefined'.  But why?

**Comment by thechiefalone** [comment]
Thanks @AlikKosarevskiy , it worked for me too.
