### ISSUE TITLE
In IE8 hidden borders display as solid black lines

### ISSUE THREAD

**Issue by oddz** [fullcalendar/fullcalendar#3322]
If you view the full calendar home page in IE8 the hidden borders will not be hidden at all, instead they are solid black lines. I have narrowed down the cause of this to border-style hidden. Although IE8 supports hidden for border-style. So perhaps it is a IE8 bug with applying a hidden border style to specific elements, like table elements or something. I wonder what would be the best way to fix this in IE8.

**Comment by arshaw** [comment]
hey @oddz i would address this, but [v3](https://github.com/fullcalendar/fullcalendar/releases/tag/v3.0.0-beta) is dropping support for IE8, so will avoid further investigation.
