### ISSUE TITLE
Right-click (context menu) on an event makes it internally selected too long.

### ISSUE THREAD

**Issue by sledgas** [fullcalendar/fullcalendar#3324]
Hi, 

This bug is easily reproducable in the calendar on the first page at https://fullcalendar.io.
1. Right click on any event which will bring up the browser's context menu.
2. Left click anywhere on the page to close the context menu.
3. Try to move any other event. This will move the first event, which was right clicked, and not the event intended for moving.

This only seem to happen once as subsequential actions works as intended on the events.

This has been tested and verified in all major browsers such as Safari, Opera, Firefox, Chrome and IE 11.

**Comment by haoksam** [comment]
Bug still present in latest version (3.5.1)
Any update?

**Comment by arshaw** [comment]
reproduced

**Comment by mukesh-n-crest** [comment]
Yes Guys, I am also facing the same issue

**Comment by GalacticWeb** [comment]
+1

**Comment by GalacticWeb** [comment]
Ist there any workaround how we could clear the internal selection of the event to stop the dragging? 

I'm exploring the dragging code but haven't found a solution yet...

**Comment by GalacticWeb** [comment]
Okay i created a monkeyPatch for this Problem if you add this after your fullcalendar file you'll have a workaround until version 4.0 comes out which hopefully solves it.

(function($) {
	function monkeyPatchMouseDown(EventDragging) {
		EventDragging.prototype.handleMousedown = function(seg, ev) {
			if (
				!this.component.shouldIgnoreMouse() && ev.which === 1 &&
				this.component.canStartDrag(seg, ev)
			) {
				this.buildDragListener(seg).startInteraction(ev, { distance: 5 })
			}
		}
	}

	const fc = $.fullCalendar;
	monkeyPatchMouseDown(fc.EventDragging)
}(jQuery));

**Comment by Batajus** [comment]
+1

**Comment by alex7egli** [comment]
+1

**Comment by alex7egli** [comment]
No longer seeing this bug in fullcalendar 4.1.0

**Comment by arshaw** [comment]
yup, this bug is no longer present in 4.x
