### ISSUE TITLE
Wrong Event information provided in eventAfterRender callback for events happening before current view

### ISSUE THREAD

**Issue by sebastienratez** [fullcalendar/fullcalendar#3325]
I made this plain calendar with only one callback hooked to eventAfterRender, and then populated it with 3 events:

http://jsbin.com/pivuvewoyu/edit?html,output

The first event and the last events are in august 2016 so they show up nicely in the callback - check the console. But, for some reason, not only is there 4 afterEventRender calls, but the 2 in the middle don't match at all the 2nd event (with title = meeting).

If you only change the month from 07 to 08 for the 2nd event, everything looks normal again...

What's happening here?

Note: same thing happens with eventRender

**Comment by arshaw** [comment]
What's happening is that only one of the events is ever in view, and only that even should ever be rendered in this case. However, whenever a `renderEvent` method call is made, regardless of whether that event is in view, it *rerenders all currently rendered events* on the calendar too. that is what you are seeing.

This issue will go away with this collection of problems is solved:
https://github.com/fullcalendar/fullcalendar/issues/3003
https://github.com/fullcalendar/fullcalendar/issues/2938
https://github.com/fullcalendar/fullcalendar/issues/2524
