### ISSUE TITLE
Multiweek event render issue when appending text

### ISSUE THREAD

**Issue by xcodinas** [fullcalendar/fullcalendar#3326]
I have an event with a description that I want to add to the event view, so i use the eventRender function and I append the description that i want to the element.

`element.append(event.description)`

The description is an array with a text line, a jquery br object and another text line.

`["First line", jQuery('<br>'), "Second"]`

And here begins the problem, if the event duration it's in the same week  it shows correctly (Event2 in fiddle) but if the event duration extends one week the description is not shown correctly (event 1 and 3 in fiddle) so there's no separation in the two text lines (when in event2 is).

After making different events i get two different results, in the event 1 the text isn't separated by the br object in the both weeks of duration, but in the event 3 in the first week it's not separated but in the second it's.

Fiddle:
http://jsfiddle.net/0amkL6yq/

**Comment by arshaw** [comment]
the bug will go away if you freshly instantiate the `jQuery('<br>')` for each eventRender call. what's happening is that the subsequent calls are referencing the same DOM reference and remove/reinserting the `<br>`.

**Comment by xcodinas** [comment]
> the bug will go away if you freshly instantiate the `jQuery('<br>') `for each eventRender call. what's happening is that the subsequent calls are referencing the same DOM reference and remove/reinserting the `<br>`

What do you mean with freshly instantiate? How can I do that?
