### ISSUE TITLE
contentHeight, height and aspectRatio dynamic change won't work when you set multiple options

### ISSUE THREAD

**Issue by yoancutillas** [fullcalendar/fullcalendar#3327]
Hello,

contentHeight, height and aspectRatio can't be set dynamically with others options. For example :
`$('#calendar').fullCalendar('option', {
    contentHeight: 500,
    anyOtherOption: 'foo'
});`
will **NOT work**.

But
`$('#calendar').fullCalendar('option', {
    anyOtherOption: 'foo'
});
$('#calendar').fullCalendar('option', {
    contentHeight: 500
});`
will **work**.

You can try it here:
http://jsbin.com/vazilaw/edit?js,output

**Comment by arshaw** [comment]
released in [v3.1.0](https://github.com/fullcalendar/fullcalendar/releases/tag/v3.1.0)

**Comment by yoancutillas** [comment]
Hello,

Actually, the bug remains as is in 3.1.0 : http://jsbin.com/vazilaw/edit?js,output

Thank you for your work anyway :)

**Comment by arshaw** [comment]
@yoancutillas , you say this is the part that is not working?
```
  $('#not_working_dynamic_change').on( 'click', function(){
    var options = {};
    options.contentHeight = 750; //Only trying contentHeight, but the bug is also on height, contentHeight, and aspectRatio
    options.minTime = '06:00';
    $('#calendar').fullCalendar( 'option', options );
  });
```

when I click that button, the height adjusts AND the minTime adjusts, which is the intended behavior.

can you further describe the buggy behavior you're seeing?

**Comment by yoancutillas** [comment]
Yeah you're right, I actually tried to update the three size options at the same time in my project, and didn't figure out how it worked in that case.

Sorry, 
You are doing a great job with fullcalendar, keep going !
