### ISSUE TITLE
Changing month columnFormat

### ISSUE THREAD

**Issue by gerik43** [fullcalendar/fullcalendar#3329]
Hi,

I want the full day name to show up instead of just sun mon ect.
when i tried the solution i found online (columnFormat: {month: 'dddd',},)
it shows up as object Object can u help me out?
also is it possible to have the toolbar on the bottom ?

Kind regards,

Jerry Geerts

**Comment by harish0000** [comment]
@gerik43 you can use the below code for full names of days in month view 

```
views: {
    month: {
	columnFormat:'dddd'
	}
},
```

if you want to show also in week you can add that view in above code :)

**Comment by gerik43** [comment]
Thanks man thought i tried that but guess i screwed up the order ...

**Comment by link2pk** [comment]
hi @harish0000 , http://imgur.com/a/wV1ki . Here I would like to have week days on the left and time  on the top. Do you have any idea about this?

Thanks
