### ISSUE TITLE
[FullCalendar V1.6.7] - Slot Selection bug persist (Help needed)

### ISSUE THREAD

**Issue by Ziinax** [fullcalendar/fullcalendar#3333]
![2016-09-07 00_44_43-dr agenda compagny _ easy appointments](https://cloud.githubusercontent.com/assets/19927527/18293664/9a0830f0-7494-11e6-87bf-eb296d863f31.png)

hello,
i have a big problem with the 1.6.7 version of full calendar when selecting a slot, i know that the bug was fixed but i still have it, in the demo version it works fine but in my app it dosen't work 

i tried to make a JSbin exemple but it works correctly 

is here a configuration of widht or height  that i must make to fix this bug ?

i read a lot of issue about this bug, and all this issue was merged into #1302 issue but it still bug
can you please Help me ?

**Comment by Ziinax** [comment]
in the 1.6.1 Version When The zoom is 90% it works fine if this may help you

**Comment by arshaw** [comment]
Hi @Ziinax v 1.x is no longer supported for bugfixes like this, so please find a way to upgrade.
