### ISSUE TITLE
list view, not showing the events under one day

### ISSUE THREAD

**Issue by harish0000** [fullcalendar/fullcalendar#3334]
I have implemented the full calendar new feature "listMonth" .However when i passed the events its not showing the events under one day.In the link you can see that there are multiple events on 23rd Sep 2016 but it has split the events in 2 same dates why ? Also my events are not full day events so why full calendar is showing all day event 

eg.
```
{
    "id": "1343820871",
    "functionality": "A",
    "title": "ITD_Proximity_Services (Home)",
    "start": "2016-09-23 07:54:00",
    "end": "2016-09-24 07:55:00"
  }
```
In the above event full calendar is showing 2 events i.e. on 23rd sept 2016  and a all day event on 24th Sep 2016 . why its showing a all day event  for 24th ?

Js bin : [http://jsbin.com/leroxuv/1/edit?html,js,output]

**Comment by arshaw** [comment]
recreated the bug. thanks.

note to self, change this line:
https://github.com/fullcalendar/fullcalendar/blob/master/src/list/ListView.js#L206

to:
```
if (event.allDay) {
```

**Comment by harish0000** [comment]
@arshaw how can i correct it in js file ?

**Comment by harish0000** [comment]
@arshaw thanks for acknowledging the issue :) but in order to correct it can you tell me where to change in min js file ?

**Comment by harish0000** [comment]
@arshaw thanks for acknowledging ,i have changed in js file and "all day" removes successfully ,but still the day headers are coming multiple times.If there are multiple events on a particular day then it should come under one day only.

**Comment by harish0000** [comment]
![capture](https://cloud.githubusercontent.com/assets/22025958/18314901/aa551ee8-7532-11e6-9f24-c395881b628e.PNG)

@arshaw you can see in the above snapshot in listmonth view ,multiple events of the same day should come under the same date. still confusing why the date headers are splitted for multiple events.

**Comment by arshaw** [comment]
Could you please attempt this on the newly-release [v3.0.1](https://github.com/fullcalendar/fullcalendar/releases/tag/v3.0.1) ?

If your events' end times are under the [nextDayThreshold](https://fullcalendar.io/docs/event_rendering/nextDayThreshold/), whose default is 9am, then they should render on only one day as you desire.
