### ISSUE TITLE
Change Header options based on view

### ISSUE THREAD

**Issue by ChristianLuxem** [fullcalendar/fullcalendar#3335]
I thought this would be a view-specific option, but it doesn't seems like. 

I am using Fullcalendar Version 3.0.0 and got the following setup:

I got 2 views: Month and ListYear.  In my default settings i got the header like the following:
```
header : {
	left : "prev, next, today",
	center : "title", 
	right : "month,listYear"
},
```

When i change the view from month to listYear i would like to hide the complete left section, because i only need the year 2016. How can i do this?

The following is not working:
`
views : {
	listYear: {
		header: {
			left: "",
			center : "title", 
			right : "month, listYear"
		}
	}
}
`

**Comment by harish0000** [comment]
@ChristianLuxem you can show and hide  in viewRender function
```
viewRender: function(view,element) {
	    		if(view.name=="month"){
	    			//month
	    			$('.fc-left .fc-button-group,.fc-today-button').show();
	    		}else{
                                //listYear
	    			$('.fc-left .fc-button-group,.fc-today-button').hide();
	    		}
}
```

Hope the above code resolves you issue :)

**Comment by ChristianLuxem** [comment]
@harish0000 ,
thank you, that helped a lot!
