### ISSUE TITLE
dayclick and select events are raised on a single day

### ISSUE THREAD

**Issue by LilBiggs** [fullcalendar/fullcalendar#3336]
**Scenario 1 - Desktop Browser**
http://jsbin.com/wodicigewo/1/edit?js,output
Click on a single day. Both dayClick and select events are raised on a single day.
Expected: Only dayClick raised

**Scenario 2 - Mobile Emulation**
http://jsbin.com/wodicigewo/1/edit?js,output
Hit F12 to open chrome dev tools
Select mobile emulation 
Click on a single day. Only dayClick is raised
Click on a single day. Hold mouse down till selection is made. Once selection is made, drag mouse from left hand side to right hand side inside of a single day cell. dayClick and select events are raised.
Expected: I can see a case for either event to be raised. But I think only one should be, not both.

What is the expected functionality for the two scenario's above?

May or may not be similar to #3332

**Comment by arshaw** [comment]
Hi @LilBiggs, what you are experiencing is intended behavior. for mouse, the select is supposed to fire alongside a dayClick. The reason it is different on touch is that the selection will only happen after [longPressDelay](https://fullcalendar.io/docs/event_ui/longPressDelay/) has elapsed. There's an open ticket for doing a similar behavior with mouse:
https://github.com/fullcalendar/fullcalendar/issues/2428
&uarr;
Could you please visit the link, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates?
