### ISSUE TITLE
Localize daynumbers

### ISSUE THREAD

**Issue by fcis2008** [fullcalendar/fullcalendar#3339]
When switching from English to Arabic, dayNumber are not localized. e.g. 1,2 should be ١, ٢

**Comment by arshaw** [comment]
reproduced. jsbin: http://jsbin.com/xoteticude/1/edit?js,output

thanks

**Comment by arshaw** [comment]
fixed in 3.8.1 and released
updated working jsbin: http://jsbin.com/xevosiqutu/edit?js,output
