### ISSUE TITLE
Multiple Day Event bug

### ISSUE THREAD

**Issue by Migueeeeel** [fullcalendar/fullcalendar#3344]
Hi,

In events like this example starting 2016-09-23 20:00:00 and ends 2016-09-24 06:00:00, is not being displayed as supposed to. Bellow you have a google calendar image and full calendar for comparison, the event in question is the one with red circle. The Event called Teste also doesn't show correctly. this event starts 2016-09-22 09:30 and ends 2016-09-30 10:30

**Google:**
![image](https://cloud.githubusercontent.com/assets/563127/18473015/9a69d526-79b2-11e6-87bf-2536edf14ec5.png)

**Fullcalendar:**
![image](https://cloud.githubusercontent.com/assets/563127/18473056/d47b9006-79b2-11e6-8b98-35b2751957c2.png)

Both moment.js and fullcallendar are updated to latest version.
Bellow goes the code:

![image](https://cloud.githubusercontent.com/assets/563127/18473193/8a30c858-79b3-11e6-9582-074f682a13bf.png)

Thanks.

**Comment by arshaw** [comment]
this is actually a combination of two other feature request tickets:

https://github.com/fullcalendar/fullcalendar/issues/440

https://github.com/fullcalendar/fullcalendar/issues/3038


Could you please visit the links, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates?
