### ISSUE TITLE
Is it possible to show the fc-start-resizer?

### ISSUE THREAD

**Issue by VictorGirardin** [fullcalendar/fullcalendar#3345]
I am wondering if there is implemented support to show the fc-start-resizer for my fullcalendar events. The fc-end-resizer appears to be displayed by default when an event is reziable but not the fc-start-resizer.

I would expect that the fc-start-resizer would be positioned in the top-middle section of each event when the event is hovered upon.

Any ideas?

**Comment by arshaw** [comment]
which view are you referring to?

this ticket is a precursor to doing any styling on the start resizer:
https://github.com/fullcalendar/fullcalendar/issues/374
&uarr;
Could you please visit the link, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates?
