### ISSUE TITLE
Incorrect order and duplicate days in list view with "all day" events

### ISSUE THREAD

**Issue by rizoom** [fullcalendar/fullcalendar#3347]
The order of the day rows in not always correct in presence of long "all day" events (ie. more than one day "all day" events.
Also when a long all day event is displayed along with other basic events, some day rows are duplicated.

## Reproducible example
We can use the demo to easily reproduce this issue.

Open https://fullcalendar.io/js/fullcalendar-3.0.0/demos/list-views.html and reorganize the events to obtain the same result as the image below (note that duration of the long event have been extended).

![selection_412](https://cloud.githubusercontent.com/assets/1694104/18551874/a1b3e5ac-7b5a-11e6-8d3b-dff2181a9413.png)

You can then switch to week view and should observe the following list.
![selection_413](https://cloud.githubusercontent.com/assets/1694104/18552035/26e2f3d0-7b5b-11e6-9363-cc79c6d462c8.png)

Here is the day view for a specific day. We can see that day row is not duplicated anymore.
![selection_414](https://cloud.githubusercontent.com/assets/1694104/18552048/32ac5986-7b5b-11e6-93fc-d894f16eed95.png)

You can then play with the month view to organize events differently, you will see various unpredictable side effects on the corresponding list view.
For example, moving a single day event can affect the display order of the days of the "Long event".
![fc-listview-example](https://cloud.githubusercontent.com/assets/1694104/18553747/e3863b2c-7b61-11e6-9dec-97d691a8e220.gif)

I guess the expected week view should be the combinaison of all the day views for that week (=> no duplicate days and correct day order)

**Comment by arshaw** [comment]
recreated. thanks. jsbin i had to make: http://jsbin.com/yeqasekumu/1/edit?js,output

**Comment by arshaw** [comment]
this is fixed in [v3.0.1](https://github.com/fullcalendar/fullcalendar/releases/tag/v3.0.1)

http://jsbin.com/kizanivufi/1/edit?html,output
