### ISSUE TITLE
Valid date not rendering properly in firefox

### ISSUE THREAD

**Issue by pfatyga** [fullcalendar/fullcalendar#3349]
When specifying a defaultDate in this format: '2016-9-15', the calendar does not render on firefox but it does on chrome.

$('#calendar').fullCalendar({
          defaultDate: '2016-9-15'
        });

http://jsbin.com/labaqoyuqe/edit?html,js,output

**Comment by pfatyga** [comment]
A temporary fix is to do
$('#calendar').fullCalendar({
          defaultDate: new moment('2016-9-15')
        });

**Comment by pfatyga** [comment]
The error the console gives me is:

dayDates[0] is undefined

**Comment by arshaw** [comment]
`'2016-9-15'` is invalid because the mont must be two digits. the parsing is likely falling-back to browser-implemented parsing, which is inconsistent, because momentjs can't handle it. just use two-digit month numbers.
