### ISSUE TITLE
Many overlapping events too small after 5 or more

### ISSUE THREAD

**Issue by CedNet** [fullcalendar/fullcalendar#3350]
Hi, when creating many overlapping events on the same day, the width of each event is adjusted smaller and smaller until they're unusable. The last element stays wider than the first X.

On a touch device having 5 or more overlapping = invisible events / not possible to click on. 

Example:
http://jsbin.com/tadusiyicu/edit?js,output

Setup:
Reduce width of "Live view" and scroll to the multiple events added. They're just a line on screen.

You can see that 4 of 5 are tiny lines. While the 5th event stays wide and usable.

NOTE: this did not occur on version 1 of full calendar

**Comment by arshaw** [comment]
dup of:
https://github.com/fullcalendar/fullcalendar/issues/2809
&uarr;
Could you please visit the link, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates?
