### ISSUE TITLE
change jp columnFormat

### ISSUE THREAD

**Issue by mblandfo** [fullcalendar/fullcalendar#3353]
http://jsbin.com/facaboqopa/1/edit?html,js,output

Go to week view. Notice the headers are in this format: "日 11/9"

This is wrong, it should be "11/9 日"

Also, the week number "週38" might be incorrect and need to be "38週"

Example here is Japanese, but this probably applies to other languages as well.

The most commonly used date format in Japan is "year month day (weekday)"
https://en.wikipedia.org/wiki/Date_and_time_notation_in_Japan

This also reproduces here: https://fullcalendar.io/js/fullcalendar-3.0.0/demos/locales.html

**Comment by arshaw** [comment]
fixing this would be a matter of overriding the Japanese locale's `columnFormat` setting. It probably doesn't provide its own and thus relies on the automatically computed format string.

**Comment by arshaw** [comment]
the built-in Intl API is used for this now, so it's probably fixed
