### ISSUE TITLE
In view agendaDay,agendaWeek,month with Resource hide day (only specific resource)

### ISSUE THREAD

**Issue by duetempi** [fullcalendar/fullcalendar#3356]
Thanks very much to the contributors here.
I have a view with the resources, for example the view day (but it could also be the view week or the view month) and (using the property groupByDateAndResource:true ).
Is it possible to hide one resource for a single day?

As in the example (like in the image)

DAY			RESOURCES ENABLED
-----------------------------
Monday		A,B,C
Tuesday		A,B
Wednesday	A,B,C
Thurday		B,C
Friday		A,C
Saturday	        A,B,C
Sunday 		C

Thank you
![table-resource](https://cloud.githubusercontent.com/assets/22366073/18742593/76cc9ac2-80b5-11e6-83e6-bf43b0841519.png)

**Comment by arshaw** [comment]
moved over to the scheduler issue tracker:
https://github.com/fullcalendar/fullcalendar-scheduler/issues/222
&uarr;
Could you please visit the link, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates?
