### ISSUE TITLE
TypeError: Cannot read property 'ownerDocument' of undefined  at getScrollParent 

### ISSUE THREAD

**Issue by CJBrew** [fullcalendar/fullcalendar#3357]
I've created the simplest possible inheritor of AgendaView. You should be able to see on selecting it from the calendar menu, that an error appears in the Console from the getScrollParent function.
In Firefox the error is something like " el[0] is undefined"

https://jsbin.com/wabecosaha/

**Comment by arshaw** [comment]
this problem seems to have nothing to do with your custom views. i stripped that code out and still get the JS error:
https://jsbin.com/jukijodahi/1/edit?html,output

Luckily, if I upgrade the FC version to 3.0.0, the problem goes away:
https://jsbin.com/jukijodahi/2/edit?html,output

**Comment by CJBrew** [comment]
OK. I'm using the Angular fullcalendar wrapper. This is more fuel for the argument to get them to upgrade...
Thanks

**Comment by benvan** [comment]
Sorry for commenting on a closed thread, but I thought it better here for searchability than to open a new issue.

I had the same problem as @CJBrew - and upgrading to 3.3.0 made things worse by spinning an infinite loop on view instantiation :|

After having a root around the fc code it seems that the `AgendaView` cannot instantiate itself if it isn't provided with defaults. The documentation is partly at fault, as providing a class as an entry into `FC.views` is deprecated:
https://github.com/fullcalendar/fullcalendar/blob/master/src/Calendar.js#L118

Instead, you can emulate the approach that the existing views take:

```
FC.view.myCustomView = {
  class: FC.AgendaView.extend({ }),
  defaults: {
            maxTime:"24:00:00",
            minTime:"00:00:00",
            slotDuration:"00:30:00",
            
  }
}
```

**Comment by arshaw** [comment]
@benvan  would you be able to post a [runnable, stripped-down demonstration of the bug](http://fullcalendar.io/wiki/Reduced-Test-Cases/)?

**Comment by benvan** [comment]
Sure. https://jsfiddle.net/myw43kqq/2/

I think there are two issues here:
1. The docs suggest registering a view via `FC.views.custom = CustomView` but this is in conflict with the pending deprecation of views being functions - see:
https://github.com/fullcalendar/fullcalendar/blob/master/src/Calendar.js#L118
2. The `AgendaView` is not directly subclassable. It expects the defaults provided by `FC.views.agenda.defaults`

Again, it is the documentation that makes this confusing. If a view should be registered via `FC.views.SomeView` then it stands to reason that an existing view should be able to be subclassed.

The result is surprising - I'd suggest the documentation should probably be updated

**Comment by arshaw** [comment]
thanks @benvan I've broken this into two separate tickets:

https://github.com/fullcalendar/fullcalendar/issues/3657
https://github.com/fullcalendar/fullcalendar/issues/3658
&uarr;
Could you please visit the links, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates?
