### ISSUE TITLE
Moment extension

### ISSUE THREAD

**Issue by frlinw** [fullcalendar/fullcalendar#3358]
Hi,

What is the point with this extension ?
https://fullcalendar.io/docs/utilities/date_formatting_string/
"LT" in moment do a similar thing

And there is a consistance problem since moment documentation says : 
> As of version 1.5.0, calling moment#format without a format will default to moment.defaultFormat. Out of the box, moment.defaultFormat is the ISO8601 format YYYY-MM-DDTHH:mm:ssZ.

so, if I want to use this default format manually the T is converted in A or P. I know that I can escape it with [T] but it's not the point.

**Comment by arshaw** [comment]
the point of the `t` and `T` tokens is to provide a **one-character** rendering of am/pm, which moment doesn't currently provide. `LT` produces something pretty different (ex: `'8:30 PM'`).

could you provide a [jsbin](https://fullcalendar.io/wiki/Reduced-Test-Cases/) where the defaultFormat is producing the wrong text based on the T? i could have sworn the logic i wrote would have prevented it.
