### ISSUE TITLE
issue in scrolling events and dropping them to full calendar from side bar.

### ISSUE THREAD

**Issue by parth-dals** [fullcalendar/fullcalendar#3360]
I have an iPad application built using ionic framework and having rest services in backend.

I have a screen where there is a full-calendar component and a scrollable list of draggable and droppable items in left side panel.

Once the screen loads I can drag and drop items from left side panel to calendar and can generate event.

But once I scroll side panel list or do any touch activity on any where outside calendar DRAG functionality works but DROP on calendar does not work for first time.

Then again the functionality works properly in successive attempts.

Thus after every scroll in Side bar or any touch outside calendar,  the drop of item on calendar does not work for first time.

No such issues is generated when application is tested in browser.

Components and environment :

For touch : jQuery touch punch
Calendar : jQuery full calendar 2.7.3
Framework : ionic + angular
Platform : ios (iPad)

**Comment by arshaw** [comment]
Would you be able to post a [runnable, stripped-down demonstration of the bug](http://fullcalendar.io/wiki/Reduced-Test-Cases/)? Would really appreciate it because the time saved reproducing will be time spent fixing.

**Comment by parth-dals** [comment]
well i got the solution for my problem. I did some changes in fullcalendar.js in v 2.7.3 added following two lines in function 'processUnselect' around 8790 line

this.dayGrid.isDraggingExternal = false;

this.timeGrid.isDraggingExternal = false;

so my function looks like below

processUnselect: function(ev) {

        this.dayGrid.isDraggingExternal = false;

        this.timeGrid.isDraggingExternal = false;

        this.processRangeUnselect(ev);

        this.processEventUnselect(ev);

    },

The reason for doing so is whenever i scroll grid besides calendar it identifies that event as drag event. Due to this value for "this.dayGrid.isDraggingExternal" is set to true and never gets false since after scrolling no drop event is received by calendar.
