### ISSUE TITLE
fc-today missing in agendaWeek day header

### ISSUE THREAD

**Issue by Rouche** [fullcalendar/fullcalendar#3361]
### Bug Reports

http://jsbin.com/hahuzes/6/edit?html,js,output
### Feature Requests

Is it possible to add the fc-today class to the header like the day header have in the month view?

Im not sure if its wanted to have the background of the header to be like cells but the css could be adjusted.
If not acceptable, i guess i can do exactly like in the jsbin and add it manually.

Was mixed in #3337

**Comment by arshaw** [comment]
Thanks for the explanation. I didn't realize the fc-today class wasn't on the agenda views' headers. thanks

**Comment by Rouche** [comment]
Need PR for this one?

**Comment by arshaw** [comment]
a PR [with some simple tests](https://github.com/fullcalendar/fullcalendar/wiki/Automated-Tests) would be awesome

**Comment by arshaw** [comment]
released in [v3.1.0](https://github.com/fullcalendar/fullcalendar/releases/tag/v3.1.0)
