### ISSUE TITLE
https forcing user to login to view google calendar details

### ISSUE THREAD

**Issue by petrakid** [fullcalendar/fullcalendar#3363]
Gcal.js is working, but when a user clicks on an even from the public/shared calendar, the user is required to log into google to view it.  I checked with google calendar folks and they said it's because the 's' is included in the link to google.

I looked at gcal.js and can't see where that 's' is being added.  There needs to be either an option to have public calendars exclude the secure option, or instructions on how to remove it from the script.

**Comment by arshaw** [comment]
Would you be able to post a [runnable, stripped-down demonstration](http://fullcalendar.io/wiki/Reduced-Test-Cases/), populated by a real public google calendar? will really help debug. will reopen when you do
