### ISSUE TITLE
Drag and Drop iOS scrolling

### ISSUE THREAD

**Issue by BrandonEMiller** [fullcalendar/fullcalendar#3367]
When dragging and dropping on iOS the page scrolls making it impossible to drag an event from one week to another in the week view

This can be seen on full calendar home page.  

Scenario:
- Open https://fullcalendar.io/ on an iOS device or simulator
- Touch and hold an event to trigger drag and drop
- Try to drag event to a new week and the page scrolls with you making it impossible to do so

**Comment by BrandonEMiller** [comment]
Nevermind this seems to be an issue only in the xcode simulator not on actual iOS devices.

**Comment by grajan** [comment]
The issue seems to be there on iOS 10.1 (Simulator and Device)
Works perfectly on iOS 9.3 though

**Comment by arshaw** [comment]
@grajan any way you could post a video?
