### ISSUE TITLE
customButton alt text

### ISSUE THREAD

**Issue by sante85** [fullcalendar/fullcalendar#3369]
In customButton  i want add other properties as alt="" etc.

**Comment by arshaw** [comment]
superseded by:
https://github.com/fullcalendar/fullcalendar/issues/6521
&uarr;
Could you please visit the link, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates?
