### ISSUE TITLE
Event time text cut off in print view

### ISSUE THREAD

**Issue by jm06487** [fullcalendar/fullcalendar#3371]
The original print.css from fullcalendar did not render short events properly.  The css duplicated times and added information that could not be displayed.  I will attach a file that has all the updated css in a min to fully render times and events.

[fullcalendar.print.min.css.txt](https://github.com/fullcalendar/fullcalendar/files/511806/fullcalendar.print.min.css.txt)

**Comment by arshaw** [comment]
could you post some screenshots of the undesired behavior?

**Comment by jm06487** [comment]
![fullcalendar-print-css](https://cloud.githubusercontent.com/assets/10539923/19214292/53c6a9c4-8d4d-11e6-92ab-1f57a417f200.jpg)

**Comment by arshaw** [comment]
Got it. I see the `7:507:50AM - 7:55 AM` text.

**Comment by safrick** [comment]
I've found that the initial start time could be removed with:
`$("div.fc-time").removeData("data-start").removeAttr("data-start");`

**Comment by TarikAbou-Saddik** [comment]
Is this an issue that is still in the pipeline to be fixed, or is there a workaround in the meantime?

**Comment by arshaw** [comment]
this is almost certainly fixed in v5. if the bug persists, please post another comment
