### ISSUE TITLE
locale files does not contain all the translations

### ISSUE THREAD

**Issue by FrancoisDucobu** [fullcalendar/fullcalendar#3372]
Hello,

I think something is missing in all locales files.
Only a few words are translated.

As workaround, I download the "all locale" from the example to get it work.
https://fullcalendar.io/js/fullcalendar-3.0.1/demos/locales.html

Have a nice day

Francois

**Comment by arshaw** [comment]
can you give me some examples of languages that aren't working well? things fine to me

**Comment by FrancoisDucobu** [comment]
on the fr.js file

$.fullCalendar.locale("fr", {
	buttonText: {
		year: "Année",
		month: "Mois",
		week: "Semaine",
		day: "Jour",
		list: "Mon planning"
	},
	allDayHtml: "Toute la<br/>journée",
	eventLimitText: "en plus",
	noEventsMessage: "Aucun événement à afficher"
});

there is no translation for month names, day names.
perhaps they are translated by moment.js ?

in the locale file "all.js", I see translation for months, days, ...

Sorry if i'm wrong ;)

Francois

**Comment by FrancoisDucobu** [comment]
Ok if I include fr.js, everything seems to work.

Only the today button is not translated with fr.js
the button is translated with the all.js file

Francois

**Comment by arshaw** [comment]
glad you figured it out. it seems that you were using the original translation files from the dev repo whereas the *built* translations in the distributables have everything you need.
