### ISSUE TITLE
Multi-day events are off-by-one on ending day

### ISSUE THREAD

**Issue by davija** [fullcalendar/fullcalendar#3374]
When looking at your examples (specifically [](https://fullcalendar.io/js/fullcalendar-3.0.1/demos/basic-views.html)), the duration of events isn't correct.

The starting date is fine, but ending date is not included in the event.

For example in your basic demo I pointed to above, starting date is 9/7/2016 and ending is 9/10/2016.  However, your demo only highlights 9/7-9/9 (inclusive) when it should highlight 9/10 as well.

It does seem to work correctly when the event has times associated with starting/ending events.

I did a little bit of digging around and it seems that it may be related to timezone issues.  If I add starting/ending times I can get the ending cell to be highlighted if I pick an hour that is late enough in the day (For testing purposes, I'm in PST).

(Please erase the above text and begin typing. Thanks!)

**Comment by davija** [comment]
Ok, digging a little bit further, it appears to be in the computeDayRange method.
I see two issues here:
- default for nextDayThreshold is '09:00:00' according to documentation (this shouldn't be set to a fixed time by default as it provides bizarre/unexpected behavior)
- logic in computeDayRange assumes that you never want an empty day (no time) to be inclusive which is counter-intuitive from what I would expect.

I was able to resolve my issue by changing the conditional to this (and passing in a nextDayThreshold that makes midnight valid, hence the 0):
if (0 == this.nextDayThreshold || (endTimeMS && endTimeMS >= this.nextDayThreshold))

My apologies, but I am unable to submit a pull request at this time due to not having a git client installed and am unable to install due to restrictions on my workstation.

**Comment by ptica** [comment]
i think that a common practice is that the event interval is semi-open: [start, end)
ie start time is included in the event and the end is not

it seems (to me) to be established by the book 'Developing Time-Oriented Database Applications in SQL' by 'RICHARD T . SNODGRASS'

the reason being mainly that do not have overlapping events when they are just continuations, ie
e1:[t1, t2) and e2:[t2, t3) are computed as not to overlap
(opposing to what your proposed encoding yields: an overlap at t2)

**Comment by davija** [comment]
While I understand what you are saying if you say you have an event that runs 9/7/2016-9/8/2016 this would be a 2-day event and should show accordingly.  Otherwise it would just be an event for 9/7/2016.

Open up a google calendar and add an event with a starting and ending date (that are not the same) and you will get the behavior I described, not the behavior as built by this application.  I believe this also applies to other office & calendar applications.

**Comment by ptica** [comment]
check the docs for `end` property at https://fullcalendar.io/docs1/event_data/Event_Object/
the code will make more sense than

**Comment by davija** [comment]
Yeah, the docs do seem to make that case, however that is not what is commonly expected as evidenced by google, MS office, etc.  With calendar events when you specify a starting and ending day (without time) you expect the standard inclusive behavior, not what is done with this event calendar.

Additionally the code doesn't respect the allDay property on the event when looking at the end date as the inclusive behavior exists without respect to the allDay setting (true or false it is exclusive).

**Comment by davija** [comment]
I guess that if the code properly respected the `allDay` event property and worked as the documentation described, then I would be fine with it.  However at this point, it doesn't properly handle `allDay`.

**Comment by ptica** [comment]
could you please update the counterexample than? the https://fullcalendar.io/js/fullcalendar-3.0.1/demos/basic-views.html seem ok to me

btw ical seems to exclude the end time moment as well: http://www.kanzaki.com/docs/ical/vevent.html

**Comment by davija** [comment]
I don't have a way to update that page as it is one provided by the developer.  I can try to get an example uploaded somewhere, but a simple repro step would be to add the `allDay` property to the event titled 'Long Event' in the default.html file and verify that it doesn't include 2016-09-10 in the range as it should.

**Comment by ptica** [comment]
ooh, i see, i've pointed you to an obsoleted version of docs, i'm very sorry for that,
at v2 a switch to moment.js has probably been made with a following change:
`.end	is now a Moment, and is always exclusive!`

see https://fullcalendar.io/wiki/Upgrading-to-v2/

**Comment by davija** [comment]
Yes, ical does seem to show that.  However, I'm not seeing how they would define an "all day" event.  It appears that most calendar solutions require either specifying all-day or provide a time.  Also in the spec they do not address the case of having a starting element with just a date (not date-time) that has an ending element with just a date (not date-time).  As a result, they seem to leap-frog the entire issue that I'm bringing out here that a date range (with no times) should be inclusive.

I just finished looking at the updated doc and I can see where they are going with it, however it doesn't seem right to me that if a user specifies a date range for an event as 9/7/2016-9/10/2016 that I must reprocess that and change it to 9/7/2016-9/11/2016.  That just doesn't make sense IMO...

**Comment by davija** [comment]
I guess I can live with this as-is, just not crazy about it.

**Comment by ptica** [comment]
i've been through this as well, it was a sort of very unexpected surprise to me, once I noticed my events are 1 day shorter
