### ISSUE TITLE
Print background-color of element

### ISSUE THREAD

**Issue by kruppa** [fullcalendar/fullcalendar#3375]
Hello, 
Please i use Fullcalendar and i have trouble with printing bacground of event, i want to have full BGcolor and not only frame. 

There is how my print look:

![bez nazvu](https://cloud.githubusercontent.com/assets/3974758/19229684/b8635a34-8ecf-11e6-8dc0-f412b31dc262.png)

If i use this settigs for print:

`@media print {
fc-time-grid-event,
.fc-v-event .fc-event, .fc-start, .fc-end, .fc-draggable, .fc-resizable  {
     position: relative;
     overflow: hidden; /* this might not work well in all situations */
}
 fc-time-grid-event,
.fc-v-event .fc-event, .fc-start, .fc-end, .fc-draggable, .fc-resizable:before {
     content: '';
     position: absolute;
     top: 0;
     right: 0;
     left: 0;
     bottom: 0;
      z-index: 0; 
     	display: block; 
	font-size: .85em;
	line-height: 1.3;
	border-radius: 3px;
	font-weight: normal; 
              background-color: #1a4567 !important;
    -webkit-print-color-adjust: exact; 
  }
fc-time-grid-event,
.fc-v-event .fc-event, .fc-start, .fc-end, .fc-draggable, .fc-resizable  * {
    /* was required in my situation */
    position: relative;
    z-index: 1;
  }
}`
background color is displayed, when i print:

![fillup](https://cloud.githubusercontent.com/assets/3974758/19229752/379ce720-8ed0-11e6-8154-a5e41f941a47.png)

Please do you have some tip how i can print color that is used  in View (database color) and not color what i send in media print ?

I tried a many things like, transparent, inhert but nothing help.  (set print background on my printer)

I tested it in Chrome and mozila.

Still the same output.
Thank you in advance.
BR
MK

**Comment by arshaw** [comment]
Would you be able to post a [runnable, stripped-down demonstration of the bug](http://fullcalendar.io/wiki/Reduced-Test-Cases/)? Would really appreciate it because the time saved reproducing will be time spent fixing.

**Comment by caseyjhol** [comment]
You can't print background color, by default. If you want to print background color, that's a setting you need to enable on your browser. See http://its.yale.edu/how-to/article-printing-web-page-background-colors-and-images.

**Comment by kruppa** [comment]
Ok i will prepere it, 

caseyjhol: if i use below style: I can print even when i have disallow BG. 

@media print { fc-time-grid-event, .fc-v-event .fc-event, .fc-start, .fc-end, .fc-draggable, .fc-resizable { position: relative; overflow: hidden; /* this might not work well in all situations */ } 

fc-time-grid-event, .fc-v-event .fc-event, .fc-start, .fc-end, .fc-draggable, .fc-resizable:before {
 content: ''; 
position: absolute;
top: 0;
 right: 0;
 left: 0; 
bottom: 0; 
z-index: 0; 
display: block; 
font-size: .85em; line-height: 1.3; border-radius: 3px; 
font-weight: normal; 
background-color: #1a4567 !important; 
-webkit-print-color-adjust: exact; } f

c-time-grid-event, .fc-v-event .fc-event, .fc-start, .fc-end, .fc-draggable, .fc-resizable * { /* was required in my situation */ position: relative; z-index: 1; } }

 There is informaiton about printcss, and as you can see my second picture color is displayed, but i have trouble when i dont set bg color statitc (background-color: #1a4567 !important; ) if i want to take it from DB.  (after it is style without color :/ ) 

I will try debud it and i let you know.
caseyjhol: There is good info about print.css.
http://stackoverflow.com/questions/14987496/background-color-not-showing-in-print-preview

Thank you
MK
