### ISSUE TITLE
Recurrent Events

### ISSUE THREAD

**Issue by lellisga** [fullcalendar/fullcalendar#3376]
The calendar is duplicating events ( see the attachment ) If I click the calendar, create a new recurrent event and then click on 'Next' or 'Prev' ( It displays normally until I click on Next of Prev).

![screen shot 2016-10-10 at 4 04 59 pm](https://cloud.githubusercontent.com/assets/210771/19251122/583ed546-8f03-11e6-8f8d-4e84779c9659.png)

This is the event that I'm creating:

```js
var event = {
         start: '10:00',
         end:   '14:00',
         "dow": [
           "1",
           "3",
           "4"
         ],
         "title": "OUT",
         "color": "Grey"
       };
```

Here's the complete code:

```html
<html>
  <head>
    <link rel="stylesheet" href="bower_components/fullcalendar/dist/fullcalendar.css" />
    <script src="bower_components/jquery/dist/jquery.js"></script>
    <script src="bower_components/moment/moment.js"></script>
    <script src="bower_components/fullcalendar/dist/fullcalendar.js"></script>
  </head>

  <body>

    <div id="fullCalendar"></div>

    <script type="text/javascript">
     var calendarOptions = {
       header: {
         left:   'title',
         center: '',
         right:  'today prev,next'
       },
       defaultView:  'agendaWeek',
       editable:     true,
       selectable:   true,
       selectHelper: true,
       select:       newEvent
     };

     $('#fullCalendar').fullCalendar(calendarOptions);

     function newEvent(start, end){
       var event = {
         start: '10:00',
         end:   '14:00',
         "dow": [
           "1",
           "3",
           "4"
         ],
         "title": "OUT",
         "color": "Grey"
       };

       $('#fullCalendar').fullCalendar('renderEvent', event, true);
     }
    </script>
  </body>

</html>
```

FC version = "3.0.1"
jQuery Version = 2.1.4

**Comment by espen** [comment]
FC doesn't support recurring events. Please see the event object supported attributes at https://fullcalendar.io/docs/event_data/Event_Object/ Also start/end should include the entire date + time.

Your event source must return generated recurred events.

**Comment by arshaw** [comment]
`dow` is not meant to work on events yet. for proper recurring event support:
https://github.com/fullcalendar/fullcalendar/issues/387
&uarr;
Could you please visit the link, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates?
