### ISSUE TITLE
NetworkError: 403 Forbidden when assign eventsourcr to full calender

### ISSUE THREAD

**Issue by archish1989** [fullcalendar/fullcalendar#3378]
I am doing long pooling using php, (which work fine) and assigning it's output JSON to fullcalender event source.

My js code

`var source = new EventSource(WEBROOT+'model/applongpooling.php?start=1476037800&end=1476642600');
source.addEventListener('message', function(e) {
     console.log(e.data);
     $('#calendar').fullCalendar( 'removeEvents');
     $('#calendar').fullCalendar('addEventSource',e.data);// here i am getting error
}, false);`

My php pooling code.

`
    <?php
         header('Content-Type: text/event-stream');
         header('Cache-Control: no-cache');
         function SetAppointment(){
              //my logic which is working fine and giving me correct result

             echo 'data: ' . json_encode($res) . "\n\n";//code to get output
            echo PHP_EOL;
            ob_flush();
            flush();
     }
 do {
 SetAppointment();
  sleep(15);

  // If we didn't use a while loop, the browser would essentially do polling
  // every ~3seconds. Using the while, we keep the connection open and only make
  // one request.
} while(true);
?>`
In console i am getting correct output.

> [{"allDay":"","id":"21930","fee":"100","doctorid":"1266","clinicid":"1306","patientid":"449","reason":[],"prescriptionid":"23084491","atime":"09:00 AM","adate":"11\/10\/2016","start":"2016-10-11 9:00:00","end":"2016-10-11 9:30:00","duration":"30","doctorname":"Ankit Mishra","patientname":"uma vats1","pmobile1":"9426800679","pmobile2":"1234567890","plandline":[],"pgender":"Female","page":"47","profilepic":[],"back_color":"#1AA5BD","font_color":"#FFFFFF","clinic_name":"abc","total_appointment":"53","caseno":"2011201541545","canceledbit":"False","cancelled_reason":[],"rescheduledbit":"False","reschedule_reason":[]},{"allDay":"","id":"22133","fee":"100","doctorid":"1266","clinicid":"1306","patientid":"449","reason":[],"prescriptionid":"72732647","atime":"10:00 AM","adate":"12\/10\/2016","start":"2016-10-12 10:00:00","end":"2016-10-12 10:30:00","duration":"30","doctorname":"Ankit Mishra","patientname":"uma vats1","pmobile1":"9426800679","pmobile2":"1234567890","plandline":[],"pgender":"Female","page":"47","profilepic":

Error I am getting ,

> NetworkError: 403 Forbidden - http://localhost:81/DsAdmin/dsadmin/[%7B%22allDay%22:%22%22,%22id%22:%2221930%22,%22fee%22:%22100%22,%22doctorid%22:%221266%22,%22clinicid%22:%221306%22,%22patientid%22:%22449%22,%22reason%22:[],%22prescriptionid%22:%2223084491%22,%22atime%22:%2209:00%20AM%22,%22adate%22:%2211....

In another js i have also assign event source to fullcalender,

`eventSources: [
        {
            url:'model/appointments.php',
            editable: true,
        }
    ]`

so my question where am i wrong, any suggestions? why am i getting such error?

**Comment by espen** [comment]
403 is an error code from your server (php), not Fullcalendar. Also please see https://fullcalendar.io/support/

**Comment by archish1989** [comment]
@espen but i am getting error only when i am assigning event source. if i am commenting this `$('#calendar').fullCalendar('addEventSource',e.data);` line i am not getting error

**Comment by espen** [comment]
@archish1989 the event source uses your PHP which seemingly has returned that 403 error. Try opening up the URL manually and try to debug the error. FullCalendar is a JavaScript lib and would not return a HTTP 403 error (forbidden). Please close this issue and try asking on StackOverflow is you still have problems with your PHP setup.

**Comment by arshaw** [comment]
definitely a problem on the server-side... out of scope for fullcalendar support.
