### ISSUE TITLE
plugin.xml

### ISSUE THREAD

**Issue by sengmow** [fullcalendar/fullcalendar#3379]
Hi

There isn't a plugin.xml in the zip file. Would appreciate if anyone who has it can share it with me.

Thanks.

**Comment by espen** [comment]
Why do you need a plugin.xml file? Also please see https://fullcalendar.io/support/ regarding questions

**Comment by sengmow** [comment]
Hi

I am looking for a cordova/phonegap plugin for Android and iOS. I think
this is not what I am looking for.

Thank you.
