### ISSUE TITLE
Google Calendar Integration Outdated

### ISSUE THREAD

**Issue by Ujjwal-N** [fullcalendar/fullcalendar#3381]
Hello,
I was trying to follow the instructions on [this page](https://fullcalendar.io/docs/google_calendar/) to integrate FullCalendar with Google Calendar. The instructions in the page are outdated because Google API Console just got updated. Can someone help with Google Calendar integration? More details about my problem [here](http://stackoverflow.com/questions/40078434/fullcalendar-sync-with-google-calendar-permissions).

**Comment by arshaw** [comment]
according to the stackoverflow question, you figured this out. closing.
