### ISSUE TITLE
Fullcalendar, Specific time of each day

### ISSUE THREAD

**Issue by wiiwilasinee** [fullcalendar/fullcalendar#3385]
In the week and day view.
{ title : "My Event" , start : "2016-10-20T08:00", end : "2016-10-22T17:00" } 
So my event starts on October 20th, and it ends on October 22th, and happens on each day from 8am to 5pm. But FullCalendar shows the event in week and day view as if it happens non-stop from October 20th at 8am to October 22th at 5pm. Like this:
![image](https://cloud.githubusercontent.com/assets/22979416/19595914/44d4dada-97b6-11e6-9e85-40baf11390db.png)

October 20th: 8am to 12am; October 21th: 12am to 12am; October 22th: 12am to 5pm. 
I want the event to span those 3 days, but only to show from 8am to 5pm on each day for the week and day view. Like this:

October 20th: 8am to 5pm; October 21th: 8am to 5pm; October 22th: 8am to 5pm.
Can this be done? How should I set my event properties to achieve this?

Thank you for your help :)

**Comment by espen** [comment]
Create three different events. That's the norm and that's how the iCalendar specification defines such cases. Alternatively you can create a custom view or automatically split up one event the way you want when parsing the event in FullCalendar.

**Comment by arshaw** [comment]
also, this issue might be relevant to you:
https://github.com/fullcalendar/fullcalendar/issues/440
&uarr;
Could you please visit the link, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates?

**Comment by wiiwilasinee** [comment]
Thank you for your help :)
