### ISSUE TITLE
How can I set the listYear view to start from the current month?

### ISSUE THREAD

**Issue by illuminate3** [fullcalendar/fullcalendar#3387]
How can I set the listYear view to start from the current month?

Thanks!

**Comment by arshaw** [comment]
can you see this issue:
https://github.com/fullcalendar/fullcalendar/issues/2847
&uarr;
Could you please visit the link, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates?
