### ISSUE TITLE
The selected date on first row month view

### ISSUE THREAD

**Issue by EricDotCA** [fullcalendar/fullcalendar#3388]
Hi,

Im fool or i dont have find a way to set the pre-selected date (like today) on the first row in month view?

I have a fullcalendar and I want change the position of the today date. At the moment it could be on any row (check the screenshot) but I want set the today date on the first row only, like this I could see the next month.

I have create a topic on stackoverflow 4 days ago and i dont have any news...

I have create a screenshot of what im asking and a JSBIN file.

[http://stackoverflow.com/questions/40119213/fullcalendar-first-row-month-view](http://stackoverflow.com/questions/40119213/fullcalendar-first-row-month-view)
Thx for anwser.

**Comment by espen** [comment]
So you want to hide the first two weeks if current date is in the third week of a month? That's not possible by the default settings. You have to do this manually or create a new custom view. But perhaps this behaviour would be a bit confusing for users? If in the fourth week you only want to see the current week and not the first three weeks of the month? Perhaps this feature makes more sense if there was a scrolling month view instead of next/prev showing of just one selected month.

**Comment by EricDotCA** [comment]
I dont want hide rows, I just want to be able to set the date of the first row. For me project, I need to see the next month and not previous weeks. If the today date is on the first row, the should show the next month on next rows... Do you have check the screenshot on stackoverflow ? Thx for you help.

**Comment by espen** [comment]
Yes I saw the screenshot but it doesn't really illustrate the desired outcome very well. I think you need to explain a bit more of what should be visible in different situations (different dates). Like I said the month view shows the entire month. You need to make your own custom view for anything else. There has been some talk about endless scrolling but I'm not sure if there is an active issue about that which can be voted for.

**Comment by EricDotCA** [comment]
I have updated my StackOverFlow topic with 3 more exemples. That should help you to understand. Thx again for  you help

**Comment by espen** [comment]
So there will be no next/prev behaviour and have endless scrolling? Or will the user click next to show the next period?

**Comment by EricDotCA** [comment]
Nothing change on this side, i keep all functionality, like next/prev and all others... I just want change the display.  The image is just for show you my current date is always on the first row. It just this setting i want change, everything else is perfect and done. Thx

**Comment by espen** [comment]
So you want the rest of the current month (October) + the next month (November in the initial view? Then what should happen when the user clicks next? Show December? And what if the user clicks prev? Show only October? Show September?

**Comment by arshaw** [comment]
I'm nearly certain this could be implemented as a [custom view](https://fullcalendar.io/docs/views/Custom_Views/) with type: `basic` and duration of 4 weeks (or whatever).

If you want anything beyond that, these issues are likely relevant:
[Continuous scrolling of months](https://github.com/fullcalendar/fullcalendar/issues/2276)
[Custom views, easily customize prev/next duration jump](https://github.com/fullcalendar/fullcalendar/issues/2710)
