### ISSUE TITLE
viewRender inconsistency with fullcalendar('clientsevents") results

### ISSUE THREAD

**Issue by foxalfabravo** [fullcalendar/fullcalendar#3389]
There is a documentation problem about what can be filtered using clientEvents method or when it can be called

Calling it in the viewRender callback has strange behavior
1) Complete refresh from loading page : no event available
2) Using navigation arrows : events are not in synch with new view range, previous one is used
3) Changing view : previous view data

I feel the documentation shall say that it's forbidden to call clientEvents method from a renderer point.

**Comment by arshaw** [comment]
@foxalfabravo, for the strange behavior you describe, would you be able to post a [runnable, stripped-down demonstration of the bugs](http://fullcalendar.io/wiki/Reduced-Test-Cases/)?
