### ISSUE TITLE
integration with angular2

### ISSUE THREAD

**Issue by duetempi** [fullcalendar/fullcalendar#3392]
Do you can integrate the full calendar with angular2?
Where can I find an example?
Where are a example with groupByResource?

Thanks You

**Comment by arshaw** [comment]
the fullcalendar angular project is this: https://github.com/angular-ui/ui-calendar/

i'm not sure if it supports angular **2**, but if it doesn't, that project would be responsible for implementing it.

**Comment by mani3202** [comment]
@duetempi  Please go through the below example.

https://www.npmjs.com/package/ap-angular2-fullcalendar

Note : If calender is not displaying change Height to auto in CalenderOptions.
