### ISSUE TITLE
List View event dot marker, better docs

### ISSUE THREAD

**Issue by valentinozx** [fullcalendar/fullcalendar#3393]
Anyone know how to make sure of the event dot on the List View??
![listweek](https://cloud.githubusercontent.com/assets/23044932/19671687/200fcbb6-9aa3-11e6-81c3-98d039ffdf49.png)

I want to change the color according to the event status.

**Comment by espen** [comment]
What status? There is no status in the [event object](https://fullcalendar.io/docs/event_data/Event_Object/).

Perhaps you can try setting `className` on the event object based on your event status and then style it using `.my-class-name .fc-event-dot`.

**Comment by valentinozx** [comment]
Yes, I am aware there is no status field on the event object.

Let me re-phrase my question then, what is the purpose of the highlighted markers on the list view??

Can we manipulate it to display differently?

**Comment by espen** [comment]
Looks like it's the color that is normally used for [background color](https://github.com/fullcalendar/fullcalendar/blob/363db44fa57703eeca77fb1bf146173b28ee6c2f/src/list/ListView.js#L268) in the other views. So you could use this to display a status by setting [backgroundColor in the event object](https://fullcalendar.io/docs/event_data/Event_Object/).

**Comment by valentinozx** [comment]
This is the sample of my real implementation:
![samplelistweek](https://cloud.githubusercontent.com/assets/23044932/19749898/74e8d470-9c1f-11e6-9c3d-578bbc5042e1.PNG)

As you can see, I used different background colors to differentiate type of events but the marker dot is the same color for all events.

I wanted to make sure of the marker dot to indicate status

**Comment by ptica** [comment]
please follow the [advice by espen](https://github.com/fullcalendar/fullcalendar/issues/3393#issuecomment-256343945) then

**Comment by arshaw** [comment]
that is correct. thanks @espen . I'll repurpose this ticket to be about improving the docs, to make it clear that these event object color props affected the color of the dot.

**Comment by philip** [comment]
Related, how do we remove this dot from list view?

**Comment by ObuleshBandaru** [comment]
How can we change dot color for those events which are expired/completed?

**Comment by NestorlOsorioT** [comment]
encontré la solución, la idea es sobre cargar el color que tiene por defecto, en mi caso con primefaces, crear una hoja de estilo y sobre cargar el atributo css 
fc-event-dot

asi:
en hoja css nueva y sobre cargar
fc-unthemed .fc-list-item .fc-event-dot {
    background: white !important;
    border-color: white !important;
}

.fc-unthemed .fc-list-item.fc-event-solid-info .fc-event-dot, .fc-unthemed .fc-list-item.fc-event-info .fc-event-dot {
    background: white !important;
    border-color: white !important;
}

**Comment by Herz3h** [comment]
Is there an option to instead of having backgroundColor apply to do, to instead apply to the whole event like in dayGridMonth/timeGridWeek/etc @arshaw  ?
