### ISSUE TITLE
How to use Angularjs to create a calendar with resource

### ISSUE THREAD

**Issue by duetempi** [fullcalendar/fullcalendar#3395]
I have created the agenda with resource, but it don't work, why?

> var myApp = angular.module('myApp', ['ui.calendar', 'ui.bootstrap']);

myApp.controller('MainCtrl', ['$scope', '$timeout',
  function ($scope, $timeout) {

      $scope.n = 100;

      /* config object */
      $scope.uiConfig = {
          calendar: {
              allDaySlot: false,
              defaultView: 'agendaDay',
              editable: true,
              groupByDateAndResource: false,
              //groupByResource: true,
              lang: 'it',
              lazyFetching: false,
              locale: 'it',
              maxTime: '20:00:00',
              minTime: '08:00:00',
              nowIndicator: true,
              selectable: true,
              selectHelper: true,
              slotEventOverlap: false,
              slotDuration: '00:05:00',
              header: {
                  left: 'prev,next today',
                  center: 'title',
                  right: 'agendaDay,agendaTwoDay,agendaWeek,month'
              },
              views: {
                  agendaTwoDay: {
                      type: 'agenda',
                      duration: { days: 2 },

                      // views that are more than a day will NOT do this behavior by default
                      // so, we need to explicitly enable it
                      groupByResource: true

                      //// uncomment this line to group by day FIRST with resources underneath
                      //groupByDateAndResource: true
                  }
              },

              resources: [{
                  id: '1',
                  title: 'Room A'
              }, {
                  id: '2',
                  title: 'Room B'
              }],
              eventSources: [
                  {
                      id: '1',
                      resourceId: '1',
                      title: 'Meeting',
                      start: '2016-10-17 08:00',
                      end: '2016-10-17 08:15',
                      url: '#/planner/1/28',
                      color: randomColor(),
                      allDay: false
                  },
              {
                  id: '2',
                  resourceId: '2',
                  title: 'Meeting',
                  start: '2016-10-17 08:45',
                  end: '2016-10-17 09:00',
                  url: '#/planner/1/28',
                  color: randomColor(),
                  allDay: false
              },
              {
                  id: '3',
                  resourceId: '3',
                  title: 'Meeting',
                  start: '2016-10-17 08:45',
                  end: '2016-10-17 09:00',
                  url: '#/planner/1/28',
                  color: randomColor(),
                  allDay: false
              }]
          }
      };
}
]);
![ddd3d40c-9478-11e6-8273-43c452f8582f](https://cloud.githubusercontent.com/assets/22366073/19802110/625c5a14-9d02-11e6-9264-cf739b1b7097.png)

**Comment by espen** [comment]
hi @duetempi, this is for bugs and other issues not questions. Can you please try over at StackOverflow? See https://fullcalendar.io/support/

**Comment by arshaw** [comment]
this project's issue tracker would be a better place to ask about angular stuff:
https://github.com/angular-ui/ui-calendar/
