### ISSUE TITLE
Event overlaped with slotEventOverlap set to false

### ISSUE THREAD

**Issue by oscamen** [fullcalendar/fullcalendar#3396]
Sometimes events are overlaped with `slotEventOverlap: false` option.

Demo: https://jsfiddle.net/b14hkwun/2/

![demo](https://cloud.githubusercontent.com/assets/11599942/19803173/8e91c0ce-9d07-11e6-9b93-c05e2623e137.png)

**Comment by arshaw** [comment]
dup of:
https://github.com/fullcalendar/fullcalendar/issues/2758
&uarr;
@oscamen, could you please visit the link, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates?
