### ISSUE TITLE
How can I render a new event into a eventsource

### ISSUE THREAD

**Issue by qqbless** [fullcalendar/fullcalendar#3398]
### Bug Reports
When I use property 'eventSources',but I got a problem.I try to render a new event which containt property 'source',but it dose not work---no new dom display in the calendar.

mainDom.fullCalendar({
	......
	select : function (start, end, jsEvent, view){
		var source = mainDom.fullCalendar( 'getEventSourceById', "event" );
        var eventData = { id: uuid(), title: "abc", start: start, end: end ,source : source};
		//No error , but no dom display in the calendar
        mainDom.fullCalendar('renderEvent', eventData, true);
	},
	eventSources : [
	{
	  id:"plan",
	  events : [......],
	  color : '#00b300',
	  textColor : '#ffffff'
	},{
	  id:"event",
	  events : [......],
	  color : '#1a1aff',
	  textColor : '#ffffff'
	}
	]
});

PS:If I remove the property 'source',It's work,but it's not what I want --- I must set the event object into a eventsource;
var eventData = { id: uuid(), title: "abc", start: start, end: end};
//It's work
mainDom.fullCalendar('renderEvent', eventData, true);

### Feature Requests
How can I do,Thanks!

(Please erase the above text and begin typing. Thanks!)

**Comment by arshaw** [comment]
Would you be able to post a [runnable, stripped-down demonstration of the bug](http://fullcalendar.io/wiki/Reduced-Test-Cases/)? Would really appreciate it because the time saved reproducing will be time spent fixing.
