### ISSUE TITLE
Event snapping while using an external list

### ISSUE THREAD

**Issue by Rubenvanhoeyveld** [fullcalendar/fullcalendar#3399]
Hi,

I'm having issues with the way events are snapping in the recent versions of fullcalendar. I wanted to create an external list and I used this example to begin with: https://codepen.io/subodhghulaxe/pen/qEXLLr

This works and all, but when I try to drag an event outside of the calendar (in my environment, with fc 3.x), it still snaps in the timeline because more than half of the width of the event is still over the timeline. In the example on the page mentioned above, this is not the case as the snapping stops once the mouse leaves the timeline container.

The problem I'm having, is that eventDragStop and eventDrop are both fired, resulting in the event duplicating. One stays in the timeline while the other goes to the external list.

What am I missing here? Is there a way to adjust the way events snap? Did the snapping change between version 2.3 and 3.x?

**Comment by arshaw** [comment]
I'm having trouble knowing what the reproduction steps are after I open up your demo. could you please describe them more clearly or post a video?

**Comment by Rubenvanhoeyveld** [comment]
@arshaw The demo isn't mine and uses another version of fc (2.2.6). As I said, in my environment I use version 3.x.

Some screenshots of the problem:
(all names used are fictive)

My setup. At the left: the external list. At the right: fullcalendar with scheduler. 2 resources.
![image](https://cloud.githubusercontent.com/assets/3180443/20341647/5db79bd8-abe7-11e6-9c5d-c981b19b2208.png)

I selected the red event (by clicking on the left half of the event) and dragged my mouse to the left to over the external list. The event however still snaps to the inside of the calendar. In previous versions, the event only snapped as long as the mouse was over the calendar.
![image](https://cloud.githubusercontent.com/assets/3180443/20341714/a22d7c60-abe7-11e6-9988-48d013bcd8ce.png)

When I drop the event like this, both eventDragStop and eventDrop are fired, resulting in duplicating the event (only in the view, not in the back end or database).

![image](https://cloud.githubusercontent.com/assets/3180443/20341853/431ada8c-abe8-11e6-8c5a-3a79341ee6d2.png)

If I select the event in the calendar by clicking on the right half of the event, the event's half is outside the calendar faster and I can drop it in the external list properly.

![image](https://cloud.githubusercontent.com/assets/3180443/20341779/ea5055c6-abe7-11e6-9d9c-834b3a0b0421.png)

![image](https://cloud.githubusercontent.com/assets/3180443/20341782/f1d5832a-abe7-11e6-8b0b-098aede3576d.png)

Thanks in advance.

**Comment by arshaw** [comment]
Ah ok, thanks for the detailed explanation. So the event is so wide that when you try to drag it outside of the calendar, it never fully lets go of the snap.

May I ask, how are you hoping to accept the drop on the external list? I'm not sure FullCalendar's drag-n-drop system would know how to communicate this to whatever drop-accept system you're using.

Regardless, all these issues will be solved once an API is developed for this issue:
[Drop event outside of calendar / between calendars](https://github.com/fullcalendar/fullcalendar/issues/820)
&uarr;
Could you please visit the link, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates?

**Comment by Rubenvanhoeyveld** [comment]
I'm using the eventDragStop and eventDrop js events to know when the calendar event is dropped and in those js event listeners, I use a method to check whether or not the mouse cursor is over the external list. Dropping the calendar event on the external list already works, but as I said, both js events are fired, duplicating the calendar event. (wow, that's a lot of events)
