### ISSUE TITLE
How to disable a particluar event from dragging in v3.0.1

### ISSUE THREAD

**Issue by Sandip9021** [fullcalendar/fullcalendar#3400]
Hi @arshaw ,

I am using release 3.0.1 of ui-calender. My uiConfig file is like this -
```
 this.uiConfig = {
      calendar: {
        height: 'auto',
        editable: false,
        eventStartEditable  : true,
        header: {
          right: '',
          center: 'title',
          left: 'title,prev,next'
        },
        eventClick: function (calEvent, jsEvent, view) {
          vm.openSlotDialog(calEvent);
        },
        eventDrop: function(event, delta, revertFunc) {
                console.log("After drop this is called");
        },
        eventAllow: function(dropLocation, draggedEvent) { 
                      return  vm.calenderEventAllow(dropLocation, draggedEvent);                      
        },
```
![image](https://cloud.githubusercontent.com/assets/17237067/19865962/5dddf82a-9fc4-11e6-9899-7ca384383dd0.png)

But how to disable dragging for a particular event not the other events.

Like green events i want to drag , but not the orange ones.

Thanks in advance...

**Comment by Sandip9021** [comment]
Hi @arshaw , can you please help me on this..

**Comment by espen** [comment]
@Sandip9021 please see https://fullcalendar.io/support/ regarding questions. Also look through documentation. See for example https://fullcalendar.io/docs/event_ui/editable/ which should provide you with an answer.

**Comment by Sandip9021** [comment]
thanks a lot @espen , i got my answer....

**Comment by vaibhavshaha** [comment]
Hello Sandip9021 ,

How did you get solved to disable specific event from dragging can you post code that help me out

**Comment by Sandip9021** [comment]
Hi @vaibhavshaha ,  
when you will create event object for your calendar like below 
 this.events.push({
                    id: meeting.id,
                    title: "meeting 1",
                    start: meetingStartDate,
                    editable: false
                  });
make this editable field as false for not dragging and make it true for dragging.

**Comment by taublast** [comment]
do not forget to set startEditable = false; if you had it set to true in-before..

**Comment by arif-sk** [comment]
@Sandip9021 editable not working when declaring event object

**Comment by iamFoxx** [comment]
Just set editable = false;  on Event object
