### ISSUE TITLE
Booking/reservation platform: how to show booked dates in datepicker?

### ISSUE THREAD

**Issue by DavidatSplitPeak** [fullcalendar/fullcalendar#3401]
We are building a booking platform using fullcalendar and using a jquery datepicker via form fields on the room page.  Has anyone had any experience with connecting full calendar to the datepicker and showing dates that are already booked as not available?

**Comment by arshaw** [comment]
This is probably a feature request for the jquery datepicker project.

Though at some point the FC project might implement it's own version of it:
https://github.com/fullcalendar/fullcalendar/issues/438
&uarr;
Could you please visit the link, and if you're interested, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates?
