### ISSUE TITLE
Remove days from fullCalendar view

### ISSUE THREAD

**Issue by BourhiMaryem** [fullcalendar/fullcalendar#3404]
Hello

Im trying to remove days from a calendar, I Have a quarter view, but i each quarter displays the months and each day of the month, i only wan't to have 3 columns per quarter (No need for the days).

How can i achieve that ?

![untitled](https://cloud.githubusercontent.com/assets/18191091/19936325/feae9858-a114-11e6-95d6-a89e079a8ced.png)

**Comment by espen** [comment]
I think you have to create a custom view, see https://fullcalendar.io/docs/views/Custom_Views/. Alternatively you might have some luck overriding CSS and hiding some classes.

Also see regarding asking questions here https://fullcalendar.io/support/

**Comment by arshaw** [comment]
https://github.com/fullcalendar/fullcalendar-scheduler/issues/165
&uarr;
Could you please visit the link, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates?
