### ISSUE TITLE
The scroll bar always shows both in IE8 and chrome.

### ISSUE THREAD

**Issue by luoluojuzi** [fullcalendar/fullcalendar#3405]
Recently I use the fullcalendar in my project, but when I want to change the height of calendar in order to disable the scroll bar, both the 'height' and 'contentHeight' can not works, when I fix the contentHeight, rows becomes high and the scroll bar still exists. How can I fix the calendar's height, and make every month view contains the same height?
PS, the vesion is 3.0.1, sorry for my poor English. Thanks very much.

**Comment by arshaw** [comment]
Would you be able to post a [runnable, stripped-down demonstration of the bug](http://fullcalendar.io/wiki/Reduced-Test-Cases/)? Would really appreciate it because the time saved reproducing will be time spent fixing.
