### ISSUE TITLE
 customize noEventsMessage rendering in list view?

### ISSUE THREAD

**Issue by ganySA** [fullcalendar/fullcalendar#3406]
Hi

Is there a way to customise no events message using a template?

Thanks

**Comment by arshaw** [comment]
Not currently. You can only [customize the text](https://fullcalendar.io/docs/list_view/noEventsMessage/).

There should probably a way to have more rendering control. Will likely add a hook similar to `viewRender`.

**Comment by ganySA** [comment]
- Just one thing to add here might be nice to add a function callback here too.

**Comment by rkorebrits** [comment]
Did anything get implemented? Struggling to find any info. Also need a custom view with HTML in there.

**Comment by arshaw** [comment]
as of v5, this is fully customizable via [these render hooks](https://fullcalendar.io/docs/no-events-render-hooks)
