### ISSUE TITLE
default date is not working for months

### ISSUE THREAD

**Issue by BourhiMaryem** [fullcalendar/fullcalendar#3408]
I am trying to create  a calendar with a specific start and end date, for example i would like it to start on March 2012 and end on February 2013

i have tried defaultDate set as march 2012 and the duration as 1 year, but all it does is give me the start date as 2012 but the start month is by default January

**Comment by arshaw** [comment]
https://github.com/fullcalendar/fullcalendar/issues/429
&uarr;
Could you please visit the link, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates?

**Comment by arshaw** [comment]
this ticket might actually be more appropriate:
https://github.com/fullcalendar/fullcalendar/issues/3245
&uarr;
Could you please visit the link, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates?
