### ISSUE TITLE
how to show only current month date in month view of v1.6.4?

### ISSUE THREAD

**Issue by 805728578** [fullcalendar/fullcalendar#3409]
![calendar](https://cloud.githubusercontent.com/assets/9798724/19992991/37302b60-a27d-11e6-8b73-2b05c5ada473.png)

how to remove othe month date?follow up

**Comment by arshaw** [comment]
`fixedWeekCount` to `false`
https://fullcalendar.io/docs/display/fixedWeekCount/

or this feature request might better capture what you want:
https://github.com/fullcalendar/fullcalendar/issues/437
&uarr;
Could you please visit the link, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates?

**Comment by jimmylogic** [comment]
fixedWeekCount is not working in timelineMonth view.

**Comment by ubaa** [comment]
set `showNonCurrentDates` to `false`
https://fullcalendar.io/docs/showNonCurrentDates

**Comment by jaisonvarghese23** [comment]
set
 showNonCurrentDates: false,
