### ISSUE TITLE
Multi-day events with long titles adversely affect neighbouring events 

### ISSUE THREAD

**Issue by alex-humphreys** [fullcalendar/fullcalendar#3412]
Events with multiple days that have a long title that wraps to a second line will force events on the same week to be below it.

Also, and possibly related, single-day events with long titles seem to adversely effect neighbouring events in some way.

http://jsbin.com/sehojiliho/edit?css,js,output

**Comment by alex-humphreys** [comment]
I just discovered that it also happens with multi-line single-day events that have an event following them. [As seen here.](https://i.imgur.com/j1nnNg4.png)

**Comment by laoneo** [comment]
I second this, would be nice to have the same look and feel as with version 1 and 2. It looks much more elegant when the events are bigger.

Version 1.6
![image](https://cloud.githubusercontent.com/assets/251072/20106498/afb66918-a5d5-11e6-9abf-28befaf765a5.png)

Version 3.x
![image](https://cloud.githubusercontent.com/assets/251072/20106553/dcfb1608-a5d5-11e6-8b2f-7aba14fbdbd9.png)

Your proposed change does work but honestly I can't see all the consequences at the moment.

**Comment by arshaw** [comment]
hi guys, this existing ticket captures what you're requesting:
https://github.com/fullcalendar/fullcalendar/issues/2853
&uarr;
Could you please visit the link, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates?

Please give a 👍  on the TOOP DESCRIPTION of the issues.
Please see this comment on this issues, it's the most relevant:
https://github.com/fullcalendar/fullcalendar/issues/2853#issuecomment-225391100

**Comment by laoneo** [comment]
Honestly I'm not sure if this is the same problem as in #2853.
