### ISSUE TITLE
Webpack Issue

### ISSUE THREAD

**Issue by aaesis** [fullcalendar/fullcalendar#3413]
I use webpack for my JS compiler. I integrated the full calendar. and did not find the function "fullCalendar".

`import fullCalendar from 'fullCalendar';

$('..').fullCalendar({...})
`

**Comment by ocarreterom** [comment]
```js
import 'fullcalendar'; // or fullCalendar if you renamed it

$('..').fullCalendar({...})
```

**Comment by arshaw** [comment]
https://fullcalendar.io/support/
