### ISSUE TITLE
Stack events on week and day view.

### ISSUE THREAD

**Issue by mega-n3ss** [fullcalendar/fullcalendar#3414]
Hi,

I searched for this feature, options but I didn't find it. I have few events on the same moments. In my week view, I have this 
![screen shot 2016-11-07 at 14 27 36](https://cloud.githubusercontent.com/assets/8612349/20059469/b6d7e648-a4f6-11e6-9787-cf355524f739.png)

For the day view : 
![screen shot 2016-11-07 at 14 30 37](https://cloud.githubusercontent.com/assets/8612349/20059485/cf666f18-a4f6-11e6-802f-ac8a0996502c.png)

Is there a way to change this and stack them like in this month view  ?
![screen shot 2016-11-07 at 14 31 37](https://cloud.githubusercontent.com/assets/8612349/20059519/ea15de20-a4f6-11e6-845b-4692a3029df1.png)

Best Regards,

**Comment by arshaw** [comment]
i believe you are experiencing this known bug:
https://github.com/fullcalendar/fullcalendar/issues/2809
&uarr;
Could you please visit the link, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates?
