### ISSUE TITLE
Minified 'Print' CSS for Fullcalendar

### ISSUE THREAD

**Issue by sheltonjb** [fullcalendar/fullcalendar#3415]
Hi,

Can you please include a Minified CSS file of the Fullcalendar Print file, my particular version is 2.7.1 - I'm going through optimising and it's still complaining about this...

Thanks :)

**Comment by arshaw** [comment]
yes i'll try to make sure the next release does this. i might have already fixed this, i forget

**Comment by arshaw** [comment]
fixed in [v3.1.0](https://github.com/fullcalendar/fullcalendar/releases/tag/v3.1.0)

https://github.com/fullcalendar/fullcalendar/tree/v3.1.0/dist
