### ISSUE TITLE
Selection not properly clear on external event drop with unselectAuto=false

### ISSUE THREAD

**Issue by HgAlexx** [fullcalendar/fullcalendar#3417]
https://jsfiddle.net/0g7k27na/13/

Steps:
1. Make a selection to turn some days bleu.
2. Drop an external event on calendar
3. Make a new selection

Bug:
First selected days stay bleu

Expected:
Previous selection should be cleared on new selection.

Thank you for a great product !

**Comment by arshaw** [comment]
I can confirm. Thanks for the bug report.

**Comment by arshaw** [comment]
if this is still an issue in v5, the solution is to call `calendar.unselect()` when `eventReceive` is triggered. I'd prefer not to make the selection-clearing behavior built-in and default

**Comment by HgAlexx** [comment]
Hello,
Sadly the project I was using fullcalendar in is currently dead/sleeping :(
So I won't be able to test v5. I don't event remember how I fixed that at the time, certainly just like to said.
