### ISSUE TITLE
eventLimitClick, CellInfo add row, col.

### ISSUE THREAD

**Issue by Rouche** [fullcalendar/fullcalendar#3418]
### Bug Reports
Ive been struggling trying to mix Angular correctly with the popover rendered by ```renderMoreLink``` since 2 days. And its just impossible. 
Here are my findings, the only solution i that could figure out.

The idea is to use ```eventLimitClick``` as a callback, wich is already possible. But i need more.

I need to reuse the method of dayGrid ```showSegPopover```, so the events clicks gets rendered identically as original code, and goes through the same process.
This is mendatory for one thing, provide my own options to override ```showSegPopover``` default. Like ```autoHide: false``` and the method needs to return the Popover instance so i can hide it myself.

Problem with autoHide is the ```stopPropagation and preventsDefalt``` wich stop all clicks everywhere on other angular components. 
Popover also need to stay there in some "double popovers", to keep angular scopes in the DOM.

### Feature Requests
I know its a big change, but its all with no regressions.
add ```row, col``` properties to CellInfo parameter callback.

add options parameter to ```showSegPopover``` to override defaults.
A way to expose the method in a clean way, but i can already access it dirty with ```getView().dayGrid```.

return the Popover instance.
Note: i could hack inside dayGrid and reuse ```this.segPopover``` but thats definatelly wrong.

**Comment by Rouche** [comment]
Solution 2. less hacky.

in ```renderMoreLink``` provide ```eventLimitClick``` return value a way to inform about overrides and calback to inform about the Popover instance.

Lets say an object with 
```
{
setPopoverCallback: function,
popoverOptionsOverrides: {}
}
```

```
if (typeof clickOption === 'function') {
    // the returned value can be an atomic option
    clickOption = view.trigger('eventLimitClick', null, {
        date: date,
        dayEl: dayEl,
        moreEl: moreEl,
        segs: reslicedAllSegs,
        hiddenSegs: reslicedHiddenSegs
    }, ev);
}

if(typeof clickOption === 'object') {
    clickOption.setPopoverCallback(_this.showSegPopover(row, col, moreEl, reslicedAllSegs, clickOption.popoverOptionsOverrides));
} else if (clickOption === 'popover') {
    _this.showSegPopover(row, col, moreEl, reslicedAllSegs);
}
```

**Comment by arshaw** [comment]
Hi @Rouche thanks for the report. I'm just trying to flesh out exactly what you need, and if the API can be improved to accommodate:

When you say you want your "own options to override `showSegPopover default`. Like `autoHide: false`" ... are there any other options you want?

You say you need a "method needs to return the Popover instance so i can hide it myself." Would an API method to explicitly hide all popovers be sufficient for you, without needing the reference to the Popover object?

I'm afraid to make it toooo flexible because the API might seem incomprehensible to most. At that point you might want to create a custom view that is a subclass of one of the standard views, and have unlimited freedom of your own code.

**Comment by Rouche** [comment]
Hello @arshaw, your idea would work. 
* Yes, only ```autoHide``` is the problem, because it prevents defaults. But i need the possibility to provide a ```popoverClosed``` call back. Because someone can click the X in the corner to close it, and i would not be notified for this one.

* Yes, with above solution, a method to hide popovers would be sufficient. (Since i dont need to call destroy myself with #3419 commit)

Side note, I also think ```eventLimitClick``` definatelly need row col.
````    clickOption = view.trigger('eventLimitClick', null, {
        row: row,
        col: col
        date: date,
        dayEl: dayEl,
        moreEl: moreEl,
        segs: reslicedAllSegs,
        hiddenSegs: reslicedHiddenSegs
    }, ev);````
