### ISSUE TITLE
Locale are not built correctly on Windows. And build currently failing in master.

### ISSUE THREAD

**Issue by Rouche** [fullcalendar/fullcalendar#3420]
### Bug Reports
Trying to find what was the build problem with minify, i finally found what was the problem with Windows build.

in tasks\locale.js
Task : ```gulp.task('locale:each:data', function() {```
```file.path``` in windows is returned like C:\path\to\fullcalendar

You need to match against \ or / and its ok.

```var localeCode = file.path.match(/([^\/\\]*)\.js$/)[1];```

THEN i finally get the same error in your travis CI : 
```
[21:57:57] Starting 'locale:all'...
GulpUglifyError: unable to minify JavaScript
Caused by: SyntaxError: Unexpected token: punc ()) (line: 150, col: 0, pos: 4148)
```

So my code is not the problem. I will push you the fix for the build so it works in all systems.

**Comment by Rouche** [comment]
I finally finished finding the exact location of the failing build.

tasks/locale.js again

```js.replace``` function the ```return body;``` is returning the correct string, but the final js have an extra ");" added at the end. Resulting in an invalid javascript.

moment local wrapping may have been changed. Expression now need to have 3 X end parenthesys.
```/\(\s*function[\S\s]*?function\s*\(\s*moment\s*\)\s*\{([\S\s]*)\}\)\)\);?/```

Not sure if its enough tough. Pull request done.

```
function extractMomentLocaleJS(js) {

	// remove the UMD wrap
	js = js.replace(
		/\(\s*function[\S\s]*?function\s*\(\s*moment\s*\)\s*\{([\S\s]*)\}\)\)\);?/,
		function(m0, body) {
			return body;
		}
	);

	// the JS will return a value. wrap in a closure to avoid haulting execution
	js = '(function() {\n' + js + '})();\n';

	return js;
}
```

Time to sleep!

**Comment by ptica** [comment]
`npm install && gulp dev` fails for me on osx as well:
```
GulpUglifyError: unable to minify JavaScript
Caused by: SyntaxError: Unexpected token: punc ()) (line: 150, col: 0, pos: 4148)
```

**Comment by Rouche** [comment]
Use this commit Ptica https://github.com/Rouche/fullcalendar/commit/72332ed23cea72f7dd944e308193802c99f39e8b

**Comment by arshaw** [comment]
thanks for this work. i'll try to dig into this soon.
