### ISSUE TITLE
Select event not triggered when access from mobile

### ISSUE THREAD

**Issue by DMGPage** [fullcalendar/fullcalendar#3423]
In version 3 disappeared touch support. If I open version 2 demo page (fullcalendar.io/js/fullcalendar-2.7.0-beta/demos/selectable.html) in mobile, I can click events and I see javascript message. If I open version 3 demo page (fullcalendar.io/js/fullcalendar-3.0.1/demos/selectable.html) in mobile, after event click nothing happens.

**Comment by arshaw** [comment]
what type of device are you using?

**Comment by DMGPage** [comment]
Well I tested this with Chrome Device Toolbar, but clients say that calendar is not working with iPhone + Chrome. I can confirm that new version not working with my HTC + (CM Browser and Chrome) and Huawei ascend p6 + Firefox (works on Chrome). Today we find out, that on all browsers it works, if press on event a longer time. But problem is, that after release it selects some random event.

**Comment by DanielMutu** [comment]
I have the same problem, the touch doesn't work with V3. 
I tested it with Visual Studio Emulator For Android and Samsung phone

**Comment by DanielMutu** [comment]
ok, in the version 2.7.2 " dayClick:" works!! 
Good!! 😄

**Comment by arshaw** [comment]
Could you please try the [latest release](https://github.com/fullcalendar/fullcalendar/releases) (v3.2.0) ... I made quite a few touch-related fixes.

If you continue to have problems, I will reopen this ticket.

**Comment by DMGPage** [comment]
Tested this page: https://fullcalendar.io/js/fullcalendar-3.2.0/demos/selectable.html with chrome toggle device toolbar and firefox responsive design mode (with touch events) and it is not working. Nothing happens, when I click on events. HTC + (CM Browser and Chrome) again nothing...

**Comment by arshaw** [comment]
@DMGPage it is working great for me, though of course [eventLongPressDelay](https://fullcalendar.io/docs/event_ui/eventLongPressDelay/) and [selectLongPressDelay](https://fullcalendar.io/docs/selection/selectLongPressDelay/) are taking effect

**Comment by DMGPage** [comment]
Did not know there is delay now. In version 2.7.0 there was no delays, so I thought new version will work the same way.
Anyway tested again and everything looks good. Thank you for fixes.

**Comment by akshaysethia** [comment]
I am facing this same issue in version 5.4.9, 5.5.0 and 5.5.1

**Comment by innoflash** [comment]
I am having the same issue with v4.4.2
