### ISSUE TITLE
Fullcalendar custom content not related to event but to cell

### ISSUE THREAD

**Issue by stenkec** [fullcalendar/fullcalendar#3424]
Is there a way to put some content(ex. price for that day) in bottom right corner of the cells, predefined by database(or array), which is not related to some event - just days in calendar?
![test](https://cloud.githubusercontent.com/assets/23482471/20317853/271d0150-ab68-11e6-9376-ec97bbab1c60.png)

**Comment by arshaw** [comment]
hmm, even though you might visually consider this information tied to that day, I would still to prefer to keep it as an event. I'd rather not create a new paradigm or data structure for representing this info. Instead, I'd rather reuse the familiar existing event object.

So, I'd recommend using a styled event. If that does not suite your needs, and the styling you want to achieve are only possible via embedding the element within the day cell itself, I'd recommend using the [dayRender callback](https://fullcalendar.io/docs/display/dayRender/) to inject your own content.
