### ISSUE TITLE
timezone bug in select event

### ISSUE THREAD

**Issue by chilukey** [fullcalendar/fullcalendar#3427]
When set the timezone to 'local', the start and end in select event in Month view are still UTC time. But in Week and Day view, the start and end are correct as local time.

So, in the Month View, when I click a date to add an 'all day' event, the start time is:

Fri Nov 25 2016 19:00:00 GMT-0500 (EST)

It should be:

Fri Nov 26 2016 00:00:00 GMT-0500 (EST)

**Comment by arshaw** [comment]
that's because the month view emits ambiguously-timed moments:
https://fullcalendar.io/docs/utilities/Moment/

see this ticket if you are interested in discussion about ambig-timed moments:
https://github.com/fullcalendar/fullcalendar/issues/2981
