### ISSUE TITLE
Tapping on a Day automatically taps on an event right after

### ISSUE THREAD

**Issue by Vikaton** [fullcalendar/fullcalendar#3429]
I have a calendar that when you tap on a day, it sets that day with an event, and when you tap on the event, it deletes the event.

This works fine on my laptop, but it doesn't when I tried this on Safari on my iPhone and iPad.

What happened was when I hit the day to create a new event, it creates the new event but the `eventClick` handler is triggered without even explicitly tapping on the event. it's very strange.

here is the link to the full output to test on an iDevice: http://jsbin.com/cemunu/

here is the code: http://jsbin.com/cemunu/edit?html,js,console,output

**Comment by arshaw** [comment]
I'm able to reproduce this about 50% of the time. Seems somewhat dependent on fast I tap and possibly dependent on where on the day cell I tap.

I have a feeling this is related to the browser-blocking `confirm()` method. I have a feeling the touch event is being cancelled by the confirm dialog and when it closes, the touch event is "finished", even though your finger has already left the touchpad.

One way to find out is to use a non-native alert, like Bootstrap's dialog.
