### ISSUE TITLE
Getting error "units.toLowerCase is not a function" on v3.0.0 and above

### ISSUE THREAD

**Issue by hardik2038** [fullcalendar/fullcalendar#3430]
Until v2.9.1 works fine in my code.  However I want to use the new list views.  So tried v 3.0.0 & 3.0.1. But getting error "units.toLowerCase is not a function" on v3.0.0 and above.

Code as below:

HTML:
     // div id='calendar1'></div

Client Script:
	$(document).ready(function() {

		$('#calendar1').fullCalendar({
			header: {
				left: 'prev,next,today',
				center: 'title',
				right: 'month,agendaWeek,agendaDay,listWeek'
				},
			events: [
        {
            title  : 'event1',
            start  : '2010-01-01'
        },
        {
            title  : 'event2',
            start  : '2010-01-05',
            end    : '2010-01-07'
        },
        {
            title  : 'event3',
            start  : '2010-01-09T12:30:00',
            allDay : false // will make the time show
        }
    ]	
		});
  
	});

**Comment by arshaw** [comment]
i can't recreate when using 3.0.1:
http://jsbin.com/lobehahari/1/edit?js,output

**Comment by toxaq** [comment]
I had this issue today. Upgrading momentjs fixed it for me. I was in the middle of converting from bower to npm so wasn't sure quite what triggered as I was trying to keep the same version numbers where possible.
