### ISSUE TITLE
SlotDuration & minTime Bug

### ISSUE THREAD

**Issue by loyum** [fullcalendar/fullcalendar#3431]
Hello,

I'm french, sorry for my bad english...

I'm trying to do a timed slot duration for a special event.
1 slot duration is 35 mins, same for snap duration, and the event is starting at 8 am.
It was working on version 2, but not even more on V3.
What append is the slotDuration is correctly 35 mins (also snap), but starting at 00:00:00 instead of 8 am. It doesn't care about minTime.

JSfiddle FOR V3:                             http://jsfiddle.net/bxpxnwL2/3/
JSfiddle FOR V2 (Working one):     http://jsfiddle.net/bxpxnwL2/2/

**Comment by arshaw** [comment]
thanks! there's an existing ticket for this:
https://github.com/fullcalendar/fullcalendar/issues/2786
&uarr;
Could you please visit the link, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates?
