### ISSUE TITLE
Events on multiples days are badly displayed

### ISSUE THREAD

**Issue by loyum** [fullcalendar/fullcalendar#3433]
Hello,
When you have an event on multiples days without specifying the time, the displayed event is 1 day shorter.

JSFiddle: http://jsfiddle.net/bxpxnwL2/7/
PS: sorry for my bad english.

**Comment by loyum** [comment]
Same problem when it's a fullday event.

**Comment by arshaw** [comment]
please see:
https://github.com/fullcalendar/fullcalendar/issues/3205
