### ISSUE TITLE
Month view day number color?

### ISSUE THREAD

**Issue by fakeartist** [fullcalendar/fullcalendar#3434]
Hi. I have a question. In month view, I want to colorize the day number, only if it has an event. Ideally, I would the like the day number to have the event's color. How is this possible?

**Comment by arshaw** [comment]
will bel possible when this is implemented:
https://github.com/fullcalendar/fullcalendar/issues/345
&uarr;
Could you please visit the link, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates?
