### ISSUE TITLE
scrollTime propagate click

### ISSUE THREAD

**Issue by ricaragao** [fullcalendar/fullcalendar#3435]
Hi, 

I'm using scrollTime in runtime for change start time of day presantation go to first time with event of day.
But when I used the command above, the click is propagating and simulating one click on event (on app Android):

            $('#calendar').fullCalendar('option','scrollTime',varFirstTime);

**Comment by arshaw** [comment]
Would you be able to post a [runnable, stripped-down demonstration of the bug](http://fullcalendar.io/wiki/Reduced-Test-Cases/)? Would really appreciate it because the time saved reproducing will be time spent fixing.
