### ISSUE TITLE
Persistent URLs/URIs for each view

### ISSUE THREAD

**Issue by dereuromark** [fullcalendar/fullcalendar#3436]
### Feature request

Most JS driven solutions that update the content via AJAX provide some way of persisting this in the URL.

Currently if you click on next month a few times, and you are at `February 2017`, and you want to share this current page/link with a friend, it is impossible.
They always end up at the current month again.
But in fact, the URL should be now sth like `/my-calendar/#2017-02` and the library will pick that up and jump to that month.

It can also be query strings or alike if it is linked to the PHP code (outputting the right stuff) - but that would be a bit too advanced for now maybe.
The basic use case of copy-and-pasting between users and seeing the same content is a very important principle in web, though.

**Comment by ptica** [comment]
out of need I wrote this:
https://github.com/ptica/fullcalendar-history
ie updating the url via history api coupled with a client side cookie to persist the current date+view, plus clearing the presisted cookie on 'today' button
(which is a functionality you may not want at all)
the code is not much clean though

**Comment by arshaw** [comment]
please see:
https://github.com/fullcalendar/fullcalendar/issues/659
&uarr;
Could you please visit the link, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates?

**Comment by dereuromark** [comment]
Sure that is the same issue? Mine is more about having the current URL inside the browser URL - so copy and pasting it to someone else (via email) will open exactly the same month or detail view etc.

**Comment by arshaw** [comment]
yes, that issue's solution entails putting the state of the calendar (its date and possibly its view name) into the `#whatever` of the URL. will help the back button and will also solve your usecase of persistence when sharing links

**Comment by arshaw** [comment]
i've renamed that issue to better reflect
