### ISSUE TITLE
ES6 classes are not supported for grid class

### ISSUE THREAD

**Issue by bisubus** [fullcalendar/fullcalendar#3437]
Using native ES6 classes for grid classes in view class (e.g. TimeGrid) results in 

> Uncaught TypeError: Class constructor TimeGrid cannot be invoked without 'new'.

because of [this line](https://github.com/fullcalendar/fullcalendar/blob/v3.0.1/src/common/Class.js#L41-L43)

The same issue likely applies to Babel ES6 classes because they have a safeguard that prevents constructors from being called without `new`.

There's no problem if third party developer can choose if `Class.extend` or ES6 class is used.

But `Class.extend` is used internally to extend classes provided by third party (currently  `instantiateTimeGrid` and `instantiateDayGrid`).

The suggestion is to use mix-in technique [in `instantiateTimeGrid` and `instantiateDayGrid`](https://github.com/fullcalendar/fullcalendar/blob/v3.0.1/src/agenda/AgendaView.js#L40-L53) instead of grid class inheritance (applies to `AgendaView` and `BasicView`). Added methods aren't required on grid class construction and don't have to be prototype methods, they can be added to grid class instance:

```
var instance = new this.timeGridClass(this);
copyOwnProps(agendaTimeGridMethods, timeGridInstance);
return instance;
```

The example that reproduces the problem (JSBin is [here](http://jsbin.com/yefodun/edit?js,output)):

```
class CustomTimeGrid extends TimeGrid {}

class CustomView extends AgendaView {
	constructor(...args) {
		super(...args);
	}

	get timeGridClass() {
		return CustomTimeGrid;
	}
}

$.fullCalendar.views.custom = { class: CustomView };
 
$('#calendar').fullCalendar({
  defaultView: 'custom',
  ...
})
```

**Comment by arshaw** [comment]
i would have this this was resolved with 3.8.0, which uses the typescript compiler to target ES5, but now that i think about it, that doesn't make sense. seems the only way this would be fixed is if FC generated ES6 output.

whatever build system you're using to transpile and/or do modules (webpack?) you might want to have it reference the `src/` files of fullcalendar

**Comment by bisubus** [comment]
@arshaw I personally met this problem in native ES6 environment with fullcalendar global, but I assume same applies to any environment with ES6 target. I consider this issue a usual problem for any transpiled library that allows to use user-defined classes in configuration.

To my knowledge, relying on internal package structure and importing `src` is a bad practice and should be used only as the last resort.

As I mentioned in the issue, changing subclass a mix-in will likely solve the problem:
```
	instantiateTimeGrid: function() {
		var instance = new this.timeGridClass(this);
		copyOwnProps(agendaTimeGridMethods, timeGridInstance);
		return instance;
	},
```
or if the library relies on ES6 polyfills,

```
	instantiateTimeGrid: function() {
		return Object.assign(new this.timeGridClass(this), agendaTimeGridMethods);
	},
```

I see that agendaTimeGridMethods was refactored to [a subclass inside makeTimeGridSubclass mixin function](https://github.com/fullcalendar/fullcalendar/blob/v3.8.0/src/agenda/AgendaView.ts#L370-L372), but it's no problem becayse a subclass still adds methods and doesn't affect constructor.

**Comment by arshaw** [comment]
this is now possible in 3.8.1 (just released)

i still had to do them mixin approach you suggested w/ the current version of the code

working JSBin: http://jsbin.com/vehehavotu/edit?js,output
(please note i had to modify your code because of #3657 , which would cause an infinite loop ):
