### ISSUE TITLE
hide the heading row with columnFormat:false

### ISSUE THREAD

**Issue by Doc999tor** [fullcalendar/fullcalendar#3438]
AgendaDay view displays events for just one day. 
If a custom header is in use, the day title is unnecessary. 
I propose to add a view-specific `columnFormat: false` option which will empty the whole `thead.fc-head` or `td.fc-head-container`.

**Comment by arshaw** [comment]
makes sense.

**Comment by Doc999tor** [comment]
I'll send a pull request in a few days if I'll have a time.

**Comment by Rouche** [comment]
Do you think this one could be taken care of at the same time? 
#3331

**Comment by NickJorens** [comment]
Is there any progress? 
I'd love for this to be an option!

**Comment by Rouche** [comment]
No idea. You can build locally with my pull request i guess.

@arshaw Wanted to change it for dom manipulation hook. Wich requires a lot more change. Too much in fact.
Because right now, ```renderHeadDateCellHtml``` is only generating plain html string.

Personally, making it possible to customise the Html generated is enough. For now...

**Comment by caseyjhol** [comment]
@arshaw When `columnHead` is false, would you rather have an empty `<thead>` element, or do you want it gone completely?

**Comment by arshaw** [comment]
sorry for the delay @caseyjhol . If `columnHead` is `false`, I'd expect the `<thead>` to be completely gone.

**Comment by arshaw** [comment]
Released in [v3.6.0](https://github.com/fullcalendar/fullcalendar/releases/tag/v3.6.0)

docs: https://fullcalendar.io/docs/display/columnHeader/

(renamed to *columnHeader*)
