### ISSUE TITLE
"fullcalendar.min.js:6 Uncaught TypeError:  Cannot read property 'apply' of undefined"

### ISSUE THREAD

**Issue by McGreeb** [fullcalendar/fullcalendar#3439]
I have a popup that can be used to adjust things about an event such as time's name ect...

I have writen the following code to modify the event when the pop is closed.

```
    $("#SaveEvent").click(function(e) {
        
        $idstr = $("#eventid").val();
        $id = parseInt($idstr);
        
        $event = $("#calendar").fullCalendar('clientEvents', $id)[0];

        $event['title'] =  $("#title").val();
        $event['notes'] =  $("#notes").val();
        $event['resourceId'] =  $("#userid").val();
        $event['start'] =  moment($("#start").val());
        $event['end'] =  moment($("#end").val());
        
        SaveEventData($event);
        
        $("#NoteModal").modal('hide');
        $('#calendar').fullCalendar( 'rerenderEvents' );
    });
```

after executing rerenderEvents the calendar is blank and I get the console error "fullcalendar.min.js:6 Uncaught TypeError:  Cannot read property 'apply' of undefined" 

I will also get the error whenever I change pages or change from day, week, month ect. after having editied an event

**Comment by devarashetty** [comment]
@McGreeb I would like to know if you fixed the issue as I am facing the same issue too.Thanks

**Comment by arshaw** [comment]
Would you be able to post a [runnable, stripped-down demonstration of the problem](http://fullcalendar.io/wiki/Reduced-Test-Cases/)? Would really appreciate it because the time saved reproducing will be time spent fixing.
