### ISSUE TITLE
missing lines when zoomed in Firefox

### ISSUE THREAD

**Issue by rikuho** [fullcalendar/fullcalendar#3440]
1. open page in firefox 
https://fullcalendar.io/
2. click week
3. Zoom in/out the page
Some times the line is missing.
![screenshot_113016_041725_pm](https://cloud.githubusercontent.com/assets/16629429/20771691/7bdc856a-b718-11e6-8055-b4c616bc233f.jpg)
Other browser is ok

**Comment by arshaw** [comment]
hmm i can't recreate on my end. what version of firefox? what OS/version?

**Comment by rikuho** [comment]
Windows 10. Newest Firefox.

**Comment by rikuho** [comment]
I Reproduced the issue on another computer.
Windows 10 and latest FF
Zooming is by pressing ctrl button and moving the mouse wheel up/down 
![image](https://cloud.githubusercontent.com/assets/16629429/20867649/a6d99706-ba17-11e6-9e75-bbd162abc051.png)

**Comment by arshaw** [comment]
thanks, i've somewhat recreated. i've always known FF has problems with 1px borders and zooming. I'm not sure what the FullCalendar JS/CSS can do about this, but I'll leave this ticket open to collect feedback.

**Comment by arshaw** [comment]
this problem is probably impossible to solve, and also affects the whole internet not just FullCalendar, so closing
