### ISSUE TITLE
dow not working with timezone moment .. check for this 

### ISSUE THREAD

**Issue by rativardhan** [fullcalendar/fullcalendar#3441]
Hi sir,

i am user from IST and data come as per GMT and for repeating event where dow is set and timezone is local , i try to drop this anohter timeframe but it is automatically calculated and add +530 hour in it .
it is bug in 3.1.0 and 3.0.1 and some older version also. i tested can you please check and fix this . let me send you my configuration 
 

### Bug Reports
You MUST have a JSBin recreation, or else your issue will be CLOSED without explanation.
Instructions: http://fullcalendar.io/wiki/Reporting-Bugs/

### Feature Requests
Search the issue tracker for an existing ticket before creating a new one.
Instructions: http://fullcalendar.io/wiki/Requesting-Features/

(Please erase the above text and begin typing. Thanks!)

**Comment by arshaw** [comment]
Would you be able to post a [runnable, stripped-down demonstration of the bug](http://fullcalendar.io/wiki/Reduced-Test-Cases/)? Would really appreciate it because the time saved reproducing will be time spent fixing.
