### ISSUE TITLE
Window Scroll cause issue , while dragging the event.

### ISSUE THREAD

**Issue by affan-p-crest** [fullcalendar/fullcalendar#3442]
Hi!
I am using two pane display on web, one for calendar and another for Drag-able events, now the issue is when right side  panel have more lists of Drag-able events, then User can scroll to reach for particular event. and drop it over Calendar. 

Now we have vertical scroll bar , and tries to drag the Calendar event , moving to time slot, cause me issue, like , the position of dragging event not showing relative to mouse position. 

Please guide me to fix the same.

**Comment by arshaw** [comment]
could you post a video? i'm having a tough time visualizing the problem in my head

**Comment by affan-p-crest** [comment]
Hi!
I want to inform you that I have used https://github.com/seankenny/fullcalendar,
Link : http://www.screencast.com/t/6eS1F8z6qBb

Thanks!!!

**Comment by arshaw** [comment]
Thanks for the video. Question: how are the blue event elements on the right pane draggable? Are you using jQuery UI for those?

**Comment by arshaw** [comment]
and if you could somehow rig up a [Reduced Test Case](https://fullcalendar.io/wiki/Reduced-Test-Cases/) based on the [external event dragging demo](https://fullcalendar.io/js/fullcalendar-3.1.0/demos/external-dragging.html), that'd be great.

**Comment by affan-p-crest** [comment]
> Thanks for the video. Question: how are the blue event elements on the right pane draggable? Are you using jQuery UI for those?

Yes, the same on used on https://fullcalendar.io/js/fullcalendar-3.1.0/demos/external-dragging.html

**Comment by affan-p-crest** [comment]
Is it possible of JQuery conflicts with version ? 
I have also used Lobian JS plugin for Panel.

**Comment by arshaw** [comment]
@affan-p-crest , because you're using this repo's code: https://github.com/seankenny/fullcalendar
which is a fork of fullcalendar from long ago,
i cannot support your bug report. if you start using [Scheduler](https://fullcalendar.io/scheduler/) (an official paid plugin) for vertical resource view, you might have better luck.

**Comment by affan-p-crest** [comment]
Yeah , I got your point. 
By the way thanks for your time to respond me.
Have a great day!
