### ISSUE TITLE
End date not displayed correctly

### ISSUE THREAD

**Issue by netthinks** [fullcalendar/fullcalendar#3445]
If an event is longer than one day (full day), the end date is not shown correctly. 
https://fullcalendar.io/playground/jsbin.php/
![07-12-_2016_11-14-01](https://cloud.githubusercontent.com/assets/23073131/20963590/4fa01b8c-bc6e-11e6-9319-a8ec1c9634c9.jpg)

**Comment by Maciek143** [comment]
have the same error in 3.0.1 version

**Comment by arshaw** [comment]
please see: https://github.com/fullcalendar/fullcalendar/issues/3205
