### ISSUE TITLE
Events covering more than 1 week do not follow eventOrder

### ISSUE THREAD

**Issue by AppsbyMe** [fullcalendar/fullcalendar#3448]
http://jsbin.com/biciyoviyo/1/edit?js,output

The orange banners should always be at the top as titles for each week which are then clicked into for further details (not in jsbin example)

The blue event covers more than one week in this 4 week view and its position is below the week 1 banner but above the week 2 banner and no setting on eventOrder will fix this.

Other events then fill the blank space left above the orange banners

**Comment by arshaw** [comment]
i believe you request is similar to this:
https://github.com/fullcalendar/fullcalendar/issues/2907
&uarr;
Could you please visit the link, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates?

also, please let me know if i'm misclassifying this ticket
