### ISSUE TITLE
selectHelper function not getting called? How to keep selectHelper same size and move it one the screen until drag stopped? 

### ISSUE THREAD

**Issue by mitomm** [fullcalendar/fullcalendar#3451]
Hi everybody,

I'm not sure if I'm misunderstanding the docs, it's a bug or if I'm using it incorrectly but the select helper doesn't seem to get called at all (if I pass a function to it).

Here is a [JS Bin](http://jsbin.com/kixolubuwo/1/edit?js,console,output).

However, I may also be on the wrong path for what I'm trying to achieve. I would actually want something similar to this [demo with selectable time ranges](https://fullcalendar.io/js/fullcalendar-3.1.0/demos/selectable.html) with the difference that I always want the placeholder event to be 30 min and that it simply slides with the users moves/drags (with his finger or mouse) over the screen. I guess the functionality is similar to the native iPhone calendar. Everything happing after the user releases the select helper (storing event etc...) should be fine. My question is only related to the period where the user is draging the event.

Any ideas on how I can achieve the later?

Any help is greatly appreciated.

**Comment by arshaw** [comment]
eek. thanks for the report. it is actually a dup of:
https://github.com/fullcalendar/fullcalendar/issues/2832
&uarr;
Could you please visit the link, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates?
