### ISSUE TITLE
slodDuration 1 second

### ISSUE THREAD

**Issue by Tatikyan** [fullcalendar/fullcalendar#3452]
### Bug Reports
You MUST have a JSBin recreation, or else your issue will be CLOSED without explanation.
Instructions: http://fullcalendar.io/wiki/Reporting-Bugs/

### Feature Requests
Search the issue tracker for an existing ticket before creating a new one.
Instructions: http://fullcalendar.io/wiki/Requesting-Features/

(Please erase the above text and begin typing. Thanks!)

**Comment by Tatikyan** [comment]
I want to change slotDuration to 1 second as I drop on timeline videos , but browser is lagging , not responding , how can I fix this ? . Also is there any way that events overlap and don't get bottom second event other concatenate each other ? Thanks a lot.

**Comment by arshaw** [comment]
there are probably too many dom nodes. you'll probably want to make a [custom view](https://fullcalendar.io/docs/views/Custom_Views/) that has a very short duration, say, an hour or two. actually you might need to use `minTime/maxTime`. Unfortunately I can't help more than this; your usecase is not a typical one
