### ISSUE TITLE
Dynamically Changing businessHours,weekends,events option on .fc-next-button/.fc-prev-button button click

### ISSUE THREAD

**Issue by dhrubo001** [fullcalendar/fullcalendar#3455]
Hello friends,
I am trying to update some options of fullcalendar when clicked on .fc-next-button/.fc-prev-button button in week view.Actually i am having different business hours for each day and for that when a week in changed from 50  to 51, those days of 51 week should populate with their respective business hours.
It's not that it's not working but it's working for  a single click only from the 2nd click on .fc-next-button/.fc-prev-button jquery $.post method to fetch the business hours are not working, i am wondering why it is working in the first attempt and not working from the 2nd click.

$(' .fc-next-button').click(function () {
   var week = $('#week_number').val();
   var search_w = parseInt(week) + 1;
  $.post(base_url+'/update-calendar',{week:search_w},function(data){
	 $('#calendar').fullCalendar('option', {
		businessHours: data.bh,
		weekends: data.weekends,
	 });
	$('#calendar').fullCalendar('refresh');
    });
   $('#week_number').val(search_w);
 });

Presently this is the code i am trying to update both these options in fullcalendar.

Where i am doing wrong ??

And my complete code when the page loads

$('#calendar').fullCalendar({

    header: {
        left: 'prev,next today',
        center: 'title',
        right: 'month,agendaWeek,agendaDay,listWeek'
    },
    selectConstraint: 'businessHours',
    eventConstraint: 'businessHours',
    defaultView: 'agendaWeek',
    businessHours: {
        {
            $bh
        }
    },
    views: {
        month: { // name of view
            columnFormat: 'ddd'
                // other view-specific options here
        },
        agendaWeek: {
            columnFormat: 'ddd D'
        },
        agendaDay: {
            columnFormat: 'ddd D'
        },
        listWeek: {
            buttonText: 'list week'
        }
    },
    weekends: {
        {
            $weekends
        }
    },
    firstDay: 1,
    timeFormat: 'H:mm',
    navLinks: true,
    editable: true,
    eventLimit: true, // allow "more" link when too many events
    selectable: true,
    selectHelper: true,
    slotDuration: '00:15:00',
    eventLimitText: 'more',
    displayEventEnd: true,
    fixedWeekCount: false,
    weekNumbers: true,
    weekNumberCalculation: 'ISO',
    axisFormat: 'HH:mm',

    select: function(start, end) {

        var view = $('#calendar').fullCalendar('getView');
        //console.log(view.name);
        if (view.name != "month") {
            $('#ModalAdd #start_date').val(moment(start).format('YYYY-MM-DD'));
            $('#ModalAdd #end_date').val(moment(end).subtract(1, "days").format("YYYY-MM-DD"));
            $('#ModalAdd').modal('show');

        } else {
            $('#ModalAdd #start_date').val(moment(start).format('YYYY-MM-DD'));
            $('#ModalAdd #end_date').val(moment(end).subtract(1, "days").format("YYYY-MM-DD"));
            $('#ModalAdd').modal('show');
        }

    },
    eventRender: function(event, element) {
        element.bind('dblclick', function() {

            $('#editModal #id').val(event.id);
            $('#editModal #edit_title').val(event.title);
            $('#editModal #edit_customer').val(event.customer_id);
            $('#editModal #edit_team_member').val(event.team_member_id);
            $('#editModal #edit_description').val(event.description);

            $('#editModal #edit_color_value').val(event.color);
            $('#editModal #edit_start_date').val(moment(event.start).format("YYYY-MM-DD"));
            $('#editModal #edit_end_date').val(moment(event.end).format("YYYY-MM-DD"));
            $('#editModal #edit_start_hour').val(event.start_hour);
            $('#editModal #edit_start_min').val(event.start_min);
            $('#editModal #edit_end_hour').val(event.end_hour);
            $('#editModal #edit_end_min').val(event.end_min);
            $('#editModal').modal('show');
            $('.datepicker').datepicker('update', moment(event.start).format("YYYY-MM-DD"));
            $('.datepicker-end').datepicker('update', moment(event.end).format("YYYY-MM-DD"));

        });

    },
    eventDrop: function(event, delta, revertFunc) { // si changement de position

        edit(event);

    },
    eventResize: function(event, dayDelta, minuteDelta, revertFunc) { // si changement de longueur

        edit(event);

    },
    events: {
        {
            $data
        }
    },

});

**Comment by arshaw** [comment]
Would you be able to post a [runnable, stripped-down demonstration of the bug](http://fullcalendar.io/wiki/Reduced-Test-Cases/)? Would really appreciate it because the time saved reproducing will be time spent fixing.
