### ISSUE TITLE
Can't use vertical-resource-view + resourceGroupField

### ISSUE THREAD

**Issue by jlnery** [fullcalendar/fullcalendar#3458]
I tried to use de resourceGroupField with defaultView: 'agendaDay' but it doens't happen.

The child resources are not treated as would be in defaultView: 'timelineDay'.

![captura3](https://cloud.githubusercontent.com/assets/3345204/21125472/225d67e8-c0cd-11e6-9e09-ade26cc33f70.png)

**Comment by arshaw** [comment]
Would you be able to post a [runnable, stripped-down demonstration of the bug](http://fullcalendar.io/wiki/Reduced-Test-Cases/)? Would really appreciate it because the time saved reproducing will be time spent fixing.

**Comment by jlnery** [comment]
@arshaw sorry. This is the runnable: http://jsbin.com/vapezer/edit?js,output

My question is: if I change do 'timelineDay' it works. But with 'agendaDay' not. 

There is any way of this feature run with agendaDay displayView?

Something like 
![templateipi](https://cloud.githubusercontent.com/assets/3345204/21196247/1983f6e4-c21e-11e6-8abe-3f4839378df4.JPG)

Thanks

**Comment by arshaw** [comment]
thanks. i'm sorry for not understanding your original feature requests. there's actually already a request for this:
https://github.com/fullcalendar/fullcalendar-scheduler/issues/214
&uarr;
Could you please visit the link, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates?
