### ISSUE TITLE
Use FullCalendar without date

### ISSUE THREAD

**Issue by devqirl** [fullcalendar/fullcalendar#3459]
Right now, I'm making a timetable for a class schedule. My idea is to set the FullCalendar view to agendaWeek only and format other things. The programmatical side on how to fetch and add events is what I have no idea about since I won't be using any date for this instance.

This is the schedule table:

```
| schedid | subjectcode | prof_id  | day     | start_time | end_time | duration | room |
-------------------------------------------------------------------------------------------
| 1       | TECHNO      | 16-00001 | Monday  | 11:00:00   | 14:00:00 | 3        | SL   |
| 2       | TECHNO      | 16-00001 | Tuesday | 10:30:00   | 13:30:00 | 3        | SL   |
```

This is what I'm trying to achieve:

![image](https://cloud.githubusercontent.com/assets/24491133/21131426/9050c67e-c149-11e6-9011-74c65f6ed11f.png)

Here's my script for the FullCalendar:

```
$(document).ready(function() {
    $("#add-sched").fullCalendar({
        header: false,
        columnFormat: 'dddd',
        allDaySlot: false,
        hiddenDays: [0],
        defaultView: 'agendaWeek',
        minTime: '07:00:00',
        maxTime: '21:00:00',
        editatble: true,
        events: [ // values will be coming from an ajax call so I'm just placing here what inputs I would like
            {
                title: 'Event',
                start: 'MondayT11:00:00', //what I would like to input
                end: 'MondayT11:00:00',
//                start: '2016-12-12T11:00:00',
//                end: '2016-12-12T14:00:00',
                editable: true
            }
        ]
    });
});
```

I've read the documentation, the more I read, the more I can't figure out what to do and I really don't have any idea on how to implement this since FullCalendar depends on dates. Any advice and help would be very appreciated! ✨

**Comment by arshaw** [comment]
you're right, fullcalendar heavily relies on there being real dates, not merely times. i'd suggest using a fake date (like 2000-01-01) and then using the format string settings to make sure it's not displayed.

for more help, pls see https://fullcalendar.io/support/
