### ISSUE TITLE
How to retrieve the business hours of a specific day on select or click method

### ISSUE THREAD

**Issue by dhrubo001** [fullcalendar/fullcalendar#3460]
I have a application where different days in a week have different business hours now when in select or click in month/week view i need to get back the business hours i have setted for that particular day.

How to get that, plz help

**Comment by arshaw** [comment]
Question: since you set the business hours originally, why isn't this information already available to you?

**Comment by dhrubo001** [comment]
Actually i figured out a hack for this, i don't know it will be the correct way or not.
if we want the business hours of a specific date we set within fullcalendar and click or select event

var bh = $('#calendar').fullCalendar('option', 'businessHours');

We can get the complete set of business hours from this, it return and array and from this array we can get a day business hours and manipulate it
console.log(bh[6]); 
Where 1= Monday,2=Tuesday ...... 0 = Sunday.

Hope this one will help others also,.

**Comment by roldan** [comment]
If you need to check if the "selection" is inside of your business hours you could set "selectConstraint" option to "businessHours"

https://fullcalendar.io/docs/selection/selectConstraint/
