### ISSUE TITLE
Event rendered incorrectly in agendaWeek if event start and event end is same

### ISSUE THREAD

**Issue by badboy22** [fullcalendar/fullcalendar#3461]
In agendaWeek view, if event start date and event end date is same, event rendered incorrectly.

I tried it also with v3.1.0. To reproduce bug, init with an event like below;

events: [
            {
                title: 'Test',
                start: new Date(y, m, d, 23, 20),
                end: new Date(y, m, d, 23, 20),
                allDay: false
            }         
        ],

**Comment by arshaw** [comment]
this might be a misunderstanding of how end dates work. please see: https://github.com/fullcalendar/fullcalendar/issues/3205
