### ISSUE TITLE
Hide empty time ranges 

### ISSUE THREAD

**Issue by bartzushka** [fullcalendar/fullcalendar#3462]
Hello! I would like to know is it possible to hide time ranges where are not any event. 

![image](https://cloud.githubusercontent.com/assets/6364945/21217176/8b8f43b6-c2b3-11e6-9f63-4aea20f95720.png)

**Comment by arshaw** [comment]
no, not possible. i'm not sure that would be very usable tho. have you seen [list view](https://fullcalendar.io/docs/list_view/intro/) ?

**Comment by bartzushka** [comment]
Client want to minimize empty space, so i need to do that same as make some time ranges bigger if the event description is big... ok maybe it will have sense to find array of all empty time ranges  and hide them after rendering ? And they want a timeline, not a list view(

**Comment by espen** [comment]
@bartzushka you can create a custom view see https://fullcalendar.io/docs/views/Custom_Views/

**Comment by bartzushka** [comment]
@espen  Yeah, i did. I just need to hide empty cells dynamically on filtering and else. I think ill need to get an array of unused time slots and then just hide them on each filter  or next prev buttons clicked.
