### ISSUE TITLE
SCSS/SASS implementation of styles

### ISSUE THREAD

**Issue by medhatdawoud** [fullcalendar/fullcalendar#3463]

**Comment by arshaw** [comment]
@medhatdawoud could you please fill out the description a bit? what do you want as scss variables specifically?

**Comment by medhatdawoud** [comment]
I just want to use SCSS version for maintainability and for usage in applications that use scss

**Comment by phaidon** [comment]
That would be great. +1

**Comment by iMegABub** [comment]
A SCSS version  would be nice.

**Comment by RYJASM** [comment]
Was this ever added? I don't see any scss files.

**Comment by iMegABub** [comment]
Is this still in progress?

**Comment by arshaw** [comment]
the codebase is now using SASS
https://github.com/fullcalendar/fullcalendar/blob/master/src/main.scss

though we are not taking advantage of any of SASS's features yet. will wait for the front-end HTML/CSS to be refactored.
