### ISSUE TITLE
New phrases for locale files

### ISSUE THREAD

**Issue by masinosinaga** [fullcalendar/fullcalendar#3464]
I've just modified locale file for Indonesian language. I added some new phrases for several buttons: listDay, listWeek, listMonth, and listYear.

`!function(e){"function"==typeof define&&define.amd?define(["jquery","moment"],e):"object"==typeof exports?module.exports=e(require("jquery"),require("moment")):e(jQuery,moment)}(function(e,a){!function(){var e=a.defineLocale("id",{months:"Januari_Februari_Maret_April_Mei_Juni_Juli_Agustus_September_Oktober_November_Desember".split("_"),monthsShort:"Jan_Feb_Mar_Apr_Mei_Jun_Jul_Ags_Sep_Okt_Nov_Des".split("_"),weekdays:"Minggu_Senin_Selasa_Rabu_Kamis_Jumat_Sabtu".split("_"),weekdaysShort:"Min_Sen_Sel_Rab_Kam_Jum_Sab".split("_"),weekdaysMin:"Mg_Sn_Sl_Rb_Km_Jm_Sb".split("_"),longDateFormat:{LT:"HH.mm",LTS:"HH.mm.ss",L:"DD/MM/YYYY",LL:"D MMMM YYYY",LLL:"D MMMM YYYY [pukul] HH.mm",LLLL:"dddd, D MMMM YYYY [pukul] HH.mm"},meridiemParse:/pagi|siang|sore|malam/,meridiemHour:function(e,a){return 12===e&&(e=0),"pagi"===a?e:"siang"===a?e>=11?e:e+12:"sore"===a||"malam"===a?e+12:void 0},meridiem:function(e,a,i){return e<11?"pagi":e<15?"siang":e<19?"sore":"malam"},calendar:{sameDay:"[Hari ini pukul] LT",nextDay:"[Besok pukul] LT",nextWeek:"dddd [pukul] LT",lastDay:"[Kemarin pukul] LT",lastWeek:"dddd [lalu pukul] LT",sameElse:"L"},relativeTime:{future:"dalam %s",past:"%s yang lalu",s:"beberapa detik",m:"semenit",mm:"%d menit",h:"sejam",hh:"%d jam",d:"sehari",dd:"%d hari",M:"sebulan",MM:"%d bulan",y:"setahun",yy:"%d tahun"},week:{dow:1,doy:7}});return e}(),e.fullCalendar.datepickerLocale("id","id",{closeText:"Tutup",prevText:"&#x3C;mundur",nextText:"maju&#x3E;",currentText:"hari ini",monthNames:["Januari","Februari","Maret","April","Mei","Juni","Juli","Agustus","September","Oktober","Nopember","Desember"],monthNamesShort:["Jan","Feb","Mar","Apr","Mei","Jun","Jul","Agus","Sep","Okt","Nop","Des"],dayNames:["Minggu","Senin","Selasa","Rabu","Kamis","Jumat","Sabtu"],dayNamesShort:["Min","Sen","Sel","Rab","kam","Jum","Sab"],dayNamesMin:["Mg","Sn","Sl","Rb","Km","jm","Sb"],weekHeader:"Mg",dateFormat:"dd/mm/yy",firstDay:0,isRTL:!1,showMonthAfterYear:!1,yearSuffix:""}),e.fullCalendar.locale("id",{buttonText:{month:"Bulan",week:"Minggu",day:"Hari",listView:"Agenda",listDay:"Harian",listWeek:"Mingguan",listMonth:"Bulanan",listYear:"Tahunan"},allDayHtml:"Sehari<br/>penuh",eventLimitText:"lagi",noEventsMessage:"Tidak ada acara untuk ditampilkan"})});`

**Comment by arshaw** [comment]
@masinosinaga thanks, but would you mind submitting a PR with only [this file modified](https://github.com/fullcalendar/fullcalendar/blob/master/locale/id.js)?

Everything that is not in that file is brought in by moment.js's translations.

**Comment by masinosinaga** [comment]
Sure, I've just submitted it. Thanks for your quick response.

**Comment by arshaw** [comment]
thanks, i will try my best to incorporate this into the next release!

**Comment by masinosinaga** [comment]
Okay. Please do the similar thing also for the default language, English.

**Comment by arshaw** [comment]
What do you mean? Do you mean have "List Day" and "List Week" be the actual text? Is that what you implemented for your Indonesian fixes? I don't understand Indonesian so I don't know :)

I'm a little hesitant to do that because I imagine most people will only incorporate a single List view at a time. And most of the time you don't want something as verbose as "List Day" displayed to the user: it is not important to communicate the window of time. Just my opinion.

**Comment by masinosinaga** [comment]
My Calendar web application has the requirement to display listDay, listWeek, listMonth, and listYear so that users would be able to switch among those options. 

Currently, when it uses English as the default language, then those four buttons will display the same  "list list list list" (list four times), and it looks not good for user to see those buttons have the same caption/text on them.

**Comment by arshaw** [comment]
yes, but i'm guessing that the predominant usecase is a single list view, not multiple like yours. for you and others with your problem, you can simply override the text as calendar-specific settings, and not include it in the global locale data.

**Comment by masinosinaga** [comment]
Do you know how to override the caption/text for the specific button (such as my case above) on header/footer fullcalendar?

**Comment by arshaw** [comment]
yes, it's possible with [view-specific options](https://fullcalendar.io/docs/views/View-Specific-Options/). Demo:
http://jsbin.com/buramecaku/1/edit?js,output

**Comment by masinosinaga** [comment]
Thank you so much for your best support. I would like to send you some donation. Do you have the specific link for that? Thanks again!

**Comment by arshaw** [comment]
don't worry about it! just spread the word about the premium [Scheduler plugin](https://fullcalendar.io/scheduler/)!

**Comment by masinosinaga** [comment]
Sure, I will... and I am willing to purchase Developer License (1 developer) for that Scheduler plugin. Please wait within this next one or two days. Thanks again, and keep up the good support! :-)
