### ISSUE TITLE
The month view dates are disabled, when days in week view have different business hours

### ISSUE THREAD

**Issue by dhrubo001** [fullcalendar/fullcalendar#3465]
The month view dates are disabled, when days in week view have different business hours
Why this is happening, plz check the screenshots
In the week view actually i am able to select certain time slots and add new events in the calendar now the newly added events are coming in the month view no problem.But when trying to add new events for a particular date from month view i am unable to do it.

My week view has different business hours for each day.

What is the problem

![week_view](https://cloud.githubusercontent.com/assets/7116995/21305723/4535acc8-c5f3-11e6-9c3d-00f74143c194.png)
And this is the month view
![month_view](https://cloud.githubusercontent.com/assets/7116995/21305735/510a760a-c5f3-11e6-8ad6-4bd33305c37a.png)

**Comment by arshaw** [comment]
Would you be able to post a [runnable, stripped-down demonstration of the bug](http://fullcalendar.io/wiki/Reduced-Test-Cases/)? Would really appreciate it because the time saved reproducing will be time spent fixing.
