### ISSUE TITLE
[Docs] Incorrect method name

### ISSUE THREAD

**Issue by Ranjit-S** [fullcalendar/fullcalendar#3466]
On the renderEvents documentation page, the method name is incorrect.

`.fullCalendar( 'renderEvent', events [, stick ] )`

https://fullcalendar.io/docs/event_rendering/renderEvents/

**Comment by arshaw** [comment]
fixed, thanks!

**Comment by shawe** [comment]
May be isn't the one. For example:

https://fullcalendar.io/docs/event_data/Event_Object/

Event object with scheduler have resourceId, that isn't documented, I don't know if without scheduler resourceId also exists, but this type of problems case that we need more time than really needed to develop anything.
