### ISSUE TITLE
selectConstraint don't work with multiple hours

### ISSUE THREAD

**Issue by clockover** [fullcalendar/fullcalendar#3468]
Hello,

If I assign to selectConstraint (example): 
"{dow: [ 5 ],start: '14:30:00',end: '16:00:00'}"
I can't select slot other that in Friday between 14:30 and 16:00 as excepted.

But with:
"[{dow: [ 5 ],start: '12:45:00',end: '14:15:00'}, {dow: [ 5 ],start: '14:30:00',end: '16:00:00'} ]"
I can select all slots.

The value works with businessHours.
Anybody has the same issue ?
I use fullcalendar 3.1.0.

Thanks a lot!

**Comment by arshaw** [comment]
Would you be able to post a [runnable, stripped-down demonstration of the bug](http://fullcalendar.io/wiki/Reduced-Test-Cases/)? Would really appreciate it because the time saved reproducing will be time spent fixing.
