### ISSUE TITLE
Method to Set the slotDuration

### ISSUE THREAD

**Issue by NiklasKamenisch** [fullcalendar/fullcalendar#3470]
For my Implementation in need a Method to edit the slotDuration and rerender the View.
I will Resize the slotDuration on the fly.

I need a Method like:  $( '#FullCalendar' ).fullCalendar('option', 'slotDuration', '00:05:00');

**Comment by arshaw** [comment]
that should work. does it not work for you? if not, could you post a reduced test case? https://fullcalendar.io/wiki/Reduced-Test-Cases/
