### ISSUE TITLE
[DEPRECIATION WARNING] Conflict with locales of FullCalendar and Moment

### ISSUE THREAD

**Issue by vincent-guesnard** [fullcalendar/fullcalendar#3471]
Hello,

Nothing really important, just in case someone search on these keywords : 

Deprecation warning: use moment.updateLocale(localeName, config) to change an existing locale. moment.defineLocale(localeName, config) should only be used for creating a new locale See http://momentjs.com/guides/#/warnings/define-locale/ for more info.

That's OK, you just don't need to load both locales, from FullCalendar AND from Moment, else it will throw you this error.

**Comment by arshaw** [comment]
We might want to rethink how translations are done when fc is implemented as with ES6 modules, which the locales will hopefully leverage. until then, youre right, this is not showstopping

**Comment by sbsrouteur** [comment]
Upping this one as well. using moment.js does not conflct (and seems ok). Using moments-with-locale.js creates the issue, since all locales have already been inited in moments.
Seems weird to use the "non localized" version of moments and get moments localisation as a side effect of fullcalendar.

**Comment by arshaw** [comment]
I wonder if this is still the case with the v4 moment plugin. we'd need a recreation...

**Comment by arshaw** [comment]
on second thought, there's no way this bug still exists. in v4, fullcalendar does not attempt to populate moment locales in any way.
