### ISSUE TITLE
Add more <td> with info to calendar

### ISSUE THREAD

**Issue by luislopes27** [fullcalendar/fullcalendar#3472]
Hi guys, first of all congratulations for the great job!

I want to show more info in my calendar after the name of the event and I want to do that with more <td>.

Something like this: [link](https://s27.postimg.org/dvd4jfm6r/Capturar.png)

I can add more info with something like this:
 `element.find('.fc-list-item-title').append(event.description + "   " + event.teste);`

But that give me something like this: [link](https://s30.postimg.org/goe5f217l/Capturar.png) and I want to have it all in just one line.

Hope someone could help me, and sorry for my English mistakes!

**Comment by arshaw** [comment]
Would you be able to post a [runnable, stripped-down demonstration of the problem](http://fullcalendar.io/wiki/Reduced-Test-Cases/)? Would really appreciate it because the time saved reproducing will be time spent fixing.
