### ISSUE TITLE
Sticky/Fixed Header Row

### ISSUE THREAD

**Issue by chrisribal** [fullcalendar/fullcalendar#3473]
It would be nice to have the ability to fix the calendars thead if it reaches the browser window top.
See http://www.w3schools.com/Bootstrap/trybs_affix_navbar.htm for example using bootstrap affix.

I'm using the scheduler with more than 50 resources. After scrolling the desired resource i can't see the header row, which makes it dificult to drop events to the right time.

**Comment by arshaw** [comment]
would be cool!

**Comment by sense-design** [comment]
Would like to have this feature too

**Comment by VSpock** [comment]
Would be great

**Comment by adamduren** [comment]
Also locking time column is useful. I've been looking into if it can be done with purely css changes but with no luck. In our context the calendar is displayed on a phone with 7 days at a time. We can fit 3 days and want to scroll horizontally for the rest. Unfortunately the time column slides as well so we lose track of the timeslots.

**Comment by harish0000** [comment]
ETA? or any work around to fix this?

**Comment by harish0000** [comment]
any work around for this?? i need this badly

**Comment by adamduren** [comment]
I found a JS/CSS workaround I'll post when I get back to a desktop.

**Comment by harish0000** [comment]
@adamduren thanks ,awaiting your response

**Comment by adamduren** [comment]
I found the code in the referenced gist in a previous commit. Apologies there will be some extra css in this solution as it also implemented a sticky label column for horizontal scrolling as well. We eventually dropped fullcalendar as a dependency and went with a custom solution but hopefully this will get you on the right track.

https://gist.github.com/adamduren/c1f746824b273bef85bc914637dca5be

**Comment by harish0000** [comment]
@arshaw any fix for this ? need urgently..

**Comment by harish0000** [comment]
@arshaw any updates ?

**Comment by frlinw** [comment]
@harish0000 you can be patient or use the fullcalendar param `height: 'parent'` with something like `height: 100vh;` in the parent css class.
https://codepen.io/frlinw/full/JMvXEy/

**Comment by Shukarity** [comment]
The above workaround does not solve all scenarios
Is there anything steady on the stove?

**Comment by IndyHaine** [comment]
@frlinw hello and excuse me for the question, but how does that work?
If I use this in my code, the fullcalendar ignores the parent height (even if "height: parent" is set). You can easily see that in your codepen, too, if you change the height of #calendar to something like "30vh" or just "100px".
So whenever I try this in my code, there will not be a scrollbar and so the header will not be behaving like a sticky.

**Comment by IndyHaine** [comment]
@frlinw Is it possible that this workaround breaks as soon as I use the scheduler's timelineview? I'd really need it there...

**Comment by panfanky** [comment]
A jQuery workaround 
**to fix header row:**
css:
```
.fc-row.fc-widget-header{
	position:relative;
        z-index:2;
}
```
jQuery:
```
jQuery(window).on('scroll', function () {
 jQuery('.fc-row.fc-widget-header').css('top', jQuery(window).scrollTop());
});
```

**to fix time column:**
css:
  ```
.fc-axis.fc-time.fc-widget-content{
	position:relative;
}
```
jQuery:
```
jQuery(window).on('scroll', function () {
 jQuery('.fc-axis.fc-time.fc-widget-content').css('left', jQuery(window).scrollLeft());
});
```

Use jQuery("#container") instead of jQuery(window) if you have the calendar in overflow:scroll/auto element.

**Comment by arshaw** [comment]
If you're curious to know, this will be included in v5 (currently in-development)
**blog post:** https://fullcalendar.io/blog/2020/02/changes-in-the-upcoming-v5

**Comment by arshaw** [comment]
Please see the [v5.0.0-beta.2 blog post](https://fullcalendar.io/blog/2020/04/new-ui-features-beta). It has links to demos showing the new v5 sticky header behavior.

For those of you wanting to fix the time time axis in timegrid view, you can achieve that with [dayMinWidth](https://fullcalendar.io/docs/v5/dayMinWidth). See [a demo](https://fullcalendar.io/docs/v5/dayMinWidth-demo). also in v5-beta

**Comment by arshaw** [comment]
the ability to make the top and bottom **toolbars** is still not implemented however. for that, please see this issue:
https://github.com/fullcalendar/fullcalendar/issues/5357

**Comment by arshaw** [comment]
officially released: https://fullcalendar.io/blog/2020/06/v5-official

**Comment by arshaw** [comment]
docs: https://fullcalendar.io/docs/stickyHeaderDates
