### ISSUE TITLE
`fc-nonbusiness` elements blocking mouse events

### ISSUE THREAD

**Issue by StefanoGitHub** [fullcalendar/fullcalendar#3475]
Hello,
I created a tooltip which displays the time slot (mainly for people with sight impediment): https://jsfiddle.net/jStefano/1daqmhL4/
It mostly works fine, but it does not appear over the `fc-nonbusiness` elements.
What am I doing wrong? I haven't been able to correctly target the row probably...
Is there maybe like an event bubbling stop on the overlapping elements?

Thanks

**Comment by arshaw** [comment]
in your code, you are using some clever hacks to get the slot time to get the example, which depend heavily on the structure of the dom. if this feature request is implemented, would make it much more robust:
https://github.com/fullcalendar/fullcalendar/issues/2430
&uarr;
Could you please visit the link, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates?

**Comment by StefanoGitHub** [comment]
Thanks @arshaw, but do you see any workaround in the meanwhile?
Why the mouse event is "blocked" over the `fc-nonbusiness` elements? Shouldn't it bubble up from the `td` and "pass" the covering element? 
Thanks

**Comment by arshaw** [comment]
the fc-nonbusiness elements share a completely different parent than the slot elements, so it won't work. i'd recommend using `pointer-events: none` (https://developer.mozilla.org/en-US/docs/Web/CSS/pointer-events) on the fc-nonbusiness elements to have them ignore mouse interaction

**Comment by StefanoGitHub** [comment]
Great, it works!!
Thanks a bunch
