### ISSUE TITLE
Incorrect logic of calendar title formatting 

### ISSUE THREAD

**Issue by Mubat** [fullcalendar/fullcalendar#3478]
I have incorrect logic of formatting calendar title in Russian language.
I want to see "02 - 08 January 2017 " in Russian. 

_Expected result_: "02 – 08 январ**я** 2017" 
_Actual result_: "02 – 08 январ**ь** 2017" 

Moment.js has correct formatting. If it try to format month and see that day staying before month, it use `months.fomat` array from _locale/ru.js_.

Issue placed in `formatRangeWithChunks()` function - it format title separately.

**Comment by arshaw** [comment]
I understand @Mubat , thanks. FullCalendar's range formatting will need to respect the ["standalone" month date formatting](https://github.com/moment/moment/blob/2.17.1/locale/ru.js#L47)

**Comment by arshaw** [comment]
Fixed in [v3.2.0](https://github.com/fullcalendar/fullcalendar/releases/tag/v3.2.0)
