### ISSUE TITLE
difference between minified and full 

### ISSUE THREAD

**Issue by chrwei** [fullcalendar/fullcalendar#3479]
not sure I can actually make a jsbin for this...

I was able to make my implementation work on IE8 (yeah I know it's not supported all around) by adding the "polyfill" prototype from https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/forEach

BUT it only works on the full version, the min.js version from the same fullcalendar-3.1.0.zip gives a rather difficult to track generic object error.  

is it expected that the full and minfied versions behave differently?

**Comment by arshaw** [comment]
Strange. The minified version is supposed to behavior exactly the same as the non-minified version.

Since the preconditions to recreate this bug are rather obscure, it might take a little while before we see a solution.

**Comment by chrwei** [comment]
reproduction should be easy, add the forEach prototype code from the link, then load in IE, especially IE8.  I've got mine up and running now so I'll see if I can make a simple page
