### ISSUE TITLE
How to block all weekdays in a week and weekends of another week

### ISSUE THREAD

**Issue by dhrubo001** [fullcalendar/fullcalendar#3480]
Hello guys,
I have situation where i need to block all weekdays in a week making saturday and sunday editable only and vice versa , but how to achieve it.Remember i have different business hours for different days in a week.
I am setting the business hours in week mode like this
businessHours: [{"start":"09:00","end":"17:00","dow":[1]},{"start":"09:00","end":"17:00","dow":[2]},{"start":"09:00","end":"17:00","dow":[3]},{"start":"09:00","end":"17:00","dow":[4]},{"start":"09:00","end":"17:00","dow":[5]},{"start":"16-01-2016","end":"16-01-2016","overlap":false,"rendering":"background","color":"#ff9f89","dow":[6]},{"start":"17-01-2016","end":"17-01-2016","overlap":false,"rendering":"background","color":"#ff9f89","dow":[0]}],

But i want the weekdays to be ashed color if they are closed and same with the weekends of another week.

How to achieve it

**Comment by espen** [comment]
You can do this in two ways:

1) Update the businessHours when changing date/view: https://fullcalendar.io/docs/utilities/dynamic_options/

2) Render unavailable times as background events.

btw see https://fullcalendar.io/support/ regarding questions.

**Comment by dhrubo001** [comment]
You didn't get me properly the thing which i want to achieve is that lets say
In week 1 of 2017 only weekends are active , so in this case i want to disable (Will be shown in month view) the weekdays and the opposite in week 2 of 2017 how to achieve this

**Comment by arshaw** [comment]
[Background Events](https://fullcalendar.io/docs/event_rendering/Background_Events/) allow arbitrary dates @dhrubo001. You should be able to achieve what you want.
