### ISSUE TITLE
Provide a way to separate the event per day

### ISSUE THREAD

**Issue by geraldvillorente** [fullcalendar/fullcalendar#3481]
Consider this example.
http://web-341020d5-e153-47c1-98fa-d9a1a696458f.runnablecodesnippets.com

For styling/design purposes is there a way to separate the event per day instead of having to have single element that display the event once per week? 

I have a requirements to only display the event as dot below the date. So for example I have an event from January 1 to January 6 then I should have a dot foreach day from 1 until 6.

Is this possible?

See my example.

![sample](https://cloud.githubusercontent.com/assets/820842/21825293/1a968c62-d7be-11e6-991d-beec9f4c6e92.png)

Thank you.

**Comment by espen** [comment]
1) Please see https://fullcalendar.io/support/ regarding questions and feature requests.

2) Your link is 404

3) If you require some custom functionality consider using a custom view: https://fullcalendar.io/docs/views/Custom_Views/
