### ISSUE TITLE
Invalid view month

### ISSUE THREAD

**Issue by jbije** [fullcalendar/fullcalendar#3484]
Hello, 

Im having a bit problem with viewing current month events only, just wanted to exclude other months event.

using ` view.start.month()` while viewing December 2016, it show `View: 10` instead of `View: 11` as December is 11 while `event.start.month()` is correct it gives 11.

Code:
```
eventRender (event, element, view) {
    console.log('View: '+view.start.month(), 'Event: '+event.start.month(), 'Date: '+event.start._i);
    if( view.start.month() != event.start.month() ) {
        return false;
    }
 }
```

Current view month: December 2016
![fc](https://cloud.githubusercontent.com/assets/7915328/21943218/3d8e5110-da0b-11e6-83fe-2ba9b08564e6.PNG)

Hopping to solve this.

**Comment by arshaw** [comment]
Would you be able to post a [runnable, stripped-down demonstration of the bug](http://fullcalendar.io/wiki/Reduced-Test-Cases/)? Would really appreciate it because the time saved reproducing will be time spent fixing.
