### ISSUE TITLE
Sunday event not showing in Week view when using JSON feeder.

### ISSUE THREAD

**Issue by kkazants** [fullcalendar/fullcalendar#3485]
Full disclosure:
	This is a bug that needs fixing or remove the PHP code. Please read through everything before closing this issue. I was able to duplicate the issue with code that comes with FullCalendar-3.1.0. I am aware that FullCalendar is a front-end widget, but as this back-end code was provided with the whole package, at least I wanted to get this issue known. Anyone who has the demos provided by FullCalendar can easy reproduce this issue by following the below instructions. The original demo can be viewed here: https://fullcalendar.io/js/fullcalendar-3.1.0/demos/json.html, but unable to make the minor changes to reproduce the issue. But I bet if FullCalendar goes and makes the 2 minor changes to their code, everyone would be able to see the issue. I have tried to produce a website to for easy reproduction but I couldn't find any site that would host dynamic sites for free. JSbin and JSFiddle do not run server side code.

I am not alone on this issue, I have searched online for answer and did not find any. Here is another person that has/had this issue: http://stackoverflow.com/questions/34756701/fullcalendar-agendaview-not-showing-sunday-events. Yes the question is old but I was able to duplicate this issue in the 3.1 version as well.

Desired Behavior: 
	Have a fullcalendar that gets data from json file using the default get-events.php whose default view is week and display all events including Sunday events. Unfortunately, when user is feeding the events from a json file using the get-events.php file provided by FullCalendar, and the default view is a week or day, the event(s) that happen on a Sunday (start and end on that day) are not displaying. But when the user clicks on month view, the event shows up. After that, when user clicks on week or day view, the event will display. But if user refreshes their browser (keeping in mind that the default view is week), the Sunday event does not display.

To Reproduce the Bug: 
	Use the json.html file found in the demos of the FullCalendar (3.0.1 or 3.1.0). Set the default view to week agenda or list.  
![image](https://cloud.githubusercontent.com/assets/10411394/21995928/9e7210ac-dbf5-11e6-8f7e-3464163c8bb0.png)
 In the json folder, change one of the events dates to a Sunday or create an event that starts and ends on the same Sunday in events.json file.
![image](https://cloud.githubusercontent.com/assets/10411394/21995936/aa694524-dbf5-11e6-880a-1e677fbe5e03.png)
Now, open the json.html, and the Sunday event does not show up:
![image](https://cloud.githubusercontent.com/assets/10411394/21995945/bf4a0690-dbf5-11e6-99f2-719914af9105.png)
Now click on month and notice that the event has shown up: 
![image](https://cloud.githubusercontent.com/assets/10411394/21995951/cd258258-dbf5-11e6-8986-4edb048d329d.png)
Now click on week or list and you will notice that the event still displays: 
![image](https://cloud.githubusercontent.com/assets/10411394/21995961/d9ea08ba-dbf5-11e6-99a9-a53ac3275737.png)
Then refresh the browser and you will notice that the event is not showing up again. All this using the default functions of FullCalendar.

**Comment by arshaw** [comment]
You've definitely uncovered a bug in the PHP.

I've created a fix. will get into the next release:
https://github.com/fullcalendar/fullcalendar/commit/002393ce3d828ab4f2d5d3bb3f67d9c6b9692eec

Was an erroneous `>` comparison when it should have been a `>=`, when dealing with start dates.

**Comment by arshaw** [comment]
Released in [v3.2.0](https://github.com/fullcalendar/fullcalendar/releases/tag/v3.2.0)

**Comment by Shaileshbudakoti100** [comment]
I am also getting the above problem in angular 5. My defaultView is agendaWeek.
but when set 

          {
                start: '00:00', 
                end: '01:00', 
                dow: [1, 2, 3, 4, 5, 6, 7], // Repeating every day but not  sunday
                color: 'green',
                textColor: 'black',
                title: '01:00',
                className:"custom-class"
            }

dow is repenting every day but not on Sunday
![calendar](https://user-images.githubusercontent.com/37871376/38030388-17543096-32b6-11e8-98b7-9e039844e0db.png)

**Comment by billyshena** [comment]
Also having this issue on Sunday, any news about this

**Comment by acerix** [comment]
Your issue doesn't seem related, so please open a new issue if there is a bug, but I think you just need to use 0 for Sunday instead of 7.
