### ISSUE TITLE
Localization missing for 'No events to display'

### ISSUE THREAD

**Issue by fra-gadio** [fullcalendar/fullcalendar#3488]
The text 'No events to display' is always in English and is not localized.

**Comment by arshaw** [comment]
![screen shot 2017-01-18 at 11 14 50 pm](https://cloud.githubusercontent.com/assets/56520/22097069/ee5d51d2-ddd3-11e6-97d0-2f9607606c26.png)

^ are you sure?
https://fullcalendar.io/js/fullcalendar-3.1.0/demos/locales.html

**Comment by fra-gadio** [comment]
I had to add locales-all.js to make it work.  thank you.

**Comment by palhinhax** [comment]
i´m having the same issue now. everything is being translated but this.

**Comment by keygun-development** [comment]
@palhinhax to fix the problem:
```
<script>
import { Calendar } from '@fullcalendar/core';
import allLocales from '@fullcalendar/core/locales-all';

let calendar = new Calendar(calendarEl, {
  locales: allLocales,
  locale: 'fr' // the initial locale
  // All your other options
});

calendar.render()
</script>
```
