### ISSUE TITLE
Make ListView available to use it as a customView

### ISSUE THREAD

**Issue by jmontoyaa** [fullcalendar/fullcalendar#3489]
In the custom view example here:

https://fullcalendar.io/docs/views/Custom_Views/
```

var FC = $.fullCalendar; // a reference to FullCalendar's root namespace
var View = FC.View;      // the class that all views must inherit from
var CustomView;          // our subclass

CustomView = View.extend({ // make a subclass of View

    initialize: function() {
        // called once when the view is instantiated, when the user switches to the view.
        // initialize member variables or do other setup tasks.
    },

```
I cannot inherite the ListView class.

The idea is to call it like this:

```
var FC = $.fullCalendar;
var View = FC.ListView;      // <<--- changed
```

There's a reason why "ListView" is not available?

**Comment by arshaw** [comment]
we no longer offer views as classes to be extended. we should probably make more composable view subcomponents for people to use. discussing an API should be done on another ticket.

fyi: https://fullcalendar.io/docs/custom-view-with-js
