### ISSUE TITLE
eventClick: Event end date is null when event is one day

### ISSUE THREAD

**Issue by mtaylor456** [fullcalendar/fullcalendar#3491]
Is this a bug? The event **end** date is missing when event is one day:  

http://jsbin.com/gopajaqiyi/1/edit?js,output

Click on the 19th january event

If it's not a bug what is the benefit of leaving it null?

**Comment by arshaw** [comment]
That's because the `end` wasn't specified in the input.

you might want to look at [forceEventDuration](https://fullcalendar.io/docs/event_data/forceEventDuration/)

**Comment by mtaylor456** [comment]
I found in my case that if I specified an end date input (e.g 2017-01-01) but not a **time** it would return null as the end date.

**Comment by arshaw** [comment]
i bet the end date you're specifying is the same as the start date, in which case it drops it as invalid. end dates are exclusive. just a guess. can't tell for sure without another jsbin.

**Comment by mtaylor456** [comment]
Not quite, the end **time** has to be the same. If you have the same date + time or do not specify a time then null is returned....see 19th

http://jsbin.com/keqinoraqu/1/edit?js,output

**Comment by arshaw** [comment]
```
{
    title: 'END DATE NULL',
    start: '2017-01-19T07:00:00', // has a time specified! whole even considered "timed" now
    end: '2017-01-19' // does not have a time specified... will infer 00:00:00
}
```

...and because `2017-01-19T00:00:00` takes place BEFORE `2017-01-19T07:00:00` it is considered invalid and discarded.

**Comment by arshaw** [comment]
in summary: the event must have a non-zero duration

**Comment by mtaylor456** [comment]
Thanks
