### ISSUE TITLE
Question: Is version 3.1 supposed to work with jquery 1.9.x?

### ISSUE THREAD

**Issue by rnixx** [fullcalendar/fullcalendar#3493]
Hi,

is the current version of fullcalendar supposed to work with jquery < 2.0? AFAIK 2.0 is API compatible with 1.9.x, so are there any new features in 2.0 used in fullcalendar?

Thanks

**Comment by arshaw** [comment]
The reason I dropped jQuery 1.x support is because FC dropped support for IE 8 and lower, so there was no need to officially "support" jQuery 1.x anymore. It might work, but use at your own risk.
