### ISSUE TITLE
Formatting functions (momComputableOptions) fails with non-default format

### ISSUE THREAD

**Issue by MartijnWelker** [fullcalendar/fullcalendar#3494]
Hi, 

When you have a non-standard `LT` date format with a custom string (such as `HH[time]mm`) the `momComputableOptions` replace regex (`/(\Wmm)$/`) fails, i've tried to create a [full test case](http://jsbin.com/zobokelizi/1/edit?js,console) explaining the situation.

**Comment by arshaw** [comment]
ah yes, it's being mangled here:
https://github.com/fullcalendar/fullcalendar/blob/v3.1.0/src/locale.js#L122

the `[` is matching the `\W` in the regex.

thanks.

**Comment by arshaw** [comment]
v4/v5 no longer offer string-base date formatting specifiers. uses the built-in Intl API instead
