### ISSUE TITLE
How can update the id of an event?

### ISSUE THREAD

**Issue by necto101** [fullcalendar/fullcalendar#3495]
1. I add an event using drag&drop from a table.
2. The event is added to a MySQL database. The database assign an id (autonumeric).
3. The id is returned by json to jquery.
4. I try to use this:

event.id = idAssigned;                      
$('#calendario').fullCalendar('updateEvent', event); 

But it doesnt work, because if I try to find the event using:
$("#calendario").fullCalendar('clientEvents', idAssigned);
it returns an empty array.

**Comment by arshaw** [comment]
dup:
https://github.com/fullcalendar/fullcalendar/issues/2928
&uarr;
Could you please visit the link, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates?
