### ISSUE TITLE
more option in slotLabelFormat

### ISSUE THREAD

**Issue by leehan0617** [fullcalendar/fullcalendar#3496]
hi, I have question about slotLabelFormat in agenda view.

my option lists are  this
`
slotDuration : '00:30:00',
scrollTime : '09:00:00',
slotLabelFormat : 'HH:mm [~] HH:30'
`
I want to show time format 'HH:mm [~] HH:' + (mm+30) 
but this code is useless.
I want to this view
`
<table>
<tr>
<td>09:00 ~ 09:30</td><td></td><td></td>
</tr>
<tr>
<td>09:30 ~ 10:00</td><td></td><td></td>
</tr>
<tr>
<td>10:00 ~ 10:30</td><td></td><td></td>

</tr>
</table>
` 

but now, My project is showing..
<table>
<tr>
<td>09:00 ~ 09:30</td><td></td><td></td><td></td>
</tr>
<tr>
<td></td><td></td><td></td><td></td>
</tr>
<tr>
<td>10:00 ~ 10:30</td><td></td><td></td><td></td>
</tr>
</table>
So, how can I set option to make this view?
My English skill is so little.. thanks

**Comment by leehan0617** [comment]
my temporary solution is below code.. (I use jQuery)

after fullcalendar loading
```
$('.fc-slats tr .fc-time').html(function(){
		let parent = $(this).parent();
		parent = $(parent[0]).attr('data-time');
		sdt = parent.substr(0,5);
		let edt = "";
		let temp = parent.substr(3,2);
		
		if(temp == '00'){
			edt += parent.substr(0,3) + '30';
		}else{
			let timeValue = parent.substr(0,2);
			edt = Number(timeValue) + 1;
			if(edt < 10) edt = "0" + (Number(timeValue) + 1);
			edt += ":00";
		}
		
		return sdt + '~' + edt;
	});
```

better solution please.. thanks

**Comment by arshaw** [comment]
this issue has been requested in this other ticket:
https://github.com/fullcalendar/fullcalendar/issues/2887
&uarr;
Could you please visit the link, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates?

**Comment by leehan0617** [comment]
oh thanks. 
Height bug solution is below code..
```
$('.fc-slats tr .fc-time span').html(function(){
		let parent = $(this).parent().parent();
		parent = $(parent[0]).attr('data-time');
		let sdt = parent.substr(0,5);
		let edt = parent.substr(0,3) + '30';
		
		return sdt + '~' + edt;
	});
	
	$('.fc-minor .fc-time').html(function(){
		let parent = $(this).parent();
		parent = $(parent[0]).attr('data-time');
		let timeValue = parent.substr(0,2);
		let sdt = parent.substr(0,5);
		let edt = Number(timeValue) + 1;
		
		if(edt < 10) edt = "0" + (Number(timeValue) + 1);
		edt += ":00";
		return sdt + '~' + edt;
	});
	
	$('.fc-slats tr .fc-time').css({
		'text-align' : 'center',
	});
	
	$('.fc-minor').css({
		'font-size' : '15px'
	});
	
	$('.fc-slats tr .fc-time span').css({
		'font-size' : '15px'
	});
```

Reason of duplication code is className is different.
Now my best solution is this code..

**Comment by MiguelQueiroz** [comment]
Hello, i changed my copy to fit exactly something very similar. 

Because for the minutes i wanted to display a different format, and also a different CSS class.

so i did:

`   var axisHtml;
        var slotLabelFormat=this.opt('slotLabelFormat');
        var isMainHour;
        // Calculate the time for each slot
        while (slotTime < dateProfile.maxTime) {
            slotDate = calendar.msToUtcMoment(dateProfile.renderUnzonedRange.startMs).time(slotTime);
            isLabeled = util_1.isInt(util_1.divideDurationByDuration(slotIterator, this.labelInterval));
            
            isMainHour=slotDate.minutes() == 0;
            this.labelFormat=slotLabelFormat.length==2? (isMainHour?slotLabelFormat[0]:slotLabelFormat[1]):slotLabelFormat[0];
            axisHtml =
                '<td class="fc-axis fc-time ' + theme.getClass('widgetContent') + '" ' + view.axisStyleAttr() + '>' +
                    (isLabeled ?
                        '<span '+(isMainHour?"fc-time-main-hour":"fc-time-minor-hour")+'>' + // for matchCellWidths
                            util_1.htmlEscape(slotDate.format(this.labelFormat)) +
                            '</span>' :
                        '') +
                    '</td>';`

and then use  slotLabelFormat: ['H:mm',':mm'], 

but in your cause it would be  slotLabelFormat: ['HH:mm [~] HH:30','HH:30 [~] HH:mm'],
