### ISSUE TITLE
Firing dayClick event programmatically

### ISSUE THREAD

**Issue by plippard** [fullcalendar/fullcalendar#3500]
How can I programmatically fire a dayClick event ?

I have located the td tag with the appropriate data-date attribute content and then doing a $(element).trigger("click") .... but it is not firing.

Any ideas ?

**Comment by rubjo** [comment]
Trigger the click on the `a.fc-event` element?

**Comment by plippard** [comment]
There is not an event within the TD (.fc-day) tag at this point.... it is an empty day on which I need to programmatically click.

I welcome any other suggestions you may have.

PL

**Comment by rubjo** [comment]
Ah. I guesss you could just do `$('#calendar').fullCalendar('select', '2017-01-25')`

**Comment by plippard** [comment]
This did what I need.... provided I also have a select callback.  This is not equivalent to doing a trigger where the existing dayClick event is utilized... but it will suffice.

Thanks for your assistance.

You have an first class incredible product... however can I suggest that while your documentation is complete ... it has events, methods and options all thrown in a pile together... and it is quite painful to find what one is looking for.  Please consider reorganizing your documentation such that one can go to an alphabetical list of all methods... an alphabetical list of all events.... a list of all options...etc.   this would be quite helpful.

Again... thanks for the assistance.

**Comment by arshaw** [comment]
@plippard, i agree, i'm planning to reorganize the docs when time allows.

**Comment by C-E-Rios** [comment]
Is there a way to pass jsEvent to the select method with this approach?
