### ISSUE TITLE
rendering background not working in agenda week

### ISSUE THREAD

**Issue by dhrubo001** [fullcalendar/fullcalendar#3501]
I am trying to block a weekday in month  as well as in week view, it's working fine in month view but not greying out the date in week view.

$overlap =  false;
$rendering = 'background';
$color = '#ff9f89';
$allday = true;
$editable = false;

![month](https://cloud.githubusercontent.com/assets/7116995/22201988/13dff8a4-e18c-11e6-8e6f-abcd89121e79.png)
![week](https://cloud.githubusercontent.com/assets/7116995/22201993/1a302e36-e18c-11e6-92aa-b6dc29a34a27.png)

-How to grey out 2017-01-24 in agendaWeek view???

**Comment by arshaw** [comment]
Would you be able to post a [runnable, stripped-down demonstration of the bug](http://fullcalendar.io/wiki/Reduced-Test-Cases/)? Would really appreciate it because the time saved reproducing will be time spent fixing.
