### ISSUE TITLE
Set the month view row height with css

### ISSUE THREAD

**Issue by mtaylor456** [fullcalendar/fullcalendar#3505]
http://jsbin.com/lonopu/edit?html,css,js,output

I have the calendar as a sidebar set at width: 260px  and in fullcalendar set the height to 480px to avoid scrolling. How can I give the calendar a squarer appearance without scrolling?  I just want to reduce the row heights, but  

`.fc-row .fc-week .fc-widget-content { height: 20px }`

doesn't work, I guess it's because the calendar height is set dynamically at runtime?

I could fix this with jquery but wanted to check CSS first

**Comment by arshaw** [comment]
Sounds like an [aspectRatio](https://fullcalendar.io/docs/display/aspectRatio/) of `1` would solve your problem.

**Comment by mtaylor456** [comment]
Thanks @arshaw but setting aspectratio to 1 does nothing. I've updated the jsbin in my OP with the `aspectRatio: 1`. The calendar does a little adjustment during loading which would suggest that it is being overridden. I will put this on stackoverflow

**Comment by arshaw** [comment]
you need to remove your `height` declaration and then it should work.
