### ISSUE TITLE
Calling changeView on a hidden calendar leaves it in a bad state

### ISSUE THREAD

**Issue by ChlorideCull** [fullcalendar/fullcalendar#3506]
Calling changeView on a hidden calendar leaves it in a bad state - calendar view is missing and the title is incorrect.

----

Can be reproduced on [this JSBin](http://jsbin.com/xeyuxifebu/1/edit?js,output).

1. Click "Toggle calendar visibility" to hide the parent container of the calendar (to not interfere with it)
2. Click "Change calendar view to week" to call `.fullCalendar("changeView", "agendaWeek")`
3. Click "Toggle calendar visibility" to show the parent container of the calendar again
4. Notice that the calendar view is missing, and the calendar title will be showing the same string as it did in the default month view.

**Comment by arshaw** [comment]
if you call the render method right after you re-show it
https://fullcalendar.io/docs/display/render/

should solvve the problem

**Comment by ChlorideCull** [comment]
Ah, okay. It would be nice if the "won't render while not visible" behavior was documented somewhere though, unless I missed it. A "Quirks" section or something similar.
