### ISSUE TITLE
Responsive improvement for agendaWeek header 

### ISSUE THREAD

**Issue by frlinw** [fullcalendar/fullcalendar#3509]
In a responsive perspective, I wonder if it is possible to set the day of week and the related date in separate DOM elements to prevent this kind of thing with css :

![image](https://cloud.githubusercontent.com/assets/11896237/22401148/e4667d72-e5c9-11e6-9511-bb5e529e76c5.png)

**Comment by arshaw** [comment]
in your opinion, what would the best visual design be for when a screen gets really narrow?

FYI, you can use CSS `white-space:nowrap` to force everything on the same line, or to force a newline between the day-of-week and the date/month, you can introduce a `\n` into your format string for [columnFormat](https://fullcalendar.io/docs/text/columnFormat/).

**Comment by frlinw** [comment]
From this state
![image](https://cloud.githubusercontent.com/assets/11896237/22417112/cc8c0ff0-e6d2-11e6-8d60-f50a76b6bb0f.png)
To this state
![image](https://cloud.githubusercontent.com/assets/11896237/22417120/ddf5914e-e6d2-11e6-984e-57037f4e0d3e.png)
So avoid these non consistents states
![image](https://cloud.githubusercontent.com/assets/11896237/22417142/0b3378b0-e6d3-11e6-8f57-3897cf2a51d3.png)

I thought about day of week/date in separate span inline-block with a fixed width so headers will wrap at the same time. But like you said, we can customize the date format, so this idée is not relevant.
I didn't want to force a representation with white space no wrap and \n but I will think about it

**Comment by arshaw** [comment]
thanks for the suggestions.

**Comment by frlinw** [comment]
Suggestion: It can be like the list view with fc-list-header-main / fc-list-header-alt

**Comment by frlinw** [comment]
keep fullcalendar simple, a line break is probably the best way to handle it.
(Moreover, it's possible to style the first and second line differently thanks to `::first-line` pseudo element 
https://developer.mozilla.org/fr/docs/Web/CSS/::first-line)
