### ISSUE TITLE
Feature Request, listview next x days

### ISSUE THREAD

**Issue by NickSutton** [fullcalendar/fullcalendar#3510]
As per title, why show past days of the week in list view? Option to show next three, seven, etc days please!

**Comment by arshaw** [comment]
this other ticket will encompass a solution to your concern:
https://github.com/fullcalendar/fullcalendar/issues/3340
&uarr;
Could you please visit the link, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates?

**Comment by arshaw** [comment]
in combination with this feature request: https://github.com/fullcalendar/fullcalendar/issues/3105

I'm not exactly sure how i'll design the API to do it.
