### ISSUE TITLE
Selection Touch Support does not seens to work

### ISSUE THREAD

**Issue by githubdoramon** [fullcalendar/fullcalendar#3513]
Is there a way to check if touch support is really enabled? I am trying to change the longPressDelay but nothing happens... It stills select a date range on a simple swype.

**Comment by arshaw** [comment]
Would you be able to post a [runnable, stripped-down demonstration of the bug](http://fullcalendar.io/wiki/Reduced-Test-Cases/)? Would really appreciate it because the time saved reproducing will be time spent fixing.

**Comment by githubdoramon** [comment]
@arshaw When I was trying to create the script I found out the problem... for future references:

- I was using background events instead of businessHours for the businessHours
- On envetRender, i was using "element.addTouch()" on events
- Since there was several background events in the calendar, I guess that was breaking the ability to scroll

Changed to businessHours, all solved :)
