### ISSUE TITLE
excessive minTime/maxTime not reflected in event fetching

### ISSUE THREAD

**Issue by githubdoramon** [fullcalendar/fullcalendar#3514]
I am trying to make the calendar show the dates starting at 10am and ending at 2am. I was able to accomplish that by setting minTime to "10:00:00" and maxTime to "1.02:00:00".

But now I got problems rendering the events that starts after midnight. They don't get rendered at all. Also it is not possible to drag events to this part of the day, or show the selection placeholder when selecting the calendar (althoug the calendar returns the correct selected time).

Is there a way to correct render the events on this after midnight part?

Thanks

**Comment by espen** [comment]
AFAIK that is not supported in the day view. And your way of setting 2AM looks very hackish so I'm not surprised that it doesn't work.

The Scheduler does however have a [timeline view](https://fullcalendar.io/scheduler/) which can span over multiple days.

Another option is to [create a custom view](https://fullcalendar.io/docs/views/Custom_Views/) yourself.

**Comment by githubdoramon** [comment]
Just found that #3186 seems to work this out... Will make some tests with it

**Comment by githubdoramon** [comment]
I was able to do it with #3055 and had also to change the fetchEvents(start,end) function, adding 2 hours to the end time, so the calendar displays the events on the last day.

@arshaw Is there a better way to change the range date that events should be rendered other than changind the actual fetchEvents function?

**Comment by arshaw** [comment]
@githubdoramon , no, the core code would need to be modified.

i'm repurposing this ticket to deal with the problem you just brought up: the minTime/maxTime does not affect the start/end of fetching

**Comment by githubdoramon** [comment]
thx @arshaw ... I have modified the core based on some other tickets and got it to work with the events after midnight and fecthing correctly.

**Comment by arshaw** [comment]
This is implemented in **v3.3.0**
Blog post: https://fullcalendar.io/blog/2017/03/fullcalendar-33-and-scheduler-16/

When maxTime is beyond 24hrs or minTime is negative, the full accurate datetime is now sent to events function as well as events feed.
