### ISSUE TITLE
gotoDate should reorient if date already in view

### ISSUE THREAD

**Issue by arshaw** [fullcalendar/fullcalendar#3515]
If a custom-view has multiple days (4-day view for example), and `gotoDate` is called on a date that is already visible, but not the first date, nothing will happen.

DESIRED: the calendar's view will rerender with the given date as the first date.

Requested by Heidi Haverlock and others.

**Comment by arshaw** [comment]
This is the new behavior in **v3.3.0**
Blog post: https://fullcalendar.io/blog/2017/03/fullcalendar-33-and-scheduler-16/

If the view is a Custom View specified with a number of days, and gotoDate is called, the view will rerender with the given date as the new beginning.

**Comment by kilroy05** [comment]
I seem to have this exact issue with version 4.1...
Using it in a react app (before the react version was available) with my own implementation.
Wondering if this is my implementation that's wrong or if this functionality was lost...
In short, if I 'gotoDate' but the day is already visible, nothing happens...

**Comment by acerix** [comment]
There is a new issue for this:
https://github.com/fullcalendar/fullcalendar-scheduler/issues/532
↑
Could you please visit the link, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates?

I didn't realize that functionality was already implemented (in this issue), so I just updated the other issue to indicate it's not a feature request but a regression.
