### ISSUE TITLE
Rendering failed on events without title

### ISSUE THREAD

**Issue by hidingmode** [fullcalendar/fullcalendar#3517]
Referring to [http://plnkr.co/edit/tkK8rk?p=preview](http://plnkr.co/edit/tkK8rk?p=preview) from #2678
I realised it fails rendering a month that has an event without a title on the google calendar.

Stack trace using the non minified version:
![image](https://cloud.githubusercontent.com/assets/7817101/22769707/65366242-eec5-11e6-9181-13fb92366f63.png)

So when an event doesnt have title, the htmlEscape function param becomes undefined which is throwing the exception.

**Comment by arshaw** [comment]
looks like you are using a pretty old version of fullcalendar. i'm nearly certain this problem is now fixed. can you upgrade and try again?
