### ISSUE TITLE
Setting Time brakes automatic all-day calculation

### ISSUE THREAD

**Issue by trsh** [fullcalendar/fullcalendar#3520]
### Bug Reports
https://jsfiddle.net/sf11633n/4/

If I specify Time for Long Event (star, end), the all-day automatic calculation is broken in week view and instead I have large event boxes even for the days in middle, that are fully filled.

**Comment by arshaw** [comment]
the event has a time, which causes it to show up in the slots on the lower half of the calendar, NOT on the all-day slots. this behavior is as-designed.

i think you might be requesting the ability to do this:
https://github.com/fullcalendar/fullcalendar/issues/440
&uarr;
Could you please visit the link, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates?

**Comment by trsh** [comment]
OK! Yes!
