### ISSUE TITLE
select callback fired immediately upon touch on Windows 10

### ISSUE THREAD

**Issue by mattlacey** [fullcalendar/fullcalendar#3523]
Minimal reproduction:
http://codepen.io/pen/ygQBQe

The above demonstration shows an alert box with the selected start time when the start callback is called by fullcalendar. On Safari on an iOS device this works as expected and the selection only occurs after a one second delay. Using a touch screen with Edge on Windows 10, the callback is triggered immediately without the delay.

Expected result:
On a Windows 10 touch device, the select event should respect the delays specified/defaulted for touch events.

**Comment by mattlacey** [comment]
After digging through the code and finding how events are tested for touch, it seems as though Edge is sending mouse events for touches. Is there a way to fix this via some CSS flag or similar, or perhaps have a mode that forces all events to touch?

**Comment by arshaw** [comment]
Hi @mattlacey , thanks for the report. I have yet to confirm this. I still need to get ahold of a Windows+Edge VM.

Would you mind trying this on the latest version: [v3.2.0](https://github.com/fullcalendar/fullcalendar/releases/tag/v3.2.0) ?

I made some touch improvements in there
