### ISSUE TITLE
Parent resource length based on children values in scheduler view

### ISSUE THREAD

**Issue by fr1sty** [fullcalendar/fullcalendar#3524]
In the scheduler view https://fullcalendar.io/js/fullcalendar-scheduler-1.5.0/demos/scale.html
i would like to hava an option to display the total length of all the children in the parent row. 
At this moment there seems to be no relation in time between the parent and children. 

Something like this:
![example](https://cloud.githubusercontent.com/assets/3081677/22881348/5004af4a-f1e6-11e6-8938-d14badb4d156.jpg)

**Comment by arshaw** [comment]
Thanks @fr1sty . There is another feature request for this already:
https://github.com/fullcalendar/fullcalendar-scheduler/issues/95
&uarr;
Could you please visit the link, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates?
