### ISSUE TITLE
Error installing package using composer

### ISSUE THREAD

**Issue by BBrunekreeft** [fullcalendar/fullcalendar#3526]
Composer gives the following error while installing:
```
[UnexpectedValueException]
Could not parse version constraint >=~2: Invalid version string "~2"
```

I used the following commands in an empty folder:
```
composer clearcache
composer require bower-asset/fullcalendar
```
That produces the "Cold not parse version constraint" message.
My composer version is: `Composer version 1.3.2 2017-01-27 18:23:41`

**Comment by steffendietz** [comment]
That's odd. We are having the same issue, despite using a rather ancient version of fullcalendar.
```json
"require": {
    "bower-asset/fullcalendar": "^1.6.7",
}
```

**Comment by steffendietz** [comment]
There is also a corresponding issue at the `composer-asset-plugin` project: https://github.com/fxpio/composer-asset-plugin/issues/270

**Comment by marcomenzel** [comment]
So this is more an issue in fxp/composer-asset-plugin than in fullcalendar.

**Comment by steffendietz** [comment]
It seems like that. Yes.

**Comment by arshaw** [comment]
Yes, this problem is outside of the core project's responsibility. Seems like a bugfix is in-progress: https://github.com/fxpio/composer-asset-plugin/issues/270

The workaround is to hardcode a lower version of yii2fullcalendar (or fullcalendar?), though I am not expert on Composer, so can't say for sure.

**Comment by francoispluchino** [comment]
@arshaw I confirm that it's a bug of my plugin.

**Comment by arshaw** [comment]
@francoispluchino, looks like [you fixed it](https://github.com/fxpio/composer-asset-plugin/commit/623fe6b9bb28fa23b64efc208d53d6d3fcf84170) ?

Are there any instructions that people need to follow to fix their stuff? Upgrade to a higher version of your plugin (sorry, I am not familiar with your Composer plugin).

**Comment by francoispluchino** [comment]
To update the plugin on the current branch of dev:

```
$ composer global require fxp/composer-asset-plugin:~1.3@dev
```

The stable version will arrive coming soon, see the [1.3.0 milestone](https://github.com/fxpio/composer-asset-plugin/milestone/12).

@arshaw You can close your issue, thanks.
