### ISSUE TITLE
colorize days with no events in fullcalendar 

### ISSUE THREAD

**Issue by MangeshK3007** [fullcalendar/fullcalendar#3527]
I want to set color to those days which has no events into the database. so is there any way to set the color of days with no event when fullCalendar is load?

**Comment by arshaw** [comment]
I've found an existing ticket that fits your description. I've made a note to support a className for when there are NO events:
[CSS class for days w/ events over them](https://github.com/fullcalendar/fullcalendar/issues/345)
&uarr;
Could you please visit the link, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates?
