### ISSUE TITLE
Error when installing via Composer

### ISSUE THREAD

**Issue by p2made** [fullcalendar/fullcalendar#3531]
In the last 36 hours Composer has started throwing an error when updating projects that have fullcalendar as a dependancy (or, like mine, as a dependancy of a dependancy)...

```
[UnexpectedValueException]                                            
  Could not parse version constraint >=~2: Invalid version string "~2"
```

That is, somewhere in the dependancy chain, something declares the impossible version constraint `>=~2`.

I have examined the `bower.json` of fullcalendar & cannot find this invalid version constraint there, so I expect it lies somewhere in the dependancies of fullcalendar's dependancies.

I do hope you won't respond by simply saying you don't support Composer as Composer quite happily installs Bower packages.

**Comment by arshaw** [comment]
could you please follow the discussion here?
https://github.com/fullcalendar/fullcalendar/issues/3526
&uarr;
Could you please visit the link, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates?

**Comment by p2made** [comment]
Have done, & thank you.
