### ISSUE TITLE
Drag and Drop iOS scrolling (in iframe lightbox)

### ISSUE THREAD

**Issue by captain-planet** [fullcalendar/fullcalendar#3533]
This bug appends onto this previously closed bug: https://github.com/fullcalendar/fullcalendar/issues/3403#issuecomment-280250857

A partial fiddle of the lightbox I am using is here: 
https://jsfiddle.net/c33xf3n0/

The fiddle is partial because instead of loading https://learn.jquery.com/using-jquery-core/document-ready/, i really need to load a sample page (with vertical scrolling like the example), that contains the fullcalendar plugin with events.  However I have nowhere to host it (other than my live site, which I cannot share right now).

The problem:
When dragging and dropping on iOS **in the page loaded within the lightbox (which is an iframe, and has vertical scrolling)** the lightbox iframe page scrolls along with the drag motion, making it impossible to drag an event from one week to another in the week view.

Please note that this works fine on android and on desktops.

**Comment by arshaw** [comment]
hi @captain-planet can you change the fiddle to load this page ? https://fullcalendar.io/js/fullcalendar-scheduler-1.5.1/demos/simple.html

**Comment by captain-planet** [comment]
yep sure - https://jsfiddle.net/c33xf3n0/1/

However the example I was referring to was when i was **creating** events.  I don't think the page you provided allows you to create events (by holding down on the phone).

**Comment by arshaw** [comment]
If that's the case, can you somehow get that demo into your iframe? I want to be able to reproduce this instantly without having to do any additional work.
