### ISSUE TITLE
Once removed Event Sources ,there is no effect use addEventSource function

### ISSUE THREAD

**Issue by little-sean** [fullcalendar/fullcalendar#3535]
<!DOCTYPE html>
<html>
<head>
<meta charset='utf-8' />
<link href='../dist/fullcalendar.css' rel='stylesheet' />
<link href='../dist/fullcalendar.print.css' rel='stylesheet' media='print' />
<script src='moment.min.js'></script>
<script src='http://apps.bdimg.com/libs/jquery/2.1.4/jquery.min.js'></script>
<script src='https://fullcalendar.io/js/fullcalendar-3.2.0/fullcalendar.min.js'></script>

<style>

	body {
		margin: 40px 10px;
		padding: 0;
		font-family: "Lucida Grande",Helvetica,Arial,Verdana,sans-serif;
		font-size: 14px;
	}

	#calendar {
		max-width: 900px;
		margin: 0 auto;
	}

</style>
</head>
<body>

	<div id='calendar'></div>
	<script>
	// click next button ,and then click next button. and then click prev button
	// when removeEventSources once. then addEventSource. function $calendar.fullCalendar("getEventSources") can not get Event Sources. is a empty array.
	var eventData = [
		{
			title: 'All Day Event22',
			start: '2017-02-01'
		},
		{
			title: 'Long Event22',
			start: '2017-02-07',
			end: '2017-02-10'
		},
		{
			id: 999,
			title: 'Repeating Event22',
			start: '2017-02-09T16:00:00'
		},
		{
			title: 'All Day Event22',
			start: '2017-02-28'
		},
		{
			title: 'All Day Event22',
			start: '2017-03-02'
		}
	];

	var eventData2 = [
		{
			title: 'All Day Event333',
			start: '2017-03-01'
		},
		{
			title: 'Long Event333',
			start: '2017-03-17',
			end: '2017-03-10'
		},
		{
			id: 997,
			title: 'Repeating Event333',
			start: '2017-03-19T16:00:00'
		},
		{
			id: 996,
			title: 'Repeating Event333',
			start: '2017-03-26T16:00:00'
		},
		{
			title: 'Conference333',
			start: '2017-03-21',
			end: '2017-03-23'
		},
		{
			title: 'Meeting333',
			start: '2017-03-31T10:30:00',
			end: '2017-03-31T12:30:00'
		},
		{
			title: 'Conference333',
			start: '2017-04-01',
			end: '2017-04-01'
		}
	];

	var eventData3 = [
		{
			title: 'All Day Event444',
			start: '2017-04-01'
		},
		{
			title: 'Long Event444',
			start: '2017-04-17',
			end: '2017-04-10'
		},
		{
			id: 999,
			title: 'Repeating Event444',
			start: '2017-04-19T16:00:00'
		},
		{
			id: 999,
			title: 'Repeating Event444',
			start: '2017-04-26T16:00:00'
		},
		{
			title: 'Conference444',
			start: '2017-04-21',
			end: '2017-04-23'
		},
		{
			title: 'Meeting444',
			start: '2017-04-30T10:30:00',
			end: '2017-04-30T12:30:00'
		}
	];

	var time = 1;

	var $calendar = $('#calendar');

	$calendar.fullCalendar({
		header: {
			left: 'prev,next today',
			center: 'title',
			right: 'month,basicWeek,basicDay'
		},
		defaultDate: '2017-02-12',
		navLinks: true,
		editable: true,
		eventLimit: true,
		eventRender: function(event, el) {
			console.log("eventRender");

		},
		// events: eventData,
		viewRender: function(view) {
			//

			console.log("viewRender");

			if(time === 1) {
				$calendar.fullCalendar("addEventSource", eventData);
				console.log($calendar.fullCalendar("getEventSources")); // right

			}

			if(time === 2) {
				$calendar.fullCalendar("addEventSource", eventData2);
				console.log($calendar.fullCalendar("getEventSources")); // why is a empty array? 

			}

			if(time === 3) {
				$calendar.fullCalendar("addEventSource", eventData3);
				console.log($calendar.fullCalendar("getEventSources"))
				time = time -2;
			}

			time++;

		},
		dayRender: function() {
			console.log("dayRender");
		},
		eventDestroy: function() {
			console.log("eventDestroy");
			$calendar.fullCalendar("removeEventSources");
		}
	});

	</script>
</body>
</html>

**Comment by criztovyl** [comment]
Please don't simply paste your code but rather provide a [Reduced Test Case](https://fullcalendar.io/wiki/Reduced-Test-Cases/). Thank you :)
