### ISSUE TITLE
hello i am using full calendar it is really nice plugin for EMS but i am suffering from one issue i have created one event  when i am going to week view and then if i drag that event and drop it on the time slot under week view i am getting event.end is null under the evntDrop function please let me help if any one have the solution 

### ISSUE THREAD

**Issue by pateldipak** [fullcalendar/fullcalendar#3536]
### Bug Reports
You MUST have a JSBin recreation, or else your issue will be CLOSED without explanation.
Instructions: http://fullcalendar.io/wiki/Reporting-Bugs/

### Feature Requests
Search the issue tracker for an existing ticket before creating a new one.
Instructions: http://fullcalendar.io/wiki/Requesting-Features/

(Please erase the above text and begin typing. Thanks!)

**Comment by criztovyl** [comment]
Move details from title to description, it's unreadable if everything is in the title.

**Comment by pateldipak** [comment]
hello i am using full calendar it is really nice plugin for EMS but i am suffering from one issue i have created one event  when i am going to week view and then if i drag that event and drop it on the time slot under week view i am getting event.end is null under the evntDrop function please let me help if any one have the solution

**Comment by criztovyl** [comment]
event.end is null when the stored date is invalid, see https://github.com/fullcalendar/fullcalendar/issues/2655#issuecomment-223838926
Maybe check whether the end date is valid.
