### ISSUE TITLE
Time in resource group divider

### ISSUE THREAD

**Issue by VSpock** [fullcalendar/fullcalendar#3537]
A little bit like the sticky header from https://github.com/fullcalendar/fullcalendar/issues/3473 but for fullcalender in mode "height: 'auto'" it would be nice to have the possibility to add the timeslotLabels inside the resource group divider. Helps while scrolling down when there are a lot of resources.

![grouping with-time](https://cloud.githubusercontent.com/assets/5154794/23067220/87162046-f51e-11e6-8bf9-62a6a3eafe83.png)

Or would this be possible somehow with resourceGroupField and resourceGroupText?

**Comment by arshaw** [comment]
@VSpock would you mind moving this to the fullcalendar-scheduler issue tracker?
https://github.com/fullcalendar/fullcalendar-scheduler/issues

**Comment by VSpock** [comment]
Sure thing :)
