### ISSUE TITLE
Deselection of dates not working

### ISSUE THREAD

**Issue by dominic333** [fullcalendar/fullcalendar#3545]
[http://jsfiddle.net/iamsajeev/932ynzsc/](http://jsfiddle.net/iamsajeev/932ynzsc/)

I'm trying to select multiple (future) dates and when user selects them, these dates are pushed into an array. That part works. (:

But I'm trying to deselect the selected dates which is not happening so I can pop the elements from the array unselect method is not working.

How to fix this? Is there a workaround?

```
var today = $('#calendar').fullCalendar('getDate');
$('#calendar').fullCalendar({
  defaultDate: today,
  header: {
    left: 'prev,next today',
    center: 'title',
    right: 'month'
  },
  defaultView: 'month',
  events: [],
  selectable: true,
  select: function(start, end, jsEvent, view) {
    if (moment().diff(start, 'days') > 0) {
      $('#calendar').fullCalendar('unselect');
      // or display some sort of alert
      return false;
    }
     
    var date = $('#calendar').fullCalendar('getDate');

    $("#calendar").fullCalendar('addEventSource', [{
      start: start,
      end: end,
      rendering: 'background',
      block: true,
    }, ]);
    $("#calendar").fullCalendar("unselect");


  },
  selectOverlap: function(event) {
    return !event.block;
  }
});
```

**Comment by arshaw** [comment]
Really? It's correctly deselecting the blue selection for me, for either case.

It's leaving behind the green background event, which seems intentional.

Could you post a video or something? I'm having trouble understanding the bug.

**Comment by NamedPython** [comment]
Hello, I'm in similar trouble. 
I recorded a video and took some screenshots.  Check please.
Sorry for terrible english. 

https://youtu.be/F8cbJZ6n-pE
![elements](https://cloud.githubusercontent.com/assets/7601339/25386930/fd8b8012-2a03-11e7-9bee-e2da90558ab8.png)

**Comment by arshaw** [comment]
@NamedPython are you using [unselectAuto](https://fullcalendar.io/docs/selection/unselectAuto/) ?

Could you try to make a [Reduced Test Case](https://fullcalendar.io/wiki/Reduced-Test-Cases/)

**Comment by NamedPython** [comment]
@arshaw Thank you for replying. I set it 'false' because when user clicks text fields, selected event will be unselected.
OK, thanks. I'll try that.

**Comment by akashGR** [comment]
I have the same issue as @dominic333, but can't seem to find a solution. I am very new to this framework (started today). I tried the solutions discussed above, but those too do not work.
