### ISSUE TITLE
Composer halt using bower dependency

### ISSUE THREAD

**Issue by bhagwatchouhan** [fullcalendar/fullcalendar#3546]
Notes: JSBin or JSFiddle does not support composer.json hence pasting the stripped version of composer.json having faulty code within this section.

**Code**:
`{
        "name": "test/test",
	"description": "test",
	"type": "project",
	"minimum-stability": "stable",
    "require": {
        "yiisoft/yii2": "2.0.11",
	"bower-asset/fullcalendar": "3.2.*"
    },
    "require-dev": {
        "yiisoft/yii2-debug": "2.0.*",
        "yiisoft/yii2-gii": "2.0.*",
        "yiisoft/yii2-faker": "2.0.*"
    },
    "extra": {
        "asset-installer-paths": {
            "npm-asset-library": "vendor/npm",
            "bower-asset-library": "vendor/bower"
        }
    }
}`

**Expected Results**: Composer should install the bower asset.

**Actual Result**:
When we run composer update command, it shows below mentioned error and the execution halts:

  [UnexpectedValueException]                                            
  Could not parse version constraint >=~2: Invalid version string "~2"

**Comment by bhagwatchouhan** [comment]
It was working fine till last month and downloading fullcalendar dependency without any issue.

**Comment by arshaw** [comment]
please see the discussion here: https://github.com/fullcalendar/fullcalendar/issues/3526
last comment offers a workaround until a new version is released.

**Comment by bhagwatchouhan** [comment]
@arshaw Thanks for reply. I will follow the workaround as mentioned in 3526.
