### ISSUE TITLE
Feature request : optionnal 'event' parameter to 'select' method

### ISSUE THREAD

**Issue by artem-tim** [fullcalendar/fullcalendar#3547]
Hello,
Feature request :
I would like to suggest a simple feature consisting in adding a 'event' parameter to the 'select' method, which would set the jsEvent parameter of the 'select' callback instead of setting it to 'undefined' (this would still remain the default option if no event explicitly passed).

Context :
My usecase is the implementation of keyboard controls to navigate the selection on the calendar without the mouse (I use only one day at once so it's a very simple keypress switch which fires 'select' method depending on key pressed). Problem is, I would like to parametrize the behavior depending on key pressed (for example Enter for some action and arrows for simple selection navigation). Therefore I would like to avoid ugly hacks, such as saving the pressed key in some global, when a pretty solution appears to be within the reach of few lines of code

**Comment by arshaw** [comment]
I see what you mean. Would need to think about that ideal API for this, or if we should allow for this at all.

FWIW, here's a ticket on keyboard drag-n-drop: https://github.com/fullcalendar/fullcalendar/issues/2535

**Comment by artem-tim** [comment]
Yes, I have seen this ticket when I searched for similar issues. I think the keyboard controls implementation itself is something very specific so it should be left to users, I only mentioned it for the context. But for that to be possible, the event handling chain requires some additional flexibility, such as the one I suggest. It's about not loosing useful data on the way to the callback.
Thank you!

**Comment by arshaw** [comment]
there doesn't seem to be enough demand to implement this feature but if more people request it, i'll reopen
