### ISSUE TITLE
dayClick not fired when a selection is set

### ISSUE THREAD

**Issue by RiccardoB** [fullcalendar/fullcalendar#3549]
I need to execute the dayClick function even when a range of dates is selected, but it looks like that dayClick event is fired only when a selection is not set.

Here an example for test:
```javascript
$('#calendar').fullCalendar({
	dayClick: function(date, jsEvent, view){
		console.log('dayClick');
		$('#calendar').fullCalendar('select', date);
	}
});
```
and another to explain it clearer:
```javascript
$('#calendar').fullCalendar({
	unselectAuto: false,
	dayClick: function(date, jsEvent, view){
		console.log('dayClick');
		$('#calendar').fullCalendar('unselect');
		$('#calendar').fullCalendar('select', date);
	}
});
```

**Comment by arshaw** [comment]
why not just use the [select callback](https://fullcalendar.io/docs/selection/select_callback/) to know when a selection is made?

**Comment by RiccardoB** [comment]
Using "select" you can choose any amount of days/hours, is it possible to limit the selection to just a day like dayClick (or disable the dragging effect)?

**Comment by arshaw** [comment]
yes, of you call select with a single argument, an [ambiguously-timed moment](https://fullcalendar.io/docs/utilities/Moment/#ambiguously-timed) and do not provide an end time, you should get what you want.
