### ISSUE TITLE
Bug refetchEvent and refetchEventSources

### ISSUE THREAD

**Issue by tro69** [fullcalendar/fullcalendar#3551]
Public demonstration of the bug: https://output.jsbin.com/puhisefido/
When I change the selection of "eventSelect" select, it always sends this post request:

> POST: http://example.com/events.php
end: 2017-02-25
start: 2017-02-20
state: all

Why doesn't the "state" variable change its value?

**Comment by tro69** [comment]
@arshaw Are those bugs?

**Comment by arshaw** [comment]
because your `data` is only evaluated once in your code.

you can make it dynamic:
https://fullcalendar.io/docs/event_data/events_json_feed/
see "Dynamic data parameter"
