### ISSUE TITLE
Error on Dragging/Dropping event FullCalendar

### ISSUE THREAD

**Issue by vpacheco2000-mahisoft** [fullcalendar/fullcalendar#3554]
Hello I am implement drag and drop feature which is available in fullcalendar. It is working but when i'm try drag from event on fifth week on month view not work a send this message.

here error:
fullcalendar.min.js:7 
Uncaught TypeError: Cannot read property 'component' of undefined
    at constructor.hitOver (fullcalendar.min.js:7)
    at constructor.trigger (fullcalendar.min.js:7)
    at constructor.handleHitOver (fullcalendar.min.js:7)
    at constructor.handleDrag (fullcalendar.min.js:7)
    at constructor.handleMove (fullcalendar.min.js:7)
    at constructor.handleMouseMove (fullcalendar.min.js:7)
    at HTMLDocument.proxy (jquery.min.js:548)
    at HTMLDocument.dispatch (jquery.min.js:4670)
    at HTMLDocument.elemData.handle (jquery.min.js:4338)

**Comment by arshaw** [comment]
Would you be able to post a [runnable, stripped-down demonstration of the bug](http://fullcalendar.io/wiki/Reduced-Test-Cases/)? Would really appreciate it because the time saved reproducing will be time spent fixing.

**Comment by sivajisanapala** [comment]
hi @vpacheco2000-mahisoft ,
Even I came across the same in recent time, thought something related to JS but absolutely no.
Give calendar " .fc-view > table"  the `overflow:auto` property it will work for it.

**Comment by themightystephen** [comment]
I have encountered exactly the same error and had similar problems of not being able to drop events into the last few days of the month. 

So far when testing, it appears it might be related to how tall the calendar is and whether scrolling is required to see the whole thing. Setting a smaller max-width CSS property on my calendar div (along with setting a sensible aspect ratio) at least masks the issue for me.

**Comment by fabio-a-beretta** [comment]
I have got the same issue. I tried to add the overflow: auto; but it did not work. Need help to find a workaround.

**Comment by olivia-chen** [comment]
I added this piece of code to css file and the issued solved:
body .fc {
  overflow:auto;
}

**Comment by olivia-chen** [comment]
I added this piece of code to css file and the issued solved:
body .fc {
  overflow:auto;
}

**Comment by olivia-chen** [comment]
I added this piece of code to css file and the issued solved:
body .fc {
  overflow:auto;
}

**Comment by olivia-chen** [comment]
I added this piece of code to css file and the issued solved:
body .fc {
overflow:auto;
}

**Comment by imegory** [comment]
The above-suggested comment by Olivia Chen works well for me. Thank you.

**Comment by mariohmol** [comment]
This is happening with me just with dev cools open (seems to be related with height of the view)
