### ISSUE TITLE
Before and after selecting

### ISSUE THREAD

**Issue by a-jahanshahlo** [fullcalendar/fullcalendar#3555]
Hi, thank you for your product .
Please tell me fullcalendar has event like "before selecting" or "after selecting"?
I want when user begin selecting in other month or future then automatically selecting process cancel.
In fact i want to know user select other month? or current month?!.

**Comment by arshaw** [comment]
there is the [select callback](https://fullcalendar.io/docs/selection/select_callback/) but no other callbacks like you describe.

i'm having trouble understanding the usecase.

you might want to look at this. it allows/prevents selection on certain ranges and give you complete control:
https://fullcalendar.io/docs/selection/selectAllow/

**Comment by unknown4unnamed** [comment]
@arshaw Hi, I have some trouble wit `selectAllow` callback.
In my fullCalendar config `timezone` prop is set to `local` and when I'm trying to `console.log(selectInfo)` within `selectAllow` I get wrong start and end time. But inside `select` callback these values are correct.
Here is an example:
<img width="469" alt="screen shot 2017-03-16 at 4 35 46 pm" src="https://cloud.githubusercontent.com/assets/11380325/24001418/bf754f72-0a66-11e7-9752-2208af643f86.png">

Please tell me why this happens. Thanks.
