### ISSUE TITLE
[v3.2] computed height on chrome for android 

### ISSUE THREAD

**Issue by frlinw** [fullcalendar/fullcalendar#3556]
First of all, thanks for the scrollbar fix on 3.2!

Now, with `height: 'parent'` the computed height seems to be too high (even if you jump between differents views)
It's not easy to reproduce considered that it happens if you have a PWA on chrome for android (56).
This issue doesn't seem to exist on chrome itself nor on device emulation in chrome desktop.
![fullcalendar-scrollbar-issue](https://cloud.githubusercontent.com/assets/11896237/23370897/7c92ffb8-fd16-11e6-9bf8-47cbdec9ccf4.png)

**Comment by arshaw** [comment]
i have a feeling this is happening due to the sticky toolbar at the top of the screen. If you try initializing after a setTimeout of about a second, way after the header toolbar has initialized, does it still happen. might also be due to wrapping of some sort. could you please try to post a demo?

**Comment by frlinw** [comment]
fullcalendar container got `height: calc(100vh - 64px)` so it's not affected by others elements in the page
Weird thing is that it's perfectly fine in the browser itself but if you have a PWA (ie. a manifest.json with `display: 'fullscreen'`) the computed height on `fc-scroller` has an extra 20px (even if resize is trigger). And there is no way to create a PWA test case in jsbin-like site.
The issue appeared since Chrome 56 (and fullcalendar 3.2 but I didn't see any changes related to this thing) before that everything was ok.
I will update if I find something...

**Comment by frlinw** [comment]
It's related to Blink, issue opened in chromium bugs report
