### ISSUE TITLE
Prevent an immediate new selection?

### ISSUE THREAD

**Issue by adamhartford** [fullcalendar/fullcalendar#3558]
Hi, I noticed this recent change to Grid.js (dayMouseDown and dayTouchStart):

```js
// prevent a user's clickaway for unselecting a range or an event from
// causing a dayClick or starting an immediate new selection.
if (view.isSelected || view.selectedEvent) {
    return;
}
```

What is the rationale behind this change? I preferred the old behavior, but I wonder if that's because of my specific use case and maybe I'm in the minority? Is it worth making this behavior opt in/out?

Thanks!

**Comment by arshaw** [comment]
So, you want to start an "immediate new selection" after one is already made.

Yes, that was the old behavior. There is a behavior change that I neglected to mention in the changelog.

This change was part of a refactor to make touch selection better. I forget the exact details, but this behavior was better for touch devices.

I'll audit this in time for next release. Might change it.

**Comment by arshaw** [comment]
I reverted back to the previous behavior **v3.3.0**
Blog post: https://fullcalendar.io/blog/2017/03/fullcalendar-33-and-scheduler-16/

Please let me know if it's satisfactory.
