### ISSUE TITLE
scroll up not working while dragging as one of the box beome long.

### ISSUE THREAD

**Issue by Sandip9021** [fullcalendar/fullcalendar#3559]
Hi,

I am using fullcalendar@3.0.1, and I am getting events in list order. 

![image](https://cloud.githubusercontent.com/assets/17237067/23393565/c2b99ad6-fda9-11e6-908e-53a021e2549b.png)

But below is the way(2nd pic) , I want in my application. Means  (+2 more , like this).

How to enable that ??. Do I have to change my version to reflect it automatically.

**Comment by Sandip9021** [comment]
can I get a help in this ???

**Comment by tro69** [comment]
[eventLimit](https://fullcalendar.io/docs/display/eventLimit/)

**Comment by Sandip9021** [comment]
thanks @tro69  , it is really helpful...
