### ISSUE TITLE
Have future "now" date trigger today button enable/disable

### ISSUE THREAD

**Issue by thadin** [fullcalendar/fullcalendar#3560]
After midnight a new date starts, but the today button in the header is still disabled.

We already call `$('#calendar').fullCalendar('refetchEvents');` periodically to get an up-to-date calendar, this doesn't trigger the `updateToolbarsTodayButton` function (likely because the `currentView` didn't change).
Would it be possible to always call the `updateToolbarsTodayButton` function on re-render or expose the function so we could call it in our script?

**Comment by arshaw** [comment]
thanks for the request. it would be nice to have the internal timer update the today button

**Comment by thadin** [comment]
It looks like a similar issue has been created in the meantime: #3783.
We might want to link these issues seeing they'll fix the same problem.

The quoted code in my initial description has become outdated after several refactors of this library. The check currently lives in a function called `updateToolbarButtons`.

About a possible solution; maybe setting a `midnightTimeoutID` on initial load and just call `renderView` right after midnight? This might run additional code that hurts the performance, but it'll only run once a day.

**Comment by arshaw** [comment]
yes, same as
https://github.com/fullcalendar/fullcalendar/issues/3783
&uarr;
Could you please visit the link, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates?
