### ISSUE TITLE
event start or end time may be decremented when use snapDuration

### ISSUE THREAD

**Issue by pubron** [fullcalendar/fullcalendar#3563]
Hi, thank you for your product 

When selecting a range,
The event start time or end time value may be decremented with a combination of specific parameters.
It is probably due to the combination of snapDuration and minTime.

[An example is shown in codepen](https://codepen.io/pubron/pen/EWPywP)

Somehow It does not happen after 3:00

If it does not happen, try drag & drop several times.

**Comment by pubron** [comment]
workaround ...not a good method.

1. add following code to function of "formatRange" in fullcalenadar.js

```
var mySlotDuration = 10;

if(date1.valueOf() % mySlotDuration != 0) {
  date1.add(1, 's');
}

if(date2.valueOf() % mySlotDuration != 0) {
  date2.add(1, 's');
}
```

2. add following code to function of "select" when call fullcalenadar.js

```
var mySlotDuration = 10;

if(start.valueOf() % mySlotDuration != 0) {
  start.add(1, 's');
}
if(end.valueOf() % mySlotDuration != 0) {
  end.add(1, 's');
}
```

**Comment by arshaw** [comment]
reproduced. thanks.

probably related to this: https://github.com/fullcalendar/fullcalendar/issues/2786

**Comment by arshaw** [comment]
could you please try this in v5 and see if it still exists?
