### ISSUE TITLE
eventClick not firing on iPad (Chrome nor Safari)

### ISSUE THREAD

**Issue by blaur** [fullcalendar/fullcalendar#3567]
Hi guys,

I have a bit of a problem you might be able to assist with. I'm using fullcalendar (2.0.3, i know an older version) together with Ember.

my dayClick events are working fine but no eventClicks are fired when opening the website on my iPad in chrome or safari. No errors are thrown and therefore something simply seems to ignore the events.

Following has been configured (which works perfectly fine on desktop):
```
<div class="box-body no-padding">
  <!-- THE CALENDAR -->
                      {{
                      fullcalendar-component
                      dayClick='createEvent'
                      eventClick='eventClick'
                      eventMouseover='eventClick'
                      eventDragStart='dragStart'
                      eventDragStop='dragStop'
                      events=events
                      eventResize='eventResize'
                      defaultView = 'agendaWeek'
                      headerLeft = 'today, prev,next'
                      headerCenter = ''
                      headerRight = 'agendaDay,agendaWeek,month'
                      allDayDefault = false
                      editable = true
                      lazyFetching = true
                      handleWindowResize = true
                      }}
                    </div>
```

And of course the equivalent methods are defined in the corresponding controller: 

```
eventClick: function (event, jsEvent, view) {
      if (event.id) {
        this.setSelectedDetail(event.id);
      }
    }, 
```

Any idea if I have to do something special to turn on touch?

Looking forward to your answers.

**Comment by spikeon** [comment]
I am also seeing this on my iPhone.

**Comment by spikeon** [comment]
I just updated to 3.2.0 and I am still having this issue.  

I'm using all-day events with custom classes to shade days in the calendar, and that is also working on desktop chrome, not working in mobile chrome or safari.  It is also not working in normal Safari.

A link to the running site is below.

http://englishlessonhub.com/teacher.php?id=50

**Comment by spikeon** [comment]
Update: It's also not working in Microsoft Edge

**Comment by arshaw** [comment]
what's with the `{{ fullcalendar-component` code?

Would you be able to post a [runnable, stripped-down demonstration of the bug](http://fullcalendar.io/wiki/Reduced-Test-Cases/)?

**Comment by spikeon** [comment]
@arshaw - have you been able to see the bug occurring on my instance?  I have a client on my ass so I have developed my own calendar to do what I need it to do - only all day events and clicking on them runs a function - and am going to be removing full calendar and implementing my own soon, I want to make sure I'm not removing a resource you need to fix this bug.

**Comment by arshaw** [comment]
Would you be able to post a [runnable, stripped-down demonstration of the bug](http://fullcalendar.io/wiki/Reduced-Test-Cases/)?

**Comment by evanjmg** [comment]
+1 same issue - when I have time I'll create pen

**Comment by evanjmg** [comment]
@arshaw reproducible demo - just try clicking +3more on your home page. Doesn't work nor does dayClick for tablet on that example https://fullcalendar.io/ - .fc-unselectable is breaking it. !important override on the css properties is the workaround.

**Comment by evanjmg** [comment]
found my issue: selectAllow doesn't fire on ipad

**Comment by tonyrumph** [comment]
I found that tapping & holding on a specific day fires the eventClick.

**Comment by arshaw** [comment]
in this demo i've created: https://codepen.io/arshaw/full/pazbwo

i open it up on safari on my iphone and the event click fires just fine, immediately on touch-down.

i even tried turning `selectable` on and same effect: https://codepen.io/arshaw/full/bLbeoJ/

i'm having trouble determining how `selectAllow` relates to this big and having trouble recreating, so I'll close this ticket until I get more info

**Comment by stephiescastle** [comment]
I am running into this same issue. I found that the first time I tap, it works as expected. However, anytime after the first, I see the behavior that @evanjmg has -- I have to tap and hold.
