### ISSUE TITLE
Dynamically add an event to a specific event source

### ISSUE THREAD

**Issue by aenany-atmosphereiot** [fullcalendar/fullcalendar#3570]
.fullCalendar( 'renderEvent', event [, stick ] )

what is meant by [, stick] here? After some time I realized that this was an optional 3rd argument. This is not immediately clear though. 

I have looked at the rest of the documentation and found that in some cases, italics is used to denote an optional argument. and in other cases this format is used. 

I would appreciate if you could use italics or make it semantically relevant like so:

.fullCalendar( 'renderEvent', event , _stick_ )

Thank you!

**Comment by Prabhakar-Poudel** [comment]
@aenany-anaren 'stick' is an optional Boolean variable. Specifying it to true will cause the event to be rendered permanently. [Check out the docs](https://fullcalendar.io/docs/event_rendering/renderEvent/).
If set to false however will cause the event to vanish soon after you navigate out of view where the event is being displayed.

Note: Stick will not cause event to be added to event source. But you can find it in [clientEvents]{https://fullcalendar.io/docs/event_data/clientEvents/)

@arshaw It would be nice if there was some way to add event to event source too when it renders using renderEvent method.

**Comment by aenany-anaren** [comment]
Thank you @Prabhakar-Poudel

**Comment by arshaw** [comment]
Yes, I will reopen this if there is more demand for such a thing. Thanks!

**Comment by jtommy** [comment]
@arshaw I agree with @Prabhakar-Poudel.
Currently, it isn't possibile to add an event to a specific event source and the workaround is about set eventSource color (and/or styles) or remove all events and add a new event source (only for no async load).
