### ISSUE TITLE
Limit the duration of selection of a new event

### ISSUE THREAD

**Issue by tro69** [fullcalendar/fullcalendar#3571]
Is there an option or a way to limit the duration of selection of a new event?
I would limit the duration of selection of a new event to max time of day (12pm/00:00 or value of "maxTime").
Example:
![immagine2](https://cloud.githubusercontent.com/assets/17103948/23656700/095d9b40-033b-11e7-8570-dcd5ac60a8c5.jpg)

**Comment by arshaw** [comment]
You can do that with [selectAllow](https://fullcalendar.io/docs/selection/selectAllow/). See it the amount of time between the start and end exceeds.
