### ISSUE TITLE
"list" used as buttonText for listMonth, listWeek and listYear

### ISSUE THREAD

**Issue by yabdab** [fullcalendar/fullcalendar#3572]
Surely there is a way to have a custom string used for each. Nothing in docs gives a clue on how to accomplish this.

**Comment by yabdab** [comment]
So if a user wants to use listWeek, listMoth, and listYear in the header, then "list list list" is what the end user sees in the final calendar output.

**Comment by tro69** [comment]
[buttonText](https://fullcalendar.io/docs/text/buttonText/)
```javascript
$('#calendar').fullCalendar({
    header: {
        left: 'prev,next today',
        center: 'title',
        right: 'month,agendaWeek,agendaDay,listMonth,listYear,listWeek,listDay'
    },
    buttonText: {
        listMonth: 'List Month',
        listYear: 'List Year',
        listWeek: 'List Week',
        listDay: 'List Day'
    }
});
```

**Comment by yabdab** [comment]
@tro69 Thanks bro. :-)

**Comment by arshaw** [comment]
@Robrecht  there is currently no easy way. can you open a new ticket so we can start discussing?

**Comment by Robrecht** [comment]
Done: https://github.com/fullcalendar/fullcalendar/issues/4544
