### ISSUE TITLE
Dragging external events from a long list make event go behind calendar

### ISSUE THREAD

**Issue by sadgamer** [fullcalendar/fullcalendar#3573]
Please go this link for more description 

I have a select drop-down list which output a list of items using ajax when you choose an option. The problem is that the list of items to be dragged on the calendar is very long. If you scroll the page completely you can go to the last item but you will not be able to see some part of the calendar. So I set the height of the external-events div to 600px and overflow-y:scroll so that you can scroll through the list only without affecting the calendar. The problem is by setting the external-events div to overflow-y:scroll , when I drag an item it does not come out of the div but go behind the calendar. Any idea how to solve this ?? 

More info on this link : http://stackoverflow.com/questions/42652963/fullcalendar-dragging-external-events-from-a-long-list-make-event-go-behind-ca

**Comment by arshaw** [comment]
Hi @sadgamer your question is too specific to your particular application. It would be great to whittle it down to a specific feature request or bug report. You're reference the external-events div, which is something outside of main rendered calendar, which is mostly your responsibility, not fullcalendar's
