### ISSUE TITLE
Double click on iPad (using Fullcalendar)

### ISSUE THREAD

**Issue by shubham19bhatt** [fullcalendar/fullcalendar#3574]
We are using Fullcalendar in saelsforce. We are binding double click like this :-
element.bind('dblclick', function()
It is working fine in desktop but not working in Ipad. Please suggest how can we enable double click in ipad too.

**Comment by arshaw** [comment]
Would you be able to post a [runnable, stripped-down demonstration of the bug](http://fullcalendar.io/wiki/Reduced-Test-Cases/)? Would really appreciate it because the time saved reproducing will be time spent fixing.
