### ISSUE TITLE
Bug: disableCursor() not properly working

### ISSUE THREAD

**Issue by maciek12305** [fullcalendar/fullcalendar#3575]
I'm trying to remove events from the calendar. It works pretty good, but the actual version don't changes the mousecursor back after the mouse click is released until other interaction with elements happens. This isn't a issue in an older version of fullcalendar.

Fullcalendar 2.30 + Moment.js 2.9.0 (Working properly)
http://jsfiddle.net/932ynzsc/13/

Fullcalendar 3.2.0 + Moment.js 2.17.1 (Will not change back the mouse cursor)
http://jsfiddle.net/z6yL4h3f/4/

**Comment by arshaw** [comment]
Thanks, reproduced.

Likely diagnosis: the event rendering is clearing the current selection, but not killing the selection drag interaction.

**Comment by arshaw** [comment]
as of v5 (and probably v4), the bad cursor doesn't stick anymore:
https://codepen.io/arshaw/pen/zYrzJVL?editors=0010
