### ISSUE TITLE
Generic days with day-of-week, no dates

### ISSUE THREAD

**Issue by arshaw** [fullcalendar/fullcalendar#3581]
A few people have requested a view for which there are no specific dates. They simply want to displays days-of-week... a view with Sun/Mon/Tue/Wed/Thu/Fri/Sat headers and the ability to assign events to them.

FullCalendar heavily relies on there being a discrete date for each day, making this feature request awkward to implement.

**Suggested workaround:** pick a real date in time, render a week view (like `agendaWeek`), and simply ignore the dates. Only rely on the moments' days-of-week (`.weekday()`).

**Comment by Anton-V-K** [comment]
The proposed approach seems to work fine except for one minor issue: it is not possible to remove dates in week coolumn headers.
As explained in the doc tuning view options should be enough, however following code doesn't affect column headers which display day names along with specific dates (like 'Mon 1/1', 'Tue 1/2', etc.):
```
      views: {
        week: { // name of view
            titleFormat: 'dddd', // 'ddd'
            // other view-specific options here
        }
      },
```

**Comment by arshaw** [comment]
we won't implement this. pls see my proposed workaround in the description
