### ISSUE TITLE
Error on the width of fc-axis with jquery 3.2.0

### ISSUE THREAD

**Issue by jvancoillie** [fullcalendar/fullcalendar#3585]
It would seem that the computation of the width of fc-axis is no longer correct with the use of jquery 3.2.0

You can see it in action in the [jsfiddle](https://jsfiddle.net/jvancoillie/nd33tzxs/)

**Comment by espen** [comment]
Can confirm, I just upgraded my dependencies and noticed this as well.

There was a [breaking change](https://jquery.com/upgrade-guide/3.0/#breaking-change-width-height-css-quot-width-quot-and-css-quot-height-quot-can-return-non-integer-values) (possibly [related issue](https://github.com/jquery/jquery/issues/3193)) for width calculations in jQuery 3.0 but the only [difference in v3.2 seems to be a bug fix](http://blog.jquery.com/2017/03/16/jquery-3-2-0-is-out/):

> Fixed a bug in .width(), .height(), and related methods where CSS transforms were included in the calculations. For instance, an element with the style transform: scale(2x) should not have its width and height values doubled (#3193).

**Comment by csavva** [comment]
I noticed the same thing today as well. It works ok up to jquery 3.1.1 which is just fine for me.

**Comment by arshaw** [comment]
thanks. will try to come up with a fix very soon

**Comment by arshaw** [comment]
Looks like there was a bug in jQuery 3.2.0, which has since been fixed with a hotfix:
https://blog.jquery.com/2017/03/20/jquery-3-2-1-now-available/

> The most significant one had to do with retrieving width or height on an inline element with no explicitly-set dimensions.

which is exactly what the problem was.

**Comment by arshaw** [comment]
tho jquery 3.2.1 is causing this problem: https://github.com/fullcalendar/fullcalendar/issues/3612

**Comment by arshaw** [comment]
just upgrade to jquery 3.2.1. the newly release fullcalendar [3.3.1](https://github.com/fullcalendar/fullcalendar/releases/tag/v3.3.1) works well with it.
