### ISSUE TITLE
eventUnclick API function?

### ISSUE THREAD

**Issue by aenany-atmosphereiot** [fullcalendar/fullcalendar#3586]
Hello FullCalendar team,

I was wondering if it was possible for an implementation of an API method possibly called eventUnclick(callback), that fires off when you click outside of an Event within your calendar.

If you could make its interface as simple as https://fullcalendar.io/docs/mouse/eventClick/ has it that would be very useful!

Thank you!

**Comment by arshaw** [comment]
What do you mean "click outside of an event"? Anywhere except an event? That seems overly broad, no? Could you describe your usecase?

**Comment by aenany-anaren** [comment]
Let's say I click on an event in the calendar, and then click elsewhere within the calendar but not in another event... anywhere in the calendar body except for the event.

Thanks!

**Comment by cptx032** [comment]
You can use `dayClick` callback
