### ISSUE TITLE
Issue with loading popup

### ISSUE THREAD

**Issue by khan5268** [fullcalendar/fullcalendar#3587]
When calendar is loading events via AJAX, it displays a  loading popup. When loading finishes, it hides the loading popup if we are on the same tab. Now during the loading of events, if we move to other tab or minimize the window of browser and then come back to the same tab, then it keeps displaying loading pop up. Although, the instruction to close the pop up does get called but the loading pop up doesn't get removed. The surprise to me is, jQuery too doesn't work the way it works properly. $('body') gives null on console. If we keep ourselves on the same tab, then the issue doesn't happen (Browser specific issue only for chrome and IE).
![loadingissue](https://cloud.githubusercontent.com/assets/24638566/24142133/a6eed7f0-0e4b-11e7-8bcd-3ed02f05236e.JPG)

**Comment by arshaw** [comment]
Would you be able to post a [runnable, stripped-down demonstration of the bug](http://fullcalendar.io/wiki/Reduced-Test-Cases/)? Would really appreciate it because the time saved reproducing will be time spent fixing.
