### ISSUE TITLE
Recurring events in week view over week boundary

### ISSUE THREAD

**Issue by TBSliver** [fullcalendar/fullcalendar#3588]
Found an issue when using recurring events, in that they dont carry across the week boundary. Example here, where it SHOULD go over from Saturday to Sunday, but it doesnt:

http://jsfiddle.net/duu0dx2t/809/

Am i missing something, or should it just work (tm)?

*edit* specified the wrong days in the issue

**Comment by tobya** [comment]
It goes over from Sunday to Monday for me. I'm using Windows 10 with Chrome, perhaps it is browser based. 
![websiteimage254](https://cloud.githubusercontent.com/assets/325502/24147860/1a582d94-0e34-11e7-9b0d-5cc222d14268.jpg)

**Comment by espen** [comment]
`end: '30:00'` Not that it matters (I assume) for the actual issue here but shouldn't this be a moment or a proper date string?

**Comment by TBSliver** [comment]
@tobya sorry my bad, my internal use has it set to ISO format so starting on a Monday - forgot i hadnt altered the demo :) *fixes the original question*

@espen if 'dow' is set, then you can just put something in which is going to be passed to a moment duration: https://github.com/fullcalendar/fullcalendar/blob/master/src/EventManager.js#L774 - documented here: https://fullcalendar.io/docs/event_rendering/Background_Events/

**Comment by DanielTung** [comment]
Looks like a bug.
The documentation for the Event Object doesn't cover 'dow' but the background event documentation does cover it and adding the reoccurring event to be a background event does not change the behaviour you described.
[http://jsfiddle.net/duu0dx2t/813/](url)

**Comment by arshaw** [comment]
Reproduced. If this were only happening with normal events, which do not officially support `dow`, I would ignore, but since it's affecting BG events, I'll take a look.

The crux of the problem is the excessive maxTime, which is beyond 24:00. That IS supported, but has been a source of tricky bugs. Doesn't play nice with `dow` I guess.

**Comment by arshaw** [comment]
I hoped that v3.3.0 would fix this, but seems that it has not.

**Comment by hostgame** [comment]
Any news? @arshaw

**Comment by arshaw** [comment]
I've adapted this for v5 and it now works: https://codepen.io/arshaw/pen/MWKoPbX?editable=true&editors=001

It might even work for v4 too.
