### ISSUE TITLE
Wrong Z-index on drag over selected button

### ISSUE THREAD

**Issue by uselessscat** [fullcalendar/fullcalendar#3589]
When you drag an event on a view type button, the selected button is above the event being dragged. Here are some examples:
![Screenshot1](https://cloud.githubusercontent.com/assets/15332878/24148098/0cc4e1c6-0e1c-11e7-8c0c-ba339fb5da92.png) ![Screenshot2](https://cloud.githubusercontent.com/assets/15332878/24148097/0cb70182-0e1c-11e7-976a-d2041c8d03a6.png)

Both examples were made in the example calendar that is [in the documentation](https://fullcalendar.io/js/fullcalendar-3.2.0/demos/background-events.html).

In the buttons on the left also happens.
![captura de pantalla de 2017-03-21 09-54-36](https://cloud.githubusercontent.com/assets/15332878/24148197/87c2ad90-0e1c-11e7-9a84-7c43a0ed9320.png)

**Comment by arshaw** [comment]
Reproduces, thanks

**Comment by arshaw** [comment]
this has been fixed in v4/v5
