### ISSUE TITLE
able to make subheader ?

### ISSUE THREAD

**Issue by fap2this1** [fullcalendar/fullcalendar#3591]
Hi

is there a custom config, where i can make a subheader?
![image](https://cloud.githubusercontent.com/assets/11610770/24200327/1e14b52c-0f0d-11e7-8874-483449b51a84.png)

is there a way i can make the images ? 

```
 buttonText: {
            prev: '<',
            next: '>'
        },
```

**Comment by arshaw** [comment]
what do you mean by a subheader? a second row of controls?
