### ISSUE TITLE
Add .fc-other-month to TDs in tbody (inside fc-content-skeleton not fc-bg) for corresponding TDs in thead

### ISSUE THREAD

**Issue by tomasofen** [fullcalendar/fullcalendar#3592]
Hi

I see this 2015 ticket closed:

https://github.com/fullcalendar/fullcalendar/issues/2964

I was searching for the same, including the _.fc-other-month_ class to TDs in the body of the "_fc-content-skeleton_" div, as it is in the "_fc-bg_" div.

I have been trying to make changes in the "_renderSegRow: function(row, rowSegs) {_" function, but i was unable to make it work.

Any help with this? Is there any event equivalent to "_eventRender: function(event, element, view) {_" to override for the day rendering outside _fullcalendar.js_?

**Comment by arshaw** [comment]
What are you hoping to achieve exactly?

It will be weird to have that className on a cell that spans multiple days, especially when one of the days is in the other month and one is not.

**Comment by nuriarai** [comment]
Hello, I need the same. In my case, I need to style the events in the days of the other month with opacity set, to show this events a little bit different from the month's events. So I need to have the class fc-other-month in the TDs of the body, not only in the header.

**Comment by jacekkarczmarczyk** [comment]
Agree, there is now no way to style differently events from other monhts

**Comment by arshaw** [comment]
in v5, the DOM is much different for month view. it will accommodate this now
