### ISSUE TITLE
Add @media print int fullcalendar.print.css

### ISSUE THREAD

**Issue by vulvulune** [fullcalendar/fullcalendar#3594]
This is a feature request.

With webpack, it's possible to include css files, with just an import in the js code, but we cannot add `media=print` because we don't manage the adding of the style or link tag.

Why don't add a media query directly in the fullcalendar.print.css file?

**Comment by arshaw** [comment]
Things are the way they are because of IE8 support, but now that is dropped, and what you describe can be implemented.

Best to wait until a major version switch IMO.

**Comment by arshaw** [comment]
This issue has been addressed in the latest alpha release (4.0.0-alpha.2)
[See the blog post &raquo;](https://fullcalendar.io/blog/2018/10/release-v4-alpha2)

https://fullcalendar.io/docs/v4/release-notes#core

**Comment by arshaw** [comment]
I'm closing this issue to signify that it's implemented (since v4-alpha2). I'll comment on this thread again when v4 is officially released.

**Comment by arshaw** [comment]
[V4 was officially released a few days ago!](https://fullcalendar.io/blog/2019/03/v4-officially-released)
