### ISSUE TITLE
Calendar Theme

### ISSUE THREAD

**Issue by john2014** [fullcalendar/fullcalendar#3597]
Hi Adam, Is it possible to have FullCalendar add a theme similar to link below:

http://areapp.azurewebsites.net/calendar/sample.php

I am sure many companies would find that helpful (instead of the default gray on blue) 😄

**Comment by espen** [comment]
That seems to be https://github.com/ronisaha/wdCalendar and not FullCalendar

You can style the calendar any way you want. It's also possible to use [jQuery UI theming](https://fullcalendar.io/docs/display/theme/).

Also see https://github.com/fullcalendar/fullcalendar/pull/3566 for an easier way to implement a custom theme (not yet merged).

**Comment by arshaw** [comment]
@espen 's response is 100% correct. closing.

**Comment by john2014** [comment]
Hey Adam, is it possible to do theming without using either Bootstrap or Jquery UI? Both of these library are too big/bloated and I would prefer to not have to include them just to get theming.

Plus since the wdCalendar looks a lot like MS Office Calendar, I am sure many corporate users of FullCalendar would like this theme to also be included by default when they install FullCalendar (in addition to current gray/blue theme).

**Comment by arshaw** [comment]
I hope to make an extensible theming system, which would work for any theme system as long as there's an adapter.
