### ISSUE TITLE
Callback function not found

### ISSUE THREAD

**Issue by surendar** [fullcalendar/fullcalendar#3599]
eventSources: [ { url:"${sri.buildUrl('getCalendarEvents').url}", type:'POST', backgroundColor:'#5cb85c', borderColor:'#4cae4c' },
{
events: function(start, end, timezone, callback) {

    		console.log('asdfasdfas');
    		
    		alert(callback);
    		
    			  var events = [];
    			  
					  events.push({
                title: 'asdfasdf',
                start: '2017-03-25T11:45:00',
                end:'2017-03-25T12:45:00' ,
                allDay: false
            });
             events.push({
                title: 'asdfasdf',
                start: '2017-03-26T11:45:00',
                end:'2017-03-26T12:45:00' ,
                allDay: false
            });
    

  
    			callback(events);
				},
				backgroundColor:'#5cb85c', borderColor:'#4cae4c'
       }
       
        ],

error : callback is not a function

**Comment by tobya** [comment]
I think Stackoverflow.com might be a better place to get help with a coding issue such as this.  You can tag it fullcalendar

**Comment by arshaw** [comment]
Would you be able to post a [runnable, stripped-down demonstration of the bug](http://fullcalendar.io/wiki/Reduced-Test-Cases/)? Would really appreciate it because the time saved reproducing will be time spent fixing.
