### ISSUE TITLE
Event display wrong in only month view not in week and day view

### ISSUE THREAD

**Issue by chiragsatapara** [fullcalendar/fullcalendar#3602]
Hello ,

I have a issue when there is a start and end date time is less than 9:00 AM. You can check this issue [here](https://jsfiddle.net/tryu1k0g/4/). It is working perfect for the Week and Day view but there is a problem with month view.

In this example , this is my event: 
 ```
{
            title: 'Birthday Party',
            start: '2017-03-26 06:00:00',
            end: '2017-03-27 05:00:00',
            allDay: false
        }
```

but in calander it is display only for the 26 of march not for the 27 of march. Can you please help me to solve this issue ASAP.

**Comment by chiragsatapara** [comment]
@brandonaaron , can you please help me to solve this issue ASAP.

**Comment by Prabhakar-Poudel** [comment]
@chiragsatapara If I understood you problem correctly [this may help](https://fullcalendar.io/docs/event_rendering/nextDayThreshold/).
If this is not what you want. Please post the query with what you expect and what you get. Thanks

**Comment by chiragsatapara** [comment]
@Prabhakar-Poudel , look this jsfiddle [click here](http://jsfiddle.net/539jx/209/) , in this same event is display in two days , any idea about this?

**Comment by Prabhakar-Poudel** [comment]
@chiragsatapara 

> but in calander it is display only for the 26 of march not for the 27 of march

Is not that your requirement? To display the event on 26th as well as on 27th. 

> in this same event is display in two days , any idea about this?

Your event spans more than a day so obviously it will show up in two days if unless the [nextDayThreshold](https://fullcalendar.io/docs/event_rendering/nextDayThreshold/) exceeds the number of hours your event spans to in the next day.

And I think there is a bug in your code. The date string is not in proper format check this [fiddle](http://jsfiddle.net/5zq7cn5s/1/)

**Comment by chiragsatapara** [comment]
@Prabhakar-Poudel 
**Is not that your requirement? To display the event on 26th as well as on 27th.**
this is my requirement , but why it is not working in my code , it is working in another jsfiddle which i share in previous reply.

**Comment by Prabhakar-Poudel** [comment]
@chiragsatapara . It works fine. You did not set nextDayThreshold value, and also when you pass date string for start/end, make sure you have the string in proper format.
[Your updated fiddle](https://jsfiddle.net/mdcnmLpo/1/)

**Comment by chiragsatapara** [comment]
@Prabhakar-Poudel  very very thanks for your help.
