### ISSUE TITLE
Question: eventRender or eventAfterRender are not triggered when updating an event

### ISSUE THREAD

**Issue by viiter** [fullcalendar/fullcalendar#3603]
when using `.fullCalendar('updateEvent', event);` methods `eventRender()` and `eventAfterRender()` are not triggered, is this a bug or a feature ?

**Comment by arshaw** [comment]
they should be.

If you think there's a bug...
Would you be able to post a [runnable, stripped-down demonstration of the bug](http://fullcalendar.io/wiki/Reduced-Test-Cases/)?
