### ISSUE TITLE
Calendar title wrong

### ISSUE THREAD

**Issue by AntonyCorbett** [fullcalendar/fullcalendar#3604]
Please see the demo:

http://output.jsbin.com/nikawi

Steps:

1. Click the "week" button - calendar title correctly changes to a date range
2. Click the "day" button - calendar title correctly changes to a single date
3. Click the "week" button again - calendar title wrongly shows a single date

**Comment by espen** [comment]
I see the same bug on fullcalendar.io with v3.3.0 but I'm unable to replicate in my own app using FullCalendar v3.2.0

**Comment by arshaw** [comment]
Wow, really lame bug. Thought automated tests would have got this one. Will investigate very soon.

**Comment by arshaw** [comment]
updated fiddle with no bug: http://jsbin.com/patakehume/1/edit?html,js,output

**Comment by arshaw** [comment]
Released in [3.3.1](https://github.com/fullcalendar/fullcalendar/releases/tag/v3.3.1)
