### ISSUE TITLE
FullCalendar print multiple months

### ISSUE THREAD

**Issue by alessiovaralta** [fullcalendar/fullcalendar#3605]
Hi, I want to print multiple months in one time is possibile?

**Comment by arshaw** [comment]
i think your request more closely relates to this feature request:
https://github.com/fullcalendar/fullcalendar/issues/470
&uarr;
Could you please visit the link, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates?

if that is implemented, print support would be implemented for it as well.
