### ISSUE TITLE
Google Calendar Integration Document

### ISSUE THREAD

**Issue by rhires** [fullcalendar/fullcalendar#3606]
In following the Google Calendar instructions, the steps do not match the pages in Google's Developer Console. There is no "APIs & Auth" in the sidebar, for example. As the options are more complex than these otherwise well written instructions, it would be helpful if the instructions matched more closely what Google is now doing and showing in its Developer Console.

**Comment by arshaw** [comment]
Thanks. I'll take a look and improve the docs.

**Comment by robungar** [comment]
Yes, please do this. I cannot Google Calendar working either. [https://codepen.io/robungar/pen/awEjOy?editors=0010](url)

I've tried three separate projects and cannot get it to work, one of which has nothing but full calendar in it. The error I keep getting is the following:

`fullcalendar.js:1800 Uncaught TypeError: g[r.substring(...)] is not a function
    at u (fullcalendar.js:1800)
    at l (fullcalendar.js:1780)
    at je.formatDate (fullcalendar.js:1514)
    at m.et.format (fullcalendar.js:1407)
    at e (fullcalendar.min.js:6)
    at u (fullcalendar.min.js:6)
    at l (fullcalendar.min.js:6)
    at je.formatDate (fullcalendar.min.js:6)
    at m.et.format (fullcalendar.min.js:6)
    at function.t.constructor.getEventTimeText (fullcalendar.min.js:7)`

**Comment by matthewbivins** [comment]
@arshaw : is there a way that you could highlight the major differences in the docs and what Google Calendar needs, here on Github? I'm also unable to get this to work, but would really love to use FullCalendar/Google Cal with a couple of clients in the next month or so. Thank you very much in advance!

**Comment by arshaw** [comment]
deplyed this docs fix: https://fullcalendar.io/docs/google-calendar
