### ISSUE TITLE
Event Resize Documentation is inaccurate 

### ISSUE THREAD

**Issue by ajaydev12** [fullcalendar/fullcalendar#3608]
### Documentation Bug
The definition of delta needs to be updated. The current document for eventResize is "delta is a Duration Object that represents the amount of time the event's end was extended by. Available in version 2.0.1 and later."
However, I find that delta is a Duration Object that represents the amount of time the event's  **time** (either start or end) was extended by **OR reduced by**.

**Comment by arshaw** [comment]
Thanks. I'll clear this up.

**Comment by maxwellt** [comment]
@arshaw , could it be that the documentation is inaccurate again? If I read the documentation for `eventResize` or `eventDrop` the info argument should have properties called `event`, `prevEvent`, `startDelta`, `endDelta`, `revert` and `view`, yet if I check the `main.d.ts` typings file I get the following method signature:

```
eventResize?(arg: {
            el: HTMLElement;
            event: EventApi;
            delta: Duration;
            revert: () => void;
            jsEvent: Event;
            view: View;
        }): void;
```

**Comment by AllyMurray** [comment]
@maxwellt I just came across the same issue, I don't think it's the documentation that's the problem, I think the typings are wrong. When debugging if you check what properties the object actually has it matches the documentation.

**Comment by arshaw** [comment]
all good! thanks!
