### ISSUE TITLE
Day view navigation bug when trying to navigate to a day of another week

### ISSUE THREAD

**Issue by johnkla** [fullcalendar/fullcalendar#3610]
Hello!

In v3.3.0 there seems to be a bug with the day view when the `weekends` option is set to `false`. Navigating from friday to monday next week, or monday to friday the previous week, ain't possible. The next/previous button shows up as disabled.

v3.2.0 didn't have this issue.

I'm guessing it might have something to do with the `buildRangeInfo` method together with the `validRange` option introduced in v3.3.0, but I haven't got to look more into it yet.

### [Test case 1, v3.3.0](http://jsfiddle.net/zk7kaacy/1/) (`weekends: false`):

Steps to reproduce:
1. change to day view
2. try and navigate to monday next week or friday the previous week
**Result:** next/previous button gets disabled, making it impossible to navigate to another week.

When changing back to week view the button stays disabled until you change week again.

**Expected behaviour:** Since the `validRange` option isn't set, I would expect it to be possible to navigate endlessly back and forwards between weeks in day view, just like the week view behaves.

### [Test case 2, v3.2.0](http://jsfiddle.net/zk7kaacy/2/) (`weekends: false`):
Works as expected, next and previous buttons don't get disabled.

### [Test case 3, v3.3.0](http://jsfiddle.net/zk7kaacy/3/) (`weekends: true`):
Works as expected, next and previous buttons don't get disabled.

**Comment by arshaw** [comment]
thanks. reproduced. will fix this very soon.

**Comment by arshaw** [comment]
fixed in v3.3.1. updated js fiddle without buggy behavior: http://jsfiddle.net/zk7kaacy/6/

**Comment by arshaw** [comment]
Released in [3.3.1](https://github.com/fullcalendar/fullcalendar/releases/tag/v3.3.1)

**Comment by johnkla** [comment]
Wonderful, much appreciated!

**Comment by marcogh** [comment]
It's seems related to me, so i posted here:

when i run the jsfiddle below, prev and next button are disabled.

clicking on "month" and then again to "agendaWeek" enables the buttons.

http://jsfiddle.net/zk7kaacy/6/

**Comment by arshaw** [comment]
the next/prev buttons are disabled because of the `validRange` you provided. Both the previous and next views would have days the are completely disabled, and thus the calendar won't let you navigate to them
