### ISSUE TITLE
jquery fullcalendar not rendering custom fields

### ISSUE THREAD

**Issue by flyingboy007** [fullcalendar/fullcalendar#3611]
I added jquery full calendar and it works fine. But its not rendering custom fields properly.

    $('.calendar').each(function () {
        var calendar = $(this);
        calendar.fullCalendar({
            header: {
                left: 'prev, next today',
                center: 'title',
                right: 'month,basicWeek,basicDay'
            },
            selectable: true,
            selectHelper: true,
            editable: false,
            displayEventTime: false,
            eventLimit: true,
            events: [{"id":22,"title":"john","start":"2017-03-30","end":"2017-03-31","color":"green","allDay":true,"last_name":"doe"}],
            eventRender: function(event, element) {
                element.attr("content",event.last_name) //As per the docs this is the way to go but not working
                
            }

        });
    })

Here the `last_name` is not showing in `calendar`. But default fields are showing fine. How can I show last_name in calendar?

**Comment by johnkla** [comment]
You need to add it to the element :)

    eventRender: function(event, element) {
        element.append(event.last_name);
    }

or wrapping it with html:


    eventRender: function(event, element) {
        element.append('<span style="color: pink;">' + event.last_name + '</span>');
    }

**Comment by flyingboy007** [comment]
@johnkla Thank you mate.Works like charm....
