### ISSUE TITLE
jquery 3.2.1, agenda view scrollbars causes misalignment

### ISSUE THREAD

**Issue by arshaw** [fullcalendar/fullcalendar#3612]
<img width="392" alt="screen shot 2017-03-31 at 12 03 09 am" src="https://cloud.githubusercontent.com/assets/56520/24535988/896086c8-15a5-11e7-98d1-0bd0c17ec8bf.png">

**Comment by arshaw** [comment]
Released in [3.3.1](https://github.com/fullcalendar/fullcalendar/releases/tag/v3.3.1)

**Comment by Moxide** [comment]
Hello,
with  FS 1.6.1 and FC 3.3.1, Jquery 3.2.1, the problem seems to be solved in Firefox but not in Chromium or Safari, I still see the misalignment, could anyone confirm this ?
Thanks.

**Comment by espen** [comment]
I'm not seeing any issues in Safari with FC 3.3.1. Can you reproduce the issue @Moxide ?

**Comment by Moxide** [comment]
Thanks for your feedback !
The Safari version is old (8.0.7), I'll update and see if there is a difference.
Chromium is version :  57.0.2987.98 , linux x64
Midori: 0.5.11 linux x64 (which behaves quite similarly to Safari, Webkit engine)
When the window size is _small enough to make scrollbars appear_, the misalignment is triggered :
![capture d ecran 2017-04-05 a 08 25 36](https://cloud.githubusercontent.com/assets/16779013/24714033/94aea09c-1a27-11e7-8c5e-70002e9b19c0.png)

The same page on Firefox 52.0.1 linux x64 :
![firefox](https://cloud.githubusercontent.com/assets/16779013/24714146/fc1a100e-1a27-11e7-8433-e8ca555ef3e2.png)

**Comment by espen** [comment]
So this is a problem with an outdated Safari version?

**Comment by Moxide** [comment]
No, just tried with Safari 10.1 and it's the same...

When you're sizing down the browser window and the scrollbars appear, can't you see the misalignment ?

**Comment by espen** [comment]
No misalignment using latest version of Safari with https://fullcalendar.io/js/fullcalendar-3.3.1/demos/agenda-views.html

**Comment by Moxide** [comment]
I cannot reproduce it either with the demos, so it must be related to the particular case of my project !
I'll try to dig further and open a new issue if I can build a demo which makes the problem appear.
Thank you very much for your answers :-)
