### ISSUE TITLE
use image in the resources area of the scheduler

### ISSUE THREAD

**Issue by saleman67** [fullcalendar/fullcalendar#3613]
Currently we can use the title property of the resource object that will be displayed in the resource area of the scheduler, this is only text.
In our case the resource objects are employees. We would like to show an image of those employees, so you can quickly see who you are working with. 
Therefore it would be nice if the Resource Object would get an extra property, for example: imageUrl. Depending if a title or imageUrl is passed, one or both of them should be shown.

**Comment by espen** [comment]
I haven't done that myself but I think https://fullcalendar.io/docs/resource_rendering/resourceRender/ should do what you want. 

btw use https://github.com/fullcalendar/fullcalendar-scheduler for Scheduler issues. But questions should be asked on StackOverflow, see https://fullcalendar.io/support/

**Comment by saleman67** [comment]
Thanks for you reply. That works perfectly!

**Comment by mitulhevin** [comment]
Dear @saleman67 please share how you get image with resource name..

**Comment by ravindrajain-hash** [comment]
Dear @saleman67 please share how you get image with resource name..

**Comment by edeoliv** [comment]
Dear @saleman67 please share how you get image with resource name..
