### ISSUE TITLE
Wrong Now Indicator with Min/Max Time

### ISSUE THREAD

**Issue by furkankadioglu** [fullcalendar/fullcalendar#3616]
Hello,

My calendar options is:
```
           nowIndicator: true,
           slotDuration: '00:05:00', 
            minTime: "15:00:00",
            maxTime: "38:59:59", 
```

It appears on the wrong day and time:

![screen shot 2017-04-02 at 02 19 57](https://cloud.githubusercontent.com/assets/5060068/24583195/ee3cd488-174a-11e7-903e-5b04da381e74.png)

**Comment by arshaw** [comment]
Would you be able to post a [runnable, stripped-down demonstration of the bug](http://fullcalendar.io/wiki/Reduced-Test-Cases/)? Would really appreciate it because the time saved reproducing will be time spent fixing.
