### ISSUE TITLE
Feature request: Add ability to pass html data attributes at instantiation time to event elements

### ISSUE THREAD

**Issue by lavanda-igor** [fullcalendar/fullcalendar#3618]
To enhance calendar customizability, it'd be convenient in some scenarios to have the ability to pass html attributes at instantiation time.

### Calendar instantiation
```
{
    events: [
        {
            title: 'Birthday Party',
            start: '2011-04-04',
            data-attributes: {
                 eventDressCode: 'casual' 
            }
        }
    ]
}
```

### Generated element
```
<a class="fc-day-grid-event fc-h-event fc-event fc-start fc-end fc-draggable" data-event-dress-code="casual">
	<div class="fc-content">
		<span class="fc-time">7a</span> <span class="fc-title">Birthday Party</span>
	</div>
</a>
```

**Comment by espen** [comment]
You should be able to accomplish this with https://fullcalendar.io/docs/event_rendering/eventRender/

**Comment by lavanda-igor** [comment]
Indeed, thanks @espen.

**Comment by mtachaudhary** [comment]
> You should be able to accomplish this with https://fullcalendar.io/docs/event_rendering/eventRender/

@espen this link is not working, can you please share a solution to this issue?
I want to add a data attribute to the event element.

**Comment by mtachaudhary** [comment]
> @espen this link is not working, can you please share a solution to this issue? I want to add a data attribute to the event element.

This solution is working for me: 
```
eventDidMount: function (info) {
    let eventEl = info.el;
    jQuery(eventEl).attr('data-rrule', values);
}
```

**Comment by elin-y** [comment]
https://fullcalendar.io/docs/v4/eventRender

**Comment by PabloManuel78** [comment]
> 

What do we do if we use version 6.1.4?

**Comment by PabloManuel78** [comment]
`
// Se ejecuta al pintar cada elemento: https://fullcalendar.io/docs/event-render-hooks
// llamado justo después de que el elemento se haya agregado al DOM. Si los datos 
// del evento cambian, NO se vuelve a llamar.
eventDidMount: function(info) 
{
	// Tomo el elemento del DOM recién pintado.
	let eventEl = info.el;
	// Le añado un atributo DATA. En el parámetro info.event.X están todos los atributos que vienen del DOM.
	$(eventEl).attr('data-id', info.event.id);
	$(eventEl).css("background-color", info.event.backgroundColor);
	$(eventEl).css("color", info.event.textColor);
}
`

OK with 6.1.4

**Comment by augustofagioli** [comment]
> `// Se ejecuta al pintar cada elemento: https://fullcalendar.io/docs/event-render-hooks` `// llamado justo después de que el elemento se haya agregado al DOM. Si los datos ` `// del evento cambian, NO se vuelve a llamar.` `eventDidMount: function(info) ` `{` ` // Tomo el elemento del DOM recién pintado.` ` let eventEl = info.el;` ` // Le añado un atributo DATA. En el parámetro info.event.X están todos los atributos que vienen del DOM.` ` $(eventEl).attr('data-id', info.event.id);` ` $(eventEl).css("background-color", info.event.backgroundColor);` ` $(eventEl).css("color", info.event.textColor);` `}`
> 
> OK with 6.1.4

// Run each item: https://fullcalendar.io/docs/event-render-hooks
// Called just after the element has been added to the DOM. Yes the data
// of the event changes, NO if you go back to call.
