### ISSUE TITLE
Does updateEvent triggers full re-rendering?

### ISSUE THREAD

**Issue by marcoancona** [fullcalendar/fullcalendar#3624]
It looks like a single event update with `updateEvent()` triggers the `eventRender` and `eventAfterRender` callback for all events in view. See http://jsfiddle.net/anconam/334ntqrw/

Is this expected behaviour? Are all events rendered upon update of any event?

**Comment by arshaw** [comment]
pls see my comment in this ticket:
https://github.com/fullcalendar/fullcalendar/issues/3003
&uarr;
Could you please visit the link, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates?
