### ISSUE TITLE
Custom time for now indicator

### ISSUE THREAD

**Issue by fra-gadio** [fullcalendar/fullcalendar#3628]
Hello ,
I would like to set a custom time for the now time indicator, 
in my case the indicator should not follow the client's computer time but the system time, which is different.
Is this possible?
https://jsfiddle.net/dcryan22/7xcqaLpq/

thank you

**Comment by fra-gadio** [comment]
Nevermind I found the solution on my own (but if there's a simpler solution please let me know. :) 

Here it is for whoever is interested.  
1) make sure you're not displaying the indicator
2) Set to the moment() object to the date/time that you want to be displayed by the now indicator.
3) add this code to the full calendar properties:

eventAfterAllRender: function(callback)
						{
							//render now indicator
							var view = $('#calendar').fullCalendar( 'getView' );
							view.renderNowIndicator(moment());
						},

**Comment by arshaw** [comment]
is the [now](https://fullcalendar.io/docs/timezone/now/) hook not good enough?
