### ISSUE TITLE
how customize header base button

### ISSUE THREAD

**Issue by EKovalevich** [fullcalendar/fullcalendar#3631]
Hello.
I was faced with the following situation, I need to implement within one calendar day list and day time line. Please tell me how to customize the button names of base types.
Here's how it looks:
http://dl4.joxi.net/drive/2017/04/11/0021/2268/1394908/08/7ba5ac2075.jpg
http://dl3.joxi.net/drive/2017/04/11/0021/2268/1394908/08/9f38874313.jpg

**Comment by Prabhakar-Poudel** [comment]
If you are looking to rename the buttons you can simply use [buttonText](https://fullcalendar.io/docs/text/buttonText/) option.
Worst case you can use jQuery to rename your buttons on render.

**Comment by EKovalevich** [comment]
As I understood from the documentation, the buttonText option helps to change the title only my custom buttons. Or am I wrong?

**Comment by Prabhakar-Poudel** [comment]
I'm not sure if I understand what are you asking about.
But here is what might help:

If you want to change default text in FC buttons use buttonText as 

 ```
 buttonText: {
    month: 'Month', 
    agendaDay: 'Day', 
    agendaWeek: 'Week', t
    today: 'Today'
 },
```

But if you want to title your [custom buttons](https://fullcalendar.io/docs/display/customButtons/) use `text` attribute as on the example page.

Further, for usage queries,I would suggest to post your question on the [StackOverflow fullcalendar tag](http://stackoverflow.com/questions/tagged/fullcalendar). When entering a new question, make sure you tag it with fullcalendar.

**Comment by EKovalevich** [comment]
Thanks for the help, your example was enough to correct the error.

I used :
```
views: {
       basicDay: { buttonText: 'list' },
       agendaDay: { buttonText: 'time line' },
},
```

instead of your method.
