### ISSUE TITLE
Unable to change yearly view to the vertical/horizontal single row /column

### ISSUE THREAD

**Issue by brijesh333** [fullcalendar/fullcalendar#3635]
Default year view it display is 12 box each of sinlgle month. I want to chnage it to single row which contains date from 1 to 31. But while changing file fullcalendar.js file it is not able to rander the events in view.
### Bug Reports
You MUST have a JSBin recreation, or else your issue will be CLOSED without explanation.
Instructions: http://fullcalendar.io/wiki/Reporting-Bugs/

### Feature Requests
Search the issue tracker for an existing ticket before creating a new one.
Instructions: http://fullcalendar.io/wiki/Requesting-Features/

(Please erase the above text and begin typing. Thanks!)

**Comment by arshaw** [comment]
"Default year view it display is 12 box each of sinlgle month" -- really? fullcalendar does not yet have this feature.

**Comment by brijesh333** [comment]
However after changing internal library I am able to do it. Is there any alternate library which provide this views?
