### ISSUE TITLE
Event's EndTime when event's EndDate is greater than current date 

### ISSUE THREAD

**Issue by luetn** [fullcalendar/fullcalendar#3638]
Hello all
Maybe I am missing something.
In this JSBin http://jsbin.com/pujeqajuro/edit?js,output the displayed endtime is not the endtime of the event. Should be 15:00 and not 23:59
Is it possible to display the time on Sun 4/9 according to displayEventTime?
Thanks

**Comment by arshaw** [comment]
hmm, weird. i'll look into it.

**Comment by TCOA** [comment]
Certainly odd behavior on end times - on each view......
https://codepen.io/TechCoder/pen/YxQbBV
all events are in Sept, from a day at noon until X time the next day.

When the event ends later in the day, it shows on the month view (my main concern at the moment and easiest to see the issue - other views have 'mixed' results for the same event!)

Specific example:

**Month view**
Sept 10 shows 15 events (11 starting on that day and 4 that ended {though it should be 11})
Sept 11 shows ONLY 4 events

**Week view**
Shows as expected

**List view**
Events that should end the next day AFTER 9 AM are showing as ended, while others show an 11:59 end (missing one minute - as reported in another ticket)

Rolling over the weekend, Sun loses 7 of the events (showing only the 4 that had 11:59 end times) and doesn't show the times at all (the 11 starting on that date are similar to the 10th - if they end AFTER 9 AM, then they show, but the correctly show 12:00 end times).

Monday (11th) shows only 4 ending events (those ending after 9AM).

**Comment by arshaw** [comment]
much better in v5: https://codepen.io/arshaw/pen/KKVqGeB?editable=true&editors=001
(and maybe v4)
