### ISSUE TITLE
FullCalendar : ne is not defined

### ISSUE THREAD

**Issue by Swati7shinde** [fullcalendar/fullcalendar#3640]
Hello Support,

I am using full Calendar in salesforce lightning and facing an issue while loading the page.While loading the page i can see the component is being loaded but i am getting the below error.
**Uncaught ReferenceError: ne is not defined  throws at fullCalendar.min.js:1340**

As the issue is in js library we are not able to load our component in salesforce. Could you please fix this asap.

Thanks,
Swati
![snapshot](https://cloud.githubusercontent.com/assets/27682797/25233036/0d8a17c4-25fb-11e7-9988-b38ab2c8374d.png)

**Comment by arshaw** [comment]
Would you be able to post a [runnable, stripped-down demonstration of the bug](http://fullcalendar.io/wiki/Reduced-Test-Cases/)? Would really appreciate it because the time saved reproducing will be time spent fixing.
