### ISSUE TITLE
dayClick() is not fired after select() is called on touch devices

### ISSUE THREAD

**Issue by dmytro-shchurov** [fullcalendar/fullcalendar#3642]
Our clients are not satisfied with touch support in FullCalendar, so they do not like to wait 300-500 msec after they tap on a day to get it selected. It appears not natural for them.
I liked to use `dayClick()` callback to select a day for them by calling `calendar.select()` after some checks.
The problem is that the `dayClick()` callback is fired only when `select()` was ***not*** called before.
There is a reason of all this *longDelay* settings: to let user to drag a view without firing `select`.
But I think it's easy to fire `dayClick()` only when drag was not initiated. You have `mouseDown`, `mouseMove`, and only then `mouseUp` which must be used to generate `dayClick`.
Until you manage *longDelay*s, please fix the issue with not fired `dayClick()`

**Comment by dmytro-shchurov** [comment]
Open your own _Selecting time ranges_ demo either on mobile or in Chrome emulator, and make sure that touch device support does not exists.
Some times instead of selecting a day, a day view is opened instead.

**Comment by arshaw** [comment]
have you looked at selectLongPressDelay?
https://fullcalendar.io/docs/selection/selectLongPressDelay/
