### ISSUE TITLE
Event is not visible (rendered behind other event)

### ISSUE THREAD

**Issue by lan0** [fullcalendar/fullcalendar#3650]
In this jsbin the event with the title "invisible" gets rendered behind other events: https://jsbin.com/geremolipe/edit

If I set a higher `z-index` and apply a width the event appears here:
![image](https://cloud.githubusercontent.com/assets/7386264/25399529/fd1a520c-29ef-11e7-97ee-c2ea86c1c7c7.png)

**Comment by arshaw** [comment]
thanks @lan0 . i've recreated. this is actually a duplicate issue. can we use the old issue instead?
https://github.com/fullcalendar/fullcalendar/issues/2758
&uarr;
Could you please visit the link, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates?
