### ISSUE TITLE
problem with agendaWeek,  [prev,next] and validRange in the past

### ISSUE THREAD

**Issue by marcogh** [fullcalendar/fullcalendar#3651]
As shown here:

http://jsfiddle.net/zk7kaacy/10/

When the calendar is rendered, [prev] button is wrongly disabled.

When I change the to month view, and then change back to agendaWeek, the [prev] button is enabled.

**Comment by arshaw** [comment]
Thanks. Recreated. This is a legit bug.

**Comment by marcogh** [comment]
Related to this:

http://jsfiddle.net/zk7kaacy/11/

In this case the [prev] button must stay disabled (previous week outside range) but after switch to month and switchback to agendaWeek, it get enabled.

**Comment by arshaw** [comment]
queued for release

**Comment by arshaw** [comment]
Released in v3.5.0 ([blog post](https://fullcalendar.io/blog/2017/08/bootstrap-support-and-future-developments/#more-257))
