### ISSUE TITLE
dateAlignment in month view

### ISSUE THREAD

**Issue by luks-g** [fullcalendar/fullcalendar#3653]
> > Hi,
> > 
> > When I use "dateAlignment : 'week' " in month view, the "Next" button does not work properly. See https://jsfiddle.net/luks/yus79a1g/5/
> > 
> > Thanks for help!
> 
> "v3.3.1 fixed this issue.
> 
> adjusted your demo: https://jsfiddle.net/yus79a1g/6/
> works"
> 

For my is still not working, because when I cliked ">" (next month button) calendar display few weeks earlier.
This is hepend only when current day in calendar is not in the first week in month.

Thanks

**Comment by arshaw** [comment]
Could you post an updated jsbin?
