### ISSUE TITLE
EventDataTransform TypeError: input is undefined

### ISSUE THREAD

**Issue by kanonhian** [fullcalendar/fullcalendar#3654]
When fetching events using an eventSource as function, eventDataTransform throws 
```
TypeError: input is undefined
out._id = input._id || (input.id === undefined ? '_fc' + eventGUID++ : input.id .... 
```
No tested with eventSource as JSON, but according to [docs](https://fullcalendar.io/docs/event_data/eventDataTransform/) it should work for both of them. 

In the picture
![picture](https://cloud.githubusercontent.com/assets/23344994/25443329/87270eb0-2a75-11e7-83da-fe234c1dd1d4.png)
 you can see the hook is triggered, because the EventData object is shown in the firebug console. Looks like the problem is after the execution of the hook.

My calendar configuration is attached
[publication_calendar.js.zip](https://github.com/fullcalendar/fullcalendar/files/958949/publication_calendar.js.zip)

**Comment by arshaw** [comment]
Could you turn this into a JSBin?
https://fullcalendar.io/wiki/Reduced-Test-Cases/
