### ISSUE TITLE
Set custom start/end date for month view 

### ISSUE THREAD

**Issue by GeorgianaSc** [fullcalendar/fullcalendar#3661]
Hello,

I have searched everywhere for a solution to my problem but I couldn't find one. I really like your component and I want to use it. For the month view I would like to be able to set custom start/end date. 

I need to display more or less than one month, not full months. I found something more general in this issue https://github.com/fullcalendar/fullcalendar/issues/1108 but it's not what I need. 

For example my exam session could start on 16 March Friday and end on 11
 May Thursday. I would like to see the whole period in one view to have an overview on my exams(events). I attached a printscreen for this situation. 

<img width="612" alt="view" src="https://cloud.githubusercontent.com/assets/28138313/25530319/86cf9a12-2c2e-11e7-91ab-928d5f960098.PNG">

Is it possible to add this feature or maybe do you know how could I solve this?

**Comment by arshaw** [comment]
https://fullcalendar.io/docs/views/Custom_Views/

**Comment by JoeNandhini** [comment]
Hi,
I'm using full calendar and I want to use same as GeorgianaSc has mentioned in the screenshot. But end is not  showing the duration in month view.
for example,
events:[ {
title: 'Long Event',
start: '2017-10-07T10:00',
end: '2017-10-10T11:00'
}]

It has to show in the month view as 10:00-11:00 or duration is 1 hour. But it does not show either. 
Any suggestion can you provide here.

**Comment by trigbit-sukhwinder** [comment]
@JoeNandhini   i have the same issue.

**Comment by AlejandroPena813** [comment]
I'm having issues with trying to use the time functionality for the month view. If one event has time inserted into the start date, the month view breaks. However, week, day and list view still work. If all events dont have a time slot, then all views will work. 

This is the errror i get: specialTokens[fakePart.substring(...)] is not a function
    at renderFakeFormatStringParts

**Comment by acerix** [comment]
Please post a new issue, the original issue above is different and can be accomplished with a Custom View. Also, please include a [runnable, stripped-down demonstration of the bug](http://fullcalendar.io/wiki/Reduced-Test-Cases/), if possible.
