### ISSUE TITLE
Dragging all day events with same start and end doesn't return end date

### ISSUE THREAD

**Issue by mhenris** [fullcalendar/fullcalendar#3662]
JSBin: http://jsbin.com/pahowaceba/edit?js,console,output

When dragging an all day, single day event from one day to another, fullcalendar returns null for the "end" if the start date and end date are the same calculated day.

In my case, I'm displaying dynamic (configurable) calendar data.  The database fields are configurable as well.

Take for example a database table with the fields "start" and "end", which are date fields, not datetime, and as such, I want them to display on the calendar as all day events.

So let's say event 1 has start of May 3rd and and end of May 3rd, which correctly shows on the calendar as an all day event on may 3rd.

I have an event drop method which accepts your event object and updates the underlying record using the start and end dates that you are passing in the event object to the eventDrop method.

However in this case, when I drag it to may 2nd, the end date I get back is null, so my update method adjusts the start date, but not the end date, resulting in bogus data in the database.  The resulting database record now shows May 2nd as the start date, and still May 3rd as the end.

If I enable forceEventDuration, it does give me an end date back, but the end date it gives back has not been adjusted by the delta of the drag, so it is effectively useless.

I'm unable to wrap my head entirely around the reasoning behind passing a null end date back to the eventDrop callback for all day events with the same start and end.  Any help would be appreciated.

**Comment by acerix** [comment]
It sounds like it is working as documented; the `end` time is exclusive and is `null` if not specified.

https://fullcalendar.io/docs/event-object
