### ISSUE TITLE
All the custom dateFormat option is string only, inflexible

### ISSUE THREAD

**Issue by chairuosen** [fullcalendar/fullcalendar#3664]
why not functions?

**Comment by arshaw** [comment]
i agree, there should be some way to programmatically generate text for a given displayed date

**Comment by arshaw** [comment]
This issue has been addressed in the latest alpha release (4.0.0-alpha.2)
[See the blog post &raquo;](https://fullcalendar.io/blog/2018/10/release-v4-alpha2)

Now possible to specify a function:
https://fullcalendar.io/docs/v4/date-formatting#formatting-functions

**Comment by chairuosen** [comment]
Thanks man. That's great!

**Comment by arshaw** [comment]
[V4 was officially released a few days ago!](https://fullcalendar.io/blog/2019/03/v4-officially-released)
