### ISSUE TITLE
All Day Events should display on end date

### ISSUE THREAD

**Issue by mhenris** [fullcalendar/fullcalendar#3667]
JSBin: http://jsbin.com/tenozoweya/edit?js,output

If an all-day, multi-day event starts on May 4th and ends on May 6th, it should display on the calendar on the 4th, 5th, and 6th, not just the 4th and 5th.

If what I've said above is not the default behavior, is there a flag?

I see in the docs about "exclusive" but I don't understand what that means, really.  If the underlying data which drives the calendar display indicates that an event spans a certain day, I can't think of any reason why the calendar should not display the event on that day, or at least have an option to display it in this fashion for all day events.

Could timezones be causing an issue?

I saw one stackoverflow post asking about this and the responder suggested to the OP that they should extend the date out by 1 day if they want it to display on the calendar on the end date.  But that just causes headaches when things get dragged etc. and you need to readjust at drop time and account for all scenarios and edge cases.  Can get tricky.

I feel like I might be missing something obvious.  Let me know.

**Comment by florentdestremau** [comment]
There tons of issues such as https://github.com/fullcalendar/fullcalendar/issues/3190, while I totally agree with you, nothing much to be expected for now.

**Comment by jhwinters** [comment]
For a fuller explanation of why the current behaviour is the way it is, see https://github.com/fullcalendar/fullcalendar/issues/3679

What you've actually identified is an inconsistency in the way people refer to the duration of events.

**Comment by jhwinters** [comment]
> I saw one stackoverflow post asking about this and the responder suggested to the OP that they should extend the date out by 1 day if they want it to display on the calendar on the end date. But that just causes headaches when things get dragged etc. and you need to readjust at drop time and account for all scenarios and edge cases. Can get tricky.

Definitely *don't* do this.  Trying to adjust the dates as you pass them to FC for display means you have stored them wrongly in the first place and you're right, it will get very tricky.

Regardless of whether or not you are using FullCalendar, the correct start and end times for an event which runs through the 4th, 5th and 6th of May are:

2017-05-04 00:00 and 2017-05-07 00:00

Yes, that's not how they would be referred to in everyday conversation, but that's what they are and that's what you need to store if you don't want to create endless problems for yourself.  Just translate the dates from colloquial English to the precise version above as the user enters them, and translate back if you ever need to re-display them in a non-graphical way (e.g. as pre-filled values on a form).

**Comment by arshaw** [comment]
this mirrors the discussion on https://github.com/fullcalendar/fullcalendar/issues/3190 . please discuss there.
