### ISSUE TITLE
Changing event properties requires view change

### ISSUE THREAD

**Issue by neroux** [fullcalendar/fullcalendar#3668]
JSFiddle at https://jsfiddle.net/c7bb0ygk/

Changes made to event properties in the eventRender callback seem to require a manual change of the view in order to take effect.

In the example the title and durationEditable are changed but only take effect once you switch to and from the monthly view.

**Comment by neroux** [comment]
Addendum, a change of view does not seem to be necessary but still a re-rendering. It can be also reproduced by changing the week.

**Comment by arshaw** [comment]
changing the properties isn't enough. you need to also call [updateEvent](https://fullcalendar.io/docs/event_data/updateEvent/). lmk if it doesnt work

**Comment by neroux** [comment]
Calling updateEvent in eventRender seems to end up in an infinite loop. The event properties do get updated though, it is only shown after a second rendering though. It seem as if changing them in eventRender does not apply it for the current rendering.

**Comment by neroux** [comment]
@arshaw Could you reproduce it?
