### ISSUE TITLE
Scroll issue on monthView

### ISSUE THREAD

**Issue by frlinw** [fullcalendar/fullcalendar#3669]
Step to reproduce:
- https://fullcalendar.io/js/fullcalendar-3.4.0/demos/basic-views.html
- remove margin on body tag
- On chrome, set zoom to 125% 
- Try to resize between 950-960px
- A scrollbar appear one pixel out of two

![image](https://cloud.githubusercontent.com/assets/11896237/25814039/ce0ab2ee-3413-11e7-8bbb-d3a062a04fe2.png)

In my app, the issue is a bit different but it's maybe related. 
When I click on prev/next buttons on month view, a scrollbar appear then disappear after few ms

**Comment by vkrupach** [comment]
Scroll is present even on a demo page: https://fullcalendar.io/js/fullcalendar-3.4.0/demos/background-events.html
![image](https://user-images.githubusercontent.com/8613225/29465773-168e8a0c-8443-11e7-8bca-474ae1388eb2.png)

**Comment by arshaw** [comment]
@vkrupach what OS / browser / zoom are you using?

**Comment by vkrupach** [comment]
@arshaw it's reproduced under 
- CentOS with Gnome 3.14.2
- Chrome Version 60.0.3112.78 (Official Build) (64-bit)
- No zoom, and the scroll dissapears when I zoom in/out to 110% / 90%.
- It's fine under FireFox

For now I kill the scroll with a CSS:
```
#calendar .fc-scroller {
  overflow-x: hidden !important;
  overflow-y: hidden !important;
}

```
I am pretty sure that the same is under Ubunu with Unity + Chrome. Will check it later and update you.

**Comment by vkrupach** [comment]
Hi @arshaw ,
It's fine under Ubuntu + Unity + Chrome/FireFox. Looks like it's Gnome + Chrome specific.

**Comment by frlinw** [comment]
Related to Chrome.
Fixed in v64
https://bugs.chromium.org/p/chromium/issues/detail?id=777095#c27
