### ISSUE TITLE
about more

### ISSUE THREAD

**Issue by UglyMelon007** [fullcalendar/fullcalendar#3670]
![image](https://cloud.githubusercontent.com/assets/13254781/25833424/d6787a20-34a3-11e7-91d1-72d2c3b0b1a9.png)

**Comment by UglyMelon007** [comment]
sorry, my english is not good. so i can't provide more info for the issue.

**Comment by arshaw** [comment]
Would you be able to post a [runnable, stripped-down demonstration of the bug](http://fullcalendar.io/wiki/Reduced-Test-Cases/)? Would really appreciate it because the time saved reproducing will be time spent fixing.
