### ISSUE TITLE
3.4.0: unable to retrieve view start/end in event source on load

### ISSUE THREAD

**Issue by espen** [fullcalendar/fullcalendar#3671]
I noticed a breaking change in v3.4.0. Prior versions allowed me to get info from the view object about start/end dates. With 3.4.0 .start gives me a null on load and info only if i change the date. With v3.3.1 I can get start/end dates on load.

v 3.4.0: http://jsbin.com/hififaj/edit?js,console,output
v 3.3.1: http://jsbin.com/kucopi/1/edit?js,console,output

I see there are some async changes for v3.4.0 perhaps this is the reason for the change of behaviour.

I'm not entirely sure why I depended on the view object for start/end dates as there is start/end date in the eventSource function input. So now I am using the event source input and it seems to be working for me (doing some more tests). So I am no longer dependent on this info but I still wanted to create the issue as it is not mentioned in the changelog.

Is this behaviour intentional?

**Comment by arshaw** [comment]
recreate, thanks. will try to fix this for the next release.

**Comment by arshaw** [comment]
v3.3.1 was executed things like this:

1. rendering view
    a. instantiate view
    b. actually do the view rendering
2. start fetching events

whereas v3.4.0 was changed to be this (not intentionally. just as part of a minirefactor):

1. start fetching events
2. rendering view
    a. instantiate view
    b. actually do the view rendering

it should probably be fixed to be something like this:

1. instantiate view
2. start fetching events
3. actually do the view rendering

but hopefully not a lot of people are depending on the nuance.

**Comment by arshaw** [comment]
this is most likely fixed since it was reported

but there is now a related issue: https://github.com/fullcalendar/fullcalendar/issues/4914
