### ISSUE TITLE
Change moment.locale when changing FC locale

### ISSUE THREAD

**Issue by espen** [fullcalendar/fullcalendar#3672]
Fullcalendar does not change moment.locale when changing FC locale.
To reproduce: Do ```moment.locale()``` in the console after changing locale here: https://fullcalendar.io/js/fullcalendar-3.4.0/demos/locales.html

It does however change moment.locale when [loading the FC locale files.](https://github.com/fullcalendar/fullcalendar/issues/2467)

**Comment by FluffyMatt** [comment]
This would be incredible handy... I'm having issues with Moment adding hours due to daylight savings

**Comment by espen** [comment]
@FluffyMatt current workaround is to do `moment.locale()` after FC has been required. Or after each FC locale change.

**Comment by arshaw** [comment]
I would need to think a bit more about the ideal API. I'm a bit afraid of FullCalendar causing state change in the global moment API.

Might want to force the developer to set `moment.locale()`, and then FullCalendar picks up on that somehow.

**Comment by arshaw** [comment]
since v4 doesn't even have moment js anymore, i'm closing this issue.
