### ISSUE TITLE
In week view, as the number of events at a given time goes up, the visual gap between them gets bigger.

### ISSUE THREAD

**Issue by jhwinters** [fullcalendar/fullcalendar#3673]
This may not be regarded as a bug, but it doesn't even need a JSFiddle implementation to see.  You can see it on the main FullCalendar demo page at:

https://fullcalendar.io/js/fullcalendar-3.4.0/demos/agenda-views.html

Switch to week view, and drag all the events to the same time on the same day.  As each event comes in it gets narrower - fair enough, the behaviour you'd expect - but at the same time the visual gap between the events gets wider.  By the time you get to 12 events at the same time, all the available space is taken up by the gaps, whilst each event is reduced to just a very thin vertical line.

Obviously there is a limit to how much can be fitted in, but earlier versions of FullCalendar handled this rather better.  You ended up with 12 small coloured rectangles separated by 11 thin white strips, rather than FullCalendar 3.4's 11 wide white strips with thin coloured lines between them.

Incidentally - thank you for an awesome product.

**Comment by jhwinters** [comment]
Having studied this a bit further, I've realised that it's not that the white strips are too wide - the events are appearing at exactly the right pitch given the number of events which FC is trying to fit in the space, but it's mis-calculating how wide each individual event box should be, making most of them much too narrow.  The white space is just a consequence of this.

I'll have a go myself at finding the problem.

**Comment by jhwinters** [comment]
I've had a look and I fear that fully diagnosing it is beyond my JavaScript abilities.  However, I have a bit more information which may be useful.

If, on the main FullCalendar demo page, you drag the 9 available events to the same time slot in the week view you end up with 8 very narrow events (with wide white gaps) and then the ninth a sensible width.  On my particular screen the first 8 are each 4 pixels wide, and the ninth is 11 pixels.  The white gaps are about 8 pixels each - twice the width of the events.

Examining the DOM, the width seems to be driven by the fc-time-grid-event element, which contains the fc-content one.  It has a margin-right of 20px, which doesn't seem to reduce as the number of events goes up.  If you manually reduce it to 15px then the events look much better.

I hope this is useful.

**Comment by jhwinters** [comment]
Further input - a couple of screen shots.  The first is from FullCalendar 2.0.2

![screenshot from 2017-05-21 07-31-09](https://cloud.githubusercontent.com/assets/345516/26281711/a311cf4e-3df7-11e7-9dfc-84f6c11181bc.png)

and the second from FullCalendar 3.4.0

![screenshot from 2017-05-21 07-31-17](https://cloud.githubusercontent.com/assets/345516/26281714/b80b00be-3df7-11e7-963f-b515970968cd.png)

Cheers,
John

**Comment by arshaw** [comment]
dup:
https://github.com/fullcalendar/fullcalendar/issues/2809
&uarr;
Could you please visit the link, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates?
