### ISSUE TITLE
eventRender flag to know if rendering is for helper

### ISSUE THREAD

**Issue by pgiani** [fullcalendar/fullcalendar#3674]
### Feature Requests
 
While the selection is being made and you are selecting a range eventRender is not called, there is any callbacks I can use to change the selection render to  inform the user the delta of the current selection, see image of what Im trying to achieve

![slack - pdj 2017-05-12 14 35 15](https://cloud.githubusercontent.com/assets/5713173/26014011/685fef6c-3720-11e7-969f-db9feae49bfe.png)

**Comment by arshaw** [comment]
The helper element is sent through the [eventRender](https://fullcalendar.io/docs/event_rendering/eventRender/) callback, but there is no way to discern whether the event being rendered is a real event or a helper, from within the callback.

I propose some additional flag that gets passed in.

**Comment by arshaw** [comment]
Here is a workaround

```js
    eventResizeStart: function() {
      isResizing = true;
    },
    eventResizeStop: function() {
      isResizing = false;
    },
    eventRender: function(event, $el) {
      if (isResizing) {
        $el.css('background-color', 'red');
      }
    },
```

[see the demo](https://codepen.io/arshaw/pen/JywQJQ?editors=0010)

**Comment by arshaw** [comment]
This issue has been addressed in the latest alpha release (4.0.0-alpha.2)
[See the blog post &raquo;](https://fullcalendar.io/blog/2018/10/release-v4-alpha2)

https://fullcalendar.io/docs/v4/eventRender

The `isMirror` flag. FYI, "mirror" is the new name for "helper"

**Comment by arshaw** [comment]
I'm closing this issue to signify that it's implemented (since v4-alpha2). I'll comment on this thread again when v4 is officially released.

**Comment by arshaw** [comment]
[V4 was officially released a few days ago!](https://fullcalendar.io/blog/2019/03/v4-officially-released)
