### ISSUE TITLE
Feature Request - Highlight Available Slots To Drop

### ISSUE THREAD

**Issue by sagivo** [fullcalendar/fullcalendar#3676]
When I want to drag&drop a specific event with constraints there is no way to know what the constraints are. It can be nice to automatically highlight the available time slots that can be dropped to. 
Using agenda view.

**Comment by jetlej** [comment]
+1

**Comment by espen** [comment]
@jetlej please use the github reaction feature to vote. See https://fullcalendar.io/wiki/Requesting-Features/

**Comment by arshaw** [comment]
this feature request is a dup of this previously poorly-named feature request:
https://github.com/fullcalendar/fullcalendar/issues/2513
&uarr;
Could you please visit the link, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates?
