### ISSUE TITLE
No space between events in the month view

### ISSUE THREAD

**Issue by laoneo** [fullcalendar/fullcalendar#3677]
Is it possible that the events on the same week in the month view will not have spaces (like in version 1.6)?
![image](https://cloud.githubusercontent.com/assets/251072/26089351/4a890d54-39fd-11e7-8407-ba4917ba10a8.png)

**Comment by arshaw** [comment]
A dup of this [previously-poorly-named] issue: 
https://github.com/fullcalendar/fullcalendar/issues/2853
&uarr;
Could you please visit the link, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates?
