### ISSUE TITLE
Additional event elements not clickable

### ISSUE THREAD

**Issue by neroux** [fullcalendar/fullcalendar#3678]
Clickable elements added in the eventRender callback won't be clickable unless they are wrapped in the element's inner `.fc-content` div, which however doesnt allow for full use of the event estate (CSS wise).

https://jsfiddle.net/um4gx8hr/ provides an example, please note the two append calls

**Comment by arshaw** [comment]
reproduced, thanks

**Comment by ken-gerada-congrego** [comment]
Any update regarding this issue?

**Comment by arshaw** [comment]
this is no longer the case in v5, which has [event-rendering-hooks](https://fullcalendar.io/docs/event-render-hooks) that ensure that the outer event wrapper is preserved.
