### ISSUE TITLE
Need better view selection control for many views

### ISSUE THREAD

**Issue by harohl** [fullcalendar/fullcalendar#3681]
I am offering a large list of view options to my customers.  I would like a better control for displaying the options.  In the screen shot below (if I attached properly), you can see the wide list of views as well as the split button for the refresh, which is currently open and collapses if clicked again.  I think a split button option for view options might be nice.  I would maybe offer 2-3 view buttons and then an other button with the rest of the views.  The other button would drop down into a list.  I would be happy to consider other options as well.  If this is not being offered, I will need to code my own, but it seems like a useful feature.
![splitbuttonexample](https://cloud.githubusercontent.com/assets/19411389/26165428/f0a42ede-3afd-11e7-920a-4281636522ea.jpg)

**Comment by jhwinters** [comment]
I've just been considering the same problem.  I haven't started progressing it yet, but the idea I had in mind was to offer a user configuration option (some kind of dialogue) where they can choose which views they want to have on screen.  That would offer the full list and they would tick the ones which they liked, then those chosen ones would appear in their button bar as above.

**Comment by harohl** [comment]
My goal is to allow the users to select which views get the preferred button slots but to list all of the rest in the dropdown.  This gives them access to the largest number of views without cluttering the header.  I think the variety of views is the strength of this tool.

**Comment by arshaw** [comment]
This is a bit out of the scope of fullcalendar. Rather than provide infinite options to tweak the header buttons, I'd rather have people implement their own buttons and then use the API methods to switch views.

**Comment by harohl** [comment]
Adam,
I am working on my code to build my own button control (combined buttons
and dropdown for extra choices), which will be data-driven.  I would like
to access the view properties in order to get the buttonText to put on the
button.  Is there an easy way to do this?  My example code is below.  I
would have the view name 'timelineDay' and would want to be able to
retrieve the buttonText '1 day'.

timelineDay: {
                        slotLabelFormat: sHourFormat,
                        buttonText: '1 day',
                        titleFormat: 'ddd MMM D, YYYY' //not needed for
other views that show DOW
  },

I would be happy to share my button control code once I get it working.

Heidi

**Comment by harohl** [comment]
I created a nice control that accommodates several views.  Here is a screen shot and some code in case anyone is interested.  I tried to pasted in all of the related code, but I may have missed some.
![viewnav](https://user-images.githubusercontent.com/19411389/27655417-4ccc3900-5c13-11e7-90ce-c8d35616ed6e.jpg)

`<div  id="div_viewnav" class="widget"  style="display:inline-block; margin-right:40px">
      <input type="hidden" id="h_view3" class="btn3" />
      <div class="cgviewnav">
           <button id="btn_view1" type="button" class="ui-button ui-widget ui-corner-left"    >
         </button>
        <button id="btn_view2" type="button" class="ui-button ui-widget"  >
         </button>
            <button id="btn_view3" type="button" class="ui-button ui-widget btn3"  >
         </button>
         <select id="sel_views" name="sel_views" class="viewsel"  >
         </select>
      </div>
  </div>

     $(function () { // document ready
 var sViewString = 'timelineDay,timeline2Day,timeline4Day,timeline9Day,timeline10Scroll,timelineMo,month,listWeek,agenda1,agenda7';
            var aViews = sViewString.split(","); //get views into array
            var saveindex;
            //Set button text and events 06/22/17 HH
            //highlight and disable/enable button 6/23/17 HH

            //buttonText values - have to hard-code due to no access to view defn 6/28/17 HH
            var buttonText = {
                timelineDay: '1 day',
                timeline2Day: '2 day',
                timeline4Day: '4 day',
                timeline9Day: '9 day',
                timeline10Scroll: '10d scroll',
                timelineMo: '30 day',
                month: 'month',
                listWeek: 'list',
                agenda1: 'agenda 1',
                agenda7: 'agenda 7'
            }

            //assign view names to hidden field
            $('#h_view1').val(aViews[0]); 
            $('#h_view2').val(aViews[1]); 
            $('#h_view3').val(aViews[2]);

            //var selected = []; 
            var selected = $("#btn_view1") //set first button to selected
            $("#div_viewnav").find('button').each(function (index) {
                //$(this).text(aViews[index]); //uses view name for button text. Find way to get button text from view
                $(this).text(buttonText[aViews[index]]);
                $(this).click(function () { //ON view button click
                    //clickViewButton(this, aViews[index], selected);
                    var viewname;
                    if ($(this).hasClass("btn3")) {viewname=$('#h_view3').val();} else {viewname=aViews[index]};
                    $('#calendar').fullCalendar('changeView', viewname); //change view

                    //trying to change highlight on button - 6/23/17 HH WORKS
                    if (selected[0]) {
                        selected.button('enable').removeClass('ui-state-active ui-state-hover');
                    }
                    //Cache the previous
                    selected = $(this);
                    //Disable this and keep color attributes
                    selected.button('disable').addClass('ui-state-active').removeClass('ui-state-disabled');
                    
                });
                saveindex = index;
            });
            //Set select options 06/22/17 HH
            $.each(aViews , function(index, val) {
                if (index > saveindex) { //skip first few used for buttons
                    //$("#sel_views").append($('<option>', { value: this, text: this }));
                    $("#sel_views").append($('<option>', { value: this, text: buttonText[this] }));
                }
            }); 
           
            //try new code for control group and select menu 6/23/17
            $( ".viewsel" ).selectmenu({
                classes: {
                    //"ui-selectmenu-button": "viewnav-splitbutton-select"
                    "ui-selectmenu-button": "ui-button-icon-only viewnav-splitbutton-select"
                },
                //width: 200 ,
                change: function(){
                 //if (this.value.length>0) { //do not try to retrieve more--REMOVED MORE, NOT REALLY NEEDED
                     $('#calendar').fullCalendar('changeView', this.value);
                     //$("#btn_view3").text(this.text); //set 3rd button text to selected item
                     $("#btn_view3").text(buttonText[this.value]); //set 3rd button text to selected item
                     if (! $("#btn_view3").hasClass('ui-state-active')) { //if switching from 
                         $("#btn_view3").button('disable').addClass('ui-state-active').removeClass('ui-state-disabled');
                         selected.button('enable').removeClass('ui-state-active ui-state-hover'); //enable and unselect works
                         selected = $("#btn_view3");
                     }
                     $('#h_view3').val(this.value);
         
                      //$(".viewnav-splitbutton-select").addClass('highlight'); 
                 //}
                }
          });
       
        $(".cgviewnav").controlgroup();
        //Disable first button and highlight; needs to go after controlgroup for some reason
        $("#btn_view1").button('disable').addClass('ui-state-active').removeClass('ui-state-disabled');
}
<style>
  .ui-selectmenu-button.viewnav-splitbutton-select {
        /*width: 8em;*/
        width:1em;
    }`
</style>
