### ISSUE TITLE
render hook for timeGrid view slots

### ISSUE THREAD

**Issue by jetlej** [fullcalendar/fullcalendar#3683]
dayRender() is only called on the full day slots, but not on the Scheduler time slots. Is there a way to make this work so I can style individual time slots differently?

**Comment by arshaw** [comment]
There's not official hook. I will have this ticket be a request for adding one.

What you can do is scrape the DOM on [viewRender](https://fullcalendar.io/docs/display/viewRender/) and manipulate the slots manually.

**Comment by emregulerr** [comment]
what's about this request's status?

**Comment by arshaw** [comment]
this now exists in v5!
https://fullcalendar.io/docs/slot-render-hooks
