### ISSUE TITLE
Gratuitous opacity leads to inconsistent event colours

### ISSUE THREAD

**Issue by AntonyCorbett** [fullcalendar/fullcalendar#3684]
fullcalendar.css contains the following style

.fc-event .fc-bg { /* the generic .fc-bg already does position */
	z-index: 1;
	background: #fff;
	opacity: .25;
}

which leads to events being shown in a different colour depending on the current view.

https://codepen.io/antonyc/pen/rmqoVY

Notice that month view renders the event color correctly whereas the colour of the event in the week view is slightly paler (because of the above mask). The effect is seen even when a colour is specified programmatically.

**Comment by arshaw** [comment]
I agree, there should be some better system.

As a workaround, you can always hide the fc-bg div with display:none

**Comment by AntonyCorbett** [comment]
>As a workaround, you can always hide the fc-bg div with display:none<
Thanks. Yes, that's what I've done. Do you know if the original mask has a purpose or whether it's perhaps just a left-over from a previous design?

**Comment by MiguelQueiroz** [comment]
by the way , why is there the opacity and the background if the event.color already takes it pro grammatically. I also noticed that opacity "layer" and had to do my CSS hack to remove it, but never understood why it was there? any comment on that ( why is there an opacity ) ?

**Comment by DonavanMartin** [comment]
Opacity is overriding some importing custom style.css... Event objects should have 'color' + 'opacity' properties. 0.25 default opacity is not very well designed, since it's hard to change this value without hard coding fullcalendar.css.

**Comment by DanielTung** [comment]
Running into this issue now. I am setting the event colour during eventDataTransform and in month view it works fine but in day or week view a 25% white background is being applied via fc-bg and it's not needed. I can't find a way to disable fc-bg so I've had to do it with a CSS override.

Any advice? We're running a very old version of 2.6.1 but don't have the time to go through a migration to the latest version as there are a lot of changes we think we'd need to make.

**Comment by arshaw** [comment]
this opacity thing has been removed in v4!

**Comment by jango07** [comment]
I am using version 4.0.0-alpha-2.I cant see any opacity in .fc-bg..But the eventbackgroundcolor still appears to be lighter..What is going wrong..Pls help me.

Thanks
Jan

**Comment by serp777** [comment]
The opacity isn't gone for background event, not sure why its asserted that there is no opacity:
![image](https://user-images.githubusercontent.com/10540204/105874594-9ba40580-5fb1-11eb-8d64-fc9b57ead679.png)

I had to remove the opacity here to make background events not look completely weird during overlap
