### ISSUE TITLE
validRange used with hiddenDays can cause fully disabled week views and disabled navigation buttons

### ISSUE THREAD

**Issue by yoancutillas** [fullcalendar/fullcalendar#3686]
Hi,

If you use validRange with hiddenDays, you can find yourself with a fully disabled Week view, and disabled navigation buttons, as you can see here:
https://codepen.io/anon/pen/mmaGbG?editors=1010

It only happens when the validRange start is a day that should appear on the-view-before-the-first-actual-visible-day, but didn't actually appear because it is an hidden day.

Example you will find in the codepen.io:
```
validRange start = saturday 03 May 2036
hidden days = saturday
firstDay of the week = sunday 
```

Using Fullcalendar 3.4.0

**Comment by arshaw** [comment]
confirmed. thanks

**Comment by arshaw** [comment]
fixed with 0727a1e271290dc7ce6fb42b1cc3d18017b28dc9

tests: 6a4eba71cf4c44a64e528b63a240469fa7834468

queued for release

**Comment by arshaw** [comment]
Released in v3.5.0 ([blog post](https://fullcalendar.io/blog/2017/08/bootstrap-support-and-future-developments/#more-257))

**Comment by yoancutillas** [comment]
Hi Adam,

Sorry, this bug now creates a fatal error as you can see with the same codepen but with FullCalendar 3.5.1:
https://codepen.io/yoancutillas/pen/Yryxgr?editors=1010

This is the error:
Cannot read property 'startMs' of null @ fullcalendar.js:9861

Can you provide a fix?
Thanks :)

**Comment by arshaw** [comment]
@yoancutillas i moved your latest issue here: https://github.com/fullcalendar/fullcalendar/issues/3846
