### ISSUE TITLE
resizing an event triggers eventClick if no change

### ISSUE THREAD

**Issue by yoancutillas** [fullcalendar/fullcalendar#3687]
Hi,

Is it possible not to trigger eventClick when you resize an event whithout changing its duration? (like if you change your mind after you start resizing)

Because the action was a long press to resize, not a brief click. When a user does that, he doesn't intend to click on the event.

He is a codepen to highlight the problem:
https://codepen.io/anon/pen/MmLrVb?editors=1000

Using FullCalendar 3.4.0

**Comment by arshaw** [comment]
I understand. We might want to prevent an eventClick if the mouse started on the resizer.

**Comment by bensaintsever** [comment]
I need a correction about this. Can we expect a future fix ?

**Comment by arshaw** [comment]
this is fixed in v5
