### ISSUE TITLE
Event.end is coming null if start date and end date are same

### ISSUE THREAD

**Issue by harish0000** [fullcalendar/fullcalendar#3688]
In JSON data there are some events having start date and end date as same ,so in event render i am getting null in event.end. 

Full Calendar Version : 3.4.0

JS BIN : http://jsbin.com/boxegawumi/edit?html,js,output

**Comment by espen** [comment]
Please read https://fullcalendar.io/wiki/Reporting-Bugs/

**Comment by harish0000** [comment]
@espen Added the  JS BIN url

**Comment by espen** [comment]
According to the iCalender specification:

> [The "DTEND" property for a "VEVENT" calendar component specifies the non-inclusive end of the event.](http://www.kanzaki.com/docs/ical/vevent.html)

> [The value MUST be later in time than the value of the "DTSTART" property.](http://www.kanzaki.com/docs/ical/dtend.html)

'end' is actually optional in Fullcalendar. Not specifying 'end' results in the same behaviour. This is since the event doesn't really have a duration as the end date is non-inclusive.

**Comment by arshaw** [comment]
please see this discussion: https://github.com/fullcalendar/fullcalendar/issues/3190
