### ISSUE TITLE
events partially outside of validRange, in month view, wrong time text

### ISSUE THREAD

**Issue by burriep** [fullcalendar/fullcalendar#3690]
See CodePen example here: [https://codepen.io/burriep/pen/eWXzMa](https://codepen.io/burriep/pen/eWXzMa)

In month view, no start time is shown for "crossing valid start" and I would expect that a start time would be shown, since it has a start time and is not an all day event.

**Comment by arshaw** [comment]
recreated, thanks

**Comment by arshaw** [comment]
in month view, in either case, I feel that that the full time text should be shown on the event, regardless of whether it passes the validRange.

For the other feature you proposed (`includeLeadingEvents `,`includeTrailingEvents`), can you open a separate ticket? I would prefer if it was just a single setting that determined both.

**Comment by christianortega123** [comment]
Was this ever fixed? I'm facing the same issue. Thanks.

**Comment by arshaw** [comment]
no longer an issue in v5: https://codepen.io/arshaw/pen/YzwQJmN?editors=0010
