### ISSUE TITLE
Export fullcalendar to ics format

### ISSUE THREAD

**Issue by kalyanixraut** [fullcalendar/fullcalendar#3692]
Looking for feature to export the fullcalendar view to ics format.

**Comment by espen** [comment]
It's currently not a feature in Fullcalendar (and IMHO shouldn't but sounds like a nice plugin). You can use a lib such as [ics](https://github.com/adamgibbons/ics) to generate an iCalendar file by getting all events from FC using [clientEvents](https://fullcalendar.io/docs/event_data/clientEvents/).

But most likely you want to do this on the server side as FullCalendar only has the current displayed events (for example this month). In most cases the user want an iCalendar-feed for all events which should be generated by your backend. Also be aware that iCalendar feeds are very limited. Many clients refresh very rarely and if you have many events it is problematic to produce the file on demand.

**Comment by arshaw** [comment]
i agree with @espen. out of fullcalendar's scope. mostly a backend problem.
