### ISSUE TITLE
End time missing from event label when selecting only 1 slot

### ISSUE THREAD

**Issue by geoffrussel** [fullcalendar/fullcalendar#3697]
https://codepen.io/anon/pen/MogvYv?editors=0010 

Why is it that when I select only 1 slot for an event that the label for it is missing the end time? When creating an event that uses more than 1 slot, the label shows fine. The HTML structure of what is generated between the two events seems different.

![image](https://cloud.githubusercontent.com/assets/12013557/26695481/a450132a-46d0-11e7-9efe-ac81b2c205a2.png)

**Comment by geoffrussel** [comment]
Update: it seems to be adding a class to the event called "fc-short" which is causing this behavior.

**Comment by arshaw** [comment]
thanks. this is a dup of this issue:
https://github.com/fullcalendar/fullcalendar/issues/3049
&uarr;
Could you please visit the link, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates?
