### ISSUE TITLE
Can we show the weekend as one day? (compress the weekend to show as one day)

### ISSUE THREAD

**Issue by shaani88** [fullcalendar/fullcalendar#3699]
I've been looking to compress the weekend to show as one day and show all the events on saturday and sunday in one column. Is this possible? Appreciate if you could provide any solution for this.

**Comment by arshaw** [comment]
dup of:
https://github.com/fullcalendar/fullcalendar/issues/1603
&uarr;
Could you please visit the link, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates?
