### ISSUE TITLE
Can we show more rows in month view when we select the number of weeks to display?

### ISSUE THREAD

**Issue by shaani88** [fullcalendar/fullcalendar#3700]
![untitled](https://cloud.githubusercontent.com/assets/14992453/26718775/ad85454e-479f-11e7-925b-c6a39e6fa727.png)
By default, currently full calendar shows 5 weeks in the monthly view. Let's say I have put a dropdown menu to select the number of weeks(ex: 1-10 weeks) to display in monthly view. Is there a solution for this? (eg: I select number of weeks as 3, and there should be only 3 rows ie:- 3weeks shown in the month view)

**Comment by arshaw** [comment]
instead of doing a month view, you'd want to do a [Custom View](https://fullcalendar.io/docs/views/Custom_Views/) and dynamically change its duration
