### ISSUE TITLE
Angular 2 : AOT build error

### ISSUE THREAD

**Issue by praveenrengarajan** [fullcalendar/fullcalendar#3701]
Angular Cli : 1.0.0.rc2
npm :3.10.8
Angular : 2
ap-angular2-fullcalendar: 2.7.40

When build App in Prod mode(AOT) getting following error:

> ERROR in Error encountered resolving symbol values statically. Calling function 'ɵmakeDecorator', function calls are not supported. Consider replacing the function or lambda with a reference to an exported function, resolving symbol Injectable in C:/inetpub/wwwroot/smilesProdFinal/node_modules/ap-angular2-fullcalendar/node_modules/@angular/core/core.d.ts, resolving symbol ɵf in C:/inetpub/wwwroot/smilesProdFinal/node_modules/ap-angular2-fullcalendar/node_modules/@angular/core/core.d.ts, resolving symbol ɵf in C:/inetpub/wwwroot/smilesProdFinal/node_modules/ap-angular2-fullcalendar/node_modules/@angular/core/core.d.ts

**Comment by arshaw** [comment]
smilesProdFinal? angular? not part of the fullcalendar project
