### ISSUE TITLE
object-oriented initialization API, without jQuery

### ISSUE THREAD

**Issue by bkdotcom** [fullcalendar/fullcalendar#3703]
issue description by @arshaw:

Eventually I want to move away from depending on jQuery and have an initialization look something like this:

```js
var calendar = new FullCalendar({/* options */});
calendar.setOption('name', 'val');
calendar.render(containerEl);
```

-----

issue description by @bkdotcom:

I'm dynamically setting options...
https://fullcalendar.io/docs/utilities/dynamic_options/

a) It seems that options can't be set until fullcalendar is initialized (ie `$("#myCalendar").fullcalendar();  // now I can set options`
b) setting (at least certain) options causes fullcalendar to refetch events

nutshell:  it's currently tricky to initialize fullcalendar with dynamic options.

It'd be nice to have an `init`  callback that could be utilized for such initial setting/configuration... perhaps the callback could/should return a promise object?

**Comment by espen** [comment]
More callbacks can definitively be useful but why can't you just dynamically set the options when initialising fullcalendar?

**Comment by arshaw** [comment]
Eventually I want to move away from depending on jQuery and have an initialization look something like this:

```js
var calendar = new FullCalendar({/* options */});
calendar.setOption('name', 'val');
calendar.render(containerEl);
```

That would allow you to setting of options prior to rendering. Would that help you?

**Comment by bkdotcom** [comment]
@arshaw yes.. I believe that's the crux of the issue.   fullcalendar begins to immediately render, dynamic options are set -> which triggers a re-render / re-fetch of events and a "race condition" or something...  I initially solved by wrapping my dynamic options in a setTimeout (which was janky).. then did a bit of refactoring to pass them in the initial initialization.

**Comment by alex-barberi** [comment]
+1 for using less jQuery. Angular is the big thing right now and it doesn't play well with jQuery.

**Comment by ocarreterom** [comment]
Also something like this could be nice:
```js
const container = document.querySelector('#container');
const calendar = new FullCalendar({
  element: container
});
```
or:
```js
const calendar = new FullCalendar({
  element: '#container'
});
```

**Comment by frlinw** [comment]
How can we help to remove jQuery dependency ?

**Comment by arshaw** [comment]
@frlinw there are lots of prerequisites for the project. the simplest way to help is to free up some of my time by jumping on [Issue Tracker Triage](https://fullcalendar.io/wiki/Contributing/)

**Comment by frlinw** [comment]
What is the new way for function call ?

I tried to figure out with this demo but it still uses the jquery way (note: jquery is not imported)
https://github.com/fullcalendar/fullcalendar/blob/v4.0.0-alpha/demos/selectable.html#L33

**Comment by arshaw** [comment]
More updates in the latest alpha release (4.0.0-alpha.2)
[See the blog post &raquo;](https://fullcalendar.io/blog/2018/10/release-v4-alpha2)

**Comment by arshaw** [comment]
I'm closing this issue to signify that it's implemented. I'll comment on this thread again when v4 is officially released.

**Comment by arshaw** [comment]
[V4 was officially released a few days ago!](https://fullcalendar.io/blog/2019/03/v4-officially-released)
