### ISSUE TITLE
change date in row

### ISSUE THREAD

**Issue by davodaslanifakor** [fullcalendar/fullcalendar#3705]
### Feature Requests
hi
i want change date in row show some like this pic 
![photo_2017-06-03_12-51-00](https://cloud.githubusercontent.com/assets/14367811/26751999/516fc40c-485b-11e7-9e19-682faac364de.jpg)
how i can do this please Guide me
Tnx...

**Comment by espen** [comment]
That view is not included in FullCalendar. You can however:

1) Show multiple days with Fullcalendar Scheduler (paid plugin): https://fullcalendar.io/scheduler/

2) Creata a custom view and make it yourself: https://fullcalendar.io/docs/views/Custom_Views/
