### ISSUE TITLE
Feature Request: add "style" option for event for any css

### ISSUE THREAD

**Issue by NashBridgesAT** [fullcalendar/fullcalendar#3711]
Similiar to the 'backgroundColor' or 'borderColor' options for an event, a 'style' option for adding ANY css-code would be great. With such an option you could easily use patterns as background colors or even background images for events (see pic).

![grafik](https://cloud.githubusercontent.com/assets/22543777/26789368/626124e8-4a10-11e7-9ce5-de0e7b60c8df.png)

I guess this could be easily done by introducing a 'style' option which is appended to the style attribute in the <a... tag (similar to fullcalendar's coloring functions). 
As a workaround you could use following solution. Just add a "; (your css code here);" in the backgroundColor or borderColor option to override the styling feature of fullcalendar.

For example, in php it looks like:
```
$event['backgroundColor'] = ';background: repeating-linear-gradient(
  45deg,
  #606dbc,
  #606dbc 10px,
  #465298 10px,
  #465298 20px
);';
```

**Comment by arshaw** [comment]
could be done with [eventRender](https://fullcalendar.io/docs/event_rendering/eventRender/)

**Comment by arshaw** [comment]
... in combination which a custom event property, which it would leverage.

**Comment by NashBridgesAT** [comment]
ah ok i see.. thanks... didn't realize that ;)
