### ISSUE TITLE
dayRender callback not fired when allDaySlot is false for the agendaWeek view

### ISSUE THREAD

**Issue by srthakkar** [fullcalendar/fullcalendar#3715]
dayRender callback not fired when allDaySlot is false for the agendaWeek view. it is working with allDaySlot = true.  for more info check [here](http://embed.plnkr.co/sM6ktu0G4icmTEp0y8Px/) . please change the value of allDaySlot in plunker for more info. I need this callback without setting allDaySlot true.

**Comment by arshaw** [comment]
dayRender only gets called on the whole-day slots in the month view, any of the "basic" views, and the all-day slots in agenda views. It is not called for the time slots in agenda view. By design. When those are disabled, it won't be called at all. What are you trying to achieve?

**Comment by srthakkar** [comment]
@arshaw  I want to use dayRender callback when the allDaySlot =false  for the agendaWeek view. Is that possible ?

**Comment by arshaw** [comment]
but what are you trying to change the rendering of? what do you plan to do in dayRender?

**Comment by srthakkar** [comment]
Actually, I want to change some of the dates backgrounds to red and I don't want to enable allDaySlot. Anyway, I used viewRender and customize it using following code.
`$("[data-date=" + moment(new Date()).format("YYYY-MM-DD") + "]").css("background-color", "#ffe5e5");`

thank you but I have managed what I need.

**Comment by antoniandre** [comment]
Hi, thanks for the awesome library and releasing the v4.

I am also after modifying the cells content (I want to display the time in each cell) using dayRender hook.
If I am not wrong, this is what I should use for this purpose as recommended from documentation: https://fullcalendar.io/docs/dayRender.

And from https://fullcalendar.io/docs/datesRender:
> If you need access to individual day-cells, use dayRender.

But I could not find anywhere that it won't be firing on certain conditions  like you say:

> dayRender only gets called on the whole-day slots in the month view, any of the "basic" views, and the all-day slots in agenda views. It is not called for the time slots in agenda view. By design. When those are disabled, it won't be called at all. What are you trying to achieve?

Is there a way to customise cells then when using resourceTimeGrid plugin/view? 

Thank you very much!

**Comment by japhfortin** [comment]
+1

hope this can still be opened.
I have this design on week view that is updated using dayRender function:
![image](https://user-images.githubusercontent.com/29589649/56182421-b5769180-6044-11e9-8730-f3a484b65ee1.png)

However, setting allDaySlots to false makes it not to read the dayRender function:
![image](https://user-images.githubusercontent.com/29589649/56182454-e5259980-6044-11e9-8d6c-f67f51aa2f87.png)
