### ISSUE TITLE
Eventlimit is not showing in customweek and timelineday view

### ISSUE THREAD

**Issue by imransmy** [fullcalendar/fullcalendar#3716]
Im using fullcalender in my application. Currently im not using any agenda views instead of that im using "timelineday" and "customweek" view as per my client request.  The issue is when im in month view the eventlimit is working fine whereas in customweek or timelineday view it was showing all the events which is more disrurbing the design. Can you please help me how to fix this as like as month view need to show in customweek and timelineday views.

**Comment by arshaw** [comment]
could you post a screenshot of demonstrating what you don't like? then i'll reopen
