### ISSUE TITLE
dayNamesMin missing.

### ISSUE THREAD

**Issue by Chieleman** [fullcalendar/fullcalendar#3718]
The shortest notation for a day is not translated. By changing the following pieces of code, they are translated correctly.

**Change 1**

Original:
```
		this.optionsModel.watch('buildingMomentLocale', [
			'?locale', '?monthNames', '?monthNamesShort', '?dayNames', '?dayNamesShort',
			'?firstDay', '?weekNumberCalculation'
```
Should be:
```
		this.optionsModel.watch('buildingMomentLocale', [
			'?locale', '?monthNames', '?monthNamesShort', '?dayNames', '?dayNamesShort', '?dayNamesMin',
			'?firstDay', '?weekNumberCalculation'
```

**Change 2**

Original:
```
			if (opts.dayNames) {
				localeData._weekdays = opts.dayNames;
			}
			if (opts.dayNamesShort) {
			    localeData._weekdaysShort = opts.dayNamesShort;
			}
```
Should be:
```
			if (opts.dayNames) {
				localeData._weekdays = opts.dayNames;
			}
			if (opts.dayNamesShort) {
			    localeData._weekdaysShort = opts.dayNamesShort;
			}
			if (opts.dayNamesMin) {
			    localeData._weekdaysMin = opts.dayNamesMin;
			}

```

Now you can use dayNamesMin the same way as dayNamesShort to translate Mo,Tu,We,etc...

**Comment by arshaw** [comment]
so you are requesting that there be a new setting, correct? I don't think FullCalendar ever had "dayNamesMin", so this is not really a regression.

I'd encourage you to add these _weekdaysMin settings to the moment locale directly instead of going through fullcalendar.

**Comment by Chieleman** [comment]
Correct, a new setting would be appreciated. If there is a setting for dayNames and dayNamesShort, it would be nice if one could set the dayNamesMin in the same way.

But I will try the moment.js detour tomorrow.
