### ISSUE TITLE
Vertically centring week numbers

### ISSUE THREAD

**Issue by ShadeBlack** [fullcalendar/fullcalendar#3719]
Hi. I've been using fullcalendar v3.1.0 for a project
I was asked to vertically centre the week numbers

I noticed the week numbers are in the fc-content table instead of fc-bg table
the function below placed the week numbers in the fc-content:
```
renderNumberIntroHtml: function(row) {
  var view = this.view;
  var weekStart = this.getCellDate(row, 0);
  if (view.colWeekNumbersVisible) {
    return '' +
      '<td class="fc-week-number" ' + view.weekNumberStyleAttr() + '>' +
        view.buildGotoAnchorHtml( // aside from link, important for matchCellWidths
          { date: weekStart, type: 'week', forceOff: this.colCnt === 1 }
        ) +
      '</td>';
  }
  return '';
},
```

so I placed the weeknumber formatting in the renderbg function instead:
```
renderBgIntroHtml: function(row) {
  var view = this.view;
  var weekStart = this.getCellDate(row, 0);
  if (view.colWeekNumbersVisible) {
    return '<td class="fc-week-number ' + view.widgetContentClass + '" ' +
      view.weekNumberStyleAttr() + '>'+weekStart.format('w')+'</td>';
  }
  return '';
},
```

_Truth be told, I did not look into the full impact of the modification above, I was just looking for quick solution to the request I was given._

The bg table has the height required for the following css to work correctly:
`.fc-week-number.fc-widget-content {vertical-align: middle;}`

It would be great if this were an option though:
```
$('#fcal').fullCalendar({
  weekNumbersAlign: 'middle',
});
```

**Comment by arshaw** [comment]
i agree with you that the markup should be simpler to be able to achieve this with pure css. there will be a markup refactor in the near future. i will wait for that instead of implementing a new setting.

**Comment by arshaw** [comment]
can easily be done with CSS now:
https://codepen.io/arshaw/pen/abdwQbO?editors=0110

```css
.fc-daygrid-day-top {
  justify-content: center;
}
```
