### ISSUE TITLE
Resize button (div) on my events by default

### ISSUE THREAD

**Issue by akenateb** [fullcalendar/fullcalendar#3721]
Hello First of all:

It is not an issue, it is a request. I have migrated full calendar v1 to v3. And now I do not see resize button (div) on my events by default, I have mouseovering every event to resize them but I would like to see this div by default (when calendar starts). How can I do that?

Thanks in advances.
Regards.

**Comment by arshaw** [comment]
make sure [editable](https://fullcalendar.io/docs/event_ui/editable/) is set to `true`.

if this is still a problem, you might be experiencing this issue: https://github.com/fullcalendar/fullcalendar/issues/2441
