### ISSUE TITLE
[Request] dayDoubleClick

### ISSUE THREAD

**Issue by thomascaillier** [fullcalendar/fullcalendar#3722]
I use fullcalendar for a rich-client application, and I'd like to easily trigger double clicks on days.

So I think it could be useful to have the same that `dayClick`, but with **double click**

Thank you 👍

**Comment by arshaw** [comment]
dup: https://github.com/fullcalendar/fullcalendar/issues/638
&uarr;
Could you please visit the link, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates?

**Comment by CamiloQB** [comment]
how to do dblclick in an event in fullcalendar v4. Thanks
