### ISSUE TITLE
Selecting Time Range selected WRONG date after zooming (only happens on mobile phones)

### ISSUE THREAD

**Issue by shungz89** [fullcalendar/fullcalendar#3724]
https://fullcalendar.io/js/fullcalendar-3.4.0/demos/selectable.html

I have tried the demo for the link above, apparently when selecting date, without zooming, it works fine. But everytime when I zoom. It shows another date.

Been trying hard to search for solution, but none exist :(

**Comment by arshaw** [comment]
i can't reproduce. what browser are you using?

**Comment by arshaw** [comment]
this issue is most likely a dup of:
https://github.com/fullcalendar/fullcalendar/issues/2492
&uarr;
Could you please visit the link, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates?

**Comment by shungz89** [comment]
@arshaw I am using android phone, google chrome. Other android phones has similar problem too
