### ISSUE TITLE
Start and end of events (month view) - part or full day?

### ISSUE THREAD

**Issue by Robinjoeh** [fullcalendar/fullcalendar#3727]
Hi!

Would it be possible (in an easy way) to have different start and end marks on the monthly view? Currently, fullCalendar is putting a new even below, but in case that events finishes at 12:00 and another one starts at 18:00, could it be put on the same row?

Also, if you create an event which starts at 18:00, fullcalendar displays it in the cell (monthly view, again) as it was started from the beginning of the day.

Is there any way to push the events forwards/backwords a bit if they don't cover the whole day?

Thanks!

**Comment by arshaw** [comment]
could you provide visual mockups of what you are requesting?
