### ISSUE TITLE
print-view month view events cause missing vertical day borders

### ISSUE THREAD

**Issue by jwhulette** [fullcalendar/fullcalendar#3728]
When printing the calendar in month view with an event the spans multiple days, the day boarder is missing. 
![month-html-view](https://user-images.githubusercontent.com/4930051/27302980-21008ef6-5507-11e7-83af-a78d5d1e9daa.png)
![month-print-view](https://user-images.githubusercontent.com/4930051/27302981-236477c0-5507-11e7-9f5e-8a3557505175.png)

I'm not sure why it happens. I've gone through the print.css file and cannot see anything that would cause the issue.

**Comment by arshaw** [comment]
confirmed, thanks

**Comment by arshaw** [comment]
this is no longer the case in v5
