### ISSUE TITLE
Missing the align position while creating a event by select a time area with the style of zoom on the body tag.

### ISSUE THREAD

**Issue by yinlianghui** [fullcalendar/fullcalendar#3729]
The codepen is there:https://codepen.io/yinlianghui/pen/gRWjEK

![image](https://user-images.githubusercontent.com/6219465/27372275-a279ac2a-5696-11e7-92df-a4e5ad73ef85.png)

The main style code :
```
body {
  zoom: 135%;
}
```
- The mouse hover**(the red arrow on the screenshot)** is not in the correct position when we want to create a new event by drag and drop operation on the fullCalendar board.
- It always to create a event that appeared at the bottom right corner which is offset the mouse hover.

**Comment by steedos** [comment]
+1

**Comment by arshaw** [comment]
yes, this is almost definitely the same issue as
#2492
&uarr;
Could you please visit the link, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates?
