### ISSUE TITLE
Divide long event and move "end part" on the top of next day or smth else

### ISSUE THREAD

**Issue by gromova-sn** [fullcalendar/fullcalendar#3730]
There are some long events. All events ordered by eventOrder: "_id" 
<img width="1048" alt="2017-06-21 12 02 11" src="https://user-images.githubusercontent.com/12665111/27376553-2e28c038-567b-11e7-9fa0-b99262bf5439.png">

Event with id:3 appears on top of id:2 but it shouldn't since we ordered by eventOrder: "_id".
The event with id: 2 should be divided and the end part(encircled grey) should go on top  of next day. 
<img width="1048" alt="2017-06-21 12 02 11_2" src="https://user-images.githubusercontent.com/12665111/27376638-69ee4ce6-567b-11e7-9b70-22cf24aaa755.png">
 or it should look like stairs 
<img width="638" alt="2017-06-21 12 18 31" src="https://user-images.githubusercontent.com/12665111/27376750-c439decc-567b-11e7-9f66-901c777907de.png">

I think it is incorrect behaviour of eventOrder(or something else), becouse long events at the end of week is divided. 
What do you think? Is it bug?  And will this ever be realized?

**Comment by arshaw** [comment]
I believe your problems with `eventOrder` are discussed here: https://github.com/fullcalendar/fullcalendar/issues/2907
