### ISSUE TITLE
Full calendar event is spanning in two days.

### ISSUE THREAD

**Issue by ajinkyab** [fullcalendar/fullcalendar#3731]
If the event is going to start on 11:30 PM and end on 12:30 AM next day then its displaying as spited. I want to show it only on starting day not on next day. Please see attached screen shot and help me to trace it out.  
![screenshot-118 102 250 138 2017-06-22 11-02-40](https://user-images.githubusercontent.com/8361270/27441262-a15594b8-578a-11e7-841f-b4cd2fbc9242.png)

**Comment by MartijnWelker** [comment]
Can you make a [reduced test case](https://fullcalendar.io/wiki/Reduced-Test-Cases/) for your issue ?

**Comment by arshaw** [comment]
closing until a reduced test case is posted
