### ISSUE TITLE
Days with Events Before 9AM are not highlighted on Calendar

### ISSUE THREAD

**Issue by Bramhananda** [fullcalendar/fullcalendar#3733]
Hi,

I have taken the full calendar example and modified the events. Why isn't 8th Of June highlighted in the calendar? 

Please click [here](https://codepen.io/NReddy/pen/zzEMaM) for a demo version.

My event starts on 5th and ends on 8th June(8 AM), if I change the end time to be >= 9 AM it works. Am I missing some config here or is this a bug or expected behaviour.

How can I highlight 8th of June in this case if there were events before 9 AM?

![screen shot 2017-06-26 at 14 21 33](https://user-images.githubusercontent.com/1013936/27541264-388a6938-5a7b-11e7-9ef5-f6ad22c931ce.png)
![screen shot 2017-06-26 at 14 21 52](https://user-images.githubusercontent.com/1013936/27541265-388a96c4-5a7b-11e7-9fc8-eab21093175d.png)

**Comment by harish0000** [comment]
check this link : https://fullcalendar.io/docs/event_rendering/nextDayThreshold/

to solve your problem add "**nextDayThreshold:"00:00:00**"

**Comment by Bramhananda** [comment]
Thanks for the update.
