### ISSUE TITLE
To show several users schedule in some date range

### ISSUE THREAD

**Issue by harish0000** [fullcalendar/fullcalendar#3734]
I have a requirement in which i want to show the employees schedule in some date range. On Left hand side there is a column having employees and on right there are multiple date columns.Is there any facility in full calendar to do that ? for reference i am attaching one screenshot .I want to implement the same.

![scheduleemployee](https://user-images.githubusercontent.com/22025958/27701386-42156378-5cf0-11e7-8a96-de340f3f4a87.png)

**Comment by MartijnWelker** [comment]
You can use the [Fullcalendar Scheduler](https://fullcalendar.io/scheduler/) for this

**Comment by arshaw** [comment]
yes, Scheduler's timeline view is exactly this. closing this ticket.
