### ISSUE TITLE
visibleRange not work in month view

### ISSUE THREAD

**Issue by mafeifan** [fullcalendar/fullcalendar#3736]
Hi there, 
I want to build the below calendar page, seems that the visibleRange options not work in month view.
note: the start date is 2016-10-19 and end date is 2016-11-15
![Image](http://i1.buimg.com/1949/95e945ec9814621e.png)

that's my jsbin, please take a look, thanks,  could anyone tell me how to fix it ?
http://jsbin.com/ricomod/4/edit?html,js,output

**Comment by haseebahmad109** [comment]
> Hi there,
> I want to build the below calendar page, seems that the visibleRange options not work in month view.
> note: the start date is 2016-10-19 and end date is 2016-11-15
> ![Image](https://camo.githubusercontent.com/b2582861452727643a2226008202735684b01ce8/687474703a2f2f69312e6275696d672e636f6d2f313934392f393565393435656339383134363231652e706e67)
> 
> that's my jsbin, please take a look, thanks, could anyone tell me how to fix it ?
> http://jsbin.com/ricomod/4/edit?html,js,output

Did you find any solution to this problem. I need to create a view that looks exactly like monthly view but with a different time range

**Comment by iranwz** [comment]
> > Hi there,
> > I want to build the below calendar page, seems that the visibleRange options not work in month view.
> > note: the start date is 2016-10-19 and end date is 2016-11-15
> > ![Image](https://camo.githubusercontent.com/b2582861452727643a2226008202735684b01ce8/687474703a2f2f69312e6275696d672e636f6d2f313934392f393565393435656339383134363231652e706e67)
> > that's my jsbin, please take a look, thanks, could anyone tell me how to fix it ?
> > http://jsbin.com/ricomod/4/edit?html,js,output
> 
> Did you find any solution to this problem. I need to create a view that looks exactly like monthly view but with a different time range

+1  I need this too

**Comment by abmahmoodi** [comment]
I have this problem too. Any solution?
