### ISSUE TITLE
Move start date via resize

### ISSUE THREAD

**Issue by arshaw** [fullcalendar/fullcalendar#374]
Originally reported on Google Code with ID 103

```
What steps will reproduce the problem?
1. Hover over end of calendar entry so icon changes to resize icon
2. Shrink or grow calendar entry by one or more day
3. Hover over beginning of calendar entry waiting for icon  to change to 
resize icon, which never happens.

What is the expected output? What do you see instead?
Similar support for moving startDate forward or backward.


What version of the product are you using? On what operating system?
v1.3 on a XAMPP windows installation.

Please provide any additional information below.

```

Reported by `impressthenet` on 2009-09-22 23:58:46

Imported with **7** stars.

**Comment by gsambrotta** [comment]
As far as i understood, this feature isn't implemented yet right? So i would like to say that we are also interested on having it :)

**Comment by Stichoza** [comment]
+1 for this feature. Many calendars (Apple Calendar, Sunrise, etc) have this feature and it would be cool it fullcalendar had it too.

I think it should be a feature which is disabled by default to maintain backwards compatibility.

**Comment by arshaw** [comment]
yes, FC should have this

**Comment by TejasCMehta** [comment]
Any update on this?

**Comment by TejasCMehta** [comment]
Can any one provide this custom js in FullCalendar 1.6.4 version ??

**Comment by dearrbear** [comment]
any news about this issue?

**Comment by rednebmas** [comment]
I don't know how stable this is (because it's not mentioned in the documentation), but when initializing fc, if you add the property `eventResizableFromStart: true` it enables resize from start.

**Comment by arshaw** [comment]
@rednebmas that will only work in Timeline views

**Comment by hunkydoryrepair** [comment]
Here's just a +1 on this issue. Using this as a shift planner, it's common to call an employee in early. When dragging to the new start time it is easy to forget what time they were initially scheduled to get off work, so even knowing how much to resize after moving is a problem.

**Comment by GalacticWeb** [comment]
+1 would be awesome to habe in fullcalendar 4

**Comment by cristiansimioni** [comment]
+1 on this feature! :smiley: 

If possible, plese include this feature on the next version of fullcalendar.

**Comment by anatel** [comment]
+1

**Comment by arshaw** [comment]
This issue has been addressed in the latest alpha release (4.0.0-alpha.2)
[See the blog post &raquo;](https://fullcalendar.io/blog/2018/10/release-v4-alpha2)

https://fullcalendar.io/docs/v4/eventResizableFromStart

**Comment by arshaw** [comment]
I'm closing this issue to signify that it's implemented (since v4-alpha2). I'll comment on this thread again when v4 is officially released.

**Comment by arshaw** [comment]
[V4 was officially released a few days ago!](https://fullcalendar.io/blog/2019/03/v4-officially-released)

If people want an example to be written in the docs, can you open another ticket?

**Comment by japhfortin** [comment]
How do we get the eventResizableFromStart to work?
https://codepen.io/japhfortin/pen/gEJKgd

**Comment by acerix** [comment]
> How do we get the eventResizableFromStart to work?
> https://codepen.io/japhfortin/pen/gEJKgd

@japhfortin It only works in dayGrid view, please open a new issue if you want to request it for timeGrid.

https://codepen.io/acerix/pen/aMgyao?&editable=true&editors=001
