### ISSUE TITLE
viewDisplay 404 in doc

### ISSUE THREAD

**Issue by netalex** [fullcalendar/fullcalendar#3740]
https://fullcalendar.io/docs/display/viewDisplay/ is missing

**Comment by espen** [comment]
Where is it linked from?

**Comment by jasteele12** [comment]
I can see it at least here at the bottom - See also: viewDisplay

https://fullcalendar.io/docs/views/

Looks like a leftover from v1...

**Comment by arshaw** [comment]
fixed on https://fullcalendar.io/docs/views/
