### ISSUE TITLE
Translations to Shqip

### ISSUE THREAD

**Issue by msamarek** [fullcalendar/fullcalendar#3742]
Hello.
We are using your great solution and actually we are missing translations to Sqhip (Albany, Kosovo). If you have full list of expressions to translate we can send you back translations. LCID 1052.

Thank you
Milan Samarek

**Comment by espen** [comment]
Check out the current locales in https://github.com/fullcalendar/fullcalendar/tree/master/locale

**Comment by msamarek** [comment]
sq.AL is missing can we add here translated one? There is not so much expressions.

**Comment by arshaw** [comment]
the 3 requirements to get a new locale into fc is
- jquery ui needs to already have a translations file. https://github.com/jquery/jquery-ui/blob/master/ui/i18n/datepicker-sq.js
- moment js needs to already have a translations file. https://github.com/moment/moment/blob/develop/locale/sq.js
- fc needs one too.

looks like all that is missing is fc's locale js file for Shqip. You can add one into here: https://github.com/fullcalendar/fullcalendar/tree/master/locale

please follow these brief instructions. "Contributing Locales"
https://github.com/fullcalendar/fullcalendar/blob/master/CONTRIBUTING.md#contributing-locales

I'm going to close this issue, but you can always open your own PR.
