### ISSUE TITLE
fetchEventSources Promise.resolve behaves differently in v3.4.0 vs v3.3.1

### ISSUE THREAD

**Issue by caseyjhol** [fullcalendar/fullcalendar#3744]
Changes were made in v3.4.0 to the promise function, and I'm not quite getting the same behavior as I was in v3.3.1. After calling `refetchEventSources`, I'm passing a variable through which is then used in my promise success function.

```js
  function refetchEventSources(sourceID) {
    return $calendar.fullCalendar('refetchEventSources', sourceID);
  }

  function refetchAndGetResponse(sourceID) {
    var previousEventCount = $calendar.fullCalendar( 'clientEvents').length;

    return refetchEventSources(sourceID).then(function() {
      return 'There were ' + previousEventCount + ' events.';
    });
  }

  $('.refetchEventSources').click(function() {
    refetchAndGetResponse('source2').then(function(response) {
      var currentEventCount = $calendar.fullCalendar( 'clientEvents').length;

      console.log('previous', response);
      console.log('current', 'There are ' + currentEventCount + ' events.');
    });
  });
```

In v3.3.1, the resulting `response` argument is the refetchAndGetResponse result (the phrase `'There were ' + n + ' events.'`). In v3.4.0, `response` is always an array of events (`prunedCache`). The correct response isn't being passed through. I'm not an expert in promises - is there something I'm missing?

Here are live examples (check the console):

- [v3.3.1](https://plnkr.co/edit/OuSB9szlF14I24mmQncq?p=preview)
- [v3.4.0](https://plnkr.co/edit/XpRRYwE5L0sfmfrln9WN?p=preview)

**Comment by caseyjhol** [comment]
Changing `attachImmediatelyResolvingThen` from 
```js
function attachImmediatelyResolvingThen(promise, val) {
	promise.then = function(onResolve) {
		if (typeof onResolve === 'function') {
			onResolve(val);
		}
		return promise; // for chaining
	};
}
```
```js
function attachImmediatelyResolvingThen(promise, val) {
	promise.then = function(onResolve) {
		if (typeof onResolve === 'function') {
			return Promise.resolve(onResolve(val));
		}
		return promise; // for chaining
	};
}
```
to fixes my particular problem, but not sure what other problems that might cause.

This is more similar to the resolve function in v3.3.1:

```js
promise.then = function(onFulfilled, onRejected) {
	if (typeof onFulfilled === 'function') {
		return Promise.resolve(onFulfilled(value));
	}
	return origThen.call(promise, onFulfilled, onRejected);
};
```

**Comment by arshaw** [comment]
@caseyjhol you're right, there was a behavior change with .then

i used your fix and pushed to master. will be released soon.

fix & tests: https://github.com/fullcalendar/fullcalendar/commit/7758d872cdba39f7f32ae7de4b9defb913cefd3d

**Comment by caseyjhol** [comment]
I can't get Promise.reject and `.catch` to work either. Not really an issue for me personally, just thought you might want a heads up.

**Comment by arshaw** [comment]
What about `Promise.reject` doesn't work?

I didn't implement `.catch`. My goal was NOT to make a completely Promise/A+ compliant object, but rather make a wrapper around jQuery's Deferred, make it easier to use, internally-used only. I never really meant to expose this to the public API, though I see you've found a way with `refetchEventSources`.

**Comment by arshaw** [comment]
Released in v3.5.0 ([blog post](https://fullcalendar.io/blog/2017/08/bootstrap-support-and-future-developments/#more-257))

**Comment by caseyjhol** [comment]
@arshaw It looks like there are still issues with promises in the latest version.

Compare:

- [v3.3.1](https://plnkr.co/edit/OuSB9szlF14I24mmQncq?p=preview)
- [v3.5.1](https://plnkr.co/edit/AAjs5r8whUWCIrVynAPj?p=preview)

It's not working at all now.

**Comment by caseyjhol** [comment]
I found a workaround (having my function creates a promise, and then in the eventSource function I call `Promise.resolve()` after the data is loaded). Still I think it would be handy to have the function return a promise (I see there's another issue for it already).
