### ISSUE TITLE
Request: businessHours by date 

### ISSUE THREAD

**Issue by Lacitomi** [fullcalendar/fullcalendar#3747]
Hi
I'm looking for a way how to use a businessHours for date.
I think, its not possible at the moment.
eg:
businessHours: [ 
                    {
                        date: "2017-08-19"
                        start: '10:00',
                        end: '18:00'
                    },
                    {
                         date: "2017-08-25"
                        start: '9:00', 
                        end: '16:00' 
                    }
                ]

The problem for "dow: [ 1, 2 ]", that set the hours all monday, and all thuesday.

If there isn't an option for this, does anyone have any advice for possible workarounds?

**Comment by espen** [comment]
You can use [background events](https://fullcalendar.io/docs/event_rendering/Background_Events/) instead.
