### ISSUE TITLE
How to block dragging event on fullcalendar with specific date range?

### ISSUE THREAD

**Issue by HELMAB** [fullcalendar/fullcalendar#3748]
![issuse](https://user-images.githubusercontent.com/15307857/28348499-8664094a-6c67-11e7-9247-5c9b38d435f1.png)

**Comment by cptx032** [comment]
You can use `eventDrop` callback calling `revertFunc` if the event is moved to a wrong range (https://fullcalendar.io/docs/event_ui/eventDrop/)

**Comment by HELMAB** [comment]
@cptx032 Thanks for your help. Could I have a solution better than this? I mean that some technic fullcalendar configuration.

**Comment by Mihai-github** [comment]
Hi, a bit late to the "party" but there's no official answer on how you can limit the max drag length.

Example: Able to drag events to max 3 hours from the hour they are dragged ( current hour 14 - max draggable hour 17. )

Thanks in advance 👍
