### ISSUE TITLE
Events not displaying if start date is prior to today, yet event spans into the future.

### ISSUE THREAD

**Issue by bjhansen** [fullcalendar/fullcalendar#3749]
We are using the calendar to build a reservation system where people can book rooms. The problem arises when there is a reservation that starts in the past, includes today, and then the checkout is in the future.

Let's say today is 7/19/2017 and the reservation is from 7/16/2017 to 7/22/2017.

When we load any view (timelineDay, timelineWeek, timeline2Week) we are not seeing events that exist in the data if they 'span' today (current day).

Please see full outline of issue with code and screenshots on StackOverflow:
[https://stackoverflow.com/questions/45201498/fullcalendar-events-not-displaying-if-start-date-is-prior-to-today-yet-event-sp](https://stackoverflow.com/questions/45201498/fullcalendar-events-not-displaying-if-start-date-is-prior-to-today-yet-event-sp)

**Comment by espen** [comment]
Try disabling [lazyFetching](https://fullcalendar.io/docs/event_data/lazyFetching/) to see if that helps.

**Comment by bjhansen** [comment]
Than you espen.
Tried to disable lazyFetching to no avail.  I'm still poking around in there, but I'm not finding the solution yet.  If someone has any other ideas, please do share!

**Comment by espen** [comment]
Can you see that the request is actually returning these events when you are changing view/dates?

**Comment by arshaw** [comment]
@bjhansen , would you be able to post a [runnable, stripped-down demonstration of the bug](http://fullcalendar.io/wiki/Reduced-Test-Cases/)? Would really appreciate it because the time saved reproducing will be time spent fixing.
