### ISSUE TITLE
Event editable only by dragging to another day, not able to edit start or duration through drag and drop

### ISSUE THREAD

**Issue by ppazos** [fullcalendar/fullcalendar#3750]
Created a calendar and added an event that looks like this:

```
          {
            title: "hola",
            start: "2017-07-21T10:00-03:00", // NO TZ is GMT
            end:   "2017-07-22T14:30-03:00",
            color: "#9B8FCD",
            textColor: "#FFFFFF",
            editable: true,
            startEditable: true,
            durationEditable: true
          }
```

Dragging from any point of the event, just moves the event around between days. Also tested with:

eventDurationEditable: true and eventStartEditable: true as options, nothing works.

Tested on MacOs / Chrome. Full calendar 3.4.0.

Is there an example of start editable and duration editable by dragging?

Thanks.

**Comment by cptx032** [comment]
If you switch to "day view" or "week view" you will be able to change the "duration range"

**Comment by qwe852147** [comment]
Unless you make event to all day event, you can't resize it in month view .

**Comment by arshaw** [comment]
Would you be able to post a [runnable, stripped-down demonstration of the bug](http://fullcalendar.io/wiki/Reduced-Test-Cases/)? Would really appreciate it because the time saved reproducing will be time spent fixing.
