### ISSUE TITLE
When switching from any view to listview no eventAfterRender is called

### ISSUE THREAD

**Issue by ArnoldZoutman** [fullcalendar/fullcalendar#3751]
I don't know if this is a designchoice or a bug.

The eventAfterRender-event doesn't fire when swicthing to the listWeek view.

As I demonstrate in the added pen:
https://codepen.io/ArnoldZoutman/pen/VWovaL?editors=1111

We use the afterEventRender to add certain functionalities to specific events. These functionalities are also needed in the listview.

**Comment by cptx032** [comment]
What you want to do cant be done with `viewRender` callback (https://fullcalendar.io/docs/display/viewRender/)?

**Comment by ArnoldZoutman** [comment]
Alas, no...

We bind the functionality to the specific event. The viewRender doesn't have the event callback.

viewRender : function( view, element ) {} VS. eventAfterRender: function( **event**, element, view ) { }

**Comment by caseyjhol** [comment]
Any chance you could use eventRender instead? Might also be able to get by using viewRender and then utilizing `clientEvents` to make the necessary changes. https://fullcalendar.io/docs/event_data/clientEvents/

I'd have to look over the code more closely, but I'm assuming eventAfterRender is probably supposed to be called.

**Comment by ArnoldZoutman** [comment]
Again I have to respond negative.

While the event is rendered I cannot bind to the specific HTML element that is/will be rendered. 
For example:

I want to bind to the `<tr class="fc-list-item">...</tr>` that is rendered. From the eventRender I cannot acces that element, from the eventAfterRender I can (in the 'normal' views anyway ;) ).

**Comment by caseyjhol** [comment]
It looks like this problem is resolved in the current version in `master`, so it should be fixed in the next release, v3.5.0.

**Comment by ArnoldZoutman** [comment]
Ah, that's nice!

Any idea when the next release is planned?

**Comment by ArnoldZoutman** [comment]
@caseyjhol Do you have any idea when the next release is planned?

**Comment by caseyjhol** [comment]
@ArnoldZoutman No clue - @arshaw is responsible for each release. Commits have been increasing in frequency, so I wouldn't be surprised if it was released within the next month. If you absolutely need this feature right away, and don't mind having an "alpha" version, you can compile the version in the master branch and use that.

**Comment by arshaw** [comment]
I'll verify this is fixed for the upcoming v3.5.0 release. still doing some refactoring on it.

**Comment by ArnoldZoutman** [comment]
Thanks in advance! 👍

**Comment by arshaw** [comment]
this is fixed in the already-release 3.5.1
https://codepen.io/arshaw/pen/GMQqKM?editors=0010

**Comment by arshaw** [comment]
seems to have been fixed in 3.5.0
