### ISSUE TITLE
Drag many events at a time [feature request]

### ISSUE THREAD

**Issue by cptx032** [fullcalendar/fullcalendar#3752]
Sorry if this is duplicated, i search in issues and in pull requests but i didnt find anything like.

**Feature request**
Would be nice if I could select multiple events at once and drag them all. Maybe using the `selectable` options or control clicking the events

**Comment by MartijnWelker** [comment]
The way I've got this implemented is as follows:
- On eventclick: user has shift selected ? add event in an array, else overwrite the array
- On drag end: loop over all the events in the array and clone the start/end from the dragged event

Working demo [here](https://codepen.io/anon/pen/eEOmLp?editors=0010)

**Comment by cptx032** [comment]
Thank you, this works for my purpose :D. Now I'm doing something like that. In my problem I need preserve the difference between events, so I need calculate the difference between events selected and the event that are being dragged. But would be nice see the selected events being dragged together because, visually, the user will only know that he is dragging many events after he had finished the dragging.

**Comment by MartijnWelker** [comment]
@cptx032 To preserve the difference you can use the `delta` argument (as described in my code comment). A delta is the difference between two moments, so by adding the difference on the start and end of all events they will all move relatively

**Comment by arshaw** [comment]
dup of
#2253
&uarr;
Could you please visit the link, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates?
