### ISSUE TITLE
Wrong date chosen day-click event

### ISSUE THREAD

**Issue by rosshigh** [fullcalendar/fullcalendar#3753]
This may be a misunderstanding of how dates are processed in JavaScript but I'm having an issue that the date that's passed to the day-click event handler is always the day before the day I click.  If I click July 12 this is the moment I get (it's 10:00 am CDT):

`Moment {_isAMomentObject: true, _isUTC: true, _offset: 0, _pf: Object, _locale: f…}
_ambigTime: true
_ambigZone: true
_d: Tue Jul 11 2017 19:00:00 GMT-0500 (Central Daylight Time)
_fullCalendar: true
_isAMomentObject: true
_isUTC: true
_isValid: true
_locale: f
_offset: 0
_pf: Object
__proto__: Object`

**Comment by arshaw** [comment]
Would you be able to post a [runnable, stripped-down demonstration of the bug](http://fullcalendar.io/wiki/Reduced-Test-Cases/)? Would really appreciate it because the time saved reproducing will be time spent fixing.

**Comment by rosshigh** [comment]
The problem is because the date is shown in GMT (-5 hours for the central time zone).  When I bound it to a date control using Aurelia, the data control didn't take that into account.  I'm sure there is a better way to handle it but I ended up adding 5 hours to the date and it works. Sometimes you have to just hold your nose and do what works to keep moving along.  Thanks.
