### ISSUE TITLE
Event Days Exclude Weekends

### ISSUE THREAD

**Issue by hsuanweifu** [fullcalendar/fullcalendar#3754]
Help / Feature Request

The result should be Friday to next Monday if an event starts from Monday to Tuesday and later dragged to Friday. And if it's dragged back to Monday it will start from Monday to Tuesday.

Visual Example
S M T W T F S
X O O X X X X

to 

S M T W T F S
X X X X X O X
X O X X X X X

I have tried to use the data structure for a event.
```
      {
        title: 'Long Event',
        start: '2016-09-07',
        end: '2016-09-10',
        weekend: false,
      }
```

**Comment by arshaw** [comment]
dup of
https://github.com/fullcalendar/fullcalendar/issues/338
&uarr;
Could you please visit the link, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates?

**Comment by trigbit-sukhwinder** [comment]
I didnt get the answer of this question yet.... can you please help me out

**Comment by trigbit-sukhwinder** [comment]
If my event is dropped on friday and the event is of more than timing from busineess hours then event should move to monday automatically

**Comment by acerix** [comment]
@trigbit-sukhwinder The original issue is still open:
https://github.com/fullcalendar/fullcalendar/issues/338
↑
Could you please visit the link, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates?

**Comment by Lynn-cc** [comment]
I have the same problem, and `eventExclude` seems not a right property because of the typescript errors.

**Comment by starnapp** [comment]
Has this been solved? For timeline view non of these options seem to work. It is kind of useless to try to schedule tasks on a schedule without being able to skip non working hours.
