### ISSUE TITLE
defaultTimedEventDuration can't be set dynamically

### ISSUE THREAD

**Issue by jespersh** [fullcalendar/fullcalendar#3755]
The defaultTimedEventDuration can't be set dynamically as stated here for future events: https://fullcalendar.io/docs/utilities/dynamic_options/ 

> Some options affect processing of event data. Dynamically setting them will not change current event data, but will take effect for future event fetches:
>    defaultAllDayEventDuration
>    defaultTimedEventDuration

As I see it, then defaultTimedEventDuration is set internally once during calendar's constructor call:
https://github.com/fullcalendar/fullcalendar/blob/9e4f2bd725b0d55cc02a193aad5dfbfd20e4fc80/src/Calendar.moment.js#L12

So while this doesn't work:
`$('#calendar').fullCalendar("option", "defaultTimedEventDuration", "00:15:00")`
This does:
`$('#calendar').fullCalendar("getView").calendar.defaultTimedEventDuration = moment.duration("00:15:00")`

defaultAllDayEventDuration could be affected too, but I haven't tested that.

**Comment by arshaw** [comment]
confirmed. thanks.

**Comment by jairdeon** [comment]
Thanks, @jespersh. You save me.

**Comment by arshaw** [comment]
this is almost definitely fixed in v5. would need a recreation to know
