### ISSUE TITLE
Can't select dates / ranges in iOS 10.3 when "selectable": true

### ISSUE THREAD

**Issue by derekaug** [fullcalendar/fullcalendar#3757]
Here's the link to the JSBin utilizing fullcalendar 3.4.0:
https://jsbin.com/disateb/edit?html,output

To reproduce, on any iOS 10.3 device try to click on a date or select a range of dates, the date will not be selected. I was able to reproduce this on the Simulator on OS X.

**Comment by paw3lx** [comment]
Hi @derekaug 
I have checked your example on Safari on iOS 10.3.3 (iPhone) and for me everything is working good. You have to click on the day and hold for 3 seconds. This will select day. Then you can select other days by moving your finger.

**Comment by arshaw** [comment]
@derekaug are you sure this isn't related to [selectLongPressDelay](https://fullcalendar.io/docs/selection/selectLongPressDelay/), which is activated by default?

**Comment by derekaug** [comment]
that is probably the issue, I will try this and report back.
