### ISSUE TITLE
event.dow doesn't support 'ISO' weekNumberCalculation

### ISSUE THREAD

**Issue by DAfanasyev** [fullcalendar/fullcalendar#3758]
Hi,

Would it be a good idea to support 'ISO' weekNumberCalculation in event.dow?

**Comment by arshaw** [comment]
what do you mean? the `dow` property for business-hours is an integer denoting sunday-saturday. how do ISO week numbers affect that?

**Comment by DAfanasyev** [comment]
Hi,

OK, maybe weekNumberCalculation property is not the best one for behavior I'm expecting, but still dow is also used for recurrent events, not only for business-hours, so if server works in ISO format, then days in a week numbered starting from 1 - Monday and up to 7 - Sunday. 
Actually, moment follows this rule for ISO mode https://momentjs.com/docs/#/get-set/iso-weekday
