### ISSUE TITLE
updateEvent doesn't update event start

### ISSUE THREAD

**Issue by hsuanweifu** [fullcalendar/fullcalendar#3759]
When calling updateEvent, the event will move to the correct column on the calendar and the title is updated. However the start data does not get updated"

1. Click event: print out today -> update to 2017-07-01 -> update event
2. Click event again: print out **today (should be 2017-07-01 now)**

```
        eventClick: function (calEvent, jsEvent, view) {

            console.log(calEvent);
            calEvent.title = 'New Event Title';
            calEvent.start = moment("2017-07-01", "YYYY-MM-DD");
            $(this.calendar.nativeElement).fullCalendar('updateEvent', calEvent);
        }.bind(this)
```

```
        events: function (start, end, timezone, callback) {
            let events = [
                {
                    title: 'today',
                    start: moment(new Date()).format("YYYY-MM-DD"),
                }
            ];
            callback(events);
        }
```

**Comment by arshaw** [comment]
Would you be able to post a [runnable, stripped-down demonstration of the bug](http://fullcalendar.io/wiki/Reduced-Test-Cases/)? Would really appreciate it because the time saved reproducing will be time spent fixing.
