### ISSUE TITLE
about“getEventSources”

### ISSUE THREAD

**Issue by mcltl** [fullcalendar/fullcalendar#3760]
source is
“	function getEventSources() {
		return sources.slice(1); // returns a shallow copy of sources with stickySource removed
	}
”
why 1，began index  is 0

return  “[Object { events=[4],  _fetchId=1,  _status="resolved"}]” 
version 3.4.0 
thanks

**Comment by caseyjhol** [comment]
Index 0 is stickySource. As described in the comment, sources.slice(1) is a shallow copy of sources with stickySource removed.
