### ISSUE TITLE
Secod resize of selected time range on week view

### ISSUE THREAD

**Issue by nickitatkach** [fullcalendar/fullcalendar#3764]
Hi.

I have noticed such a behavior in FC.

1. Under week view select time range without creating new event.
2. Try to change time range - event dissapears (javascript error occurs "Cannot read property 'clone' of undefined").

Here is a short video of described bug.
https://www.dropbox.com/s/2vrjiutzim38k9z/fullcalendar_bug.webm?dl=0

Also here is a pen with small example.
https://codepen.io/anon/pen/mMyReo

Is it normal behavior?

P.S.  I do not need create an event after time range selection.

**Comment by arshaw** [comment]
confirmed. thanks for the high-quality bug report.

**Comment by arshaw** [comment]
queued for release

**Comment by arshaw** [comment]
released in 3.8.1
