### ISSUE TITLE
Resize limit

### ISSUE THREAD

**Issue by qwe852147** [fullcalendar/fullcalendar#3766]
It possible to config event resize duration or end time limit?
example 
I resize an event 
```
{
 start: moment("2017-07-27T02:09:00.460Z"),
 end: moment("2017-07-28T02:09:00.460Z")
}
```
When I config the end limit is  "2017-07-29", the event length max will not over "2017-07-29T23:59:59.999Z"

or  I config the duration is Day:2 , the event length max will not over "2017-07-29T02:09:00.460Z"

**Comment by arshaw** [comment]
Could you post a video, a sequence of steps, or a [runnable, stripped-down demonstration](http://fullcalendar.io/wiki/Reduced-Test-Cases/)? I'm having trouble understanding what your question is.
