### ISSUE TITLE
Division of the day into time intervals in the representation of the month.

### ISSUE THREAD

**Issue by andykov** [fullcalendar/fullcalendar#3768]
Hello!

Is it possible to divide the day into two or more parts with different or identical intervals of time?

I need to stretch the line at different intervals as follows:

- from 00:00 to 11:59
- from 12:00 to 14:59
- from 15:00 to 17:59
- from 18:00 to 23:59

[Here is a visual example](http://dl4.joxi.net/drive/2017/07/29/0010/1659/710267/67/fe726b02da.jpg)
[And this general picture of what I need](http://dl3.joxi.net/drive/2017/07/29/0010/1659/710267/67/bc06e2ee05.jpg)

Or at least divide into two parts:
- from 00:00 to 11:59
- from 12:00 to 23:59

There is a similar [demo](https://fullcalendar.io/js/fullcalendar-scheduler-1.6.2/demos/scale.html).
But this works if the timeline is displayed. I need the same behavior only in the days of the month.
Is it even possible?

**Comment by arshaw** [comment]
you'd like a month view where individual day cells are partitioned into pieces of time? in my opinion that would appear rather busy, and there might not even be enough space.
