### ISSUE TITLE
Custom title for day View

### ISSUE THREAD

**Issue by webtechie94** [fullcalendar/fullcalendar#3770]
Hi,

I'm working on the project using this plugin, where I think to add title for the columns created for the events in day view and popover window for the +more.
I searched in the documentation and googled lot, but I couldn't able to find out the solution.

If the said feature might be required as a feature in this plugin is very useful.

I'm attaching herewith the screenshot of the feature I'm asking for better understanding,

![fcimage](https://user-images.githubusercontent.com/16777266/28762922-d34e569c-75d7-11e7-8e53-c60401e9a8a4.png)

**Comment by arshaw** [comment]
you might be able to hack in your own DOM nodes when the [viewRender](https://fullcalendar.io/docs/display/viewRender/) trigger fires
