### ISSUE TITLE
Same Time with a startDate != endDate -> bug

### ISSUE THREAD

**Issue by Stan92** [fullcalendar/fullcalendar#3773]
Hi,
I m facing to a strange behavior.
My start date is  2017-07-29T08:00:00
My end date is 2017-07-30T08:00:00
From the Fullcalendar, the event is only shown on the 07/29/2017 view.
If I change the end date with 2017-07-30T10:00:00, I get the 07/29 & 07/29 views tagged.
Any idea, how to fix this issue?
Thanks

**Comment by arshaw** [comment]
set `nextDayThreshold` to `"00:00"`. see this discussion https://github.com/fullcalendar/fullcalendar/issues/2902
