### ISSUE TITLE
My ranges in event don't work

### ISSUE THREAD

**Issue by zeing** [fullcalendar/fullcalendar#3776]
this is my code [https://jsfiddle.net/zeing/msLsr7pu/10/](https://jsfiddle.net/zeing/msLsr7pu/10/)
```
ranges: [{ 
          start: moment().startOf('week').day("Monday"), 
          end: moment().endOf('week').add(7,'day')
 }]
```
i follow my code from [http://jsfiddle.net/slicedtoad/duu0dx2t/5/](http://jsfiddle.net/slicedtoad/duu0dx2t/5/) ranges is next two weeks of monthly

but my code  range i fix don't work  
how to fix it 

thank you

**Comment by paw3lx** [comment]
Hi @zeing,
I don't know if I understood you, but it could be problem with hour and minutes part in the start range. You need to set hour and minutes to 0  in: `moment().startOf('week').day("Monday")`. Then every event on this day will be visible. 

[https://jsfiddle.net/msLsr7pu/14/](https://jsfiddle.net/msLsr7pu/14/)

**Comment by zeing** [comment]
sorry for my english ,  
i have problem about ranges of "My repeating event"  i fix this event twice a week ( 1st  and 2nd week ) 

`          events: [
                {
                    id: 1,
                    title:"My repeating event",
                    start: "12:00:00",
                    end: "12:30:00",
                    dow: [ 1, 4 ], // Repeat monday and thursday
                    ranges: [{ 
                        start: moment().startOf('week').day("Monday"), start in 1st week 
                        end: moment().endOf('week').add(7,'day')  // end of 2nd week
                    }]
                },

            ]`

but my result  is "My repeating event" repeat until end of **validRange** it don't stop  end of 2nd week of month 

do you understand me ? TT

**Comment by lesilent** [comment]
Your code is missing the eventRender option that specifies whether to render the event between the ranges:

[https://jsfiddle.net/msLsr7pu/15/](https://jsfiddle.net/msLsr7pu/15/)

**Comment by zeing** [comment]
omg i miss , thank you

On Aug 6, 2560, 4:16 AM +0700, lesilent <notifications@github.com>, wrote:

Your code is missing the eventRender option that specifies whether to render the event between the ranges:

https://jsfiddle.net/msLsr7pu/15/
