### ISSUE TITLE
jquery JS and jquery-UI redirect to google

### ISSUE THREAD

**Issue by turans** [fullcalendar/fullcalendar#3777]
Hello.

I was using this two links:
http://fullcalendar.io/js/fullcalendar-2.1.1/lib/jquery.min.js
http://fullcalendar.io/js/fullcalendar-2.1.1/lib/jquery-ui.custom.min.js

But my website started to redirect to google. When I tracked down I found that these two have this code: 'window.location.href = "https://www.google.com/search?q=hotlinking";'.

I think this is an error or someone change the files!

**Comment by lesilent** [comment]
You should be using the following urls instead:

[https://cdnjs.cloudflare.com/ajax/libs/jquery/1.12.1/jquery.min.js](https://cdnjs.cloudflare.com/ajax/libs/jquery/1.12.1/jquery.min.js)
[https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.js](https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.js)

The css files should also be loaded from that location as well.

**Comment by arshaw** [comment]
see my latest comment here: https://github.com/fullcalendar/fullcalendar/issues/3772#issuecomment-320296933 (please respond on that thread of you have feedback)
