### ISSUE TITLE
Check dayClick event from which grid

### ISSUE THREAD

**Issue by qwe852147** [fullcalendar/fullcalendar#3779]
How to check the dayclick event is from allday grid or other grid?

**Comment by lesilent** [comment]
The view object is passed to the dayClick function. So you would use the view object to determine what grid is displayed. Below is an abbreviated example:

```
$('#calendar').fullCalendar({
    dayClick: function(date, jsEvent, view) {
        alert('Current view: ' + view.name);
    }
});
```

**Comment by qwe852147** [comment]
But this method doesn't show I click "all-day" date grid or other grid in agenda view

**Comment by lesilent** [comment]
The "all-day" date has a start time of midnight, so you can check date that's passed:

```
$('#calendar').fullCalendar({
    dayClick: function(date, jsEvent, view) {
        if (date.hour() == 0 && date.minute() == 0) {
            alert('all-day');
        } else {
            alert(date.format('LT'));
        }
    }
});
```

**Comment by arshaw** [comment]
you can leverage `.hasTime()`

```js
$('#calendar').fullCalendar({
    dayClick: function(date, jsEvent, view) {
        if (!date.hasTime()) {
            alert('all-day');
        } else {
            alert(date.format('LT'));
        }
    }
});
```

more info: https://fullcalendar.io/docs/utilities/Moment/
