### ISSUE TITLE
Output at once three months (quarter)

### ISSUE THREAD

**Issue by mefist1990** [fullcalendar/fullcalendar#3780]
Tell me how to do it in one script, so that it displays three months at once, and not one. Quarter. And there were all the possibilities of this calendar. Thank you

**Comment by lesilent** [comment]
This is not possible at this time, but might be available in a future update. I believe currently the only way to display 3 months at once is to do 3 different calendars.

**Comment by mefist1990** [comment]
And how to make navigation on the same calendar work all at once?

**Comment by arshaw** [comment]
aside from initializing 3 calendars, you can make a custom view with a duration of 3 months:
https://fullcalendar.io/docs/views/Custom_Views/

however, it won't have breaks in between the months.

this is the feature request:
https://github.com/fullcalendar/fullcalendar/issues/470
&uarr;
Could you please visit the link, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates?
