### ISSUE TITLE
Unable to drag & drop in agendaDay view after FullCalendar v3.3.0 / Scheduler v1.6.0

### ISSUE THREAD

**Issue by mintotsai** [fullcalendar/fullcalendar#3786]
Hi there!

I'm seeing an issue where drag and drop is not working in agendaDay view. When dragging, the UI gives a circle with a line through it and when I drop the event, it reverts back to the original position.

![cursor_and_salesforce_-_enterprise_edition](https://user-images.githubusercontent.com/1557318/29214905-86b80c48-7e6e-11e7-83c7-31dabd5449c8.png)

The editable option is set to true. And, Drag and drop is working in the Month view.

In addition, the code works with FullCalendar v3.2.0 / Scheduler v1.5.1 and prior. And, breaks on FullCalendar v3.3.0 / Scheduler v1.6.0 and after.

Apologies for the lack of jsfiddle, I'm only seeing this issue on one system with customer data.

Any idea on what may be causing this?

**Comment by mintotsai** [comment]
Closing, until I can get more information to share.

**Comment by jamesdixon** [comment]
@mintotsai were you able to figure this out?

**Comment by jamesdixon** [comment]
For what it's worth, in my app, I only allow drag + drop on `agendaDay` view. I used to set the `editable` flag in my `eventRender` function, but for some reason it no longer works in 3.3+/1.6+. 

To fix it, I handled setting that flag in `eventDataTransform`.

**Comment by mintotsai** [comment]
@jamesdixon I did figure it out. If my memory is correct, I was not populating the resourceId on the event.
