### ISSUE TITLE
Browser becomes freeze and unresponsive.

### ISSUE THREAD

**Issue by adilsaeed31** [fullcalendar/fullcalendar#3789]
HI,

I'm using this library in my project, due to some reason when user try to switch the views like "month, week, day , list", Sometime browser becomes freeze and unresponsive. How to resolve this issue ?

How I'm using this library,

Im using VueJs for components, This is also a component but when Vuejs mount the DOM then I'm initializing this FullCalendar jquery library into next Tick callback. That's it.

Thanks
Adil

**Comment by espen** [comment]
> You MUST have a JSBin recreation, or else your issue will be CLOSED without explanation.
> Instructions: http://fullcalendar.io/wiki/Reporting-Bugs/
