### ISSUE TITLE
Business hours for specific Dates in full calendar

### ISSUE THREAD

**Issue by anilkumar-nyros** [fullcalendar/fullcalendar#3790]
Hi There,
I am using full calendar to let users book an specific available time  set by the clients. So have to disable the fullcalendar when the client is not available. Currently I am able to set multiple business hours for whole calendar i.e. all the years and months.

But I am not able set for specific chunks of date ranges. I need to set different business hours for different date ranges in full calendar. For example  15th Aug 2017 i want to set business hours 10:00 AM to 01:00 PM  and 04:00 PM to 08:00 PM ,16th Aug 2017 i want to set business hours 8:00 AM to 04:00 PM  and 09:00 PM to 11:00 PM ,..etc. Remaining Date should be disabled for creating event for whole year and above specified date and time should be enabled to create event. I tried many options but it seems there aren't enough options to fulfill my requirement. So calling for some help if someone can.

**Comment by espen** [comment]
Business hours is only per weekday. You can use background events to accomplish this for specific dates. See other issues about this.

**Comment by arshaw** [comment]
you can use background events
https://fullcalendar.io/docs/event_rendering/Background_Events/

and if you want to constrain all events to fit into those business hours, you can use this:
https://fullcalendar.io/docs/event_ui/eventConstraint/
and set it do the same ID as your background events

**Comment by Pinaksh** [comment]
We have specific requirement similar to this. By default we have set business hour for weekends now we need to enable the weekend for specific date, which is not possible with background events. Can you suggest some idea for enable/disable business hours for a particular date only. not day specific to week. 
Thanks in advance.

**Comment by RyanEwen** [comment]
I am in the same boat where I would like to support overriding the business hours of particular dates, but this is difficult to do with background events, as if the hours are being extended as opposed to shortened, the original hours still grey-out part of the day. It's not possible to counter-that as far as I can tell.

**Comment by RyanEwen** [comment]
I worked around this using CSS and background events. It means you can't use background events for other purposes, however.

What I do is loop through my list of exceptions/holidays and add background events like so:
```javascript
business_hours.exceptions.forEach((exception) => {
            // all day exceptions
            if (!exception.open || !exception.close) {
                this.calendar.addEvent({
                    rendering: 'background',
                    className: 'fc-nonbusiness',
                    allDay: true,
                    start: exception.date,
                    end: exception.date
                })
            // standard exceptions
            } else {
                this.calendar.addEvent({
                    rendering: 'background',
                    className: 'fc-nonbusiness',
                    allDay: false,
                    start: exception.date + 'T00:00',
                    end: exception.date + 'T' + exception.open
                })

                this.calendar.addEvent({
                    rendering: 'background',
                    className: 'fc-nonbusiness',
                    allDay: false,
                    start: exception.date + 'T' + exception.close,
                    end: exception.date + 'T24:00'
                })
            }
        })
```

Note that I don't use `inverse-background` as I couldn't find a good way to make that work. Instead I create events from 00:00 -> open and from close -> 24:00.

Then I use this CSS rule to hide the business hour container, if the adjacent background events container is not empty:

```css
.fc .fc-bgevent-container:not(:empty) ~ .fc-business-container {
    display: none;
}
```

Now if I have background events, I see them instead of business hours.

**Comment by samvloeberghs** [comment]
This seems to be working fine in `v5` now.

**Comment by Wellers0n** [comment]
> How does it work in v5?

How does it work in v5?

**Comment by danielR2001** [comment]
> This seems to be working fine in `v5` now.

How does it work in v5?
