### ISSUE TITLE
Colum Format show OBJECT object PT_BR

### ISSUE THREAD

**Issue by HugoOliveiraThor** [fullcalendar/fullcalendar#3791]
Hello Guys , i trying to use colum format to put long name in the agenda week . 
I use the colum format 
columnFormat: {
        month: 'ddd',
        week: 'ddd d',
        day: 'dddd'
    },
and i use the lang pt-br , but the problem is always show OBJECT in the header . 
I reproduce this in the jsfiddle
https://jsfiddle.net/HugoOliveira/owet2j51/31/
If anyone can help me . 
Thanks !

**Comment by lesilent** [comment]
Since you're specifying different formats for each view, you should probably use view-specific options to specify the format instead:

[https://jsfiddle.net/owet2j51/35/](https://jsfiddle.net/owet2j51/35/)

**Comment by HugoOliveiraThor** [comment]
Thanks @lesilent is works perfectly !!!!
