### ISSUE TITLE
Calendar label doesnt occupy last day

### ISSUE THREAD

**Issue by xpandgit888** [fullcalendar/fullcalendar#3792]
![1](https://user-images.githubusercontent.com/31031599/29311071-ee57fc42-81e2-11e7-9a56-c36691008147.PNG)
![2](https://user-images.githubusercontent.com/31031599/29311073-f261ecc6-81e2-11e7-85cd-924257612d88.PNG)

Example scenario: Event set for 02/08/2017 to 04/082017.

The label only occupies 02/08/2017 to 03/08/2017. But not 04/08/2017.

for refer picture 1 and 2.

**Comment by arshaw** [comment]
that's because event ends are exclusive:
https://fullcalendar.io/docs/event_data/Event_Object/
