### ISSUE TITLE
Show durationInMinutes in 'fc-time' with eventResize

### ISSUE THREAD

**Issue by HugoOliveiraThor** [fullcalendar/fullcalendar#3795]
I´m trying to append a value in a class 'fc-time' of an event to show a duration in minutes of it .
I´m show in the jsfiddle below:
https://jsfiddle.net/HugoOliveira/owet2j51/79/

My objective is to show the time of start and end event and more a time in minutes of it . 
Example : 08:00 - 09:30 (1h 30m)
I make in eventResize when i stop resizing i make a action to append a value in fc-time and if a put a console.log in that element he is changed but in the event doesnt appear nothing . 
 `eventResize(event, delta, revertFunc, jsEvent, ui, view) {
              .... my code
              const timeDuration = utils.tituloEventoFormatadoHoraInicialEMinutos(event.start, event.end);
              $(this).find('.fc-time').append(` ( ${timeDuration} ) `);
              console.log($(this).find('.fc-time'));
            },`
Probably i´m doing something wrong , could be the place that i doing this or the code ?
Or I can´t do that ?
If anyone can help , maybe that is a function that do that but I didnt find . 
Thanks !

**Comment by arshaw** [comment]
please see the workaround technique i just posted here:
https://github.com/fullcalendar/fullcalendar/issues/3674#issuecomment-326391532
