### ISSUE TITLE
Stop Right Click on Events

### ISSUE THREAD

**Issue by sandeepparihar** [fullcalendar/fullcalendar#3796]
I want to show some option at right click on Calendar. But i want to make right click disable on Events.
I am using this code but its not working.

$('#calendar:not(".fc-event")').on('mousedown', function (event) {
				    var keycode = ( event.keyCode ? event.keyCode : event.which );
				    if (keycode === 3) 
                                   {
				        alert('----event right click---');
				       document.getElementById('showSchedulerBlock').style.display='block';
				    }
				});

**Comment by lesilent** [comment]
One way to disable right-click on events is to use the eventRender option like so:

```
eventRender: function(event, element) {
    element.contextmenu(false);
}
```

**Comment by arshaw** [comment]
`eventRender` is the way to go
