### ISSUE TITLE
setState on event click in react component

### ISSUE THREAD

**Issue by devendrabohre** [fullcalendar/fullcalendar#3798]
@arshaw  there is a problem in set state on click of any event in react component, I am doing such thing.
eventClick: function(calEvent, jsEvent, view) {
			  	console.log("event and view",calEvent,view.name)
			  	_that.setState({clickedevent:calEvent})
			  	$('#eventview').show();
		        $(this).css('border-color', 'red');
    		},
but there is coming an error of react minified #31
https://facebook.github.io/react/docs/error-decoder.html?invariant=31&args[]=Sat%20Aug%2012%202017%2012%3A00%3A00%20GMT%2B0530%20(IST)&args[]=

**Comment by arshaw** [comment]
how are you initializing fullcalendar from react? are you using some sort of adapter?

**Comment by arshaw** [comment]
Would you be able to post a [runnable, stripped-down demonstration of the bug](http://fullcalendar.io/wiki/Reduced-Test-Cases/)? Would really appreciate it because the time saved reproducing will be time spent fixing.
