### ISSUE TITLE
Full calendar touch support. Can left and right swipes be customized?

### ISSUE THREAD

**Issue by devanand** [fullcalendar/fullcalendar#3800]
I have been trying to customize swiping from left and swiping from right to go to the day before and day after. But I have yet to stumble upon a solution. Is there a way to customize swiping in fullcalendar?

**Comment by arshaw** [comment]
dup:
https://github.com/fullcalendar/fullcalendar/issues/3666
&uarr;
Could you please visit the link, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates?
