### ISSUE TITLE
SCRIPT5007: Unhandled exception at line 8, column 2987 in http://.../fullcalendar.min, JavaScript runtime error: Unable to get property 'day' of undefined or null reference fullcalendar.min.js (8,2987)

### ISSUE THREAD

**Issue by patrickmtan** [fullcalendar/fullcalendar#3802]
I have been using fullcalendar.min.js 2.3.1, and there was some issues with IE11. Fullcalendar does work on Chrome, and IEs 9 & 10, but on 11 it would load the page, but it cannot load the calendar, and it will freeze on the loading screen. In the console it will say:

SCRIPT5007: Unhandled exception at line 8, column 2987 in http://cdnjs.cloudflare.com/ajax/libs/fullcalendar/3.4.0/fullcalendar.min.js
0x800a138f - JavaScript runtime error: Unable to get property 'day' of undefined or null reference
fullcalendar.min.js (8,2987)

And it when comparing both 2.3.1 and 3.4.0 the error was always somewhere here in this for-loop:  
if (this.breakOnWeeks) {
                for (e = a[0].day(),
                t = 1; t < a.length && a[t].day() != e; t++)
                    ;
                n = Math.ceil(a.length / t)
            }
When looking at the Chrome's console, it would say e is undefined, but regardless it can still run it.

**Comment by arshaw** [comment]
Would you be able to post a [runnable, stripped-down demonstration of the bug](http://fullcalendar.io/wiki/Reduced-Test-Cases/)? Would really appreciate it because the time saved reproducing will be time spent fixing.
