### ISSUE TITLE
eventLimitClick, cellInfo.dayEl get an wrong element

### ISSUE THREAD

**Issue by auven** [fullcalendar/fullcalendar#3803]
### Bug Reports

I was studying fullcalendar and stumbled upon such a bug. Please look at the picture.

<img width="683" alt="chrome_2017-08-25_10-36-57" src="https://user-images.githubusercontent.com/23731087/29697654-02b34e74-8983-11e7-858d-e5a09e786767.png">

when i set the option like this, it will get a wrong element.
```
weekNumbersWithinDays: true,
showNonCurrentDates: false
```

you can see in codepen (https://codepen.io/auven/pen/WEKKEV).

I am use the Fullcalendar-3.4.0

**Comment by arshaw** [comment]
What is the bug though? What actions are you performing as a user? What would you expect to see and what actually happens? I don't understand. I'll reopen when I get more clarity.
