### ISSUE TITLE
Style the section of events that is in the non business days

### ISSUE THREAD

**Issue by hsuanweifu** [fullcalendar/fullcalendar#3806]
How do I style the section of the event that is on a non business day.

What I am trying to create is to allow the event to show as happening on a non-business day (aka on top of stripes), or not happening on a non-business day (aka below stripes).

The way I plan to achieve it is to style the non business days (background) using css which I have done. Then use jquery to get each event block dom and event data. Using the event data to determine what days the event is on and replace the event block with a table then style the td that's on the non-business days.

As you can see this process is rather complicated. Is there any way to do this without doing so?

The challenges with this approach is the dom doesn't seem to have event data. I will also have to calculate each event block (imaging an event that spans over multiple weeks).

**Comment by arshaw** [comment]
https://fullcalendar.io/support/

"Getting Help"
