### ISSUE TITLE
Get Resource Id on right click on fullcalendar-Scheduler

### ISSUE THREAD

**Issue by sandeepparihar** [fullcalendar/fullcalendar#3808]
Hi,

I need to get resource id on right clicking on fullcalendar-scheduler . Just like getting resource id on DayClick. I try to override right mouse button click function with left mouse button click but its not work for me.

**Comment by arshaw** [comment]
I've modified this ticket to also concern itself with a day double-click: https://github.com/fullcalendar/fullcalendar/issues/248

It will support the resource param just like the `dayClick` trigger
