### ISSUE TITLE
Get firstDay returns undefined if it is not set

### ISSUE THREAD

**Issue by hsuanweifu** [fullcalendar/fullcalendar#3809]
Trying to get the default week first day that's either controlled by default or locale.
 But `$('#calendar').fullCalendar('option', 'firstDay'); ` will return` undefined` even if visually the firstDay changes when I set the locale to 'es' ([1, 2, 3, 4, 5, 6, 0]).

I think it should always return the current week first day.

**Comment by arshaw** [comment]
The `firstDay` option is mushed into the internal calendar moment system. The best way to get what you want:

```js
  var calendar = $('#calendar').fullCalendar('getCalendar');
  var m = calendar.moment();
  alert('firstDay: ' + m.weekday(0).day());
```

https://codepen.io/arshaw/pen/GvPVdG?editors=0010
