### ISSUE TITLE
Loading event not triggered

### ISSUE THREAD

**Issue by forxer** [fullcalendar/fullcalendar#3810]
Since 3.5.0 the "loading" event no longer triggered.

https://codepen.io/anon/pen/zdyaXJ

Switch between 3.4.0 and 3.5.0 to see the problem.

**Comment by arshaw** [comment]
Confirmed. Will get this fixed very soon.

note to self: the above codepen is for 3.4.0 (working). this codepen is for 3.5.0: https://codepen.io/arshaw/pen/brOXKZ

**Comment by arshaw** [comment]
fixed in new release:
https://github.com/fullcalendar/fullcalendar/releases/tag/v3.5.1
thanks!

**Comment by jacobmischka** [comment]
I seem to still be running into this on 3.5.1. I'm not sure how or why.

![image](https://user-images.githubusercontent.com/3939997/30500277-3b61cd1c-9a23-11e7-9d6b-cbdd3d0405d4.png)

![image](https://user-images.githubusercontent.com/3939997/30500328-6bb1c148-9a23-11e7-93bc-02aa28be0030.png)

**Comment by jacobmischka** [comment]
In case anyone else runs into this with the same problem as me, I'm still running into this on 3.5.1, but I can't seem to reproduce it in codepen.

I'll create a new issue if and when I'm able to do so.
