### ISSUE TITLE
Event Object _id prop gets thrown away

### ISSUE THREAD

**Issue by 719media** [fullcalendar/fullcalendar#3811]
When creating events, I happened to have a "custom field" in the event called "_id".
It just so happens in the latest 3.5.0 version this field name is used internally, which caused me to lose my value for this field as it was reset with whatever fullcalendar is doing internally.
Obviously I can just use another field name, but perhaps the usage of the field name "_id" should be listed on the page:

https://fullcalendar.io/docs/event_data/Event_Object/

**Comment by arshaw** [comment]
Reproduced.
v3.4.0: https://codepen.io/arshaw/pen/oeJKQo?editors=0010
v3.5.0: https://codepen.io/arshaw/pen/vJvoQj?editors=0010
(see console.log)

The `_id` prop was already used internally prior to v3.5.0. Prior to 3.5.0 it would accept a user-provided value, whereas now it throws it away and uses its own.

I'll not this on the docs page like you said.

**Comment by arshaw** [comment]
I actually restored the behavior to what it was.
fixed in new release: https://github.com/fullcalendar/fullcalendar/releases/tag/v3.5.1
