### ISSUE TITLE
[ dayRender callback - Don't change sunday background color ]

### ISSUE THREAD

**Issue by danilosantosdev** [fullcalendar/fullcalendar#3816]
Hi all, i'm facing a curious issue.

**Explain**:

In my calendar i have events (blue) and some others informations to show (as you can see in the attachment).

The problem is with the "class days" in grey. My class days in this print are: monday, wednesday, friday and saturday, but if i add "sunday" as a class day, it doesn't display in the calendar.

My logic is wrong? What can i do?

This happens only with sunday. Someone can help me?

**Obs**.: I add the class day in the second print to show in the first.

https://pastebin.com/a7DCw5XN

![calendar](https://user-images.githubusercontent.com/2335679/29978119-3c743766-8f16-11e7-85f0-2b0297aa5308.png)
![class-day](https://user-images.githubusercontent.com/2335679/29978118-3c72e398-8f16-11e7-92be-e479b1ba4eb5.png)

**Comment by arshaw** [comment]
Use momentjs's weekday method:
https://momentjs.com/docs/#/get-set/weekday/

instead of doing the date math yourself. i see two errors with your date math.
