### ISSUE TITLE
async loading events fullcalendar Cannot read property 'length' of undefined at constructor.addEventDefs

### ISSUE THREAD

**Issue by Argorate** [fullcalendar/fullcalendar#3817]
Need help with an error in V3.5: https://stackoverflow.com/questions/46006757/async-loading-events-fullcalendar-cannot-read-property-length-of-undefined-at

**Comment by arshaw** [comment]
Would you be able to post a [runnable, stripped-down demonstration of the bug](http://fullcalendar.io/wiki/Reduced-Test-Cases/)? Would really appreciate it because the time saved reproducing will be time spent fixing.
