### ISSUE TITLE
background color in week in year mode

### ISSUE THREAD

**Issue by eduardobelchior** [fullcalendar/fullcalendar#3818]
When rendering the calendar to display the full year, the script adds a full week's background color, even if the event is only in 1 day.

FullCalendar v2.2.7
![calendar](https://user-images.githubusercontent.com/18681450/29992626-b90dbbb6-8f76-11e7-994e-85889289e571.JPG)

**Comment by arshaw** [comment]
Would you be able to post a [runnable, stripped-down demonstration of the bug](http://fullcalendar.io/wiki/Reduced-Test-Cases/)? Would really appreciate it because the time saved reproducing will be time spent fixing.
