### ISSUE TITLE
Event Object "date" property issue

### ISSUE THREAD

**Issue by nikolaglumac** [fullcalendar/fullcalendar#3819]
Hi there,

starting with version v3.5.0 FullCalendar removes "date" property from Event Objects.
If this is on purpose then, perhaps, documentation should be updated by stating that "date" property is reserved: https://fullcalendar.io/docs/event_data/Event_Object/
Would be much better if this property could be left in the Event Object as it was before (incl. v3.4.0)...

To reproduce the issue simply provide an event with default props (start, end, id, etc) and with additional "date" prop. After rendering "date" property will be removed :(

Thanks for looking into this!

**Comment by arshaw** [comment]
thanks for the report
this is now fixed: https://github.com/fullcalendar/fullcalendar/releases/tag/v3.5.1

**Comment by nikolaglumac** [comment]
Thanks for fixing it ;)

**Comment by nikolaglumac** [comment]
@arshaw I can confirm that now the date property is not removed BUT there is one new issue now - looks like FullCalendar expects that date field is a Moment.js object/date which should not matter I guess. The problem is that if you have a string value for `date` property (e.g. "07/09/2017" or "John Doe") and you invoke `updateEvent` method on that particular event Moment.js date format error will be thrown and the event will disappear from the calendar :(

This looks like `date` property is still wired up internally.

![screen shot 2017-09-07 at 10 15 59](https://user-images.githubusercontent.com/376611/30153190-0c26bad0-93b6-11e7-8301-29a3ec2a77b7.png)
