### ISSUE TITLE
Dynamic change of "selectable" option trigger "events" function

### ISSUE THREAD

**Issue by frlinw** [fullcalendar/fullcalendar#3820]
Since 3.5, dynamic change of ```selectable``` (```x.fullCalendar('option', 'selectable', true/false)```) cause trigger of ```events``` function. 
I don't know if it happens only for 'selectable'

**Comment by arshaw** [comment]
confirmed. thanks https://codepen.io/arshaw/pen/JyVMZo?editors=0010

**Comment by arshaw** [comment]
fixed now: https://github.com/fullcalendar/fullcalendar/releases/tag/v3.5.1
