### ISSUE TITLE
Wrong event dragged when ctrl key is pressed (on windows)

### ISSUE THREAD

**Issue by mounia87** [fullcalendar/fullcalendar#3823]
Hello, 
I have an issue with event dragging if ctrl-key is pressed on windows. It's not dragging the correct one.

I reproduced it on the example given at https://fullcalendar.io/ with the day view:
- In the example, select the day view.
- Click (with the mouse left key) on 1 event, for example: 'Meeting'.
- Then, click on another event 'Lunch', using this time mouse left key + ctrl key pressed (it's the behaviour to do if we want to select multiple events for example, this what I am trying to do).
-  Now, drag the first event 'Meeting'.
Expected: the event grabbed 'Meeting' is the one dragged.
Actual: the event dragged is the second one 'Lunch' and not the first.

This issue is only happening on Windows, as on Mac, I am using command-key to do multiple selection instead of ctrl-key (on mac, it's more like right click on the mouse).

From my investigation, I found that the issue is coming from the function 'isPrimaryMouseButton'. It's checking if the click isn't a right click and adds the test of ctrl-key pressed for Mac, but it's not the case for Windows.

I am using fullcalendar version: 2.7.3 that is included in the directive angular-ui-calendar v1.0.2.

Could you please have a look at this issue?
Thanks for your help.

**Comment by mounia87** [comment]
Proposition for a solution: check if it's a Mac or Windows and then add the ctrl-key check only if it's a Mac.
`function isPrimaryMouseButton(ev) {
	var isMac = navigator.platform.toUpperCase().indexOf('MAC') >= 0;
	if (isMac) {
		return ev.which == 1 && !ev.ctrlKey; 
	} else {
		return ev.which == 1;
	}
}`

**Comment by jferriol** [comment]
Thanks for the solution @mounia87 
Any date for official publication of change @arshaw ?

**Comment by polmabri** [comment]
Are there any reasons why @mounia87 's patch isn't yet pulled into master? Should we open a PR?

**Comment by Batajus** [comment]
I noticed that I have the same behavior on MAC, when I use a right-click on an element and drag another element the I used the right-click on is dragged instead of the other element.

Reproducable on https://fullcalendar.io/:
* Right-Click on the "All Day Event" event
* Drag the "Long Event"
 Expected: "Long Event" is dragged
 Actual: "All Day Event" is dragged

**Comment by arshaw** [comment]
this seems to no longer be an issue in v4 nor v5. please interact with https://fullcalendar.io/ to see. thanks. please comment if the bug is present in **v5** for you.
