### ISSUE TITLE
Cannot read property 'top' of null on change view

### ISSUE THREAD

**Issue by kveldscholten** [fullcalendar/fullcalendar#3825]
Get a TypeError message when I change view to week or day.

In my calendar with 4 entries run it.
My calendar with 1004 entries shows the TypeError error

![typeerror message](https://user-images.githubusercontent.com/5719257/30186762-2d06b5b8-9427-11e7-9e7d-c3ed0acd24e9.jpg)

 i used the 3.5.1 version

**Comment by arshaw** [comment]
Would you be able to post a [runnable, stripped-down demonstration of the bug](http://fullcalendar.io/wiki/Reduced-Test-Cases/)? Would really appreciate it because the time saved reproducing will be time spent fixing.

**Comment by CurtisVayne** [comment]
hi Guys,

i got the same error message, tracked down to this line:

this.$calendar.fullCalendar('option', 'maxTime', r.maxtime + ':00:00');

i got bad value in the maxtime :-(
r.maxtime is :"0"

**Comment by ransanjeev** [comment]
I also had the same problem. My min/max time were not valid. Max time was greater than the min-time but Full calendar was still trying to render the page.
Added a validation to throw the error before initializing the full calendar.
It will be nice, if this could be added in the library itself.

**Comment by icodk** [comment]
In my opinion if maxTime < minTime fullcalenddar should  regard it as next day. This will make it possible to create events that are almost 2 day long. ex. a party that starts 10PM and ends 2AM

**Comment by JNPSoftware** [comment]
Is there any solution to this?. In my case occurs only in **Week** and **Day** view. In **Month** and **ListWeek** they don't occurs.

![image](https://user-images.githubusercontent.com/33754986/39006834-aeab3694-43da-11e8-8a5a-d8f7822eeb81.png)

**Comment by acerix** [comment]
@JNPSoftware I'm not sure the issue is related, please create a new issue and submit a demonstration if possible.

**Comment by JNPSoftware** [comment]
@acerix, I discover **my** mistake. I pass **null** to **slotDuration** and broke the calendar. Sorry for any inconvenience.

**Comment by kundusouvik89** [comment]
@JNPSoftware I am also facing the same issue. I am passing slotDuration but still getting the error.

**Comment by JNPSoftware** [comment]
@kundusouvik89, except for `lang: currentLangCode,`, everything works.

**Comment by kundusouvik89** [comment]
@JNPSoftware I found out the issue. It's with
minTime: '4:00am',
maxTime: '24:00pm',

It would be 

minTime: '04:00',
maxTime: '24:00',
