### ISSUE TITLE
Disable resource row conditionally from creating events 

### ISSUE THREAD

**Issue by rubixcoder** [fullcalendar/fullcalendar#3827]
Can we please have a feature to disable a resource row on the basis of its availability. I want to show the resources disabled and also the select should be disabled for those slots. I have already checked the business-hours-per-resource but it's not working.

Here is the JSBin of what I tried with business-hours-per-resource: [http://jsbin.com/minomom/edit?js,output](http://jsbin.com/minomom/edit?js,output)

**Comment by arshaw** [comment]
How would you expect the system to determine if a resource is "available" ? If every single block of time within it is taken by a pre-existing event?

**Comment by rubixcoder** [comment]
No, I want to disable any resource on the role basis. I am working on an app which allows users to schedule the events on the resources based on their permissions to that resource.

**Comment by arshaw** [comment]
If you own the data about whether the resource should be available or not, then you could style the resource via  https://fullcalendar.io/docs/resource_rendering/resourceRender/
