### ISSUE TITLE
removeEvents by _id stop to work in rev v3.5.0 and v3.5.1

### ISSUE THREAD

**Issue by ginho1** [fullcalendar/fullcalendar#3828]
Fullcalendar after revs v3.5.0 and v3.5.1 stop to work removeEvents by _id.

`$('#calendar').fullCalendar('removeEvents', event._id);`

Used for new events using Drag and Drop and itens still dont have id then in old version we use auto id (_id) to remove temp events.

**Comment by arshaw** [comment]
hi @ginho1 , the `_id` property was never officially supported, so what you are doing is somewhat unsupported. You're right, the internal behavior changed a bit from v3.5.0 to v3.5.1. Here is a workaround you can use now:

```js
$('#calendar').fullCalendar('removeEvents', function(searchEvent) {
	return searchEvent._id === findEvent._id;
});
```

**Comment by luto** [comment]
@arshaw while this does of course not define the behavior of fullcalendar, please note that there are loads of SO answers referencing the `._id`-way of deleting events:
* https://stackoverflow.com/questions/40974441/fullcalendar-deleting-event-on-button-click
* https://stackoverflow.com/questions/43216360/how-to-delete-an-event-on-fullcalendar
* https://stackoverflow.com/questions/26530076/fullcalendar-js-deleting-event-on-button-click

**Comment by arshaw** [comment]
oh geez, thanks for letting me know @luto

**Comment by arshaw** [comment]
Released in [v3.6.0](https://github.com/fullcalendar/fullcalendar/releases/tag/v3.6.0)

`removeEvents` will accept an `_id` now

**Comment by tobiratzberger** [comment]
@arshaw 
So could you tell me why this is not working then?

    var eventAfterRenderFunction = function (event, element) {
        if (event.className.indexOf("jsAppointmentChooser-dateSeries") !== -1) {
            var eventDeleteItem_Button = $("<button/>", { "class": "btn btn-danger btn-circle jsAppointmentChooserDeleteEvent appointmentChooserDeleteEvent", "type": "button" });
            var eventDeleItem_Icon = $("<i/>", { "class": "fas fa-trash-alt" })

            element.append(eventDeleteItem_Button.append(eventDeleItem_Icon));
            eventDeleteItem_Button.on("click", function () {
                console.log(event._id);
                calendarElement.fullCalendar('removeEvents', event._id);
            });
        }
    }

Am I using it wrong?

**Comment by helphop** [comment]
Also with recurring events, when I try to do
```
 $('#calendar').fullCalendar('removeEvents', function(searchEvent) {
	return searchEvent._id === findEvent._id;
});
```
it deletes all of the events even though event._id is unique for each event.
