### ISSUE TITLE
Swipe Screen on mobile devices

### ISSUE THREAD

**Issue by joaocolling** [fullcalendar/fullcalendar#3836]
So, i'm trying use swipe events on calendar, but full calendar consume the touchstart event and not propagate. So my event works just outside of calendar.

Is there one way to get swipe events normally?

**Comment by espen** [comment]
Can you describe what you mean by swiping events on calendar? If this is a question instead of an issue report you should try asking on StackOverflow, see https://fullcalendar.io/support/

**Comment by joaocolling** [comment]
Thanks @espen for your quick answer.

I'm a bit confuse. Because in #2203 issue, closed yet, was already asked this functionality.
I'm see the duplicated issue #994, but don't have any description of this.
It's already developed? It's possible develop in the future?

For now i'm trying using swipe event on ionic, and I believe it's a touchstart event triggered is preventing the propagation of swipe event. Would be great if I can use swipe events inside the calendar to get 'next' and 'prev' view.

Thanks by the way. I'll try ask in StackOverflow too.

**Comment by espen** [comment]
You would have to hack it, not sure if there is some internal events that would block it or not. The FC view only shows the current timespan (for example one week). So next week will be a new rendering. So a swiping the entire week calendar view will have to mimic swiping and then do a normal render of the next week.

**Comment by joaocolling** [comment]
Ok. I will try! Tks @espen. Can close this "issue".
