### ISSUE TITLE
Objects used as non-standard Event properties are ignored in an "updateEvent" call

### ISSUE THREAD

**Issue by jharrisweinberg** [fullcalendar/fullcalendar#3839]
Hello,

I have a non-standard property set on the `Event` called `obj`, but after updating from `v3.4.0` to `v3.5.1`, this property is removed after calling `$('#calendar').fullCalendar('updateEvent', event)`. This non-standard property is an object as opposed to a primitive, which seems to be the root of the problem. When I set `obj` to be a string value, it does not get removed.

Thanks!

**Comment by jharrisweinberg** [comment]
The issue appears to be here: `fullcalendar/src/models/event/EventDefMutation.js`

The function `createFromRawProps` is called from `updateEvent `and it deliberately filters out property that are `typeof` `object`.

Is there a reason that objects are being filtered out or can that be changed to allow objects?

Thanks!

**Comment by arshaw** [comment]
confirmed. thanks.

repro: https://codepen.io/arshaw/pen/mBOvaO?editors=1011

**Comment by arshaw** [comment]
queue for release.

**Comment by arshaw** [comment]
Released in [v3.6.0](https://github.com/fullcalendar/fullcalendar/releases/tag/v3.6.0)
