### ISSUE TITLE
Multiply week event's rendering

### ISSUE THREAD

**Issue by brobro777** [fullcalendar/fullcalendar#3840]
So, when my event exceeds the 00.00 time (it goes on to next day), fc send 2 same requests (params are equals) to server for event rendering.   Timezone - 'local', got minTime and maxTime properties, view - 'agendaWeek'.
nextDayThreshold doesn't help.

**Comment by arshaw** [comment]
Would you be able to post a [runnable, stripped-down demonstration of the bug](http://fullcalendar.io/wiki/Reduced-Test-Cases/)? Would really appreciate it because the time saved reproducing will be time spent fixing.
