### ISSUE TITLE
when click on today button, today date more link should popover.

### ISSUE THREAD

**Issue by Dinesh-Wasnik** [fullcalendar/fullcalendar#3844]
Hi,

I solved this issue in 2.4.0

line no:5695
            renderMoreLink: function(cell, hiddenSegs) {
		   var _this = this;
		   var view = this.view;
		  var custom = moment(cell.start).format('YYYY-MM-DD');
		  return `$('<a` class="fc-more" id="fc-more-'+custom+'"/>')

**Comment by arshaw** [comment]
Would you be able to post a [runnable, stripped-down demonstration of the bug](http://fullcalendar.io/wiki/Reduced-Test-Cases/)? Would really appreciate it because the time saved reproducing will be time spent fixing.

**Comment by Dinesh-Wasnik** [comment]
[https://jsfiddle.net/DineshBW/aseeycpp/10/](url)

Here I reproduce requirement. When you click on today button the popover not shown (In v2.4.0) and In jsfiddle code also as I not push the changed file.

paste the above in main file and then run. Then click on today button .

**Comment by arshaw** [comment]
you're trying to do some really hacky stuff.

`$('#fc-more-' + moment().format('YYYY-MM-DD'))` does not resolve to a real element on the page.
