### ISSUE TITLE
eventSources object differs between 3.4 and 3.5

### ISSUE THREAD

**Issue by jblachly** [fullcalendar/fullcalendar#3845]
Not sure if bug report or feature request :)

In FullCalendar 3.4 and prior, `getEventSources` returns an array of objects, the elements "url" and "cache" (etc.) of which can be accessed directly, ala:

`url = $('#calendar').fullCalendar('getEventSources')[0].url;`

whereas in FullCalendar 3.5, the array of objects is of a different type. Inspection in the javascript debugger reveals that now to access the event source properties, you have to access them through the sub object "ajaxSettings":

`url = $('#calendar').fullCalendar('getEventSources')[0].ajaxSettings.url;`

Here is a minimal test case:
https://codepen.io/anon/pen/YrpYed
 

**I mention this because the upgrade to 3.5/3.5.1 broke existing code, and I could not find any mention of `ajaxSettings` in either the documentation or the current Github issues list. Thanks for any feedback and help!**

**Comment by arshaw** [comment]
thanks. the `url` was moved to a different internal object, but some people like yourself might be relying on reading in later from the event source object. will move it back in the next version.

**Comment by arshaw** [comment]
queued for release

**Comment by arshaw** [comment]
Released in [v3.6.0](https://github.com/fullcalendar/fullcalendar/releases/tag/v3.6.0)

**Comment by jamesdixon** [comment]
@arshaw I believe I'm running into this same issue, even when using 3.6+.

I maintain the [ember-fullcalendar](https://github.com/scoutforpets/ember-fullcalendar) addon and was updating from FC 3.3 to 3.6 when the following error occurred:

```
fullcalendar.js:16300 Uncaught TypeError: Cannot read property 'url' of null
    at Function.JsonFeedEventSource.parse (fullcalendar.js:16300)
    at Object.parse (fullcalendar.js:15981)
    at constructor.addEventSource (fullcalendar.js:13344)
    at HTMLDivElement.<anonymous> (fullcalendar.js:59)
    at Function.each (jquery.js:362)
    at jQuery.fn.init.each (jquery.js:157)
    at jQuery.fn.init.$.fn.fullCalendar (fullcalendar.js:36)
    at Class.observeEvents (full-calendar.js:219)
    at Object.applyStr (ember-utils.js:528)
    at sendEvent (ember-metal.js:378)
```

Clicking on the line referencing JsonFeed, I see the following:

![image](https://user-images.githubusercontent.com/110114/31588003-f2e7c27e-b1a8-11e7-92e5-26799b8e8ccc.png)

I incrementally downgraded to each previous version and things finally started working again when switching to v3.4.0.

Do you have any thoughts/suggestions?

Thanks!

**Comment by jamesdixon** [comment]
FWIW, I updated the `ember-fullcalendar` addon to check that the events being passed to `addEventSource` is not `null`. With that change, everything works as expected. That said, it seems like FC should deal with `null` just as it would an empty array or something similar. 

Would love to hear your thoughts and keep up the great work!

**Comment by arshaw** [comment]
@jamesdixon that's a sufficiently different issue. the original issue was that the `url` property was absent from the successfully-process event source.

why is the response to a JSON feed returning null? that's a failure case I'm not sure fullcalendar should be obligated to handle.

could you open up a new ticket for further convo?
