### ISSUE TITLE
validDays with hiddenDays, js error when no days active

### ISSUE THREAD

**Issue by arshaw** [fullcalendar/fullcalendar#3846]
reported by @yoancutillas at the end of #3686

when no days are active, due to `validRange`, in combination with `hiddenDays`, there's a fatal error: https://codepen.io/arshaw/pen/RLovzo?editors=0010

**Comment by arshaw** [comment]
queued up for release

**Comment by arshaw** [comment]
Released in [v3.6.0](https://github.com/fullcalendar/fullcalendar/releases/tag/v3.6.0)

**Comment by yoancutillas** [comment]
Hello Adam,

I hope you are doing well and I wish you the best for this new year!

There is a regression on that bug.
This time the JS error isn't "Cannot read property 'startMs' of null"
But "Cannot read property 'constrainDate' of null"

You can see it here:
https://codepen.io/yoancutillas/pen/OdXzLO?editors=0010

Regards,
Yoan Cutillas

**Comment by acerix** [comment]
This is not the same issue as above, the original code works in the 3.10.  It does look like a bug though so please submit a new issue.

**Comment by yoancutillas** [comment]
Ok, thank you!
Reported in #4476
