### ISSUE TITLE
Touch external DnD, with jQuery UI, use Touch Punch

### ISSUE THREAD

**Issue by sebastianrds** [fullcalendar/fullcalendar#3849]
Hi!

I am working with your fullcalendar (great job!), but I have a problem with the external dragging events. As example, if I use the External Events demo (https://fullcalendar.io/js/fullcalendar-3.5.1/demos/external-dragging.html) I can work with it in a normal PC, I can touch and drag the external event to the calendar grid. But when I go to the page using touch devices like Samsung Tab3, Samsung Galaxy ACE or in a PC with Chrome but in Touch Device mode, I cannot drag the event. It is not selectable from the list. I can se it but it don't moves.

Could you help me with that or with a workaround?

Best regards,

Sebastián

**Comment by arshaw** [comment]
That demo uses jquery ui, which doesn't support touch, so you'll need to use [Touch Punch](http://touchpunch.furf.com/) with it.

I'll repurpose this ticket to mention this in the docs.

**Comment by arshaw** [comment]
deployed https://fullcalendar.io/docs/jquery-ui-dnd
