### ISSUE TITLE
addEventSource add duplicate event into calendar

### ISSUE THREAD

**Issue by alex1007** [fullcalendar/fullcalendar#3850]
version: FullCalendar v3.4.0

doc: https://fullcalendar.io/docs/event_data/addEventSource/

```
var newEvent = {
    id: ...,
    title: ...,
    start: ...,
    end: ...,
}

$("#calendar").fullCalendar("addEventSource", [newEvent]);
```

If the start date is not in the week which is shown in the calendar, a duplicate event will be added. However, if the page is refreshed, there is no duplicate.

![screenshot1](https://user-images.githubusercontent.com/523684/30941483-a563c03c-a3b3-11e7-83da-1b43b512fe5e.gif)

If the start date is in the week which is shown in the calendar, there is no duplicate.

![screenshot2](https://user-images.githubusercontent.com/523684/30941885-a6dbccbe-a3b5-11e7-84b8-1784ded96352.gif)

**Comment by espen** [comment]
Can you provide a failing test at JSBin for this? See http://fullcalendar.io/wiki/Reporting-Bugs/

Does this occur in v3.5.0 too?

**Comment by alex1007** [comment]
@espen I figure out the problem. It's not a bug. In the events callback function I use ajax to get data from my server. I post the new event to the server and add it into the calendar the events list. If I click prev button, it will force calendar to get events from server again. That's why a duplicate event is the the events list.
