### ISSUE TITLE
Fullcalendar refetchEvents does not work 

### ISSUE THREAD

**Issue by Karador1995** [fullcalendar/fullcalendar#3851]
Pressing the btn_insert button saves the form data to my DB, but the data is not updated on the calendar screen. I'm using .fullCalendar ('refetchEvents') but it does not work. If I reload the page, the calendar data is updated. The controller and the model have no errors. Is there a compatibility problem when using ajax and fullcalendar? I'm using version 3.4

   $("#btn_insert").click(function(){
     
    var rut_usu = $("#rut_usu").val();
    var rut_estu = $("#rut_estu").val();
    var id_mot = $("#id_mot").val();
    var fecha_ini = $("#fecha_ini").val();
    var fecha_ter = $("#fecha_ter").val();

 
    $.ajax({

     url: "<?php echo base_url(); ?>" + "cCalendar/insertar_cita/",
     type: 'post',
     data: { "rut_usu": rut_usu, "rut_estu": rut_estu, "id_mot" : id_mot , "fecha_ini": fecha_ini , "fecha_ter": fecha_ter},

     success: function(response){ 

          $("#calendar").fullCalendar( 'refetchEvents' );
      
         }
 
      });
    }); `

**Comment by arshaw** [comment]
Would you be able to post a [**runnable**, stripped-down demonstration of the bug](http://fullcalendar.io/wiki/Reduced-Test-Cases/)? Would really appreciate it because the time saved reproducing will be time spent fixing.
