### ISSUE TITLE
Long press start and end event + prevent scrolling

### ISSUE THREAD

**Issue by nicDamours** [fullcalendar/fullcalendar#3852]
Hi, this is kind of a feature request.
I would like to know if it's possible to send an event on longPressStart and longPressEnd for mobile device.
Also, i'm in timeline view and when i'm trying to do a select, the whole calendar move ( the day part ). Could it be possible to disable calendar scroll on long press start ? 
Thanks !

**Comment by arshaw** [comment]
The calendar is supposed to automatically freeze scrolling while a selection is happening anyway. I'll try to reproduce.

**Comment by acerix** [comment]
This works as described in v4.  If there is still an issue, please supply a [runnable, stripped-down demonstration of the bug](http://fullcalendar.io/wiki/Reduced-Test-Cases/).

**Comment by JayAhn2** [comment]
@nicDamours I found that I have the below code, and it make freezing scroll logic I guess.

`fromEvent(elementRef.nativeElement, 'touchstart')`

I've changed it to 

`fromEvent(elementRef.nativeElement, 'touchstart', { passive: true })`

Check whether you have any logic like this in your codebase.
