### ISSUE TITLE
ListViews are not working 

### ISSUE THREAD

**Issue by srujan21** [fullcalendar/fullcalendar#3853]
Hi, I am facing issue when switching to listViews, I m getting an exception
**Uncaught TypeError: Cannot read property 'startMs' of undefined**

JS Bin recreation

http://jsbin.com/garuqep/5/edit?html,output

**Comment by guilhermecastros** [comment]
Hi. I had the same problem a few days ago. To solve this problem I changed a piece of code and it looks work fine. Go to the file "fullcalendar.js" open it with an text editor and find the function "componentFootprintToSegs: function(footprint)".

There, change this line:
    footprint.unzonedRange.endMs < dayRanges[dayIndex + 1].startMs + view.nextDayThreshold
to this one:
   footprint.unzonedRange.endMs < dayRanges[dayIndex].startMs + view.nextDayThreshold

**Comment by guilhermecastros** [comment]
I have found another solution "Check if dayRange index exists". You can check it out here: https://github.com/fullcalendar/fullcalendar/pull/3837/commits/e74ea6a88296888143aff7b78610a1cc583f57f2

**Comment by srujan21** [comment]
OK thanks , I ll check out. But for now I shifted to version 3.4.1.There every thing is good. It seems this is new issue.

**Comment by arshaw** [comment]
this was fixed in 3.6.0
please download a newer release: https://github.com/fullcalendar/fullcalendar/releases
