### ISSUE TITLE
Full calendar when event update (eventDrop ,eventResize)  all other events are re-render as well. 

### ISSUE THREAD

**Issue by korengal** [fullcalendar/fullcalendar#3855]
Hi ,
First of all , thank you very much for your hard work ! 

I'm developing full calendar  v3.6.1 with angularjs 1.6,

I need to customize the events view and control them with angular js  so i wrap them with component in the eventRender function like this : 

                    vm.eventRender = function (event, element, view) {
                        var newScope = $scope.$new(true, $scope);
                        newScope.event = event;
                        element.find('.fc-content').html($compile("<event-component-agenda-day></event-component-agenda-day>")(newScope));
                    };

The problem is:
When event is update , all other events update too and this is causing to performance issues , and design issues ( user can see that all the events are re created );

is there a way to update only the specific event that changed ? 

Example plunker that shows that eventDrag cause all the events to re render:
https://codepen.io/anon/pen/oGGxYZ

Thanks !

**Comment by arshaw** [comment]
that's partially what this ticket is for:
https://github.com/fullcalendar/fullcalendar/issues/3003

to be able to only rerender the affected event elements and no others.
