### ISSUE TITLE
The "more" popover shows duplicated events when they span several weeks

### ISSUE THREAD

**Issue by jasonsavard** [fullcalendar/fullcalendar#3856]
Create a "long event" spanning more than 1 week.
Then fill a day with enough single day events to get a "more" button displayed.
Click that more button and the "long event" will be duplicated in the popover.

https://codepen.io/anon/pen/OxOxEZ?editors=0010

Inside the renderMoreLink function

Line creating the problem is the resliceDaySegs seems to append the duplicated events
var reslicedAllSegs = _this.resliceDaySegs(allSegs, date);

Patch solution is to change the line to:
var reslicedAllSegs = allSegs;

![image](https://user-images.githubusercontent.com/1268278/31176784-0c68842e-a8e2-11e7-82f6-a436c34ae90e.png)

![image](https://user-images.githubusercontent.com/1268278/31176801-1c1c9784-a8e2-11e7-8bad-ce08a9b249da.png)

**Comment by gaarashura** [comment]
This BUG appears in version 3.5

**Comment by arshaw** [comment]
fixed and released in 3.6.1
