### ISSUE TITLE
The scroll position needs to be kept the same if the view-state changes (not the view-type)

### ISSUE THREAD

**Issue by ParanormalCoder** [fullcalendar/fullcalendar#3857]
### Bug Reports
The issue in my case is observed inside the **timelineDay** while changing the day. If the day changes in calendar, the scroll position resets.

The below example is from (**non-premium view**) agendaDay:

https://jsbin.com/pawepon/edit?html,output

(Please change the day value inside the calendar, and see how it resets the scroll value)

### Feature Requests
The feature needed is to have an option for each calendar view type, to make each of them able to keep the scroll value if the state-change is happening inside the same calendar view (e.g. day change inside the timelineDay).

This is a general behavior inside other known calendars.

**Comment by arshaw** [comment]
i'm going to group your request into this ticket:
https://github.com/fullcalendar/fullcalendar/issues/1037

**Comment by arshaw** [comment]
&uarr;
Could you please visit the link, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates?
