### ISSUE TITLE
eventDataTransform conflicts with eventConstraint

### ISSUE THREAD

**Issue by archemedia** [fullcalendar/fullcalendar#3859]
I have made a jsFiddle example here:
https://jsfiddle.net/w4L66k08/3/

Key to this issue is: 
In my eventDataTransform function, I converted incoming events to fullCalendarEvents. This works well.
When I combine this with a eventConstraint, things mess up.

Reproduce:
1. run the code and watch the console: 'converted event' objects are shown, all works well;
2. uncomment line 17 in the code: 
//eventConstraint: {start: "08:00:00", end: "16:00:00"},
3. run the code and then **move** or **alter length** of an event in the calendar
4. now you will see that the eventDataTransform function is called again with undefined input or even constraint input.

further information:
- The bug does not prevent me from dragging and resizing; this still works as expected.
But the constraint specified does not work. Dragging and resizing is not restricted to the given time period in the constraint property.

- When I omit the eventDataTransform function, constraining works as expected.

**Comment by arshaw** [comment]
Ah ok. During event resize, the `eventDataTransform` should not be called at all. It should only be called for initial parsing. I suspect that since `eventDataTransform` is returning an invalid event during resize, because it receives invalid input, the constraint system is ignoring it.

**Comment by arshaw** [comment]
queued for release.

**Comment by arshaw** [comment]
released in [3.6.2](https://github.com/fullcalendar/fullcalendar/releases/tag/v3.6.2)
