### ISSUE TITLE
cannot move the calendar in listWeek and listday view

### ISSUE THREAD

**Issue by bin123485** [fullcalendar/fullcalendar#3860]
jsFiddle : https://jsfiddle.net/bin123485/161tceyz/2/

When I add a event start at '2017-09-02T23:00:00' to the demo "list-views.html", the calendar cannot move through that day(2017-09-02) if I press 'prev' or 'next' button.

If the date is the very last day of the week(Sat by default, Sun if firstDay set to 1, and etc), and the time is greater than 22:00, this bug happens.

It seems v3.5.0 and 3.5.1 have this issue, and v3.4.0 works fine.

sorry for my bad English ,it is not my native language.

**Comment by arshaw** [comment]
you were running into this bug, which is now solved:
https://github.com/fullcalendar/fullcalendar/issues/3843

update with latest version. works:
https://jsfiddle.net/161tceyz/5/
