### ISSUE TITLE
Time labels don't render within their slot in Agenda views

### ISSUE THREAD

**Issue by paronne** [fullcalendar/fullcalendar#3863]
### Bug Reports
The time slot doesn't render with the proper width and the time labels in time slots overflow on top of the day column in the agenda view.

https://jsfiddle.net/paronne/5a8gbwa8/1/

**Comment by paronne** [comment]
Handlers are now returning dates

**Comment by arshaw** [comment]
modified your jsfiddle to have latest version:
https://jsfiddle.net/5a8gbwa8/2/
(still broken)

but for some reason the bug is not happening in codepen:
https://codepen.io/arshaw/pen/gGJgMM?editors=0010

Rather confusing...

**Comment by paronne** [comment]
Hi Adam,

it seems related to the JQuery version. In JSFiddle i am using JQuery 3.2.0 (the same used in our application), while your codepen is using JQuery 2.1.3.

I can replicate also in codepen using the JQuery 3.2.0 https://code.jquery.com/jquery-3.2.0.min.js

**Comment by arshaw** [comment]
ah ok. looks like it's a bug specifically with jQuery 3.2.0:

> Ensure we get proper values for width and height on elements with display “inline”

https://blog.jquery.com/2017/03/20/jquery-3-2-1-now-available/

That's exactly the problem.

If you upgrade to jquery 3.2.1, it's fixed
