### ISSUE TITLE
JSON url not working in 3.6.0

### ISSUE THREAD

**Issue by Guite** [fullcalendar/fullcalendar#3865]
Probably related to the change for #3845 fetching events from JSON seems to be broken in 3.6.0. For a demo see https://fullcalendar.io/js/fullcalendar-3.6.0/demos/json.html which tries to fetch events from  `https://fullcalendar.io/js/fullcalendar-3.6.0/demos/json.html` instead of `php/get-events.php`.

**Comment by demorose** [comment]
Solved the problem by renaming "this.url" to "_this.url" in the promise function in JsonFeedEventSource.fetch
(line 14347)

**Comment by NicolasCARPi** [comment]
Can confirm. The solution of @demorose is working.

**Comment by arshaw** [comment]
fixed and released in 3.6.1

there was a bug in the json feed tests :/

**Comment by NicolasCARPi** [comment]
Thanks @arshaw
