### ISSUE TITLE
[Bug Report] Aligning Events against right Time in Week and Day Mode

### ISSUE THREAD

**Issue by harshamv** [fullcalendar/fullcalendar#3868]
### Bug Reports

When i have multiple events in a day. The events do not get aligned against the right time of the day.

![2017-10-12_11-29-12](https://user-images.githubusercontent.com/249592/31481420-cf349862-af40-11e7-81c4-2d5631938943.jpg)
![2017-10-12_11-27-46 copy](https://user-images.githubusercontent.com/249592/31481421-cf6e8068-af40-11e7-8221-a0b02d8658fa.jpg)

**Comment by arshaw** [comment]
I don't understand: what's the "right time of the day" ? can you explain what is happening in each screenshot? Why are the headers cut off in the second screenshot?

**Comment by harshamv** [comment]
@arshaw sorry for the late reply.

Second Screenshot the image show is so. The header is there just not in the image.

If i see the second screenshot and see against 8am the event of 1.35pm is being displayed.
