### ISSUE TITLE
navLinks navigates to wrong day from previous click

### ISSUE THREAD

**Issue by jeppetinghoj** [fullcalendar/fullcalendar#3869]
Select month view. Click on a date to get the day view. This works. 
But then go back to the month view again and select another date - in the day view the date is not updated to the chosen date, but stays at the previous.

This is a new bug that was not present in previous versions.

**Comment by arshaw** [comment]
I can confirm this and will get it fixes for the next bugfix release

**Comment by arshaw** [comment]
queued for release

**Comment by arshaw** [comment]
released in [3.6.2](https://github.com/fullcalendar/fullcalendar/releases/tag/v3.6.2)
