### ISSUE TITLE
Bug in Week View columnFormat "ddd, DD/MMM"

### ISSUE THREAD

**Issue by shruthikj** [fullcalendar/fullcalendar#3870]
Expected date format in Week View **columnFormat** : Wed, 30 Oct
What is being rendered is : Wednesday, 30 Oct

"**ddd**" is being overlooked.

**Comment by arshaw** [comment]
Would you be able to post a [runnable, stripped-down demonstration of the bug](http://fullcalendar.io/wiki/Reduced-Test-Cases/)? Would really appreciate it because the time saved reproducing will be time spent fixing.

**Comment by shruthikj** [comment]
Found the issue. It was because **dayNamesShort** had all full forms of the day names. Assigned it to short names. Now, it's working perfectly well. Thank you.
