### ISSUE TITLE
Return hour and column number at click on an event

### ISSUE THREAD

**Issue by alexandruneagu** [fullcalendar/fullcalendar#3871]
Hello,

I am using the fullcalendar 2.5 with the fullcalendar column extension.

I am looking for a method that, in the week view, at the click on one event, should return the hour and the column that correspond to my mouse position.  

So, I have an event that starts for example, at 3 pm, and ends at 5 pm. When I click somewhere, let s say, in the middle, I want to see the hour that is correspondent to my mouse position. If I press in the middle, I should have 4pm.

It's like I am clicking on an event, but I want to call the 'select' function, under the event div.

#Later edit: should return the hour and the "DAY" that correspond to my mouse position.

**Comment by arshaw** [comment]
this ticket probably fits your description: https://github.com/fullcalendar/fullcalendar/issues/2430

implementing what you say word-for-word is probably too specific for the general API
