### ISSUE TITLE
EventLimit not working with custom view

### ISSUE THREAD

**Issue by afranzencallibrity** [fullcalendar/fullcalendar#3873]
I want to limit the number of events shown with my custom view, but it seems that EventLimit doesn't work for custom views. I have a view that has a duration of 90 days and I want only the first 5 events to show up in my view. When I use the EventLimit it doesn't have an effect on my view and I end up with an endless scrollbar which I don't want. Is there another way to accomplish this?

**Comment by arshaw** [comment]
what `type` of custom view? could you provide a [demo](http://fullcalendar.io/wiki/Reduced-Test-Cases/)?

**Comment by afranzencallibrity** [comment]
It is a custom list view. I want to either show a certain number of events or limit the events to fit the content height. Essentially I don't want the user to have the option to scroll within the plugin.
Demo https://codepen.io/afranzen/pen/PJMqGy

**Comment by arshaw** [comment]
`eventLimit` is currently not supported in List view. would be a new feature with new UI. could you post a mockup of what you'd want it to look like? the design of it is not clearly coming to mind.

**Comment by afranzencallibrity** [comment]
![image](https://user-images.githubusercontent.com/28712546/32019410-18ce7dd0-b99b-11e7-9ff9-6b45c71e47e0.png)

I would like the list view to have an option to automatically limit the number of events displayed so as to fit as many events as possible within the height I specify, without introducing a scroll bar.

**Comment by BenSchumacher-cjf** [comment]
Is there any way to bump this issue? Like setting a bounty on it?
