### ISSUE TITLE
Is it possible to refresh the businessHours in any way?

### ISSUE THREAD

**Issue by Karador1995** [fullcalendar/fullcalendar#3877]
Hello, I need to update the businessHours according to the selected user, I am passing the parameter I need using a listboxt, however I would like to know if there is something like refetchEvents for this.

**Comment by espen** [comment]
@Karador1995 please ask questions on StackOverflow. See https://fullcalendar.io/support/.

**Comment by Karador1995** [comment]
I am asking here, because I read the documentation, ask in stackoverflow and search in google. I'm not even asking about an XD error. I am just asking if there is something like refetchEvents to update businessHours hal perform X action. So far I have not found anything, so I thought that maybe I missed something of the documentation.

**Comment by korengal** [comment]
You can do this it this way :  (https://fullcalendar.io/docs/utilities/dynamic_options/)

update what ever you want : 
                        $('#calendar').fullCalendar('option', {
                            businessHours: businessHours,
                            minTime: minTime,
                            maxTime: maxTime,
                            hiddenDays: hiddenDays,
                            resources: resources,
                            selectConstraint: 'businessHours',
                            eventConstraint: 'businessHours',
                        });
                        
Then you need to refetchResources (https://fullcalendar.io/docs/resource_data/refetchResources)
$('#calendar').fullCalendar('refetchResources');

**Comment by Karador1995** [comment]
Thanks for replying, I will try to do it that way, I am passing a variable through a listboxt to pass it to my controller, which sends it to the model and in this way get the values of the queries per day.

`businessHours: [ 
    {
        dow: [ 1], // Monday

        <?php foreach($monday as $row){?>
           start: '<?php  $inicio= "00:00"; $start1_ok = $row->hrs_ini;

        if (empty($start1_ok)) { echo $inicio;}

        else { echo $start1_ok;} ?>',  // empty evalua si el campo se encuentra vaio o si es cero
        end: '<?php echo $row->hrs_ter ;?>' 
        <?php }?>

    },

    {
        dow: [2], // Tuesday
        <?php foreach($tuesday as $row1){?>
           start: '<?php  $inicio= "00:00"; $start1_ok = $row1->hrs_ini;

        if (empty($start1_ok)) { echo $inicio;}

        else { echo $start1_ok;} ?>',   // 10am
        end: '<?php echo $row1->hrs_ter ;?>' // 4pm
        <?php }?>
    },


    {
        dow: [3], //  Wednesday
        <?php foreach($wednesday as $row2){?>
           start: '<?php  $inicio= "00:00"; $start1_ok = $row2->hrs_ini;

        if (empty($start1_ok)) { echo $inicio;}

        else { echo $start1_ok;} ?>',  // 10am
        end: '<?php echo $row2->hrs_ter ;?>' // 4pm
        <?php }?>
    },

    {
        dow: [4], // Thursday
        <?php foreach($thursday as $row3){?>
           start: '<?php  $inicio= "00:00"; $start1_ok = $row3->hrs_ini;

        if (empty($start1_ok)) { echo $inicio;}

        else { echo $start1_ok;} ?>',  // 10am
        end: '<?php echo $row3->hrs_ter ;?>' // 4pm
        <?php }?>
    },

    {
        dow: [5], // Friday
        <?php foreach($friday as $row4){?>
        start: '<?php  $inicio= "00:00"; $start1_ok = $row4->hrs_ini;

        if (empty($start1_ok)) { echo $inicio;}

        else { echo $start1_ok;} ?>', 
        end: '<?php echo $row4->hrs_ter ;?>'// 4pm

        <?php }?>
    },

    {
        dow: [6], // Saturday

        <?php foreach($saturday as $row5){?>

        start: '<?php  $inicio= "00:00"; $start_ok = $row5->hrs_ini;

        if (empty($start_ok)) { echo $inicio;}

        else { echo $start_ok;} ?>', 

        end: '<?php echo $row5->hrs_ter ;?>'
         <?php }?>
    },
],
`

**Comment by arshaw** [comment]
@Karador1995 , my last comment here should answer your question:
https://github.com/fullcalendar/fullcalendar/pull/3879#issuecomment-338772933
