### ISSUE TITLE
dynamically scrollTime not working.

### ISSUE THREAD

**Issue by korengal** [fullcalendar/fullcalendar#3878]
Hi ,
First of all , thank you very much for your hard work !

I'm using full calendar v3.6.1.

The scrollTime option is working only when set on startup,

when I'm trying to dynamically scroll to specific time (on some event click) its not working :

I'm using this (https://fullcalendar.io/docs/utilities/dynamic_options/) for update the value of scroll time

$('#calendar').fullCalendar('option', {
                            scrollTime: '19:00:00'
                        });

Thanks.

**Comment by arshaw** [comment]
this is what you'd want:
https://github.com/fullcalendar/fullcalendar/issues/467
&uarr;
Could you please visit the link, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates?

**Comment by korengal** [comment]
Can you send me the code example?
I don't understand what I need to take from the long conversion #467

**Comment by arshaw** [comment]
it's a proposed API method that's not implemented yet

**Comment by korengal** [comment]
If it help someone, I fix it by implementing this function:


```
var scrollToCurrentHour = function () {
              $timeout(function () {
                                var hour = moment().format('h');

                                var scrollToElement = $('.fc-slats').find('tr[data-time*="' + hour + ':00"]');

                                //vertical scroll
                                var elementOffsetTop = scrollToElement && scrollToElement.length > 0 ? scrollToElement[0].offsetTop : 0;
                                $('div.fc-scroller').scrollTo(elementOffsetTop + 'px');

                            }, 500);
                  
                    };
```
