### ISSUE TITLE
Visibility of very short events in agendaView

### ISSUE THREAD

**Issue by georgehrke** [fullcalendar/fullcalendar#3881]
### Expected behavior
Short events should be readable even in agenda views 

### Actual behavior 
Short events are barely visible

## Reproduction Code
https://jsfiddle.net/o4z8qfg1/2/

## Screenshot
![33cc05c3-b562-415a-8c59-354f6150d757](https://user-images.githubusercontent.com/1250540/31733933-5bad6660-b43d-11e7-8426-3d4d7e1351bc.jpg)

**Comment by neroux** [comment]
How would you suggest to fix that?

**Comment by georgehrke** [comment]
Each event should have a minimum height, so you can always read its title, and it should be displayed as if those two events were in an overlapping timeframe, so basically next to each other.

cc'ing @jancborchardt, our design guru at [Nextcloud](https://github.com/nextcloud)

**Comment by neroux** [comment]
I wouldnt know how that could be reasonably implemented without distorting the concept of time slots but I am sure arshaw is open to ideas.

**Comment by georgehrke** [comment]
> I wouldnt know how that could be reasonably implemented without distorting the concept of time slots but I am sure arshaw is open to ideas.

I get your point, but I think it's the lesser evil compared to not being able to read an event's title or not even seeing it in the first place.

**Comment by neroux** [comment]
I do understand the issue the original reporter brought up as well, I am just not sure if arbitrarily inflating time slots is the best way to do that.

**Comment by jancborchardt** [comment]
Well, every event should at least be readable and visible, no matter if it's just 5 minutes long. Readability goes over "exactness" here. :)

@georgehrke's design proposal is good, showing them next to each other.

**Comment by arshaw** [comment]
[agendaEventMinHeight](https://fullcalendar.io/docs/agenda/agendaEventMinHeight/) is a recently-implemented workaround to this exact problem.

In a future version of FC, we will start using the organic height, regardless of end-time, as the minimum height.

**Comment by georgehrke** [comment]
Thx for the info! :)

We will use agendaEventMinHeight for now.

**Comment by arshaw** [comment]
discussion about making a breaking change in the future: https://github.com/fullcalendar/fullcalendar/issues/961
