### ISSUE TITLE
Stain in calenndar after click next week

### ISSUE THREAD

**Issue by Chiiviito** [fullcalendar/fullcalendar#3883]
This is error, help me please!

![image](https://user-images.githubusercontent.com/12447729/31776059-c37dd652-b4c0-11e7-9467-1ab69f693d82.png)

![image](https://user-images.githubusercontent.com/12447729/31776072-cdd1c2f8-b4c0-11e7-87a7-a80f95fc7858.png)

![image](https://user-images.githubusercontent.com/12447729/31776083-d3c420ac-b4c0-11e7-9e0b-a2a55862a2ae.png)

**Comment by neroux** [comment]
> ### Bug Reports
> You MUST have a JSBin recreation, or else your issue will be CLOSED without explanation.
> Instructions: http://fullcalendar.io/wiki/Reporting-Bugs/

**Comment by calendarluxe** [comment]
I had a same error !

Try [printable 2019 calendar](https://www.luxecalendar.com/)
