### ISSUE TITLE
FullCalendar 3.6.1 GoogleCalendar events not calling loading callback

### ISSUE THREAD

**Issue by dyhrdmet** [fullcalendar/fullcalendar#3884]
I think I found a bug in fullcalendar.io version 3.6.1. When using a google calendar event source, the loading callback is not getting fired.

It looks like there are calls to this.calendar.pushLoading(); in fullcalendar.js right before the return Promise.construct statement is called in each of the extended EventSource classes. But in gcal.js for the Google Calendar event sources, this is missing. Same issue with the call to _this.calendar.popLoading(); when the response is received.

I added this in the local copy for my site and it seemed to work. It had worked in version 3.4.0, but it looks like the building of the EventSources was re-written in 3.5.0 and has been missing since then.

codepen:
https://codepen.io/dyhrdmet/pen/NaJqKR
(if you notice in the pen, the "loading" callback logs to the console and raises an alert, and neither of those events took place)

**Comment by arshaw** [comment]
reproduced, thanks

**Comment by arshaw** [comment]
queued for release

**Comment by arshaw** [comment]
released in [3.6.2](https://github.com/fullcalendar/fullcalendar/releases/tag/v3.6.2)

**Comment by dyhrdmet** [comment]
Looks good. Thanks!
