### ISSUE TITLE
Events during a DST changeover are shortenend/extended by one hour

### ISSUE THREAD

**Issue by neroux** [fullcalendar/fullcalendar#3887]
Example at https://jsfiddle.net/ocucLm98/

When `timezone` is set to "local" and the system timezone is "Europe/London", events taking place during the DST changeover seem to be hidden.

In the example we have an event on October 29th (when time goes back one hour at 2am local time) from 00:00 UTC to 01:00 UTC, which translates locally from 01:00 BST to 01:00 GMT.

When `timezone` is set to "Europe/London" it places the event between 00:00 and 01:00. The beginning is an hour early, the end would be correct in this case. Could it be that using "local" takes additionally `Date.getTimezoneOffset()` into account and that skews the period?

**Comment by arshaw** [comment]
because the event is in UTC, and the calendar's timezone is in 'local', the event will appear at a different time depending on your computer's local timezone. for example, I'm in New York and I scroll back one day and see the event happening at 8pm

**Comment by neroux** [comment]
That is why I mentioned the timezone. Please set it to Europe/London and you will notice the issue.

**Comment by neroux** [comment]
@arshaw

**Comment by arshaw** [comment]
oh sorry, will look into this again

**Comment by arshaw** [comment]
recreated. I see what's happening. the browser is rounding up `2017-10-29T00:00:00Z` to `2017-10-29T01:00:00Z` because of DST and because the end time is the same date, FullCalendar is considering the event's dates to be invalid and discarding the event.

the correct thing to do is: if the end date is invalid ignore it and use `defaultTimedEventDuration/defaultAllDayEventDuration`. this solution does not specifically take DST into account, but it solves the problems, as well as the issue of ppl being confused when they have invalid end dates.

**Comment by neroux** [comment]
`defaultTimedEventDuration` unfortunately does not seem to have an effect in this case. Setting it to `'01:00:00'` still does not display it.

What exactly did you mean by "rounding up"? Could this be an issue that needs to be reported with moment? Were you referring to the issue I mentioned at the beginning, that both times are 1am - in two different timezones though, respectively with and without DST applied?

I'd assume the fundamental problem here might be that countries using DST will have the same hour twice this weekend (or whenever their switch is) and that is not accounted for yet in fullcalendar. It would basically require to render only 23 hours for days when DST becomes effective (skip the one hour that is skipped) and 25 hours for days when the switch back takes place (add the one hour that is added).

Do you think the current implementation could support that, particularly from a visual point of view?

**Comment by arshaw** [comment]
sorry, when I say "the correct thing to do is", I mean that's what fullcalendar should do internally to handle this edge case.

**Comment by neroux** [comment]
Alright, I understand, thanks for the clarification. Though that would be still sort of a workaround. What do you think about the proposed change (23/25 hours)? It would skew the layout somewhat but would properly map the number of hours on the days when the state of DST changes and would avoid the issue at hand altogether.

**Comment by arshaw** [comment]
that would be a little weird for a week view, where most days would have 24 hours, but only one day would have 23 or 25.

**Comment by neroux** [comment]
I agree, but after all that is exactly what is happening twice a year in countries using DST and I guess it would be only "proper" implementation to avoid problems like the one here.

As for the visuals, maybe the skipped hour (when 23) could be shown as greyed out in the table and in case of an added hour (when 25) the hour-tuple could be maybe "squeezed" into one regular hour. Just ideas.

**Comment by neroux** [comment]
Examples for [adding one hour](https://www.worldtimebuddy.com/?pl=1&lid=2643743,5128581&h=2643743&date=10/29/2017%7C4) and [skipping one hour](https://www.worldtimebuddy.com/?pl=1&lid=5128581,2643743&h=5128581&date=3/24/2018%7C5).

**Comment by neroux** [comment]
Same issue for when the clock is going forward

https://jsfiddle.net/t46vcmwc/ - it shows a two hour duration when the event is only one hour long

Ideally, the day when DST changes (forward or backward) would be either extended or shrunk by the hour in question. I took a quick look at the calendar structure and guess it should be an "easy" fix in case of `agendaDay` but possibly not so easy for `agendaWeek`, as there the hours are uniformly rendered via table rows for the entire week.

So I assume - under the current implementation - extending/shrinking one particular day would not be possible, neither would be squeezing two hours into one or greying out one hour.

One possible solution I could imagine would be to check whether any DST changes fall into the current view (is the DST status of `start` and `end` the same?) and if there are, render the maximum amount of hours for this period as table rows (either 24 or 25) but number them still sequentially from 0 to 23 and only apply for the day in question visual cues that there is an hour more or less. Of course that special handling would also apply to event boxes rendered for that day.

What do you think about this approach @arshaw? Would that require a lot of changes to the current code base?

**Comment by neroux** [comment]
Any thoughts on this issue @arshaw? March is approaching quickly :).

**Comment by neroux** [comment]
@arshaw?

**Comment by arshaw** [comment]
this issue is not high enough priority right now to focus mental energy. will circle back on it when other stuff is completed.

**Comment by neroux** [comment]
No worries, considering it is only an issue twice a year I can understand it does not have the highest of priorities right now but it shouldnt be forgotten either. Ideally it would be addressed until next March or October/November the latest, after all it is not exactly a minor issue.

Generally speaking though, would you accept a pull request with the implementation outlined above?

**Comment by acerix** [comment]
It's hard to predict how that would look exactly and what might get broken by the change before trying it. So, sending a PR with a demonstration is a good way to push this forward, but I can't say it would be accepted at this point.

Since some days have 25 hours under DST, there needs to be some way to show all 25 hours, but maybe something more elegant than tacking an extra hour at the bottom.

**Comment by neroux** [comment]
> but I can't say it would be accepted at this point.

No offence, but in which capacity are you making that statement? I'd appreciate something slightly more official from @arshaw.

> Since some days have 25 hours under DST, there needs to be some way to show all 25 hours, but maybe something more elegant than tacking an extra hour at the bottom.

And some days only have 23 hours as mentioned before, that is the whole point. That is why I asked that exact question earlier in this conversation. If you have a better idea how to implement that please do share.

**Comment by acerix** [comment]
I'm helping with responding to issues, @arshaw has already mentioned that this is not a priority so that's more official, I just wanted to respond to your question.

I didn't mean to imply that such a PR would not be accepted, but having some days with odd hours might look weird and is probably going to break other things, so not as simple as others which generally get accepted.

Choosing an implementation also takes time (ie. not a priority), but having a demo that fixes this issue would be a great start.

I like your suggestion but would have 25 hour slots every day, so most days would have an empty slot at the bottom, keeping the size consistent.

**Comment by neroux** [comment]
> I'm helping with responding to issues, @arshaw has already mentioned that this is not a priority so that's more official.

Thats why my follow-up response :).

> I didn't mean to imply that such a PR would not be accepted, but having some days with odd hours might look weird and is probably going to break other things, so not as simple as others which generally get accepted.

Please see my earlier response to that issue.

> I like your suggestion but would have 25 hour slots every day, so most days would have an empty slot at the bottom, keeping the size consistent.

Please see here my earlier response here as well. A quick recap: 25 slots would be only necessary for a period when there is an additional hour (i.e. DST becomes ineffective) and in that case these 25 slots should be rendered for all days in that period, even when there is no change on that day (which mostly refers to the weekly view).

**Comment by arshaw** [comment]
@neroux could you please do some homework and see what other products do for such a situation? Try Google Calendar, apple calendar, outlook for example. Other products that have similar UI and form factor as FullCalendar. The worldtimebuddy is too different. Also, see how they handle dragging events into, out of, and over the extra hour.

FYI, acerix is working with me to help triage github tickets. He'll try his best to work w/ you to get actionables out of this convo. But please be warned that there might be long gaps in response time because there are lots of other initiatives on our plate and this is much lower prio. Even if you were to make a PR, it would likely take a while to be reviewed and accepted. And we also need to do the cost/benefit analysis of whether solving for this edge case is worth the additional code complexity.

The top priority in this ticket is making sure that all events are displayed, one way or another, which is your originally bug report I believe.

The secondary priority (much lower) is adapting the UI for fit 23/25 hours or whatever.

**Comment by neroux** [comment]
> The top priority in this ticket is making sure that all events are displayed, one way or another, which is your originally bug report I believe.

I encountered the issue at the time when DST became ineffective, so you could say it originally was about events being hidden, however (as the changed title also indicates) it is to be taken in a broader context. As it is at the moment, FullCalendar does not support DST. Rendering such events in a way that they have a minimum height would _work around_ the display issue but would skew the entry's time slot.

> The secondary priority (much lower) is adapting the UI for fit 23/25 hours or whatever.

I believe though that (or any other reasonable approach) necessarily goes hand in hand.


Just my two cents :)

**Comment by urkle** [comment]
So google calendar fails horribly. I tested the gaining an hour scenario.  And the UX just displays 24hours only..  thus an event from 12:30 -> 1:30 EDT  and 12:30 -> 1:30 EST look identical (for the gaining an hour scenario)

![image](https://user-images.githubusercontent.com/101123/32924237-9d6b2af0-cb09-11e7-9b35-63d5a6c67d84.png)

Their editing UI does not allow you at all to pick 1:30 EST (the extra hour).  So I had to use a different program to create these events..    Which was  Calendar on OS X.

in OS X the UX visually is the same you can't tell the difference from looking at it.

![image](https://user-images.githubusercontent.com/101123/32924258-be595494-cb09-11e7-854f-4e763c94e5a6.png)

incorrect labels in the popover
![image](https://user-images.githubusercontent.com/101123/32924267-c8793200-cb09-11e7-8ebd-0be53ce4fa4c.png)

but when editing they allow you to "sort of" set the other 1:30a, however it doesn't appear to stick. :(

![image](https://user-images.githubusercontent.com/101123/32924297-ed562a88-cb09-11e7-8b9f-3e228b309276.png)

So all varying degrees of "gee we never thought about it" even though a good half the world does DST.

**Comment by arshaw** [comment]
@urkle thank you so much for doing this research. i bet @neroux is thankful as well. good to know the rest of the world is just as bad as fullcalendar :)

not saying this isn't an issue, but does put things into perspective.

top priority is still the same: making sure events that fall into the gap don't disappear

**Comment by neroux** [comment]
@urkle
> So google calendar fails horribly.

So it seems. I ran a quick check and noticed as well that they do not seem to treat days with a DST switchover any different.

The particular scenario I tested was when DST becomes effective (only 23 hours) and in this case Google seems to realise that you cannot specify anything within the skipped hour and it adds one hour (e.g. 1:30am to 2:30am), though it extends the entire event by one hour (e.g. a one hour event suddenly shows two hours).

> So all varying degrees of "gee we never thought about it" even though a good half the world does DST.

Yep.

@arshaw
> good to know the rest of the world is just as bad as fullcalendar :)
> not saying this isn't an issue, but does put things into perspective.

Well .... ;)

> top priority is still the same: making sure events that fall into the gap don't disappear

That particular case would be even rarer than the overall issue already itself (considering a DST switch only happens twice a year), as it only affects events lasting _less than one hour_ on days when DST _ends_.

As I said earlier though, considering it is not a daily issue but happens at maximum only twice a year, I do not think everything needs to be dropped in order to fix it straight away but a good mid-term plan to target either next spring, or the latest next autumn, would be more than enough. However personally I would still not rate the issue as low-priority, but a decent medium one.

**Comment by neroux** [comment]
@arshaw Any updates on this issue?

**Comment by neroux** [comment]
Would you have any update @acerix?

**Comment by brajgopal** [comment]
@neroux  using timezone "America/Los_Angeles", need user to restrict from creating events during DST transition. Will be helpful if can show any alert message for user.

**Comment by neroux** [comment]
@brajgopal If the 23/25 hours approach outlined earlier was implemented it wouldnt be an issue, but thats apparently not going to happen.

**Comment by neroux** [comment]
@arshaw @acerix, is there any movement on this issue? Version 4 hasnt addressed it and as far as I understand version 5 wont either.

**Comment by neroux** [comment]
@arshaw @acerix, no comment?
