### ISSUE TITLE
Issue while using destroy inside windowResize

### ISSUE THREAD

**Issue by shruthikj** [fullcalendar/fullcalendar#3888]
Hello,

When **destroy** is used inside **windowResize**, the calendar content stops resizing horizontally after a range. But when I reload, the calendar fills the whole of the window.

<img width="1295" alt="screen shot 2017-10-23 at 3 21 41 pm" src="https://user-images.githubusercontent.com/12105075/31882913-ec8afe06-b805-11e7-82cf-882fbf59cf60.png">

[Click here ](https://www.useloom.com/share/9103039521234ff9ab75a85c65388947) to view the video where I have reproduced the issue.

**Comment by neroux** [comment]
As per the bug report requirements

> ### Bug Reports
> You MUST have a JSBin recreation, or else your issue will be CLOSED without explanation.
> Instructions: http://fullcalendar.io/wiki/Reporting-Bugs/

But why would you call `destroy` in the first place?

**Comment by shruthikj** [comment]
If I don't use 'destroy', the events don't resize and retain their initial width on windowResize.

**Comment by neroux** [comment]
I'd rather go with `rerenderEvents` in this case I guess.

But again, you'd need to post a working example.

**Comment by shruthikj** [comment]
@arshaw Any updates on this?

**Comment by arshaw** [comment]
Would you be able to post a [runnable, stripped-down demonstration of the bug](http://fullcalendar.io/wiki/Reduced-Test-Cases/)? Would really appreciate it because the time saved reproducing will be time spent fixing.

**Comment by shruthikj** [comment]
@arshaw The issue was caused from our side due to setting _max-width_ from an outer dom object. I'm closing this issue. Thanks.
