### ISSUE TITLE
error when event source is null

### ISSUE THREAD

**Issue by jamesdixon** [fullcalendar/fullcalendar#3890]
Continuation of conversation from #3845 
-----------

I maintain the [ember-fullcalendar](https://github.com/scoutforpets/ember-fullcalendar) addon and was updating from FC 3.3 to 3.6 when the following error occurred:

```
fullcalendar.js:16300 Uncaught TypeError: Cannot read property 'url' of null
    at Function.JsonFeedEventSource.parse (fullcalendar.js:16300)
    at Object.parse (fullcalendar.js:15981)
    at constructor.addEventSource (fullcalendar.js:13344)
    at HTMLDivElement.<anonymous> (fullcalendar.js:59)
    at Function.each (jquery.js:362)
    at jQuery.fn.init.each (jquery.js:157)
    at jQuery.fn.init.$.fn.fullCalendar (fullcalendar.js:36)
    at Class.observeEvents (full-calendar.js:219)
    at Object.applyStr (ember-utils.js:528)
    at sendEvent (ember-metal.js:378)
```

Clicking on the line referencing JsonFeed, I see the following:

![image](https://user-images.githubusercontent.com/110114/31588003-f2e7c27e-b1a8-11e7-92e5-26799b8e8ccc.png)

I incrementally downgraded to each previous version and things finally started working again when switching to v3.4.0.

Do you have any thoughts/suggestions?

Thanks!

**Comment by jamesdixon** [comment]
FWIW, I updated the `ember-fullcalendar` addon to check that the events being passed to `addEventSource` is not `null`. With that change, everything works as expected. That said, it seems like FC should deal with `null` just as it would an empty array or something similar. 

Would love to hear your thoughts and keep up the great work!

**Comment by jamesdixon** [comment]
From @arshaw:

```@jamesdixon that's a sufficiently different issue. the original issue was that the url property was absent from the successfully-process event source.

why is the response to a JSON feed returning null? that's a failure case I'm not sure fullcalendar should be obligated to handle.

could you open up a new ticket for further convo?
```

**Comment by jamesdixon** [comment]
@arshaw not disagreeing with you -- just wanted to point out that the behavior deviates from 3.3.

I'm not sure why the feed is `null`; I didn't get that far unfortunately 😄 

I think it's worthwhile check to add given its simplicity, but I understand if you don't want to add it either.

Thank you!

**Comment by arshaw** [comment]
no worries @jamesdixon . thanks for making the new ticket.

it's definitely a behavior change, but it's idiosyncratic enough where i don't want to go through any effort to match it to the old version. hope you understand

best,
Adam
