### ISSUE TITLE
Render function does not re-adjust calendar dimension after previously hidden element is shown

### ISSUE THREAD

**Issue by mbursa** [fullcalendar/fullcalendar#3893]
Calling `render` function to readjust calendar dimensions does not work as expected.

If the calendar is initialized on a hidden element
`<div style="display:none;"></div>`
and then after this element is shown and fullcalendar's render function is called, the component does not adjust its dimensions right. This bug seems to be introduced by version 3.6.0 as using version 3.5.1 it works as expected.

Demo:
https://codepen.io/anon/pen/MEdNeR?editors=1011

**Comment by arshaw** [comment]
confirmed, thanks.

here is a demo of 3.5.1 working correctly: https://codepen.io/arshaw/pen/xXvdgq?editors=1011

**Comment by philippfrenzel** [comment]
any workaround for this within the latest version apart from downgrading to 3.5.1?

**Comment by bebemau** [comment]
Also experiencing this issue, downgrading to 3.5.1 fixed the rendering issue but caused some other functionalities to stop working ie doubleClick.

**Comment by arshaw** [comment]
queued for release

**Comment by arshaw** [comment]
Released in [v3.7.0](https://github.com/fullcalendar/fullcalendar/releases/tag/v3.7.0).

**Comment by bebemau** [comment]
Thanks for the update.

I upgraded to the latest but still having issues where the event items are not being displayed initially.  It does look better where the times (i am using agendaWeek view) are all aligned.  Downgraded back to 3.5.1 fixes the issues.

**Comment by acerix** [comment]
@bebemau The original issue above does not occur in 3.7, please create a new issue with a [runnable, stripped-down demonstration of the bug](http://fullcalendar.io/wiki/Reduced-Test-Cases/) you are experiencing.
