### ISSUE TITLE
allDay - Not placed near callendar header.

### ISSUE THREAD

**Issue by luisfbmelo** [fullcalendar/fullcalendar#3894]
### Not Working in 3.6.2
If the `allDay` property is set with `"true"|"false"` or `1|0`, the event is not shown in the top of the calendar in agenda view, using version 3.6.2:
http://jsfiddle.net/Lqcjnk6h/

### Working in 3.4.0
With version 3.4.0, I can use the all options to set the property value:
http://jsfiddle.net/dddfbn4q/.

O believe that this is a way to standerize the var type, but since this is coming in json, is there a way to revert this to the previous way of setting `allDay`?

**Comment by arshaw** [comment]
if you change your `1` to `true`, it works as expected.

i understand that `0` and `1` may have been supported in previous versions, but since the docs say you must use a boolean, this behavior is rather undocumented so I'm not doing to go through the effort to maintain backwards behavior.

**Comment by luisfbmelo** [comment]
Thank you, I understand 😉.
