### ISSUE TITLE
localized format tokens, in combo with basic ones, wrong title

### ISSUE THREAD

**Issue by arshaw** [fullcalendar/fullcalendar#3898]
When a localized format string like `ddd` is combined in the same string with a normal one like `ddd`, the range formatting double-displays the date.

```
  $('#calendar').fullCalendar({
    titleFormat: 'ddd, ll'
   });
```

Will incorrectly display "Thu, Oct 26, 2017 – Oct 26, 2017"

Recreation: https://codepen.io/arshaw/pen/EbYNQg?editors=0010

**Comment by acerix** [comment]
Duplicate of #3645
