### ISSUE TITLE
Timezone is not preserved on selection

### ISSUE THREAD

**Issue by sp00m** [fullcalendar/fullcalendar#3899]
Given the following config (Europe/London being +0100):

```js
{
  timezone: "Europe/London",
  select: function (start, end) {
    console.log(start.toString());
    console.log(end.toString());
  }
}
```

If you select a period of time, say from 8AM to 10AM, you'll get:

```text
Fri Oct 27 2017 08:00:00 GMT+0000
Fri Oct 27 2017 10:00:00 GMT+0000
```

While I would expect:

```text
Fri Oct 27 2017 08:00:00 GMT+0100
Fri Oct 27 2017 10:00:00 GMT+0100
```

See http://plnkr.co/edit/ik4uIZPFwscHVRnA7ZT0?p=preview.

Let me know if I can help fixing this.

**Comment by neroux** [comment]
Not sure if related to #3887 but in this case it also seems to make a difference whether the timezone is statically assigned (Europe/London) or dynamically via `local`. In the latter case it seems to work just fine.

**Comment by neroux** [comment]
`start` and `end` generally do not seem to take the timezone into account but are always the local time locked to UTC. Accessing the view's start and end time in `eventAfterAllRender` shows the same behaviour.

**Comment by arshaw** [comment]
yeah, in this article, see the last section:

https://fullcalendar.io/docs/timezone/timezone/

> NOTE: Because the browser does not know the timezone offset for every time in every timezone, when an event is modified, whether through user dragging/resizing or updateEvent, the dates will become ambiguously-zoned.

https://fullcalendar.io/docs/utilities/Moment/#ambiguously-zoned

A lot of people do not like this behavior. I'm thinking of ways to make this better for v4.0. The issue stems from the fact that the browser does not know the timezone offset of every timezone in every browser.

**Comment by sp00m** [comment]
Could [Moment Timezone](https://momentjs.com/timezone/) be of any help?

Here is the way I temporarily fixed it:

```js
// see https://github.com/fullcalendar/fullcalendar/issues/3899
const fixTimezone = (wrongMomentInUtc, anotherMomentInTheExpectedTimezone) => {
  let fixedMoment = wrongMomentInUtc;
  if (0 === wrongMomentInUtc.utcOffset()) {
    const expectedUtcOffset = anotherMomentInTheExpectedTimezone.utcOffset();
    fixedMoment = wrongMomentInUtc.utcOffset(expectedUtcOffset);
    if (0 < expectedUtcOffset) {
      fixedMoment = fixedMoment.subtract(expectedUtcOffset, 'minutes');
    } else if (expectedUtcOffset < 0) {
      fixedMoment = fixedMoment.add(expectedUtcOffset, 'minutes');
    }
  }
  return fixedMoment;
};
```

A bit convoluted, but I haven't found any other more proper solution yet...
