### ISSUE TITLE
Empty row at the bottom

### ISSUE THREAD

**Issue by janswist** [fullcalendar/fullcalendar#3901]
I have strange allDaySlot-like row below calendar - not sure where it comes from since I disables allDaySlot option:
![image](https://user-images.githubusercontent.com/5583954/32143040-c0233016-bca3-11e7-9d2c-988dd90ca962.png)
Anyone knows what that is?

**Comment by arshaw** [comment]
are you hoping this would happen instead?
https://github.com/fullcalendar/fullcalendar/issues/265

**Comment by janswist** [comment]
@arshaw it's not documented anywhere and I couldn't find it in issues so no need to be rude. Thanks for pointing out why it is like this.
