### ISSUE TITLE
jQueryUI dependency required for dropping external events?

### ISSUE THREAD

**Issue by nhaberl** [fullcalendar/fullcalendar#3902]
Just would like to know if I still have to use jQueryUI for dropping events into fullcalendar?
As you mentioned [https://fullcalendar.io/docs/event_ui/Requirements/](https://fullcalendar.io/docs/event_ui/Requirements/) there is no dependency.

I'm asking because I would like to use other libs for drag and drop like [dragula](https://github.com/bevacqua/dragula)

**Comment by arshaw** [comment]
You're right, this is not clear in the docs.

jQuery UI isn't needed for dragging events within the calendar, but when you need to drag them from outside the calendar, you need jQuery UI.

https://fullcalendar.io/docs/dropping/droppable/

**Comment by arshaw** [comment]
as for the docs, it is somewhat mentioned here: https://fullcalendar.io/docs/droppable

**Comment by arshaw** [comment]
This issue has been addressed in the latest alpha release (4.0.0-alpha.2)
[See the blog post &raquo;](https://fullcalendar.io/blog/2018/10/release-v4-alpha2)

No need for any third party libs anymore:
https://fullcalendar.io/docs/v4/external-dragging

**Comment by arshaw** [comment]
I'm closing this issue to signify that it's implemented (since v4-alpha2). I'll comment on this thread again when v4 is officially released.

**Comment by arshaw** [comment]
[V4 was officially released a few days ago!](https://fullcalendar.io/blog/2019/03/v4-officially-released)
