### ISSUE TITLE
Use Same Google Calendar For Both Event And Background Rendering Failed in v3

### ISSUE THREAD

**Issue by tsaiid** [fullcalendar/fullcalendar#3904]
### Bug Reports

I use the same google calendar for both event and background event rendering. 

The rendering is good in v2.9.1: http://jsbin.com/kosucow/edit?html,js,output

But failed in v3.6.2:  http://jsbin.com/hogocas/edit?html,js,output

**Comment by Druidsnake** [comment]
Same =(
![captura](https://user-images.githubusercontent.com/3800087/32336105-64dbe358-bfbc-11e7-9d99-d71e99879e74.JPG)

**Comment by arshaw** [comment]
recreated, thanks. the bug is probably related to the two event sources sharing the same google calendar ID.

**Comment by arshaw** [comment]
when adapted to v5, seems to work well:
https://codepen.io/arshaw/pen/LYGLXrj?editable=true&editors=001
