### ISSUE TITLE
feature: disable forceScroll in display()

### ISSUE THREAD

**Issue by Voyz** [fullcalendar/fullcalendar#3907]
Could we have a boolean flag to set that would prevent forceScroll from executing in `display`:

```
else {
    _this.forceScroll(_this.computeInitialScroll(prevScrollState));
}
```
line 8128.

I'm trying to implement scrolling to various times (depending on the day and the day's contents) and this line always default-scrolls to scrollTime. I'm temporarily working around by using a setTimeout, but ideally - could there be a flag that would disable this feature?

```
else {
   if(_this.opt('forceScrollEnabled'){
        _this.forceScroll(_this.computeInitialScroll(prevScrollState));
    }
}
```

**Comment by arshaw** [comment]
hi @Voyz , i believe this ticket already captured what you want:
https://github.com/fullcalendar/fullcalendar/issues/1037
&uarr;
Could you please visit the link, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates?

**Comment by Voyz** [comment]
Indeed, thank you!
