### ISSUE TITLE
eventLimit on all views

### ISSUE THREAD

**Issue by damirsel** [fullcalendar/fullcalendar#3909]
I'm wondering is eventLimit available only for month view, since I can't see results in other views, for example when I set following config:

```
eventLimit: 4,
           views: {
               basic: {
                   eventLimit: 4
               },
                agenda: {
                   eventLimit: 4
               },
               week: {
                   eventLimit: 4
               },
               day: {
                   eventLimit: 4
               }
           }

```

**Comment by arshaw** [comment]
it should be working all those views.

could you post a codepen link of it not working?
https://fullcalendar.io/wiki/Reduced-Test-Cases/

**Comment by damirsel** [comment]
sure, you can see it here https://codepen.io/dsel/pen/qVRRrp samo goes for day view...

**Comment by arshaw** [comment]
i see. you're expecting event limit to work for events that have times and are rendered within the time slot section? right now eventLimit only works for events within the all-day section as well as for the day tiles within month/basic view.

other ppl have requested their be an eventLimit for the event slot but nobody has been able to give me a hint of what the UI would look like. Are there any other products that have a UI like this? could you make a screenshot mockup?

**Comment by shivam25** [comment]
Hello Arshaw,

Somehow I am also facing same difficulties in my application using eventLimit in timelineView, agendaWeek etc. However I am able to give you some design(attached) of how I want my UI to be as asked by you in above comment.

Please have a look at below images and tell us how feasible it is as a solution.
![sample1](https://user-images.githubusercontent.com/4638586/39233619-7d26ad8e-488e-11e8-9fd8-1cd994cff82c.png)
![sample2](https://user-images.githubusercontent.com/4638586/39233620-7d664eda-488e-11e8-8b1f-9b1272845e93.png)
![sample3](https://user-images.githubusercontent.com/4638586/39233621-7daf8bc2-488e-11e8-98d0-0e249fc883fa.png)
