### ISSUE TITLE
Event spanning multiple days does not show event start/end time

### ISSUE THREAD

**Issue by Prabhakar-Poudel** [fullcalendar/fullcalendar#3913]
I have observed that event spanning multiple days shows start/end time only on the first and last day.
Rest of the days just shows up the event title.

![fcbug](https://user-images.githubusercontent.com/20899846/32445167-f52da600-c32a-11e7-920a-760ff8fc3981.png)

Not so sure what is the use case of current implementation (other than it being visually obvious and not required to show the time range). But IMO, it would be more consistent if we could render the time range over each day. May be a flag to turn feature on/off could get better of both worlds.

**Comment by arshaw** [comment]
i believe this existing ticket captures this need:
https://github.com/fullcalendar/fullcalendar/issues/3038
&uarr;
Could you please visit the link, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates?

**Comment by jayatulsiani** [comment]
is this ticked resolved? I dont see whether its resolved or not. if yes then how to set the properties of the event? It would be great if anyone links to this comment. thanks in advance.
