### ISSUE TITLE
Themes not loading due to new Bootswatch URLs

### ISSUE THREAD

**Issue by simsketch** [fullcalendar/fullcalendar#3916]
Bootswatch CSS files are returning a 404, causing no themes to be loaded

https://fullcalendar.io/js/fullcalendar-3.6.2/demos/themes.html

They changed the URLs of their theme files. Instead of

ie: https://bootswatch.com/cosmo/bootstrap.min.css

it is now

ie: https://bootswatch.com/4/cosmo/bootstrap.css
https://bootswatch.com/4/darkly/bootstrap.css

**Comment by simsketch** [comment]
https://github.com/fullcalendar/fullcalendar/pull/3917

**Comment by simsketch** [comment]
created a pull request if you'd like.

**Comment by arshaw** [comment]
queued for release

fyi, i needed to do `/3/` for bootstrap 3, b/c that's what fullcalendar supports, and the classnames for 4 look weird.
