### ISSUE TITLE
Not working in fullcalendar 3.6.2

### ISSUE THREAD

**Issue by nitin19** [fullcalendar/fullcalendar#3921]
Hello,

I have updated fullcalendar version but year view is not working. Please help with updated fullcalendar version.

Thanks

**Comment by espen** [comment]
### Bug Reports
You MUST have a JSBin recreation, or else your issue will be CLOSED without explanation.
Instructions: http://fullcalendar.io/wiki/Reporting-Bugs/

**Comment by acerix** [comment]
Would you be able to post a [runnable, stripped-down demonstration of the bug](http://fullcalendar.io/wiki/Reduced-Test-Cases/)? Would really appreciate it because the time saved reproducing will be time spent fixing.
