### ISSUE TITLE
Eager fetching generates an infinite loop when trying to dynamically set an option in my events fetcher function

### ISSUE THREAD

**Issue by sp00m** [fullcalendar/fullcalendar#3923]
A bit of an edge case, but I could not find a workaround yet.

I have a [custom function to fetch my events](https://fullcalendar.io/docs/event_data/events_function/). The API I'm calling returns both the events and the min/max times to display (as the min/max times depend on the fetched events).

So, once I got my events, before invoking the callback, I [dynamically set](https://fullcalendar.io/docs/utilities/dynamic_options/) the `minTime` and `maxTime` options.

This works when I have the [lazy fetching option](https://fullcalendar.io/docs/event_data/lazyFetching/) enabled, but I need it to be disabled. When I disable it (i.e. eager fetching enabled), dynamically setting the option in the function generates an infinite loop, probably because this triggers the fetch of the events again, which then triggers the fetch of the events again, etc.

Here is an example: http://plnkr.co/edit/521W0zNZudZuhHeHDpo2 (don't worry, it will fail after 3 iterations).

Any thoughts about this?

Also, any idea of a workaround to help me continue with my stuff before a potential fix is pushed? I tried to set the option via `fullCalendar("getView").options.minTime = "10:00:00";`, but nothing happens, even after firing `"render"`. I tried to play with the `viewRender` callback as well, but still no success.

**Comment by acerix** [comment]
The docs say if [lazyFetching](https://fullcalendar.io/docs/event_data/lazyFetching/) is false, 
> the calendar will fetch events any time the view is switched, or any time the current date changes.

So it looks to be working as expected; if you change the view after events are loaded, that will cause the events to get fetched again if lazyFetching is false.

If you want to change `minTime` without reloading events, lazyFetching should be `true`.

**Comment by sp00m** [comment]
Well, lazy fetching does not seem to be possible in my case, as I have a switch that allows me to display events from different sources. So say for a given week, displayed events can be different depending on the switch.

Maybe can I enable lazy loading, but clear the cache before each fetch somehow? Could not find any "clear cache" feature in the docs.

**Comment by sp00m** [comment]
Also:

> The calendar will fetch events any time the view is switched, or any time the current date changes.

I would personally not expect minTime/maxTime to fit these conditions (view is not switched, current date does not change).

**Comment by sp00m** [comment]
I've tried playing with [`OptionsManager.add(newOptionHash)`](https://github.com/fullcalendar/fullcalendar/blob/9c97382a2b22aed5a217fedc261edbe60fe4ab6a/src/OptionsManager.ts#L26), could not find any workaround yet. Any idea for a temporary workaround is welcome!

**Comment by arshaw** [comment]
@sp00m , as a hack, when you set minTime/maxTime, try also setting `lazyFetching` to `true` at the same time (using the [compound options setter](https://fullcalendar.io/docs/utilities/dynamic_options/)). Then afterwards, set it back to `false`. When you set it back to false, it will try to refetch again sadly, so you might need to add a hack [around here](https://github.com/fullcalendar/fullcalendar/blob/9c97382a2b22aed5a217fedc261edbe60fe4ab6a/src/OptionsManager.ts#L38) to short-circuit for the lazyFetching option.

**Comment by sp00m** [comment]
@arshaw Interesting, could indeed work. I'll keep you updated.

Do you think this ticket is an actual issue BTW?

**Comment by acsar** [comment]
I also have a similar problem!
The simple fact of configuring the language, generates a new request to the server!
[](https://codepen.io/acsar/pen/eYNRmPX?editors=1111)

**Comment by arshaw** [comment]
version 5, which was [just officially released](https://fullcalendar.io/blog/2020/06/v5-official), no longer has this problem.

proof: https://codepen.io/arshaw/pen/abdWvoB?editors=0010

You'll only see a console.log for one request, not two.
