### ISSUE TITLE
onclick on today button not working

### ISSUE THREAD

**Issue by javaanalist** [fullcalendar/fullcalendar#3927]
Hi all,
i have a problem with today button on fullcalendar 3.6.0. I have implemented a custom method, this method is called onclick of next,prev,month,agendaweek,agendaDay,today buttons.
Whereas it's ok for next,prev,month,agendaweek,agendaDay buttons, it's not working on today button.
Below is my code.

$(document).on('click', 'button.fc-next-button', function () {
	  alert('next button');
  }); 

  $(document).on('click', 'button.fc-prev-button', function () {
	  alert('prev button');
  });

  $(document).on('click', 'button.fc-month-button', function () {
	  alert('month button');
  });  
  
  $(document).on('click', 'button.fc-agendaWeek-button', function () {
	  alert('agendaWeek button');
  });

  $(document).on('click', 'button.fc-agendaDay-button', function () {
	  alert('agendaDay button');
  });
  
  $(document).on('click', 'button.fc-today-button', function () {
	  alert('today button');  
  });

**Comment by acerix** [comment]
It's not obvious why `$(document).on('click'` doesn't fire for the Today button, but I got it to work with this code:
```javascript
$('button.fc-today-button').click(function() {
  alert('today button');
});
```
https://codepen.io/anon/pen/KyXMbG

If it's still an issue, please post a [runnable, stripped-down demonstration of the bug](http://fullcalendar.io/wiki/Reduced-Test-Cases/).
