### ISSUE TITLE
Recurrent Background Events

### ISSUE THREAD

**Issue by danyfu** [fullcalendar/fullcalendar#3928]
Hello I trying to make a recurrent background event, for mark weekends as not workable days.

I test with an example of one jsfiddle that I find in stackoverflow of implementation of recurrent weekly event in montly view. [http://jsbin.com/zovopu/2/edit?html,js,output] (http://jsbin.com/zovopu/2/edit?html,js,output).

The event has been structured like this:
```
{
	title: "Elementary & Middle School Art Exhibit",
	start: '2016-06-03T13:00:00',
	end: '2016-06-26T23:59:59',
	dow:[0,3,4,5,6],
	url: "event.cfm?pid=122&event=Elementary & Middle School Art Exhibit"
}
```

And its works fine for recurrent wekly events.

But if i set the attribute rendering as "background" the events are not displayed. [http://jsbin.com/xiqage/edit?html,js,output](http://jsbin.com/xiqage/edit?html,js,output)

How can I show the background recurrent events?

**Comment by danyfu** [comment]
I just make a implementation of recurrent background event using a plugin of moment called [moment-recur](https://github.com/c-trimm/moment-recur). But it will be good if we can do it also for yearly dates like 4th of July or 25th of December, etc.

Here is the jsbin with the implementation: [http://jsbin.com/xutome/4/edit?html,js,output](http://jsbin.com/xutome/4/edit?html,js,output)

**Comment by acerix** [comment]
In your second example, I see the [events only show in Agenda View](http://jsbin.com/raximutina/3/edit?html,js,output), which is how [Background Events](https://fullcalendar.io/docs/event_rendering/Background_Events/) are described in the docs:
> Background events that are timed will only be rendered on the time slots in agenda view.

But after removing the times, the [events still do not show](http://jsbin.com/saqutitudu/edit?html,js,output) in month view, is that what you are referring to?  ie. you want to have background events that are recurring and also have start/end dates?

There is also the [https://fullcalendar.io/docs/display/weekends/](option to hide weekends) that might work instead.

**Comment by danyfu** [comment]
@acerix Thanks for your response. I need to show the weekends. I don't need the Agenda View right now, only the Monthly View.

The really thing I am doing is a Working Calendar that a user can specify events in this calendar. Exception of dates the user can specify a event are:

- **The working week.** An array of numbers that represents the days of the week, where the user can assign events. So the days that are not specified in the array are disabled of assigning events. For example if the array is [1,2,3,5], that means the user can't drop events on Sundays, Thursdays and Saturdays.

- **Holidays**. An array of recurrent yearly dates that the user specify that can be between on the work week but that day can't be assigned a event because inthat day is not workable, For example 25th of December, 1st of January, etc.

I was trying to use the "background" events because it looks different as the "normal" events, but I just handle this issue with the method [dayRender](https://fullcalendar.io/docs/display/dayRender/) and make the validation if the date is a recurrent no workable day in the working week or is a holiday for setting the background color of the cell as gray, to set the look like if was disabled. And ussing the [eventAllow](https://fullcalendar.io/docs/event_ui/eventAllow/) method for make the constrain of where the user can drag and drop an event.

**Comment by acerix** [comment]
If I understand, you have resolved the issue by using a different the style, etc. instead of using `rendering=background`, so I'll close the ticket because background events seem to be working properly.

**Comment by danyfu** [comment]
Yes, maybe we can implemt something like this for recurrent events.

#387

**Comment by stefanuebe** [comment]
Seems like this is still a problem, right? Tried to add recurring background events, e. g.
```
{
    title: "some bg",
    dow:[0,6],
    rendering: "background",
    color: "blue"
}
```

an it is not displayed.
