### ISSUE TITLE
DayClick doesn't work with zoom on Chrome

### ISSUE THREAD

**Issue by tacieana** [fullcalendar/fullcalendar#3935]
When I set a zoom to my document, the DayClick event of fullCalendar take wrong hour.

I understood that the zoom modifies the hour where the element is shown in the window, so when you click in "4 hour" for example, the calendar takes 2 hours before.

This error occurs only on Google Chrome because Firefox doesn´t change the zoom.

For the example the DayClick event will show a alert with the date/hour:
https://codepen.io/tacieana/pen/rYYZZa

Could you help me with this please?
Thanks

**Comment by acerix** [comment]
I see the issue in Chrome; when clicking on an hour slot, the CSS zoom is ignored, so it doesn't open the same slot that was clicked on.

However, CSS zoom is not standard, and it works properly with this CSS, which also works in Firefox:

```css
transform: scale(0.8, 0.8);
```

https://codepen.io/anon/pen/yPPWoe

Does that work for you?
