### ISSUE TITLE
Render fullcalendar events as progress bar

### ISSUE THREAD

**Issue by M1991** [fullcalendar/fullcalendar#3940]
# Issue : Render fullcalendar events as progress bar

I am trying to build an application, a scheduler that reflects the events in the fullcalendar and schedules them according to business logic. All the business logic working fine but I am unable to render events as progress bar. Below is reference fiddle :-

-[Reference Fiddle](http://jsfiddle.net/Manoj_89/tda7obtb/1/)

-[Git pull request with Visual (Image provided how the UI looks)](https://github.com/fullcalendar/fullcalendar/pull/3929)

Logic:  All events will be rendered from DB. Also, will divide the total time taken into 10 parts (progress increment +10 for each) from start date and end date and will be passed into a variable 'value'. As jsprogress bar requires a value for showing the successive progress.

Could you help me with this please?
Thanks

**Comment by acerix** [comment]
I get this error when trying your fiddle: `Uncaught TypeError: event.progressbar is not a function`.

The progressbar is for Jquery elements, so something like this instead:
```
$(element).progressbar()
```
http://jsfiddle.net/2nz9aj1d/

**Comment by M1991** [comment]
Thanks a lot.

I will try this and lots of other modifications are to be made. Will keep trying with new changes.

Thanks. Cheers.
