### ISSUE TITLE
MVC helper

### ISSUE THREAD

**Issue by HajbokRobert** [fullcalendar/fullcalendar#3942]
Hi,

I've been working on a [MVC helper](https://github.com/HajbokRobert/FullCalendarMVC) for this project, and it turned out I can support all the options for version 3.5.1 at the moment. For the moment I support around 85% of these. I would like to publish this as a NuGet package, using [this](https://www.nuget.org/packages/jQuery.Fullcalendar) as a dependency, it might be useful for some ASP.NET MVC guys out there. If you agree, let me know where should I give you credit for this. Keep up the good work!

**Comment by acerix** [comment]
I'm not familiar with MVC, is your project basically a wrapper to make it easier to use FullCalendar from Visual Studio?

You are giving credit by including a copy of the licenses with the code, so I'm not sure what you are asking.

**Comment by HajbokRobert** [comment]
Yes, something like that. I will publish the package than. Thanks!
