### ISSUE TITLE
First day in View - Event spans from previous day ignoring nextDayThreshold

### ISSUE THREAD

**Issue by melzmedia** [fullcalendar/fullcalendar#3943]
I'm using fullcalendar-3.7.0. I'm working on a calendar to display on-call shifts. They are consistent 24 hour shifts from 8am to 8am the next day.

I only want the shifts to display on their start date so I've turned off spanning by using: 
`nextDayThreshold: "09:00:00" `

Expected Results: 
All events respect nextDayThreshold and are only displayed on their Start Date

Actual Result: 
Most events respect nextDayThreshold, except the first day in the basic monthly/week view also displays the spanned events from the previous day. These events don't display the time and are left-aligned in the cell.

Here is a JSbin example - The issue is visible in the Month/Week view on October 1st: http://jsbin.com/sibehix/14/edit?html,js,output

This is causing some confusion among users. Is there a way to have the first day of the view respect the nextDayThreshold like the other days?

**Comment by acerix** [comment]
Thanks for the report, I agree that since Shift 1 starts in Sept and ends at 8 am on Oct 1, it should not show in October since nextDayThreshold is later in the day.

**Comment by fesjes** [comment]
Hi,

is this something that will be addressed?

**Comment by arshaw** [comment]
This has been very difficult to fix w/o a refactor, so here's a workaround for now:

```js
    eventRender: function(eventObj, el, view) {
      if (
        eventObj.start < view.start &&
        eventObj.start.time() < NEXT_DAY_THRESHOLD
      ) {
        return false;
      }
    },
```

https://codepen.io/arshaw/pen/LQPXQj?editors=0010

**Comment by nathansamson** [comment]
@arshaw Your code snippet seems wrong

I have this modification.
Basically it renders if the start was not in this view, and the end date (beginning of day) is smaller or equal than view.start (=> ends the day this view starts).
Note this is for the special case the NEXT_DAY_TRESHOLD is midnight.

This also works for events longer than 24 hour (even spanning several weeks)
This also works for events that start before the next time treshold (eg imagine your treshold is 6:00, your event is starts at day 1 at 3:00, and ends 3 weeks later on monday. In the weekview it would basically not show up in week 2 with your snippet.

Note this is still a workaround, you still get a "visual glitch" at the end of the previous week where the event is open ended (it should not be)

~~~
eventRender: function(event, el, view) {
    if (event.start < view.start && event.end.startOf('day') <= view.start) {
        return false;
    }
~~~

**Comment by melzmedia** [comment]
@arshaw Thank you! Your code worked perfectly for me!

**Comment by arshaw** [comment]
will be fixed when v4 is released. 78f29f6e810242ce03a7b455ba295858257fad5a

**Comment by arshaw** [comment]
[V4 was officially released a few days ago!](https://fullcalendar.io/blog/2019/03/v4-officially-released) This issue is fixed.
