### ISSUE TITLE
Add support for Microsoft Exchange Web Services

### ISSUE THREAD

**Issue by dbrewerton** [fullcalendar/fullcalendar#3944]
What I think would be extremely useful is to add Exchange Web Services (EWS) support. Currently I have to use code behind c# to read and authenticate against the calendar, convert the received data to JSON format and then it will display on the calendar. Perhaps adding some type of ASP.NET hooks that allow the calendar to authenticate so it can pull these items from Exchange. Thank you.

**Comment by acerix** [comment]
Not sure I understand, are you authenticating with EWS and retrieving events on the server side, then sending them to the client side with JSON? It's not clear what kind of support could be added for that, could you provide some sample hooks that you are looking for?
