### ISSUE TITLE
Implement a remove button.

### ISSUE THREAD

**Issue by JNPSoftware** [fullcalendar/fullcalendar#3945]
Is it possible to implement a remove button like this paint image:

![image](https://user-images.githubusercontent.com/33754986/33039570-86aea8f0-ce1f-11e7-9280-fe24a561f220.png)

And a eventRemove

> $('#calendar').fullCalendar({
   eventRemove: function(calEvent, jsEvent, view) {
      console.log('removeClick id: ' + calEvent.id);
    }
});

**Comment by acerix** [comment]
A built-in remove button sounds like a useful feature, although it shouldn't be hard make a hack for that functionality.

There is already [removeEvents()](https://fullcalendar.io/docs/event_data/removeEvents/) which I believe is what you are asking for with `eventRemove`.

**Comment by amaster507** [comment]
I think if this is implemented a onEvenDelete trigger would be helpful.

**Comment by JNPSoftware** [comment]
@acerix i'm thinking eventRemove( CallBack ) event like eventResize, eventDrop, etc. 
I work with Delphi and use a lot callback events. 
I implemented an external button and use removeEvents in this button. 
But a remove button **inside** the core with a callback would be wonderful.

**Comment by acerix** [comment]
Ahh, there is the [eventDestroy](https://fullcalendar.io/docs/event_rendering/eventDestroy/) callback for that.

**Comment by JNPSoftware** [comment]
@acerix when eventDestroy event is fired? I would like to reproduce this event.

**Comment by acerix** [comment]
`eventDestroy` fires before each event element is removed from the DOM, so it's not actually what you want because it fires for each event, not just the event(s) being removed:

http://jsfiddle.net/2shxcv0q/  (click an event to remove)

Instead you are looking for an `eventRemove` callback that fires when the remove button is clicked, but before the event is removed?  For example, the callback might delete the event from a database in an AJAX call, in which case the event would only be removed after the AJAX succeeds.

**Comment by JNPSoftware** [comment]
@acerix thank you for your example, i can figure out how eventDestroy works.
I made a little change to explain my point of view.

http://jsfiddle.net/2shxcv0q/1/ (click an event button to remove)

In this modified example you can see how i imagine fullcalendar working with a removeBtn. Off course eventRender is for example only.

**Comment by arshaw** [comment]
@JNPSoftware, i'd prefer this functionality not to be in core as a built-in future. what you did with `eventRender` and `removeEvents` is exactly the right route... allows people so solve this their own way using the API. maybe if there's a more robust plugin architecture in the future, this could be a plugin, but closing this case for now
