### ISSUE TITLE
Fullcalendar  instant touch in touch device

### ISSUE THREAD

**Issue by vivek543** [fullcalendar/fullcalendar#3948]
Hi,
Awesome fullcalendar plugin.In Touch device,can u tell me the solution of instant touch event.I am not able fix that issue and in system(In mouse events perfect).So,Kindly give the solution for the touch device and i attached the jsfiddle link for ur reference..

https://jsfiddle.net/sf11633n/26/

**Comment by acerix** [comment]
I opened your example on my phone, and it seems to be working properly.  I can move events by touching them for a few seconds to select, then dragging.

What are you trying to do that is not working?

**Comment by vivek543** [comment]
Hi,
thanks,working good,can u make it to do like instant touch and dragging,Here my requirement is instant touch and dragging things.here people no one knows touch for few seconds and then drag.thats my problem.

**Comment by acerix** [comment]
By default, there is a delay of 1 second, you can set [longPressDelay](https://fullcalendar.io/docs/event_ui/longPressDelay/) to zero for no delay.

https://jsfiddle.net/sf11633n/27/

**Comment by vivek543** [comment]
Thank a lot,this will helps me.

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by bakseungho** [comment]
> 기본적으로 1 초의 지연이 있으며 지연 없이 [longPressDelay](https://fullcalendar.io/docs/event_ui/longPressDelay/) 를 0으로 설정할 수 있습니다 .
> 
> https://jsfiddle.net/sf11633n/27/

와우 감사합니다 Thank you
