### ISSUE TITLE
eventOrder doesn't work on custom fields because they are now in miscProps

### ISSUE THREAD

**Issue by AlanBell** [fullcalendar/fullcalendar#3950]
https://codepen.io/anon/pen/ooyoBZ?editors=0010

line 487 of fullcalendar.js in compareByFieldSpecs function

return flexibleCompare(obj1[fieldSpec.field], obj2[fieldSpec.field]) 

doesn't work because the custom field isn't a direct property of obj1, so this would work:
return flexibleCompare(obj1.miscProps[fieldSpec.field], obj2.miscProps[fieldSpec.field]) 

however that wouldn't work for the standard fields

**Comment by acerix** [comment]
Thanks for the report and test.  It works as expected with old version 3.4.0.

**Comment by danyfu** [comment]
Hello,

You can sort with custom fields, if you use eventOrder as a function.
Here is a example in jsbin: [https://jsfiddle.net/8zqgckf5/6/](https://jsfiddle.net/8zqgckf5/6/)

In the documentation, explains [that](https://fullcalendar.io/docs/event_rendering/eventOrder/):

> This setting accepts a few different arguments:
> 
> a name of an Event Object property, like "title". This can be the name of a non-standard field. Sorting will happen in ascending order. If prefixed with a minus sign like "-title", sorting will happen in descending order.
> 
> a comma-separated string of property names, like "title,propA,-propB"
> 
> a function that accepts two arguments and returns -1 or 1, similar to sort's compare function.
> 
> an array of property names and functions like [ "title", "-propA", myFunc ].

**Comment by arshaw** [comment]
eventOrder now considers the props in miscProps. Should be working as originally expected. released in 3.8.1
