### ISSUE TITLE
add segment information to eventRender callback

### ISSUE THREAD

**Issue by w-site** [fullcalendar/fullcalendar#3956]
Add segment argument to hook eventRender that allow user to customize event rendering based on information about current rendered segment.

It will be very helpful to get additional information about segment. For ex. attributes firstRowDayIndex, lastRowDayIndex for customization my event.
For ex. in month view if I know firstRowDayIndex, lastRowDayIndex I can figure out what is the size of current rendered segment of event and based on this information I can attach html that I need, this is one of the case.

I think in any case info about segment will be helpfull for some case.
Thanks.

https://github.com/fullcalendar/fullcalendar/pull/3952

**Comment by w-site** [comment]
@acerix @arshaw Hi. So, what do you guys think about this improvement ? Are you going to support something like this in next releases ?
Thanks.

**Comment by arshaw** [comment]
this is a good idea.

changing the arguments for `eventRender` will be considered a breaking change, and i'll save it for 4.0, which might be in a little bit. best solution is to make your own fork for now

**Comment by arshaw** [comment]
[V4 was officially released a few days ago!](https://fullcalendar.io/blog/2019/03/v4-officially-released)
