### ISSUE TITLE
Resize events previously retrieved from eventSource 

### ISSUE THREAD

**Issue by danyfu** [fullcalendar/fullcalendar#3957]
Hello,

I have a problem to manipulate (resize) of the events that I previously get from an endpoint, in this endpoint receive an array of JSON objects as represent events, which each one is structured like this:

> {
> id: _String_
> title: _String_
> start: _Date_
> end: _Date_
> }

The start date is always set on the first minute of the day: **YYYY-MM-YYT00:00:00.000Z**.
The end date is always set on the last minute of the day: **YYYY-MM-YYT23:59:59.999Z**.

So once the render of the calendar is complete and shows the events are set from eventSource, I want to resize those events but I can't. I don't know is because are render with the time, like this image:

![image](https://user-images.githubusercontent.com/9112457/33292330-bcdc9834-d37d-11e7-9582-331547cbbdf6.png)

Here is an example of a jsbin: [https://jsfiddle.net/f4o3ckup/4/](https://jsfiddle.net/f4o3ckup/4/)

**Comment by acerix** [comment]
Events can only be resized in Month view if the start/end are only dates without time.  If there is a time, they can be resized in the Week or Day view instead.

https://jsfiddle.net/6pw9qhc5/1/

It sounds like you could just remove the times from your events.  If not, are you looking to have those events editable in month view, so resizing would change only the dates, preserving the time of day?

**Comment by danyfu** [comment]
@acerix, thanks for your response. I don't think I would need the time for now so I going to parse the dates to remove the time and only use the dates.

Is this answer is also on the documentation because i don't see it.

**Comment by acerix** [comment]
I didn't see this explained in the docs, should probably be mentioned here:

https://fullcalendar.io/docs/event_ui/editable/

**Comment by danyfu** [comment]
I see that
