### ISSUE TITLE
Render broken in wkhtmltopdf and QtWeb (broken by 3.7.0)

### ISSUE THREAD

**Issue by nreynis** [fullcalendar/fullcalendar#3960]
The compatibility with wkhtmltopdf and QtWeb has been broken by this commit:

https://github.com/fullcalendar/fullcalendar/commit/ad6b792001cd9add1287da31ff99a616c653bdda

More particulary theses edits
### src/Calendar.render.js
```
148 -	this.listenTo(renderQueue, 'start', this.onRenderQueueStart);
149 -	this.listenTo(renderQueue, 'stop', this.onRenderQueueStop);
```
### src/View.js
```
80 +	this.renderQueue.on('start', this.onRenderQueueStart.bind(this));
81 +	this.renderQueue.on('stop', this.onRenderQueueStop.bind(this));
```

These runtimes do not yet implement Function.prototype.bind and will throw the following errors:
```
TypeError: 'undefined' is not a function (evaluating 'this.onRenderQueueStart.bind(this)')
TypeError: 'undefined' is not an object (evaluating 't.queryScroll')
```

Not sure if you want to include a polyfill in fullcalendar (as this have rather good support in regular browsers) or just document it as a compatibility issue.
This can be polyfilled by the user themselves if they need it.

Sorry for the lack of proper codepen, but as it is not reproducible in mainstream browser, I'm not sure this is relevant.

**Comment by acerix** [comment]
Thanks for the report. 

Since those are not [supported browsers], it makes sense for users to add their own polyfill if they want to get it working.

Adding support for other browsers could be a feature request if it seems worth it.
