### ISSUE TITLE
Moment.js format date display "A" or "P" instead of "T" with event date

### ISSUE THREAD

**Issue by Guilouf** [fullcalendar/fullcalendar#3961]
I don't know if this issue is more related with moment.js, but it happens only with event dates from fullcallendar. 

I try to to format the dates as `iso8601`, with date and hours even if there is only a date stamp provided, (e.g `2017-06-01T00:00:00`) so the `.format()` alone is not a solution for me, because i want the same format everytime, even if hours not provided (set to  #0).

`format('YYYY-MM-DDTHH:mm:ss')` could have worked perfectly, but the 'T' of `iso8601` is replaced with either a 'A' or 'P', depending the hour (A.m P.m).

However, this comportement only shown moment.js instance from a fullcalendar event.
Here is the code  #(3.7.0): http://jsfiddle.net/jso51pm6/284/ (in eventClick)

I also found this in the moment.js issues: https://github.com/moment/moment/issues/4081
Workaround is to escape the 'T' between `[ ]`

**Comment by caseyjhol** [comment]
You can include custom text that won't be formatted by wrapping in square brackets to escape the text. See http://momentjs.com/docs/#escaping-characters.

```js
event.start.format('YYYY-MM-DD[T]HH:mm:ss');
