### ISSUE TITLE
Impossible to make the calendar display : no error

### ISSUE THREAD

**Issue by crouti** [fullcalendar/fullcalendar#3965]
FullCalednar 3.7
jQuery edge
Please see this jdfiddle 
http://jsfiddle.net/o1xg041h/1/

**Comment by neroux** [comment]
Moment.js is missing in your external resources

**Comment by crouti** [comment]
Thanks, but even added, it's not enough : http://jsfiddle.net/o1xg041h/2/
Something else needed ?

**Comment by neroux** [comment]
You need to run it before FullCalendar

**Comment by crouti** [comment]
Correct! it works : http://jsfiddle.net/o1xg041h/3/
One more thing, why the weekList is not displayed ?
Thanks

**Comment by neroux** [comment]
weekList is not a valid view.

**Comment by crouti** [comment]
thank you : http://jsfiddle.net/o1xg041h/4/
