### ISSUE TITLE
eventClick changed all clicked earlier events

### ISSUE THREAD

**Issue by mariusz88011** [fullcalendar/fullcalendar#3967]
Hi, I use a modal to display the information of the event. When I click on an event and click 'save changes', and then I click on another event and also click 'save changes', the two events update with the last information.
See code https://jsfiddle.net/6sLrwvpz/5/

**Comment by acerix** [comment]
This issue is that `on('click')` in jQuery does not replace previous `on('click')`s, so your code is running the callbacks for all previous buttons clicked as well.  It works if you remove previous callbacks like this:

```js
$(".antosubmit2").prop("onclick", null).off("click");
```

https://jsfiddle.net/20yg79go/1/

**Comment by mariusz88011** [comment]
Thanks for your help
