### ISSUE TITLE
eventAllow always have same dates in dropLocation, draggedEvent.

### ISSUE THREAD

**Issue by dimensi** [fullcalendar/fullcalendar#3969]
https://codepen.io/anon/pen/wPOqEe?editors=0011
The dates for the event and for dropLocation are always the same. Because of this, there is no way to check where the event comes from and where it should come.
![screenshot_20171204_183125](https://user-images.githubusercontent.com/11390039/33560655-66d4e992-d921-11e7-8fdc-dfa5887d5b2e.png)

**Comment by acerix** [comment]
Thanks for the report.

I would expect `draggedEvent.start` to be the date of the event before dragging, but instead it is the date where it was will be after dragging which is the same as `dropLocation.start`.

As a workaround, you can load the event data by it's ID, which has the start date before dragging:

https://codepen.io/anon/pen/MOxZoQ?editors=0011

**Comment by arshaw** [comment]
It'd be great to get a repro of this in v4

**Comment by baileyandy** [comment]
I think this issue is fixed.

I'm using `v4.2.0` and wired up an `eventAllow` function today. The `span` argument is definitely updating when an event is dragged fully or being extended. The `movingEvent` start and end times are correctly showing the original location.

**Comment by acerix** [comment]
Thanks for the info.  Confirmed fixed in v4:

https://codepen.io/acerix/pen/oKajzK?editors=0011
