### ISSUE TITLE
JS error when using updateEvent or removeEvents on the event in eventDragStart

### ISSUE THREAD

**Issue by acerix** [fullcalendar/fullcalendar#3971]
This example gives an error when dragging an event:
https://codepen.io/anon/pen/qVGVba?editors=0010
> fullcalendar.js:10690 Uncaught TypeError: Cannot read property 'component' of null
>    at HitDragListener.hitOver (fullcalendar.js:10690)

Reported in https://fullcalendar.freshdesk.com/a/tickets/92

**Comment by vahanpetrosyan** [comment]
When I try drag it I receive error written below and event become to random position.

> Uncaught TypeError: Cannot read property '1' of null
        at ResourceTimelineView.queryHit (scheduler.js:3308)
        at e.queryHit (fullcalendar.min.js:6)
        at e.handleDragStart (fullcalendar.min.js:6)
        at e.t.startDrag (fullcalendar.min.js:8)
        at e.t.handleDistanceSurpassed (fullcalendar.min.js:8)
        at e.t.handleMove (fullcalendar.min.js:8)
        at e.t.handleMouseMove (fullcalendar.min.js:8)
        at t.d (vendor.js:5)
        at t.e (fullcalendar.min.js:6)
        at t.dispatch (vendor.js:6)


Code part

> eventDragStart: function(event, jsEvent, ui, view) {
                event.title = Math.random();
	        $('#calendar').fullCalendar('updateEvent', event);
}


* FullCalendar v3.8.0
* FullCalendar Scheduler v1.9.1

**Comment by gantaa** [comment]
+1 This is majorly blocking us in our Scheduling implementation

**Comment by ilizunov** [comment]
+1 blocks us as well

**Comment by hmzlam** [comment]
Fix this please

**Comment by arshaw** [comment]
very similar to https://github.com/fullcalendar/fullcalendar/issues/3978

**Comment by arshaw** [comment]
also similar to https://github.com/fullcalendar/fullcalendar/issues/3196

**Comment by arshaw** [comment]
anyone know if this is still the case in v4? a repro ?

**Comment by hmzlam** [comment]
please silent this error with a try catch

**Comment by hmzlam** [comment]
or test if object is null before accessing component

**Comment by arshaw** [comment]
probably fixed in v5

**Comment by hmzlam** [comment]
you should be sure of that we had hard times with this in the past ,for example changing description/color of event when dragging . we were using huge workarounds for this.
