### ISSUE TITLE
Additional Touch Support for External Dragging Events and Dragging Exsiting Events in Monbile Devices

### ISSUE THREAD

**Issue by danyfu** [fullcalendar/fullcalendar#3972]
Hello,
Is there a way to drag external events to the calendar using a mobile device like an iPad or a tablet. Because right now I can't drag nothing in any device. Here is a test using the device view in Chrome with the example [External Dragging](https://fullcalendar.io/js/fullcalendar-3.7.0/demos/external-dragging.html) of full calendar:

![screen recording 2017-12-06 at 12 39 34 pm](https://user-images.githubusercontent.com/9112457/33684295-a51b2196-da82-11e7-9fc5-6f73ef1eb500.gif)

Also I made the test with a real device using an iPad mini and I have the same behavior, all events are not dragabble, so what can I can do?.

Can I use an external drag library to drag the events like [hammer.js](http://hammerjs.github.io/) or [Dragabilly](https://draggabilly.desandro.com/)?, Because this libraries have more active support for touch devices like jqueryUI.

**Comment by acerix** [comment]
jQuery UI does not support the use of touch events, but you could try [Touch Punch](http://touchpunch.furf.com/).

There is an existing ticket for this to be documented:

https://github.com/fullcalendar/fullcalendar/issues/3849
