### ISSUE TITLE
Highlight .FC-Day-Number When Day Has Event 

### ISSUE THREAD

**Issue by mwilson85** [fullcalendar/fullcalendar#3973]
Hi There,

I was wondering if there is a way to add a class to an .fc-day-number box so I can add a style that highlights that day's number if it has an event?  Something like .day-has-event would be great.  Currently the day numbers don't have a specific class for it if it has an event that day.

Is there a way I could add it myself?  I looked in the plugin code and couldn't find where to do it.  Maybe a function could work.

Thanks!
Mitch

**Comment by acerix** [comment]
I believe this existing ticket captures this need:
https://github.com/fullcalendar/fullcalendar/issues/345
↑
Could you please visit the link, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates?

You could try something like this:
https://stackoverflow.com/a/31918055
