### ISSUE TITLE
Can't drag multiple resource events over other resources

### ISSUE THREAD

**Issue by mkerp** [fullcalendar/fullcalendar#3974]
### Bug Reports
I can't drag multiple resource event over other resources. It only drags one event to other resource but not other associated event.

One idea is to build one single wide box over resources for associated events to be able to drag and resize event over resources.

**Comment by acerix** [comment]
I'm not sure what the issue is, does it happen in one of the [demos](https://fullcalendar.io/scheduler/)?

Otherwise, would you be able to post a [runnable, stripped-down demonstration of the bug](http://fullcalendar.io/wiki/Reduced-Test-Cases/)? Would really appreciate it because the time saved reproducing will be time spent fixing.

**Comment by mkerp** [comment]
I uploaded one example based on vertical resource view demo and documentation example "Associating Events with Resources": https://codepen.io/anon/pen/XVrEYQ

If I drag one event to other (left/right) resource then others associated event doesn't move along.

**Comment by acerix** [comment]
Thanks for the demo, although I still don't understand the issue.

For example, if I drag the event from C to D, the `resourceIds` of the event changes from `a, b, c` to `a, b, d` as expected. Are you requesting that to work differently?

https://codepen.io/anon/pen/EoYzLE?editors=0010

**Comment by mkerp** [comment]
Thanks for the info. 
If it should be working that way, maybe is it possible to create one wide event box over resources (not 3 separate), which can be dragged over resources (left/right) entirely?

**Comment by acerix** [comment]
In that case, based on my previous example, do you mean that dragging from C to D would change the resources from `a, b, c` to `b, c, d`? ie. every resource moves to the right by 1

**Comment by mkerp** [comment]
That's right, if it is possible somehow. So it works like one wide booking.

**Comment by acerix** [comment]
I'm not sure this will be accepted as a new feature since it seems a bit obscure.

You might be better off to adjust the resources how you want them in the `eventDrop` callback.
