### ISSUE TITLE
eventLimit meaning is inconsistent

### ISSUE THREAD

**Issue by kkomu** [fullcalendar/fullcalendar#3977]
https://jsbin.com/vuyacuferi/edit?html,js,output

If I set 'eventLimit: 2' I would expect to always see one or two events and text '+x more' when there are more events. 
Now I see only one event and the text '+x more' unless there are exactly two events.  

Seems like text '+2 more' is count as one item in eventLimit.

**Comment by acerix** [comment]
I believe this existing ticket captures this need:
https://github.com/fullcalendar/fullcalendar/issues/3035
↑
Could you please visit the link, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates?
