### ISSUE TITLE
Month View Event not extend to next day if end is before 09:00:00

### ISSUE THREAD

**Issue by hsuanweifu** [fullcalendar/fullcalendar#3979]
Test Case: https://codepen.io/hsuanweifu/pen/NXPMXM

In this test case you can see that there are two events that differ by 1 second for end time. The event with end time 08:59:59 will extend over 2 days which I consider incorrect. While the event with end time 09:00:00 extends over 3 days.

```
    events: [{
      title: '8:59',
      allDay: false,
      start: '2010-01-01 10:00:00',
      end: '2010-01-03 08:59:59'
    },{
      title: '9:00',
      allDay: false,
      start: '2010-01-01 10:00:00',
      end: '2010-01-03 09:00:00'
    }]
```

**Comment by acerix** [comment]
This is based on the [nextDayThreshold](https://fullcalendar.io/docs/event_rendering/nextDayThreshold/) setting. By default, events don't extend if they end before 9am.

Does it work as you expect with that set to `00:00:00`?

https://codepen.io/anon/pen/opgQWJ

**Comment by hsuanweifu** [comment]
@acerix  Thanks for you help. Yes it works as expected when set to 00:00:00
