### ISSUE TITLE
[Feature request] Return Promise from callback in event source function

### ISSUE THREAD

**Issue by MattCz** [fullcalendar/fullcalendar#3980]
Hi, firstly, thank you for a great calendar!

Currently the Event Sources as function (https://fullcalendar.io/docs/event_data/events_function/) has a callback to which we can pass object with events data. It would be very useful if this function could return a JS Promise, so we could interact with calendar after are events are added.

I have a case where I need to fetch event by ID, using clientEvents method for this purpose. However calling it after callback results in event not being found. That's why returned promise, after events are added, would be better than "loading" function from docs.

Thank you.

**Comment by acerix** [comment]
Thanks for the suggestion.  I made a quick example to understand better:

https://codepen.io/anon/pen/aEOqpZ?editors=0010

Would it work in your case to match the event in `eventRender`? Or to match all events in `eventAfterAllRender`?

**Comment by MattCz** [comment]
I ended up with setTimeout at the very beginning but 'eventAfterAllRender' with a condition seems to be a best solution. Thank you
