### ISSUE TITLE
z-Index of event improvement proposal

### ISSUE THREAD

**Issue by jonasgroendahl** [fullcalendar/fullcalendar#3983]
Hello!

I've been trying to create a similiar behaviour for adding events in FullCalendar as in Google Calendar where one event gets highlighted through a backdrop on select like this:  [Imgur](https://i.imgur.com/T6p18dw.png)
There seems to be a problem with FullCalendar when changing the z-index of events - nothing happens. I have managed to get the whole calendar div in front of a backdrop but targetting one event at a time seems to be a pain. 

Maybe an idea.

**Comment by acerix** [comment]
Would you be able to post a [runnable, stripped-down demonstration of the code](http://fullcalendar.io/wiki/Reduced-Test-Cases/) and how you expect it to work?

I'm not sure how you are using z-index to replicate what is in the screenshot.
