### ISSUE TITLE
In v3.5.0+, if multiple events have the same ID, the first event's options affect the options of the other events

### ISSUE THREAD

**Issue by caseyjhol** [fullcalendar/fullcalendar#3989]
v3.4.0
https://codepen.io/caseyjhol/pen/QaEreG

v3.8.0
https://codepen.io/caseyjhol/pen/MrjKKw

In v3.5.0+, disabling `rendering: 'background'` for the first event causes all events to be displayed as normal, all-day events, even though only 2 events are all-day. Removing the allDay attribute doesn't resolve the issue either, as FullCalendar determines the event is all-day based on its start/end attributes, and passes along those options to other events.

**Comment by acerix** [comment]
According to the docs, the ID "uniquely identifies the given event. Different instances of repeating events should all have the same id.".

https://fullcalendar.io/docs/event_data/Event_Object/

My interpretation is that all instances of a repeating event should have the same properties.

Would it resolve your issue to use unique ID's when events have different properties, and relate them another way instead?

**Comment by caseyjhol** [comment]
I did read that, but the behavior is significantly different compared to previous versions. It makes sense that events with the same ID need the same properties, I just feel like the change should be documented somewhere, as it left me scratching my head for a bit. It's a bit jarring for events to just not show up. I ended up completely removing the event ID and I'm now just utilizing the event source ID, which works for my purposes.

**Comment by acerix** [comment]
I agree, such a change should be documented, and I'm not sure it was an intentional change, just that it seems to be working as expected according to the docs.

**Comment by Anatakun** [comment]
I think there's a problem there. In our case we're using recurring events on multiple ressources (tasks handled once per week by a team of 2 people). In that case, having the same id is very usefull to ask for the deletion of all the objects reffering to this one event, but then having multiple resources won't work as expected (the objects all happen to appear in the first resourceId provided, eventhough all other objects use other resourceIds).
I can work this around using ids being unique according to event_id AND resource_id, but it seems to me like a bad way to handle that kind of event... What do you think about that usage ?

**Comment by khenderick** [comment]
I have the same (similar?) issue where I have a single event that has a mixed schedule. For example, on monday the event spans from 16h till 17h, and on tuesday it's allday. However, since they share the same event id, the event is not showed in the allDay section on tuesday, but is stretched out over the 24h.

**Comment by arshaw** [comment]
I've adapted this for v5 and it seems to work well: https://codepen.io/arshaw/pen/OJMgrRe?editable=true&editors=001
