### ISSUE TITLE
Next Year

### ISSUE THREAD

**Issue by fibreiv** [fullcalendar/fullcalendar#3990]
It isn't rendering Jan 2018 events correctly on the calendar. They are all being shifted back 1 day. 
{title:'Financial: No Employee Available',start: '2017-1-01', allDay: true, backgroundColor: '#FF0000'},
This renders on Dec 31st.
{title:'Financial: Tina',start: '2017-1-02', allDay: true},
This renders on Jan 1st.

I have updated to the newest version of the calendar as well with the same issue. Also confirmed it by replacing the events on the default.html in the demo folder with the same result.

Thanks,
Brett

### Bug Reports
You MUST have a JSBin recreation, or else your issue will be CLOSED without explanation.
Instructions: http://fullcalendar.io/wiki/Reporting-Bugs/

### Feature Requests
Search the issue tracker for an existing ticket before creating a new one.
Instructions: http://fullcalendar.io/wiki/Requesting-Features/

(Please erase the above text and begin typing. Thanks!)

**Comment by acerix** [comment]
Would you be able to post a [runnable, stripped-down demonstration of the bug](http://fullcalendar.io/wiki/Reduced-Test-Cases/)? Would really appreciate it because the time saved reproducing will be time spent fixing.

I tried changing the dates in the template to January, but it looks fine to me:

https://codepen.io/anon/pen/ypamjY?editors=0010

**Comment by fibreiv** [comment]
Just getting back to this issue and it's still happening.  I updated the js and css to the 3.9 but same issue.
Here is the data and then a screenshot of how it renders on the page.

Thanks!
Brett

`
		$('#calendar').fullCalendar({
			header: {
				left: 'prev,next',
				center: 'title',
				right: 'month,basicWeek,listMonth'
			},
			//defaultDate: '01/01/2018',
			//3/01/2018
			defaultDate: '2018/3/01',
			defaultView: 'month',
			navLinks: false, // can click day/week names to navigate views
			editable: false,
			weekends: false,
			eventTextColor: '#fff',
			eventLimit: false, // allow "more" link when too many events
			nowIndicator: false,
			events: [
{title:'Financial: Tina',start: '2018-3-01', allDay: true},
{title:'Deposit: Maryann',start: '2018-3-01', allDay: true},
{title:'Counter: Susan',start: '2018-3-01', allDay: true},
{title:'Mail: Jennie',start: '2018-3-01', allDay: true},
{title:'Financial: Tina',start: '2018-3-02', allDay: true},
{title:'Counter: Jennie',start: '2018-3-02', allDay: true},
{title:'Mail: Maryann',start: '2018-3-02', allDay: true},
{title:'Financial: Tina',start: '2018-3-05', allDay: true},
{title:'Counter: Lori',start: '2018-3-05', allDay: true},
{title:'Mail: Susan',start: '2018-3-05', allDay: true},
{title:'Financial: Tina',start: '2018-3-06', allDay: true},
{title:'Counter: Maryann',start: '2018-3-06', allDay: true},
{title:'Mail: Lori',start: '2018-3-06', allDay: true},
{title:'Financial: Tina',start: '2018-3-07', allDay: true},
{title:'Counter: Susan',start: '2018-3-07', allDay: true},
{title:'Mail: Jennie',start: '2018-3-07', allDay: true},
{title:'Financial: Tina',start: '2018-3-08', allDay: true},
{title:'Deposit: Maryann',start: '2018-3-08', allDay: true},
{title:'Counter: Colleen',start: '2018-3-08', allDay: true},
{title:'Mail: Michael',start: '2018-3-08', allDay: true},
{title:'Financial: Tina',start: '2018-3-09', allDay: true},
{title:'Counter: Michael',start: '2018-3-09', allDay: true},
{title:'Mail: Colleen',start: '2018-3-09', allDay: true},
{title:'Financial: Tina',start: '2018-3-12', allDay: true},
{title:'Counter: Jennie',start: '2018-3-12', allDay: true},
{title:'Mail: Susan',start: '2018-3-12', allDay: true},
{title:'Financial: Tina',start: '2018-3-13', allDay: true},
{title:'Counter: Maryann',start: '2018-3-13', allDay: true},
{title:'Mail: Lori',start: '2018-3-13', allDay: true},
{title:'Financial: Tina',start: '2018-3-14', allDay: true},
{title:'Counter: Lori',start: '2018-3-14', allDay: true},
{title:'Mail: Maryann',start: '2018-3-14', allDay: true},
{title:'Financial: Tina',start: '2018-3-15', allDay: true},
{title:'Deposit: Maryann',start: '2018-3-15', allDay: true},
{title:'Counter: Colleen',start: '2018-3-15', allDay: true},
{title:'Mail: Michael',start: '2018-3-15', allDay: true},
{title:'Financial: Tina',start: '2018-3-16', allDay: true},
{title:'Counter: Michael',start: '2018-3-16', allDay: true},
{title:'Mail: Colleen',start: '2018-3-16', allDay: true},
{title:'Financial: Tina',start: '2018-3-19', allDay: true},
{title:'Counter: Susan',start: '2018-3-19', allDay: true},
{title:'Mail: Jennie',start: '2018-3-19', allDay: true},
{title:'Financial: Tina',start: '2018-3-20', allDay: true},
{title:'Counter: Maryann',start: '2018-3-20', allDay: true},
{title:'Mail: Susan',start: '2018-3-20', allDay: true},
{title:'Financial: Tina',start: '2018-3-21', allDay: true},
{title:'Counter: Jennie',start: '2018-3-21', allDay: true},
{title:'Mail: Maryann',start: '2018-3-21', allDay: true},
{title:'Financial: Tina',start: '2018-3-22', allDay: true},
{title:'Deposit: Maryann',start: '2018-3-22', allDay: true},
{title:'Counter: Lori',start: '2018-3-22', allDay: true},
{title:'Mail: Colleen',start: '2018-3-22', allDay: true},
{title:'Financial: Tina',start: '2018-3-23', allDay: true},
{title:'Counter: Colleen',start: '2018-3-23', allDay: true},
{title:'Mail: Michael',start: '2018-3-23', allDay: true},
{title:'Financial: Tina',start: '2018-3-26', allDay: true},
{title:'Counter: Michael',start: '2018-3-26', allDay: true},
{title:'Mail: Lori',start: '2018-3-26', allDay: true},
{title:'Financial: Tina',start: '2018-3-27', allDay: true},
{title:'Counter: Susan',start: '2018-3-27', allDay: true},
{title:'Mail: Maryann',start: '2018-3-27', allDay: true},
{title:'Financial: Tina',start: '2018-3-28', allDay: true},
{title:'Counter: Jennie',start: '2018-3-28', allDay: true},
{title:'Mail: Susan',start: '2018-3-28', allDay: true},
{title:'Financial: Tina',start: '2018-3-29', allDay: true},
{title:'Deposit: Maryann',start: '2018-3-29', allDay: true},
{title:'Counter: Lori',start: '2018-3-29', allDay: true},
{title:'Mail: Jennie',start: '2018-3-29', allDay: true},
{title:'Financial: Tina',start: '2018-3-30', allDay: true},
{title:'Counter: Maryann',start: '2018-3-30', allDay: true},
{title:'Mail: Colleen',start: '2018-3-30', allDay: true},`

![scheduler](https://user-images.githubusercontent.com/29683648/37176582-6547cad0-22e2-11e8-89d7-ae1a2dc776e7.PNG)
