### ISSUE TITLE
error in fullcalendar.d.ts & scheduler.d.ts

### ISSUE THREAD

**Issue by LordJoStar** [fullcalendar/fullcalendar#3991]
### Bug Reports

Error in fullcalendar.d.ts & scheduler.d.ts npm files. I deleted "node_modules" and reinstalled it. Same issue

I built a new Angular 5 project and installed fullcalendar & fullcalendar-scheduler. When compiling I get the following errors:

```
ERROR in node_modules/fullcalendar-scheduler/dist/scheduler.d.ts(760,44): error TS2304: Cannot find name 'JQueryPromise'.
node_modules/fullcalendar-scheduler/dist/scheduler.d.ts(795,66): error TS2304: Cannot find name 'JQueryAjaxSettings'.
node_modules/fullcalendar/dist/fullcalendar.d.ts(695,36): error TS2304: Cannot find name 'JQueryPromise'.
node_modules/fullcalendar/dist/fullcalendar.d.ts(696,29): error TS2304: Cannot find name 'JQueryPromise'.
node_modules/fullcalendar/dist/fullcalendar.d.ts(697,20): error TS2304: Cannot find name 'JQueryPromise'.
node_modules/fullcalendar/dist/fullcalendar.d.ts(759,22): error TS2304: Cannot find name 'JQueryPromise'.
node_modules/fullcalendar/dist/fullcalendar.d.ts(775,50): error TS2304: Cannot find name 'JQueryPromise'.
node_modules/fullcalendar/dist/fullcalendar.d.ts(988,23): error TS2304: Cannot find name 'JQueryEventObject'.
node_modules/fullcalendar/dist/fullcalendar.d.ts(1401,70): error TS2304: Cannot find name 'JQueryAjaxSettings'.
node_modules/fullcalendar/dist/fullcalendar.d.ts(1603,50): error TS2304: Cannot find name 'JQueryPromise'.
node_modules/fullcalendar/dist/fullcalendar.d.ts(1623,50): error TS2304: Cannot find name 'JQueryPromise'.
node_modules/fullcalendar/dist/fullcalendar.d.ts(2588,50): error TS2304: Cannot find name 'JQueryPromise'.
```
I found the following errors in the "fullcalendar.d.ts" & "scheduler.d.ts" file, :

JQueryPromise
JQueryEventObject
JQueryAjaxSettings

When I went to the node_modules/fullcalendar/dist/fullcalendar.d.ts, I opened the file, and found that VS Code is reporting "[ts] Cannot find name 'JQueryPromise'." Same for the others. 

A quick-fix was to change the type to  'any' but I felt it prudent to open an issue for them. 

I've attached the files as evidence. Thanks! Happy Holidays!

[problem-childs.zip](https://github.com/fullcalendar/fullcalendar/files/1584612/problem-childs.zip)

**Comment by acerix** [comment]
Thanks for the report, but I didn't come across this error when following the [compilation instructions](https://github.com/fullcalendar/fullcalendar/blob/master/CONTRIBUTING.md#getting-set-up).

Is it maybe an issue with the Angular wrapper you are using, or specifically with VS Code? Is there something that could be changed (besides compiled files in /dist/) to improve compatibility?

**Comment by LordJoStar** [comment]
Hi acerix, 

I posted a question on StackOverflow as well, https://stackoverflow.com/questions/47950588/fullcalendar-angular-5, which outlines the steps that I took to reproduce the error. I've included my package.json file as reference. Could it be related to the fact that I'm running @angular/cli 1.6.2? I get similar errors with firebase 4.8.1

[package.json.zip](https://github.com/fullcalendar/fullcalendar/files/1593922/package.json.zip)

I'll revisit this following the compilation instructions.

**Comment by dgsqrs** [comment]
I have the same problem

**Comment by DaceloNovaeguineae** [comment]
I've just installed `npm install --save-dev @types/jquery@3.2.7` and it's works.
package.json:
"fullcalendar": "^3.8.0",
"jquery": "^3.2.1",
"@types/jquery": "^3.2.7",

**Comment by LordJoStar** [comment]
Thank DaceloNovaeguineae

The error was being caused due to the absence of the jquery typings file. Installing @types/jquery fixed the problem.

**Comment by arshaw** [comment]
thanks for the solutions everyone.

i will reopen this ticket to remind me to update the docs in regards to this

**Comment by arshaw** [comment]
this is now accounted for in the docs: https://fullcalendar.io/docs/typescript/

**Comment by subbumsd** [comment]
Hey,

I had @types/jquery in my package.json already. But still getting the same error.

**Comment by subbumsd** [comment]
`@types/jquery`

**Comment by menthollisa** [comment]
ERROR in node_modules/fullcalendar/dist/fullcalendar.d.ts(695,36): error TS2304: Cannot find name 'JQueryPromise'.
node_modules/fullcalendar/dist/fullcalendar.d.ts(696,29): error TS2304: Cannot find name 'JQueryPromise'.
node_modules/fullcalendar/dist/fullcalendar.d.ts(697,20): error TS2304: Cannot find name 'JQueryPromise'.
node_modules/fullcalendar/dist/fullcalendar.d.ts(759,22): error TS2304: Cannot find name 'JQueryPromise'.
node_modules/fullcalendar/dist/fullcalendar.d.ts(775,50): error TS2304: Cannot find name 'JQueryPromise'.
node_modules/fullcalendar/dist/fullcalendar.d.ts(988,23): error TS2304: Cannot find name 'JQueryEventObject'.
node_modules/fullcalendar/dist/fullcalendar.d.ts(1401,70): error TS2304: Cannot find name 'JQueryAjaxSettings'.
node_modules/fullcalendar/dist/fullcalendar.d.ts(1608,50): error TS2304: Cannot find name 'JQueryPromise'.
node_modules/fullcalendar/dist/fullcalendar.d.ts(1628,50): error TS2304: Cannot find name 'JQueryPromise'.
node_modules/fullcalendar/dist/fullcalendar.d.ts(2614,50): error TS2304: Cannot find name 'JQueryPromise'.
src/app/containers/warehouse/houses/shippings/export/export.component.ts(4,10): error TS2305: Module ''fullcalendar'' has no exported member 'Options'.
src/app/containers/warehouse/houses/shippings/import/import.component.ts(4,10): error TS2305: Module ''fullcalendar'' has no exported member 'Options'.


I still have the problem after install @jquery

**Comment by satoshionoda** [comment]
@subbumsd @menthollisa 

Same happened on me.

If you are using fullcalendar with Angular.
Adding `import * as $ from 'jquery';` at AppModule solved the problem.

https://github.com/lbertenasco/ap-ng2-fullcalendar#usage

**Comment by benwinding** [comment]
In Angular, I had to include `import * as $ from 'jquery';` at the top of my `test.ts` file for karma tests to work
