### ISSUE TITLE
eventRender not triggering during resizing when coming back to original end time.

### ISSUE THREAD

**Issue by migburillo** [fullcalendar/fullcalendar#4002]
Hello,

I'm facing the following issue:  while resizing an event with mouse dragging in agenda view the eventRender callback is not triggering when each time you come back to original end time.

Affected versions: > 3.5.0

Steps to reproduce:
- resize an event increasing end time (eventRender is triggered)
- without releasing the mouse button, come back to original time (eventRender is not triggered)
- continue resizing decreasing original end time (eventRender is triggered again)

https://codepen.io/anon/pen/Lezdve

Thanks!

**Comment by acerix** [comment]
Thanks for the details report, `eventRender` should fire when returning to original size during resize.

**Comment by jan18calendars** [comment]
I having same issue for **[january 2018 calendar](https://freshcalendars.com/january-2018-calendar)**

<p>
https://freshcalendars.com/
</p>

**Comment by arshaw** [comment]
this is almost definitely a non-issue in v5 (using `eventContent` hook instead)
