### ISSUE TITLE
How to Customize Time Grid Column?

### ISSUE THREAD

**Issue by KevangPatel** [fullcalendar/fullcalendar#4003]
I need To style Hourly Time like 9:00 AM, 10:00 AM etc to bold and rest time like 9:15, 9:30 should look normal in time column..how can i do such thing ....?
I tried to override its css class but result was that it changed all time to bold....
I tried doing following thing
e.g:-  .fc-time-grid .fc-slats td {
                            font-weight: bold;
}

**Comment by acerix** [comment]
I believe this existing ticket captures this need:
https://github.com/fullcalendar/fullcalendar/issues/3164
↑
Could you please visit the link, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates?

If it's always the same row numbers that you want to style (eg. every fourth row), you could do that in CSS:

https://codepen.io/anon/pen/Wddmpz?editors=0110

**Comment by KevangPatel** [comment]
@acerix thanks alot ...!!!!
it worked for me ....
