### ISSUE TITLE
Issue of popup on emptyEvent click & eventclick 

### ISSUE THREAD

**Issue by vishalgupta153** [fullcalendar/fullcalendar#4005]
When i click on empty cell(select) & onevent(eventClick) of the full calendar, popover gets opened but it doesn't display event list data  which i call from api and when i click second time it display data but for static data popover works fine on first click.......
i want to display dynamic data from the very first click.....
This is the code i have done on Select event of full calendar:
      select: function(start, end, jsEvent, view, id) {        // this is for empty cell click event
                var dateEvent = moment($scope.setDate).format("YYYY-MM-DD");

                CalendarData.emptyEventClicks(dateEvent, id.id)
                    .success(function(data) {
                        $scope.popups = data.data;
                        if ($scope.popups.length > 0) {
                            $('#popover2').popover('destroy');
                            closePopovers();

                            popoverElement = $(jsEvent.target);
                            $(jsEvent.target).popover({
                                title: 'Select Action',
                                content: function() {
                                    return $("#popover").html();
                                },
                                template: popTemplate,
                                placement: 'top',
                                html: 'true',
                                trigger: 'click',
                                animation: 'true',
                                container: 'body'
                            }).popover('show');
                        }
                    })
                    .error(function(error) {
                        console.log(error);
                    });

            },
     eventClick: function(event, jsEvent, view) {         // this is for onevent click
                CalendarData.onEventClick()
                    .success(function(data) {
                        $scope.clickPopups = data.data;
                        if ($scope.clickPopups.length > 0) {
                            $('#popover').popover('destroy');
                            closePopovers();
                            popoverElement = $(jsEvent.target);
                            $(jsEvent.target).popover({
                                title: 'Select Action',
                                content: function() {
                                    return $("#popover2").html();
                                },
                                template: popTemplate,
                                placement: 'top',
                                html: 'true',
                                trigger: 'click',
                                animation: 'true',
                                container: 'body'
                            }).popover('show');
                            
                        }
                    })
                    .error(function(error) {
                        console.log(error);
                    });
            },

------------------------------------------------------
This is the reference of the code from where i have used popover:
http://jsfiddle.net/slyvain/6vmjt9rb/

**Comment by acerix** [comment]
Thanks for the report.

In that jsfiddle, `popover('show')` isn't working in the `select` callback because the popover isn't created yet, I got it working with `setTimeout`:

http://jsfiddle.net/wu3obvn3/

Are you looking for a new callback eg. `selectRender` that would fire after rendering the selection? ie. You would call `popover('show')` there instead.

**Comment by vishalgupta153** [comment]
Thanks for helping Acerix 
========================
 setTimeout(function(){
        	popoverElement.popover('show');
        }, 0);
========================
setTimeout() worked for me...
