### ISSUE TITLE
JS Error : Uncaught TypeError: Cannot read property 'datepickerLocale' of undefined

### ISSUE THREAD

**Issue by Moranbzh** [fullcalendar/fullcalendar#4008]
Hi,

I have a Javascript error in the browser console with fullcalendar-3.8.0 and fullcalendar-scheduler-1.9.1 : 

> Uncaught TypeError: Cannot read property 'datepickerLocale' of undefined

![error_fullcalendar](https://user-images.githubusercontent.com/25210066/34786292-077d4086-f634-11e7-875b-268acaa7a91a.png)

I have installed fullcalendar and fullcalendar-scheduler in the drupal libraries folder. I have created a simple JS file with the following code : 

`jQuery(document).ready(function($) {

	$('#calendar').fullCalendar({
		schedulerLicenseKey : 'GPL-My-Project-Is-Open-Source',
		editable : true,
		scrollTime : '00:00',
		defaultDate : '2018-01-02',
		defaultView : 'timelineDay',
		resourceLabelText : 'Rooms',
		resources : [ {
			id : 'R1',
			title : 'Room 1'
		} ],
		events : [ {
			id : '1',
			resourceId : 'R1',
			start : '2018-01-02T02:00:00',
			end : '2018-01-02T07:00:00',
			title : 'First event'
		} ]
	});
});`

It looks like the calendar is not displayed very well too... According to the JS console, the error is located in the locate-all.js file. I tried to configure a locale (like `lang:'fr'` or `locale:'fr'`) in the fullcalendar definition but it doesn't changed anything. I am not able to find which object in the locale-all.js file is undefined. Is it a problem of configuration of fullcalendar (missing property for example) ?

Thank you.

**Comment by acerix** [comment]
Would you be able to post a [runnable, stripped-down demonstration of the bug](http://fullcalendar.io/wiki/Reduced-Test-Cases/)? Would really appreciate it because the time saved reproducing will be time spent fixing.

I put your code in the debugging template and didn't get any error:

https://codepen.io/anon/pen/dJmezv?editors=0010

**Comment by Moranbzh** [comment]
I don't understand... in your example you don't import locale-all.js file. Why this file is included in the fullcalendar-3.8.0.zip archive to put in the library folder of drupal if there is no need to use it to make the code running ??

**Comment by acerix** [comment]
locale-all.js is only needed for internationalization, like in this example:

https://fullcalendar.io/js/fullcalendar-3.8.0/demos/locales.html

**Comment by ridha2019** [comment]
U have to put in order :
1. moment.js
2. fullcalendar.js
3. ur_lang.js
