### ISSUE TITLE
Events & resources not showing when fast clicking next/previous on vertical resource view with asynchronous ajax calls

### ISSUE THREAD

**Issue by Cris200992** [fullcalendar/fullcalendar#4009]
Hello, 

I am working on developing application for a project for one of my subjects at  university with  using MVC 5 + FullCalendar 3.6.2 + Scheduler 1.8.1 

![tosook](https://user-images.githubusercontent.com/35325847/34814271-4f16f77e-f6ad-11e7-8289-59e367b6ab12.JPG)

To do so I use asynchronous ajax calls to ASP.NET using SQL Server database to feed the event & resource data from my database that are called each time a new view is shown(e.g. when next/previous button is clicked). 

The issue has arised when fast clicking in either both of next/previous buttons when a vertical resource view of 1 day is being shown. It happens in Chrome/Firefox/IE. 

![cascado](https://user-images.githubusercontent.com/35325847/34814377-ad7230f4-f6ad-11e7-918c-d3c2ed247ad8.JPG)

It just stops showing the events and updating resources and the following js error pops in the console: 

`TypeError: this.contentSkeletonEl is null`

Therefore the resources are not updated and the event data isn't either.  After that, when switching to agendaWeek view and back to day view again it just dissapears.

![masroto](https://user-images.githubusercontent.com/35325847/34814385-b1b14100-f6ad-11e7-9211-cf265b220166.JPG)

The ajax calls are still being made and the data is arriving to the view, but it's just not being shown by the calendar.

Sorry, couldn't make a running example but I provide a codepen with my calendar declaration: https://codepen.io/anon/pen/ypKdxj?editors=0010. 

The issue may look similar to #3920?

**Comment by acerix** [comment]
Thanks for the report.

That error message indicates unrenderContentSkeleton() is being called when there is no skeleton:

https://github.com/fullcalendar/fullcalendar/blob/5af235874b3fd95b57ec9f632e2e8b9e8c26f6c3/src/agenda/TimeGrid.ts#L357

I get a similar error using `refetchResourcesOnNavigate` in the debugging template by clicking "<" button a few times quickly:

https://codepen.io/anon/pen/gozzOg?editors=0010

`fullcalendar.js:11867 Uncaught TypeError: Cannot read property 'remove' of null`

**Comment by arshaw** [comment]
here's a simplified codepen derived from acerix's:
https://codepen.io/anon/pen/ddbXNV?editors=0010

with acerix's and my recreations, it's a different JS error than @Cris200992, however, the effects are nearly the same, including a blank week view when switching to week view, so i'm betting it's the same bug.

**Comment by arshaw** [comment]
queued for release
https://github.com/fullcalendar/fullcalendar/commit/bd5deb0f370f036967f160845a9e2f53f5656a1d
https://github.com/fullcalendar/fullcalendar-scheduler/commit/84a628fc51be455de63cef0d9dfb95434b4c086a

**Comment by arshaw** [comment]
fixed in core 3.8.1 / scheduler 1.9.2 (just released)

working codepen: https://codepen.io/arshaw/pen/QQLXBX?editors=0010
