### ISSUE TITLE
how to show timeGridDay with rowspan dynamically

### ISSUE THREAD

**Issue by vishalgupta153** [fullcalendar/fullcalendar#4012]
i cant get any css that change the specific column header with title when event loader ....

![34869787-12218418-f7ae-11e7-99de-dcaa98c53fe6](https://user-images.githubusercontent.com/34914716/34874497-2a72469a-f7bf-11e7-8b67-40b069b03d93.PNG)
 
this mine

Here is angularjs code

function initCalendar(myresources) {
$('#day-calendar').fullCalendar({
defaultView: 'agendaDay',
// defaultDate: '2017-12-28',
defaultDate: $scope.setDate,
aspectRatio: 1.8,
editable: true,
selectable: true,
eventLimit: true,
slotEventOverlap: true,
minTime: $scope.lessonStartTime,
maxTime: $scope.lessonEndTime,
contentHeight: 'auto',
slotLabelInterval: $scope.lessonTimeInterval,
slotLabelFormat: "HH:mm:A",
header: {
left: '',
center: 'Time',
right: ''
},
views: {
agendaDay: {
groupByDateAndResource: true,
}
},
selectable: true,
selectHelper: true,
resourceLabelText: "Venue",
allDaySlot: false,
resources: myresources,
events: eventsData,
eventAfterRender: function(event, element, view) {
$(element).css('width', '200px');
},

![34869806-22ba3ea0-f7ae-11e7-950f-c30a1c75f42f](https://user-images.githubusercontent.com/34914716/34874528-46677050-f7bf-11e7-87c2-06e591312aa4.PNG)

this what i want

i want with resource header and event width both are same
is it done by dynamicaly ?
if staticly that can be done then what way should i do that?

**Comment by vishalgupta153** [comment]
Are you looking to have the columns resize automatically, based on the width of the events?
-->
yes 

can you explain me how to set width option of resourceColumns
because i set in my code but i didn't get any result so please help me in resourceColumns  ??

in your same example debugging template..

**Comment by acerix** [comment]
The `resourceColumns` option applies to the `timelineDay` view, quick example:

https://codepen.io/anon/pen/eyPBLa?editors=0010

I don't believe that option helps you, just that you are looking for something similar in `agendaDay` view.

**Comment by GalacticWeb** [comment]
It would be awesome if we could change the column width in the **agendaDay** as well!

**Comment by arshaw** [comment]
this other ticket captures a more general description of this feature request:
https://github.com/fullcalendar/fullcalendar/issues/2591
&uarr;
Could you please visit the link, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates?
