### ISSUE TITLE
Fullcalendar event(s) loading indication for end users

### ISSUE THREAD

**Issue by Sarath-Raja** [fullcalendar/fullcalendar#4020]
### Feature Requests ###
Greetings,
                  Whenever fullcalendar events are getting loaded and UI is getting updated, it will be helpful if there is an loading image indicating that the process is going on  and also the user will know that he/she has to wait for the events to get completed.

Thanks.

**Comment by acerix** [comment]
There is a [loading](https://fullcalendar.io/docs/event_data/loading/) callback that makes it easy to toggle your own indicator.

I agree having some indicator by default would be useful though, so the user knows to wait if the server response is slow:

https://codepen.io/anon/pen/YYdBjK?editors=0010

**Comment by livingBEEF** [comment]
Somewhat related: as far as I'm aware, there is no (clean) way to tell whether the request was successful or not. If there was a network error, the indicator could show that too. Or at least `loading` should be called with status of the request.

I can think about some workarounds, but none seem very good.

**Comment by bgallagh3r** [comment]
> Somewhat related: as far as I'm aware, there is no (clean) way to tell whether the request was successful or not. If there was a network error, the indicator could show that too. Or at least `loading` should be called with status of the request.
> 
> I can think about some workarounds, but none seem very good.

If you use AJAX to fetch events, you can use the *error* ajax callback to tell the user there was an issue via an alert or notification.

```
events: {
    url: '/myfeed.php',
    type: 'POST',
    error: function() {
      alert('there was an error while fetching events!');
}
```

Provided you send the right headers back you should be able to check if there is an error that way.

**Comment by arshaw** [comment]
yup, use the `error` function for each event source, or use the general `eventSourceError`
