### ISSUE TITLE
view like a pollen calendar

### ISSUE THREAD

**Issue by marcelglaeser** [fullcalendar/fullcalendar#4022]
Hi at all,

i need a view like a pollen calendar. Please whats this graphic:
[http://www.allergie-geneve.com/wp-content/uploads/2012/04/calendrier-pollens-en1.jpg](http://www.allergie-geneve.com/wp-content/uploads/2012/04/calendrier-pollens-en1.jpg )

It is possible?

Thanks for your help!

Marcel

**Comment by acerix** [comment]
Looks like the `timeline` view of the Scheduler addon could work, as in this example:

https://codepen.io/anon/pen/NXJeEo?editors=0010

There's no a similar view in plain FullCalendar, but there are some open requests for adding year-long views which might work, or you could request it as a new feature.   

https://github.com/fullcalendar/fullcalendar/issues/3963
