### ISSUE TITLE
Event EndTime is not shown in Calendar for small Durations

### ISSUE THREAD

**Issue by Bisdow** [fullcalendar/fullcalendar#4024]
Hi,

for small durations the endTime of an event is not shown, even when "displayEventEnd" is true
Instead of "01:00 - 01:15" it shows only "01:00  - "

See the JSBin
[My JSBin](http://jsbin.com/turoyiq/2/edit?js,output)

In my JSBin the effect appears when the duration is shorter than 42 minutes.
In my real application it appears beginning with 47 minutes...

I checked the effect with Chrome (63.0), IE (11.096...) and Firefox (58.0).
But I did not check if it is a localisation thing.
I tried it with de-de and UTC+1

As a workaround i could overwrite the css with
```
.fc-time-grid-event.fc-short .fc-time span {
    display: inline;
}

.fc-time-grid-event.fc-short .fc-time:before {
    content: normal;
}  

.fc-time-grid-event.fc-short .fc-time:after {
    content: normal;
}
```

By the way, thank you for this great calendar :-)

Warm regards
Bisdow

**Comment by acerix** [comment]
Thanks for the detailed report and workaround.

**Comment by jamesdixon** [comment]
@Bisdow thanks for the workaround!

**Comment by arshaw** [comment]
FYI, this issue a dup of this one:
https://github.com/fullcalendar/fullcalendar/issues/3049
&uarr;
Could you please visit the link, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates?
