### ISSUE TITLE
Different start times for Month and Week view

### ISSUE THREAD

**Issue by imilo** [fullcalendar/fullcalendar#4027]
I use both **Month** and **Week** views to create events and have noticed an issue with a **Start** time.

Here is a JSFiddle example: https://jsfiddle.net/vitrute/ojgbp11z/1/

In a **Month** view click any day and an alert will show current day + timezone hours. In my case: `Thu Jan 25 2018 02:00:00 GMT+0200 (EET)`

In a **Week** view click any day's **0:00** section and an alert will show current day + normal **00:00** hours. In my case: `Thu Jan 25 2018 00:00:00 GMT+0200 (EET)`

You see the 2 hours difference. It's correct for the **Week** view, but how do I avoid these wrong additional **02:00** hours in a **Month** view? My timezone is **+2**.

**Comment by acerix** [comment]
In Week view, `start`/`end` are dates including the time, when a timeslot is clicked.  If an All Day slot is clicked, or a day in Month view is clicked, `start`/`end` are just dates without the time, eg:

https://jsfiddle.net/ojgbp11z/2/

When you format with `moment.toDate()`, the dates are assumed to be midnight UTC (+0), which is 02:00 your time. This demo converts them to midnight local time first:

https://jsfiddle.net/ojgbp11z/3/
