### ISSUE TITLE
Make header title element targetable

### ISSUE THREAD

**Issue by mpassaglia** [fullcalendar/fullcalendar#4028]
I'd like to be able to create click events on the calendar's header title so that we can provide the user with a "Jump to (month/year)..." functionality. 

In its current state, we are able to target the header loosely based on the right/left placement of the h2 element holding the title text, e.g.:
`$('.fc-toolbar .fc-left h2')`
This builds a dependency on the current placement of the title, which if changed would require rewriting whatever hook is attached to the element. 

I propose adding a class or id to the header text element so that it can be easily targeted regardless of alignment, e.g.:
`<div class="fc-left">`
`    <h2 class="fc-date-title">January 2018</h2>`
`</div>`

**Comment by acerix** [comment]
Thanks for the suggestion, agree it would be good to have a class to target the title.  

`$('.fc-toolbar > div > h2')` should work for now, since there are no other h2's in there.

**Comment by arshaw** [comment]
v5 now has `.fc-toolbar-title` for this
