### ISSUE TITLE
Bootstrap 4 Theme

### ISSUE THREAD

**Issue by m-andreas** [fullcalendar/fullcalendar#4032]
The title is quite self explanatory.
As Bootstrap 4 is out of beta phase, a theme for it would be great!

**Comment by arshaw** [comment]
I agree! Right now only Bootstrap 3 is supported

**Comment by mamadoo** [comment]
@arshaw When will Bootstrap 4 be supported?
I need fullcalendar with bootstrap 4.
Can you help me to do it?

**Comment by alexmandt** [comment]
I would need that, too.

**Comment by GeekJosh** [comment]
I have created a PR for this #4065

**Comment by arshaw** [comment]
queued for release

**Comment by arshaw** [comment]
released in [v3.9.0](https://github.com/fullcalendar/fullcalendar/releases/tag/v3.9.0) !
https://fullcalendar.io/docs/theming

**Comment by arshaw** [comment]
blog post: https://fullcalendar.io/blog/2018/03/bootstrap-4-support/
