### ISSUE TITLE
titleFormat is formatted incorrect

### ISSUE THREAD

**Issue by andrzejpindor** [fullcalendar/fullcalendar#4038]
Problem is with Polish (and I think other than English) locale. When you provide date format "LL" subjective month names should be used. Instead of this nominative names are used.

I created jsfiddle with reproduction steps:
https://jsfiddle.net/152jL2cz/1/

Problem is in function chunkFormatString (and other correlated), because in Polish locale (and other as I think) if you use momentjs like this:
`moment('2018-01-30').format('MMMM')`
 you will get **"styczeń"** which is ok when there is no day part included
But when you use format with day part:
`moment('2018-01-30').format('DD MMMM')`
you will get **"30 stycznia"**

With fullcalendar using format "LL" (which is translated to "DD MMMM YYYY") you will get **"30 styczeń 2018"** which is incorrect. It should be **"30 stycznia 2018"**.

Because you are splitting date format to a chunks and getting each part of date separately, final date display format is incorrect.

**Comment by acerix** [comment]
Thanks for the detailed report.

**Comment by tenetdavazin** [comment]
We are experiencing the same problem on our web site. How can we solve it?
<p>
https://freshcalendars.com/
</p>

**Comment by acerix** [comment]
For now, you could replace the title with the correct version like this, eg:

https://jsfiddle.net/152jL2cz/2/

**Comment by kohatang** [comment]
When used with `validRange`, That resolve is seems not works.

https://jsfiddle.net/v3q0r8n6/1/

**Comment by arshaw** [comment]
i believe this should now be a non-issue, as v4/v5 no longer rely on moment but instead use the Intl API
