### ISSUE TITLE
OptionsInput type is not exported and some of jquery hooks definitions are incorrect

### ISSUE THREAD

**Issue by bendykowski** [fullcalendar/fullcalendar#4041]
`OptionsInput` type is not exported from the main module. Exposing it will ease typing fullcalendar options building externally.
Also a few jquery hooks are typed incorrectly because some optional parameters are typed as required.

Made a PR to fix that: #4040

**Comment by acerix** [comment]
Duplicate of https://github.com/fullcalendar/fullcalendar/issues/4006
