### ISSUE TITLE
eventResize / scheduler delta is undefined when resize from begining ( left ) of event

### ISSUE THREAD

**Issue by pgiani** [fullcalendar/fullcalendar#4042]
The **delta** on **eventResize** is undefine when you drag the event from the start/begining/left side of the event 

Here is a code to verify the bug, open console to see the value of delta at the end of the resize
https://codepen.io/JustinRLeonard/pen/Jpdqqw?editors=1111
 
Here is a video of the error when resized is done to the start of the event .
http://take.ms/Xcaak

Documentation for the eventResize
https://fullcalendar.io/docs/event_ui/eventResize/

Thank You

**Comment by acerix** [comment]
Thanks for the detailed report.

I'll move this issue to the scheduler repo since events can only be resized from the beginning in timeline view.

**Comment by acerix** [comment]
https://github.com/fullcalendar/fullcalendar-scheduler/issues/416
↑
Please visit the link, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates
