### ISSUE TITLE
end time not showing when event duration > slotDuration

### ISSUE THREAD

**Issue by jamesdixon** [fullcalendar/fullcalendar#4052]
Hi,

The end time of the appointment doesn't show up on events where the duration of the event is greater than the `slotDuration`. 

See the following pen and look at the 10:30am event:

https://codepen.io/anon/pen/zRBaqY

If I adjust the slot duration to 10 minutes and the event duration is 15 minutes, the end time will show. If the slot duration is 15 minutes, it does not -- it will only show the start time.

Thanks!

**Comment by acerix** [comment]
Thanks for the detailed report.  There is already an open issue for this:
https://github.com/fullcalendar/fullcalendar/issues/4024
↑
Could you please visit the link, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates?

**Comment by jamesdixon** [comment]
@acerix sorry - missed it when i did my search! thank ya

**Comment by Tandulje** [comment]
creating slot for 30 min i.e. 11.00 - 11.30 in this case 11.30 it not show on event in cell.
