### ISSUE TITLE
FcMoreCell class not always applied

### ISSUE THREAD

**Issue by boyomarinov** [fullcalendar/fullcalendar#4054]
*Scenario:* Two events. Both starting today, one ends today and the other ends tomorrow. Starting hour is different (for some reason that makes a difference). Calendar is in "mobile" view and `eventLimit` is enabled, so for both days `+ events` hyperlink is shown.

*Codepen:* https://codepen.io/boyomarinov/pen/paNgar 

*Expected result:* `fc-more-cell` class is applied on the table cell for tomorrow, since a link is displayed.

*Actual result:* `fc-more-cell` class is not applied

Full Calendar version: 3.4.0

**Comment by acerix** [comment]
Thanks for the detailed report.

Same issue in latest version, parent `td` is missing this class when the start times of these 2 events are different.

https://codepen.io/acerix/pen/bLBRwO?editors=0010

**Comment by dannyhanke** [comment]
@acerix any chance that this issue will be fixed anytime soon ?

**Comment by arshaw** [comment]
this is a strange bug, but as of v5, the issue no longer really applies because the DOM is completely different. please inspect the new DOM to see the new classnames
