### ISSUE TITLE
Dropped external event not added to calendar when using events source as a function

### ISSUE THREAD

**Issue by jayrosen1576** [fullcalendar/fullcalendar#4055]
If I create a calendar with an events source as a custom function (https://fullcalendar.io/docs/event_data/events_function/) dropping an external event onto the calendar does not seem to work. If I switch the events source to an array or a json feed the event is rendered when dropped. 

I tried to manually render the event using .fullCalendar('renderEvent', ...) but that is ineffective as well when using the events source as a function.

fiddle: https://jsfiddle.net/zrp3vvcn/21/

Not sure if this is a bug (somewhat likely) or if I'm doing something wrong (way more likely). Any help is greatly appreciated.

**Comment by acerix** [comment]
Supply events with a function requires `callback` to be called, your example works by calling that even on an empty array:

https://jsfiddle.net/zrp3vvcn/24/

**Comment by jayrosen1576** [comment]
Ah ok. The ajax call I implemented returned a 404 for no events found and in the error response I was not calling the callback with an empty array which I am now and it works. Thanks.
