### ISSUE TITLE
Possible Bug

### ISSUE THREAD

**Issue by paulwright75** [fullcalendar/fullcalendar#4058]
Please read this before dropping the request; I'm not sure if there is a bug or not. I have not written any code on my side as I am just reviewing the scheduler feature and testing it on various browsers from your site. I find that Safari does not render the same as Firefox. Example:
Firefox:
![firefox](https://user-images.githubusercontent.com/24362470/36043914-bd00773a-0d85-11e8-9086-26ce302a9384.PNG)

Safari:
![image](https://user-images.githubusercontent.com/24362470/36043942-d6af8266-0d85-11e8-8b8c-5998874ff669.png)

I am using Safari v.5.1.7 and Firefox v.58.0.1

You will notice that in the time area (far lefthand side) Safari does not respect the boundaries of the time text and removes the styling from that area completely.

I did not find any mention of this in google searches and just wondering if this is an issue or not.

**Comment by paulwright75** [comment]
Forgot to mention I am using both browsers on Windows 10.

**Comment by acerix** [comment]
Safari for Windows was discontinued, that old version is not supported.   I don't have a Mac to test with, but it would be a bug if it looks like that in the latest version.

Is this the demo you are testing?

https://fullcalendar.io/js/fullcalendar-scheduler-1.9.2/demos/vertical-resource-view.html

**Comment by paulwright75** [comment]
Yes, that's the page...

**Comment by paulwright75** [comment]
Okay, taking what you stated about it being discontinued on Windows, I tried it on High Sierra running the latest version of Safari and it works. I did not know that Safari was discontinued on windows so the version I have must be older.

Thanks for getting back to me on this...
