### ISSUE TITLE
Wrong event dragged when right mouse is pressed on a different event before

### ISSUE THREAD

**Issue by PBuchmann** [fullcalendar/fullcalendar#4059]
Just similar to issue https://github.com/fullcalendar/fullcalendar/issues/3823 

I reproduced it on the example given at https://fullcalendar.io/:
• Click (with the mouse right key) on any event. Close the context menu.
• Now, drag the any other event.
 Expected: the event grabbed is the one dragged.
 Actual: the event dragged is the event where the right mouse was pressed on.

After dragging this one wrong element, drag and drop works as it should. Interestingly a second right click on a other event does not make this other event the dragged event. It still remains the first one.

The given solution on the issue above does not work here.

**Comment by cptx032** [comment]
i think this is the same from: https://github.com/fullcalendar/fullcalendar/issues/3324

**Comment by arshaw** [comment]
yes, thanks, this is the same issues as:
#3324
&uarr;
Could you please all visit the link, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates? I'm going to use this issue as the canonical one
