### ISSUE TITLE
"columnHeaderHtml" and "columnHeaderText" not in Type Definitions

### ISSUE THREAD

**Issue by Bisdow** [fullcalendar/fullcalendar#4061]
Just a tiny thing, hardly worth a bugfix :-)

Currently the 
columnHeaderHtml ([see Documentation](https://fullcalendar.io/docs/text/columnHeaderHtml/))
and
columnHeaderText  ([see Documentation](https://fullcalendar.io/docs/text/columnHeaderText/))
have no TypeSccript Definitions.

It seems that in the file "input-types.ts" in the interface "OptionsInputBase" the part
`columnHeaderHtml?: string | ((date: MomentInput) => string)`
and
`columnHeaderText ?: string | ((date: MomentInput) => string)`
is missing.

Warm regards
Bisdow

**Comment by acerix** [comment]
Thanks for reporting this, similar to https://github.com/fullcalendar/fullcalendar/issues/4006

**Comment by arshaw** [comment]
queued for release https://github.com/fullcalendar/fullcalendar/commit/c3164fab8ecfb366166667fbd87673d3fa58b613

**Comment by arshaw** [comment]
released in [v3.9.0](https://github.com/fullcalendar/fullcalendar/releases/tag/v3.9.0)
