### ISSUE TITLE
Scheduler background color weekend

### ISSUE THREAD

**Issue by thiagoducca** [fullcalendar/fullcalendar#4064]
Hi,  I didn't find how I can put background color on weekends in  "Scheduler", only in "Fullcalendar".

My test:
https://codepen.io/anon/pen/oEowgq?editors=0110

this css doesn't work  
.fc-sat, .fc-sun {
    background-color: red !important;
}

**Comment by acerix** [comment]
Are you trying to color the entire column? It might work to use `businessHours`:

https://codepen.io/anon/pen/vddbgL
