### ISSUE TITLE
Strict time ordering events (request)

### ISSUE THREAD

**Issue by ivkirill** [fullcalendar/fullcalendar#4068]
I'm trying to use FullCalendar for rendering events with duration between days, events isn't overlaping. 

Events doesn't sorting by time in day block, but sorting by available space:
http://dl4.joxi.net/drive/2018/02/15/0005/4033/360385/85/a4ae49a9f7.png

I need to reorder events in day block. "Event 3" should be after "Event 2", "Event 5" after "Event 4".
https://image.ibb.co/fEqjGS/Screen_Shot_2018_02_19_at_13_56_16.png

It's like agenda view but for month timeline.

**Comment by acerix** [comment]
Are you requesting this as a new feature? 

You might be able to achieve that with a custom view:

https://fullcalendar.io/docs/views/Custom_Views/

**Comment by ivkirill** [comment]
Yes, request to a new feature.
But i will try to resolve this by myself and show solution.

**Comment by ivkirill** [comment]
Problem solved :) with dirty hack, but solved
