### ISSUE TITLE
display in Ascending order when we click on more button

### ISSUE THREAD

**Issue by bindusree** [fullcalendar/fullcalendar#4073]
### Bug Reports
You MUST have a JSBin recreation, or else your issue will be CLOSED without explanation.
Instructions: http://fullcalendar.io/wiki/Reporting-Bugs/

### Feature Requests
Search the issue tracker for an existing ticket before creating a new one.
Instructions: http://fullcalendar.io/wiki/Requesting-Features/

(Please erase the above text and begin typing. Thanks!)

**Comment by acerix** [comment]
Are you requesting to have the events after `eventLimit` displayed from oldest to newest when `+1 more` is clicked?
