### ISSUE TITLE
Null pointer when the now indicator is outside the time grid

### ISSUE THREAD

**Issue by joseluismolinasoria** [fullcalendar/fullcalendar#4074]
The context is:
* Today range of hours is limited, and there is another day with a different range of hours (values of minTime and maxTime are different in each day)
* Whenever we go from today to the other day the calendar is incorrectly rendered

We attach a Codepen pen with the case and a screenshot with the error raised
[Codepen link](https://codepen.io/joseluismolinasoria/pen/VQdbjq)
![error1](https://user-images.githubusercontent.com/3055726/36529766-983d876a-17b9-11e8-86d1-37e2d2ca0312.png)

**Comment by acerix** [comment]
Thanks for the report. 

Here's a reduced demo: https://codepen.io/acerix/pen/NyLxNM?editors=0010

Seems to not happen with a bigger range: https://codepen.io/acerix/pen/aqadBz?editors=0010

**Comment by arshaw** [comment]
fixed in v5: https://codepen.io/arshaw/pen/GRoEPwR?editors=0010
