### ISSUE TITLE
Fullcalendar window is automatically scrolling up

### ISSUE THREAD

**Issue by imilo** [fullcalendar/fullcalendar#4075]
JSFiddle example: https://jsfiddle.net/edomzxLL/1/

I've got an issue with creating new events. Please open JSFiddle demo, in Chrome for example, scroll down the result window to the bottom, make sure it's height is small enough, so you **cannot** see the whole calendar.

Click buttons **month** -> **week** -> **month** -> **week** (several times). Now try to create a event today at **11pm** - a modal window will appear -> press **Cancel**.

What I get now and what is wrong - browser window is scrolled up, until the Title of the calendar!

As you see - there is no my own libraries included, only basic code from fullcalendar/semantic-ui documentation.

The issue doesn't happen with Semantic-ui modal window itself (without fullcalendar), so I've decided to create an issue here. Moreover, just after a page refresh everything is Ok, but then pressing **month** -> **week** -> **month** -> **week** enables this scrolling up.

Please help to understand what's wrong and how to prevent this strange/unneeded scrolling up?

**Comment by acerix** [comment]
Thanks for the report.  It's hard to confirm that the scrolling issue is in fullcalendar, but it does look that way since it happens only after clicking the buttons.

**Comment by imilo** [comment]
Hello!
This issue has ended with a problem in Semantic UI, so nothing to do from your side :)

The problem is that after modal window is closed - focus is returning to the previously active element. So if it is somewhere up - browser is scrolling up.
