### ISSUE TITLE
eventLimit month view sets to 7, but more link displays when cell has 3 event

### ISSUE THREAD

**Issue by SergeyPiskov** [fullcalendar/fullcalendar#4076]
when a day has a lot of events all next days have more link too.
![image](https://user-images.githubusercontent.com/4173143/36536756-a98b959c-1800-11e8-9f5e-73208eed446c.png)

22 day has 24 events
23 day has 3 events and should be displayed without more link

configurations:
```
eventLimit: true, 
views: {
    month: {
        eventLimit: 7
    }
},
```

**Comment by acerix** [comment]
Would you be able to post a [runnable, stripped-down demonstration of the bug](http://fullcalendar.io/wiki/Reduced-Test-Cases/)? Would really appreciate it because the time saved reproducing will be time spent fixing.

**Comment by SergeyPiskov** [comment]
Please try next link 
https://codepen.io/SergeyPiskov/pen/GQPOMP
21th and 22th February had a lot of events and had more link. 23th and 24th February have 2 events, but also had more link.

**Comment by acerix** [comment]
Thanks for the demo.  I removed your custom code and the issue still exists with just the events:

https://codepen.io/acerix/pen/QQoJmo?editors=0010

**Comment by TigressBailey** [comment]
@arshaw How did it go?

**Comment by arshaw** [comment]
this other ticket captures the more general problem:
https://github.com/fullcalendar/fullcalendar/issues/4960
&uarr;
Could you please visit the link, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates?
