### ISSUE TITLE
minTime and maxTime also businessHour not working with month view aganda 

### ISSUE THREAD

**Issue by dipak-d** [fullcalendar/fullcalendar#4077]
I'm using fullcalendar with angular 1 and I'm having issue like I set minTime and maxTime duration and it's working fine in week and day view but it's not working in Month view.

I want to set timing from 6AM to Next day 5AM

Please check below working example 
[http://jsfiddle.net/DDDipak/jso51pm6/658/](http://jsfiddle.net/DDDipak/jso51pm6/658/)

Please help us to solve.

**Comment by acerix** [comment]
The month view shows full days only, so it doesn't take into account times like minTime.  I think you could use a custom view for what you want:

https://fullcalendar.io/docs/views/Custom_Views/
