### ISSUE TITLE
Drag & Drop Problem

### ISSUE THREAD

**Issue by StefanTD** [fullcalendar/fullcalendar#4080]
I have a problem with darg & drop (tested in FireFox & IE)
https://codepen.io/anon/pen/zRmPKp?editors=0011

In the example you can see one event.
darg & drop the event from the 6. to the 8.
now click the event.
Every time you click the event was changed in the frontend.  (+ days from the first drag & drop) 

It only happens when start and end are the same

**Comment by acerix** [comment]
If the start and end are the same, you should not provide any end date.  Otherwise, the end time just gets changed to `null`, so when you try to format that as a date, it causes a JS error which leads to this behaviour.  

https://codepen.io/acerix/pen/KQrVMZ?editors=0011

**Comment by StefanTD** [comment]
Thank you for your answer. Okay thats works.
But then the day-view shows a duration of two hours ??
I think if the start and end are the same the best solution ist to add 30min to the end.

**Comment by acerix** [comment]
Yes, events with no duration show up the size of 2 hours, otherwise nothing would show up.
