### ISSUE TITLE
New option 'columnHeaderFormat' isn't avaiable in typescript definition file

### ISSUE THREAD

**Issue by thiagoburgo** [fullcalendar/fullcalendar#4085]
Version: v3.8.2

New option 'columnHeaderFormat' isn't avaiable in typescript definition file.

**Comment by acerix** [comment]
Thanks for reporting

**Comment by arshaw** [comment]
queue for release https://github.com/fullcalendar/fullcalendar/commit/c3164fab8ecfb366166667fbd87673d3fa58b613

**Comment by arshaw** [comment]
released in [v3.9.0](https://github.com/fullcalendar/fullcalendar/releases/tag/v3.9.0)

**Comment by kamleshwebtech** [comment]
how to change header date format to UK date format (day / month / year) in week view in full calendar 4 version? Please suggest. Thank you.
