### ISSUE TITLE
Custom event object

### ISSUE THREAD

**Issue by Kalpesh300** [fullcalendar/fullcalendar#4090]
This is not about bug but I am requesting a new feature. In its latest version calendar only displays title, start-date and end-date. But I want to request you to allow dynamic creation of event object which is going to be rendered. What I mean by dynamic creation is I want to display parameters like project-name, then array of member-name and some icon-buttons.

**Comment by acerix** [comment]
You can use the [eventRender](https://fullcalendar.io/docs/eventRender) callback to change what is rendered for each event.
