### ISSUE TITLE
jQuery UI definitely required to drag external element onto calendar?

### ISSUE THREAD

**Issue by jdudleyie** [fullcalendar/fullcalendar#4093]
Hi - I am just wondering if there is a hard dependency on including jQuery UI to allow an external e.g. div to be draggable and to be dropped onto the calendar, or is there any other way to create an external element that can be dropped? Thanks.

**Comment by acerix** [comment]
The built-in support (eg. `eventReceive`) is based on jQuery UI, but you can add events with [addEventSource](https://fullcalendar.io/docs/addEventSource) after some other dragging method.

**Comment by jdudleyie** [comment]
Hi @acerix - thanks for this. I assume by using addEventSource, I would not be able to have elements be dropped directly onto the calendar with the same highlighting/events as happens with jQuery UI draggable elements?

**Comment by acerix** [comment]
Yes, you would need to do the highlighting yourself, as well as figuring out which dates to set on the new event.
