### ISSUE TITLE
REFETCHING  OF EVENT SOURCE REDRAWS ALL EVENTS/UNSELECTION/DRAG START FAILS

### ISSUE THREAD

**Issue by danserbanoiudev** [fullcalendar/fullcalendar#4095]
### Bug Report

**What I am trying to achieve**: As soon as a user clicks on an todo event or drag the todo, its constraints will be drawn on the fullcalendar in order to visually see where that todo can be moved to.

**Bug Explaination**: I created a fullcalendar instance with multiple sources (todos and constraints), but when refetching just one of the sources with 'refetchEventSources' (after doing some processing maybe), it seems like internally it will re-instantiate/re-draw all dom aliases of all the events. 

I made an example of what I mean in the **codepen**: https://codepen.io/danserbanoiu/pen/VXZgaz?editors=1111

If you click on the blue 'Cool Todo', it will trigger a SelectEvent function, which will:

1. Change its color to 'Dark Blue';
2. 3 seconds pass;
3. Adds one constraint to constraintSource;
4. Triggers the refetching of only the constraintSource so that only the constraints will be drawn on the fullcalendar instance;
5. The new constraints (one in the pen example) are drawn on the fullcalendar instance.

Unfortunately when the calendar refetches the constraintSource the 'Cool Todo' will change its color back to original. This means that the dom element to which was originally applied the 'Dark Blue' style was removed and a new one was created. A new dom element is now associated to the same todo.

Of course a simple workaround to keep the 'Cool Todo' 'Dark Blue' (to symbolize the fact it is selected) would be to simply search for the new dom element right after refetching the 'constraints' and re-apply the 'Dark Blue' style.

Unfortunately this solution fails when dealing with the eventDragStart event. If you start dragging the 'Cool Todo' the same SelectEvent function will be triggered, only this time after 3 seconds, it will not be possible to keep dragging the 'Cool Todo' anymore because the element that is being dragged is referencing that old dom event alias that was deleted, replaced with a new one. 

**My Question**: is it possible to make it so that when the fullcalendar is refetching only one source it will draw on the fullcalendar only the events of that specific source, but keep everything else unchanged?

**Comment by acerix** [comment]
I believe this existing ticket captures this need:
https://github.com/fullcalendar/fullcalendar/issues/3003
↑
Could you please visit the link, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates?

You could get the result you want by adding a custom property to the event object (eg. `selected`) that you set to `true` when the event is clicked.  Then you can set the color in `eventRender` `if (event.selected)` so it will always render the color based on that property which is not lost after rendering.

**Comment by danserbanoiudev** [comment]
Of course,

But this solution fails when dealing with the eventDragStart event. In the example If you start dragging the 'Cool Todo' the same SelectEvent function will be triggered, only this time after 3 seconds, it will not be possible to keep dragging the 'Cool Todo' anymore because the element that is being dragged was deleted.

**Comment by danserbanoiudev** [comment]
Thank you very much for your answer,

You actually gave me a pretty cool idea. Is it possible to prevent only one event from being destroyed, maybe with the eventDestroy callback (I tried returning false but it doesn't prevent the destruction)?

If it was possible to prevent an event destruction, maybe it would be possible to solve the DragStart problem, by then preventing the rendering (which can be achieved by returning false if the id is equal to the selected event).

**Comment by acerix** [comment]
`eventDestroy` doesn't allow for stopping the event from being destroyed. I don't think it would work great to do that anyways, since events are positioned based on position of other events, so without that you might get overlapping events, or spaces between events after removing one, etc.

**Comment by danserbanoiudev** [comment]
How about I monkey patch the rendering process so that it will only rerender the backgroundEvents (in my scenario I only use backgroundEvents for the constraints) and only do that when I do the actions I described above.

In my situation it shouldn't matter much where these events are drawn in relation to the other events since I do not mind if the constraints overlap entities in the scheduler.

Assuming I try to follow this path what do you suggest I monkey patch to achieve this result without breaking everything else?

It could be great if there could be some 'rerender' method I could decorate with an if that checks when I choose to draw some background events of type 'constraints' and  if so will only rerender those and avoid destroy-rendering everything else...

I was reading the source code and although it's a nice written code I am having some trouble understanding what every class is doing. It would really help to have the activity diagrams/class diagrams/sequence diagrams and relative descriptions.

Thank you for the help you gave me so far, a beer's on me

**Comment by danserbanoiudev** [comment]
For example, I think this could be achieved by monkey patching refetchEventSources(sourceMultiQuery) of the Calendar object. I am having trouble accessing the eventManager property so I can call     eventManager.refetchSource(sources[i]) only once when refetching the 'constraints'

![cattura](https://user-images.githubusercontent.com/32792904/37332628-7e3e016c-26a7-11e8-9c84-fc9acc88600c.PNG)

https://github.com/fullcalendar/fullcalendar/blob/master/src/Calendar.ts

**Comment by danserbanoiudev** [comment]
Ok, I can access the eventManager property inside my own monkey patched function of refetchEventSource using 'this', the Calendar's instance execution context.

**Comment by danserbanoiudev** [comment]
` refetchEventSources(sourceMultiQuery) {
    let eventManager = this.eventManager
    let sources = eventManager.multiQuerySources(sourceMultiQuery)
    let i

    eventManager.freeze()

    for (i = 0; i < sources.length; i++) {
      eventManager.refetchSource(sources[i])
    }

    eventManager.thaw()
  }`
