### ISSUE TITLE
Calendar is putting events back 1 day

### ISSUE THREAD

**Issue by fibreiv** [fullcalendar/fullcalendar#4096]
Ever since 2018 all my events are showing back 1 day from what they are suppose to be.

`$('#calendar').fullCalendar({ header: { left: 'prev,next', center: 'title', right: 'month,basicWeek,listMonth' }, //defaultDate: '01/01/2018', //3/01/2018 defaultDate: '2018/3/01', defaultView: 'month', navLinks: false, // can click day/week names to navigate views editable: false, weekends: false, eventTextColor: '#fff', eventLimit: false, // allow "more" link when too many events nowIndicator: false, events: [ {title:'Financial: Tina',start: '2018-3-01', allDay: true}, {title:'Deposit: Maryann',start: '2018-3-01', allDay: true}, {title:'Counter: Susan',start: '2018-3-01', allDay: true}, {title:'Mail: Jennie',start: '2018-3-01', allDay: true}, {title:'Financial: Tina',start: '2018-3-02', allDay: true}, {title:'Counter: Jennie',start: '2018-3-02', allDay: true}, {title:'Mail: Maryann',start: '2018-3-02', allDay: true}, {title:'Financial: Tina',start: '2018-3-05', allDay: true}, {title:'Counter: Lori',start: '2018-3-05', allDay: true}, {title:'Mail: Susan',start: '2018-3-05', allDay: true}, {title:'Financial: Tina',start: '2018-3-06', allDay: true}, {title:'Counter: Maryann',start: '2018-3-06', allDay: true}, {title:'Mail: Lori',start: '2018-3-06', allDay: true}, {title:'Financial: Tina',start: '2018-3-07', allDay: true}, {title:'Counter: Susan',start: '2018-3-07', allDay: true}, {title:'Mail: Jennie',start: '2018-3-07', allDay: true}, {title:'Financial: Tina',start: '2018-3-08', allDay: true}, {title:'Deposit: Maryann',start: '2018-3-08', allDay: true}, {title:'Counter: Colleen',start: '2018-3-08', allDay: true}, {title:'Mail: Michael',start: '2018-3-08', allDay: true}, {title:'Financial: Tina',start: '2018-3-09', allDay: true}, {title:'Counter: Michael',start: '2018-3-09', allDay: true}, {title:'Mail: Colleen',start: '2018-3-09', allDay: true}, {title:'Financial: Tina',start: '2018-3-12', allDay: true}, {title:'Counter: Jennie',start: '2018-3-12', allDay: true}, {title:'Mail: Susan',start: '2018-3-12', allDay: true}, {title:'Financial: Tina',start: '2018-3-13', allDay: true}, {title:'Counter: Maryann',start: '2018-3-13', allDay: true}, {title:'Mail: Lori',start: '2018-3-13', allDay: true}, {title:'Financial: Tina',start: '2018-3-14', allDay: true}, {title:'Counter: Lori',start: '2018-3-14', allDay: true}, {title:'Mail: Maryann',start: '2018-3-14', allDay: true}, {title:'Financial: Tina',start: '2018-3-15', allDay: true}, {title:'Deposit: Maryann',start: '2018-3-15', allDay: true}, {title:'Counter: Colleen',start: '2018-3-15', allDay: true}, {title:'Mail: Michael',start: '2018-3-15', allDay: true}, {title:'Financial: Tina',start: '2018-3-16', allDay: true}, {title:'Counter: Michael',start: '2018-3-16', allDay: true}, {title:'Mail: Colleen',start: '2018-3-16', allDay: true}, {title:'Financial: Tina',start: '2018-3-19', allDay: true}, {title:'Counter: Susan',start: '2018-3-19', allDay: true}, {title:'Mail: Jennie',start: '2018-3-19', allDay: true}, {title:'Financial: Tina',start: '2018-3-20', allDay: true}, {title:'Counter: Maryann',start: '2018-3-20', allDay: true}, {title:'Mail: Susan',start: '2018-3-20', allDay: true}, {title:'Financial: Tina',start: '2018-3-21', allDay: true}, {title:'Counter: Jennie',start: '2018-3-21', allDay: true}, {title:'Mail: Maryann',start: '2018-3-21', allDay: true}, {title:'Financial: Tina',start: '2018-3-22', allDay: true}, {title:'Deposit: Maryann',start: '2018-3-22', allDay: true}, {title:'Counter: Lori',start: '2018-3-22', allDay: true}, {title:'Mail: Colleen',start: '2018-3-22', allDay: true}, {title:'Financial: Tina',start: '2018-3-23', allDay: true}, {title:'Counter: Colleen',start: '2018-3-23', allDay: true}, {title:'Mail: Michael',start: '2018-3-23', allDay: true}, {title:'Financial: Tina',start: '2018-3-26', allDay: true}, {title:'Counter: Michael',start: '2018-3-26', allDay: true}, {title:'Mail: Lori',start: '2018-3-26', allDay: true}, {title:'Financial: Tina',start: '2018-3-27', allDay: true}, {title:'Counter: Susan',start: '2018-3-27', allDay: true}, {title:'Mail: Maryann',start: '2018-3-27', allDay: true}, {title:'Financial: Tina',start: '2018-3-28', allDay: true}, {title:'Counter: Jennie',start: '2018-3-28', allDay: true}, {title:'Mail: Susan',start: '2018-3-28', allDay: true}, {title:'Financial: Tina',start: '2018-3-29', allDay: true}, {title:'Deposit: Maryann',start: '2018-3-29', allDay: true}, {title:'Counter: Lori',start: '2018-3-29', allDay: true}, {title:'Mail: Jennie',start: '2018-3-29', allDay: true}, {title:'Financial: Tina',start: '2018-3-30', allDay: true}, {title:'Counter: Maryann',start: '2018-3-30', allDay: true}, {title:'Mail: Colleen',start: '2018-3-30', allDay: true},
![scheduler]
`
![scheduler](https://user-images.githubusercontent.com/29683648/37177026-c474248a-22e3-11e8-9584-c17a44203d61.PNG)

### Bug Reports
You MUST have a JSBin recreation, or else your issue will be CLOSED without explanation.
Instructions: http://fullcalendar.io/wiki/Reporting-Bugs/

### Feature Requests
Search the issue tracker for an existing ticket before creating a new one.
Instructions: http://fullcalendar.io/wiki/Requesting-Features/

(Please erase the above text and begin typing. Thanks!)

**Comment by acerix** [comment]
Would you be able to post a [runnable, stripped-down demonstration of the bug](http://fullcalendar.io/wiki/Reduced-Test-Cases/)? Would really appreciate it because the time saved reproducing will be time spent fixing.

**Comment by fibreiv** [comment]
I just put this in default.html in the demo folder and it show this even on Feb. 28.  I think I'm at the point now where I might try a different server. Wondering if it's a me problem.


`	$(document).ready(function() {

		$('#calendar').fullCalendar({
			defaultDate: '2018-03-01',
			editable: true,
			eventLimit: true, // allow "more" link when too many events
			events: [
				
				{title:'Financial: Tina',start: '2018-3-01', allDay: true}

			]
		});
		
	});`

**Comment by acerix** [comment]
The issue is that start date needs to be in ISO_8601 format, so '2018-03-01' instead of  '2018-3-01', eg:

https://codepen.io/anon/pen/eMYEyQ?&editors=001
