### ISSUE TITLE
error TS2559: Type '"removeEventSources"' has no properties in common with type 'OptionsInput'.

### ISSUE THREAD

**Issue by jdudleyie** [fullcalendar/fullcalendar#4099]
Hello,

I have been playing with the different options to remove events from the calendar, and the following is the only one that has worked for me when using a local array to bind:

```
this.calendar.fullCalendar('removeEventSources');
```

As per the the documentation, the second parameter should be optional (in any case events are only removed for me if I don't specify it) - https://fullcalendar.io/docs/removeEventSources

The problem I have is that I believe the event definition without the second parameter is not specified in node_modules\fullcalendar\dist\fullcalendar.d.ts which is part of the npm package I installed (fullcalendar@3.9.0). So when I run ng serve - I get the following error:

```
error TS2559: Type '"removeEventSources"' has no properties in common with type 'OptionsInput'.
```

If I add the definition into fullcalendar.d.ts file, inserting the following:

```
fullCalendar(method: 'removeEventSources'): JQuery;
```

before the following existing line (line 2586):

```
fullCalendar(method: 'removeEventSources', sourceMultiQuery: any): JQuery;
```

Then 'ng serve' works. But then when I deploy on my App Service using Visual Studio Team Services, because the agent re-installs the packages, my build fails with the same error:

```
error TS2559: Type '"removeEventSources"' has no properties in common with type 'OptionsInput'.
```

My understanding is that I can "patch" an interface, adding the missing definition locally in my angular component - but I am not sure how to do it, especially as the interface is nested.

```
declare module 'fullcalendar/src/types/jquery-hooks' {
...
	    interface JQuery {
...
			fullCalendar(method: 'removeEventSources', sourceMultiQuery: any): JQuery;
...
```

I am new to Typescript, so there's probably a simple solution, but if you could help it would be appreciated.

Thanks.

**Comment by acerix** [comment]
The files under `/dist/` are compiled automatically from the source files, so you don't want to edit those, but instead the source files, eg. [jquery-hooks.ts](https://github.com/fullcalendar/fullcalendar/blob/master/src/types/jquery-hooks.ts#L46). So that should get your fix working if the dist files are being recompiled on `ng serve`. 

I can't test that at the moment, but I believe your error is because the definition is missing a `?` to indicate the param is optional, eg:

    fullCalendar(method: 'removeEventSources', sourceMultiQuery?: any): JQuery;

**Comment by jdudleyie** [comment]
Ok thanks @acerix. Sorry from your reply I am not sure how to solve or override this. For now I have taken the whole fullcalendar.d.ts file into my source and made the fix there, until I can figure out how to resolve or until the definitions file is fixed in a new version.

**Comment by jdudleyie** [comment]
Thanks @acerix @arshaw for your reply. Probably due to my lack of knowledge, I am not sure from your reply how to fix or override this in my source code, either perhaps by defining in interface for the version of the method with no second argument, or by someone overriding the existing signature and making the second argument optional.

If you have any example or pointers on how to do this, it would be helpful.

Thanks.

**Comment by naidu95** [comment]
I am also getting same error.But function is working and it showing error in terminal.
`ERROR in src/app/bookcalendar/bookcalendar.component.ts(35,32): error TS2559: Type '"removeEventSources"' has no properties in common with type 'OptionsInput'.`

**Comment by arshaw** [comment]
the original reported is no longer an issue in v4/v5 because the API for calling methods has completely changed. @naidu95 your issue sounds different
