### ISSUE TITLE
Changing 'hiddenDays' dynamically causes events to disappear sometimes

### ISSUE THREAD

**Issue by justanotheranonymoususer** [fullcalendar/fullcalendar#4102]
Here's a demonstration of the bug:
https://codepen.io/anon/pen/MVwpYp

As a workaround, I don't set `hiddenDays` upon initialization, and it seems to work.

**Comment by acerix** [comment]
Thanks for the report.

**Comment by arshaw** [comment]
this is almost definitely fixed in v5
