### ISSUE TITLE
Agenda week abnormal background color

### ISSUE THREAD

**Issue by MicheleVarnier** [fullcalendar/fullcalendar#4103]
I have noticed that if I use "jquery ui" theme, the first row (7 a.m.) in agenda week has a lighter background (#F8F8F8 vs #EEEEEE). Obviously I'd like to have the same color all around. Any suggestions? Thanks.

Here is a fiddle reproducing the error
https://jsfiddle.net/mvarnier/yhfsv455/

**Comment by acerix** [comment]
Are you using the latest versions? I tried your code with the latest versions and don't see the issue:

https://codepen.io/anon/pen/jzWaye?&editors=001

**Comment by MicheleVarnier** [comment]
I'm using ver.3.8.2. I downloaded it just a few days away... but did you see my fiddle? the problem is there...

**Comment by acerix** [comment]
I see the issue in your fiddle, but not when I test it with the latest versions.  Maybe it's jquery-ui that you need to update, the style looks quite different than my example.

**Comment by arshaw** [comment]
jquery ui theming is no longer supported in v4
