### ISSUE TITLE
SelectConstraint - business hours with multiple days

### ISSUE THREAD

**Issue by dnyg** [fullcalendar/fullcalendar#4108]
I'm trying to use the selectConstraint property to only allow events during business hours, but it won't let me use selectable to create an event that spans across multiple days in the agendaWeek view (while following business hours).

I've created a codepen https://codepen.io/anon/pen/JLYqrq?&editors=001

I'm looking for a way to support selecting of multiple days, while still following business hours.

**Comment by acerix** [comment]
Thanks for the suggestion, agree that could be useful.

You could try `eventRender` to create a repeating event with all the segments that you manually calculate based on the business hours.

**Comment by arshaw** [comment]
i believe this is a dup:
https://github.com/fullcalendar/fullcalendar/issues/3793
&uarr;
Could you please visit the link, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates?
