### ISSUE TITLE
After collapse or expand resource "eventAfterRender" not triggered however "eventRender" triggered

### ISSUE THREAD

**Issue by ahmelessawy** [fullcalendar/fullcalendar#4109]
Hi Team,
After "timeline" view rendered successfully, and all life-cycle events triggered successfully.
When I try to collapse then expand back the resource "eventRender" triggered but "eventAfterRender" not.

Thanks in advance

**Comment by acerix** [comment]
Would you be able to post a [runnable, stripped-down demonstration of the bug](http://fullcalendar.io/wiki/Reduced-Test-Cases/)? Would really appreciate it because the time saved reproducing will be time spent fixing.
