### ISSUE TITLE
bug: scrollTime not scrolling in couple of different cases

### ISSUE THREAD

**Issue by karlmnz** [fullcalendar/fullcalendar#4114]
Bug Reports
Problem 1) I have full calendar in an angular component.  Then in the ngOnInit I configure the calendar e.g. $('#calendar').fullCalendar({ defaultView: 'agendaWeek', scrollTime: '04:00:00'}),

But when I open the page the calendar opens to scollTime 6am even thought 4am is set.

This behaviour is the same in all browsers.  Expected behaviour is as a JS project/code pen which seems to work.  But in angular I have not been able to get this to work, expect it to work the same.

Problem 2)  So then I thought to use a function after the calendar has loaded.  And set the scollTime there  See this code pen for example. (understand this is different from initial scollTime)

https://codepen.io/karlmnz/pen/JLbJJm

I have 4 buttons that there clicked events to demo what I have tried I cause of problem 1 not working.

Buttons:
Just scrollTime - set sets the scollTime in code.  This doesn't scroll.

ScollTime &* Bad solution - this works but uses getData and so to much movement of the calendar for no reason.  And it needs the days moved to be 7+ for it to work.
(the lag on IE11 make this really noticeable as bad solution).

ScrollTime & Scroll Top (too hard) this uses DOM and scrollTop but that a position integer not a time so to hard to calc especially when SlotDuration is changed.

ScollTime & Render - seemed might be logical as scollTime is initialisation ...  but just doesn't work.

My use case is moving between weeks as timesheets and each week can have different slotDurations. also view can be agendaDay or agendaWeek and switch between.  Using scrolltime so when page opened are positioned on current time of day (calculated).

Just want a way in angular to set the initial scrollTime that works.

**Comment by korengal** [comment]
This bug is already reported here: 
https://github.com/fullcalendar/fullcalendar/issues/467.

If you need the same scroll time hour for different views you can use it in the calendarOptions like this:

[https://fullcalendar.io/docs/custom-view-with-settings](url)


`views: {
                                agendaDay: {
                                    type: 'agenda',
                                    scrollTime: '07:00:00',
                                },
                                agendaThreeDay: {
                                    type: 'agenda',
                                    duration: { days: 3 },
                                    scrollTime: '10:00:00',
                                },
                                agendaWeek: {
                                    scrollTime: '12:00:00',
                                }
                            },`

**Comment by acerix** [comment]
@karlmnz Would you be able to post a [runnable, stripped-down demonstration of the bug](http://fullcalendar.io/wiki/Reduced-Test-Cases/)? Would really appreciate it because the time saved reproducing will be time spent fixing.

**Comment by karlmnz** [comment]
Thanks @korengal, view settings didn't work for me.  But it pointed me in the direction to get a solution.

My issues was, I was making calls changedVIew after setting scrollTime and these were outside the config so got weird results.

My problem was that I could not do the following in ngOnInit cause my observable which provided the these settings hadn't returned them yet (SO OVERALL A TIMING ISSUE).

```
$('#calendar').fullCalendar({
  defaultView: myViewName,
  scrollTime: myScrollTime,
  slotDuration: mySlotDuration,
  slotLabelInterval: myslotLabelInterval,
});
```

So could then init the calendar with the right settings.  And this meant that the initial scrollTime was random not even the default.

My Solution was to move the above config out of ngOnInit to a function and then when the observable returns the response I get the settings and config the calenader then and that is all I have to do to get the initial calendar to display correct.

Then when changing views I do like following, which make the new view be positioned in the same location as the old view. (this assumes that the slotDurations haven't changed).

```
let y = document.querySelector('.fc-scroller').scrollTop;
$('#calendar').fullCalendar('changeView', 'agendaDay');
document.querySelector('.fc-scroller').scrollTop = y;
```

@acerix, What would be nice as a feature is just to have an option on the fullcalendar that takes a time and the calendar is scrolled to that when the option is changed.  Understand this requires figuring out slotDuration to positions ... but would be better this is encapsulated in the full calendar rather than every dev having to figure this out ...  my scrollTop solution above has problems if the slotDurations change which in my app is possibility.  Leave it for the testers to find, very edge case.
