### ISSUE TITLE
Dynamic visible range changing is not working

### ISSUE THREAD

**Issue by IvanPoida** [fullcalendar/fullcalendar#4116]
Hello!
I'm trying to change calendar visible range, by event. But the code from the example (https://fullcalendar.io/docs/visibleRange) didn't worked for me.

I've created reproduction for this issue ( http://jsfiddle.net/mw8b030z/5/ )
Could you please help me with this?

**Comment by acerix** [comment]
Since you are supplying the date range, you should use the view as "agenda" instead of "agendaWeek" which has a duration. Here's an example:

https://codepen.io/acerix/pen/PRmKwM?&editors=001

**Comment by IvanPoida** [comment]
Thanks for replying. It hepled me a lot.

**Comment by NaveenTula90** [comment]
@acerix Does visible Range is working on Angular Full calendar?
