### ISSUE TITLE
Events with time between 10:00 pm and 11:59 pm are appearing in AM and on other dates as well

### ISSUE THREAD

**Issue by prashantdsala** [fullcalendar/fullcalendar#4117]
**1. Reduced test case**

a) Define an event with 'title' and 'start' attribute
b) Give the time of the event between 22:00 and 23:59 (10:00 pm and 11:59 pm) on any date
c) This event will appear twice on the Month and Day tab of the calendar
b) One in the PM and one in the AM, event duplicated in the AM part will either appear on same date or on next day

**2. Public Demonstration**
a) https://codepen.io/p1989chauhan/pen/XENBxB
b) Here i have defined an event 
  {
        title: 'My Event',
				start: '2018-03-20T22:45:00',
      }

c) In the "Week"  and "Day" tabs of the calendar this event is appearing on 2018-03-20 at 22:45:00 but also appearing on 2018-03-21 10:45:00 AM

This seems to be a major issue as i am using full-calendar in one of my websites where i found this issue.

**Comment by acerix** [comment]
If you don't set an end time, it defaults to 2 hours later, so with a start date after 22:00, the event continues on the next day.  You could set the end time to the end of the day, eg.:

https://codepen.io/acerix/pen/vRmJqN?editors=0010

**Comment by prashantdsala** [comment]
Hi acerix,

Thanks for your response.

But what if we don't want to specify the end time for the events after 10 pm ?
Is there any way to prevent these events from appearing on the next day ?

**Comment by acerix** [comment]
I don't see what you mean about appearing at 10:45 am.  In your example, the event shows the last 15 minutes in the 12 am timeslot.  

I suppose there should be a way to prevent an event with no `end` time, which starts after 10 pm, from displaying on the subsequent day, so I'll reopen this request since I don't see an obvious way to do that.

**Comment by prashantdsala** [comment]
Please check https://codepen.io/p1989chauhan/pen/XENBxB

1. Navigate to Week/day tab on the calendar
2. Check the event named "My Event" which is defined for 2018-03-20T22:45:00
3. This event is appearing at 2018-03-20 10:45:00PM
4. This event is also appearing at 2018-03-21 10:45:00PM

**Comment by acerix** [comment]
This is what I see: 

https://i.imgur.com/rv0bAe5.png

It shows the start time (10:45) on the event, but is in the 12:00 am time slot.

**Comment by prashantdsala** [comment]
@acerix 

Let me clarify once again please check the screenshots.
https://prnt.sc/j3pkar
https://prnt.sc/j3pknr
https://prnt.sc/j3pl1i

**Comment by acerix** [comment]
Yes, the start time (10:45) is repeated, but it's in the time slot 12:00 to 12:45 am if you look at the labels to the left.

It would be a new feature to have such events only show on the first day.  You could try [eventAfterRender](https://fullcalendar.io/docs/eventAfterRender) to remove or hide the DOM element of the part you don't want.

**Comment by thangnn86** [comment]
I also encountered this issue on version 4.0.2
![fullcalendar_issue1](https://user-images.githubusercontent.com/14267336/60639873-a4247080-9e4e-11e9-8547-ecad4ddf3675.png)
![fullcalendar_issue2](https://user-images.githubusercontent.com/14267336/60639874-a4bd0700-9e4e-11e9-9217-d7581c073529.png)

Please help me!

**Comment by arshaw** [comment]
i have no idea why this was happening, but it seems fixed in v5:
https://codepen.io/arshaw/pen/JjGJxdz?editable=true&editors=001
