### ISSUE TITLE
Bug: Center mouse cursor on event while dragging and scrolling together (dragScroll )

### ISSUE THREAD

**Issue by korengal** [fullcalendar/fullcalendar#4118]
Bug Reports:

Hey there :)

I have come across with 2 issues:

1)  The pointer cursor located out of the event when dragging and scrolling at the same time.
2) When trying to drag and scroll you can't drop the event into to wanted time frame If one is located in a scrolling distance.  

For example, I would like it to behave as google calendar.

Example of the issue:
![2018-03-20_19h01_07](https://user-images.githubusercontent.com/5110512/37670119-2ea7412a-2c71-11e8-8e51-5ab083749a69.gif)

Thanks

**Comment by acerix** [comment]
Thanks for the report, the drag position should be updated with scrolling. 

Related issue: https://github.com/fullcalendar/fullcalendar/issues/3487

**Comment by lucagouty** [comment]
I spent a bit time investigating, and I finally found a **quick** fix for this.

It seems adding `prepareHits` methods in `AgendaView` to trigger `grid.prepareHits()` does the trick. 

**It's really not perfect, and I really don't understand FC code, so I have no idea of possible implications.**

Though, if you want to git it a try, here is the change : https://github.com/lucagouty/fullcalendar/pull/1/files

And as an even dirtier fix, you can also do that directly in your code : 
```ts
const fc: any = jquery.fullCalendar
fc.AgendaView.prototype.prepareHits = function() {
  if (this.timeGrid) this.timeGrid.prepareHits()
  if (this.dayGrid) this.dayGrid.prepareHits()
}
```

**Comment by arshaw** [comment]
this should be fixed in v4.x
