### ISSUE TITLE
Event not display if the hour is less or equal to than T08:00:00

### ISSUE THREAD

**Issue by Ludovicmoreau** [fullcalendar/fullcalendar#4120]
### Bug Reports

Hello,
I save some events on fullCalendar and I think I found a bug.
When the start of the event is on a day and the end is on day+1 or more, if the end hour's is less or equal than T08:00:00, the event is not display on the calendar end's date.

The CodePen test : https://codepen.io/anon/pen/JLJeKX?editors=0010

**Comment by acerix** [comment]
By default, events ending before 9 AM are not displayed on the last day, you
