### ISSUE TITLE
Creating repeating event bug

### ISSUE THREAD

**Issue by inmylo** [fullcalendar/fullcalendar#4125]
Hello!

I think I've found a bug with creating repeating events.
JSFiddle demo: https://jsfiddle.net/8bq3fw79/18/

1. Open the link
2. Open browser console (F12)
3. Press **Add event** button
4. Check the console for dates being analyzed by FullCalendar.

**Expected result:** JavaScript goes through all visible days (only once) and adds events when needed.

**Wrong result** I get: JavaScript loop over days is very strange. It's a March currently, visible days are 26.02 - 08.04. How javascript goes through days:

**1.** 26.02
**2.** 26.02, 27.02
**3.** 26.02, 27.02, 28.02
**4.** 26.02, 27.02, 28.02, 01.03
**5.** 26.02, 27.02, 28.02, 01.03, 02.03
...
**N.** 26.02, ... , 07.04
**M.** 26.02, ... , 07.04, 08.04

You see the issue. If my math is correct - there are **903** iterations instead of **42**. Could you fix it please? Creating new events will happen ~20 times faster.

If there already exist repeating events in a current view, like here - https://jsfiddle.net/8bq3fw79/20/ - in addition to the previous big loop, JavaScript also loops through possible days for existing event, and also many multiple times.

Result - adding new events is very slow, and with many existing events it will be extremely slow.

**Comment by acerix** [comment]
Thanks for the report. I also made this demo to test and can see 903 renders when it should be one per day (for each occurence of the event).

https://codepen.io/anon/pen/GxyJaK?editors=0011

**Comment by arshaw** [comment]
in v5, it only renders 42 times!
https://codepen.io/arshaw/pen/qBbjexy?editable=true&editors=001
