### ISSUE TITLE
start in validRange not display fullcalendar?

### ISSUE THREAD

**Issue by namkidd** [fullcalendar/fullcalendar#4129]
I have :
<div class="show-schedule"></div>
<input id="start-at" type="date">
JS:

$('#start-at').change(function(){
  from_date = moment($('#start-at').val(), "YYYY-MM-DD"); 
  if (from_date._i.length != 0){
    $('.show-schedule').fullCalendar('option', 'validRange', {start: from_date}); 
  } 
}); 
For example: this month is March, if I choose January or February, I will not show me January or February, forcing me to press the PREV button to display it! How do I show last month without pressing the PREV button? Please help me !!

**Comment by acerix** [comment]
Would you be able to post a [runnable, stripped-down demonstration of the bug](http://fullcalendar.io/wiki/Reduced-Test-Cases/)? Would really appreciate it because the time saved reproducing will be time spent fixing.
