### ISSUE TITLE
Header buttons localization

### ISSUE THREAD

**Issue by IvanPoida** [fullcalendar/fullcalendar#4133]
Hello!
I've little bit stuck on localization of calendar.

The translations of months and days names works fine but for some reason navigation buttons like
"today, month, week" are not translatable.

Could you please check if smth wrong on my example?

https://codesandbox.io/s/2vx4m7po9r

**Comment by acerix** [comment]
Some translations might be missing, but I tested those is your example and it seems fine:

https://codepen.io/anon/pen/vRaWZW?&editors=001

Did you try with the latest versions? It could be the translations were added since the version you are using.

**Comment by IvanPoida** [comment]
Yes the problem was, that I've used 'moment/min/locales.min' as localization file and the one is needed is 'fullcalendar/3.9.0/locale-all.js'.

Thanks for your help!

**Comment by alexandrebarbaruiva** [comment]
@IvanPoida how did you set to 'fullcalendar/3.9.0/locale-all.js' instead of 'moment/min/locales.min'?

**Comment by iulianba** [comment]
> @IvanPoida how did you set to 'fullcalendar/3.9.0/locale-all.js' instead of 'moment/min/locales.min'?

If you don`t embed locales-all.js, I guess it takes required info from moment locale. 

Just embed "core/locales-all.js" and you should be fine.
