### ISSUE TITLE
is Can Showing event per line into basic type

### ISSUE THREAD

**Issue by Zerglrisk** [fullcalendar/fullcalendar#4134]
### Bug Reports
You MUST have a JSBin recreation, or else your issue will be CLOSED without explanation.
Instructions: http://fullcalendar.io/wiki/Reporting-Bugs/

### Feature Requests
Search the issue tracker for an existing ticket before creating a new one.
Instructions: http://fullcalendar.io/wiki/Requesting-Features/

(Please erase the above text and begin typing. Thanks!)
i want to render only 1 event each line. likes picture.
in image, it has 2018-04-09 ~ 2018-04-10 event next 2018-04-11 ~ 2014-04-16 event on one line.
i wanna move 2018-04-11 ~ 2014-04-16 event  to bottom  for one line only exist one event.
![111](https://user-images.githubusercontent.com/8271831/38349711-48887e3c-38e3-11e8-950c-9abfdb5641ae.png)
![333](https://user-images.githubusercontent.com/8271831/38349982-53250eea-38e4-11e8-8349-b12900f655a1.png)

sry my bad english. :)

how can i do that?

i want to showing like this
![222](https://user-images.githubusercontent.com/8271831/38349913-243a14fe-38e4-11e8-9b98-db68c4699255.png)

**Comment by Zerglrisk** [comment]
i try to moving after event all render but its complicate cuz it has row span anywhere. so i thought if fc-not-end event render to bottom. so i use eventOrder: "end". it doesn't happen reason is when rendering event fc-not-end event rendering first i think. 
anyway how can i render has fc-not-end (isEnd = true) event

**Comment by acerix** [comment]
I can't think of a good way to get that look other than having that feature built-in.  I'm not sure what you are asking regarding the event end, would you be able to post a [runnable, stripped-down demonstration of the bug](http://fullcalendar.io/wiki/Reduced-Test-Cases/)?
