### ISSUE TITLE
Popover

### ISSUE THREAD

**Issue by OuTseries** [fullcalendar/fullcalendar#4138]
Anyone can show me a eventRender popover example.
I'm doing this : 

     `eventRender(details) {
       var element = details.element;
       var event = details.event;
       if (element.hasClass('fc-day-grid-event')) {
          element.data('content', event.description);
          element.data('placement', 'top');
          (mApp.initPopover($(element));
      } else if (element.hasClass('fc-time-grid-event')) {
        element.find('.fc-title').append('<div class="fc-description">' + event.description + '</div>');
      } else if (element.find('.fc-list-item-title').lenght !== 0) {
        element.find('.fc-list-item-title').append('<div class="fc-description">' + event.description + '</div>');
      }`

and the mApp.initPopover is : 

    `var initPopover = function(el) {
        var skin = el.data('skin') ? 'm-popover--skin-' + el.data('skin') : '';
        var triggerValue = el.data('trigger') ? el.data('trigger') : 'hover';
            
        el.popover({
            trigger: triggerValue,
            template: '\
            <div class="m-popover ' + skin + ' popover" role="tooltip">\
                <div class="arrow"></div>\
                <h3 class="popover-header"></h3>\
                <div class="popover-body"></div>\
            </div>'
        });
    }`

There is no error on the console but the popover does not appear. Any thoughts?

**Comment by acerix** [comment]
Would you be able to post a [runnable, stripped-down demonstration of the bug](http://fullcalendar.io/wiki/Reduced-Test-Cases/)? Would really appreciate it because the time saved reproducing will be time spent fixing.

**Comment by OuTseries** [comment]
well, i changed to the jquery "native" fullcalendar and it works fine. seems the problem is that ng-fullcalendar eventRender is returning a jquery element that isnt recognized on the el.popover() function

**Comment by acerix** [comment]
Thanks for the update, so it sounds the issue is specific to ng-fullcalendar.
