### ISSUE TITLE
eventMouseOver change color, can't find DOM element for other events sharing the same id or value of property.

### ISSUE THREAD

**Issue by urmamb** [fullcalendar/fullcalendar#4139]
I am trying to change the color of those events which are sharing the same id or value of property. 

I can print an array of all the properties of these same events in eventMouseOver but i am unable to find there DOM elements. $(this) only refer to the mouseover event.

I also tried to update eventColor and it changes in the property of event but no effect on front end even after `updateEvent`. If i try to use `renderEvents` it change divide the event in 2pieces( one original and other with the color change) and then after each mouseover it goes on but all this happen with just one event among 3 same events. I am Detecting all same event using 'WID' and adding color and class to see the effect but no luck. The following is the array of one of the same event object but i don't know how to find a DOM element through this.

    {…}
    WID: "2"
    _id: "_fc49"
    allDay: false
    className: "sameevent"
    color: ""
    description: "COLPISOLE"
    end: Object { _isAMomentObject: true, _i: "2018-04-07 15:30:00", _f: "YYYY-MM-DD HH:mm:ss", … }
    eventColor: "#000"
    resourceId: "d"
    resourceIds: null
    source: Object { calendar: {…}, uid: "1", url: "/loadevents.php", … }
    start: Object { _isAMomentObject: true, _i: "2018-04-07 15:00:00", _f: "YYYY-MM-DD HH:mm:ss", …}
    title: "client 3"
    __proto__: Object { … }

The printed abject above has the class name 'sameevent' this means that properties are updated but rendering didn't took place. 

That will be a lot more easier if i can get a DOM element for each event and apply a class to them. 

    eventMouseOver:function( event, jsEvent, view ) {
			var newColor = "#000";
                         var sameEvents = $("#calendar").fullCalendar('clientEvents', function(e) { 
				return e.id=== event.id
			});
			$.each(sameEvents, function(x){
				if (event.id== sameEvents[x].id) {
					sameEvents[x].eventColor = newColor;
					sameEvents[x].className = 'sameevent';
					eventCount += 1;
					// console.log(sameEvents);
					calendar.fullCalendar( 'updateEvent', sameEvents);
					// renderEv(newData);
				}
			});
		},

In `renderEv()` i am firing for once, one or the other
    calendar.fullCalendar( 'updateEvent', array);
    calendar.fullCalendar( 'renderEvents', array);

**Comment by acerix** [comment]
Would you be able to post a [runnable, stripped-down demonstration of the bug](http://fullcalendar.io/wiki/Reduced-Test-Cases/)? Would really appreciate it because the time saved reproducing will be time spent fixing.

**Comment by urmamb** [comment]
Yes. here is a runnable demonstration. [PIN](https://codepen.io/urmamb/pen/vRbVYe)

It is also related to this bug [#4141](https://github.com/fullcalendar/fullcalendar/issues/4141)

**Comment by acerix** [comment]
Thanks, didn't notice it was the same code.  

I tested with `this` and it is the DOM element as it should be:

https://codepen.io/acerix/pen/bvywVE?editors=0010

`this` won't work after calling `updateEvents` though, because the DOM element is replaced when the event is rendered.  You might want to change the color in [eventAfterRender](https://fullcalendar.io/docs/eventAfterRender) instead.

**Comment by urmamb** [comment]
`eventAfterRender` is a callback and i don't have any logic to assign different classes to the different groups of the same clients for hover effect. How on eventMouseOver i can call `eventAfterRender`.

**Comment by acerix** [comment]
In `eventMouseOver` you would set some property on the event, eg. `event.isActive = true`, then in `eventAfterRender` would check the value of `isActive` and change the class if it is true.
