### ISSUE TITLE
Current time indicator in agenda views

### ISSUE THREAD

**Issue by arshaw** [fullcalendar/fullcalendar#414]
Originally reported on Google Code with ID 143
```
- would it be possible to have a "current time" indicator (red line and red
arrow) in the agenda views?

see file attached

```

Reported by `stefan.kilp@gmx.net` on 2009-10-23 06:57:58

<hr>
 * *Attachment: Bild2Fullcalendar.png<br>![Bild2Fullcalendar.png](https://storage.googleapis.com/google-code-attachments/fullcalendar/issue-143/comment-0/Bild2Fullcalendar.png)*

Imported with **57** stars.

**Comment by vakeeel** [comment]
Is this functionality in a released version yet? I see comments indicating that the 2.2.3 has it but this issue has not been closed and so was unsure.

**Comment by arshaw** [comment]
@vakeeel this has not yet been implemented

**Comment by vakeeel** [comment]
@arshaw is there an estimate on when this will be available. I will need to mark the code I am writing now to be removed. Thank you!!

**Comment by arshaw** [comment]
actively working on it and should be out before the new year or shortly after

**Comment by tobia** [comment]
Awesome, thanks a lot!

**Comment by arshaw** [comment]
release in v2.6.0
http://fullcalendar.io/docs/current_date/nowIndicator/

**Comment by kruglyjmax** [comment]
Thank you so much
