### ISSUE TITLE
Cannot read property 'build' of undefined

### ISSUE THREAD

**Issue by fizdalf** [fullcalendar/fullcalendar#4140]
I have not been able to reproduce the bug, but I can give a sentry bug report, that might help find out more about the problem

[Sentry Bug Report](https://sentry.io/share/issue/0d3be973e2de46c1ae8d03873659084f/)

I have to say this is the first time ever I've encountered this issue, but unfortunately I didn't get feedback from the user to know more.

**Comment by acerix** [comment]
It's hard to know where the issue might be without a way to reproduce it.  Do you know if the error happened in the latest version?

**Comment by fizdalf** [comment]
it did happen with the latest version

**Comment by acerix** [comment]
If there is still a bug, please submit a [runnable, stripped-down demonstration](http://fullcalendar.io/wiki/Reduced-Test-Cases/).
