### ISSUE TITLE
Bug in doc for Custom View

### ISSUE THREAD

**Issue by Kypaz** [fullcalendar/fullcalendar#4146]
https://fullcalendar.io/docs/custom-view-with-js

![screenshot from 2018-04-12 15-26-06](https://user-images.githubusercontent.com/6717752/38680030-9455e124-3e65-11e8-80ab-fb20e2ae671c.png)

It should be ``this.triggerViewDestroy();`` instead of  ``View.prototype.destroy.apply(this, arguments);``

**Comment by acerix** [comment]
Thanks for the report.  I'm not sure of the basis for this change, is it because the code more simple?

**Comment by arshaw** [comment]
I see this now. The destroy method was rename to `removeElement` a little while ago, but seems that I did not attempt to make it backwards-compat. Will address this in the next release.

**Comment by arshaw** [comment]
i won't fix this in v3, but i WILL fix this in the v3 docs

**Comment by arshaw** [comment]
clarified in docs
