### ISSUE TITLE
[alpha1] Set event listeners passive

### ISSUE THREAD

**Issue by frlinw** [fullcalendar/fullcalendar#4149]
### Improvment

Chrome suggestion:

> [Violation] Added non-passive event listener to a scroll-blocking 'touchstart' event. Consider marking event handler as 'passive' to make the page more responsive. See https://www.chromestatus.com/feature/5745543795965952

This message appears at init and point to : 
- https://github.com/fullcalendar/fullcalendar/blob/v4.0.0-alpha/src/component/InteractiveDateComponent.ts#L95
- https://github.com/fullcalendar/fullcalendar/blob/v4.0.0-alpha/src/util/dom-event.ts#L63

These others listeners don't generate a warning at init (but potentially on a specific action ?):
- https://github.com/fullcalendar/fullcalendar/blob/v4.0.0-alpha/src/common/GlobalEmitter.ts#L89 (event: scroll)
- https://github.com/fullcalendar/fullcalendar/blob/v4.0.0-alpha/src/common/ListenerMixin.ts#L47 (event: ?)
- https://github.com/fullcalendar/fullcalendar/blob/v4.0.0-alpha/plugins/dragula/main.ts#L23 (event: touchstart)

**Comment by acerix** [comment]
Is there something that can be improved in the calendar? I get the same suggestion, but it seems to be referring only to jQuery code.

**Comment by frlinw** [comment]
Sorry for the lack of details, I'm talking about v4

**Comment by frlinw** [comment]
https://codepen.io/frlinw/pen/ELpaXB
- Open devtools console
- Enable Verbose log level
- Rerun the pen if needed
- There is 8 `[Violation] Added non-passive event listener to a scroll-blocking 'touchstart' event`

Note: toggle the selectable option cause warning as well

**Comment by arshaw** [comment]
fixed with c6d9636d2ecd8a0f4aae264cfe80feecf9a20025 and f3af2ca56501bd86b641068ca62bef3166bafe54 (not yet released)

**Comment by arshaw** [comment]
this has been addressed and released in [4.0.0-alpha.4](https://github.com/fullcalendar/fullcalendar/releases/tag/v4.0.0-alpha.4)

**Comment by arshaw** [comment]
[V4 was officially released a few days ago!](https://fullcalendar.io/blog/2019/03/v4-officially-released)
