### ISSUE TITLE
Make past dates not selectable

### ISSUE THREAD

**Issue by NashBridgesAT** [fullcalendar/fullcalendar#4152]
Hi
I need a way to prevent past dates from being selected. I've searched in the issue tracker but didn't find a solution. The only code i found so far, was:

```
dayRender: function(date, cell){
			nowDate=moment();
			if (date < nowDate){
				$(cell).addClass('disabled');
				console.log("C "+cell);
			}
		},
```
This option adds the class to the cells properly, but they can be selected anyway. The solutions working with the `select function` do not fit for me, because the cells can be selected though. I need the past date cells being not markable/selectable. Can you help me?

**Comment by JNPSoftware** [comment]
Hi @NashBridgesAT, try [validRange](https://fullcalendar.io/docs/validRange).

**Comment by NashBridgesAT** [comment]
Thanks for your reply!

I did. The problem with validRange is, that the dates are not only disabled, but completely hidden. The data should stay visible (the prev button should work as well) for documentation prupose, so validRange doesn't work for me i this case.

Christian :)

Am 16. April 2018 18:41:07 MESZ schrieb JNP Software de Franca Ltda <notifications@github.com>:
>Hi @NashBridgesAT, try
>[validRange](https://fullcalendar.io/docs/validRange).
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/fullcalendar/fullcalendar/issues/4152#issuecomment-381668855

-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.

**Comment by NashBridgesAT** [comment]
Finally i found a solution, which is not the best, but in fact it works:

`selectConstraint: {
        start: $.fullCalendar.moment().subtract(1, 'days'),
		end: $.fullCalendar.moment().startOf('year').add(100, 'year')
		},`

Unfortunately you have to set the `end` parameter, so this solution works for the next 100 years only... 
I suggest to change the sources related to accept the `start` parameter only in the next release.

**Comment by acerix** [comment]
You can control what is selectable using `selectAllow`, eg:

https://codepen.io/anon/pen/ZozZeG?editors=0011
