### ISSUE TITLE
Hide all events on given date

### ISSUE THREAD

**Issue by kveldscholten** [fullcalendar/fullcalendar#4153]
hi,
give it an option to hide all events on given date?

I have two events on 01.05 with dow[] event function but this day is an public holidy in Germany.
I would like to hide all events on this day.

i have found this code to add data-date to first event.
```
eventAfterAllRender: function (view) {
    var row, cell, date;

    // First iterate over each calendar row
    $('.fc-content-skeleton').each(function (i) {
        row = $(this);

        // Now iterate over each header cell within this row
        $('thead td', row).each(function (k) {
            cell = $(this);

            // Get the date attribute from the current thead td
            date = cell.data('date');

            // Find the matching tbody td, at the same index 'k'
            // as our current thead td, and add the data attribute.
            $('tbody td', row).eq(k).data('date', date);

            // Since the data attribute won't be visible in the source,
            // temporarily add the actual date to the cell to confirm
            // it is really working.  Remove this once you can see it works.
            $('tbody td', row).eq(k).html(date);
        });
    });
}
```
But the other events on this day dont have the data-date attr.
Do the events have a data-date so I could query all dates with data-date and hide accordingly

Thanks for help

**Comment by acerix** [comment]
There is not a built-in way to do that, and the hack you are trying gets a bit complicated for events which span more than one day, and for different views, etc.

For example, in this example, if the holiday is April 12, would you want the 3 events on that day not to show and the conference to show only on the 11th?

https://codepen.io/anon/pen/RybONj?editors=0010

The best way I can think to do that is to check the range of each event in `eventRender` and remove any time on that day from the event.  So, an event from Apr 11 at noon until Apr 13 at noon, you would change it to two events, one from Apr 11 noon until Apr 11 at midnight, and the other from Apr 12 midnight until Apr 13 at noon, so there would be a gap on Apr 12.

**Comment by kveldscholten** [comment]
Hi
i have edit your code
https://codepen.io/anon/pen/RybONj?editors=0010

i use repeating events with dow: [1,2]
```
      {
        title: 'Repeating Event',
        start: '17:00',
        end: '20:00',
        dow: [1,2]
      },
      {
        title: 'Repeating Break',
        start: '12:00',
        end: '12:30',
        dow: [1,2]
      },
      {
        title: 'Holiday Event',
        start: '2018-05-01'
      },
```

look for Repeating Break and Repeating Event

Now Mai 1 is an Public Holiday
i will not show other events on this day

**Comment by acerix** [comment]
Do you mean you want the repeating event to not show up on the holidays? For example, in your demo there would be nothing on May 1?

**Comment by kveldscholten** [comment]
Yes.

The dow[] function repeat the events every but i will not show events with dow funticion on holiday

**Comment by acerix** [comment]
Would it work to hide the elements in `eventRender`?

https://codepen.io/anon/pen/deogbW?editors=0010

**Comment by kveldscholten** [comment]
thx for help but this works for me

```
    eventRender: function( event, element, view ) {
      var eventStartString = event.start.format("YYYY-MM-DD"),
          holidayDates = ["2018-01-01", "2018-03-30", "2018-04-02", "2018-05-01", "2018-05-10", "2018-05-21", "2018-05-31", "2018-10-03", "2018-11-01", "2018-12-25", "2018-12-26"];

      if ($.inArray(eventStartString, holidayDates) > -1) {
        element.hide()
      }
    }
```

https://codepen.io/anon/pen/gzpNKp?editors=0010

**Comment by acerix** [comment]
Thanks for the code sample.
