### ISSUE TITLE
eventAfterAllRender not triggered if too much re-renders are fired consecutively

### ISSUE THREAD

**Issue by lmerotta** [fullcalendar/fullcalendar#4154]
Hi,

We are currently dealing with a situation where we frequently need to navigate between event sources. This means we need to delete all event sources present in the calendar, and immediately add new event sources.

The event sources we use are providing a URL to fullcalendar, so it can fetch events from an API.

Given this configuration, when we trigger `removeEventSources`, the `eventAfterAllRender` callback is called. However, when we (immediately) add a new event source, if the AJAX call that fullcalendar makes is too fast to respond, `eventAfterAllRender` is not called after rendering the new events.

Here is a codepen that shows the issue, by mocking a jQuery AJAX request: https://codepen.io/anon/pen/PeYqmP?editors=0011

**Comment by acerix** [comment]
Thanks for the report.  It seems to be ok in your demo, I always see the events showing on the 30th and no errors. What is happening in your demo that is not as expected?

**Comment by lmerotta** [comment]
Sorry, maybe I was not specific enough. I updated the Codepen with a mock for a loader we use. It's `show` and `hide` methods simply log to the Codepen's console and fade in/out a div. 

Since we use `setInterval` to call periodically `removeEventSources` and `addEventSource`, we should periodically see `loader.show()` and `loader.hide()` called in the console. However, the logging (and therefore the call to the methods) stops after the second call to `loader.show()`, while the interval is still running (can be seen via the `console.log('interval');` calle periodically). 

This means that the `loading` callback is fired twice, but `eventAfterAllRender` only once, which is problematic

**Comment by acerix** [comment]
It seems to be working as expected:

https://codepen.io/anon/pen/rvVZoB?editors=0010

`loading` should be called twice, `isLoading` is true when loading starts and false when done.

https://fullcalendar.io/docs/loading

`eventAfterAllRender` is called only after events are rendered, so it makes sense that it wouldn't be called if the loading is interrupted before the render. 

I think you could use just the `loading` callback, you would show your loader if `isLoading` is true, otherwise hide it.

**Comment by lmerotta** [comment]
It's working fine indeed. I was mislead because my dev environment was slower than the production one, and thus eventAfterAllRender was called twice (nothing interrupted the render).

Thank you for your help !
