### ISSUE TITLE
full calendar not showing slots before 10am

### ISSUE THREAD

**Issue by yakkalipavan** [fullcalendar/fullcalendar#4157]
i am working with fullcalendar in my frontend to display the time slots. I am sending json data to fullcalendar config and it is displaying all the time slots expet the time before 10 though the json data present.

`$('#calendar').fullCalendar({
            defaultView: 'agendaDay',
            defaultDate: $scope.today,
            schedulerLicenseKey: 'CC-Attribution-NonCommercial-NoDerivatives',
            header: {
                left: 'prev,next today',
                center: 'title',
                right: 'agendaDay,agendaWeek,month'
            },
            allDaySlot: false,
            eventClick: function (eventsFeed) {
                $scope.openApptDetails(eventsFeed);
            },
            minTime: "07:00:00",
            maxTime: "21:00:00",
            contentHeight: "auto",
            resources: resourcesFeed,
            events: eventsFeed
        });`
![capture](https://user-images.githubusercontent.com/3719268/39030018-ca0bee0c-4424-11e8-9819-107b3d8943bf.JPG)

I am using FullCalendar v3.6.1 

and sample json data

`{color:"green"
end:"2018-04-18T10:00:00"
resourceId:1
start:"2018-04-18T9:00:00"
studentName:""
title:"Available"
tutorName:""
type:""
}`

**Comment by acerix** [comment]
Would you be able to post a [runnable, stripped-down demonstration of the bug](http://fullcalendar.io/wiki/Reduced-Test-Cases/)? Would really appreciate it because the time saved reproducing will be time spent fixing.

**Comment by yakkalipavan** [comment]
Issue was resolved long ago, the issue is at string operation, didn't included the **0** in front of hours position.

Sorry for not closing the issue
