### ISSUE TITLE
Fullcalendar Timeline yearview with labels in cells and events

### ISSUE THREAD

**Issue by hamdipro** [fullcalendar/fullcalendar#4165]
Hello, 
i want to create a custom timeline view with 3 years view with cols(resources), 
but when i use "dayRender" method to override day rendering i am able just to modify the first resource row and all events are gone.

![image](https://user-images.githubusercontent.com/6583410/39256035-2f65be80-48ae-11e8-9591-69911a28322b.png)

example worked with : [https://codepen.io/anon/pen/zjBWJo?editors=0010](url)

**Comment by hamdipro** [comment]
I understand now the use of day render.
So, is there any other method to append text in all cells according to each resource ? 

PS : for the events i corrected the issue i was using cell.html instead of cell.append.

**Comment by acerix** [comment]
You would need to add DOM elements for each cell, either positioning them yourself, or you could add background events, eg:

https://codepen.io/anon/pen/qYaQdd?editors=0010
