### ISSUE TITLE
月视图时，时间所占天数的格数不正确；活动列表视图时，会将天数不对应。

### ISSUE THREAD

**Issue by az6161311** [fullcalendar/fullcalendar#4168]
选择开始时间为 2017-10-31 01:00 结束日期为 2017-11-02 02:10
理论上在 月视图 中 应该所占天数的是为 2017-10-31，2017-11-01，2017-11-02 三天，实际却是两天。
而在  活动列表 中 应该是 【2017-10-31 01:00-00:00】 , 【2017-11-01  00:00-00:00】【2017-11-02 00:00 -02:10】  实际却是 【2017-10-31 01:00-00:00】 , 【2017-11-01 00:00 -02:10】 
这样完全是不正确的呀。

**Comment by az6161311** [comment]
FullCalendar v1.6.4 是【月视图】正常的

**Comment by acerix** [comment]
Would you be able to post a [runnable, stripped-down demonstration of the bug](http://fullcalendar.io/wiki/Reduced-Test-Cases/)? Would really appreciate it because the time saved reproducing will be time spent fixing.  Also please submit your ticket in English so we can understand better.

**Comment by az6161311** [comment]
@acerix https://codepen.io/az6161311/pen/JvNMmX?editors=0010 
In the example, "Meeting2" and "meeting1" have the same date, but the time is different, but there are different formats in [month], [listWeek]

**Comment by az6161311** [comment]
@acerix  It seems that the problems I encountered are the same.
 https://github.com/fullcalendar/fullcalendar/issues/4170
 ` nextDayThreshold ` set  "00:00" 
This solves the problem.
thank you!!!
