### ISSUE TITLE
How to create an all day repeating event?

### ISSUE THREAD

**Issue by imilo** [fullcalendar/fullcalendar#4173]
Hello!

In short - how to create an all day repeating event?

As I see at the moment - with **dow[]** we can create repeating events, but then Date is ignored - we have to set start/end times (not full dates) to make this working. If both **start** and **end** times are **00:00:00** - we get an invalid event. If I replace the **end** time with **23:59:00** - I get a 24H long object in a week view instead of a single small element in a "all-day" area.

Adding **allDay = true** doesn't help.

Is there an existing way to create an all day repeating event? If not - what do you think about an idea: if **event.start == event.end == "00:00:00"** then place this event in the "all-day" area?

**Comment by acerix** [comment]
Thanks for the report.

`dow` is not documented as an event property, but I would expect it to work for allDay events since it works for events with a start/end time, as you described:

https://codepen.io/acerix/pen/vjJKrP?editors=0010

To make a repeating event currently, you could create an event for each day and link them by using the same `id`.

**Comment by imilo** [comment]
Thanks for confirmation. Pure JavaScript workaround, but for the regular clicking users it will be difficult to follow ID's, and I believe a event creation forms won't contain a custom ID field.

What do you think about placing an event in the "all-day" area when **event.start == event.end == "00:00:00"** ?

**Comment by arshaw** [comment]
im planning on having true recurring event support in v4, with a plugin that hooks into this: https://github.com/jakubroztocil/rrule

right now, the `dow` event property was not meant to be exposed, and recurring events were not meant to be part of the public API, but people found a way. thus, the bugs

**Comment by arshaw** [comment]
an rrule plugin was released in v4!
