### ISSUE TITLE
Calendar locale not used in all moments objects. 

### ISSUE THREAD

**Issue by obeal** [fullcalendar/fullcalendar#4174]
The issue is very easy to understand. 
I define a locale for my calendar, let's say 'fr'.
I handle the  eventClick handler to handle events selection and the select handler to handle dates selection. 
For the events selection, the EventObject start is a moment object with the right locale: 'fr'.
For the dates selection, the start object is a moment object with the wrong locale: 'en'.
I haven't done a full test of all moment objects returned by methods of the calendar, just seen this specific case. 

    function initCalendar() {
      $('div #calendar').fullCalendar({
        header: {
          left: 'month,listWeek',
          center: 'title',
          right:  'today prev,next'
        },
        defaultView: 'month',
        locale: 'fr',
        selectable: true, 
        timezone: 'Europe/France',
        weekends: true,
        eventLimit: true, 
        views: {
          month: {
            eventLimit: 4
          }
        },
        eventClick: function(event) {
          console.error(event.start.format("dddd, DD/MM/YYYY, h:mm"));
        },
        select: function(startDate, endDate) {
          console.error(startDate.format("dddd, DD/MM/YYYY, h:mm"));
        }
      });
    }

**Comment by acerix** [comment]
Thanks for the report.  Makes sense that it should be consistent, here's a demo:

https://codepen.io/acerix/pen/MGvexv?editors=0011

**Comment by arshaw** [comment]
released in [3.10.0](https://github.com/fullcalendar/fullcalendar/releases/tag/v3.10.0)
