### ISSUE TITLE
There is no option for modifying view to have days on y axis and times on x axis in agendaWeek view

### ISSUE THREAD

**Issue by VenkatBaddi** [fullcalendar/fullcalendar#4176]
My Issue is very simple. But not available that view option in fullcalendar. 
I have to show my calendar like below (Hrs in X-axis and dates in Y-axis in week view)
![img_03052018_085955_0](https://user-images.githubusercontent.com/19591769/39619871-ec537eca-4fa6-11e8-881a-5e196f951025.jpg)

So please give me solution for this.
Is there any option to handle jquerty or any other?

**Comment by acerix** [comment]
We could look at adding a view like that as a new feature but the closest built-in view currently is `timelineWeek`.  You should be able to do something like that with a custom view:

https://fullcalendar.io/docs/custom-view-with-js
