### ISSUE TITLE
v3.9.0 not working at all with Google Calendar

### ISSUE THREAD

**Issue by RockGuitarist1** [fullcalendar/fullcalendar#4179]
I can't get my Google Calendar to come up at all. Seems that everything fullcalendar is breaking before the actual call for fullCalendar().

Edit: I followed the documentation on fullcalendar's website and looked at the Google Calendar integration that does work on the site to copy my code.

### Bug Reports
- Uncaught TypeError: Cannot read property 'push' of undefined.
- Uncaught TypeError: Cannot read property 'EventSource' of undefined.
- Uncaught TypeError: $(...).fullCalendar is not a function.

Here is a Plunker: https://plnkr.co/edit/ZihCrb5mv2LViE3KeXqx?p=preview

**Comment by arshaw** [comment]
this version of FC requires moment.js version 2.9.0 or above, and you are using version 2.1.0. hope that helps

**Comment by RockGuitarist1** [comment]
Yep! That's exactly what it was. I guess I missed it in the docs. Thanks!
