### ISSUE TITLE
Month view Event display

### ISSUE THREAD

**Issue by sairamchinna** [fullcalendar/fullcalendar#4182]
Hi,

am using fullcalendar in my local system. i have events with start & end datetime, So am getting issue in only month view to display the events, this issue is not coming up week and day calendar(view). 
I have event in calendar with event name - "
                              {
					title: 'Long Event',
					start: '2014-06-18T06:30:00',
					end: '2014-06-20T07:30:00'
				},
Please check the below link,How can i solve this issue without effect any day & weekly views. Please update me ASAP.

http://jsfiddle.net/sairamchinna1243/jso51pm6/1870/

**Comment by arshaw** [comment]
looks fine to me. what do you expect to see that you aren't seeing?
