### ISSUE TITLE
Causes highlight.js to not work

### ISSUE THREAD

**Issue by chrisx84** [fullcalendar/fullcalendar#4188]
No matter what i did i cant have fullcalendar and highlight.js working at the same time.
I have put the required import for fullcalendar on the page itself where my calendar is, fc wont load.
Put the import in my own js file, highlight wont load.
Thought you guys want to know this. Hope there is a fix for it because i do like both fc and highlight.js

**Comment by acerix** [comment]
Would you be able to post a [runnable, stripped-down demonstration of the bug](http://fullcalendar.io/wiki/Reduced-Test-Cases/)? Would really appreciate it because the time saved reproducing will be time spent fixing.

**Comment by chrisx84** [comment]
sorry i don't really know all these advance dev stuff, i just old code php. you can see what i mean at https://gridplay.net/calendar at the bottom of the calendar the iframe tag should be in colour using highlight.js but calendar is somehow preventing highlight to work.

**Comment by acerix** [comment]
I tested with highlight.js and they work fine together:
