### ISSUE TITLE
updateEvent: className property bug

### ISSUE THREAD

**Issue by littlehawk** [fullcalendar/fullcalendar#4189]
Hi @arshaw! 

According with the documentation, the className property of the event can be a string (class) or array of classes that will be attached to the event.

But "updateEvent" function accept **ONLY** an array.
If a string is passed, fullcalendar respond with the following error:
`TypeError: second argument to Function.prototype.apply must be an array`

P.S.: This time, before entering this issue, I carefully checked my code ;)

**Comment by arshaw** [comment]
yes, you are correct. I'm going to hold off on fixing this because in v4, update an event will be done differently (via methods of an event object). as I'm sure you figured out, for now, just make sure it's an array

**Comment by arshaw** [comment]
in v4, if you call `setProp('classNames', whatever)`, it will accept a string OR an array.

more info: https://fullcalendar.io/docs/v4/Event-setProp

i might add .addClassName and .removeClassName methods to the Event class but not sure

**Comment by arshaw** [comment]
I'm closing this issue to signify that it's implemented (since v4-alpha2). I'll comment on this thread again when v4 is officially released.

NOTE TO SELF: this should be documented in the Release Notes

**Comment by arshaw** [comment]
https://github.com/fullcalendar/fullcalendar/issues/4189#issuecomment-449907483

**Comment by arshaw** [comment]
[V4 was officially released a few days ago!](https://fullcalendar.io/blog/2019/03/v4-officially-released)
