### ISSUE TITLE
Date bug on FullCalendar

### ISSUE THREAD

**Issue by Devcorns** [fullcalendar/fullcalendar#4191]
when we select 31/12/2017 to 2/1/2018
it shows correct event date on graph but when we get that date, it increases date by 1

**Comment by acerix** [comment]
Would you be able to post a [runnable, stripped-down demonstration of the bug](http://fullcalendar.io/wiki/Reduced-Test-Cases/)? Would really appreciate it because the time saved reproducing will be time spent fixing.
