### ISSUE TITLE
Request: Copy event

### ISSUE THREAD

**Issue by breden** [fullcalendar/fullcalendar#4194]
Hello, I will implement a fullcalender to a company I work for. I would love to have a feature that could copy an event (maybe hold down Shift). In my case a externally drop an event. Do all the settings for that event for Monday. (title, start, end, project nr etc). Then I want to copy the event to tuesday, wednesday and friday,

![dragcopy](https://user-images.githubusercontent.com/15260884/40574059-e596d7cc-60cb-11e8-97d9-56edfc448152.png)

**Comment by acerix** [comment]
You can check if Shift is being held in `eventDrop` and create a copy of the event if it is.  Please give more specifics if you are looking for a new feature.

**Comment by breden** [comment]
How Will the code look like?
