### ISSUE TITLE
Doc : searchable feature

### ISSUE THREAD

**Issue by maieul** [fullcalendar/fullcalendar#4196]
It would be very useful to add a search form in the doc, for example if we need to find the details about a specific settings.

**Comment by acerix** [comment]
Thanks for the suggestion, agree a content search would be nice.  I use [google](https://www.google.com/search?q=site%3Afullcalendar.io+timelineYear) when I need find something specific.

**Comment by starkipraggy** [comment]
It's crazy that that the best way to search the fullcalendar docs is to google it. Hoping this gets implemented for v5

**Comment by koosvanderkolk** [comment]
The ways these guys handle their documentation could be a nice example: https://datatables.net/reference/event/

**Comment by pjdevries** [comment]
I second the request for a documentation search function. The documentation is extensive, which is much appreciated. However, many times I'm quite sure a feature is available somewhere, but it's not always obvious where to look for it.

**Comment by OwenPattison** [comment]
@acerix the google tip is useful so thank you for that, however, I do feel there should be a search function within the documentation as this workaround is nonintuitive. I've become frustrated when trying to find props as I try to understand a previously implemented solution on multiple occasions.

**Comment by fre2mansur** [comment]
Google gives the result from all the versions, sometime we need to check the version selector, it would be great if you have search contented to specific version.

**Comment by shelomito12** [comment]
when?

**Comment by arshaw** [comment]
This is now implemented. See the search bar at the top of all docs pages:
https://fullcalendar.io/docs

The results are constrained by the version of the current page.

Please write here if there are any issues.
