### ISSUE TITLE
Infinite loop on view re-declaration

### ISSUE THREAD

**Issue by Fohlen** [fullcalendar/fullcalendar#4198]
If you define a view with a name and type of an existing view, fullcalendar will cause an infinite loop, eventually leading the browser tab to crash.
Producing a codepen is a bit tricky, but here it is. https://codepen.io/anon/pen/ERxXwN?&editors=001
Beware that this will definitely crash your browser (tab).
My sample code here is:

```
views: {
    month: {
        type: 'month'
    }
}
```

**Comment by acerix** [comment]
Thanks for the report, definitely crashing my browsers.

**Comment by arshaw** [comment]
This was fixed in 4.3.0 though please start using 4.3.1
Releases: https://github.com/fullcalendar/fullcalendar/releases

An error is now thrown in this case. No more crashing.
