### ISSUE TITLE
Display wrong time on weekend

### ISSUE THREAD

**Issue by tranvan538** [fullcalendar/fullcalendar#4200]
### Bug Reports
I found a bug which display wrong time on weekend. Please see the attached gif file for more info.

Before drag:
May 31: 9-24h
June 1: 24h-13h

After drag:
June 2: 9h30-13h30
June 3: 9h30-13h30

I thought the correct time will be:
June 2: 9h30-24h
June 3: 24h-13h30

![display_time_bug](https://user-images.githubusercontent.com/11737226/40770110-f51a2476-64e3-11e8-8b40-9a49e2010066.gif)

regard.

**Comment by acerix** [comment]
Would you be able to post a [runnable, stripped-down demonstration of the bug](http://fullcalendar.io/wiki/Reduced-Test-Cases/)? Would really appreciate it because the time saved reproducing will be time spent fixing.

**Comment by tranvan538** [comment]
I haven't code anything yet. Simply drap and drop event on demo at https://fullcalendar.io/ :)
Thanks for quick reply

**Comment by acerix** [comment]
Thanks for the report.  So, if I understand, if you start with a day long event that starts in the middle of Friday and drag it to Saturday, it shows the end time on Sunday, when it should show midnight (end time on Saturday).

**Comment by arshaw** [comment]
this is no longer an issue in v5
