### ISSUE TITLE
Prev button doesn't work when previous days are hidden by hiddenDays and dayCount is greater than dateIncrement

### ISSUE THREAD

**Issue by acerix** [fullcalendar/fullcalendar#4202]
https://codepen.io/anon/pen/PaPbqM?editors=0010

Click `Prev` a few times, it stops working when the previous day is Sunday.

Reported in https://fullcalendar.freshdesk.com/a/tickets/325

**Comment by arshaw** [comment]
i've made the fix: https://github.com/fullcalendar/fullcalendar/commit/2c778ad48ae6aff5a37c996645656c4a242e0bdd

though it's not yet released in an official release. that will happen mid-week.

you can use the fullcalendar(.min).js files in this zip:
[fullcalendar-0.0.0.zip](https://github.com/fullcalendar/fullcalendar/files/2088591/fullcalendar-0.0.0.zip)

**Comment by arshaw** [comment]
released in [3.10.0](https://github.com/fullcalendar/fullcalendar/releases/tag/v3.10.0)
