### ISSUE TITLE
'googleCalendarApiKey' does not exist in type 'OptionsInput'.

### ISSUE THREAD

**Issue by RockGuitarist1** [fullcalendar/fullcalendar#4205]
Whenever using FullCalendar v3 with Angular <=6, you get the following error:

`googleCalendarApiKey does not exist in the model OptionsInput`

For example: 

```
$('#calendar').fullCalendar({
      themeSystem: 'bootstrap4',
      header: {
        left: $(window).width() <= 576 ? null : 'prev,next today',
        center: 'title',
        right: $(window).width() <= 576 ? null : 'month,agendaWeek,agendaDay,listMonth'
      },
      defaultView: $(window).width() <= 576 ? 'listMonth' : 'month',
      googleCalendarApiKey: 'myApiKey', //error
      events: 'myGmail',
      eventLimit: true,
      eventClick: function (event) {
        window.open(event.url, 'gcalevent', 'width=700,height=600');
        return false;
      }
    });
```

Typescript will complain that googleCalendarApiKey does not exist in type OptionsInput, which is actually OptionsInputBase.

Adding `googleCalendarApiKey?: string;` to the interface OptionsInputBase inside of `fullcalendar.d.ts` fixes this issue. This issue will currently prevent any app from building.

**Comment by acerix** [comment]
This would be fixed in v4, that option is now defined here: 

https://github.com/fullcalendar/fullcalendar/blob/44c16bb687c911318306f1c1d0e05bfb186cc9a7/packages/google-calendar/src/main.ts#L8
