### ISSUE TITLE
Event Limit is not working as it should

### ISSUE THREAD

**Issue by ovidiua2003** [fullcalendar/fullcalendar#4206]
https://codepen.io/ovidash/pen/dKMaYV

The codepen above is duplicated off the official demo for event limit as seen here https://fullcalendar.io/docs/eventLimit

The problem is that if i have N events and i set a limit to, say 2, I logically expect to see 2 events followed by + (n-2) more. Right? Wrong. Your code only shows 1 event and + (n-1) more, which I believe i know why but here's the kicker. If I have a situation where I have 2 events on a day plus another day with 3 events, and i want to limit the view to 1, only the + x more apppears.

If i increase the limit to 2, i see 2 events where there are only 2, and where there's 3 i see 1 event + 2 more.

This is absurd.

**Comment by medero** [comment]
Agreed and there's actually a similar issue and a comment about a fix for this: https://github.com/fullcalendar/fullcalendar/issues/3035#issuecomment-356582132

**Comment by ovidiua2003** [comment]
Sorry for the dupe. I actually searched but I surely missed it
