### ISSUE TITLE
Event Duplicate

### ISSUE THREAD

**Issue by dhanabalanc** [fullcalendar/fullcalendar#4209]
Hi,

In full calendar, while clicking more option, **Event has been duplicated in popup**. 
Pls do help.

![eventlimit-duplicate](https://user-images.githubusercontent.com/1265096/41100185-4afc1954-6a7e-11e8-90d4-6536ef2a2ae0.png)
Regards,
Dhanabalan.cs

**Comment by acerix** [comment]
Would you be able to post a [runnable, stripped-down demonstration of the bug](http://fullcalendar.io/wiki/Reduced-Test-Cases/)? Would really appreciate it because the time saved reproducing will be time spent fixing.

**Comment by mikevolmar** [comment]
I have also experienced this issue and have posted on stackoverflow about it here https://stackoverflow.com/questions/56385284/fullcalendar-fc-more-shows-lots-of-duplicates-in-popup
My guess is that it is related to events whose start and end dates are longer than several days. I'm currently working on trying to remove the duplicates passed by eventFootprintToSegs: function(eventFootprint, constraintRange) at line 5217 to resliceDaySegs: function(segs, dayDate) at about line 8390.
