### ISSUE TITLE
Feature Request: FullCalendar v4.0.0 as Angular Component

### ISSUE THREAD

**Issue by trevormaliborski** [fullcalendar/fullcalendar#4212]
**Hello!**

I'm currently trying to utilize FullCalendar v4.0.0 in an Angular application. What's problematic is that, as far as I know, this new version of FullCalendar which removes jQuery as a dependency doesn't have an Angular wrapper available.

What I would like is to have Full Calendar v4 as an Angular Component. Is there a compatible wrapper available or will one be made available soon?

Thanks,
Trevor Maliborski

**Comment by acerix** [comment]
It don't know of any wrappers updated to 4.0 yet.  There's already a request open to add Angular support:

https://github.com/fullcalendar/fullcalendar-scheduler/issues/11
↑
Could you please visit the link, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates?
