### ISSUE TITLE
Missing the last day in listview, multiday events

### ISSUE THREAD

**Issue by jonbo679** [fullcalendar/fullcalendar#4214]
Can be reproduced in the demo at main page. https://fullcalendar.io/

- Drag an event in week view so it spans multiple days
- Make sure it ends before 9:00am the last day
- Look at the event in list view

When I do the above the last day is missing from the multiday event in list view. It looks fine when the event ends at 9:00 am or later but when I end it earlier one day disappear in list view. 

I am sitting in Sweden with the timezone CET (+1). It might or might not have something to do with the issue.

**Comment by acerix** [comment]
The `nextDayThreshold` setting hides events starting after 9 am by default:

https://fullcalendar.io/docs/nextDayThreshold

**Comment by coreboarder** [comment]
Just a thought. Is there any way that somebody could put a clear example up on how to format events that span multiple days? The documentation is clearly not clear enough if you look through StackOverflow etc. and would hep this project be a bit less frustrating to utilize.
