### ISSUE TITLE
Can't get "prev" and "next" button text to display with "bootstrap4" theme system

### ISSUE THREAD

**Issue by tfuda** [fullcalendar/fullcalendar#4216]
I'm trying to render a calendar with the "buttonIcons" option set to false, so that the previous and next buttons contain text instead of the < > icons. It works fine with the default theme, however, when I apply the "bootstrap4" themeSystem option, I get buttons with neither text nor icons. This can easily be demonstrated via this JSBin: http://jsbin.com/cetuyiz/2/edit?html,css,js,output. Uncomment the "themeSystem" option, and you will see the "prev" and "next" text disappear. In looking at the generated markup, it looks like it's still trying to render the chevrons, rather than the button text. And by the way, the chevrons don't appear either.

**Comment by acerix** [comment]
You need to include fontawesome for bootstrap4, see https://fullcalendar.io/docs/themeSystem.

Eg:
https://use.fontawesome.com/releases/v5.0.13/css/all.css

**Comment by tfuda** [comment]
Wait though... that solves the problem of the < > not rendering. However, if I set buttonIcons: false, it's supposed to render "prev" and "next" buttons instead of < >. That's still not happening.

**Comment by arshaw** [comment]
problem still in v5: https://codepen.io/arshaw/pen/ExPXqOL?editable=true&editors=001
