### ISSUE TITLE
visibleRange doesnt work on timelineMonth

### ISSUE THREAD

**Issue by AlexisVidal** [fullcalendar/fullcalendar#4217]
i have some issue withe timelineMonth, trying to set visibleRange but it not working
here is my code:

_var newDate = new moment($(this).data('date'));
var calendar = $('#calendar').fullCalendar({
                    selectable: true,
                    contentHeight: 500,
                    aspectRation: 1.35,
                    defaultDate: new Date(),
                    nowIndicator: true,
                    navLinks: true,
                    timeFormat: 'h(:mm)a',
                    locale: 'es-PE',
defaultView: 'timelineMonth',
                    header: {
                        left: 'prev,next today',
                        center: 'title',
                        right: 'basicWeek,timelineMonth'
                        //right: 'timelineMonth'
                    },
                    validRange: function (newDate) {
                        return {
                            start: moment(newDate).subtract(3, "days"),
                            end: moment('2018-09-30')
                        };
                    },
                    slotDuration: { day: 1 },
                    dateIncrement: { month: 1 },
                    visibleRange: function (newDate) {
                        console.log("visibleRange: " + newDate);
                        return {
                            start: moment(newDate).subtract(3, "days"),
                            end: moment(newDate).add(15, 'days') // exclusive end, so 3
                        };
                    },_

and the result
![fullcalendar](https://user-images.githubusercontent.com/22396974/41498618-c1b718f4-7137-11e8-9e9f-6cbd9d60b5fe.png)

visibleRange working but no visibleRange

**Comment by acerix** [comment]
Would you be able to post a [runnable, stripped-down demonstration of the bug](http://fullcalendar.io/wiki/Reduced-Test-Cases/)? Would really appreciate it because the time saved reproducing will be time spent fixing.

**Comment by AlexisVidal** [comment]
mmm i have it on production mode: http://200.121.214.213/hotel
user: 42738236
password: 221084

**Comment by AlexisVidal** [comment]
do you mean this: https://codepen.io/alexis-vidal/pen/pKaWXM?editors=0010

**Comment by acerix** [comment]
Thanks for the demo.  Since you are specifying the dates for the view, I think you want just the base "timeline" view, instead of "timelineMonth" which specifies a date range:

https://codepen.io/anon/pen/oyqbzQ?editors=0010

**Comment by AlexisVidal** [comment]
ohh i see, there is a way to set end of visibleRange at the end of the current month?

**Comment by acerix** [comment]
You can use Moment to calculate that, eg: https://codepen.io/anon/pen/JZLRgq?editors=0010
