### ISSUE TITLE
Fullcalandar doesn't want to show when chart.js is on the website on the same time

### ISSUE THREAD

**Issue by lunez1** [fullcalendar/fullcalendar#4220]
I am not an expert on java so it could very well be my fault and if it is i would appreciate
 it if you would at least point me to the right answer, Thank you very much

**Comment by JNPSoftware** [comment]
Hi @lunez1, two things:
1) Jquery First.
```
<script src='fullcalendar/lib/jquery.min.js'></script>
<script src='fullcalendar/lib/moment.min.js'></script>
<script src='fullcalendar/fullcalendar.js'></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.6.0/Chart.min.js"></script>
```
2) Same name on function  and div.
```
$('#calandar').fullCalendar({
<div id="calandar"></div>
```

**Comment by acerix** [comment]
Would you be able to post a [runnable, stripped-down demonstration of the bug](http://fullcalendar.io/wiki/Reduced-Test-Cases/)? Would really appreciate it because the time saved reproducing will be time spent fixing.
