### ISSUE TITLE
how to enable the description tooltip

### ISSUE THREAD

**Issue by hayes-seyah09354085977** [fullcalendar/fullcalendar#4224]
in demo 
 eventRender: function(eventObj, $el) {
      $el.popover({
        title: eventObj.title,
        content: eventObj.description,
        trigger: 'hover',
        placement: 'top',
        container: 'body'
      });
    }

says $el is not a function

**Comment by acerix** [comment]
Would you be able to post a [runnable, stripped-down demonstration of the bug](http://fullcalendar.io/wiki/Reduced-Test-Cases/)? Would really appreciate it because the time saved reproducing will be time spent fixing.

**Comment by sebaqe** [comment]
try this instead: 

eventRender: function(eventObj, el) {
$(el).popover({
title: eventObj.title,
content: eventObj.description,
trigger: 'hover',
placement: 'top',
container: 'body'
});
}
