### ISSUE TITLE
hitTest & offset & bounding rect computation bug

### ISSUE THREAD

**Issue by hinet2013** [fullcalendar/fullcalendar#4225]
Hi.
Latest vTiger CRM v.7.1 uses fullcalendar.js version 3.1 for Calendar management.
For some screen sizes, when in month view, day cells responds to click events only for first or second rows ('add task' modal does not pop up when clicking on last rows when window is scrolled on small screens)

After several investigation emerged that the method **queryBoundingRect** at line 2426 avoids the computation of the bounding rect when `scrollParentEl` is `document`
In our experience we came there with `html` element. This caused the bounding rect to be computed (with top & left set at zero, obviously) and that caused all the hit tests to fail when window is scrolled enough (in such situation `topOffset` is huge in comparison, because it is computed from document's origin)

We found that adding to that conditional also the `html` element makes everything to work properly.

Is it a bug??

We report here the snippet we used to patch the bounding rect computation

```
queryBoundingRect: function() {
	var scrollParentEl;

	if (this.els.length > 0) {
		scrollParentEl = getScrollParent(this.els.eq(0));

		//Original code
		/*if (!scrollParentEl.is(document)) {
			return getClientRect(scrollParentEl);
		}*/
		
		//Patched code
		var htmlEl = $("html");

		if (!scrollParentEl.is(htmlEl) && !scrollParentEl.is(document)) {
			return getClientRect(scrollParentEl);
		}
	}

	return null;
}
```

**Comment by acerix** [comment]
Would you be able to post a [runnable, stripped-down demonstration of the bug](http://fullcalendar.io/wiki/Reduced-Test-Cases/)? Would really appreciate it because the time saved reproducing will be time spent fixing.

**Comment by hinet2013** [comment]
I have found a company that provides a live CRM demo where the calendar bug is visible:

1) visit (http://demo7.vtexperts.com/vtigercrm7demo/index.php)
2) login with _demo_ _demo_
3) Go to calendar section clicking to the second icon in the top-right toolbar
4) Switch to month-view in calendar page
5) **Scroll down** the page (scrolling is essential to let the bug emerge)
6) Now you can notice that last days of month (rows below initial scroll point) are not reactive, while first are

**Comment by acerix** [comment]
Thanks for providing the demo, but I don't notice any issue after following your instructions; I am still able to click on the events at the bottom.  Tried Firefox, Chrome and also on my phone.  

Which browser do you notice the issue in? Also, could you clarify what you mean by "not reactive" and "below initial scroll point"?

**Comment by hinet2013** [comment]
Sorry for my bad explanation: i didn't mean clicking on already existing events but clicking on the white space inside the day cell (when correctly detected it triggers a popup modal to insert a new event)

Ensure to non have a too wide window, so when you first land on the page the scrolbar is available (some last rows od days are not visibile on screen). After having scrolled (those days get revealed) and clicking 'below that line' popup is not triggered

**Comment by acerix** [comment]
Thanks for the clarification.  I didn't get any modal when I last tested but now see it only works on the top part of the calendar. It's not clear that it's a bug in fullcalendar though. 

I'm not sure what you mean by "we came there with `html`", what are you doing differently (compared to the demos) that you need this patch for?

**Comment by hinet2013** [comment]
Please read snippet in first post:
**Original code** of `queryBoundingRect` does computation only when 'scroll parent element' is not `document`
```
if (!scrollParentEl.is(document)) {
	return getClientRect(scrollParentEl);
}
```

In our setup, when the bug is encountered (modal not triggered after clicking on lower day cells) we arrived in that method with variable `scrollParentEl` set to `html` dom element
```
//Patched code
//avoids bounding rect computation when scrollParentEl is document AND ALSO html

var htmlEl = $("html");

if (!scrollParentEl.is(htmlEl) && !scrollParentEl.is(document)) {
	return getClientRect(scrollParentEl);
}
```

**Comment by acerix** [comment]
What I'm asking is, what is different about your code that you need this patch, when the official demos don't have this issue? It's still not clear why you need this patch and it's hard to view the source code of your demo since it's compressed.

It's best if you can recreate the issue in a stripped-down test case so we can reproduce the issue and track down the cause.

**Comment by hinet2013** [comment]
The issue is related to calendar. Take for example this official demo: (https://fullcalendar.io/releases/fullcalendar/3.9.0/demos/selectable.html)

1. Edit body node with browser inspector and wrap the calendar's div with another div.
2. Style that wrapper with fixed height ad overflow: scroll.
3. Scroll the wrapped calendar

Now cells highlighting feature and clicking stopped working (while clicking on already inserted events works), same behavior encountered in vTiger.
I think every time the calendar is put inside something that is scrollable computations went wrong.
As soon i find some time i try to write a code pen.

Thank you

**Comment by acerix** [comment]
I just tried those steps, and it makes the highlight and day click stop working, but it seems that editing the DOM using the browser is breaking the calendar; the buttons at the top stop working too, and it happens with just a plain <div> with no CSS.

I made this demo with a <div> like you described and don't have the issue:

https://codepen.io/anon/pen/ajbgdE
