### ISSUE TITLE
Include function of the date of the day an eventclick was called

### ISSUE THREAD

**Issue by alejojau** [fullcalendar/fullcalendar#4226]
Hi, I loved this development but it would be awsome if we can get a way to get the date (the date where the click event took place) within a eventclick so I can split that event into 2 events, one from the start date to the date I clicked in the event, and the other from the followed day I click in the event to the end date of the original event, and could be like some property in the event such as dayClicked or dateClicked that is a moment element.

**Comment by acerix** [comment]
Thanks for the suggestion. To confirm, are you looking for a new param in `eventClick` which would be like the `date` param in `dayClick`; giving which day was clicked on?

**Comment by alejojau** [comment]
Acerix, yes thats precisly what I'm looking for.
