### ISSUE TITLE
Typescript project can't be built after adding fullCalendar. error code: TS2694

### ISSUE THREAD

**Issue by iPazooki** [fullcalendar/fullcalendar#4227]
I have just added fullCalendar using bower. now, when I just build the project it fires an error that is related to the `fullcalendar.d.ts` file:

>   error TS2694: Namespace 'moment' has no exported member 'Locale'.

I have even added `moment` using bower and referenced its `moment.d.ts` file but it didn't work.

**Comment by acerix** [comment]
Are you using the latest version of fullcalendar and momentjs? Sounds like you have some old typescript definitions.

**Comment by iPazooki** [comment]
@acerix  It's very strange, Yeah I use the last version. you mean this `fullcalendar.d.ts` shouldn't be available?

**Comment by acerix** [comment]
I tried installing to an empty directory with `bower install fullcalendar` and it installs only the compiled files (not source) and I don't see any error in the typescript definitions.

Which build command is producing the error? I'm trying to reproduce the issue but it's not clear what to do after installing with bower.

**Comment by arshaw** [comment]
this is probably a non-issue in v5
