### ISSUE TITLE
Time slots cannot be selected in timeline view after scrolling (IE11)

### ISSUE THREAD

**Issue by acerix** [fullcalendar/fullcalendar#4234]
> The issue only seems to occurs on Windows 7, IE 11. 
> 
> How to re-produce the error:
> Step 1: Load scheduler page, eg. https://fullcalendar.io/docs/date-clicking-selecting-resource-demo
> Step 2: Start scrolling
> Step 3: Select on timeline (no time will get selected)
> Step 4: Select again on timeline (timeline is selected)
 
https://fullcalendar.freshdesk.com/a/tickets/366

**Comment by acerix** [comment]
Tested in IE11 on Windows 10 and could not reproduce the issue.

**Comment by acerix** [comment]
Confirmed in IE11 on Windows 7 VM from https://developer.microsoft.com/en-us/microsoft-edge/tools/vms/ .

**Comment by acerix** [comment]
Don't actually need to scroll, just click on the scrollbar and the calendar elements become unclickable.  Clicking triggers `#calendar.onClick()` the first time, then calendar elements work on subsequent clicks.

As a quick hack, calling `rerenderEvents` after the calendar is scrolled makes things work after scrolling.

https://codepen.io/anon/pen/vaYqzo?editors=0011

**Comment by arshaw** [comment]
i'm having trouble recreating this original problem in IE11. with this updated codepen: https://codepen.io/arshaw/embed/MWKoNxE?editable=true&editors=001

i'm closing for now, but if this is still a problem, please reopen
