### ISSUE TITLE
TypeScript: Wrong parameter type for eventAllow

### ISSUE THREAD

**Issue by kremerd** [fullcalendar/fullcalendar#4236]
According to the TypeScript type definitions the `eventAllow` function should be called with a `DropInfo` and an `Event` parameter. This doesn't make sense, and indeed the function is actually called with a `DropInfo` and an `EventObjectInput` parameter.

Since type errors cannot be tracked in a CodePen I created a StackBlitz for this: https://stackblitz.com/edit/typescript-kjxyih . The compiled code does work, but if you wait for IntelliSense to show up, you'll see the type error in the editor.

Fixing this should be a one-liner. I'll gladly provide a PR if you like.

**Comment by acerix** [comment]
Thanks for the report and demo.  A PR would be appreciated and likely get it fixed sooner.
