### ISSUE TITLE
Error on view change to list (4.x alpha + Bootstrap themes)

### ISSUE THREAD

**Issue by noahlange** [fullcalendar/fullcalendar#4238]
Attempting to use the alpha on NPM with Bootstrap 4, calendar throws on change to a list view. 

Problem is that the provided classes for both Bootstrap themes use whitespace in (some) names (i.e., they consist of multiple classes separated with a space). Strings with whitespace do not appear to be not valid arguments for `classList.add`.

I haven't looked into whether or not this is an issue with older versions of fc.

## Demo + Steps to Reproduce
https://codepen.io/anon/pen/jKoROo
1. Press 'list' button on header.
2. Error:
    - Opera/Chrome: `Failed to execute 'add' on 'DOMTokenList': The token provided ('card card-primary') contains HTML space characters, which are not valid in tokens.`
    - Safari: `The string contains invalid characters.`
    - Firefox: `String contains an invalid character.`

## Relevant Code + Fix
https://github.com/fullcalendar/fullcalendar/blob/v4/src/list/ListView.ts#L45

```js
renderSkeleton() {
    this.el.classList.add('fc-list-view')
    let themeClass = this.calendar.theme.getClass('listView')
    if (themeClass) {
      // split on whitespace; cannot add classnames with a whitespace character
      const classes = themeClass.split(/\s/g)
      this.el.classList.add(...classes)
    }
    this.scroller.render()
    this.el.appendChild(this.scroller.el)
    this.contentEl = this.scroller.scrollEl // shortcut
  }
```

**Comment by acerix** [comment]
Thanks the detailed report and suggested fix.

**Comment by arshaw** [comment]
thanks! fixed in the latest v4 alpha (3): https://fullcalendar.io/docs/v4/bootstrap4-theme-demo
