### ISSUE TITLE
Clickable day numbers/headers for easier navigation

### ISSUE THREAD

**Issue by arshaw** [fullcalendar/fullcalendar#424]
Originally reported on Google Code with ID 153
```
I have some ideas on how to improve the navigation possibilities between
the different views. As I am not too much of a JS coder, maybe you might
consider coding them:

- weekView: Make headers with names of days clickable to switch to this
day's view.
- monthView: Add a new column with the week numbers to the left and make
those clickable to switch to this week's view.
- In addition to the arrows to go to the next and previous
year/month/week/day a select box might be helpful. In the month view it
would contain the past X and next Y months to choose from. The same for
weeks with the previous X and next Y weeks.
```

Reported by `renzo.lauper` on 2009-10-29 08:43:04

Imported with **41** stars.

**Comment by SaeX** [comment]
Workarounds/hacks for related matters can be found on http://stackoverflow.com/questions/31151320/fullcalendar-detect-click-in-week-or-day-view. For clickable day numbers, see http://stackoverflow.com/questions/8419116/how-to-make-day-value-clickable-in-month-view / http://jsfiddle.net/cjaarmgp/1/. 

Especially the below requests would be very handy as a native feature.
`    - weekView: Make headers with names of days clickable to switch to this day's view.`
`    - monthView: Add a new column with the week numbers to the left and make those clickable to switch to this week's `

**Comment by arshaw** [comment]
thanks for posting those articles to show what kind of hacks are necessary to get around this issue

**Comment by arshaw** [comment]
implemented in v3! https://fullcalendar.io/blog/2016/09/feature-packed-releases/

[navLinks](https://fullcalendar.io/docs/mouse/navLinks/)

**Comment by funkytooo** [comment]
> ```
> My Dup'd issue (403), was to change monthview where you can click on the day number,
> and it opens up the agendaDay view for that specific day ...
> 
> Here is the code I changed/added to make it happen, in case anyone else wants to add
> it.
> 
> On my calendar page, I used the following:
> 
> function moveToDay(date){
>     var toDate = new Date(date);
>     //alert(toDate);
>     $('#calendar').fullCalendar( 'changeView', 'agendaDay' );
>     $('#calendar').fullCalendar( 'gotoDate', toDate );
> }
> 
> In fullcalendar.js, I modified the following:
> 
> <div class='fc-day-number'>"+aO.getDate()+"</div>
> 
> with:
> 
> <div class='fc-day-number'><a href='#' onClick='moveToDay(\""+aO+"\");return
> false'>"+aO.getDate()+"</a></div>
> 
> And the added these new css entries for link color:
> 
> .fc-grid .fc-day-number a{
>     color:#000;
>     }
> 
> .fc-grid .fc-day-number a:hover{
>     color:#F60;
>     }
> 
> 
> This seems to work really well in this format.  As I figured, pretty simple code
> changes, but really helpful for usable navigation.
> ```
> 
> Reported by `robtaylor` on 2010-03-16 05:26:07

Hi, is this still working?:) I spend all day and couldn't find a solution to this problem:(

**Comment by maaban** [comment]
Hi, i am new to jquery and I wanna use fullcalendar in a way. Each date should show a count of events from mysql and when I click a number it should show the locations of the events and then clicking locations should show details of the events but I dont know how to do it .Help would be appreciated.
