### ISSUE TITLE
List View Accessibility Enhancements

### ISSUE THREAD

**Issue by mgifford** [fullcalendar/fullcalendar#4240]
### Bug Reports
Your list view is really the best presentation for many people using assistive technology.  The regular calendar view is broken up into too many tables. 

The list view can be improved by following an example from the W3C https://www.w3.org/WAI/tutorials/tables/multi-level/

By providing id & headers attributes you can ensure that blind users know when they are in a table cell what day it corresponds to.

**Comment by Luukyb** [comment]
We are also experiencing accessibility issue.
In our case, to make it accessible, we would need to remove the nested tables from the calendar and mark them up as a normal data table. Do you have any guidance on how turn nested tables into normal data table?
Many thanks!

**Comment by arshaw** [comment]
@mgifford and @Luukyb, if you have time, could you please inspect a v5 calendar (like on the https://fullcalendar.io/ homepage)? There are fewer nested tables now.

**Comment by arshaw** [comment]
and could you please also look at list view (the original reason for this ticket). that has been improved too I believe

**Comment by gbonker** [comment]
@arshaw The nested table issue is still present, even in the demo at https://fullcalendar.io/demos:

![image](https://user-images.githubusercontent.com/6987710/109711587-05916b00-7b6d-11eb-89d4-994a1d905ccb.png)

I'm happy to open a separate Github issue if needed.

**Comment by arshaw** [comment]
@mgifford thank you for your ticket and recommendations. I've created a separate ticket for implementing this in list-view:
https://github.com/fullcalendar/fullcalendar/issues/6525
&uarr;
Could you please visit the link, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates?

@Luukyb and @gbonker, I've created a separate, actionable ticket for addressing the nested table issue:
https://github.com/fullcalendar/fullcalendar/issues/6526
&uarr;
Could you please visit the link, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates?
