### ISSUE TITLE
How to import using webpack? v4 (alpha)

### ISSUE THREAD

**Issue by jonasgroendahl** [fullcalendar/fullcalendar#4242]
Hey,

I have tried `import FullCalendar from "fullcalendar"`, but I get undefined.
I have also tried  `import "fullcalendar"` and then tried to access FullCalendar on the window object but there's none.

Works fine if I just put the script tags in the html file.

I'm using latest version of create-react-app.

**Comment by kremerd** [comment]
You need to import `fullcalendar.Calendar` ([Stackblitz](https://stackblitz.com/edit/js-gjtxmv)):

```js
import { Calendar } from 'fullcalendar';

const appDiv = document.getElementById('app');
const cal = new Calendar(appDiv, {  /* options */ });
cal.render();
```

**Comment by lr12003** [comment]
I get reference undefined when I want to use the Schedule component of PrimeNG.
Here my entries:

'@angular/animations',
    '@angular/common',
    '@angular/compiler',
    '@angular/core',
    '@angular/forms',
    '@angular/http',
    '@angular/platform-browser',
    '@angular/platform-browser-dynamic',
    '@angular/router',
    'zone.js',
    'moment',
    'fullcalendar/dist/fullcalendar.min.css',
    'fullcalendar/dist/fullcalendar.min.js'
