### ISSUE TITLE
Memory leak using fullcalendar with jquery 2.1.3.

### ISSUE THREAD

**Issue by goran11** [fullcalendar/fullcalendar#4247]
### Bug Reports

It seems that leak happens because fullcalendar uses jquery eventing on all sorts of objects via 
EmmiterMixin but on destroy it doesn't correctly remove those objects from $.cache.

With jquery 2.2.4 it works fine because jquery stopped using $.cache.

Jquery used $.cache for compatibility with old versions of Internet Explorer - circular references via expando property on DOM element.

[Description 1](https://stackoverflow.com/questions/10092619/precise-explanation-of-javascript-dom-circular-reference-issue)

[Description 2](https://makandracards.com/makandra/31325-how-to-create-memory-leaks-in-jquery)

Reproduction - just click destroy button and analyze memory with Chrome (find calendar retainers)
[Fiddle](https://jsfiddle.net/goran11/ckq7dnx2/37/)

**Comment by acerix** [comment]
Thanks for the report, I can see the memory is not freed with 2.1 but is freed with 2.2.

Is there a reason not to use the newer version though? Even 2.x is no longer maintained.

**Comment by goran11** [comment]
For project I worked on there was no reason not to upgrade jquery, so we upgraded to 2.2. The reason we use jquery 2 is because we used other js libraries that would be broken by usage of jquery 3.x.x. Anyway fullcalendar website recommends jquery 2.0.0+ so we figured to report the issue, might be helpful to others as well.

**Comment by arshaw** [comment]
v4 no longer uses jquery, so closing this ticket
