### ISSUE TITLE
why the version4 remove jquery but the example page still use jquery

### ISSUE THREAD

**Issue by xhkang1314** [fullcalendar/fullcalendar#4249]
### Bug Reports
why the version4 remove jquery but the example page still use jquery。
fullcalendar-4.0.0-alpha\demos\selectable.html   in this demo page，still use jquery
 $('#calendar').fullCalendar('renderEvent', eventData, true);

I want to speed up the 4.0 of API, maybe I have not found the address. XD

**Comment by acerix** [comment]
Are you suggesting that jQuery be removed from the demos?  v4 can still work in jQuery it's just no longer a requirement.

**Comment by xhkang1314** [comment]
maybe es6 code style be better.   use the Class。 
like ：
let calendar = new FullCalendar.Calendar(calendarEl, {}); 
calendar.renderEvent(eventData);

**Comment by frlinw** [comment]
he is probably talking about https://github.com/fullcalendar/fullcalendar/blob/v4/demos/selectable.html#L32
It's is not supposed to work this way in v4

**Comment by arshaw** [comment]
this is fixed in v4.0.0-alpha2 (just released)
