### ISSUE TITLE
Deprecated composer dependency

### ISSUE THREAD

**Issue by Eseperio** [fullcalendar/fullcalendar#4250]
Robloach/component-installer is deprecated.

https://github.com/fullcalendar/fullcalendar/blob/c59e5d49daaf1b207d2605b885317c60804348d8/composer.json#L22

**Comment by acerix** [comment]
Thanks for pointing it out

https://github.com/RobLoach/component-installer

**Comment by acerix** [comment]
Related to https://github.com/fullcalendar/fullcalendar/issues/4489

**Comment by arshaw** [comment]
composer support has been dropped, so closing this ticket
