### ISSUE TITLE
Create React Version

### ISSUE THREAD

**Issue by rhuanbarreto** [fullcalendar/fullcalendar#4252]
You could create a react component from this great library!

**Comment by acerix** [comment]
There are wrappers for React available but not part of fullcalendar.  What are you looking to have added?

There is a related discussion for adding Angular support:

https://github.com/fullcalendar/fullcalendar-scheduler/issues/11

**Comment by bshiroya** [comment]
https://fullcalendar.io/releases/fullcalendar-scheduler/1.9.4/demos/external-dragging.html



above example move to react

**Comment by sradgit1** [comment]
Hi 
Im writing a React Studio Plugin for Fullcalendar-Sheduler 4.0.1  - Resource-TimeGrid.
I need a react wrapper for this.
Any Idea when one would be available.
it needs to include { core, dayGrid, resource-common, timeGrid, resource-timeGrid, interaction }
Plugins.
I have successfully coded a Plugin  (3.*  fullCalendar-sheduler) into React Studio with
 npm -- fullcalendar-reactwrapper-with-scheduler 
 -- magic - but looking forward to non jQuery & moment implementation
Steve

**Comment by arshaw** [comment]
we're actually working on this!

**Comment by arshaw** [comment]
!!! https://fullcalendar.io/blog/2019/04/react-vue-and-angular-connectors

**Comment by bshiroya** [comment]
but external event drag and drop is not working 

https://fullcalendar.io/releases/fullcalendar-scheduler/1.9.4/demos/external-dragging.html
