### ISSUE TITLE
Cannot able to get END Date in full calender,can you please fix this issue

### ISSUE THREAD

**Issue by dhana1290** [fullcalendar/fullcalendar#4256]
Cannot able to get END Date in full calender is null when using eventDrop,its optional here please change it required. please fix this issue

(Please erase the above text and begin typing. Thanks!)

**Comment by acerix** [comment]
Would you be able to post a [runnable, stripped-down demonstration of the bug](http://fullcalendar.io/wiki/Reduced-Test-Cases/)? Would really appreciate it because the time saved reproducing will be time spent fixing.
