### ISSUE TITLE
Drag/Drop not working in v4 Alpha

### ISSUE THREAD

**Issue by StickNitro** [fullcalendar/fullcalendar#4260]
Im sure this is not a bug but more a plea for support since I seem to be unable to get the drag/drop to work, I am creating a component wrapper in Angular 6 around the fullcalendar/scheduler.  Please see stackblitz link below:

[StackBlitz](https://stackblitz.com/edit/angular-fullcalendar-schedule)

Everything, I am sure is imported/linked correctly but for some reason the drag and drop are not working, I have googled this and looked on SO but nothing found that can help so I am falling at your feet with a plea for help.

fullcalendar: v4.0.0-alpha
fullcalendar-scheduler: v4.0.0-alpha.2

**Comment by acerix** [comment]
I tested your demo in Firefox and dragging the events seems to work fine.  Which browser are you using and do you get any errors in the console?

I also tried Chromium, but the calendar never renders, I just get "Uncaught DOMException: Failed to read the 'localStorage' property from 'Window'" errors.

**Comment by StickNitro** [comment]
I was using Chromium, wasn't getting any errors at all in the browser but did manager to fix in the end, I discovered I had a) not imported the fullcalendar dragula script file and b) I had not provided the external drag container reference. So closing this now as resolved.
