### ISSUE TITLE
year views

### ISSUE THREAD

**Issue by liuweiju** [fullcalendar/fullcalendar#4261]
hello, when add year views? thank you!

**Comment by acerix** [comment]
There is already a timelineYear view, and several open requests for adding other year views but no ETA:

https://github.com/fullcalendar/fullcalendar/issues/1140
https://github.com/fullcalendar/fullcalendar/issues/3963
https://github.com/fullcalendar/fullcalendar/issues/2525
https://github.com/fullcalendar/fullcalendar/issues/470
↑
Could you please visit the links, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates?
