### ISSUE TITLE
Multi-day timed event not displaying on end date if before 9:00am when calendar in month view

### ISSUE THREAD

**Issue by elebetsamer** [fullcalendar/fullcalendar#4262]
I think I've found a strange edge case where a timed event that spans more than a single day doesn't get displayed on the end date unless it has a time after 9:00am when viewing the Month view for the calendar.

![image](https://user-images.githubusercontent.com/75610/43489716-cd5cdab8-94d2-11e8-92a4-631f1755a202.png)

The first event, shown incorrectly on a single day, is:

```javascript
{
  title: 'Multi-Day Timed',
  start: '2018-07-23T07:00:00',
  end: '2018-07-24T08:00:00'
}
```

The second event, shown correctly on both days, is:

```javascript
{
  title: 'Multi-Day Timed',
  start: '2018-07-25T07:00:00',
  end: '2018-07-26T09:00:00'
}
```

Demonstration: https://codepen.io/elebetsamer/pen/yqvQbP

**Comment by acerix** [comment]
The default of setting of `nextDayThreshold` only shows events that end after 9 AM, so you can change that to '00:00' to have those events show on the final day.

https://fullcalendar.io/docs/nextDayThreshold
