### ISSUE TITLE
Keep order and position of events with Ajax

### ISSUE THREAD

**Issue by itpao25** [fullcalendar/fullcalendar#4264]
### Feature Requests
We are using FullCalendar with ajax.
Type of view: _basicWeek_, _displayEventTime_: false

1 - Position of items by changing page
Clicking next, the position of events are **dynamically**:
how to keep the position (like hour) of one item when i change page of the day?
Eg. Of a day contains a item that in the next page isn't present, the position of all **items are changing**.

2 - Scroll position by changing page
How to keep the **scroll position** clicking next day? 

Thanks!

**Comment by acerix** [comment]
Please submit separate requests as their own issue.

I'm not sure what you mean for #1, by "items" are you referring to events? Those are positioned based on the start time which would be different for every day.  It would help if you can provide a demo:

https://fullcalendar.io/reduced-test-cases

For 2, I found this example, are you looking for similar functionality to be built-in?

http://jsfiddle.net/doLf3q5u/

**Comment by acerix** [comment]
Thanks for the example.  Are you looking to make the yellow event "stick" to the top, meaning it would always be rendered before (above) other events?

Please submit your second request in a separate issue since it's not related to the first one.

**Comment by itpao25** [comment]
We would like all events to always maintain the same position by changing page, **yellow is an example** of what happens. The **purple event** allowed the yellow to stay in that position (top), but for some reason when I change the page and the purple event disappears, the yellow event moves below.

I need to keep the position of all events by changing page.
Thanks!!

**Comment by acerix** [comment]
The visible events are always drawn starting from the top-left with no gaps.

For the events to never move vertically, it seems the calendar would need to know about all events in advance (eg. could not be fetched by JSON when changing page) and there would be gaps anywhere there is an even in a previous page.

**Comment by itpao25** [comment]
How can I do this? is it possible to maintain the position of events by changing page? (storing them in memory for example).
I don't think it's a good idea to load all the events in same moment.

**Comment by acerix** [comment]
You could probably do that with a custom view, but I believe it would need to know about all the events in advance, and if there's lots of events it would not look very good.

**Comment by arshaw** [comment]
specifying an [eventOrder](https://fullcalendar.io/docs/eventOrder) and basing it off a custom property of the event object would cause the vertical order to be deterministic
