### ISSUE TITLE
Feature Request: Background events - recurring dow type - set exceptions

### ISSUE THREAD

**Issue by sebaqe** [fullcalendar/fullcalendar#4267]
Hi Adam, 
first of all, thank you very much for this awesome software! It is very complex and pretty hard to get a hang of, but it is a gem, and can do so much! 

I have read the recurring events issue, and I'm not sure if this belongs to that, or just as an addition to the already existing dow functionality. 

I have a scenario where I have set default business hours as background events (so that I may have full granular control and even set 3 sessions of business hours per day (8-12, 2-4, 6-9 for example) . 
The data of these background events is in the form: 
start: "08:00", 
end: "11:00",
dow: ["1"]

Clients can book weeks in advance based on these background events. However, I would like to implement custom business hours for specific days. Let's say one Thursday the contractor is not available in the morning due to a doctor's appointment. Instead of changing the default business hours for all Thursdays, I would like to set an exception for a particular thursday, say August 9th, 2018. The background event(s) on that day would be in the form: 
start: "2018-08-09T16:00:00+Tz"
end: "2018-08-09T21:00:00+Tz"

Would it be possible to set exceptions for the recurring dow type events for a particular day so that I can add a custom event for that particular day separately? 

Many thanks!
Sebastian

**Comment by acerix** [comment]
Thanks for the suggestion.  I couldn't find an easy way to do that currently.  The [eventRender](https://fullcalendar.io/docs/eventRender) should allow changing some properties of the event, but I couldn't get the start time to update in this example: https://codepen.io/anon/pen/yqjjyp?editors=0010

**Comment by sebaqe** [comment]
Hmmm... would you be able through event render to simply not render events on certain days?  Let the dow behave as intended, bit delete all bg events for specific dates?

**Comment by sebaqe** [comment]
Sorry, i have gotten sidetracked away from developing this portion for my project. But I am now back at it. This solution is great and i think it should do the trick perfectly. Thanks a lot!!

**Comment by arshaw** [comment]
there's actually already an issue for this:
https://github.com/fullcalendar/fullcalendar/issues/4549
&uarr;
Could you please visit the link, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates?
