### ISSUE TITLE
Locales for MomentJS are loaded when not used

### ISSUE THREAD

**Issue by gmw-web** [fullcalendar/fullcalendar#4268]
According to the docs on [locale](https://fullcalendar.io/docs/locale)...
> When you load a FullCalendar locale file, it also loads the translations for MomentJS and jQuery UI Datepicker...

### Expected behaviour:
Without any locales set, only the default locale (English) should be loaded for MomentJS.
When loading one or more FullCalendar locale files, the related locale files for MomentJS should get loaded, but only those (no more, no less).

### What's happening now:
All locales for MomentJS appear to be loaded regardless.

### Details:
We have a project that we're bundling using WebPack in which we use FullCalendar. However, even without any locales set for the FullCalendar instance (thus relying on the default English setting, it appears that **all** locales for MomentJS end up in the final package, resulting in a JavaScript file that's much larger than needed. 

See screenshot below from the WebPack Bundle Analyzer, this is the result of a default import of only FullCalendar and FullCalendar-Scheduler without any of FullCalendar's locales being imported or a locale config option set.

![moment-locales](https://user-images.githubusercontent.com/27803283/43588082-0855a33a-966c-11e8-8ffa-a6dca81a16f0.png)

**Comment by acerix** [comment]
I just tried building the [webpack example](https://github.com/fullcalendar/scheduler-webpack-example) and no locales are imported, as expected. Is your project based on that example and/or what are you doing differently?

**Comment by gmw-web** [comment]
Sorry, forgot to mention my exact setup. I'm using the new (alpha) release with jQuery removed. To be exact, I'm using the following:

`fullcalendar: 4.0.0-alpha`
`fullcalendar-scheduler: "4.0.0-alpha.2`

I've tried the webpack example and made minimal changes to match my setup. I must admit that no (unused) locales were imported when analyzing the result bundle, so I have to check my project to see what's causing my issue. Thanks for pointing me to the webpack example.
