### ISSUE TITLE
alpha 4.0.0, set option without jquery not working ?

### ISSUE THREAD

**Issue by rem5** [fullcalendar/fullcalendar#4269]
Hello,

Try to use the fullCalendar 4.0.0 alpha (https://github.com/fullcalendar/fullcalendar/releases/tag/v4.0.0-alpha) and want to modify options dynamically,
particularly for _minTime_ and _maxTime_
No Jquery with this new version, so I understand I can't use this : $('#calendar').fullCalendar('option', 'minTime', 10:00');
I tried with `calendar.option('minTime', '10:00');` but returns:

> Uncaught TypeError: Cannot read property 'setToolbarOptions' of undefined
>    at Calendar.renderHeader (fullcalendar.js:12389)
>    at OptionsManager.add (fullcalendar.js:13192)
>    at Calendar.option (fullcalendar.js:11972)

Not found the 4.0.0 alpha in JSBin but here is the simple javascript code from an example ([https://github.com/fullcalendar/fullcalendar/blob/jquery-removal/demos/default.html](https://github.com/fullcalendar/fullcalendar/blob/jquery-removal/demos/default.html))
 with the added line that returns this error:

```
  document.addEventListener('DOMContentLoaded', function() {
    var calendarEl = document.getElementById('calendar');
    var calendar = new FullCalendar.Calendar(calendarEl, {
      header: {
          left: 'title',
          center: '',
          right: 'today prev,next'
      },
      displayEventTime: false, // don't show the time column in list view
        schedulerLicenseKey: 'CC-Attribution-NonCommercial-NoDerivatives',
        height: 1500,
        contentHeight: "auto",
        aspectRatio: 5,
        defaultView: 'agendaDay',
        nowIndicator: true,
        minTime: '18:00',
        maxTime: '20:00',
      events: [],
      eventClick: function(event) {
        // opens events in a popup window
        return false;
      },
      loading: function(bool) {
        document.getElementById('loading').style.display =
          bool ? 'block' : 'none';
      }
    });

    calendar.option('minTime', '10:00');

    calendar.render();
  });;

```

Any idea ?

Thanks

**Comment by frlinw** [comment]
repro: https://codepen.io/frlinw/pen/QBrMwM
Indeed there is an error but it works if you render the calendar before changing any options.

**Comment by rem5** [comment]
Hello, not tested in this order (noob :/) so it resolves now my problem... :)
Anyway this bug can maybe block someone else in other conditions ?
Thank you for your answer and your codepen !

**Comment by acerix** [comment]
The docs say that setting dynamic options can be done "after a calendar has already been initialized" but in the example above it is called before that, so it doesn't seem like a bug.  The options can either be specified when the calendar is initialized or after initialization is complete.
