### ISSUE TITLE
option to never reset scroll when changing days within same view

### ISSUE THREAD

**Issue by itpao25** [fullcalendar/fullcalendar#4273]
Feature Requests

We are using FullCalendar with ajax.
Type of view: basicWeek, displayEventTime: false

How to keep the scroll position clicking next day?
I need a somethings like this http://jsfiddle.net/doLf3q5u/ but for the basicWeek view.
Thanks!

**Comment by acerix** [comment]
Original request: https://github.com/fullcalendar/fullcalendar/issues/4264#issuecomment-410389172

Demo of functionality: http://jsfiddle.net/doLf3q5u/

**Comment by marcoancona** [comment]
Pretty much needed

**Comment by arshaw** [comment]
This has been released in v5.7.0!
blog post: https://fullcalendar.io/blog/2021/05/new-features-in-v570

set the `scrollTimeReset` option to `false`
