### ISSUE TITLE
nowIndicator doesn't show in timeline view when slotDuration is in whole days

### ISSUE THREAD

**Issue by RikEskes** [fullcalendar/fullcalendar#4275]
**Correct Behaviour**
When a view is rendered, and the FullCalendar option 'nowIndicator' is set to true, the now indicator should be representing the current time of day on the calendar view.

When a view is rendered, and the FullCalendar option 'scrollTime' is set (even as default value), the start time of the time slots in the view should be the set scrollTime.

When a view is rendered, and the FullCalendar option 'slotDuration' is set (even as default value), the duration of the time slots in the view should be the same as the stated slotDuration

**Buggy Behaviour**
When a view is rendered, and the FullCalendar option 'nowIndicator' is set to true, the now indicator is not being represented in the 'timelineWeek' view when the slotDuration is set to '24:00:00'.

When a view is rendered as 'timelineWeek with 'slotDuration' set to '24:00:00', and the FullCalendar option 'scrollTime' is set (even as default value), the start time of the time slots when changing view to the 'agendaWeek' view is not set or set to 00:00, instead of the set one from the fullCalendar options. Therefore not representing the set scrollTime when slotDuration is set to '24:00:00' in 'timelineWeek' before changing view to 'agendaWeek'.

**Reproducing**
Codepen: https://codepen.io/anon/pen/GBBwpx

Open the Codepen and see that when initialising fullCalendar as 'timelineWeek' with slotduration set to '24:00:00' and 'nowIndicator' set to true that the nowIndicator is not shown.

Click on the 'change view' button to change to 'agendaWeek' view, then you can see that when changing 'slotDuration' to '00:30:00' the set 'scrollTime' of '07:00:00' is not represented in the view. Instead the view starts at midnight.

When one would initalise the calendar view(s) without a slotDuration set, the nowIndicator is always shown when it is set to true, and the scrollTime is properly rendered when slotDuration isn't set. However, as shown in the codePen, this does not happen properly when slotDuration is set.

**Comment by acerix** [comment]
Thanks for the detailed report.

Here's another example showing that the nowIndicator is missing in timeline view if the slotDuration is in whole days:

https://codepen.io/acerix/pen/QBJgMB?&editors=001

The issue with scrollTime is separate, you need to change the slotDuration option before changing the view, otherwise it's scrolling to the position based on the previous slotDuration:

https://codepen.io/acerix/pen/ejQRea?editors=1010

**Comment by arshaw** [comment]
This has been fixed in v5 (maybe earlier?)
https://codepen.io/arshaw/pen/ExZjMRy?editors=0010

For more fine-grain control, see this issue: https://github.com/fullcalendar/fullcalendar/issues/6175
