### ISSUE TITLE
Multi Day spans months doesn't render correctly

### ISSUE THREAD

**Issue by ThisBytes5** [fullcalendar/fullcalendar#4282]
Apologies if this was reported previously, I searched but didn't turn up anything that looked the same.

I'm not sure how to set up a sample issue as I don't want to give up my Google API keys.

The image below I've created an event that goes from Aug 30th through Sept 3rd. In the image you can see that the empty block after the 31st has the event continuing, and nothing shows up on the Sept calendar for the 1st through the 3rd.

My Options for creating the calendar:

var options = {
      // put your options and callbacks here
      header: {
        left: '',
        center: 'title',
        right: ''
      },
      fixedWeekCount: false,
      height: 650,
      googleCalendarApiKey: 
      events: {
        googleCalendarId: 
      },
      eventRender: function (event, element, view) {
        // ignored for day view since it only sees 1 date (no overlap across days of different months)
        // ignored for week view since we want to see events which appears in 2 different months (overlap)
        // this will only be triggered in initialization or when view is changed to month view to hide events from other months
        if (view.name == "month") {
          if (event.start._i.split("-")[1] != getMonthFromString(view.title.split(" ")[0])) {
            return false;
          }
        }
      }
    };

    $('#currentMonth').fullCalendar(options);
    $('#nextMonth').fullCalendar(options);
    $('#nextMonth').fullCalendar('next');
    $('#thirdMonth').fullCalendar(options);
    $('#thirdMonth').fullCalendar('next');
    $('#thirdMonth').fullCalendar('next');

![image](https://user-images.githubusercontent.com/7539201/44065484-f50dc192-9f38-11e8-8998-f16b224fffc5.png)

Hoping this isn't user error :)

**Comment by acerix** [comment]
Would you be able to post a [runnable, stripped-down demonstration of the bug](http://fullcalendar.io/wiki/Reduced-Test-Cases/)?

It sounds like the issue is not specific to the Google API, in which case you can try to reproduce in the JSON feed template. Otherwise you could remove your API key before submitting so all that is needed to reproduce the issue is to add a key.

**Comment by ThisBytes5** [comment]
I'm an idiot, it's completely user error. I have a render event that says don't draw it if the month of the event doesn't match the calendar month. So it must be the way the events are being passed in. So back to the drawing board.

Thanks for making me think about how I could get this to the smallest amount of code, it made me find the problem to something I wrote over a year ago!
