### ISSUE TITLE
how to fetch bank data with the next button

### ISSUE THREAD

**Issue by andrejm7** [fullcalendar/fullcalendar#4283]
hello .. using the next button from fullcalendar I need it to be loaded by a get with id, start date and end date.

When I open my calendar, the information for the current month is loaded, but when I click next, I can not load the information from the database.

I tried to use the viewRender but it does not recognize my method.

example:

`funcoesAgenda() {
    let diaClick = '01/01/1900';
    let horaClick = '01/01/1900';

    $('#data').datepicker({
      language: 'pt-BR',
      todayHighlight: true,
      autoclose: true
    });

    $('.clockpicker').clockpicker();

    $('#calendar').fullCalendar({
      height: 550,
      header: {
        left: 'prev,next today',
        center: 'title',
        right: 'month,agendaWeek,agendaDay'
      },
      hiddenDays: [0],
      defaultDate: new Date(),
      defaultView: 'agendaWeek',
      // navLinks: true, // can click day/week names to navigate views
      selectable: true,
      selectHelper: true,
      select: (start, end) => {
        this.editar = 'N';

        // this.agendamento.data = moment(diaClick, 'DD/MM/YYYY').format('LL');
        this.agendamento.dataHoraInicio = moment(diaClick, 'DD/MM/YYYY').format('YYYY-MM-DD') + 'T' + horaClick;

        // $('#calendarModal').modal();
        this.agendamentoCadastro.abrir(this.agendamento);

      },
      editable: true,
      eventLimit: true, // allow "more" link when too many events,
      eventClick: (event, jsEvent, view) => {
        this.evento = event;
        $('#opcoesModal').modal();

      },
      events: this.eventos,
      dayClick: (date, jsEvent, view) => {
        // dia clicado
        diaClick = moment(date).format('DD/MM/YYYY');
        horaClick = moment(date).format('HH:mm');
      },
      viewRender: function (view, element) {
        this.dataInicio = moment(view.start).format();
        this.dataFim = moment(view.end).format();
      }
    });
  }`

` ngOnInit(): void {
    this.carregarAgenda();
    this.funcoesAgenda();
  }

  alteraAgenda(idAgenda) {
    this.agendaSelecionada.id = idAgenda;

    // const view = $('#calendar').fullCalendar('getView');

    this.carregarAgendamento(this.agendaSelecionada.id, '2018-01-01', '2019-01-01');
  }

  carregarAgenda() {
    this.agendaService.getAgenda().subscribe(
      (data: any) => {
        // ok
        this.agendas = data;
        // this.pacienteSelecionado = this.pacientes[0];
        this.alteraAgenda(this.agendas[0].id);
      },
      err => {
        // caso erro
        this.errorHandler.handle(err);
      },
      () => {
        // quando a promise termina
      }
    );
  }

  carregarAgendamento(idAgenda, inicio, fim) {
    this.eventos = [];
    this.agendaService.getAgendamento(idAgenda, inicio, fim).subscribe(
      (data: any) => {

        this.eventos = data;

        this.eventos.forEach(evento => {
          evento.title = evento.paciente.nome;
          evento.start = evento.dataHoraInicio;
          evento.end = evento.dataHoraEncerramento;
          evento.color = evento.agenda.cor;
        });

        // $('#calendar').fullCalendar( 'refetchEvents' );
        $('#calendar').fullCalendar('removeEvents');
        $('#calendar').fullCalendar( 'renderEvents', this.eventos );

        console.log('teste' , this.eventos);

        // this.funcoesAgenda();
      },
      error => this.errorHandler.handle(error),
      () => { });
  }`

**Comment by acerix** [comment]
Would you be able to post a [runnable, stripped-down demonstration of the bug](http://fullcalendar.io/wiki/Reduced-Test-Cases/)? Would really appreciate it because the time saved reproducing will be time spent fixing.

**Comment by andrejm7** [comment]
Hi ... I figured out what the problem was.
I changed it
`
dayClick: (date, jsEvent, view) => {
    // dia clicado
    diaClick = moment(date).format('DD/MM/YYYY');
    horaClick = moment(date).format('HH:mm');
  },
  viewRender: function (view, element) {
    this.dataInicio = moment(view.start).format();
    this.dataFim = moment(view.end).format();
  }
`

for it.

`
dayClick: (date, jsEvent, view) => {
    // dia clicado
    diaClick = moment(date).format('DD/MM/YYYY');
    horaClick = moment(date).format('HH:mm');
  },
  viewRender: (view, element)  => {
    this.dataInicio = moment(view.start).format();
    this.dataFim = moment(view.end).format();
  }
`
