### ISSUE TITLE
In drag and drop with scroll, the element does not follow the cursor

### ISSUE THREAD

**Issue by bharatModiIsMe** [fullcalendar/fullcalendar#4284]
During drag and drop using scrollbar, when I try to drag an element below the visible area, the element sticks to one position while the cursor moves down the screen, thus creating a confusion.

Here is the Codebin link - https://codepen.io/anon/pen/EpBjLj?editors=0110
to reproduce, just resize the demo (bottom) area so that the outer scroll goes away

Thanks in advance!

**Comment by dennis-jiang** [comment]
I have the same issue

**Comment by bharatModiIsMe** [comment]
Hi,
I was able to resolve the issue.
The catch was to apply the height and scroll only to the inner calendar component with this class - .fc-day-grid-container (in my case)
