### ISSUE TITLE
Event randomly shows in the allDay field, even though allDay is set to false

### ISSUE THREAD

**Issue by nc-csl** [fullcalendar/fullcalendar#4286]
Hi all,

I have an issue where events shows up in the allDay field, even though the allDay property is set to false. This happens randomly when I e.g. switch views. I cannot seem to find a pattern to why this is happening. It is not happening with all events, but only some.

Why is Fullcalendar interpreting my event as allDay? I have set both start and end time. allDay is set to false and I even set the allDayDefault to false.

This is the format I use for my start and end time: "YYYY-MM-DDTHH:mm:ss.SSSSZ"

**Comment by acerix** [comment]
Would you be able to post a [runnable, stripped-down demonstration of the bug](http://fullcalendar.io/wiki/Reduced-Test-Cases/)? Would really appreciate it because the time saved reproducing will be time spent fixing.

**Comment by nc-csl** [comment]
Hi acerix. Sorry for the late answer, and thank you for replying. 
We have a test environment up and running where I can show you the bug. You can write me a private message to get login information. I tried to create a code pen for the bug but I cannot recreate it. Remember that this bug happens randomly, so sometimes the event shows normally, other times it shows as allDay. I use the same FC options and exact copy of an event. https://codepen.io/anon/pen/pxzaJq 

The event didn't show in the code pen until I removed the timezone of the start and end property: "2018-09-27T11:37:35**.000+00:00**" <- Why is that?

**Comment by nc-csl** [comment]
Hi again. I just tried to retest this on my local machine, and encountered the bug, but the other way: Now my allDay event shows in the timeline view. See attached SS. 
![image](https://user-images.githubusercontent.com/722375/46143328-e5517980-c259-11e8-8add-62fad7c314eb.png)

**Comment by acerix** [comment]
I don't see any events incorrectly showing as allDay or vice-versa and am not sure what you are logging, I don't see that in the demo. Also, don't see how to reproduce the issue with timezone.  Can you specify the steps to reproduce , and why you are expecting the output not to be true?  It's best if you can keep the demo as small as possible so there's not too much code to look through.

**Comment by nc-csl** [comment]
If you look at the codepen example and go to 27th of september 2018, week view, you can see that the allDay events are not displayed in the allDay section. 
Regarding my screenshots, you can see that the allDay event (Fødselsdag: Malthe...) is displayed in the timeline view and not the allDay view. What I am logging is whether the event is allDay or not. So as you can see, all events are allDay. Still I see one of the events in the timeline area.

**Comment by acerix** [comment]
All day events should have only a date for the start/end, it doesn't work if you include the time:

https://codepen.io/anon/pen/aREaxO?editors=0010

**Comment by acerix** [comment]
The issue is that you have another event with the same `id` so that makes it a "repeating event", ie. both events have the same properties.

**Comment by Flynamic** [comment]
This seems inconvenient in situations where events are fetched directly from different database tables. The primary keys then also serve as `id`s and are therefore not unique. Maybe an option to define the property name events are matched by would be helpful.

**Comment by arshaw** [comment]
this will no longer be an issue in v5

ps- going forward use `groupId` to link related events together, not `id`
