### ISSUE TITLE
NowIndicator has limited vertical representation

### ISSUE THREAD

**Issue by puttiron** [fullcalendar/fullcalendar#4287]
I noticed the vertical NowIndicator is not covering the full resources list when it is somewhat longer. Also the vertical lines to indicate the hours are not covering the full board. See screendump on Google+ below.
[https://plus.google.com/photos/photo/107478875588502230056/6590604763800124114?authkey=CMWU7s6R84eduQE](url)

Is there a way to fix this?

**Comment by acerix** [comment]
Would you be able to post a [runnable, stripped-down demonstration of the bug](http://fullcalendar.io/wiki/Reduced-Test-Cases/)? Would really appreciate it because the time saved reproducing will be time spent fixing.

**Comment by puttiron** [comment]
Hi acerix,
The Calendar is part of a large OutSystems application. Stripping it to the core and still keeping a working page is not doable. But I have saved the page as a stand-alone set (attached) which is showing what goes wrong. If you activate Planboard.html, goes to the Day view and drag it a little down, you will see the NowIndicator stops somewhat half way.

[Planboard.zip](https://github.com/fullcalendar/fullcalendar/files/2306249/Planboard.zip)

**Comment by acerix** [comment]
If there is still an issue, try turning off CSS and other scripits to find what is conflicting.
