### ISSUE TITLE
Calendar is not coming when publishing in iis 

### ISSUE THREAD

**Issue by sunnyk11** [fullcalendar/fullcalendar#4288]
ajax full calendar is showing in localhost but when i publish it in iis calendar does not show, following error occurs

modernizr-2.6.2.js:838 [Deprecation] Application Cache is deprecated in non-secure contexts, and will be restricted to secure contexts in M69, around September 2018. Please consider migrating your application to HTTPS, and eventually shifting over to Service Workers. See https://goo.gl/rStTGz for more details.

(Please erase the above text and begin typing. Thanks!)

**Comment by acerix** [comment]
This doesn't sound like an issue with the calendar, please post a [runnable, stripped-down demonstration](http://fullcalendar.io/wiki/Reduced-Test-Cases/) if there is a bug.
