### ISSUE TITLE
double click event trigger

### ISSUE THREAD

**Issue by gjob83** [fullcalendar/fullcalendar#4289]
Hi, 
It is possible to have a double click event trigger like the one that exists for the event click?
https://fullcalendar.io/docs/eventClick

I ask this, because I developed as workaroud a double click jquery bind (code below), but this approach is not the best, because the trigger works some times, and others not:

function db_click"+EncodeJavaScript(code)+"(Event, curr_date){  
   window.location.href = 'https://xxx/ScheduleEdit.aspx? 
   GoDate='+curr_date+'&FromCall=true&ScheduleInfoBoxId='+Event.id;
    
}

...
...
...

element.bind('dblclick', function() {
     var moment = $('#"+CalendarPlaceholder.Id+"').fullCalendar('getDate');
     db_click"+EncodeJavaScript(code)+"(event, moment.format());  
 });

best regards

**Comment by acerix** [comment]
Would you be able to post a [runnable, stripped-down demonstration of the bug](http://fullcalendar.io/wiki/Reduced-Test-Cases/)?

I found this solution that might work better:

https://stackoverflow.com/a/8143130

The discussion linked in that answer mentions that it's better to keep things like this out of the core.

**Comment by moto-geek** [comment]
For reference using v4 https://codepen.io/motogeek/pen/xxxoGGL

**Comment by ramibaccour** [comment]
<full-calendar #ucCalendar 
  (eventRender) = "eventRender($event)"
  >
</full-calendar>
eventRender(event)
{
     event.el.ondblclick = (()=>{alert('ondblclick event')})
}

**Comment by LrntL** [comment]
> <full-calendar #ucCalendar
> (eventRender) = "eventRender($event)">
> 
> eventRender(event)
> {
> event.el.ondblclick = (()=>{alert('ondblclick event')})
> }

Nice one!
jQuery :
```
eventRender: function(eventObj, element, view) {
...
element.on('dblclick', function() { alert('ondblclick event'); } );
}
```

**Comment by xeroxstar** [comment]
I am getting `Unknown option 'eventRender'` is there a fix to it?

**Comment by omidd1315** [comment]
This piece of code can be used for version 6.

    initialView: 'dayGridMonth',
	dateClick: function (info) {
		if (info.dayEl.dblclick) {
			return;
		}

		info.dayEl.dblclick = true;

		info.dayEl.addEventListener('dblclick', function () {
			console.log(info)
		});
	},
