### ISSUE TITLE
removeEvents() not working with _id

### ISSUE THREAD

**Issue by tobiratzberger** [fullcalendar/fullcalendar#4292]
Hello!
I've read in an Issue Ticket that it should be possible to removeEvents with the "_id" (  #3828 ).
But it looks like it's not working. It removes all events from the calendar. Any Idea, is it a bug?

    var eventAfterRenderFunction = function (event, element) {
        if (event.className.indexOf("jsAppointmentChooser-dateSeries") !== -1) {
            var eventDeleteItem_Button = $("<button/>", { "class": "btn btn-danger btn-circle jsAppointmentChooserDeleteEvent appointmentChooserDeleteEvent", "type": "button" });
            var eventDeleItem_Icon = $("<i/>", { "class": "fas fa-trash-alt" })

            element.append(eventDeleteItem_Button.append(eventDeleItem_Icon));
            eventDeleteItem_Button.on("click", function () {
                console.log(event._id);
                calendarElement.fullCalendar('removeEvents', event._id);
            });
        }
    }

Or am I using it wrong?

Thanks <3

**Comment by acerix** [comment]
Would you be able to post a [runnable, stripped-down demonstration of the bug](http://fullcalendar.io/wiki/Reduced-Test-Cases/)? Would really appreciate it because the time saved reproducing will be time spent fixing.

**Comment by helphop** [comment]
I'm having the same problem. I have tried to remove an event using the event._id which is unique for each event but it removes all events with the same event.id (ie recurring events.)

**Comment by arshaw** [comment]
in v4, there is no longer a private _id property
