### ISSUE TITLE
Error displaying date and time

### ISSUE THREAD

**Issue by Haintst** [fullcalendar/fullcalendar#4294]
Hello Team,
My customer has a issues.
Example: Monday 20th August is correct but it shows on 23rd.
![edit service your living wordpress](https://user-images.githubusercontent.com/24773519/44499276-5e830d00-a6ad-11e8-949b-fa6ee887bc79.png)
<img width="495" alt="bildschirmfoto-2018-08-22-um-23 55 42" src="https://user-images.githubusercontent.com/24773519/44499317-8a05f780-a6ad-11e8-9458-da6d66744955.png">

Thanks
Hai

**Comment by acerix** [comment]
Would you be able to post a [runnable, stripped-down demonstration of the bug](http://fullcalendar.io/wiki/Reduced-Test-Cases/)? Would really appreciate it because the time saved reproducing will be time spent fixing.

**Comment by Haintst** [comment]
Hi acerix
My client said it came from only Safari browser.

**Comment by acerix** [comment]
Is the issue visible in one of the demos? Otherwise, we need a way to reproduce so it's best if you can provide a [reduced test case](http://fullcalendar.io/wiki/Reduced-Test-Cases/).
