### ISSUE TITLE
Cannot Read property 'lenght' of Undefined (same as  #3598)

### ISSUE THREAD

**Issue by joxley** [fullcalendar/fullcalendar#4297]
I started receiving 'Cannot Read property 'lenght' of Undefined' errors.
I upgraded to FC v3.9.0 but it did not help.
***** Received message *********************************************************************************
fullcalendar.min.js:6 Uncaught TypeError: Cannot read property 'length' of undefined
    at e.parseEventDefs (fullcalendar.min.js:6)
    at fullcalendar.min.js:9
    at Object.success (events.php:118)
    at j (VM1804 jquery-2.1.0.min.js:2)
    at Object.fireWith [as resolveWith] (VM1804 jquery-2.1.0.min.js:2)
    at x (VM1804 jquery-2.1.0.min.js:4)
    at XMLHttpRequest.<anonymous> (VM1804 jquery-2.1.0.min.js:4)
e.parseEventDefs @ fullcalendar.min.js:6
(anonymous) @ fullcalendar.min.js:9
success @ events.php:118
j @ jquery-2.1.0.min.js:2
fireWith @ jquery-2.1.0.min.js:2
x @ jquery-2.1.0.min.js:4
(anonymous) @ jquery-2.1.0.min.js:4
load (async)
send @ jquery-2.1.0.min.js:4
ajax @ jquery-2.1.0.min.js:4
events @ events.php:107
(anonymous) @ fullcalendar.min.js:9
construct @ fullcalendar.min.js:6
e.fetch @ fullcalendar.min.js:9
t.requestSource @ fullcalendar.min.js:11
t.requestSources @ fullcalendar.min.js:11
t.setPeriod @ fullcalendar.min.js:11
t.requestEvents @ fullcalendar.min.js:11
t.requestEvents @ fullcalendar.min.js:10
e.fetchInitialEvents @ fullcalendar.min.js:7
(anonymous) @ fullcalendar.min.js:7
(anonymous) @ fullcalendar.min.js:8
c @ fullcalendar.min.js:8
(anonymous) @ fullcalendar.min.js:8
e @ fullcalendar.min.js:6
dispatch @ jquery-2.1.0.min.js:3
r.handle @ jquery-2.1.0.min.js:3
trigger @ jquery-2.1.0.min.js:3
triggerHandler @ jquery-2.1.0.min.js:3
e.trigger @ fullcalendar.min.js:6
e.setProps @ fullcalendar.min.js:8
e.set @ fullcalendar.min.js:8
e.setDate @ fullcalendar.min.js:7
t.renderView @ fullcalendar.min.js:10
t.nextYear @ fullcalendar.min.js:10
g @ fullcalendar.min.js:11
(anonymous) @ fullcalendar.min.js:11
dispatch @ jquery-2.1.0.min.js:3
r.handle @ jquery-2.1.0.min.js:3
***********************************************************************************************************

After testing and reading other posted issues like this for about 4 hours I tried the following mod to fullcalendar.js at line 1112.
---------------------------------------------------------------------
if(rawEventDefs === undefined){ 
    console.log("rawEventDefs: "+rawEventDefs);
}else{
    for (i = 0; i < rawEventDefs.length; i++) {
        eventDef = this.parseEventDef(rawEventDefs[i]);
        if (eventDef) {
            eventDefs.push(eventDef);
        }
    }
}
----------------------------------------------------------------------

Everything is working OK now.

**Comment by acerix** [comment]
Would you be able to post a [runnable, stripped-down demonstration of the bug](http://fullcalendar.io/wiki/Reduced-Test-Cases/)? Would really appreciate it because the time saved reproducing will be time spent fixing.

**Comment by victorantos** [comment]
same error still
