### ISSUE TITLE
Cursor is regular for Chrome and Firefox, text-selection for IE and Edge

### ISSUE THREAD

**Issue by justanotheranonymoususer** [fullcalendar/fullcalendar#4301]
Example:
https://codepen.io/anon/pen/MVwpYp

Edge:
![image](https://user-images.githubusercontent.com/5781692/44732861-f25e3a00-aaee-11e8-8ccc-aef2b923213c.png)

Chrome:
![image](https://user-images.githubusercontent.com/5781692/44732882-fbe7a200-aaee-11e8-8884-1c0e00a265b5.png)

Adding this rule will fix this I believe:
```
.fc-event {
    cursor: default;
}
```

**Comment by acerix** [comment]
Thanks for the report, makes sense that it should be consistent.

**Comment by arshaw** [comment]
in v5 at least, the cursor is consistent between chrome and edge. both have the text cursor when not draggable and the pointer draggable
