### ISSUE TITLE
Can't get the appropriate event date at 1970 January

### ISSUE THREAD

**Issue by Keis828** [fullcalendar/fullcalendar#4307]
### Bug Reports
Hello, 

I found when the calendar set date to 1970 January, date of dayClick function, events function and others, can't get appropriate date. For Example, when I click day on Jan, 2, 1970 dayClick date returns Sep, 2, 2018. 

Here, you can check it. Thank you.
https://codepen.io/keis-nishi/pen/RYgrmQ

<img width="1209" alt="2018-09-04 22 18 19" src="https://user-images.githubusercontent.com/9313642/45033769-79338980-b090-11e8-80c1-aa474b9f765f.png">

**Comment by acerix** [comment]
Thanks for the report and demo.  I can see it works fine in previous years and in Feb 1970, so it seems to be broken specifically for January 1970.

**Comment by arshaw** [comment]
when adapted for v5, this is fixed: https://codepen.io/arshaw/pen/XWXaKab?editable=true&editors=001
