### ISSUE TITLE
After change event start/end and set allDay = false the event vanished in month view

### ISSUE THREAD

**Issue by alexjonser** [fullcalendar/fullcalendar#4308]
Hello,

i have some problem with changing the start and end datetime of an event.

I create a new event by dropping it from external on the month view.
Next step in a form can the user choose on which time the event will start.
After this i load the event and change the start and end datetime and set
allDay to false. Now the event is vanished in the month view

> **EXAMPLE from code**
> var event = $element.fullCalendar('clientEvents', options.event_id)[0];
> event.start  = moment('2018-09-07T07:00:00+02:00');
> event.end    = moment('2018-09-07T10:00:00+02:00');
> event.allDay = false;
> $element.fullCalendar('updateEvent', event);

In "options.event_id" is the id from event._id saved

> **These are my init-settings of fullcalendar**
> editable: true,
> header: false,
> firstDay: 1,
> locale: 'de',
> timezone: 'Europe/Berlin',
> height: 'auto',
> slotDuration: '00:15:00',
> slotLabelFormat: 'HH:mm',
> eventOverlap: false,
> allDaySlot: false,

Any ideas what i did wrong? (except my poor english ;) )

PS: i use fullcalendar v3.9.0

**Comment by alexjonser** [comment]
ok i found a solution.
First i load the event and change the data like described.
Then i reload the event by 'clientEvents' and change the end date once again and save it again.
This works.

While debugging i saw that are start and end date are set with the start date after "updateEvents".
So i get the event again by "clientEvents" and set end again.

**Comment by acerix** [comment]
If there is still an issue, would you be able to post a [runnable, stripped-down demonstration of the bug](http://fullcalendar.io/wiki/Reduced-Test-Cases/)? Would really appreciate it because the time saved reproducing will be time spent fixing.
