### ISSUE TITLE
Use of selectOverlap together with all-day event

### ISSUE THREAD

**Issue by feyzayavuz** [fullcalendar/fullcalendar#4310]
Hello, 

I created official holidays as an all-day event. And i gave true option for selectOverlap feature. I can not add new event this days because this is considered to be an intersection. It makes sense to use this feature for official holidays. But i want to add new event for some special days (mother's day etc.) like all-day event. (with selectOverlap feature) and it to look like it appears in the all-day event slot and add new events to this day. How can i do this? Is this possible? If there is no such feature, should i make feature request about it? 

Thanks for your help.

**Comment by acerix** [comment]
Would you be able to post a [runnable, stripped-down demonstration of the bug](http://fullcalendar.io/wiki/Reduced-Test-Cases/)? Would really appreciate it because the time saved reproducing will be time spent fixing.

Making the holiday a "background" event may fix this.

**Comment by feyzayavuz** [comment]
Hello again,

I'll give you a quick summary for my problem with screenshots. I wrote you wrong information about selectOverlap attribute true for all-day events firstly this attribute is false.

For example:
![screenshot from 2018-09-12 15-38-18](https://user-images.githubusercontent.com/6138244/45486812-195e7200-b765-11e8-9aa7-3e1cb38e15cf.png)

It is an official holiday event(all-day event) and i gave selectOverlap false for this event so user can not click this days fields.

For conclusion i want to give special day event(also an all-day event) for whole day but i don't want to give selectOverlap: false for this type of events (mothers day etc.) so user can click, add their events.

**Comment by acerix** [comment]
Does it not work to use a background event for the entire day? It might help if you can provide a demo, I'm not sure exactly what you are looking for.
