### ISSUE TITLE
empty block when use maxTime in timeGrid view

### ISSUE THREAD

**Issue by brasileric** [fullcalendar/fullcalendar#4314]
hi,

When I use maxTime in agendaWeek, for example 20:00, there is an empty block below 20:00, see the screenshot.

![image](https://user-images.githubusercontent.com/6453793/45301347-110df900-b511-11e8-8fa5-7cad49009d2c.png)

**Comment by acerix** [comment]
Would you be able to post a [runnable, stripped-down demonstration of the bug](http://fullcalendar.io/wiki/Reduced-Test-Cases/)? Would really appreciate it because the time saved reproducing will be time spent fixing.

**Comment by OBreidenbach** [comment]
See: http://jsfiddle.net/62rq79zs/1/

**Comment by acerix** [comment]
The default height is based on a default aspect ratio.  You could set the height to 'auto' to have it stop after the last timeslot:

http://jsfiddle.net/j1s4x8az/
