### ISSUE TITLE
Crom slot rander is incorrect 

### ISSUE THREAD

**Issue by devashishsohani** [fullcalendar/fullcalendar#4320]
Hi Team

I faced the  issue with fullcalnder  weekly view , here when event are rendered then it works fine on mozila but chrome event slot position are wrong when I inspect or press ctrl+ and ctrl- its  automatic correct without page refresh. As well as i used left and right button it works fine on chrome

can  you assist me  for this issue
Thanks
Vasudev

**Comment by acerix** [comment]
Would you be able to post a [runnable, stripped-down demonstration of the bug](http://fullcalendar.io/wiki/Reduced-Test-Cases/)? Would really appreciate it because the time saved reproducing will be time spent fixing.
