### ISSUE TITLE
Events don't render for dow=7 when weekNumberCalculation="ISO"

### ISSUE THREAD

**Issue by nlyn** [fullcalendar/fullcalendar#4321]
When I enable `weekNumberCalculation` as "ISO" I would expect 7 to be interpreted as Sunday, but it appears that Sunday is 0. Is this correct? I ask because it doesn't match either moment's isoWeekday() or weekday() methods. 

Can be seen here:
https://codepen.io/anon/pen/LJvgGm

**Comment by acerix** [comment]
The `dow` setting comes from [businessHours](https://fullcalendar.io/docs/businessHours) where it specifies that Sunday is `0`.

`weekNumberCalculation` is used only to calculate week numbers so it doesn't affect the `dow` setting.

**Comment by dakala** [comment]
@arshaw What to do with this issue? https://fullcalendar.io/docs/week-numbers and https://fullcalendar.io/docs/businessHours are clear enough, I think.
