### ISSUE TITLE
Fullcalendar not showing events in IOS devices

### ISSUE THREAD

**Issue by quangpro1610** [fullcalendar/fullcalendar#4322]
I have used Fullcalendar in one of my Wordpress page. It is working fine in Chrome and Mozilla. Also the same is working fine in Android devices. But issue is with IOS device. (It works on iOS >=12)

Calendar events it self-are not being loaded. Didn't find any solution for this on net. Please provide any help on this.
Link events calendar: https://livemusicnow-koeln.de/konzertkalender/
I also tried to follow the answer to the below question but doesn't work. (https://stackoverflow.com/questions/40280577/fullcalendar-not-showing-events-in-ios-devices)

**Comment by acerix** [comment]
Would you be able to post a [runnable, stripped-down demonstration of the bug](http://fullcalendar.io/wiki/Reduced-Test-Cases/)? Would really appreciate it because the time saved reproducing will be time spent fixing.

I don't have an iOS device to test with at the moment.  If you notice any errors in the console those would help.

**Comment by quangpro1610** [comment]
Hi @acerix ,
I send you the screenshot on iPhone about this issue. Please review it below.

On Iphone (ios11)
https://imgur.com/8LdLIki

On Iphone (ios12)
https://imgur.com/Y9yl49s

Thank you very much.

**Comment by acerix** [comment]
Thanks, I see the same issue in Firefox if I make the window small so I think any device with a small screen would look like that.

This demo also doesn't show the full event titles on small screens:

https://fullcalendar.io/releases/fullcalendar/3.9.0/demos/basic-views.html

To fit more event info, you need to make the calendar cells bigger or the events smaller.  Or for mobile devices you could hide the details until the event is clicked.

**Comment by quangpro1610** [comment]
@acerix I have found the cause and I fixed it.

**Comment by pyromanci** [comment]
@quangpro1610 can you explain what you found and fixed? Was it inside your code or the fullcalender code? I've just stumbled on to this problem as well.

**Comment by quangpro1610** [comment]
> @quangpro1610 can you explain what you found and fixed? Was it inside your code or the fullcalender code? I've just stumbled on to this problem as well.

About my case, I have found an issue that is on Safari, the title of the event has a special character or if I use break line inside JSON string will error and the calendar not show.

On my safari notify is Syntax Error: Unexpected EOF and I have fixed it by way clean special character and it works for me.

**Comment by pyromanci** [comment]
Thanks for the clarification. 

I had just stumbled on to the solution for my problem a moment. Which boiled down to a incompatibility in the moment datetime string format between browsers in side my eventRender function.  for some reason the iOS version of browsers just didn't like it when every other browser and platform did. Apples "Think Different" at work.

**Comment by quangpro1610** [comment]
Yes. At first, I also thought that my date format was wrong, and after debugging in safari, I found the cause was not as I thought.

**Comment by Uudis** [comment]
In my case , old IE, Safari and Iphones reqested datetime separator T in btw date and time like so:
2018-10-09T16:00:00
instead of just 
2018-10-09 16:00:00

**Comment by piernik** [comment]
My clients have the same problem - not all events are showing on safari, apple.
Sadly I don't own iMac so I cannot reproduce that issue...

**Comment by arshaw** [comment]
@quangpro1610 I'll consider this issue closed since you figured out it was strange character encoding in your event text.

@Uudis  and @piernik , your problem is something else. It's related to the way ISO8601 dates are parsed in Safari:
https://github.com/fullcalendar/fullcalendar/issues/4610
&uarr;
Could you please visit the link, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates?

**Comment by needwit** [comment]
Tengo el mismo problema. En una aplicación web tengo un calendario. En un dispositivo android las horas en el calendario (events) me sale de forma correcta, pero en ios como en un iphone o ipad me sale de forma diferente se salta un dia, y una hora normal 12:00 me muestra como 00:00 ayuda porfavor

**Comment by rohitjpsingh** [comment]
> In my case , old IE, Safari and Iphones reqested datetime separator T in btw date and time like so:
> 2018-10-09T16:00:00
> instead of just
> 2018-10-09 16:00:00

Yes, it's working for me.

**Comment by meet1919** [comment]
Hey, I am seeing the same thing like @quangpro1610  but it happens to the screen having, width <= 767px. What should be the problem?

**Comment by burithetech** [comment]
+1 same
