### ISSUE TITLE
Add wrap up time with (optional) matching variable in the event

### ISSUE THREAD

**Issue by weha** [fullcalendar/fullcalendar#4323]
I'd like to add a wrap-up time, or cool-down period if you will, to an event.
If a certain variable matches (optional?) on two events and one has a wrap-up time I can't drag it in the wrap-up time of the other.
If the variable does not match you can.
Indicating how long the wrap-up time is while dragging it is also good.

Just to clarify: this would keep a better overview of the events instead of just enlarging the event with a wrap-up time.

**Comment by acerix** [comment]
Thanks for the suggestion, can see how that would be useful.    Would every event have it's own wrap up time, or would that be a global setting for all events?

**Comment by arshaw** [comment]
dup of:
https://github.com/fullcalendar/fullcalendar/issues/3174
&uarr;
Could you please visit the link, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates?
