### ISSUE TITLE
How to Change selection color in FullCalendar

### ISSUE THREAD

**Issue by Diane0517** [fullcalendar/fullcalendar#4325]
this is more of a two pronged question. Based on items I've tried, there is no way to change the "selectable/selectableOverlap" of a full calendar after it is initialized. The reason I'd like to do that is to have a toggle on the page that allows the user to indicate whether or not they'd like to be able to select or not on the calendar control.

In lieu of that, since the "select" callback is only called when the selection is released (and I want to prevent selection visually), my thought was to just set the opacity of the selected cells to 0 so that they are not shown and I can just unselect when the select callback executes. However, I cannot find a way to modify the colors or css properties of the cells being selected, as shown here:

enter image description here

Is there a way to change the css properties of the cells being selected, or perhaps the first way of dynamically changing whether selection works?

Thanks -selection works?

Thanks -

**Comment by acerix** [comment]
Your image didn't get attached and I'm not sure exactly what you are trying to do. 

Here's a quick example I made that makes selection red but only on Tuesday:

https://codepen.io/anon/pen/aRdNVj?editors=0110

It sounds like you just want to set `selectable` depending if the user wants to be able to select or not.

**Comment by acerix** [comment]
If this is a bug, please supply a [runnable, stripped-down demonstration](http://fullcalendar.io/wiki/Reduced-Test-Cases/).
