### ISSUE TITLE
*Format properties accept function

### ISSUE THREAD

**Issue by frlinw** [fullcalendar/fullcalendar#4328]
### Feature Requests

Allow function as a value for properties accepting Date Formatter:
- listDayFormat
- listDayAltFormat
- slotLabelFormat
- eventTimeFormat
- titleFormat
- dayPopoverFormat

```js
views: {
  listMonth: {
    listDayFormat: (date) => myCustomDateFormatter(date, "MM DD YYYY")
  }
}
```

or add new properties `listDayText`, `listDayAltText`, `slotLabelText`, .... to be consistent with `columnHeaderFormat`/`columnHeaderText`

**Comment by arshaw** [comment]
v4 supports this:
https://fullcalendar.io/docs/date-formatting#formatting-functions

**Comment by frlinw** [comment]
@arshaw after some tests, it doesn't work that way (for `listDayFormat` at least).
function params is an object, not an instance of Date and `date`, `start` & `end` members are not instance of Date:
![image](https://user-images.githubusercontent.com/11896237/62285144-52730400-b455-11e9-94e8-740762daed1e.png)

**Comment by kamleshwebtech** [comment]
how to change header date format to UK date format (day / month / year) in week view in full calendar 4 version? Please suggest. Thank you.
