### ISSUE TITLE
Controlling formatting of the time axis

### ISSUE THREAD

**Issue by ganySA** [fullcalendar/fullcalendar#4334]
Hi

Is there any way that the time axis slots can be formatted?

I would like to control the rendering of the time labels. e.g Make full hours large and small time elements small.

e.g full hour to display 06:00
and the next ones just 15, 30, 45

see screenshot:

![image](https://user-images.githubusercontent.com/3189206/46593497-c27e5b00-cacc-11e8-958a-db19cc465c99.png)

Thanks

**Comment by acerix** [comment]
I believe this existing ticket captures this need:
https://github.com/fullcalendar/fullcalendar/issues/3164
↑
Could you please visit the link, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates?
