### ISSUE TITLE
Scheduler Printing issue

### ISSUE THREAD

**Issue by Picpool** [fullcalendar/fullcalendar#4336]
I have a schdeuler timeline daily view with 40 ressources lines and a horizontal time range from 8AM to 11PM.
When a print i have several pages and the result is not very printer friendly

**Comment by acerix** [comment]
I believe this existing ticket captures this need:
https://github.com/fullcalendar/fullcalendar-scheduler/issues/83
↑
Could you please visit the link, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates?
