### ISSUE TITLE
Printable version of Scheduler on 1 A4 page

### ISSUE THREAD

**Issue by eothein** [fullcalendar/fullcalendar#4337]
It would be nice if there was an out-of-the-box printing functionality, i.e. that the Scheduler is able to be fitted onto a A4 page for printing. Now it cuts off the days which are out of the page, although resizing would make it able to be printed on one page.

Kind regards

Jens Buysse

**Comment by acerix** [comment]
I believe this existing ticket captures this need:
https://github.com/fullcalendar/fullcalendar-scheduler/issues/83
↑
Could you please visit the link, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates?
