### ISSUE TITLE
[alpha2] ExtendedEventSourceInput events type does not allow EventSourceFunc

### ISSUE THREAD

**Issue by baileyandy** [fullcalendar/fullcalendar#4342]
The [documentation](https://fullcalendar.io/docs/v4/events-function) suggests an [EventSourceFunc](https://github.com/fullcalendar/fullcalendar/blob/v4/src/event-sources/func-event-source.ts#L5) type value can be assigned to the `events` parameter when using [Calendar::addEventSource](https://fullcalendar.io/docs/v4/Calendar-addEventSource), however, the [current v4-alpha.2 code](https://github.com/fullcalendar/fullcalendar/blob/v4/src/structs/event-source.ts#L44) does not allow it.

Editing `fullcalendar.d` locally to `events?: EventInput[] | EventSourceFunc` (or adding `@ts-ignore`) allows my v4-alpha.1 code to compile.

I could submit a PR but wanted to check if this a regression or is the intention to switch to only allowing `events?: EventInput[]`?

**Comment by acerix** [comment]
Would you be able to post a [runnable, stripped-down demonstration of the bug](http://fullcalendar.io/wiki/Reduced-Test-Cases/)? Would really appreciate it because the time saved reproducing will be time spent fixing.

**Comment by baileyandy** [comment]
I saw a demo on a different issue concerning a TypeScript problem, so I've done the same.

[My demo](https://stackblitz.com/edit/typescript-mbqwow) shows an error using the current code and an updated `ExtendedEventSourceInput` interface used in function call that TypeScript is happy with. Hope this helps.

**Comment by arshaw** [comment]
fixed this in the v4 branch at commit ab15b32888cf0cf7a8d66b5d19942d0b1b2a1c14

i'll comment again when this is released

**Comment by arshaw** [comment]
this has been addressed and released in [4.0.0-alpha.4](https://github.com/fullcalendar/fullcalendar/releases/tag/v4.0.0-alpha.4)

**Comment by baileyandy** [comment]
Thanks! I can confirm, in the latest alpha release, this is working for me
