### ISSUE TITLE
Typescript d.ts Errors (found in Angular 7 RC)

### ISSUE THREAD

**Issue by ganySA** [fullcalendar/fullcalendar#4349]
Hi

Just something to be aware of. For Angular 7, i suspect because of an update to typescript the t.ds files are no longer compatible it seems and spit out a serious of issues, this is when run with fullcalendar-scheduler + fullcalendar combination.

I believe some of this has something to do with similar Interfaces being declared between the two libraries.

Anyways - something to check / verify.

**Comment by acerix** [comment]
Would you be able to post a [runnable, stripped-down demonstration of the bug](http://fullcalendar.io/wiki/Reduced-Test-Cases/)? Would really appreciate it because the time saved reproducing will be time spent fixing.

We don't support the Angular connectors out there but there's an open issue to add Angular support:

https://github.com/fullcalendar/fullcalendar-scheduler/issues/11
↑
Could you please visit the link, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates?

**Comment by ganySA** [comment]
Hi 

The errors all relate to typescript compilation - and duplication of types between the fullcalendar and fullcallendar-scheduler library.

`ERROR in node_modules/fullcalendar-scheduler/dist/scheduler.d.ts(112,6): error TS2416: Property 'renderDates' in type 'ResourceDayGrid' is not assignable to the same property in base type 'Default'.
  Type '(dateProfile: any) => void' is not assignable to type '() => void'.
node_modules/fullcalendar-scheduler/dist/scheduler.d.ts(132,6): error TS2416: Property 'renderDates' in type 'ResourceTimeGrid' is not assignable to the same property in base type 'Default'.
  Type '(dateProfile: any) => void' is not assignable to type '() => void'.
node_modules/fullcalendar-scheduler/dist/scheduler.d.ts(347,6): error TS2416: Property 'fgSegHtml' in type 'TimelineEventRenderer' is not assignable to the same property in base type 'Default'.
  Type '(seg: any, disableResizing: any) => string' is not assignable to type '(seg: Seg) => void'.
node_modules/fullcalendar-scheduler/node_modules/fullcalendar/dist/fullcalendar.d.ts(1,1): `

`error TS6200: **Definitions of the following identifiers conflict with those in another file:** **ElementContent, Default, globalDefaults, rtlDefaults, viewHash, eventDataTransform, version, internalApiVersion, BusinessHoursInput, OptionsInput, applyAll, debounce, isInt, capitaliseFirstLetter, parseFieldSpecs, compareByFieldSpecs, compareByFieldSpec, flexibleCompare, log, warn, htmlEscape, cssToStr, removeExact, intersectRects, assignTo, multiplyDuration, findElements, findChildren, htmlToElement, createElement, insertAfterElement, prependToElement, removeElement, appendToElement, applyStyle, applyStyleProp, elementMatches, forceClassName, preventDefault, listenBySelector, whenTransitionDone, computeInnerRect, computeEdges, computeHeightAndMargins, formatDate, formatRange, EmitterMixin, EmitterInterface, EventDef, defineThemeSystem, Mixin, Theme, DateComponent, Calendar, View, defineView, getViewConfig, DayTableMixin, EventRenderer, FillRenderer, AgendaView, TimeGrid, DayGrid, BasicView, MonthView, ListView, exportHooks,` 


`node_modules/fullcalendar-scheduler/node_modules/fullcalendar/dist/fullcalendar.d.ts(1460,6): error TS2374: Duplicate string index signature.`

`node_modules/fullcalendar-scheduler/node_modules/fullcalendar/dist/fullcalendar.d.ts(1468,6): error TS2717: Subsequent property declarations must have the same type.  Property 'event' must be of type 'Default', but here has type 'EventObjectInput'.
node_modules/fullcalendar-scheduler/node_modules/fullcalendar/dist/fullcalendar.d.ts(1469,6): error TS2717: Subsequent property declarations must have the same type.  Property 'start' must be of type 'Date', but here has type 'Moment'.
node_modules/fullcalendar-scheduler/node_modules/fullcalendar/dist/fullcalendar.d.ts(1470,6): error TS2717: Subsequent property declarations must have the same type.  Property 'end' must be of type 'Date', but here has type 'Moment'.
node_modules/fullcalendar-scheduler/node_modules/fullcalendar/dist/fullcalendar.d.ts(1475,6): error TS2717: Subsequent property declarations must have the same type.  Property 'date' must be of type 'Date', but here has type 'Moment'.
node_modules/fullcalendar-scheduler/node_modules/fullcalendar/dist/fullcalendar.d.ts(1482,6): error TS2717: Subsequent property declarations must have the same type.  Property 'start' must be of type 'Date', but here has type 'Moment'.
node_modules/fullcalendar-scheduler/node_modules/fullcalendar/dist/fullcalendar.d.ts(1483,6): error TS2717: Subsequent property declarations must have the same type.  Property 'end' must be of type 'Date', but here has type 'Moment'.
node_modules/fullcalendar-scheduler/node_modules/fullcalendar/dist/fullcalendar.d.ts(1503,6): error TS2717: Subsequent property declarations must have the same type.  Property 'weekNumberCalculation' must be of type '"local" | "ISO" | ((m: Date) => number)', but here has type '"local" | "ISO" | ((m: Moment) => number)'.
node_modules/fullcalendar-scheduler/node_modules/fullcalendar/dist/fullcalendar.d.ts(1504,6): error TS2717: Subsequent property declarations must have the same type.  Property 'businessHours' must be of type 'BusinessHoursInput', but here has type 'boolean | BusinessHoursInput | BusinessHoursInput[]'.
node_modules/fullcalendar-scheduler/node_modules/fullcalendar/dist/fullcalendar.d.ts(1514,6): error TS2717: Subsequent property declarations must have the same type.  Property 'now' must be of type 'string | number | number[] | Date | (() => DateInput)', but here has type 'string | number | object | Date | Moment | (() => MomentInput)'.
node_modules/fullcalendar-scheduler/node_modules/fullcalendar/dist/fullcalendar.d.ts(1518,6): error TS2717: Subsequent property declarations must have the same type.  Property 'slotDuration' must be of type 'DurationInput', but here has type 'DurationInput'.
node_modules/fullcalendar-scheduler/node_modules/fullcalendar/dist/fullcalendar.d.ts(1519,6): error TS2717: Subsequent property declarations must have the same type.  Property 'slotLabelFormat' must be of type 'FormatterInput', but here has type 'string'.
node_modules/fullcalendar-scheduler/node_modules/fullcalendar/dist/fullcalendar.d.ts(1520,6): error TS2717: Subsequent property declarations must have the same type.  Property 'slotLabelInterval' must be of type 'DurationInput', but here has type 'DurationInput'.
node_modules/fullcalendar-scheduler/node_modules/fullcalendar/dist/fullcalendar.d.ts(1521,6): error TS2717: Subsequent property declarations must have the same type.  Property 'snapDuration' must be of type 'DurationInput', but here has type 'DurationInput'.
node_modules/fullcalendar-scheduler/node_modules/fullcalendar/dist/fullcalendar.d.ts(1522,6): error TS2717: Subsequent property declarations must have the same type.  Property 'scrollTime' must be of type 'DurationInput', but here has type 'DurationInput'.
node_modules/fullcalendar-scheduler/node_modules/fullcalendar/dist/fullcalendar.d.ts(1523,6): error TS2717: Subsequent property declarations must have the same type.  Property 'minTime' must be of type 'DurationInput', but here has type 'DurationInput'.
node_modules/fullcalendar-scheduler/node_modules/fullcalendar/dist/fullcalendar.d.ts(1524,6): error TS2717: Subsequent property declarations must have the same type.  Property 'maxTime' must be of type 'DurationInput', but here has type 'DurationInput'.
node_modules/fullcalendar-scheduler/node_modules/fullcalendar/dist/fullcalendar.d.ts(1526,6): error TS2717: Subsequent property declarations must have the same type.  Property 'listDayFormat' must be of type 'string | boolean | object | FuncFormatterFunc', but here has type 'string | boolean'.
node_modules/fullcalendar-scheduler/node_modules/fullcalendar/dist/fullcalendar.d.ts(1527,6): error TS2717: Subsequent property declarations must have the same type.  Property 'listDayAltFormat' must be of type 'string | boolean | object | FuncFormatterFunc', but here has type 'string | boolean'.
node_modules/fullcalendar-scheduler/node_modules/fullcalendar/dist/fullcalendar.d.ts(1529,6): error TS2717: Subsequent property declarations must have the same type.  Property 'defaultDate' must be of type 'DateInput', but here has type 'MomentInput'.
node_modules/fullcalendar-scheduler/node_modules/fullcalendar/dist/fullcalendar.d.ts(1531,6): error TS2717: Subsequent property declarations must have the same type.  Property 'visibleRange' must be of type 'DateRangeInput | ((currentDate: Date) => DateRangeInput)', but here has type 'RangeInput | ((currentDate: Moment) => RangeInput)'.
node_modules/fullcalendar-scheduler/node_modules/fullcalendar/dist/fullcalendar.d.ts(1532,6): error TS2717: Subsequent property declarations must have the same type.  Property 'validRange' must be of type 'DateRangeInput', but here has type 'RangeInput'.
node_modules/fullcalendar-scheduler/node_modules/fullcalendar/dist/fullcalendar.d.ts(1533,6): error TS2717: Subsequent property declarations must have the same type.  Property 'dateIncrement' must be of type 'DurationInput', but here has type 'DurationInput'.
node_modules/fullcalendar-scheduler/node_modules/fullcalendar/dist/fullcalendar.d.ts(1535,6): error TS2717: Subsequent property declarations must have the same type.  Property 'duration' must be of type 'DurationInput', but here has type 'DurationInput'.
node_modules/fullcalendar-scheduler/node_modules/fullcalendar/dist/fullcalendar.d.ts(1540,6): error TS2717: Subsequent property declarations must have the same type.  Property 'columnHeaderFormat' must be of type 'FormatterInput', but here has type 'string'.
node_modules/fullcalendar-scheduler/node_modules/fullcalendar/dist/fullcalendar.d.ts(1541,6): error TS2717: Subsequent property declarations must have the same type.  Property 'columnHeaderText' must be of type 'string | ((date: DateInput) => string)', but here has type 'string | ((date: MomentInput) => string)'.
node_modules/fullcalendar-scheduler/node_modules/fullcalendar/dist/fullcalendar.d.ts(1542,6): error TS2717: Subsequent property declarations must have the same type.  Property 'columnHeaderHtml' must be of type 'string | ((date: DateInput) => string)', but here has type 'string | ((date: MomentInput) => string)'.
node_modules/fullcalendar-scheduler/node_modules/fullcalendar/dist/fullcalendar.d.ts(1543,6): error TS2717: Subsequent property declarations must have the same type.  Property 'titleFormat' must be of type 'FormatterInput', but here has type 'string'.
node_modules/fullcalendar-scheduler/node_modules/fullcalendar/dist/fullcalendar.d.ts(1552,6): error TS2717: Subsequent property declarations must have the same type.  Property 'dayPopoverFormat' must be of type 'FormatterInput', but here has type 'string'.
node_modules/fullcalendar-scheduler/node_modules/fullcalendar/dist/fullcalendar.d.ts(1554,6): error TS2717: Subsequent property declarations must have the same type.  Property 'navLinkDayClick' must be of type 'string | ((date: Date, jsEvent: Event) => void)', but here has type 'string | ((date: Moment, jsEvent: Event) => void)'.
node_modules/fullcalendar-scheduler/node_modules/fullcalendar/dist/fullcalendar.d.ts(1560,6): error TS2717: Subsequent property declarations must have the same type.  Property 'selectOverlap' must be of type 'Overlap', but here has type 'boolean | ((event: EventObjectInput) => boolean)'.
node_modules/fullcalendar-scheduler/node_modules/fullcalendar/dist/fullcalendar.d.ts(1561,6): error TS2717: Subsequent property declarations must have the same type.  Property 'selectConstraint' must be of type 'ConstraintInput', but here has type 'ConstraintInput'.
node_modules/fullcalendar-scheduler/node_modules/fullcalendar/dist/fullcalendar.d.ts(1562,6): error TS2717: Subsequent property declarations must have the same type.  Property 'events' must be of type 'EventSourceInput', but here has type 'EventSourceInput'.
node_modules/fullcalendar-scheduler/node_modules/fullcalendar/dist/fullcalendar.d.ts(1563,6): error TS2717: Subsequent property declarations must have the same type.  Property 'eventSources' must be of type 'EventSourceInput[]', but here has type 'EventSourceInput[]'.
node_modules/fullcalendar-scheduler/node_modules/fullcalendar/dist/fullcalendar.d.ts(1572,6): error TS2717: Subsequent property declarations must have the same type.  Property 'nextDayThreshold' must be of type 'DurationInput', but here has type 'DurationInput'.
node_modules/fullcalendar-scheduler/node_modules/fullcalendar/dist/fullcalendar.d.ts(1573,6): error TS2717: Subsequent property declarations must have the same type.  Property 'eventOrder' must be of type 'string | (string | ((a: Default, b: Default) => number) | ((a: Default, b: Default) => number))[]', but here has type 'string | (string | ((a: EventObjectInput, b: EventObjectInput) => number) | ((a: EventObjectInput, b: EventObjectInput) => number))[]'.
node_modules/fullcalendar-scheduler/node_modules/fullcalendar/dist/fullcalendar.d.ts(1581,6): error TS2717: Subsequent property declarations must have the same type.  Property 'eventOverlap' must be of type 'Overlap', but here has type 'boolean | ((stillEvent: EventObjectInput, movingEvent: EventObjectInput) => boolean)'.
node_modules/fullcalendar-scheduler/node_modules/fullcalendar/dist/fullcalendar.d.ts(1582,6): error TS2717: Subsequent property declarations must have the same type.  Property 'eventConstraint' must be of type 'ConstraintInput', but here has type 'ConstraintInput'.
node_modules/fullcalendar-scheduler/node_modules/fullcalendar/dist/fullcalendar.d.ts(1583,6): error TS2717: Subsequent property declarations must have the same type.  Property 'eventAllow' must be of type 'Allow', but here has type '(dropInfo: DropInfo, draggedEvent: Event) => boolean'.
node_modules/fullcalendar-scheduler/node_modules/fullcalendar/dist/fullcalendar.d.ts(1821,6): error TS2717: Subsequent property declarations must have the same type.  Property 'dayDates' must be of type 'Date[]', but here has type 'any'.
node_modules/fullcalendar-scheduler/node_modules/fullcalendar/dist/fullcalendar.d.ts(2165,6): error TS2416: Property 'fgSegHtml' in type 'Default' is not assignable to the same property in base type 'Default'.
  Type '(seg: any, disableResizing: any) => string' is not assignable to type '(seg: Seg) => void'.
node_modules/fullcalendar-scheduler/node_modules/fullcalendar/dist/fullcalendar.d.ts(2281,6): error TS2717: Subsequent property declarations must have the same type.  Property 'content' must be of type '(el: HTMLElement) => void', but here has type 'ElementContent'.
node_modules/fullcalendar-scheduler/node_modules/fullcalendar/dist/fullcalendar.d.ts(2330,6): error TS2416: Property 'fgSegHtml' in type 'Default' is not assignable to the same property in base type 'Default'.
  Type '(seg: any, disableResizing: any) => string' is not assignable to type '(seg: Seg) => void'.
node_modules/fullcalendar-scheduler/node_modules/fullcalendar/dist/fullcalendar.d.ts(2468,6): error TS2416: Property 'buildRenderRange' in type 'Default' is not assignable to the same property in base type 'Default'.
  Type '(currentUnzonedRange: any, currentRangeUnit: any, isRangeAllDay: any) => Default' is not assignable to type '(currentRange: DateRange, currentRangeUnit: any, isRangeAllDay: any) => DateRange'.
    Type 'Default' is not assignable to type 'DateRange'.
      Property 'start' is missing in type 'Default'.
node_modules/fullcalendar-scheduler/node_modules/fullcalendar/dist/fullcalendar.d.ts(2508,6): error TS2416: Property 'buildRenderRange' in type 'Default' is not assignable to the same property in base type 'Default'.
  Type '(currentUnzonedRange: any, currentRangeUnit: any, isRangeAllDay: any) => Default' is not assignable to type '(currentRange: any, currentRangeUnit: any, isRangeAllDay: any) => DateRange'.
    Type 'Default' is not assignable to type 'DateRange'.
node_modules/fullcalendar/dist/fullcalendar.d.ts(1,1): error TS6200: Definitions of the following identifiers conflict with those in another file: ElementContent, Default, globalDefaults, rtlDefaults, viewHash, eventDataTransform, version, internalApiVersion, BusinessHoursInput, OptionsInput, applyAll, debounce, isInt, capitaliseFirstLetter, parseFieldSpecs, compareByFieldSpecs, compareByFieldSpec, flexibleCompare, log, warn, htmlEscape, cssToStr, removeExact, intersectRects, assignTo, multiplyDuration, findElements, findChildren, htmlToElement, createElement, insertAfterElement, prependToElement, removeElement, appendToElement, applyStyle, applyStyleProp, elementMatches, forceClassName, preventDefault, listenBySelector, whenTransitionDone, computeInnerRect, computeEdges, computeHeightAndMargins, formatDate, formatRange, EmitterMixin, EmitterInterface, EventDef, defineThemeSystem, Mixin, Theme, DateComponent, Calendar, View, defineView, getViewConfig, DayTableMixin, EventRenderer, FillRenderer, AgendaView, TimeGrid, DayGrid, BasicView, MonthView, ListView, exportHooks, main
src/app/services/providers/components/dxscheduler/dxscheduler.component.ts(96,78): error TS2345: Argument of type '{ editable: false; height: "parent"; header: false; selectHelper: true; selectable: boolean; defaultView: string; unselectAuto: false; timezone: string; views: { agendaTwoDay: { type: string; duration: { ...; }; groupByResource: true; }; }; ... 9 more ...; events: (start: any, end: any, timezone: any, callback: any)...' is not assignable to parameter of type 'OptionsInput'.
  Types of property 'eventClick' are incompatible.
    Type '(calEvent: any, jsEvent: any, view: any) => void' is not assignable to type '{ (arg: { el: HTMLElement; event: Default; jsEvent: MouseEvent; view: Default; }): boolean | void; (event: EventObjectInput, jsEvent: MouseEvent, view: Default): boolean | void; }'.
src/app/services/providers/components/dxscheduler/dxscheduler.component.ts(516,38): error TS2339: Property 'clientEvents' does not exist on type 'Default'.
src/app/services/providers/components/dxscheduler/dxscheduler.component.ts(524,20): error TS2339: Property 'updateEvent' does not exist on type 'Default'.
src/app/services/providers/components/dxscheduler/dxscheduler.component.ts(530,20): error TS2339: Property 'removeEvents' does not exist on type 'Default'.`

**Comment by acerix** [comment]
Here's an example for building the typescript:

https://github.com/fullcalendar/scheduler-typescript-example

What is being done differently to generate the typescript errors?

**Comment by ganySA** [comment]
I found the issues - it was the version of fullcalendar + fullcalendar-scheduler. 

Would be good to have the version numbers between the two aligned if possible.

**Comment by turbolego** [comment]
@ganySA Can you elaborate on how you managed to fix this?
What do you mean by "version of fullcalendar +  fullcalendar-scheduler" ?

I'm on Angular CLI: 7.2.2 and Angular: 7.2.1

I'm using the latest version of fullcalendar (3.10.0) and fullcalendar-scheduler (1.9.4) according to npmjs.

https://www.npmjs.com/package/fullcalendar
https://www.npmjs.com/package/fullcalendar-scheduler

The project I'm working on has worked fine for months until today, and this was the only thread i could find about this issue.

Thanks!
