### ISSUE TITLE
update event-constraint-demo for v4 groupId

### ISSUE THREAD

**Issue by jgadbois** [fullcalendar/fullcalendar#4351]
This can be reproduced in the main constraint demo, but whenever a constraint is added to an event it can't be dragged *anywhere*.

https://fullcalendar.io/docs/v4/event-constraint-demo

**Comment by acerix** [comment]
I can see the Meeting event can't be dropped on the green areas where it is allowed, is that the issue you mean?

**Comment by jgadbois** [comment]
Yes, thanks @acerix .

**Comment by arshaw** [comment]
it wasn't working because it must reference an event `groupId` instead of `id`.

codepen with working code: https://codepen.io/arshaw/pen/oJwxWy?&editable=true&editors=001

so, this example in the docs is wrong. keeping this ticket around to fix the docs

**Comment by dakala** [comment]
Fixed by @arshaw on 2019-02-04
