### ISSUE TITLE
[v4-alpha.2] Bootstrap 3/4 and list views crash FullCalendar

### ISSUE THREAD

**Issue by nicegamer7** [fullcalendar/fullcalendar#4357]
Rather than making a stripped down version of the bug, it can be viewed on the Bootstrap 3 and 4 demos. 

https://fullcalendar.io/docs/v4/bootstrap3-theme-demo
https://fullcalendar.io/docs/v4/bootstrap4-theme-demo

If you click the listMonth view, the calendar stop rendering any view.

**Comment by nicegamer7** [comment]
That's exactly what I get, thanks for confirming.

**Comment by nicegamer7** [comment]
Issue is, as far as I know, identical to #4238. This issue can be closed if you want.

**Comment by acerix** [comment]
Thanks, missed that.

Duplicate of #4238
