### ISSUE TITLE
[v4-alpha.2] Ambiguously-timed Moments

### ISSUE THREAD

**Issue by adjioev** [fullcalendar/fullcalendar#4359]
Hello,

I was wondering, in v3 moment.js date object is patched with `hasTime()` method that returns false in case it was initiated without a time. 
My question is what do I do in v4 with JS Date object? At this moment I just check if time equals '00:00' but of course it's a bad hack.

Thanks Alex

**Comment by acerix** [comment]
The JS Date object always includes a time, unlike moment dates, so there isn't a way to tell "midnight" apart from "initialized without a time".

**Comment by arshaw** [comment]
pretty much any place that emits a date in the API also has an `allDay` prop, like dateClick:
https://fullcalendar.io/docs/v4/dateClick

if there's a place where an `allDay` prop is NOT available, let us know. closing this issue in the meantime. plz comment back on this issue
