### ISSUE TITLE
eventLimit in wrong dates

### ISSUE THREAD

**Issue by joncepeda** [fullcalendar/fullcalendar#4361]
The event limit text on dates are going only to one date per row. This view is for mobile view. Currently 323px width x 666px height.
See image below:
![image](https://user-images.githubusercontent.com/9354641/47629681-8a23e700-db77-11e8-9d70-50578271b0fc.png)

Anyone has solution for this?

**Comment by acerix** [comment]
Would you be able to post a [runnable, stripped-down demonstration of the bug](http://fullcalendar.io/wiki/Reduced-Test-Cases/)? Would really appreciate it because the time saved reproducing will be time spent fixing.

**Comment by joncepeda** [comment]
This caused the problem.
.fc-more-cell {
     display: block;
}
I've added a css on that class trying to add some design on EventLimit text.
My fault on this.
