### ISSUE TITLE
Month view - show wrong date

### ISSUE THREAD

**Issue by duchanhmta** [fullcalendar/fullcalendar#4365]
Hi,
Help me issue of show date in month view.
This is my start and end date
> start: 2018-11-05 00:00:00
> end: 2018-11-06 08:00:00
And i don't know why when it show in month in only show 1 day.

But when i change end to 2018-11-06 09:00:00 it show correctly.

This is my jsbin:
https://jsbin.com/dovidul/edit?html,js,output

Please help me!
![image](https://user-images.githubusercontent.com/38970107/47904954-75698b00-deb8-11e8-829f-a585bdc46e1e.png)

**Comment by acerix** [comment]
By default, events ending before 9 AM do not show on the next day, you can change that with https://fullcalendar.io/docs/nextDayThreshold .
