### ISSUE TITLE
Is it safe to remove htmlescape when calendar is not editable?

### ISSUE THREAD

**Issue by MichaelKHTai** [fullcalendar/fullcalendar#4368]
### Contributing Features

As title mentioned, I want to remove the code for escaping the html input, as I want to stylish the calendar element and add a tooltip. Like this (https://imgur.com/a/uySHYAa) I made it already.

I understand that when the calendar is editable, it is quite danger for enabling user enter their own html content. But what if the calendar is not editable?

I have made a version that allow html content when calender is not editable. Is there any other concern? And can I make a pull request for this?

**Comment by acerix** [comment]
I'm not sure where you are trying to add HTML, do you mean for example in the labels like in https://github.com/fullcalendar/fullcalendar/issues/2919 ?

**Comment by MichaelKHTai** [comment]
> I'm not sure where you are trying to add HTML, do you mean for example in the labels like in #2919 ?

It seems like, but when I take a look in, for example, `TimeGridEventRenderer.ts line102`, there is always escaping input text by `htmlEscape(eventDef.title)` which I don't (?) have a choice to not escape it.

**Comment by acerix** [comment]
I believe this existing ticket captures this need:
https://github.com/fullcalendar/fullcalendar/issues/2919
↑
Could you please visit the link, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates?
