### ISSUE TITLE
Typeerror when using `startRecur` and `endRecur` when   calendar is outside event range

### ISSUE THREAD

**Issue by acerix** [fullcalendar/fullcalendar#4369]
I've tried to use `startRecur` and `endRecur` props, here is my test event:
````
      events: [
        {
          title: 'Event Title 1',
          daysOfWeek: [1],
          startTime: '02:00',
          endTime: '04:00',
          startRecur: '2018-11-15',
          endRecur: '2018-12-22'
        }
      ]
````

but I get `ERROR TypeError: Cannot read property 'start' of null` error if I open calendar outside event range (startRecur/endRecur).

When ranges don't intersect `intersectRanges` returns null and then we get nullPointException:
````
  let dayMarker = startOfDay(framingRange.start)
````
in `expandRanges` method because framingRange is null.

Thanks Alex

_Originally posted by @adjioev in https://github.com/fullcalendar/fullcalendar/issues/4335#issuecomment-433248704_

**Comment by acerix** [comment]
Demo: https://github.com/adjioev/fullcalendar-bug

**Comment by onizuka8** [comment]
Hello I had the same issue.
I fixed just adding:
`if(framingRange == null){
        return [];
    }`
after:
`framingRange = date_range_1.intersectRanges(framingRange, recurRange);`
within expandRanges function.

**Comment by arshaw** [comment]
this is probably fixed since v4/v5, but if not, could someone post an immediately-runnable demo?
