### ISSUE TITLE
Option to hide day numbers/events/cells for prev/next months

### ISSUE THREAD

**Issue by arshaw** [fullcalendar/fullcalendar#437]
Originally reported on Google Code with ID 166

```
For example, October 2009 starts on a Thursday so you also see September 27
thru 30 at the beginning of the calendar. Is there any way to turn this off
so those cells would simply be blank?

```

Reported by `snh9905` on 2009-11-04 17:33:55

Imported with **20** stars.

**Comment by LorenGr** [comment]
Is there a plan to have this feature in a future release?

**Comment by phammer** [comment]
+1 for providing the feature. In our case, setting the "other-month" class on the event as well, would already allow to do what is needed, i.e., to hide the event with CSS.

**Comment by tamtam22** [comment]
For those who are looking for a temporary fix, here's what I have came up with:

1. First of all, we need to ensure that only events for this month are being rendered

		eventRender: function(event, element, view) {
			// ignored for day view since it only sees 1 date (no overlap across days of different months)
			// ignored for week view since we want to see events which appears in 2 different months (overlap)
			// this will only be triggered in initialization or when view is changed to month view to hide events from other months
			if(view.name == "month") {
				if(event.start._i.split("-")[1] != getMonthFromString(view.title.split(" ")[0])) {
					return false;
				}
			}
		}

2. Next we need to ensure that this is not the same case for Week view since it can be an overlap across 2 different months

		viewRender: function(view, element) {
			if(view.name == "agendaWeek" || view.name == "basicWeek")
				$('#calendar').fullCalendar('rerenderEvents');
		}


With the above 2 functions in place, you will achieve the result!

**Comment by arshaw** [comment]
I'm hoping to tackle this ticket and others like it in the next release and I'd like to get some clarity on the requirements. Are the following true:

- you'd like the ability to not display events that are outside of the given month? I assume you'd want the [events function](https://fullcalendar.io/docs/event_data/events_function/) and [events json feed](https://fullcalendar.io/docs/event_data/events_json_feed/) to receive the strict month start/end dates instead of days before/after.
- you'd like to completely hide days that are in past/future months? Do you want to hide the day number or hide the whole rectangle...

If you hide the whole rectangle, things look a little strange, at least in the current design:
![edited](https://cloud.githubusercontent.com/assets/56520/23318624/1722cf86-fa88-11e6-8df0-17f16576c5c8.png)

Is hiding the day number enough?

**Comment by LorenGr** [comment]
yes i think things should like your screenshot. Even it looks strange, at least it is clear that there are no cells there. Leaving a border gives the idea that cells still exist and one might think there is missing data.

**Comment by arshaw** [comment]
Released in **v3.3.0**
Blog post: https://fullcalendar.io/blog/2017/03/fullcalendar-33-and-scheduler-16/

Setting: https://fullcalendar.io/docs/display/showNonCurrentDates/
(set it to `false`)

The styling is a bit different that I originally depicted. Hope that's okay. Still stylable via CSS.

**Comment by Pallavi-09** [comment]
Hi arshaw,

I'm stuck in one problem is like when i select date from friday to monday and added event but at the same time i don't want that event should apply on weekends that sat and sun in few condition only.
Please suggest.

**Comment by kingsubash** [comment]
Hi tamtam22,

Thanks for you solution. It worked for me. 

Thanks a lot.

Regards,
Subash


> For those who are looking for a temporary fix (for v2), here's the solution:
> 
> First of all, we need to ensure that only events for this month are being rendered
> 
> ```
>     eventRender: function(event, element, view) {
>         // ignored for day view since it only sees 1 date (no overlap across days of different months)
>         // ignored for week view since we want to see events which appears in 2 different months (overlap)
>         // this will only be triggered in initialization or when view is changed to month view to hide events from other months
>         if(view.name == "month") {
>             if(event.start._i.split("-")[1] != getMonthFromString(view.title.split(" ")[0])) {
>                 return false;
>             }
>         }
>     }
> ```
> You will need this method in javascript as well to extract the month which is used in eventRender method above:
> 
> ```
>     function getMonthFromString(mon){
>         var d = Date.parse(mon + "1, 2012");
>         if(!isNaN(d))
>             return new Date(d).getMonth() + 1;
>         return -1;
>     }
> ```
> Next we need to ensure that this is not the same case for Week view since it can be an overlap across 2 different months
> 
> ```
>     viewRender: function(view, element) {
>         if(view.name == "agendaWeek" || view.name == "basicWeek")
>             $('#calendar').fullCalendar('rerenderEvents');
>     }
> ```
> With the above 2 functions in place, you will achieve the result!
