### ISSUE TITLE
FullCalendar eventClick fire dayClick

### ISSUE THREAD

**Issue by meridPL** [fullcalendar/fullcalendar#4372]
I have problem with FullCalendar schedular. When I click event fired eventClick and get start and end date. When I click day fired dayClick get specif date. I need get specific date when click event, but don't fired dayClick.

`eventClick: function( event, jsEvent, view ) { 
    //I need date from dayClick
    console.log("eventClick");
    console.log(event.start);       
},
dayClick: function( date, jsEvent, view, resourceObj ) {
    //not fired when click event
    console.log('dayClick');
    console.log(date);
}`

**Comment by acerix** [comment]
Would you be able to post a [runnable, stripped-down demonstration of the bug](http://fullcalendar.io/wiki/Reduced-Test-Cases/)? Would really appreciate it because the time saved reproducing will be time spent fixing.

**Comment by acerix** [comment]
So you are looking for an option that will make dayClick trigger even if there is an event in the way?

You could also check the position that was clicked on and calculate the time that way:

https://codepen.io/anon/pen/LXNBPN?editors=0011

**Comment by meridPL** [comment]
https://codepen.io/pawelI/pen/JeXQwW?editors=0011

Thank you for your help, I tried earlier  your solutions, but I thought I could fire a dayClick. You can see in codepen my attempts which are similar. I think this issue can be closed.

**Comment by adesheddie** [comment]
@meridPL 
Did you find a way to get the clicked date via eventClick? It's really frustrating that such an important feature is not available....
