### ISSUE TITLE
[v4-alpha.2] TypeError "Cannot read property 'eventRange' of null" when clicking outside business hours with selectConstraint: 'businessHours'

### ISSUE THREAD

**Issue by quangquy87** [fullcalendar/fullcalendar#4375]
Hello!
https://codepen.io/quangquy87/pen/zMZvWJ?editors=0010
When select none businessHours, i get error:
`Uncaught TypeError: Cannot read property 'eventRange' of null
    at HTMLDivElement.EventClicking.handleSegClick (fullcalendar.js:11226)
    at HTMLDivElement.realHandler (fullcalendar.js:2325)`

Please help me, thanks!

**Comment by arshaw** [comment]
this problem was fixed when alpha.3 was released. proof: https://codepen.io/arshaw/pen/ZVyWzW?editors=0010
