### ISSUE TITLE
Ability to add right-click callback to days in monthview eg. dayRightClick

### ISSUE THREAD

**Issue by SuperPat45** [fullcalendar/fullcalendar#4376]
Hello,

Please add a way to define a rightclick on a Day cells in month/week/day views with the start and end dates as function collback:
```
$(fcElement).fullCalendar({
	cellDayRightClick : function(start, end, jsEvent) {

	}.bind(this)
});
```

And the same for Half-Hour cells in day/week views
```
$(fcElement).fullCalendar({
	cellHalfHourRightClick : function(start, end, jsEvent) {

	}.bind(this)
});
```

**Comment by acerix** [comment]
You can attach event listeners in `eventRender`, eg:

https://codepen.io/anon/pen/qQjjaV?editors=0011

**Comment by SuperPat45** [comment]
Sorry, I was mistaken in my example, I fixed it.
It is not what I need. The right click callback is for a full background cell, not an event...

I try to use the dayRender callback to affect the context event on month view but it does not work on the whole cell: https://codepen.io/anon/pen/YRxPEm?editors=0011
```
  $('#calendar').fullCalendar({
    dayRender: function(date, $cell) {
      $('#calendar').find('[data-date='+date.format()+']').contextmenu(function(event) {
        console.log('right click on cell ' + date.format());
        event.preventDefault();
      });
    },
```

**Comment by acerix** [comment]
The problem is there are some invisible elements covering the top part of the cell.  I couldn't find a good way to get right click working on the whole cell, so I think that would need to be a new feature.

You can try `pointer-events:none;` so the clicks go through those elements, but then you can't click on events and also doesn't work in older IE.

**Comment by acerix** [comment]
Also there's this request which is the same but for agenda view:
https://github.com/fullcalendar/fullcalendar/issues/2748
↑
Could you please visit the link, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates?

**Comment by SuperPat45** [comment]
I will test the monkey patch soon

**Comment by adjioev** [comment]
Hello, 

I need the same functionality for v4 calendar. Is there an example somewhere for it or at least demo how to monkey patch v4?

Thanks alex
