### ISSUE TITLE
Ability to change the order of events with same start time but different durations

### ISSUE THREAD

**Issue by dghamir** [fullcalendar/fullcalendar#4378]
offer the ability to sort events with the same start date, by name or other property of the event

example

current result
i.imgur.com/Wm60zTi.png

expected result (when ordring events by title)
 i.imgur.com/iYZv5Rw.png

**Comment by acerix** [comment]
You can use [eventOrder](https://fullcalendar.io/docs/eventOrder) to change the default order.

**Comment by dghamir** [comment]
of course I used "eventOrder", but eventOrder only acts on events with same start date and duration
as shown in the images, the feature will allow sorting on events with the same start date without having the same duration
thanx

**Comment by f1nch** [comment]
Any updates on this request? Using v3.9 and I'm really hoping to be able to reverse the order of events with the same start time so that the longer duration is at the bottom.

**Comment by arshaw** [comment]
in v4, what you specify in `eventOrder` will override the ordering by start date

please see https://fullcalendar.io/docs/upgrading-from-v3#event-rendering
