### ISSUE TITLE
Hours separting counts

### ISSUE THREAD

**Issue by mrananyan** [fullcalendar/fullcalendar#4379]
I set the slotDuration 15 minutes ( `slotDuration: '00:15:00'` ) it's works but in hour row it's show 2 td but will be show 4. 1 is 15 minute.

P.S.
See red and blue rows in scrennshoot -> https://screenshots.firefox.com/T0hU4EMMJo2xMUiu/sargis.dentapp.ru

**Comment by acerix** [comment]
Would you be able to post a [runnable, stripped-down demonstration of the bug](http://fullcalendar.io/wiki/Reduced-Test-Cases/)? Would really appreciate it because the time saved reproducing will be time spent fixing.
