### ISSUE TITLE
Calendar event sorting with mixed offset

### ISSUE THREAD

**Issue by giRobert** [fullcalendar/fullcalendar#4380]
Hey there,

i'm running my fullcalendar with different offset dates. because the dates appear in different timezones.

I have these four events:

```
calendar_events = [
                        {
							id: 7407,
                            title: 'This should be on third postion but is second.',
                            start: '2018-04-25T19:30:00+01:00',
                            end: '2018-04-25T19:30:00+01:00'
                        },
                        {
							id: 7408,
                            title: 'This should be fourth position but is third',
                            start: '2018-04-25T19:30:00+00:00',
                            end: '2018-04-25T19:30:00+00:00'
                        },
                        {
							id: 7409,
                            title: 'This should be on first position but is forth',
                            start: '2018-04-25T19:30:00+02:00',
                            end: '2018-04-25T19:30:00+02:00'
                        },
                        {
							id: 7410,
                            title: 'This should be on second position but is first',
                            start: '2018-04-25T19:29:00+01:00',
                            end: '2018-04-25T19:30:00+01:00'
                        },
];
```

**the calendar shows them in this order:**

7410
7407
7408
7409

**but it should be:**

7409
7410
7407
7408

this is my fullcalendar setup: FullCalendar v3.9.0

```
if ( $('#calendar').length )
    {
        $('#calendar').fullCalendar({
            editable: false,
            eventLimit: true, 
            events: calendar_events,
            timeFormat: 'HH:mm',
            height: 600,
            displayEventEnd: true,
            eventOrder: "id"
        });
```

**Comment by acerix** [comment]
The event times should all be in the same timezone, ie. based on the `timezone` setting of the calendar.  You could add another parameter to the events (eg. "timezone") and use that to convert the times to local time to display them that way.

**Comment by giRobert** [comment]
Hi,

thanks for the reply. I dont see why I must use one timezone in the calendar when there is an option to add the offset of the "start". But anyway...

I like your approach and tried this right away.

i created a field "sortedTimestamp" for the events including the perfectly sorted timestamp.
and on calendar the init I set: eventOrder: ["sortedTimestamp"] or eventOrder: "sortedTimestamp" (i tried both).

still it didnt work in total. there was a change but the sorting is not right unfortunately.

i putted the timestamp into the title to make it easier to see that its not sorted right:

![sorting](https://user-images.githubusercontent.com/43425628/48807129-e0bab600-ed1c-11e8-8b47-bf83b1879648.JPG)

Is that a bug? I dont see how I can influence this any further.

**Comment by acerix** [comment]
`eventOrder` only works for events with the same start time (in UTC).

I suggest using UTC for all the event times which will make them show in the correct order, then each event can have a `timezone_offset` like `-5`, `+2`, etc that you would add to the start time before displaying it in `eventRender`.

**Comment by giRobert** [comment]
oh I see...

can you show an example of what you are describing? I mean i would need to use different times. one time for displaying (the actual input) and one time for sorting (including the offset).

**Comment by acerix** [comment]
Here's a quick demo, I added `moment-timezone` to make it simpler:

https://codepen.io/anon/pen/oQEGgd?editors=0010

**Comment by giRobert** [comment]
Thanks a lot for the assistance but I tried it one hour now to get it running the way I'd like to.
I tried your way mentioned in the example but its giving me a big date-mess. I added instead of CET/EET the exact timezone like "EUROPE/PARIS" etc... Also I tried it with and without offset (eg. +01:00) in the "start" parameter.

Let me describe again what I am trying to do.

I have a huge data set of events with various mixed timezones. example:

- Event 1: 16:00 gmt+0 (GMT LONDON)
- Event 2: 16:00 gmt+1 (CET PARIS)
- Event 3: 16:00 gmt-1 (GMT AZORES)

now I want to display them in the calendar like this and in exactly this order:

- 16:00 Event 2
- 16:00 Event 1
- 16:00 Event 3

i dont want the time to change. I only want it to get ordered in the physically right order. For the viewer of the calendar only the LOCAL event time matters. and that is 16:00 . always. but its important which 16:00 happends first.

**Comment by acerix** [comment]
Assuming you only want that for Month view, I think it would work better to make them "all day" events (with only a start date, not a time) and then use eventOrder to put the events in order by their timezone. Then you could add the local start time to the event title, or add it using eventRender.
