### ISSUE TITLE
Callbacks on mobile devices

### ISSUE THREAD

**Issue by adver89** [fullcalendar/fullcalendar#4388]
I found out issue that appears only on mobile devices. When I click on some row in a day view, dayClick and select callbacks should be fired. And on desktop they do. But on Android Chrome nothing happens until I change day, month or view type (from day to month). So all this callbacks are fired when new view is rendered. 

I've tried to debug. And on the desktop after I click on the timeslot, DragListener.prototype.endInteraction is called with event type 'mouseup'. On the mobile this function is called only when I switch the view. It looks like touch event is detected as a dragging.

It's hard to replicate this issue on the jsfiddle. Because even the example from fullcalendar site is working as expected. But maybe this is known problem or someone have had similar issue?

Configuration:

> $(document).ready(function() {
    $('#calendar').fullCalendar({
        height: 450,
        eventLimit: 4,
        editable: false,
        locale: 'pl',
        longPressDelay: 10,
        selectLongPressDelay: 10,
        selectable: true,
        header:{
            left: 'title',
            center: '',
            right: 'today prev,next'
        },
        viewRender: self.viewRender,
        dayClick: function(date, jsEvent, view, resourceObj) {
            console.log('---> day click 2');
        },
        timezone: 'local',
        aspectRatio: 1.6,
        selectHelper: true,
        select: function(start, end) {
            var title = prompt('Event Title:');
            var eventData;
            if (title) {
              eventData = {
                title: title,
                start: start,
                end: end
              };
            $('#calendar').fullCalendar('renderEvent', eventData, true); // stick? = true
            console.log('select clicked:', start, end);
            }
            console.log('---> day select 2');
            self.showAddEventDialog(date);
        },
        eventLimit: true
    })
});

Dependencies:

> "dependencies": {
    "angular-joyride": "^1.0.10",
    "angular-material-badge": "^1.2.9",
    "bootstrap": "^3.3.7",
    "intro.js": "^2.9.3",
    "jquery-parallax.js": "^1.5.0",
    "jquery.ui.touch": "0.0.1",
    "save-dev": "^2.0.0",
    "webpack": "^3.10.0"
  },
  "devDependencies": {
    "@uirouter/angularjs": "^1.0.13",
    "angular": "^1.5.8",
    "angular-animate": "^1.5.8",
    "angular-aria": "^1.5.8",
    "angular-cookies": "^1.5.8",
    "angular-fullpage.js": "^0.2.6",
    "angular-material": "^1.1.4",
    "angular-messages": "^1.5.8",
    "angular-resource": "^1.5.8",
    "angular-route": "^1.5.8",
    "angular-translate": "^2.18.1",
    "angular-ui-bootstrap": "^2.5.6",
    "angular-ui-calendar": "^1.0.2",
    "babel-loader": "^7.1.2",
    "babel-minify-webpack-plugin": "^0.2.0",
    "babel-plugin-angularjs-annotate": "^0.8.2",
    "clean-webpack-plugin": "^1.0.0",
    "copy-webpack-plugin": "^4.5.1",
    "css-loader": "^0.28.9",
    "extract-text-webpack-plugin": "^3.0.2",
    "file-loader": "^1.1.6",
    "font-awesome": "^4.7.0",
    "font-awesome-sass-loader": "^2.0.1",
    "font-awesome-webpack": "0.0.5-beta.2",
    "fullcalendar": "^3.9.0",
    "fullpage.js": "^2.9.7",
    "html-loader": "^0.5.5",
    "html-minify-loader": "^1.3.0",
    "html-webpack-plugin": "^3.2.0",
    "jquery": "^3.3.1",
    "ng-file-upload": "^12.2.13",
    "ng-template": "^1.0.0",
    "ngtemplate-loader": "^2.0.1",
    "raw-loader": "^0.5.1",
    "roboto-fontface": "^0.8.0",
    "statuses": "^1.4.0",
    "style-loader": "^0.20.1",
    "url-loader": "^0.6.2",
    "webpack-bundle-analyzer": "^2.13.0",
    "webpack-dev-server": "^2.11.3"
  }

**Comment by acerix** [comment]
Would you be able to post a [runnable, stripped-down demonstration of the bug](http://fullcalendar.io/wiki/Reduced-Test-Cases/)? Would really appreciate it because the time saved reproducing will be time spent fixing.

If you can't reproduce, try turning off other CSS and JavaScript to track down what is interfering.

**Comment by adver89** [comment]
So far I found out that the problem is with Angular Material 1.1.14. I've tried to turn off every library, one by one. And when I've added Angular Material it stopped working. Later I'll try to move piecies of my code to jsfiddle.

**Comment by adver89** [comment]
Unfortunately I couldn't replicate described case. I've tried a lot of configurations, I've even tried to copy files generated by webpack... But every time it works on jsFiddle. I know it's hard analyze anything without code, but maybe someone has similar case. Below you can see described case:
![ice_video_20181129-112130 1](https://user-images.githubusercontent.com/453670/49246264-5122a080-f3c9-11e8-8ed2-ebf30164c244.gif)

**Comment by adver89** [comment]
When I use version 3.1.0 hadlers works as expected. From version 3.2.0 something has impact on this behaviour. I've found this commit: https://github.com/fullcalendar/fullcalendar/commit/488107744c78da76552f916daa2d18c78476f591
And when I change back from 
`this.listenTo(globalEmitter, {` 
to
`this.listenTo($(document), {`
it works.

**Comment by wumke** [comment]
> When I use version 3.1.0 hadlers works as expected. From version 3.2.0 something has impact on this behaviour. I've found this commit: [4881077](https://github.com/fullcalendar/fullcalendar/commit/488107744c78da76552f916daa2d18c78476f591)
> And when I change back from
> `this.listenTo(globalEmitter, {`
> to
> `this.listenTo($(document), {`
> it works.

I'm also having issues with select event on a specific device. While searching I've found https://github.com/fullcalendar/fullcalendar/issues/4521 which has same browser and OS as my device. Are the issues related?
(I use latest version 4.3.1 which works fine with mouse and also worked on ipad/safari... which made me think it would work on any touch device.)
