### ISSUE TITLE
locale Days number in month view in Arabic language

### ISSUE THREAD

**Issue by ginaGeorgee** [fullcalendar/fullcalendar#4389]
I'm using  fullcalendar with Typescript and the local for Arabic language worked but not with all the items on the page so I override some elements to display the Arabic language such as the button text ,but the issue is only the numbers in the month view shows in English and there is no item to override this element

so any help would be much appreciated here is my code
this.calendarOptions = {
  editable: true,
  eventLimit: false,
  locale:'ar',
  allDayDefault:true,
  nowIndicator: true,
  buttonIcons: true, // show the prev/next text
  navLinks: true, // can click day/week names to navigate views
  header: {
    left: 'prev,next today',
    center: 'title',
    right: 'month,agendaWeek,agendaDay,listMonth'
  },
  selectable: true,
  isRTL:true,
  events: [],
  allDayText: "طوال اليوم",
  buttonText: {
    today:'اليوم',month:'شهر',week:'أسبوع',day:'يوم',list:'أجندة'
  },
  dayNames:['السبت','الأحد','الأثنين','الثلاثاء','الأربعاء','الخميس','الجمعة'],
  weekNumberTitle:'أسبوع',
  eventLimitText: "أخرى",
  timezone:'Cairo',
  views: {
    month: {
      eventLimit: 2
    }
  },

  };
}

**Comment by acerix** [comment]
Would you be able to post a [runnable, stripped-down demonstration of the bug](http://fullcalendar.io/wiki/Reduced-Test-Cases/)? Would really appreciate it because the time saved reproducing will be time spent fixing.

It sounds like you might be missing the locale file, this example has the day numbers translated:

https://fullcalendar.io/releases/fullcalendar/3.9.0/demos/locales.html

**Comment by acerix** [comment]
You need to include locale-all.js (or the specific locale file) like in the example.

**Comment by ginaGeorgee** [comment]
yes i can see its loaded in the full calendar folder

**Comment by ginaGeorgee** [comment]
i just want to note that i am using typescript not jquery

**Comment by acerix** [comment]
This page has some examples for typescript which might help:  https://fullcalendar.io/docs/typescript

It's best if you can provide a runnable demo showing the issue.
