### ISSUE TITLE
Limit Events per timeGridDay and Place Overflow Events in Duplicate Slat

### ISSUE THREAD

**Issue by Thundax** [fullcalendar/fullcalendar#4391]
The feature we're trying to develop is a simple one on the surface. We're trying to create a functionality that limits the number of events that will stack horizontally in any given time slat in an agenda day view. This is similar to the "eventLimit" functionality you already have in the month view. However, our client has specifically requested that once this event limit for a horizontal slat is exceeded that any overflowing events begin to stack in a duplicate slat placed below the original which also follows this limit rule. The end result would be a "limitInteger" x "yRows" 2-dimensional grid of events that all start and end at the same time.

We are modifying the fullcalendar.js file directly and we are working in v4.0.0-alpha.2 because working in previous versions was far more difficult and we couldn't figure out where to start. To achieve the slat duplication and to trigger based on the number of events we are using "if (seriesBacwardPressure > timeSlatEventLimit - 1)" in "TimeGridEventRenderer.prototype.computeFgSegForwardBack". This then calls our newly created function "TimeGridEventRenderer.prototype.stackOverflowEvents". This custom function of ours works pretty well so far. It duplicates the slat, makes the new slat an "fc-minor", places it below the original, increments the "PositionCache" for tops and bottoms, adds the new slat to the slats array property in the position cache, and moves the dropped overflowing event down into the new slat. 

However, there are a few issues we're having trouble resolving which I'll detail below (images):

1. The previous 3 events in the original slat do not rerender and adjust their horizontal span when we move the overflowing event down into the duplicate slat. This is because we're using "seg.top", "seg.bottom", and the CSS "top:" and "bottom:" style attributes to move the event down into the duplicate slat and this does not trigger any of the events you are using to rerender events. We need to know which event to call, and how, in order to fix this issue. Note in the images below that the original 3 events in the 12:00pm slat are still rendered as thought there's a 4th event in that slat.

Before:
![image](https://user-images.githubusercontent.com/26488640/49165951-6384d780-f300-11e8-999e-1690fdd36108.png)
After:
![image](https://user-images.githubusercontent.com/26488640/49165971-697ab880-f300-11e8-8511-5b06c34bf99e.png)

2. The introduction of the new slat places all events occurring below and afterwards off in position by -1 slat and +00:30:00. We should be able to resolve this issue by moving each event downward in code and triggering the same event we need to trigger to resolve issue #1, or even just triggering the same rerendering event that would resolve issue #1. We attempted to resolve this issue by using a conditional integer offset in "TimeGrid.prototype.computeTimeTop" to offset the index of the position array element being grabbed according to the number of "splices" we had inserted before a given event. However, this caused issue #3.

Example: (Here you can see that an event following the duplicated and spliced in slat is off by -1 slat and +00:30:00. We checked to see if this time offset was persistent after moving these events as a user would with the mouse and it is, so we applied the offset solution mentioned above.)
![image](https://user-images.githubusercontent.com/26488640/49165992-73042080-f300-11e8-8b4f-2c3b84af98da.png)

3. After applying the index offset solution in "computeTimeTop" all times after the duplicated slat are correct but we now experience an undesirable behavior on the duplicated slat which we do not know how to fix. 

Example: (Any event which the user tries to drag into the duplicate slat does not display correctly or read the correct time once the fix for issue #2 was applied. The "Meeting" event here should be in the duplicate slot and running from 12:00 to 12:30. Neither the duplicate slot nor the slot below it is usable properly after we apply our time offset fix.)
![image](https://user-images.githubusercontent.com/26488640/49166001-77c8d480-f300-11e8-909b-dc7c08c8cc2a.png)

Here's the modified code.
https://pastebin.com/WpMKd6bF

**Comment by arshaw** [comment]
it'd be great to get a runnable demo and also a more succinct description of this bug (feature?)
