### ISSUE TITLE
[v4-alpha.2] dateClick event returning one day less than expected

### ISSUE THREAD

**Issue by elias-garcia** [fullcalendar/fullcalendar#4392]
### Bug Report

Hi! I'm using fullcalendar with Angular and I noticed that when you click some calendar date and `dateClick` event fires, it's returning one day less than expected. For example, if you click on `28-11-2018` it returns `27-11-2018`.

You can see a repro here (you can see the `event.date` log in the console):

https://stackblitz.com/edit/angular-rg444q

**Comment by acerix** [comment]
The days start at midnight UTC but the date is rendered in local-time so it makes sense that it would show the day before if your timezone is being UTC.  You can use `event.dateStr` to get the actual date.

**Comment by elias-garcia** [comment]
Yes I know @acerix ! The problem was that all works fine, but eventually, the click is detected on the previous day in the row, so it triggers the day before. I was doing some tests because I can only reproduce it in my local machine (on a big project) but not in the StackBlitz.

I'll try to reproduce it in StackBlitz, but meanwhile I've recorded a [demo of the issue](https://streamable.com/zyvti) from my project so you can see what I'm talking about. Also I forgot to mention that I'm using the native Date objects and `es` locale. Also, my Chrome version used in the demo is `70.0.3538.77`.

**Comment by gwannemacher** [comment]
I was able to repro, even with UTC dates.  I realized I had a side nav that was rendered after the calendar was rendered, so the `dateClick` function was returning the dates pre side nav.

**Comment by elias-garcia** [comment]
Hi @gwannemacher , my problem also happens with a sidenav (in my case from `Angular Material` library and a responsive sidenav. I went back to fullcalendar v3 and all is working fine and as expected, so I can confirm that's a bug in v4.

**Comment by arshaw** [comment]
I couldn't reproduce the bug, neither in a static file or in a codepen.

here's what i tried: https://codepen.io/arshaw/pen/ebRJwz?editors=0011
(i'm simulating a dynamic left margin being added to the div after calendar initialization)
(i thought the width of the demo in codepen was better than other code playgrounds)

let me know if you can reproduce in some type of code playground. otherwise, i can't fix it.

**Comment by Hoakie** [comment]
@arshaw,  The issue I noticed is not handling the dateClick event, but rather when using navLinks:true.  When you select the link in the calendar, it takes you to the previous day.

https://codepen.io/hoakie/pen/ZVvzrg

**Comment by arshaw** [comment]
@Hoakie , in that case your issue is probably #4467

I'll keep this issue open to address **dateClick** ... though I won't start working on it until i see a recreation

**Comment by arshaw** [comment]
i believe this is an issue of printing the date via toISOString or toUTCString when the date is in local time, thus it will show as the day before if you are east of the prime meridian (the author of this issue seems to be in Spain). the solution is to print it in local time, or just use `dateStr`

**Comment by luncia** [comment]
Hello. I'm seeing this issue still happening. I just recreated it today, using your own demo code with no modifications. 

https://codepen.io/anon/pen/JzpwLy?&editable=true&editors=001

I started with the reduced template for v4 and was able to reproduce using it.

**Comment by acerix** [comment]
It was fixed a week ago, but is not released yet

https://github.com/fullcalendar/fullcalendar/commit/83ffa5a082a1749a58ae568134e487473d6cc432
