### ISSUE TITLE
renderBgRanges does not filter segs

### ISSUE THREAD

**Issue by park896** [fullcalendar/fullcalendar#4394]
The renderBgRanges method does not filter the segs array with the same logic as the renderFgRanges. The end result is that it blows up when rendering a date that is filtered out by returning false from renderEvent for rucurring background ranges using dow. The below code is a quick solution to the problem by simply calling buildSegEls with the same arguments. I am submitting the below code with the hope that you accept the bug report despite me not building a reproduction as my intention is to help you improve your product.

    EventRenderer.prototype.renderBgRanges = function (eventRanges) {
        var eventFootprints = this.component.eventRangesToEventFootprints(eventRanges);
        var segs = this.component.eventFootprintsToSegs(eventFootprints);
        // render an `.el` on each seg
        // returns a subset of the segs. segs that were actually rendered
        if (this.fillRenderer) {
            var _this = this;
            segs = this.fillRenderer.buildSegEls('bgEvent', segs, {
                getClasses: function (seg) {
                    return _this.getBgClasses(seg.footprint.eventDef);
                },
                getCss: function (seg) {
                    return {
                        'background-color': _this.getBgColor(seg.footprint.eventDef)
                    };
                },
                filterEl: function (seg, el) {
                    return _this.filterEventRenderEl(seg.footprint, el);
                }
            });
        }
        if (this.renderBgSegs(segs) !== false) {
            this.bgSegs = segs;
        }
    };

**Comment by acerix** [comment]
Thanks for the report and solution.  We do need a [runnable, stripped-down demonstration of the bug](http://fullcalendar.io/wiki/Reduced-Test-Cases/) to proceed though.
