### ISSUE TITLE
AngularJS locale ovewrite FullCalendar locale

### ISSUE THREAD

**Issue by Tarcisiofl** [fullcalendar/fullcalendar#4396]
I'm using FullCalendar with AngularJS and the lang parameter ´locale´ for each language is not showing properly for months and days due to it getting these data from the AngularJS locale as below:

![screencapture-192-168-99-100-web-2018-11-30-17_34_51](https://user-images.githubusercontent.com/1232004/49310900-cb851a80-f4c6-11e8-9543-98cf4cb047d5.png)

How can I avoid this conflict?

**Comment by acerix** [comment]
Would you be able to post a [runnable, stripped-down demonstration of the bug](http://fullcalendar.io/wiki/Reduced-Test-Cases/)? Would really appreciate it because the time saved reproducing will be time spent fixing.

**Comment by Tarcisiofl** [comment]
@acerix I'm trying to provide it!

**Comment by Tarcisiofl** [comment]
I found out the issue, it was override by ui-calendar due to an old script!
Thank you.
