### ISSUE TITLE
jalali (persian calendar)

### ISSUE THREAD

**Issue by bahmansh** [fullcalendar/fullcalendar#4397]
I have read last issues about my problem.
But I did not get good response.

In current there are two calendar that support persian fullcalendar that both are using [moment-jalali](https://github.com/ehsandanesh/moment-jalaali) for this purpose, [this](https://github.com/ehsandanesh) that is based on fullcalendar 2.6 and [that](https://github.com/Natico/fullcalendar-Jalaali/) is based on fullcalendar 3.0.1 .

Now new fullcalendar version is 3.9.0, and certainly it have been changed so much from version 2.6 and 3.0.1 .

I think is better that your calendar support popular calendar such as persian calendar to every time that you release new version it contain it too and anyone can use it without worrying about converting it's functions for supporting his/her calendar.

Thanks a lot for your job.

**Comment by bahmansh** [comment]
I saw version 4 alpha, and it support jalali calendar (locale fa).
It is so good.
Will it remain in final version?
![ashampoo_snap_ 11 1397_13h27m22s_002_](https://user-images.githubusercontent.com/19801131/49338431-31dc7b00-f636-11e8-8f29-b1d371646de0.png)

**Comment by acerix** [comment]
I believe this existing ticket captures this need:
https://github.com/fullcalendar/fullcalendar/issues/1813
↑
Could you please visit the link, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates?

**Comment by bahmansh** [comment]
No man, I think you could not understand my purpose.

Please look at images and compare them again.
thanks.

**Comment by acerix** [comment]
There is already an open feature request to add Jalalia support, the other calendars you mentioned are not part of FullCalendar.   Let me know if you are requesting something different than  https://github.com/fullcalendar/fullcalendar/issues/1813
