### ISSUE TITLE
stop scroll to focus buttons when popup closed

### ISSUE THREAD

**Issue by ryannz** [fullcalendar/fullcalendar#4405]
I am trying to stop the calendar from scrolling up after my popup is closed. This issue is caused by the focus on one of the button on the header. To reproduce the issue,
1. first click on one of the buttons on the header, 
2. try to scroll down until you cannot see the buttons in the header and click on of the date
3. click anywhere outside the popup to close the popup and it will scroll up to the focus button. 

 Is there a way to stop the scrolling and keep the scroll position as it is. Here is the jsfiddle.

https://jsfiddle.net/kd7e2xpc/35/

And here is the video clip

https://www.screencast.com/t/fzKgWdZj

thanks

**Comment by acerix** [comment]
I can see the issue but it seems to that jQuery Popup Overlay is doing the scrolling.  You could try another popup library or maybe fix that with the settings.

**Comment by ryannz** [comment]
Thanks for the reply. Is there a function in fullcalendar to clear the focus of those buttons before the popup is opened?

**Comment by acerix** [comment]
Not built-in, but `blur()` on the whatever is focused should work, or just `focus()` on something else.

**Comment by ryannz** [comment]
Hi thanks for pointing me to the right direction. Here is how I could fix this: 

$('.fc-button').blur();
