### ISSUE TITLE
Long event titles overlap in timeline view

### ISSUE THREAD

**Issue by pizzadev** [fullcalendar/fullcalendar#4407]
Hi Fullcalendar Team.

I have long names in event title.  Sometimes title of event can overlap next event. How can I send an event to the next line if prev. event title overlapping next event?

How it looks like now:
![4](https://user-images.githubusercontent.com/5230858/49949267-85cc4700-fef5-11e8-8484-754cf01b7d62.png)

How It should work:
![3](https://user-images.githubusercontent.com/5230858/49949245-7b11b200-fef5-11e8-8f67-7c0b9c6080ae.png)

Looking forward to your answer,
Thank you!

**Comment by acerix** [comment]
That is not built-in and I'm not sure I understand how you want it to work, you want the 10 am event to show below in the 8 am timeslot?  

If you want the text to wrap to the next line, I think that would need to be a custom view.

**Comment by pizzadev** [comment]
Sorry, my fault. Updated the screenshots. In short: if name is too long - event should go to the next line in this resource. here is a codepen: 
https://codepen.io/anon/pen/OrMMQQ

**Comment by pizzadev** [comment]
How to calculate event width, equal to long name of prev.event ?

**Comment by acerix** [comment]
You can also set `editable:false` in the event object:

https://fullcalendar.io/docs/event-object

**Comment by kgilden** [comment]
Ideally the overflow should be hidden IMHO and hovering on the event could reveal the full title. But `overflow: hidden` will sadly currently break the nifty `position: sticky` effect.

**Comment by arshaw** [comment]
this seems to not be happening in the latest v3: https://codepen.io/arshaw/pen/vYLJXZQ?editable=true&editors=001

and probably in v4/v5 as well
