### ISSUE TITLE
在webkit4.7.4版本中无法解析fullcalandar3.9、3.5、3.0多个版本

### ISSUE THREAD

**Issue by dopayz** [fullcalendar/fullcalendar#4412]
### fullcalandar3.9
在webKit中解析会报如下错误：
![image](https://user-images.githubusercontent.com/30381975/50206633-f0263100-03a6-11e9-9c90-a496b7e0dbe4.png)
### fullcalandar3.5
同上
### fullcalandar3.0
同上

**Comment by acerix** [comment]
Would you be able to post a [runnable, stripped-down demonstration of the bug](http://fullcalendar.io/wiki/Reduced-Test-Cases/)? Would really appreciate it because the time saved reproducing will be time spent fixing. 

Also, which browser do you get this error in?
