### ISSUE TITLE
[v4-alpha.2] Cannot read property 'getEvenyById' of undefined

### ISSUE THREAD

**Issue by palikman** [fullcalendar/fullcalendar#4413]
document.addEventListener('DOMContentLoaded', function() {
	let calendarEl = document.getElementById('calendar');

	let options = {
		header: {
			left: 'title',
			center: '',
			right: 'prev,next'
		},
		height: 'parent',
	};

	let calendar = new FullCalendar.Calendar(calendarEl, Object.assign(options));

	calendar.render();

});

$(document).ready(function () {
	$('#calendar').calendar.getEvenyById(2193);
});

**Comment by acerix** [comment]
Would you be able to post a [runnable, stripped-down demonstration of the bug](http://fullcalendar.io/wiki/Reduced-Test-Cases/)? Would really appreciate it because the time saved reproducing will be time spent fixing.

**Comment by arshaw** [comment]
this is almost definitely a problem with your code. i can tell from the misspelling... "getEvenyById"
