### ISSUE TITLE
Qtwebkit could not normally execute fullcalendar.js

### ISSUE THREAD

**Issue by dopayz** [fullcalendar/fullcalendar#4415]
### Qtwebkit version
![1](https://user-images.githubusercontent.com/30381975/50272819-ec141500-0473-11e9-9239-ceec2ada12d2.png)
![2](https://user-images.githubusercontent.com/30381975/50272841-ffbf7b80-0473-11e9-9806-ee4bf7b496a8.png)

### Fullcalendar version
![3](https://user-images.githubusercontent.com/30381975/50272957-457c4400-0474-11e9-88e6-47363a198e43.png)

### Error
![4](https://user-images.githubusercontent.com/30381975/50273073-88d6b280-0474-11e9-95e0-775fb7009df7.png)

### Notice
Sorry, I can't provide a working demo. If the information is not complete, please forward it and I will try my best to provide it.I have spent too much time on it, please reply to me, thank you!

**Comment by acerix** [comment]
Maybe updating to the current version would help, 3.0 is quite old.  We need a way to reproduce the error, it's best if you can provide a [runnable, stripped-down demonstration of the bug](http://fullcalendar.io/wiki/Reduced-Test-Cases/).
