### ISSUE TITLE
fc-today class is not added to date labels

### ISSUE THREAD

**Issue by quasiunafantasia** [fullcalendar/fullcalendar#4419]
https://codepen.io/quasiunafantasia/pen/BvWddb
the orange color is applied to current day label in `week view` but it not applied for `customDay view`.
when using a scroller, the day labels are added dynamically and there is no way to handle this event.
it means that its impossible to highlight the today's date - looks like it can only be handled when rendering those absolutely-positioned  `.sfc-cell-text.fc-following` spans.
adding a proper class(`fc-today`) like its done for the week/month views should solve this problem, shouldn't it?

**Comment by acerix** [comment]
There is no `fc-today` in timeline view, are you requesting that as a new feature?  You could highlight the current day using a background event.

**Comment by quasiunafantasia** [comment]
yeah, that also can be considered as a feature request
i dont think i can handle day-label highlighting with a background event
updated the codepen to actually show the difference: current day label is highlighted for week but is not highlighted for custom day view

**Comment by quasiunafantasia** [comment]
@acerix looking forward to hearing any response

**Comment by arshaw** [comment]
in v5, the `fc-slot-today` class is sprinkled around the DOM in all the right places
