### ISSUE TITLE
[v4-alpha.3] [recurring event] Cannot read property 'start' of null

### ISSUE THREAD

**Issue by aitboudad** [fullcalendar/fullcalendar#4422]
### Bug Reports
Hi, I've noticed a regression after upgrading from alpha.2 that concern recurring event,
please check the following reproduction example:

https://stackblitz.com/edit/typescript-kchkwr?file=index.ts
By clicking on the Prev button the following error is thrown:
```console
Cannot read property 'start' of null
```

**Comment by arshaw** [comment]
I fixed this bug in the `v4` branch: https://github.com/fullcalendar/fullcalendar/commit/59fce29f66d42746acdc77cb029f76c8fd305a7b

I'm closing this issue to signify that it's been fixed in the dev branch. will comment again when it's released

**Comment by arshaw** [comment]
this has been addressed and released in [4.0.0-alpha.4](https://github.com/fullcalendar/fullcalendar/releases/tag/v4.0.0-alpha.4)
