### ISSUE TITLE
[v4-alpha.3] [nowIndicator] Sets to local timezone after automatic update

### ISSUE THREAD

**Issue by harryy2510** [fullcalendar/fullcalendar#4424]
### Bug Reports
Specifying a different timezone other than local makes the nowIndicator behave differently. After initializing with a different timezone, nowIndicator is positioned at current time in that timezone, but navigating on other day and coming back to today repositions it to local current time.

### Steps to reproduce

1. Goto [Stackblitz](https://stackblitz.com/edit/js-ilq3k7)
2. Change the timezone to something other than your local machine
3. Check current time and indicator
4. Navigate to some other day and navigate to today again
5. Check current time again. It should be local current time.

**Comment by acerix** [comment]
Thanks for the detailed report.

The indicator shows at the wrong time for me even though the timezone in your example is local for me but moves to the correct local time after navigating.

**Comment by harryy2510** [comment]
Any update on this in new version?

**Comment by arshaw** [comment]
for numbers 2 and 3 in your recreation steps, are you sure you're able to get the timeZone indicator to something other than local or UTC? that is supposed to be impossible if you don't have a named timezone implementation set up (in [this article](https://fullcalendar.io/docs/timeZone) the section "With a TimeZone Plugin")

when there is no named timezone implementation, it falls back to displaying the indicator at local time. i think you're just seeing the fallback behavior. but i don't understand how initially you're seeing something else
