### ISSUE TITLE
[v4] bootstrap 4 button class

### ISSUE THREAD

**Issue by piernik** [fullcalendar/fullcalendar#4428]
Is it possible to use custom class for buttons in bootstrap 4 theme? 
Now You're using `btn btn-primary active` I want to use `btn btn-outline-secondary`.
Maybe You can provide api where we can define own html?
That api could be for icons, buttons, button-groups or even whole header or event

**Comment by piernik** [comment]
Edit: I will create my own header

**Comment by jongbonga** [comment]
is there actually a way to change the classes?

**Comment by nateweiss** [comment]
Hi @jongbonga, I found that the following works. I'm not sure if this is documented anywhere or officially supported though:

`FullCalendar.BootstrapTheme.prototype.classes.button = 'btn btn-sm btn-secondary'`

...if you do this before calling `new FullCalendar`, it seems to pick up the classes just fine. Without the above, it defaults to `btn btn-primary`. In the currently shipping code, that's defined at Line 12 here: https://github.com/fullcalendar/fullcalendar/blob/master/packages/bootstrap/src/main.ts#L12

**Comment by schmoove** [comment]
For anyone using FullCalendar 6 with `themeSystem: "bootstrap"`, this is now:

`FullCalendar.Bootstrap.Internal.BootstrapTheme.prototype.classes.button = 'btn btn-default';`
