### ISSUE TITLE
Debounce fetching new events

### ISSUE THREAD

**Issue by piernik** [fullcalendar/fullcalendar#4430]
I have two different sources - google calendar and my own backend used with events as function (https://fullcalendar.io/docs/v4/events-function).

Can You introduce debounce option form triggering all operations concerning event fetching?
Something like `fetchingDebounceTime`. If set all fetching operations would wait until view is not changed for given amount of time.

**Comment by acerix** [comment]
Just to confirm, you are looking for a delay after the view is changed before any events are fetched so that none would be fetched if the view is changed again before that delay?

**Comment by acerix** [comment]
I believe this existing ticket captures this need:
https://github.com/fullcalendar/fullcalendar/issues/268
↑
Could you please visit the link, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates?
