### ISSUE TITLE
Show events without overlapping in year view

### ISSUE THREAD

**Issue by abhiindian** [fullcalendar/fullcalendar#4431]
Hi Fullcalendar Team,

I am using version v2.2.7. Our team has customized the full calendar to show year view with event data overlapping across months. This causing the same event to be shown in both overlapped months as shown below as an example.

![image](https://user-images.githubusercontent.com/7735653/50554574-f4294b80-0ce2-11e9-8aff-dcd411b174a9.png)

Is there any solution where we can show an event without overlapping the event for next/previous months.
We have already tried "eventOverlap: false", but it didn't work.

**Comment by acerix** [comment]
Are you looking to have the event in your example not show up on the "greyed out" days?  Eg. in January it would appear to end on the 31st and in Feb it would start on the 1st?

**Comment by abhiindian** [comment]
> Are you looking to have the event in your example not show up on the "greyed out" days? Eg. in January it would appear to end on the 31st and in Feb it would start on the 1st?

Yes.

**Comment by abhiindian** [comment]
Thanks for your reply....at least can we have an additional CSS class attached to events shown in greyed out dates, so that we can hide them using CSS. It will be of great help.

**Comment by inacio-luizalabs** [comment]
The example mentioned above with defaultview 'year' not work google chrome

This year fullcalendar example only works in mozila firefox, in chrome it breaks in the year 2021. can anyone help me understand why this?

http://embed.plnkr.co/xhahIV/

**Comment by arshaw** [comment]
my advice would be to use this setting: https://fullcalendar.io/docs/showNonCurrentDates

or wait until this is implemented: https://github.com/fullcalendar/fullcalendar/issues/1140

**Comment by vijayvargiyaakshay** [comment]
Hello, full calendar team, year view is a very good and awesome feature. But this is implementing only for the lower version. I have also used fullcalendar.js to implement year view. 
But in year mode every date of every month is behind by one day but in month or day or week mode everything is good. 
Can please anyone tell me what is the problem.
![Screenshot from 2019-07-31 13-04-53](https://user-images.githubusercontent.com/51439770/62192825-fdbb8480-b393-11e9-9155-4c8365f50b18.png)
