### ISSUE TITLE
[V4 alpha] Single way data binding not working on angular when calendar is set

### ISSUE THREAD

**Issue by Mortaurat** [fullcalendar/fullcalendar#4433]
Hello,
I got a component which is composed of a calendar (fullcalendar.io V4) and a simple text which must contain informations of an event. Fullcalendar integrate a function which make me able to know which element has been clicked. This is the function below :
```
 eventClick: function (info) {
    this.modal_title = "Reservation : ";
    this.modal_start = info.event.start;
    this.modal_end = info.event.end;

    console.log("start : " + this.modal_start);
    console.log("end : " + this.modal_end);
  }
```

In this function i have some variable called modal_title/start/end. In this variable i store my info.event data in order to displayed it into my html view. The console.log is only here for debug and works perfectly.

In the html part of my component I just display the calendar and variables. Here is the full code :
```
<div id="calendar"></div>

<p>title : {{modal_title}}</p>
<p>arival : {{modal_start}}</p>
<p>leave : {{modal_end}}</p>
```

I got only this displayed...
```
title : plop

arival :

leave :
```

I don't understand why this simple databinding is not working. It's probably due to a conflict with FullCalendar, but i don't understand how i can fix it. Thanks for your help.

Here is the full code of my component.ts
```
//general import
import { Component, OnInit, Input } from '@angular/core';
import { ViewChild } from '@angular/core';

//import pour modal
import { TemplateRef } from '@angular/core';

//service
import { IcsService } from '../../_Services/ics.service';
import { visitAll } from '@angular/compiler';

//variables
declare const FullCalendar: any;
declare const $: any;

@Component({
    selector: 'app-scheduler',
    templateUrl: './scheduler.component.html',
    styleUrls: ['./scheduler.component.css']
})
/** scheduler component*/
export class SchedulerComponent implements OnInit {
  ressources: any;
  event: any;
  modal_title: any = "plop";
  modal_start: any;
  modal_end: any;
  /** scheduler ctor */
  constructor(private ics_service: IcsService) {}

  ngOnInit() {
    this.ics_service.GetAllRessources().subscribe(result => {
      this.ressources = result;
      console.log(this.ressources);
      this.ics_service.GetAllEvents().subscribe(result => {
        this.event = result;
        console.log(this.event);
        this.calendar();
      });
    });

  }

  calendar() {
    var calendarEl = document.getElementById('calendar');
    var calendar = new FullCalendar.Calendar(calendarEl, {
      schedulerLicenseKey: 'CC-Attribution-NonCommercial-NoDerivatives',
      locale: 'fr',
      now: Date.now(),
      defaultDate: Date.now() - 172800000, //date où sa commence le schedule - 2 jours
      editable: false,
      aspectRatio: 2,
      header: {
        left: 'today prev,next',
        center: 'title',
        right: 'Scheduler, month',
      },
      titleFormat: { // will produce something like "Tuesday, September 18, 2018"
        month: 'long',
        year: 'numeric',
        day: 'numeric',
        weekday: 'long'
      },
      defaultView: 'Scheduler',
      views: {
        Scheduler: {
          type: 'timeline',
          duration: { days: 20 },
        }
      },
      resourceLabelText: 'Rooms',
      height: 'auto',
      resources: this.ressources,
      events: this.event,
      eventClick: function (info) {
        //document.getElementById("openModalButton").click();
        this.modal_title = "Reservation : ";
        this.modal_start = info.event.start;
        this.modal_end = info.event.end;

        console.log("start : " + this.modal_start);
        console.log("end : " + this.modal_end);
      },
      eventMouseEnter: function (info) {
      }
    });
    calendar.render();
  }
}
```

**Comment by Mortaurat** [comment]
Hi, 
i'm still facing this issue.
The problem seems to be that the functions on Fullcalendars are not able to access to my component variables. 
Does someone know how i can fix that or if it's a bug ? 

Thanks

**Comment by acerix** [comment]
Sorry I missed your issue and didn't respond earlier.

It looks like the `Date` objects are maybe getting converted to an empty string, you could try converting them first:

https://codepen.io/anon/pen/zybdMR?editors=0011

If you still have the issue, it's best if you provide a [runnable, stripped-down demonstration of the bug](http://fullcalendar.io/wiki/Reduced-Test-Cases/)? Would really appreciate it because the time saved reproducing will be time spent fixing.

**Comment by Mortaurat** [comment]
Hi, 
Thanks for your reply.
I've just find today the solution of this issue.
The problem is that Angular doesn't have the same scope as javascript. So the "this.modal_*" is not the value of the angular component.

In order to solve this issue i have to add into calendar() : 
` var that = this;`

Then i could use that.modal inside the javascript.
