### ISSUE TITLE
[alpha3] setOption doesn't take account of `minTime` change

### ISSUE THREAD

**Issue by aitboudad** [fullcalendar/fullcalendar#4435]
### Bug Reports

when calling the following code, I'd expect to take account of the new passed option, which not the case for `minTime` for example:
```ts
calendar.setOption('minTime', { hour: 12 });
```
Reproduction example: https://stackblitz.com/edit/typescript-cvmz2g
Working example using V3: https://codepen.io/anon/pen/MZQyrZ?editors=0001

**Comment by acerix** [comment]
Thanks for the report, I can see `minTime` was working as a dynamic setting in v3 but not anymore. 

As a workaround you could change to another view and back to update it:

https://stackblitz.com/edit/typescript-6gdtr1

**Comment by cococore** [comment]
This also applies for "maxTime". For every "changeView" events and resources get fetched again. So with "changeView switch"  we are loading data 3 times.

 I added _.debounce to event/resource fetching in order to "hot fix" this problem.

**Comment by arshaw** [comment]
fixed this issue with the aforementioned commit. @cococore , the problem you mention in your most recent comment is another issue, #4483
