### ISSUE TITLE
Implement RRuleSet's for more complex recurrence setups like excluding dates

### ISSUE THREAD

**Issue by piernik** [fullcalendar/fullcalendar#4439]
It's a feature request.
You wrote that You're using this lib form rrules: https://github.com/jakubroztocil/rrule
Could You add also rruleSets?

Why I need it? Let's assume that I have everyday tasks for a week. I forgot to do it on Monday but did it on Tuesday and have to do it on Wednesday and so on. 
If I use Rrule only, fullcalendar will mark all days with events. But on Tuesday shouldn't be event - it's done.

Will You consider my request ?:)

**Comment by acerix** [comment]
Seems like it would be useful, especially since it's part of that lib.

https://github.com/jakubroztocil/rrule#rruleset-constructor

**Comment by teriblus** [comment]
I need it too, I'll keep generating recurring on the server side until rruleset is available in fullcalendar.

**Comment by arshaw** [comment]
btw, you can do this currently with an rrule string, like is mentioned in this comment: https://github.com/fullcalendar/fullcalendar/issues/4549#issuecomment-472228339

**Comment by arshaw** [comment]
This has been implemented in v5.5.0. `exdate` and `exrule` are now top-level properties of the event object.

Please look at the updated docs: https://fullcalendar.io/docs/rrule-plugin
