### ISSUE TITLE
eventRender not working in Fullcalendar 4 alpha 3 HTMLElement is not passed to the function event parameter

### ISSUE THREAD

**Issue by epelaic** [fullcalendar/fullcalendar#4442]
### Bug Reports

Hello,

When trying to use eventRender, the el (HTMLElement) of the event is not passed in the info event object.

var calendar = new Calendar(calendarEl, {
...
eventRender: function(info:any) {
      console.log('title : ' + info.event.title);
      console.log('el : ' + info.el);
      console.log('view : ' + info.view);
      console.log('isStart : ' + info.isStart);
      console.log('isEnd : ' + info.isEnd);
      console.log('isMirror : ' + info.isMirror);
    },
...
});

Result : 

title : Repeating Event
el : 
view : [object Object]
isStart : true
isEnd : true
isMirror : false

Tested with fullcalendar 4.0.0 alpha 2 & 3.

I'am not JS-Bin friendly, so I forked the typescript example and upgrade it to compile with FC 4.x. 

https://github.com/epelaic/typescript-example

Thanks,

Edo

**Comment by acerix** [comment]
I put your code in the debugging template to test, `info.el` is actually the element, it's just converted to an empty string when you concat it.

https://codepen.io/anon/pen/maKdXm?editors=0011

**Comment by epelaic** [comment]
Thanks for the test,

It  works !

Many thanks ;)

Edo

**Comment by liggth** [comment]
How can I insert HTML into an event title in eventRender?

**Comment by hosseinKabeh** [comment]
You can set html tag, see this
https://stackoverflow.com/a/74542206/10618391
