### ISSUE TITLE
[alpha3] Dragging between calendars gives an error if drop calendar is in agenda view

### ISSUE THREAD

**Issue by bobdenardd** [fullcalendar/fullcalendar#4444]
When using the 'agendaDay' view, it seems that drag and dropping of events between two different calendars does not work.

Here is an example:
https://codepen.io/camillepierre/pen/xmzBQx

On the left hand side calendar select December 13 2018, then attempt to drag event2 to the right hand side calendar, it will trigger a javascript error.

Many thanks, keep up the amazing work on the fullcalendar project!

**Comment by acerix** [comment]
Thanks for the detailed report. I also get the error but it works if I change the second calendar to "month" view.

**Comment by bobdenardd** [comment]
Thanks dear Acerix. As you mention it perfectly works with a month view calendar, but unfortunately in the project I'm working on I have to use the agendaDay view.

If that can help investigating the issue, I've been digging in the code (from the HEAD in the v4 branch), and I found out that the probleme may be related to the splitEventStore code (Splitter.prototype._splitEventStore = function(... etc ...). There is a for loop which attemps to iterate over defKeys[defId]: for (var _i = 0, _a = defKeys[defId]; _i < _a.length; _i++)
Sometimes _a happens to be undefined, which breaks the code. So converting that loop 
from
for (var _i = 0, _a = defKeys[defId]; _i < _a.length; _i++)
to
for (var _i = 0, _a = defKeys[defId]; _a && _i < _a.length; _i++)
seems to do the trick, at least the event can be dragged around without error.

However I have to admit I don't have any understanding about what the aforementioned code does, I'm just trying to help diagnosing the problem.

Thanks again

**Comment by arshaw** [comment]
fixed in 8f50d7ce0d16983fac40424234a45c23e1cd6d31 (not yet released)

**Comment by bobdenardd** [comment]
Awesome, you guys rock!

**Comment by arshaw** [comment]
this has been addressed and released in [4.0.0-alpha.4](https://github.com/fullcalendar/fullcalendar/releases/tag/v4.0.0-alpha.4)
