### ISSUE TITLE
[alpha 3] Events as json feed is ignoring extraParams

### ISSUE THREAD

**Issue by jezzdk** [fullcalendar/fullcalendar#4446]
I'm unable to create a jsbin with this release.

To reproduce:
```
document.addEventListener('DOMContentLoaded', function() {
    var calendarEl = document.getElementById('calendar');

    var calendar = new FullCalendar.Calendar(calendarEl, {
      events: {
        url: 'https://fullcalendar.io/demo-events.json',
        extraParams: {
          custom_param1: 'something',
          custom_param2: 'somethingelse'
        }
      }
    });

    calendar.render();
});
```

I expected "custom_param1" and "custom_param2" to be sent along with the request, but they are not. The same applies when using eventSources.

**Comment by acerix** [comment]
Thanks for the report.

I tried to reproduce in alpha3 and alpha4 but get an error `request is undefined` just by using a url as the event source:

https://codepen.io/anon/pen/xmQZvb?editors=0010

**Comment by acerix** [comment]
Thanks, I got it working and confirmed that `extraParams` are not included in the JSON requests:

https://codepen.io/anon/pen/ebQzXy?editors=0010

**Comment by arshaw** [comment]
fixed this in master. tho @toxpal I couldn't recreate the POST problem with the latest. might have been fixed. I ensured it was fixed with a test

**Comment by arshaw** [comment]
[V4 was officially released a few days ago!](https://fullcalendar.io/blog/2019/03/v4-officially-released) This is fixed.

**Comment by toxpal** [comment]
Yes, v4.0.1 doesn't have this issue anymore.

**Comment by bdobson01** [comment]
I wasn't quite ready to move to v4 yet (will do soon). In case anyone needs to update an older version, this addition of the extraParams line seems to work: 
`
 JsonFeedEventSource.prototype.buildRequestParams = function (start, end, timezone) {
 ...
        $.extend(params, customRequestParams);
        $.extend(params, ajaxSettings.extraParams);
        params[startParam] = start.format();
        params[endParam] = end.format();
...
`
