### ISSUE TITLE
[alpha:3] - EventDrop does not return resource

### ISSUE THREAD

**Issue by cococore** [fullcalendar/fullcalendar#4447]
I'm using FullCalendar 4-beta3 with Scheduler and also Draggable from Fullcalendar.

When I'm dragging event into Calendar, then I get the resource object on drop().

When I'm dragging event between resources the eventObject does not contain "oldResource" and "newResource" anymore.

Code : https://jsbin.com/yasunam/edit?html,js,output

Screenshots added with the event object

![screenshot 2019-01-11 at 17 32 06](https://user-images.githubusercontent.com/9106635/51043676-eff50c00-15c7-11e9-897f-f1d5b4b85a8d.png)
![screenshot 2019-01-11 at 17 31 27](https://i.imgur.com/AU3jMiV.png)

**Comment by acerix** [comment]
Thanks for the report.  I wasn't able to get your demo working (js errors) but I was able to reproduce the issue in alpha3 and also found that it's fixed in alpha4:

https://codepen.io/anon/pen/VqVaKp?editors=0010
