### ISSUE TITLE
Custom time slot grids for week view

### ISSUE THREAD

**Issue by mahi007rocks** [fullcalendar/fullcalendar#4448]
Hi, Generally , we do have time slot grids like 6:00 to 6:30 and  6:31 to 7:00. These are 2 time slots, between these we get a grid line.Now i will come to my point.
I have event timings  and all are hours and minutesi.e 
start - end
6:00 - 7:00    
7:01 - 7:20
7:21 - 7:55
8:30 - 8:40
Is there any way to get custom time slots based on these event timings for week view ?

**Comment by Grunge** [comment]
Just have a look at this zillion years old pull request (that was all ignored):
https://github.com/fullcalendar/fullcalendar/pull/94
did excactly what you want.

**Comment by arshaw** [comment]
there is already another issues that represents this request:
https://github.com/fullcalendar/fullcalendar/issues/472
&uarr;
Could you please visit the link, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates?

(it mentions different "slotMinutes", but the ticket also encapsulated the concept of having different arbitrary ranges)
