### ISSUE TITLE
peer dependencies not install automatically

### ISSUE THREAD

**Issue by zjcf** [fullcalendar/fullcalendar#4450]
### issue
jquery & moment will not install automatically in 3.10.0, which work well in 3.9.0

### environment
npm 6.1.0
yarn 1.12.3

### test
just run `npm i fullcalendar` or `yarn add fullcalendar`, it will only install fullcalendar, and throw warning below
```
// warning in npm
npm WARN fullcalendar@3.10.0 requires a peer of jquery@2 - 3 but none is installed. You must install peer dependencies yourself.
npm WARN fullcalendar@3.10.0 requires a peer of moment@^2.20.1 but none is installed. You must install peer dependencies yourself
````
``` 
// warning in yarn
warning " > fullcalendar@3.10.0" has unmet peer dependency "jquery@2 - 3".
warning " > fullcalendar@3.10.0" has unmet peer dependency "moment@^2.20.1".
```

### debug
The difference between 3.9.0 and 3.10.0 is that moment and jquery were added into devDependencies in 3.10.0, this maybe help.

**Comment by acerix** [comment]
Yes, this was just changed so you need to install jquery and moment as peer depedencies now:

https://github.com/fullcalendar/fullcalendar/issues/4136#issuecomment-453357934
