### ISSUE TITLE
[alpha3] getView() still mentioned in docs

### ISSUE THREAD

**Issue by cococore** [fullcalendar/fullcalendar#4451]
I'm not able to get current view of the calendar. getView() is described in docs(https://fullcalendar.io/docs/v4/Calendar-getView)

Code example: https://codepen.io/anon/pen/aPPmgr?editors=0010

**Comment by acerix** [comment]
Thanks for the report.  `getView()` was removed in the latest alpha so docs need to be updated:

https://github.com/fullcalendar/fullcalendar/blob/2c5d0431919b44bdd2e4d3ab5ae8ba6d5c2425df/CHANGELOG.md#v400-alpha3-2018-12-21

**Comment by arshaw** [comment]
this is fixed in `master` in the the docs repo
