### ISSUE TITLE
Alpha v4 - omitZeroMinute does not work

### ISSUE THREAD

**Issue by cococore** [fullcalendar/fullcalendar#4452]
I'm not able to add zeros after hours. I think its not updating "slowLabelFormat".

Example code: https://codepen.io/anon/pen/aPPmgr?editors=0010

**Comment by acerix** [comment]
You have a typo in [slotLabelFormat](https://fullcalendar.io/docs/v4/slotLabelFormat) and the default value of `omitZeroMinute` is `false` so you need to make it `true` to hide the minutes:

https://codepen.io/anon/pen/WLmEwN?editors=0010
