### ISSUE TITLE
Alpha v4 - nowIndicator does not work with "now"

### ISSUE THREAD

**Issue by cococore** [fullcalendar/fullcalendar#4453]
If we define "now" in the calendar configuration, then the "nowIndicator" on top of the calendar.

Code: https://codepen.io/anon/pen/aPPmgr?editors=0010

**Comment by bbalet** [comment]
I cannot see the bug when executing your Codepen (Chrome,Firefox,Edge). I've tried to click on various days and to come back on today: no issue.

![image](https://user-images.githubusercontent.com/1221546/51107142-891e5f80-1820-11e9-8ee1-3485694e2b3b.png)

**Comment by cococore** [comment]
Was my fault, did not set the time, though now is just a time. Thank you, can close this one.
