### ISSUE TITLE
Dragging an event into the past in month view with eventDurationEditable=false stretches the event instead of moving it

### ISSUE THREAD

**Issue by iiibbbmmm** [fullcalendar/fullcalendar#4458]
codepen: [v3](https://codepen.io/anon/pen/bOybGN) [v4](https://codepen.io/anon/pen/OrYLLK)
Reproduce: drag the event backward, v3's **duration** stays, but v4's **end** stays.
Also `durationEditable` of Event Object.

**Comment by acerix** [comment]
Thanks for the clear demo

**Comment by chrisribal** [comment]
Same here in scheduler's resource view.

**Comment by ocarreterom** [comment]
It happens in all view types (v4 beta.2)
https://codepen.io/anon/pen/BMmNJy

**Comment by acetrand** [comment]
As a temporary workaround I need to put `editable: false` - meaning I don't get the drag and drop event feature either. 

Hope to see this issue fixed soon! 💪

**Comment by arshaw** [comment]
[V4 was officially released a few days ago!](https://fullcalendar.io/blog/2019/03/v4-officially-released). This issue is now fixed.
