### ISSUE TITLE
Swipe when we drag event out of page

### ISSUE THREAD

**Issue by M-Falken** [fullcalendar/fullcalendar#4459]
Feature Request:

Hello,
whatever the view as day, week or month, it would be great that the page swap on the next nor previous just when we drag an events out of the left and right calendar frame.
Perhaps also with left and right indicators that appears when the pointer pass the border, something like that.
Thanks to consider

**Comment by acerix** [comment]
I believe this existing ticket captures this need:
https://github.com/fullcalendar/fullcalendar/issues/2542
↑
Could you please visit the link, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates?
