### ISSUE TITLE
Event Render not working while appending html in ionic 3

### ISSUE THREAD

**Issue by anto-rupak** [fullcalendar/fullcalendar#4461]
this.calendarOptions = {
// allDaySlot:false,
height: 480,
//editable: true,
businessHours: true,
defaultView: "agendaWeek",
weekends: false,
// allDaySlot: false,
hiddenDays: [6, 7],
// showNonCurrentDates: false,
eventLimit: false,
header: {
left: 'title',
center: '',
right: 'prev,next today'
},
selectable: true,
editable: false,
// eventAfterAllRender: function (view) {
// $(".fc-content").append("X");
// $(".closon").click(function () {
// console.log("clicked on button")
// // $('#calendar').fullCalendar('removeEvents',event._id);
// });
//
// },
events: this.eveload,
};
console.log("evdata1", this.eveload);
}

eventRender(model, element, view) {
$(".fc-content").append("X");
// $(".closon").click(function () {
// console.log("clicked on button")
// // $('#calendar').fullCalendar('removeEvents',event._id);
// });
console.log("event render", element);
}

**Comment by acerix** [comment]
Would you be able to post a [runnable, stripped-down demonstration of the bug](http://fullcalendar.io/wiki/Reduced-Test-Cases/)? Would really appreciate it because the time saved reproducing will be time spent fixing.

**Comment by 5im0n** [comment]
@acerix I recreate a [Stackbliz demo](https://stackblitz.com/edit/ionic-angular-fullcalendar-gatjnq) of the problem.

https://github.com/fullcalendar/fullcalendar/issues/4976#issuecomment-664319535
