### ISSUE TITLE
v4 Alpha.4 not loading in IE11

### ISSUE THREAD

**Issue by calemcme** [fullcalendar/fullcalendar#4462]
### Bug Reports
1. Download v4 alpha.4 directly from https://fullcalendar.io/docs/v4/release-notes
2. Deploy the download to Apache server's web directory
3. Got a blank page when loading the alpha.4 from an IE 11 browser, e.g.: http://localhost/FC-4.0.0-A4/demos/default.html where FC-4.0.0-A4 is the full v4 alpha.4 folder unzipped. 
4. Got a calendar screen displayed properly when loading from Chrome from the same folder (http://localhost/FC-4.0.0-A4/demos/default.html).

**Comment by acerix** [comment]
The debug template works for me in IE11:

https://codepen.io/arshaw/full/VqVaBr

Do you get any errors in the console? You should also check the Network tab to see that nothing is getting blocked.

**Comment by calemcme** [comment]
Hi Dylan,Thank you for the prompt response. I ran into errors when loading the link you used for testing. I have included two attachments:a) A IE11 version screenshot so we can compare IE versionsb) An error screen with dev tool enabled.If needed I am available for a quick online session tonight or next week of your convenience. I can send you a gotomeeting link so we can look at my screens together.
Regards, Clay 

    On Friday, January 18, 2019 5:30 PM, Dylan Ferris <notifications@github.com> wrote:
 

 The debug template works for me in IE11:https://codepen.io/arshaw/full/VqVaBrDo you get any errors in the console? You should also check the Network tab to see that nothing is getting blocked.—

**Comment by acerix** [comment]
I can't see the screenshots, please upload them somewhere to attach them here.  I tested in the latest IE 11 and Edge and don't get any errors.

**Comment by calemcme** [comment]
Attached IE 11 version and error screenshots. 
![ie11_version](https://user-images.githubusercontent.com/19936079/51500680-8bd70280-1d94-11e9-881a-aa3c1392b0f3.png)
![ie_11_error](https://user-images.githubusercontent.com/19936079/51500684-8ed1f300-1d94-11e9-9122-9631b540add6.png)

**Comment by calemcme** [comment]
Also an issue with Edge. Works fine with Chrome. Edge screenshot.
![edge_error](https://user-images.githubusercontent.com/19936079/51500717-b6c15680-1d94-11e9-84dc-3c6fd3edccbe.png)

**Comment by acerix** [comment]
Thanks for the info, it seems you are using the same version of IE11.  Could you try with all browser extensions turned off in case one of them is causing the issue.

I'm not sure the 2 errors are related since it looks like they happen at different places in the code but I also can't reproduce the error in Edge.

**Comment by acerix** [comment]
I get the same warning but no errors in either IE11 or Edge.

It looks like you have some strange scripts running. If you can create a new Windows user and test with that account that will indicate if it's some problem with your profile.  Also try with your antivirus turned off in case that is interfering.
