### ISSUE TITLE
Webpack and locale - v4.0.0-alpha.4

### ISSUE THREAD

**Issue by seb-jean** [fullcalendar/fullcalendar#4463]
Hi,
I use FullCalendar v4.0.0-alpha.4.
This page [https://fullcalendar.io/docs/v4/locale](https://fullcalendar.io/docs/v4/locale) works with script tags but not with Webpack.
With Webpack, how can you load a locale, for example "fr", all locale ? It's with an import ?
Thanks :)

**Comment by acerix** [comment]
It's not very well documented yet, but I believe you just need to include the locale files that are generated by Webpack as in v3.  

https://github.com/fullcalendar/webpack-example

**Comment by ocarreterom** [comment]
@seb-jean that works for me.
```js
import { Calendar } from 'fullcalendar'
import 'fullcalendar/dist/locales/es'
```

**Comment by arshaw** [comment]
btw, a beta has been released and the docs now describe how to do locales: https://fullcalendar.io/docs/v4/locale
