### ISSUE TITLE
Setting an events classNames

### ISSUE THREAD

**Issue by jacobrabjohns** [fullcalendar/fullcalendar#4465]
First off, apologies for the lack of recreation steps, but this is less a bug and more a typing issue.

Basically, the setProp's function of an Event accepts only a string as a value, whereas the the classNames property is an array. I've worked around this with a ts-ignore for now, as shown in this little example :

    //@ts-ignore This is the issue
    event.setProp('classNames', ['class1', 'class2']);

I would suggest either adding a specific function for classes, or allowing objects/any as a property. Happy to provide a pull request if you want. Or have I missed something obvious?

Cheers guys, and great library overall.

**Comment by jacobrabjohns** [comment]
``

**Comment by arshaw** [comment]
v5 will now accept a string or an array of strings
