### ISSUE TITLE
Days outside validRange are not identified with the bootstrap4 theme

### ISSUE THREAD

**Issue by jcasilva86** [fullcalendar/fullcalendar#4466]
Hello, I have searched but I did not find anything related to this, I am using version 4.0.0-alpha.4 and when I define the bootstrap theme 4, in the calendar the days are blocked but the css is not applied, that is, it does not turn gray

i created codepen: [https://codepen.io/jcasilva/pen/rPaExO](https://codepen.io/jcasilva/pen/rPaExO)

Are you doing something wrong?

**Comment by acerix** [comment]
Thanks for the report, it looks like those styles don't work in bootstrap4 yet.

https://codepen.io/anon/pen/RvPgEe?editors=0010

**Comment by arshaw** [comment]
would somebody mind making a recreation for v3 in order to see if this is a regression or not in v4?

**Comment by acerix** [comment]
Confirmed same issue in v3

https://codepen.io/anon/pen/ZPeZRg?&editors=001

**Comment by arshaw** [comment]
seems like this is fixed in v5 right?
https://codepen.io/arshaw/pen/ExPvNxp?editable=true&editors=001
