### ISSUE TITLE
navLinks navigates to the previous day when the local timezone is < UTC

### ISSUE THREAD

**Issue by fansaien** [fullcalendar/fullcalendar#4467]
### Bug Reports

Please try this demo [V4 navLinks-demo](https://fullcalendar.io/docs/v4/navLinks-demo). Click the week/day names will navigate to the previous day. 

Click 2019-1-11 -> 2019-1-10, 
Click Wed 1/23, 2019 -> Wed 1/22, 2019

**Comment by Hoakie** [comment]
same issue reported in #4392 and may be related to #4454

Changing local system timezone to one that is > UTC+0 works fine but links don't behave properly when system timezone < UTC+0.   Seems like the internal calculation to factor in timezone that are < UTC+0 so the links navigate to correct date in timezone

**Comment by acerix** [comment]
Thanks for the report.

It's definitely related to those issues but not really a duplicate.

**Comment by fansaien** [comment]
Hello Acerix,

@acerix My local timezone is UTC-6, not after UTC. I set the local time zone to UTC+8, it works fine.

I think the title may be "before UTC"?

**Comment by fansaien** [comment]
@LukeTowers

**Comment by acerix** [comment]
I guess it depends how you look at it; I meant in the sense that UTC-6 would reach midnight 6 hours after UTC-0 does.

**Comment by fansaien** [comment]
Yes, there are two ways to look at it.

**Comment by arshaw** [comment]
fixed with 83ffa5a082a1749a58ae568134e487473d6cc432. will comment again when released

**Comment by arshaw** [comment]
[V4 was officially released a few days ago!](https://fullcalendar.io/blog/2019/03/v4-officially-released)
