### ISSUE TITLE
When "now" is defined as a moment, nowIndicator moves back to that initial position when the view is changed

### ISSUE THREAD

**Issue by acerix** [fullcalendar/fullcalendar#4470]
From https://fullcalendar.freshdesk.com/a/tickets/600

Demo: https://codepen.io/anon/pen/qLzeNO?editors=0010

1. Wait a few minutes for the nowIndicator to move ahead
2. Click "next day" then back to today
3. nowIndicator jumps back to the original position

The issue is fixed by wrapping the moment in a function:

https://codepen.io/anon/pen/pGJwWo?editors=0010

The docs should mention that `now` continually moves forward:

https://fullcalendar.io/docs/now

**Comment by arshaw** [comment]
in v5, the now date no longer jumps back to original value upon navigation. it continually moves forward in time: https://codepen.io/arshaw/pen/GRovNmZ?editable=true&editors=001

but yeah, I should probably document that ... https://github.com/fullcalendar/fullcalendar/issues/5550
