### ISSUE TITLE
unable to drag anymore when filter is applied on external events

### ISSUE THREAD

**Issue by adielidin** [fullcalendar/fullcalendar#4471]
I recreated the issue that I'm facing in the following [CodePen](https://codepen.io/adier/pen/bOXYbV):
opened also in [stackoverflow](https://stackoverflow.com/questions/54377310/not-able-to-drag-anymore-when-filter-is-applied)
At the first time, Dragging an external event from the list into the calendar works fine. 
However, when I apply the filter on a book in the search input text filter books, I have the following issue.

Here are the steps to reproduce :

1- look for 111 in the search input that will filter to the only resulting 111 event book.

2- As you could observe that dragging this resulting event from the filter into 
   the calendar could work fine : but Here we are mainly interested on the case 
   we decide to filter but to do not drag anything into calendar.

3-  so for now clear the 111 filter as text from the search input,  the 
    external events box would back all the defaults events but this time trying 
    to drag one of them into the calendar freezes. It's no more working.  
    It freezes on all the external events **except** **for** **the last found
    by the  filter means the 111 event  (look at the last row on the events )** 
    that onlty one that could be dragged.
    and no more able to drag others events into the calendar.

4- and even If I dragged 111 into the calendar, and after that if I try to drag 
   anothor one It will freeze.

Any help would be greatly appreciated.

Best regards,

Adier

https://fullcalendar.io/releases/fullcalendar/3.10.0/lib/moment.min.js
https://fullcalendar.io/releases/fullcalendar/3.10.0/lib/jquery.min.js
https://fullcalendar.io/releases/fullcalendar/3.10.0/fullcalendar.min.js
https://code.jquery.com/ui/1.11.3/jquery-ui.min.js

**Comment by iiibbbmmm** [comment]
Filter recreats items DOM.
In order to make them draggable again, you must call `.draggable()` on every filter action.

**Comment by adielidin** [comment]
many thanks iiibbbmmm

OrderBy by using sort function in the filter recreats items DOM.

    So In order to make them draggable again, we must call .draggable() on every filter action.
    Hence I'm running the jQuery selector before angular renders, so I'm only selecting 
    the initial DOM element, not the others items DOM recreated by Filter during filtering.
    The perfect solution is to do a DOM manipulation within an angular directive via the link function.
	
	
	$(document).ready( function(){     
      $(".fc-event").draggable();
  });

to sum up
=========
JS works with loaded DOM on page. This means when ever you call sort function, 
HTML elements must be present on the page.

Let's try to understand what's going on here?
=============================================
- All html elements loaded first.
- JS trigger and all dragging functionality to loaded DOM.
- orderBy using sort function call to fetch new data and replace old DOMs.
- Now drag functionality stops working.
- why? because JS drag function run on old DOM and currently it has been removed.
- need to call the drag function again on new loaded DOM.
- NOTE: make sure elements or HTML must be loaded before calling JS drag function.

[WorkingcodePen](https://codepen.io/adier/pen/exzGgv)
