### ISSUE TITLE
overflow clipping issue for dragging external events into calendar (or from calendar back to 'external-events' list)

### ISSUE THREAD

**Issue by adielidin** [fullcalendar/fullcalendar#4472]
I recreated the issue that I face in the following [CodePen](https://codepen.io/adier/pen/bOXYbV):
opened also on [stackoverflow](https://stackoverflow.com/questions/54375570/overflow-clipping-issue-for-dragging-external-events-into-calendar-or-from-cale)
Dragging an external event from the list into the calendar works fine. However, while dragging it from external event box into the calendar(or from the calendar back to the list), the event disappears behind the Virtual Scroll Repeat (until released into the callendar it shows up in the calendar). 
Note that I set the z-index of the external events list on purpose.

However, I wonder how I can influence the **overflow:auto of repeater-container css class**  necessary for the scroll that holds the external events. 
How to make events shows up over the virtual scroll during their trips into the fullcalendar? 
N.B: the same thing should be apply for the case when I want to dragg back an event from the calendar back to the external event list.

N.B: to see clearly the problem that I'm describing here.
       Here are the steps to reproduce : 
  1) comment the overflow: auto;  line 147 in the css file on the  
     class="repeater-container" on the codepen.
  2) scroll down to one event 

  3) drag it into the calendar
     so you can see from steps 1-2-3 the drag into the calendar works fine .

  Now uncomment the overflow: auto;  line 147 in the css file on the 
  class="repeater-container"

  repeat the steps 2-3 like described before 
  so from steps 1-2-3(with overflow: auto;) the drag into the calendar 
  works also well but during the trip(from external events box to calendar) 
  the  event disappear under the virtual scroll until it reaches the 
  calendar and it shows up into the calendar.
Any help would be greatly appreciated.

Best regards,
Adier.

https://fullcalendar.io/releases/fullcalendar/3.10.0/lib/moment.min.js
https://fullcalendar.io/releases/fullcalendar/3.10.0/lib/jquery.min.js
https://fullcalendar.io/releases/fullcalendar/3.10.0/fullcalendar.min.js
https://code.jquery.com/ui/1.11.3/jquery-ui.min.js

**Comment by acerix** [comment]
Since the problem is with dragging the external events, it doesn't seem related to anything in the calendar.  If you think it's a bug, it's best if you can provide a [stripped-down demonstration of the bug](http://fullcalendar.io/wiki/Reduced-Test-Cases/).

**Comment by adielidin** [comment]
made a [workaround in SO](https://stackoverflow.com/questions/54375570/overflow-clipping-issue-for-dragging-external-events-into-calendar-or-from-cale)
