### ISSUE TITLE
Drag events wrong position on modal

### ISSUE THREAD

**Issue by Ixreb** [fullcalendar/fullcalendar#4473]
Hi,

I have discovered an isue. Drag events (calendar or external) works perfectly, but only if you work on "body".

If your calendar is placed in a modal (bootstrap, jquery ...) the element does not follow the cursor when you use the scroll.

Example:
https://codepen.io/anon/pen/VgjjLo

1º- Open modal
2º- Drag event (calendar or external)
3º- While dragging, use scroll

You can see the wrong position of event respect cursor. I've been trying to solve it for hours and I do not discover the way.

Any solution? Thanks

**Comment by acerix** [comment]
I believe this existing ticket captures this need:
https://github.com/fullcalendar/fullcalendar/issues/4118
↑
Could you please visit the link, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates?
