### ISSUE TITLE
rerenderEvents cause vertical scrolling

### ISSUE THREAD

**Issue by pizzadev** [fullcalendar/fullcalendar#4474]
Hi Fullcalendar Team,

Calling rerenderEvents causes scrolling of the view.
Please check the codepen below. 

Just click on a single event and rerenderEvents will be called. Fullcalendar view will be scrolled after all events are ready.

https://codepen.io/pizzadev/pen/pGbNwE?editors=0010

**Comment by acerix** [comment]
Thanks for the detailed report.  I simplified the test case a bit and see it still scrolls down when calling rerenderEvents with a few events stacked in the top resource: 

https://codepen.io/anon/pen/KJMBVv?editors=0010

**Comment by arshaw** [comment]
update v3 demo: https://codepen.io/arshaw/pen/LYGjbpa?editable=true&editors=001

this should no longer happen in v5
