### ISSUE TITLE
Wrong date in navLinkDayClick

### ISSUE THREAD

**Issue by jcasilva86** [fullcalendar/fullcalendar#4477]
Hello when i click in **navLinkDayClick** get always last day
[https://codepen.io/jcasilva/pen/rPaExO](https://codepen.io/jcasilva/pen/rPaExO)

**Comment by acerix** [comment]
Thanks for the report. It's similar to the issue in https://github.com/fullcalendar/fullcalendar/issues/4454 , but in this case the date is still off even if converted to UTC:

https://codepen.io/anon/pen/BMLbQo?editors=0010

**Comment by arshaw** [comment]
fixed with 83ffa5a082a1749a58ae568134e487473d6cc432. will comment again when released

**Comment by arshaw** [comment]
[V4 was officially released a few days ago!](https://fullcalendar.io/blog/2019/03/v4-officially-released)
