### ISSUE TITLE
Documentation Typo

### ISSUE THREAD

**Issue by ivanmijatovic89** [fullcalendar/fullcalendar#4478]
It's should be 
calendar.getEventById( id )
instead of
calendar.getEvenyById( id )

https://fullcalendar.io/docs/v4/Calendar-getEventById
http://prntscr.com/meiw8z

**Comment by dakala** [comment]
Fixed. No longer valid in current live version

**Comment by acerix** [comment]
Thanks, confirmed fixed now.
