### ISSUE TITLE
About Custom View click body 

### ISSUE THREAD

**Issue by LAIFUA** [fullcalendar/fullcalendar#4479]
The version I'm using is 3.0
When I click on the body in the custom view ,Will appear about the mouse error!
How to solve it？
I'm Not Using the renderDates method in  DayGrid , I'm rewriting this method myself
like this :
              renderDates: function () {

				this.el.addClass('fc-basic-view').html(this.renderSkeletonHtml());
				this.renderHead();  

				var dayGridContainerEl = $('<div class="fc-day-grid-container"></div>');
				var dayGridEl = $('<div class="fc-day-grid" />').appendTo(dayGridContainerEl);
				this.el.find('.fc-body > tr > td').append(dayGridContainerEl);

				this.dayGrid.setElement(dayGridEl);
				renderBodyDatas();  
				this.rowEls = this.el.find('.fc-row');
				this.cellEls = this.el.find('.fc-day');

				this.rowCoordCache = new FC.CoordCache({
					els: this.rowEls,
					isVertical: true
				});
				this.colCoordCache = new FC.CoordCache({
					els: this.cellEls.slice(0, this.colCnt), // only the first row
					isHorizontal: true
				});
			},

**Comment by acerix** [comment]
Would you be able to post a [runnable, stripped-down demonstration of the bug](http://fullcalendar.io/wiki/Reduced-Test-Cases/)? Would really appreciate it because the time saved reproducing will be time spent fixing.
