### ISSUE TITLE
Event is not show in alldayslot on Sunday

### ISSUE THREAD

**Issue by jcasilva86** [fullcalendar/fullcalendar#4480]
The events is not show in alldayslot on Sunday
[https://codepen.io/jcasilva/pen/rPaExO](https://codepen.io/jcasilva/pen/rPaExO)

**Comment by iiibbbmmm** [comment]
According to [https://fullcalendar.io/docs/v4/validRange](https://fullcalendar.io/docs/v4/validRange), that's the alright.

**Comment by jcasilva86** [comment]
in tests, if left without the property maxTime the events appear on Sunday, it follows again the codepen

[https://codepen.io/jcasilva/pen/rPaExO?editors=0010](https://codepen.io/jcasilva/pen/rPaExO?editors=0010)

**Comment by jcasilva86** [comment]
as a matter a fact, it always happens with the last day rendered in the calendar, its I put: firstDay: 0, the last day of the week will be Saturday, and the allday events will not be shown, the other days rendered this does not happen,

**Comment by jcasilva86** [comment]
complementing, it happen in views agendaweek and agendaday, on views list and month don't happen

**Comment by acerix** [comment]
I believe this existing ticket captures this need:
https://github.com/fullcalendar/fullcalendar/issues/4483
↑
Could you please visit the link, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates?
