### ISSUE TITLE
Calendar fails loading when calendar not in focus

### ISSUE THREAD

**Issue by jokkis0** [fullcalendar/fullcalendar#4481]
I have created a pen her:
https://codepen.io/jokkis0/pen/daNqZy

I have a bootstrap tab where one showing the calendar, and the other is showing a datatable. 
On datatable I have a delete button on each event, when I delete and reloads the calendar, the calendar is not being populated. If I add a button on the tab where the calendar is, that rerender the calendar, the calendar will show as expected. I can see that the "TR" rows on the reources are being set as "height=0", so I think the Javascript is trying to set a height dynamicly, but it seems it will fail when the calendar view is hidden. 

Do you have any suggestion to handle this?

Thanks!

**Comment by jokkis0** [comment]
I have now updated the codepen, 
If you try to click on "calendar" tab, and click "reload" the calendar loads correct, but I you click back on "List" and delete one Item, and then click back on "calendar" tab, The calendar looks messy. 

Thanks

**Comment by acerix** [comment]
I believe you need to call `render` in a callback function that happens after the tab is changed:

https://fullcalendar.io/docs/render
