### ISSUE TITLE
Year View Render

### ISSUE THREAD

**Issue by alonetech** [fullcalendar/fullcalendar#4482]
In the year View I can't able to renderEvent using Select function but month is working fine.

Thanks!

**Comment by acerix** [comment]
Would you be able to post a [runnable, stripped-down demonstration of the bug](http://fullcalendar.io/wiki/Reduced-Test-Cases/)? Would really appreciate it because the time saved reproducing will be time spent fixing.

**Comment by alonetech** [comment]
Please Checkout this link 
https://codepen.io/alonetech/pen/daWNQe

When i am trying to drag on date color highlighted but when i release the mouse button it  faded away.

**Comment by acerix** [comment]
The year view your are using is not part of the calendar.  There is an open request to add a view like that:

https://github.com/fullcalendar/fullcalendar/issues/1140
↑
Could you please visit the link, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates?

**Comment by alonetech** [comment]
@acerix I Have tried you link but its not working. It show $calendar is not a function and year view is in different js how could i implement that.

**Comment by acerix** [comment]
You could try those examples as a starting point for now but that view is not built-in yet so you would need to implement it yourself for now/
