### ISSUE TITLE
AllDay events are not visible in Day view if minTime, maxTime is defined

### ISSUE THREAD

**Issue by piernik** [fullcalendar/fullcalendar#4483]
As in topic. If You define `minTime` `maxTime` `AllDay` event is not displayed on day view:
https://codepen.io/piernik/pen/YBZjgR?editors=0010

Also switch to `weekView`. Event is not displayed on Sundays

**Comment by jcasilva86** [comment]
exact

>

**Comment by acerix** [comment]
Thanks for the report and demo.

**Comment by piernik** [comment]
@arshaw will it be fixed in next release? I want to use v4 in production next month.

**Comment by piernik** [comment]
thanks

**Comment by arshaw** [comment]
[V4 was officially released a few days ago!](https://fullcalendar.io/blog/2019/03/v4-officially-released) This issue is fixed!
