### ISSUE TITLE
minTime and maxTime only type Duration

### ISSUE THREAD

**Issue by jcasilva86** [fullcalendar/fullcalendar#4484]
In documentation is write: "Duration, default: '00:00:00'" but work only with type Duration,
example: 
            minTime: '00:00:00', // don't work

            it is work
            minTime: {
                minutes: 8,
                hours: 0,
            },

am i doing something wrong or documentation is missing information ?
[https://codepen.io/jcasilva/pen/rPaExO?editors=0010](https://codepen.io/jcasilva/pen/rPaExO?editors=0010)

**Comment by acerix** [comment]
`minTime: '00:00:00'` seems to be working as expected, how do you expect it to work?

`minTime: '00:08:00'` would start 8 minutes after midnight like your duration example.
