### ISSUE TITLE
Weekends show in list view with custom dayCount even though weekends is set to false

### ISSUE THREAD

**Issue by daniel-stoll** [fullcalendar/fullcalendar#4486]
See in codepen:
[codepen](https://codepen.io/anon/pen/gqRQRv?&editable=true&editors=001)

if an event occurs on a weekend (here it is Saturday and Sunday) the fullcalendar will show it evenn though the setting "weekend" is set to false.
Same goes for hiddenDays: [ 0,6 ]

This only happens in the list view, not the agenda view.

Might be the case, that in the listview the evaluation of the daycount is not correct.

**Comment by acerix** [comment]
Thanks for the detailed report.  It works as expected if dayCount is commented out from that view.

**Comment by arshaw** [comment]
i consider this the same as this other bug:
https://github.com/fullcalendar/fullcalendar/issues/3644
&uarr;
Could you please visit the link, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates?
