### ISSUE TITLE
[v4-alpha.3] Current year skipped in yearly recurring events

### ISSUE THREAD

**Issue by beau-gosse** [fullcalendar/fullcalendar#4487]
When using the RRule plugin to generate yearly recurring events, the current/starting year is skipped in the calendar. 

For example, the following rule: `RRULE:FREQ=YEARLY;COUNT=3;BYYEARDAY=51` should return events every year on the 51th day for 3 times, including in the base year set in `dtstart` 

Here's a JSBin that reproduces this behavior => events are only visible in 2020 and up:
https://jsbin.com/wezoremoda/edit?html,output

**Comment by beau-gosse** [comment]
It seems `dtstart` is exclusive. I'm able to address this issue by setting the start date to one year prior. In PHP, this does it  => `$dtstart = $date->modify('-1 year')`, where $date is a DateTime object.

**Comment by acerix** [comment]
It seems to be working as expected.  The 51st day of the year is Feb 20, so for the first occurrence to be in 2019, `dtStart` needs to be 2019-02-20 or before.

https://codepen.io/anon/pen/QYMjWr?editors=0010

**Comment by beau-gosse** [comment]
@acerix thanks. It's indeed correct, though I should point out that PHP's `$date->format('z')` returns a zero-index output ranging from 0 to 365. In this case, the 51st day of 2019 is February 21.
```
$dtstart = DateTime::createFromFormat('Y-m-d', '2019-02-21');
echo $dtstart->format('z'); // should output 51 for the Eastern Standard Time
```
Setting `dtstart` to 1 day in the past ensures that the first occurence will be in 2019 => `$dtstart = $date->modify('-1 
 day')`
