### ISSUE TITLE
Is there an indication when version 4 will be out of alpha/beta?

### ISSUE THREAD

**Issue by RikEskes** [fullcalendar/fullcalendar#4488]
First of all apologies if this is the wrong place to ask, but I could not find another place to post this question.

I was wondering whether a roadmap is available of when version 4 will be out of alpha and possibly beta? I am looking into updating a project that uses version 3 to version 4. And for this I was wondering whether it would be a smart move to be doing so already or whether to wait for version 4 to be out of alpha/beta. However, for me to decide on this depends on whether this roadmap is known and whether updates to version 3 will keep happening, and if so, for how long this will be done?

Is there a possibility some more information can be provided on the matter?

**Comment by acerix** [comment]
I think it would be useful to have a roadmap for updates so will leave this open as a request. 

We expect a full release of version 4 by the end of February.  The API will not change between now and then so we recommend using v4 for new projects that will be launched after March 1. So, you could update your project sooner but should not use v4 in production until there's a stable release.

**Comment by superandrew213** [comment]
Will beta version be published on npm soon?

**Comment by arshaw** [comment]
v4 is out!
