### ISSUE TITLE
Npm release diff

### ISSUE THREAD

**Issue by frlinw** [fullcalendar/fullcalendar#4492]
### Bug Reports
There is a diff between @fullcalendar/interaction version and the others packages
Check version tab:
https://www.npmjs.com/package/@fullcalendar/interaction -> latest: beta.1
https://www.npmjs.com/package/@fullcalendar/core -> latest: beta.2

npm warn:
```
npm WARN @fullcalendar/interaction@4.0.0-beta.1 requires a peer of @fullcalendar/core@4.0.0-beta.1 but none is installed. You must install peer dependencies yourself.
```

**Comment by acerix** [comment]
I'm not sure what the "interaction" version is but can see it's not updated to beta 2 yet.

**Comment by arshaw** [comment]
@frlinw thanks for letting me know about this. i updated all the plugins. they are all in sync. at version 4.0.0-beta.4 ( i had to push a bunch of dummy versions and use trial and error, thus the .4)

**Comment by frlinw** [comment]
@arshaw only core & interaction have been updated to v4.0.2 this time

**Comment by arshaw** [comment]
@frlinw, that's intentional. only certain plugins had bugfixes. the unaffected plugins were not published as new versions. everything should work just fine. let me know if anything's broken

**Comment by frlinw** [comment]
it makes sense to update plugin version only if there is a change but in a user perspective, I'm afraid it will be confusing. 
Think about interaction v4.3.2, core v4.5.6, daygrid v4.2.3, timeGrid v4.1.6....
- Versionning will be less clear. (A breaking change in a plugin cause a new major version? if not, versions will be related except for minor?)
- github releases won't be representative (because there is a [dayGrid v4.0.2](https://github.com/fullcalendar/fullcalendar/tree/v4.0.2/dist/daygrid) on github but it's still 4.0.1 on npm)
- tagging & reproducing issues will be harder
- it causes additional issues

**Comment by arshaw** [comment]
@frlinw , you're not using NPM? NPM will make sure all versions are compatible.
