### ISSUE TITLE
[v4 - beta2] weekends:false - completely breaks calendar

### ISSUE THREAD

**Issue by palikman** [fullcalendar/fullcalendar#4494]
[Demo](https://codepen.io/palikman/pen/gZJGPJ)

**Comment by frlinw** [comment]
in your demo, it's the v4-alpha.4

**Comment by acerix** [comment]
Would you be able to post a [stripped-down demonstration of the bug](http://fullcalendar.io/wiki/Reduced-Test-Cases/)? It seems to be an issue with something in `renderCalendarSkeleton()`.

**Comment by arshaw** [comment]
this is probably fixed in v4 official
