### ISSUE TITLE
[beta 2] Plugins issue

### ISSUE THREAD

**Issue by frlinw** [fullcalendar/fullcalendar#4495]
### Bug Reports
Error from PluginSystem.add when using an array of objects
![image](https://user-images.githubusercontent.com/11896237/52340591-6e4e9d80-2a10-11e9-996f-e59e30bf9b7b.png)

**Comment by acerix** [comment]
Would you be able to post a [runnable, stripped-down demonstration of the bug](http://fullcalendar.io/wiki/Reduced-Test-Cases/)? Would really appreciate it because the time saved reproducing will be time spent fixing.

**Comment by frlinw** [comment]
tried in codepen but got an other error: https://codepen.io/frlinw/pen/Erbgja

**Comment by arshaw** [comment]
@frlinw , i don't know exactly why this is happening for you, but the root of the problem is that you are passing in ALL the members of each package into the `plugins` array, not the `default`. it needs the `default` of each package. Though this is something your build env should handle automatically. how are you writing your import statements for the plugins?

**Comment by frlinw** [comment]
I'm using webpack dynamic imports, it looks like this:
```js
  const Fullcalendar = () => {
    return Promise.all([
      import(/* webpackChunkName: 'fullcalendar' */ '@fullcalendar/core'),
      import(/* webpackChunkName: 'fullcalendar' */ '@fullcalendar/interaction'),
      import(/* webpackChunkName: 'fullcalendar' */ '@fullcalendar/daygrid'),
      import(/* webpackChunkName: 'fullcalendar' */ '@fullcalendar/timegrid'),
      import(/* webpackChunkName: 'fullcalendar' */ '@fullcalendar/list')
    ])
  }

  const [Core, ...plugins] = await Fullcalendar()
  
  const fullcalendar = new Core.Calendar(el, {
        plugins: plugins,
  })
```

**Comment by frlinw** [comment]
Well, it's related to dynamic import syntax (not Fullcalendar) and it seems to be [per spec](https://tc39.github.io/proposal-dynamic-import/#sec-hostresolveimportedmodule).
