### ISSUE TITLE
Array of Business Hours doesn't work starting in v4

### ISSUE THREAD

**Issue by plfgavilan** [fullcalendar/fullcalendar#4496]
Reduced test case:
https://codepen.io/plfgavilan/pen/GzMwyW

Version: 4.0.0-alpha.4

If I pass an array of bussines hours to the configuartion object, it doesn't show them in the calendar.
It is only works if I pass a sigle bussines hour object.

According to the documentation, shoud be possible to pass an array:
https://fullcalendar.io/docs/businessHours

 => businessHours: { item }  => it works
![image](https://user-images.githubusercontent.com/4791544/52351549-49b3ef00-2a2b-11e9-9efc-29551b2b656e.png)

 => businessHours: [ items ] => doesn't work 
![image](https://user-images.githubusercontent.com/4791544/52351501-3012a780-2a2b-11e9-9469-c0c292e2cbb8.png)

**Comment by acerix** [comment]
Thanks for the report, same code works in v3:

https://codepen.io/anon/pen/KJyMGB?&editable=true&editors=001

**Comment by aitboudad** [comment]
use `startTime`, `endTime` and `daysOfWeek` instead:
```ts
businessHours : [{
  daysOfWeek: [0, 1, 2, 3, 4, 5, 6],
  startTime: '09:00',
  endTime: '11:00'
}, {
  daysOfWeek: [0, 1, 2, 3, 4, 5, 6],
  startTime: '13:00',
  endTime: '18:00'
}]
```

**Comment by acerix** [comment]
Thanks for pointing that out, it does work with the new params that were renamed:

https://codepen.io/anon/pen/PVOjLK?editors=1010

https://fullcalendar.io/docs/v4/businessHours
