### ISSUE TITLE
[4.0.0-beta.2] Wrong dateClick arg typing

### ISSUE THREAD

**Issue by dzonatan** [fullcalendar/fullcalendar#4497]
In **4.0.0-beta.2** the day element property for `dateClick` event is declared to be **el**:
https://github.com/fullcalendar/fullcalendar/blob/27296e747b721c0861563717682be63267571808/src/core/types/input-types.ts#L184

When the actual property name is **dayEl**:
https://github.com/fullcalendar/fullcalendar/blob/5c271f1d0f603406530fed294b50315de3715055/src/core/Calendar.ts#L41

**Comment by acerix** [comment]
Thanks for the report and PR.  Does this cause a type error when clicking on a date?

**Comment by dzonatan** [comment]
No. Just you don't see this property in typescript.
Current workaround: `(event as any).dayEl`

**Comment by acetrand** [comment]
Also, the argument `dateStr: string` is mentioned in the [doc](https://fullcalendar.io/docs/v4/dateClick) but is missing from the dateClick arg typing.

**Comment by arshaw** [comment]
these problems have been addressed in the master branch

**Comment by arshaw** [comment]
[V4 was officially released a few days ago!](https://fullcalendar.io/blog/2019/03/v4-officially-released)
