### ISSUE TITLE
Break line in title of events

### ISSUE THREAD

**Issue by arshaw** [fullcalendar/fullcalendar#450]
Originally reported on Google Code with ID 179

```
FullCalendar currently ignores newlines. It would be very useful if this 
feature was implemented. Sometimes I need to put long day event on the 
calendar with long desscription on this event (in title). And I just cannot 
put break lines into the text so it looks very messy.

I would appreciate if this issue will be at least considered as worth 
thinking about.

Thanks in advance,
Marcin
```

Reported by `marcin.milinski` on 2009-11-11 08:29:54

**Comment by rahuljs** [comment]
Hello People,
Simply just add this below line to your stylesheet
`.fc-day-grid-event .fc-content{
    white-space: normal!important;
}`

**Comment by KonradMil** [comment]
Full fix for adding html:

eventRender : function(event, element) {
            $(element).each( function(val, obj) {
                vale = $(obj).find('span.fc-title').text().replace('&lt;', '<').replace('&gt;', '>');
                $(obj).find('span.fc-title').html(vale);
	        });

        }

**Comment by kamleshwebtech** [comment]
<br> tag worked for me. Thanks a lot. Use html instead of text.

$('.fc-day-header span').each(function(){
	var text = $(this).text();
	text = text.replace(',',"<br>");
	text = text.replace('/','-');
	text = text.replace('/','-');
	$(this).html(text);
});

![weekly-view](https://user-images.githubusercontent.com/43021973/66825697-6912fc80-ef68-11e9-9d84-07ab7a5f11ba.png)

**Comment by kamleshwebtech** [comment]
< br > tag worked for me. Thanks a lot. Use html instead of text.

```
$('.fc-day-header span').each(function(){
	var text = $(this).text();
	text = text.replace(',',"<br>");
	text = text.replace('/','-');
	text = text.replace('/','-');
	$(this).html(text);
});
```

![weekly-view](https://user-images.githubusercontent.com/43021973/66825901-dd4da000-ef68-11e9-929e-035f2f4c7797.png)

**Comment by MRSAIHAIK** [comment]
$('#calendar').fullCalendar({
        defaultView: 'agendaWeek',
        minTime: '06:00:00',
        maxTime: '22:00:00',
        height: 1150,
        header: {
            left: 'prev,next today',
            center: 'title',
            right: 'month,agendaWeek,agendaDay'
        },
        firstDay: 1,


        events : [
                    {
                        "title":"TCC-000004",
                        "id":"2",
                        "start":"2019-12-03 09:00:00",
                        "end":"2019-12-03 00:00:00",
                        "color":"#730058",
                        "status":"A",
                        "description":"Testing Description"
                    }
                ],

        eventRender: function(event, element) {

            // To append if is description in next line
            if(event.description != '' && typeof event.description  !== "undefined")
            {  
                element.find(".fc-title").append("<br/><b>"+event.description+"</b>");
            }
        }, 
        
    });

![image](https://user-images.githubusercontent.com/29477008/69704245-ffbd0680-112d-11ea-9509-1388687dc2c7.png)

**Comment by anassaaid** [comment]
You can try \n

**Comment by jeffersoil** [comment]
> You can try \n

Worked to me like a charm

**Comment by gagania** [comment]
if you want to use html just use element.html dont use element.text
ex:
element.html('testing<br/>'+event.start._i.substring(10)+"-"+event.end._i.substring(10));

**Comment by rjworks** [comment]
> if you want to use html just use element.html dont use element.text
> ex:
> element.html('testing
> '+event.start._i.substring(10)+"-"+event.end._i.substring(10));

Doesn't work

**Comment by GreybeardTheUnready** [comment]
**Update to MRSAIHAIK's entry.**
eventRender disappeared in V5 ( [See this: ](https://fullcalendar.io/docs/v5/event-render-hooks)  ) - so try this...

      eventDidMount: function(info) {               // If a description exists add as second line to title
        if(info.event.extendedProps.description != '' && typeof info.event.extendedProps.description  !== "undefined") {  
            $(info.el).find(".fc-event-title").append("<br/><b>"+info.event.extendedProps.description+"</b>"); 
        }
      },

As developers have said for years "It works for me"  :-)

**Comment by mrobst** [comment]
Thanks @GreybeardTheUnready - I found a similar way to change the title (using with Angular)

```
eventDidMount: function (info) {
      // If a description exists add as second line to title
      if ( info.event.extendedProps.desccription != '' &&
        typeof info.event.extendedProps.description !== 'undefined'
      ) {
        const a = info.el.getElementsByClassName('fc-event-title');
        a[0].innerHTML = info.event.title +  '<br>' + '<span style="color:red">' +
          info.event.extendedProps.description +  '</span>';
      }
    },
```

**Comment by shizukura06** [comment]
For some reason, all seems not working, I just use this to my code and all html codes are working now:
                        ```
eventRender: function eventRender( event, element, view ) {
  $("#calendar .fc-title").each(function (i){
    $(this).html($(this).text());
  });
}
```

**Comment by viniciusmelocodes** [comment]
> It works for me

**Comment by viniciusmelocodes** [comment]
> Thanks @GreybeardTheUnready - I found a similar way to change the title (using with Angular)
> 
> ```
> eventDidMount: function (info) {
>       // If a description exists add as second line to title
>       if ( info.event.extendedProps.desccription != '' &&
>         typeof info.event.extendedProps.description !== 'undefined'
>       ) {
>         const a = info.el.getElementsByClassName('fc-event-title');
>         a[0].innerHTML = info.event.title +  '<br>' + '<span style="color:red">' +
>           info.event.extendedProps.description +  '</span>';
>       }
>     },
> ```

Thanks. It works for me with VueJS 2.
