### ISSUE TITLE
BusinessHours - disable grid for past days

### ISSUE THREAD

**Issue by mcichocki** [fullcalendar/fullcalendar#4500]
I have grid on the week, but for each next day I set fc-past as disabled day. But businesshours grid and fc-ast impose itself and it looks terrible. How remove businesshours for past days? 

` dayRender: function(date, cell ){
        if (moment().diff(date,'days') > 0){
	    $(".fc-past").css("background-color", "silver");
    	}
 }`

**Comment by acerix** [comment]
Would you be able to post a [runnable, stripped-down demonstration of the bug](http://fullcalendar.io/wiki/Reduced-Test-Cases/)? Would really appreciate it because the time saved reproducing will be time spent fixing.
