### ISSUE TITLE
[4.0.0-beta.2] Date clicking is not working

### ISSUE THREAD

**Issue by kevinmarrec** [fullcalendar/fullcalendar#4501]
`dateClick`, `select` and many others triggers are never called, making lot of things not working.

Reproduction : https://fullcalendar.io/docs/v4/date-clicking-selecting-demo

I checked source code quickly, it seems that triggers are defined but never called, at least around `core`.
I don't know is the issue comes from plugins or core, but something seems wrong.

The demo is using `4.0.0-beta.2`, and the issue is also still present in `4.0.0-beta.4`

**Comment by frlinw** [comment]
`interaction` plugin is missing in the demo.
This one works correctly https://codepen.io/frlinw/pen/KJyOeL

**Comment by kevinmarrec** [comment]
Oh yeah, thanks @frlinw ! I missed this doc part : https://fullcalendar.io/docs/v4/selectable with `interaction` import.

_Note : The demo still needs an update_ 🙂

**Comment by lucasmoyano** [comment]
> `interaction` plugin is missing in the demo.
> This one works correctly https://codepen.io/frlinw/pen/KJyOeL

In that example, after 8:30pm the click is not working :C

**Comment by acerix** [comment]
I believe this existing ticket is for the same issue:
https://github.com/fullcalendar/fullcalendar/issues/4503
↑
Could you please visit the link, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates?
