### ISSUE TITLE
[beta4] Cannot drag events to the bottom of the calendar in agenda view

### ISSUE THREAD

**Issue by superandrew213** [fullcalendar/fullcalendar#4503]
https://codepen.io/anon/pen/PVEeVe

Try dragging event2 past 4pm. Events cannot be dragged past 4pm on any of the days.

The cutoff time seems to be linked to the width of the calendar. Try changing the width of the calendar from 700px to 900px. The time changes from 4pm to 9pm.

**Comment by arshaw** [comment]
fixed with https://github.com/fullcalendar/fullcalendar/commit/90a978e8dce5f4add8e2322652525a462febac9a. comment again when released

**Comment by arshaw** [comment]
[V4 was officially released a few days ago!](https://fullcalendar.io/blog/2019/03/v4-officially-released)
