### ISSUE TITLE
AspectRatio not changeable with .setOption with windowResize (works till alpha 2)

### ISSUE THREAD

**Issue by Jangerr** [fullcalendar/fullcalendar#4506]
I noticed after updating from Alpha 2 to Alpha 4 that windowResize, which i used for landscape / portrait mode detection, no longer updates "aspectRatio" via ".setOption" properly, see stackblick below.

https://stackblitz.com/edit/angular-amd9fg

The ".getOption" function clearly states the correct value, but its not shown.

**Comment by acerix** [comment]
Thanks for the report, can see aspectRatio is not updating dynamically.

**Comment by arshaw** [comment]
any way someone can post a recreation with vanilla JS? (no angular)

**Comment by acerix** [comment]
Confirmed in vanilla

https://codepen.io/anon/pen/YgZmzw?editors=0010

Initially, the aspectRatio is random but it should also change to a random ratio when the window is resized.

**Comment by arshaw** [comment]
[V4 was officially released a few days ago!](https://fullcalendar.io/blog/2019/03/v4-officially-released) This is fixed.
