### ISSUE TITLE
Resize and drag event Slow when there are too many events

### ISSUE THREAD

**Issue by quangquy87** [fullcalendar/fullcalendar#4507]

**Comment by acerix** [comment]
I believe this existing ticket captures this need:
https://github.com/fullcalendar/fullcalendar/issues/2524
↑
Could you please visit the link, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates?
