### ISSUE TITLE
[4.0.0-beta.4] getView() function not found

### ISSUE THREAD

**Issue by danydhondt** [fullcalendar/fullcalendar#4508]
Clicking on an event, I want to call `getView()`on the calendars' instance.
Error is thrown `getView() is not a function`

I isolated the problem on [codesandbox](https://codesandbox.io/s/koz06m2op3)
Just run the sandbox and click on any 'Foo' event

Could it be that this method is not implemented yet?

**Comment by frlinw** [comment]
Indeed
![image](https://user-images.githubusercontent.com/11896237/52569450-827c0b80-2e11-11e9-9f72-28974b8f4a3e.png)

**Comment by acerix** [comment]
`getView()` was replaced by `view`:
https://github.com/fullcalendar/fullcalendar/issues/4451
