### ISSUE TITLE
TittleFormat week issue

### ISSUE THREAD

**Issue by leventeolahx** [fullcalendar/fullcalendar#4510]
Hello,

TitleFormat for weeks with "w" formatter is not correct. 
E.g.: set the defaultDate date to: '2019-01-13'
the title week number will be 2 but the value should be 3 (as it is in the calendar)

![image](https://user-images.githubusercontent.com/22756232/52575639-d3463100-2e1e-11e9-9700-13f862332da7.png)

https://codepen.io/anon/pen/exrgJZ?&editable=true&editors=001

Cheers,
Levente

**Comment by acerix** [comment]
Your demo uses "W" which is the ISO format, it sounds like you want "w" (lowercase) so it matches your locale:

http://momentjs.com/docs/#/displaying/format/

**Comment by leventeolahx** [comment]
Hi,
Yes, you were right. It works fine.
Thanks
