### ISSUE TITLE
FullCalendar need event for before view render

### ISSUE THREAD

**Issue by SushmaShashidhar** [fullcalendar/fullcalendar#4514]
Is there an event in fullcalendar that gets triggered before a view is rendered while changing views.
My requirement is to set different scroll times for different dates.
Right now I am using renderView, but this gets called after view is rendered, so the change takes place in the next button click. 
I have also tried using html onclick, but if I am clicking on any of the buttons, the click event is triggered after view is rendered.

**Comment by acerix** [comment]
I believe this existing ticket captures this need:
https://github.com/fullcalendar/fullcalendar/issues/3521
↑
Could you please visit the link, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates?

For now, you could use custom buttons that first change the `scrollTime` then change the view as expected.
