### ISSUE TITLE
Move event calendar to other week in AgendaWeek View

### ISSUE THREAD

**Issue by Cris200992** [fullcalendar/fullcalendar#4515]
I would like to move a event from the calendar to other week with dragging in the view AgendaWeek. I tried some options but not work. Is there a function for do this?

**Comment by VilasPT** [comment]
I've been looking for the same thing. It seems that it's not implemented yet.

Please give it a thumbs up here:

https://github.com/fullcalendar/fullcalendar/issues/2542

**Comment by acerix** [comment]
Thanks for pointing that out, I missed this issue and it is a duplicate.

https://github.com/fullcalendar/fullcalendar/issues/2542
↑
Could you please visit the link, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates?
