### ISSUE TITLE
resource-daygrid/main.css does not exist but is mentioned in docs

### ISSUE THREAD

**Issue by cococore** [fullcalendar/fullcalendar#4519]
From docs: https://fullcalendar.io/docs/v4/resource-daygrid-view

From the docs there should be 
"<link href='fullcalendar/resource-daygrid/main.css' rel='stylesheet' />"

main.css file, but that file is not in the package

![screenshot 2019-02-15 at 17 37 00](https://user-images.githubusercontent.com/9106635/52866895-554c9780-3148-11e9-96bb-cb6190a9c02e.png)

P.S.
In docs there is development href link fullcalendar.test in "https://fullcalendar.io/docs/v4/plugin-index" on "event drag-n-drop and resizing" text

**Comment by Hoakie** [comment]
I noticed this too and I think the documentation may be incorrect/legacy.  For the "resource" versions  I think you only need the "base" main.css files.  I had this issue with resource-timegrid but everything worked when I added the timegrid/main.css to my project 

 
@fullcalendar/daygrid/main.css  for resource-daygrid
@fullcalendar/timegrid/main.css for resource-timegrid
@fullcalendar/timeline/main.css for resource-timeline

**Comment by arshaw** [comment]
correct, these stylesheets dont exist and you dont need them. i updated the docs in the `master` branch of the docs repo
