### ISSUE TITLE
dayClick+select on Chrome on Windows tablet

### ISSUE THREAD

**Issue by Yuji0531** [fullcalendar/fullcalendar#4521]
I am sorry if my translation is wrong because my English is not good.

https://fullcalendar.io/docs/date-clicking-selecting-demo

I tested the above URL on Chrome on Windows tablet, but it does not work properly. IE worked correctly.
Originally when touching the date, alert of dayclick is displayed, then alert of select is displayed but select alert is not displayed.
Since long time depressing sometimes comes out, we set localPressDelay locally, but it will not be selected well.

**Comment by acerix** [comment]
I don't have a Windows tablet to test this on, do you get any javascript error?

**Comment by Yuji0531** [comment]
No javascript error.
On Chrome, I need DoubleCliick for dayclick and  that not selected without too long touch (but on Edge no problem.)

**Comment by arshaw** [comment]
@Yuji0531 any way you can provide a screen capture (video or gif)?

also, could you try without the `alert` ? that might be screwing up the screen focus
