### ISSUE TITLE
The last month in the header is bigger than the others in timeline view with visibleRange set and a small slotWidth

### ISSUE THREAD

**Issue by smxdevst** [fullcalendar/fullcalendar#4526]
### Bug Reports
https://jsbin.com/dobowaqatu/edit?html,output

When rendering scheduler with `slotWidth` it renders with 1 month being width bigger. I need to fit all days without scroll thats why I added `slotWidth`

**Comment by acerix** [comment]
Thanks for the report.  I simplified the test case a bit and it does seem like a bug:

https://codepen.io/anon/pen/xMNoGV?editors=0010

**Comment by smxdevst** [comment]
@acerix Thank you

Why its not a bug? I expect to `slotWidth` just scale down whole view and render each cell with same width. But instead all cells are few pixels and last cell takes most of space

**Comment by smxdevst** [comment]
@acerix Thank you

**Comment by smxdevst** [comment]
@acerix It also happens with different days. Example: start 2019-01-01 end 2019-31-12 and etc.

**Comment by arshaw** [comment]
adapted for v5, this now works as intended: https://codepen.io/arshaw/pen/yLeoVjE?editable=true&editors=001

all slots are equal width
