### ISSUE TITLE
extra nowIndicator arrows are created after refetchResources

### ISSUE THREAD

**Issue by dennyak47** [fullcalendar/fullcalendar#4527]
### Bug Reports

https://codepen.io/anon/pen/BMeaOg

Check this out.
After 'refetchResources', inspect the dom of nowIndicator arrow and there are more than one arrow.
If you wait for several minutes, more than one arrow would show up;

Todo:

there should be only one nowIndicator arrow after 'refetchResources';

**Comment by acerix** [comment]
Thanks for the detailed report

**Comment by arshaw** [comment]
Confirmed in v3.x, but would someone be able to reproduce this in 4.x ?

**Comment by acerix** [comment]
This is fixed in v4, updated demo:

https://codepen.io/acerix/pen/MNGJQa?editors=0011
