### ISSUE TITLE
CSS timeslot height changing breaks interaction features

### ISSUE THREAD

**Issue by Lamberthassel** [fullcalendar/fullcalendar#4528]
I've been using 4.0.0-alpha version and use this CSS code to increase the timeslot height:
`.fc-time-grid .fc-slats td {
  height: 75px;
}`

Everything worked fine but I've switched to 4.0.0-beta few days ago and found out that interaction features like dateClick and select callbacks don't work at all (it actually works but only for the very top part of the calendar table)
Here's a link to codepen: https://codepen.io/anon/pen/yZWPPN

Is there any way to fix it? I've tried to find some more legit way to change the timeslot height but I failed (changing height, contentHeight or aspectRatio doesn't affect timeslot size).

**Comment by acerix** [comment]
There isn't a reliable way to change the size in CSS,  you would need a custom view:

https://fullcalendar.io/docs/v4/custom-view-with-js

If you just want each hour to be bigger you can use `slotDuration`:

https://codepen.io/anon/pen/yZWPPN?editors=0010

You could try CSS to hide some of the time slot borders in that case if you don't want them.

**Comment by Lamberthassel** [comment]
Thank you for the prompt reply.

Making a custom view for just changing a slot height sounds like an overkill. 

Using `slotDuration` also breaks the interaction, try to click on any timeslot later than 09:45 am
https://codepen.io/anon/pen/OdYeOB?editors=0010
Is it possible to fix it?

**Comment by acerix** [comment]
There is an open ticket for that issue:
https://github.com/fullcalendar/fullcalendar/issues/4505
↑
Could you please visit the link, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates?

I'm not sure fixing that issue will also fix your issue when modifying the CSS though.

**Comment by Lamberthassel** [comment]
The issue seems to be the same: the lower part of  the agenda view calendar being non-interactive. I've just checked v.4 alpha once again and both custom CSS and increased `slotSuration` works perfectly.

**Comment by Lamberthassel** [comment]
The issue has been fixed together with [#4505](https://github.com/fullcalendar/fullcalendar/issues/4505)
