### ISSUE TITLE
date-clicking-selecting demo is missing the interaction plugin

### ISSUE THREAD

**Issue by Lamberthassel** [fullcalendar/fullcalendar#4529]
Date selecting demo doesn't work correctly cause interaction plugin is missing: https://fullcalendar.io/docs/v4/date-clicking-selecting-demo

I found the link here: https://fullcalendar.io/docs/v4/selectable

**Comment by acerix** [comment]
Thanks for the report

**Comment by arshaw** [comment]
i already fixed this with a recent commit. thanks.
