### ISSUE TITLE
Event Limit per resource

### ISSUE THREAD

**Issue by HeyItsRoi** [fullcalendar/fullcalendar#4532]
Is there a way to limit the number of event shown per category shown in a day. For example given the categories: Meeting, Interview, Call, etc. I would like to have 3 shown per day on each of those and then click on more to show the rest.

**Comment by PhanSon95** [comment]
@HeyItsRoi You're using full-calendar for web or ionic (app) ?
Can you support me , thanks you :)

**Comment by HeyItsRoi** [comment]
@PhanSon95 I'm using fullcalendar for web. :)

**Comment by acerix** [comment]
It's not built-in, but there is an open request to add that feature to other views, so it could apply to resources (categories) as well: 
https://github.com/fullcalendar/fullcalendar/issues/4218
↑
Please visit the link, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates?

**Comment by arshaw** [comment]
I'll close this issue because #4218 seems to match
