### ISSUE TITLE
why this show undefined in this dom?

### ISSUE THREAD

**Issue by zhilianbi520** [fullcalendar/fullcalendar#4533]
<img width="497" alt="c19a7c7ca94c18728530fe082171489f" src="https://user-images.githubusercontent.com/16549630/53393204-b42ad000-39d6-11e9-9f61-5cc13c8db962.png">
when use event add something, this dom show that。。。

**Comment by acerix** [comment]
Would you be able to post a [runnable, stripped-down demonstration of the bug](http://fullcalendar.io/wiki/Reduced-Test-Cases/)? Would really appreciate it because the time saved reproducing will be time spent fixing.
