### ISSUE TITLE
[beta4] Can't drop event near bottom of calendar in timeGridDay

### ISSUE THREAD

**Issue by AlanCrevon** [fullcalendar/fullcalendar#4534]
Hi.

Here is a reproducer : 

- Go to https://fullcalendar.io/docs/v4/external-dragging-demo (official documentation's example for Drag n Drop external events)
- Switch to day view
- Drag and drop an event at the end of the day.
=> You can't drop event after 7:30pm

Actually, depending on the event's duration, sometimes you can't drop it after 7:00 pm. On my own project (4.0.0-beta.4), it's 12:30 pm, and i don't understand why. 

Cheers and thanks for this awesome project.

**Comment by acerix** [comment]
I believe it's the same issue as in this ticket:
https://github.com/fullcalendar/fullcalendar/issues/4505
↑
Could you please visit the link, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates?

**Comment by AlanCrevon** [comment]
I confirm it's is the same as #4505.

Changing the calendar's width as explained in #4503 modifies the hours after wich you can't drop. Actually : you can't drop an event under a line equal whose distance from calendar's top is equal to the calendar's width (not sure how to express this...).

**Comment by arshaw** [comment]
fixed with https://github.com/fullcalendar/fullcalendar/commit/90a978e8dce5f4add8e2322652525a462febac9a. comment again when released

**Comment by AlanCrevon** [comment]
Fix confirmed on v4.0.1 \o/

Thanks :)

**Comment by arshaw** [comment]
[V4 was officially released a few days ago!](https://fullcalendar.io/blog/2019/03/v4-officially-released)

Glad you've tested and noted it's fixed @AlanCrevon
