### ISSUE TITLE
Why is it showing this？？？？？？

### ISSUE THREAD

**Issue by zhilianbi520** [fullcalendar/fullcalendar#4535]
let moment1=moment('2019-09-23T13:00:00');
console.info(moment1);
let moment2=moment('2019-09-24T07:00:00');
console.log('check=>  ',$.fullCalendar.formatRange(moment1, moment2, 'HH:mm:ss'));
<img width="827" alt="20190226203209" src="https://user-images.githubusercontent.com/16549630/53412885-9f196580-3a05-11e9-9ec8-d7c98460da68.png">

fullcalendar :V3.9.0

**Comment by arshaw** [comment]
the same issue as https://github.com/fullcalendar/fullcalendar/issues/4533
&uarr;
Could you please visit the link, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates?

but we still need a recreation. could you post on on that issue?
[instructions: runnable, stripped-down demonstration of the bug](http://fullcalendar.io/wiki/Reduced-Test-Cases/)
