### ISSUE TITLE
dayNameShort is being ignored

### ISSUE THREAD

**Issue by ddesmond1** [fullcalendar/fullcalendar#4536]
this.options = {
      defaultDate: '2019-02-25',
      editable: true,
      aspectRatio: 1.5,
      height: 650,
      monthNamesShort: ['ss'],                               this is being ignored by options in v4
      dayNamesShort: ['S', 'T', 'W', 'T', 'F' , 'S'],      this is being ignored by options in V4

**Comment by acerix** [comment]
Would you be able to post a [runnable, stripped-down demonstration of the bug](http://fullcalendar.io/wiki/Reduced-Test-Cases/)? Would really appreciate it because the time saved reproducing will be time spent fixing.

**Comment by ddesmond1** [comment]
Hi, 
I will try and deploy something, it is a feature that worked until the new version. Just renaming the weekday headers  ===> dayNamesShort: ['S', 'T', 'W', 'T', 'F' , 'S']. I did notice in the documentation that it is in V3, but not mentioned the V4 docs.

Thanks

**Comment by arshaw** [comment]
dayNamesShort has been removed in v4:
https://fullcalendar.io/docs/v4/release-notes#locales
