### ISSUE TITLE
Calendar is not defined in angular6

### ISSUE THREAD

**Issue by chloroplast11** [fullcalendar/fullcalendar#4538]
Hello, I met the same problem as [https://stackoverflow.com/questions/54640441/cannot-get-fullcalendar-v4-to-work-with-angular-and-the-angular-cli](url)

The problem always happened when I import a resource plugin.  If I import e.g. DayGridPlugin, the problem gone.

**Comment by acerix** [comment]
Would you be able to post a [runnable, stripped-down demonstration of the bug](http://fullcalendar.io/wiki/Reduced-Test-Cases/)? Would really appreciate it because the time saved reproducing will be time spent fixing.

**Comment by stehag** [comment]
I get the same problem, just clone the oroject and run it locally to reproduce.
