### ISSUE TITLE
[beta4] Date clicking is not working correctly

### ISSUE THREAD

**Issue by lucasmoyano** [fullcalendar/fullcalendar#4539]
Hello,

I working with the last version of Fullcalendar v4.0.0-beta.4, and I have a problem with the week view.
I can't click after 20:30hs:
[https://codepen.io/frlinw/pen/KJyOeL](https://codepen.io/frlinw/pen/KJyOeL
)

And if I try to change the height of the rows, I can't click after 12pm:
`.fc-time-grid .fc-slats td {
  height:2.5em !important;
}`

I try to make a patch or something, but I can't resolve this. Does anyone know what is going on?

**Comment by arshaw** [comment]
similar to #4501 and #4503

@acerix let's keep this ticket open and not merge it with #4503 because this ticket deals with dayClick, whilst the other ticket deals with event dragging. probably the same underlying issue, but let's keep them separate for now.

**Comment by arshaw** [comment]
fixed with https://github.com/fullcalendar/fullcalendar/commit/90a978e8dce5f4add8e2322652525a462febac9a. comment again when released

**Comment by lucasmoyano** [comment]
> fixed with [90a978e](https://github.com/fullcalendar/fullcalendar/commit/90a978e8dce5f4add8e2322652525a462febac9a). comment again when released

Ohh perfect! Sometimes it's hard to see these bugs in the code. Great job arshaw!

**Comment by arshaw** [comment]
[V4 was officially released a few days ago!](https://fullcalendar.io/blog/2019/03/v4-officially-released)
