### ISSUE TITLE
Enable RefetchResourcesOnNavigate, Resources not able to display

### ISSUE THREAD

**Issue by muhammadumairaslam** [fullcalendar/fullcalendar#4543]
when i enable to refetchResourcesOnNavigate option so resources not render on scheduler.
https://fullcalendar.io/docs/v4/refetchResourcesOnNavigate

Can you add fetchInfo parameter when that option has disabled as you did in past version.

**Comment by acerix** [comment]
Would you be able to post a [runnable, stripped-down demonstration of the bug](http://fullcalendar.io/wiki/Reduced-Test-Cases/)? Would really appreciate it because the time saved reproducing will be time spent fixing.

**Comment by muhammadumairaslam** [comment]
Thank you for the prompt reply.

i didn't use any thing, just enable this option in your given demo. see below link as reference.
https://codepen.io/muhammadumairaslam/pen/pYegvQ

**Comment by acerix** [comment]
`refetchResourcesOnNavigate` is intended for when the resource list is dynamic (JSON or callback function) which is working:

https://codepen.io/anon/pen/EMWMJM?editors=0010

I can see it's not working when `resources` is a static list, but what are you expecting that option to do if the resources never change?

**Comment by muhammadumairaslam** [comment]
Thank you so much for the time you given.

yes i known, sorry my mistake, i put static list in given example.
I identify the actual issue that is producing due to set `null` value into `parentId`.
when i set the empty value in `parentId`. It's working fine.

please check it again the below link.
https://codepen.io/muhammadumairaslam/pen/pYegvQ

**Comment by acerix** [comment]
I can see that the resources don't show with `parentId: null` but that's because there is no resource with `id` of `null`:

https://codepen.io/anon/pen/xBrwrj

The top-level resources should have no `parentId` setting instead of setting it to `null` like the example here:

https://fullcalendar.io/docs/resource-object
