### ISSUE TITLE
How to disable queue for adding many resources?

### ISSUE THREAD

**Issue by HoracioEspinosa** [fullcalendar/fullcalendar#4548]
Hi, i have an issue about this component, when i add a lot of resources it is to slow, this work's fine at first time when we calling to setResources in scheduler.js "ResourceManager.prototype.setResources", but when i call to addResource function this is to slow "ResourceManager.prototype.addResource" specifically in 
_this.trigger('add', resource, _this.topLevelResources); 

i debug this function and the problem is the event render queue in fullcalendar.js the plugin ever wait the previous render resource, but if i call the method how:

`
View.prototype.requestRender = function (func, namespace, actionType) {
        func();
    };`

this works but the design is to bad, the scroll not working

the first view without call func() directly is:
![image](https://user-images.githubusercontent.com/8210280/54048485-f22ead80-41a7-11e9-8f17-95d7b8d3a5a0.png)

when i charge data is this:

![image](https://user-images.githubusercontent.com/8210280/54048580-39b53980-41a8-11e9-9b61-5fc431cb411a.png)

but if i enable the add resources directly with the previous code is the next:
without data:
![image](https://user-images.githubusercontent.com/8210280/54048657-6bc69b80-41a8-11e9-8e3d-1db336c173a1.png)

with data:
![image](https://user-images.githubusercontent.com/8210280/54048689-84cf4c80-41a8-11e9-9e07-c4858afd2322.png)

the last image has not a scroll and not charge the styles of the calendar, i suppose that is is for the namespace load from the queue render event, but im lost here, 

**¿how i cant add multiple resources without wait the queue?**

i was adding my resources with jquery:

`arrayDiffByKey('id', _c_resources, $('#calendar').fullCalendar('getResources')).forEach(function (res) {
                    $('#calendar').fullCalendar('addResource', res, true);
                });
`
the problem is not load data, the problem is the slow render on multiple adding resources

**Comment by acerix** [comment]
Would you be able to post a [runnable, stripped-down demonstration of the bug](http://fullcalendar.io/wiki/Reduced-Test-Cases/)? Would really appreciate it because the time saved reproducing will be time spent fixing.

**Comment by arshaw** [comment]
in v4 you'll be able to do batch rendering
https://fullcalendar.io/docs/v4/Calendar-batchRendering
