### ISSUE TITLE
Clicking on a google calendar event opens in the same window instead of the popup window that appears

### ISSUE THREAD

**Issue by piernik** [fullcalendar/fullcalendar#4550]
Here is demo page of google calendar plugin: https://fullcalendar.io/docs/v4/google-calendar-demo
After clicking on event google calendar opens in the same  window as fullcalendar.
I think it should open in new window.

**Comment by acerix** [comment]
Thanks for pointing it out.  Looks like a bug because there is an empty popup window, then Google Calendar loads in the background window.

**Comment by arshaw** [comment]
returning `false` to prevent the default action is no longer supported in v4, gotta use jsEvent.preventDefault() instead. this example is out of date. this ticket will be for fixing the example

**Comment by piernik** [comment]
@arshaw even if You use `event.preventDefault()` it does not work.

**Comment by arshaw** [comment]
@piernik  i just fixed it. see https://github.com/fullcalendar/fullcalendar-site-static/commit/36fd18229b450a6b9cf2342e1da76591d1fb5b72 ... will show you how to get the url
