### ISSUE TITLE
Some locales have missing or incorrect translations

### ISSUE THREAD

**Issue by micobarac** [fullcalendar/fullcalendar#4551]
I am using scheduler in an Angular application and I have these issues with locales:

1. Serbian, serbian cyrillic, bosnian, croatian, macedonian and many other locales do not have a translation for a year
2. Bosnian and macedonian locales have bad month names, like M03, M04...
3. Serbian locale has header translated in latin, with month and day names in serbian cyrillic
4. Montenegrin locale with 'me' key is missing in locales. It should be created as `me.js` like this:

```javascript
(function(global, factory) {
  typeof exports === 'object' && typeof module !== 'undefined'
    ? (module.exports = factory())
    : typeof define === 'function' && define.amd
    ? define(factory)
    : ((global = global || self),
      ((global.FullCalendarLocales = global.FullCalendarLocales || {}), (global.FullCalendarLocales.me = factory())));
})(this, function() {
  'use strict';

  var me = {
    code: 'me',
    week: {
      dow: 1,
      doy: 7 // The week that contains Jan 1st is the first week of the year.
    },
    buttonText: {
      prev: 'Prethodni',
      next: 'Sljedeći',
      today: 'Danas',
      month: 'Mjеsеc',
      year: 'Godina',
      week: 'Sedmica',
      day: 'Dan',
      list: 'Planеr'
    },
    weekLabel: 'Sed',
    allDayText: 'Cijeli dan',
    eventLimitText: function(n) {
      return '+ još ' + n;
    },
    noEventsMessage: 'Nеma događaja za prikaz'
  };

  return me;
});

```

Adding new language only translates the buttons in the header of the scheduler. Month names and day names all render in default english. How and where do I translate these, without external libraries like moment.js and luxon?

How do I translate a custom button's text that's added to the header?

According to [Release notes](https://fullcalendar.io/docs/v4/release-notes), a [date-formatting](https://fullcalendar.io/docs/v4/date-formatting) plugin or function should be used instead. This page is pretty confusing, without any useful information on how to solve my issue. It only shows info on formatting, but no info on translating.

Where are current day and month names stored internally for the existing locales, mentioned as 1. above?

**Comment by acerix** [comment]
The new default is to use "native" formatting,

**Comment by micobarac** [comment]
However, those translations are incomplete / faulty for the locales I have mentioned above.

**Comment by micobarac** [comment]
If I add a custom button to the header, how to I localize it?

```typescript
    customButtons: {
      resource: {
        text: 'resource',
        click: (info: any) => {
          console.log(info);
        }
      }
    }
```

I've tried adding the translation into a locale file:

```json
    buttonText: {
      prev: 'Prethodni',
      next: 'Sledeći',
      today: 'Danas',
      month: 'Mеsеc',
      year: 'Godina',
      week: 'Sedmica',
      day: 'Dan',
      list: 'Planеr',
      resource: 'Resurs'
    },
```

but, it doesn't work :(.

**Comment by micobarac** [comment]
Analyzing code of `@fullcalendar/core/main.js`,  this is what I found for custom buttons rendering:

```javascript
                            if ((customButtonProps = calendarCustomButtons[buttonName])) {
                                buttonClick = function (ev) {
                                    if (customButtonProps.click) {
                                        customButtonProps.click.call(buttonEl, ev);
                                    }
                                };
                                (buttonIcon = theme.getCustomButtonIconClass(customButtonProps)) ||
                                    (buttonIcon = theme.getIconClass(buttonName)) ||
                                    (buttonText = customButtonProps.text);
                            }
```

It appears that custom buttons' text doesn't get translated at all.

**Comment by acerix** [comment]
Currently there is no way to define custom button text so it's localized based on the `locale` setting, are you requesting that as a new feature?

For now, you could localize that text using gettext.js or similar and recreate the buttons if the locale is changed.

The problems with incorrect/missing translations should be added as separate issues, if possible with [runnable, stripped-down demonstrations](http://fullcalendar.io/wiki/Reduced-Test-Cases/).

**Comment by scrnjakovic** [comment]
On a side note, there is no `me` locale. Correct locale for Montenegro is `sr-ME` and `sr-Latn-ME`.

**Comment by arshaw** [comment]
@micobarac, could you please make a [reduced test case](https://fullcalendar.io/reduced-test-cases) for the [comment you wrote](https://github.com/fullcalendar/fullcalendar/issues/4551#issuecomment-472740198) ? Otherwise we can't begin.

@scrnjakovic , please open another issue for that.
