### ISSUE TITLE
Events that are initially hidden by eventLimit cannot be dropped on the day below in month view

### ISSUE THREAD

**Issue by Loevbo** [fullcalendar/fullcalendar#4552]
### Bug Reports
https://codepen.io/anon/pen/Mxrpga?editors=0010

**RECREATING THE ERROR**

If you click the '+4 more' on February 12 the popover will open , then you have to drag the last event on the list ( which is Meeting at 2:30p ) and drop it on February 19 and it won't work .

But if i take the Meeting at 10:30A and drop it on the 19'th of February then it works.

Is this indeed a bug or am i doing something wrong.

**Comment by acerix** [comment]
Thanks for the report and demo.  It's not obvious why this is happening but I'm pretty sure it's a bug.  `eventAllow` does get called but not `eventDragStop` or `eventDrop`.

https://codepen.io/anon/pen/MxrBEd?editors=0010

**Comment by arshaw** [comment]
I'm nearly certain this is fixed in v4.x, could someone please make a new recreation?
