### ISSUE TITLE
v4 Beta: How to load locales using import syntax?

### ISSUE THREAD

**Issue by realtebo** [fullcalendar/fullcalendar#4555]
Thanks for marvellious v4 !

Thanks for the excellent doc and for all step-by-step included.

I am relatively new to `import` syntax. How can I use the italian localization using `import` statements?

Thanks in advance

**Comment by realtebo** [comment]
Oh, never mind. ... using 

    import { Calendar } from '@fullcalendar/core';

it works.

I advise that 'today' button is not translated into italian. 
Can I help you?

**Comment by realtebo** [comment]
Fixed ... not your fault, but please document it

```
import { Calendar } from '@fullcalendar/core';
import dayGridPlugin from '@fullcalendar/daygrid';
import bootstrapPlugin from '@fullcalendar/bootstrap';

import '@fullcalendar/core/main.css';
import '@fullcalendar/daygrid/main.css';
import it from '@fullcalendar/core/locales/it';

export default function FullCalendarModule() {

    var calendarEl = document.getElementById('calendar');

    calendarEl.innerHTML = "";
    
    var calendar = new Calendar(calendarEl, {
        plugins: [ dayGridPlugin, bootstrapPlugin ],
        locale: it,
    });
    
    calendar.render();

}
 
```

**Comment by arshaw** [comment]
@realtebo , an example was already written here https://fullcalendar.io/docs/v4/locale
