### ISSUE TITLE
refetchResources() and refetchEvents() do nothing when both defined as arrays

### ISSUE THREAD

**Issue by micobarac** [fullcalendar/fullcalendar#4557]
### Bug Reports

In version 4 beta, `refetchResources()` and `refetchEvents()` do nothing when both defined as arrays through getters.
According to the docs, refetch should get new data and re-render calendar, which doesn't happen at all.

**Comment by micobarac** [comment]
In case of using functions as sources for both resources and events, refetch works fine.

**Comment by acerix** [comment]
Would you be able to post a [runnable, stripped-down demonstration of the bug](http://fullcalendar.io/wiki/Reduced-Test-Cases/)? Would really appreciate it because the time saved reproducing will be time spent fixing.

**Comment by tsulatsitamim** [comment]
same here https://jsfiddle.net/xk4cyzjm/

**Comment by tsulatsitamim** [comment]
you can detroy and re render for quick fix

**Comment by micobarac** [comment]
@tsulatsitamim with huge amount of data placed on the calendar, destroying and rendering again is not a good solution.

**Comment by micobarac** [comment]
The alternative solution is to create an Observable and cast it to a Promise:

```typescript
  get resources(): Promise<CalendarResource[]> {
    return this.resources$
      .pipe(
        debounceTime(0),
        take(1),
        share()
      )
      .toPromise();
  }

  get events(): Promise<CalendarEvent[]> {
    return this.events$
      .pipe(
        debounceTime(0),
        take(1),
        share()
      )
      .toPromise();
  }
```

```typescript
  ngAfterViewInit() {
    const calendarElement = this.calendarRef.nativeElement;
    this.calendar = new Calendar(calendarElement, {
      ...this.settings.config,
      ...this.settings.callbacks,
      resources: () => this.service.resources,
      events: () => this.service.events,
      loading: (isLoading: boolean) => this.loading(isLoading)
    } as OptionsInput);

    this.calendar.render();
  }
```

**Comment by arshaw** [comment]
@micobarac you need to post reduced test cases. tho it seems you figured this one out
