### ISSUE TITLE
v4.0.1 endRecur - event ends too early

### ISSUE THREAD

**Issue by toxpal** [fullcalendar/fullcalendar#4559]
Just upgraded from 3.x to 4.0.1 and noticed some bugs/strange behavior. 

I use recurring events that repeat weekly. Since v3 didn't support recurring events, I managed to get them working by re-creating recurring event with the same ID until its last recurrence date. Just like in your demo at https://fullcalendar.io/docs/debug-json-feed.html

Now, v4 supports recurring events, so I modified my feed accordingly. It works, except that **last occurrence is not displayed**. For example,  fullcalendar receives such feed:

```
id: 1
title: "my title"
url: "schedules_edit.php?schedule_id=1"
startRecur: "2019-01-28"
startTime: "17:15:00"
endRecur: "2019-04-01"
endTime: "19:15:00"
daysOfWeek: array(1)
```

All recurring events are displayed, except the last one, which should occur on 2019-04-01. In other words, fullcalendar displays the last entry for this event at 2019-03-25.

Docs ( https://fullcalendar.io/docs/recurring-events ) say: 

> For all-day recurring events, make the endRecur the day after you want your last recurrence.

However, my events are **not** all-day (each event has start time and end time defined), so I should not add one extra day to endRecur, right? 

Also, I tried adding **allDay** option to event (as well as adding **allDayDefault** option to configuration settings), but the same issue still happens, no matter if allDay is included or not (and no matter if allDay is set to true or false).

Is it a bug, or I miss something here?

**Comment by flamber** [comment]
Hi @toxpal 
From what I read, all end-dates are exclusive. And you've missed the first part of the quote:
> **This value is exclusive! I repeat, this value is exclusive!!!** Just like every other end-date in the API.

**Comment by toxpal** [comment]
Thanks for the input. I was probably confused between v3 and v4 because v3 docs ( https://fullcalendar.io/docs/v3/event-object ) also say that **end** is exclusive, but formatting this parameter like "2019-04-01 16:30" always rendered correctly. But that's probably because v3 accepted both date and time into the same parameter "end", while v4 uses separate parameters for date and time.

Thanks again.
