### ISSUE TITLE
V4.0.1 Update NPM

### ISSUE THREAD

**Issue by CollinHerber** [fullcalendar/fullcalendar#4561]
Would like to use V4 in NPM. Please update your NPM package so I can start using V4.

https://www.npmjs.com/package/fullcalendar

**Comment by CollinHerber** [comment]
Even targeting github releases npm does not get the correct files.

**Comment by zachzoup** [comment]
The new version of FullCalendar is a completely separate NPM package, accessible here - https://www.npmjs.com/package/@fullcalendar/core

Be sure to read the [blog post](https://fullcalendar.io/blog/2019/03/v4-officially-released) about the update, where you'll find links and examples like below. 
https://fullcalendar.io/docs/upgrading-from-v3
https://fullcalendar.io/docs/initialize-es6
https://fullcalendar.io/docs/plugin-index
