### ISSUE TITLE
With resourceTimelineYear view, calendar should scroll to current date/month

### ISSUE THREAD

**Issue by micobarac** [fullcalendar/fullcalendar#4564]
### Bug Reports
With `resourceTimelineYear` view, calendar should scroll to current date/month. It actually scrolls to january. `resourceTimelineWeek` and `resourceTimelineMonth` views scroll to current date just fine.

**Comment by acerix** [comment]
I believe this existing ticket captures this need:
https://github.com/fullcalendar/fullcalendar/issues/1037
↑
Could you please visit the link, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates?

**Comment by micobarac** [comment]
Well, it's been a while since that first feature request. Version 4 is out, and scrolling year timeline view into current month's position is not easy without jquery stripped from the v4.

**Comment by tudor2004** [comment]
Is there any solution to implement this?

**Comment by arshaw** [comment]
#1037 is still the ticket that you all need
&uarr;
Could you please visit the link, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates?
