### ISSUE TITLE
Documentation refers to weekNumberTitle which is now weekLabel

### ISSUE THREAD

**Issue by badger-github** [fullcalendar/fullcalendar#4567]
Hi
v4 Docs state weekNumberTitle for "heading text for week numbers" - works in v3 not in v4
Seems to be using weekLabel now
example:
https://codepen.io/anon/pen/QoZrap
Thanks 
Pete

**Comment by acerix** [comment]
Thanks for the report

**Comment by arshaw** [comment]
i'll update the docs and the upgrade guide

**Comment by arshaw** [comment]
thanks! i renamed everything and updated the upgrade guide
https://fullcalendar.io/docs/weekLabel
