### ISSUE TITLE
How to customize event title?

### ISSUE THREAD

**Issue by realtebo** [fullcalendar/fullcalendar#4569]
I cannot find info about how to use HTML in titles. 

My goal is display a font-awesome icon based on event kind via extended props. Or to set html in the title. 
Is there a way?

**Comment by acerix** [comment]
I believe this existing ticket captures this need:
https://github.com/fullcalendar/fullcalendar/issues/2919
↑
Could you please visit the link, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates?
