### ISSUE TITLE
Support for event/resource JSON data sources wrapped in 'data' as in JSON:API v1

### ISSUE THREAD

**Issue by bcorcoran** [fullcalendar/fullcalendar#4571]
Hi,

My application is following the jsonapi.org spec, which a lot of applications follow. That being said, providing fullcalendar v4 a feed generated by my api doesn't work by default because it wraps the collection of objects under "data" as defined by the jsonapi spec.

Can you add a check for that data element or allow us to specify one manually? I'd prefer not to have to create a custom feed that removes the wrapper JUST for fullcalendar.

**Comment by acerix** [comment]
Thanks for the suggestion, info here: https://jsonapi.org/format/#document-top-level

**Comment by arshaw** [comment]
already possible with this hook: https://fullcalendar.io/docs/eventSourceSuccess

**Comment by bcorcoran** [comment]
Thanks, I missed this.

**Comment by bcorcoran** [comment]
I actually ended up having to use events as a function, because events with a simple URL does not send a typical XHR request (it appears under the "Other" tab in chrome dev tools).

If anyone finds this and like me was using axios, here is an example:

`
                events: async function(info, successCallback, failureCallback) {
                    await axios.get('/api/v1/calendar', {})
                        .then(res => {
                            success(res.data.data);
                        })
                        .catch(err => {
                            failureCallback(err);
                        });
                },
`
