### ISSUE TITLE
Incorrect definitions in event-parsing docs

### ISSUE THREAD

**Issue by vwasteels** [fullcalendar/fullcalendar#4573]
in : 
https://fullcalendar.io/docs/event-parsing

multiple fields has the same description :
![Screenshot -  2019-03-22 à 11 06 38](https://user-images.githubusercontent.com/1151398/54815661-c83eb600-4c92-11e9-9a0a-a1b9b7fe92fb.jpg)

**Comment by acerix** [comment]
Thanks for the report

**Comment by arshaw** [comment]
this fix is live
