### ISSUE TITLE
draggedEvent properties cannot be accessed in eventAllow from external drag & drop

### ISSUE THREAD

**Issue by Hoakie** [fullcalendar/fullcalendar#4575]
Currently when dragging an external event, the eventAllow event is fired, however the second parameter "draggedEvent" is not vaild.

Can an event be created from the "eventData" and passed as a parameter into this event?  When dragging an event, its physical  representation of duration is displayed  so should have access eventData before officially "dropped".  It would be nice to be able to have access to the the event information uniformly (whether external or internal) to make decisions

In pen, see browser console for "invalid" draggedEvent properties 
   console.log(draggedEvent);

https://codepen.io/hoakie/pen/rRomYZ?editors=0011

or if trying to access individual property
  console.log(draggedEvent.title); // yields [Cannot read property 'title' of undefined]

**Comment by acerix** [comment]
Confirmed, thanks for the detailed report

**Comment by arshaw** [comment]
fixed in [v4.0.2](https://github.com/fullcalendar/fullcalendar/releases/tag/v4.0.2)!
