### ISSUE TITLE
React Wrapper for resource-timeGrid

### ISSUE THREAD

**Issue by sradgit1** [fullcalendar/fullcalendar#4577]
Hi  -- Not an issue -- more of a request for react wrapper.
Im writing a React Studio Plugin for Fullcalendar-Sheduler 4.0.1  - Resource-TimeGrid.
I need a react wrapper for this.
Any Idea when one would be available.
it needs to include { core, dayGrid, resource-common, timeGrid, resource-timeGrid, interaction }
Plugins.
I have successfully coded a Plugin  (3.*  fullCalendar-sheduler) into React Studio with
 npm -- fullcalendar-reactwrapper-with-scheduler 
 -- magic - but looking forward to non jQuery & moment implementation
Steve

**Comment by acerix** [comment]
I believe this existing ticket captures this need:
https://github.com/fullcalendar/fullcalendar/issues/4252
↑
Could you please visit the link, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates?
