### ISSUE TITLE
Bug: clicking on eventLimit popover 'X' button triggers dateClick

### ISSUE THREAD

**Issue by Deadpikle** [fullcalendar/fullcalendar#4584]
If I have a date limit popover showing, when I click the 'X' button to close the popover, the `dayClick` event for the calendar date underneath the X button is triggered, and it should not be triggered, as the user did not actually click on that date -- at least, in my opinion 😅 .

Codepen:
https://codepen.io/anon/pen/zbQXre (Click '+2 More' on March 12 -> click X to close popover -> JS alert is shown for `dayClick` and it shouldn't be)

Thanks! :)

**Comment by acerix** [comment]
Confirmed, thanks.

**Comment by CollinHerber** [comment]
Just noticed this bug myself! Please update this issue the minute this is fixed to solve my issue.

**Comment by arshaw** [comment]
fixed in [v4.0.2](https://github.com/fullcalendar/fullcalendar/releases/tag/v4.0.2)!
