### ISSUE TITLE
Any way let users confirm before add a external event onto calender?

### ISSUE THREAD

**Issue by huajiongyu** [fullcalendar/fullcalendar#4587]
Before drop a external event onto calender, I need user to confirm it. how can I do that?
This is my code, but is that any other way ?
Thank you for help!

      eventReceive : function(info){
        if(!confirm('confirm add event?')){
          info.event.remove()
        }
      }

**Comment by acerix** [comment]
I made a demo to test:

https://codepen.io/acerix/pen/ZPgJQr?editors=0010

It seems like a good way to do it, is there is an issue with that method?

**Comment by huajiongyu** [comment]
HAHA, thank you, Acerix.
