### ISSUE TITLE
4.0.1 Custom view bug

### ISSUE THREAD

**Issue by hvilppu** [fullcalendar/fullcalendar#4592]
As in example:
https://fullcalendar.io/docs/custom-view-with-js

Code rows:
https://codepen.io/anon/pen/rRXXLJ

Not work. I got error:
Argument of type '{ views: { custom: typeof CustomView; }; }' is not assignable to parameter of type 'PluginDefInput'.
  Object literal may only specify known properties, and 'views' does not exist in type 'PluginDefInput'.

Bug in code or example?

**Comment by acerix** [comment]
Would you be able to post a [runnable, stripped-down demonstration of the bug](http://fullcalendar.io/wiki/Reduced-Test-Cases/)? The codepen you linked to doesn't seem to work.

**Comment by arshaw** [comment]
you're probably using a beta version (where it was named `viewDefs` or something). if you update to the latest stable version, it will probably work (renamed to `views`)
