### ISSUE TITLE
Prev button not works

### ISSUE THREAD

**Issue by roman-huliak** [fullcalendar/fullcalendar#4594]
Hi,
prev button in header not working. I must click to "next" to "repair" prev button.
Example on official homepage: https://fullcalendar.io/

After page load click on prev button not works. After change month with "next" button, prev button works correctly. 
No errror or warning in console.

**Comment by haksolo** [comment]
Probably a bug, but figured out a quick workaround: try adding `defaultDate` option with valid date.
```
var calendar = new FullCalendar.Calendar(calendarEl, {
  plugins: [ 'dayGrid' ],
  defaultDate: '2019-03-31',
});
```

**Comment by haksolo** [comment]
There is probably something wrong with today's date: `2019-03-31`. If you change the `defaultDate` to other date (except `2019-03-29`, `2019-03-30`), it fixes somehow.

**Comment by arshaw** [comment]
dup. closing in favor of this one:
https://github.com/fullcalendar/fullcalendar/issues/4595
&uarr;
Could you please visit the link, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates?
