### ISSUE TITLE
Previous button not working after clicking on today button in month view

### ISSUE THREAD

**Issue by JasperBarzilaij** [fullcalendar/fullcalendar#4595]
Hi!

The previous button doesn't work ~anymore after the today button has been clicked~ at certain dates.
When you click the next button, the previous button will start to work again.

As mentioned by @haksolo, it seems it has something to do with the current date.
I've tested it again and it happens only when the date is between `2019-03-29` and `2019-03-31` (inclusive).

## Steps to reproduce
~1. Click on the previous or next button (this will work fine).~
~2. Click on the today button.~
3. Click on the previous button **(this is where it won't work)**.
4. Click on the next button.
5. Click on the previous button **(this is where it will work again)**.

## Reduced test case on CodePen
https://codepen.io/JasperBar/pen/yrLbLv

------------------

Let me know if you have any questions!

**Comment by haksolo** [comment]
I believe it has something to do with today's date `2019-03-31`, a bug actually.  Try again testing it by tomorrow.

**Comment by arshaw** [comment]
i noticed this as well. will fix

**Comment by arshaw** [comment]
fixed in [v4.0.2](https://github.com/fullcalendar/fullcalendar/releases/tag/v4.0.2)!

occurred when starting out on the 31st of a month, and then moving to a month that had no 31st. i thought these types of bugs were behind us :/
