### ISSUE TITLE
Rrule events not displaying in daily view (timeGridDay)

### ISSUE THREAD

**Issue by bhavikji** [fullcalendar/fullcalendar#4596]
I am working with fullcalendar v4 and it ships with great changes and eventually much-needed changes. but here I am facing issue with Rrule in daily view.

I have created a couple of events one with no range but flagged as every day and another event with a range of 7 days with every day flag, the events are working fine in month and week view but not showing up in day view. 
Along with that, the daily recurring event is not able to show in week view on Sunday. Check the fiddle given below.
 
https://jsfiddle.net/bhavikbamania/0m56aLv1/1/

**Comment by arshaw** [comment]
confirmed. modified fiddle: https://jsfiddle.net/Lqojsdar/1/

**Comment by bhavikji** [comment]
@arshaw hey adam, thanks for such quick response, though in your modified fiddle I can't see any difference, the event is not rendering on sunday in week view and not at all visible in day view.

**Comment by arshaw** [comment]
the modified fiddle was just to make the code more minimal for me. anyway...

officially fixed in [v4.0.2](https://github.com/fullcalendar/fullcalendar/releases/tag/v4.0.2)!
