### ISSUE TITLE
[FullCalendar v4.0.1] Force Event Duration Flag does not work as intended

### ISSUE THREAD

**Issue by dalmaxor** [fullcalendar/fullcalendar#4597]
Hello, I have encountered the following issue:
Regarding the docs, when forceEventDuration is set to true: 
> If an event’s end is not specified, it will be calculated and assigned to the Event Object using defaultTimedEventDuration or defaultAllDayEventDuration.

This does not happen in the demo I provided, as the end date of the event (see CodePen's console after dragging an event) is never set.

Steps to reproduce  (Codepen with minimal case: https://codepen.io/anon/pen/xebdrB?editors=0010):

1.  Drag an external event to the calendar
2.  Open Codepen's console and see that every value of event.end logged is null (If multiple, the last one is the result of dropping the event)

![imagen](https://user-images.githubusercontent.com/20403858/55340652-673e8b80-54a5-11e9-8940-575b33a91d0f.png)

Thank you in advance.

P.S: In case anyone else encountered this problem and the bug isn't solved yet: just specify a duration in the Draggable eventData either manually or using the calendar.defaultTimedEventDuration.

**Comment by arshaw** [comment]
confirmed, thanks

**Comment by arshaw** [comment]
fixed in [v4.0.2](https://github.com/fullcalendar/fullcalendar/releases/tag/v4.0.2)!
