### ISSUE TITLE
eventLimit does not work in timeGrid

### ISSUE THREAD

**Issue by CollinHerber** [fullcalendar/fullcalendar#4598]
Codepen: https://codepen.io/anon/pen/YMPxGj

I would expect The week view and day view to limit viewable events within the column http://prntscr.com/n5zebx with a "Show More", like what is happening in the header of those views for full-day events, in the time slot.

Perhaps this is not a bug but rather a feature request? The documentation on eventLimit is rather slim so I'm unsure what is intended and not intended.

In the pen I tried many different options: timeGrid, week, day

Any additional information about the expected behavior, or if this is possible please let me know.

**Comment by acerix** [comment]
The docs for `eventLimit` should mention which views it applies to, there is an existing ticket to have something similar for that view:
https://github.com/fullcalendar/fullcalendar/issues/4218
↑
Could you please visit the link, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates?

**Comment by arshaw** [comment]
#4218 is the correct feature request for this.
