### ISSUE TITLE
Broken links on plugin index page

### ISSUE THREAD

**Issue by zachjharris** [fullcalendar/fullcalendar#4602]
Most of the `(generic)` links on the plugin index (https://fullcalendar.io/docs/plugin-index) are linked to fullcalendar.test instead of fullcalendar.io. Changing the TLD to `io` fixes all of the links that I tested.

**Comment by acerix** [comment]
Thanks for the report

**Comment by arshaw** [comment]
thanks! fixed: https://fullcalendar.io/docs/plugin-index
