### ISSUE TITLE
I am facing issue for the Height and contentheight with view week and day

### ISSUE THREAD

**Issue by preetitiwari12** [fullcalendar/fullcalendar#4604]
I am using angular 6 Scenarios, in day and week view
1. When I am day or week view 
2. With events its taking the contentHeight and Height which i have specified.
3. Then the date range comes where there is no events it takes the height 
4. Then click next the in contentheight and height are same but on Calendat the height changes.

It happens in day and week view only

**Comment by acerix** [comment]
Would you be able to post a [runnable, stripped-down demonstration of the bug](http://fullcalendar.io/wiki/Reduced-Test-Cases/)? Would really appreciate it because the time saved reproducing will be time spent fixing.

**Comment by preetitiwari12** [comment]
I can provide you the steps and other details

Below are the code details
1. We are using angular 6
2. options we have used are
contentHeight:400px
{
  editable: true,
            dropAccept: '.fc-content-skeleton',
            eventLimit: true, // for all non-agenda views
            views: {
                agenda: {
                    eventLimit: 1 // adjust to 6 only for agendaWeek/agendaDay
                }
            },
            header: false,
            events: this.events,
            contentHeight: contentHeight,
            height: contentHeight,
            defaultView: this.view,
            columnFormat: (this.view=== 'day') ? 'D ddd' : 'ddd',
            slotLabelFormat: 'h(:mm)A',
            allDaySlot: true,
            allDayText: '',
            businessHours: {
                // days of week. an array of zero-based day of week integers (0=Sunday)
                dow: [1, 2, 3, 4, 5], // Monday - Friday
                start: this.startTime, // a start time (in 24 hour format)
                end: this.endTime, // an end time (in 24 hour format)
            },
            showNonCurrentDates: false,
            eventOverlap: true,
            noEventsMessage: 'No meetings to display',
            scrollTime: moment.duration(8, 'hour')
}

3. html we have used 

 <ng-fullcalendar #eventCalendar oncontextmenu="return false;" 
                        [(options)]="options"
                        [(eventsModel)]="events" id="Scheduler" (eventRender)="eventRender($event.detail)"
                        (viewRender)="viewRender($event.detail)" (eventResize)="eventResized($event.detail.event)"
                        (eventDragStart)="eventDragStarted($event.detail.event)" 
                        (eventDrop)="eventDropped($event.detail.event)"
                        (dayClick)="dayClicked($event.detail)"  
                         (windowResize) ="windowResize($event)"                  
                       ></ng-fullcalendar>
       

Below are the steps.with example 
1. In current week(7- April-2019 to 13-April-2019) we have events as per the contentheight it will have 400px height i.e. fc-view-container will have 400px
2. When user click on next week (14-April to 20 April) where there is no events  as per the contentheight it will have 400px height i.e. fc-view-container will have 400px
3.When user click on next week (14-April to 20 April) where there is no events  as per the contentheight it will have 400px  height BUT NOW THE " fc-view-container" will TAKE NOW  HEIGHT TAKEN IS AUTO


Kindly let me know if still more information you needed.

**Comment by acerix** [comment]
It's best if you can submit a runnable demo of the issue.  There is a new debugging template that you could use as a starting point:

https://stackblitz.com/github/fullcalendar/fullcalendar-example-projects/tree/master/angular
