### ISSUE TITLE
timeGridEventMinHeight is not defined in OptionsInput or OptionsInputBase interface 

### ISSUE THREAD

**Issue by HugzM** [fullcalendar/fullcalendar#4605]
It seems since timeGridEventMinHeight is the new name for agendaEventMinHeight it has not been included in the type definition of OptionsInputBase.
All other timeGrid-Specific Options such as allDaySLot, allDayText, ect are there .

**Comment by arshaw** [comment]
confirmed, thanks

(i don't think `agendaEventMinHeight` was ever included in the first place)

**Comment by arshaw** [comment]
this is fixed in v4.1.0
