### ISSUE TITLE
Maintain scroll position when changing days in timeGrid view

### ISSUE THREAD

**Issue by preetitiwari12** [fullcalendar/fullcalendar#4607]
Currently in options we have set the scrolltime to 8:00 AM, when the user scroll down to 8:00 PM and the click next it should maintain the scroll position. instead of setting the scroll position to 8:00 AM.

**Comment by acerix** [comment]
For reference, here's a demo showing that it resets to `scrollPosition`: https://codepen.io/acerix/pen/KYMvye?editors=0010

**Comment by acerix** [comment]
I just found a duplicate request:
https://github.com/fullcalendar/fullcalendar/issues/4273
↑
Could you please visit the link, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates?

**Comment by acerix** [comment]
`eventAfterAllRender` is called even with no events.

**Comment by justingrant** [comment]
@acerix - `eventAfterAllRender` is excluded from the V4 docs and, AFAIK, isn't present in V4. Is there another event that's available to track changes to vertical scroll position in a `timeGrid` view?

**Comment by zealot128** [comment]
For version 5, i've had luck using the allDay hooks:

```
        allDayDidMount() {
            setTimeout(() => that.scrollBack(), 0)
          },
          allDayWillUnmount() {
            that.updateScrollPosition()
          },
```

with updateScrollPosition and scrollBack like:

```
      updateScrollPosition() {
        const slots = document.querySelector('.fc-timegrid-slots')
        if (!slots) return
        this.scrollPosition = slots.parentNode?.parentNode?.scrollTop;
      },
      scrollBack() {
        if (this.scrollPosition && this.scrollPosition > -1)
          document.querySelector('.fc-timegrid-slots').parentNode.parentNode.scrollTop = this.scrollPosition;
      },
```

(from a Vue app with a ``scrollPosition`` data state)

**Comment by ahoopes16** [comment]
For anyone looking for the answer to this in FullCalendar v6, you can provide the prop `scrollTimeReset={false}` on the `FullCalendar` React component. That option should be available in the direct implementation of FullCalendar as well.

https://fullcalendar.io/docs/scrollTime
