### ISSUE TITLE
Events with no T in datetime not rendering Safari/Mac

### ISSUE THREAD

**Issue by nbcnc** [fullcalendar/fullcalendar#4610]
This issue only seems to apply to FullCalendar on **Safari/Mac** (Safari Version 12).  I haven't seen this problem in any other browser.

In FullCalendar v4.0.1, events with full times as the `start` or `end` (YYYY-MM-DD HH:MM:SS) do not display.  However, when the `start` or `end` are entered as simple dates (YYYY-MM-DD), they do display.

Here's an example:
https://jsfiddle.net/marcparillo/79mk20p8/

**Comment by arshaw** [comment]
Confirmed.

If you place a T between the date and time, like `2019-04-06T04:30:00`, things will work cross-browser. https://jsfiddle.net/uobth91c/

Regardless, I will get this to work cross-browser.

**Comment by arshaw** [comment]
@Uudis, in the other thread, you mentioned the dates are *requested* with the `T`. Does this happen when FC calls a JSON event feed?

**Comment by piernik** [comment]
When can we expect this bug fixed? I't major issue for my clients.

**Comment by aravael** [comment]
i have the same one problem

**Comment by aravael** [comment]
@arshaw, any updates for this issue?

**Comment by arshaw** [comment]
this is fixed in v4.1.0

**Comment by nbcnc** [comment]
Works great!  Thank you!

Marc Parillo
Sr Manager, Web Operations
NBC News Channel
704-770-6382

On Apr 24, 2019, at 3:02 PM, Adam Shaw <notifications@github.com<mailto:notifications@github.com>> wrote:


this is fixed in v4.1.0

-

**Comment by needwit** [comment]
Yo tengo el mismo problema, tengo un calendario con eventos que se muestra la hora inicial, en android las horas se visualiza correctamente pero en ios aparecen diferente EJ. la hora 12:00 en ios me muestra como 00:00
