### ISSUE TITLE
eventDrop not working properly

### ISSUE THREAD

**Issue by Mowso** [fullcalendar/fullcalendar#4611]
I have some issues when I use the eventDrop callback on the month view. I did some research and found out once in a while the info.event.end's value is null.

This might be a bug.

You can see it [here](https://codepen.io/anon/pen/MRyNoz?editors=0011)

**Comment by acerix** [comment]
If the end time is not specified the value will be `null`. https://fullcalendar.io/docs/event-object 

In that case you could use the start time instead:

https://codepen.io/anon/pen/KYNBvK?editors=0010
