### ISSUE TITLE
Editable:false not working 

### ISSUE THREAD

**Issue by ganySA** [fullcalendar/fullcalendar#4612]
Hi

I have set editable:false on init of the calendar and it doesnt seem to be working - i am using hammerjs in angular. 

It seems no matter the setting the appointments are editable and draggable even if this setting is explicitly set to false.

**Comment by acerix** [comment]
Would you be able to post a [runnable, stripped-down demonstration of the bug](http://fullcalendar.io/wiki/Reduced-Test-Cases/)? Would really appreciate it because the time saved reproducing will be time spent fixing.

**Comment by ganySA** [comment]
Hi

I have solved it - it was the editable flag on the appointment data that was set which overrides the main setting.

Thanks
