### ISSUE TITLE
temporary addEvent for no specific event source

### ISSUE THREAD

**Issue by ganySA** [fullcalendar/fullcalendar#4614]
Summary:
When adding an appointment using addEvent() and no datasource, it can result in duplication when this field is empty, because it does not add it to the existing datasource mapped but creates a new one?

**Background:**
I am using a semi-hack to update an appointment:
event.remove()
scheduler.addEvent()

This way i dont have to match the properties. However it is not possible to use scheduler.events[] to specify the source using the above approach because the "addEvent" has an optional parameter for the source ID which you cannot specify when using just scheduler.events[]

So this is what ends up happening:
1) I use an ajax call to populate events[]
2) I then remove an event using remove() and re-addEvent()
3) but when re-added the event (with no second parameter), and then refresh my datasource for the first one i get two of the same events.
4) addEvent without a second parameter, can result in duplicate appointments.

The only way to get around this is to use eventSources and not events
```
eventSources: [

          // your event source
          {
            events: (fetchInfo, successCallback, failureCallback) => {
              this.loadEvents(fetchInfo.start, fetchInfo.end, fetchInfo.timeZone, successCallback);
            },
            id: 'myremotesource'
          }
```

And then later on when adding an appointment:

`scheduler.addEvent(obj,'myremotesource')`

**Comment by acerix** [comment]
Would you be able to post a [runnable, stripped-down demonstration of the bug](http://fullcalendar.io/wiki/Reduced-Test-Cases/)? Would really appreciate it because the time saved reproducing will be time spent fixing.

**Comment by arshaw** [comment]
@acerix , this is an issue with limitations of the API, not a bug report.

@ganySA , your workaround works well, but yeah, it'd be nice to have something more convenient. maybe if the second argument is `true`, that would imply the event should be kept around until the next refetch (of no event source in particular).

**Comment by arshaw** [comment]
in v5, specifying the second argument as `true` will have this effect:
https://fullcalendar.io/docs/Calendar-addEvent

**Comment by imtiyaj786** [comment]
Hey I'm implanting full calendar js in My **Salesforce** org with Lightning web component  and I am showing Each (month ,week ,day) with specific event and with the help of  **viewRender**  event getting **intervalStart**, **intervalEnd** date and pass to my apex class and getting event according to start and end date.

But problem was that when I click next and previous button each and every time my event get duplicate value like attachment show. **AnyOne**,   please help me to fix this problem. how can I remove the duplicate event when my component is refresh.
$(ele).fullCalendar('renderEvents', this.events, true);

![duplicateCalendar](https://user-images.githubusercontent.com/55544765/221105281-048881a3-a9ef-487c-a837-55a711329b33.PNG)
![duplicateCalendar2](https://user-images.githubusercontent.com/55544765/221105521-7c639aec-b526-4a78-85e2-86ec2963ec26.PNG)
