### ISSUE TITLE
Typo in rrule docs (Plugin file not loaded for rrulePlugin)

### ISSUE THREAD

**Issue by panfanky** [fullcalendar/fullcalendar#4615]
Hi, I think you have a typo at this page:
https://fullcalendar.io/docs/rrule-plugin
works for me only as
`plugins: [ rrule ],`
instead of
`plugins: [ rrulePlugin ],`
which gives me "Plugin file not loaded for rrulePlugin".

**Comment by acerix** [comment]
Thanks for the report.

**Comment by arshaw** [comment]
@acerix do you have a recreation?

**Comment by arshaw** [comment]
it's supposed to be `rrulePlugin`

**Comment by acerix** [comment]
I get the error if I try include the plugin 'rrulePlugin' on codepen but 'rrule' works:

https://codepen.io/anon/pen/YMNMxd?editors=0010

But 'rrulePlugin' works in the typescript-example project, I just didn't realize the plugins had a different name there.

**Comment by arshaw** [comment]
if you're using script tags and browser globals, it's `[ 'rrule' ]`, but if you are using ES6 modules, you need to already have the reference to the module, and assuming you've imported it as `rrulePlugin`, you must do `[ rrulePlugin ]`.

**Comment by moto-geek** [comment]
I recommend updating the documentation really needs to be updated for this. This one got me stuck for a couple of days on a project. I change to 'rrule' and everything started working for me @arshaw
