### ISSUE TITLE
AllDay event can not be dragged if more than 3 events in all day section

### ISSUE THREAD

**Issue by bruceyue** [fullcalendar/fullcalendar#4616]
https://fullcalendar.io/docs/external-dragging-demo
Check this link, if we drag event from left side to calendar, if event number more than 3, only first two events can be dragged, the remaining can not. But I need it. Is it a bug?

**Comment by acerix** [comment]
Thanks for the report, it looks like a bug to me.

Here are the steps to reproduce:

1. Switch to week view
2. Drag at least 3 events to the same all day slot
3. Only the first 2 events in the all-day slot can be dragged (and the top of the third)

**Comment by bruceyue** [comment]
When can we have it?
Thanks

**Comment by arshaw** [comment]
this is fixed in v4.1.0

**Comment by bruceyue** [comment]
> this is fixed in v4.1.0

Thanks so much

**Comment by bruceyue** [comment]
I just tested all works fine.
