### ISSUE TITLE
Recurring events that extend past the end of the view range do not show in the following view range (eg. next week)

### ISSUE THREAD

**Issue by bhavikji** [fullcalendar/fullcalendar#4617]
Hey, I am working with v4 of fullcalendar and using rrule for recurrence of events but wondering how can I add an event with long range say an event with a duration of 8 days. One way I figured out was using duration when all day event is set to be true, something like this.

`{
                        title: 'event with everyday with range',
                        allDay: true,
                        rrule: {
                            freq: 'daily',
                            dtstart: '2019-04-02',
                            until: '2019-04-09'
                        },
                        duration: '192:00'
 },`

but this event is not rendering properly in timeGridWeek and timeGridDay I am attaching the fiddle for the reference. Any other way to do this?

https://jsfiddle.net/bhavikbamania/j3pn9frb/3/

**Comment by acerix** [comment]
Thanks for the report, it seems like a bug to me since those events should be showing in the all-day slots for every day they are ongoing. 

I didn't find a good workaround but this might work better in timeline view:

https://fullcalendar.io/docs/timeline-view

**Comment by bhavikji** [comment]
hey, @acerix thanks for such a quick response as recommended above I tried the following in v4.0.1 and v4.0.2 both but events are not rendering properly as it should have, check the given updated fiddle.

In timeGridDay only the main event is rendering ie.., an event from 2nd April to 9th April no other recurring events are rendered.
In timeGridWeek, things have gone more weird as events are rendered up to 13th April, not up to 16th April.

https://jsfiddle.net/bhavikbamania/t541ekqd/1/

**Comment by arshaw** [comment]
i believe you're seeing this bug: https://github.com/fullcalendar/fullcalendar/issues/4596

can you try to upgrade and see if it's fixed?

**Comment by bhavikji** [comment]
@arshaw Nope, not that bug, I have upgraded to v4.0.2 and yes #4596 works fine, this is different I have not added v4.0.2 because I don't have CDN for that version in my local env, I am using v4.0.2 and this bug appears when I am trying to add an event with range, I even tried with the method suggested by @acerix though by this approach I am able to see events in weekly and daily view, still it is just a workaround and events are not properly rendering even by following the suggested approach.

**Comment by bhavikji** [comment]
@arshaw @acerix any update on this?

**Comment by arshaw** [comment]
running in 4.0.1:
https://jsfiddle.net/arshaw/ufkqet96/4/

running in 4.0.2:
https://jsfiddle.net/arshaw/fuc9m4et/6/

i guess i don't understand what you mean by "not rendering correctly"

**Comment by arshaw** [comment]
look at my v4.0.2 demo for correct behavior. the 4.0.1 demo is exhibiting the rrule bug i previously mentioned.

**Comment by bhavikji** [comment]
@arshaw I beg your pardon for misunderstanding, but in your v4.0.2 demo checkout for the last recurring event which starts from 9th April, logically it should end on 16th April since it is a week-long event, and in Monthly view it is ending on 16th April as it should be, but in the week view it is ending on 13th April instead of 16th April. 
Also, it is not appearing in the day view, after 9th April whereas logically it should appear till 16th April as they are appearing in the month view.

https://jsfiddle.net/arshaw/fuc9m4et/6/

**Comment by acerix** [comment]
Thanks for the details.  It might be more clear with just one recurring event compared to a normal event:

https://jsfiddle.net/v4sxqza1/1/

The rrule event should be 100 days long but only shows in the first week.

**Comment by bhavikji** [comment]
@acerix exactly, however, it should  reoccur upto 100 days as it is recurring in month view, however in your fiddle I have noticed one more thing that the same bug exist in monthly view as well "event with everyday with range" is recurring in April month only.

**Comment by arshaw** [comment]
Thanks @bhavikji. I see what's going on now. I'll have this fixed for the next release.

**Comment by bhavikji** [comment]
@arshaw hey thanks for fixing this, can I have v4.2.0 on npm via `npm i fullcalendar` command?
