### ISSUE TITLE
Monthly events by weekday not rendering using rrule plugin

### ISSUE THREAD

**Issue by bhavikji** [fullcalendar/fullcalendar#4618]
Hello folks, after reading documentation of rrule which offers support for recurring events on specific day say `Every month on the 2nd last Friday` I tried to replicate the same functionality in fullcalendar but it doesn't allow me to do the same in full calendar here is my JSON by which I am trying to do, The following code just crashes the calendar and the console reads the following error

> Uncaught TypeError: Cannot read property 'nth' of undefined

`{
                        title: 'event with every month (all day)',
                        allDay: true,
                        rrule: {
                            freq: 'monthly',
                            byweekday: [rrule.FR.nth(-2)],
                            dtstart: '2019-04-12',
                            until: '2021-04-12',
                        },
                        duration: '24:00',
                    },
`
Apparently, I tried the following way as well and it's not working as it should have

and here is fiddle for the same. I guess it should be shipped this feature seems to be pretty cool, plus I need this one in one of my project!
` {
                        title: 'event with every month (all day)',
                        allDay: true,
                        rrule: {
                            freq: 'monthly',
                            byweekday: ['tu'],
                            dtstart: '2019-04-09',
                            until: '2021-04-09',
                        },
                        duration: '24:00',
                    },`

Here is the fiddle link 
https://jsfiddle.net/bhavikbamania/g1w9ehp8/2/

**Comment by acerix** [comment]
`rrule` is the plugin wrapper which contains the actual `RRule` object, so you could use it like `rrule.RRule.FR.nth(-2)`:

https://jsfiddle.net/74rpqkdz/

**Comment by bhavikji** [comment]
thanks @acerix most perfect solution I was looking for!
