### ISSUE TITLE
Bug: ScrollTime not respected

### ISSUE THREAD

**Issue by ganySA** [fullcalendar/fullcalendar#4623]
ScrollTime is not respected in the following scenario:

      this.scheduler.refetchResources();
      this.scheduler.refetchEvents();
      this.scheduler.render();   (this seems to break the ScrollTime)

ScrollTime goes back to 12am.

**Comment by acerix** [comment]
Would you be able to post a [runnable, stripped-down demonstration of the bug](http://fullcalendar.io/wiki/Reduced-Test-Cases/)? Would really appreciate it because the time saved reproducing will be time spent fixing.

**Comment by darkzeroman** [comment]
@acerix: I made a short demo: https://codesandbox.io/embed/8z1104q0m2

Scroll time should be 2:00PM, but it's 12:00AM.

I went and used a previous version of `@fullcalendar/timegrid` `(4.0.1)`, and the scroll time works. Looks like an issue with the latest version.

**Comment by kylethielk** [comment]
We are seeing this on 3.10.0. 

Here is a bare bones example of this: https://jsfiddle.net/9vxtf3hb/1/
