### ISSUE TITLE
Internal scrollbar appears at some zoom levels

### ISSUE THREAD

**Issue by dzonatan** [fullcalendar/fullcalendar#4624]
Internal scrollbar appears in IE11 with 90% zoom.

![image](https://user-images.githubusercontent.com/5166666/55860927-f458a300-5b7d-11e9-9786-ec35bde81466.png)

**Comment by acerix** [comment]
Confirmed in Firefox and Chrome as well.  The scrollbar when the zoom is changed from 100% to 90% but not at 80% and not after changing back to 90% from 80%.  Other zoom levels also have the issue.

https://fullcalendar.io/docs/daygrid-view-demo

**Comment by arshaw** [comment]
This was fixed in 4.3.0 though please start using 4.3.1
Releases: https://github.com/fullcalendar/fullcalendar/releases

@dzonatan could you please confirm the problem is fixed?
