### ISSUE TITLE
sass build issue on Windows 10

### ISSUE THREAD

**Issue by mohas** [fullcalendar/fullcalendar#4626]
Hi, I can't seem to be able to build sass files on my win 10 machine, my first mistake was using js sass instead of gem sass which is now resolved but now I get 

directory $(bin
error No such file or directory @ rb_sysopen - $(bin/sass-args.js)

I removed $( and ) from the package.json script now I get sass-args.css file in bin folder as follow:
[sass-args.css](https://gist.github.com/mohas/fd707c34dd0e0d52d6a6ce8442bd3798)

**Comment by acerix** [comment]
Would you be able to post a [runnable, stripped-down demonstration of the bug](http://fullcalendar.io/wiki/Reduced-Test-Cases/)? Would really appreciate it because the time saved reproducing will be time spent fixing.

**Comment by arshaw** [comment]
@acerix , since this is a build-system issue, it won't be recreatable on a code playground.

@mohas, in the `master` branch I've moved the codebase to a different, more portable SASS library. can you try?
