### ISSUE TITLE
updateSize doesn't trigger eventPositioned

### ISSUE THREAD

**Issue by yakovyarmo** [fullcalendar/fullcalendar#4628]
When I call updateSize function the eventPositioned isn't triggered.
Is that the expected result?

**Comment by acerix** [comment]
Yes, `eventPositioned` is called when the events are originally positioned, but not when their position is updated.

**Comment by yakovyarmo** [comment]
So what callback can I use when the position is updated?

**Comment by acerix** [comment]
That is not built-in but you could attach a callback to the DOM element in `eventRender` that would do something when the position/size of the event changes, although that will not be very efficient.

What are you looking to use that callback for?
