### ISSUE TITLE
Angular 7 responsive header 

### ISSUE THREAD

**Issue by electron23** [fullcalendar/fullcalendar#4629]
I am using angular 7 and want that the header be responsive like that:

[add] [refresh]
[prev] [prevYear] [title] [next] [next Year]
[dayListDay] [dayGridMonth] [daylistWeek]

I tried to use scss mixin breakpoint with the filling settings, but with no success:

/deep/ .fc-toolbar .fc-left, .fc-toolbar .fc-center, .fc-toolbar .fc-right {
        display: inline-block;
        float: none !important;
    }

Does anyone successfully made it responsible with angular 7?

**Comment by acerix** [comment]
Would you be able to post a [runnable, stripped-down demonstration of the bug](http://fullcalendar.io/wiki/Reduced-Test-Cases/)? Would really appreciate it because the time saved reproducing will be time spent fixing.

If your issue is related to the new Angular component you can report it here:

https://github.com/fullcalendar/fullcalendar-angular

**Comment by electron23** [comment]
So I have created an plunk: https://stackblitz.com/github/rlmilymw

I am still not able to fix it and the code here will not work: https://stackoverflow.com/questions/18492078/fullcalendar-js-adjust-header-for-mobile

It looks like your link will redirect me to the official fullcalendar package here. I actually use the official fullcalendar package like documented here: https://fullcalendar.io/docs/angular 

npm install --save @fullcalendar/angular @fullcalendar/core @fullcalendar/daygrid

**Comment by electron23** [comment]
I got it working:

`@import '../../../@theme/styles/themes';
@import '~bootstrap/scss/mixins/breakpoints';
@import '~@nebular/theme/styles/global/breakpoints';

/deep/ .nb-theme-default .btn {
    padding: 5px 1.5rem !important;
}

@include media-breakpoint-down(sm) {
 
    ::ng-deep full-calendar > div.fc-toolbar {
        display: block !important;
    }

    ::ng-deep full-calendar > div.fc-toolbar > div.fc-left,
    ::ng-deep full-calendar > div.fc-toolbar > div.fc-center,
    ::ng-deep full-calendar > div.fc-toolbar > div.fc-right {
        float: none !important;
        display:inline-block !important;
    }

    ::ng-deep full-calendar > div.fc-toolbar > div.fc-center > button {
        padding: 5px 5px !important
    }

    ::ng-deep full-calendar > div.fc-toolbar > * > :not(:first-child) {
        margin-left: 2px;
    }

    ::ng-deep full-calendar > div.fc-toolbar.fc-header-toolbar > div.fc-center > button:nth-child(2) {
        margin-right: 5px;
    }

    ::ng-deep full-calendar > div.fc-toolbar.fc-header-toolbar > div.fc-center > h2 {
        margin-right: 5px !important;
    }
    
}`

Thanks!
