### ISSUE TITLE
Resize option for Selected Dates across multiple months in FullCalendar

### ISSUE THREAD

**Issue by khurram-ishaque** [fullcalendar/fullcalendar#4631]
![Selecting-Days-Across-Months-arrows](https://user-images.githubusercontent.com/49519598/55960187-b181f280-5c85-11e9-908f-c5854b73cd8b.jpg)

I just started using Full Calendar 4. Its awesome. All things working great.

I am using the Event resizing option without any hassle. 
But couldn't find same option for Selected Dates for adding events.
For example, I select dates in April, and I want to continue my selection to 10th of May, But I think currently it is not possible.
I went through new feature requests and issues, but this exact feature did not listed there.

Kindly bestow with your opinion if this option is likely to be include in near future ?
Or should I need to work it out my own way ?

Thank you so much for wonderful Calendar Plugin. Thumbs Up!!!

**Comment by acerix** [comment]
Thanks for the suggestion, I think that would be a useful feature but will not likely to be added in the near future since there are many other feature requests so you likely want to come up with something yourself.

**Comment by khurram-ishaque** [comment]
I am working on it, Hopefully will get it working!
