### ISSUE TITLE
slotDuration CSS issues 

### ISSUE THREAD

**Issue by GinFoB** [fullcalendar/fullcalendar#4632]
Hi everyone,

i add slotDuration attribute =>      slotDuration: '00:45:00' 

I get 
<img width="1085" alt="image" src="https://user-images.githubusercontent.com/10551642/56099725-85c26f00-5f08-11e9-910e-43716f06c306.png">

Plz how to fix this bug

**Comment by acerix** [comment]
Would you be able to post a [runnable, stripped-down demonstration of the bug](http://fullcalendar.io/wiki/Reduced-Test-Cases/)? Would really appreciate it because the time saved reproducing will be time spent fixing.

**Comment by GinFoB** [comment]
@acerix I remove all unrelated stylesheets and JS files. I get the same bug i use "^4.0.2".  

I can't add code in codepen because i can't find version 4.0.2 in CDN cloud.

Thanks.

**Comment by acerix** [comment]
You can use the "Standard v4" debugging template at the bottom of this page which already includes 4.0.2:

https://fullcalendar.io/reduced-test-cases
