### ISSUE TITLE
Danish locale changes the slotLabelFormat divider and can't be overriden

### ISSUE THREAD

**Issue by alvaroagarfer** [fullcalendar/fullcalendar#4640]
When formatting the slotLabelFormat for the Danish locale the divider between hours and minutes is ".", and I wish to set it up to ":" but I can't.

I am not sure where is that modification being loaded from, since inside the locale file for Danish from fullcalendar I can't find any property related to this.

Also, as a reference, moment.js for Danish follows the desired format: HH:mm https://github.com/moment/moment/blob/master/locale/da.js

The following pen has the slotLabelFormat modified, and it displays the hours as HH:mm when the locale property is removed.

https://codepen.io/anon/pen/XQPeMR

Thank you in advance.

Alvaro

**Comment by acerix** [comment]
As of version 4, the dates are [native JavaScript dates](https://fullcalendar.io/docs/date-object), so how they are localised is determined by the browser and all my browsers use a period for the time separator in the Danish locale. 

You could revert back to moment.js formatting using the [moment plugin](https://fullcalendar.io/docs/moment-plugins):

https://codepen.io/acerix/pen/ZZqYgG?editors=0010
