### ISSUE TITLE
Day double click

### ISSUE THREAD

**Issue by gattomannaro** [fullcalendar/fullcalendar#4641]
Hi, is it possible to have the double click feature on a single day?
Thanks

**Comment by acerix** [comment]
I believe this existing ticket captures this need:
https://github.com/fullcalendar/fullcalendar/issues/638
↑
Could you please visit the link, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates?
