### ISSUE TITLE
Sometimes `view: View` event parameters are `DateComponent` instances. Is this OK?

### ISSUE THREAD

**Issue by justingrant** [fullcalendar/fullcalendar#4644]
4 places in FullCalendar code trigger an event with a `view: View` parameter that is declared as a `DateComponent`, not a `View`. Is this OK?  `View` inherits from `DateComponent`, so it's certainly possible that some `DateComponent` instances are also `View` instances.  But is this always true when triggering events?  If so then it's easy to add a type cast to fix this. If not, then how to resolve?  Here's some options: 
* pass `null` if the component's `isView` property is falsy
* pass the component's `view` property if the component's `isView` property is falsy
* pass the component's `view` property in all cases (even if the component's `isView` property is true)
* change the TS type declarations for these event parameters from `view: View` to `view: DateComponent<any>`

BTW, I found these while working on a (filing soon) PR to enable type-safe event handling and triggering. I've gotten far enough to be able to check across the entire FullCalendar codebase to find places where events are triggered that don't match their TypeScript declarations. In almost all of these cases, it was the declarations (not runtime code) that were wrong and I'll fix those in my PR. But in the case of `view: View`, I wasn't sure what to do so I'm asking for advice.

UPDATE: I think I have an answer for two of the cases below, because all codepaths that trigger  those events are calling them on `context.view` (which is a `View`) so it's safe to cast them to `View`.  The other two still look like they may be bugs.

Here's the problematic code snippets: 

1. **`drop`**
https://github.com/fullcalendar/fullcalendar/blob/f827f233581338ceb9723eabb7f895731498fd5b/src/interaction/interactions/EventDragging.ts#L301-L306 The corresponding code for external drags uses `finalHit.component.view`, not `finalHit.component` like the code above for internal drops: 
https://github.com/fullcalendar/fullcalendar/blob/f827f233581338ceb9723eabb7f895731498fd5b/src/interaction/interactions-external/ExternalElementDragging.ts#L130-L139

2. **`eventReceive`**
https://github.com/fullcalendar/fullcalendar/blob/f827f233581338ceb9723eabb7f895731498fd5b/src/interaction/interactions/EventDragging.ts#L307-L319 The corresponding code for external drags also re-uses the same `finalView` variable (which is `finalHit.component.view`) that was defined in case 1 above.
https://github.com/fullcalendar/fullcalendar/blob/f827f233581338ceb9723eabb7f895731498fd5b/src/interaction/interactions-external/ExternalElementDragging.ts#L154-L165

3. **`eventPositioned`**
_UPDATE: This event is only triggered in `DateComponent.triggerRenderedSegs()`. This method is only called in two places, both of which call it on `ComponentContext.view` so it's safe to cast `this` to a view.  I'll PR this change._
https://github.com/fullcalendar/fullcalendar/blob/f827f233581338ceb9723eabb7f895731498fd5b/src/core/component/DateComponent.ts#L183-L203~~

4. **`eventDestroy`** 
_UPDATE: This event is only triggered in `DateComponent.triggerWillRemoveSegs()`. This method is only called in two places, both of which call it on `ComponentContext.view` so it's safe to cast `this` to a view.  I'll PR this change._
https://github.com/fullcalendar/fullcalendar/blob/f827f233581338ceb9723eabb7f895731498fd5b/src/core/component/DateComponent.ts#L215-L227

**Comment by acerix** [comment]
Thanks for the report, I'm not sure if that is intentional.

Do you get a TypeScript error when the param is not as expected?

**Comment by justingrant** [comment]
@acerix - Not on current master branch because event-handler parameters are typed as `any` so invalid params are _never_ caught by the compiler.  
https://github.com/fullcalendar/fullcalendar/blob/f827f233581338ceb9723eabb7f895731498fd5b/src/core/Calendar.ts#L711-L719

I just submitted a PR #4657 that will enable type checking on event handler params, and with type checking enabled then I definitely get TS errors on the code excerpted in this issue.

**Comment by arshaw** [comment]
#4657 has been merged.

summary: in the TypeScript, yes, sometimes we are passing a DateComponent in as a View, but in reality they are always View objects (View is a subclass of DateComponent). this requires internal code cleanup, which we don't create issues for on the issue tracker.
