### ISSUE TITLE
All Travis builds are failing (Node 12 issue)

### ISSUE THREAD

**Issue by justingrant** [fullcalendar/fullcalendar#4649]
All builds are failing in Travis because of a problem with Node 12 support. (Node 12 was released only a few days ago). See https://discourse.elm-lang.org/t/travis-build-failing-and-other-occassions/3546

I just submitted PR #4648 to fix this problem.

**Comment by acerix** [comment]
Thanks for the report, I can see your PR fixes the Travis errors that show in your other PR.

https://github.com/fullcalendar/fullcalendar/pull/4648/checks

**Comment by wagnermaciel** [comment]
@acerix I believe this is a [known issue](https://github.com/gulpjs/gulp/issues/2324) which will not be resolved because gulp 3 is no longer supported.

Would another possible solution be just to upgrade to gulp version 4+ ?

**Comment by justingrant** [comment]
If it's going to take a while to do the gulp upgrade, then I'd suggest just leaving Travis on Node 11 in the meantime. Until Travis builds are fixed then all PRs will fail CI tests. This makes it hard for PR authors to know if their code is working... and hard for maintainers to know which PRs passed tests and which ones aren't ready yet.  TL;DR - the current state is wasting everyone's time, so fixing it seems like a pretty high priority. Upgrading Gulp seems like it could proceed on a more leisurely pace.
