### ISSUE TITLE
Make FullCalendar easier to setup and build by switching to JS Sass

### ISSUE THREAD

**Issue by justingrant** [fullcalendar/fullcalendar#4651]
Currently, you can't clone the fullcalendar repo, run npm install, and then build because a global install of Sass is required. 

Furthermore, you must use the Ruby version of Sass (`gem install sass`) instead of the JS version (`npm i -g sass`) because the `--nosourcemap` command-line parameter in package.json is `--no-source-map` in the JS variant of Sass CLI.  Having on a non-JS dependency complicates things (I assume especially for Windows where Ruby won't be installed by default). It's also possible that using this separate dependency might be the cause of #4626, although I'm not a Windows user so can't repro.

Also FYI: the Ruby version of Sass (the one used in the Travis config) is end-of-lifed, so even if we don't swtich to a JS Sass, using the Ruby one is probably something to move away from. Here's the output I just got from installing Ruby Sass on my Mac: 
```
Ruby Sass has reached end-of-life and should no longer be used.

* If you use Sass as a command-line tool, we recommend using Dart Sass, the new
  primary implementation: https://sass-lang.com/install

* If you use Sass as a plug-in for a Ruby web framework, we recommend using the
  sassc gem: https://github.com/sass/sassc-ruby#readme

* For more details, please refer to the Sass blog:
  https://sass-lang.com/blog/posts/7828841

```

Anyway, requiring a global, non-JS dependency seems to add unnecessary complexity to the setup, build, and dependency-updating process. It'd be easier if Saas was a local devDependency that could be installed and updated just like all other dev dependencies.

**Comment by arshaw** [comment]
this has actually been the case since v4 i believe:
https://github.com/fullcalendar/fullcalendar/blob/v4.3.1/package.json#L101
