### ISSUE TITLE
Custom event object attributes are not working on V4

### ISSUE THREAD

**Issue by dcangulo** [fullcalendar/fullcalendar#4652]
In version 3, I can drag an external event into the calendar with a `customAttribute` like this:

```javascript
$(this).data('event', {
  title: $.trim($(this).text()),
  stick: true,
  customAttribute: 'custom attribute'
});
```
Then if I click on the event that has been dragged into the calendar I can do this:
```javascript
eventClick: function( event, jsEvent, view ) {
 console.log(event.title); // WILL PRINT 'My Event 1'
 console.log(event.customAttribute) // WILL PRINT 'custom attribute'
}
```

Codepen for V3: https://codepen.io/dcangulo/pen/PgxXbb

But in version 4, I do it like this:

```javascript
new Draggable(containerEl, {
  itemSelector: '.fc-event',
  eventData: function(eventEl) {
    return {
      title: eventEl.innerText,
      customAttribute: 'custom attribute'
    };
  }
});
```

Then on my `eventClick`:

```javascript
eventClick: function(info) {
 console.log(info.event.title); // WILL PRINT 'My Event 1'
 console.log(info.event.customAttribute); // WILL PRINT 'undefined'
}
```

Codepen for V4: https://codepen.io/dcangulo/pen/yrQGVj

Can't I add custom attributes on event objects anymore in V4? Is there any workaround to this?

I also noticed that in the Docs of V3 (https://fullcalendar.io/docs/v3/event-object), it mentions **Non-standard Fields**, wherein V4 (https://fullcalendar.io/docs/event-object) it isn't mentioned anywhere.

Anyway, thanks for this wonderful package.  :)

**Comment by acerix** [comment]
In version 4, there's a new property `extendedProps` for non-standard attributes, it works if you use that:

https://codepen.io/anon/pen/zXXLRv?editors=1010

**Comment by dcangulo** [comment]
I see. Thank you very much. This would definitely do the job. :)
