### ISSUE TITLE
The timeGridDay times will flash in IE11

### ISSUE THREAD

**Issue by drmflying** [fullcalendar/fullcalendar#4653]
### Bug Reports V4.1.0
In IE 11
When I change the date in timeGridDay. The view times will flash.
<img width="920" alt="WX20190426-183640@2x" src="https://user-images.githubusercontent.com/3291182/56802342-5e499b80-6852-11e9-942f-65a00c8e0939.png">

**Comment by acerix** [comment]
I tested this demo in IE 11 on Windows 8 and don't see any flashing of the times:

https://fullcalendar.io/docs/timegrid-standard-view-demo

Please confirm if you see the issue in that demo, and which version of Windows you are using.  Also try turning off browser addons if you have any.

**Comment by drmflying** [comment]
Windows 10 IE version is 11.523.17134.0
Windows 7 IE version is 11.0.9600.17843

**Comment by acerix** [comment]
Thanks for the details, do you see the issue in this demo?

https://fullcalendar.io/docs/timegrid-standard-view-demo

Otherwise can you send a link to the demo in your video so I can test that one?

**Comment by drmflying** [comment]
https://fullcalendar.io/docs/timegrid-standard-view-demo

**Comment by acerix** [comment]
I just tested in Windows 7 using the same version as you and don't see the issue.  

Do you have any addons installed in IE and are there any errors in the console (press F12 to open the console). 

Also let me know if there is any other info that would help me to reproduce this issue.

**Comment by drmflying** [comment]
The console errors are 'Objects do not support "forEach" attributes or methods' in demo-to-codepen.js (121,3).

addons only have Shockwave Flash

**Comment by acerix** [comment]
Thanks for the info.  I also get that error now, and found that IE11 doesn't support `forEach` as it's used in the demo:

https://developer.mozilla.org/en-US/docs/Web/API/NodeList/forEach#Browser_Compatibility

That error is specific to the demos though and not related to the "flashing" issue you have.

**Comment by acerix** [comment]
The demos are working again in IE11 now.

I still can't replicate this issue, I'm testing with the VirtualBox VMs from here:

https://developer.microsoft.com/en-us/microsoft-edge/tools/vms/

**Comment by arshaw** [comment]
i was able to reproduce the original problem in IE11

i just checked v5 and the issue is fixed!
