### ISSUE TITLE
Bug with 'inverse-background'

### ISSUE THREAD

**Issue by Dev1lDragon** [fullcalendar/fullcalendar#4659]
### Bug Reports
I have problem with Inverse Backgrounds in FullCalendar v4.1.0.

```
let calendarEl = document.getElementById(this.element_id);
this.calendar = new FullCalendar.Calendar(calendarEl, {
    plugins: [ 'timeGrid' ],
    height: "auto",
    nowIndicator : true,
    defaultView: 'timeGridWeek',
    defaultDate: "2019-04-17",
    events: [
       {
            id: 2,
            start: '2019-04-17 10:00:00',
            end: '2019-04-17 11:00:00',
            color: 'blue',
            rendering: 'inverse-background'
        } , {
            id: 2,
            start: '2019-04-17 14:00:00',
            end: '2019-04-17 15:00:00',
            color: 'blue',
            rendering: 'inverse-background'
        } , {
            id: 2,
            start: '2019-04-17 14:00:00',
            end: '2019-04-17 15:00:00',
            color: 'blue',
            rendering: 'inverse-background'
        } , {
            id: 2,
            start: '2019-04-17 14:00:00',
            end: '2019-04-17 15:00:00',
            color: 'blue',
            rendering: 'inverse-background'
        } , {
            id: 2,
            start: '2019-04-17 14:00:00',
            end: '2019-04-17 15:00:00',
            color: 'blue',
            rendering: 'inverse-background'
        }
    ]
});
this.calendar.render();
```
when i use this code events that share the same id wouldn't grouped together when this rendering happens.

example: https://codepen.io/dev1ldragon/pen/jRRPYz

**Comment by acerix** [comment]
I don't see any issue with the rendering, how do you expect it to look?

As of version 4, every event needs to have a unique ID, you can use rrule to make a repeating event:

https://fullcalendar.io/docs/rrule-plugin

**Comment by Dev1lDragon** [comment]
I expected as in other version element with same id is grouped and made 1 laier with white space in [10:00:00-11:00:00] and [14:00:00-15:00:00].
https://fullcalendar.io/docs/background-events -> Inverse Backgrounds -> Events that share the same id will be grouped together when this rendering happens

**Comment by acerix** [comment]
Thanks for the info, I missed that in the docs.  There is no longer any grouping of events with the same ID, so the docs should be updated, and I don't think that functionality exists in version 4 yet.

**Comment by Dev1lDragon** [comment]
inverse background grouping will be implemented or not?

**Comment by arshaw** [comment]
in v4, you gotta use `groupId` to associate them together instead of `id`.

https://codepen.io/arshaw/pen/GLLexQ?editors=0010

the docs are wrong right now (they say `id`). i'll update them

**Comment by Dev1lDragon** [comment]
Tnx for ansver

**Comment by acerix** [comment]
Reopening because docs still need to be update
