### ISSUE TITLE
v 4.1.0 not backwards compatible with 3.9.0

### ISSUE THREAD

**Issue by oliversiegel** [fullcalendar/fullcalendar#4661]
thanks for all your work making this calendar, i love it, it's super useful!

I just tried adding a feature to my implementation, and decided to upgrade first. Turns out it's not backwards compatible...

`$(...).fullCalendar is not a function`

**Comment by acerix** [comment]
jQuery was removed from version 4, there's an upgrade guide here:

https://fullcalendar.io/docs/upgrading-from-v3
