### ISSUE TITLE
how to trigger event change date? 

### ISSUE THREAD

**Issue by CuongStf** [fullcalendar/fullcalendar#4662]
I use lib Fullcalendar in vuejs
I use view Render event in config but it belong data function, it's don't allow access this or anything (store, function, exp)?
How to i can trigger a event in $store object?
Or recommend for me solution instead?
```
configEvent: {
        locale: 'vi',
        defaultView: 'month',
        lazyFetching: true,
        viewRender (view, element) {
          if (view.type === 'month') {
            let titleDateSplit = view.title.split(' ');
            let filterEvent = {
              year: titleDateSplit[2],
              month: (Number(titleDateSplit[1]) < 10) ? ('0' + titleDateSplit[1]) : (titleDateSplit[1])
            };
            getListEvent(filterEvent)
              .then(res => {
                this.$store.dispatch('setListEventFilter', res.data);
              });
          }
        },
        header: {
          right: ' month,agendaWeek,agendaDay',
          center: 'title',
          left: 'prev,next'
        },
        footer: {
          center: 'prev,next'
        }
      },
```

**Comment by trungk18** [comment]
@CuongStf So basically you want to trigger this `this.$store.dispatch('setListEventFilter', res.data)` inside the viewRender, am I right? 
Could you please show your Vue component code, include how you initiate the Fullcalendar inside Vue and the $store too.

**Comment by acerix** [comment]
I'm not sure what you are asking. One way to change an event's dates is `event.setDates`:

https://fullcalendar.io/docs/Event-setDates

It might help if you can provide a [runnable, stripped-down demonstration of the bug](http://fullcalendar.io/wiki/Reduced-Test-Cases/).

**Comment by CuongStf** [comment]
> @CuongStf So basically you want to trigger this `this.$store.dispatch('setListEventFilter', res.data)` inside the viewRender, am I right?
> Could you please show your Vue component code, include how you initiate the Fullcalendar inside Vue and the $store too.



> @CuongStf So basically you want to trigger this `this.$store.dispatch('setListEventFilter', res.data)` inside the viewRender, am I right?
> Could you please show your Vue component code, include how you initiate the Fullcalendar inside Vue and the $store too.

Yes. That what i want

**Comment by CuongStf** [comment]
`
<template>
  <div class="">
    <el-row>
      <div class="navigation-model between mb-25">
        <el-col :span="10">
          <el-input
            size="medium"
            placeholder="Tìm kiếm ..."
            class="input-seach"
            clearable
            :prefix-icon="
              searching ? 'fa fa-spinner fa-spin' : 'el-icon-search'
            "
            v-model="filters.search"
          >
          </el-input>
        </el-col>
        <el-button
          @click="createModel"
          size="medium"
          class="btn-back"
          icon="el-icon-plus"
        >Tạo sự kiện</el-button>
      </div>
    </el-row>
    <el-row class="event-model">
      <full-calendar
        ref="calendar"
        :config="configEvent"
        :events="events"
        @event-selected="eventSelected"
      />
    </el-row>

    <el-dialog
      title="Thay đổi sự kiện"
      :visible.sync="dialogEvent"
      v-loading="loadingEvent"
      width="75%"
      top="1vh"
      lock-scroll
    >
      <el-form
        ref="modelEvent"
        :model="modelEvent"
        @submit.native.prevent="submit('modelEvent');"
        label-width="150px"
        :rules="ruleForm"
        label-position="top"
      >
        <el-form-item label="Ânh đại diện">
          <div class="avatar">
            <div class="display">
              <img
                v-if="imageDemo"
                :src="imageDemo"
                class="avatar-fullView"
              />
              <img
                v-else-if="modelEvent.thumbnail && imageDemo === ''"
                :src="base_url + modelEvent.thumbnail"
                class="avatar-fullView"
              />
              <div v-else>
                <div class="avatar-holder center"><span>avatar</span></div>
              </div>
              <input
                id="iconImage"
                type="file"
                ref="inputFile"
                @change="changeIcon"
                style="display: none"
              />
            </div>
            <div
              class="overlay clickable center"
              @click="openFile"
            >
              <span class="el-icon-plus"></span>
            </div>
          </div>
        </el-form-item>
        <el-row
          :gutter="12"
          type="flex"
        >
          <el-col :span="12">
            <el-form-item
              label="Tiêu đề"
              prop="title"
            >
              <el-input
                size="medium"
                v-model="modelEvent.title"
                class="input-seach inputLog"
                ref="inputName"
              ></el-input>
            </el-form-item>
          </el-col>
          <el-col :span="6">
            <el-form-item
              label="Thời gian bắt đầu"
              prop="date_start"
            >
              <el-date-picker
                size="medium"
                v-model="modelEvent.date_start"
                type="datetime"
                :placeholder="null"
                value-format="yyyy-MM-dd HH:mm:ss"
                format="HH:mm dd/MM/yyyy"
                class="date-inline inputLog"
              >
              </el-date-picker>
            </el-form-item>
          </el-col>
          <el-col :span="6">
            <el-form-item
              label="Thời gian kết thúc"
              prop="date_end"
            >
              <el-date-picker
                size="medium"
                v-model="modelEvent.date_end"
                type="datetime"
                :placeholder="null"
                value-format="yyyy-MM-dd HH:mm:ss"
                format="HH:mm dd/MM/yyyy"
                class="date-inline inputLog"
              >
              </el-date-picker>
            </el-form-item>
          </el-col>
        </el-row>
        <el-form-item label="Nội dung">
          <vue-ckeditor
            v-model="modelEvent.content"
            :config="configEditor"
          />
        </el-form-item>
        <el-form-item label="Chọn tin tức liên quan">
          <el-select
            v-model="modelEvent.news_ids"
            multiple
            filterable
            size="medium"
            placeholder="Chọn tin tức"
          >
            <el-option
              v-for="item in listNews"
              :key="item._id"
              :label="item.title"
              :value="item._id"
            >
            </el-option>
          </el-select>
        </el-form-item>
        <el-row
          :gutter="12"
          type="flex"
        >
          <el-col :span="6">
            <el-form-item label="Hiển thị sự kiện: ">
              <el-switch
                v-model="modelEvent.public"
                :active-value="1"
                :inactive-value="2"
              >
              </el-switch>
            </el-form-item>
          </el-col>
          <el-col :span="6">
            <el-form-item label="Hiển thị cho khách: ">
              <el-switch
                v-model="modelEvent.public_guest"
                :active-value="1"
                :inactive-value="2"
              >
              </el-switch>
            </el-form-item>
          </el-col>
          <el-col :span="6">
            <el-form-item label="Cho đăng kí: ">
              <el-switch
                v-model="modelEvent.join_event"
                :active-value="1"
                :inactive-value="2"
              >
              </el-switch>
            </el-form-item>
          </el-col>
          <el-col :span="6">
            <el-form-item label="Số người tham gia: ">
              <p>{{numberPeopleJoins}}</p>
            </el-form-item>
          </el-col>
        </el-row>
        <el-form-item>
          <el-button
            icon="el-icon-check"
            type="success"
            plain
            @click="submit('modelEvent');"
          >Xác nhận</el-button>
          <el-button
            icon="el-icon-close"
            @click="cancelModel"
          >Hủy bỏ</el-button>
          <el-tooltip content="Xóa sự kiện">
            <el-button
              size="medium"
              plain
              class="btn-small"
              type="primary"
              icon="el-icon-delete"
              @click="confirmDelete(modelEvent.event_id);"
            >
              Xóa sự kiện
            </el-button>
          </el-tooltip>
        </el-form-item>
      </el-form>
    </el-dialog>
  </div>
</template>

<script>
import { mapActions } from 'vuex';
import { FullCalendar } from 'vue-full-calendar';
import 'fullcalendar/dist/locale/vi';
import { getListEvent, deleteEvent, editEvent } from '@/api/event';
export default {
  name: 'Event',
  props: ['listNews'],
  components: {
    VueCkeditor: () => import('vue-ckeditor2'),
    FullCalendar
  },

  data () {
    return {
      searching: false,
      loading: false,
      filters: {
        search: ''
      },

      numberPeopleJoins: 0,

      modelEvent: {
        news_ids: []
      },

      table: {
        database: []
      },

      dialogEvent: false,
      loadingEvent: false,
      imageDemo: '',
      base_url: process.env.BASE_URL,
      events: [],
      configEvent: {
        locale: 'vi',
        height: '90%',
        defaultView: 'month',
        lazyFetching: true,
        viewRender (view, element) {
          // if (view.type === 'month') {
          //   let titleDateSplit = view.title.split(' ');
          //   let filterEvent = {
          //     year: titleDateSplit[2],
          //     month: (Number(titleDateSplit[1]) < 10) ? ('0' + titleDateSplit[1]) : (titleDateSplit[1])
          //   };
          //   getListEvent(filterEvent)
          //     .then(res => {
          //       this.$store.dispatch('setListEventFilter', res.data);
          //     });
          // }
        },
        header: {
          right: ' month,agendaWeek,agendaDay',
          center: 'title',
          left: 'prev,next'
        },
        footer: {
          center: 'prev,next'
        }
      },
      ruleForm: {
        title: [
          {
            required: true, message: 'Trường bắt buộc nhập', trigger: 'blur'
          }
        ],
        date_end: [
          {
            required: true, message: 'Trường bắt buộc nhập', trigger: 'blur'
          }
        ],
        date_start: [
          {
            required: true, message: 'Trường bắt buộc nhập', trigger: 'blur'
          }
        ]
      }
    };
  },
  methods: {
    ...mapActions(['setLoading', 'setStopLoading'])
}
}
`

**Comment by CuongStf** [comment]
My data
`
<script>
export default {
  props: ['listNews'],
  components: {
    FullCalendar
  },
  data () {
    return {
      searching: false,
      loading: false,
      filters: {
        search: ''
      },
      numberPeopleJoins: 0,
      modelEvent: {
        news_ids: []
      },
      table: {
        database: []
      },
      dialogEvent: false,
      loadingEvent: false,
      imageDemo: '',
      base_url: process.env.BASE_URL,
      events: [],
      configEvent: {
        locale: 'vi',
        height: '90%',
        defaultView: 'month',
        lazyFetching: true,
        viewRender (view, element) {
          // if (view.type === 'month') {
          //   let titleDateSplit = view.title.split(' ');
          //   let filterEvent = {
          //     year: titleDateSplit[2],
          //     month: (Number(titleDateSplit[1]) < 10) ? ('0' + titleDateSplit[1]) : (titleDateSplit[1])
          //   };
          //   getListEvent(filterEvent)
          //     .then(res => {
          //       this.$store.dispatch('setListEventFilter', res.data);
          //     });
          // }
        },
        header: {
          right: ' month,agendaWeek,agendaDay',
          center: 'title',
          left: 'prev,next'
        },
        footer: {
          center: 'prev,next'
        }
      },
      ruleForm: {
        title: [
          {
            required: true, message: 'Trường bắt buộc nhập', trigger: 'blur'
          }
        ],
        date_end: [
          {
            required: true, message: 'Trường bắt buộc nhập', trigger: 'blur'
          }
        ],
        date_start: [
          {
            required: true, message: 'Trường bắt buộc nhập', trigger: 'blur'
          }
        ]
      }
    };
  },
  methods: {}
}
`

**Comment by CuongStf** [comment]
My data 
`
data () {
    return {
      searching: false,
      loading: false,
      filters: {
        search: ''
      },

      numberPeopleJoins: 0,

      modelEvent: {
        news_ids: []
      },

      table: {
        database: []
      },

      dialogEvent: false,
      loadingEvent: false,
      imageDemo: '',
      base_url: process.env.BASE_URL,
      events: [],
      configEvent: {
        locale: 'vi',
        height: '90%',
        defaultView: 'month',
        lazyFetching: true,
        viewRender (view, element) {
          if (view.type === 'month') {
            let titleDateSplit = view.title.split(' ');
            let filterEvent = {
              year: titleDateSplit[2],
              month: (Number(titleDateSplit[1]) < 10) ? ('0' + titleDateSplit[1]) : (titleDateSplit[1])
            };
            getListEvent(filterEvent)
              .then(res => {
                this.$store.dispatch('setListEventFilter', res.data);
              });
          }
        },
        header: {
          right: ' month,agendaWeek,agendaDay',
          center: 'title',
          left: 'prev,next'
        },
        footer: {
          center: 'prev,next'
        }
      },
}`

**Comment by acerix** [comment]
Since viewRender is a callback, `this` is not the Vue object as you are expecting.  You could store the Vue object in a global variable so it can be accessed from the callback.

https://vuejs.org/v2/guide/instance.html

**Comment by arshaw** [comment]
I believe this ticket boils down to having `this` be a reference to the Vue instance.

Could you please open up a ticket on the [Vue issue tracker](https://github.com/fullcalendar/fullcalendar-vue/issues) if so?
