### ISSUE TITLE
Callbacks when nowIndicator is rendered/repositioned

### ISSUE THREAD

**Issue by Dev1lDragon** [fullcalendar/fullcalendar#4663]
### Feature Requests
if its posible to add now indicator update event?

**Comment by mdevDE** [comment]
I also would appreciate having such a now indicator update event for render and unrender.

However, you can do it on your own:
In: TimeGrid.prototype.renderNowIndicator = function (segs, date)
trigger your event like so:
$(document).trigger('nowRendered', [nowTime]);

and in: TimeGrid.prototype.unrenderNowIndicator = function ()
trigger your event like so:
$(document).trigger('nowUnrendered',[your options]);

Maybe this can be included in a future update.

**Comment by acerix** [comment]
@Dev1lDragon To confirm, are you looking for a callback function when the now indicator is rendered?

**Comment by mdevDE** [comment]
Yes I am looking for a callback when the now indicator is rendered(top, nodes and date) and unrendered(). Currently I use the approach posted above to produce this behaviour:
<img width="1132" alt="Bildschirmfoto 2019-05-10 um 22 50 34" src="https://user-images.githubusercontent.com/37185489/57556006-12c8de80-7376-11e9-8e56-08c75a129fa7.png">

**Comment by Dev1lDragon** [comment]
i need now indicator calback to reder not picable reriods

**Comment by acerix** [comment]
Do you mean you are looking for an callback that would fire when the indicators moves, but not when it is initially rendered?

**Comment by Dev1lDragon** [comment]
y

**Comment by zaalbarxx** [comment]
I created pull request for this feature. Basically the reason behind this commit is to gain ability to modify the `now` indicator so I can expand it to other columns inside timeGridView. Currently the indicator shows up only for the current day column which is not exacly what I'd like to achieve.

**Comment by Dev1lDragon** [comment]
@zaalbarxx thanks a lot

**Comment by Dev1lDragon** [comment]
Vue component dont have nowIndicatorRender event

**Comment by arshaw** [comment]
we now have these render hooks in v5:
https://fullcalendar.io/docs/now-indicator-render-hooks
