### ISSUE TITLE
Possibility to Set rowHeight in Timeline View

### ISSUE THREAD

**Issue by gotjoshua** [fullcalendar/fullcalendar#4666]
Somehow related to https://github.com/fullcalendar/fullcalendar/issues/4637, but for the Timeline view.

Similar to how you have [slotWidth](https://fullcalendar.io/docs/slotWidth), I would like to have rowHeight. I know that it is calculated based on the number of stacked events in each row, but then the height prop is set on each div individually, so I think there is no way to do it with css.

Allowing us to set eventHeight and eventRowPadding could also be a way to implement it.
Then the eventual row height would be:
 `numberOfStackedEvents*eventHeight + eventRowPadding.top + eventRowPadding.bottom`

We have a scheduler calendar that needs to be able to display many events quite densely, and i _can_ manage to set the font and event height via css, but then the row does _not_ shrink to adapt, so it actually does not densify at all...

If there is a known workaround that me and google couldn't find, I apologize in advance, and I'd love some links!

**Comment by arshaw** [comment]
try setting a css min-height on the `.fc-cell-content` class. it should work

**Comment by BlairMcClelland** [comment]
```.fc-widget-content .fc-cell-content```
Could be used to target just the resource rows, on V3.10.5
