### ISSUE TITLE
"Year" button text is not translated when locale is 'ar'

### ISSUE THREAD

**Issue by Srinivas-Alle** [fullcalendar/fullcalendar#4668]
### Bug Reports
I created resource-timeline view, with locale:'ar' & locales are added.
In this case year is not translated to arabic.
https://codesandbox.io/s/zqk5rjn5rp?fontsize=14

passing buttonText:{year:'my year label'} does the trick, but year should get translated without any additional config as local is 'ar'

**Comment by acerix** [comment]
Thanks for the report, I can see 'year' is missing from the ar locale:

https://github.com/fullcalendar/fullcalendar/blob/master/locales/ar.js#L9

**Comment by arshaw** [comment]
thanks

the new file is here: https://github.com/fullcalendar/fullcalendar/blob/master/packages/core/src/locales/ar.js#L9

what is the "year" translation in Arabic?

**Comment by kenneylo2113** [comment]
Hi.
It looks like this issue isn't restricted to ar. 
I've not seen year in any of the locales that I checked.

**Comment by arshaw** [comment]
I realized there's already a ticket for this:
https://github.com/fullcalendar/fullcalendar/issues/4193
↑
Please visit the above issue, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates.
