### ISSUE TITLE
Could not find an option named "sourcemap".

### ISSUE THREAD

**Issue by wagnermaciel** [fullcalendar/fullcalendar#4671]
### Bug Reports
To reproduce the issue, update your global sass version and try running ```npm run sass```.
I had this issue come up when installing a clean repo and installing the latest version of sass globally.

This is failing because we are still using the ```--sourcemap``` option and need to switch to using the ```--no-source-map``` option.

Please see [sass-lang's documentation](https://sass-lang.com/documentation/cli/dart-sass#no-source-map) for this option if you have any questions.

**Comment by arshaw** [comment]
this should no longer be an issue because fullcalendar now uses rollup/webpack instead of using sass directly.
