### ISSUE TITLE
Print week/day view

### ISSUE THREAD

**Issue by jcalori** [fullcalendar/fullcalendar#4672]
Is it correct that week (or even day) view like this

![image](https://user-images.githubusercontent.com/50403023/57371593-64fdda00-7193-11e9-94f1-0fdb92a335dd.png)

gets printed with events listed one below the other?

![image](https://user-images.githubusercontent.com/50403023/57371621-79da6d80-7193-11e9-82cb-2e5e22f8b4ba.png)

Printing the month view, instead, is working fine.

![image](https://user-images.githubusercontent.com/50403023/57371677-ad1cfc80-7193-11e9-8a1a-d60a9898e145.png)

Thank you

**Comment by acerix** [comment]
It looks like they are displaying as intended, the examples on the homepage print the same way: https://fullcalendar.io/

How do you expect it to print?

**Comment by jcalori** [comment]
Thanks for you reply.
I would prefer the print to be like the first of my images, which is actually a screenshot, where concurrent events appear one next to the other. Printing from the browser results like my second image instead, where concurrent events appear one below the other.

**Comment by arshaw** [comment]
The reason we implemented TimeGrid's print-mode the way we did was because the normal view relies heavily on absolute positioning, which works poorly in many browsers in print-mode, so we force a normal non-absolute positioning flow instead.

**Comment by arshaw** [comment]
I'll reassess the situation in future versions of FC

**Comment by cmartin81** [comment]
Any update on this issue?
