### ISSUE TITLE
Dragged element in wrong position when parent have css transform property

### ISSUE THREAD

**Issue by Calvin-LL** [fullcalendar/fullcalendar#4673]
### Bug Reports
When the parent element has css transform property, dragging events in the calendar shows incorrect position of the mirrored event.

Shown in: https://codepen.io/coolcyberbrain/pen/oRjaLv

**Comment by CoolCyberBrain** [comment]
I think a good solution would be to add the mirrored event to document root instead of the root of the calendar

**Comment by acerix** [comment]
Thanks, confirmed

**Comment by numsu** [comment]
Is there a timeline for this? We're facing the same issue.

**Comment by manukieli** [comment]
I've the same issue.
Is there any solution already?
Thank you.

**Comment by arshaw** [comment]
The codepen link isn't working (points to github). Can you repost @CoolCyberBrain

**Comment by CoolCyberBrain** [comment]
Oops didn't do the markdown correctly so when it's clicked it goes to github. The URL is correct, I just changed the markdown, should work now. If it doesn't then try copy pasting on to url bar. https://codepen.io/coolcyberbrain/pen/oRjaLv

**Comment by arshaw** [comment]
In `master` I've created a new settings called `fixedMirrorParent` that will offer a workaround for this issue. I'll release very soon. I'll comment here when I do.

**Comment by arshaw** [comment]
I've released the new setting:
https://fullcalendar.io/docs/fixedMirrorParent

Demo if it working in 5.4.0
https://codepen.io/arshaw/pen/LYZMJMp

**Comment by pixel9** [comment]
Thank you! I think you meant to point to a different codepen (it looks like a reproduction of the bug instead) but I'll take a look at the update and the new API.

As always, I appreciate all the hard work!

**Comment by arshaw** [comment]
Sorry about that. Here's the corrected pen: https://codepen.io/arshaw/pen/ZEOVMVw

**Comment by FUGIFA** [comment]
@arshaw is there any solution for this issue in version 4?
