### ISSUE TITLE
Feature Request: visible hours in timeGrid view

### ISSUE THREAD

**Issue by mdevDE** [fullcalendar/fullcalendar#4682]
Hi there, is it possible to include this new feature in a future update?

For example: visible hours = 8. This means that in the visual area of the calendar (fc-time-grid-container) 8 hours will be displayed with the consequence that the slot heights must be updated dynamically to show exactly 8 hours. The slot height must also be updated after resizing the calendar since this will change the height of the fc-time-grid-container.

**Comment by acerix** [comment]
If you want to have the same 8 hours visible every day you can use minTime/maxTime.  If you mean something else it might help to include a mockup of what you are looking for.

**Comment by mdevDE** [comment]
Hi, a quick mockup. The current behaviour is to show more hours when the height of the container is increased img 1.
<img width="356" alt="Bildschirmfoto 2019-05-15 um 00 50 55" src="https://user-images.githubusercontent.com/37185489/57737481-23e25a00-76ac-11e9-9714-ffd8a1067aa5.png">

I am looking for an adjusted slot height when the when the height of the container is increased img 2 & 3.
<img width="356" alt="Bildschirmfoto 2019-05-15 um 00 52 09" src="https://user-images.githubusercontent.com/37185489/57737512-45dbdc80-76ac-11e9-9c86-e9c45cff55f9.png">
<img width="356" alt="Bildschirmfoto 2019-05-15 um 00 53 26" src="https://user-images.githubusercontent.com/37185489/57737513-45dbdc80-76ac-11e9-90dd-48bc661274a4.png">
The 3rd img still shows the same 06:00 to 11:00but the time slot height was adjusted to do so.

**Comment by acerix** [comment]
I believe this existing ticket captures this need:
https://github.com/fullcalendar/fullcalendar-scheduler/issues/373
↑
Could you please visit the link, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates?

**Comment by mdevDE** [comment]
Hi thank you for the link, but unfortunately the link  #373 and #265 discussed something different.

Image 2 and 3 does have a time range from 00:00 to 24:00 but just show X visible hours (in this case 5 hours). You should certainly be able to scroll up or down to show different X hour segments, e.g. 00:00 - 05:00, 05:00 : 10:00, etc. In the end I am looking for a dynamically adapted slot height  based on the container height and the visible hours to be displayed (on calendar creation and calendar resize).

3 visible hours, slot duration 00:15, fc-time-grid-container height 500 -> 500/3/4 = 41.6666666667px height .fc-time-grid .fc-slats td
3 visible hours, slot duration 00:15, fc-time-grid-container height 600 -> 600/3/4 = 50px height .fc-time-grid .fc-slats td

The easiest and most flexible solution would be to have a method to set the .fc-time-grid .fc-slats td height dynamically.

**Comment by arshaw** [comment]
@mdevDE , though the discussion meanders a bit, #265 is the ticket you want.

it shouldn't be a method, but rather a setting. if the setting is toggled on, the slots' heights will expand to fill the available space automatically.

please let me know if i'm off-base

**Comment by mdevDE** [comment]
@arshaw, I am looking for the behaviour observed in macOS calendar. This means, to show X hours at a time. If set to six hours the slot height is automatically adjusted to show exactly six hours. On resizing the fc-view-container, the slot height will be adjusted to still show the same six hours. I hope this example helps to understand what I am looking for.
