### ISSUE TITLE
Feature Request: nowIndicator callbacks

### ISSUE THREAD

**Issue by mdevDE** [fullcalendar/fullcalendar#4683]
Hi there, could you please consider to integrate those two new callbacks for the now indicator in a future update?

callbacks:
- nowIndicatorRender
- nowIndicatorUnRender

TimeGrid.prototype.renderNowIndicator = function (segs, date) {
  // HACK: if date columns not ready for some reason (scheduler)
  if (!this.colContainerEls) {
      return;
  }
  var top = this.computeDateTop(date);
  var nodes = [];
  var i;
  // render lines within the columns
  for (i = 0; i < segs.length; i++) {
      var lineEl = core.createElement('div', { className: 'fc-now-indicator fc-now-indicator-line' });
      lineEl.style.top = top + 'px';
      this.colContainerEls[segs[i].col].appendChild(lineEl);
      nodes.push(lineEl);
  }
  // render an arrow over the axis
  if (segs.length > 0) { // is the current time in view?
      var arrowEl = core.createElement('div', { className: 'fc-now-indicator fc-now-indicator-arrow' });
      arrowEl.style.top = top + 'px';
      this.contentSkeletonEl.appendChild(arrowEl);
      nodes.push(arrowEl);
  }
  this.nowIndicatorEls = nodes;

  this.publiclyTrigger('nowIndicatorRender',[top, nodes, date]);
};
TimeGrid.prototype.unrenderNowIndicator = function () {
    if (this.nowIndicatorEls) {
        this.nowIndicatorEls.forEach(core.removeElement);
        this.nowIndicatorEls = null;
    }
    this.publiclyTrigger('nowIndicatorUnRender',[]);
};

**Comment by acerix** [comment]
Related to https://github.com/fullcalendar/fullcalendar/issues/4663

**Comment by arshaw** [comment]
closing in favor of #4663
