### ISSUE TITLE
Question: Display of events having multiple resources

### ISSUE THREAD

**Issue by koosvanderkolk** [fullcalendar/fullcalendar#4688]
@arshaw 
This is neither a bug nor a feature request, but I could not find a suitable place on the website (e.g. a contact form for sales inquiries) to address the issue. 

We are considering buying the premium version of the lib, so we can use the Resource Timeline / Grid functionality. And because FullCalendar is a great piece of work, of course ;-). Before we make our decision, we would like to know whether what we want is achievable using this lib.

In our use case we have people and equipment (so both are Resources). People book equipment at certain times (and thus they are creating Events). 

In the Resource Timeline I would like to show:
1) Which person booked which piece of equipment when. So the rows are persons, the columns timeslots and in the events the name of equipment is being displayed.
2) Which piece of equipment is when booked by which person. So the rows are pieces of equipment, the columns timeslots and in the events the name of the person/persons is displayed.

Is this possible to achieve with the standard FullCalendar Premium? How would this solution - in broad terms - look like?

**Comment by acerix** [comment]
If you mean having those as 2 separate views or separate calendars, then you can set the list of people as the `resources` in one, and the list of equipment as the `resources` in the other, and similar for the event titles.

Please contact sales@fullcalendar.io if you have other inquiries.

**Comment by koosvanderkolk** [comment]
Thanks!
