### ISSUE TITLE
OptionsInput missing several properties

### ISSUE THREAD

**Issue by dneuschaefer-rube** [fullcalendar/fullcalendar#4690]
I noticed a property missing in `OptionsInput`, and tried to comiple a list of all missing properties. I checked all the properties listed on the documentation's toc, as well as everything that is accessed via `.opt('...')` from code, but I can't guarantee that the list is exhaustive.

Most of these properties are also missing in the vue & angular components, I have created separate issues over there. Here's the list:

- `allDayHtml` (entirely undocumented, so this might be by choice)
- `eventDragMinDistance`
- `eventResourceEditable`
- `eventSourceFailure`
- `eventSourceSuccess`
- `forceEventDuration`
- `googleCalendarApiKey` (already fixed for angular & vue)
- `progressiveEventRendering`
- `selectLongPressDelay`
- `selectMinDistance` (already fixed for angular)
- `timeZoneParam`
- `titleRangeSeparator`
- `refetchResourcesOnNavigate` (scheduler)

**Comment by acerix** [comment]
I believe this existing ticket captures this need:
https://github.com/fullcalendar/fullcalendar/issues/4654
↑
Could you please visit the link, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates?

**Comment by justingrant** [comment]
Most of the props above are present in the latest 4.2 typings that include changes from #4654. But three of them are still missing from `OptionsInput` in @fullcalendar/core/main.d.ts. Two of the missing properties are scheduler-related (which I don't use so couldn't detect in #4654) and one is Google-related which I'm not sure about why it's missing. Anyway, here's the three remaining missing props: 

`eventResourceEditable`
`refetchResourcesOnNavigate`
`googleCalendarApiKey`

@dneuschaefer-rube - if you wanted to PR these three props I'm sure the maintainers would be happy!

**Comment by arshaw** [comment]
`refetchResourcesOnNavigate` and `eventResourceEditable` are already present:
https://cdn.jsdelivr.net/npm/@fullcalendar/resource-common@4.2.0/main.d.ts

they are in the `@fullcalendar/resource-common` package by design.

as for googleCalendarApiKey, i already made that fix and it's in master. will release soon

**Comment by arshaw** [comment]
This was fixed in 4.3.0 though please start using 4.3.1
Releases: https://github.com/fullcalendar/fullcalendar/releases
