### ISSUE TITLE
Error in eventSource eventDataTransform leads to unhelpful error message

### ISSUE THREAD

**Issue by koosvanderkolk** [fullcalendar/fullcalendar#4692]
The evenDataTransform callback (https://fullcalendar.io/docs/eventDataTransform) allows for data processing after e.g. a JSON feed returned from the server.

When there is a problem inside this evenDataTransform callback function, e.g. a typo, one will receive a very generic error message 'Failure parsing JSON', as per

```
xhr.onload = function () {
            if (xhr.status >= 200 && xhr.status < 400) {
                try {
                    var res = JSON.parse(xhr.responseText);
                    successCallback(res, xhr);
                }
                catch (err) {
                    failureCallback('Failure parsing JSON', xhr);
                }
            }
            else {
                failureCallback('Request failed', xhr);
            }
        };
```

A solution could be to provide the 'err' object with failureCallback:

```
4333c4333
<                     failureCallback('Failure parsing JSON', {"xhr": xhr});
---
>                     failureCallback('Failure parsing JSON', {"xhr": xhr, "err": err});
4380,4381c4380,4381
<             }, function (errorMessage, xhr) {
<                 failure({ message: errorMessage, xhr: xhr });
---
>             }, function (errorMessage, xhr, err) {
>                 failure({ message: errorMessage, xhr: xhr, err: err });

```

or only to provide the error message itself:

```
4333c4333
<                     failureCallback('Failure parsing JSON', {"xhr": xhr});
---
>                     failureCallback('Failure parsing JSON: ' + err.message, {"xhr": xhr});
```

**Comment by alaouy** [comment]
Experienced the same issue, it was due to a date parsing issue on the start/end attributes, I resolved it by including the moment plugin https://fullcalendar.io/docs/moment-plugins.

**Comment by koosvanderkolk** [comment]
> 
> 
> Experienced the same issue, it was due to a date parsing issue on the start/end attributes, I resolved it by including the moment plugin https://fullcalendar.io/docs/moment-plugins.

Yeah, but the underlying issue is that _any_ mistake in your code will cause the same non-descriptive error message, making it hard to debug.

**Comment by DiegoVenancioVieira** [comment]
> Experienced the same issue, it was due to a date parsing issue on the start/end attributes, I resolved it by including the moment plugin https://fullcalendar.io/docs/moment-plugins.

I'm in this problem. Yesterday all work fine, today I get this problem. Include moment.js but not working. Can u tell more about your solution way? I'm using Asp Net Core

**Comment by arshaw** [comment]
this should be fixed in v5. a thrown exception in that handler should bubble all the way up and not be caught
