### ISSUE TITLE
Dynamic interval time in slotDuration

### ISSUE THREAD

**Issue by bhargavcreolestudios** [fullcalendar/fullcalendar#4694]
#### slotDuration with not same(dynamic) interval time:

As I have found library is providing support for equal timeslots using slotDuration feature
like that 

slotDuration = 2

But my requirement is that interval with unequal slotDuration
I want to pass array in span of 24 hours duration would be like:

` [0,0.15,0.48,1,1.24,1.46,2,2.40,2.56, … 23.47]
`

It should be render in sidebar where slotDuration are visible with all existing functionality like drag event and etc..
Is it possible ?

**Comment by acerix** [comment]
There is no view like that built-in but you should be able to do that with a custom view:

https://fullcalendar.io/docs/custom-view-with-js

**Comment by arshaw** [comment]
this ticket captures what you want @bhargavcreolestudios 
https://github.com/fullcalendar/fullcalendar/issues/472
&uarr;
Could you please visit the link, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates?
