### ISSUE TITLE
refetchResourcesOnNavigate has no effect in vue component?

### ISSUE THREAD

**Issue by j-fdion** [fullcalendar/fullcalendar#4697]
I have enabled refetchResourcesOnNavigate in my vue component and the fetchInfo arg in the resource callback function is never called on navigation and is always returning an empty object.

https://codesandbox.io/embed/fullcalendar-vue-32tp2

If you look at the console output, it only output once with an empty fetchInfo object.

**Comment by acerix** [comment]
Thanks, confirmed in Vue but works fine without Vue:

https://codepen.io/anon/pen/gJeNzO?&editable=true&editors=001

Can you please create this issue in the repo for the Vue component instead?

https://github.com/fullcalendar/fullcalendar-vue/issues

**Comment by j-fdion** [comment]
Done. Thanks for the answer.
