### ISSUE TITLE
Multi-Month View

### ISSUE THREAD

**Issue by arshaw** [fullcalendar/fullcalendar#470]
Originally reported on Google Code with ID 199

```
Please provide any additional information below.

I'm using the calendar to schedule videos for publishing online. I usually have 
content for up to two to three months. 

How can I display three months at the same time so I can drag videos from 
one month to the next if neccesary?
```

Reported by `garifuna` on 2009-11-20 07:48:14

Imported with **47** stars.

**Comment by masteroleary** [comment]
Here is an example of how I imagine a multi month view to look. It is similar to how the calendar scrolls down with each month connected vertically on my android phone. I would imagine the configuration would  allow you to at the least set the number of months to display vertically connected. An alternative would be to lazy load each row in a never ending scroll into future months.

![calendar example](https://user-images.githubusercontent.com/476827/27229155-4ac0b702-525f-11e7-982c-5f00a04a02cb.jpg)

**Comment by REPH26** [comment]
Any new way to do that with V4? Using multiple calendar is problematic with selection trought months...

**Comment by live-bit** [comment]
would be nice to be able to render a calendar from a start date to an end date, with every date between visible, all in one calendar

**Comment by miltonlaufer** [comment]
With the team I work in, we came up with this solution (for Vue.js, but it can by applied to any version)

First, we create a view for multiple months. These are the parameters we send to the calendar component: 

`

       <fullcalendar 
                     defaultView="multiMonths"


                     :views="{

                        multiMonths: {
                            type: 'dayGrid',
                            buttonText: 'Multi-months',
                            duration: {
                                months: 3
                            },
                         }
                     }"
                     :dayRender="dayRenderer" //this does the magic
                     :header="{
                        'right': 'prev today next'
                     }"
                     :editable="true"
                     start-date="2019-10-01" // this can be dynamic too
                     :weekends="true"
                     :fixed-week-count="false"
                     :show-non-current-dates="false"
        />
`

Then we have the dayRenderer function as it follows:

`


    dayRenderer(day){
                const date = moment(day.date);
                const isDisabled = day.el.classList.contains('fc-disabled-day');
                if (date.date() === 1 && !isDisabled) {
                    // Add the month name to the first day of every month
                    day.el.classList.add('text-weight-bold', 'text-smaller');
                    day.el.innerHTML += `
                        &nbsp;${date.format('MMMM')}
                    `;
                } else if (isDisabled) {
                    // Change the style of days that are out of the "validRange" definition, so that they are visible
                    day.el.classList.add('bg-grey-lighter', 'p-2', 'text-right');
                    day.el.innerHTML += `
                        ${date.format('DD')}
                    `;
                }
                if (!isDisabled) {
                    // Change the background color of cells based on months
                    const campaignStartMonth = moment.utc(this.campaign.campaign_start).month();
                    const campaignStartEven = campaignStartMonth % 2 === 0;
                    if (
                        (campaignStartEven && date.month() % 2 !== 0)
                        || (!campaignStartEven && date.month() % 2 === 0)
                    ) {
                        day.el.classList.add('bg-grey');
                    }
                }
        }
`

So, you can have in a single calendar many months and they are differentiated from each other by the name of the month in the first day of it and by the background color. It works pretty well and, in contrast with the solution of having multiple instances of the calendar, here you can drag and drop events from one month to the other and create events that start in one month and end in the other.

**Comment by JJZolper** [comment]
This is what I did. I thought I'd want +2 for calendar 3 but it seems the way the rendering works +1 works.

document.addEventListener('DOMContentLoaded', function() {

    var calendar1 = document.getElementById('calendar1');
    var calendar2 = document.getElementById('calendar2');
    var calendar3 = document.getElementById('calendar3');

    var calendar2 = new FullCalendar.Calendar(calendar2, {
        plugins: [ 'dayGrid' ],
        defaultView: 'dayGridMonth'
    });
    calendar2.render();

    var calendar3 = new FullCalendar.Calendar(calendar3, {
        plugins: [ 'dayGrid' ],
        defaultView: 'dayGridMonth'
    });
    calendar3.render();

    var calendar1 = new FullCalendar.Calendar(calendar1, {
        plugins: [ 'dayGrid' ],
        defaultView: 'dayGridMonth',
        datesRender: function (view) {
            if(view.view.props) {
                // Calendar 1 Current State date
                cal1Date = view.view.currentStart;

                // Calendar 2 & 3 new dates
                var cal2Date = new Date(cal1Date.setMonth(cal1Date.getMonth()+1));
                var cal3Date = new Date(cal1Date.setMonth(cal1Date.getMonth()+1));

                // Set new dates
                calendar2.gotoDate( cal2Date )
                calendar3.gotoDate( cal3Date )
            }
        }
    });
    calendar1.render();

});

**Comment by bogdancarmanus** [comment]
Any news on releasing this feature? Would like to get the premium version, but multi month is a must...

**Comment by franciscoortiz16** [comment]
Its a great calendar... but  I cant believe this feature (multi month) its not out of the box.  :/

**Comment by strarsis** [comment]
It would be even better when it is also possible to drag a selection over to further months, and scroll the view with it.

**Comment by webrafaelso** [comment]
Please, can anyone make an example for v5 version.

**Comment by strarsis** [comment]
@miltonlaufer: Your example is great, I tried a fiddle/pen of it. However, it is doesn't work like this with v5 as there are multiple day handlers now (for different aspects of the day element).

**Comment by webrafaelso** [comment]
Here's my example code for React JS dayGridMonth Multi-month

React JS
Multi-month view
// calendarAPI= React.createRef();  to fetch calendar API

`             <FullCalendar
		 plugins={[ dayGridPlugin ]}
	               initialView="dayGridMonth"
                        ref={calendarAPI}  // Optional for custom date.  
			views ={{	
				dayGrid: {
					type: 'dayGrid', 
					duration: { months: 2}, // Ex: Current month + (current)next month
		        	}
			}}
			fixedWeekCount={false}
                   />
`

**Comment by sanjana-ct** [comment]
@

> Here's my example code for React JS dayGridMonth Multi-month using Fullcalendar v5.
> 
> React JS Multi-month view
> 
> ```
> Library Version
> "@fullcalendar/daygrid": "^5.3.2",
> "@fullcalendar/interaction": "^5.3.1",
> "@fullcalendar/react": "^5.3.1",
> ```
> 
> ```
> // calendarAPI= React.createRef();  to fetch calendar API
> 
> import FullCalendar from '@fullcalendar/react'; 
> import dayGridPlugin from '@fullcalendar/daygrid';
> 
>            <FullCalendar
> 		 plugins={[ dayGridPlugin ]}
> 	               initialView="dayGridMonth" // dayGridMonth requires dayGridPlugin
>                         ref={calendarAPI}  // Optional for dynamic custom date
> 			views ={{	
> 				dayGrid: {
> 					type: 'dayGrid',  // Applicable for: dayGrid and dayGridMonth
> 					duration: { months: 2}, // Ex: Current month + (current)next month
> 		        	}
> 			}}
> 			fixedWeekCount={false}
>                    />
> ```
> 
> I'm sorry, my English is not very good.


> calendarAPI= React.createRef();

thanks for this example. I wanted to know if you figured out a way to arrange these calendars side by side horizontally.

**Comment by grazielleanna** [comment]
Any update on this? I have the same problem.

**Comment by gitalvininfo** [comment]
> @
> 
> > Here's my example code for React JS dayGridMonth Multi-month using Fullcalendar v5.
> > React JS Multi-month view
> > ```
> > Library Version
> > "@fullcalendar/daygrid": "^5.3.2",
> > "@fullcalendar/interaction": "^5.3.1",
> > "@fullcalendar/react": "^5.3.1",
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ```
> > // calendarAPI= React.createRef();  to fetch calendar API
> > 
> > import FullCalendar from '@fullcalendar/react'; 
> > import dayGridPlugin from '@fullcalendar/daygrid';
> > 
> >            <FullCalendar
> > 		 plugins={[ dayGridPlugin ]}
> > 	               initialView="dayGridMonth" // dayGridMonth requires dayGridPlugin
> >                         ref={calendarAPI}  // Optional for dynamic custom date
> > 			views ={{	
> > 				dayGrid: {
> > 					type: 'dayGrid',  // Applicable for: dayGrid and dayGridMonth
> > 					duration: { months: 2}, // Ex: Current month + (current)next month
> > 		        	}
> > 			}}
> > 			fixedWeekCount={false}
> >                    />
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > I'm sorry, my English is not very good.
> 
> > calendarAPI= React.createRef();
> 
> thanks for this example. I wanted to know if you figured out a way to arrange these calendars side by side horizontally.

Did you get it? Having the same exact issue.

**Comment by arshaw** [comment]
This feature has been implemented:

- docs: [Multi-Month Stack](https://fullcalendar.io/docs/multimonth-stack)
- github release: [v6.1.0](https://github.com/fullcalendar/fullcalendar/releases/tag/v6.1.0)
- blog post: [Multi-Month and more in v6.1](https://fullcalendar.io/blog/2023/01/multimonth-and-more)
