### ISSUE TITLE
Support for fullcalendar V3

### ISSUE THREAD

**Issue by ReverseObscureness** [fullcalendar/fullcalendar#4700]
Is there an ongoing support in terms of security patches for fullcalendar V3?

Our company is using V3 and we are reluctant to go through the process of upgrading to V4 if security issues are going to be patched in V3.

**Comment by arshaw** [comment]
because of fullcalendar's front-end-only nature, a true "security" bug would be very rare. If it happens, we would patch v3, yes. However, if you're just talking about normal bugs, no, we would be more reluctant to fix those in v3. does that answer your question?
