### ISSUE TITLE
Fullcalendar half day events

### ISSUE THREAD

**Issue by ru1x89** [fullcalendar/fullcalendar#4701]
Is it possible to show half-day events in full calendar? Please refer to the attachment here.

![half-day-events](https://user-images.githubusercontent.com/1969949/58398191-dc77a880-8071-11e9-915c-7a2f3191b05a.png)

Thanks!

**Comment by acerix** [comment]
That's not built-in but you could use `eventRender` to change the size of the event element based on the length of the event and style it like your mockup.

https://fullcalendar.io/docs/eventRender

**Comment by arshaw** [comment]
yup, best solution is eventRender

**Comment by jinming88** [comment]
Hello @arshaw 
Would you like to share code for this function.
I want to show 3.5 days event.
I tried to find solution but I have no idea.
Please teach me.
