### ISSUE TITLE
businessHours constraint prevents events from spanning across 2 dates in time-grid view with maxTime > 24 hours

### ISSUE THREAD

**Issue by kelvin-pfp** [fullcalendar/fullcalendar#4703]
I'm using v4 and not sure whether it is a bug or configuration problem.

Here are the settings:
1) Time grid displays from today to tomorrow noon
2) Business hours of some weekdays are from 00:00 to 24:00
3) Events are resizable

I want to resize a event to make it across two dates. For example, a event is from 22:00 to 23:00 originally and I want to make it from 22:00 to 01:00.
However, I cannot achieve that with my implementation.

CodePen: [https://codepen.io/kelvin-pfp/pen/byjVLP](url)

**Comment by acerix** [comment]
Thanks for the detailed report. I can see the businessHours constraint prevents events from spanning across 2 dates even if the business hours include midnight so it seems like a bug:

https://codepen.io/anon/pen/VOGZwZ?editors=0010

As a workaround you could use a custom constraint function:

https://fullcalendar.io/docs/eventConstraint

**Comment by arshaw** [comment]
this is the same exact request as this ticket:
https://github.com/fullcalendar/fullcalendar/issues/4440
&uarr;
Could you please visit the link, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates?
