### ISSUE TITLE
Week view: Select slots behind events

### ISSUE THREAD

**Issue by Phibedy** [fullcalendar/fullcalendar#4704]
I find it quite difficult to create new events by selecting slots if there are already events during that time, because the space you can select is quite small.

First idea: The most obvious solution would be to be able to set the total width of the events to increase the space like shown here: https://stackoverflow.com/questions/35579749/increase-clickable-area-of-slots-behind-fullcalendar-event
What I currently do:
```
.fc-ltr .fc-time-grid .fc-event-container {
    margin: 0 5.0% 0 2px;
}
```

Second idea:
If event-drag is not enabled, pass the event to the time-grid.

**Comment by arshaw** [comment]
change the margins of the event-container via CSS exactly like you're doing is the best solution
