### ISSUE TITLE
Fullcalendar v4 integrating browser back/forward buttons

### ISSUE THREAD

**Issue by karres-illinois** [fullcalendar/fullcalendar#4705]
Hi,

This was initially reported on StackOverflow [HERE](https://stackoverflow.com/questions/56134731/fullcalendar-v4-prev-button-and-browser-back-button-integration-fail).  The rest of this is repeating the SO question.

Creating a fiddle or using CodePen, etc doesn't work.  My guess is that the fiddle sites have wrappers that interfere with the browser back/forward buttons.  I do have a minimal example [HERE](https://test.pipers-hut.com/calendar.html).

An example of expected behavior is:

- Visit the link above; click the Go to calendar link (for testing I need a launch page to test the back button operation from the real calendar "home" page).
- Look at the top, right of the calendar toolbar and click the month then day buttons in turn.
- Use the browser back/forward buttons to move between the views.

An example of the flawed behavior:

- Go the the month view. Look to the top, left of the calendar toolbar and click the "<" prev button. This will move the display back one month.
- Try to use the browser back button to return to the initial month view and nothing happens.

I am managing the calendar state via window.history.state. It looks to me that when a page is first visited the window.history.state is null. One of the very first things that happens after the Fullcalendar is initialized and rendered is that the initial view is rendered and datesRender is called.

I check to see if window.history.state is null and if so I use window.history.replaceState to set the default view state. I then either use replaceState or pushState to add or update the state info.

```
    'datesRender': function (info) {
        if (window.history.state === null) {
            //
            // seems like when a page is first visited the history
            // for that page has a null state.  Add a default state.
            const tempState = {
                'view': info.view.type,
                'range': {
                    'start': moment(info.view.activeStart)
                        .local().format(dateFormatHuman),
                    'end': moment(info.view.activeEnd)
                        .local().format(dateFormatHuman)
                },
                'url': window.location.href,
                'comment': "INIT"
            };

            window.history.replaceState(
                tempState,
                "INIT",
                window.location.href
            );
        } else {
            //
            // if state.comment = POP then we are here after a
            // BACK button press.  Change the comment to "dateRender".
            if (window.history.state.comment === "POP") {
                const tempState = window.history.state;
                tempState.comment = "datesRender";

                window.history.replaceState(
                    tempState,
                    "From pop",
                    window.location.href
                );
            } else {
                //
                // there is current state and we need to change views.
                // add new state for the new view
                const state = {
                    'view': info.view.type,
                    'range': {
                        'start': moment(info.view.activeStart)
                            .local().format(dateFormatHuman),
                        'end': moment(info.view.activeEnd)
                            .local().format(dateFormatHuman)
                    },
                    'url': window.location.href,
                    'comment': "datesRender"
                };

                window.history.pushState(
                    state,
                    "datesRender",
                    window.location.href
                );
            }
        }
    },
```

When the browser forward/back buttons are pressed the window.onpopstate event is triggered. When the handler is run the "current" window.history.state is the state after the browser button POP. I update the state comment to flag this as a browser button event then call the Fullcalendar  changeView method to update the view.

```
    function handleStatePopEvent(event) {
        try {
            const tempState = window.history.state;
            tempState.comment = "POP";

            window.history.replaceState(
                tempState,
                tempState.comment,
                tempState.url
            );

            calendar.changeView(
                window.history.state.view,
                window.history.state.range
            );
        } catch (e) {
            throw `handleStatePopEvent: ${e.message}`;
        }
    }
```

The problem seems to be that after a Fullcalendar prev button click something changes in the FC internal state -- though I can't prove that. The window.history.state is changed correctly in the datesRender. When the browser back button is hit, the window.onpopstate event is triggered and the view and date ranges are correct to return to the previous month view but the changeView call renders nothing.

I have used my browser's Developer Tools debugger and have stepped all the way through changeView in this case. Nothing dramatic jumps out at me other than at some point there is a flag that seems to say "Do I need to render anything?" is set to false.

Am I doing something wrong?

**Comment by acerix** [comment]
I believe the issue is that `changeView` only accepts a date range for custom views, otherwise the second param should be just the first day of the view in the format "2017-06-01".

https://fullcalendar.io/docs/Calendar-changeView

**Comment by acerix** [comment]
`changeView` still works to change the view, the date range is just ignored.  So, if you change the date and view a few times, then use "back" to go back to a day view, it's not always the same day that it should be from the history.

**Comment by karres-illinois** [comment]
Hmm, so, after another tour through the docs… if I am in view-mode-X and using the prev/next buttons should I be using gotoDate instead of changeView?  Only use cahngeView when moving from view-mode-X to Y?

Cheers

--
Dean Karres
Sr Research Programmer, Beckman Institute
Illinois XSEDE Campus Champion
https://campuschampions.web.illinois.edu/

**Comment by acerix** [comment]
Yes, `gotoDate` is better to change just the date, but `changeView` should also work if the date is supplied.

**Comment by karres-illinois** [comment]
I will try just supplying a single date to changeView first then try gotoDate tomorrow.

Cheers


--
Dean Karres
Sr Research Programmer, Beckman Institute
Illinois XSEDE Campus Champion
https://campuschampions.web.illinois.edu/
