### ISSUE TITLE
Cannot read property 'milliseconds' of null

### ISSUE THREAD

**Issue by kurdtpage** [fullcalendar/fullcalendar#4706]
https://codepen.io/kurdtpage/pen/dEqMXb
I am getting data via JSON, which is not shown.

Sometimes (intermittently) FC has problems getting the milliseconds and spits out "Cannot read property 'milliseconds' of null".
I have isolated this problem to the following areas:
*core\main.js*:
- function `asRoughMs`, sometimes `dur` is null. Fix: `if (dur == null) return 1;`
- around line 4914, `DateEnv.prototype.add = function (marker, dur) {` the error is at the following line: `a[6] += dur.milliseconds;`. My fix is to add `if (marker == null) marker = new Date(); // Today` at the start of the function (seems to work?)
- the last function, `computeActiveRange` sometimes `dateProfile.minTime` is null so getting the property `.milliseconds` fails

However with these fixes in place, sometimes the calendar will show a blank page

**Comment by kurdtpage** [comment]
Oh, one small thing to note, I don't care about milliseconds, I only need down to whole minute resolution

**Comment by kurdtpage** [comment]
This error pops up every now and then, if I refresh the page, sometimes it works, sometimes not. Very frustrating

**Comment by acerix** [comment]
I wasn't able to get that error from your demo,  do I need to do more than just refreshing the page?

**Comment by kurdtpage** [comment]
It's like going to the doctor, right? The problem disappears. As I stated earlier, the problem is very intermittent and isn't there all the time, which is very strange.
This issue was more for error checking/avoidance. What happens if (like in my case, sometimes) these values are null/undefined?
Is it possible to add a little bit of logic to check for null/undefined in the 3 areas I pointed out above?

**Comment by kurdtpage** [comment]
Stacktrace/output:
```
Uncaught TypeError: Cannot read property 'years' of null
    at DateEnv.add (core_main.js:4917)
    at i.r (allworkshop.min.js:1)
    at i.buildDayRanges (core_main.js:1541)
    at i.render (allworkshop.min.js:1)
    at i.Component.receiveProps (core_main.js:3961)
    at o.render (allworkshop.min.js:1)
    at o.Component.receiveProps (core_main.js:3961)
    at CalendarComponent.renderView (core_main.js:6331)
    at CalendarComponent.render (core_main.js:6256)
    at CalendarComponent.Component.receiveProps (core_main.js:3961)
DateEnv.add @ core_main.js:4917
r @ allworkshop.min.js:1
(anonymous) @ core_main.js:1541
i.render @ allworkshop.min.js:1
Component.receiveProps @ core_main.js:3961
o.render @ allworkshop.min.js:1
Component.receiveProps @ core_main.js:3961
CalendarComponent.renderView @ core_main.js:6331
CalendarComponent.render @ core_main.js:6256
Component.receiveProps @ core_main.js:3961
Calendar.renderComponent @ core_main.js:6867
Calendar.executeRender @ core_main.js:6827
Calendar.render @ core_main.js:6649
setcal @ workshop.php:370
refreshevents @ workshop.php:751
(anonymous) @ workshop.php:817
setTimeout (async)
(anonymous) @ workshop.php:815
l @ allworkshop.min.js:1
fireWith @ allworkshop.min.js:1
ready @ allworkshop.min.js:1
a @ allworkshop.min.js:1

**Comment by acerix** [comment]
It's not obvious that the undefined properties are because of a bug in the calendar and not something in your code, and it could also be something specific to your browser, etc. so it's best if you can provide a way to reproduce the issue.    About how often do you get the error? (like after 100 refreshes?)

**Comment by gabspeck** [comment]
Hello, I'm getting the same error since upgrading from version 4.1.1 to version 4.2.2 of fullcalendar-vue. My event source is a function that fetches events from a remote endpoint and applies a transformation to return them in the format expected by FullCalendar.

**Comment by gabspeck** [comment]
Oops, my bad. I have an endpoint to return some calendar parameters and I was using different parameter keys on the backend and on the frontend.

**Comment by acerix** [comment]
If there is still an issue, please provide a way to reproduce it.
