### ISSUE TITLE
Intl is not defined in QQ Browser mobile v9.3.0

### ISSUE THREAD

**Issue by StanleyWCTan** [fullcalendar/fullcalendar#4710]
### Bug Reports
Everything is working fine in Chrome/Safari desktop and mobile. But for business purpose, we must supprt QQ Browser as well. However, we encounter following issue. Please advise how to solve it. Thanks!!

Anyone who uses android mobile phone can download QQBrowser via https://mb.qq.com/, then launch the browser to open fullcalendar.io, and the error occurs.

Error details:
jQuery.Deferred exception:Intl is not defined ReferenceError: Intl is not defined

Our code snippet:
......
gCalendar = new FullCalendar.Calendar(document.querySelector("#hsCalender"), {
	        plugins: ['interaction', 'dayGrid', 'timeGrid', 'list', 'bootstrap'],
	        themeSystem: 'bootstrap',
	        header: {
	            left: 'prev,next today',
	            center: 'title',
	            right: 'dayGridMonth,timeGridWeek,timeGridDay,listMonth'
	        },
	        businessHours: {
		        dow: [ 1, 2, 3, 4, 5 ],
		        start: '09:00',
		        end: '18:00',
		    },
		    eventTimeFormat: { // like '14:30'
		    	hour12: false,
		    	hour: '2-digit',
		        minute: '2-digit'
		    },
		    eventLimitText: '更多',
	        locale: 'zh-cn',
	        contentHeight: 'auto',
	        selectable: true,
	        eventLimit: true, // allow "more" link when too many events
	        select: <handler>,
	        eventClick: <handler>,
	        eventMouseEnter: <handler>,
		    events: <handler>
	    });
......

**Comment by acerix** [comment]
That is not a supported browser, you could try adding a polyfill or maybe version 3 will work better.

**Comment by StanleyWCTan** [comment]
My bad, I should provide more browser details, sorry for that. That browser last version actually bases on Chrominum(Chrome 66), and of course the vendor added some amendments, but still it's core is webkit. that's why we need to support it.

Tried with fullcalendar 3, it can be rendered, but seems it is not working fine for adding events: no matter click, double click or long press in that browser, the eventClick/select handler not triggered.   

So will fullcalendar 4 support this kind of browser or not? and if adding a polyfill will fix it, would you please provide more details? as we are all rookies to fullcalendar. Thanks a lot!!

**Comment by acerix** [comment]
Chrome is supported, but it sounds like QQ is missing some features that are required for the calendar to work.  You can leave this issue open as a feature request to add support for that browser.

"Intl is not defined" is a common error so you can search for that to find possible solutions, here's an example polyfill that might work to add that missing feature:

https://github.com/andyearnshaw/Intl.js/

**Comment by StanleyWCTan** [comment]
Tried adding Intl.js and related locale json, but no luck. Therefore, as mentioned above, leave the issue as feature request.

Dylan, thanks for your help!

**Comment by arshaw** [comment]
@StanleyWCTan, what happens when you include the Intl polyfill?

I'm afraid we might need to close this ticket because supporting browser like this is not within the project scope.
