### ISSUE TITLE
Facing fullcalendar event create in firefox

### ISSUE THREAD

**Issue by Ezhilarasu1330** [fullcalendar/fullcalendar#4711]
I am using fullcalendar **Version3.9** agendaDay view. I am trying to create an event it is working perfect on chrome. When i try the same in latest version of firefox it returns year with minus. Kindly can you please help me out.

` select: function (start, end, jsEvent, view, resource) {

                            var formattedStart, formattedEnd;

                            console.log('Start Obj : ', start);

                            if (Array.isArray(start._i)) {
                                console.log('Array');
                                var formattedTempStart = moment(start._d.toUTCString());
                                formattedStart = moment.utc(formattedTempStart).format('DD MMM YYYY hh:mm a');

                            } else {
                                formattedStart = new Date(start._i);
                            }

                            var today = new Date();
                            var tz = $('#ip16')[0].options[$('#ip16')[0].selectedIndex].value.split("@@")[1];
                            var currentTime = moment.tz(today, tz);
                            console.log('Selected Time : ', formattedStart);
                            console.log('Current Time : ', currentTime);

                            if (new Date(formattedStart) > new Date(currentTime._d)) {

                                $('.modal-backdrop').remove();
                                var test = start.format();
                                var obj = {
                                    "start": test,
                                    "resource": resource.id
                                };
                                $this.trigger('loadpopup', obj);

                                var start = test.split("T");
                                var timeString = start[1];
                                var H = +timeString.substr(0, 2);
                                var h = (H % 12) || 12;
                                var ampm = H < 12 ? " AM" : " PM";
                                timeString = h + timeString.substr(2, 3) + ampm;

                                $('#starts-at').val(timeString);

                                var end = end.format().split("T");
                                var timeString = end[1];
                                var H = +timeString.substr(0, 2);
                                var h = (H % 12) || 12;
                                var ampm = H < 12 ? " AM" : " PM";
                                timeString = h + timeString.substr(2, 3) + ampm;

                                $('#interview').val(resource.title);
                                $('#ends-at').val(timeString);
                                console.log('select', resource ? resource.id : '(no resource)', test);
                            }
                            else {
                                Manager.trigger("messages:toastr", 'error', 'Selected time already passed');
                            }
                        },
`

<img width="960" alt="firefox" src="https://user-images.githubusercontent.com/19296585/58746761-b4c47e00-847f-11e9-904f-28ee2c0991d4.PNG">

<img width="960" alt="chrome" src="https://user-images.githubusercontent.com/19296585/58746762-bee67c80-847f-11e9-97dd-1ad40fffe4fa.PNG">

**Comment by acerix** [comment]
Would you be able to post a [runnable, stripped-down demonstration of the bug](http://fullcalendar.io/wiki/Reduced-Test-Cases/)? Would really appreciate it because the time saved reproducing will be time spent fixing.
