### ISSUE TITLE
Use Fullcalendar in TypeScript without modules

### ISSUE THREAD

**Issue by Almeonamy** [fullcalendar/fullcalendar#4713]
Hello. I try to use Fullcalendar in our project. We use TypeScript. Official documentation offer import module in TypeScript.
https://fullcalendar.io/docs/typescript

We have not big frontend in our project and we don't use modules. Is there any way to use Fullcalendar from TypeScript without modules.

Ok, I imported module in TypeScript, compiled it to es6 modules in JS and tried to use webpack to resolve modules. All Fullcalendar packed to output bundle. I tried to add Fullcalendar to externals and download Fullcalendar's script from cdn. But after that I got error in console "Uncaught ReferenceError: require is not defined".

What I am doing wrong? Can I use Fullcalendar in TypeScript without extra complexity?

**Comment by acerix** [comment]
I'm not sure I understand but if you don't to build the TypeScript like in the [example project](https://github.com/fullcalendar/scheduler-typescript-example) you can instead load it from the CDN as [described here](
https://fullcalendar.io/docs/initialize-globals).

**Comment by Almeonamy** [comment]
@acerix, yes, I tried this method. It works when I use JavaScript only. But I want to use TypeScript. In TypeScript I can't use FullCalendar class (or namespace). TypeScript Compiler don't see FullCalendar (or Calendar) and throw the error. To solve this issue I need to import "@fullcalendar/core" module but it leads to unnecessary complexity and using additional tools (systemjs, webpack, gulp, rollup...)

**Comment by acerix** [comment]
I don't know of a more simple way to include it in TypeScript, do you have an example of what you mean by using it "without modules"?

**Comment by Almeonamy** [comment]
Now I need to write this in TypeScript
```TypeScript
import { Calendar } from '@fullcalendar/core';
import dayGridPlugin from '@fullcalendar/daygrid';

class Talks {
    constructor() {
        let calendar = new Calendar(document.getElementById("Calendar"), { 
            plugins: [dayGridPlugin]
        });
        calendar.render();
    }
}
```

It is compiled to this JavaScript (the code is the same):
```JavaScript
import { Calendar } from '@fullcalendar/core';
import dayGridPlugin from '@fullcalendar/daygrid';
class Talks {
    constructor() {
        let calendar = new Calendar(document.getElementById("Calendar"), {
            plugins: [dayGridPlugin],
        });
        calendar.render();
    }
}
```

Then I try to load this JavaScript to browser:
```html
<script src="https://cdn.jsdelivr.net/npm/@fullcalendar/core@4.1.0/main.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/@fullcalendar/daygrid@4.1.0/main.min.js"></script>
<script src="/Scripts/MyScripts/Talks.js"></script>
```

Browser says me that he can't find module @fullcalendar/core. That's because browser doesn't support Node's resolving algorithm (because it's not local files).

To solve this issue we have to do some kind of manipulation with JavaScript file.

It would be much easier to use FullCalendar namespace directly in TypeScript, how it is done in JavaScript. Without importing of modules.
```TypeScript
class Talks {
    constructor() {
        let calendar = new FullCalendar.Calendar(document.getElementById("Calendar"), { 
            plugins: [FullCalendar.DayGridPlugin]
        });
        calendar.render();
    }
}
```
---------------------------
If this method can't be realized can you provide webpack's (or other tools) configuration that can transform compiled JavaScript file to use @fullcalendar/core module from cdn?

I saw your [example project](https://github.com/fullcalendar/scheduler-typescript-example). Thanks for that. But in this project compiled JavaScript file was bundled with FullCalendar's files in one bundle. It's the problem.
1. I want to use CDN to download external libraries as FullCalendar.
2. Our project is not SPA. We have many entry points. By this example each entry point must has itself bundle. And each bundle must contains copies of FullCalendar's files.

**Comment by arshaw** [comment]
You can probably just avoid using ES6 modules altogether. Use the globals directly from your typescript. but first you'll need this line:

```
declare let FullCalendar;
```

(or something like that)

The better solution is to continue to use modules but have webpack/rollup map them to the browser globals that the CDNs provide.

Either way, this is out of the scope of the issue tracker.
