### ISSUE TITLE
eventLimit fails on month view for "overnight" events

### ISSUE THREAD

**Issue by rodrigues** [fullcalendar/fullcalendar#4715]
In the month view, if a day hits the max event limit (in my case, a function that returns `5` for month view, undefined for the rest), and there is an event starting this day and ending next day, next day cell won't render fine:

<img width="421" alt="Screenshot 2019-06-04 at 15 43 26" src="https://user-images.githubusercontent.com/128147/58886133-ae364080-86e3-11e9-8f53-e570c02f4f9a.png">

Other events next day that don't start the day before will be shown:

<img width="516" alt="Screenshot 2019-06-04 at 16 15 01" src="https://user-images.githubusercontent.com/128147/58886363-0d945080-86e4-11e9-8ad7-d9345dbea3f0.png">

I'm using latest `@fullcalendar` npm deps, `4.2.0`

**Comment by acerix** [comment]
Would you be able to post a [runnable, stripped-down demonstration of the bug](http://fullcalendar.io/wiki/Reduced-Test-Cases/)? Would really appreciate it because the time saved reproducing will be time spent fixing.

**Comment by rodrigues** [comment]
@acerix there you go, thanks! https://github.com/rodrigues/fc-event-limit-bug

**Comment by acerix** [comment]
Thanks for the demo, confirmed.  I put the code in a debug template for easier reproduction:

https://codepen.io/anon/pen/NVZNwM?editors=0010

**Comment by arshaw** [comment]
I believe it's the same issue as this:
#4076
&uarr;
Could you please visit the link, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates?
