### ISSUE TITLE
How to keep two FullCalendar instances' dates in sync?

### ISSUE THREAD

**Issue by justingrant** [fullcalendar/fullcalendar#4717]
My React app is using two FullCalendar instances as a master/detail view: the "master" is a `dayGridWeek` view showing one week, and the "detail" is a `timeGridDay` view showing one day: the currently selected date on the master view.  Each view has an appropriate toolbar: the master view's next/prev buttons will move the selected date by one week, while the detail view's toolbar's prev/next buttons will move the selected date by one day.

What's a good way to keep the selected dates in sync between the two instances?  Specifically, if I click the "next" button on the master view, then what's a good way to get notified that the selected date has changed, so that I can call `gotoDate()` on the other instance?

My first attempt was to use `dayRender` and/or `datesRender` handlers on both instances, and when the "new date" doesn't match the "old date" then save the old date and set the new date on the other FullCalendar instance. But in my React environment (where state updating is async and extra renders are common) I've found this to be tricky because it's easy to get into an infinite loop where the old and new state values are fighting to be the current date.  I ended up with duelling async state updates which triggered new renders which triggered more async state updates.... and so on.

One approach would be to replace all FullCalendar toolbar UI with my own UI so I could control all date changes. But I'm hoping to avoid re-implementing something that's already working.

The ideal solution would be a `changeDate` event that would trigger whenever the date changed by toolbar clicks (or any future UI capabilities, like a swipe handler for mobile) but did *not* trigger for every render.

Does something like this exist?  If not, what's a good way to keep dates in sync across multiple instances, given React's challenges with frequent re-renders and async state updates?

**Comment by acerix** [comment]
Here's a simple demo with `datesRender` which seems to work well for this:

https://codepen.io/anon/pen/Rmzroz?editors=0010

I'm not very familiar with React, so maybe I don't understand the extra rendering you are referring to but I think this approach should also work there.

I can see how synchronising calendars would be useful if you are requesting that as a built-in feature.

**Comment by justingrant** [comment]
@acerix - I don't think built-in synced calendars is the right granularity to fix this. Synced calendars seems nice but complex and kinda specialized to a small use-case.  A better fix IMHO would be to make it easier to build synced calendars and lots of other similar cases where the app both controls FC and is controlled by FC (in response to user actions like clicking the "next" button).

The general problem here is that FC doesn't (or maybe it does but I haven't found it?) have an easy way to differentiate renders that are triggered by a user action e.g. click on "today" or prev/next buttons.  If, for example, there were an `isUserTriggeredEvent` prop on the arg passed to render event handlers, it'd make it easier to do what I want to do. For example, in the "synced calendar" example above, if I get a `dayRender` event caused by user action and the date is different from the other calendar's current date, then I'll want to call `gotoDate()` on the other calendar.  But if the render was caused by my own code (not the user) then I don't want to do anything, because at best it'd cause unnecessary code to run and at worst could cause an infinite loop.

So that's my feature request: a new parameter for render events that clarifies the reason for the render: user interaction or programmatic call from the app.  I don't know if this is easy or not given FC's existing design.

BTW, I figured out the cause of my infinite loops, and it's not particularly React-related. The TL;DR is that in my "calendar props changed" handler, I fixed the infinite loop by changing the date (via calling `gotoDate`) *before* calling `mutateOptions` to change other FC options. Doing this ensures that when the `dayRender` handler is called, the "new" date will be in `arg.date`. This prevents the infinite loop.

However, if I call `mutateOptions` before calling `gotoDate` however, bad things happen because a `dayRender` event is triggered (by `mutateOptions`) with the "old" date before the `gotoDate` call executes. My `dayRender` handler sees the "old" date and assumes it was a user action and sets the date prop to the "old" date. Then (back in the original call to the props-changed handler in my code) `gotoDate` is called with the "new" date, which triggers another render, which triggers another prop change, and so on.  Moving the `gotoDate` before `mutateOptions` prevents the problem because then there's no FC renders that happen with the old date, so the next `dayRender` handler doesn't see any reason to change the date prop.

For more details, here's the comment I added to that "props changed" handler as a warning: 

```ts
    // IMPORTANT: changing the date must come before changing other props.
    // Otherwise we can end up in infinite loops in Calendar rendering, because
    // of the following sequence that would happen if we set the date after
    // other props: 
    // 1.  caller sets the new defaultDate prop programmatically in response to
    //     user action, which triggers this method
    // 2.  we call Calendar.mutateOptions with any other props that changed
    //     (typically handled functions and the date)
    // 3.  this in turn causes the FullCalendar instance to re-render with the
    //     old selected date (because we haven't changed the date yet)
    // 4.  this triggers a dayRender event
    // 5.  the dayRender event compares the current rendered date to the current
    //     defaultDate prop, and because they won't match (remember, we haven't
    //     changed the date yet!) my dayRender handler assumes that the rendered
    //     date is a new date (e.g. triggered by the user clicking the "next"
    //     button on the toolbar) and sets the defaultDate prop back to the old
    //     date.
    // 6.  Changing the defaultDate prop queues up a call to this method (more
    //     on this later)
    // 7.  Meanwhile, the first execution of this method isn't done yet... it
    //     still has to call gotoDate() to set the date on the FullCalendar
    //     instance. It does this.
    // 8.  Calling gotoDate triggers a re-render of the FullCalendar instance,
    //     which triggers the dayRender handler, which (correctly) sees that the
    //     selected date has changed (to the new date).  It changes the
    //     defaultDate prop to the new date. 
    // 9.  But remember the erroneous prop update (to the old date) from step #6
    //     above? That prop update causes this "on props changed" method to fire
    //     again, with the "old" date as a prop.
    // 10. This triggers a Calendar.mutateOptions() call, which triggers another
    //     render with the selected date being the "new" date.  But remember we
    //     haven't called gotoDate yet with the "old" date. (more on this in
    //     step 12)
    // 11. This triggers the dayRender handler, which compares the current
    //     selectedDate prop (which was set to the "old" date in step #5) to the
    //     "new" date set by step #7. They don't match. The dayRender handler
    //     assumes that the user clicked a toolbar navigation button again, and
    //     sets the defaultDate prop to the "new" date.
    // 12. At the end of step 11, we're in a similar state as the end of step 1:
    //     changing the defaultDate prop to the "new" date. But there's still a
    //     pending gotoDate call from step 10 that will cause this whole process
    //     to repeat itself over and over.  FAIL! However, if you set the date
    //     first before mutating other options, then the dayRender handler will
    //     see the "new" date (which will match the "new" date in the
    //     defaultDate prop) and it won't try to reset that prop to another
    //     value. No infinite loop. Yay!
```

**Comment by justingrant** [comment]
After thinking about it more, I realized that FC already has a solution to know if a user action triggered an event: the `jsEvent` parameter.  So I think a better ask would be to add a new `dateChange` event that's fired before FC changes from one date range to another.

The user could revert the change if needed like with other events.  The revert should cancel the "parent" action in cases like changing views where changing the view causes a change to the date range.

Like other events, we can use the usual `jsEvent` parameter to know if it's a user interaction that triggered the change, because it will be `undefined` if the change was programmatically triggered.

I was thinking of a signature like this: 

```ts
dateRangeChange ? (arg: {
  el: HTMLElement;
  oldRange: DateRange;
  newRange: DateRange;
  oldView: View;
  newView: View;
  revert: () => void;
  jsEvent: Event;  // undefined if triggered programmatically, e.g. by gotoDate()
});
```

Whaddya think?

**Comment by arshaw** [comment]
in v5, the [datesSet](https://fullcalendar.io/docs/datesSet) callback now exists.

that is about as far as I think FullCalendar's API will come to facilitating this feature. you can write custom code to react to datesSet, determine the current view type, and sync that with other calendars.
