### ISSUE TITLE
Render function moves time column header to another position

### ISSUE THREAD

**Issue by danydhondt** [fullcalendar/fullcalendar#4718]
When I call the `render()` function after initialization, the time column moves to the middle of the calendar.
See this [codepen](https://codepen.io/archemedia/pen/gJJKzo) to view the error.
Recreate it by just clicking on the single event.
I remember that this issue came up in the past but I can't find it.

**Comment by acerix** [comment]
Thanks for the report, confirmed. Even just calling render twice in a row causes the same issue:

https://codepen.io/anon/pen/eawJVM?&editable=true&editors=001

**Comment by arshaw** [comment]
This was fixed in 4.3.0 though please start using 4.3.1
Releases: https://github.com/fullcalendar/fullcalendar/releases
