### ISSUE TITLE
Include working sourcemaps in dist

### ISSUE THREAD

**Issue by justingrant** [fullcalendar/fullcalendar#4719]
FullCalendar includes sourcemaps but there are multiple problems that prevent them from being useful, especially with file-based debuggers like VSCode: 
* the copyright/license banner added by gulp to the bundle file after sourcemaps are generated throws off line numbering
* the original TS source files are not included in FullCalendar npm packages. This means that file-based debuggers like VSCode won't be able to fully use debugging features, like setting breakpoints on FullCalendar files when the debugger is not running.  
* even if the files were installed, the `sources` array in the sourcemap points to paths that don't exist when FullCalendar is installed from npm, which will also break VSCode debugging. For example, below is the first few lines of the 4.2 sourcemap (https://unpkg.com/@fullcalendar/core@4.2.0/main.js.map), showing paths like `"../../src/core/util/dom-manip.ts"` that point to the build-time paths, not real paths under the npm install directory of any FullCalendar package.
```json
{  
   "version":3,
   "file":"main.js",
   "sources":[  
      "../../src/core/util/dom-manip.ts",
      "../../src/core/util/geom.ts",
      "../../src/core/util/scrollbars.ts",
      "../../src/core/util/dom-geom.ts",
      "../../src/core/util/dom-event.ts",
```

To repro: 
1) Using VSCode, open any app that installed FullCalendar from npm
2) Debug the app, setting a breakpoint in app code that calls into FullCalendar
3) Step into that call. You might have to Step Into several times to get past the module-loading shims. 

Expected: Debugger shows the first line of the method in the original TS source file
Actual: Debugger shows a line in a transpiled JS file. If you manually copy source files into the folders expected by the sourcemap, then the debugger will show the wrong line in a TS file.

I've built a PR that will address these problems. Will file it shortly. 

P.S. - to clarify, sourcemaps for debugging FullCalendar itself (for contributors) probably work just fine. The problem is when developers who use FullCalendar as a dependency want to debug into it.

**Comment by acerix** [comment]
Thanks for the detailed report and PR.  I can see the npm package contains `main.js.map` which points to source files that are not included.

**Comment by justingrant** [comment]
Yep! FWIW, ever since I rolled out the fix in my own dev environment yesterday, it's like I'm debugging at warp speed. Tracking down FC-related problems is sooooo much easier. For example, I just solved #4717 in a half hour when before I'd been stuck on it for a day and a half.  Debugging with real source code FTW!

**Comment by arshaw** [comment]
I actually did not intent to publish those map files at all. I must have published from a dirty tree.

Anyway, I'm not exactly sure what I want to do here. If you're debugging FC code, wouldn't it be best to fork FullCalendar, build/watch it in dev-mode (which generates source maps), and then npm-link your other project to it?

Discussion about the topic in general: https://github.com/googleapis/google-cloud-node/issues/2867

**Comment by justingrant** [comment]
Asking devs to fork, build, and npm-link dependencies seems like unnecessary overkill for the majority of debugging cases where devs simply want to step into or break on code inside a library to understand what their own code is doing wrong, or to understand how the library works.  Also, lots of newbie devs won't know how to do those steps correctly.  Also, once you fork, you have to remember to unfork later-- another thing that may trip up newbies.  I know you and I know how to do it safely (although it's still more work than debugging in Chrome) but I think a library should assume limited skills from its users.

Anyway, I'd recommend adding sourcemaps and including source in the npm distro.

The related discussion at googleapis/google-cloud-node#2867 is interesting. AFAIK the concerns of the maintainer about sourcemaps (to reduce npm tarball size and that it makes it more difficult to figure out where to place console.log statements in library code) sound more like typical concerns of an expert library author, not of a less-experienced client developer using the library which will be the majority of usage of any library.

Client developers I know tend to prefer to use IDE debugging (Chrome DevTools, VSCode, etc.) first, and only in advanced/unusual cases resort to console.log inside libraries. This will likely become even more true in the future as more corporate devs continue to flee the Java/C# ecosystem for the JS ecosystem but bring their preferences with them for "it just works" IDE debugging which is a baseline expectation in those other platforms that have had mature IDE debuggers for decades.

re: tarball size concern, it seems odd to trade disk space on a dev machine for debuggability.  Sourcemaps don't affect runtime bundle size, and while it's annoying to have a large node_modules folder on your dev machine, it's much more annoying to have to debug transpiled code!

re: inline or separate sourcemaps, I'm admittedly unfamiliar with inline sourcemaps so can't comment on using them like what's recommended in that thread, but I do know that almost all libs that use sourcemaps today *don't* use inline sourcemaps (they use separate sourcemaps like in my PR) so if I were in your shoes I'd probably choose the separate sourcemaps option because more tools work with them. For example, here's a thread about a rollup plugin for typescript that apparently isn't compatible with inline sourcemaps. https://github.com/ezolenko/rollup-plugin-typescript2/issues/71#issuecomment-379114306.  Another concern I have is whether the inline sourcemap will blow up the runtime bundle size-- one of the nice things about separate (non-inline) sourcemaps is that they have zero runtime cost (download size or perf) if you're not actually debugging anything, which makes them great for production debugging use-cases.

So I'd probably stick with the traditional (separate) sourcemaps and let the Google guys blaze the trail for inline maps. They probably have more pull with V8, Chrome, Node, and bundlers than we do. ;-)

Anyway, sorry to talk your ear off about sourcemaps. As you can tell I have opinions here. ;-)

**Comment by arshaw** [comment]
this is now working in v5-beta3!
info on the release: https://fullcalendar.io/blog/2020/05/react-ts-v5-beta

**Comment by arshaw** [comment]
v5, which has [just been officially release](https://fullcalendar.io/blog/2020/06/v5-official) now has working sourcemaps for all packages
