### ISSUE TITLE
eventLimit for the timeline view

### ISSUE THREAD

**Issue by zebeel** [fullcalendar/fullcalendar#4721]
Hi there,
I created a custom timeline view  name "allDay", it will display all day of calendar in configured range with the timeline style. In case there are many events are added in one resource of one day, when I change the view to "allDay", the row include that resource is spread out too large. I found the eventLimit but it doesn't support the timeline view. How can I customize it like the event popover? Hope you guy update this feature soon.

**Comment by acerix** [comment]
I believe this existing ticket captures this need:
https://github.com/fullcalendar/fullcalendar-scheduler/issues/128
↑
Could you please visit the link, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates?
