### ISSUE TITLE
timeGrid content doesn't grow when calendar height increases

### ISSUE THREAD

**Issue by Riamse** [fullcalendar/fullcalendar#4722]
### Bug Report

When the calendar height is  parent, the timegrid does not grow to fit the container it's in by making each of the rows taller until the whole thing fits. https://codesandbox.io/s/fullcalendar-react-9gfdm?fontsize=14 is a minimal example of the problem - the blue dashed box shows the size of the calendar (2000px) but the bottom of the calendar's content (the grey bar) does not move to the bottom of the blue dashed box.

#### index.html

```html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
  </head>
  <body>
    top
    <div id="root"></div>
    <script src="src/main.jsx"></script>
    bottom
  </body>
</html>
```
#### styles.css
```css
.demo-app {
  font-family: Arial, Helvetica Neue, Helvetica, sans-serif;
  font-size: 14px;
}

.demo-app-top {
  margin: 0 0 3em;
}

.demo-app-calendar {
  /*margin: 0 auto;*/
  max-width: 900px;
  border: 3px dashed blue;
  height: 2000px;
}
```
#### DemoApp.jsx
```jsx
import React from "react";
import FullCalendar from "@fullcalendar/react";
import dayGridPlugin from "@fullcalendar/daygrid";
import timeGridPlugin from "@fullcalendar/timegrid";
import interactionPlugin from "@fullcalendar/interaction"; // needed for dayClick

import "./styles.css";

// must manually import the stylesheets for each plugin
import "@fullcalendar/core/main.css";
import "@fullcalendar/daygrid/main.css";
import "@fullcalendar/timegrid/main.css";

export default class DemoApp extends React.Component {
  calendarComponentRef = React.createRef();

  state = {
    calendarWeekends: true,
    calendarEvents: [
      // initial event data
      { title: "Event Now", start: new Date() }
    ]
  };

  render() {
    return (
      <div className="demo-app">
        <div className="demo-app-calendar">
          <FullCalendar
            defaultView="timeGridWeek"
            header={null}
            plugins={[dayGridPlugin, timeGridPlugin, interactionPlugin]}
            ref={this.calendarComponentRef}
            weekends={this.state.calendarWeekends}
            events={this.state.calendarEvents}
            height="parent"
          />
        </div>
      </div>
    );
  }
}
```

Below I propose a solution:

Current:
![image](https://user-images.githubusercontent.com/2367611/59159111-df6f9180-8a92-11e9-9b3d-0f7a632ff151.png)
Proposed feature:
![image](https://user-images.githubusercontent.com/2367611/59159115-f6ae7f00-8a92-11e9-9c2c-f7acc42d92c6.png)

Notice how in the first picture, there's a gray bar showing the bottom of the calendar - but below that, there's a lot of empty space that isn't being used. The second screenshot illustrates the calendar expanding to use all the space.

The screenshot of what I propose was created with the following:
```javascript
            let rowHeight = Math.max(24, document.getElementsByClassName("fc-time-grid-container")[0].style["height"].slice(0, -2)  / 2 / 13) + "px"
            //let rowHeight = (window.innerHeight) / 13 / 2 + "px"
            console.log(rowHeight)
            let cssHack = document.createElement("style")
            cssHack.innerHTML = ".fc-time-grid .fc-slats tr { height: " + rowHeight + "; }"
            document.getElementsByTagName("head")[0].appendChild(cssHack)
```
I dug through the source code to figure out what to do. The files I believe are most important are:
- https://github.com/fullcalendar/fullcalendar/blob/e81dd831d739694163fe6b39cabec948876c8678/src/timegrid/AbstractTimeGridView.ts#L52
- https://github.com/fullcalendar/fullcalendar/blob/f86b5f33148cb43178e21c46a6ea814d128a88e1/src/core/common/ScrollComponent.ts#L82
- https://github.com/fullcalendar/fullcalendar/blob/e81dd831d739694163fe6b39cabec948876c8678/src/timegrid/AbstractTimeGridView.ts#L240

**Comment by Riamse** [comment]
(the code I propose as a solution only calculates it once; it would be very cool if we could have a real solution, one that works with window resizes)

**Comment by wterpilowski** [comment]
Hi guys
we're having the same issue. Do you have some timeline for fixing this issue?

**Comment by arshaw** [comment]
this is the same request as this ticket:
#265
&uarr;
Could you please visit the link, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates?
