### ISSUE TITLE
Delayed render() in dayGrid month hides eventLimit links and resizes calendar

### ISSUE THREAD

**Issue by acerix** [fullcalendar/fullcalendar#4723]
The "+ more" links are missing after calling "calendar.render()" a second time.

https://codepen.io/acerix/pen/QXLXXo?editors=0010

Related to https://github.com/fullcalendar/fullcalendar/issues/4718

Reported in https://fullcalendar.freshdesk.com/a/tickets/925

**Comment by acerix** [comment]
As a workaround, calling `changeView` after seems to correct it:

https://codepen.io/acerix/pen/NZKQxJ?editors=0010

**Comment by arshaw** [comment]
This was fixed in 4.3.0 though please start using 4.3.1
Releases: https://github.com/fullcalendar/fullcalendar/releases
