### ISSUE TITLE
[Feature] Support custom template in list views

### ISSUE THREAD

**Issue by frlinw** [fullcalendar/fullcalendar#4724]
### Feature Requests
It often makes sense to have differents data displayed depending on the view.
Most of the time you can't put to much data in an event square but in a list view you have as much space as you want.
In that way, a render function could be a nice to have.

```js
{
  listEventRender: ({ resource, event, eventClick }) =>  {
    return `<div>
      <h4>${event.title}<h4>
      <div>Some data</div>
      <a onclick="eventClick">more details</a>
    </div>`
  }
}
```

**Comment by acerix** [comment]
You could do that in `eventRender` by rendering something different based on which view is active, eg:

https://codepen.io/acerix/pen/Kjwzjv?editors=0010

**Comment by frlinw** [comment]
It's great, but there is an issue, an eventClick will prevent html links
https://codepen.io/frlinw/pen/OePaVN
That's why, in my initial example, I was more for a template of the whole block with control of an eventual eventClick (and the default template of this function could be the current one)

**Comment by acerix** [comment]
I didn't find a good way to make `eventClick` not apply to the entire element so that would be a new feature. 

As a workaround, you could use `event.stopPropagation()` in your links to stop the `eventClick` from running.  You could also try a [custom view](https://fullcalendar.io/docs/custom-view-with-js) for the list view.

**Comment by arshaw** [comment]
FWIW, people want something similar to this for the react connector:
https://github.com/fullcalendar/fullcalendar-react/issues/12#issuecomment-513175402

**Comment by arshaw** [comment]
this issue is a dup of:
https://github.com/fullcalendar/fullcalendar-vue/issues/14
&uarr;
Could you please visit the link, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates?

**Comment by frlinw** [comment]
I'm just asking for the control of `eventClick` in the `eventRender`, not the ability to return JSX in `eventRender` or v-slot support for event rendering.
If all these issues imply a global change in fullcalendar, may you create an issue in this repo ?
