### ISSUE TITLE
Version 4 became hard to use

### ISSUE THREAD

**Issue by YSZeng** [fullcalendar/fullcalendar#4726]
### Bug Reports
https://fullcalendar.io/docs/plugin-index

### Feature Requests
Version 4 became hard to get started
After modularization, there are so many files referenced that I don't know which ones to use.

**Comment by acerix** [comment]
There is a discussion on making a version with all plugins included:

https://github.com/fullcalendar/fullcalendar/issues/4566
↑
If that's what you are looking for, please visit the link, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates.
