### ISSUE TITLE
ListView does not unrender events on destroy

### ISSUE THREAD

**Issue by dneuschaefer-rube** [fullcalendar/fullcalendar#4727]
It seems like `ListView` does not unrender any of its events when destroyed. I have a button that switches the view between `DayGrid`, `TimeGrid` and `ListView`; elements are correctly destroyed when navigating away from `DayGrid` & `TimeGrid`, but not `ListView`. The `eventDestroy` callback is not called, and switching back and forth frequently increases memory consumption significantly, since new events are being rendered, but not destroyed.

Navigating within a `ListView` (e.g. prev/next) unrenders previous events as expected.

Repro: https://codepen.io/anon/pen/xowMBX?editors=0010

**Comment by acerix** [comment]
Thanks, confirmed.

**Comment by arshaw** [comment]
This was fixed in 4.3.0 though please start using 4.3.1
Releases: https://github.com/fullcalendar/fullcalendar/releases
