### ISSUE TITLE
Add optional property to Event::setProp to not rerender

### ISSUE THREAD

**Issue by pboyd04** [fullcalendar/fullcalendar#4729]
Currently Event::setProp re-renders the calendar after every call. While this is great when you're editing only a couple of events when you get into the hundred+ event range this wastes lots of CPU time (It's currently spending 30+ seconds in certain calendar views on my system). It would be nice if there were a third optional property to the call that defaulted to true (to rerender i.e. current behavior) but could be set to false to allow only one calendar rerender to occur.

**Comment by pboyd04** [comment]
For now I've done the following to work around this:
```js
calendar.renderingPauseDepth = true;
events[i].setProp(...)
calendar.renderingPauseDepth = false;
calendar.render();
```

**Comment by acerix** [comment]
It will help if you can provide a [runnable, stripped-down demonstration](http://fullcalendar.io/wiki/Reduced-Test-Cases/) of the performance issue. It might help to use rerenderDelay:

https://fullcalendar.io/docs/rerenderDelay

**Comment by arshaw** [comment]
this is what `rerenderDelay` is for!
