### ISSUE TITLE
Vertical Scrolbar shown in month view on Firefox

### ISSUE THREAD

**Issue by laoneo** [fullcalendar/fullcalendar#4732]
### Bug Reports
On Firefox (67.0.2) is a vertical scrollbar shown even when there is nothing to overflow. Not sure if it is a rounding issue.

You can open that pen on Firefox and you will see them.
https://codepen.io/anon/pen/KjzOQX

**Comment by acerix** [comment]
Thanks for the report.  I can see the scrollbar showing up when it shouldn't in Firefox, which also causes the day names in the header to not be aligned with the day cells.  

It seems to be triggered by having four events on the same day, and it shows up randomly when resizing the screen so might only happen at specific sizes.

I didn't find a good workaround, but `eventLimit: 3` prevents the bug:

https://codepen.io/anon/pen/bPeWOj?editors=0010

**Comment by laoneo** [comment]
I'v debugged it a bit and here https://github.com/fullcalendar/fullcalendar/blob/f86b5f33148cb43178e21c46a6ea814d128a88e1/src/core/common/scroll-controller.ts#L19 was this.getScrollWidth() 1 pixel bigger than this.getClientWidth().

**Comment by arshaw** [comment]
very similar to #4624

thanks for debugging it @laoneo ! that will be helpful

**Comment by arshaw** [comment]
is this on Windows? Might be, I can't recreate on Mac

**Comment by arshaw** [comment]
actually, i've recreated this on mac when using a zoom

**Comment by arshaw** [comment]
This was fixed in 4.3.0 though please start using 4.3.1
Releases: https://github.com/fullcalendar/fullcalendar/releases

@laoneo could you please confirm the problem is fixed?

**Comment by laoneo** [comment]
It works. Thanks for the fix!!
