### ISSUE TITLE
How to move allDay slot to bottom of fullcalendar view?

### ISSUE THREAD

**Issue by ElectricCarbon** [fullcalendar/fullcalendar#4733]
Hello, I was wondering is it possible to move the allDay slot to the bottom of the full calendar view?

**Comment by acerix** [comment]
That is not built-in and I didn't find an easy way, I think you would need to make a custom view:

https://fullcalendar.io/docs/custom-view-with-js

**Comment by ElectricCarbon** [comment]
> That is not built-in and I didn't find an easy way, I think you would need to make a custom view:
> 
> https://fullcalendar.io/docs/custom-view-with-js

Ok, thanks. Is the code for the default views available somewhere?

**Comment by acerix** [comment]
Yes, it's all in this repo, eg: https://github.com/fullcalendar/fullcalendar/blob/master/src/timegrid/TimeGridView.ts

**Comment by amh-mw** [comment]
In v4, you can use the [viewSkeletonRender](https://fullcalendar.io/docs/v4/viewSkeletonRender) hook to move the DOM elements:
```javascript
viewSkeletonRender: (info) => {
    // Move all-day events to bottom.
    var parent = $(info.el).find('.fc-day-grid').parent()[0];
    var header = parent.removeChild(parent.childNodes[0]);
    var rule = parent.removeChild(parent.childNodes[0]);
    parent.append(rule);
    parent.append(header);
}
```
