### ISSUE TITLE
FirstDay setting is not respected when week calc ISO 

### ISSUE THREAD

**Issue by laoneo** [fullcalendar/fullcalendar#4734]
According to the docs when weekNumberCalculation is set to 'ISO' it defaults to firstDay setting to Monday. But with the current code the firstDay setting is ignored when weekNumberCalculation is ISO.
Testing instructions

- Load a calendar
- Set the firstDay setting to 3
- Set the weekNumberCalculation setting to 'ISO'

The result is that it shows Monday as first day in week.

Pen to test it is here https://codepen.io/anon/pen/PrNdwo

Pr which fixes the issue is #4731.

**Comment by acerix** [comment]
Thanks, confirmed.

**Comment by arshaw** [comment]
This was fixed in 4.3.0 though please start using 4.3.1
Releases: https://github.com/fullcalendar/fullcalendar/releases
