### ISSUE TITLE
v4: fc-sat, fc-sun .. weekday classes are missing in timelineWeek and resourceTimelineWeek views

### ISSUE THREAD

**Issue by doncatnip** [fullcalendar/fullcalendar#4735]
pen:
https://codepen.io/anon/pen/MMeMGa

expected result:
Red colored Saturdays in Week and Month view.

actual result:
Red colored Saturdays only in Month view.

The month view also loses all weekday indicator classes (including fc-past and fc-future) when setting a duration, slotDuration or slotLabelInterval.

**Comment by acerix** [comment]
Those class names are not documented so I think they are used internally and not intended to be on all views.

You can use datesRender to add styles:

https://fullcalendar.io/docs/datesRender

**Comment by doncatnip** [comment]
Hmm, okay. If they aren't meant to be used this ticket can be closed. Thanks for the datesRender hint.
