### ISSUE TITLE
FullCalendar V4 Yarn does not install proper libs

### ISSUE THREAD

**Issue by gdurelle** [fullcalendar/fullcalendar#4739]
Under Rails 5 latest (webpack through webpacker) 
```
yarn add @fullcalendar/core @fullcalendar/daygrid
```
does not know the Calendar Object...

&nbsp;

Whereas everything works fine with
```
npm install --save @fullcalendar/core @fullcalendar/daygrid
```

Is the yarn package up to date ?

**Comment by acerix** [comment]
For me, that yarn command seems to install everything it should.

What is missing or what is the error message you get?

**Comment by gdurelle** [comment]
`ReferenceError: Calendar is not defined`

But there is a mistake on my own:
The imports are in application JS (main js file)
The JS code implementing Calendar is in another file (import './calendar';)
I moved the imports in the same file and everything works fine.

My bad, sorry for your time.
