### ISSUE TITLE
Events are overlaping when dragging and resizing in resource timeline 

### ISSUE THREAD

**Issue by evromalarkey** [fullcalendar/fullcalendar#4741]
https://codepen.io/anon/pen/rEWyaL

If there is more events in one resource, the event's are overlaping each other upon resizing and dragging. This is caused because event does not have correct top position in mirror container.

I'm kind of ok with overlaping when event is dragged to a different resource row. But it's really anoying when it happens on the same resource row, that could be easily fixed if the top position in mirror container was the same as original event.

**Comment by acerix** [comment]
I believe this existing ticket captures this need:
https://github.com/fullcalendar/fullcalendar-scheduler/issues/354
↑
Could you please visit the link, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates?
