### ISSUE TITLE
Drag-n-drop for overlapping calendar with different z-index's

### ISSUE THREAD

**Issue by sibbngheid** [fullcalendar/fullcalendar#4742]
**Use case:** Calendar in a modal.

**Reproduction:** https://codepen.io/anon/pen/orBgQy

**Steps to reproduce:**
![fcdrag](https://user-images.githubusercontent.com/19991745/59841513-1e3bfc00-935d-11e9-9368-0d642f79f3fc.gif)

**Comment by acerix** [comment]
Thanks, confirmed.

Related to https://github.com/fullcalendar/fullcalendar/issues/4593

**Comment by acerix** [comment]
I found another ticket which I believe captures this need, I will keep that one open as it has more details and a workaround:
https://github.com/fullcalendar/fullcalendar/issues/5026
↑
Please visit the above issue, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates.
