### ISSUE TITLE
Typescript errors when installing v4.01 and above via bower

### ISSUE THREAD

**Issue by ZackTech** [fullcalendar/fullcalendar#4744]
In Visual Studio create a new Asp.Net Core MVC Project (.Net core version 2.0)
Add bower.json file to the project
Add .bowerrc file with the following content:
"directory": "wwwroot/lib"

Then right click on the bower.json file and select "Manage Bower Packages"
Install FullCalendar v4.01 (or above)
Select Build - Rebuild All

![image](https://user-images.githubusercontent.com/8045996/59905754-ee453500-93fe-11e9-8ddf-668029e4ecf7.png)

**Comment by acerix** [comment]
Is there something in the code that could be adjusted to fix that?

Bower is deprecated, you can use the example project as a starting point:

https://github.com/fullcalendar/scheduler-typescript-example

**Comment by arshaw** [comment]
I'm surprised installing v4.x of FC via bower even downloads any files in the first place.

Yeah, Bower is no longer supported unfortunately.

**Comment by ZackTech** [comment]
Why is bower no longer supported?
Is there an alternative?
