### ISSUE TITLE
inconsistent property names in dnd/resize info objects

### ISSUE THREAD

**Issue by danydhondt** [fullcalendar/fullcalendar#4745]
When moving or resizing an event, in both cases an `info` object is generated.
Most of the properties of these objects have similar names like `event` and `revert`
However, the unaltered event, prior to dropping or resizing is called different:
After moving: `info.oldEvent`
After resizing: `info.prevEvent`

Is there a reason to do this or is it an inconsistency?

Screenshot (above `eventDrop`, below `eventResize`)
`
![Schermafbeelding 2019-06-21 om 10 05 20](https://user-images.githubusercontent.com/34274779/59908174-1340a480-940d-11e9-8990-a6aecfc962c3.png)

**Comment by arshaw** [comment]
good point. that's a mistake. they should both be `oldEvent`. I'll correct

**Comment by arshaw** [comment]
this has been fixed in v5 ([just released](https://fullcalendar.io/blog/2020/06/v5-official)). it's now called `oldEvent` in both cases
