### ISSUE TITLE
defaultTimedEventDuration overrides end time if start time and end time is same

### ISSUE THREAD

**Issue by sibbngheid** [fullcalendar/fullcalendar#4747]
Repro: https://codepen.io/anon/pen/LKyRgy

In this example my event starts on 23:10 and ends immedietly. But it is takes 2 cells. Looks like https://fullcalendar.io/docs/defaultTimedEventDuration overrides end time when start and end time is same.

**Comment by acerix** [comment]
Events are assumed to not have any duration if the start and end times are the same (ie. same as `end: null`), so it makes sense that `defaultTimedEventDuration` would determine how long the length of the event that is displayed.

You could set defaultTimedEventDuration to `00:00`, and the end date does not be set for an event has no duration:

https://codepen.io/acerix/pen/WqOdqY?editors=0010

Also, the end date is exclusive, so even for an event has very tiny duration, it should always be after the start time which also works as expected:

https://codepen.io/acerix/pen/zVzROv?editors=0010
