### ISSUE TITLE
eventLimit chops tall events

### ISSUE THREAD

**Issue by yoancutillas** [fullcalendar/fullcalendar#4751]
Hello,

If eventLimit = true, and if the event's height is altered, the "+n more" link won't appear.

https://codepen.io/yoancutillas/pen/ZdXemq

I think it happens when the event is taller than its row.

Can you take a look?

Regards,
Yoan Cutillas

**Comment by acerix** [comment]
I can see the layout breaks when the height of the events is changed with CSS, I believe the issue is that the month view assumes a fixed height of each event, so the +n link is displayed behind the events when they are made bigger.

I didn't find a way to make the events bigger without that issue, I think you would need a custom view for that. 

https://fullcalendar.io/docs/custom-view-with-js

**Comment by yoancutillas** [comment]
Thank you for your answer, 
I have tried a lot of workaround too and nothing worked. 

In the codepen, if you disable the `height: 90px;` in your browser console, you will notice that the events are actually all displayed, regardless of the day cell height, the "+n link" doesn't appear at all. And if you look into the HTML, the `.fc-more` element doesn't exist either, it isn't hidden. This shows that even if the events had a normal height, they wouldn't fit into the day cell. Now if you switch to "week" view and come back to the "month" view, the "+n link" appears (because the event height is normal this time).

This makes me think that the event height is somehow taken into account, but there is an error in the calculation to determine the output when eventLimit = true.

As per the docs "A value of true will limit the number of events to the height of the day cell.", the expected behiour is to display the "+n link" only in that case.

Moreover, if you set the aspectRatio to 10 in the codepen, you can see that the problem also appear in the other basic views (dayGridWeek and dayGridDay).

**Comment by arshaw** [comment]
when adapted for v5, seems fixed:
https://codepen.io/arshaw/pen/RwrLQWm?editors=0110
