### ISSUE TITLE
FullCalendar 4.2.1 - Height 'parent' not defined or scaling

### ISSUE THREAD

**Issue by jamesamuel** [fullcalendar/fullcalendar#4752]
**Using**:
 Angular "8.0.2"
"@fullcalendar/angular": "^4.2.1", "@fullcalendar/core": "^4.2.0", "@fullcalendar/daygrid": "^4.2.0", "@fullcalendar/timegrid": "^4.2.0",

[height]="parent" not defined and not working as expected. Not scaling to size of parent.

**Comment by acerix** [comment]
Would you be able to post a [runnable, stripped-down demonstration of the bug](http://fullcalendar.io/wiki/Reduced-Test-Cases/)? Would really appreciate it because the time saved reproducing will be time spent fixing.
