### ISSUE TITLE
bug in showNonCurrentDates option

### ISSUE THREAD

**Issue by sabersaberi2** [fullcalendar/fullcalendar#4754]
hi
when i set lacale : 'fa' , fullcalendar show me jalali (persian) calendar correctly, but when i set showNonCurrentDates to show only this month's days, then it calculate first day and last day of month according to non-jalali (non-persian) month day. 
in fact calculate according Gregorian month's days and show me for example start day of month from second day of jalali month and second day of that jalali month set with first gregorian date.
you can implement this bug only with this options:
locale: 'fa',
showNonCurrentDates: false,

**Comment by acerix** [comment]
There is an open request to add Jalali support, it is not fully implemented yet:
https://github.com/fullcalendar/fullcalendar/issues/1813
↑
Could you please visit the link, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates?
