### ISSUE TITLE
How to go to different view while dragging and dropping a event?

### ISSUE THREAD

**Issue by ElectricCarbon** [fullcalendar/fullcalendar#4755]
I would like to be able to switch the calendar view while dragging and dropping my event, however, the event I am dragging disappears when I switch to a different view.

**Comment by ElectricCarbon** [comment]
For example, the ability to scroll through days, months , weeks, etc while dragging and dropping an event

**Comment by acerix** [comment]
I believe this existing ticket captures this need:
https://github.com/fullcalendar/fullcalendar/issues/2542
↑
Could you please visit the link, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates?

**Comment by ElectricCarbon** [comment]
> I believe this existing ticket captures this need:
> #2542
> ↑
> Could you please visit the link, **give a** 👍 **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates?

Yes, but there is no solution in that ticket at all
