### ISSUE TITLE
Issues occur when wrapped in Polymer LitElement

### ISSUE THREAD

**Issue by masaoliou** [fullcalendar/fullcalendar#4756]
I am trying to wrap Fullcalendar as a Polymer LitElement component. I have encountered two styling issues which probably are caused by missing HTML `class`.

* `prev` and `next` on header are not styled. They are displayed as `e900` and `e901`, respectively.

* timeGrid view:
	All cells in focused column instead of the focused single cell are selected.
	Class `fc-highlight` is not added after cells are selected.

Which key parts have I missed during wrapping?

file `index.html`:

```html
<html lang="en">
	<head>
		<title>Full Calendar As Polymer LitElement</title>
		<style>
			full-calendar {
				display: block;
			}
		</style>
	</head>
	<body>
		<full-calendar></full-calendar>
		<script type="module" src="fc.js"></script>
	</body>
</html>
```

file `fc.js`:

```javascript
import {LitElement,html,css} from 'lit-element';
import '@fullcalendar/core/main.js';
import {fullcalendarStyle} from './core-style.js';
import '@fullcalendar/daygrid/main.js';
import {dayGridStyle} from './daygrid-style.js';
import '@fullcalendar/timegrid/main.js';
import {timeGridStyle} from './timegrid-style.js';
import '@fullcalendar/interaction/main.js';

class FullCalendarClass extends LitElement{
	static get styles() {
		return [
			fullcalendarStyle
			,dayGridStyle
			,timeGridStyle
			,css`
				 :host {
					display:block;
				}
			`
		];
	}
	render(){
		return html`
			<div id="calendar"></div>
		`;
	}
	firstUpdated(){
		let config={
			plugins:['dayGrid','timeGrid','interaction'],
			header:{left:"prev,next",center:"dayGridMonth,timeGridWeek,timeGridDay",right:"today"},
			selectable:true,
			select:info=>console.log('select')
		};
		let fc=new FullCalendar.Calendar(this.shadowRoot.getElementById('calendar'),config);
		fc.render();
	}
}

window.customElements.define('full-calendar',FullCalendarClass);
```

file `./core-style.js`:

```javascript
import {css} from 'lit-element';
export const fullcalendarStyle=css`
/* Everything from file "@fullcalendar/core/main.css" */
`;
```

file `./daygrid-style.js`:

```javascript
import {css} from 'lit-element';
export const dayGridStyle=css`
/* Everything from file "@fullcalendar/daygrid/main.css" */
`;
```

file `./timegrid-style.js`:

```javascript
import {css} from 'lit-element';
export const timeGridStyle=css`
/* Everything from file "@fullcalendar/timegrid/main.css" */
`;
```

These source files are bundled with tools _Rollup_ and _BABEL_ into two files `index.html` and `fc.js`, which are uploaded to [jsfiddle](https://jsfiddle.net/cnliou/y39pxoq7/) and runnable by Opera v58 (Firefox v60.3 appears to eat up my CPU but not respond).
However, command _npm run buid_ prints these warnings:

[log.txt](https://github.com/fullcalendar/fullcalendar/files/3365635/log.txt)

**Comment by acerix** [comment]
Would you be able to post a [runnable, stripped-down demonstration of the bug](http://fullcalendar.io/wiki/Reduced-Test-Cases/)? Would really appreciate it because the time saved reproducing will be time spent fixing.

**Comment by masaoliou** [comment]
@acerix I much appreciate your patience. I redacted my question just now.
