### ISSUE TITLE
Is there a way to have two or more different colors for a single event or cell?

### ISSUE THREAD

**Issue by rohitmarneni** [fullcalendar/fullcalendar#4757]
On the calendar, say we have a rectangle denoting some event on one day. This rectangle can take `backgroundColor`, `borderColor`, etc options and we can change its color. But is there a way to have two colors on this rectangle? 

An arbitrary example case would be to say emphasize the fact that 70% of time denoted by this event corresponds to working hours while 30% denote vacation time or something.

**Comment by acerix** [comment]
That is not built-in, but you could add styles for that from eventRender:

https://fullcalendar.io/docs/eventRender
