### ISSUE TITLE
V4 Database Connection

### ISSUE THREAD

**Issue by pepijndik** [fullcalendar/fullcalendar#4758]
Can't connect Version 4 To a database to Add new event's /Delete event's or Update event's 

Able to load event's from  database BY :
`  eventSources: [
          // your event sourc
          {
            url: 'load.php',
            method: 'POST',
            failure: function() {
              alert('Er was een Fout met de Planning op halen');
              },
              color: 'green',   // a non-ajax option
              textColor: 'black' // a non-ajax option
              }
              // any other sources...
              ],`

**Comment by acerix** [comment]
Would you be able to post a [runnable, stripped-down demonstration of the bug](http://fullcalendar.io/wiki/Reduced-Test-Cases/)? Would really appreciate it because the time saved reproducing will be time spent fixing.
