### ISSUE TITLE
View layouts don't render correctly when switching views with a validRange of a few days

### ISSUE THREAD

**Issue by ips-illuminz** [fullcalendar/fullcalendar#4760]
Hi, Thanks for this great module.

I'm having one issue with layout of Month and week when using validRange. If i choose days range of 10 days then it seems working fine, but when i use 2-3 days range then it has some weird layout issues with Month and Week calendars. If i click on Month and then Week the layout get distorted.

I have recreated the issue on stackblitz, please have a look and let me know how to solve this:
https://stackblitz.com/edit/fullcalendar-angular-example

**Comment by acerix** [comment]
Thanks for the report, confirmed.  The problem also happens without Angular:

https://codepen.io/acerix/pen/zVLaVd?editors=0010

I didn't find a good workaround, but they seem to render correctly when the previous view is the "day" view so you could override the view buttons so they first change to the day view then change to the desired view.
