### ISSUE TITLE
Simplify exporting events

### ISSUE THREAD

**Issue by willthames** [fullcalendar/fullcalendar#4764]
### Feature Requests
The internal structure of an event object makes it hard to export and then reimport

To store an event suitable for reimporting, I had to do something like this with the event:
```
function serializeEvent(event) {
  eventDefinition = Object.assign(event['_def'], event['_instance']['range']);
  eventDefinition['backgroundColor'] = eventDefinition['ui']['backgroundColor'];
  eventDefinition['borderColor'] = eventDefinition['ui']['borderColor'];
  eventDefinition['textColor'] = eventDefinition['ui']['textColor'];
  return eventDefinition;
}
```
and of course this mostly just ignores all the properties I personally don't need to persist.

It would be good if there were a method that exported the event into the format expected by e.g. `addEvent`. 

Current working code (for my case) is here, but a built-in `exportEvent` or similar would be very helpful (and hopefully less fragile to internal `EventApi` changes
```
function loadEvents() {
  events = localStorage.getItem('my.planner.events');
  return JSON.parse(events);
}

function serializeEvent(event) {
  eventDefinition = Object.assign(event['_def'], event['_instance']['range']);
  eventDefinition['backgroundColor'] = eventDefinition['ui']['backgroundColor'];
  eventDefinition['borderColor'] = eventDefinition['ui']['borderColor'];
  eventDefinition['textColor'] = eventDefinition['ui']['textColor'];
  return eventDefinition;
}

function saveEvents(events) {
  localStorage.setItem('my.planner.events', JSON.stringify(events.map(x => serializeEvent(x))));
}

document.addEventListener('DOMContentLoaded', function() {
  var Calendar = FullCalendar.Calendar;
  var calendarEl = document.getElementById('calendar');
  var calendar = new Calendar(calendarEl, {
   ...
    eventReceive: function(info) {
      saveEvents(this.getEvents())
    },
    events: loadEvents(),
  });

```

**Comment by acerix** [comment]
I see `JSON.stringify` doesn't work on the event object because of a circular reference but it works to serialize all properties that are not an object if that's what you are looking for, eg:  https://codepen.io/anon/pen/VJqxPE?editors=0011

**Comment by willthames** [comment]
Close, but that doesn't include `start` or `end` - taking that into account gets you to a point where you think "This is quite hard to get right, I wish there were a built in function that does this for me"

**Comment by arshaw** [comment]
v5 has much better methods for this:
https://fullcalendar.io/docs/Event-toPlainObject

So, you can do something like this:

```js
console.log(JSON.stringify(calendar.getEvents()))
```
