### ISSUE TITLE
Arrays in extraParams are not encoded inside square brackets since version 4

### ISSUE THREAD

**Issue by itajackass** [fullcalendar/fullcalendar#4768]
In the version 4.2.0, extraParams can view variable passed as array.

Example for 2 selections in the select example: option 1 and option 2

Version 3.x: http://jsfiddle.net/m4t6jdgk/ is ok. array_ids in the firefox console is seen as array: 

    array_ids[]
       0: 1
       1: 2

     data: function() {
        return {
          array_ids: $("#ids").val()
        };
      }

In version 4.x the same code converted: https://codepen.io/ADyson82/pen/jjJVGm there is a problem: array_ids in the firefox console is NOT seen as array:

      array_ids: 1,2

      extraParams: function() {
        return {
          array_ids: $("#ids").val()
        };

**Comment by acerix** [comment]
I can see in version 3 that an array in `extraParams` is encoded in the URL as "[a,b,c]" and in version 4 it's just "a,b,c". I'm not sure that's a bug but it should be documented how that works.

You could convert the array yourself in that function and return the format you want, eg:

https://codepen.io/pen/?&editable=true&editors=001

**Comment by arshaw** [comment]
this is happening due to the fact that jquery would be smarter about massaging non-string objects into strings when doing AJAX.

fullcalendar won't worry about this anymore. just do a `.join`....

$("#ids").val().join(',')
