### ISSUE TITLE
rerenderDelay causes selectable and editable lag

### ISSUE THREAD

**Issue by AllyMurray** [fullcalendar/fullcalendar#4770]
When setting a rerenderDelay it should work as stated in the documentation "the calendar will begin to wait after any operation that might result in rerendering". However, this should not be the case when dragging or resizing events or selecting cells.

The docs state rerenderDelay "can reduce the number of rerenders, for performance reasons". The issue is the current implementation delays the above operations giving the impression there is a performance problem.

[Reduced Test Case](https://codepen.io/ally-murray/pen/BgELXg)

**Comment by acerix** [comment]
It seems to be working as documented, and I beleive this setting is intended to be a shorter time like 10 ms which doesn't make it seem slow.

Are you looking or a similar option which would not add any delay to selecting/editing?

**Comment by AllyMurray** [comment]
In the app I actually had it set to 50ms, I set it high in the reduced test case to exaggerate the issue so it could be easily seen.

With it set to 50ms I found that moving over one or 2 cells was fine but if you move over a lot it's laggy.

If you feel this is intended behaviour it would be nice having an additional setting that doesn't apply the delay in those scenarios.

**Comment by AllyMurray** [comment]
Also do you think it's worth mentioning this in the documentation? As I say I was using 50ms but it could be worth warning users not to set too high a value for this reason.

**Comment by arshaw** [comment]
I agree, rerenderDelay should not take effect for pointer interactions like event dnd

**Comment by arshaw** [comment]
If you're curious to know, this will be included in v5 (currently in-development)
**blog post:** https://fullcalendar.io/blog/2020/02/changes-in-the-upcoming-v5

**Comment by arshaw** [comment]
this is fixed [in the latest v5-beta](https://fullcalendar.io/blog/2020/04/new-ui-features-beta)

**Comment by arshaw** [comment]
officially released: https://fullcalendar.io/blog/2020/06/v5-official
