### ISSUE TITLE
Uncaught TypeError : Cannot read property 'FgEventRenderer' of undefined

### ISSUE THREAD

**Issue by ShinArkane** [fullcalendar/fullcalendar#4771]
Hello,

When trying to use for the first time this library, I'm not able to render it on ServiceNow. After some research, I was not able to found information about this error, and most of articles found about Full Calendar in ServiceNow is about the V3. 

The console print me the following error : 

"
Uncaught TypeError: cannot read property ' FgEventRenderer ' of undefined 
        at main.min.js:20
        at main.min.js:6
        at main.min.js:6
" 
by using these dependency and their css  :

![fullCalendar depency 1](https://user-images.githubusercontent.com/47025999/61122730-d82d1080-a4a2-11e9-9bb7-f6817a994ef3.PNG)

This happens even with the reduced test cases present on the website ( FullCalendar v4 - Standard used for the test ). 

Any Idea of the root cause ?

**Comment by acerix** [comment]
Would you be able to post a [runnable, stripped-down demonstration of the bug](http://fullcalendar.io/wiki/Reduced-Test-Cases/)? Would really appreciate it because the time saved reproducing will be time spent fixing.

It sounds like the dependencies are not loading.  This page explains how to include the scripts: https://fullcalendar.io/docs/initialize-globals

**Comment by ShinArkane** [comment]
I'm sorry for the late answer, the code used is the standard of the debugging templates in Full calendar V4 : 
html : 
`
<div id='calendar'></div>
`
Other CSS  without css files in dependency correctly include inside the page :
```

#calendar {
  max-width: 900px;
  margin: 40px auto;
}
```

javascript : 
```

document.addEventListener('DOMContentLoaded', function() {
  var calendarEl = document.getElementById('calendar');

  var calendar = new FullCalendar.Calendar(calendarEl, {
    plugins: [ 'interaction', 'dayGrid', 'timeGrid' ],
    defaultView: 'dayGridMonth',
    defaultDate: '2019-06-07',
    header: {
      left: 'prev,next today',
      center: 'title',
      right: 'dayGridMonth,timeGridWeek,timeGridDay'
    },
    events: [
      {
        title: 'All Day Event',
        start: '2019-06-01'
      },
      {
        title: 'Long Event',
        start: '2019-06-07',
        end: '2019-06-10'
      },
      {
        groupId: '999',
        title: 'Repeating Event',
        start: '2019-06-09T16:00:00'
      },
      {
        groupId: '999',
        title: 'Repeating Event',
        start: '2019-06-16T16:00:00'
      },
      {
        title: 'Conference',
        start: '2019-06-11',
        end: '2019-06-13'
      },
      {
        title: 'Meeting',
        start: '2019-06-12T10:30:00',
        end: '2019-06-12T12:30:00'
      },
      {
        title: 'Lunch',
        start: '2019-06-12T12:00:00'
      },
      {
        title: 'Meeting',
        start: '2019-06-12T14:30:00'
      },
      {
        title: 'Birthday Party',
        start: '2019-06-13T07:00:00'
      },
      {
        title: 'Click for Google',
        url: 'http://google.com/',
        start: '2019-06-28'
      }
    ]
  });

  calendar.render();
});

```

Screenshot inside the ServiceNow plateform : 
![issue full calendar](https://user-images.githubusercontent.com/47025999/61358137-f6678780-a879-11e9-9fc8-700dda87197a.PNG)
After a another verification before this message, dependency is correctly present inside the page in similar way of your last link ( "<script src='   CDN LINK  '></script> " ) .

**Comment by arshaw** [comment]
we need a runnable test case in order to proceed

**Comment by jseverinson** [comment]
Found this thread when searching for the same error message. Just want to feed back that what had gone wrong was that (due to my script loader) the <script> tag for main.js ended up after the plugins in the output, not before. Fixing the output order fixed the issue.
