### ISSUE TITLE
Fullcalendar 4 packages with src catalog to allow importing source SCSS/JS

### ISSUE THREAD

**Issue by poradz** [fullcalendar/fullcalendar#4776]
Hi! After install @fullcalendar/core or plugins with yarn or npm we get only dist files:
![image](https://user-images.githubusercontent.com/31520119/61360846-8cea7780-a87f-11e9-96c1-cd495d106d12.png)

Source files would be usefull for customization, like importing directly some scss/js files.

### 👎 Actual Behavior
Fullcalendar 4 packages contain only dist files 

### 👍 Expected Behavior
Fullcalendar 4 packages contain dist and src cataloges

**Comment by acerix** [comment]
Thanks for the suggestion. There's a related discussion here:

https://github.com/fullcalendar/fullcalendar/issues/4490

**Comment by arshaw** [comment]
@acerix, this is less an issue of bundling the CSS and more an issue of allow debugging within FC's original source files.

@poradz I believe this ticket captures what you want:
#4719
&uarr;
Could you please visit the link, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates?

Please chime in on that ticket about *why* sourcemaps would be valuable versus building the dev repo yourself (or just debugging with the non-minified JS)
