### ISSUE TITLE
Override browser's localization default strings

### ISSUE THREAD

**Issue by DavidSili** [fullcalendar/fullcalendar#4778]
### Feature Requests
As noted in this issue request: [https://github.com/fullcalendar/fullcalendar/issues/4551](https://github.com/fullcalendar/fullcalendar/issues/4551) browsers do not have a correct default translation for certain languages (Serbian, Bosnian, Montenegrin, Croatian, Macedonian, ...).
In such cases it would be useful for script to first check if there are parameters in config files present that would override the browser's default strings (parameters like array of day_of_week_names or day_of_week_names_short).
It really sticks out and degrades a really cool design.

**Comment by scrnjakovic** [comment]
+1 for this, we're now getting M07 instead of July, and it is pain to diagnose as it depends on device/browser. I'd rather depend on consistent `momentjs` than on inconsistent native solution.

**Comment by arshaw** [comment]
In my opinion, the `@fullcalendar/moment` plugin, if installed, should take over in this case. People would have a bigger JS bundle but more visual consistency
