### ISSUE TITLE
Document linked recurring events with groupId while DnD

### ISSUE THREAD

**Issue by thibaudpriou** [fullcalendar/fullcalendar#4779]
### Bug Report
Events can be resized or dragged with the "interaction" plugin. For repeating / recurrent events, these operations are not persisted correctly : 
- resize or drag an event
- switch to the next month then go back to the current month
- the changes you made are not there, even though the event was specified as an array and a refetch should not occur here.

https://codepen.io/thibaudpriou/pen/MNgEpd

**Comment by acerix** [comment]
I beleive it would be a new feature since the docs don't mention that behaviour.  

You could use the callbacks like [eventDrop](https://fullcalendar.io/docs/eventDrop) to change how the event repeats.

Another option is to add an event for every instance and give them all the same `groupId` so they are resized/moved together.

**Comment by thibaudpriou** [comment]
Ok so the resizing/moving of events is only performed on "expanded" events. The docs also don't explicitly mention that this behaviour is restricted to regular events and these operations will not be permanently stored.

> You could use the callbacks like eventDrop to change how the event repeats

How can we achieve that with the current API ?
The Event Object provided by the eventDrop callback (`eventDropInfo.event`) seems to only relate to the instance that was moved. We haven't found any way to change how the associated "non-expanded" event repeats.

We did try to define an `id` for this recurrent event, then fetch it with a `Calendar::getEventById` in the eventDrop callback. But as it's a recurrent event, `Event::setDates` has no effect : this event has no start or end to begin with.


> Another option is to add an event for every instance and give them all the same groupId so they are resized/moved together.

Manually expanding delegated events is not a viable option for us. If that is the only option left, we'd prefer to create a source object, update recurrent events in the eventDrop callback then perform a `FullCalendar::refetchEvents` afterward.

**Comment by acerix** [comment]
`eventDrop` provides a `delta` with how far the event was moved.  So, for example, if an event is moved 2 days backwards, you could change `daysOfWeek` from 4 to 2 which would move all instances 2 days back.

**Comment by arshaw** [comment]
If a `groupId` is defined, it will work:
https://codepen.io/arshaw/pen/wVzzer?editors=0010

It's mentioned here:
https://fullcalendar.io/docs/event-parsing
"Events that share a groupId will be dragged and resized together automatically."

...but I understand that it's hard to wrap your head around for a recurring event with a single definition.

TODO: make the docs more clear

**Comment by arshaw** [comment]
docs fix implemented

**Comment by BlackPhoenix134** [comment]
I have set my group id like in the docs

`  events: [
                {
                    groupId: "blueEvents",
                    title: 'The Title',
                    startTime: "11:00:00",
                    endTime: "13:00:00",
                    daysOfWeek: [4],
                }
            ]
`

Interaction works but is not persisted. Moving to next week and back resets it
