### ISSUE TITLE
DOC | Getting started: step by step

### ISSUE THREAD

**Issue by abelardolg** [fullcalendar/fullcalendar#4780]
Hi,

This page [v1-Step by step](https://fullcalendar.io/docs/v1/usage) points to an older version. Inside this page, you explained how to add your widget (step by step) . 

By another hand, your most recent version of this doc doesn't include a step-by-step guide.

I wonder if you may include a step-by-step guide to add it.

Thanks in advance.

Kindest regards.

**Comment by arshaw** [comment]
I agree that the new ["Initialize with Script Tags" page](https://fullcalendar.io/docs/initialize-globals) could be more "step-by-step".
