### ISSUE TITLE
viewRender callback not executing

### ISSUE THREAD

**Issue by dasatti** [fullcalendar/fullcalendar#4783]
viewRender call back does not execute.

```
document.addEventListener('DOMContentLoaded', function() {
        var calendarEl = document.getElementById('calendar');
        var calendar = new FullCalendar.Calendar(calendarEl, {
            plugins: [ 'dayGrid' ],
            defaultView: 'dayGridMonth',
            viewRender : function (view, element) {
                console.log("view render call ", view, element);
            },
        });

        calendar.render();
    });
```
Result nothing on console on rendering calender view or changing through dates.

**Comment by acerix** [comment]
Would you be able to post a [runnable, stripped-down demonstration of the bug](http://fullcalendar.io/wiki/Reduced-Test-Cases/)? Would really appreciate it because the time saved reproducing will be time spent fixing.

**Comment by dasatti** [comment]
Please checkout this link

https://jsfiddle.net/n2wuqdt6/

**Comment by acerix** [comment]
`viewRender` is from version 3, it replaced in v4:

https://fullcalendar.io/docs/upgrading-from-v3#view-rendering
