### ISSUE TITLE
Fullcalendar SSR (server-side rendering)

### ISSUE THREAD

**Issue by Bornegrim** [fullcalendar/fullcalendar#4784]
[sandbox](https://codesandbox.io/s/example-hello-world-j6piv?fontsize=14)

FullCalendar displays "Element is not defined" error. I've tried to install it as a plugin and set nuxt SSR to false, the problem persists. The only fix without changing the code (that I found) is setting nuxt to --spa mode. 

Found this [issue at fullcalendar-react](https://github.com/fullcalendar/fullcalendar-react/issues/17) and that fixed the problem. 

[My pull request](https://github.com/fullcalendar/fullcalendar/pull/4781)

EDIT:

Found a workaround. 

Instead of this:

plugins/full-calendar.js
```
import Vue from 'vue'
import FullCalendar from "@fullcalendar/vue"

Vue.use(FullCalendar)
```
Do this:

plugins/full-calendar.js
```
import Vue from 'vue'
import Calendar from '~/components/calendar'

Vue.component('calendar', Calendar)
```

and in nuxt.config.js
```
plugins: [
    {src: '~/plugins/full-calendar.js', ssr: false}
]
```

**Comment by arshaw** [comment]
It's up for discussion whether we should modify FC to correctly operate in these weird simulated DOM environments (is that the best term for what Nuxt is doing?). What is nuxt's philosophy behind not allow this?

But I'm glad there's a workaround with `ssr: false`

**Comment by brendanmckenzie** [comment]
We are experiencing the same issue using ReactJS.NET.

`Element` does not exist in the global namespace, just like `document` and `window`.

**Comment by superbiche** [comment]
This happens for any server-side rendering environment, not only Nuxt.js but also Next.js for React and - I suppose - ReactJS.NET.  

FC _could_ be modified to support SSR by not supposing `window` exists (or behaving differently in case it doesn't exist).I guess this is not a trivial task, and also that it's not that useful: SSR support is generally useful for content relevant to SEO, as we usually need this content to be rendered on the server side. My bet is that this won't be the case in most environments.

@brendanmckenzie have you tried to render FC only if `typeof window !== 'undefined'`? That should do the trick by not rendering it in SSR context, then render it on the client.

**Comment by brendanmckenzie** [comment]
Yes, we could that by either doing the check `typeof Element !== 'undefined'` or setting a nodejs global variable (`global.Element = {...}`) fixed the issue.

**Comment by zorrme** [comment]
Can we please fix document, window and Element issue in ssr ? I am having the same issue in angular universal

**Comment by usha-raikwar** [comment]
I am also facing same issue in next.js 9.2. Any luck so far?

**Comment by janswist** [comment]
@Bornegrim did something changed since 2019? I have trouble importing it plugin to the component.

Also, worth noting that `ssr: false` will be depracated. See: https://nuxtjs.org/guide/plugins#client-side-only

**Comment by janswist** [comment]
I see some updates here - should we expect some solution for that issue in the near future? 😀

**Comment by arshaw** [comment]
I was thinking that maybe v5 would have solved this problem, but then realized it probably has not

**Comment by arshaw** [comment]
@janswist, as you mentioned, nuxt will only support `mode:'client'` it seems (https://nuxtjs.org/guide/plugins#object-syntax)

I really don't think FullCalendar should be runnable on server-side only. We can fix the `Element` issue, but then we'd need to safeguard all references to `window` and `document` as others point out. Even if we did that, FullCalendar would not have access to real-world dimensions of certain elements that it needs to render its layout.

Do others agree that it's not appropriate for FullCalendar to render on the server-side?

**Comment by brendanmckenzie** [comment]
It would be good if FullCalendar would be at least SSR-friendly.  Not that it works in SSR-only modes as that is obviously not feasible.

Fixing the references to `window` and `document` resolves the issues we're facing, renders what's needed on the server then leaves the rest up to the client-side to sort out.

**Comment by janswist** [comment]
> (...) FullCalendar would not have access to real-world dimensions of certain elements that it needs to render its layout.

Out of curiosity - how come other page elements, like Bootstrap, work then? They render (probably) without knowing real-world dimensions somehow.

Also there might be (slight?) SEO advantage, but maybe some other more experience people would say something about it.

**Comment by morhook** [comment]
@janswist Bootstrap uses CSS logic to modify it's behaviour/rendering. In this case, `fullcalendar` is using JS logic to modify what is it rendering.

**Comment by morhook** [comment]
Maybe we should consider what they suggest on this [SO answer](https://stackoverflow.com/a/55424232/6505594)? (I don't know much, so that's why I re-post someone elses answer)

**Comment by arshaw** [comment]
a proper fix is coming up in the next release. i'll comment when published

**Comment by FarazPatankar** [comment]
Just came across this whole conversation, happy to see that a fix is coming. Is there an ETA on it, @arshaw? Thanks!

**Comment by arshaw** [comment]
This is released in v5.2.0. You will no longer see errors about window/document/Element when rendering FullCalendar in an SSR environment.

Please keep in mind there are other hoops you need to jump through to use FullCalendar with Nuxt/Next. Please see these sample projects:
https://github.com/fullcalendar/fullcalendar-example-projects/tree/master/nuxt
https://github.com/fullcalendar/fullcalendar-example-projects/tree/master/next

**Comment by janswist** [comment]
Nice! So all there is to do is to add one line in config file?

**Comment by arshaw** [comment]
For Nuxt, yes. For Next, it's a bit more complicated.

**Comment by janswist** [comment]
Today I updated packages and still have this problem:
![image](https://user-images.githubusercontent.com/5583954/89218094-b9c61580-d5cd-11ea-8f79-34424f61aa73.png)
(upper console is Nuxt server so they are not shown in order)

Should I still keep `client-only` wrap around FullCalendar component?

**Comment by amirakbulut** [comment]
Has the following issue anything to do with this?

https://github.com/fullcalendar/fullcalendar/issues/5730

**Comment by stupidguy176** [comment]
I have run your project in https://github.com/fullcalendar/full
![image](https://user-images.githubusercontent.com/15109912/96536249-d2d18f00-12bd-11eb-9547-88ce4ef4b5ed.png)
calendar-example-projects/tree/master/nuxt and still got this error

**Comment by atifsyedali** [comment]
I still get window is not defined but I hit it in @full-calendar/premium-common/main.js:30 where it does `isImmuneUrl(window.location.href)` for license check.

Anyway to supply a URL or disable this check on server? Just checking for existence of window will not do because many environments have things like jsdom for SSR, and window.location.href doesn't work which is what the line above tries to access.

**Comment by vhlavsa** [comment]
If you are still experiencing the "window is not defined" issue, try updating your Node version to at least v12.

**Comment by Emiliorth** [comment]
> If you are still experiencing the "window is not defined" issue, try updating your Node version to at least v12.

Worked! Node 14.17.5 LTS! Even without transpile, no-ssr, <client-only>, full-calendar.js with component as a imported no-ssr plugin

**Comment by gfragioud** [comment]
Using angular universal, this [line](https://github.com/fullcalendar/fullcalendar/blob/ede23c4b2bf0ee0bb2cbe4694b3e899a09d14da6/packages/core-preact/src/vdom.ts#L59) causes
`ERROR ReferenceError: document is not defined`

Any suggestion?

**node:** 14.18.1,
**angular:** 12.2.8,
**universal:** 12.1.1
**fullCalendar:** 5.10.1
