### ISSUE TITLE
eventSourceSuccess handler not called when attached with "on"

### ISSUE THREAD

**Issue by TheDigitalOrchard** [fullcalendar/fullcalendar#4787]
When defining `eventSourceSuccess` as an `on` handler, it is not being called. This handler is called correctly when directly defined on options object during initialization.

This does not work:
```
calendar.on('eventSourceSuccess', function(content, xhr) {
        console.log(content);
        console.log(xhr);
        return content;
});
```

This is working correctly:
```
var calendar = new FullCalendar.Calendar(frame, {
        eventSourceSuccess: function() {
            console.log(content);
            console.log(xhr);
            return content;
        }
});
```

Other event handlers attached using `on`, such as `eventDrop`, are working correctly.

Yes, these handlers are all defined before calling `render()`.

**Comment by acerix** [comment]
Would you be able to post a [runnable, stripped-down demonstration of the bug](http://fullcalendar.io/wiki/Reduced-Test-Cases/)? Would really appreciate it because the time saved reproducing will be time spent fixing.
