### ISSUE TITLE
selectOverlap prevents creation of allday events

### ISSUE THREAD

**Issue by wsergent** [fullcalendar/fullcalendar#4792]
(Edit: Sorry, I know this reads as a support request, but it's technically a feature request - please add the 'selection' object to the properties of the `selectOverlap` function).

Because [selectOverlap](https://fullcalendar.io/docs/selectOverlap) function only passes through the event being overlapped, and not the selection, it is difficult to customise how to handle event creation.

In my case, we are working on a calendar/diary system, with background events showing the employee's shifts, and events showing their individual bookings.

At this point, other than the background events - absolutely no events should be able to overlap each other.

However... on top of that - we are then overlaying 'all day events' - which might be any number of things, but for examples sake, let's say they're 'staff birthdays' - therefore, you might have a couple of events today, but there will be an event in the all day section, showing someone's birthday.

I am checking for `eventOverlap` and doing some other checks on `eventDrop` and `eventResize` which handle different clashes, but these only work for existing events being moved or resized. I would like to do the same on event creation - which happens during the `select`. In order to disallow the `select` of spaces which already have events, I am using the example function from the `selectOverlap` documentation:

```
function(event) {
    return event.rendering === 'background';
}
```
This works fantastically. However, if I try to create a new All Day event, it will 'overlap' any other events that exist on that day, and not pass this check.
I was hoping to be able to use the selection's object to check it for an `allDay=true`, but the function is only passed the existing event, and there is no way to check the selected section.

You can see a very simplified demo here:
https://codepen.io/anon/pen/NQrxOO
Try to create an allday event on the day which already has events.

Is there a better way to do this? I can completely remove the `selectOverlap` and do everything in the [select](https://fullcalendar.io/docs/select-callback) callback instead, but I would need to essentially duplicate the overlap checks just to make this work, and I feel like that seems like overkill for something that should be relatively simple.

Is it possible to get not only the overlapped event object, but also the selection object when doing a `selectOverlap` function?

**Comment by wsergent** [comment]
Current workaround is to remove the `selectOverlap` check, and instead do it myself within the `select callback`.

Curious as to whether there is a more official way that is better.

Below is a simplified version of a quick function I wrote to call when using `select={this.handleEventCreate}` :

```
    handleEventCreate = (info) => {
        // Get the Calendar API to allow unselection
        let calendarApi = this.calendarRef.current.getApi();

        // Get all Events
        let checkEvents = calendarApi.getEvents();
        // Loop through them
        checkEvents.forEach(function(event){
            // If it's not a background element, check whether the new element contains the existing, or vice versa.
            if(event.rendering !== "inverse-background" && 
                    (
                        (event.start >= info.start && event.start <= info.end) ||
                        (event.end >= info.start && event.end <= info.end) ||
                        (info.start >= event.start && info.start <= event.end) ||
                        (info.end >= event.start && info.end <= event.end)
                    )
                ){
                    // It is an overlapping event, so we reject it.
                    return calendarApi.unselect();
                }
        });

        alert('All good here to create the event.');
        //extra event creation code to fire here.
    }
```

**Comment by acerix** [comment]
So, if I understand, you are looking for a way to make `selectOverlap` not apply to all-day slots?

I believe doing it from `select` is the best way to do that currently.

**Comment by wsergent** [comment]
Yes, that's exactly it, and it's what my `select` function above is now doing.

Personally though, I do think that there would be benefit in the `selectOverlap` being passed the selection and the overlapped event - in the same way that the `eventOverlap` method receives the two events.

**Comment by arshaw** [comment]
i definitely understand the need for this. i've found another ticket that already expresses this need:
https://github.com/fullcalendar/fullcalendar/issues/3793
&uarr;
Could you please visit the link, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates?
