### ISSUE TITLE
Logo proposal

### ISSUE THREAD

**Issue by Miguimonti** [fullcalendar/fullcalendar#4793]
Hello @blissdev @fullcalendar
Good morning, I would like to contribute to the project by providing a logo without commitment.
Let me know if you want me to submit any proposal.

Good Day.

**Comment by arshaw** [comment]
Hi @Miguimonti , thanks for the ping. We recently redesigned the branding which you can see at https://fullcalendar.io/ , including a new logo. I have not yet uploaded it the GitHub organization FYI. But I'm open to seeing what ideas you have, I'm always receptive to design improvements. Please email me at arshaw@(the domain of fullcalendar's website)
