### ISSUE TITLE
Add rendering property to event source object

### ISSUE THREAD

**Issue by chrisribal** [fullcalendar/fullcalendar#4798]
In my application i tried to load events from 2 different sources, each of them is an array. The first source contains events an employee has to attend to. The second source contains absences of each employee and needs to be rendered as background events.

To realize that, i created 2 arrays as Vue prop and bound them in an array of eventSources to add other options, like `rendering` or `editable`. Unfortunately the `rendering` property seems to be ignored.

https://codesandbox.io/embed/fullcalendar-vue-fd8rp

**Comment by arshaw** [comment]
when adapted to v5, this now works:
https://codepen.io/arshaw/pen/xxZXYee?editable=true&editors=001

make sure to use the `display` property instead of `rendering`
