### ISSUE TITLE
resourceRender: incorrect args

### ISSUE THREAD

**Issue by arshaw** [fullcalendar/fullcalendar#4811]
http://fullcalendar.io/docs/resource_rendering/resourceRender/

should read:

```
resourceRender: function(resourceObject, dataTds, eventTd) {
    dataTds.css('background', 'blue');
}
```

the `resourceObject` param was omitted

**Comment by dakala** [comment]
@arshaw The docs have been updated. Both v4 and v3 (https://fullcalendar.io/docs/v3/resourceRender) look ok.
