### ISSUE TITLE
Calls to re-render resources while selecting/dragging/resizing leads to error

### ISSUE THREAD

**Issue by notajingoist** [fullcalendar/fullcalendar#4817]
I have run into a bug where calling any method that re-renders resources (`refetchResources`, etc.) while in the middle of performing a selection/drag/resize (at least these) leads to the following error (stack trace included): 

```
Uncaught TypeError: Cannot read property 'length' of null

FC.CoordCache.Class.extend.getHorizontalIndex @ fullcalendar.js:2122
FC.TimeGrid.Grid.extend.queryHit @ fullcalendar.js:6340
DragListener.extend.queryHit @ fullcalendar.js:2784
DragListener.extend.drag @ fullcalendar.js:2709
FC.DragListener.Class.extend.mousemove @ fullcalendar.js:2341
(anonymous function) @ fullcalendar.js:942
n.event.dispatch @ jquery.min.js:3
r.handle @ jquery.min.js:3
```

I think what's happening is that when I re-render, the original `colCoordCache` object is reinitialized in the `renderDates` function but the query hits are still happening and so this check for length on `colCoordCache.left` (which is now null) results in this error.

The reason this is a problem for me is that I am working with a live-updating asynchronous data model that continuously pushes updates from the server to the client. This means that at any point, I might need to re-render the resources if they change on the server. And because these live updates are unpredictable, they may happen while a user is selecting some part of the scheduler, or dragging/resizing an event. 

To work around this, I tried to set a flag to indicate when the scheduler is "busy," i.e. not safe to re-render resources, but the API doesn't include callbacks that fire at the very start of each of these interactions. `eventDragStart` is OK, but `select` and `eventResize` don't actually fire until after a selection and resize are completed (mouse click is released), and that is too late. (Although I would rather this bug be fixed than have a change to the API to provide more useful callbacks).

I've simulated this bug on jsbin (http://jsbin.com/kavowocufo/edit?js,output) by making a call to `refetchResources` every 1000 milliseconds. Open up the console, and start selecting parts of the scheduler/dragging events/resizing events and observe the above error get logged.

**Comment by arshaw** [comment]
this is no longer an issue: https://codepen.io/arshaw/pen/abdwvON?editable=true&editors=001

**Comment by ickphum** [comment]
Hi Adam. Re your comment "no longer an issue", does this assume v5 is in use?
Thanks.

**Comment by arshaw** [comment]
exactly. i forgot to clarify that. the problem is fixed, only in v5
