### ISSUE TITLE
horizontal scrolling in Agenda views

### ISSUE THREAD

**Issue by alan1o** [fullcalendar/fullcalendar#4819]
If dealing with lots of resources, currently each resource column just gets more and more compressed. It would be good if we could set a minimum width and have a horizontal scroll bar appear for resources that are unable to fit within the existing view.

**Comment by arshaw** [comment]
Hello all, we recently merged the fullcalendar and fullcalendar-scheduler issue trackers. This issue (horizontal scrolling in timeGrid views) was represented in both, so now it's a...

Duplicate of #3022 
&uarr;
Please visit the above issue, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates?

We are still aware this is a highly requested feature. The thing holding us back from implementing it is the extensive DOM/CSS refactoring needed to get it to work. We are investigating and planning solutions for the next major release.
