### ISSUE TITLE
businessHours are not rendered properly in resourceTimelineMonth view when CSS margin and font-size are set

### ISSUE THREAD

**Issue by micobarac** [fullcalendar/fullcalendar#4839]
### Bug Reports
Weekends are not rendered properly in v4 in resourceTimelineMonth view. They are misplaced along the x axis. Other views render weekends ok. Btw, I am using the default theme. I have an extra custom button which loads resources and events dynamically.

```javascript
      businessHours: {
        daysOfWeek: [1, 2, 3, 4, 5],
        startTime: '08:00',
        endTime: '16:00'
      },
```

![Screenshot 2019-03-21 at 08 58 50](https://user-images.githubusercontent.com/16001837/54739208-96a4ec80-4bb7-11e9-92e6-c314082a8336.png)

This happens both with Chrome, Safari and Firefox on MacOS. If I resize the browser, the glitch disappears.
It looks like the left positions of the weekend highlights are not calculated correctly.

**Comment by acerix** [comment]
I can't reproduce this in Firefox anymore but it still happen for me with Chromium 76.0.3809.100 and version 4.3.1:

https://codepen.io/acerix/pen/NWKPrqq

**Comment by lucasbrtd** [comment]
Hi, 
I also encountered this render problem but I succeed to fix it by putting a listener on calendar loading and inside, update the size of the calendar :
```javascript
calendar.on('loading', function () {
    calendar.updateSize();
});
```
I refer to the documentation here : https://fullcalendar.io/docs/handlers
Hope it was helpful ! :+1:

**Comment by armisoftware** [comment]
Hi, from where can I download the different versions of fulcalendar? I an using a fullcalendar.min.js version v3.4.0 and dont know how to upgrade.
Thanks
