### ISSUE TITLE
filterResourcesWithEvents does not always hide resource columns without any events when using groupByDateAndResource

### ISSUE THREAD

**Issue by madhawa-se** [fullcalendar/fullcalendar#4843]
i want to hide resources those doesn't have any events  in multiday view.i can use filterResourcesWithEvents but unfortunately it only works in single day view.for example if i have 2 days view in first day resource A have events ,second day resource A doesn't have events i want to hide Resource A in 2nd day only.here is a demo of my issue.
https://codepen.io/anon/pen/XGjxEP

as you can see it doesn't hide resource A in second date ( 2019-03-05 ) even it doesn't have any events.
it's possible hide resource those doesn't have event in that day in multiview calender?

**Comment by arshaw** [comment]
https://github.com/fullcalendar/fullcalendar/issues/4290
&uarr;
Could you please visit the link, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates?
