### ISSUE TITLE
Scheduler dayClick Right-Click (FullCalendar v3.9.0)

### ISSUE THREAD

**Issue by LrntL** [fullcalendar/fullcalendar#4847]
Hi,

I first looked for topics related to this possibility but the answers always concern the right-click on the events (No problem with that). I'm looking for a way to call right-click on empty slots in "timelineDay" view

The goal is to generate a context menu to copy/cut an event and then paste it to another date on a free slot.

I modified the source code but it is really not ideal.
Line 13682 of fullcalendar.js

`component.bindDateHandlerToEl(el, 'contextmenu', function (ev) {
	if (!component.shouldIgnoreMouse() && ev.which == 3) {
		return dragListener.startInteraction(ev);
	}
	ev.preventDefault();
});`

Then at initialization, I can do:

`dayClick: function(date, jsEvent, view, resourceObj) {
	if(jsEvent.which == 3) {
		console.log('Right-Click ' + resourceObj.id + ' on date ' + date.format('YYYY-MM-DD HH:mm'));
	}
}`

Sometimes I get js errors (maybe related to drag functions) and it breaks all the functions.

**Is there a simple way to capture the right-click on dayClick?**

I specify that https://github.com/mherrmann/fullcalendar-rightclick is not usable with scheduler on the view "timelineDay". I ran a lot of posts on StackOverflow and here but with no success for several days.

Thank you in advance for your help which I think will serve a lot of people.

I have no jsfiddle for the time because the function is not implemented. I'm just looking for advices et I apologize if I made mistake by submitting this. This is my first post on Github ;)

**Comment by stclairdaniel** [comment]
@LrntL - You said " but the answers always concern the right-click on the events (No problem with that" - I can't find any way to do this. It's unrelated to this issue, but how did you accomplish a right-click on an event?

**Comment by LrntL** [comment]
As I remember, handle right-click on event is "quite simple". I used a third party jQuery plugin to show a context menu (jQuery contextMenu v2.7.1 - http://swisnl.github.io/jQuery-contextMenu/)

And so to capture the right-click on an event, I use a jQuery selector like:
```
$('.Timetable').contextMenu({
	selector: ".eventContextMenu",
	// define the elements of the menu
	items: {
		'open': 	{ name: "Voir", 		icon : 'custom-open', 	callback: function(key, opt){ location.href = './order.php?id_order='+opt.$trigger.attr("data-id_order"); }}, 
		'select': 	{ name: "Sélectionner", icon : 'custom-select', callback: function(key, opt){ contextSetOrderTimetable(opt.$trigger.attr("data-id_order"), opt.$trigger.attr("data-infos_context_title")); }}
	}
});
```

So a simple selector should do the trick.

Where do I set the `.eventContext` css class to make this selector?

Just use eventRender:

```
eventRender: function(eventObj, element, view) {
	[...]
	// Add class to access the context menu for event
	element.addClass('eventContextMenu');
	[...]
	// Place id_order as an attribute to get it back later
	element.attr('data-id_order', eventObj.id);
	element.attr('data-infos_context_title', eventObj.infos_context_title);
},
```

Note : In the context menu, the item "select" allows me to store the event id to to something else later with it.

The problem for me was to get a right-click on an empty slot in the timetable in order to "paste/move" the previous copied event. And this part was horrible.

I hope it will help you...
(I am french, I also hope you understand all I wrote)

**Comment by stclairdaniel** [comment]
Ahh, I see. Thanks for the explanation! I'm hoping to find a solution that does not require jQuery. I suppose I could whip up a similar vanilla JS solution.

**Comment by conradkirschner** [comment]
Why is this event restricted to a specific event? Is it possible to make a more dynamic, to attach custom events, like right click, touch start, left click? 

At least it should be possible to open this function to handle all mouse events (maybe with a feature flag, like: mouseEvents:all (default:left))

@arshaw Is this possible?

**Comment by arshaw** [comment]
i've repurposed this existing ticket to be about right-click on date cells in the general sense:
https://github.com/fullcalendar/fullcalendar/issues/2748
&uarr;
Could you please visit the link, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates?

**Comment by bwobbones** [comment]
@arshaw I think I need this one to get the `resource.id` into a context menu function (I'm implementing copy & paste).  I'm happy to submit a PR to get it done, would you be able to help kick me off with some tips on an approach?

I'm guessing that its going to be similar to `dateClick`?
