### ISSUE TITLE
resource object data param, accept a function

### ISSUE THREAD

**Issue by Vinze** [fullcalendar/fullcalendar#4850]
I think I found an bug, see the following code:

``` js
resources: {
    url: 'http://jsbin.com/pizesi.js',
        data: function() {
            return { test: 1 };
        }
    },
events: {
    url: 'http://jsbin.com/silaziv.js',
    data: function() {
        return { test: 1 };
    }
}
```

When loading the page, two requests are made:

```
Resources: http://jsbin.com/pizesi.js?_=1464608570270
Events:    http://jsbin.com/silaziv.js?test=1&start=2015-08-07&end=2015-08-08&_=1464608570271
```

As you can see, the resources data isn't present in the request URL. When data is a plain object (`data: { test: 1 }`) it does seem to work, but I need to pass the data using a function because it's dynamic. Did I just found a bug?

JS Bin example: http://jsbin.com/zeveyazevo/1/edit?js,output

**Comment by arshaw** [comment]
should work now: https://fullcalendar.io/docs/resources-json-feed

`extraParams` is allowed to be a function
