### ISSUE TITLE
animate collapsing of resource groups

### ISSUE THREAD

**Issue by anton-bot** [fullcalendar/fullcalendar#4851]
#### Issue

When you click a resource group to expand it, it is animated. 

However, when you collapse a resource group, it occurs immediately and without animation. 

It would be great to have animation on the collapsing too, although I realize it is not that easy to animate on table rows. 
#### Workaround

As a workaround, I'm using this (horribly bad) code that animates font-size instead, leading to a more or less decent simulation of the collapse effect: 

```
  RowParent.prototype.hide = function() {
    var child, j, len, ref, results;
    if (this.isShown) {
      if (this.isRendered) {
        //this.trs.hide();
        /* customization starts below */
        this.trs
            .animate({ 'fontSize': '1px' }, 70)
            .slideUp(1)
            .animate({ 'fontSize': '12px'}, 10)
            ;
        /* customization end */
      }

```

**Comment by arshaw** [comment]
this ticket now captures this need:
https://github.com/fullcalendar/fullcalendar/issues/4844
&uarr;
Could you please visit the link, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates?
