### ISSUE TITLE
Consider Locker Service Restrictions 

### ISSUE THREAD

**Issue by marvintoledo** [fullcalendar/fullcalendar#4856]
As per Salesforce, new customers will have this feature enabled. This has made our current pages that work before to break. Can fullcalendar accomodate these?
https://developer.salesforce.com/docs/atlas.en-us.lightning.meta/lightning/security_code.htm

**Comment by acerix** [comment]
I found a tool to test compatibility:

https://developer.salesforce.com/docs/atlas.en-us.lightning.meta/lightning/security_locker_console.htm

I didn't test every plugin but the core code seems fine now.  If there is still an error, please provide a code sample that is not working.
