### ISSUE TITLE
wrong slot start time for next days

### ISSUE THREAD

**Issue by nsocheleau** [fullcalendar/fullcalendar#4860]
Hello,

I'm trying to setup a schedule view with 2 time slots per day (5h slots) starting at 7am.
For the first day in the view, it shows 2 columns with 7am and 12pm es expected.
For the next day, the columns are 8am and 1pm. For the 3rd, 9am and 2pm.

http://jsbin.com/worusuwiju/edit?js,output

I am expecting 7am and 12pm columns for the days.

Is there a setting that I am missing?

Thanks,
Nicolas

**Comment by arshaw** [comment]
i believe this ticket is a dup of:
https://github.com/fullcalendar/fullcalendar/issues/472
&uarr;
Could you please visit the link, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates?
