### ISSUE TITLE
Inverse-Background events in TimelineMonth or SlotDuration 24 hours

### ISSUE THREAD

**Issue by Zenshio** [fullcalendar/fullcalendar#4862]
Hello !
Like many users, I use background events with inverse-background to replicate the businessHours option behavior and have more control over them.

But in TimelineMonth (or TimelineWeek with a 24 hours SlotDuration for example), if the events are not lasting the whole day, like 10H to 20H, they are rendered improperly. It seems to create background events overlapping each other.
The issue doesn't happen with businessHours.

With : `events: [{
      id: 'nonbusiness',
      start: '2016-09-05 10:00:00',
      end: '2016-09-05 20:00:00',
      rendering: 'inverse-background',
      color: '#D7D7DC'
    }]`
I get this : http://i.imgur.com/zinLCAH.png

With : `businessHours: {
      dow: ['1'],
      start: '10:00',
      end: '20:00'
    }`
I get this : http://i.imgur.com/AJL0j8x.png

I expected the same result with both methods.

JSBin : http://jsbin.com/desusubono/edit?js,output

**Comment by arshaw** [comment]
I wonder if this is happening in v4 also

**Comment by acerix** [comment]
This is fixed in v4, new demo:

https://codepen.io/acerix/pen/NQMjaX
