### ISSUE TITLE
Events render multiple times if no resources are defined for the calendar (timeGridDay)

### ISSUE THREAD

**Issue by demobiel** [fullcalendar/fullcalendar#4863]
Hi

here is a jsbin demonstrating the behavior:
http://output.jsbin.com/zejowejite

I have the following event array:
```javascript
[{
    "id":"EVENTXXX181912792219",
   "title":"test",
    "description":"",
   "start":"2016-12-01T04:00:00.000Z",
    "end":"2016-12-01T12:20:00.000Z",
    "allDay":false,
    "resourceIds":["ZUSRXXXX441010557007","PROJECTX566319200008"]
}]
```

my calendar provides an empty "resources" array:
```
resources:[],
```

the result is that it displays the event twice (it will show it as many times as there are resources specified in the events resourceIds attribute).

I solved this by changing the detection if it should render a normal agendaView or a the resourceAgendaView in the method FC.views.agenda.queryResourceClass, which can be found on line 6022 of the scheduler.js file. I did it there, as this behaviour is only present in the agendaDay view, not in the agendaWeek view.

I simply added (and I know this is probably not the best way) the check to see if there are any resources declared or not:
```javascript
FC.views.agenda.queryResourceClass = function(viewSpec) {
  var ref;
   // START MOD
  if(viewSpec.options.resources === undefined || viewSpec.options.resources.length === 0){
    return false;
  }
   //END MOD
  if ((ref = viewSpec.options.groupByResource || viewSpec.options.groupByDateAndResource) != null ? ref : viewSpec.duration.as('days') === 1) {
    return ResourceAgendaView;
  }
};
```

I tested this "hack" and don't find any weird behaviours due to this change.

**Comment by arshaw** [comment]
no longer the case. in v5, only renders once: https://codepen.io/arshaw/pen/eYJRJNW?editors=0010
