### ISSUE TITLE
Resources height problems with multiple lines

### ISSUE THREAD

**Issue by kvnvandenbrande** [fullcalendar/fullcalendar#4866]
Whenever you have multiple resources columns and not the first but seconds, third, ... column has a larger height then the first column the heights get calculated wrong. This causes a difference between your recourses and actual body. 
It's due to the height of the first column gets taken

https://jsfiddle.net/kvdb/nqexf62z/

**Comment by arshaw** [comment]
i adapted the repro to v5. it doesn't seem to be an issue anymore

https://codepen.io/arshaw/pen/KKVqVzg?editable=true&editors=001
