### ISSUE TITLE
Non-full-day slots should have same classNames as day slots

### ISSUE THREAD

**Issue by vbornand** [fullcalendar/fullcalendar#4870]
Sample:
http://jsbin.com/fanepodile/edit?css,js,output

In this sample, I try to set the background color of the mondays in the header.

It works on the view "1 day" but not in the view "1/2 days"

If the slotduration isn't a full day the classes on the th are missing.

Full day:
`<th class="fc-widget-header fc-mon fc-past" data-date="2017-02-06"><div class="fc-cell-content"><span class="fc-cell-text">Mo 6</span></div></th>`

Not full day:
`<th class="fc-widget-header" data-date="2017-02-06T00:00:00" colspan="2"><div class="fc-cell-content"><span class="fc-cell-text">Mo 6</span></div></th>`

**Comment by platosinski** [comment]
Hi,
I also miss these classes.

File related with header is: https://github.com/fullcalendar/fullcalendar-scheduler/blob/5c6ce8eb2638a40c8d96150708424cce450215bd/timeline/src/TimelineHeader.ts#L40

In both cases getDayClasses are not fired. Could it be that for background, the getDayClasses function will be always run, regardless of the result of the isTimeScale function? And for header, oneDay could be based on tDateProfile.labelInterval, considering that 1 day can be defined in miliseconds?

Regards

**Comment by arshaw** [comment]
fixed in v5 
https://codepen.io/arshaw/pen/MWKoqXv?editable=true&editors=001
