### ISSUE TITLE
single resource view pulldown selector

### ISSUE THREAD

**Issue by scottknoblesmith** [fullcalendar/fullcalendar#4872]
### Feature Request
Use case: with multiple resources using vertical resource view, "week" view and even "2day" view event slots can become too small to be useful.   Easy changing to single resource view would be very helpful.  Custom buttons can already do this but if you have more than a couple of resources, you quickly run out of "header" space.  A pull down selector would be an ideal widget to solve this problem.

 I have already tested changing from multi-view to single resource view in multiple view contexts and it works fine from a custom button added to the calendar header.

**Comment by arshaw** [comment]
thanks for the ticket, i'm not sure there's enough demand to implement this feature, but if you'd like to flesh out your description with visual mockups that might help people envision it better and build more demand
