### ISSUE TITLE
Adding a resource with a closed resource as previous sibling messes up the order of child resources

### ISSUE THREAD

**Issue by MartijnWelker** [fullcalendar/fullcalendar#4874]
In my example I automatically close the resources, but the bug will also occur when you manually close the resources.

If you click the `Click me` button a new resource will be added by calling `addResource`, if you open `Auditorium D` you will see that the child resources are now below the child resources of `Auditorium E`, instead of above them.

http://jsbin.com/wipobac/1/edit?output

**Comment by arshaw** [comment]
i'm wondering if this is still the case in v4
