### ISSUE TITLE
Document resources:false, for disabling resource columns

### ISSUE THREAD

**Issue by p12y** [fullcalendar/fullcalendar#4877]
Hey guys, first of all, thanks for the great calendar! It appears that the only way to activate the vertical resource view is by specifying resources. It would be great if this functionality could be toggled on/off by calling a function. Perhaps something like:

`$('#calendar').fullCalendar( 'toggleVerticalResourceView', 'off')` 

Sorry if something like this is already possible. I couldn't find anything by searching. Any ideas on how to solve this with a quick hack?

**Comment by dakala** [comment]
@arshaw Here's a pen of the v4 of this with setOption() - it doesn't seem to work:

https://codepen.io/dakala/pen/ZEzLPZj

**Comment by arshaw** [comment]
hey @dakala , in v4, setting the `resources` option to false is no longer a thing. in v4, the calendar must specifically be configured to use a resource view (like `resourceTimeline`) or not (just `timeline`). Closing this issue because it no longer applies.

**Comment by ETSmukesh** [comment]
> hey @dakala , in v4, setting the `resources` option to false is no longer a thing. in v4, the calendar must specifically be configured to use a resource view (like `resourceTimeline`) or not (just `timeline`). Closing this issue because it no longer applies.
Hello,
So, how we can handle the same above in v4?
