### ISSUE TITLE
Adjust format of fc-time and arrow for multi-day and offscreen

### ISSUE THREAD

**Issue by harohl** [fullcalendar/fullcalendar#4883]
1. When schedules extend off screen to the left and the time is displayed, the arrow is displayed between the time and the title event.  In my opinion the arrow should be on the far left of the time and the title.
2. When schedules extend off screen to the far right there does not seem to be any arrow to suggest it extends beyond the viewable area.
3. When displaying start and possibly end time for multi-day schedules, the date should be displayed.  Otherwise the time is misleading.
My screen print below illustrates standard options for a stacking (i.e. full day slots) timeline with options to show the start and end time.  It has examples of fullcalendar/fullcalendar-scheduler#1 and fullcalendar/fullcalendar-scheduler#3.
![9day-title](https://cloud.githubusercontent.com/assets/19411389/26316842/8aef04f8-3ee3-11e7-9a8d-7359387c8a1e.jpg)

**Comment by arshaw** [comment]
no longer an issue in v5: https://codepen.io/arshaw/pen/YzwQJbN?editors=0010
