### ISSUE TITLE
timeline business hours go out of alignment when container resized

### ISSUE THREAD

**Issue by PatrickRaab** [fullcalendar/fullcalendar#4884]
### Explanation
I created a 'timeline' custom view with the duration of 1 week to be displayed.
The businessHours has been added to spezific resources to display different ones for each resource.

**If i´m resizing the displayed week the workingHours background is moving "out of the day" it was rendered into.**

This Problem only exists for spezific businessHours in resources. 
When u are using "global" businessHours its working as expected.

### Reproducing the issue
- Resizing the width of "fc-scroller-canvas" (size of the displayed week)

### Spezific BusinessHours for each Resource (bug)
_reproduced Bug_
https://codepen.io/anon/pen/OggxPL?editors=0010

### Global BusinessHours
_how it should be for the spezific businessHours as well_
https://codepen.io/anon/pen/yXXzXo?editors=0010

**Comment by arshaw** [comment]
any way we could get a repro for v4?

**Comment by acerix** [comment]
This is fixed in v4:

https://codepen.io/acerix/pen/WVMxob?editors=0010
