### ISSUE TITLE
vertical scrolling of timeline view sometimes not in sync

### ISSUE THREAD

**Issue by VietQLe** [fullcalendar/fullcalendar#4889]
There's a strange behavior in regards to vertical scrolling of scheduler when on tablet, where columns aren't scrolling in sync.

Able to reproduce with ipad 3 from basic Schedule Template provided on https://fullcalendar.io/playground/codepen.php?demo=scheduler/

To reproduce, scroll all the way down with leftside 'Rooms' column, then scroll back up with rightside 'Times' column.  Issue is that right side will scroll up, but the left side will not scroll

**Comment by arshaw** [comment]
this is fixed [in the latest v5-beta](https://fullcalendar.io/blog/2020/04/new-ui-features-beta), though I can't exactly know all your recreation steps. could someone try to repro this in v5?

**Comment by arshaw** [comment]
v5 has been officially released: https://fullcalendar.io/blog/2020/06/v5-official
