### ISSUE TITLE
Scheduler dragScroll vertically is really slow and flickers

### ISSUE THREAD

**Issue by evanjmg** [fullcalendar/fullcalendar#4891]
### Bug Reports
See -> https://fullcalendar.io/scheduler/
Drag an event vertically down outside of the scroll view and it takes seconds for the scroll to respond and it flickers as it's doing it. 

Chrome 60.0.3 - Macbook Pro Retina i7 16gb of ram - 15inch mid 2015

**Comment by arshaw** [comment]
this has almost definitely been fixed since this ticket was created
