### ISSUE TITLE
timeline event drag/resize when on second line, pops to top

### ISSUE THREAD

**Issue by arshaw** [fullcalendar/fullcalendar#4893]
When dragging an event that is not the topmost event in the row, the semi-clear helper event gets pulled to the top of the row while dragging. Would expect it to maintain the same y coordinate when being dragged.

![timeline-event-dragging](https://user-images.githubusercontent.com/56520/31193611-9d201aa6-a912-11e7-83cd-bfa78f90fed7.gif)

**Comment by easededge** [comment]
Is there a workaround for the time being?

**Comment by arshaw** [comment]
this is fixed [in the latest v5-beta](https://fullcalendar.io/blog/2020/04/new-ui-features-beta)

**Comment by arshaw** [comment]
this has been fixed in v5 ([just released](https://fullcalendar.io/blog/2020/06/v5-official))
