### ISSUE TITLE
all bg events shown on first resource

### ISSUE THREAD

**Issue by AssassinLV** [fullcalendar/fullcalendar#4894]
When updating the Full Calendar and Scheduler to the newest versions - I found that all the background events were shown on first resource.

After deeper investigation I found that all background events (availability) were with Id "0" as Zero is default value of "long" type - and for background events we in project usually don't care about background event id - so it was not set.

result was like this:
https://codepen.io/anon/pen/YrRJgr?editors=0010

Note: I did fixed the code by changing from "long" to "long?" (nullable long).

**Comment by arshaw** [comment]
i wonder if this is still happening in v4

**Comment by AssassinLV** [comment]
Don't know. We had not updated it to v4...

**Comment by acerix** [comment]
In v4, `id` is unique for each event and was replaced by `groupId`. This updated demo shows it's now fixed: 

https://codepen.io/acerix/pen/bXMpJj?editors=0010

**Comment by AssassinLV** [comment]
@acerix, actually it would still happen if the id is default int/long value of "0" :)

Also this change is a breaking change for us - as our work-around was to set the id as "null" - in which case BG events (availability) is not visible at all....

**Comment by acerix** [comment]
Could you post a demo of what you mean? I don't see any issue with `id=0` or `groupId=0`, even though `id` should be unique and `groupId` should be a string.

https://codepen.io/acerix/pen/bXMpJj?editors=0010

**Comment by AssassinLV** [comment]
Ahh... never mind - seems to be code-pen bug - because if I changed any id to null and then to 0 they stoped rendering until I zoomed in/out... So never mind.. :)
