### ISSUE TITLE
Resize resource column width on Firefox 55

### ISSUE THREAD

**Issue by barthou-12** [fullcalendar/fullcalendar#4895]
Hi,

First of all, thank you for your work !
I noticed a bug on fullcalendar-scheduler-1.8.0 with Firefox 55.0.2  on Linux.

Go on demo page https://fullcalendar.io/js/fullcalendar-scheduler-1.8.0/demos/columns.html
Try to resize Room column width : It's impossible to reduce it.

Thanks,

**Comment by acerix** [comment]
I don't have any issue resizing in Firefox 68 in the original demo, and the updated v4 demo also works fine, so this seems to be fixed.

https://fullcalendar.io/docs/timeline-standard-view-demo
