### ISSUE TITLE
Background Event Not Resizable: Bug in Code or Missing in Docs?

### ISSUE THREAD

**Issue by queejie** [fullcalendar/fullcalendar#4902]
CodePen: https://codepen.io/davidquinnjacobs/pen/MraPvd

Background events cannot be resized or moved by dragging.  There is nothing in the documentation that indicates that background events are fixed and immutable, as far as I can tell.  Is this the way they were meant to be, or is this a bug, and they should be modifiable as regular events are?  (It would be ideal if they were.)

**Comment by arshaw** [comment]
we need to update the docs to state that background events are never resizable

**Comment by arshaw** [comment]
docs clarified. fix is live
