### ISSUE TITLE
Calling refetchResources before events have been loaded throws an error in v1.8.1+ with groupByResource enabled

### ISSUE THREAD

**Issue by caseyjhol** [fullcalendar/fullcalendar#4903]
FC v3.5.1/v1.7.1 (works)
https://codepen.io/caseyjhol/pen/YYwowr

FC v3.6.2/v1.8.1 (doesn't work)
https://codepen.io/caseyjhol/pen/vpLqNW

FC v3.8.0/v1.9.1 (doesn't work)
https://codepen.io/caseyjhol/pen/GyobZd

Throws the error `Cannot read property 'renderUnzonedRange' of null` because `this.dateProfile` has not yet been set. A workaround is to check to see if events are loaded before calling refetchResources, but it's an extra step that wasn't necessary previously.

**Comment by arshaw** [comment]
i wonder if this is still the case in v4

**Comment by acerix** [comment]
`refetchResources` needs to be called on an instance of the calendar, so it can't be called until after the calendar is initialized now, which means it will not work from the events function as in the original demo.

I made a new demo with v4 that adds a delay to call `refetchResources` before the events are loaded and there is no error so it seems fixed now:

https://codepen.io/acerix/pen/ymvaxx?editors=0010

**Comment by caseyjhol** [comment]
For what it's worth (in case anybody else comes across this issue), this appears to have been resolved in FC v3.10.0 (#3689).
