### ISSUE TITLE
dropInfo.resourceId in eventAllow() has the incorrect resource when dragging an event with multiple resources and having a resource which is not allowed to be dropped on

### ISSUE THREAD

**Issue by acerix** [fullcalendar/fullcalendar#4907]
Moved from https://github.com/fullcalendar/fullcalendar/issues/4036

https://codepen.io/acerix/pen/QQwrde?editors=0011

Dragging event 1 from resource A over resource C should show "resourceId c" in the console and allow dropping.

Instead, it shows "resourceId b" and doesn't allow dropping.

Dragging the event from resource B works as expected, as does dragging event 2 which has only one resource.

**Comment by arshaw** [comment]
i wonder if this is still the case in v4
