### ISSUE TITLE
BusinessHours in timelineMonth does not behave the same way as timeGridMonth

### ISSUE THREAD

**Issue by h0ndo** [fullcalendar/fullcalendar#4908]
My Example shows a timelineMonthView that has one resource with monday as available day (dow: [1])
Additional i added a monthView that has same businessHours for monday. And the result looks not same. The resource speficic businesshours ar treated somehow different.

https://codepen.io/anon/pen/eVNgGX?editors=0010

![image](https://user-images.githubusercontent.com/10778053/35624782-4b8c440e-0690-11e8-8f71-be33d0412500.png)

![image](https://user-images.githubusercontent.com/10778053/35624826-6e61f654-0690-11e8-89c4-6ba1c7fb3fd5.png)

**Comment by arshaw** [comment]
this seems fixed in v5: https://codepen.io/arshaw/pen/wvMeRjK?editors=0010
