### ISSUE TITLE
styling issue with resource grouping and bootstrap theme

### ISSUE THREAD

**Issue by rayden84** [fullcalendar/fullcalendar#4909]
I don't know wether this is a bug or an intentional styling, but if you use fullcalendar-scheduler with the bootstrap3 theme (option -> themeSystem: 'bootstrap3') together with resource grouping, then the row used as resources divider inside the timeline area is displayed with the slots, as shown here:

https://codepen.io/anon/pen/VQvwGa

This does not happen when using the default theme. A quick workaround can be found in the CSS section of the code pen (actually commented out)

**Comment by arshaw** [comment]
this is almost definitely not an issue anymore with v5
