### ISSUE TITLE
columnHeaderHtml does not work on scheduler

### ISSUE THREAD

**Issue by pgiani** [fullcalendar/fullcalendar#4911]
The columnHeader customization does not work if you are using the scheduler plugin, pretty easy to verify, it should say **Friday**! on the image below, works fine with out the pluging

![columnheaderhtml on scheduler - google chrome 2018-03-29 15 37 15](https://user-images.githubusercontent.com/5713173/38114889-4e31f60a-3367-11e8-8ccd-78284f00a4d8.png)

https://codepen.io/JustinRLeonard/pen/PRRqpB?&editors=001

**Comment by arshaw** [comment]
these slot render hooks are now available!
https://fullcalendar.io/docs/slot-render-hooks
