### ISSUE TITLE
Timeline - Prevent squeezing above 41 days duration

### ISSUE THREAD

**Issue by monsterdream** [fullcalendar/fullcalendar#4912]
Hi,
I don't know if it's a bug but I assume that is not, if not, please guide me how I could avoid this behaviour, so far it seems that nobody asked about this before. I would like to prevent of squeezing slot label above duration days 41.

Please take a look at link below.
https://codepen.io/anon/pen/jzpYgw?&editors=001

I discovered that if I will put duration{days: 41 }, everything seems like it should, like here:
![Image](https://cl.ly/1Y3937221H0w/Image%202018-04-04%20at%201.34.29%20AM.png)

But from 42 it will squeeze everything and I would like to prevent this, it is possible?
![Image](https://cl.ly/352S2a2F3m2g/Image%202018-04-04%20at%201.33.50%20AM.png)

**Comment by arshaw** [comment]
this is almost definitely fixed in v5
