### ISSUE TITLE
Events (as function) receiving outdated start/end dates on view switch

### ISSUE THREAD

**Issue by kdenzel** [fullcalendar/fullcalendar#4914]
I know this issue was already confirmed from my other account but because of trolling it is now flagged, so i do it again with my real account.

See jsbin. Open the output window to see the description

https://jsbin.com/jipozedohu/1/edit?html,output

Problem is: If you load the year view, then switch back to the month view and manually reload the events for the monthview, the parameters 'start' and 'end'-momentObjects are still in the 'year'-mode and starts from YYYY-1-1 til YYYY-12-31 instead of 1st of month til end of month.

**Comment by arshaw** [comment]
im wondering if this is still the case in v4

**Comment by arshaw** [comment]
related to https://github.com/fullcalendar/fullcalendar/issues/3892
