### ISSUE TITLE
Timeline print view that scales to fit the page

### ISSUE THREAD

**Issue by farhanfaiz** [fullcalendar/fullcalendar#4915]
Details are specified in the post @ https://stackoverflow.com/questions/50922359/fullcalendar-scheduler-print-truncating-timeline

along with code

BTY, great work.

**Comment by arshaw** [comment]
v5, which as [just been released](https://fullcalendar.io/blog/2020/06/v5-official), will handle this much more gracefully. please check it out and if there are still problems, please open a new ticket
