### ISSUE TITLE
resourceRender can't access all-day tds / cells in timeGridDay

### ISSUE THREAD

**Issue by jwillinghalpern** [fullcalendar/fullcalendar#4916]
When resourceRender fires for agendaDay view, the bodyTds param is empty as expected. However I hoped that we could manually select the relevant DOM elements within the callback function like: `resourceRender: function(resource, labelTds, bodyTds){
	$tds = $("td").find(`[data-resource-id=${resource.id}]`);
	/* Do something to $tds */
}`

But this does not select the all-day row, which seems like odd behavior considering those cells do end up having the data-resource-id attribute when the calendar is fully rendered.

[JSFiddle](https://jsfiddle.net/0sergv3y/46/)

It seems like those should be available when resourceRender runs. If I run the same select statement in the console after the calendar loads, it selects the all-day cells too as expected.

**Comment by arshaw** [comment]
in v5, this should be possible with the day-cell render hooks:
https://fullcalendar.io/docs/day-cell-render-hooks

You'll have access the resource in any of those hooks
