### ISSUE TITLE
Drop events back to backlog from calendar

### ISSUE THREAD

**Issue by pizzadev** [fullcalendar/fullcalendar#4917]
Hi,
I think it would be nice to have feature of drag'n'drop event from calendar back to backlog.

For now I am using this workaround. Will you add this behavior to the next release?

**Comment by arshaw** [comment]
would be solved by this when it's implemented:
https://github.com/fullcalendar/fullcalendar/issues/3140
&uarr;
Could you please visit the link, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates?
