### ISSUE TITLE
Drag and drop resources scheduler

### ISSUE THREAD

**Issue by Eye-t** [fullcalendar/fullcalendar#4921]
Is there any possibility to drag and drop the resources in the scheduler?
This could be very handy if you want a custom sorting.

**Comment by arshaw** [comment]
i believe this request is captured in an earlier ticket: https://github.com/fullcalendar/fullcalendar/issues/3596

**Comment by arshaw** [comment]
&uarr;
Could you please visit the link, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates?

**Comment by CraftyDlx** [comment]
https://github.com/fullcalendar/fullcalendar/issues/3596 is about merging resources, not sorting them. This is about a drag and drop function in the scheduler for sorting resources. For instance, you drag the top first resource and drop it below the 3rd resource. All the events belonging to the first resource are also dropped with it.
