### ISSUE TITLE
Event is not the correct size in timeline view with slotDuration of 1 month and snapDuration of 1 day

### ISSUE THREAD

**Issue by acerix** [fullcalendar/fullcalendar#4922]
Reported in https://fullcalendar.freshdesk.com/a/tickets/519

https://codepen.io/anon/pen/pxameY?editors=0010

The event is a year long but shows up as less than one month.

**Comment by arshaw** [comment]
fixed in v5: https://codepen.io/arshaw/pen/XWXaKGK?editable=true&editors=001

tho there's a new bug where scrollbars unnecessarily show up when navigation. i'll file that separately
