### ISSUE TITLE
Line break in resource title causes events to render in the wrong resource

### ISSUE THREAD

**Issue by ajaxsys** [fullcalendar/fullcalendar#4924]
### Bug Reports

https://jsfiddle.net/tu067o5y/

Hi,

With long resource label that more then one line,
resources and events alignments are broken.

(Browser: Chrome, Scheduler 1.9.4, FullCalendar 3.9.0)

Regards

**Comment by techouse** [comment]
I have the same issue with `v4.3.0`. When the label is too long to fit in one line it gets all misaligned and quite confusing to read.

**Comment by techouse** [comment]
It seems it was a CSS issue. Once I included all the required CSS modules it works :)

**Comment by ajmueller** [comment]
I'm seeing a similar issue with v4.3.0 as well where the resource and its associated event heights are not being properly calculated on page load.  Interestingly enough they are recalculated correctly on window resize.

In my case, I'm trying to render JSX, specifically from the Material UI project, inside of a resource to provide checkbox controls for selecting resources.  [A full example can be seen on CodeSandbox](https://codesandbox.io/s/fullcalendar-rendering-material-ui-jsx-y2yly).

@techouse you mentioned that requiring the CSS modules fixed the issue for you, but I believe I'm including all of the necessary CSS (core/main.css, resource-timeline/main.css, and timeline/main.css).  The issue I'm seeing is related to the inline height applied to a div that wraps the `.fc-cell-content` div:

```html
<td class="fc-widget-content" rowspan="1">
    <div style="height: 33px;"><!-- this is the problem div -->
        <div class="fc-cell-content">
...
```

**Comment by arshaw** [comment]
this is fixed in v5
