### ISSUE TITLE
Event titles flow outside of element and overlaps with other events in timeline month view when event includes a start time

### ISSUE THREAD

**Issue by acerix** [fullcalendar/fullcalendar#4928]
The title of the April 4 event overlaps the April 5 event:

https://codepen.io/acerix/pen/MRQZmE?editors=0010

Reported in https://fullcalendar.freshdesk.com/a/tickets/808

**Comment by arshaw** [comment]
This was fixed in 4.3.0 though please start using 4.3.1
Releases: https://github.com/fullcalendar/fullcalendar/releases

@acerix could you please notify the creator of the original ticket in freshdesk?
