### ISSUE TITLE
Method to change the first day in the timeline view with a custom duration of a few days

### ISSUE THREAD

**Issue by acerix** [fullcalendar/fullcalendar#4929]
Request for a method to change the first day in multi-day timeline view.

`gotoDate` achieves that when the day is not already visible, but when the day is already somewhere in the view, `gotoDate` does not change it to the first day.  As a workaround, `gotoDate` can first be called with a date outside the view (eg. 1970-01-01) then back to the date which makes it the first day of the week. 

Desired effect can be seen by increment the date in this demo. 

https://codepen.io/acerix/pen/eoPmOx?editors=0010

Reported in https://fullcalendar.freshdesk.com/a/tickets/818

**Comment by animator013** [comment]
Same issue here.

**Comment by arshaw** [comment]
fix is released in [v5.8.0](https://github.com/fullcalendar/fullcalendar/releases/tag/v5.8.0)

updated repro:
https://codepen.io/arshaw/pen/dyvwExy?editors=0010
