### ISSUE TITLE
eventStartEditable false is not compatible with eventResourceEditable true

### ISSUE THREAD

**Issue by Cirivas** [fullcalendar/fullcalendar#4930]
## Description

In vertical resource view v4.1.0, when is set `eventStartEditable: false`, and `eventResourceEditable: true`, you can no longer drag events and drop to other resources. Even if `editable: true` you still cant drag n drop them.

## CodePen to reproduce

https://codepen.io/cirivas/pen/KYrgRG

## Expected behaviour

I should be able to switch resource, but not the start of the event.

**Comment by arshaw** [comment]
This was fixed in 4.3.0 though please start using 4.3.1
Releases: https://github.com/fullcalendar/fullcalendar/releases
