### ISSUE TITLE
draggedEvent start time is `null` in eventAllow when event is dragged to another resource

### ISSUE THREAD

**Issue by acerix** [fullcalendar/fullcalendar#4932]
Came across this in my workaround for https://github.com/fullcalendar/fullcalendar-scheduler/issues/533

https://codepen.io/acerix/pen/pBqPNY?editors=0010

It works when dragging the event within the resource but gives an error when dragging to a different one.

**Comment by arshaw** [comment]
This was fixed in 4.3.0 though please start using 4.3.1
Releases: https://github.com/fullcalendar/fullcalendar/releases
