### ISSUE TITLE
scrollToTime does not work in timeline view when duration is an object

### ISSUE THREAD

**Issue by gmw-web** [fullcalendar/fullcalendar#4935]
FullCalendar has a `scrollToTime` method which has a `duration object` as input.

According to the docs, the `duration object` can be specified in three different ways, namely as...
- an object (with keys 'year', 'month', 'day', etc.)
- a string in the format `hh:mm:ss.sss`, `hh:mm:sss` or `hh:mm`
- a total number of milliseconds (since unix epoch?)

Unfortunately, for the timeline view, the first and last option (when they include the date) do not scroll to the correct date.

See the following codepen (relevant function call at the bottom):
https://codepen.io/anon/pen/MdbXja?editors=0010

**Comment by arshaw** [comment]
This was fixed in 4.3.0 though please start using 4.3.1
Releases: https://github.com/fullcalendar/fullcalendar/releases

scrollToTime now honors a full duration

**Comment by fwd079** [comment]
Seems to be broken again, seems to scroll to _correct_ time, but on first day shown in Calendar. e.g. I added `Wed Jun 10 2020 09:00:00 GMT+0100` as value but it seems to scroll to `Mon Jun 6 2020 09:00:00 GMT+0100` instead.
Kind Regards.

**Comment by arshaw** [comment]
@fwd079, would you be able to post **NEW issue** with a [runnable, stripped-down demonstration of the bug](https://fullcalendar.io/reduced-test-cases)? Would really appreciate it because the time saved reproducing will be time spent fixing. I'm closing this issue until then.

**Comment by johnbaro** [comment]
Reopening this with a demo (see the `scroll to now` button on the sidebar)
https://codesandbox.io/s/pensive-river-i4wdxk

Source is [here](https://github.com/johnbaro/fullcalendar-example-projects/tree/jb-dev/angular)

Relevant [code](https://github.com/johnbaro/fullcalendar-example-projects/blob/jb-dev/angular/src/app/app.component.ts#L98) if someone wants to point out a glaring issue as I'm sure it's me :)

```ts
  scrollToNow() {
    ////////////////////////////////////////////////////////////////////////
    // Just time
    ////////////////////////////////////////////////////////////////////////
    //const time = LocalDateTime.now().format(DateTimeFormatter.ofPattern("HH:mm:ss"));

    ////////////////////////////////////////////////////////////////////////
    // ISO 8601
    ////////////////////////////////////////////////////////////////////////
    const time = ZonedDateTime.now().withFixedOffsetZone().toString();

    ////////////////////////////////////////////////////////////////////////
    // Object
    ////////////////////////////////////////////////////////////////////////
    //    const now = ZonedDateTime.now();
    //    const time = {
    //      year: now.year(),
    //      month: now.monthValue(),
    //      day: now.dayOfMonth(),
    //      hour: now.hour(),
    //      minute: now.minute(),
    //      second: now.second()
    //    };

    console.debug("Scroll to time", { time });
    this.calendar.scrollToTime(time);
  }
```

**Comment by johnbaro** [comment]
Well, that didn't reopen this :)
For future selves, this is fixed, link [here](https://codesandbox.io/s/twilight-currying-uyqstk).
