### ISSUE TITLE
[v3] Multi-day events do not render correctly with minTime in multi-day timeline view

### ISSUE THREAD

**Issue by ZadravecMarko** [fullcalendar/fullcalendar#4942]
When set the value `MinTime`, the class of the events are calculated wrongly.
For example, if MinTime is 6.00 then, all Events before 6 has class fc-not-start although whole Events is visible.

Example [here](https://jsfiddle.net/Ly9rsoc1/2/)

The 2 events on Friday 7/13 has < sign witch shouldn't be the case...

**Comment by arshaw** [comment]
i think you best bet is to write custom CSS to remove the arrows on the beginning/ends of the event elements
