### ISSUE TITLE
JSON parsing failure callback call even on valid JSON

### ISSUE THREAD

**Issue by cedric-anne** [fullcalendar/fullcalendar#4952]
When fetching events, if xhr succeed but `successCallback` triggers an error, this error will be catched and `failureCallback` will be called.
In this case, a "Failure parsing JSON" warning will be shown console, misleading user. Furthermore, as initial error is catched, root cause of failure is hard to identify.

Example: https://codepen.io/anon/pen/MNoVqd?editors=1111

I think in this case, initial error should not be catched, in order to make it displayed in browser console.

**Comment by adipasquale** [comment]
Thanks for posting @cedric-anne I just encountered this problem and lost some time trying to figure out what was wrong with my JS

**Comment by arshaw** [comment]
things should be fixed in v5, which was [just released](https://fullcalendar.io/blog/2020/06/v5-official)

demo: https://codepen.io/arshaw/pen/RwrVWev?editable=true&editors=001
