### ISSUE TITLE
Adding a recurring event that repeats every week to the last day of timeGridWeek creates an event instance outside the visible range

### ISSUE THREAD

**Issue by NicoMarech** [fullcalendar/fullcalendar#4954]
This is a copy of the post on stackoverflow : 

I am implementing a calendar for my new website I retrieve events from a BackEnd application and show result in a modal using fullcalendar. I also use recurring feature from fullcalendar (https://fullcalendar.io/docs/recurring-events) to facilitate the use of my calendar.

Here something strange happened, When the user creates a recurring event on Sunday it is created twice with different dates whereas it works like a charm on the other days.

I made a JSfiddle : https://jsfiddle.net/Marech/0fdr5vq3/37/ Please create a event on any day (except sunday) by selecting on the calendar and check console to see the created events. Then create an event on Sunday and check again, the event is created twice. 

Do you have any idea on how to fix this problem ? Do I use the fullcalendar API in a correct way ??? 

It appears that if I change the firstDay parameter, the problem has moved to the last day of the grid. As ADyson mentionned into commentary.

**Comment by nigamabhay671** [comment]
Hello NicoMarech,
You have to declare events array as null from where yours events are got copied.
Just Like this

var events[];

**Comment by NicoMarech** [comment]
Well, could you be more specific ?
Where to declare this array ?
In my case, events are created with select option, not from an event source or an event array...
Could you update JSFiddle to explain your purpose ?
Here is an updated link : https://jsfiddle.net/jzq6748u/

**Comment by acerix** [comment]
Thanks for the report.  I made a simplified test in the debug template to test it:

https://codepen.io/acerix/pen/zgEqQj?editors=001

I can see that adding a recurring event that repeats every week to the last day of the timeGridWeek view causes a second instance of the event to also be created in memory exactly one week before, even though that day is not visible, so that seems like a bug.  

As a workaround, you could save a copy of all the events in an array when they are added and use that array instead of `getEvents()`.

**Comment by NicoMarech** [comment]
Thank you, 

I will work with the workaround for now and wait for the patch  !

**Comment by arshaw** [comment]
when you create an event with `daysOfWeek`, that creates a recurring event

**Comment by AravindTReddy** [comment]
Is it possible to have an recurring event that repeats on a specific day for every 2 weeks ? If possible please guide me here. Thanks
