### ISSUE TITLE
In fullcalendar year view date are behind by one day.

### ISSUE THREAD

**Issue by vijayvargiyaakshay** [fullcalendar/fullcalendar#4956]
Hello fullcalendar team, fullcalendar is an awesome plugin to implement and very good to use. But there is no option for year view after v2. I also implement a year view using the v2 version. Problem with this view is my all date is behind by one day, like 08-02-2019 is on Friday but in year view it is on Saturday. Although everything is correct in all rest of the views (month, day, week).
![Screenshot from 2019-08-02 09-17-54](https://user-images.githubusercontent.com/51439770/62343036-c4efec80-b506-11e9-85b9-cf873c207716.png)

**Comment by acerix** [comment]
There is an open request for a view like that:
https://github.com/fullcalendar/fullcalendar/issues/1140
↑
Please visit the above issue, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates.

If you are reporting a but, please post a [runnable, stripped-down demonstration of the bug](http://fullcalendar.io/wiki/Reduced-Test-Cases/).

**Comment by vijayvargiyaakshay** [comment]
hey, @acerix I have implement year view but there is a bug in fullcalendar. Every day is behind by one day. Please see the attachment.

**Comment by acerix** [comment]
Please provide a runnable demo so we can reproduct the issue.
