### ISSUE TITLE
npm run build fails on fresh install

### ISSUE THREAD

**Issue by Invincibear** [fullcalendar/fullcalendar#4957]
### Bug Report

On a CentOS7 server, I performed the following steps [per instructions here](https://github.com/fullcalendar/fullcalendar/blob/master/CONTRIBUTING.md):
```
cd ~/httpdocs
git clone git://github.com/fullcalendar/fullcalendar.git
cd fullcalendar
sudo npm install -g sass yarn gulp
npm install
```
`npm run build` & `npm run watch` output the following errors:

[redacted successful output up until this point]
> [rollup] created packages/core/dist/locales-all.js in 71ms
> [rollup]
> [rollup] tmp/tsc-output/packages?(-premium)/__tests__/src/globals.js, tmp/tsc-output/packages?(-premium)/__tests__/src/**/*.js → tmp/tests.js...
> [rollup] **[!] Error: 'config' is not exported by ../../node_modules/@fullcalendar/core/main.js**
> [rollup] https://rollupjs.org/guide/en#error-name-is-not-exported-by-module-
> [rollup] tmp/tsc-output/packages/__tests__/src/hacks.js (1:9)
> [rollup] 1: import { config } from '@fullcalendar/core';
> [rollup]             ^
> [rollup] 2: beforeEach(function () {
> [rollup] 3:     // On real devices, when a click-like touch interaction happens, there is a preiod of time where mouse events
> [rollup] Error: 'config' is not exported by ../../node_modules/@fullcalendar/core/main.js
> [rollup]     at error (/var/www/vhosts/warmapcalendar.com/httpdocs/fullcalendar/node_modules/rollup/dist/rollup.js:3598:30)
> [rollup]     at Module.error (/var/www/vhosts/warmapcalendar.com/httpdocs/fullcalendar/node_modules/rollup/dist/rollup.js:14470:9)
> [rollup]     at handleMissingExport (/var/www/vhosts/warmapcalendar.com/httpdocs/fullcalendar/node_modules/rollup/dist/rollup.js:14397:21)
> [rollup]     at Module.traceVariable (/var/www/vhosts/warmapcalendar.com/httpdocs/fullcalendar/node_modules/rollup/dist/rollup.js:14739:17)
> [rollup]     at ModuleScope.findVariable (/var/www/vhosts/warmapcalendar.com/httpdocs/fullcalendar/node_modules/rollup/dist/rollup.js:13408:37)
> [rollup]     at FunctionScope.ChildScope.findVariable (/var/www/vhosts/warmapcalendar.com/httpdocs/fullcalendar/node_modules/rollup/dist/rollup.js:4245:67)
> [rollup]     at ChildScope.findVariable (/var/www/vhosts/warmapcalendar.com/httpdocs/fullcalendar/node_modules/rollup/dist/rollup.js:4245:67)
> [rollup]     at MemberExpression.bind (/var/www/vhosts/warmapcalendar.com/httpdocs/fullcalendar/node_modules/rollup/dist/rollup.js:12369:47)
> [rollup]     at AssignmentExpression.NodeBase.bind (/var/www/vhosts/warmapcalendar.com/httpdocs/fullcalendar/node_modules/rollup/dist/rollup.js:10239:23)
> [rollup]     at AssignmentExpression.bind (/var/www/vhosts/warmapcalendar.com/httpdocs/fullcalendar/node_modules/rollup/dist/rollup.js:11001:31)
> [rollup]
> [rollup] npm ERR! code ELIFECYCLE
> [rollup] npm ERR! errno 1
> [rollup] npm ERR! fullcalendar@4.2.2 rollup: `rollup -c --environment BUILD:production`
> [rollup] npm ERR! Exit status 1
> [rollup] npm ERR!
> npm ERR! Failed at the fullcalendar@4.2.2 rollup script.
> [rollup] npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
> [rollup]
> [rollup] npm ERR! A complete log of this run can be found in:
> [rollup] npm ERR!     /var/www/vhosts/warmapcalendar.com/.npm/_logs/2019-08-02T04_04_41_756Z-debug.log
> [rollup] npm run rollup exited with code 1
> [21:04:41] 'npm:rollup' errored after 8 s
> [21:04:41] Error
>     at SwitchMapSubscriber.project (/var/www/vhosts/warmapcalendar.com/httpdocs/fullcalendar/node_modules/concurrently/src/completion-listener.js:31:33)
>     at SwitchMapSubscriber._next (/var/www/vhosts/warmapcalendar.com/httpdocs/fullcalendar/node_modules/rxjs/internal/operators/switchMap.js:49:27)
>     at SwitchMapSubscriber.Subscriber.next (/var/www/vhosts/warmapcalendar.com/httpdocs/fullcalendar/node_modules/rxjs/internal/Subscriber.js:66:18)
>     at MapSubscriber._next (/var/www/vhosts/warmapcalendar.com/httpdocs/fullcalendar/node_modules/rxjs/internal/operators/map.js:55:26)
>     at MapSubscriber.Subscriber.next (/var/www/vhosts/warmapcalendar.com/httpdocs/fullcalendar/node_modules/rxjs/internal/Subscriber.js:66:18)
>     at BufferCountSubscriber._next (/var/www/vhosts/warmapcalendar.com/httpdocs/fullcalendar/node_modules/rxjs/internal/operators/bufferCount.js:52:30)
>     at BufferCountSubscriber.Subscriber.next (/var/www/vhosts/warmapcalendar.com/httpdocs/fullcalendar/node_modules/rxjs/internal/Subscriber.js:66:18)
>     at MapSubscriber._next (/var/www/vhosts/warmapcalendar.com/httpdocs/fullcalendar/node_modules/rxjs/internal/operators/map.js:55:26)
>     at MapSubscriber.Subscriber.next (/var/www/vhosts/warmapcalendar.com/httpdocs/fullcalendar/node_modules/rxjs/internal/Subscriber.js:66:18)
>     at Subject.next (/var/www/vhosts/warmapcalendar.com/httpdocs/fullcalendar/node_modules/rxjs/internal/Subject.js:60:25)
> [21:04:41] 'build' errored after 15 s
> npm ERR! code ELIFECYCLE
> npm ERR! errno 1
> npm ERR! fullcalendar@4.2.2 build: `gulp build`
> npm ERR! Exit status 1
> npm ERR!
> npm ERR! Failed at the fullcalendar@4.2.2 build script.
> npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

It also looks like @fullcalendar doesn't exist in node_modules
```
-sh-4.2$ ls node_modules/@
ls: cannot access node_modules/@: No such file or directory
-sh-4.2$ ls node_modules/@*
node_modules/@arshaw:
dts-bundle  monorepo-tool

node_modules/@babel:
code-frame  highlight

node_modules/@types:
detect-indent  estree  glob  jasmine  jasmine-jquery  jquery  luxon  minimatch  mkdirp  node  sizzle
-sh-4.2$ ls node_modules/|grep calendar
-sh-4.2$
```

Are the instructions on the site missing a step? Or did I take a wrong turn somewhere?

**Comment by acerix** [comment]
Those are the instructions to build the calendar itself from source which is why it doesn't include fullcalendar as dependency.

To include it as a dependency in a new project you should use these instructions:

https://fullcalendar.io/docs/initialize-es6

**Comment by Invincibear** [comment]
Yes, I am intentionally trying to build from source, not include FC as a dependency in a new project.

**Comment by acerix** [comment]
It builds for me following those instructions, so it could be that you have an old version of some tools, you might need to clear npm's cache.

**Comment by Invincibear** [comment]
Yep, something is buggered on this multi-tenant hosting server. `npm cache clear --force` didn't help.

I just setup a new VPS and ran the following sequence of commands and FC built successfully.
```
# yum install -y epel-release nano
# yum update && systemctl reboot
# yum install -y git gcc-c++ make
# systemctl enable httpd && systemctl start httpd
# firewall-cmd --add-service=http --add-service=https --permanent && firewall-cmd --reload
# curl -sL https://rpm.nodesource.com/setup_10.x | sudo -E bash -
# yum install -y node.js
# node -v
v10.16.2
# npm -v
6.9.0
# npm install -g sass
# cd /var/www/html
# git clone git://github.com/fullcalendar/fullcalendar.git
# cd fullcalendar
# npm install
# npm run build
```

The big difference is that this was using node.js v10 instead of what my web server is using (v12). So I removed v10 and installed v12 and it still built without issue. I'll troubleshoot my server some more and post findings here so that it hopefully may help someone else.

**Comment by Invincibear** [comment]
The thing I can't figure out, is on my production domain in /fullcalendar I can build FC v4.0.x. But if I `mkdir /fctest`, `git clone`, `npm install`, `npm run build` it fails to build v4.2.0.

**Comment by Invincibear** [comment]
okay I got it working, FINALLY hahaha \*happy dance\*.
I listed installed NPM packages using `npm list --depth 0` and removed them with `npm uninstall PackageNameHere`. I then `mkdir fctest2`, `git clone`, `npm install`, `npm run build`
Globally, I did the same. `npm list -g --depth 0` then uninstalled all of them except npm & sass using `npm uninstall -g PackageNameHere`.

Seems to have done the trick.

**Comment by Invincibear** [comment]
Okay I think I found the root cause.
If you have webpack installed with @fullcalendar/* libraries installed, you can't also have a subfolder with source FC files to build. I think that happens is the FC source build operation looks to the NPM-installed @fullcalendar/* libraries which then fails the build operation.

**Comment by Invincibear** [comment]
I submitted pull request https://github.com/fullcalendar/fullcalendar/pull/4966 to warn others of this scenario.

**Comment by acerix** [comment]
Thanks for the suggestion but I don't think it should be finding libraries in subfolders, or parent folders like your PR mentions. What are the extra steps to create the folder that causes that error?

**Comment by Invincibear** [comment]
Here's the directory structure
```
/var/www/domain.tld/httpdocs/ (Apache serves documents from this folder)
/var/www/domain.tld/httpdocs/fullcalendar/ (full calendar source files)
/var/www/domain.tld/webpack.js (includes other files in this directory)
```
from /var/www/domain.tld/, I ran `npm install @fullcalendar/core` and used it as a dependency in webpack to initialize full calendar, like any other normal ES6 project as recommended on the FC website.

In /var/www/domain.tld/httpdocs/fullcalendar I had `git clone` the FC source code and was attempting to `npm run build` to build FC from source. Unfortunately it was detecting @fullcalendar/core in the parent folder which was preventing NPM from building FC from source.

Is NPM supposed to do that? I don't know, I don't have enough experience with it to know.

**Comment by acerix** [comment]
NPM should not find dependencies in other directories, I tried the same thing and it builds properly without finding `@fullcalendar/core` in the parent dir.  Maybe that can happen if `@fullcalendar/core` is installed globally or if your npm root is wrong, you can see that with `npm root`

**Comment by arshaw** [comment]
closing in favor if this newer issue:
https://github.com/fullcalendar/fullcalendar/issues/5504
&uarr;
Could you please visit the link, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates?
