### ISSUE TITLE
events start not work

### ISSUE THREAD

**Issue by empty-back** [fullcalendar/fullcalendar#4961]
### Bug Reports
get events array form ajax like that:
[
            {
                id: 'xxx',
                title: '111',
                start: '20190803',
                description: 'abc'
            }
]
array like that cannot render event in calendar
normal start format like '2019-08-03'
so ,not contain ‘-’ that start attribute how to work in calendar
### React/Vue/Angular/etc

(Please erase the above text and begin typing. Thanks!)

**Comment by acerix** [comment]
Would you be able to post a [runnable, stripped-down demonstration of the bug](http://fullcalendar.io/wiki/Reduced-Test-Cases/)? Would really appreciate it because the time saved reproducing will be time spent fixing.
