### ISSUE TITLE
Drag and drop events between 2 resourceTimelines

### ISSUE THREAD

**Issue by bartroodzant** [fullcalendar/fullcalendar#4962]
Hello,

In my application I have created 2 resourceTimelines and I want to drag events from the second resourceTimeline to the first resourceTimeline. This can be done with the callbacks eventReceive or drop, but I am running into a problem with these callbacks. When I use the eventReceive callback I only get the event which is being dropped and not the resource in which it is dropped as you can see in this picture.

![Screenshot 2019-08-09 at 09 51 56](https://user-images.githubusercontent.com/15012958/62763311-840a5180-ba8b-11e9-8470-01151ebd0adf.png)

And in the drop callback I only get the resource in which the event is being dropped and not the event itself or even the start and end times.

![Screenshot 2019-08-09 at 09 54 21](https://user-images.githubusercontent.com/15012958/62763374-ac924b80-ba8b-11e9-83bc-dce260a0bed1.png)

Here is a codepen with an example: https://codepen.io/BartFTW/pen/xvJroE. When you drag the event from the bottom resourceTimeline to the top resourceTimeline and open the browser console you can get see the objects of both functions.

When I drop an event into the receiving resourceTimeline I expect the info object to contain both the resource in which it is dropped and the event object which was dropped there. I don't know if this is a bug or maybe I am doing something wrong.

Any help would be appreciated!

**Comment by acerix** [comment]
You can get use `info.event.getResources()` to find which resource it was dropped on:

https://codepen.io/acerix/pen/dxgYvb?editors=0011

**Comment by bartroodzant** [comment]
Thank you very much for the fast reply! This works great.
