### ISSUE TITLE
dayClick doesnt work with Android (native or developer console on pc)

### ISSUE THREAD

**Issue by rebruCH** [fullcalendar/fullcalendar#4963]
Bug

The dayclick event isnt fired on android, it doesnt matter if its native or over the developer console in chrome.

Its reproducable on the demos itself on the fullcalendar.io site (selectable dates). I'm not able to fire the dayclick event with my phone/tablet or pc in developer console.

So in my mind, there is a basic problem in the library?

**Comment by rebruCH** [comment]
Afterburner

The element .fc-widget-content is the target, when i check over $('body').on('click',function(e) { console.log(e.target); }). So the click itself is not prevented by another element or script - it seems, that FC doesnt react to .fc-widget-content clicks when you are using mobile device or mobile device simulation ( chrome devcon )

**Comment by acerix** [comment]
This demo shows a popup for me when touch-clicking a time slot:

https://fullcalendar.io/docs/date-clicking-selecting-resource-demo

Do you mean nothing happens when you try that?

To select/drag, you need to hold touch for 1 second:

https://fullcalendar.io/docs/longPressDelay

**Comment by rebruCH** [comment]
Oh ok, i noticed that ...

But on my theme ( Metronic v5, FC 3.10, Jquery 3.4 ) it still doesnt work. Cant click, cant touch ... on events it works, but not on dayClick.

I'm short before to bite into my desk - cant figure out, which setting (css) or which script would be responsible for that behaviour. Spending the whole time until now to find out, what happens.

Try to figure out the differences but i find nothing thats different.

**Comment by acerix** [comment]
If the demo is working for you, try turning off all other CSS and JavaScript to find when is interfering.  If there is an issue in the calendar please provide a [runnable, stripped-down demonstration of the bug](http://fullcalendar.io/wiki/Reduced-Test-Cases/).
