### ISSUE TITLE
Event has Incorrect Stop Time

### ISSUE THREAD

**Issue by Seth10001** [fullcalendar/fullcalendar#4965]
I am using the `resourceTimeline` plugin and it's not recognizing when events are stopping. I have a table set up for 7 resources and I created a 15 minute event for a resource. It shows up as an hour long event event though the start/stop time is an hour long.

This is my event data:
```
events:[
{
              'id': '1',
              'resourceId': '1', 
               'start': new Date("2019-08-09 09:00:00"),
               'stop': new Date("2019-08-09 09:15:00")
}]
```

The resulting calendar looks like this:
![Screen Shot 2019-08-09 at 1 53 21 PM](https://user-images.githubusercontent.com/7267438/62798754-12db9600-baad-11e9-97e0-a01c830590ef.png)

No matter what I make the stop time of the event it makes it an hour long. I want to have 15 minute events

I created a jsfiddle with all the details: https://jsfiddle.net/qhL3rdm5/3/

**Comment by acerix** [comment]
The setting is `end` instead of `stop`.
