### ISSUE TITLE
schedulerLicenseKey doesn' work in 4.3.0

### ISSUE THREAD

**Issue by ex1st** [fullcalendar/fullcalendar#4967]
**Bug Report**

@fullcalendar/resource-common 4.3.0 (npm)

After the last update, our license key is no longer valid.
I've made an investigation and found: the RELEASE_DATE param was missed in the resource-common module. Can you make a correct release? 

Thank you!

**Comment by arshaw** [comment]
thank you, i will look into this ASAP

**Comment by the-it** [comment]
We encountered the same error in the version 3.10.1. ("fullcalendar": "3.10.1", "fullcalendar-scheduler": "1.10.0",)
