### ISSUE TITLE
datesRender not triggered when toggling between week and list views

### ISSUE THREAD

**Issue by bkriss** [fullcalendar/fullcalendar#4970]
Toggling between any of the view types (month, week, day, list) will trigger `datesRender`, as expected, but it doesn't work when you go from _week_ to _list_ or _list_ to _week_.

It's possible that this is intended behavior. If so, what is the best way for me to know when a user has changed from _week_ to _list_ or vice versa? I'd like to know which view type the user was last on so when they refresh the page, I can return them to that same view

Steps to recereate:
1: open codepen: https://codepen.io/bkriss/pen/VoEWLJ
2: Open developer tools so you can see console logs
3. Notice that toggling between _day_ and _week_ will log "timeGridDay" and "timeGridWeek" to the console, but going from _week_ to _list_ does not log anything to the console, as `datesRender` is not triggered in that scenario.

**Comment by acerix** [comment]
`datesRender` is called after a new set of dates is rendered and switching between listWeek and timeGridWeek doesn't change the dates.  You can use `viewSkeletonRender` to detect view changes:

https://fullcalendar.io/docs/viewSkeletonRender
