### ISSUE TITLE
TypeError: s.computeEventDraggable is not a function

### ISSUE THREAD

**Issue by trashdres** [fullcalendar/fullcalendar#4971]
Hi, this is the Error

Uncaught TypeError: s.computeEventDraggable is not a function
    at r.renderSegHtml (main.min.js:6)
    at r.e.renderSegEls (main.min.js:9)
    at r.e.renderSegs (main.min.js:9)
    at i [as renderFgEvents] (main.min.js:6)
    at i.render (main.min.js:6)
    at i.e.receiveProps (main.min.js:8)
    at r.render (main.min.js:6)
    at r.e.receiveProps (main.min.js:8)
    at i.render (main.min.js:6)
    at i.e.receiveProps (main.min.js:8)

I'm getting the events from a Json

My Code

var calendarEl = document.getElementById('CalendarioDiv');
var calendar = new FullCalendar.Calendar(calendarEl,{
	header:{
		left: 'prev,next today',
		center: 'title',
		right: 'dayGridMonth,timeGridWeek,timeGridDay'
	},
	defaultView: 'timeGridDay',
	locale: 'es',
	plugins: [ 'bootstrap', 'dayGrid', 'timeGrid' ],
	timeZone: 'America/Bogota',
	events: JSON.parse(localStorage.getItem("clases")),
	eventClick: function(info){
		DataTableActions("edit", info.event.id, "edit_clase", "request/clase.php");
	},
	eventRender: function(info){
		$(info.el).popover({
			container: "body",
			content: info.event.extendedProps.contenido,
			html: true,
			placement: 'top',
			template: "<div class='popover' role='tooltip'><div class='arrow'></div><h3 class='popover-header'></h3><div class='popover-body'></div></div>",
			title: info.event.title,
			trigger: 'hover'
		});
	}
});
calendar.render();

**Comment by arshaw** [comment]
you're probably using a mix of old and new versions. make sure core is version 4.3.1 and everything else is 4.3.0

**Comment by acerix** [comment]
Would you be able to post a [runnable, stripped-down demonstration of the bug](http://fullcalendar.io/wiki/Reduced-Test-Cases/)? Would really appreciate it because the time saved reproducing will be time spent fixing.

**Comment by estimtrack** [comment]
I just ran into a similar issue. 

it seems there is a problem with the events that can be dragged. I didn't have a problem with background events.

My fix is to use:

` "@fullcalendar/core": "4.2.0",`
 `   "@fullcalendar/daygrid": "4.2.0",`
`    "@fullcalendar/timegrid": "4.2.0",`
`    "@fullcalendar/interaction": "4.2.0",`
  `  "@fullcalendar/vue": "4.2.2",`

**Comment by haexyh** [comment]
> I just ran into a similar issue.
> 
> it seems there is a problem with the events that can be dragged. I didn't have a problem with background events.
> 
> My fix is to use:
> 
> ` "@fullcalendar/core": "4.2.0",`
> ` "@fullcalendar/daygrid": "4.2.0",`
> ` "@fullcalendar/timegrid": "4.2.0",`
> ` "@fullcalendar/interaction": "4.2.0",`
> ` "@fullcalendar/vue": "4.2.2",`

I made the same with an NG project and updated all with version 4.4.0
