### ISSUE TITLE
Equalize width of events across timeGrid view

### ISSUE THREAD

**Issue by DaveOfAllTrades** [fullcalendar/fullcalendar#4972]
When using the timeGrid day view with events in [this linked example's configuration](https://codepen.io/DaveOfAllTrades/pen/YmbOwv?&editable=true&editors=001), events are calculated with disparate widths. Ideally, each event occurring on the left side should reduce their width in order to increase the width of the events on the right.

I understand another view might be more ideally suited for this many events. However, my team prefers this view type for our use case.

**Comment by arshaw** [comment]
thanks for the report. yes, confirmed. i'm merging this ticket with this one:
https://github.com/fullcalendar/fullcalendar/issues/5004
&uarr;
Could you please visit the link, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates?
