### ISSUE TITLE
EventSourceFunc type missing properties

### ISSUE THREAD

**Issue by baileyandy** [fullcalendar/fullcalendar#4979]
In writing event handlers in TypeScript, I had previously been duplicating argument types from the fullcalendar source, for example taking

```JavaScript
eventDrop?(arg: {
    el: HTMLElement;
    event: EventApi;
    oldEvent: EventApi;
    delta: Duration;
    revert: () => void;
    jsEvent: Event;
    view: View;
}): void;
```

and creating a type in my code as:

```JavaScript
export interface EventDropArgs {
    el: HTMLElement;
    event: EventApi;
    oldEvent: EventApi;
    delta: Duration;
    revert: () => void;
    jsEvent: Event;
    view: View;
}
```

Recently, in upgrading from `4.1.0` to `4.3.1` some function arguments have changed, which caused some issues. To solve the duplication I am now extracting the types directly from the functions like so:

```TypeScript
export type EventDropArgs = Parameters<Pick<OptionsInput, 'eventDrop'>['eventDrop']>[0]
```

which should help with future type changes. Obviously any new required types will still cause compiler errors but this inferred type alias removes the duplication problem.

**The problem**: In creating the inferred type alias for EventSourceFunc I found some missing properties, which I am adding manually with:

```TypeScript
interface EventSourceFuncMissingArgs {
    startStr: string;
    endStr: string;
    timeZone: string;
}

export type EventSourceFuncArgs = Parameters<EventSourceFunc>[0] & EventSourceFuncMissingArgs
```

or see [online demo](https://codesandbox.io/s/cranky-darkness-er2cw?fontsize=12&module=%2Fsrc%2Findex.ts&view=preview). This is verified by comparing the [type in the source](https://github.com/fullcalendar/fullcalendar/blob/master/packages/core/src/event-sources/func-event-source.ts#L6) with the [returned object shape](https://github.com/fullcalendar/fullcalendar/blob/master/packages/core/src/event-sources/func-event-source.ts#L33) **and** the [docs](https://fullcalendar.io/docs/events-function).

It would be great to see the EventSourceFunc type updated to match the docs and return object shape. I can attempt a PR if this is confirmed as an issue.

Even better can fullcalendar create and export the event handler function signatures as separate types to eliminate the need to create aliases? I can raise this as a separate request if this is something that warrants its own discussion.

**Comment by arshaw** [comment]
this should be resolved in v5
