### ISSUE TITLE
resourceColumns width has no effect when specified as a percentage

### ISSUE THREAD

**Issue by acerix** [fullcalendar/fullcalendar#4980]
The `width` setting works as a number of pixels but not for a percentage like "50%".

https://codepen.io/acerix/pen/yLBOeEb?editors=0010

Reported in https://fullcalendar.freshdesk.com/a/tickets/1074

**Comment by arshaw** [comment]
this now works in v5: https://codepen.io/arshaw/pen/BajRovB?editable=true&editors=001

please be mindful of the new setting names from v4-> v5

also, you'll need to remove the `width:80` from the other column. The web browser, which is simply leveraging a `<colgroup>` for all of this, gets mixed up when you mix percentages with pixels
