### ISSUE TITLE
Get the calendar in custom buttons handler arguments

### ISSUE THREAD

**Issue by aurelien-robineau** [fullcalendar/fullcalendar#4989]
Hi,
I guess many people use custom buttons to call some methods on the calendar containing the custom button, and I see no way to access the calendar properly.
It would be really usefull to have access to the calendar in the handler of custom buttons, for exemple in handler arguments.

```
customButtons: {
    myCustomButton: {
        text: 'myCustomButton',
        click: function(calendar) {
            calendar.gotoDate('whatever');
        }
    }
}
```

**Comment by acerix** [comment]
You can store a reference to the calendar when it is initialized and use that in the callback, eg:

```js
var calendar = new Calendar(calendarEl, {
    customButtons: {
        myCustomButton: {
            text: 'myCustomButton',
            click: function() {
                calendar.gotoDate();
            }
        }
    }
});
```
