### ISSUE TITLE
TypeError when switching Timeline views after changing slotDuration

### ISSUE THREAD

**Issue by patrikdevcore** [fullcalendar/fullcalendar#4993]
Reproduction:
https://codepen.io/cherrycake/pen/VwZPYZa
1. Change view to week
2. Click change slot time to 1 week in top left corner.
3. Switch view to Day,

Calendar breaks and no more interaction possible. Also breaks when changing slot time to 1 week upon first loading.

The bug seems to occur when a slotDuration has been set to a duration longer than the duration of the view. For instance it does not occur when setting slot time to 1 day in month view and then changing back to day view.

This is problematic because there is no fail free way of switching between Timeline views that have a slotDuration set through options.

A fix would be to reset the slotDuration when switching views to a sensible default (is possible, to the default specified in the view object upon initialization - views[].slotDuration

**Comment by acerix** [comment]
Thanks for the detailed report, confirmed, I get this error:

```
Uncaught TypeError: Failed to execute 'getComputedStyle' on 'Window': parameter 1 is not of type 'Element'.
    at TimeAxis.computeDefaultSlotWidth (main.js:1416)
    at TimeAxis.computeSlotWidth (main.js:1402)
    at TimeAxis.updateSize (main.js:1389)
    at i.updateSize (main.min.js:6)
    at t.updateSize (main.min.js:6)
    at t.render (main.min.js:6)
    at t.e.receiveProps (main.min.js:6)
    at e.renderComponent (main.min.js:6)
    at e.executeRender (main.min.js:6)
    at e.tryRerender (main.min.js:6)
    at e.requestRerender (main.min.js:6)
    at e.dispatch (main.min.js:6)
    at e.changeView (main.min.js:6)
    at HTMLButtonElement.c (main.min.js:6)
```

**Comment by acerix** [comment]
Also reported in https://fullcalendar.freshdesk.com/a/tickets/1179

I took a closer look and that error seems to come from having a `slotDuration` of specifically 7 days in the timelineDay view:

https://codepen.io/acerix/pen/vYBvBBb?editors=0010

To have the slotDuration "reset" when changing view, it can be set as a view-specific option instead which should avoid the error:

https://codepen.io/acerix/pen/LYPMPpg?editors=0010

**Comment by ABooooo** [comment]
I am having the same error. I've posted a reply and code sample here [https://stackoverflow.com/questions/57512805/fullcalendar-scheduler-uncaught-typeerror-failed-to-execute-getcomputedstyle/60548138#60548138](https://stackoverflow.com/questions/57512805/fullcalendar-scheduler-uncaught-typeerror-failed-to-execute-getcomputedstyle/60548138#60548138)

**Comment by arshaw** [comment]
no longer dies in v5: https://codepen.io/arshaw/pen/ExPwEPz?editors=1010
