### ISSUE TITLE
Resource Timeline Grouping - Same resource under different grouping

### ISSUE THREAD

**Issue by mpitchandi** [fullcalendar/fullcalendar#4995]
Resource Time Grouping - Same resource under different grouping.

same resource under different grouping doesn't allow. it always merge to single group.

We want display same resource, group under different group and appropriate mapping event added  to that

**Comment by acerix** [comment]
Do you mean having the same resource show in more than one group, with all the same events? For example by allowing `resourceGroupField` to be an array of strings, one for each group it show show under?

https://fullcalendar.io/docs/resourceGroupField

**Comment by mpitchandi** [comment]
I mean having Same Resource in more than one group. With having different events. Please see the image below. I want to achieve same as below.


1.       Same resources under different group.

2.       Different event grouping.

As per current settings, we cannot duplicate resources and different event. And all event merge to resource. We cannot able to show in different grouping.
[cid:image001.png@01D559BA.FB432B50]

Thanks & Regards,
Mani

**Comment by acerix** [comment]
You could add those as separate resources but use the same title which would look like your screenshot.  If it's not working, please post a [runnable, stripped-down demonstration of the bug](http://fullcalendar.io/wiki/Reduced-Test-Cases/).
