### ISSUE TITLE
Height Auto and DayClick

### ISSUE THREAD

**Issue by rhousham** [fullcalendar/fullcalendar#4996]
Hi this is pretty obscure so bear with me.

If you have height as auto and a function on dayCLick in fullcalender 3.9 then in ie11 it wont fire unless you are in debug mode or do something like zoom in and out again, then it seems to work.

It's quite odd.

**Comment by rhousham** [comment]
In fact even setting the height, naffs it up. 
So basically on views agendaDay with having dayClick you seem to have to need a massive table with a gutter.

**Comment by rhousham** [comment]
It's ok in 3.3.1 but 3.7 has this issue as well.

**Comment by acerix** [comment]
Would you be able to post a [runnable, stripped-down demonstration of the bug](http://fullcalendar.io/wiki/Reduced-Test-Cases/)? Would really appreciate it because the time saved reproducing will be time spent fixing.

If the issue is reproducable in the v4 demos, please specify which demo and the steps to reproduce it.

**Comment by rhousham** [comment]
Hi there, can't believe it's been a month.
I've knocked together a quick example for the 3.7 version.
https://jsfiddle.net/rhousham/fyrnq176/3/

If you click a timeslot in ie11 you don't get the alert like you do in chrome.

I'd stick something together for the v4 demos but I've had a real time of it trying to find the links in cdm or other suitable public locations

**Comment by acerix** [comment]
Thanks for the demo, but I tried in IE 11 on Windows 7 and I get the popup as expected. Do you get any message in the error console?

This page has CDN links for v4 under UNPKG:

https://fullcalendar.io/docs/plugin-index

**Comment by rhousham** [comment]
I'm using windows 10 however this is a tricky one.
Switch debug mode on in fullcalendar - works
Press F12 to see the console/errors - works (even if you hide it again)
Go to settings and display script error for every error - no errors.

At this point, I've tested this on several 'in-house' windows 10 machines and now my own machine.
All the same.

I'll try and whip up a fullcalendar v4 example fingers crossed it's ok there.
Thanks
Richard

**Comment by rhousham** [comment]
Got a version here
https://jsfiddle.net/rhousham/37we1bok/
Just testing on a few machines.

**Comment by rhousham** [comment]
Yeah, just tested on my machine and same issue on version 4.
It's all down to that height:auto.
R

**Comment by acerix** [comment]
I tried your first demo in [Windows 10 virtualbox](https://developer.microsoft.com/en-us/microsoft-edge/tools/vms/) and the alert works in IE11 and also in Edge.

Your v4 demo wasn't working for me in any browser, UNPKG gives a 500 error for the interaction script which seems like a temporary server problem:

https://unpkg.com/@fullcalendar/interaction/main.min.js

I replaced that with a working URL and it also works fine in IE11 for me:

https://jsfiddle.net/j0b67n34/

**Comment by rhousham** [comment]
Well, it seems to be fixed in v4 - so that's a good thing. 
Thanks for fixing my js. Its a bit more tricky getting it setup in v4 - so thanks for the example.

I still don't get anything in v3.7
Like I said no error messages and it works if I press F12 to try and see any error messages it starts working!

I guess this is one of those times when the solution is to upgrade to v4!
