### ISSUE TITLE
Scheduler on ResourceTimeLineWeek, click on a day nav-links renders month-view instead of day-view

### ISSUE THREAD

**Issue by hrigu** [fullcalendar/fullcalendar#4997]
Hello 
When I click on a day nav-link, I expect that the day-view of this day is rendered. Instead, the month-view is rendered.

This only happens in the week-view. In the month-view it works correctly.

This behaviour can be found in V4.1.0 but also in the newest version 4.3.9.
On the outdated schedular version (1.9.3, fullcalendar: 3.9.0) it worked as expected.

See the behaviour on V4.1.0: https://codepen.io/hrigu/pen/vYBgGmz

Christian

**Comment by acerix** [comment]
I believe this existing ticket captures this need:
https://github.com/fullcalendar/fullcalendar/issues/4931
↑
Please visit the above issue, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates.
