### ISSUE TITLE
eventOrder is wrong in more complex event scenario (view: timeGridDay)

### ISSUE THREAD

**Issue by MatLeRock** [fullcalendar/fullcalendar#4998]
_eventOrder_ (overlapping) is wrong when having one big event lasting multiple hours and multiple small events which occur in between the range of that big event. The big event shall be ordered in the middle of the calendar while smaller events shall be ordered lower or higher.  

See this example:
https://jsfiddle.net/c3zs1fjv/2

To be correct the _T2-b_ event should be at the same position as the _T2-a_ event. Can anyone get my point and help me with that?

By the way: FullCalendar is an awesome tool. Love it!

Greets & thanks in advance, mat

**Comment by acerix** [comment]
For events that start at the same time, the order is determined by `eventOrder` so they are showing in the order you defined with `level`.  You set `eventOrder` to "-end" to make longer events come before shorter ones.

https://jsfiddle.net/ce7mw5z6/1/

**Comment by MatLeRock** [comment]
Thanks for your response but ...

... is there is no way the events get ordered correctly by _level_-attribute? _Correctly_ would mean leaving left space free and moving _T2-b_ on top of _T1_ in my example (https://jsfiddle.net/c3zs1fjv/2https://jsfiddle.net/c3zs1fjv/2). Respecting not only the start of an event but the whole timespan for rendering the correct order.

**Comment by MatLeRock** [comment]
Could you reopen this as it is not finished yet?

**Comment by MatLeRock** [comment]
Hey, thanks for reopening.

In my opinion it should look something like this:

![eventOrder_expectation](https://user-images.githubusercontent.com/4527552/63755856-ad164900-c8b7-11e9-8dbb-564e1a5cb12a.png)

**Comment by MatLeRock** [comment]
Works correctly without _T0_
https://jsfiddle.net/fyp6vrsc/

**Comment by acerix** [comment]
Thanks for the clarification.  It seems the issue is that T0 makes some space on the left and the strategy is to display events as close to the left as possible when there is space.

I think your suggested display strategy would not work in some other cases, but could be useful as an option so I'll leave this as a feature request.

As a workaround, you could add an invisible event in that case to push the actual event over:

https://jsfiddle.net/2bmcgfnr/

**Comment by MatLeRock** [comment]
Thanks!

**Comment by arshaw** [comment]
I plan to refactor timegrid event position when I tackle this issue: https://github.com/fullcalendar/fullcalendar/issues/4126

when I do so, the issue in this ticket will likely be fixed

**Comment by MatLeRock** [comment]
Just for the people stumbling upon this thread. My problem above can be solved by setting the option **eventOrderStrict** to **true** (added in v5.7.0)
https://fullcalendar.io/docs/eventOrderStrict

All hail to the fullcalendar-team! You are awesome!
