### ISSUE TITLE
Concurrent events have less homogeneous widths and use less of the available space in v4  

### ISSUE THREAD

**Issue by ocarreterom** [fullcalendar/fullcalendar#5004]
The position strategy has changed in v4 and now it seems waste more space. Also events' width is less homogeneous.

Toggle the commented event to see how events are repositioned.

| v3 | v4 |
|----|----|
| https://jsfiddle.net/76svdro5/ | https://jsfiddle.net/xf632nws/4/ |
| ![Captura de pantalla 2019-08-27 a las 16 29 18](https://user-images.githubusercontent.com/11599942/63780058-d8189100-c8e7-11e9-90ef-d228aef01acc.png) | ![Captura de pantalla 2019-08-27 a las 16 28 21](https://user-images.githubusercontent.com/11599942/63779967-ba4b2c00-c8e7-11e9-9905-a4d9d3a9d498.png) |

**Comment by AsemK** [comment]
any idea if this will be picked up soon?

**Comment by arshaw** [comment]
the problem still exists in v5: https://codepen.io/arshaw/pen/JjEppME?editors=0010

i will provide a fix in the next release

**Comment by arshaw** [comment]
This has been fixed in v5.7.0!
blog post: https://fullcalendar.io/blog/2021/05/new-features-in-v570

repro:
https://codepen.io/arshaw/pen/JjEppME?editors=0010
