### ISSUE TITLE
Events after 11pm appear to span two days

### ISSUE THREAD

**Issue by ryandeba** [fullcalendar/fullcalendar#5008]
See: https://jsfiddle.net/412qh7zx/5/

The `:)` event at 11pm is correctly appearing on the correct date (8/1), but the `:(` event that starts 1 minute later appears to span across two days (8/1 - 8/2). See screenshot below.

![image](https://user-images.githubusercontent.com/1010108/63869816-65a6c000-c97e-11e9-8938-640779b0b9b4.png)

I have tried various date formats and timezones, but am able to consistently see this issue no matter what I change.

**Comment by acerix** [comment]
If you don't specify the end time, the default duration is 1 hour which makes it run into the next day:

https://fullcalendar.io/docs/defaultTimedEventDuration

**Comment by kartikparmar** [comment]
A similar issue I am facing when using RRules. 
Screenshot: https://prnt.sc/ythaa5

**RRule Array:** 
`[0] => Array
        (
            [id] => 15586
            [title] => Sunday Reopen
            [url] => https://localhost/rental/product/sunday-reopen-2/
            [allDay] => 
            [rrule] => Array
                (
                    [dtstart] => 2021-02-09
                    [freq] => daily
                    [interval] => 1
                    [until] => 2021-09-12 23:59:00
                    [byweekday] => Array
                        (
                            [0] => su
                        )

                    [byhour] => Array
                        (
                            [0] => 23
                        )

                    [byminute] => Array
                        (
                            [0] => 30
                        )

                )

            [extendedProps] => Array
                (
                    [productType] => simple
                    [bookingType] => date_time
                    [view] => list
                    [greyOutBooked] => true
                    [showQuantity] => false
                    [holidays] => Array
                        (
                            [0] => 
                        )

                    [showTime] => 1
                    [price] => 0
                    [sort] => 0
                    [timeslot_value] => 23:30 - 00:30
                )

            [duration] => 01:00
        )` 

**JS**
`jQuery( document ).ready(function($) {
	const calendarEl = document.getElementById( 'calendar' );
	var cal = new FullCalendar.Calendar(calendarEl, {
		noEventsMessage: 'No Events',
		timeZone: 'Europe/London',
		plugins: [ 'rrule', 'dayGrid','list' ],
		header: {"left":"title","center":"","right":"prev,next"},
		defaultView: 'listWeek',
		loading: function (isLoading) {
			bkapListing.loading( isLoading, false )
		},
		events: [
			{
			   "id": 15586,
			   "title": "Sunday Reopen",
			   "url": "https://localhost/rental/product/sunday-reopen-2/",
			   "allDay": false,
			   "rrule": {
				  "dtstart": "2021-02-09",
				  "freq": "daily",
				  "interval": 1,
				  "until": "2021-09-12 23:59:00",
				  "byweekday": [
					 "su"
				  ],
				  "byhour": [
					 "23"
				  ],
				  "byminute": [
					 "30"
				  ]
			   },
			   "extendedProps": {
				  "productType": "simple",
				  "bookingType": "date_time",
				  "view": "list",
				  "greyOutBooked": "true",
				  "showQuantity": "false",
				  "holidays": [
					 ""
				  ],
				  "showTime": true,
				  "price": "0",
				  "sort": 0,
				  "timeslot_value": "23:30 - 00:30"
			   },
			   "duration": "01:00"
			}
		 ],
		eventOrder: 'sort, start,-duration,allDay,title',
		eventRender: function(info) {
			bkapListing.eventRender( info, false );
		},
		allDayText: 'All Day',
		datesRender: function( info ) {
			let start = info.view.currentStart;
			if ( moment() >= start  ) {
				$(".fc-prev-button").prop('disabled', true); 
				$(".fc-prev-button").addClass('fc-state-disabled'); 
			} else {
				$(".fc-prev-button").removeClass('fc-state-disabled'); 
				$(".fc-prev-button").prop('disabled', false); 
			}
		},
		firstDay: 0,
		eventClick: function( info ) { // Adding date param to url when Calendar view
			info.jsEvent.preventDefault(); // don't let the browser navigate
			let cal_view     = [ 'dayGridMonth', 'dayGridWeek', 'dayGridDay' ];
			let view_type    = info.view.type;
			let clicked_date = moment( info.event.start ).format( 'YYYY-MM-DD' );
			if ( info.event.url ) {
				if( cal_view.includes( view_type ) ) {
					window.open( info.event.url + '?bkap_date=' + clicked_date );
				}
			}
		},
		locale: 'hi',
	});
	cal.render();
});`
