### ISSUE TITLE
Inverse background docs refers to events that share the same id

### ISSUE THREAD

**Issue by acerix** [fullcalendar/fullcalendar#5009]
Reported in https://fullcalendar.freshdesk.com/a/tickets/1120

https://fullcalendar.io/docs/background-events#inverse-backgrounds

As of version 4 `id` is unique, the docs should say `groupId`:

https://codepen.io/acerix/pen/abowvRq?editors=0010

**Comment by dakala** [comment]
Hey @acerix, if there’s a bug in the docs, could you tag me please? Thanks!

**Comment by dakala** [comment]
Yeah, that'd be better. Any triaged issue that's documentation-related, just assign to me. Thanks!

**Comment by arshaw** [comment]
clarified in docs
