### ISSUE TITLE
Event Object does not provide properties like editable in eventClick function 

### ISSUE THREAD

**Issue by pupattan** [fullcalendar/fullcalendar#5013]
I have a eventClick function like follows.
I am trying to check whether the event is edible or not after it is clicked
But calEvent object (in the below example) does not provide properties like editable.
```
eventClick: function(eventClickInfo) {
        var calEvent = eventClickInfo.event
       console.log(calEvent.editable)
        var title = prompt('Event Title:', calEvent.title, {
            buttons: {
                Ok: true,
                Cancel: false
            }
        });
        if (title) {
            calEvent.setProp('title', title);
        }
```
console.log(calEvent.editable) shows undefined

**Comment by acerix** [comment]
Would you be able to post a [runnable, stripped-down demonstration of the bug](http://fullcalendar.io/wiki/Reduced-Test-Cases/)? Would really appreciate it because the time saved reproducing will be time spent fixing.

**Comment by cmette** [comment]
I have the same "issue" (or maybe I misunderstood the concept??). the editable attribute inside the event object disappears in some eventHandlers - by example in the eventClick handler. to verify this problem look at my fiddle [https://jsfiddle.net/theobaldo/xjhfrL4e/67/](url)
