### ISSUE TITLE
Scheduler - ResourceId field is not stored for Events

### ISSUE THREAD

**Issue by code2bfr33** [fullcalendar/fullcalendar#5016]
I'm working on project that utilizes the Resource plugins for fullcalendar and I'm trying to build my custom handler for situation when Event was dragged from one resource to another.

According to debug output, the Event object has no resourceId field after being stored in Calendar
I've created the CodePen to reproduce the situation:
https://codepen.io/vdimv/pen/oNvGzwP

It uses the Resource and Event data from Fullcalendar demo. 

ResourceId field is filled properly on the server side:
![image](https://user-images.githubusercontent.com/54810945/64123284-9cc90700-cdac-11e9-8a54-68dcb7d41999.png)

but Event object has no resourceId field (https://fullcalendar.io/docs/resources-and-events) when Event is rendered:
![image](https://user-images.githubusercontent.com/54810945/64123651-a7d06700-cdad-11e9-87ed-e31a1089b773.png)

And there is no way to detect situation of Event is dragged between Resources (from A to B) and not being dropped yet  (the eventRender callback before the eventDrop)

**Comment by acerix** [comment]
Starting in version 4 you need to use `getResources`:

https://fullcalendar.io/docs/Event-getResources

**Comment by Emsal92** [comment]
But what if you want the resourceid for where the event was dropped? Get resources returns an array of all associated resources? It also always returns the same resourceid if placing the event on different resources (in the eventRecieve callback).

**Comment by acerix** [comment]
You can use the `resource` property from the `drop` callback:

https://fullcalendar.io/docs/drop

**Comment by Emsal92** [comment]
Yeah, I stumbled upon the fix creating a variable for resource in drop callback and using it in eventRecieve. It looks kind of messy though. getResources from eventRecieve doesn't work for me.

Example:
If I drop an event on a resource I get the correct resourceid, but if I drop the same event on another resource, getResources gives me the previous resource id and not the one where it was dropped.

**Comment by RapidOwl** [comment]
I've run into this today while playing with the resource timeline view. Here is how I've been building the complete event objects I need to persist:

```
function persistEvents() {
	let eventsToPersist = calendar.getEvents().map((event) => {
		// Strip out all the object cruft
		let parsedEvent = JSON.parse(JSON.stringify(event));

		// Manually add the resource ID to the event
		parsedEvent.resourceId = event.getResources()[0].id;

		return parsedEvent;
	});

	localStorage.setItem('events', JSON.stringify(eventsToPersist));
}
```

Is this the best way of doing this?
