### ISSUE TITLE
first load

### ISSUE THREAD

**Issue by xumoqiu** [fullcalendar/fullcalendar#5019]
![微信图片_20190904115728](https://user-images.githubusercontent.com/24932876/64224757-4cb48680-cf0b-11e9-9eb5-c00c5ec505fa.png)

what ’s the problem when the plugin first load

**Comment by acerix** [comment]
Would you be able to post a [runnable, stripped-down demonstration of the bug](http://fullcalendar.io/wiki/Reduced-Test-Cases/)? Would really appreciate it because the time saved reproducing will be time spent fixing.
