### ISSUE TITLE
google-calendar - import issue

### ISSUE THREAD

**Issue by QuytNguyen** [fullcalendar/fullcalendar#5020]
angular 6 with fullcalendar v4.3.1
> ERROR in node_modules/@fullcalendar/core/main.d.ts(7,14): error TS2484: Export declaration conflicts with exported declaration of 'OptionsInput'.

this error returned when I import google-calendar and re-compiling.
all import are:
`import { Component, ViewChild, ChangeDetectorRef, Renderer2 } from '@angular/core';
import { FullCalendarComponent } from '@fullcalendar/angular';
import { EventInput } from '@fullcalendar/core';
import dayGridPlugin from '@fullcalendar/daygrid';
import timeGrigPlugin from '@fullcalendar/timegrid';
import listPlugin from '@fullcalendar/list';
import interactionPlugin from '@fullcalendar/interaction'; // for dateClick
import googleCalendarPlugin from '@fullcalendar/google-calendar';
import viLocale from '@fullcalendar/core/locales/vi';
import * as _moment from 'moment';
import { default as _rollupMoment, Moment } from 'moment';
import { MatCalendar, MatDialog } from '@angular/material';
import { NhapLichDialogComponent } from './nhap-lich/nhap-lich.dialog.component'
import { TranslateService } from '@ngx-translate/core';
import { LayoutUtilsService } from '../../../_core/utils/layout-utils.service';
import { ContextMenuComponent, ContextMenuService } from 'ngx-contextmenu';`

Thanks!

**Comment by acerix** [comment]
Would you be able to post a [runnable, stripped-down demonstration of the bug](http://fullcalendar.io/wiki/Reduced-Test-Cases/) or steps to reproduce the issue? Would really appreciate it because the time saved reproducing will be time spent fixing.
