### ISSUE TITLE
Cannot read property 'minTime' of null

### ISSUE THREAD

**Issue by mitomm** [fullcalendar/fullcalendar#5022]
Hi there,

we are using fullcalendar 3.9.0 and we bought scheduler v1.9.4.

We keep getting an issue that appears very randomly and that I cannot properly reproduce.

What we are seeing:
A dayClick does randomly not return the correct moment that was clicked. This happens randomly in our production environment. We also track our errors with sentry and sometimes see the following error: 

`Cannot read property 'minTime' of null`

We pinned the error down to the following function:

`
    TimeGrid.prototype.computeSnapTime = function (snapIndex) {
        return moment.duration(this.dateProfile.minTime + this.snapDuration * snapIndex);
    };
`

It seems like _ this.dateProfile_ is sometimes null. Although it happens very rarely it's a major issue for us if it happens as the calendar is not working as expected after it happens.

I know you usually want a reproducible example put since it seems to happen very randomly and rarely I can't reproduce it. Could it maybe be a race condition somewhere? Or do you maybe have an idea on where we should look, or a first guess where it could come from.

P.s not sure if it is related to the same issue, but we also randomly get the following error:
`
TypeError: Cannot read property 'def' of undefined
  at t.getEventDef (/bower/fullcalendar/dist/fullcalendar.min.js:6:24250)
  at t.isEventInstanceGroupAllowed (/bower/fullcalendar/dist/fullcalendar.min.js:9:10440)
  at t.e.isEventInstanceGroupAllowed (/bower/fullcalendar/dist/fullcalendar.min.js:7:13716)
  at e.hitOver (/bower/fullcalendar/dist/fullcalendar.min.js:10:24173)
  at e.t.trigger 
`

Thanks a lot for your help.

**Comment by acerix** [comment]
We would need a way to reproduce the issue to look into it.

Someone reported a similar error which got fixed in version 3.10.0 so updating to that release might help:

https://github.com/fullcalendar/fullcalendar/issues/3689#issuecomment-409587731
