### ISSUE TITLE
Cannot Sync with Google Calendar on Ionic iOS

### ISSUE THREAD

**Issue by mibzman** [fullcalendar/fullcalendar#5033]
Issue Recreated at [This Repo](https://github.com/mibzman/Ionic-FullCalendar-Issue)
Since this issue involves running natively, in order to see the bug in action you have to be running in an ios emulator, not in a webview.

1. Make sure some event exists in the calendar you are pulling data from
1. Rename `environment.example.ts` to `environment.prod.ts` and `environment.ts`
1. Insert your google credentials
1. `ionic cordova run android`
1. Note that the google calendar syncs your event
1. `ionic cordova run ios`
    - note: your system may require `ionic cordova emulate ios -- --buildFlag="-UseModernBuildSystem=0"`
1. Note that the event does not sync on ios
1. Below is a screenshot from the console output

![image](https://github.com/mibzman/Ionic-FullCalendar-Issue/blob/master/error-example.png?raw=true)

The FullCalendar code makes its requests from the ionic built-in browser, not via the Ionic HTTP Client. Since the ionic browser on IOS is hosted at ionic://, the google API blocks the requests for CORS reasons.

I do not believe this bug is really specific to any framework, as this error will occur in any situation where the calendar is hosted anywhere except a website and localhost.  Also, I see several ways to resolve this issue without having to include any ionic-specific code in the library:

1. Hack FullCalendar in such a way to allow google calendar data to be pulled outside the library (in this case by ionic's native http package) and handed off as normal
2. Require ionic users to re-engineer FullCalendar's parsing of google calendar's event data structure and pass it to FullCalendar as standard events.

The first one seems the easiest for everyone.  Please let me know if there is already an existing way to insert google calendar data into FullCalendar myself.

**Comment by acerix** [comment]
Thanks for the detailed report and suggestions.  Ionic is not supported so it's not really a bug but a feature request.

It sounds like `XMLHttpRequest` does not work from Ionic but using Angular's `HttpClient` should work so you could try putting that here as a hack:

https://github.com/fullcalendar/fullcalendar/blob/master/packages/core/src/util/requestJson.ts#L13

**Comment by mibzman** [comment]
Thank you for the feedback!  I'll make a modification to that function in a fork then.
