### ISSUE TITLE
Add resourceDestroy method to calendar API

### ISSUE THREAD

**Issue by FreexD** [fullcalendar/fullcalendar#5034]
Similarly to `eventDestroy` https://fullcalendar.io/docs/eventDestroy there could be a `resourceDestroy` method for resources. 

When using FullCalendar React wrapper you can use `ReactDOM.render` to mount your custom react component into the event element inside the `eventRender` method and then `ReactDOM.unmountComponentAtNode` inside `eventDestroy`.  For resources however you can only render in your component inside `resourceRender` but without the destroy callback will just keep rendering in the components without ever unmounting them. 

Adding the method would also make the API more consistent and predictable :)

**Comment by nicholaszuccarelli** [comment]
+1

**Comment by arshaw** [comment]
in v5 there is now a `resourceLabelWillUnmount` and `resourceLaneWillUnmount` hook:
https://fullcalendar.io/docs/resource-render-hooks
