### ISSUE TITLE
Typescript eventDrop API handler does not expose newResource and oldResource as arguments

### ISSUE THREAD

**Issue by FreexD** [fullcalendar/fullcalendar#5035]
When installing the scheduler plugin the TS API for eventDrop function should change to accept `newResource` and `oldResource` as arguments - according to https://fullcalendar.io/docs/eventDrop - but right now it does not. The object passed in however has this information and it can be retrieved by lodash `get` or simply ignoring TS for the moment.

It would be nice to fix that API so that it can be used with Typescript without hacking JS objects.

**Comment by arshaw** [comment]
the typedefs in v5 have been updated to fix this

**Comment by jansequens** [comment]
Running version 5.1.0 but the `EventDropArg` interface still does not expose `newResource` and `oldResource`.
