### ISSUE TITLE
ENOENT error in monorepo-tool when running "npm install"

### ISSUE THREAD

**Issue by Poumm** [fullcalendar/fullcalendar#5036]
Hello,

I tried to build fullcalendar, but when I run "npm install" I get an error : 

![image](https://user-images.githubusercontent.com/4928430/64784635-d4813d00-d56a-11e9-9980-e0a63a4fbe15.png)

Here is exactly what I'm doing : 

```
git clone 
cd fullcalendar
npm install
``` 
I'm on windows 10.
NPM version :  6.11.3
Node.js version : v10.16.3

LOG file mentionned in the log : 

[2019-09-12T12_34_07_284Z-debug.log](https://github.com/fullcalendar/fullcalendar/files/3605476/2019-09-12T12_34_07_284Z-debug.log)

Clear npm cache didn't change anything.

**Comment by arshaw** [comment]
i stripped out the monorepo tool from the v5 codebase, so this should no longer be an issue
