### ISSUE TITLE
Navigation arrow fc-icon-chevron-right not working

### ISSUE THREAD

**Issue by bsgies** [fullcalendar/fullcalendar#5042]
Hi,

I have installed FC calendar and using default styling. I fail to understand the reason why fc-icon-chevron-right showing left icon? I have attached the console of Google chrome below:

<img width="1352" alt="fc" src="https://user-images.githubusercontent.com/32961638/64921318-e0af0980-d7b9-11e9-8d11-447326fdc7e8.png">

<img width="1362" alt="fc" src="https://user-images.githubusercontent.com/32961638/64921357-4602fa80-d7ba-11e9-9c60-426460821dae.png">

**Comment by acerix** [comment]
Would you be able to post a [runnable, stripped-down demonstration of the bug](http://fullcalendar.io/wiki/Reduced-Test-Cases/)? Would really appreciate it because the time saved reproducing will be time spent fixing.
