### ISSUE TITLE
Weekend background event click not trigger

### ISSUE THREAD

**Issue by gayanfdo** [fullcalendar/fullcalendar#5043]
I am experiencing an issue that eventClick is not working for background events in weekends. My fullcalendar version is 4.3.1

**Comment by acerix** [comment]
Would you be able to post a [runnable, stripped-down demonstration of the bug](http://fullcalendar.io/wiki/Reduced-Test-Cases/)? Would really appreciate it because the time saved reproducing will be time spent fixing.
