### ISSUE TITLE
Day names are in cyrilic for Serbian-Latin locale

### ISSUE THREAD

**Issue by Zolak94** [fullcalendar/fullcalendar#5044]
I'm using fullcalendar 4.3.1 that I downloaded locally for my Laravel App. I want to use Serbian locale but it's in cyrilic not Latin. This is my code:
``` 
var calendar = new FullCalendar.Calendar(calendarEl, {
    locale: 'sr',
    plugins: ['dayGrid', 'timeGrid', 'list', 'interaction'],
});
```
Buttons are in Latin but Month names and day names are in cyrilic. I know that in older version I could have used this: `dayNames: ['Ponedeljak','Utorak','Sreda','Četvrtak','Petak','Subota','Nedelja']` to solve this. But that option was removed in v4 version.
How can I solve this? Is there a file that I can edit or?

**EDIT 1**
This is in my script: ` <script src='/js/FullCalendar/packages/core/locales-all.js'></script>`

**Comment by acerix** [comment]
There is a separate locale "sr-cyrl" which seems to be what you are looking for. It can be tested in this demo:

https://fullcalendar.io/docs/locale-demo

**Comment by acerix** [comment]
As of v4, the day names are determined by the browser and it seems the major browsers display the day names in cyrilic for both the "sr" and "sr-cyrl" locales.

You could use the Moment.js plugin since that has the day names in latin for the "sr" locale:

https://fullcalendar.io/docs/moment-plugins

https://github.com/moment/moment/blob/develop/locale/sr.js#L39

**Comment by Zolak94** [comment]
I included this `<script src='/js/FullCalendar/packages/moment/main.js'></script>`  but I can't seem to find how to change locale.

**Comment by acerix** [comment]
It uses the same 'locale' setting in the calendar, but you need to also include the moment file for your locale, or "moment-with-locales" which has all locales. Here's an example:

https://codepen.io/acerix/pen/zYOmjNd?editors=0010

**Comment by Zolak94** [comment]
I added locale like this:
```
document.addEventListener('DOMContentLoaded', function() {
    calendarEl = document.getElementById('calendar');
    calendar = new FullCalendar.Calendar(calendarEl, {
        plugins: [ 'dayGrid', 'timeGrid', 'list', 'rrule', 'moment', 'interaction' ],
        locale: 'sr',
        ...
```
And it's still Serbian cyrilic. I cleared cache and it's still same. Buttons are in Serbian latin but month names and day names are again in cyrilic.

**Comment by acerix** [comment]
You need to change `slotLabelFormat` to a moment string and also include "moment-with-locales" as in my demo above.  If it's not working because of a bug, please provide a [runnable, stripped-down demonstration](http://fullcalendar.io/wiki/Reduced-Test-Cases/).

**Comment by Zolak94** [comment]
I found much simpler solutions. I used `locale: 'sr-ME'`. Because ME and Sr are identical when it comes to day, month names.

**Comment by Zolak94** [comment]
> You need to change `slotLabelFormat` to a moment string and also include "moment-with-locales" as in my demo above. If it's not working because of a bug, please provide a [runnable, stripped-down demonstration](http://fullcalendar.io/wiki/Reduced-Test-Cases/).

I had more time to look into this and this is a solution. Every date in the calendar I had to format to moment string. Just like this:
```
...
    titleFormat: 'MMMM, YYYY',
    columnHeaderFormat: 'ddd',
    listDayFormat: 'dddd',
    listDayAltFormat: 'DD. MMMM YYYY',
    slotLabelInterval: { days: 1 },
    slotLabelFormat: [
      'MMMM YYYY',
      'D dddd'
    ],
...
```
After this, every date was in Serbian. Thank you, and sorry for the slow reply.

**Comment by SilverDoll** [comment]
just use: sr-Latn-RS and it will work
