### ISSUE TITLE
dateClick not firing in resourceTimeGridDay and resourceTimelineDay view

### ISSUE THREAD

**Issue by jared201** [fullcalendar/fullcalendar#5046]
My have initialised the fullCalendar with these properties, but dateClick is only working in timeGridDay view and other views without resource
```            
plugins: ['timeGrid', 'dayGrid', 'interaction', 'resourceTimeline', 'resourceTimeGrid'],
            
dateClick: function(info){
                alert ('Clicked on: ' + info.dateStr + ', ' + info.resource);
            },
  select: function(info) {
                alert('selected ' + info.startStr + ' to ' + info.endStr);
            },
            selectable: true,

**Comment by acerix** [comment]
Would you be able to post a [runnable, stripped-down demonstration of the bug](http://fullcalendar.io/wiki/Reduced-Test-Cases/)? Would really appreciate it because the time saved reproducing will be time spent fixing.
