### ISSUE TITLE
Range showing when using dayGridDay titleFormat with moment plugin

### ISSUE THREAD

**Issue by chrisatmydrivetime** [fullcalendar/fullcalendar#5049]
If I use moment date formatting with the `dayGridDay` I am shown the date twice with range separator.

Reproduced: [https://codesandbox.io/s/fullcalendar-vue-ljlp1](https://codesandbox.io/s/fullcalendar-vue-ljlp1)

`:titleFormat` values I have tried:

- `'DD'` outputs `19 - 19`
- `'dddd'` outputs `Thursday - Thursday`
- `'dddd DD'` outputs `Thursday 19 - Thursday 19`
- `'{DD}'` outputs `19 - 19`
- `'{dddd DD}'` outputs `Thursday 19 - Thursday 19`
- `'{{dddd} DD}'` outputs `Thursday - Thursday 19`
- `{ day: 'numeric' }` **correctly** outputs `19`

I believe this is related to some similar issues but with slightly differing configurations:
- #3645 - in this case `dddd` appears works as expected, possibly related to the use of agendaDay rather than dayGridDay, and the issue focuses on `LL`
- #3898 - in relation to use of `LL`
- #4941 - using `resourceDayTimeline`, but otherwise identical

**Comment by acerix** [comment]
Thanks for the report.  It seems like the same problem as in the issues you mentioned so I closed the other one that was open to avoid duplicates.

https://github.com/fullcalendar/fullcalendar/issues/3645
↑
Please **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)) and press the 🔈**Subscribe** button to receive updates.
