### ISSUE TITLE
maxTime ending at next day causes problems at timeGridWeek and timeGridDay

### ISSUE THREAD

**Issue by tyapkov** [fullcalendar/fullcalendar#5051]
I am moving to fullcalendar 4.3.0.
In my app there are a lot of events which are happening around midnight. That is why for every day the **maxTime** should be at the next day. For example, **maxTime: "1.03:00:00"**. However, it causes some problems:
1. At the timeGridWeek events for the last day of the week are not shown.
2. At the timeGridDay events are now shown at all.

Here is the codepen: 
https://codepen.io/tyapkov/pen/ExYOoRw

**Comment by acerix** [comment]
The [duration string](https://fullcalendar.io/docs/duration-object) format does not include the number of days, but you can have more than 24 hours like `maxTime: "27:00:00"` which doesn't have those issues:

https://codepen.io/acerix/pen/aboPoJj?editors=0010

**Comment by tyapkov** [comment]
@acerix Thank you for helping! Your solution is working fine.
