### ISSUE TITLE
Event Object does not provide properties like editable in eventClick function

### ISSUE THREAD

**Issue by cmette** [fullcalendar/fullcalendar#5052]
#5013 I have reopened this [issue](https://github.com/fullcalendar/fullcalendar/issues/5013) because nobody looks at my fiddle. Please give me a short answer about the issue.

I have the same "issue" like pupattan #5013 (or maybe I misunderstood the concept??). the editable attribute inside the event object disappears in some eventHandlers - by example in the eventClick handler. to verify this problem look at my fiddle [https://jsfiddle.net/theobaldo/xjhfrL4e/67/](https://jsfiddle.net/theobaldo/xjhfrL4e/67/)

The same problem I have inside the eventRender(info) Handler. the info-object provides no event object like described in the docs. the info-object provides only objects with underscore like _calendar, _def, _instance etc. I expected an object like "event" (info.event) in accordance with the docs.

**Comment by acerix** [comment]
Thanks for the report and demo. I didn't notice when you posted the demo on the other issue but it seems like the same issue.

I couldn't find any way to read the "editable" property, it seems like a bug that it's undefined in your demo.

As a workaround, you could also store the value in an extended property:

https://codepen.io/acerix/pen/oNvmzJo?&editable=true&editors=001

**Comment by cmette** [comment]
OK thank you for your answer - no problem. can you or I fix this bug? in the docs v4 I can read that it should work. but I will also test the workaround in the meantime. thanks, cmette

**Comment by borisbsu** [comment]
Also there is no `resourceId` value in event object. Storing extra properties in `extendedProps` work, but it really looks ugly to send extra 2 fields from backend.

**Comment by przemyslaw-szustak** [comment]
I have these same problem.
I think that the problem is because "color" and "editable" are map to other keys (in api/EventApi.ts class EventApi method setProp()):

```
      if (name === 'color') {
        ui = { backgroundColor: val, borderColor: val }
      } else if (name === 'editable') {
        ui = { startEditable: val, durationEditable: val }
      } else {
        ui = { [name]: val }
      }

```

If it is not a bug it would be great if it was in the manual :)

**Comment by arshaw** [comment]
the [event object](https://fullcalendar.io/docs/event-object) has `startEditable` and `durationEditable`. specifying `editable` is a shortcut for specifying these two properties at the same time. this one property gets expanded into two
