### ISSUE TITLE
eventAllow is not called on the event that is dragged if there is an earlier event with the same groupId

### ISSUE THREAD

**Issue by correalucas** [fullcalendar/fullcalendar#5056]
Hi Guys, 
I'm trying to use the eventAllow event to block draggedEvent previous events from being dragged too, but when the eventAllow is triggered, it's give me the wrong draggedEvent.

When the Event 2 is dragged, the draggedEvent returns Event 1 instead.

Here is a example to reproduce the issue:
https://codepen.io/correalucas/pen/qBWvmxo

**Comment by acerix** [comment]
Thanks, confirmed.  I can see it also gets the date from the first event:

https://codepen.io/acerix/pen/aboMaPN?editors=0011

I think eventAllow should actually be called for all events with the same groupID to check that they are all allowed since they move together.

**Comment by arshaw** [comment]
it actually does do this (see my v5 [updated repro](https://codepen.io/arshaw/pen/XWXeEeL?editors=0011))

the `eventAllow` function now returns false. When it wasn't returning anything, it was assuming false and then short-circuiting and not testing for the other event instances.
