### ISSUE TITLE
Support with VisibleRange on resourceTimeline (Scheduler)

### ISSUE THREAD

**Issue by cicampemu** [fullcalendar/fullcalendar#5061]
Hello,

We'd like to be able to resize events between 2 dates from 06 o' clock to 06 o' clock the next morning on a resourceTimeline view. 

Without the use of visibleRange param, it's showing the right time we want to show, but we're not able to resize the event over 24hours (i.e. cannot resize event past midnight), meaning from first day to second day:
https://codepen.io/krupalpatel92/pen/BaBeeRx?editors=0010

When using visibleRange, as advised, we are able to resize the event but it's now showing 48 hours instead of only 24 hours:
https://codepen.io/krupalpatel92/pen/oNvRRWY?editors=0010 

We're using Angular 7.

Any help would be great! Thanks!

**Comment by trungk18** [comment]
I got the same issue before, you might want to check this link. 

https://github.com/fullcalendar/fullcalendar/issues/4658

**Comment by cicampemu** [comment]
Thx @trungk18, but see, we have the same issue :

"Basically I want to show the range from 2019-03-16T05:00:00 to 2019-03-17T08:00, but as you can see on the pen above, It will show until 2019-03-18T08:00. Which is another one day."

But we really want to show 24h (from 06 to 06 in the morning the next day - so 2 dates, not 3) and be able to resize events after midnight.

Maybe there's something I missed in your ticket but I don't understand how to do that.

Thx

**Comment by krupalpatel92** [comment]
> I got the same issue before, you might want to check this link.
> 
> #4658

Facing the same issue as @cicampemu said

**Comment by trungk18** [comment]
Hi @krupalpatel92, @cicampemu,

Sorry I didn't read your description carefully. 

I have just quickly setting up the calendar with minTime and maxTime, it is not possible to resize the event beyond the 24 hours. In my use case, I ended up open a popup modal that allowing me to edit the startTime and endTime on click into a specific event.

Hope you could find the workaround soon. Or somebody can help you with that.

**Comment by krupalpatel92** [comment]
Hi @trungk18 ,

That's a good solution to open popup and edit event time but we have a different scenario some UI/UX limitation and requirement we have to follow.

Anyway popup is a good solution Thanks!

**Comment by krupalpatel92** [comment]
Hello @everyone,

Also, try a custom view for it
https://fullcalendar.io/docs/custom-view-with-js"

Maybe it help something.

**Comment by acerix** [comment]
Also reported in https://fullcalendar.freshdesk.com/a/tickets/1202

As mentioned in my support reply:

I believe this existing ticket captures the issue with `maxTime` > 24 hours:
https://github.com/fullcalendar/fullcalendar/issues/3900
↑
Please visit the above issue, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates.

For the workaround, `visibleRange` only works for whole dates, it does not consider the time of day.  It seems to do what you are looking for with just the dates and combined with `maxTime`:

https://codepen.io/acerix/pen/wvwVMYg?editors=0010

**Comment by krupalpatel92** [comment]
> Also reported in https://fullcalendar.freshdesk.com/a/tickets/1202
> 
> As mentioned in my support reply:
> 
> I believe this existing ticket captures the issue with `maxTime` > 24 hours:
> #3900
> ↑
> Please visit the above issue, **give a** 👍 **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates.
> 
> For the workaround, `visibleRange` only works for whole dates, it does not consider the time of day.
> 
> Also, the `end` date is _exclusive_ so should be the same as the `start` to make the view 1 day long.
> 
> It seems to do what you are looking for with just the dates and combined with `maxTime`:
> 
> https://codepen.io/acerix/pen/wvwVMYg?editors=0010

Hi @acerix 

we already achieved this https://codepen.io/acerix/pen/wvwVMYg?editors=0010 solution, but it's not allowing to resize the after 24h of the first day but can drag event. 

So, an issue is the resizing event between two days, I mean the event will start on 22hrs and end at 23hrs but I want to resize it from day one 23hrs to second day 3hrs. That's an issue.

anyway changed the scope due to this limitation.

I hope Fullcalendar will come to the solution.

**Comment by albangr** [comment]
Hi @acerix,

Any update on this ? 

Like @krupalpatel92 said, the workaround doesn't work, on all your codepen, when we are trying to drag and drop an event after midnight by clicking on it after midnight it doesn't work.
It appears that the part of the calendar after midnight can't manage drag and drop events.

An answer would be really appreciated !

Thanks for your time

**Comment by LrntL** [comment]
Need help on this!

**Comment by krupalpatel92** [comment]
Nope, thanks :)

*Thanks & Regards.*
*Krupal Patel*

ᐧ

**Comment by LrntL** [comment]
I mean: I need help !
@krupalpatel92 did you fixed this?
