### ISSUE TITLE
Tap on background events triggering eventClick on mobile (Chrome For Android)

### ISSUE THREAD

**Issue by spencerwmiles** [fullcalendar/fullcalendar#5062]
Can reproduce using this pen. 
[https://codepen.io/straskal/pen/MxNbqW](https://codepen.io/straskal/pen/MxNbqW)

On desktop the background event is not clickable - this is due to the selection occuring.
On mobile, the day click will trigger on every tap of a background event.

This has created a huge inconsistency in the functionality we're desiring to create. Ideally, the functionality would be in parity or to be able to achieve it using provided settings.

For context, we use background events to show 'availabilities' which are editable in a separate 'mode'. Fortunately, the correct functionality occurs on eventClick but it would be nice if it didn't happen at all. 

If this is expected functionality, we'll write around it, but to me it seems like a bug.

We're currently running FC 4.2.0.

**Comment by acerix** [comment]
There is a delay before the selection starts on mobile; it works the same as on desktop if you hold the tap for at least 1 second or you could set `longPressDelay` to zero.

https://fullcalendar.io/docs/longPressDelay
