### ISSUE TITLE
Add a plus icon to the standard buttonIcons

### ISSUE THREAD

**Issue by mfmevans** [fullcalendar/fullcalendar#5064]
Feature Request - Add a plus icon to the standard buttonIcons to allow for a custom add event button to be added inline with the standard theming.

**Comment by acerix** [comment]
You add a [customButton](https://fullcalendar.io/docs/customButtons) for that.

**Comment by mfmevans** [comment]
Yes, I know but as far as I can see there are only a set number of icons available, would be nice for a mobile view if there was a plus "+" one, save having to switch to the bootstrap theme.

**Comment by edwardmjackson** [comment]
The specific request for a + icon can be done by a customButton like so. 

addEvent: {
            text: "no icon",
            icon: "fc-icon-plus-square",
            click: function() {
              alert("clicked the addEvent!");
            }
          }

What I'd really like to see is a wider set of the feathericons.com library available in the base64 encoded font string in FullCalendar's CSS, for example a settings cog. It seems per [this](https://github.com/fullcalendar/fullcalendar/tree/d3a2b13db43cfe9a450091776da3be25a0ca15c0/packages/common/src/styles/icon-generation) that a pro license at IconMoon is needed though, before we could generate a PR.

**Comment by arshaw** [comment]
FWIW, you can specify `'plus-square'` in buttonIcons:

https://codepen.io/arshaw/pen/XWXeEMw?editable=true&editors=001

**Comment by mfmevans** [comment]
That works. Thanks.
