### ISSUE TITLE
eventLimit does not work if refetchResourcesOnNavigate is true and resourceTimeline plugin is included

### ISSUE THREAD

**Issue by acerix** [fullcalendar/fullcalendar#5065]
Reported in https://fullcalendar.freshdesk.com/a/tickets/1220

https://codepen.io/acerix/pen/MWWWwyr?editors=0010

Changing to the next month and back causes all events to show despite the eventLimit.

**Comment by acerix** [comment]
A possible workaround is to trigger a window resize after navigating:

https://codepen.io/acerix/pen/OJJJVmR?editors=0010

**Comment by jwigal** [comment]
Thanks for looking into this, I appreciate it!

**Comment by jwigal** [comment]
This sort-of worked but sort-of didn't. Still seeing intermittent issues even with the work-around above. 

Ended up changing my `resources` call into a function, rather than just specifying the URL:

```javascript
resources: function(fetchInfo, successCallback, failureCallback) {
  $.get('/calendars/venues.json',
    {
      start: fetchInfo.startStr,
      end: fetchInfo.endStr,
    },
    function(data){
      successCallback(data);
      window.dispatchEvent(new Event('resize'));
    }
  );
},
```

**Comment by drgrice1** [comment]
This doesn't seem to have anything to do with using resources or the refetchResourcesOnNavigate option.  I am using a static event list and this happens.  It seems to be a general bug with the dayGridMonth view.  Dispatching a window resize event is not a good alternative.  It has undesirable side effects, such as scrolling to the top of the page if the calendar happens to be lower on the page.

**Comment by arshaw** [comment]
seems fixed in v5: https://codepen.io/arshaw/pen/PoZJRjK?editable=true&editors=001
