### ISSUE TITLE
Add  break times like lunch options in businessHours

### ISSUE THREAD

**Issue by pasblin** [fullcalendar/fullcalendar#5066]
### Feature Requests
It would be nice to be able to reflect workers' breaks, for example.

Regards.

**Comment by arshaw** [comment]
i'd more description about this feature before being able to think about implementing. what would the API be? how would the UI look?

**Comment by horsebuzz** [comment]
Give an option to pass an array for `businessHours` in `businessHours-per-resource` as well.

Like this example [https://fullcalendar.io/docs/businessHours](https://fullcalendar.io/docs/businessHours)
