### ISSUE TITLE
Option to scroll through events in each day cell

### ISSUE THREAD

**Issue by Zengsh123** [fullcalendar/fullcalendar#5068]
### Feature Requests
In the day view, there are many events in one day. I want to see these events by sliding the mouse up and down inside each cell. I set'EvetLimit'to false, but that will push the whole table apart (as in the figure below). How do I set it up?
![捕获](https://user-images.githubusercontent.com/42644033/66318826-a109b680-e94e-11e9-968a-11e560795a92.PNG)

**Comment by acerix** [comment]
Are you looking to have a scrollbar inside the day cell this case?

That is not built-in, I think it should be possible with a custom view:

https://fullcalendar.io/docs/custom-view-with-js

**Comment by Zengsh123** [comment]
I'm very glad to receive your reply. I'll give it a try according to your suggestion.
