### ISSUE TITLE
DIST folder in .gitignore

### ISSUE THREAD

**Issue by tmendesilva** [fullcalendar/fullcalendar#5073]
Why v4.3.1 dist folder is in .gitignore file? I'm installing by composer and .js files aren't downloaded. Tried using "npm-asset/fullcalendar" and "bower-asset/fullcalendar".

**Comment by acerix** [comment]
When downloading the source with git, you also need to build it which gives you "dist". Otherwise you should install like this:

https://fullcalendar.io/docs/getting-started
