### ISSUE TITLE
No vertical scrolling for dayGridMonth 

### ISSUE THREAD

**Issue by civette** [fullcalendar/fullcalendar#5074]
Number of events being variable, it happens in dayGridMonth view that  calendar table height is greater than its container height. In such a case a vertical scrollbar appears.

Beside eventLimit setting, it would make sense to have a kind of noVerticalScrolling setting (whathever the name) to prevent this scrollbar to appear but having container height adapting to match needed space and displaying all events.

**Comment by nicegamer7** [comment]
I had this issue once, it turned out to be conflicting CSS. Are you sure FullCalendar's CSS isn't being overridden?

**Comment by acerix** [comment]
Would you be able to post a [runnable, stripped-down demonstration of the bug](http://fullcalendar.io/wiki/Reduced-Test-Cases/)? Would really appreciate it because the time saved reproducing will be time spent fixing.
