### ISSUE TITLE
Event resizing not working properly with eventMouseEnter/eventMouseLeave

### ISSUE THREAD

**Issue by Reiterkk** [fullcalendar/fullcalendar#5075]
Hello,

I wanted to make a hover effect for my events so that it changes the color and displays "click to delete" when the user hovers over the event. To get this done I used eventMouseEnter and eventMouseLeave and most things just work as supposed. But with this modification the resizing doesn't work properly any more. I can make the events smaller without any problems, but I can't make them larger. As far as I see the problem is, that the mouse leaves the event before it increases and thus the el is null. If I click and drag into the event first to make it smaller and then make it larger without releasing the mouse, everything is ok.
I've made an example which can be found here: https://jsfiddle.net/935uw02d/
You have to click and drag at the very bottom of the event to see this effect. 
Can you tell me how to fix this behaviour?

Thank you for your help

**Comment by acerix** [comment]
There are some javascript errors in the console that come from the last line in your `eventMouseEnter` that is replacing the event element.  Instead of replacing the element with new html, you should just add the new properties to the element that is created by the calendar.

But if you just want to change the style, it would be much simpler to use CSS ":hover" for that instead of those callbacks.

**Comment by damjanvucina** [comment]
@Reiterkk were you ever able to fix this? I'm experiencing the same very issue.

Furthermore, this is the EventResizeDoneArg:

```
event: EventApi
_context: {dateEnv: DateEnv, options: {…}, pluginHooks: {…}, emitter: Emitter, dispatch: ƒ, …}
_def: undefined
_instance: null
allDay: [Exception: TypeError: Cannot read properties of undefined (reading 'allDay') at EventApi.get (http://localhost:3000/static/js/bundle.js:104860:24) at EventApi.<anonymous> (<anonymous>:1:29)]
allow: [Exception: TypeError: Cannot read properties of undefined (reading 'ui') at EventApi.get (http://localhost:3000/static/js/bundle.js:104917:24) at EventApi.<anonymous> (<anonymous>:1:29)]
backgroundColor: [Exception: TypeError: Cannot read properties of undefined (reading 'ui') at EventApi.get (
...
```
