### ISSUE TITLE
Tooltip is duplicated indefinitely when dragging in timeGridWeek view

### ISSUE THREAD

**Issue by azuken** [fullcalendar/fullcalendar#5078]
Hi,

I'm doing Fullcalendar migration from v3 to v4, and I have an issue with qTip generation. With v3, I instanciated qTip in `eventAfterRender` event, and everything worked fine.

Now, with `eventPositioned` event in v4, tooltip is recreated when you drag an event and move it (because event is fired at every pixel move).
For qTip, it shows it on the top left of screen, and with event, instead of be hidden.

I tought it was qTip library, so I switched with your own tooltip.js example (https://fullcalendar.io/docs/eventRender). It works fine in dayGrid mode (https://fullcalendar.io/docs/event-tooltip-demo), but I modified your codepen demo to have draggable function, and timeGridWeek view (like my app), and the issue is the same as qTip (but here we see all the created tooltips when you move). 

Same behaviour if I move tooltip code into `eventRender`.

So I think eventPositioned and eventRender are called too often in this view.

Here is a bug reproduction :

https://codepen.io/Azuken/pen/vYYGKRw

Is there a workaround or any plan to fix it ?

**Comment by acerix** [comment]
`eventRender` is the right place to attach the tooltip, but you should only attach it when `isMirror` is `false` so it doesn't get added to the event while it is being dragged:

https://codepen.io/acerix/pen/dyyXqdx?editors=0010

**Comment by azuken** [comment]
Thank you for your tip ! It works like a charm.

**Comment by VISAE** [comment]
Marvelous!!!

**Comment by GallitoMZ** [comment]
Thank you very much, it works for me too for **popover**.
