### ISSUE TITLE
Monthly view shows 6 rows for months with no days after row 5

### ISSUE THREAD

**Issue by stefanuebe** [fullcalendar/fullcalendar#5080]
The current version 4.3.1 of FC shows as last week in the monthly view always a week, that lays completely in the next month. Can be seen for instance in the demo on the FC's landing page.

![image](https://user-images.githubusercontent.com/36725474/66806037-cf772b00-ef26-11e9-8093-a6df63b53dd2.png)

**Comment by acerix** [comment]
I believe it's intentional so things don't change size when there is a month that does need 6 rows like June 2019.

I can see why you would not want the empty week to show though, so that could be a new feature.

**Comment by maximebochon** [comment]
I may be wrong in my understanding, but it looks very close to what is controlled by the `fixedWeekCount` boolean property.

Here is the documentation on that property: https://fullcalendar.io/docs/fixedWeekCount

**Comment by stefanuebe** [comment]
Yep, it's an added feature in v5, but the issue occured in v4 :)

**Comment by arshaw** [comment]
`fixedWeekCount` also existed in v4: https://fullcalendar.io/docs/v4/fixedWeekCount

**Comment by pabloroxo** [comment]
@maximebochon setting `fixedWeekCount` to `false` solved for me. thanks!
