### ISSUE TITLE
Fullcalendar scolling not working on specific iPhone devices(IPhone X and Iphone 8)

### ISSUE THREAD

**Issue by AshutoshRout-ABI** [fullcalendar/fullcalendar#5088]
We have implemented fullcalendar in Salesforce Lightning.For few users having IPhone  X and Iphone 8 are not able to scroll fullcalendar on these devices.Is there any fix available for such kind of issues.

Note :This is happening for few users

**Comment by acerix** [comment]
Would you be able to post a [runnable, stripped-down demonstration of the bug](http://fullcalendar.io/wiki/Reduced-Test-Cases/)? Would really appreciate it because the time saved reproducing will be time spent fixing.
