### ISSUE TITLE
Calling setOption within an event fetcher triggers an infinte loop when called before a success/error callback

### ISSUE THREAD

**Issue by mattschlosser** [fullcalendar/fullcalendar#5091]
[Minimum Running Example Here](https://codepen.io/mattschlosser/pen/KKKgqjz)

I have come across an issue similar to #4160 and #3923 where trying to set an option for the calendar from within an event fetcher function triggers the event fetcher function again, causing an infinite loop, even when I hadn't turned off lazyFetching. 

The example is in a stable state. Fetching events should only happen upon switching views But if the success callback is called after setting the option like so...
```js
var calendarEl = document.getElementById('calendar')
var calendar = new FullCalendar.Calendar(calendarEl,{
  plugins: ['timeGrid', 'interaction']
})
calendar.addEventSource( function(info, ok, err) {
  console.log("REFETCHING EVENTS")
  
// swap these two lines in the demo
  calendar.setOption('selectConstraint', {});
  ok({});
})
calendar.render();
```

then, this creates an infinite loop. I don't know if this is a bug or should be placed in the documentation that `setOption` should only be called after calling the success/error callbacks have been called. Hopefully, this issue helps someone in the future facing the same issue 😃 

Can someone explain why this behaviour happens?

**Comment by acerix** [comment]
Thanks for the report.  It seems like a bug to me because `setOption` is not supposed to refetch any events and also because it works when setOption is moved after the success function.

**Comment by dariovinci** [comment]
this is still present in 5.0.0 beta 1 . Any workaround ?

i need to set business hours after fetching event

**Comment by arshaw** [comment]
i'm going to fix this for the next release, beta or not

**Comment by dariovinci** [comment]
Hello @arshaw did you find a solution for this? is there any workaround i can use meanwhile you fix it?

**Comment by acsar** [comment]
I solved it like this:

`var runLoad = false; <=======

var setOptions = function() {
                    
	fullcalendar.setOption('minTime', minTime);
    fullcalendar.setOption('maxTime', maxTime);
    fullcalendar.setOption('slotDuration', moment().set({ hour: 0, minutes: slotDuration }).format('HH:mm'));
    fullcalendar.setOption('businessHours', businessHours);
    fullcalendar.setOption('selectConstraint', businessHours);
    
	runLoad = true; <======= 
    
	fullcalendar.refetchEvents();
	
}

var get_events = function() {

	if(!runLoad) return
	...
	
}`

**Comment by arshaw** [comment]
fixed in v5, [which has just been officially released](https://fullcalendar.io/blog/2020/06/v5-official)

https://codepen.io/arshaw/pen/JjGNYGN?editable=true&editors=001
(you'll see only one console.log instead of infinite)
