### ISSUE TITLE
Stacking of header sections on small screens

### ISSUE THREAD

**Issue by lalo4ka** [fullcalendar/fullcalendar#5093]
I just did some nice changes in CSS that I would like to share it.

before: 
![image](https://user-images.githubusercontent.com/1745823/67120104-35c1af00-f1ae-11e9-8b6e-593a1f925fd9.png)

Afer:
![image](https://user-images.githubusercontent.com/1745823/67119897-b8963a00-f1ad-11e9-9d96-be54bd854e05.png)

@media (max-width: 768px) {
  .fc-toolbar {
    flex-wrap: wrap;
  }
  .fc-toolbar > div {
    float: left !important;
    width: 100%;
    margin: 4px 0;
  }
  .fc-center {
    order: 1;
  }
  .fc-right {
    order: 2;
  }
  .fc-left {
    order: 3;
  }
}

**Comment by arshaw** [comment]
thanks for the workaround!

this other issue captures the more general need:
https://github.com/fullcalendar/fullcalendar/issues/4638
&uarr;
Could you please visit the link, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates?
