### ISSUE TITLE
resourceOrder

### ISSUE THREAD

**Issue by iansheldon** [fullcalendar/fullcalendar#5094]
Hi

Thanks for the great calendar tool!  I purchased the timeline Resource and its working great, just having an issue with the resourceOrder.

I am ordering by two fields, complex name and order number (defined elsewhere in the database).  The complex name orders perfectly, but the number orders as if its a string (database value is Int).

<img width="317" alt="Screenshot 2019-10-19 at 16 12 56" src="https://user-images.githubusercontent.com/56677258/67147265-57dd2f00-f28b-11e9-8827-d361fc26633f.png">

This is the JS initialising the timeline.

```
document.addEventListener('DOMContentLoaded', function() {
		  
        var calendarEl = document.getElementById('bookingcalendar');

        var calendar = new FullCalendar.Calendar(calendarEl, {
		  plugins: ['resourceTimeline','interaction'],
		  schedulerLicenseKey: 'xxxxx',
		  resourceLabelText: 'Properties',
		  aspectRatio: 2,
		  slotLabelFormat: { weekday: 'short',day: 'numeric' },
		  resourceGroupField: 'parentid',
  		  defaultView: 'resourceTimelineMonth',
		  resources: "scripts/_getresources.php",
		  resourceOrder: 'parentid,no',
		  eventSources: [{url:'scripts/_getallbookings.php'},{url:'scripts/_allicalcalendars.php'}],
		   resourceRender: function(info) {
			
			var clickable = document.createElement('strong');
			clickable.innerHTML = '&nbsp;<a href="scripts/_gettoken.php?token='+info.resource.id+'"><i class="fad fa-calendar-alt"></i></a>';

			info.el.querySelector('.fc-cell-text')
			  .appendChild(clickable);
		  }
			
        });

        calendar.render();
      });

```

And finally, the JSON providing the data....

`{"id":"267","title":"Playa Park 1","parentid":"Playa Park","token":"v6OqrdVcB8EXpASHJ1eysjhQw","sortname":"Playa","no":"1"},{"id":"276","title":"Playa Park 3","parentid":"Playa Park","token":"7eBEuYKVkonxwTLhrjvlatSqd","sortname":"Playa","no":"3"},{"id":"184","title":"Playa Park 5","parentid":"Playa Park","token":"qZBM4FNtLPTQnp7iHYImJKgOW","sortname":"Playa","no":"5"},{"id":"223","title":"Playa Park 6","parentid":"Playa Park","token":"xL2SNmn5IyJ1KU6wuqpYBojh9","sortname":"Playa","no":"6"},{"id":"215","title":"Playa Park 7","parentid":"Playa Park","token":"FMmtjpNdWCOPn8wBQur51fb3J","sortname":"Playa","no":"7"},{"id":"253","title":"Playa Park 16","parentid":"Playa Park","token":"FcibWGf3jT9XDBUmvusLHKV5C","sortname":"Playa","no":"16"},{"id":"187","title":"Playa Park 33","parentid":"Playa Park","token":"Ex5eU16NoGDr08kIsd9fWiwtj","sortname":"Playa","no":"33"},{"id":"190","title":"Playa Park 45","parentid":"Playa Park","token":"0Ka75wukGCiYUSTvb4fjsRc3X","sortname":"Playa","no":"45"},{"id":"186","title":"Playa Park 46","parentid":"Playa Park","token":"rnAbzGIx28jPKstp9h76SulO1","sortname":"Playa","no":"46"}`

So the ordering should show 1,3,5,6,7,16,33,45,46

The documentation seems to suggest if I don't provide an order then it will use the order provided by the JSON.  But I've found it goes a bit crazy and doesn't respect the order at all.

<img width="304" alt="Screenshot 2019-10-19 at 16 15 32" src="https://user-images.githubusercontent.com/56677258/67147305-b1455e00-f28b-11e9-96ac-3305b4ac6767.png">

Am I missing something?

Thanks!
Ian

**Comment by acerix** [comment]
Would you be able to post a [runnable, stripped-down demonstration of the bug](http://fullcalendar.io/wiki/Reduced-Test-Cases/)? Would really appreciate it because the time saved reproducing will be time spent fixing.
