### ISSUE TITLE
'Intl' is undefined in IE10

### ISSUE THREAD

**Issue by rohinmvp** [fullcalendar/fullcalendar#5096]
I have a SharePoint application where I am trying to use fullcalendar.
When the website is opened in IE 11, the compatibility us changed to IE10, and I am getting this error.

Is there any workaround?

Everything is loading fine in Firefox and Chrome.

SCRIPT5009: 'Intl' is undefined
demos.js (36,48055)

To reproduce the issue, open the fullcalendar demos in IE10 or compatibility mode.
![Intl](https://user-images.githubusercontent.com/29095628/67199382-c6062b00-f41e-11e9-90d0-9f8f1fb571f5.PNG)

**Comment by acerix** [comment]
Only IE11+ is supported as of version 4.  You could try adding polyfills or use version 3.
