### ISSUE TITLE
Customize title so it says "Week of [first day of week]"

### ISSUE THREAD

**Issue by damienmckenna** [fullcalendar/fullcalendar#5098]
I've been trying to work out how to do this but have not been able to do so.

For this project our client is requesting that the calendar title say "Week of [first day of week]" instead of the typical range-based string. Is this possible? Looking at computeTitle() it seems to be hardcoded to only work with ranges.

**Comment by acerix** [comment]
There is an open request for customizing header elements which would make this possible:

https://github.com/fullcalendar/fullcalendar/issues/496
↑
Please visit the above issue, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates.

There is a demo posted there showing how to customize the header for now:

https://codepen.io/frlinw/pen/VNbRLL

**Comment by damienmckenna** [comment]
Thanks for letting me know about that.

For what it's worth, I ended up hiding the standard header and recreating it server-side.
