### ISSUE TITLE
Events are overlapping even if slotEventOverlap and eventOverlap is set to false

### ISSUE THREAD

**Issue by abhishek-malviya-au1** [fullcalendar/fullcalendar#5100]
<full-calendar
            #calendar
            [header]="headerJSON"
            defaultView="timeGridWeek"
            [plugins]="calendarPlugins"
            [weekends]="true"
            [firstDay]="firstDay"
            editable="false"
            [droppable]="droppable"
            [draggable]="draggable"
            navLinks="true"
            [selectable]="selectable"
            eventLimit="true"
            allDayText=""
            slotEventOverlap="false"
            eventOverlap = "false"
            [scrollTime]="scrollTime"
            [displayEventTime]="displayEventTime"
            timeGridEventMinHeight="1px"
            nowIndicator="true"
            (datesRender)="calendarDatesChanged($event)"
            [events]="eventsArray"
            [slotDuration]="slotDuration"
            (eventClick)="eventClicked($event)"
            (eventMouseEnter)="eventMouseEntered($event)"
            (eventMouseLeave)="eventMouseLeft($event)"
            (dateClick)="calendarDateClick($event)"
          ></full-calendar>
![Screenshot from 2019-10-22 19-39-39](https://user-images.githubusercontent.com/47751567/67294840-ff649680-f503-11e9-947b-72f4c3b45d7a.png)

There are two appointments at 9:30AM but they are overlapped.

**Comment by acerix** [comment]
Would you be able to post a [runnable, stripped-down demonstration of the bug](http://fullcalendar.io/wiki/Reduced-Test-Cases/)? Would really appreciate it because the time saved reproducing will be time spent fixing.
