### ISSUE TITLE
BUG: Title not updating on change of view of a Timeline

### ISSUE THREAD

**Issue by Glenny088** [fullcalendar/fullcalendar#5101]
FullCalendar: v3.3.0
FullCalendar Scheduler v1.6.0
JQuery: v2.2.4
MomentJs: v2.14.1

Code example:
[codepen.io](https://codepen.io/Sparker88/pen/LYYxaqx)

The default view is timelineDay, when I click in the toolbar on Week and then Month, the title changes as expected.
But when I click on Week or Day afterwards, the title keeps the Month display and doesn't change anymore.

**Comment by acerix** [comment]
The bug is no longer present using the latest version 3 release and updated dependencies:

https://codepen.io/acerix/pen/MWWpYdp?editors=001
