### ISSUE TITLE
event limit for resourceTimeline view

### ISSUE THREAD

**Issue by janchua** [fullcalendar/fullcalendar#5102]
Hi,

I am trying to add `eventLimit` into a resourceTimelineWeek view and unfortunately, it's not being applied.

**Comment by acerix** [comment]
I believe this existing ticket captures this need:
https://github.com/fullcalendar/fullcalendar/issues/4827
↑
Please visit the above issue, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates.
