### ISSUE TITLE
Delaying eventSources

### ISSUE THREAD

**Issue by rodrigoguariento** [fullcalendar/fullcalendar#5103]
It's hard to explain but I'll try: when someone try to see a day in the future, they use to click in Next many times fast until there. Each click my eventSources is being called. Is there a way to delay each calling to eventSources? I tried to use rerenderDelay but the purpose of this is another. I'm trying to avoid many background requests with no need. Thanks.

**Comment by acerix** [comment]
I believe this existing ticket captures this need:
https://github.com/fullcalendar/fullcalendar/issues/268
↑
Please visit the above issue, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates.
