### ISSUE TITLE
Multi-day schedule daylist display

### ISSUE THREAD

**Issue by HaoDaYiGuoFan** [fullcalendar/fullcalendar#5109]
Hello, I found a problem. In the cross-day schedule, the start and end time displayed under the daylist is easy to mislead;

For example, my schedule time range is 10.24 08:00:00 ~ 10.26 15:00:00
At this time, under the daylist, 10.24 is displayed as 08:00:00 - 00:00:00 (12h will be displayed as 12am), which is easy to mislead.
So I changed it to 08:00:00 - 23:59:59

Change the renderSegHtml() method section under /list/main.js to the following way
  Seg.end = new Date(seg.end.setTime(seg.end.setSeconds(seg.end.getSeconds() - 1)));
     If (seg.isStart) {
         //timeHtml = core.htmlEscape(this._getTimeText(eventInstance.range.start, seg.end, false // allDay source code
         timeHtml = core.htmlEscape(this._getTimeText(eventInstance.range.start, seg.end, false // allDay changed code
         ));
     }
after:
![image](https://user-images.githubusercontent.com/24630361/67552358-85b7ed00-f73d-11e9-8032-e61a7d92fbb3.png)

**Comment by acerix** [comment]
Would you be able to post a [runnable, stripped-down demonstration of the bug](http://fullcalendar.io/wiki/Reduced-Test-Cases/)? Would really appreciate it because the time saved reproducing will be time spent fixing.
