### ISSUE TITLE
EventRender - info.el coming back empty

### ISSUE THREAD

**Issue by eamello** [fullcalendar/fullcalendar#5113]
Hi there,

I am trying to use the bind function to the element coming from info.el in EventRender and the el is coming back empty. I was using an old version of fullcalendar and the element is there and I could use the bind function:
element.bind('contextmenu',function(e){ ... }
Is this a bug?

**Comment by eamello** [comment]
Hi there, 
Could anyone answer this question? I am a paid customer.

**Comment by acerix** [comment]
Would you be able to post a [runnable, stripped-down demonstration of the bug](http://fullcalendar.io/wiki/Reduced-Test-Cases/)? Would really appreciate it because the time saved reproducing will be time spent fixing.
