### ISSUE TITLE
Eary calendar

### ISSUE THREAD

**Issue by subweb** [fullcalendar/fullcalendar#5115]
### Bug Reports
You MUST post a recreation or else your issue will be CLOSED without explanation.
Instructions: https://fullcalendar.io/reporting-bugs

### Feature Requests
Search the issue tracker for an existing ticket before creating a new one.
Instructions: https://fullcalendar.io/requesting-features

### React/Vue/Angular/etc
If your bug is specific to one of these frameworks, use the corresponding tracker.
List: https://github.com/fullcalendar

(Please erase the above text and begin typing. Thanks!)
Hello
is possible to have a year calendar?

**Comment by acerix** [comment]
The timeline view can show a full year and there are requests for new year views:

https://github.com/fullcalendar/fullcalendar/issues/1140
https://github.com/fullcalendar/fullcalendar/issues/2525

↑
Please visit the above issue, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates.
