### ISSUE TITLE
Ability to add CSS classes to custom buttons

### ISSUE THREAD

**Issue by quantumwebco** [fullcalendar/fullcalendar#5117]
Is there a way to add a custom class to a custom button?

In the docs it says buttons have

text 
click
icon
bootstrapFontAwesome 

Is there any way to do something like
```
customButtons: {
    myCustomButton: {
      text: 'custom!',
      class: 'btn-sm',
      click: function() {
        alert('clicked the custom button!');
      }
    }
```
And the class property gets added to the class list of the custom button element

**Comment by acerix** [comment]
It is not built-in but I see how that could be a useful feature. For now you could use viewSkeletonRender like this:

https://codepen.io/acerix/pen/jOOYypP?editors=0110

**Comment by quantumwebco** [comment]
OK I'll use the callback for now. Thanks a lot!

**Comment by jag2136** [comment]
I'd like to request this as well - running a post-render selector based on a hardcoded button string is obviously slow and inefficient, and if you're relying on adding classes for styling purposes, then the styling might now actually take effect on the user's browser until AFTER the buttons have already rendered.

I looked briefly at the `Toolbar.ts` source for custom button code, and it doesn't look like it would be too hard to just add another `customButtonParams` attribute for classes that gets appended on to the `buttonClasses` array.

**Comment by blairdrivescout** [comment]
i'd like to point out the if you use the "viewSkeletonRender" hook to add classes to the buttons manually, if you change the date in the cal, you lose the added classes

**Comment by jaapz** [comment]
I think this issue should not be closed because adding a class to custom buttons would be very helpful!

**Comment by jaapz** [comment]
Would be even greater if we had some kind of way to implement our own button or toolbar views, but that would probably be out of scope for this issue. My use case for this is adding bootstrap dropdowns, for example, to switch between several modes. I'd also like to add some kind of "on/off" switch or radio buttons in the toolbar

**Comment by jaapz** [comment]
Why are you closing this issue? The issue of adding css class to buttons is still valid.

**Comment by acerix** [comment]
@jaapz  It seems the original requestor is not interested in this, you could open a new issue for the same.

**Comment by jaapz** [comment]
Sure, no problem
