### ISSUE TITLE
Click Event on ResourceGroupText

### ISSUE THREAD

**Issue by mpitchandi** [fullcalendar/fullcalendar#5121]
### Feature Requests
In  resourceTimeline view, we are displaying different type of resource under different grouping.
All resource are group by resourcegroupText.

Is that any way we can enable click event on resource group field, by passing dynamic parameter to it.

MVC/c#/Jquery

**Comment by acerix** [comment]
It's not built-in but could be useful as a new feature.  I believe you can attach a click callback manually from [viewSkeletonRender](https://fullcalendar.io/docs/viewSkeletonRender).

**Comment by arshaw** [comment]
it'll be pretty easy to attach handlers in the *DidMount hooks in v5: https://fullcalendar.io/docs/resource-group-render-hooks
