### ISSUE TITLE
scrollTime not working in resourceTimeGridDay if css calendar.max-width=100%

### ISSUE THREAD

**Issue by ibowditch** [fullcalendar/fullcalendar#5122]
It works fine if css calendar.max-width is 900px as in the example https://fullcalendar.io/docs/vertical-resource-resourceRender-demo, but if you change it to max-width: 100%;  (or 1500px) it does not scroll to the default '06:00:00' start time.

Setting the scrollTime option manually or calling scrollToTime doesn't fix this either.

 I only tested on Chrome at this stage.

[resTimeGrid.zip](https://github.com/fullcalendar/fullcalendar/files/3817795/resTimeGrid.zip)

**Comment by acerix** [comment]
The issue is that your calendar is so tall that the entire time grid is visible so there is nothing to scroll.  You could limit the height so enough of the grid is hidden to make it possible to scroll to that time:

https://codepen.io/acerix/pen/zYYjyMw?editors=0010

**Comment by ibowditch** [comment]
Thanks very much for your prompt response! Much appreciated.
