### ISSUE TITLE
How remove all events in v4?

### ISSUE THREAD

**Issue by 89466598946659** [fullcalendar/fullcalendar#5123]
### Feature Requests
I can't find **removeEvents** or **addEvents** in the v4 docs. Only find **removeEvent** and **addEvent**.
How can I remove all events or add multiple events once? Just can one by one?

**Comment by 89466598946659** [comment]
The doc: https://fullcalendar.io/docs/event-model

**Comment by dvd73** [comment]
It is required to remove banch of events like this:
```
$('#calendar').fullCalendar('removeEvents', function(e){
					return $.grep(eventsToBeRemoved, function(_){ return _.id == e.id}).length > 0; 
				});	
```

**Comment by acerix** [comment]
You can use `getEvents` to get the all events then `event.remove` on each.

https://fullcalendar.io/docs/upgrading-from-v3#event-model
