### ISSUE TITLE
In Custom View it is not possible to move back in time more than one time

### ISSUE THREAD

**Issue by masrlinu** [fullcalendar/fullcalendar#5125]
recreation of the error:

https://codepen.io/masr/pen/LYYrvBL

You are just able to press the left button (to go back in time) one time and not multiple times.

**Comment by acerix** [comment]
I believe this existing ticket captures this need:
https://github.com/fullcalendar/fullcalendar/issues/4678
↑
Please visit the above issue, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates.
