### ISSUE TITLE
Korean month unit is duplicated in IE11

### ISSUE THREAD

**Issue by pluto94cokr** [fullcalendar/fullcalendar#5128]
I changed my language to Korea and there is an error in the monthly unit of the calendar.
In Korea, '월' is a unit of the month .
So it should be marked as "2019년 11월", not "2019년 11월월".
What can I modify and mark "월월" as a "월"?
str_replace("월월","월",$month);

http://iebiz.ifkn.net/temp.html

`	var calendar = new Calendar(calendarEl, {
		plugins: [ 'interaction', 'dayGrid', 'timeGrid', 'list' ],
		header: {
			left: 'prev,next today',
			center: 'title',
			right: 'dayGridMonth,timeGridWeek,timeGridDay,listWeek'
		},
		editable: true,
		droppable: true, // this allows things to be dropped onto the calendar
		drop: function(arg) {
		// is the "remove after drop" checkbox checked?
		//if (document.getElementById('drop-remove').checked) {
		// if so, remove the element from the "Draggable Events" list
		//arg.draggedEl.parentNode.removeChild(arg.draggedEl);
		//}
		},
		locale: 'ko'
	});`

**Comment by pluto94cokr** [comment]
I am not sure how to amend the list section, although I have modified the other part.
`views: {
				dayGridMonth: {
					titleFormat: {
						month: 'short',
						year: 'numeric'
					}
				},
				day: {
					titleFormat: {
						day: 'numeric',
						month: 'short',
						year: 'numeric'
					}
				}
			}`

**Comment by acerix** [comment]
I can see the month unit is displayed twice in IE 11 when the day number is also included, but in other browsers it only shows once as expected. This demo shows the difference between browsers which looks like a bug in IE 11:

https://codepen.io/acerix/pen/ExxpGYz?editors=0011

Starting in version 4, the calendar dates are rendered by the browser, so if you want to render them differently you can use a formatting plugin like moment.js:

https://fullcalendar.io/docs/moment-plugins

**Comment by arshaw** [comment]
I'm afraid this is an issue with IE's implementation of the Intl API. For now, we'll consider this out of FullCalendar's scope. The workaround is to use moment as @acerix said
