### ISSUE TITLE
Listen for prev and next button clicks

### ISSUE THREAD

**Issue by andre-idrive** [fullcalendar/fullcalendar#5131]
I need a function in my controller to run when one of the header buttons (that changes the month and/or year) is clicked. That function needs to received the month and year that the user is now viewing. 

1. Is there any data that comes back after those arrow buttons are clicked in the same way data comes back when a user clicks on a date?
2. Is there a built in way to listen for that click?

**Comment by acerix** [comment]
I believe this existing ticket captures this need:
https://github.com/fullcalendar/fullcalendar/issues/3521
↑
Please visit the above issue, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates.

For now, you could replace them with custom buttons:

https://fullcalendar.io/docs/customButtons

**Comment by andre-idrive** [comment]
The referenced issue wasn't all the way clear to me but it did lead me to the right answer. For those still looking for an answer to this question, add an "events" callback/handler (i.e. "events:") to your calendar object. You app will his this callback every time you click the navigation arrows.

```
var calendar = new FullCalendar.Calendar(calendarEl, {
    events: // function or array or json object goes here
});
```

**Comment by lodnert** [comment]
This should probably be better documented on the docs-site. I found alot of references to v3 before finding this
