### ISSUE TITLE
Avoid re-rendering events if their position does not change

### ISSUE THREAD

**Issue by tomgard** [fullcalendar/fullcalendar#5132]
V3 fullcalendar with scheduler plugin.
I have discovered that methods such as "renderEvent", "renderEvents" and "removeEvents" when called cause all events to re-render in the scheduler timeline view. This can be observed by adding a console.log in the eventRender callback and calling one of the above functions.

This should be considered a bug as a events that are not within the same resource could not be effected by the individual event change/delete. This would heavily reduce renders.

No example needed as this is the default behaviour of fullcalendar.

**Comment by acerix** [comment]
( From https://fullcalendar.freshdesk.com/a/tickets/1316 )

**Comment by arshaw** [comment]
this has been implemented in v5
