### ISSUE TITLE
businessHours not displayed correctly when allDayDefault is true

### ISSUE THREAD

**Issue by Emsal92** [fullcalendar/fullcalendar#5135]
When I started creating this issue I didn't know why the business hour logic didn't work. When I tried to recreate the error I found that removing the `allDayDefault: true` property fixed my issue.

Issue:
https://codepen.io/Emsal/pen/XWWyXvw

**Comment by acerix** [comment]
It looks as expected to me, what is the issue?

**Comment by Emsal92** [comment]
> By default, allDayDefault is not set. As a result, any Event Objects that do not specify an allDay property will be subject the guessing behavior mentioned in the Event Object article.

1. Event 2,3,4 and 5 are clearly not all day events, but when using the attribute all of the events are shown as allday events.

2. Business Hours are not highlighted correctly when using the attribute.

Maybe it's just me who doesn't understand what `allDayDefault: true` actually does.

**Comment by acerix** [comment]
Only events without a time of day show in the "all day" slot, but you can force events that have a time to show there by setting `allDay:True`. Setting `allDayDefault` means that all events will have `allDay:True` by default.

Business Hours has nothing to do with that, it just highlights some cells.  I don't see any issue with the highlighting and it doesn't change by changing `allDayDefault`.

**Comment by Emsal92** [comment]
How can you not see the difference in background color?
`allDayDefault attribute removed`: https://imgur.com/dKjYKvd
`allDayDefault: true`: https://imgur.com/Gkp4UCt

**Comment by acerix** [comment]
I see the issue now. I was just commenting out the `allDayDefault` line in your example and didn't notice that it is setting it to `false`.

https://codepen.io/acerix/pen/xxxQYQE?&editable=true&editors=001

**Comment by arshaw** [comment]
what a bizarre bug. anyway, it's fixed in v5: https://codepen.io/arshaw/pen/XWXeBOJ?editable=true&editors=001
