### ISSUE TITLE
Specify Accept header for JSON requests

### ISSUE THREAD

**Issue by Mushr0000m** [fullcalendar/fullcalendar#5137]
When using eventSources to fetch JSON from an API, the request have in the header : `Accept: '*'` it should be possible to change this to have a valid `Accept: application/json` so a backend API will return valid response format.

Can be visible on the base demo looking in the xhr request : https://codepen.io/pen/?&editable=true&editors=001

**Comment by acerix** [comment]
It makes sense to specify that header on JSON requests since only JSON is accepted.  

For now, you could provide events "as a function" and set the header there:

https://fullcalendar.io/docs/events-function

**Comment by arshaw** [comment]
we probably won't expose a hook for directly adding headers, but here's another issue that would give you an appropriate place to add this logic yourself:
https://github.com/fullcalendar/fullcalendar/issues/4627
&uarr;
Could you please visit the link, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates?
