### ISSUE TITLE
SnapDuration cannot select more than 1 timeslot at a time

### ISSUE THREAD

**Issue by gsitu** [fullcalendar/fullcalendar#5142]
Hey, wanted to to be able to change my snap duration to select at an hour interval while the slot durations was still at 30mins. But changing the snap duration doesn't seem to work with this. You can see it in this [fiddle](https://jsfiddle.net/op5298ds/6/).

I'm currently using jquery to render this view. 

It's something similar to this issue a while ago https://github.com/fullcalendar/fullcalendar/issues/2736

**Comment by gsitu** [comment]
Looks like it has something to do with the wholeDivideDurations core/main.js. Since we're only allowing whole number divisions smaller ratios do not work.

**Comment by acerix** [comment]
I believe this existing ticket captures this need:
https://github.com/fullcalendar/fullcalendar/issues/4865
↑
Please visit the above issue, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates.
