### ISSUE TITLE
Set columnHeaderText based on calendar information like view, events

### ISSUE THREAD

**Issue by Phibedy** [fullcalendar/fullcalendar#5147]
I am using React and would like to set the `columnHeaderText` based on the view and add some information based on the events shown at that day.

I am facing two problems:
* I can't access the calendar in  `columnHeaderText`. The method just gives the date and no access to the calendar/view currently shown. If I create a ref, the ref.current is sometimes undefined (in the first run).
* I am using a callback to set the events, therefore the events are not there yet when `columnHeaderText` is called. Atm I call calendar.render() after fetching the events.

Possible solutions:
* Provide the calendar as a second parameter in `columnHeaderText`
* Provide a method to only rerender the skeleton/headers

Hacks I use:
* Use the view passed to the calendar if the calender-ref is not set.
* Rerender whole calender after each fetch.

I am fine which rerendering the whole calendar after each fetch, but it would be great to have calendar information in `columnHeaderText` without using refs.

**Comment by acerix** [comment]
The issue is that the column header is rendered before the events. 

You could use `columnHeaderHtml` to add placeholder elements, then you can add content to those elements after the view/elements are rendered.

**Comment by Phibedy** [comment]
That's a good idea :+1: 
Is there a callback that is called after all events were rendered?

**Comment by acerix** [comment]
There is no callback when events are all rendered anymore since events are never considered "fully rendered".

You could supply your events "as a function" and update the header from that function, eg. after `successCallback`.

https://fullcalendar.io/docs/events-function

**Comment by Phibedy** [comment]
I am already using events-function so I will go with that, thank you :+1:

**Comment by arshaw** [comment]
You could use [dayHeaderContent](https://fullcalendar.io/docs/day-header-render-hooks) with a function that relies on outside data. When you know that data changes, you could call [Calendar::render](https://fullcalendar.io/docs/Calendar-render) to force the render logic re-execute

**Comment by Glideh** [comment]
If we add a render for example after en eventSource is loaded, itsn't going to render twice the whole thing each time ?
