### ISSUE TITLE
### Feature Requests (eventResize and eventDrop had same old event name)

### ISSUE THREAD

**Issue by Dev1lDragon** [fullcalendar/fullcalendar#5151]
now `eventResize` contain `oldEvent` and  `eventDrop` contain `prevEvent`.
Solution is to rename objects to had same name.

**Comment by acerix** [comment]
I believe this existing ticket captures this need:
https://github.com/fullcalendar/fullcalendar/issues/4745
↑
Please visit the above issue, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates.
