### ISSUE TITLE
dividerRender for resourceGroups

### ISSUE THREAD

**Issue by gotjoshua** [fullcalendar/fullcalendar#5152]
### Feature Request:

We need a hook to alter the divider(s), both for the resource list and for the main timeline dividers.

In essence we want to adapt the way the dividers look (adding info graphics when the resource group is collapsed).
We also want the row for the resource group dividers to have the resource group id as a DOM id (for easier querying)

I jqHacked my way in there but its much uglier than what is possible via:
resourceRender, and eventRender...

**Comment by acerix** [comment]
To confirm, by "dividers" do you mean the rows for each resource group, like "460 Bryant" in this example?

https://fullcalendar.io/docs/timeline-resourceGroupField-demo

**Comment by gotjoshua** [comment]
Exactly!

Both In the Resource list (with "460 Bryant") and in the main timeline (empty divider).

I said divider, because thats what it is called in the code...

**Comment by gotjoshua** [comment]
Hello again, 
Do you accept this as a feature request?

**Comment by arshaw** [comment]
this is now possible with the "Lane Hooks" in v5: https://fullcalendar.io/docs/resource-group-render-hooks
