### ISSUE TITLE
Calls to setOption() before initial fetch completes cause unnecessary fetching of events

### ISSUE THREAD

**Issue by bodgerbarnett** [fullcalendar/fullcalendar#5155]
If I initialise my calendar like this:-

    var calendar = new FullCalendar.Calendar(calendarEl, {
        plugins: [ 'interaction', 'dayGrid' ],
        events: calendarEl.dataset.eventsUrl
    });

    calendar.render();

then the events URL is called once, as expected.

But I call setOption (on any method) afterwards, that causes the events URL to be called twice. In fact, it's called an extra time for every setOption I use:-

    var calendar = new FullCalendar.Calendar(calendarEl, {
        plugins: [ 'interaction', 'dayGrid' ],
        events: calendarEl.dataset.eventsUrl
    });

    calendar.setOption('selectable', true);

    calendar.render();

I need to call setOption in a separate call like this, rather than putting the options in the initialisation function but I don't want the URL to be hit repeatedly like this.

**Comment by acerix** [comment]
Would you be able to post a [runnable, stripped-down demonstration of the bug](http://fullcalendar.io/wiki/Reduced-Test-Cases/)? Would really appreciate it because the time saved reproducing will be time spent fixing.

I tested `setOption('selectable'` in the debug template and it doesn't refetch events:

https://codepen.io/acerix/pen/yLLmZda?editors=1011

**Comment by bodgerbarnett** [comment]
Interesting. I set up my calendar a little differently and it does seem to call the URL twice.

I've set up an example of it here -> https://codepen.io/Bodger/pen/jOEOzNg?editors=1011

You'll see that the URL is called twice because of the setOption. It's not a valid calendar URL because I'm not aware of a public one but it doesn't make any difference really.

**Comment by acerix** [comment]
Thanks, I can see `setOption` causes events to be fetched if it's called before `render()` so it seems like a bug.

https://codepen.io/acerix/pen/yLLmZda?editors=0011

Although `setOption` is intended to change settings after the calendar was rendered, any initial settings should be specific when initializing the calendar instead.

**Comment by bodgerbarnett** [comment]
Ah yes, sorry, I left it that way round on the codepen but I'm actually using it with the call to setOption after the render and that causes multiple fetches too.

I noticed the same behaviour in version 3 but I think that turned out to be related to lazyFetching, where I haven't set lazyFetching on this one, so maybe that's not related in this case?

**Comment by acerix** [comment]
It seems to happen if the initial fetch is not complete when `setOption` is called, it works if a delay is added:

https://codepen.io/acerix/pen/MWYYmbZ?editors=0011

The timeout won't be reliable, but you could supply the events as a function and call setOption at the end of that function so it's called after the initial fetch.

`lazyFetching` is on by default, if that is `false`, then every call to setOption refetches events.

**Comment by arshaw** [comment]
this no longer happens in v5: https://codepen.io/arshaw/pen/WNrZgeP?editable=true&editors=001
