### ISSUE TITLE
popover events doesn't trigger eventClick function on FullCalendar v4

### ISSUE THREAD

**Issue by molinetmoli** [fullcalendar/fullcalendar#5156]
I have a custom calendar with this setup:

`{
			locale : 'en',
			plugins : ['dayGrid','timeGrid','list','interaction'],
			header : {
				left : 'prev,next today',
				center : 'title',
				right : 'dayGridWeek, dayGridMonth, dayGridDay'
			},
			allDaySlot : false,
			aspectRatio : 1.8,
			displayEventTime : false,
			editable : false,
			navLinks : true,
			eventLimit : true,
			views : {
				dayGridMonth : {
					eventLimit : 2
				}
			},
			events : this.eventLIST,
			eventClick : this.calendareventClick,
			eventRender : this.calendareventRender,
			eventLimitClick : this.calendareventlimitClick
}`

`calendareventClick`, `calendareventRender` and `calendareventlimitClick` are custom methods.

eventClick works fine unless you're clicking on a 'more' popover event which trigger eventRender instead of eventClick and doesn't allows me to fullfill same behaviour.

I'm working with `lightning-web-components`. Could be because of this? Or is there some kind of param/s I need to set on calendar mapper for this to work properly?

**Comment by acerix** [comment]
Would you be able to post a [runnable, stripped-down demonstration of the bug](http://fullcalendar.io/wiki/Reduced-Test-Cases/)? Would really appreciate it because the time saved reproducing will be time spent fixing.
