### ISSUE TITLE
Ability to expand resource column in monthly timeline 

### ISSUE THREAD

**Issue by alexanderwhatley** [fullcalendar/fullcalendar#5160]
Not sure if this feature exists already, but I could not find it anywhere. Is there a way to expand the columns in the monthly timeline, to better view an event that spans say only 1 or 2 days?

**Comment by acerix** [comment]
If you mean expanding horizontally to show more time, you can do that by changing the range of the view.

Otherwise I'm not sure what you mean, it will help if you can post a mockup image of how it should expand.

**Comment by alexanderwhatley** [comment]
Apologies for the unclear question. I was wondering if there was a way to manually adjust the slotWidth (say if the column is very narrow, the user could enlarge it to make it wider.) Does that make sense?

**Comment by acerix** [comment]
You can change slotWidth based on the event data but that applies to all columns.

If you mean having some columns with different widths, that would not work in timeline view, the slotWidth has to be the same for all columns, but you could make a custom view to work like that.

https://fullcalendar.io/docs/custom-view-with-js
