### ISSUE TITLE
Export util functions, types and classes in main.ts files so modules can be resolved

### ISSUE THREAD

**Issue by MrRious** [fullcalendar/fullcalendar#5165]
We're using fullcalendar in Angular (but not the fullcalendar-angular component). We want to build plugins with custom views etc.
It seems some util functions, types and classes are not exported in the main.ts files of their packages. This results in imports which can't be resolved.

For example the following app, which is a simple, small example, says that it needs to install the `@fullcalendar/core` package, which is in fact already installed:
https://stackblitz.com/edit/angular-cp1cdl

And on the local machine i get errors in VS Code and on the terminal.
`ERROR in ./src/app/app.component.ts
Module not found: Error: Can't resolve '@fullcalendar/core/util/html' in '/home/mrrious/dev/fc-test/src/app'`

PRs for fullcalendar and scheduler to export util functions, types and classes:
[#5163](https://github.com/fullcalendar/fullcalendar/pull/5163)
[#565](https://github.com/fullcalendar/fullcalendar-scheduler/pull/565)

**Comment by acerix** [comment]
Thanks for the explanation, demo and PRs.

**Comment by arshaw** [comment]
this is no longer an issue in v5. in v5 all exports are from the package root
