### ISSUE TITLE
event for next year not being loaded

### ISSUE THREAD

**Issue by barshamalbul** [fullcalendar/fullcalendar#5168]
i have a variable with json formatted data, which is loaded into the events 
the problem is that even though the data exists it is ignoring, the next year events 
listed below is a codepen, demonstrating the issue

https://codepen.io/barshamalbul/pen/MWYWNeE

**Comment by uasmirnov** [comment]
Up! I have a similar problem: some events (happy birthday icons) for next month and year not being rendered

![fullcalendar](https://user-images.githubusercontent.com/9690165/70063616-c2a2b980-15f0-11ea-99ff-f24e3fe69002.png)

**Comment by 21Junipers** [comment]
@barshamalbul  I believe your dates are formatted incorrectly. The month and day must contain the leading zero. For example:

    "title": "new year(Public Holiday)",
    "start": "2020-1-1"

Should be "start": "2020-01-01". I changed these in your code pen and the events show up as expected then.

HTH

**Comment by acerix** [comment]
Yes, the dates needs to be in [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format.
