### ISSUE TITLE
Dragging events when 2 calendar instances overlapping

### ISSUE THREAD

**Issue by OFMaurice** [fullcalendar/fullcalendar#5169]
Hi in my app i have rendered 2 calendar instances one in the background and one which is opened in a modal window. The calendar in the modal window is in front and the other is behind the modal window.

Example in Codepen (https://codepen.io/OFMaurice/pen/PowwPJV):

- red calendar is in background (z-index 1)
- white calendar is in front (z-index 2)

Steps to repdroduce:

- Try dragging events from white calendar around in the white are (working fine)
- Try dragging events from white calendar into the red overlapping area (dragging blocked)

For me its looks like the problem is in interaction/main.js in the HitDragging.prototype.queryHitForOffset function which is doing a wrong decision about what is the "best hit". Or if i am wrong any suggestions how i can make dragging in overlapping calendars possible?

PS: i dont want to drag the event into the red calendar, i want to keep it in the white calendar but in the overlapping area.

Best regards Maurice

**Comment by acerix** [comment]
I believe this existing ticket captures this need:
https://github.com/fullcalendar/fullcalendar/issues/5026
↑
Please visit the above issue, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates.
