### ISSUE TITLE
Unable to specify an http header from eventSources

### ISSUE THREAD

**Issue by Alexisgt01** [fullcalendar/fullcalendar#5170]
Hi, 

I use vue-fullcalendarjs 
Unable to specify an http header from eventSources 

Here is my code : 
```
eventSources: [
	{
		headers: {
			Authorization: `Bearer ` + localStorage.token,
		},
		url: 'http://dev.local:8081/api/events/calendar.json',
	},
],
```
I came across the problem : 
https://github.com/fullcalendar/fullcalendar/issues/5137

I need to pass the event as a function?

thank you

**Comment by acerix** [comment]
I believe this existing ticket captures this need:
https://github.com/fullcalendar/fullcalendar/issues/4627
↑
Please visit the above issue, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates.

For now, you need to supply the events as a function to get that control:

https://fullcalendar.io/docs/events-function
