### ISSUE TITLE
Set 'visibleRange' with view 'dayGridMonth'?

### ISSUE THREAD

**Issue by Alexisgt01** [fullcalendar/fullcalendar#5173]
Hi, 

I found a message on stackoverflow to configure 'visibleRange' with view 'dayGridMonth'
https://stackoverflow.com/questions/57495991/override-default-date-rage-for-daygridmonth-view

Apparently this has already been reported but I have not found this issues

what about that ?

Thank you

**Comment by acerix** [comment]
Would you be able to post a [runnable, stripped-down demonstration of the bug](http://fullcalendar.io/wiki/Reduced-Test-Cases/)? Would really appreciate it because the time saved reproducing will be time spent fixing.
