### ISSUE TITLE
fc-highlight element does not get rendered on touch devices

### ISSUE THREAD

**Issue by lllopo** [fullcalendar/fullcalendar#5175]
The issue is simple to reproduce. On a touch device (or simulator too), when a cell is touched in day or week view, there is no ".fc-highlight" element rendered. This can be easily verified in the DOM or the dayClick jsEvent path. 
Now, it is clear that this could be intentional and not a bug, BUT actually it is essential for giving a decent bounds for any additional actions, so it **should** work consistently across devices. In my case - for showing a popover when a cell is clicked. This very same thing works flawlessly on non-touch devices.

**Comment by acerix** [comment]
On touch there is a default delay of 1 second before selection:

https://fullcalendar.io/docs/longPressDelay

**Comment by lllopo** [comment]
I think you're missing the point. The thing is, that **when** dateClick fires the "fc-highlight" element is nowhere to be seen. No matter if it is immediately or after any kind of delay and this is inconsistent, I believe. To be honest, I get most stable reproduction of this in the Chrome simulator, yet - it happens.

**Comment by acerix** [comment]
When I do a "long press" touch in this demo, I can see the blue highlighting on the selected cells, do you mean you don't get that?

https://fullcalendar.io/docs/date-clicking-selecting-demo

It might help if you can post a [runnable, stripped-down demonstration](http://fullcalendar.io/wiki/Reduced-Test-Cases/) of the issue related to `dateClick`.

**Comment by lllopo** [comment]
@acerix no,no ...I'm not talking about long pressing, it doesn't work when I just click/touch. So, the 'select' event is ok, but forget about it. It's the 'dayClick' event that is left without physical target on touch devices. This is not nice. If it had no physical target on all devices, it would still be not nice, but at least it would be consistent. The current situation - target on desktop, no target on touch is both not nice and inconsistent. Even worse - it has a target on touch for month view, but not for the other views.
Besides - I find the long press to select quite counter intuitive for the user, but that's another story.

**Comment by acerix** [comment]
The "fc-highlight" element is only created if there is a selection which is why it isn't created on mobile unless there is a long press.

You can get the target that was clicked on in `dayClick` from `dateClickInfo.dayEl`.

**Comment by Dsyko** [comment]
I just ran into this bug as well, it's kind of unfortunate that we have to dig into the dayClick event and manually apply the highlight class to get around this. I understand that *technically* the day isn't selected on mobile unless the user does a long press. However users don't care about *technically correct* they just tap on things and expect them to select. Long pressing to select on mobile makes this feel broken, no users in any of our user testing have ever tried long pressing or knew it even existed.

**Comment by SmileSoftSr** [comment]
> I just ran into this bug as well, it's kind of unfortunate that we have to dig into the dayClick event and manually apply the select to get around this. I understand that _technically_ the day isn't selected on mobile unless the user does a long press. However users don't care about _technically correct_ they just tap on things and expect them to select. Long pressing to select on mobile makes this feel broken, no users in any of our user testing have ever tried long pressing or knew it even existed.
> 
> For those using v5 you can select the date on mobile when a user taps by adding a `dateClick` to the options:
> 
> ```
> dateClick: function (eventClickInfo) {
>     this.select(eventClickInfo.dateStr);
> }
> ```

I'd like to add that this works in v4 as well. Thanks @Dsyko!
