### ISSUE TITLE
Drag all day event to timeslot in Daily view should start with the viewed day

### ISSUE THREAD

**Issue by quorak** [fullcalendar/fullcalendar#5177]
### Feature Requests
If I look at a single day and want to move an all-day Event that has started 2 days ago to a timeslot of today, then, the start day value of the dragged event should be set to today and not to its initial day 2 days ago.

**Comment by acerix** [comment]
Would you be able to post a [runnable, stripped-down demonstration of the bug](http://fullcalendar.io/wiki/Reduced-Test-Cases/)? Would really appreciate it because the time saved reproducing will be time spent fixing.
