### ISSUE TITLE
At large widths too much space is allocated to the last time slot if the slot duration is less than 1 hour

### ISSUE THREAD

**Issue by edwin-lai** [fullcalendar/fullcalendar#5181]
**Steps to Reproduce**

1. Open the codepen [here](https://codepen.io/edwin-lai/pen/qBEZRGZ?&editable=true&editors=001)
2. Increase screen width to 1900px+
3. Check the width of the 11:30 pm time slot

**Comment by acerix** [comment]
I believe this existing ticket captures this need:
https://github.com/fullcalendar/fullcalendar/issues/4999
↑
Please visit the above issue, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates.
