### ISSUE TITLE
Event source function successCallback only accepts EventInput type, should allow anything because of eventDataTransform 

### ISSUE THREAD

**Issue by kamilchlebek** [fullcalendar/fullcalendar#5182]
I'm using event source function to fetch the events from API. Then to transform that events to match the fullcalendar model I'm using `eventDataTransform`. 

The problem is that I need to cast my model to `EventInput` before passing it to `successCallback` as it's not compatible. 

Wouldn't it be good if `successCallback` could receive `EventInput[] | any[]` (or something similar)?
I know I may do the model conversion inside custom event function, but why is the `eventDataTransform` called for that events?

**Comment by acerix** [comment]
Would you be able to post a [runnable, stripped-down demonstration of the issue](http://fullcalendar.io/wiki/Reduced-Test-Cases/)? Would really appreciate it because the time saved reproducing will be time spent fixing.

I tried this in React and don't get a type error:

**Comment by kamilchlebek** [comment]
Here's my simple demo of the issue - https://stackblitz.com/edit/typescript-2ywetc?file=index.ts 

It happens when you try to pass object with the same property name as inside `EventInput` but that is different type.

**Comment by arshaw** [comment]
hi @kamilchlebek . My comment here would also apply to this ticket: https://github.com/fullcalendar/fullcalendar/issues/5534#issuecomment-649816909
