### ISSUE TITLE
gotoDate is not working in v4

### ISSUE THREAD

**Issue by bondpati6** [fullcalendar/fullcalendar#5184]
i have upgraded from 2.1 to 4.3.1 and I have used the same in the url "https://fullcalendar.io/docs/Calendar-gotoDate". This application is hosted on salesforce and when i try to call gotoDate , it give me an error "Uncaught TypeError: calendar.gotoDate is not a function". 

I have checked the software and it is version 4.3.1.

for recreation, do it in salesforce, use the application to create the calendar and then create go to date, you will get the same error.

**Comment by acerix** [comment]
Would you be able to post a [runnable, stripped-down demonstration of the bug](http://fullcalendar.io/wiki/Reduced-Test-Cases/)? Would really appreciate it because the time saved reproducing will be time spent fixing.

It sounds like `calendar` is not actually a FullCalendar object.
