### ISSUE TITLE
Separate event limits and More buttons for different event types

### ISSUE THREAD

**Issue by pavitrakumar78** [fullcalendar/fullcalendar#5186]
Hi,

Is it possible in some way to modify the text/appearance of the `fc-more` in each day cell in the day view? 

Example of my use-case:

I'm building a calendar that displays a variety of events for a day. For example, assume there are 3 categories an event can be categorized - A, B, C. Each day can have any number of A-category events, B-category events etc., I want to display the no. of A-category events, no. of B-category events in the text which right now says `+<# total events>`. 

I want to make it appear something like this: `+<# A-category events>, +<# B-category events> ... `. This is just a simple example of what I want to build. If this is possible, then I could remove the text and add/inject CSS styling+simple HTML to display the no. of events in each category in small bubbles/circles (like notification). 

Edit: My other question was about how to override the popover events click. `eventLimitClick` is what I was looking for. Still can't find a solution for modifying the `fc-more` appearance.

**Comment by acerix** [comment]
That's not built-in and it would likely be complex to make it work based on event type, doing it yourself and injecting the html is probably easier.

**Comment by pavitrakumar78** [comment]
@acerix How can I detect when the rendering is done? It's better to inject after rendering a full calendar page right? I don't see any methods like `eventAfterAllRender` in v4 that was present in v3.

**Comment by acerix** [comment]
The events are never considered "completely rendered" which is why that was removed.  You can supply your events "as a function" then do the event processing in that function after `successCallback`.

**Comment by pavitrakumar78** [comment]
Ok, I understand the rendering part. 
But what I meant was. How do I know when to inject html into the `fc-more` element? `fc-more` appears only after all events are rendered for each day right? and the onrenderevent function is called for every event rendered, so I either I have to wait till all events are rendered and do some selection based on the `fc-more` class and then apply an edit to each function or do some bookkeeping for each day and events rendered so far and then modify `fc-more` based on it. Is the latter the only way to do it right now?

**Comment by acerix** [comment]
I suggest not using the built-in event limit or `fc-more` at all, instead make your own button that works for multiple types of event and inject that after the list of events.

**Comment by pavitrakumar78** [comment]
Right now, I'm just modeling an event itself as a button. I'm not sure if there is a better way.
I'm not sure what you mean by `inject that after the list of events`. How do I know when the events have been added to the calendar? I'm retrieving events using ajax from the server.

**Comment by acerix** [comment]
The events are added by calling `successCallback` so you would render you more buttons after that.

**Comment by pavitrakumar78** [comment]
I initially did not understand `successCallback` properly. I just played with a few examples and saw your previous comments. I think I get it now and this will be useful for me. This part:
```
events: function(fetchInfo, successCallback, failureCallback) {
        // ...
      }
```
Makes it clear to me what I can do :)
Thanks, @acerix !
