### ISSUE TITLE
Escape UTF-8 characters in CSS for compatibility

### ISSUE THREAD

**Issue by zaarin2k** [fullcalendar/fullcalendar#5187]
Within the source file, fullcalendar/packages/core/src/common/icons/_icons.scss, the CSS icon characters are written as ASCII codes, eg "\e900", however, the built CSS files have those characters converted to their unicode form, eg. "". Is it possible to keep them in their ASCII code form?

The reason I ask is that I publish within a system that messes the files up and we lose the unicode characters.

Source file:

 - /fullcalendar/packages/core/src/common/icons/_icons.scss [lines 24 to 42]

Built files (based off fullcalendar-4.3.1.zip):

 - /packages/core/main.css [lines 613 to 637]
 - /packages/core/main.min.css [line 1, column 9682 to column 9920]

**Comment by acerix** [comment]
It sounds like it's not possible using npm-sass so you will probably need a script to convert the UTF-8 CSS to ASCII.

https://github.com/sass/dart-sass/issues/79

**Comment by zaarin2k** [comment]
OK, that's fine. I have a workaround in place. Thanks for responding.
