### ISSUE TITLE
FullCalendar recurring events create duplicates

### ISSUE THREAD

**Issue by materally** [fullcalendar/fullcalendar#5192]
Hello!

I found a bug in FullCalendar getEvents() method.
If I load events (and this is recurring event) and it falls on the last column (in week view), then Calendar::getEvents() return duplicated event on that day.

Here you can see in console: https://codepen.io/matthew_gates/pen/QWwdvMz?editors=1010

**Comment by acerix** [comment]
`getEvents` returns all event instances that are in memory, not just visible ones.  

https://fullcalendar.io/docs/Calendar-getEvents

https://codepen.io/acerix/pen/mdyWWdY?editors=0010

**Comment by materally** [comment]
Try with "daysOfWeek" and put an event to Saturday (6):
![Képernyőfotó 2019-12-20 - 8 01 33](https://user-images.githubusercontent.com/21444748/71236380-202c4b00-22ff-11ea-8284-d26ab2b6e613.png)

**Comment by acerix** [comment]
I can see that getEvents is returning 2 instances when only 1 is visible, but that method returns "events in memory" not "events in the view" so it doesn't seem like a bug.

If you want all visible event instances, you can filter those events to remove any that are not in the view.

**Comment by materally** [comment]
And which memory? 
Because I have same problem at empty calendar.

**Comment by acerix** [comment]
Events can be in the calendar's memory even when they are not visible.

**Comment by Choripaix** [comment]
Having the same problem here! Don't know why, but the last week day events are duplicated.
