### ISSUE TITLE
Add Nepali Locale ne_NP

### ISSUE THREAD

**Issue by lalustine7** [fullcalendar/fullcalendar#5193]
Thank you for such wonderful calendar. I have been using this for more than a year. It you seems you have provided full calendar in many locale. Can you please include Nepali Locale? I think nepali community will be more focused on this features.

**Comment by lalustine7** [comment]
are you going to include this in coming updates ? Let me know sir.

**Comment by suraj61018** [comment]
Hope the Nepali Calendar will be included soon. It would be a great relief for developers,  here in Nepal

**Comment by meeprakash25** [comment]
support for nepal local would be appreciated

**Comment by arshaw** [comment]
Could someone please submit a PR that implements this? You'd need to add a new file in this directory: https://github.com/fullcalendar/fullcalendar/tree/master/packages/core/src/locales

**Comment by lalspicesresearch** [comment]
Ok i understand we need to add new file in that directory with Nepali Locale ne_NP. But what is PR that need to be submitted? Can you brief about this? I am very positive toward this changes. @arshaw

**Comment by lalustine7** [comment]
Ok i understand we need to add new file in that directory with Nepali Locale ne_NP. But what is PR that need to be submitted? Can you brief about this? I am very positive toward this changes. @arshaw

**Comment by acerix** [comment]
@lalustine7 You can add the file to the github repo, then submit the change as a "pull request".

https://help.github.com/articles/using-pull-requests/

**Comment by lalustine7** [comment]
@acerix i have requested pull request (https://github.com/fullcalendar/fullcalendar/pull/5574)
