### ISSUE TITLE
Event title overflows when it's longer than the event with displayEventTime

### ISSUE THREAD

**Issue by jackmagielse** [fullcalendar/fullcalendar#5195]
I use fullcalender 4.3.1 to show events in the resourceTimelineWeek.
I show the start time and the end time. When the eventTextColor is not white and the event duration is very small it will show the end time ouside the border of the event. You can see this in the next codepen example. I need the black eventTextColor because i show some events on a white foreground. 
[https://codepen.io/jackmagielse/pen/QWwpQQV](https://codepen.io/jackmagielse/pen/QWwpQQV)
![example](https://user-images.githubusercontent.com/48093740/71244832-b0748b00-2313-11ea-8703-d34ccf91c0ae.jpg)

**Comment by acerix** [comment]
Thanks, confirmed.  You could try setting CSS overflow as a workaround:

https://codepen.io/acerix/pen/zYxZyRa?editors=0110

**Comment by jackmagielse** [comment]
Thanks, that does the trick.

**Comment by arshaw** [comment]
this is much better in v5: https://codepen.io/arshaw/pen/WNrZgRB?editable=true&editors=001

**Comment by werachai06** [comment]
Thanks, !
