### ISSUE TITLE
Wordpress installation

### ISSUE THREAD

**Issue by arshaw** [fullcalendar/fullcalendar#520]
Originally reported on Google Code with ID 249

```
Enter a detailed description
Hello,

Do you have step-by-step instructions for installing FullCalendar into a
Wordpress site?

Thank you.
```

Reported by `gbckapolei` on 2009-12-17 10:36:51

**Comment by paaljoachim** [comment]
Hi

Are we there yet..:)

I have the same question that gbckapolei raised. I use WordPress a lot and having a simple way to add this to it would be great. It does not have to be a plugin. It could be just some instructions on getting it to work with WordPress. I also create tutorials for my web site https://www.easywebdesigntutorials.com  and having a good customizeable calendar I can tailor for my client would be great.

Thank you!
