### ISSUE TITLE
view is not updating properly

### ISSUE THREAD

**Issue by bondpati6** [fullcalendar/fullcalendar#5202]
i have created a working one in code pen. please use this link to check the logic.
 steps to recreate:
1. click on list view and then click today. it does not work. in full calendar v2 this same logic was working. 
link to code pen: https://codepen.io/bondalapati/pen/bGNopdN?editors=0010

**Comment by acerix** [comment]
The only error I see is "Invalid date" which seems to be from using moment.js which is not used by default in version 4.  You could replace moment with native times or add the moment plugin.

https://fullcalendar.io/docs/upgrading-from-v3

**Comment by bondpati6** [comment]
What does moment has anything do with why calendar.today() is not sorting the list view data?

**Comment by acerix** [comment]
I don't see any issue with the sorting, how is it different than what you expect?  

It will help if you can post a [stripped-down demo](http://fullcalendar.io/wiki/Reduced-Test-Cases/), ie. removing any code that is not needed to show the issue.

**Comment by bondpati6** [comment]
That is the simplified version of the code in our system. I am expecting it to sort the list view below the calendar too when calendar.today() is executed. Also this code was executing when eventAfterAllRender was there in v2 and since it was removed in v4 somehow it broke it. I am not sure how to fix it.

**Comment by acerix** [comment]
You can supply your events as a function, and move your `eventAfterAllRender` code at the end of that function so it runs after events are loaded.

https://fullcalendar.io/docs/events-function
