### ISSUE TITLE
How do I change event title in Angular component?

### ISSUE THREAD

**Issue by micobarac** [fullcalendar/fullcalendar#5204]
```html
<div class="content" role="main">
  <full-calendar defaultView="dayGridMonth" schedulerLicenseKey="CC-Attribution-NonCommercial-NoDerivatives"
    [plugins]="calendarPlugins" [header]="header" [eventTimeFormat]="eventTimeFormat" [events]="calendarEvents"
    editable="true" (eventDrop)="eventDrop($event)" (eventResize)="eventResize($event)">
  </full-calendar>
</div>
```

```ts
  // Calendar settings
  calendarPlugins = [dayGridPlugin, timeGridPlugin, listPlugin, interactionPlugin];

  header = {
    left: 'prev,next today',
    center: 'title',
    right: 'dayGridMonth,timeGridWeek,timeGridDay,listWeek'
  };

  // Event data
  calendarEvents: Event[] = [];

  // Event time format
  eventTimeFormat: {
    hour: '2-digit';
    minute: '2-digit';
    hour12: false;
  };

  // Other code omitted on purpose

  eventDrop($event: any) {
    this.save($event);
  }

  eventResize($event: any) {
    this.save($event);
  }
```

Actually, I want to use 24h event time format in all views, but I cannot find a way how to do it using Angular component :(. The above `eventTimeFormat` settings are ignored. I tried other event time settings, like `displayEventTime`, but it's also not working in Angular.

According to the official documentation, these should work as expected:

**The <FullCalendar> component is equipped with all of FullCalendar’s options! Just pass them in as properties. As with any Angular component, use [bracketed] property names for bound JavaScript expression and normal property names otherwise.**

**Comment by WildsG** [comment]
Hi, how did you solve your issue? I encountered the exact same one, that eventTimeFormat does not seem to apply the changes. Any tips?
