### ISSUE TITLE
[Webpack] Two versions of the main script included for daygrid plugin

### ISSUE THREAD

**Issue by lllopo** [fullcalendar/fullcalendar#5207]
All other plugins and the core include either main.js or main.esm.js, except the daygrid plugin, which includes both :

![Annotation 2019-12-30 131811](https://user-images.githubusercontent.com/5485902/71664197-c2691b80-2d60-11ea-8c0f-476841bc94fa.png)

Is this the right thing (should not be as it is look like double code and so - size hog), I am doing something wrong or it is a problem with the plugin ?

I'm using latest webapck, node and fullcalendar versions. Importing like this : 
```
@import "@fullcalendar/core/main";
@import "@fullcalendar/daygrid/main";
@import "@fullcalendar/list/main";
@import "@fullcalendar/timegrid/main";
@import "@fullcalendar/bootstrap/main";
```

**Comment by acerix** [comment]
Would you be able to post a [runnable, stripped-down demo](http://fullcalendar.io/wiki/Reduced-Test-Cases/) or steps to reproduce the issue? I don't know what that screenshot is from.

There's an example project which shows how to include that view with webpack:

https://github.com/fullcalendar/fullcalendar-example-projects/tree/master/webpack

**Comment by lllopo** [comment]
@acerix The screen is the output of the webpack bundle analyzer plugin, which ... well ... analyzes the output structure :-). Anyway - I ran it over the example project and the issue is **not** present there, so it is something specific to my project. Let's keep the issue closed for now, since I can't reproduce it yet and I'll let you know if I manage to set up a test case.

**Comment by lllopo** [comment]
@acerix Ok, found it - all my fault. Sorry for bothering you. Thanks.
