### ISSUE TITLE
Multiple duplicate events getting created in Week view while dragging the event with long click in react version of FullCalendar.

### ISSUE THREAD

**Issue by ruchi57** [fullcalendar/fullcalendar#5209]
I have used FullCalendar in my React application and in week view when I am trying to drag my event for few times, it starts creating duplicate issues from all the dates it gets dragged.

Please find this video explaining the issue:
https://www.loom.com/share/2e142dedf3a8469f954c7f2754669833

When I refresh the page only original event is visible and other duplicate events disappears.

**Comment by acerix** [comment]
Would you be able to post a [runnable, stripped-down demonstration of the bug](http://fullcalendar.io/wiki/Reduced-Test-Cases/)? Would really appreciate it because the time saved reproducing will be time spent fixing.
