### ISSUE TITLE
[Angular] Show / hide events problem

### ISSUE THREAD

**Issue by Stalyon** [fullcalendar/fullcalendar#5211]
All my events have a type. The user can show / hide events depending on that type.
In order to do that:
 - when the events of a type are hidden : I store the EventInput in a list (hiddenCalendarEvents), and then I remove the event with the API : `this.calendarComponent.getApi().getEventById(String(calendarEvent.id)).remove();`
 - when the events of a type are shown : I retrieve all events in my hidden list and then I push them in calendarEvents list.

Finally, to indicate to the Angular FullCalendar component I changed calendarEvents, I use `this.calendarEvents = this.calendarEvents.slice(0);` as mentionned in your docs.

It works well when we just hide / show one type. But, when we hide two types and show one, the events of this one are not displayed.

I reproduced that in a simple StackBlitz here: https://stackblitz.com/edit/github-kdg66b

> Steps to reproduce:
> 1/ Click "Type 1" button to hide events of type 1. --> OK
> 2/ Click "Type 2" button to hide events of type 2. --> OK
> 3/ Click "Type 1" button to show events of type 1 --> KO
> 4/ Click "Type 2" button to show events of type 2 --> OK

**Comment by acerix** [comment]
There's some issue with mutating `this.calendarEvents` like that, it works if you modify a clone instead:

https://stackblitz.com/edit/github-kdg66b-bc1cb8

**Comment by Stalyon** [comment]
Thanks for the answer. Perfect!
