### ISSUE TITLE
the list views provided by you are not accessibility compliant. 

### ISSUE THREAD

**Issue by bondpati6** [fullcalendar/fullcalendar#5214]
how to make the list view you have provided an accessibility compliant?
 and your working example provided by you 
https://codepen.io/pen/?&editable=true&editors=001

**Comment by acerix** [comment]
I believe this existing ticket captures this need:
https://github.com/fullcalendar/fullcalendar/issues/2536
↑
Please visit the above issue, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates.

**Comment by bondpati6** [comment]
@acerix it is not the same, i am not talking about just making the elements accessible, i am talking about making the headers accessible too. that is the reason i meant the whole list view. can you tell me how to make headers like Wednesday accessible?

**Comment by acerix** [comment]
That issue is for making everything accessible so it would also include the list view.

For now, you could use callbacks like `datesRender` to modify the HTML or make a custom view.
