### ISSUE TITLE
Resource is not reflecting in event when dropped on resourceTimeGrid

### ISSUE THREAD

**Issue by dannemanNov** [fullcalendar/fullcalendar#5215]
When dropping external event on resourceTimeGrid the resourceId is not reflecting in callback eventReceive.

See: [https://codepen.io/novasecur/pen/bGNvdyy](https://codepen.io/novasecur/pen/bGNvdyy)

**Comment by razorhenry1** [comment]
<img width="860" alt="Screen Shot 2020-01-09 at 2 47 16 PM" src="https://user-images.githubusercontent.com/32644212/72054480-0de67100-32ef-11ea-9119-ca344fbfa217.png">
I can see the resource id in _def

**Comment by dannemanNov** [comment]
Yes. I found that too. But isn't _def an internal object? Can I rely on that _def is always there and never changed when it's not mentioned in the documents?

[https://fullcalendar.io/docs/eventReceive](https://fullcalendar.io/docs/eventReceive)
The document says: "When an event has been dropped on a resource, the event’s resources will reflect."

**Comment by acerix** [comment]
You can get the resource from `info.event.getResources()`

https://codepen.io/acerix/pen/zYxWJRy?editors=0011
