### ISSUE TITLE
`agendaDay` view is broken with resources

### ISSUE THREAD

**Issue by ocarreterom** [fullcalendar/fullcalendar#5217]
### Bug Reports
`agendaDay` view is broken with resources in v3.
Test: https://codepen.io/ocarreterom/pen/abzYYpy?editors=0010

**Comment by ocarreterom** [comment]
Same for the `basicDay` view.

**Comment by ocarreterom** [comment]
Works with `agenda` and `basic` views (without `Day`).
https://codepen.io/ocarreterom/pen/ZEYxxXL?editors=0010

**Comment by acerix** [comment]
It looks fine to me, what is broken about it?

**Comment by ocarreterom** [comment]
@acerix sorry, codepen update:

|view | test | screenshot | comment |
|-----|-----|------------|-----------|
| agendaDay | https://codepen.io/ocarreterom/pen/abzYYpy?editors=0010 | <img width="978" alt="Captura de pantalla 2020-01-10 a las 9 24 51" src="https://user-images.githubusercontent.com/11599942/72137404-0ffe0d80-338b-11ea-9520-0e4f2d726203.png"> | 👎 |
| agendaWeek | https://codepen.io/ocarreterom/pen/GRgxbNw?editors=0010 | <img width="932" alt="Captura de pantalla 2020-01-10 a las 9 26 01" src="https://user-images.githubusercontent.com/11599942/72137514-39b73480-338b-11ea-9f5f-6cd89d0e3741.png"> | 👍 |
| agenda | https://codepen.io/ocarreterom/pen/ZEYxxXL?editors=0010 | <img width="929" alt="Captura de pantalla 2020-01-10 a las 9 27 19" src="https://user-images.githubusercontent.com/11599942/72137611-68350f80-338b-11ea-9d35-2a0b48449198.png"> | The expected `agendaDay` behavior |

In [agenda view docs](https://fullcalendar.io/docs/v3/agenda-view):
> The two predefined agenda views are agendaDay and agendaWeek.

The expected behavior is that agenda views should ignore resources?

**Comment by acerix** [comment]
Thanks for the info, I can see the resources don't work in agendaWeek view.  Version 3 is no longer updated though and I can see it works in v4 `resourceTimeGridWeek` view: 

https://codepen.io/acerix/pen/OJPZpYp?editors=0010

**Comment by ocarreterom** [comment]
Thanks, I will update.
`agendarWeek` works setting `groupByResource: true`.

https://codepen.io/ocarreterom/pen/jOExajr?editors=0010
