### ISSUE TITLE
renderSkeleton is not called in custom JS view

### ISSUE THREAD

**Issue by acerix** [fullcalendar/fullcalendar#5218]
Reported in https://fullcalendar.freshdesk.com/a/tickets/1469

Using the example from the docs, renderSkeleton does not get called:

https://codesandbox.io/s/fullcalendar-react-3stjz

**Comment by ickphum** [comment]
Until this is fixed, is a custom JS view possible? If so, do you have any tips past the existing docs? Ta.

**Comment by arshaw** [comment]
v5 has a completely new way of doing this : https://fullcalendar.io/docs/custom-view-with-js
