### ISSUE TITLE
change resource area width event

### ISSUE THREAD

**Issue by itajackass** [fullcalendar/fullcalendar#5221]
Is there an event to track if the resource area with is changed using mouse drag?

**Comment by acerix** [comment]
I believe this existing ticket captures this need:
https://github.com/fullcalendar/fullcalendar/issues/5038
↑
Please visit the above issue, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates.
