### ISSUE TITLE
Dist folder is missing from v4.3.0

### ISSUE THREAD

**Issue by sviluppo** [fullcalendar/fullcalendar#5223]
### Bug Reports
Hello,

I'm trying to use this package from yii2fullcalendar (https://github.com/philippfrenzel/yii2fullcalendar) that depend on the *dist* folder that is not created anymore from v4.3.0 of Fullcandar.
It is normal??
Which folder now must be pointed? 
yii2fullcalendar need to run a build somewhere??
Sorry but yii2fullcalendar is not supported enough, so i need to understand from here.

Thank you

**Comment by acerix** [comment]
That package doesn't [support version 4 ](https://github.com/philippfrenzel/yii2fullcalendar/issues/139) so you would need to use version 3.10.0 or update it to use v4 as explained here:

https://fullcalendar.io/docs/upgrading-from-v3

**Comment by sviluppo** [comment]
I still don't understand why from version 4.3.0 there are not anymore **DIST** folder.
Also if you split packages in directory and refactored.
Why inside **packages/core/** there is no **dist** folder??

So the idea is, or you use the modern ES6 way to handle this project or the alternatives is caveman old style script including (or CDN that is a caveman with a smoking).

There is nothing in the middle ... Webpack or die... correct??
If i miss a point please tell me, i would like to understand more.

**Comment by acerix** [comment]
You don't need Webpack to [build it yourself](https://github.com/fullcalendar/fullcalendar/blob/master/CONTRIBUTING.md#getting-set-up) which  creates those dist folders but I don't see how that will help you.

There's an open request to have all the packages combined if that's what you are looking for:

https://github.com/fullcalendar/fullcalendar/issues/4566
↑
Please visit the above issue, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates.

**Comment by sviluppo** [comment]
I had problem yesterday with `npm install` so i created this #5227  

Anyway have *dist* folder already packed in the packages directories could help me to reference with Yii2 the assets that i need without packing them myself.

Have one unique combined like discussed in #4566 file would be better of course, also if how to handle scheduler could be a problem for you.
