### ISSUE TITLE
fullcalendar agenda view wrong sort depending on device timezone

### ISSUE THREAD

**Issue by shahazaryan** [fullcalendar/fullcalendar#5225]
I use fullcalendar for my calendar app and have created a custom agenda view. but that is showing events in the wrong order. you can see my calendar here  https://boomtechdev.wixsite.com/mysite-20

**Comment by acerix** [comment]
Would you be able to post a [runnable, stripped-down demonstration of the bug](http://fullcalendar.io/wiki/Reduced-Test-Cases/)? Would really appreciate it because the time saved reproducing will be time spent fixing.

**Comment by shahazaryan** [comment]
I have fixed it using sort() function to sort events by start date. I  thought that events ould be in that order.
