### ISSUE TITLE
npm install doesn't work cause of arshaw/rollup-plugin-multi-entry

### ISSUE THREAD

**Issue by sviluppo** [fullcalendar/fullcalendar#5227]
### Bug Reports
Based on this document https://github.com/fullcalendar/fullcalendar/blob/master/CONTRIBUTING.md#getting-set-up

I tried `npm install` but seems that there is a problem with the dependencies.

To let `npm-install` work i had to change in **package.json**  this line:

`"rollup-plugin-multi-entry": "github:arshaw/rollup-plugin-multi-entry#dist" `

that is moved and no longer supported to this:

`"@rollup/plugin-multi-entry": "^3.0.0",`

and also change his reference into **rollup.config.js**:
`const multiEntry = require('@rollup/plugin-multi-entry')`

https://github.com/fullcalendar/fullcalendar/commit/bee86572bc3506dabf6b9820da80f0564b15514a

**Comment by acerix** [comment]
Those instructions work for me without error, you should try clearing npm's cache and check that it is up to date.

**Comment by trkaplan** [comment]
Which operating systems were using while testing this? @sviluppo @acerix If @acerix using Windows and you are usng a different one, this might be the it worked for you.
