### ISSUE TITLE
Event range exceeding maxTime/minTime or business hours should be offset to the following/previous day

### ISSUE THREAD

**Issue by drakans** [fullcalendar/fullcalendar#5228]
This requirement will really improve the library usage. It could be enable/disable with a boolean attribute. Please find an illustration example in attachment. 
Best,
![Untitled](https://user-images.githubusercontent.com/23476209/72716989-7cd78b80-3b73-11ea-9d08-b2f6de1cab80.png)

**Comment by drakans** [comment]
this is a more complete example : 
![Untitled(1)](https://user-images.githubusercontent.com/23476209/72735807-d902d580-3b9c-11ea-92b5-6901eabfb934.png)

**Comment by acerix** [comment]
So, are looking to have the end time of events be based on the start time plus the "visible duration"?

You could do that calculation from the `events` function or on the server side:

https://fullcalendar.io/docs/events-function

**Comment by drakans** [comment]
Hi Acerix, thank you for your quick reply. 
However I don't believe this is what we need because we also need this behavior when we drag/resize events.

**Comment by acerix** [comment]
I don't see how it would work differently on resizing/moving, you could calculate the new "visible duration" based on the new start/end times.

**Comment by arshaw** [comment]
i'm not sure FullCalendar should attempt to do this. You should compute different `end` dates for your events in this case
