### ISSUE TITLE
Multiples Sources dayClick get background color

### ISSUE THREAD

**Issue by seritpt** [fullcalendar/fullcalendar#5231]
### Bug Reports
I have more than one source ajax to calendar Events. When I click on day event it doesn't get the background event.
```
$(objCalendar).fullCalendar({
		eventLimit: 1,
		header: {
			left: 'prev,next today',
			center: 'title',
			right: 'month,agendaDay,listDay'
		},
		firstDay: 0,
		lang: 'pt',
		defaultView: 'month',
		eventLimitText: "Viaturas",
		timeFormat: 'H:mm',
		eventSources:[
			'lib/ajax/calendar.php?visit='+idCalendar,
			'lib/ajax/exceptions.php?visit='+idCalendar,
		],
		showNonCurrentDates: false,
		validRange: {start: moment().format('YYYY-MM-DD')},
		loading: function( isLoading, view ) {
			if(isLoading) $(this).closest(".card").find(".overlay").show();
			else $(this).closest(".card").find(".overlay").hide();
		},
		bgEventClick: function(calEvent, jsEvent, view) {
			console.log('bgEventClick');
		},
		dayClick: function(date,jsEvent,view) {
			if (jsEvent.target.classList.contains('bg-danger')) {
				console.log("danger");
			} else if (jsEvent.target.classList.contains('bg-warning')) {
				console.log("warning");
			} 
		},
		eventClick:  function(event, jsEvent, view) {
			$("#modalBookings").modal("show");
		}

**Comment by acerix** [comment]
Would you be able to post a [runnable, stripped-down demonstration of the bug](http://fullcalendar.io/wiki/Reduced-Test-Cases/)? Would really appreciate it because the time saved reproducing will be time spent fixing.

**Comment by seritpt** [comment]
Yes, of course.

I Have isolated the script to test.
You can see that works for days 11,16,17,21,22,26,27 and doesn't work for days 7,12,19,20,28,29 and 30.

What I need is always on background color click detect the color class and interact with the rest of script.

Demo here http://next.plnkr.co/plunk/OMdArzUrDmkFI0Ye.

Thanks in advance.

**Comment by seritpt** [comment]
> Would you be able to post a [runnable, stripped-down demonstration of the bug](http://fullcalendar.io/wiki/Reduced-Test-Cases/)? Would really appreciate it because the time saved reproducing will be time spent fixing.

Why you closed this help? You don't gave me enough time :-( I need help. Please...

**Comment by acerix** [comment]
I believe this existing ticket captures this need:
https://github.com/fullcalendar/fullcalendar/issues/5110
↑
Please visit the above issue, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates.

The workaround gets it working:

http://next.plnkr.co/edit/8wC8vunitk02vaV7

**Comment by seritpt** [comment]
WOW awesome :-D Thanks a lot :-D You rules \o/

**Comment by seritpt** [comment]
Humm, I think it's working just in half height down. If you try near the day number, it doesn't work. But it's better than nothing :-)
