### ISSUE TITLE
How can I get the click event of prev, today, next button

### ISSUE THREAD

**Issue by sebidev999** [fullcalendar/fullcalendar#5232]
I would like to get the click event of prev, today, next button.

**Comment by razorhenry1** [comment]
Use datesRender in calendar options to get the date from button clicks : 

```
 datesRender: () => {
        console.log(this.calendar.getDate());
      }
```

**Comment by acerix** [comment]
I believe this existing ticket captures this need:
https://github.com/fullcalendar/fullcalendar/issues/3521
↑
Please visit the above issue, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates.

For now, you could replace those buttons with custom buttons.
