### ISSUE TITLE
setOption doesn't take account of `resources` change.

### ISSUE THREAD

**Issue by ETSmukesh** [fullcalendar/fullcalendar#5235]
Hello
I need to update resource title but setOption not working on dynamically update resources.

**Comment by acerix** [comment]
Would you be able to post a [runnable, stripped-down demonstration of the bug](http://fullcalendar.io/wiki/Reduced-Test-Cases/)? Would really appreciate it because the time saved reproducing will be time spent fixing.

**Comment by ETSmukesh** [comment]
I need to update resource title in v4, but setOption not working to update dynamically resource info.
So, my question is that is there any method available named as `updateResource` like docs have `addResource`.

**Comment by acerix** [comment]
There isn't a method to update resources but you could call `addResource` with the same id to replace it:

https://codepen.io/acerix/pen/NWPZpVR?editors=0010

Another way is to set the title in resourceRender then call rerenderResources to update.

**Comment by ETSmukesh** [comment]
Thanks, we've done the same things but we're removing first old resource and then add the same deleted resource.
