### ISSUE TITLE
TypeError: Cannot read property 'daysOfWeek' of undefined.

### ISSUE THREAD

**Issue by rashid-02** [fullcalendar/fullcalendar#5237]
### Bug Reports
When navigating back from on a specific January, 2018 the calendar get stuck. Next/previous button becomes unresponsive.

In error console, it is showing:

TypeError: Cannot read property 'daysOfWeek' of undefined.
While, 'daysOfWeek' is not used anywhere in the code.

It's a bug/issue of Full calendar. Needs to be sorted.

**Comment by acerix** [comment]
Would you be able to post a [runnable, stripped-down demonstration of the bug](http://fullcalendar.io/wiki/Reduced-Test-Cases/)? Would really appreciate it because the time saved reproducing will be time spent fixing.
