### ISSUE TITLE
TypeError: Cannot read property 'daysOfWeek' of undefined.

### ISSUE THREAD

**Issue by rashid-02** [fullcalendar/fullcalendar#5239]
### Bug Reports
Steps to reproduce:
1. Try to navigating through prev/next button of calendar.
2. At month January, 2018, Try to navigate previous month.

After these steps Calendar becomes unresponsive and throws an TypeError:
Cannot read property 'daysOfWeek' of undefined. While I am not using 'daysOfWeek' anywhere in the code.

My Code is:

`function AppCalendar({ studentId }: propType) {
  const dispatch = useDispatch();

  return (
    <div className="demo-app-calendar">
      <FullCalendar
        defaultView="dayGridMonth"
        weekends={true}
        header={{
          left: "prev",
          center: "title",
          right: "next"
        }}
        nowIndicator
        eventBackgroundColor={"transparent"}
        eventBorderColor={"transparent"}
        events={(fetchInfo, successCallBack) => {
          apiCall(fetchInfo, successCallBack, dispatch, studentId);
        }}
        plugins={[dayGridPlugin]}
      />
    </div>
  );
}

async function apiCall(
  fetchInfo: any,
  successCallBack: any,
  dispatchFn: any,
  studentId: any
) {
  let startYear = new Date(fetchInfo.start).getFullYear();
  let endYear = new Date(fetchInfo.end).getFullYear();
  let startMonth = new Date(fetchInfo.start).getMonth();
  let endMonth = new Date(fetchInfo.end).getMonth();
  let startDate = new Date(fetchInfo.start).getDate();
  let endDate = new Date(fetchInfo.end).getDate();

  let start = new Date(startYear, startMonth, startDate);
  let end = new Date(endYear, endMonth, endDate);

  for (var a: any = [], d = start; d <= end; d.setDate(d.getDate() + 1) + 1) {
    a.push(new Date(d));
  }

  let formatDate = a[Math.floor(a.length / 2)];
  let date = new Date(formatDate);
  let getYear = date.getFullYear();
  let getMonth = date.getMonth() + 1;
  let monthString = getMonth >= 10 ? getMonth : "0" + getMonth;
  console.log("monnn", monthString);
  let getDate = date.getDate();
  let dateString = getDate >= 10 ? getDate : "0" + getDate;
  let fullDate = getYear + "-" + monthString + "-" + dateString;
  console.log("formmmmate", fullDate);
  try {
    let attendanceData: any = await HttpClient.request(
      "studentAttendance/month/summary?studentId=" +
        studentId +
        "&" +
        "date=" +
        fullDate,
      "GET",
      "",
      ""
    );
    successCallBack(
      attendanceData.data.monthAttendance.map((item: any, index: any) => {
        if (item.attendence === "P") {
          return {
            title: item.attendence,
            date: item.date,
            textColor: `var(--ion-color-primary)`
          };
        }
        if (item.dayType === null) {
          return {
            title: "N/A",
            date: item.date,
            textColor: `var(--ion-color-medium)`
          };
        }
        if (item.attendence === "A") {
          return {
            title: item.attendence,
            date: item.date,
            textColor: `var(--ion-color-danger)`
          };
        }
        if (item.dayType === "NonWorking") {
          return {
            title: "N",
            date: item.date,
            textColor: `var(--ion-color-warning)`
          };
        }
        if (item.dayType === "Holiday") {
          return {
            title: "H",
            date: item.date,
            textColor: `var(--ion-color-tertiary)`
          };
        }
      })
    );
    dispatchFn(
      updateAppState(
        "monthlyAttendance",
        attendanceData.data.presentDaysTillNowInMonth
      )
    );
    dispatchFn(
      updateAppState(
        "monthlyWorkingDay",
        attendanceData.data.workingDaysTillNowInMonth
      )
    );
    dispatchFn(
      updateAppState(
        "monthlyAttendancePercent",
        attendanceData.data.presentPercentageTillNowInMonth
      )
    );
    dispatchFn(
      updateAppState(
        "academicAttendance",
        attendanceData.data.presentDaysTillNowInAcademicSession
      )
    );
    dispatchFn(
      updateAppState(
        "academicWorkingDay",
        attendanceData.data.workingDaysTillNowInAcademicSession
      )
    );
    dispatchFn(
      updateAppState(
        "academicAttendancePrecent",
        attendanceData.data.presentPercentageTillNowInAcademicSession
      )
    );
    console.log("attRes", attendanceData);
  } catch (error) {
    console.log("eerr", error);
  }
}`

@acerix Please have look on this issue and suggest solution.

**Comment by acerix** [comment]
Would you be able to post a [runnable, stripped-down demonstration of the bug](http://fullcalendar.io/wiki/Reduced-Test-Cases/)? Would really appreciate it because the time saved reproducing will be time spent fixing.
