### ISSUE TITLE
Force days to show in resource timeline

### ISSUE THREAD

**Issue by depsimon** [fullcalendar/fullcalendar#5240]
Check out this pen: https://codepen.io/simondepelchin/pen/PowreMq?editors=0010

I set up a duration of 3 days & a `slotDuration` of `00:15`. It seems to be working as intended.

Now change the `slotDuration` to `00:05` and the days bar (on top of the times) disappears.

Is there any way to prevent that from happening? I want the days bar to always be visible.

**Comment by acerix** [comment]
The top labels are generated automatically by default but you can specify the format with `slotLabelFormat`

https://codepen.io/acerix/pen/OJPedqg?editors=0010

**Comment by depsimon** [comment]
Thank you!
