### ISSUE TITLE
Setting selectConstraint to a single day

### ISSUE THREAD

**Issue by Warix3** [fullcalendar/fullcalendar#5241]
It used to be possible to set the selectConstraint to start: '00:01' and end: '23:59' and this would prevent you from selecting time outside a single day. This worked in version 3.9.0 and it's not working in 4.3.1
I don't know if this is a bug or intended but it would be nice to be able to constrain the selection so it's only possible to select time from a single day. If this is not a bug but an intended change then please consider adding a new option, something like restrictSelectToSingleDay to be true or false.
And this is only a problem in week view for me because it's the only place where you can select time from multiple days. So I will disable selecting in the week view as a temporary solution. 
https://codepen.io/Warix3/pen/rNaXxwj?editable=true&editors=001

**Comment by acerix** [comment]
In v4, the setting were renamed to `startTime`/ `endTime`:

https://codepen.io/acerix/pen/RwPbMZG?editable=true&editors=001

I'm not sure if that is the behaviour you are looking for though, it should work better to use `selectAllow` and return `false` if start/end are not on the same day.
