### ISSUE TITLE
Option to display name of next/prev months in the buttons

### ISSUE THREAD

**Issue by trong291990** [fullcalendar/fullcalendar#5242]
Something like this
<img width="438" alt="calendar" src="https://user-images.githubusercontent.com/1978510/73754681-529ee400-4797-11ea-8939-295d88ca666d.png">

**Comment by acerix** [comment]
That's not built-in but you could replace them with [customs buttons](https://fullcalendar.io/docs/customButtons) and set their text from [datesRender](https://fullcalendar.io/docs/datesRender).

**Comment by trong291990** [comment]
@acerix it works. Thank you so much
