### ISSUE TITLE
Timeline Views Responsive

### ISSUE THREAD

**Issue by johnnydevs** [fullcalendar/fullcalendar#5244]
I've just seen the timeline views and I think they would work great with a project i'm working in, however unless i'm missing something, it's not responsive?

See the demo here https://fullcalendar.io/docs/timeline-standard-view-demo

When I resize the browser window it doesn't appear to be responsive?

Great calendar btw :)

**Comment by acerix** [comment]
I believe this existing ticket captures this need:
https://github.com/fullcalendar/fullcalendar/issues/3187
↑
Please visit the above issue, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates.
