### ISSUE TITLE
TypeError: Cannot read property 'daysOfWeek' of undefined

### ISSUE THREAD

**Issue by rashid-02** [fullcalendar/fullcalendar#5245]
### Bug Reports
Hi @acerix 
Please have a look on an attached error demonstration of my app, which I am facing when integrating the Full Calendar on React.
This error occurs when I am trying to navigate through next/prev button of the calendar. This error only occurs when I try to navigate through prev button from January, 2018 calendar. After that the calendar becomes unresponsive. 
The error in console says TypeError: Cannot read property 'daysOfWeek' of undefined, while I didn't use 'daysOfWeek' anywhere in my code. You can go through the attached demonstration with this issue. 
Kindly suggest a solution to get rid of it.
Thank you
[Screen Recording 2020-02-06 at 6.49.18 PM.zip](https://github.com/fullcalendar/fullcalendar/files/4165333/Screen.Recording.2020-02-06.at.6.49.18.PM.zip)

**Comment by acerix** [comment]
Would you be able to post a [runnable, stripped-down demonstration of the bug](http://fullcalendar.io/wiki/Reduced-Test-Cases/)? Would really appreciate it because the time saved reproducing will be time spent fixing.
