### ISSUE TITLE
refetchEvents when calendar Is hidden results in events disappearing. 

### ISSUE THREAD

**Issue by kylethielk** [fullcalendar/fullcalendar#5247]
### Bug Reports

I had this issue way back when we were using 2.4, we have now moved to 3.10.0 and the manual fix I had is no longer applicable since so much of the internals has changed. Please see https://github.com/fullcalendar/fullcalendar/issues/2936 for more details on original submit.

Essentially if `refetchEvents` is called while the calendar is hidden or the calendar is hidden before `refetchEvents` has time to draw the updates the next time we load the calendar the events are all draw with a height of 0 at the top of the calendar.

Here is a working example: https://jsbin.com/zediposejo/edit?html,js,output

Using JSBin click the "Run Test" button. This will:
1. Hide the Calendar.
2. fullCalendar('refetchEvents')
3. Show the Calendar.
4. fullCalendar('render')

The calendar will be empty of events. If you navigate between views or forward/backward in time events appear again.

**Comment by acerix** [comment]
The part of your demo commented as "Render" is actually calling "refetchEvents" again, it shows the events after changing to "render":

https://jsbin.com/wugivabeke/1/edit?html,js,output

**Comment by kylethielk** [comment]
hey @acerix thanks for the reply.

In our specific case, changes made while the Calendar is hidden will result in the events changing and thus needing to be refetched. From the documentation I was under the impression that refetchEvents would also re-render the calendar (https://fullcalendar.io/docs/v3/refetchEvents)

> Refetches events from all sources and rerenders them on the screen.

It sounds like what needs to happen though is if any change happens to the Calendar when it is not visible, the next time it is made visible the 'render' method needs to be called no matter what. I can definitely do this, it just caught us out as I don't believe this is what is mentioned in documentation. 

Can you clarify for me if indeed the 'refetchEvents' does indeed call `render` internally as well?

**Comment by acerix** [comment]
`refetchEvents` re-renders the events but not the whole calendar so you should still need `render` after showing it to fix the layout.

https://jsbin.com/ceqigevule/edit?js,output
