### ISSUE TITLE
Add a callback event for when an event is dragged outside the calendar

### ISSUE THREAD

**Issue by Dragomir-Ivanov** [fullcalendar/fullcalendar#5251]
Sometimes dragging an event(outside or not) should take an action and make a preview somewhere.
Using plugin hooks, tracking the drag can be made with:
```
    this.externalDragPlugin = createPlugin({
      eventDragMutationMassagers: [this.eventDragMutation],
      externalDefTransforms: [this.eventExternalDrag],
    })
```
However, when dragged item leaves `fullcalendar` time grid, preview stays at the last state before leaving the calendar. There is no way one can know if dragging is still on(albeit outside the calnedar).
Adding another hook for `dragleave` will fix this.
Thanks!

**Comment by arshaw** [comment]
dup of:
https://github.com/fullcalendar/fullcalendar/issues/3140
&uarr;
Could you please visit the link, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates?
