### ISSUE TITLE
Dropping natively draggable elements (a href, img) onto a 'droppable' v3 calendar breaks dayClick

### ISSUE THREAD

**Issue by mitomm** [fullcalendar/fullcalendar#5255]
Hi,

after months of getting some feedback from a small portion of our customer that the calendar sometimes returns the wrong time on day click, we finally found a way to reproduce it. 

Here is the plnkr link:

https://embed.plnkr.co/YrIpv2mHjInXt4mXPtBo/

To reproduce it you have to do 3 things: 
1. Drag the link (above the calendar) on the calendar
2. scroll down in the calendar
3. do a day click an see the wrong time of the day click

A couple things to note: 
In our UI the link is not supposed to be dragged on the calendar, but it seems like some customers are doing it not on purpose, so it's still causing us issues as the whole calendar breaks after that. 
Also, the same works for images, or selected text, which are all natively draggable in a browser. 

What's also weird, but not directly related to fullcalendar I assume, after you reproduce the bug above, the right click of the browser doesn't work anymore (at least in chrome). 

I know there is version 4 and soon 5 being release, but as a lot of people are still using version 3.10 it would be really great if it could still be fixed. 

Thanks a lot.

**Comment by acerix** [comment]
Confirmed in v3, and also confirmed fixed in v4:

https://codepen.io/acerix/pen/BaNzyNg?editors=0010

I couldn't find a good fix but you could use CSS to make links and images not draggable:

https://stackoverflow.com/a/12906840

**Comment by mitomm** [comment]
Thanks a lot for the quick reply. 

Your suggested fix is exactly what we did. But then it still breaks if you have selected some text (which is also draggable when selected), and drop that onto the calendar. 

Don't ask me why or how users would do that, but it happens. And unfortunately, also disabling all text selection isn't really a good solution for us as it is needed at some locations. Also feels a bit like a temporary fix that only works until something else we haven't thought of is randomly dropped onto the calendar that shouldn't. 

Isn't there some easy way to just reject all non-fullcalendar elements when dropped onto the calendar (while still keeping the external event dropping possible)

**Comment by acerix** [comment]
I don't think it's possible to fix that without editing the calendar code, it might be an issue with jquery UI which handles dragging in v3 but was removed in v4.

I noticed that only text in the same frame causes that problem though, for example "undefined" in the top left of your demo can be selected and dragged but not dropped in the calendar.  So it might help to put the calendar in a frame, then you only need to make the text in the same frame "not selectable".

**Comment by mitomm** [comment]
I’d even be willing to search and fix the issue in the library myself. Some hints on where I may have to look would be really appreciated.
I assume it should be possible to detect and ignore those “fake” drop somehow? Maybe somewhere in eventDrop of library itself?
If you have an idea on where I can start looking, that would be great. 🙂

**Comment by mitomm** [comment]
After going through the library itself in more detail, I actually discovered a much simpler way to solve the issue.
Fullcalendar already has a [dropAccept](https://fullcalendar.io/docs/v3/dropAccept) function, which makes it easy to just accepts elements with a certain class on it. After my initials tests, this seems to be a great work around as images, links and selected text is immediately reject. 

Not sure why I didn't find this setting before, but I think this will solve the issue for me. I'll report back after it's deployed in production and running for some days.

**Comment by acerix** [comment]
Thanks for the update, I didn't know about `dropAccept` but can see that it fixes this.
