### ISSUE TITLE
Calendar events load before the resource

### ISSUE THREAD

**Issue by mahjnalisha** [fullcalendar/fullcalendar#5259]
I am loading the full calendar timeline view and when I was doing the asynchronous call and load the data, it is loading the events earlier than resources call.
The problem is that when the resource datas are loaded, it is giving me different start and end date
but when i refetched the events after the resources are rendered the events start and end date are fine but doing this will call my server for two times. 
Will someone be able to send me some solution for this ?

**Comment by acerix** [comment]
Would you be able to post a [runnable, stripped-down demonstration of the bug](http://fullcalendar.io/wiki/Reduced-Test-Cases/)? Would really appreciate it because the time saved reproducing will be time spent fixing.
