### ISSUE TITLE
Add a property for specifying how to render recurring and all-day events

### ISSUE THREAD

**Issue by brainz80** [fullcalendar/fullcalendar#5261]
Currently recurring and all-day events are being rendered from given ```start``` to ```end - 1 day```. Would be nice if this behavior could be modified by e.g. a parameter ```renderUntilExactEnd```.

Same issue seems to occur with recurring events with a ```endRecur``` parameter.

**Comment by acerix** [comment]
As explained in the docs:

> `endRecur` is exclusive. Just like every other end-date in the API. For all-day recurring events, make the endRecur the day after you want your last recurrence.

If there is a bug, please post a [runnable, stripped-down demonstration](http://fullcalendar.io/wiki/Reduced-Test-Cases/).
