### ISSUE TITLE
JS Error on Select after set height of calender 

### ISSUE THREAD

**Issue by aterjung** [fullcalendar/fullcalendar#5263]
i have a fullcalender instance with scheduler. I adjust the height of the calendar like this on window resize: 

calendar.setOption('height', $(window).height() - 150);
After the resize, the "select" callback function is called right after the select is started an i can not mark more cells. Also a Error is thrown in the Console:

Uncaught TypeError: Cannot read property 'resource' of undefined
    at ResourceTimelineView.queryHit (main.js:965)
    at HitDragging.queryHitForOffset (main.js:1086)
    at HitDragging.handleMove (main.js:1049)
    at EmitterMixin.HitDragging.handleDragMove (main.js:1000)
    at applyAll (main.js:988)
    at EmitterMixin.triggerWith (main.js:3582)
    at EmitterMixin.trigger (main.js:3577)
    at EmitterMixin.FeaturefulElementDragging._this.onPointerMove (main.js:809)
    at applyAll (main.js:988)
    at EmitterMixin.triggerWith (main.js:3582)

**Comment by acerix** [comment]
Would you be able to post a [runnable, stripped-down demonstration of the bug](http://fullcalendar.io/wiki/Reduced-Test-Cases/)? Would really appreciate it because the time saved reproducing will be time spent fixing.

**Comment by ChaDonSom** [comment]
Hi, I was able to reproduce this error [on CodeSandbox](https://codesandbox.io/s/fullcalendar-v4-vue-b8vq7?fontsize=14&hidenavigation=1&theme=dark).

This was using version 4.4.2 for all packages.

It seems to be limited to the resourceTimeline view.

It can be replicated from that [sandbox](https://codesandbox.io/s/fullcalendar-v4-vue-b8vq7?fontsize=14&hidenavigation=1&theme=dark) by:

1. make a selection on the calendar by dragging, and see that no errors come up (the select handler simply logs to the console).
2. hit the 'Size Calendar' button, which sets the calendar height to 500 +/- 1.
3. try to make another selection; it should show the above error.
4. (optional) after the first selection, subsequent selections seem to work.
