### ISSUE TITLE
split view by person

### ISSUE THREAD

**Issue by basementmedia2** [fullcalendar/fullcalendar#5265]
Hi,

I would like to have a day (list) view, which is split up to 5 persons (means 5 columns). 
That means the calendar should have 5 columns with each column filled with the appointments of another person. A user interface should allow the user to add columns of further persons or delet columns. Is that possible with full calendar?

Best regards
Daniel

**Comment by acerix** [comment]
That is not built-in but you could make it with a custom view.

I believe this existing ticket captures this need:
https://github.com/fullcalendar/fullcalendar/issues/4892
↑
Please visit the above issue, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates.
