### ISSUE TITLE
eventLimit text is not localized

### ISSUE THREAD

**Issue by dviry** [fullcalendar/fullcalendar#5269]
When setting eventLimit: true, the "+ more" text is always displayed in English and not localized (e.g. to "de" locale). Everything else is localized correctly.

Regards

**Comment by acerix** [comment]
Would you be able to post a [runnable, stripped-down demonstration of the bug](http://fullcalendar.io/wiki/Reduced-Test-Cases/)? Would really appreciate it because the time saved reproducing will be time spent fixing.

It is working in this demo:

https://fullcalendar.io/docs/locale-demo

**Comment by dviry** [comment]
I am using the [3rd example from the Documentation](https://fullcalendar.io/docs/locale),

```
import { Calendar } from '@fullcalendar/core';
import allLocales from '@fullcalendar/core/locales-all';
...
let calendar = new Calendar(calendarEl, {
  locales: allLocales,
  locale: 'fr' // the initial locale
});
```

**Comment by dviry** [comment]
OK - sorry found out I was passing the allLocales parameter in a wrong way.

Thanks
