### ISSUE TITLE
Resource timeline view editing and dragging multiple events overlaps first event

### ISSUE THREAD

**Issue by easededge** [fullcalendar/fullcalendar#5274]
In resource timeline view, if you have multiple events for the same resource, and drag the event to change the time / duration, the event "jumps" up to the top position and overlaps the first event, making it difficult to visualize when editing.

It can be recreated in any browser when visiting the demo page below.

https://fullcalendar.io/docs/timeline-standard-view-demo

<img width="993" alt="Screen Shot 2020-02-24 at 2 21 10 PM" src="https://user-images.githubusercontent.com/60759655/75188039-0baa6b80-5711-11ea-8b2a-6a4686a38f2f.png">

**Comment by acerix** [comment]
I believe this existing ticket captures this need:
https://github.com/fullcalendar/fullcalendar/issues/4893
↑
Please visit the above issue, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates.
