### ISSUE TITLE
在点击空白处会显示高亮，但是为什么点击事情上没有高亮了，而且还会取消掉本来有的高亮

### ISSUE THREAD

**Issue by 516918847** [fullcalendar/fullcalendar#5279]
### Bug Reports
You MUST post a recreation or else your issue will be CLOSED without explanation.
Instructions: https://fullcalendar.io/reporting-bugs

### Feature Requests
Search the issue tracker for an existing ticket before creating a new one.
Instructions: https://fullcalendar.io/requesting-features

### React/Vue/Angular/etc
If your bug is specific to one of these frameworks, use the corresponding tracker.
List: https://github.com/fullcalendar

(Please erase the above text and begin typing. Thanks!)

**Comment by acerix** [comment]
Would you be able to post a [runnable, stripped-down demonstration of the bug](http://fullcalendar.io/wiki/Reduced-Test-Cases/)? Would really appreciate it because the time saved reproducing will be time spent fixing.
