### ISSUE TITLE
Scroll position is reset by refetchEvents when there are multiple event sources

### ISSUE THREAD

**Issue by datatraders** [fullcalendar/fullcalendar#5282]
Refetching events in a resource-timegrid or resource-daygrid **with more than one resource** resets the scroll position to the top.
The event sources in out test case are a json feed.

If we have only one calendar in this view the current position is not changed on refetching events.

here is a test environment: https://dev1.data-traders.de/test2/fc/

**Comment by acerix** [comment]
I tested in the debug template and refetchEvents does not change the scroll position:

https://codepen.io/acerix/pen/zYGwerG?editors=0010

If there is still an issue, please post a [runnable, stripped-down demonstration](http://fullcalendar.io/wiki/Reduced-Test-Cases/).

**Comment by datatraders** [comment]
I have posted a link to a stripped down test site, that shows the error. The error only occurs with **more than one** eventsource.

With one eventsource everything ist fine: https://dev1.data-traders.de/test2/fc/index2.htm
The same environment with 2 eventsources and a refetch of events resets the scroll position: https://dev1.data-traders.de/test2/fc/index1.htm

**Comment by acerix** [comment]
Thanks, I can see the issue with 2 event sources.  It was hard to see in your demo because the code is not formatted. 

https://codepen.io/acerix/pen/NWqjVgo?editors=0010

**Comment by japhfortin** [comment]
+1

**Comment by arshaw** [comment]
Doesn't happen in v5 anymore:
https://codepen.io/arshaw/pen/GRoMYER?editors=1010
