### ISSUE TITLE
Old view set at time of event request when view is changed and lazyLoading is false.

### ISSUE THREAD

**Issue by easededge** [fullcalendar/fullcalendar#5283]
I need to fetch events every time a view is switched, and need to pass the view to the server.

However, the old view is still set at the time the events are requested from the server.

For example, the following codepen alerts the view I am switching _from_, not the new view.

Switch views in the following codepen illustrates the issue 
https://codepen.io/bestrong89/pen/RwPVmdY?editors=0010

**Comment by acerix** [comment]
I believe this existing ticket captures this need:
https://github.com/fullcalendar/fullcalendar/issues/4660
↑
Please visit the above issue, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates.
