### ISSUE TITLE
Add spacing margin before or after events where other events are not allowed

### ISSUE THREAD

**Issue by WouterSchoofs** [fullcalendar/fullcalendar#5285]
Is there a possibility to add extra time to a event for blocking more than just the event period? We want to give our users the possibility to add "service minutes" to an event because sometimes they need time to prepare the meeting room.

**Comment by acerix** [comment]
You could set your "margins" for each event in `extendedProp` and use `eventOverlap` to block events where the margins overlap.

If you want to make the margin visible, I believe this request would cover that:
https://github.com/fullcalendar/fullcalendar/issues/5099
↑
Please visit the above issue, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates.

**Comment by arshaw** [comment]
this other ticket already captures this need:
https://github.com/fullcalendar/fullcalendar/issues/3174
&uarr;
Could you please visit the link, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates?
