### ISSUE TITLE
Creating calendar got 'getClass' of undefined in renderSkeletonHtml

### ISSUE THREAD

**Issue by ricardofct** [fullcalendar/fullcalendar#5286]
Hi there,

Today I was updating my project to Angular 9 and Fullcalendar/angular to the last version (^4.4.5-beta) and
I got an error related to "theme" in renderSkeletonHtml, [can see it here](https://ibb.co/ykp2Cyv).

I think this issue is related to fullcalendar lib and is not to angular lib.

What do you think?

PS: My  package.json

    "@fullcalendar/angular": "^4.4.5-beta",
    "@fullcalendar/core": "^4.4.0",
    "@fullcalendar/daygrid": "^4.3.0",
    "@fullcalendar/interaction": "^4.3.0",
    "@fullcalendar/list": "^4.3.0",
    "@fullcalendar/rrule": "^4.4.0",
    "@fullcalendar/timegrid": "^4.3.0",`

**Comment by acerix** [comment]
Would you be able to post a [runnable, stripped-down demonstration of the bug](http://fullcalendar.io/wiki/Reduced-Test-Cases/)? Would really appreciate it because the time saved reproducing will be time spent fixing.

It might not work in Angular 9 yet as the component only supports Angular 7 & 8.

**Comment by ricardofct** [comment]
Sure, I will try to reproduce it in a small version of my project, after that I post it here.

**Comment by ricardofct** [comment]
Got the issue, was the diference of versions :
`
"@fullcalendar/angular": "^4.4.5-beta",
"@fullcalendar/core": "^4.4.0",

here is 4.3.0
"@fullcalendar/daygrid": "^4.3.0",
"@fullcalendar/interaction": "^4.3.0",
"@fullcalendar/list": "^4.3.0",
"@fullcalendar/rrule": "^4.4.0",
"@fullcalendar/timegrid": "^4.3.0",`
`

Sry about this, ty.

**Comment by caoguanghua** [comment]
Hello Ricardofct , have you solved this problem? I also have this problem after upgrading from version 4.3.1
