### ISSUE TITLE
Allow maxTime and minTime configurable by Day Of Week

### ISSUE THREAD

**Issue by pgeyman** [fullcalendar/fullcalendar#5291]
The timelineView only allows setting maxTime and minTime for the whole view.

We have a requirement to show a 7 day timeline view with different time ranges for different days of the week as working hours are different for different days of the week. Users want to easily see events for working hours and do not want to have to scroll through many hours of the day that never have events. 

e.g. the view shows a week (7 days). On Monday-Friday we want the view to have minTime 07:00:00 and maxTime 18:00:00 and on Saturday-Sunday  to have minTime 00:00:00 and maxTime 24:00:00

How is it possible to achieve this?

**Comment by acerix** [comment]
I believe this existing ticket captures this need:
https://github.com/fullcalendar/fullcalendar/issues/5224
↑
Please visit the above issue, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates.
