### ISSUE TITLE
Violation] Added non-passive event listener to a scroll-blocking 'touchstart' event on fullcalendar inital load

### ISSUE THREAD

**Issue by jango07** [fullcalendar/fullcalendar#5294]
![image](https://user-images.githubusercontent.com/53347666/76028813-58582880-5f01-11ea-9e59-5b1388245f8e.png)

**Comment by acerix** [comment]
Would you be able to post a [runnable, stripped-down demonstration of the bug](http://fullcalendar.io/wiki/Reduced-Test-Cases/)? Would really appreciate it because the time saved reproducing will be time spent fixing.
