### ISSUE TITLE
Prevent selecting text in events

### ISSUE THREAD

**Issue by ravid007** [fullcalendar/fullcalendar#5295]
Selection of the Fullcalendar html components in the browser (pressing and holding down the left mouse button and then moving the mouse while still holding down the left mouse button) behaves diffrent in v3 and v4.

In v3 the selection is available only for title, buttons text and resources title (https://fullcalendar.io/docs/v3/vertical-resource-standard-demo).
![image](https://user-images.githubusercontent.com/11653718/76030844-2b2a6b00-5f3f-11ea-9aba-e6322f58dcab.png)

In v4 selection is available for every text except the buttons text (https://fullcalendar.io/docs/vertical-resource-standard-demo).
![image](https://user-images.githubusercontent.com/11653718/76030790-0fbf6000-5f3f-11ea-9113-93d418933488.png)

The difference spotted while migrating from v3 to v4, In my opinion the expected behavior would be that such selection will not be available (Similar to v3)

Thanks!
Ravid

**Comment by acerix** [comment]
You can use `user-select: none;` CSS on event elements or the entire calendar to prevent selection:

https://codepen.io/acerix/pen/RwPjoPN?editors=0100

**Comment by ravid007** [comment]
Cool, thanks a lot !ns for **next** (`fc-prev-button`) and **prev** (`fc-next-button`)  are opposite.
 
One more tiny thing. When setting the `themeSystem: 'bootstrap'` and `locale` to any RTL language (For example Hebrew or Arabic) the ico
`themeSystem: 'standard'`
   Prev icon - `fc-icon-chevron-right`
   Next icon - `fc-icon-chevron-left`

`themeSystem: 'bootstrap'`
   Prev icon - `fa-chevron-left` (should be **right**)
   Next icon - `fa-chevron-right` (should be **left**)

The problem is only when `themeSystem: 'bootstrap'`, for `themeSystem: 'standard'` it works as required.

**Comment by arshaw** [comment]
often fullcalendar prevents text-selection when the mousedown originates from within the calendar, but as you point out, it does not prevent text selection when the mousedown originates from outside.

IMO, this is not the responsibility of FC. In fact, some other developers might want certain parts of FullCalendar to remain selectable. So, closing this ticket, as it's possible to customize via CSS

**Comment by shakirayoub123** [comment]
![Screenshot from 2023-02-02 20-49-40](https://user-images.githubusercontent.com/117161359/216520049-24f8f112-05f9-42ed-b9be-c56623e72701.png)

in my case buttons are functional but fc-icons are not visible i tried everything but nothing works

**Comment by ewarrenG** [comment]
I also commented on [issue 5628](https://github.com/fullcalendar/fullcalendar/issues/5628#issuecomment-2132045434)

@arshaw can you elaborate on how this is "possible to customize via CSS"?
