### ISSUE TITLE
License warning

### ISSUE THREAD

**Issue by ricardopt** [fullcalendar/fullcalendar#5296]
Hello,

I'm using fullcalendar but only the standard version https://fullcalendar.io/license however on my website I have a warning "Please use a valid license key".
I'm using "timeGridWeek" that belongs to the standard view. How can I remove the warning?

Best regards,
Ricardo

**Comment by gongAll** [comment]
Easier workaround would be adding this line to the calendar component:
`
  schedulerLicenseKey: 'GPL-My-Project-Is-Open-Source'
`
If you are using the component for an open source project. 

But to address the problem in particular, if your code is not open source, are you importing the schedule module anywhere in your project? Sharing some code regarding your code structure would be helpful.

**Comment by ricardopt** [comment]
I was importing the wrong plugin :( sorry for spamming this. 
For historic purposes and clarity for other person so the plugin I was importing was: resourceTimeGridPlugin
and the one I want was: timeGridPlugin
(both of them worked for my use case)

This can be closed. Thanks
