### ISSUE TITLE
Date click not working on inital load

### ISSUE THREAD

**Issue by jango07** [fullcalendar/fullcalendar#5297]
I am using fullcalendar.Below is how i initialized fullcalendar.
 const calendarEl = this.querySelector('#calendar');
        this.calendar = new FullCalendar.Calendar(calendarEl, {
            selectable: true,
            events: this.events,
            eventRender: this.eventsRendering.bind(this),
            header: {
                left: 'prev',
                center: 'title',
                right: 'next',
            },
            dateClick: this.dateSelect.bind(this),
            selectAllow: this.checkForselection.bind(this),
        });
        this.calendar.render();

whenever the calendar is loaded the dateclick method doesnt fire.(not even the selectallow)but if i resize the screen or navigate to some other month dateclick event gets triggered.
Any suggestions ?
Thanks for any help..

Version used  4.0.0-alpha.2

Ja

**Comment by jango07** [comment]
working with version 4.0.0-alpha.2

**Comment by acerix** [comment]
Would you be able to post a [runnable, stripped-down demonstration of the bug](http://fullcalendar.io/wiki/Reduced-Test-Cases/)? Would really appreciate it because the time saved reproducing will be time spent fixing.
