### ISSUE TITLE
How can I test v5?

### ISSUE THREAD

**Issue by tsyrya** [fullcalendar/fullcalendar#5300]
I've cloned the branch with the v5 version, it builds with "gulp build" command. But I wanna test the new premium features, I know it is a bit early now, but I want to know if it is worth waiting. I downloaded the source files, but I have no idea how to build them. Could you give me a hint, please?

**Comment by acerix** [comment]
You can build it with these instructions, it needs to be a "recursive" clone to get the scheduler submodule.

https://github.com/fullcalendar/fullcalendar/blob/v5/CONTRIBUTING.md#getting-set-up
