### ISSUE TITLE
Resources with a numeric id are not displayed in the order they were specified

### ISSUE THREAD

**Issue by acerix** [fullcalendar/fullcalendar#5301]
Without `resourceOrder`, the resources should appear in the order they were specified but they instead get ordered by their `id`.

https://codepen.io/acerix/pen/bGdLvmM?editors=0010

Reported in https://fullcalendar.freshdesk.com/a/tickets/1522

**Comment by acerix** [comment]
Works as expected if the resource id's are letters: https://codepen.io/acerix/pen/LYVQdwR?editors=0010

**Comment by arshaw** [comment]
in v5, resources are no longer ordered in the order way are received. they are ordered alphabetically by id, then title. So, that makes this issue a moot point.

This is documented in the upgrade guide, but not the docs. I'll get to that soon

**Comment by darkpixel** [comment]
I must be missing something.  If the resource IDs are numeric *or* if they are numbers in string format, they don't sort correctly.
i.e.
```
resources: [
  { id: 1, "Bob Smith (Room 1)" },
  { id: 2, "Jeff Johnson (Room 4)" },
  { id: 10, "Susie Smith (Room 9)" },
```
Yields:
```
Susie Smith (Room 9)
Bob Smith (Room 1)
Jeff Johnson (Room 4)
```

It doesn't matter if the resource IDs are quoted or not.  You're doing an alphabetic sort, not a numeric sort.
Tested in version 5.3.2.

**Comment by arshaw** [comment]
Hi @darkpixel , they are sorting for me as-desired for both number IDs and strings.

numbers:https://codepen.io/arshaw/pen/NWRpzeZ?editors=0010
strings: https://codepen.io/arshaw/pen/JjRWZxy?editors=0010

Could you post a separate issue with a reproducible link if the problem persists for you?

**Comment by ajaydev12** [comment]
> in v5, resources are no longer ordered in the order way are received. they are ordered alphabetically by id, then title. So, that makes this issue a moot point.
> 
> This is documented in the upgrade guide, but not the docs. I'll get to that soon

@arshaw - I was wondering, the rationale behind this default setting? In most cases, the API's return resources in the order they would need to be displayed. Also when using guid for id - the default sort is not ideal.
