### ISSUE TITLE
Time slot labels start at 24:00 instead of 00:00 in Chrome with "hour12:false"

### ISSUE THREAD

**Issue by spatertot** [fullcalendar/fullcalendar#5303]
When the calendar is in timeGridWeek and the slotLabelFormat has 'hour12:false' the first slot is now 24:00 instead of 00:00.
https://codepen.io/spatertot/pen/ExjQJLN?editors=0010
![image](https://user-images.githubusercontent.com/60332571/76516675-3d6e4280-6432-11ea-90e4-c35c4eaf8597.png)

**Comment by spatertot** [comment]
After further testing, this issue exists in chrome but not firefox

**Comment by LuisSanches-GitHub** [comment]
The issue exists in both 12 hour mode and 24 hour mode.
Both the **slotLabelFormat** & **eventTimeFormat** have this problem when in **timeGridWeek**
In 12 hour mode:   **12:00am & 12:30am** instead of 00:00 & 00:30
In 24 hour mode:  **24:00 & 24:30** instead of 00:00 & 00:30

The beginning of a day in 12 hour or 24 hour should always be 00:00.

In my view, 12:00am and 24:00 should **only** be used to signify the **END** of a day - they are analogous to 00:00 in the following day.

![image](https://user-images.githubusercontent.com/62107239/76532982-47fafd00-646f-11ea-8c76-a7130b7f92fb.png)

![image](https://user-images.githubusercontent.com/62107239/76533101-737de780-646f-11ea-9a74-e415fe95cdaf.png)

**Comment by acerix** [comment]
Thanks, confirmed.

Another way to get 24 hour format is to set the `locale` to 'en-GB' which doesn't have this issue:

https://codepen.io/acerix/pen/poJLJyb?editors=0010

Or you could use a plugin like moment.js for more control over the format.

https://fullcalendar.io/docs/moment-plugins

**Comment by arshaw** [comment]
this behavior is dependent on the locale. as @acerix mentioned, set your locale to one that has this behavior, like 'en-gb'

**Comment by rgolekar** [comment]
Use of  `locale` is the only option to resolve this issue? Will it cause any other functionality to change like event time format/zone etc?

**Comment by rishavjain25** [comment]
Using "en-GB" as locale changed the format of how days(column header) are displayed in weekly view i.e they are displayed as ddd D/M (Mon 28/2) but i need it to be of format ddd M/D (Mon 2/22)

**Comment by babymaychen** [comment]
How to solve this problem when I want to set the local to zh-cn?

**Comment by selahattinunlu** [comment]
This is really weird issue.  I tried to fix this issue using `eventContent` hook but I must handle too many things if I use this method.
The issue is fixed when I set `en-GB` to locale. But why I need to set this locale, really weird :D 

By thy way, @rishavjain25, you can fix the day format by adding `dayHeaderContent` option into options.

```
dayHeaderContent: (arg) => {
    return moment(arg.date).format("YYYY-MM-DD"); // change format as you want of course
},
```

https://fullcalendar.io/docs/day-header-render-hooks

**Comment by YllzaCanaj** [comment]
On v5 you can do this:

 slotLabelFormat={[
          {
            hour: "2-digit",
            minute: "2-digit",
            meridiem: false,
          },
        ]}

**Comment by Troy-Yang** [comment]
Workaround is to customize the timeslot label:

const MID_NIGHT = '24:00';
const START_TIME = '00:00';

const TimelineLabelContent = ({ timeFormat, date }: { timeFormat: TimelineTimeFormat, date: Date }) => {
  const timeString = shortTimeOf('en-US', {
    timeFormat,
  })(date.toISOString());
  return (<span className="calendar-scheduler__timeline-label">
    {timeString === MID_NIGHT ? START_TIME : timeString}
  </span>);
};

export const shortTimeOf = (
  locale: string = DEFAULT_LOCALE,
  options?: { timeFormat: TimelineTimeFormat }) => (datetime: string) => {
  const { timeFormat = TimelineTimeFormat.TWENTY_FOUR_HOURS } = options || {};
  return new Intl.DateTimeFormat(locale, {
    hour12: timeFormat === TimelineTimeFormat.TWELVE_HOURS,
    hour: 'numeric',
    minute: 'numeric',
    timeZone: 'UTC',
  }).format(new Date(datetime));
};

**Comment by Muhiq146** [comment]
You can try this also, it works.

```
locale='en-GB'
slotLabelFormat={{hour: 'numeric', minute: '2-digit', omitZeroMinute: false}}
```

**Comment by suleymanmv** [comment]
slotLabelContent={(info) => {
                if (info.text.split(":")[0] === "24") {
                  info.text = `00:${info.text.split(":")[1]}`;
                }
              }}

**Comment by madly0894** [comment]
I think this is the best solution without any if
`
slotLabelFormat: {
    hour: '2-digit',
    minute: '2-digit',
    hour12: false,
},
slotLabelContent: info => info.text.replace(/24:00/g, '00:00');
`

**Comment by madly0894** [comment]
slotLabelFormat: {
    hour: '2-digit',
    minute: '2-digit',
    hour12: false,
},
slotLabelContent: info => {
    if (info.text === '24:00') {
        info.text = '00:00';
    }
},

**Comment by madly0894** [comment]
I think this is the good solution without any if
```
slotLabelFormat: {
    hour: '2-digit',
    minute: '2-digit',
    hour12: false,
},
slotLabelContent: info => info.text.replace(/24:00/g, '00:00');
```

**Comment by juwul** [comment]
> Thanks, confirmed.
> 
> Another way to get 24 hour format is to set the `locale` to 'en-GB' which doesn't have this issue:
> 
> https://codepen.io/acerix/pen/poJLJyb?editors=0010
> 
> Or you could use a plugin like moment.js for more control over the format.
> 
> https://fullcalendar.io/docs/moment-plugins


Thanks for the codepen 👌🏼 
It is a weird issue, and in my opinion, it should be changed to default work without setting the local.
But I have made it work with the following configuration:

```
slotDuration: '00:15:00',
slotLabelInterval: '01:00',
slotMinTime: '00:00:00',
slotMaxTime: '24:00:00',
scrollTime: '00:00:00',
locale: userCountry === 'US' ? 'en-US' : 'en-GB',
firstDay: userCountry === 'US' ? 0 : 1,
slotLabelFormat: userCountry === 'US' ?
    { // am pm time
        hour: 'numeric',
        minute: '2-digit',
        omitZeroMinute: true,
        meridiem: 'short'
    }
    : { // military time
        hour: '2-digit',
        minute: '2-digit',
        hour12: false
    },
eventTimeFormat: userCountry === 'US' ?
    { // am pm time
        hour: 'numeric',
        minute: '2-digit',
        omitZeroMinute: true,
        meridiem: 'short'
    }
    : { // military time
        hour: '2-digit',
        minute: '2-digit',
        hour12: false
    },
```
