### ISSUE TITLE
### Bug Reports: Background event bug in DayGridView

### ISSUE THREAD

**Issue by Dev1lDragon** [fullcalendar/fullcalendar#5306]
### Bug Reports
If we have more than 1 event in week its not be reachable.

I have 4 events (wed/thu/fri/sat) when is reachable is also last sat.

[bug recreation and proposal correction in css section](https://codepen.io/dev1ldragon/pen/poJLMBz)

**Comment by arshaw** [comment]
i'm not sure what the correct UI solution is here. the events are the same color and overlap each other, looking as one.

here are two other tickets proposing alternate UIs:
https://github.com/fullcalendar/fullcalendar/issues/4280
https://github.com/fullcalendar/fullcalendar/issues/3100
&uarr;
Could you please visit the links, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates?
