### ISSUE TITLE
Uncaught TypeError: Cannot read property 'appendChild' of undefined

### ISSUE THREAD

**Issue by buddyy93** [fullcalendar/fullcalendar#5308]
i have included the list plugin and it shows the error below.

![Snipaste_2020-03-17_11-37-54](https://user-images.githubusercontent.com/22981271/76816516-cb3b9a80-6843-11ea-9640-155a5cd8fea0.png)

expected behaviour is shown below.

![Snipaste_2020-03-17_11-40-03](https://user-images.githubusercontent.com/22981271/76816647-1655ad80-6844-11ea-8c43-1d0cb7857b13.png)

Can anyone help me to fix it ? thank you

**Comment by acerix** [comment]
Would you be able to post a [runnable, stripped-down demonstration of the bug](http://fullcalendar.io/wiki/Reduced-Test-Cases/)? Would really appreciate it because the time saved reproducing will be time spent fixing.
