### ISSUE TITLE
fullcalendar in ng-repeat issue

### ISSUE THREAD

**Issue by shriram0436** [fullcalendar/fullcalendar#5309]
can you help me with issue described [here](https://stackoverflow.com/questions/60704641/full-calendar-in-ng-repeat)

i'm using calendar in repeat but if i update second calendar first calendar also getting updated.

thanks :)

**Comment by acerix** [comment]
Would you be able to post a [runnable, stripped-down demonstration of the bug](http://fullcalendar.io/wiki/Reduced-Test-Cases/)? Would really appreciate it because the time saved reproducing will be time spent fixing.

**Comment by shriram0436** [comment]
sure :) please find attached files
[dept_test.zip](https://github.com/fullcalendar/fullcalendar/files/4347434/dept_test.zip)

**Comment by acerix** [comment]
It doesn't look like a bug in FullCalendar, it seems that happens because you have the dates of each calendar stored in the same variables. You need to make use separate variables for each calendar to make them independent.
