### ISSUE TITLE
Rendering, dragging, resizing events during night (over midnight) with scheduler

### ISSUE THREAD

**Issue by LrntL** [fullcalendar/fullcalendar#5310]
Hi,

I'm working with fullcalendar 3.10.0 and scheduler 1.10. 

Do you know how can we make an event between 10pm and 1am (22h and 1h) resizable and draggable ?

This bug has been reported many times but no fix has been found. It still happening in version 4.

How can we use working hours during night with scheduler ?
My working hours are 5pm to 2am (17:00 - 02:00) and I need to drag, resize events starting before midnight and ending after midnight.

When I do something, the event is cropped at midnight during dragging or resizing.
On drag stop, event get the right start and end hour but during dragging or resizing, the time of the event after midnight is hidden.

Please help, I'm on this for months !

**Comment by acerix** [comment]
I believe this existing ticket captures this need:
https://github.com/fullcalendar/fullcalendar/issues/3900
↑
Please visit the above issue, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates.
