### ISSUE TITLE
Drag and drop broken, onReceive called multiple times

### ISSUE THREAD

**Issue by Ryanauger95** [fullcalendar/fullcalendar#5311]
### Bug Reports
Here is a re-creation from another user with the same issue here:

https://codesandbox.io/s/strange-pine-5xkre

Any idea what the issue could be ? Doesn't seem like this is intentional. It seems drag and drop is broken

### React/Vue/Angular/etc
I am experiencing this issue with React, however, I imagine this is a calendar agnostic issue. Also, it seems this repo is far more responsive!

**Comment by acerix** [comment]
Would you be able to post a [runnable, stripped-down demonstration of the bug](http://fullcalendar.io/wiki/Reduced-Test-Cases/)? Would really appreciate it because the time saved reproducing will be time spent fixing.

I don't see any issue in that demo, dropping one of the events on the calendar only calls `eventReceive` one time as expected.

**Comment by conor909** [comment]
I recently had an issue where my on external drop events were firing 4 times, creating 4 duplicate events from 1 drop.  I realised I had my initialisation function ie: `new Calendar()`, inside a loop, so it seemed to create 4 calendars on the DOM.  Fixing this solved the issue.  Hope thats relevant for someone.

**Comment by DeanWunder** [comment]
Thank you @conor909 !
Also to anyone else with this issue: ensure you also have on instance of other objects as well, e.g. `new Draggable(...)`.

**Comment by kindarin** [comment]
> Thank you @conor909 ! Also to anyone else with this issue: ensure you also have on instance of other objects as well, e.g. `new Draggable(...)`.

This was my problem. I was creating a draggable every time my modal (which contains my calendar) opened. I made sure it happened only once and then the multiple drop events stopped firing.

**Comment by ewarrenG** [comment]
+1

Would it be possible for someone who's experienced this issue and resolved it to post the changes they made to their code so I can understand the issue and solution properly... Thanks!
