### ISSUE TITLE
Support for FontAwesome SVG button icons

### ISSUE THREAD

**Issue by bsautel** [fullcalendar/fullcalendar#5313]
First of all, thanks to all the fullcalendar contributors for this wonderful tool!

In the project in which I use fullcalendar, I use FontAwesome SVG icons and not CSS class based icons.

The buttons text configuration enables to configure text, but does not accept HTML, so I cannot insert SVG icons into the buttons.

I found a workaround: I listen to the view rendering and just after it is done, I render the icons using DOM CSS selectors.

It worked with fullcalendar 4.3.1 but no longer works with fullcalendar 4.4.0.

I created a simple project that reproduces it [here](https://github.com/bsautel/fullcalendar-render-bug).

In the `master` branch, the previous and next buttons contain a SVG icon.

When we switch to the `4.4` branch (don't forget to `npm install` and restart `webpack`), the icons are present only at first rendering but disappear as soon as we click on them.

I was not able to make it work with fullcalendar 4.4.0.

I analyzed the code changes and it could code from the fact the skeleton rendering is now memoized. I don't know exactly how it works, but the result is maybe (I could not easily check that) saved before the `viewSkeletonRender` hook is triggered, which could be the cause of the loss of the customization.

I know that my workaround is not very clean but I did not any other solution to use SVG icons.

Is this behavior a regression? In this case it should be fixed? Or should I use another way to get SVG icons work?

Thanks a lot!

**Comment by acerix** [comment]
It seems the button elements are now rendered when the date changes, so it works if you use `datesRender` instead of `viewSkeletonRender`.

**Comment by bsautel** [comment]
Thanks @acerix for your quick answer.

You are right, your suggested fix works in the small project I created to reproduce the issue.

But before creating this issue, I already tried doing this (in the project in which I use fullcalendar for real) and it did not work. To be more precise, what happens is that the toolbar is rendered correctly when loading but is rendered again immediately after (I see this thanks to the debugger) without the customization, as if it was restored from the cache or repainted without calling the hook. Note that this happens whether I also try to render icons from `datesRender` or not.

I still don't know where this issue comes from. My integration is much complex that the small project I created to show the issue. I also use the Angular wrapper. I am going to investigate to find what causes this issue. I will let you know.

Have a nice day, and thanks again!

**Comment by bsautel** [comment]
After multiples hours of investigation, I finally discovered that I did something wrong.

It has to do with the `defaultDate` property. I save the currently displayed date in the session storage to get the calendar display the previously displayed period by default when the user comes back to the calendar.

I use the Angular wrapper and it appears that each time the user navigated in the calendar (for instance next week), the value of the `defaultDate` binding also changed. The Angular wrapper detects it and probably asks the calender to render again. This causes an unnecessary repaint that takes some time. I changed my code so that the `defaultDate` value no longer changes.

Something probably changed between 4.3 and 4.4 because this worked with 4.3. I could see with the debugger that for instance when I click on next week, the view is updated, the `onRenderDates` hook is called and the icon customization works. But just after, the Angular wrapper renders the calendar again and this time the `onRenderDates` hook is not called and my icons are not displayed. I don't know why.

That's not a big deal, it now works for me.

But that would be nice to have a builtin support of SVG icons instead of having to use such hooks. Or accept HTML in the configuration. I also have this issue in events, I need to display some icons in events and I have to do it manually right using the `onRenderEvents` hook.

**Comment by arshaw** [comment]
please see this ticket for the latest on fontAwesome in v5:
https://github.com/fullcalendar/fullcalendar/issues/5544
&uarr;
Could you please visit the link, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates?
