### ISSUE TITLE
navLinks are not clickable if slotLabelFormat is a moment format

### ISSUE THREAD

**Issue by acerix** [fullcalendar/fullcalendar#5317]
Reported in https://fullcalendar.freshdesk.com/a/tickets/1665

Day names are not clickable, works without `slotLabelFormat`:

https://codepen.io/acerix/pen/bGdxXLB?editable=true&editors=001

**Comment by arshaw** [comment]
still in v5: https://codepen.io/arshaw/pen/QWyqZBg?editable=true&editors=001

**Comment by arshaw** [comment]
fixed in 5.2.0: https://codepen.io/arshaw/pen/QWyqZBg?editors=0010

@acerix , could you please notify the customer?
