### ISSUE TITLE
Option to use existing moment-timezone instance to preserve it's default time zone

### ISSUE THREAD

**Issue by kamilchlebek** [fullcalendar/fullcalendar#5318]
### Description 
I'm using `moment` and `moment-timezone` in our company project. When the app bootstraps I'm setting `moment.tz.setDefault(timezone)`. I have noticed that after including `@fullcalendar/moment-timezone` plugin my default settings are overridden - to be more precise, whole instance is replaced with the new one.

It's caused by this import: 
https://github.com/fullcalendar/fullcalendar/blob/f5470c2cb63579b737172eca046196e232474f2e/packages/moment-timezone/src/main.ts#L7

Few years ago, `moment-timezone` would log an error when it was about to replace existing instance, but this behavior changed ( https://github.com/moment/moment-timezone/commit/f22020d630f1a239addf3ceea0b23e6407c9b9e2 )

### Version affected
Fullcalendar v4

### Demo
https://stackblitz.com/edit/typescript-sc2nap?file=failing-demo.ts

### Possible solution

Could you add an option to provide `@fullcalendar/moment-timezone` configuration with existing `moment.tz` instance?

#### Workaround

Temporarily I've created my own `MomentNamedTimeZone` which is exact the same as original but without `import 'moment-timezone/builds/moment-timezone-with-data'`

**Comment by arshaw** [comment]
v5, which has [just been released](https://fullcalendar.io/blog/2020/06/v5-official), imports simply `'moment'` and `'moment-timezone'`

**Comment by kamilchlebek** [comment]
Thank you! I'll have a look soon :rocket:
