### ISSUE TITLE
Custom view will not show multiple years in a listYear

### ISSUE THREAD

**Issue by easededge** [fullcalendar/fullcalendar#5320]
https://codepen.io/bestrong89/pen/bGdQZOz

I have a calendar on a customer page in a custom application and would like to display all events (for a specific customer) for all time in listYear view.

I have a custom view as ListYearAll, and have set the date range from 1980 to 2230, which effectively would get all possible events, but it is still only displaying one year. In the documentation, it says you can specify a custom visible range.

```
 views: {
          listYearAll: {
            type: 'listYear',
            buttonText: 'List',
            visibleRange: {
              start: '1980-01-01',
              end: '2230-01-01'
            }
          }
        },
```

**Comment by acerix** [comment]
It works if you extend the 'list' view instead of 'listYear'.

https://codepen.io/acerix/pen/PoqXGEv?editors=0010

**Comment by easededge** [comment]
Thanks and apologies for the false alarm.
