### ISSUE TITLE
Responsive full calendar

### ISSUE THREAD

**Issue by throne1986** [fullcalendar/fullcalendar#5322]
It will be very good if you guys could provide a view  which uses bootstrap without table just div's so that users can be able to manipulate the calendar as they wish, now its looks very bad in a small device, meaning it's not responsive I would like to do something like this in mobile

![image](https://user-images.githubusercontent.com/27904724/77764781-7e26a800-703d-11ea-9e30-8f3e4f6a54ac.png)

inspired with promo calendar https://promo.com/tools/calendar/March

**Comment by acerix** [comment]
I believe this existing ticket captures this need:
https://github.com/fullcalendar/fullcalendar/issues/3187
↑
Please visit the above issue, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates.

For now, you could make a custom view:

https://fullcalendar.io/docs/custom-view-with-js
