### ISSUE TITLE
Using resourceRender with multiple resourceColumns

### ISSUE THREAD

**Issue by aximuseng** [fullcalendar/fullcalendar#5330]
I am using the timeline view with a group field and multiple resourceColumns.  I am looking to ad links to the columns.  Figured I would try `resourceRender` like had done before with `eventRender` like this (this example is from the docs - simple background color:

https://codepen.io/dantappin/pen/yLNrQwj

The issue I see (unless this (un)documented somewhere) is that it only acts on the first resource.  In my JSON feed I have the URL I want to apply to to these.

**Comment by acerix** [comment]
The resource element is the just the one cell (td), so you can use the parent element (tr) to style the other columns:

https://codepen.io/acerix/pen/MWwRZNW?editors=0010

**Comment by aximuseng** [comment]
Awesome - thanks for the tip.  It's completely obvious now - didn't even dawn on me to just traverse up the DOM 🤦‍♂️.  All I could think was from a FC perspective.
