### ISSUE TITLE
Option for JSON feed (URL) Event Sources to set XMLHttpRequest.withCredentials for authorisation

### ISSUE THREAD

**Issue by edwardmjackson** [fullcalendar/fullcalendar#5331]
When using a JSON event source in an enterprise environment, the API endpoints typically require kerberos authentication. 

Currently, there is no option in the eventsources object to set withCredentials as true/false.

eventSources: [
    {
      url: '/myfeed.php'
      // Proposed new option
      // withCredentials: true 
    }

There is a workaround, to use an eventSource function that wraps XMLHttpRequest, but it loses the convenience of a URL source.

**Comment by acerix** [comment]
I believe this existing ticket captures this need:
https://github.com/fullcalendar/fullcalendar/issues/4627
↑
Please visit the above issue, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates.
