### ISSUE TITLE
Add classes (e.g. fc-sat) for styling weekday columns when slotLabelInterval is in hours

### ISSUE THREAD

**Issue by darrenparkinson** [fullcalendar/fullcalendar#5333]
When adding a slotLabelInterval, the classes for week day are no longer present.  As a result I can no longer style the weekends differently.

[Example Code For The Issue](https://github.com/darrenparkinson/fullcalendar-issue)

**Comment by acerix** [comment]
I see how that could be useful but I think it's a new feature since the weekday classes are not documented but it makes sense they should also be added in this case:

https://codepen.io/acerix/pen/QWbPxeE?editors=0110

For now you could use `datesRender` to add the classes manually.

**Comment by arshaw** [comment]
v5 (in beta) has this
https://fullcalendar.io/docs/v5/timeline-custom-view-demo

see the classnames like `fc-slot-sat`

**Comment by arshaw** [comment]
officially released: https://fullcalendar.io/blog/2020/06/v5-official
