### ISSUE TITLE
Navigation buttons cause form to be submitted if calendar is within a form element

### ISSUE THREAD

**Issue by Karl-Parris** [fullcalendar/fullcalendar#5336]
After updating to v5 beta, if the calendar is within a form element, the form is submitted when switching months due to the buttons missing type="button".

Example: https://codepen.io/ParadoxKarl/pen/LYVKvdP

**Comment by acerix** [comment]
Thanks, confirmed

**Comment by melloware** [comment]
Is this a duplicate of: https://github.com/fullcalendar/fullcalendar/issues/5336 ???

**Comment by arshaw** [comment]
duplicate of https://github.com/fullcalendar/fullcalendar/issues/5529 , which was just fixed and released
