### ISSUE TITLE
Event fields with null values are not ignored

### ISSUE THREAD

**Issue by osuagwu** [fullcalendar/fullcalendar#5338]
I am uputing data from database that to get something like:
Works:
```
[{
"title":"Event 3",
"start":1586305800000,
"end":1586307600000,
}];
```

Does not work:
```
[{
"title":"Event 3",
"start":1586305800000,
"end":1586307600000,
"startRecur":null,
"endRecur":null,
"daysOfWeek":null,
"groupId":null,
}];
```

FullCalender seem to get confused by this. I was believing that it will just ignore the values that are null but it seem to not now what to do when some values are null. In the second case it nothing gets shown. I feel it is not very effective if I have to check individual event field to see if user has set it or not to decide to include the field only if it is set, because I have to remember to revisit the bit of code when field lists changes.

Also it is better for me to output the every events in js with a complete set of fields otherwise I would have to use obj.hasOwnProperty anytime I need to access a particular field from my json feed because I cannot be sure if the field was included or not.

By the way if two events have groupId of null, they are still linked together. I just don't think this is how null values should be treated. They seem to be treated as real values in FullCalendar

**Comment by acerix** [comment]
Would you be able to post a [runnable, stripped-down demonstration of the bug](http://fullcalendar.io/wiki/Reduced-Test-Cases/)? Would really appreciate it because the time saved reproducing will be time spent fixing.

I tested your example event and don't see any issue:

https://codepen.io/acerix/pen/pojzbKj?editable=true&editors=001

**Comment by danilo-augusto** [comment]
He's right though. Passing "groupId: null" causes the events to bind together.

Here is a minimal example (commented):

```
document.addEventListener('DOMContentLoaded', () => {
  new FullCalendar.Calendar(
    document.getElementById('calendar'),
    {
      plugins: [ 'interaction', 'dayGrid', 'timeGrid' ],
      defaultView: 'timeGridWeek',
      defaultDate: '2020-05-23',
      editable: true,
      // BUG (or at least not expected behavior): "groupId: null" causes the events to bind together
      // Dragging/expanding event 1 causes event 2 to change accordingly, and vice-versa.
      // Event 3 is however unbound and free from the other two.
      events: [
        {title: '[EVENT 1] I am bound to event 2', start: new Date(2020, 4, 23, 12), end: new Date(2020, 4, 23, 13, 30), groupId: null },
        {title: '[EVENT 2] I am bound to event 1', start: new Date(2020, 4, 23, 14), end: new Date(2020, 4, 23, 15, 30), groupId: null },
        {title: '[EVENT 3] I am free', start: new Date(2020, 4, 23, 16), end: new Date(2020, 4, 23, 17, 30) },
      ]
    }
  ).render();
});
```

**Comment by danilo-augusto** [comment]
Dragging event 1 causes event 2 to move along...
![Screen Shot 2020-05-23 at 03 26 03](https://user-images.githubusercontent.com/8104631/82718812-2c994300-9ca5-11ea-834d-c22013e4edef.png)

**Comment by danilo-augusto** [comment]
Dragging `[Event 1]` makes `[Event 2]` move too:
![Screen Shot 2020-05-23 at 03 26 03](https://user-images.githubusercontent.com/8104631/82718830-52bee300-9ca5-11ea-89d4-977fdcf2d9d7.png)

**Comment by danilo-augusto** [comment]
For now my workaround is eliminating some "falsy" values (just empty strings and null values): `Object.keys(event).forEach(k => (event[k] === null || event[k] === '') && delete event[k])`

**Comment by ToNyRANDRIAMANANTSOA** [comment]
Same issue here, my workaround was to just give a `groupId` to each and every events (recurrent or not) upon creation.

**Comment by y7t2ffff** [comment]
> For now my workaround is eliminating some "falsy" values (just empty strings and null values): `Object.keys(event).forEach(k => (event[k] === null || event[k] === '') && delete event[k])`

it work，In my case 

events =[
  {
    "id": null,
    "title": null,
    "start": "2021-01-01",
    "end": null,
    "display": "background",
    "backgroundColor": "#61FF7E",
  },
  {
    "id": null,
    "title": null,
    "start": "2021-01-02",
    "end": null,
    "display": "background",
    "backgroundColor": "#61FF7E",
  }
]

it show "null" in background event
