### ISSUE TITLE
Resource render hooks example has error causing "resource.id is undefined"

### ISSUE THREAD

**Issue by SelectSystemsInternational** [fullcalendar/fullcalendar#5341]
V5 Beta - Example - resource-render-hooks.html
Seems it can not access the id of the resource ?
resource.id is UNDEFINED
![resource-render-hooks](https://user-images.githubusercontent.com/34350154/78776929-00b74c00-79dc-11ea-9337-be1b8d54df12.png)

**Comment by acerix** [comment]
The content injection argument is not the resource itself but an object with the resource in it:

https://codepen.io/acerix/pen/gOaYVjb?editors=0010

**Comment by SelectSystemsInternational** [comment]
Dont forget to fix your example

      resourceLabelContent: function(arg) {
        return 'Auditorium ' + ('' + arg.resource.id).toUpperCase();
      },

**Comment by acerix** [comment]
Thanks, I was looking at the wrong page and didn't see that example.

https://github.com/fullcalendar/fullcalendar/blob/master/examples/resource-render-hooks.html#L43

**Comment by arshaw** [comment]
thanks, i'll include this fix

**Comment by arshaw** [comment]
this is now fixed in `resource-render-hooks.html`. thanks
