### ISSUE TITLE
V5 View Render new hook that is called when the view was modified

### ISSUE THREAD

**Issue by Phibedy** [fullcalendar/fullcalendar#5342]
Hi,
I am currently giving V5 a try. The new hook concept is quite nice :+1: 

### Feature Requests
I need to keep track on the current visible dates. In the past I used datesRender to get notified when the view was modified. It would be great if a View Render Hook will be added which is called when the dates change.
For a workaround I think I can use the dayRender method and access the calendar to get the view. But this causes a lot of function calls and a hook would be much cleaner.
Btw. I don't care if the hook is called after the view was updated or before, I would just like to be informed if the view object changes.

Thank you for your support :)

**Comment by acerix** [comment]
I believe this existing ticket captures this need:
https://github.com/fullcalendar/fullcalendar/issues/3521
↑
Please visit the above issue, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates.

You could supply events as a function and get the dates there:

https://codepen.io/acerix/pen/yLYBmZP?editors=0010
