### ISSUE TITLE
Attribute snapDuration has no effect in timeGrid

### ISSUE THREAD

**Issue by datatraders** [fullcalendar/fullcalendar#5344]
I want to use snapDuration but it's not usable. The expected behavior on clicking on a timeslot is that a select helper with a timespan of the value in snapDuration should be created.

Please have a look at the minimalistic demo:
https://codepen.io/datatraders/pen/BaoBGWq

**Comment by acerix** [comment]
I believe this existing ticket captures this need:
https://github.com/fullcalendar/fullcalendar/issues/4865
↑
Please visit the above issue, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates.

The best workaround I could find is setting `slotDuration` to what you want for the snapping.

Another option is to use `selectAllow` if you want to prevent events that are not exactly 2 hours but that doesn't work great.

https://codepen.io/acerix/pen/vYNYBGN?editors=0010

**Comment by datatraders** [comment]
Ok. Thanks for your help. I thought the fault is fixed in version 4 because other tickets refer to version 3 and lower. The attribute `snapDuration ` stil exists in the current documentation.
Unfortunatly ticket #4865 doesn't help, but I'll find something.
