### ISSUE TITLE
React, selecting doesn't work on timeGridDay view

### ISSUE THREAD

**Issue by vrambo8** [fullcalendar/fullcalendar#5346]
Hi, I previously opened another issue about this. 
Basically the selecting timeslots feature does not fire in timeGridDay view but works on all other views. I'm using version 5.0.0-beta.1.

I have now stripped down everything that was possible and the bug is reproducible at 
https://codesandbox.io/s/full-calendar-bug-m8dlz

Thank you in advance

**Comment by arshaw** [comment]
thanks for noticing this. i've already made a fix and plan to do another release by monday morning

**Comment by arshaw** [comment]
fixed in beta.2!

https://codesandbox.io/s/full-calendar-bug-eryfq?file=/src/App.js

https://fullcalendar.io/blog/2020/04/new-ui-features-beta
