### ISSUE TITLE
Update npm to version 5

### ISSUE THREAD

**Issue by stunaz** [fullcalendar/fullcalendar#5347]

**Comment by acerix** [comment]
I believe that's intentional since it's still in beta.

**Comment by stunaz** [comment]
Usually, others libs have alpha/ beta/ canary/next channel available via npm, where we can install via npm and test it.
I am not asking to release the version 5 as a final version.

**Comment by arshaw** [comment]
it's in there: https://www.npmjs.com/package/@fullcalendar/core/v/5.0.0-beta.2

tagged with the `beta` release tag. same with 5.0.0-beta.1. You see it?

**Comment by stunaz** [comment]
indeed...sorry for the confusion
