### ISSUE TITLE
v3 breaks with jQuery 3.5 due to security fix for invalid HTML tags

### ISSUE THREAD

**Issue by neroux** [fullcalendar/fullcalendar#5348]
I do realise version 3 is most likely not supported any longer, however I still reference to this issue, jquery/jquery#4664, as everyone upgrading such a setup to jQuery 3.5 will run into it due to a secuity fix they implemented.

https://github.com/jquery/jquery/issues/4664#issuecomment-612254616 essentially summarises it. FullCalendar is creating self-closing tags for tags which do no officially allow for that.

If it were possible to have a quick version 3.10.1 with that fix, I guess that would help everyone who hasn't rewritten their code for version 4 yet :)

**Comment by neroux** [comment]
An example would be
https://github.com/fullcalendar/fullcalendar/blob/bad3b01082691191c8b7ce2158a454d6dc40360d/src/util.ts#L268

**Comment by acerix** [comment]
Thanks, confirmed.

https://codepen.io/acerix/pen/VwvLRGK

**Comment by Softsmiths** [comment]
Is it possible to fix version v2 version too?

**Comment by arshaw** [comment]
this has been fixed and released!
https://github.com/fullcalendar/fullcalendar/releases/tag/v3.10.2
https://github.com/fullcalendar/fullcalendar-scheduler/releases/tag/v1.10.1

sorry @Softsmiths, we won't fix v2, only v3

**Comment by Softsmiths** [comment]
@arshaw I think I fixed it myself in source code of 2.9.1 by changing closing html tags. It looks like it will work, at least for my use. Will do some testing.
