### ISSUE TITLE
Event display bug

### ISSUE THREAD

**Issue by sokusters** [fullcalendar/fullcalendar#5349]
Hi, i have problem with displaying event in one row on week view

 
![image](https://user-images.githubusercontent.com/44870576/79039944-22375400-7be5-11ea-9227-fd16f3968a1e.png)

**Comment by acerix** [comment]
Would you be able to post a [runnable, stripped-down demonstration of the bug](http://fullcalendar.io/wiki/Reduced-Test-Cases/)? Would really appreciate it because the time saved reproducing will be time spent fixing.
