### ISSUE TITLE
Calendar freezes in a loop when zooming in Chrome with resource timeline view

### ISSUE THREAD

**Issue by silverinventor** [fullcalendar/fullcalendar#5352]
In Google Chrome in the timeline view when I zoom in or zoom out about more than 4 or 5 times, everything freezes

https://fullcalendar.io/docs/v5/timeline-standard-view-demo

**Comment by neroux** [comment]
The issue appears to be specific to Chrome. It **does not appear on Firefox**, but I can confirm it on Chrome.

As long as one stays below a zoom level of 125% everything is fine and zooming in and out works just as intended. The moment one exceeds 125%, however, the browser jumps to 100% CPU utilisation.

**Comment by acerix** [comment]
Thanks, confirmed.   Seems to only happen with resource timeline view.

https://codepen.io/acerix/pen/LYpVKOE

The issue can also be reproduced by setting the zoom level of the page to 80% then closing the page and reopening it, then it will freeze on load.

**Comment by arshaw** [comment]
fixed in the second beta release. demo: https://codepen.io/arshaw/pen/abvvZQo
[blog post](https://fullcalendar.io/blog/2020/04/new-ui-features-beta)

can either of you confirm please?

**Comment by silverinventor** [comment]
Confirmed it works now in second beta release, thanks

**Comment by fwd079** [comment]
Hi, may I know if this has made to general release yet?
Kind Regards.
