### ISSUE TITLE
v5 Beta in Google Chrome: Timeline View does not render in CodePen

### ISSUE THREAD

**Issue by silverinventor** [fullcalendar/fullcalendar#5353]
It seems only in google chrome that when I click "edit in CodePen" for the v5 beta, the timeline view does not render and appear to show in the bottom:

Click "edit in CodePen" in chrome:

https://fullcalendar.io/docs/v5/timeline-standard-view-demo

**Comment by acerix** [comment]
It's working for me, do you have any errors in the console?  Also check that you don't have the page zoomed at all since that prevent it from rendering as mentioned in the other issue you reported (https://github.com/fullcalendar/fullcalendar/issues/5352).

**Comment by silverinventor** [comment]
Works fine now. My issue seemed to be I had like 30 tabs open and a lot of them were CodePen, when I closed a bunch it works just fine, thanks (and oops)
