### ISSUE TITLE
v5 Beta 2: textColor setting in Event Object not working anymore

### ISSUE THREAD

**Issue by silverinventor** [fullcalendar/fullcalendar#5355]
The textColor setting in Event objects cannot be changed anymore, it is only white

It was working in v5 beta 1, but now it doesn't seem to be in v5 beta 2

https://codepen.io/adam-silver/pen/WNQQdaB?editable=true&editors=001%3Dhttps%3A%2F%2Ffullcalendar.io%2Fdocs%2Fv5%2FeventClick-demo

**Comment by arshaw** [comment]
good call, thanks. legit bug. the fc-event-main div now owns the color. forgot to adjust to that. will fix in next beta

**Comment by arshaw** [comment]
fixed in beta3. more info on the release: https://fullcalendar.io/blog/2020/05/react-ts-v5-beta

**Comment by arshaw** [comment]
proof: https://codepen.io/arshaw/pen/zYvyRqg?editable=true&editors=001%3Dhttps%3A%2F%2Ffullcalendar.io%2Fdocs%2Fv5%2FeventClick-demo
