### ISSUE TITLE
Fullcalendar 5.0.0-beta2: slotLaneDidMount wrong date in date object ?

### ISSUE THREAD

**Issue by dariovinci** [fullcalendar/fullcalendar#5356]
I'm trying to bind a double click event on a slot to open a modal. A consol log of the date object always shows correct time but wrong date: Thu Jan 01 1970 08:30:00 GMT+0100

```
slotLaneDidMount: function(info) {

      info.el.addEventListener('click', function() {
        clickCnt++;
        if (clickCnt === 1) {
          oneClickTimer = setTimeout(function() {
            clickCnt = 0;
            alert('SINGLE CLICK');
          }, 400);
        } else if (clickCnt === 2) {
          clearTimeout(oneClickTimer);
          clickCnt = 0;
          console.log(info.date);
        
        }
      });


    }

```

is this the expected behaviour?

**Comment by arshaw** [comment]
this is something i did intentionally, because i figured the time axis' dates shouldn't be specific to any particular day, since there may be multiple, so i chose the first day after the UTC epoch. but i may change my approach depending on the view. is your view single-day?

**Comment by dariovinci** [comment]
well i tested it on timeGridWeek view but i'm thing about using it on day and resource vertical view since i think there is no other hook were i can use this approach

**Comment by devchris** [comment]
Idk if this is the right place to ask this but what is the best way to get the new `activeStart` and `activeEnd` dates? In v4 this was easily doable with `datesRender` but now I'm not so sure anymore. All the `didMount` hooks will only render at the beginning. `dateDidUpdate` isn't returning a date object, so I'm clueless as of right now... (Using react)

**Comment by dariovinci** [comment]
@devchris 

i figured out i can use this function in the date click callback

`dateClick: function(info) {
      clickCnt++;
      if (clickCnt === 1) {
        oneClickTimer = setTimeout(function() {
          clickCnt = 0;

        }, 400);
      } else if (clickCnt === 2) {
        clearTimeout(oneClickTimer);
        clickCnt = 0;
        alert('doppio click')
      }
    }`

could you you please take a look at this infinite loop bug ? 
https://github.com/fullcalendar/fullcalendar/issues/5091

this is of crucial importance for our project. It happens when you call 

`calendar.setOption('businessHours', businessHours);`

after or before fetching events success callback.

I have tried all the mentioned solution but none seems to work.

**Comment by arshaw** [comment]
@devchris , the new [datesDidUpdate](https://fullcalendar.io/docs/v5/datesDidUpdate) isn't given any arguments right now. but it should receive a view object. i'll make sure to add that. but for now you should be able to get it by accessing `this`, which is the calendar

```js
datesDidUpdate: function() {
  console.log(this.view.activeStart)
}
```

**Comment by arshaw** [comment]
@dariovinci , i will fix that infinite loop bug, don't worry

**Comment by dariovinci** [comment]
thank you very much @arshaw :)

**Comment by devchris** [comment]
@arshaw  - how would you do this in a stateless component? It seems like the `ref` prop isn't working anymore since v5. 
```
  const calendarComponentRef = createRef();
```
...
```
 <FullCalendar
      ref={calendarComponentRef}
...
```

now if I would get `calendarComponentRef.current` inside `datesDidUpdate` it will be null. 😞

**Comment by arshaw** [comment]
the infinite loop bug is now fixed. and the ref issue has a workaround. i'll close this issue. but i still plan on giving the extra arg to datesDidUpdate

**Comment by arshaw** [comment]
@devchris , datesDidUpdate now receives an arg with the view, like `{ view }`

info on the release: https://fullcalendar.io/blog/2020/05/react-ts-v5-beta

**Comment by devchris** [comment]
@arshaw , awesome! Thanks a lot 👍

**Comment by devchris** [comment]
@arshaw , when trying to update to v3 beta I'm getting ` Couldn't find package "@fullcalendar/common@5.0.0-beta.3" required by "@fullcalendar/core@5.0.0-beta.3" on the "npm" registry.`

**Comment by omarhsouna** [comment]
I'm using the v6.1.10 of fullcalendar, I want to get the right date when makeing a right click in date view timeGridWeek, I get the right time but a wrong date : Thu Jan 01 1970 08:30:00 GMT+0100, I have used the hook slotLaneDidMount
