### ISSUE TITLE
More button from dayMaxEvents or dayMaxEventRows can get hidden behind events

### ISSUE THREAD

**Issue by phamvuau** [fullcalendar/fullcalendar#5359]
Live example here: https://codesandbox.io/s/full-calendar-core-v500-beta2-vkgbg
I tested v5-beta2 with my dataset. You can see on April 9th, there is a more link hidden under the last event bar while it shouldn't be there because dayMaxEvents is 5 (I set backgroundColor is transparent so you can see it easily)

<img width="841" alt="Screen Shot 2020-04-16 at 4 17 16 PM" src="https://user-images.githubusercontent.com/259848/79438482-c4987280-7ffd-11ea-8f92-08bcc7ef1dac.png">

**Comment by acerix** [comment]
Thanks, confirmed.  I tested those events in the debug template and it also displays that "more" link behind the events instead of below.  

https://codepen.io/acerix/pen/JjYXdQv?editors=0110

**Comment by arshaw** [comment]
this has since been fixed. see the revised demo: https://codepen.io/arshaw/pen/XWXRmqR?editors=0110

btw, [v5 has been officially released](https://fullcalendar.io/blog/2020/06/v5-official)
