### ISSUE TITLE
Some issues

### ISSUE THREAD

**Issue by Shakhboz89** [fullcalendar/fullcalendar#5360]
Please tell me what am I doing wrong here? Calendar does not display normally. Rails 6
<img width="489" alt="Снимок экрана 2020-04-16 в 17 45 42" src="https://user-images.githubusercontent.com/46559168/79452570-29f26080-800a-11ea-87d9-1b6e3948fae2.png">
<img width="352" alt="Снимок экрана 2020-04-16 в 17 45 19" src="https://user-images.githubusercontent.com/46559168/79452585-2e1e7e00-800a-11ea-950d-c04ff29f4141.png">
<img width="530" alt="Снимок экрана 2020-04-16 в 17 44 32" src="https://user-images.githubusercontent.com/46559168/79452606-35de2280-800a-11ea-8c26-b95c1675ec2e.png">
<img width="959" alt="Снимок экрана 2020-04-16 в 17 46 53" src="https://user-images.githubusercontent.com/46559168/79452650-47bfc580-800a-11ea-8293-6eb44f7fbed7.png">

**Comment by acerix** [comment]
Would you be able to post a [runnable, stripped-down demonstration of the bug](http://fullcalendar.io/wiki/Reduced-Test-Cases/)? Would really appreciate it because the time saved reproducing will be time spent fixing.
