### ISSUE TITLE
Weekly recurring event return the original position

### ISSUE THREAD

**Issue by kota-yata** [fullcalendar/fullcalendar#5363]
### Bug Reports
Recurring events suddenly return to the original position when I click dayGrid, weekGrid, or list button. 
In the case below, the original position is Thursday. I move one element of "loop" to Wednesday, and click the week(or day, and list) button. Then "loop" elements return to Thursday when I turn back to month page. 
![image](https://user-images.githubusercontent.com/51294895/79554974-d5b6b180-80d9-11ea-8930-2934f782583a.png)
### Feature Requests
//
### React/Vue/Angular/etc
vanilla JS

**Comment by acerix** [comment]
Would you be able to post a [runnable, stripped-down demonstration of the bug](http://fullcalendar.io/wiki/Reduced-Test-Cases/)? Would really appreciate it because the time saved reproducing will be time spent fixing.
