### ISSUE TITLE
resourceAreaWidth is not updated when changed with setOption

### ISSUE THREAD

**Issue by SvenEV** [fullcalendar/fullcalendar#5368]
In FullCalendar Scheduler v4, I have been using `calendar.setOption` to set the option "resourceAreaWidth" programmatically. In v5, this seems to no longer work. I couldn't find anything about this particular option in the changelog, so I assume this to be a bug.

It's easily reproducable (click anywhere to set the resourceAreaWidth):
* Working example v4: https://codepen.io/SvenEV/pen/oNjBoVp?editors=0010
* Broken example v5: https://codepen.io/SvenEV/pen/wvKgPZZ?editors=0010

**Comment by acerix** [comment]
Thanks, confimed. As a workaround, it works after forcing the view to change:

https://codepen.io/acerix/pen/ExVZrrB?editors=0010

**Comment by arshaw** [comment]
fixed in beta3. more info on the release: https://fullcalendar.io/blog/2020/05/react-ts-v5-beta

proof: https://codepen.io/arshaw/pen/wvKRyWy?editors=0010
