### ISSUE TITLE
div fc-bg issue

### ISSUE THREAD

**Issue by aqjw** [fullcalendar/fullcalendar#5369]
Hello!
I'm using vue.js framework.
Got an issue with this div `<div class="fc-bg"/>`.

I added `console.log` for debuging -
![Screenshot from 2020-04-23 20-44-45](https://user-images.githubusercontent.com/13101908/80132152-eff20300-85a3-11ea-9f41-6e3d8f471d7d.png)

In browser - 
![Screenshot from 2020-04-23 20-45-43](https://user-images.githubusercontent.com/13101908/80132158-f1bbc680-85a3-11ea-98a9-fbc308cd9950.png)

### solution
Change from `<div class="fc-bg"/>` to `<div class="fc-bg"></div>`
![Screenshot from 2020-04-23 20-47-47](https://user-images.githubusercontent.com/13101908/80132160-f2545d00-85a3-11ea-8fbc-7a642442e728.png)
![Screenshot from 2020-04-23 20-48-10](https://user-images.githubusercontent.com/13101908/80132165-f2ecf380-85a3-11ea-92d2-cdc9e4f0421f.png)

it works
![Screenshot from 2020-04-23 20-48-55](https://user-images.githubusercontent.com/13101908/80132169-f3858a00-85a3-11ea-949e-1c25f8a1282e.png)

### So I have a question: 
How to fix this without changing the library code?

**Comment by acerix** [comment]
Would you be able to post a [runnable, stripped-down demonstration of the bug](http://fullcalendar.io/wiki/Reduced-Test-Cases/)? Would really appreciate it because the time saved reproducing will be time spent fixing.

**Comment by aqjw** [comment]
In short, the problem is the closing tag. It is not there.
![Screenshot from 2020-04-23 20-55-27](https://user-images.githubusercontent.com/13101908/80133460-eff30280-85a5-11ea-9b4a-532fbd22d70d.png)

**Comment by acerix** [comment]
I believe this existing ticket captures this need:
https://github.com/fullcalendar/fullcalendar/issues/5348
↑
Please visit the above issue, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates.
