### ISSUE TITLE
with jQuery 3.5.0,the view shows a problem

### ISSUE THREAD

**Issue by cephiroth** [fullcalendar/fullcalendar#5370]
Last month, I install fullcalendar,everything is fine.

But recently I repeat install fullcalendar, the view shows a problem: all events are displayed in one day.

I check the dependency and find jQuery's version has changed, 3.4.1 => 3.5.0

So I think this may cause the problems.

**Comment by acerix** [comment]
I believe this existing ticket captures this need:
https://github.com/fullcalendar/fullcalendar/issues/5348
↑
Please visit the above issue, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates.
