### ISSUE TITLE
orderEvent not working on listWeek view

### ISSUE THREAD

**Issue by patsoh** [fullcalendar/fullcalendar#5371]
eventOrder prop does not work in 'listWeek' view. There is no problem in the 'dayGridMonth' view. I can pass such props as string like id, duration or sorting function but on 'listWeek' view there is no reaction. Is there any possibility to do this on 'listWeek' view?

**Comment by acerix** [comment]
Would you be able to post a [runnable, stripped-down demonstration of the bug](http://fullcalendar.io/wiki/Reduced-Test-Cases/)? Would really appreciate it because the time saved reproducing will be time spent fixing.

This demo shows sorting in `listWeek`:

https://codepen.io/acerix/pen/abvJLbK
