### ISSUE TITLE
className is ignored

### ISSUE THREAD

**Issue by ErAz7** [fullcalendar/fullcalendar#5373]
`FullCalendar` react component does not apply `className` to it's outer-most element  (or any other elements inside it)

**Comment by acerix** [comment]
Would you be able to post a [runnable, stripped-down demonstration of the bug](http://fullcalendar.io/wiki/Reduced-Test-Cases/)? Would really appreciate it because the time saved reproducing will be time spent fixing.

**Comment by ErAz7** [comment]
It's so simple, issue is when you supply `className` prop to `FullCalendar`, it doesn't apply (if I want to show a code sandbox, I'll just take base FullCalendar code sandbox and add `className='my-class-name'` to it which doesn't make sense)
```javascript
<FullCalendar
    //the class name is ignored and not assigned to some element in FullCalendar
    className='my-class-name'
    defaultView='dayGridMonth'
    plugins={[dayGridPlugin]} />
```

This is not a mentionable issue though but it might be better if you pass `className` prop to the outer most component inside `FulCalendar`

**Comment by acerix** [comment]
There is no `className` property in FullCalendar, but it sounds like a convention in React so I will reopen the issue there.

https://reactjs.org/docs/faq-styling.html

**Comment by acerix** [comment]
Actually I cannot tranfer it so please repon the issue in that repo:

https://github.com/fullcalendar/fullcalendar-react/issues
