### ISSUE TITLE
Add example in documentation for datesDidUpdate

### ISSUE THREAD

**Issue by dorthrithil** [fullcalendar/fullcalendar#5375]
It was not clear to me how to use `datesDidUpdate` after reading https://fullcalendar.io/docs/v5/datesDidUpdate. After some trial and error I was able to get the callback working by writing: 

```ts
this.calendarApi.on('datesDidUpdate', () => {
    this.loadNewEvents();
})
```

As `datesDidUpdate`  is listed in the View API chapter I expected to use it via the view API. But actually it is emitted by the calendar API.

**Comment by acerix** [comment]
An example of `datesDidUpdate` would be useful and I can see how "view API" is confusing. 

The callbacks are all in the top-level settings and can be set like this:

https://codepen.io/acerix/pen/vYNZQdL?editors=0011

**Comment by arshaw** [comment]
This setting was renamed to `datesSet` in the v5 release candidate and in the docs it was recategorized to the "Date & Time Display" section where it will be more discoverable:

https://fullcalendar.io/docs/v5/datesSet

As for adding an example, yes we should totally do that, but that is part of a larger initiative to get an example in every article, which I don't need a ticket for. so, closing
