### ISSUE TITLE
v5 Beta - Select Resource Error

### ISSUE THREAD

**Issue by SelectSystemsInternational** [fullcalendar/fullcalendar#5377]
I have a problem where I select a resource in resourceTimelineDay and in the calls to dateClick or Select the resource that is returned is the resource one or two rows above not the resource selected. I dont know if it is something I am doing with the setup of the page / calendar or css or something else ? 
I was trying to debug main.js - Looking at the construction of the tops and bottoms of the resources occasionally the coordinates returned by el.getBoundingClientRect() are all zero - causing the calculation of some of the tops and bottoms to be negative. 

      // Populates the top/bottom internal coordinate arrays
      PositionCache.prototype.buildElVerticals = function (originClientTop) {
          var tops = [];
          var bottoms = [];
          for (var _i = 0, _a = this.els; _i < _a.length; _i++) {
              var el = _a[_i];
              var rect = el.getBoundingClientRect();
              tops.push(rect.top - originClientTop);
              bottoms.push(rect.bottom - originClientTop);
          }
          this.tops = tops;
          this.bottoms = bottoms;
      };

It is a bit hard to setup a codepen for it
Are these tops and bottoms used to deturmine which resource is clicked ?
Is there something I am doing that will cause this problem - or could it be the code ?
If its not the code is there something I should look at ?

![tops and bottoms - negative](https://user-images.githubusercontent.com/34350154/80371996-20a0a800-88d6-11ea-821f-51ce05fd6bc5.png)
![tops and bottoms - rectangle all 0](https://user-images.githubusercontent.com/34350154/80372004-24ccc580-88d6-11ea-913b-0973be30d91c.png)

**Comment by SelectSystemsInternational** [comment]
I tried to setup a codepen - for some reason it will not read the data from my server ?
https://codepen.io/SelectSystemsInternational/pen/PoPjmjM

Yours work 
      resources: 'https://fullcalendar.io/demo-resources.json?with-nesting&with-colors',
      events: 'https://fullcalendar.io/demo-events.json?single-day&for-resource-timeline'

But mine do not ?
      resources: 'https://test1.selectsystems.com.au/GetAllSchedulerResources?productId=1618',
      events: 'https://test1.selectsystems.com.au/GetAllSchedulerEvents?productId=1618'

The full links work 
https://test1.selectsystems.com.au/GetAllSchedulerEvents?productId=1618&start=2020-04-24T00%3A00%3A00%2B10%3A00&end=2020-04-25T00%3A00%3A00%2B10%3A00%27
https://test1.selectsystems.com.au/GetAllSchedulerResources?productId=1618&start=2020-04-24T00%3A00%3A00%2B10%3A00&end=2020-04-25T00%3A00%3A00%2B10%3A00%27

**Comment by acerix** [comment]
I'm not sure what you mean by "selecting resources" but you can use `resourceLabelDidMount` to add a callback when a resource is clicked:

https://codepen.io/acerix/pen/eYpRbma?editors=0010

The requests to your server are blocked by CORS policy (see console errors), you can use the "with JSON" debug template which has instructions to add sample JSON.

https://fullcalendar.io/reduced-test-cases

**Comment by tine200926** [comment]
> HI! I have problem 
`resourceLabelDidMount` why can't  Reload when click prev or next button
in resourceTimelineMonth 
> 
 ```var calendarEl = document.getElementById('calendar2');
        var calendar = new FullCalendar.Calendar(calendarEl, {
          
            initialView: 'resourceTimelineMonth',
            height: 'auto',
            displayEventTime: true,
            displayEventEnd: true,
            aspectRatio: 1,
            allDaySlot: false,
            selectable: true,
            locale: 'zh-TW',
            headerToolbar: {
                left: 'prev,today',
                center: 'title',
                right: 'next'
            },
            editable: false,
          
            resourceAreaWidth: '150px',
            contentHeight: 'auto',

            refetchResourcesOnNavigate: true,
            resourceGroupField: 'building',
            //userName
            resources: function (fetchInfo, successCallback, failureCallback) {
                var startDate = fetchInfo.start
                var endDate = fetchInfo.end
                 $.ajax({
                        url: ,
                        cache: false,
                        type: "POST",
                        data: {
                           
                        },
                        success: function (data) {
                            var objRDataSEL = JSON.parse(data);

                            successCallback(objRDataSEL);

                        }
                        
                 });

            },

            resourceLabelDidMount: function (info) {
                var questionMark = document.createElement('strong');
                questionMark.innerText = ' * ';

                info.el.querySelector('.fc-datagrid-cell-main')
                    .appendChild(questionMark);


                $(info.el.querySelector('.fc-datagrid-cell-main')).popover({
                    title: info.resource.extendedProps.title_mon   + '當月出勤統計' + info.resource.title   ,
                    placement: 'top',
                    trigger: 'hover',
                    container: 'body',
                    html: true,
                    content: $(`<div class="CalEventSquare d-inline-block m-1" style="border:1px #adadad solid;background:#adadad;border-radius:50%;"></div>
                            <span> ${info.resource.extendedProps.dayCount}天 </span>
                            <div class="CalEventSquare d-inline-block  m-1 triangle" style=" border-width: 0 .7em 1em .7em;"></div>
                            <span> ${info.resource.extendedProps.halfDay}天 </span>
                            <div class="CalEventSquare d-inline-block m-1" style="border:.5px #adadad solid;"></div>
                            <span> ${info.resource.extendedProps.leaveDay}天 </span>`)

                });
            }
        });calendar.render();
> 
>
(https://user-images.githubusercontent.com/44522798/144972329-8f8d0455-b581-4a42-8bcc-4c4d9b78c5ff.png)

should be 2021-11-01
(https://user-images.githubusercontent.com/44522798/144972346-56b4b011-19b0-4f7c-85a9-b08e92297a0b.png)
