### ISSUE TITLE
Time Zone not Work !!!

### ISSUE THREAD

**Issue by sajjad-z** [fullcalendar/fullcalendar#5383]
Hi
My site is hosted on a server in an Asian country. And I want to change the time zone for displaying the events to Germany, but unfortunately it doesn't work.
i'm used timezone: 'Europe/Berlin' in fullCalendar 
But this Code not work !!!
thank you

**Comment by acerix** [comment]
Would you be able to post a [runnable, stripped-down demonstration of the bug](http://fullcalendar.io/wiki/Reduced-Test-Cases/)? Would really appreciate it because the time saved reproducing will be time spent fixing.

Here's a demo of timezones:

https://fullcalendar.io/docs/timeZone-demo
