### ISSUE TITLE
There is a margin bug on the Month view

### ISSUE THREAD

**Issue by apoklyak** [fullcalendar/fullcalendar#5386]
I use the 5th version of FullCalendar and Angular 9.

And I have found a strange bug with extra margin. You can see it on the picture below.

![image](https://user-images.githubusercontent.com/20241127/80699840-5a93c900-8ae5-11ea-8d45-1ffe91d13951.png)

**Comment by acerix** [comment]
Would you be able to post a [runnable, stripped-down demonstration of the bug](http://fullcalendar.io/wiki/Reduced-Test-Cases/)? Would really appreciate it because the time saved reproducing will be time spent fixing.
