### ISSUE TITLE
Linebreaks are ignored in event titles

### ISSUE THREAD

**Issue by yogiderek** [fullcalendar/fullcalendar#5387]
I am migrating a copy of my V4 development code to V5 to try out the latest changes. In V4, in new Draggable(containerEl, I could add newlines in the title field and the event would display the following title on 3 lines 

`                    return {
                        id: caseId,
                        title: caseId + "\r\n" + purpose + "\r\n" + organisation,
                    };
`

However on V5 using the new method, new FullCalendar.Draggable(containerEl, the newlines are still accepted in the string but the title in the event appears as a single line. 

I have searched the new docs but cannot find a change related to this and I am not sure if i have to use one of the new methods to achieve this.
 
Here is a cut down version of my code

`document.addEventListener('DOMContentLoaded', function () {
    var containerEl = document.getElementById('external-events');
    var calendarEl = document.getElementById('calendar');

    // initialize the external events
    // -----------------------------------------------------------------
    new FullCalendar.Draggable(containerEl, {
        itemSelector: '.booking-event',
        eventData: function (eventEl) {
            var caseId = $(eventEl).attr('data-caseId');
            var purpose = $(eventEl).attr('data-title');
            var organisation = $(eventEl).attr('data-organisation');

            return {
                id: caseId,
                title: caseId + "\r" + purpose + "\r" + organisation,
                extendedProps: {
                    roomId: '',
                    roomTitle: ''
                }
            };
        }
    });

    // initialize the calendar
    // -----------------------------------------------------------------
    calendar = new FullCalendar.Calendar(calendarEl, {
        themeSystem: 'bootstrap',
        timeZone: 'local',
        titleFormat: { month: 'long', year: 'numeric' },
        eventColor: '#6264A7',
        eventTextColor: '#fff',
        resourceColumns: [
            {
                labelText: 'Room',
                field: "title"
            }
        ],
        initialView: 'resourceTimelineDay',
        views: {
            resourceTimelineDay: {
                slotLabelFormat: {
                    hour: '2-digit',
                    minute: '2-digit',
                    omitZeroMinute: false,
                    hour12: false,
                    meridiem: false
                }
            }
        },
        height: 'auto',
        headerToolbar: {
            left: 'prev,next',
            center: '',
            right: ''
        },
        editable: true,
        droppable: true,
        resourceOrder: 'title',
        slotMinTime: "09:00",
        slotMaxTime: "22:01"
    });

    calendar.render();
});
`

**Comment by acerix** [comment]
I checked in the debug template and can confirm line breaks show in v4 but not v5 so I believe that is a bug or at least should be documented:

https://codepen.io/acerix/pen/OJyxMwv

https://codepen.io/acerix/pen/eYpGJKq

You could use `eventContent` to convert them to the HTML:

https://codepen.io/acerix/pen/YzyrwJV

**Comment by yogiderek** [comment]
Thanks for the quick response. I used eventContent as I think that gives the most flexibility in how to display the event title. Perhaps adding a multiple line title to some of the demos will help to show that you can customise the event title. Looking forward to trying out some of the new features.

**Comment by nicirinuser** [comment]
try this in fullcalendar v.6

in style css 
`.fc-direction-ltr .fc-daygrid-event.fc-event-end,
.fc-event-main-frame {
    flex-direction: column;
    text-align: left;
}

.fc-event-desc,
.fc-event-title {
    white-space: break-spaces;
}`

and add `\r\n` this in your row from database or API or etc in title
