### ISSUE TITLE
D&D not working if two calendars are on top of each other

### ISSUE THREAD

**Issue by lukgri** [fullcalendar/fullcalendar#5392]
It is not possible to drag around events if two fullcalendar instances are on top of each other(my use case for this is that one calendar is in background and another one is shown in dialog above it).

More specifically: you can't drag and drop events inside of their own fullcalendar instance if the possible "drop area" is on top of another fullcalendar instance

Codepen: https://codepen.io/lukgri/pen/xxwPQqp

![Screenshot 2020-05-04 at 09 44 38](https://user-images.githubusercontent.com/13081493/80945486-363d3280-8dec-11ea-88b5-cf5fa60564da.png)

**Comment by acerix** [comment]
I believe this existing ticket captures this need:
https://github.com/fullcalendar/fullcalendar/issues/4742
↑
Please visit the above issue, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates.
