### ISSUE TITLE
Json Event Source failure doesn't remove events

### ISSUE THREAD

**Issue by philipstratford** [fullcalendar/fullcalendar#5395]
I don't know if this is a bug or by design (I'm in two minds as to what I'd expect the behaviour to be), and I'm struggling to write a Codepen to demonstrate it because I don't have a public JSON feed of events to use.

The issue is if my calendar has a JSON feed Event Source and it successfully retrieves events from the server and displays them when the calendar is initialised and I then subsequently call `calendar.refetchEvents()` and the JSON feed fails to return results due to an issue with the AJAX call, the events for that Event Source remain displayed on the calendar.

In practice the exact use case is:

- FullCalendar is rendered and retrieves events from a JSON feed that is getting the events from Exchange Web Services for the current user.
- The user selects a different member of staff from a dropdown list on the page, triggering the `calendar.refetchEvents()` call. The id of the selected member of staff is passed to the server API method which gets the EWS events in the `extraParams` parameter.
- The API method on the server fails to retrieve EWS events for the selected user, e.g. because of insufficient permissions. The API returns `BadRequest` or `InternalServerError` or another failure response.
- The 'failure' callback for the Event Source is called, as expected, allowing me to display an error message. However, the events which were previously loaded for that Event Source are not removed - they continue to be displayed.

In my scenario this is bad because Outlook appointments for User 1 are displayed when User 2 is selected and only the error message points out that there's actually an issue. However, I can see how in a different scenario, e.g. a network error, it might be desirable to continue to display the last known set of events for an Event Source when a refetch fails.

I can, of course, manually write code to remove the Event Source's events when the refetch fails, but I really just wanted to check that this behaviour was expected and question whether it should be.

**Comment by acerix** [comment]
I believe this existing ticket captures this need:
https://github.com/fullcalendar/fullcalendar/issues/5197
↑
Please visit the above issue, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates.
