### ISSUE TITLE
Add a color setting for resources

### ISSUE THREAD

**Issue by polak25** [fullcalendar/fullcalendar#5397]
Hello,

I don't think I've figured out how to color the resource and not these events?
https://fullcalendar.io/docs/resource-object

It would be nice to be able to do that ?!

**Comment by acerix** [comment]
You could use `resourceRender` to add styles to the label:

https://codepen.io/acerix/pen/WNQzedz

To color the timeslots, you could add background events.

**Comment by sajjadrajaee** [comment]
How to change just the parent's background in the resource?

**Comment by Rudicito** [comment]
For anyone, for fullcalendar v5 and v6, you use `resourceLabelDidMount`, `resourceRender` is deprecated now :

```
resourceLabelDidMount: function(info) {
            info.el.style.backgroundColor = 'red';
        },
```
