### ISSUE TITLE
Printing timeline view with expandRows: true causes "invalid use of expandRows" error

### ISSUE THREAD

**Issue by ningzhang422** [fullcalendar/fullcalendar#5399]
I found this error when I try to print the demo page `examples/timeline-full-height.html`
![Capture d’écran du 2020-05-07 15-55-36](https://user-images.githubusercontent.com/1186049/81305366-8a5f4580-907e-11ea-9af7-9ac92173f93d.png)
But if I remove the option "expandRows: true", the view `timeline` isn't printer-friendly. 
![Capture d’écran du 2020-05-07 16-21-49](https://user-images.githubusercontent.com/1186049/81306841-3f463200-9080-11ea-8247-da475231702a.jpg)

How to eliminate the error message under the guarantee of printing-friendly ？ 
This question should be related to the EventListeners "beforeprint" or "afterprint"

**Comment by acerix** [comment]
Thanks, confirmed.  The error can be reproduced by trying to print this demo:

https://fullcalendar.io/docs/v5/expandRows-timeline-demo

**Comment by arshaw** [comment]
this JS error has been fixed in beta3. more info on the release: https://fullcalendar.io/blog/2020/05/react-ts-v5-beta

The JS error is gone, but I still need to make print-view actually look good now. that's what the next and final beta release will be about
