### ISSUE TITLE
Day-Cell Render Hooks for timeline view

### ISSUE THREAD

**Issue by jameslshannon** [fullcalendar/fullcalendar#5402]
I was hoping in v5 that the expanded render hooks would allow a custom renderer for a cell in the Resource Timeline view to have access to both the resource and the date passed in the arg, but the new Day-Cell render hook doesn't even fire for the resource timeline view - is this planned to be implemented in v5 as it seems an obvious omission in the current beta that prevents more advanced customisation of the timeline resource view, whereas this is implemented for the alternative vertical resource view.

Am I missing something to achieve this with the resource timeline view?

Thanks,

James

**Comment by acerix** [comment]
I can see they don't work in the timeline view: 

https://codepen.io/acerix/pen/YzyaOaB?editors=0011

The docs mention that these hooks are only for daygrid and timegrid views though so it would be a new feature. 

https://codepen.io/acerix/pen/YzyaOaB?editors=0011

**Comment by jameslshannon** [comment]
Great - I'm not going mad then - is it possible to tag this issue as a feature request for v5 or do I need to request elsewhere?

We purchased the premium resource plug-in to be able to customise flexible resource views and it seems like an omission in v5 to support this rendering hook in the vertical resource view but not the in timeline view.

Thanks

**Comment by acerix** [comment]
I left this issue open as a feature request but we can't give an ETA for new features, they are added based on popularity.  https://fullcalendar.io/issues/

One way you could do this for now is to add a background event to every resource/cell then use the event hooks.

**Comment by arshaw** [comment]
The DOM does not have distinct cells for the date+resource combination you're looking for. Instead, there is a cross-section of a horizontal div overlaid by a vertical div. If you inspect the DOM you'll see what I mean.

Given this setup (which is much more optimal than having individual cells for each date+resource combo), it would be impossible to style individual cells.

Instead, what you can do is:
- style the horizontal cell with `resourceLaneDidMount`
- style the vertical cell with `slotLaneDidMount`

demo: https://codepen.io/acerix/pen/YzyaOaB?editors=0010

hope that helps

**Comment by arshaw** [comment]
^updated demo link

**Comment by amirul1000** [comment]
ngAfterViewInit(){
    // Your CSS as text
    var styles =`
    .fc td, .fc th {
      vertical-align: top;
      padding: 0;
      height: 100px;
    }
    a{
      color:#3d1cba;
    }
    `


    let styleSheet = document.createElement("style");
    styleSheet.innerText = styles;
    document.head.appendChild(styleSheet);


    let arrTD = document.querySelectorAll('td.fc-timeline-slot');
    let arrTR= document.querySelectorAll('td.fc-timeline-lane.fc-resource');
    let arrInject= document.querySelectorAll('td.fc-timeline-lane.fc-resource>div.fc-timeline-lane-frame');
    console.log(arrTR);

    let k=-1;
    arrTR.forEach(eachTR => {
        let i=1;
        let str = '';
        k++;

        let data_resource_id= eachTR.getAttribute('data-resource-id');
        console.log(data_resource_id);

        arrTD.forEach(eachTD => {          
            let  k=100*(i-1);
            i=i+1;
            let data_date= eachTD.getAttribute('data-date');
            console.log(data_date);

            let data_resource_id= eachTR.getAttribute('data-resource-id'); 
            console.log(data_resource_id);

            str = str + '<span data-date="'+data_date+'" data-resource-id="'+data_resource_id+'" class="plus_icon" style="position:relative;top: 0px; left: '+k+'px !important;width:500px;height:500px;z-index:3;-moz-border-radius:100px;border:1px  solid #ddd;-moz-box-shadow: 0px 0px 8px  #fff;">+</span>';          
      
         
      });
        arrInject[k].innerHTML=str;

    });

    
    let elementList = this.elRef.nativeElement.querySelectorAll('span.plus_icon');
    for(let i=0;i<elementList.length;i++){   
     elementList[i].addEventListener('click', this.plusClick.bind(this));
    }
}
