### ISSUE TITLE
Displaying custom event title not working properly in v5 beta 2

### ISSUE THREAD

**Issue by Freezard** [fullcalendar/fullcalendar#5403]
In my v4 calendar in week/month view I rendered the event title + text of extended props in eventRender function. I also dynamically changed background colors of events with the DOM element.

Now in v5 eventRender is gone and I tried to replicate it in eventDidMount function. It works fine the first time the events are rendered but as soon as I resize or drag them. the title is appended to the custom HTML. Actually it does this for every event in the current view.

I tried doing it in eventContent but then I can't change the background colors because I don't have access to the DOM element in that function. Also the start/end time are not displayed among other issues.

https://codepen.io/Freeezard/pen/wvKmpXK

**Comment by acerix** [comment]
It should work if you use `eventContent` to modify the content, and `eventDidMount` to interact with the DOM element.  

https://codepen.io/acerix/pen/eYpRbma
