### ISSUE TITLE
Using fullcalendar in vue.js encountered cannot read property 'calendar' of undefined

### ISSUE THREAD

**Issue by wangmoi** [fullcalendar/fullcalendar#5405]
My code:
<FullCalendar
        ref="fullCalendar"
        :first-day="1"
        :plugins="calendarPlugins"
        :aspect-ratio="setWidth"
        :all-day-slot="false"
        :header="{
          left:'prev,today,next',
          center:'title',
          right: 'dayGridMonth,timeGridWeek,timeGridDay,listYear,listMonth,listWeek'
        }"
        :slot-event-overlap="false"
        :events="eventData"
        :button-text="{
          today: '今天',
          dayGridMonth:'月',
          timeGridWeek:'周',
          timeGridDay:'日',
          listYear:'年列表',
          listMonth:'月列表',
          listWeek:'周列表'
        }"
        :unselect-auto="false"
        :select-overlap="false"
        :business-hours="{
          startTime: '00:00',
          endTime:'24:00',
          daysOfWeek: [ 1, 2, 3, 4, 5, 6, 0 ]
        }"
        :select-allow="handlerSeelctAllow"
        select-mirror="true"
        min-time="00:00:00"
        max-time="24:00:00"
        selectable="true"
        slot-duration="00:30"
        slot-label-format="HH:mm"
        title-format="YYYY年MM月D日"
        default-view="dayGridMonth"
        locale="zh-cn"
        @select="handleSelect"
        @eventClick="handleEventClick"
      />

When I click the blank date, the select event will be triggered. When I don't write anything in my select event, it's OK. But when I write logic in the select event, when I click the date trigger, I will enter a similar weekly view from the monthly view, but there is no date in the view header, only Monday, Tuesday... Sunday and no time, such as 06:00,
When I have this problem, I can't click the back to current time and top right view button to return to the monthly view

my @select="handleSelect"
handleSelect(info) {
      this.dialogFormVisible = true
      this.scheduleForm.scheduleDate = [info.start, info.end]
      this.scheduleForm.scheduleDateTime = [info.start, info.end]
}

View entered after trigger select：
![A5C651B8-C8D8-4f15-81EB-BB4F816B90C0](https://user-images.githubusercontent.com/48625100/81459648-a294a900-91d3-11ea-95d4-9a640d7236e8.png)

error:
![C4F80837-20CF-4bb7-92A4-76002ABE0D8E](https://user-images.githubusercontent.com/48625100/81459660-a88a8a00-91d3-11ea-9569-58bc579b888f.png)

**Comment by wangmoi** [comment]
my version:
"@fullcalendar/daygrid": "^4.3.0",
"@fullcalendar/interaction": "^4.3.0",
"@fullcalendar/list": "^4.3.0",
 "@fullcalendar/moment": "^4.3.0",
 "@fullcalendar/timegrid": "^4.3.0",
 "@fullcalendar/vue": "^4.3.1",

**Comment by acerix** [comment]
Would you be able to post a [runnable, stripped-down demonstration of the bug](http://fullcalendar.io/wiki/Reduced-Test-Cases/)? Would really appreciate it because the time saved reproducing will be time spent fixing.

**Comment by kelly1205** [comment]
我也遇到这个问题了，咋解决啊

**Comment by wangmoi** [comment]
> 我也遇到这个问题了，咋解决啊

固定所有依赖版本为v4.3.0和4.3.1不要加^更新到4.4.0版本

**Comment by kelly1205** [comment]
感謝
