### ISSUE TITLE
Wrong month using dateClick function

### ISSUE THREAD

**Issue by goldern** [fullcalendar/fullcalendar#5406]
### Bug Reports
FullCalendar Version: 4.4.0

After calling dateClick, it shows the right day in parameters.date.getDate() but shows wrong month (starts at month zero) in parameter.date.getMonth()

Fiddle: https://jsfiddle.net/ngbcdotk/
Instructions: just click inside any day box in the calendar to call parameters.date.getDate() and parameters.date.getMonth() in an alert box

### Feature Requests
Start dateClick date.getMonth() at month 1 instead of month 0

**Comment by acerix** [comment]
`date/getMonth` is native JavaScript which returns a zero-based value, so you should add one to show the "month number". 

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/getMonth
