### ISSUE TITLE
the calendar last column size problem

### ISSUE THREAD

**Issue by TorvaldsDB** [fullcalendar/fullcalendar#5409]
As the following images showing(Ignore these Chinese characters): 

![image](https://user-images.githubusercontent.com/12232166/81543297-71210680-93a8-11ea-9095-f3eb6ecd4805.png)

![image](https://user-images.githubusercontent.com/12232166/81543305-741bf700-93a8-11ea-9d76-b861c328e1a2.png)

![image](https://user-images.githubusercontent.com/12232166/81543311-77af7e00-93a8-11ea-8eeb-16ecd8ef6108.png)

**Comment by acerix** [comment]
I believe this existing ticket captures this need:
https://github.com/fullcalendar/fullcalendar/issues/4999
↑
Please visit the above issue, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates.

If this is a different bug, please supply a [runnable, stripped-down demonstration](http://fullcalendar.io/wiki/Reduced-Test-Cases/).

**Comment by TorvaldsDB** [comment]
> I believe this existing ticket captures this need:
> #4999
> ↑
> Please visit the above issue, **give a** 👍 **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates.
> 
> If this is a different bug, please supply a [runnable, stripped-down demonstration](http://fullcalendar.io/wiki/Reduced-Test-Cases/).

Got it. Thank you very much.
