### ISSUE TITLE
Package v4.4.0 not working In lighting component Salesforce.

### ISSUE THREAD

**Issue by PrateekKumarSrivastava** [fullcalendar/fullcalendar#5412]
### Bug Reports
When using package v4.4.0 in salesforce lightning component, the calendar is showing in the backdrop but  it is showing the following error - **Uncaught TypeError: Illegal invocation
throws at https://*****************/resource/1589289819000/coreMainMin:6:1394**
I did everything correctly but I think that there is some problem with this package of full calendar.
![error calendar](https://user-images.githubusercontent.com/63948849/81719126-46af7600-949a-11ea-995d-d0ee1179ea78.png)

**Comment by acerix** [comment]
I believe this existing ticket captures this need:
https://github.com/fullcalendar/fullcalendar/issues/4990
↑
Please visit the above issue, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates. There is also a workaround there you can try.

**Comment by IvanWSM** [comment]
Wanted to confirm if the above ticket fixed the issue? I'm having this exact same issue

**Comment by PrateekKumarSrivastava** [comment]
> Wanted to confirm if the above ticket fixed the issue? I'm having this exact same issue

Yes, this issue is resolved but I am running into another issue now.

**Comment by PrateekKumarSrivastava** [comment]
> I believe this existing ticket captures this need:
> #4990
> ↑
> Please visit the above issue, **give a** 👍 **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates. There is also a workaround there you can try.

The earlier issue was resolved but I am getting the same error now when I am clicking on the calendar. 
![Screenshot 2020-05-13 at 4 54 03 PM](https://user-images.githubusercontent.com/63948849/81806777-95145180-953a-11ea-82d9-6545db58b4a9.png)

**Comment by IvanWSM** [comment]
Seems that the issue will keep appearing along with additional plugins, so modifying the source code might not be a good solution.

Guess we'll need to get some additional help or avoid using this version in Salesforce

**Comment by PrateekKumarSrivastava** [comment]
> Seems that the issue will keep appearing along with additional plugins, so modifying the source code might not be a good solution.
> 
> Guess we'll need to get some additional help or avoid using this version in Salesforce
I was able to fix this issue also, now everything is working fine. 
Replacing the below line of code in the core/main.js - 

var matchesMethod = Element.prototype.matches ||
    Element.prototype.matchesSelector ||
    Element.prototype.msMatchesSelector;
var closestMethod = Element.prototype.closest || function (selector) {
    var el = this;
    if (!document.documentElement.contains(el)) {
        return null;
    }
    do {
        if (elementMatches(el, selector)) {
            return el;
        }
        el = el.parentElement || el.parentNode;
    } while (el !== null && el.nodeType === 1);
    return null;
};
function elementClosest(el, selector) {
    if (!el.closest) {
        if (!document.documentElement.contains(el)) {
            return null;
        }
        do {
            if (elementMatches(el, selector)) {
                return el;
            }
            el = el.parentElement || el.parentNode;
        } while (el !== null && el.nodeType === 1);
        return null;
    }
    else
        return el.closest(selector);
}
function elementMatches(el, selector) {
    if (!el.matches)
        return el.msMatchesSelector(selector);
    else
        return el.matches(selector);
}

**Comment by IvanWSM** [comment]
Have you tried adding more plugins to see if it still works? 

Also, could you format your previous comment a bit better so it is more readable please?

**Comment by PrateekKumarSrivastava** [comment]
> Have you tried adding more plugins to see if it still works?
> 
> Also, could you format your previous comment a bit better so it is more readable please?

I have formatted the comment properly but I think due to editor It is showing like this. 
All you need to do it just open core/main.js file and search for the above method and replace the code with mine.  If you are still not able to get it then please let me know your email address so that I can email you the js.

**Comment by crmnv95** [comment]
Hello @PrateekKumarSrivastava, I'm having the same issue and I found the piece of code you've typed but when I upload my fullcalendar library (with the core/main.js modified) to my static resource, the library doesn't get loaded. Maybe it's the version I'm using? version 4. Do you have a repo where I can get the full library code? 
Thank you :)
