### ISSUE TITLE
Adding new event, resets the dragged event's position.

### ISSUE THREAD

**Issue by Sourabh-Pandit** [fullcalendar/fullcalendar#5416]
Dear Team,
This is an excellant library to work with, thanks for this.
I came across an issue, when a new event is added.
Please see the steps to reproduce.
1) Drag an existing event to any new Date.
2) Try adding new event on any date( by  clicking the date)

It is observed that the dragged event is resets to its original position.

https://codesandbox.io/s/fullcalendar-v4-react-jvo67?file=/src/DemoApp.jsx

**Comment by acerix** [comment]
I believe this existing ticket captures this need:
https://github.com/fullcalendar/fullcalendar-react/issues/33
↑
Please visit the above issue, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates.
