### ISSUE TITLE
jQuery 3.5.0 breaks drag & drop for version 3

### ISSUE THREAD

**Issue by bretjb** [fullcalendar/fullcalendar#5417]
### Bug Reports
The upgrade to 3.5.0 breaks drag and drop. The issue seems to be attaching `$.data('event', ...)` to the entity. With it, the entity throws some _deep_ full calendar errors when dropped on the calendar entity, and without it, it seems just fine.

#### repro cases
The official demo docs are broken as a result of this: https://fullcalendar.io/docs/v3/external-dragging-demo
More stripped down version: https://codepen.io/bretjb/pen/WNQKJEP

**Comment by acerix** [comment]
I believe this existing ticket captures this need:
https://github.com/fullcalendar/fullcalendar/issues/5414
↑
Please visit the above issue, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates.
