### ISSUE TITLE
FullCalendarMoment.toMoment argument order does not match docs

### ISSUE THREAD

**Issue by osuagwu** [fullcalendar/fullcalendar#5418]
Cost me a lot of time because the doc(https://fullcalendar.io/docs/timeZone) says:
```js
let m = toMoment(calendar, arg.date)
```
But according to the reference below it should be:
```js
let m = toMoment(arg.date,calendar)
```
no?
https://github.com/fullcalendar/fullcalendar/blob/d3a2b13db43cfe9a450091776da3be25a0ca15c0/packages/moment/src/main.ts#L5

**Comment by acerix** [comment]
Thanks, confirmed.

https://codepen.io/acerix/pen/LYpBaPa?editors=0010

**Comment by arshaw** [comment]
i fixed this on the live site. sorry about that
