### ISSUE TITLE
Overlaid calendars drag and drop odd behaviour

### ISSUE THREAD

**Issue by gongAll** [fullcalendar/fullcalendar#5420]
So far I had only used side by side or single fullcalendars per page in my app, which was working fine, but there was a request to have a fullcalendar instance on a popup which overlaid another fullcalendar. The behaviour I'm getting is the following:

 Given the calendar behind as CALENDAR#1 and the calendar on the popup as CALENDAR#2; 

When I drag and drop an external event to a region which overlays right on top of the dates of the CALENDAR#1, it will drop on the CALENDAR#1, no matter if it is also on top of CALENDAR#2. If I drag and drop on the region outside of the CALENDAR#1 and inside of CALENDAR#2 it will drop on CALENDAR#2.

CASE ALWAYS EXPECTED:
![case expected ALWAYS](https://user-images.githubusercontent.com/36202212/81956074-cc4e3580-9602-11ea-9a1a-4bb59ca38e67.png)
ODD BEHAVIOUR DETECTED:
![odd behaviour](https://user-images.githubusercontent.com/36202212/81956080-cd7f6280-9602-11ea-82f9-188004e4f80e.png)

PS: If necessary I can post a test case, I do not have enough time to do so at the moment, just was expecting to get some lights on possible solutions, if anyone has come up to similar cases.

**Comment by acerix** [comment]
I believe this existing ticket captures this need:
https://github.com/fullcalendar/fullcalendar/issues/5026
↑
Please visit the above issue, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates.

**Comment by gongAll** [comment]
@acerix thank you for the redirection, didn't find that one on the first search 👍
