### ISSUE TITLE
Selecting does not work on iPhone with Safari on browserstack, scrolls instead

### ISSUE THREAD

**Issue by acerix** [fullcalendar/fullcalendar#5424]
Reported in https://fullcalendar.freshdesk.com/a/tickets/1840

In this demo in week view, touching and dragging will scroll the screen instead of selecting, even after waiting the 1 second.

https://fullcalendar.io/docs/date-clicking-selecting-demo

Confirmed with iPhone 11 Pro Safari using browserstack.com

**Comment by singhkgautam** [comment]
Love to have this traiged.

**Comment by acerix** [comment]
Closing since it turns out this only happens on browserstack.com
