### ISSUE TITLE
Events not being rendered correctly on TimeGrid

### ISSUE THREAD

**Issue by gongAll** [fullcalendar/fullcalendar#5426]
I have a weird behaviour when using the "TimeGrid" while defining the visibleRange which I will describe bellow.

When the fullcalendar renders, it is always like this:
![dadada](https://user-images.githubusercontent.com/36202212/82233074-5958fd80-9927-11ea-8e8f-a682bccfacd0.png)

When I resize the window, it will be like this:
![dadada2](https://user-images.githubusercontent.com/36202212/82233071-58c06700-9927-11ea-8cab-a0e47738df07.png)

And when I add an external event or change some event already in the calendar (startDate or duration) it will be like this:
![dadada3](https://user-images.githubusercontent.com/36202212/82233070-5827d080-9927-11ea-8cfa-6d30f21c8575.png)

View definition:
```
function rangeFunc(startDate: MomentInput, finalDate: MomentInput): DateRangeInput {
  if (!startDate) {
    return;
  }

  if (startDate === finalDate) {
    startDate = moment(startDate).startOf('d').subtract(2, 'd').utc(false).toDate();
    finalDate = moment(finalDate).endOf('d').add(2, 'd').utc(false).toDate();
  }

  return {
    start: moment(startDate).startOf('d').format('yyyy-MM-DD'),
    end: moment(finalDate).endOf('d').add(1, 'd').format('yyyy-MM-DD')
  };
}

public views: { [viewId: string]: any } = {
    timeGrid: {
      columnHeaderFormat: {month: 'long', day: 'numeric', weekday: 'long'},
      type: 'timeGrid', allDaySlot: false,
      visibleRange: () => rangeFunc(this.currentNonConformity.start, this.currentNonConformity.end),
      validRange: () => rangeFunc(this.currentNonConformity.start, this.currentNonConformity.end)
    }
  };
```

Only side note is that all the events except the red one and the extra event on the last image are generated through rrule+duration combo. I was not able to replicate this behaviour on code pen so far...

**Comment by acerix** [comment]
Would you be able to post a [runnable, stripped-down demonstration of the bug](http://fullcalendar.io/wiki/Reduced-Test-Cases/)? Would really appreciate it because the time saved reproducing will be time spent fixing.

**Comment by gongAll** [comment]
For whom it may concern I had to manually destroy and render the calendar since I was not able to find the root of the problem. I just had the idea that it could be the way I defined visible / valid ranges.
