### ISSUE TITLE
Week numbers are not clickable as navLinks

### ISSUE THREAD

**Issue by acerix** [fullcalendar/fullcalendar#5427]
In v4, week numbers can be clicked on from month view but it doesn't work in v5:

https://codepen.io/acerix/pen/qBOQYvO?editors=0010

Reported in https://fullcalendar.freshdesk.com/a/tickets/1842

**Comment by arshaw** [comment]
fixed in beta3: https://fullcalendar.io/blog/2020/05/react-ts-v5-beta

proof: https://codepen.io/acerix/pen/qBOQYvO?editors=0010
