### ISSUE TITLE
Full Calendar - Salesforce Lightning Web Component - Improper Rendering

### ISSUE THREAD

**Issue by ggalaios** [fullcalendar/fullcalendar#5431]
I have implemented a Lightning Web Component with FullCalendar.io (V4) in order to implement a customizable calendar in my Salesforce Environment. I post it here, so maybe someone could be helped. The only problem that i have is that, sometimes, i have an issue with rendering. For example, on the first login, the calendar does not load. Any ideas why this could occur? I post my code here: HTML
`
<template>
  <div class="slds-card">
    <lightning-button
      label={label.NewEvent}
      title="New Event"
      onclick={createNewEvent}
    ></lightning-button>
    <div class="fullcalendar" lwc:dom="manual"></div>
  </div>
</template>
`

`/*
@ggalaios 07/04/2020 
Lightning Web Component to Implement fullCalendar.io solution
This LWC will be contained in an Aura Component that will have a map with the respective Locations
*/

import { LightningElement, wire, track, api } from "lwc";
import { loadScript, loadStyle } from "lightning/platformResourceLoader"; //In order for fullCalendar to be displayed
import FullCalendarJS from "@salesforce/resourceUrl/FullCalendarJS"; //import the static Resource!
import { NavigationMixin } from "lightning/navigation"; //Import this in order to be able to pop-up the New Event Screen
import getEventsForDateRange from "@salesforce/apex/fullCalendarController.getEventsForDateRange"; //in order to call fullCalendarController Apex Class
import getlocale from "@salesforce/apex/fullCalendarController.getUserLanguage";
import NewEvent from "@salesforce/label/c.New_Event";

export default class FullCalendarJs extends NavigationMixin(LightningElement) {
  //declare trackable variables eventView, startDate, endDate to send to Parent Component. Counter will be responsible for not firing event on page load!
  label = { NewEvent };
  //var that stores the "View" of events (Day, Week, Month)
  @track eventView = {
    value: "timeGridWeek"
  };
  //var that stores the start date of the selected view, in order to pass it to Apex that will return the events withing the range
  @track startDate = {
    value: ""
  };
  //var that stores the end date of the selected view, in order to pass it to Apex that will return the events withing the range
  @track endDate = {
    value: ""
  };
  //var that is used to fire the event when view changes and dates change
  @track counter = {
    value: 0
  };
  //var that is used when an event is clicked to fire an event
  @track clicked = {
    value: 0
  };
  //var that is used to store the id of the event clicked
  @track clickedEventRecordId = {
    value: ""
  };
  @track error;

  //declare wire in order to call the Apex method imperatively!
  @wire(getEventsForDateRange, {
    fromDate: `$startDate.value`,
    endDate: `$endDate.value`
  })
  getEventsForDateRange;
  @wire(getlocale) locale;

  // Listeners When one of the values changes, handle changes and fire the respective custom events
  connectedCallback() {
    var targetCounter = new Proxy(this.counter, {
      //Counter Listener This variable will cause the event to fire
      set: (target, key, value) => {
        //alert(`${key} set to ${value}`);
        target[key] = value;
        //we don't want on page load to fire the event, that's why if exists
        const viewChangeEvent = new CustomEvent("viewchange", {
          detail: {
            calendarView: this.eventView.value,
            startDate: this.startDate.value,
            endDate: this.endDate.value
          }
        });
        // Fire the custom event
        this.dispatchEvent(viewChangeEvent);
        return true;
      }
    });
    this.counter = targetCounter;

    var targetProxy = new Proxy(this.eventView, {
      //Listener for event view
      set: function (target, key, value) {
        //alert(`${key} set to ${value}`);
        target[key] = value;
        return true;
      }
    });
    this.eventView = targetProxy;

    var targetStartDate = new Proxy(this.startDate, {
      //Listener for startDate
      set: function (target, key, value) {
        //alert(`${key} set to ${value}`);
        target[key] = value;
        return true;
      }
    });
    this.startDate = targetStartDate;

    var targetEndDate = new Proxy(this.endDate, {
      //Listener for endDate
      set: function (target, key, value) {
        //alert(`${key} set to ${value}`);
        target[key] = value;
        return true;
      }
    });
    this.endDate = targetEndDate;

    var targetclicked = new Proxy(this.clicked, {
      //Listener for clicked variable
      set: (target, key, value) => {
        //alert(`${key} set to ${value}`);
        target[key] = value;
        const clickOverEvent = new CustomEvent("eventclick", {
          detail: {
            eventRecordId: this.clickedEventRecordId.value
          }
        });
        // Fire the custom event
        this.dispatchEvent(clickOverEvent);
        return true;
      }
    });
    this.clicked = targetclicked;

    var targetclickedEventRecordId = new Proxy(this.clickedEventRecordId, {
      //Listener for endDate
      set: function (target, key, value) {
        //alert(`${key} set to ${value}`);
        target[key] = value;
        return true;
      }
    });
    this.clickedEventRecordId = targetclickedEventRecordId;
  }

  //Function to pop-up New Event Standard screen
  createNewEvent() {
    this[NavigationMixin.Navigate]({
      type: "standard__objectPage",
      attributes: {
        objectApiName: "Event",
        actionName: "new"
      },
      state: {
        nooverride: "1"
      }
    });
  }

  renderedCallback() {
    Promise.all([
      // First step: load FullCalendar core
      loadStyle(this, FullCalendarJS + "/packages/core/main.css"),
      loadScript(this, FullCalendarJS + "/packages/core/main.js")
    ])
      .then(() => {
        // Second step: Load the plugins in a new promise
        Promise.all([
          loadStyle(this, FullCalendarJS + "/packages/daygrid/main.css"),
          loadScript(this, FullCalendarJS + "/packages/daygrid/main.js"),
          loadStyle(this, FullCalendarJS + "/packages/timegrid/main.css"),
          loadScript(this, FullCalendarJS + "/packages/timegrid/main.js"),
          loadScript(this, FullCalendarJS + "/packages/interaction/main.js")
        ]).then(() => {
          // Third step: calls your calendar builder once the plugins have been also loaded
          this.initialiseFullCalendar(
            this.eventView,
            this.startDate,
            this.endDate,
            this.counter,
            this.clicked,
            this.clickedEventRecordId
          );
        });
      })
      .catch((error) => {
        console.error("error while loading the scripts here: " + error);
      });
  }

  initialiseFullCalendar(
    eventView,
    startDate,
    endDate,
    counter,
    clicked,
    clickedEventRecordId
  ) {
    console.log("locale is: " + this.locale.data);
    let dataObj = {};
    let events = [];
    const ele = this.template.querySelector("div.fullcalendar");
    //console.log("ele >>> " + ele);
    //If Not greek Locale, show English view
    if (this.locale.data != "el") {
      var calendar = new FullCalendar.Calendar(ele, {
        firstDay: 1, //set first day of the week Monday
        header: {
          left: "prev,next,today",
          center: "title",
          right: "dayGridMonth,timeGridWeek,timeGridDay"
        },
        locale: this.locale.data,
        plugins: [
          "interaction",
          "resourceDayGrid",
          "resourceTimeGrid",
          "dayGrid",
          "timeGrid",
          "timeline",
          "interactionPlugin",
          "listPlugin"
        ],
        events: {},
        defaultView: "timeGridWeek",
        eventClick: function (info) {
          info.jsEvent.preventDefault(); // don't let the browser navigate
          clickedEventRecordId.value = info.event.id;
          clicked.value += 1; //increase clicked value in order to fire the event
        },
        datesRender: function (info) {
          //Triggered when a new set of dates has been rendered.
          eventView.value = info.view.type; //set the new event view to the eventView variable
          startDate.value = info.view.activeStart.toISOString().slice(0, 10); //set the new start date formatted in (YYYY-MM-DD)
          endDate.value = info.view.activeEnd.toISOString().slice(0, 10); //set the new end date formatted in (YYYY-MM-DD)
          counter.value += 1; //Increment the counter by 1, in order to fire the event
          getEventsForDateRange({
            //Call Apex method getEventsForDateRange giving the new set of dates
            fromDate: startDate.value,
            endDate: endDate.value
          })
            .then((result) => {
              //get the results of the events list that should be rendered
              console.log(result);
              var eventSources = calendar.getEventSources();
              var len = eventSources.length;
              //Erase all the existing events in the calendar
              for (var i = 0; i < len; i++) {
                eventSources[i].remove();
              }
              len = result.length;
              dataObj = {};
              events = [];
              //Build again the list of the events that should be displayed
              for (var i = 0; i < len; i++) {
                dataObj.id = result[i].Id;
                dataObj.start = result[i].StartDateTime;
                dataObj.end = result[i].EndDateTime;
                dataObj.title = result[i].Subject;
                dataObj.url = "event/" + result[i].Id + "/view";
                dataObj.allDay = result[i].IsAllDayEvent;
                events.push(dataObj);
                dataObj = {};
              }
              calendar.addEventSource(events); //Render the new events to the Calendar!
            })
            .catch((error) => {
              this.error = error;
              console.log(error);
            });
        }
      });
      calendar.render();
    } else {
      // If Language is Greek, show the appropriate buttons in greek!
      var calendar = new FullCalendar.Calendar(ele, {
        firstDay: 1, //set first day of the week Monday
        customButtons: {
          goToday: {
            text: "Σήμερα",
            click: function () {
              calendar.today();
            }
          },
          minas: {
            text: "Μήνας",
            click: function () {
              calendar.changeView("dayGridMonth");
            }
          },
          evdomada: {
            text: "Εβδομάδα",
            click: function () {
              calendar.changeView("timeGridWeek");
            }
          },
          mera: {
            text: "Ημέρα",
            click: function () {
              calendar.changeView("timeGridDay");
            }
          }
        },
        allDayText: "Ολοήμερο",
        eventLimitText: "περισσότερα",
        noEventsMessage: "Δεν υπάρχουν γεγονότα προς εμφάνιση",
        header: {
          left: "prev,next,goToday",
          center: "title",
          right: "minas,evdomada,mera"
        },
        locale: this.locale.data,
        plugins: [
          "interaction",
          "resourceDayGrid",
          "resourceTimeGrid",
          //"dayGrid",
          "timeGrid",
          "timeline",
          "interactionPlugin",
          "listPlugin"
        ],
        events: {},
        defaultView: "timeGridWeek",
        eventClick: function (info) {
          info.jsEvent.preventDefault(); // don't let the browser navigate
          clickedEventRecordId.value = info.event.id;
          clicked.value += 1; //increase clicked value in order to fire the event
        },
        datesRender: function (info) {
          //Triggered when a new set of dates has been rendered.
          eventView.value = info.view.type; //set the new event view to the eventView variable
          startDate.value = info.view.activeStart.toISOString().slice(0, 10); //set the new start date formatted in (YYYY-MM-DD)
          endDate.value = info.view.activeEnd.toISOString().slice(0, 10); //set the new end date formatted in (YYYY-MM-DD)
          counter.value += 1; //Increment the counter by 1, in order to fire the event
          getEventsForDateRange({
            //Call Apex method getEventsForDateRange giving the new set of dates
            fromDate: startDate.value,
            endDate: endDate.value
          })
            .then((result) => {
              //get the results of the events list that should be rendered
              console.log(result);
              var eventSources = calendar.getEventSources();
              var len = eventSources.length;
              //Erase all the existing events in the calendar
              for (var i = 0; i < len; i++) {
                eventSources[i].remove();
              }
              len = result.length;
              dataObj = {};
              events = [];
              //Build again the list of the events that should be displayed
              for (var i = 0; i < len; i++) {
                dataObj.id = result[i].Id;
                dataObj.start = result[i].StartDateTime;
                dataObj.end = result[i].EndDateTime;
                dataObj.title = result[i].Subject;
                dataObj.url = "event/" + result[i].Id + "/view";
                dataObj.allDay = result[i].IsAllDayEvent;
                events.push(dataObj);
                dataObj = {};
              }
              calendar.addEventSource(events); //Render the new events to the Calendar!
            })
            .catch((error) => {
              this.error = error;
              console.log(error);
            });
        }
      });
      calendar.render();
    }
  }
}`

All the other files are from fullCalendar.io version 4 package exactly the same. The error that i see in my browser console is:
`Uncaught (in promise) TypeError: Cannot read property 'DayGrid' of undefined at TimeGridView.AbstractTimeGridView._renderSkeleton (/resource/1588675724000/COGNT__FullCalendarJS/packages/timegrid/main.js:1064) at TimeGridView._renderSkeleton (/resource/1588675724000/COGNT__FullCalendarJS/packages/timegrid/main.js:1342) at TimeGridView.res [as renderSkeleton] (/resource/1588675724000/COGNT__FullCalendarJS/packages/core/main.js:3813) at TimeGridView.AbstractTimeGridView.render (/resource/1588675724000/COGNT__FullCalendarJS/packages/timegrid/main.js:1042) at TimeGridView.render (/resource/1588675724000/COGNT__FullCalendarJS/packages/timegrid/main.js:1319) at TimeGridView.Component.receiveProps (/resource/1588675724000/COGNT__FullCalendarJS/packages/core/main.js:4578) at CalendarComponent.renderView (/resource/1588675724000/COGNT__FullCalendarJS/packages/core/main.js:7343) at CalendarComponent.render (/resource/1588675724000/COGNT__FullCalendarJS/packages/core/main.js:7174) at CalendarComponent.Component.receiveProps (/resource/1588675724000/COGNT__FullCalendarJS/packages/core/main.js:4578) at Calendar.renderComponent (/resource/1588675724000/COGNT__FullCalendarJS/packages/core/main.js:7946)`

**Comment by acerix** [comment]
Would you be able to post a [runnable, stripped-down demonstration of the bug](http://fullcalendar.io/wiki/Reduced-Test-Cases/)? Would really appreciate it because the time saved reproducing will be time spent fixing.
