### ISSUE TITLE
CustomButtonInput click argument type is incorrect

### ISSUE THREAD

**Issue by kgilden** [fullcalendar/fullcalendar#5432]
It seems to me that the `CustomButtonInput` TypeScript type seems to be incorrect.

In [v4.4.0](https://github.com/fullcalendar/fullcalendar/blob/v4.4.0/packages/core/src/types/input-types.ts#L30) and [v5.0.0-beta2](https://github.com/fullcalendar/fullcalendar/blob/v5.0.0-beta.2/packages/core/src/types/input-types.ts#L30) you can see that the first argument type is declared as `HTMLElement`, but in practice it seems to be `MouseEvent`.

Proof: https://repl.it/@kgilden/fullcalendar-5432

**Comment by acerix** [comment]
Thanks, confirmed.

**Comment by arshaw** [comment]
I made some changes to this in v5.2.0 (just released). The first argument will continue to be the MouseEvent, though the typescript definitions have been updated to reflect. A newly added second argument is the HTMLElement. I might have switched them if I didn't feel the need to keep this backward compatible.
