### ISSUE TITLE
Fullcalendar v5-beta3 eventDisplay bug

### ISSUE THREAD

**Issue by martinfruehmorgen** [fullcalendar/fullcalendar#5434]
Hello,

see this codepen:
https://codepen.io/martinfruehmorgen/pen/PoPXvZj?editable=true&editors=001%3Dhttps%3A%2F%2Ffullcalendar.io%2Fdocs%2Fv5%2Fevent-colors-demo

The eventDisplay 'block' does not work.

Thanks!

**Comment by arshaw** [comment]
confirmed, thank you. i'll get this fixed asap

**Comment by arshaw** [comment]
this is fixed in beta4. could you verify?

**Comment by martinfruehmorgen** [comment]
Yes, thats fixed. Thanks!
