### ISSUE TITLE
Support for moment.js 2.26 in v3 npm module build

### ISSUE THREAD

**Issue by JoeJennings** [fullcalendar/fullcalendar#5438]
### Feature Requests
Request support for 2.26.x of moment js on v3.10.x release series of fullcalendar.

v3.10.2 released recently implementing shrinkwrap and locking moment js to 2.25.3

Reference: https://github.com/fullcalendar/fullcalendar/compare/v3.10.1...v3.10.2#diff-36018a6a9e1de1798516799b84841318R6061

moment js released 2.26.0 a day or so later

Reference: https://www.npmjs.com/package/moment/v/2.26.0

This unfortunate series of events makes it troublesome to consume v3.10.2 of fullcalendar and many other components that also leverage moment js.

**Comment by acerix** [comment]
I don't believe that should block updating to 2.26, do you get any error message?

I tested the v3 webpack example and it uses 2.26 without any changes:

https://github.com/fullcalendar/webpack-example/tree/v3

**Comment by JoeJennings** [comment]
That's not what I found when I attempted this.  Steps I performed:

1. Forked the repo
2. Checked out the v3 branch
3. Removed the package-lock.json file
4. Ran npm install
5. Ran npm list

Results only show moment 2.25.3 being available in the project, no references to 2.26.0

├─┬ karma-verbose-reporter@0.0.6
│ └── colors@1.1.2 deduped
├── moment@2.25.3
├─┬ moment-timezone@0.5.31
│ └── moment@2.25.3 deduped
├── native-promise-only@0.8.1

Am I missing something or not following some step correctly?

**Comment by JoeJennings** [comment]
Yep I see what you are saying, it does allow for 2.26.0 to be pulled in, but does duplicate the component.  

cc @acerix

**Comment by acerix** [comment]
If you mean including Moment as a browser global like jQuery that should be possible:

https://github.com/fullcalendar/webpack-example/blob/v3/webpack.config.js#L9
