### ISSUE TITLE
Day cells of Month View in japanese locale contains a unnecessary character

### ISSUE THREAD

**Issue by daigot** [fullcalendar/fullcalendar#5439]
Hello,

In Full Calendar 4, day cells of month view in ja (japanese) locale display days like "1日".
But this looks strange, because calendars in japan are printed only day number without "日" (day).

It can be reproduced in the official locales demo.
https://fullcalendar.io/docs/locale-demo

Thanks.

**Comment by acerix** [comment]
The character comes from how browsers render "day: 'numeric'" format:

https://codepen.io/acerix/pen/mdevZqK?editors=0010

As a workaround, you could use the moment.js plugin since that renders it without the character:

https://fullcalendar.io/docs/v3/locale-demo

**Comment by daigot** [comment]
@acerix , thank you for your reply.

> As a workaround, you could use the moment.js plugin since that renders it without the character:

How can I do that in v4?
I'm using v4 with the moment plugin.
But FullCalendar renders day numbers with the character by default.
And I could not find a setting for format of day numbers in the official documents.

**Comment by acerix** [comment]
Sorry, I thought the plugin could change the format of the day numbers but I couldn't find a way.

The best workaround I found is to replace the labels from `dayRender`, eg:

https://codepen.io/acerix/pen/MWaRGYa?editors=0010

**Comment by daigot** [comment]
Thank you to show me the example.
I will use the workaround for now.
I hope that it will be fixed or a setting of day number format will be added someday.

**Comment by papegoje** [comment]
> Sorry, I thought the plugin could change the format of the day numbers but I couldn't find a way.
> 
> The best workaround I found is to replace the labels from `dayRender`, eg:
> 
> https://codepen.io/acerix/pen/MWaRGYa?editors=0010

For v5, I just found the following works for day cell in grid view only (maybe).

```
      dayCellContent: function (arg) {
        return arg.date.getDate();
      },
```

I'm just new to fullcalendar and not sure if `dayCellContent` could be an alternative to `dayRender` in v4.

**Comment by arshaw** [comment]
using `dayCellContent` is probably the best idea
