### ISSUE TITLE
events/eventSources should accept an object map

### ISSUE THREAD

**Issue by arshaw** [fullcalendar/fullcalendar#5442]
Right now, the `events` and `eventSources` settings ultimately accept an **array** of event objects to parse. This is often at odds with how declarative frameworks such as React/Vue/Angular deal with their data. Often times event data is stored in an **object hash**:

```js
{
  '001': {
    id: '001',
    title: 'nice event',
    start: '2020-05-21'
  },
  '002': {
    id: '002',
    title: 'another event',
    start: '2020-05-22'
  }
}
```

Hashes are much easier for pinpointing specific events for update or removal.

When event data stored in a hash is given to FullCalendar, it must be converted into an array first. This leads to a new array being produced every time, making it seem as though event data has changed each time, which might cause unnecessary rerenders.

**Proposal:** have FullCalendar accept a hash for events. The hash keys will be ignored. Only the values will be used.

**Comment by arshaw** [comment]
I actually decided against this. It would have been impossible for FullCalendar to distinguish an events hash from an event source in extended form (also an object).

Instead, it's recommended to generate an array from your event in a different way.

In React I'd recommend a memoized function. In the react+redux example [I implemented that via reselect](https://github.com/fullcalendar/fullcalendar-example-projects/blob/294ace9f0931394445cda34c9967804204face68/react-redux/src/DemoApp.jsx#L158).

In Vue I'd recommend using a computed prop.

**Comment by marcoancona** [comment]
Amazing work with v5, thanks!
Regarding this topic, wouldn’t computed prop or memorization functions trigger the rendering of all events, even when just one was updated?
My understanding is that v5 is more rendering efficient but in all my experiments the event content hook is called for all events in the provided array, even when one of the event elements was updated
