### ISSUE TITLE
API issue with changeview functional component

### ISSUE THREAD

**Issue by wispyco** [fullcalendar/fullcalendar#5444]
I am getting the following error after trying to implememnt this changeview API
`Error: No available FullCalendar view plugins.`

https://github.com/fullcalendar/fullcalendar/issues/4684#issuecomment-620787260

here is my codesandbox

https://codesandbox.io/s/billowing-river-q1f58?file=/src/App.js

List: https://github.com/fullcalendar

**Comment by acerix** [comment]
I don't see any error in your demo and doesn't seem to be using `changeView` so maybe it didn't get saved.  Otherwise please provide the steps to reproduce the error.

This page explains how to access the API: 

https://fullcalendar.io/docs/vue#accessing-fullcalendars-api
