### ISSUE TITLE
Event title should display on same line as time for 30 minute events in grid views

### ISSUE THREAD

**Issue by brennanmurphy** [fullcalendar/fullcalendar#5447]
In the timeGridWeek or timeGridDay view, the event title does not display for 30 minute events in v5-beta3, as it is pushed outside the event block. 
In v4, the event title would appear on the same line as the time for the event. 

demo v5-beta3: https://codepen.io/brennan22lbs/pen/jObJjwJ
demo v4: https://codepen.io/brennan22lbs/pen/abvMgyN

Tested on both chrome and firefox

**Comment by arshaw** [comment]
this has been fixed in the new [v5 release candidate](https://fullcalendar.io/blog/2020/06/v5-rc-new-features)

https://codepen.io/arshaw/pen/rNxMJYm
