### ISSUE TITLE
windowResize arg incorrect in docs

### ISSUE THREAD

**Issue by brennanmurphy** [fullcalendar/fullcalendar#5448]
Based on the documention for `windowResize` option, would expect the arg to be a ViewApi object, but the ViewApi object is wrapped in another object, with view as the only key in the outer object. ie:

```js
 new FullCalendar.Calendar(calendarEl, {
    windowResize: function (view) {
        console.log(view.type); // would expect view name to be displayed, undefined logged instead
        console.log(view.view.type); // will log view name
    }
});
```

Codepen: https://codepen.io/brennan22lbs/pen/qBOvzKr

Not sure if this is the intended way it should work, but if so I think the documentation should be updated.

Documentation link: https://fullcalendar.io/docs/v5/windowResize

**Comment by acerix** [comment]
Thanks, confirmed.

**Comment by arshaw** [comment]
this is fixed in the docs now. thanks
