### ISSUE TITLE
Timed events render with a dot despite setting eventDisplay:block

### ISSUE THREAD

**Issue by ningzhang422** [fullcalendar/fullcalendar#5451]
https://codepen.io/rubytech/pen/ExVJKap
'block' - When in daygrid, renders the event as a solid rectangle. When in other views, will render normally.

**Comment by acerix** [comment]
Thanks, confirmed.

**Comment by arshaw** [comment]
dup of:
https://github.com/fullcalendar/fullcalendar/issues/5434
&uarr;
Could you please visit the link, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates?
