### ISSUE TITLE
More exports of interfaces needed

### ISSUE THREAD

**Issue by samvloeberghs** [fullcalendar/fullcalendar#5452]
The `eventClick` handler and others, more specifically the ones in `CALENDAR_LISTENER_REFINERS`, that can be bind using the `optionOverrides` have a signature of `Identity<arg: T>`. 

In this case `T` can be an interface of type `EventClickArg`, `ViewApi`, `EventHoveringArg`, `DataSelectArg` and `DateUnselectArg`. Those interfaces (except `ViewApi`) are currently not exported in the `common/main.d.ts` and they are needed when implementing the handlers in a TypeScript environment.

Example:

```ts
const calendarInstance = new Calendar(htmlElement, {
  ...
  eventClick: (eventClickArg: EventClickArg) => {
    console.log(eventClickArg
  }
  ...
});
calendarInstance.render();
```

Before I create a PR can you please let me know if this is something that will be accepted and pulled?

(There are other interfaces, like for example `EventSourceInput` in the `CALENDAR_OPTION_REFINERS` that should be exported as well.)

**Comment by arshaw** [comment]
@samvloeberghs , thanks for offering a PR. don't worry, I'll work on this rather soon, before the official v5 release

**Comment by samvloeberghs** [comment]
@arshaw cool thanks! Great work so far, thans for all your hard work on this

**Comment by arshaw** [comment]
this is fixed in beta4. could you verify @samvloeberghs ?

**Comment by samvloeberghs** [comment]
jup thx @arshaw
