### ISSUE TITLE
Different Slot Duration in v4

### ISSUE THREAD

**Issue by smhnkmr** [fullcalendar/fullcalendar#5453]
I want to define different slot duration for calendar and I see the issue [#472 ](https://github.com/fullcalendar/fullcalendar/issues/472) exactly address this problem.

But it is forked on v3.8 and it's been not updated since 2018 now. I see now the current master version is 2000+ commits ahead. And mainly I couldn't make it to work with Scheduler/Resources.

@arshaw is there any latest fork with this feature of binding a time slot. can you please suggest a way to have this feature and scheduler to work. thanks.

**Comment by acerix** [comment]
The issue you mentioned is still open as a feature request for this so please **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)) and press the 🔈**Subscribe** button to receive updates.
