### ISSUE TITLE
Use Timezone for businessHours

### ISSUE THREAD

**Issue by eggnukes** [fullcalendar/fullcalendar#5455]
When adding businessHours to calendar, it would be great if there could be an option to enable timezone conversion.
Right now, if I set bussinessHours from 32 400 000 to 61 200 000, I just get 9AM to 5PM with any timezone setting.
```
businessHours: {
  daysOfWeek: [1, 2, 3, 4],
  startTime: 32400000,
  endTime: 61200000
}
```
It would be great if timezone offset was applied here, because, especially for online businesses, 
business hours really will differ with timezone due to office location being in one place and clients possibly being from all over the world.
So bussinessHours from 32 400 000 to 61 200 000 would be 9AM to 5PM in London (UTC), 10AM to 6PM in Paris during winter (no DST), 11AM to 7PM in Paris during summer (DST) and so on.

**Comment by acerix** [comment]
Since startTime/endTime is just the time of day (ie. no date) I think it would be better to not have timestamps there but maybe adding a timeZone option to businessHours instead.

**Comment by eggnukes** [comment]
@acerix, timeZone option inside businessHours definition would work. Also, this is looks readable and is easy to understand.
```
...
businessHours: {
  daysOfWeek: [1, 2, 3, 4],
  startTime: '09:00',
  endTime: '17:00',
  timeZone: 'UTC'
},
timeZone: 'Europe/Paris',
...
```
The businessHours should be calculated by converting startTime and endTime for each day from businessHours.timeZone to calendar timeZone.

**Comment by arshaw** [comment]
businessHours are meant to be very simple, without timezones. If you want timezones, use [background events](https://fullcalendar.io/docs/background-events) instead, with a daily recurring start/end time.
