### ISSUE TITLE
@fullcalendar/common has no exported member ScrollGridChunkConfig

### ISSUE THREAD

**Issue by dennis82m** [fullcalendar/fullcalendar#5459]
Compiling only sometimes (the weird part) gives me these errors:

1.  node_modules/@fullcalendar/timeline/main.d.ts:3:23 - error TS2307: Cannot find module './vdom'.

2. node_modules/@fullcalendar/scrollgrid/main.d.ts:2:89 - error TS2724: Module '"@fullcalendar/common"' has no exported member 'ScrollGridChunkConfig'

**Comment by arshaw** [comment]
I'm witnessing problem 2. I will start to debug.

But problem 1 seems like it'd be impossible to happen in 5.0.0-beta.4. The guilty line was present in beta.3 but [no longer in beta.4](https://cdn.jsdelivr.net/npm/@fullcalendar/timeline@5.0.0-beta.4/main.d.ts). Can you check you correctly updated @fullcalendar/timeline ?

**Comment by dennis82m** [comment]
> I'm witnessing problem 2. I will start to debug.
> 
> But problem 1 seems like it'd be impossible to happen in 5.0.0-beta.4. The guilty line was present in beta.3 but [no longer in beta.4](https://cdn.jsdelivr.net/npm/@fullcalendar/timeline@5.0.0-beta.4/main.d.ts). Can you check you correctly updated @fullcalendar/timeline ?

you're right ... only problem 2 persists

**Comment by arshaw** [comment]
This is fixed in the new [v5 release candidate](https://fullcalendar.io/blog/2020/06/v5-rc-new-features)
