### ISSUE TITLE
5.0.0-beta.4 ./node_modules/@fullcalendar/react/dist/main.js Attempted import error: 'CalendarRoot' is not exported from '@fullcalendar/common'.

### ISSUE THREAD

**Issue by devchris** [fullcalendar/fullcalendar#5461]
### Bug Reports
After updating to beta 4 I'm receiving the following error:
```
./node_modules/@fullcalendar/react/dist/main.js
Attempted import error: 'CalendarRoot' is not exported from '@fullcalendar/common'.
```

**Comment by arshaw** [comment]
hey @devchris , could you go into your node_modules directory and see what version the @fullcalendar/common package is? `CalendarRoot` **IS** exported in beta.4 ([see source](https://cdn.jsdelivr.net/npm/@fullcalendar/common@5.0.0-beta.4/main.js)) so I'm not sure what's going on

**Comment by arshaw** [comment]
could you run `npm ls @fullcalendar/common` in your project directory and then paste the output into a comment?

**Comment by sgoodrow-zymergen** [comment]
I am seeing something similar when running our Jest tests, but unsure if it's the same. I don't see this issue with v4:

```
FAIL  src/components/<redacted>.js
  ● Test suite failed to run

    Cannot find module '@fullcalendar/react' from '<redacted>.js'

    However, Jest was able to find:
    	'./<redacted>.js'

    You might want to include a file extension in your import, or update your 'moduleFileExtensions', which is currently ['web.js', 'js', 'web.ts', 'ts', 'web.tsx', 'tsx', 'json', 'web.jsx', 'jsx', 'node'].
```

$ npm ls @fullcalendar/common
@<project>@<version> /Users/<user>/projects/github/<redacted>
├─┬ @fullcalendar/core@5.0.0-beta.4
│ └── @fullcalendar/common@5.0.0-beta.4
├─┬ @fullcalendar/daygrid@5.0.0-beta.4
│ └── @fullcalendar/common@5.0.0-beta.4  deduped
├─┬ @fullcalendar/react@5.0.0-beta.4
│ └── @fullcalendar/common@5.0.0-beta.4  deduped
└─┬ @fullcalendar/timegrid@5.0.0-beta.4
  └── @fullcalendar/common@5.0.0-beta.4  deduped

**Comment by arshaw** [comment]
@sgoodrow-zymergen , that's almost definitely a separate issue. can you open a new ticket please?

**Comment by devchris** [comment]
@arshaw sorry for the late reply

```
└─ @fullcalendar/common@5.0.0-beta.4
✨  Done in 0.59s.
```

**Comment by devchris** [comment]
This can be closed. 

**Pro Tip:**
After upgrading a package, don't forget to restart your server!
