### ISSUE TITLE
chang timeGridTime view to fail;

### ISSUE THREAD

**Issue by conkyliu** [fullcalendar/fullcalendar#5463]
### Bug Reports
You MUST post a recreation or else your issue will be CLOSED without explanation.
Instructions: https://fullcalendar.io/reporting-bugs
![image](https://user-images.githubusercontent.com/26617741/83098823-2f999680-a0de-11ea-923e-46e432235211.png)

When I switch from resourceTimelineWeek to timeGridDay I get an error, my slotDuration is set like this
`const slotDuration = () => {
      if (this.calendarViewType === 'timeGridDay') {
        return { hour: 0.5 };
      }
      return { day: 1 };
    };`

**Comment by acerix** [comment]
Would you be able to post a [runnable, stripped-down demonstration of the bug](http://fullcalendar.io/wiki/Reduced-Test-Cases/)? Would really appreciate it because the time saved reproducing will be time spent fixing.
