### ISSUE TITLE
Unnecessary dot in pt-br translation of weekday names

### ISSUE THREAD

**Issue by rafaelgfirmino** [fullcalendar/fullcalendar#5466]
### Bug Reports
I'm using the version 4.4.0 and when I using a pt-br translation is added one dot(.) after week name.

DOM. | SEG. | TER. | QUA. | QUI. | SEX. | SÁB.
-- | -- | -- | -- | -- | -- | --

The right way should be like this

DOM | SEG | TER | QUA | QUI | SEX | SÁB
-- | -- | -- | -- | -- | -- | --

You can see in this example. 
https://fullcalendar.io/docs/locale-demo

**Comment by acerix** [comment]
Thanks, confirmed.

As a workaround you could remove them from `datesRender`: 

https://codepen.io/acerix/pen/zYvVpzr?editors=0010

I see version 3 didn't have the dots, so using the moment plugin could fix the week name in other places.

https://fullcalendar.io/docs/v3/locale-demo

**Comment by rafaelgfirmino** [comment]
Thanks for the answer. But how do I do it using vuejs?

**Comment by rafaelgfirmino** [comment]
I managed to do it using vue.js, but I had to make some modifications.
