### ISSUE TITLE
Event popover display issues with many events

### ISSUE THREAD

**Issue by yuan9090** [fullcalendar/fullcalendar#5471]
**Bug Reports**

When I setting `dayMaxEventRows` and click `+ more Link`, the popup is broken. 
See codepen or pic :

![螢幕快照 2020-06-01 11 21 33](https://user-images.githubusercontent.com/9431852/83373217-29672b00-a3fa-11ea-83d9-f93d3a5c2ffc.png)

https://codepen.io/yuan9090/pen/BajBNVg 

Thanks a lot !

**Comment by yuan9090** [comment]
**Another Bug Report**

When I have many events and open popover, but the popover can't scroll to end.

Please Check, Thanks a lot !

**Comment by acerix** [comment]
Thanks, confirmed.

**Comment by arshaw** [comment]
This is fixed in the new [v5 release candidate](https://fullcalendar.io/blog/2020/06/v5-rc-new-features)

https://codepen.io/arshaw/pen/yLeavXJ?editors=0010

**Comment by k-sai-kiranmayee** [comment]
Hello all, I know this has been closed a while ago, but could anyone confirm that the popover is scrollable in iOS, please.
Have tried setting **height** and **max-height** and **overflow-y:auto/scroll/visible** and **-webkit-overflow-scrolling: touch** still it's not working. However, it is working fine on desktop and Android.

Could anyone help me with this one, please

Thank you
