### ISSUE TITLE
Day view width is getting increased

### ISSUE THREAD

**Issue by shafinms** [fullcalendar/fullcalendar#5474]
Hi, There is an issue in the calendar, the day view width is getting increased on clicking next button and doing drag and drop. Our calendar is a combination of resource calendar in day view and normal in week/month view. The issue occurs when we enables the option 'navLinks: true' (to make day names and week names clickable).
ie: it allows to click on a date in month/week view to redirect to day view.

[day_view_issue.zip](https://github.com/fullcalendar/fullcalendar/files/4715283/day_view_issue.zip)

**Comment by acerix** [comment]
Would you be able to post a [runnable, stripped-down demonstration of the bug](http://fullcalendar.io/wiki/Reduced-Test-Cases/)? Would really appreciate it because the time saved reproducing will be time spent fixing.

**Comment by shafinms** [comment]
okay I will make it in 'codepen'
