### ISSUE TITLE
deafultView  "resourceDayGridMonth" not working

### ISSUE THREAD

**Issue by Nolandos** [fullcalendar/fullcalendar#5475]
Hello ! I have a problem with deafultView.

When i use:

defaultView="resourceDayGrid"
defaultView="resourceDayGridDay"
defaultView="resourceDayGridWeek"

this working.

When I use:
defaultView="resourceDayGridMonth" this no working. 

I have an error: Uncaught TypeError: Cannot read property 'date' of undefined
at Object.AbstractDayGridView._this.renderDayGridNumberIntroHtml [as renderNumberIntroHtml]...

This should work. https://fullcalendar.io/docs/plugin-index

When I do: calendarApi.changeView('resourceDayGridMonth') - this working, but i want have this in default view.

**Comment by acerix** [comment]
Would you be able to post a [runnable, stripped-down demonstration of the bug](http://fullcalendar.io/wiki/Reduced-Test-Cases/)? Would really appreciate it because the time saved reproducing will be time spent fixing.
