### ISSUE TITLE
React Full Calender: When assigning setProps it crashes the browser

### ISSUE THREAD

**Issue by danvernon** [fullcalendar/fullcalendar#5477]
I am trying to set a class to each event so I can style the different events I have, but when setting the prop below it becomes unresponsive.

```
<FullCalendar
        defaultView="dayGridMonth"
        events={events}
        eventRender={(info) => {
          // Assign count to event
          let count = info.event.extendedProps.count;
          let span = document.createElement("span");
          span.classList.add("count");
          let number = document.createTextNode(count);
          span.appendChild(number);
          info.el.prepend(span);
          // Create dash
          let dash = document.createElement("div");
          dash.classList.add("dash");
          info.el.append(dash);
          // Set class for each event
          // console.log(info.event);
          info.event.setProp('classNames', [`${info.event.title}`]);
        }}
        plugins={[dayGridPlugin]} />
```

## Design

![image](https://user-images.githubusercontent.com/428197/83541885-22bbdf00-a4f2-11ea-8010-4116b196ad0e.png)

## Current Code without classes

![image](https://user-images.githubusercontent.com/428197/83541924-2ea7a100-a4f2-11ea-8de3-563cc5e3f8ee.png)

**Comment by acerix** [comment]
Would you be able to post a [runnable, stripped-down demonstration of the bug](http://fullcalendar.io/wiki/Reduced-Test-Cases/)? Would really appreciate it because the time saved reproducing will be time spent fixing.

**Comment by asadakbar** [comment]
I'll try to post a demo of the bug but wanted to document that I'm hitting the same issue as well. Dropping some console logs seems to indicate that the events rerender after the new class names are added, and the eventClassNames function hook keeps getting called. It's going into an infinite loop.
