### ISSUE TITLE
Incorrect version of tslib required

### ISSUE THREAD

**Issue by dneuschaefer-rube** [fullcalendar/fullcalendar#5479]
Many of the plugins require `tslib` with version `^1.9.3`. However most plugins also use the `__spreadArrays` helper, which was [added in 1.10](https://github.com/microsoft/tslib/releases/tag/1.10.0). Therefore you will run into errors unless you manually add a dependency to at minimum version `^1.10.0`.

**Comment by acerix** [comment]
Thanks, confirmed. 

Can be reproduced with the [typescript example project for v5](https://github.com/fullcalendar/fullcalendar-example-projects/tree/v5/typescript-scheduler), after downgrading tslib with `npm install tslib@1.9.3` it gives warnings like this during build:

```
WARNING in ./node_modules/@fullcalendar/daygrid/main.js 654:43-57
"export '__spreadArrays' was not found in 'tslib'
 @ ./src/main.ts
```

And the build doesn't work, gives the error `TypeError: Object(...) is not a function`.

**Comment by arshaw** [comment]
All packages have their tslib version updated to ^2.0.0 in the [new v5 release candidate](https://fullcalendar.io/blog/2020/06/v5-rc-new-features)
