### ISSUE TITLE
Consistent ordering of events that span several weeks

### ISSUE THREAD

**Issue by skys215** [fullcalendar/fullcalendar#5481]
# Bug Reports?

## Reduced test case:

https://codepen.io/skys215/pen/mdVdNwP

## Description

I'm using `dayRender` to add events for everyDay for some reason. 

I also have events which may last for over a week or a month.

What I found out is that if the event crosses the weekend, the event which created by `dayRender` will be in the second row which it was in the first row when I loaded the page.

Seems that events which has started from the previous week has higher priority than those events which is created by the `dayRender` method.

I thought that it would be all in the top or bottom of the day cell.

**Comment by acerix** [comment]
It appears to be working as expected; on each day, the events are in order of when they start, except during the week events continue in the same position from the day they start.  It shouldn't matter how the events are added.

If you are looking for something else, it may help to include an example of how you want them displayed.

**Comment by skys215** [comment]
I thought the event which continues from last week will show in the second row since it shows in the second row at first week.

![image](https://user-images.githubusercontent.com/4977935/83832086-70676000-a71b-11ea-8965-f36d1a58c581.png)

**Comment by acerix** [comment]
I can see how that ordering would be more consistent, but I believe it doesn't work that way because in some cases there would be too much space.

**Comment by skys215** [comment]
Is it because the event is continuing since last week, so it is showing at top? Or is it because the event created by dayRender is an all day event, it doesn't have start time, so it is showing at the bottom?

**Comment by arshaw** [comment]
This has been fixed in v5.7.0!
blog post: https://fullcalendar.io/blog/2021/05/new-features-in-v570

repro: https://codepen.io/arshaw/pen/WNprNNW?editors=0010
