### ISSUE TITLE
Fullcalender Vue v5beta4 does not show template slot eventContent correctly

### ISSUE THREAD

**Issue by martinfruehmorgen** [fullcalendar/fullcalendar#5483]
Hello,

see this codepen:
https://codesandbox.io/s/fullcalendar-vue-cvdzo?file=/src/DemoApp.vue

When loading the events by pressing the button (this works also loading events f.e. by ajax), the template is not shown correctly. The calender show a standard event template.

    "@fullcalendar/core": "5.0.0-beta.4",
    "@fullcalendar/daygrid": "5.0.0-beta.4",
    "@fullcalendar/interaction": "5.0.0-beta.4",
    "@fullcalendar/list": "5.0.0-beta.4",
    "@fullcalendar/resource-timeline": "5.0.0-beta.4",
    "@fullcalendar/timegrid": "5.0.0-beta.4",
    "@fullcalendar/vue": "5.0.0-beta.4",

Thanks!
Martin

**Comment by gitmit1tbcopters** [comment]
External component Inside template slot eventContent faild vuex, I18n binding. 

```
methods:{
...mapactions("namespace",["action"]),

saveAction(){
   this.action()   // showing undefined 
.then(r=>{
console.log(this.$t("common.message.save")   //showing  _t is not recognized as error 
})
} 
}
```

**Comment by arshaw** [comment]
confirmed. example showing how the slot works correctly on first load but then gets ignored on second render: https://codesandbox.io/s/fullcalendar-vue-7pset

**Comment by arshaw** [comment]
This is fixed in the new [v5 release candidate](https://fullcalendar.io/blog/2020/06/v5-rc-new-features)

update repro: https://codesandbox.io/s/fullcalendar-vue-7pset?file=/src/DemoApp.vue
