### ISSUE TITLE
@acerix, timeZone option inside businessHours definition would work. Also, this is looks readable and is easy to understand.

### ISSUE THREAD

**Issue by Lekkimone92** [fullcalendar/fullcalendar#5484]
@acerix, timeZone option inside businessHours definition would work. Also, this is looks readable and is easy to understand.
```
...
businessHours: {
  daysOfWeek: [1, 2, 3, 4],
  startTime: '09:00',
  endTime: '17:00',
  timeZone: 'UTC'
},
timeZone: 'Europe/Paris',
...
```
The businessHours should be calculated by converting startTime and endTime for each day from businessHours.timeZone to calendar timeZone.

_Originally posted by @eggnukes in https://github.com/fullcalendar/fullcalendar/issues/5455#issuecomment-634465687_

**Comment by acerix** [comment]
I'm not sure why you opened a new ticket, that one is still open as a feature request.
https://github.com/fullcalendar/fullcalendar/issues/5455
↑
Please visit the above issue, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates.
