### ISSUE TITLE
timeZone setting doesn't update with setOption

### ISSUE THREAD

**Issue by Khanbhai1990** [fullcalendar/fullcalendar#5485]
Timzone change doesn't reflect on calendar in my react repo as well as the v5 demo in docs (link below)
https://fullcalendar.io/docs/v5/timeZone-demo

**Comment by acerix** [comment]
Thanks, confirmed.  The initial `timeZone` setting works but it doesn't update with `setOption`.

**Comment by justvovus** [comment]
@acerix From what I tested it was broken with beta-4.
In beta-3 I have dynamic timezone and firstDay switching, but with an upgrade it got broken.

**Comment by arshaw** [comment]
This is fixed in the new [v5 release candidate](https://fullcalendar.io/blog/2020/06/v5-rc-new-features)

The demo now correctly updates: https://fullcalendar.io/docs/v5/timeZone-demo

**Comment by justvovus** [comment]
@arshaw 5.0.0-rc has introduced a new error during react build
```
./node_modules/@fullcalendar/common/main.css
ParserError: Syntax Error at line: 1, column 45
```
