### ISSUE TITLE
have textColor affect titles of bg events

### ISSUE THREAD

**Issue by CraftyDlx** [fullcalendar/fullcalendar#5488]
```
events: [
{
    start: '2020-06-08',
    end: '2020-06-10',
    rendering: 'background'
 } ]
```
is working flawlessly, while
```
eventSources: [
{
    start: '2020-06-08',
    end: '2020-06-10',
    rendering: 'background'
 } ]
is not. Is this intentional? If so, how do I define background events (e.g. to mark holidays) with events in one calendar? Thanks.

**Comment by CraftyDlx** [comment]
Thanks for your reply. Yes, I need `rendering: 'background'` for a list of holidays in my country so that you can easily see what days are holidays and therefore avoid placing certain events on it. Is there any chance that this feature will find its way to Version 5 of FullCalendar? If not, is there a workaround to color whole days for a list of holidays?

**Comment by arshaw** [comment]
I'm not sure why it didn't work in v4, but with v5 it works:
https://codepen.io/arshaw/pen/BajQJaR?editors=0010

With v5, the display/eventDisplay properties are used.

I don't think we'll fix this in v4 unfortunately.

**Comment by CraftyDlx** [comment]
Okay, my app will be in production in about 12 weeks, is it safe to upgrade to v5 beta? I am only using 
```
plugins: [ 'interaction', 'resourceTimeline' ],
defaultView: 'resourceTimelineWeek',
```

**Comment by CraftyDlx** [comment]
@arshaw I think it's important: `textColor: 'black',` in your codepen [https://codepen.io/arshaw/pen/BajQJaR?editors=0010](https://codepen.io/arshaw/pen/BajQJaR?editors=0010) seems to have no effect. I tried various colors and also tried `eventTextColor` but everything looks light grey.

**Comment by arshaw** [comment]
right now the textColor intentionally does not affect the title text in a background event. But I'll leave this ticket open to discuss that decision

**Comment by arshaw** [comment]
in the meantime you could use custom CSS or attach CSS properties in the eventDidMount hook

**Comment by arshaw** [comment]
i see you created this other issue: https://github.com/fullcalendar/fullcalendar/issues/5528

**Comment by CraftyDlx** [comment]
>in the meantime you could use custom CSS or attach CSS properties in the eventDidMount hook

could you tell me what css rule has to be modified for the textcolor of bg events? i was not successful finding it.
