### ISSUE TITLE
Definitions of the following identifiers conflict with those in another file: SimpleDayGrid, DayGridSlicer

### ISSUE THREAD

**Issue by luciancaetano** [fullcalendar/fullcalendar#5489]
I am having problems with typescript definitions.

ERROR in [at-loader] ./node_modules/@fullcalendar/timegrid/node_modules/@fullcalendar/daygrid/main.d.ts:5:1 
    TS6200: Definitions of the following identifiers conflict with those in another file: SimpleDayGrid, DayGridSlicer, DayGrid, DayGridSeg, AbstractDayGridView, DayGridView, buildBasicDayTable, DayBgRow, _default, default, Popover, DayGridEventRenderer, DayTile, DayTileEventRenderer, SimpleDayGridEventRenderer

The problem occurs when I use "@ fullcalendar / daygrid" and "@ fullcalendar / timegrid" they conflict with the internal package

    "@fullcalendar/core": "^4.4.2",
    "@fullcalendar/daygrid": "^4.4.2",
    "@fullcalendar/interaction": "^4.4.2",
    "@fullcalendar/moment": "^4.4.2",
    "@fullcalendar/timegrid": "^4.4.2",

**Comment by acerix** [comment]
Would you be able to post a [runnable, stripped-down demonstration of the bug](http://fullcalendar.io/wiki/Reduced-Test-Cases/) or steps to reproduct the error? Would really appreciate it because the time saved reproducing will be time spent fixing.
