### ISSUE TITLE
Using setTimeout to get events to appear

### ISSUE THREAD

**Issue by danwillm** [fullcalendar/fullcalendar#5492]
Hello, 

I am currently trying to initialise the calendar with events.

When I do so, I get a blank calendar, with only the header showing, like so:

![image](https://user-images.githubusercontent.com/39023874/84565385-a7afbf80-ad60-11ea-92b6-b17e7a4d2c92.png)

This is the code that I am using to setup and render the calendar:

```
calendar = new Calendar(document.getElementById('calendar'), {
        plugins: [dayGridPlugin],
        events: [{
            title: 'Event1',
            start: '2020-06-13'
        },
            {
                title: 'Event2',
                start: '2020-06-15'
            }],
    });
    calendar.render();
```
I can get the events to show by going forward and then backward in the month, or doing a bit of a hack and adding a setTimeout to the `calendar.render()`:

```
calendar = new Calendar(document.getElementById('calendar'), {
        plugins: [dayGridPlugin],
        events: [{
            title: 'Event1',
            start: '2020-06-13'
        },
            {
                title: 'Event2',
                start: '2020-06-15'
            }],
    });
    window.setTimeout(function () {
        calendar.render();
    }, 500);
```

This works as intended, and shows the events, but I was wondering if there were cleaner approaches to fixing this, and if I'm missing something?

Thanks in advance.

**Comment by acerix** [comment]
Would you be able to post a [runnable, stripped-down demonstration of the bug](http://fullcalendar.io/wiki/Reduced-Test-Cases/)? Would really appreciate it because the time saved reproducing will be time spent fixing.
