### ISSUE TITLE
Dash between event start and end times is "undefined" with eventTimeFormat and moment plugin

### ISSUE THREAD

**Issue by blutorange** [fullcalendar/fullcalendar#5493]
### Bug Reports

Version: FullCalendar v5-beta.4

I'm looking into updating the Schedule component for PrimeFaces, which uses FullCalendar. While doing so, I came across a minor issue:

* FullCalendar with moment plugin
* Option `eventTimeFormat` set to some value such as `HH:mm:ss`
* An event with a start and end time in `timeGridDay` displays as `15:38:02undefined16:08:02` (the dash between the times is missing)

To Reproduce: https://codesandbox.io/s/jolly-brown-hwbvy?file=/src/DemoApp.vue (not specific to vue, also happens with a plain webpack build without a framework)

![image](https://user-images.githubusercontent.com/2456413/84571658-84026e80-ad8c-11ea-974c-2a36826267bc.png)

**Comment by acerix** [comment]
Thanks, confirmed.

**Comment by jefbarn** [comment]
Seeing the same on v5 final and Luxon plugin.

**Comment by blutorange** [comment]
Yeah, that definitely works. As far as I can tell, we already had to pass an object to eventTimeFormat even in v4. Though the moment plugin should add support for passing a moment date-time string instead.

**Comment by citylims** [comment]
Possibly Experiencing a similar issue when passing in ISO String dates (i've also tried moment 'YYYY/MM/DD hh:mm T') 
Start: 2020-06-25T17:31:00.000Z 
End: 2020-06-25T22:45:00.000Z

I'm still on version 3.10.1 so this could just be a mistake i've made somewhere that is unrelated

The event renders properly on the calendar, but the printed out datetime string on the event includes a bunch of undefined. 
Could this be a bug where fullcalendar is having issue dealing with printing out AM/PM?

<img width="607" alt="Screen Shot 2020-06-25 at 11 10 32 AM" src="https://user-images.githubusercontent.com/4462029/85775314-85a92c00-b6d4-11ea-89e9-a2176b79b484.png">

<img width="774" alt="Screen Shot 2020-06-25 at 11 04 24 AM" src="https://user-images.githubusercontent.com/4462029/85775382-96f23880-b6d4-11ea-9725-9e68349cf8fa.png">

Looks great if those undefined strings werent included.

**Comment by arshaw** [comment]
fixed in v5.1.0

https://codesandbox.io/s/old-wood-qxh91?file=/src/DemoApp.vue
