### ISSUE TITLE
resourceTimelineYear view doesn't positions view on current day

### ISSUE THREAD

**Issue by zazy** [fullcalendar/fullcalendar#5494]
Setting resourceTimelineYear as default view for the resourceTimeline plugin will not show current date on rendering but will position the view at january the 1st with few pixels of scroll. 
This will force user to scroll to current date every time page is loaded.
I used this code for bug demo:
```
var calendarEl = document.getElementById('test');
    var calendar = new FullCalendar.Calendar(calendarEl, {
      plugins: [ 'interaction', 'resourceTimeline' ],
      timeZone: 'UTC',
      defaultView: 'resourceTimelineYear',
      aspectRatio: 1.5,
      header: {
        left: 'prev,next',
        center: 'title',
        right: 'resourceTimelineDay,resourceTimelineWeek,resourceTimelineMonth'
      },
      editable: true,
      resourceLabelText: 'Rooms',
      resources: 'https://fullcalendar.io/demo-resources.json?with-nesting&with-colors',
      events: 'https://fullcalendar.io/demo-events.json?single-day&for-resource-timeline'
    });
    calendar.render();
});
```

Adding the Today button in the top header doesn't solve the problem: the button simply doesn't works and stays disabled. If you go to next year the Today button enables but clicking on it will bring you again to january the 1st of the current year. It seems that for this view "today" means "current year" and not "current day"

**Comment by acerix** [comment]
I believe this existing ticket captures this need:
https://github.com/fullcalendar/fullcalendar/issues/4806
↑
Please visit the above issue, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates.

**Comment by waleedismaeil** [comment]
scrollTime: Date.UTC(new Date().getFullYear(), new Date().getMonth(), new Date().getDate()) - Date.UTC(new Date().getFullYear(), 0, 0),
