### ISSUE TITLE
selectOverlap does not work when timeGrid and resourceTimeline plugins are initiated together

### ISSUE THREAD

**Issue by rwhol** [fullcalendar/fullcalendar#5495]
`selectOverlap: false` does not work for timeGrid view when both resourceTimeline and TimeGrid are initiated together. When both is initated, selectOverlap only affects resourceTimeline view.

If I remove resourceTimeline plugin, then selectOverlap works for timeGrid view.

**Comment by acerix** [comment]
Would you be able to post a [runnable, stripped-down demonstration of the bug](http://fullcalendar.io/wiki/Reduced-Test-Cases/)? Would really appreciate it because the time saved reproducing will be time spent fixing.
