### ISSUE TITLE
Set resource area column width to fit content

### ISSUE THREAD

**Issue by afarral** [fullcalendar/fullcalendar#5497]
is there an option to set the resource column name to the width of the largest content, as i get lots of whit space
![first column too wide](https://user-images.githubusercontent.com/22122585/84651815-71aa4100-af02-11ea-9455-c71203275161.png)

**Comment by CraftyDlx** [comment]
that's what i'm also looking for. for the time being you could use `resourceAreaWidth: '15%'`

**Comment by acerix** [comment]
It's not built-in, but you could set `resourceAreaWidth` in pixels based on the longest resource.

**Comment by afarral** [comment]
Thanks, I have sent a value, just for anyone else, i had an idea that might be good: could restrict the length of the resource name in the data, or abbreviate it, and then put the full text in a tooltip.
