### ISSUE TITLE
Event resizer icon doesn't show on hover

### ISSUE THREAD

**Issue by Fixoon** [fullcalendar/fullcalendar#5498]
The equal sign shown when hovering on an resizable event in versions previous to v5 doesn't show up in v5. I can't find anything about this in the changelogs or upgrade guide.

Example where it doesn't work:
https://fullcalendar.io/docs/v5/sticky-timegrid-demo

**Comment by acerix** [comment]
Thanks, confirmed.

**Comment by arshaw** [comment]
this has been removed intentionally but i will be publishing some code on the changelog for how to get back to the old behavior by writing some css. please see this:

https://codepen.io/arshaw/pen/YzwNNLb?editors=0110
