### ISSUE TITLE
v5.rc Event popover scroll issues with many events

### ISSUE THREAD

**Issue by yuan9090** [fullcalendar/fullcalendar#5499]
### Bug Reports
Hi @arshaw, thanks to fix #5471 . But it still have another popover scroll issue different then v4

see the gif and codePen

![6xe1b-4wm6s](https://user-images.githubusercontent.com/9431852/84761892-aef2f980-affc-11ea-92f0-7be64feed53d.gif)

v4 
https://codepen.io/yuan9090/pen/QWyKrKV

v5.rc
https://codepen.io/yuan9090/pen/BajBNVg

Thanks a lot !

**Comment by Sharvesh56** [comment]
@yuan9090  Hi there, did you managed to fix the scrollable popover thing in fullCalendar?

**Comment by k-sai-kiranmayee** [comment]
Hello all, I know this has been closed a while ago, but could anyone confirm that the popover is scrollable in iOS, please.
Have tried setting **height** and **max-height** and **overflow-y:auto/scroll/visible** and **-webkit-overflow-scrolling: touch** still it's not working. However, it is working fine on desktop and Android.

Could anyone help me with this one please

Thank you
