### ISSUE TITLE
Fullcalendar 5rc template field 'duration' not shown

### ISSUE THREAD

**Issue by martinfruehmorgen** [fullcalendar/fullcalendar#5500]
Hello,

using Fullcalendar Vue and having events with a field 'duration', this field is not displayed in the template.

See this codepen:
https://codesandbox.io/s/fullcalendar-vue-l9wlw

    "@fullcalendar/core": "5.0.0-rc",
    "@fullcalendar/daygrid": "5.0.0-rc",
    "@fullcalendar/interaction": "5.0.0-rc",
    "@fullcalendar/list": "5.0.0-rc",
    "@fullcalendar/resource-timeline": "5.0.0-rc",
    "@fullcalendar/timegrid": "5.0.0-rc",
    "@fullcalendar/vue": "5.0.0-rc"

Thanks!
Martin

**Comment by acerix** [comment]
There is no `duration` property for events, the duration is set by the end time.

**Comment by acerix** [comment]
There is no `duration` property for events, you could store that in an `extendedProp`: 

https://codesandbox.io/s/fullcalendar-vue-j8xt5?file=/src/DemoApp.vue
