### ISSUE TITLE
Bar disappears when dragging an event in Scheduler

### ISSUE THREAD

**Issue by Xander567** [fullcalendar/fullcalendar#5501]
Recently upgraded to jQuery 3.5.1 to cover a security vulnerability and have discovered that dragging events in the scheduler doesn't work properly. We have a full paid for license, but for the sake of the example, I've used the GPL license.

When I drag an event, during the drag the bar disappears. Once I drop it, it's moved successfully and reappears. 

https://codepen.io/xander567/pen/RwrGqWX?editable=true&editors=001%3Dhttps%3A%2F%2Ffullcalendar.io%2Freduced-test-cases

jQuery: 3.5.1
Fullcalendar: 3.10.2
Scheduler: 1.10.1

**Comment by acerix** [comment]
I don't believe the issue is from updating, the timeline view in v3 needs at least one resource for that to work:

https://codepen.io/acerix/pen/gOPLKbz?editors=001
