### ISSUE TITLE
processing css with postcss, calc/var problems

### ISSUE THREAD

**Issue by adenta** [fullcalendar/fullcalendar#5503]
I do not know where to best report this, but it needs to be documented somewhere.

I am using a pretty standard [webpacker](https://github.com/rails/webpacker) configuration to run my react app that uses Fullcalendar. After upgrading to the V5 release candidate, I encountered the following error: 
```
ERROR in ./node_modules/@fullcalendar/timegrid/main.css (./node_modules/css-loader/dist/cjs.js??ref--7-1!./node_modules/postcss-loader/src??ref--7-2!./node_modules/@fullcalendar/timegrid/main.css)
Module build failed (from ./node_modules/postcss-loader/src/index.js):
ParserError: Syntax Error at line: 1, column 45
    at /Users/andre/terusama/node_modules/@fullcalendar/timegrid/main.css:84:7
    at Parser.error (/Users/andre/terusama/node_modules/postcss-values-parser/lib/parser.js:127:11)
    at Parser.operator (/Users/andre/terusama/node_modules/postcss-values-parser/lib/parser.js:162:20)
    at Parser.parseTokens (/Users/andre/terusama/node_modules/postcss-values-parser/lib/parser.js:245:14)
    at Parser.loop (/Users/andre/terusama/node_modules/postcss-values-parser/lib/parser.js:132:12)
    at Parser.parse (/Users/andre/terusama/node_modules/postcss-values-parser/lib/parser.js:51:17)
    at parse (/Users/andre/terusama/node_modules/postcss-custom-properties/index.cjs.js:47:30)
    at /Users/andre/terusama/node_modules/postcss-custom-properties/index.cjs.js:333:24
    at /Users/andre/terusama/node_modules/postcss/lib/container.js:190:18
    at /Users/andre/terusama/node_modules/postcss/lib/container.js:135:18
    at Rule.each (/Users/andre/terusama/node_modules/postcss/lib/container.js:101:16)
```

I was incredibly confused as to what to do about this. I understand that the new version of fullcalendar required a css loader, but it was my understanding that _I was already doing this_.

I was able to get webpack(er) to compile successfully by removing all uses of `calc` in Fullcalendar css manually. This is not a real solution, however; so I had to keep digging.

I was able to resolve my issues, by changing my postcss configuration from :
```
module.exports = {
  plugins: [
    require('postcss-import'),
    require('postcss-flexbugs-fixes'),
    require('postcss-preset-env')({
      autoprefixer: {
        flexbox: 'no-2009'
      },
      stage: 3
    })
  ]
}
```

to 

```
module.exports = {
  plugins: [
    require('postcss-import'),
    require('postcss-flexbugs-fixes'),
    require('postcss-preset-env')({
      autoprefixer: {
        flexbox: 'no-2009'
      },
      stage: 4
    })
  ]
}
```

So what this seems to do is target how many polyfills postcss has to add to your app. Stage 0 is experimental, and stage 4 is stable. I do not 100% understand what exactly is being pollyfilled. `3` was the default that came with rails/webpacker.

Changing this to 4, magically solved my problems.

Again, this is probably not the right place to document this, however; this was frustrating, and I can guarantee other people upgrading full-calendar are going to run into the same issues.

**Comment by arshaw** [comment]
thanks @adenta, this could be a real concern. i want to get this figured out before the official release. it seems like it's something to do with either calc statements in general, calc statements with vars, or calc statements with vars that have fallback values. any way you could try various combinations of the three to see which one causes postcss-preset-env to choke?

**Comment by adenta** [comment]
I'm not an expert in CSS, so if you write out three independent tests for calc statements in general, calc statements with vars, or calc statements with vars that have fallback values, I'm happy to run them locally.

**Comment by arshaw** [comment]
cc @ericodom

thanks for offering to help out @adenta . here are the following cases i'd love to have tested. they can be put into your app's CSS in a standalone way, just for experimentation, and don't need fullcalendar.


var test:

```css
:root {
  --test-var: 10px;
}

body {
  margin: var(--test-var);
}
```

var with unused fallback:

```css
:root {
  --test-var: 10px;
}

body {
  margin: var(--test-var, 20px);
}
```

var with used fallback:

```css
body {
  margin: var(--test-var, 20px);
}
```

var in calc:

```css
:root {
  --test-var: 10px;
}

body {
  margin: calc(var(--test-var) / 2);
}
```

var in calc with unused fallback:

```css
:root {
  --test-var: 10px;
}

body {
  margin: calc(var(--test-var, 20px) / 2);
}
```

var in calc with unused fallback:

```css
body {
  margin: calc(var(--test-var, 20px) / 2);
}
```

**Comment by ericodom** [comment]
@arshaw Sure think!  Let me work on pulling those in and I'll let you know what I find.

**Comment by adenta** [comment]
@arshaw all of these tests failed in the default rails configuration (stage: 3, not 4)

And I gotta say, I don't think this is really a release candidate. I've spent the past 24 hours trying to get my app migrated over and ran into quite a few other problems: 
  - resizing the width does not seem to work. When shrinking the calendar, and reopening it, it stays small. Closing it again cuts some content off: https://imgur.com/a/r8mCirz
  - cant customize button color (not background, color). I also cant seem to customize hover/focus/active color as well.
  - bootstrap theme completely broken
  - latest release (react) the scheduler key still does not work. I know there was an issue for this. I know it was marked as fixed, but it does not work in the RC.

**Comment by arshaw** [comment]
@adenta, we'll approach each problem individually and maybe I'll have to adjust my strategy about the release candidate.

I reopened #5462, asking for a repro. I've created #5507 for the width problem. Can you please post the issue about the buttons and the bootstrap theme as separate issues with [reproducible test case](https://fullcalendar.io/reduced-test-cases)?

**Comment by arshaw** [comment]
also, @adenta, you're saying that even this simple test case is failing?:

```css
:root {
  --test-var: 10px;
}

body {
  margin: var(--test-var);
}
```

It seems like your setup has `postcss-custom-properties` installed. It's very strange that that plugin wouldn't handle the simplest possible case for a `var` statement. That's the whole point of the plugin. Are you sure you're testing my snippets in true isolation? Did you remove any fullcalendar-related code first?

**Comment by adenta** [comment]
I did not remove fullcalendar related code first. I do have `postcss-custom-properties` installed.

The issue lies with `postcss-preset-env`, not `postcss-custom-properties`, right?

**Comment by ericodom** [comment]
@arshaw I just finished up the individual tests you sent over, that all PASSED.  I did remove all references to the full-calendar stuff in my stripped down project prior to testing.

Just to make sure I set it up correctly, I did paste in the main.css into my test style sheet, to make sure WebPack was picking it up my test file correctly in the pre-compiler, and it did FAIL (which was expected).

FYI, I'm currently running a hack in my development environment, so I can test the components.  I basically just copied the css files into a static css, and clear the contents of the main.css files in the node_modules folder.  This works for me, and I'm making good progress with my conversion efforts in my React application.

**Comment by ericodom** [comment]
@arshaw I just got a message back from the developer of the theme, and it looks like he has isolated the issue.  It seems to be related to and IE11 setting in the package.json browserlist.  Once I removed the IE11 check...reinstall full-calendar, everything works like it supposed to.  

If you care about re-working your CSS so the IE11 setting will pass compilation, I'm happy to continue testing if you want me to...otherwise, I'm moving onto other things.

Thanks again for your attention...


![Support_-__2482_-_Full_Calendar_v5_0_Support](https://user-images.githubusercontent.com/4078602/84952194-7ad41300-b0a6-11ea-9048-5dc4fcb853d5.jpg)

**Comment by arshaw** [comment]
I see what the problem is. My calc statements, some of which were being generated by one of my custom-built postcss plugins, didn't always have whitespace around the operators.

Example: https://codepen.io/arshaw/pen/pogNKPo?editors=0100

See https://developer.mozilla.org/en-US/docs/Web/CSS/calc
"The + and - operators must be **surrounded by whitespace.**"

I guess some build environments were handling this and some others, like postcss-preset-env, were not.

I'll ensure these have whitespace and that'll fix the problem.

**Comment by ericodom** [comment]
Sounds good...I'll be happy to add the IE11 flag back in and re-test once you've resolved the CSS on your side...just to check off this edge case for other people (I don't plan on supporting IE11 anyways, so I was just going to remove the flag).

**Comment by arshaw** [comment]
this has been fixed and v5 has been [officially released](https://fullcalendar.io/blog/2020/06/v5-official)

**Comment by roselily8** [comment]
Hi, I am still having the same issue. I have installed fullcalendar v5.5.0 and I am using nuxt. Upon checking, 
@fullcalendar/timegrid/main.css:94:7
and 
@fullcalendar/common/main.css:638:3
still do not have white space around operators, which resulted in syntax error with postcss. Can you please check? Thx.

**Comment by roselily8** [comment]
The syntax error occurs only when I run nuxt generate.

**Comment by melokki** [comment]
I am getting the same error on `npm run build` command
I am usng nuxt 2.15.3 with postcss8 and I am guessing postcss8 could cause this fr some reasons

```
ERROR in ./node_modules/@fullcalendar/common/main.css (./node_modules/@nuxt/postcss8/node_modules/css-loader/dist/cjs.js??ref--3-oneOf-1-1!./node_modules/@nuxt/postcss8/node_modules/postcss-loader/dist/cjs.js??ref--3-oneOf-1-2!./node_modules/@fullcalendar/common/main.css)
Module build failed (from ./node_modules/@nuxt/postcss8/node_modules/postcss-loader/dist/cjs.js):
```

**Comment by anujchhabria1** [comment]
@Roselily8 were you able to find a work around?

**Comment by 1forh** [comment]
I'm getting the same exact error as @melokki.

Nuxt: `12.15.5`
Fullcalendar: `5.4.0`

```
ERROR in ./node_modules/@fullcalendar/common/main.css (./node_modules/@nuxt/postcss8/node_modules/css-loader/dist/cjs.js??ref--3-oneOf-1-1!./node_modules/@nuxt/postcss8/node_modules/postcss-loader/dist/cjs.js??ref--3-oneOf-1-2!./node_modules/@fullcalendar/common/main.css)
Module build failed (from ./node_modules/@nuxt/postcss8/node_modules/postcss-loader/dist/cjs.js):
```

**Comment by mlazuardy-dyned** [comment]
@andreluizbnu  @1forh @melokki 

I guess i fixed the issue by adding css nano plugin config inside `nuxt.config.js`

```
build: {
        transpile: /@fullcalendar.*/,
        postcss: {
            plugins: {
                'cssnano': {
                    preset: [
                        "default",
                        {
                            "calc": false
                        }
                    ]
                }
            }
        }
    },
```

**Comment by ctwhome** [comment]
@mlazuardy-dyned just saved my day!

I used your code without the transpile option:

```
build: {
        postcss: {
            plugins: {
                'cssnano': {
                    preset: [
                        "default",
                        {
                            "calc": false
                        }
                    ]
                }
            }
        }
    },
```

**Comment by rganeyev** [comment]
I also faced that issue with calc and negative numbers, By bisecting the styles I found where the bug happens in `common/main.css`.

Please review:
https://github.com/fullcalendar/fullcalendar/pull/6563
