### ISSUE TITLE
v5 rc typescript events-json-feed method doesn't works

### ISSUE THREAD

**Issue by genyslt** [fullcalendar/fullcalendar#5505]
I trying to set events remote from URL with method POST:

```
let calendar = new Calendar(el, {
            events:  {
                url: "json.php",
                method: "POST",
                failure: function() {

                },
                extraParams: function () {
                   return me.filter;
                }
            },
...
```
And get type error:

![image](https://user-images.githubusercontent.com/12429511/84898948-b07df980-b0b0-11ea-9a87-dd66e2239f5f.png)

Also, if ir remove method, i get same error at extraParams function

I use examples from Documentation:

https://fullcalendar.io/docs/v5/events-json-feed

**Comment by arshaw** [comment]
confirmed. this is a problem with the way the types are exported in the common module. will have this fixed for the official release. in the meantime you can cast the whole object to `{} any` as a workaround

**Comment by genyslt** [comment]
Not nice, but workaround works fine

**Comment by arshaw** [comment]
this is fixed in the [official v5](https://fullcalendar.io/blog/2020/06/v5-official)

could you please verify @genyslt ?

**Comment by genyslt** [comment]
Yes. This is fixed in official v5 release. You can close this ticket. Thank you.
