### ISSUE TITLE
updated v5 docs for bootstrap

### ISSUE THREAD

**Issue by adenta** [fullcalendar/fullcalendar#5508]
https://codesandbox.io/s/sharp-archimedes-c61ik?file=/src/DemoApp.jsx

**Comment by arshaw** [comment]
It doesn't look like you are including bootstrap's styles yourself. That's required. See https://fullcalendar.io/docs/v5/bootstrap-theme

**Comment by arshaw** [comment]
apologies for that article not being up to sync with v5, but my answer still stands, you need to import your own bootstrap stylesheet

**Comment by adenta** [comment]
Just to confirm: `https://fullcalendar.io/docs/v5/upgrading-from-v4` is inaccurate. You _Still_ need to reimport the styles manually? I'm confused.

```
In v4, it was your responsibility to import all of fullcalendar’s stylesheets. You may have done this in one your project’s SASS files. Or, if you had a build system that handled CSS, you may have done this from your JavaScript.

In v5, you no longer need to do this! The plugins will import their own stylesheets. So, you’ll be able remove lines like these:

import { Calendar } from '@fullcalendar/core'
import timeGridPlugin from '@fullcalendar/timegrid'

// DON'T DO THIS ANYMORE! it will happen automatically
// import '@fullcalendar/core/main.css';
// import '@fullcalendar/daygrid/main.css'; // a dependency of timegrid
// import '@fullcalendar/timegrid/main.css';

let calendar = new Calendar(calendarEl, {
  plugins: [ timeGridPlugin ]
  // other options...
})
```

**Comment by arshaw** [comment]
FullCalendar will import its OWN stylesheets, but it will not import the Bootstrap project's stylesheets.

So, you must still import a stylesheet like this. It won't automatically happen:
https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css

FullCalendar is designed this way in order to allow authors to import different bootstrap distros with different bootstrap themes.

Does that make sense?

Again, I will clear this up in the next revision of the docs.

**Comment by adenta** [comment]
Absolutely. 

I was using the bootstrap theme in FC4, however; not actually using bootstrap I guess. I thought it looked nicer than the default stylesheet, thats where this confusion is coming from. In FC4, everything still looked presentable, but it was misconfigured.

**Comment by arshaw** [comment]
i updated the docs: https://fullcalendar.io/docs/bootstrap-theme

also updated various other places that references completely automatic css
