### ISSUE TITLE
Is HiddenDay undefined error -- V5 RC React

### ISSUE THREAD

**Issue by Khanbhai1990** [fullcalendar/fullcalendar#5510]
Not sure whats causing this error. I updated from V5 beta.4
<img width="1661" alt="Screen .Shot 2020-06-17 at 2 05 57 PM" src="https://user-images.githubusercontent.com/29368029/84951479-575c9880-b0a5-11ea-9b8c-cd98b863a671.png">

**Comment by acerix** [comment]
Would you be able to post a [runnable, stripped-down demonstration of the bug](http://fullcalendar.io/wiki/Reduced-Test-Cases/)? Would really appreciate it because the time saved reproducing will be time spent fixing.
