### ISSUE TITLE
Event popover position

### ISSUE THREAD

**Issue by negberts** [fullcalendar/fullcalendar#5512]
This issue (https://github.com/fullcalendar/fullcalendar/issues/2743) has occured before but was closed and for us it's really wanted.

I would be happy to have a setting where the popover can be positioned statically or at least be completely visible directly.

We have 12 events as limit:

![image](https://user-images.githubusercontent.com/20299260/84365407-aef49300-abd1-11ea-8e09-e4ea301a5642.png)

But when the popover opens the top of the popover is probably centered somewhere near item 6 instead of being completely visible

![image](https://user-images.githubusercontent.com/20299260/84365500-d8adba00-abd1-11ea-805d-dcf6f8b3d1b7.png)

The top position is rendered as something like -222px. It would be nicer if this was just 0.

**Comment by negberts** [comment]
We've fixed it by overriding the css with top 0 for .fc-more-popover

**Comment by SakshiTiwari28** [comment]
> We've fixed it by overriding the css with top 0 for .fc-more-popover

@negberts this solution doesn't work for all the cell in the calendar, it detaches the popover to top and doesn't look consistent.
Please provide solution for this.

**Comment by negberts** [comment]
@SakshiTiwari28 maybe you should create an issue of your own?
