### ISSUE TITLE
Event rendering cannot be cancelled from eventContent

### ISSUE THREAD

**Issue by acerix** [fullcalendar/fullcalendar#5515]
Reported in https://fullcalendar.freshdesk.com/a/tickets/1936

The v5 migration doc mentions a replacement for returning `false` from `eventRender` is to "attach a display:'none' property on the Event Input" from `eventContent` but that seems to have no effect.

https://codepen.io/acerix/pen/KKVaMXa?editors=001

https://fullcalendar.io/docs/v5/upgrading-from-v4#event-rendering

**Comment by arshaw** [comment]
I'll clear up the docs. What I meant from the docs is that if you already have a `display` property on your event object set to `'none'`, **before** eventContent is called, then it won't display.

When eventContent is executing, it's already too late.

You'll need to do it imperatively at the time the user indicates what they wan't filtered out. Here's an example:

https://codepen.io/arshaw/pen/oNbBLKr?editors=0010

```js
event.setProp('display', 'none')
```

**Comment by balexandre** [comment]
just to note that in the example from @arshaw we can't toggle the event back ... 

the idea is that, just as I mentioned in [StackOverflow](https://stackoverflow.com/q/62321792/28004), was to **after we received all events**, a way to **toggle them** to one can visually filter a certain type or types of events and by that, remove all resources that by the given time gap, have no such events (like the `filterResourcesWithEvents` property currently does)

**Comment by arshaw** [comment]
@balexandre it should be possible to toggle them back if you do `event.setProp('display', 'auto')`

https://fullcalendar.io/docs/eventDisplay

https://codepen.io/arshaw/pen/oNbBLKr?editors=0010

**Comment by conor909** [comment]
I'm not seeing any `display` property on my event objects.  Even if I manually add one to my raw json objects before they get added as a calendar event.  Other properties such a `textColor` & `renderer` are working.

**Comment by balexandre** [comment]
@arshaw tried that before and worked nicely ...

I just wonder why won't `calendar.setOption('filterResourcesWithEvents', true)` work correctly, and hide Auditorium A and C, not only D...

as there's no events showing, shouldn't that take care of the visualization? is there a hidden property I can use for this effect?

https://codepen.io/balexandre/pen/jOWBoYX?editors=0010

**Comment by arshaw** [comment]
@balexandre , I understand. The `filterResourcesWithEvents` disregards any rendering-related properties like `display`. I should have foreseen that.

I'm realizing that the `display` property won't lead you to a good approach. Let me describe an approach that works better...

Try using [eventDataTransform](https://fullcalendar.io/docs/eventDataTransform) and then return false if the event doesn't match the search criteria. When the search criteria is activated, call [refetchEvents](https://fullcalendar.io/docs/Calendar-refetchEvents) and also set `filterResourcesWithEvents` to `true`

**Comment by balexandre** [comment]
@arshaw taking your suggestion into code ...

for some reason, the `calendar.refetchEvents()` is not called

https://codepen.io/balexandre/pen/jOWBoYX?editors=0011 (js and css upgraded to final v5)

**Comment by arshaw** [comment]
apologies, that won't work either because an array event source is not considered 'refetchable' because it's a static source.

Move our filtering logic "up a level" to an events function will work. Please see what I did here:
https://codepen.io/arshaw/pen/KKVmVKa?editors=0010

Does that work for you?

**Comment by balexandre** [comment]
this was actually my initial approach, caching all events and filtering them upon selection ... but somehow I was calling `calendar.refetchResources()` instead 🤦‍♂️

was a fun topic to see a little bit more about how the fullCalendar internally works and opens up a whole lot of new ideas to develop upon 😄

thank you a bunch @arshaw for all the help and congrats on the official release of the new version, I hope I can contribute with future insights!

**Comment by arshaw** [comment]
Thanks for your patience with all the incorrect approaches. Good luck!!!
