### ISSUE TITLE
Indicate which row (or format) is being rendered in slotLabelContent

### ISSUE THREAD

**Issue by acerix** [fullcalendar/fullcalendar#5516]
Reported in https://fullcalendar.freshdesk.com/a/tickets/1936

For timeline views with multiple rows of slot labels, `slotLabelContent` should indicate which row is being rendered to allow different rendering for each row (date format).  

https://codepen.io/acerix/pen/dyGNXjL?editors=0010

**Comment by arshaw** [comment]
In the single argument, we should probably include the row index and maybe even the date formatting config

**Comment by arshaw** [comment]
please see the `level` property mentioned in this article https://fullcalendar.io/docs/slot-render-hooks

@acerix could you please notify the customer?
