### ISSUE TITLE
Events with text color 'white' can not be seen in listMonth view (V5 RC1)

### ISSUE THREAD

**Issue by Endition** [fullcalendar/fullcalendar#5518]
If an event has text color 'white' and the selected view is 'listMonth', the user is unable to see the event title because background and text color are both white.

Test Case: Use your standard test case
https://codepen.io/pen/?&editable=true&editors=001=https%3A%2F%2Ffullcalendar.io%2Freduced-test-cases

Change: initialView to 'listMonth' and add textColor 'white' for one or two events
Result: The user is unable to see the event title because background and text color are both white.

**Comment by arshaw** [comment]
fixed in the [official v5 release](https://fullcalendar.io/blog/2020/06/v5-official). could you please verify? (I wasn't able to run your codepen link)

**Comment by Endition** [comment]
Thank you. Bug fixed
