### ISSUE TITLE
unable to set daygrid TableListItemEvent dot color

### ISSUE THREAD

**Issue by fhessenberger** [fullcalendar/fullcalendar#5522]
TableListItemEvent dot color can't be set

https://codepen.io/felix-scale/pen/gOPmxPa?editable=true&editors=001

PR: #5521

**Comment by arshaw** [comment]
merged and released in the [official v5](https://fullcalendar.io/blog/2020/06/v5-official), thanks so much

**Comment by arshaw** [comment]
https://codepen.io/arshaw/pen/YzwZvyp?editable=true&editors=001

**Comment by arshaw** [comment]
FYI, the text color has been purposely made immutable per https://github.com/fullcalendar/fullcalendar/issues/5518
