### ISSUE TITLE
Fullcalendar v5 - migration issues

### ISSUE THREAD

**Issue by kamilchlebek** [fullcalendar/fullcalendar#5527]
Hello, firstly many thanks for your amazing library! I can't wait to check the new print feature - we had many cross browser issues with it. 

I'm trying to migrate our project to fullcalendar v5. 

While doing this I had few issues listed below:

#### Undocumented breaking changes (missing in migration doc)
- `Calendar.mutateOptions` - not present in v5

#### Including fullcalendar css in angular (without using fullcalendar-angular)

As it turned out I still need to include css manually into my project. Importing css from JS files seems not supported.
(workaround that works for me)
```
@import '~@fullcalendar/common/main.css';
@import '~@fullcalendar/list/main.css';
@import '~@fullcalendar/daygrid/main.css';
@import '~@fullcalendar/timegrid/main.css';
```

#### Forcing FC to be imported in right order

While working on it, I encountered error:
> Please import the top-level fullcalendar lib before attempting to import a plugin

I managed to fix it by removing `import @fullcalendar/list` from one of my angular services. I'm not sure yet, but I may need to import it in future. Anyway forcing library to be imported in "correct" order seems like bad idea.

#### Types that I've previously used are no longer exported

I have service that creates custom event sources. It returns an object that looks like that:
```
{
  id: string
  events: EventSourceFunc
}
```

The problem is that I can't use `EventSourceFunc` because it's not exported.

**Comment by arshaw** [comment]
`Calendar.mutateOptions` was never meant to be publicly exposed or documented, so I don't consider it a breaking change.

For the angular CSS importing issue you brought up, could you post a separate issue with a [reduced test case](https://fullcalendar.io/reduced-test-cases)?

For the import order issue, are you following the directions [here](https://fullcalendar.io/docs/angular)? Especially the `registerPlugin` part? Doing things that way will ensure an import order.

I've made a separate issue for the EventSourceFunc import: https://github.com/fullcalendar/fullcalendar/issues/5530

going forward, can you post things as separate issues?

**Comment by kamilchlebek** [comment]
Thanks for response. 

> Calendar.mutateOptions was never meant to be publicly exposed or documented, so I don't consider it a breaking change.

Since it was public in v4 ( https://github.com/fullcalendar/fullcalendar/blob/v4/packages/core/src/Calendar.ts#L504 ) I considered it as exposed API. Anyway it's not a big issue.

> For the angular CSS importing issue you brought up, could you post a separate issue with a reduced test case? 
 
Sure, I'll do it tomorrow.

> For the import order issue, are you following the directions here? Especially the registerPlugin part? Doing things that way will ensure an import order. 

I'm not using `fullcalendar-angular`. I have my own fullcalendar wrapper inside project. We started using FC in angular before it was convenient to use` fullcalendar-angular` for us. 
You probably had some reasons behind to enforce import in correct order, but from library user perspective it would be better to execute some `calendar.bootstrap` method, instead of relying on import side effects. 

I'd need to check it, but it may be true (correct me if I'm wrong) that user event handlers (click/hover etc.) coming from code that was executed immediately while importing, will trigger angular change detection. Additionally there is no way to run it using "ngZone.runOutsideAngular"

> I've made a separate issue for the EventSourceFunc import: #5530

Great, thanks

> going forward, can you post things as separate issues?

:+1: sure, I didn't want to pollute repo with things that could turn into discussion or be irrelevant

**Comment by arshaw** [comment]
yeah, i guess `mutateOptions` was public in the source, but I never documented it because I wanted people using `setOption` instead

no worries

i'm going to create a separate ticket for discussing the import-order issue
