### ISSUE TITLE
eventContent snippet contains reference to deleted EventApi `rendering` property

### ISSUE THREAD

**Issue by kamilchlebek** [fullcalendar/fullcalendar#5538]
Affected page: https://fullcalendar.io/docs/upgrading-from-v4#event-rendering

Section `background events` under `Event Rendering` contains code snippet:
```
eventContent: function(arg) {
  if (arg.event.rendering.match(/background/)) { // handles inverse-background too
    return null
  }
}
```

`arg.event.rendering` doesn't exist in v5. It should be `arg.event.display`

**Comment by acerix** [comment]
Thanks, confirmed.

**Comment by arshaw** [comment]
fixed. https://fullcalendar.io/docs/upgrading-from-v4#event-rendering

thanks!
