### ISSUE TITLE
Event time format has `undefined` separator when using moment plugin

### ISSUE THREAD

**Issue by kamilchlebek** [fullcalendar/fullcalendar#5539]
#### Description

After adding `momentPlugin` and setting `eventTimeFormat` to `HH:mm` event is displayed as `13:30undefined14:30`.

#### Demo

https://stackblitz.com/edit/fullcalendar-timeformat

#### Cause (?)

I think it's happening because refiner linked to `eventTimeFormat` has two parameters:
https://github.com/fullcalendar/fullcalendar/blob/79ef85decae65a4521447e6a961891da0009fd54/packages/common/src/datelib/formatting.ts#L11

It's executed here, but there's just one argument passed to that function: 
https://github.com/fullcalendar/fullcalendar/blob/257872cd6d8f6d73d5d379be70071520b2b4ce83/packages/common/src/reducers/CalendarDataManager.ts#L436

**Comment by acerix** [comment]
I believe this existing ticket captures this need:
https://github.com/fullcalendar/fullcalendar/issues/5493
↑
Please visit the above issue, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates.
