### ISSUE TITLE
Month/Year Dropdown

### ISSUE THREAD

**Issue by arshaw** [fullcalendar/fullcalendar#554]
Originally reported on Google Code with ID 283

```
It would be helpful if the Month and the year in the header were drop down
menus so that you could quickly jump to the desired date.

```

Reported by `WhoButSB` on 2010-01-12 13:34:03

**Comment by sudarshan13** [comment]
can anybody provide fiddle, plunker or codepen for the demo of month and year dropdown for new release 2.7?

**Comment by nancycg** [comment]
please provide the solution for it
