### ISSUE TITLE
Inconsistency between the timeline and schedule grid

### ISSUE THREAD

**Issue by apoklyak** [fullcalendar/fullcalendar#5541]
Hello!

It seems that in your release v5.0.0 you've introduced a new bug where there is now an inconsistency between the timeline and schedule grid.

See https://i.gyazo.com/ae88d1e1ac52c5c11205235f9d5f6c3c.png

**Comment by acerix** [comment]
Would you be able to post a [runnable, stripped-down demonstration of the bug](http://fullcalendar.io/wiki/Reduced-Test-Cases/)? Would really appreciate it because the time saved reproducing will be time spent fixing.
