### ISSUE TITLE
Resource rows are initially squished in Chome in timeline view with contentHeight: "auto" and JSON resources 

### ISSUE THREAD

**Issue by lehovec** [fullcalendar/fullcalendar#5545]
When `contentHeight: "auto"` options are set for a calendar with Timeline view and JSON feed event source, the event area is incorrectly rendered (the area is squished). After some time (usually 5-10 seconds), the view switches to the correct size. Only Google Chrome has this problem (I have Chrome 81.0.4044.129), in Firefox it works fine. Calling `calendar.setOption('contentHeight', 'auto');` in console fix problem. (I tried to call `calendar.updateSize()` with no success). There is codepen with the problem:

https://codepen.io/bluewizard/full/mdVwjPq

**Comment by acerix** [comment]
Thanks, confirmed.  

It seems the issue is only when resources are provided by JSON, so as a workaround you could supply the resources "as a function" then something like `setOption('contentHeight', 'auto')` at the end of that function to fix the size.

**Comment by arshaw** [comment]
fixed in v5.1.0

https://codepen.io/arshaw/pen/zYrEoJM?editors=0010
