### ISSUE TITLE
Cannot set custom bootstrap font awesome icons because ButtonIconsInput type does not allow unknown properties

### ISSUE THREAD

**Issue by efcoyote** [fullcalendar/fullcalendar#5548]
### Bug Reports
Due the type save setting of the options via CalendarOptions, you are not able to configure a custom button with a font awesome icon.

I insert a custom icon in the header toolbar with no text but an icon.

**Working example without Angular**
1. Edit https://fullcalendar.io/docs/bootstrap-theme-demo in CodePen
2. Replace
```
headerToolbar: {
  left: 'prev,next today',
  center: 'title',
  right: 'dayGridMonth,timeGridWeek,timeGridDay,listMonth'
},
```
 by
```
headerToolbar: {
  left: 'prev,redo,next today',
  center: 'title',
  right: 'dayGridMonth,timeGridWeek,timeGridDay,listMonth'
},
bootstrapFontAwesome: { redo: 'redo' },
customButtons: { redo: { click: () => console.log('redo') } },
```

You see an additional button between prev and next and no error.

**Type error example with Angular**
1. Open https://codesandbox.io/s/unruffled-solomon-mvfc1?file=/src/app/app.component.ts
2. Wait a moment until parsing is completed

You will see a type error in `bootstrapFontAwesome: { redo: 'redo' },`

**Comment by arshaw** [comment]
fixed in v5.1.0
