### ISSUE TITLE
Events get displaced due to incorrect collisions detected depending on browser, zoom level

### ISSUE THREAD

**Issue by acerix** [fullcalendar/fullcalendar#5549]
https://codepen.io/pixel9/pen/KKVqJQR

All events should be in the first row since they don't actually overlap, but the 11am one shows below the rest on firefox.  Chrome displays them inconsistenly for different zoom levels.

![Screenshot from 2020-06-25 18-53-21](https://user-images.githubusercontent.com/379534/85803558-6b437280-b715-11ea-913b-5d5946b71d50.png)

Reported in https://fullcalendar.freshdesk.com/a/tickets/1954

**Comment by arshaw** [comment]
fixed in v5.1.0

https://codepen.io/arshaw/full/VweMmGw

@acerix , could you notify the customer on the freshdesk ticket?

**Comment by pixel9** [comment]
@arshaw @acerix No need to notify :) Thanks for the quick turnaround!

A confirmation of the initial bug report would have been very helpful though. I'm sure you're all swamped with the new release and it's been a smooth ride so far with your well documented upgrade guide. I appreciate everything you guys do to continuously improve this wonderful library!
