### ISSUE TITLE
Bug Scheduler v5: dates in WeekView (or any other duration) wrong

### ISSUE THREAD

**Issue by girizano** [fullcalendar/fullcalendar#5551]
https://jsfiddle.net/wux0gb7L/

If you use a week (or 12 days, or whatever), every date is repeated a month-lenght. Try "Semana" for week, or "12 días " for 12 days.

**Comment by acerix** [comment]
The issue is that with those views, each time slot is 1 hour, so if the label is just the day of the month, the same label is repeated for every hour in the day.  You could change the `slotDuration` to 1 day or change the labels to show the hours:

https://jsfiddle.net/dhtg76mf/

**Comment by girizano** [comment]
Dear Dylan, thank you very much for your reply. More or less around the
same time you answered, I found exactly the same solution myself. I
apologize for my silly question, it was not a bug, just a feature. You
know, your beautiful beast can be overwhelming at first. Maybe some extra
documentation, if you can spare the time, would help. Anyway, congrats on a
beautiful product.

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Libre
de virus. www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>
