### ISSUE TITLE
css variables in v-event.css

### ISSUE THREAD

**Issue by nick-milner** [fullcalendar/fullcalendar#5552]
Attempting to override time view vertical event background-color css variables from 
https://github.com/fullcalendar/fullcalendar/blob/master/packages/timegrid/src/styles/v-event.css

Am i mistaken but aren't these two variables the wrong way around  ?

border: 1px solid var(--fc-event-bg-color);
background-color: var(--fc-event-border-color);

ie background-color is using --fc-event-border-color variable,  and border is using --fc-event-bg-color

**Comment by arshaw** [comment]
you're right. it won't have any negative effects in the default configuration because both colors are the same by default, but might be bad when customized. i'll fix

**Comment by nick-milner** [comment]
Great, thanks! Top work on v5 btw 😀

**Comment by arshaw** [comment]
fixed in v5.1.0

**Comment by nick-milner** [comment]
just one more too i think ?

https://github.com/fullcalendar/fullcalendar/blob/7a73577a78be1dc5941e58c49c740c2b0d161a90/packages/common/src/styles/h-event.css

**Comment by arshaw** [comment]
yes, thanks @nick-milner

**Comment by arshaw** [comment]
fixed in 5.2.0
https://github.com/fullcalendar/fullcalendar/blob/v5.2.0/packages/common/src/styles/h-event.css#L8
