### ISSUE TITLE
More link not showing

### ISSUE THREAD

**Issue by JavedBoqo** [fullcalendar/fullcalendar#5554]
### Bug Reports
Hi, I am using FullCalendar v2.2.5. My problem is that when I zoom browser then "+More " link is not showing if events are more than the height of cell. Please find the attached screenshot

`$('#calendar').fullCalendar(
  {
    defaultDate:date,
    editable:false,
    eventLimit:true,
    eventSources:[events],
    eventStartEditable:false,
    fixedWeekCount:false,
    eventClick:function(event)
    {
      if(event.url)
      {
        var win=window.open(event.url,'_blank');
        win.focus();
        return false;
      }
    }
  });`

[https://paste.pics/57aa7fa5d4c775b18a8eec54c509fe27](url)

**Comment by acerix** [comment]
I believe it may be the same as this issue which was fixed in v5:

https://github.com/fullcalendar/fullcalendar/issues/5359

Please post a [runnable, stripped-down demonstration of the bug](http://fullcalendar.io/wiki/Reduced-Test-Cases/) if there is still an issue.

**Comment by JavedBoqo** [comment]
Thanks @acerix  for replying. 
Let me check above mentioned thread and let you know if I will face same issue
