### ISSUE TITLE
textColor not working with eventSources using Timeline View (5.1.0)

### ISSUE THREAD

**Issue by CraftyDlx** [fullcalendar/fullcalendar#5555]
Here's a minimal 5.1.0 example using `resourceTimeline` where I can't get `textColor` to work:
https://codepen.io/craftydlx/pen/yLeXKKL

**Comment by acerix** [comment]
I reopned your previous report:

https://github.com/fullcalendar/fullcalendar/issues/5528
↑
Please visit the above issue, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates.
