### ISSUE TITLE
background events don't fire eventClick when clicked on day header

### ISSUE THREAD

**Issue by arshaw** [fullcalendar/fullcalendar#5560]
try clicking the date headers: https://codepen.io/arshaw/pen/VweMByK?editable=true&editors=001

**Comment by bfwg** [comment]
The `eventMouseEnter`, `eventMouseLeave` and `eventClick` stopped working for background events. I'm using fullcalendar/angular and they used to work in v4. @arshaw any ideas?

**Comment by arshaw** [comment]
@bfwg , can you please file as a separate ticket, with a runnable reproduction?

**Comment by bfwg** [comment]
Thanks for the quick response. I want to make sure that this is an issue before creating it. 
What I did was taking your codepen example and change one of the events to 
```
      {
        start: '2020-05-02T15:00',
        end: '2020-05-02T15:00',
        overlap: false,
        display: 'background'
      },
```
Follow by changing the calendar to the week view. Clicking on the background time slot won't trigger the click event.
Am I missing something or this is a valid problem.

**Comment by arshaw** [comment]
it sounds like it could be a real problem. yes, please go ahead and file a new ticket

**Comment by arshaw** [comment]
fixed: https://codepen.io/arshaw/pen/VweMByK?editable=true&editors=001
