### ISSUE TITLE
Attempted import error: 'isElVisible' is not exported from '@fullcalendar/common'.

### ISSUE THREAD

**Issue by harryy2510** [fullcalendar/fullcalendar#5563]
### Bug Reports

Getting error during build time
`Attempted import error: 'isElVisible' is not exported from '@fullcalendar/common'.`

Project created via CRA
All dependencies of fullcalendar have version `5.1.0`

![image](https://user-images.githubusercontent.com/7416971/86095077-0b5f1a00-bacf-11ea-9577-614f4bbb8740.png)

**Comment by acerix** [comment]
Would you be able to post a [runnable, stripped-down demonstration of the bug](http://fullcalendar.io/wiki/Reduced-Test-Cases/) or steps sto reproduce the error? Would really appreciate it because the time saved reproducing will be time spent fixing.
