### ISSUE TITLE
Google Calendar gives "Invalid Credentials" error

### ISSUE THREAD

**Issue by ErwanJes** [fullcalendar/fullcalendar#5568]
### Bug Reports

`googleCalendar` plugin just stopped working. None of the Google Calendar events are fetched anymore -> `401` error.
I didn't change anything in my website.

Here are the code to reproduce the error : https://codepen.io/wawan_/pen/ExPbVZz?editors=1111
/!\ You need to add the `googleCalendar` plugin and enter a Google Calendar API Key

**Comment by tnguyen14** [comment]
Same here. This is the API response:

```
{
 "error": {
  "errors": [
   {
    "domain": "global",
    "reason": "authError",
    "message": "Invalid Credentials",
    "locationType": "header",
    "location": "Authorization"
   }
  ],
  "code": 401,
  "message": "Invalid Credentials"
 }
}
```

Google Calendar API is requiring OAuth2 access only now?

**Comment by haderack** [comment]
I am experiencing a similar problem. I was using v3 of FullCalendar. Also the Google Calendar examples in the FullCalendar documentation for v1 through v5 are also not working. 

The error from Chrome Developer Console is: 
fullcalendar.min.js:6 Google Calendar API: Invalid Credentials - Object
      domain: "global"
      location: "Authorization"
      locationType: "header"
      message: "Invalid Credentials"
      reason: "authError"
  __proto__:
         constructor: ƒ Object()
         hasOwnProperty: ƒ hasOwnProperty()
         isPrototypeOf: ƒ isPrototypeOf()
         propertyIsEnumerable: ƒ propertyIsEnumerable()
         toLocaleString: ƒ toLocaleString()
         toString: ƒ toString()
         valueOf: ƒ valueOf()
         __defineGetter__: ƒ __defineGetter__()
         __defineSetter__: ƒ __defineSetter__()
         __lookupGetter__: ƒ __lookupGetter__()
         __lookupSetter__: ƒ __lookupSetter__()
         get __proto__: ƒ __proto__()
         set __proto__: ƒ __proto__()

fullcalendar.min.js:6 Google Calendar API: Invalid Credentials - Object
        domain: "global"
        location: "Authorization"
        locationType: "header"
        message: "Invalid Credentials"
        reason: "authError"
        __proto__: Object

fullcalendar.min.js:6 Google Calendar API: Invalid Credentials - Object
        domain: "global"
        location: "Authorization"
        locationType: "header"
        message: "Invalid Credentials"
        reason: "authError"
        __proto__: Object

**Comment by masande** [comment]
Same here. In researching the problem I came across Google's recommendation: "Get a new access token using the long-lived refresh token."

Hoping this is a temporary glitch, but knowing Google they likely made their API access more restrictive.

**Comment by WeAreELIC** [comment]
I'm also having this issue with FullCalendar v5, please help! It was working fine yesterday—the first day I launched my site for an event, and now it's broken one day in.

**Comment by kynanware** [comment]
According to the [Google calendar API documentation](https://developers.google.com/calendar/auth), only OAuth 2.0 is currently supported.

> Your application must use OAuth 2.0 to authorize requests. No other authorization protocols are supported. If your application uses Google Sign-In, some aspects of authorization are handled for you.

Perhaps Google is now enforcing this requirement.

**Comment by haderack** [comment]
> According to the [Google calendar API documentation](https://developers.google.com/calendar/auth), only OAuth 2.0 is currently supported.
> 
> > Your application must use OAuth 2.0 to authorize requests. No other authorization protocols are supported. If your application uses Google Sign-In, some aspects of authorization are handled for you.
> 
> Perhaps Google is now enforcing this requirement.

As many use cases would be such that you don't want to prompt people for authorization, it seems like use of a service account is going to be needed. 

https://developers.google.com/identity/protocols/oauth2/service-account

**Comment by WeAreELIC** [comment]
I'm using OAuth for my application via Google Sign-in and still having this issue with FullCalendar. I'm able to grab the current logged in user's calendar and add it to FullCalendar via `eventSources > events`, but trying to add a Google Calendar via the google-calendar plugin—specifying the `googleCalendarApiKey` and a `googleCalendarId` under `eventSources`—is not working anymore and I'm getting this original error as described above. And like I mentioned before, this broke today—it was working fine yesterday.

**Comment by Freezard** [comment]
Same problem here using token, tried refreshing token as stated on the Google FAQ but still doesn't work.

**Comment by kierweb** [comment]
I'm having the same issue with my sites which uses this function - i'm hoping there is a fix!

**Comment by kierweb** [comment]
https://issuetracker.google.com/issues/160190541

**Comment by acerix** [comment]
Thanks, confirmed.  This demo show the same error:

https://fullcalendar.io/docs/google-calendar-demo

```
{
 "error": {
  "errors": [
   {
    "domain": "global",
    "reason": "authError",
    "message": "Invalid Credentials",
    "locationType": "header",
    "location": "Authorization"
   }
  ],
  "code": 401,
  "message": "Invalid Credentials"
 }
}
```

**Comment by louisgranato3** [comment]
It looks like Google has now resolved the issue on their end. It's working for me now.

**Comment by kierweb** [comment]
My sites are still having issues!

**Comment by dmceballosg** [comment]
Woking for me too.

**Comment by dmceballosg** [comment]
It's working just a couple of times, after two reloads it get the same issue

**Comment by arshaw** [comment]
some of the comments on the [google thread](https://issuetracker.google.com/issues/160190541) are saying the functionality has been restored. it works for me in the most basic example. is it working again for anyone else?

**Comment by arshaw** [comment]
it's actually working for me only 50% of the time

**Comment by KristyKay** [comment]
I've refreshed the page with my google calendar a few times and it's showing the events correctly every time.

**Comment by arshaw** [comment]
working now. google seems to have fixed the problem on their end
