### ISSUE TITLE
Content overflowing outside of events can trigger eventMouseEnter

### ISSUE THREAD

**Issue by acerix** [fullcalendar/fullcalendar#5569]
Reported in https://fullcalendar.freshdesk.com/a/tickets/1964

Moving the mouse on the left side of June 6 will trigger `eventMouseEnter` from the event on June 5.

https://codepen.io/acerix/pen/NWxwbXr?editors=0111

Possible workaround is to set `overflow: hidden;` on events.  

https://codepen.io/acerix/pen/mdVqOqN?editors=0111

**Comment by arshaw** [comment]
when events render without any custom `eventContent`, their time and title text is prevented from bleeding out. When custom `eventContent` is used however, there is no such protection. It's the responsibility of the app code at that point.

I would have added `overflow:hidden` on the outermost event div, but that actually kills the sticky-title functionality, so it was impossible.
