### ISSUE TITLE
Timezone not functioning as expected

### ISSUE THREAD

**Issue by benubah** [fullcalendar/fullcalendar#5571]
I tried to edit the [Timezone demo](https://fullcalendar.io/docs/timeZone-demo) on Codepen with a different event source and the timezone only changes for Local and UTC from the drop-down list.

Steps I took:
1. I accessed the URL: https://fullcalendar.io/docs/timeZone-demo
2. I clicked on *Edit in Codepen* at the top right
3. I change this line in the JS section of Codepen: 

  From:  `events: 'https://fullcalendar.io/demo-events.json',`

 To: `events: 'https://raw.githubusercontent.com/benubah/rcentral/master/useR/events.json',`

Then I tried to vary the timezones from the Drop-down list at the top-left. Only Local and UTC works.

Thanks!

**Comment by acerix** [comment]
Your JSON has the times hardcoded in UTC, but the timeZone setting works by adding a param `timeZone` to the request and having the server return the times for that timezone.
