### ISSUE TITLE
Generic duration for dayGridMonth not working

### ISSUE THREAD

**Issue by cconnell12345** [fullcalendar/fullcalendar#5581]
I am using fullcalendar V5.  

The following code works:

 var calendar = new FullCalendar.Calendar(document.getElementById('calendar'), {
        initialView: 'dayGridMonthCustom',
        initialDate: '2020-03-01',
        views: {
          dayGridMonthCustom: {
            type: 'dayGridMonth',
            duration: { weeks: 8 }, //Works when duration is under the the views
            fixedWeekCount: false
          }
        }
      });
      calendar.render();

The following code does not work:

 var calendar = new FullCalendar.Calendar(document.getElementById('calendar'), {
        initialView: 'dayGridMonthCustom',
        initialDate: '2020-03-01',
        duration: { weeks: 8 },  //Does not work when it is here
        views: {
          dayGridMonthCustom: {
            type: 'dayGridMonth',
            fixedWeekCount: false
          }
        }
      });
      calendar.render();

I need the second instance to work because I would like to dynamically change the duration using calendar.setOption('duration', { weeks: 1 });  As per the documentation that will not work if duration is specified under the view.

Here is the CodePen: https://codepen.io/cconnell1/pen/VweyWwO

Thank you in advance.

**Comment by iiibbbmmm** [comment]
```javascript
var views = calendar.getOption("views");
views.dayGridMonthCustom.duration.weeks = 1;
calendar.setOption("views", views);
```

**Comment by cconnell12345** [comment]
Thank you for the comment.  That works great.  Based on the documentation I believe it is still an error.  For me this is a great solution.

**Comment by acerix** [comment]
The issue is that `dayGridMonth` overrides the duration, it works with just `dayGrid`:

https://codepen.io/acerix/pen/dyGmMZZ
