### ISSUE TITLE
Setting the "duration" property on an event leaves it undefined in extendedProps

### ISSUE THREAD

**Issue by LiamBull** [fullcalendar/fullcalendar#5582]
In v4, I was using events that had a `duration` property, fed in from a JSON feed. These were added to `extendedProps` as expected, and I was able to use it from there.

In v5, the `duration` property gets gobbled up and is not usable. I looked through the v5 upgrade guide and didn't see anything, and looking at the documentation for the event object it doesn't mention the `duration` property at all - only the `durationEditable` property.

Please see the attached codePen. I added a second `myDuration` property to demonstrate the expected behaviour.

https://codepen.io/LiamBull/pen/mdVpwme

**Comment by iiibbbmmm** [comment]
I think [this](https://github.com/fullcalendar/fullcalendar/blob/77b9775df16d3f7d6d9c2982be172d54d2d95227/packages/common/src/structs/recurring-event-simple-refiners.ts#L10) caused the problem.

**Comment by acerix** [comment]
Thanks, confirmed.  I believe this is a new event property that just needs to be added to the docs, so you should use a different name to workaround it.

**Comment by arshaw** [comment]
@acerix is correct, this is now an official event property that will NOT find its way into extendedProps. I'll make sure this is well documented

**Comment by LiamBull** [comment]
Since this has been documented, I think this issue is safe to close. Thank you!

I put in a PR to address some of the wording/spelling errors in the original PR.
