### ISSUE TITLE
Missing exports (eventDrop, eventResize, dateClick) 

### ISSUE THREAD

**Issue by negberts** [fullcalendar/fullcalendar#5583]
### Bug Reports
After upgrading to V5.1 the CalendarOptions no longer exports a type definition for eventDrop, eventResize and dateClick although those should still be available. Please add them to the type definitions.

See 
https://fullcalendar.io/docs/eventDrop
https://fullcalendar.io/docs/eventResize
https://fullcalendar.io/docs/dateClick

I would have expected them in the CALENDAR_LISTENER_REFINERS in https://github.com/fullcalendar/fullcalendar/blob/257872cd6d8f6d73d5d379be70071520b2b4ce83/packages/common/src/options.ts

**Comment by hmnd** [comment]
@negberts As of v4, you need to import the `@fullcalendar/interaction` plugin in order for these to work. In v5.1, the types have been moved into the interaction plugin, so they will work once the plugin is imported.
