### ISSUE TITLE
Rrule plugin is not working with fullcalendar v5.1.0 with es6 build system

### ISSUE THREAD

**Issue by softgetixtest** [fullcalendar/fullcalendar#5585]
### Bug Reports
You MUST post a recreation or else your issue will be CLOSED without explanation.
Instructions: https://fullcalendar.io/reporting-bugs

### Feature Requests
Search the issue tracker for an existing ticket before creating a new one.
Instructions: https://fullcalendar.io/requesting-features

### React/Vue/Angular/etc
If your bug is specific to one of these frameworks, use the corresponding tracker.
List: https://github.com/fullcalendar

(Please erase the above text and begin typing. Thanks!)

**Comment by acerix** [comment]
Would you be able to post a [runnable, stripped-down demonstration of the bug](http://fullcalendar.io/wiki/Reduced-Test-Cases/) or steps to reproduce the issue? Would really appreciate it because the time saved reproducing will be time spent fixing.

**Comment by softgetixtest** [comment]
I am getting this error when importing ( import rrulePlugin from '@fullcalendar/rrule' ) with using webpack i also attached error screenshot.
![Screenshot from 2020-07-06 10-42-16](https://user-images.githubusercontent.com/32354328/86557959-89ab3880-bf75-11ea-8376-df467c8e5b60.png)
