### ISSUE TITLE
render method not rerendering resourceLabelContent

### ISSUE THREAD

**Issue by BrunoCartier** [fullcalendar/fullcalendar#5586]
Hello,

Thanks for this tool, it is more than awesome!

I have a problem following the migration to V5.

I have a use case where, when loading the calendar first, all resources are shown with very few lines (so small height), but when you click on a button, more lines are shown (so higher height).
It worked very well on V4, thanks to `calendar.rerenderResources();`.
But on V5, the resource takes the correct initial height, but then, it does not change anymore, even when calling `calendar.render()`.

Initial display:
![image](https://user-images.githubusercontent.com/6161734/86479092-c8f64100-bd4b-11ea-9e69-8659bff97923.png)

Display after clicking "See more lines":
![image](https://user-images.githubusercontent.com/6161734/86479137-dd3a3e00-bd4b-11ea-8e01-4b81e23e7ec7.png)
As you can see, the content overflows at the bottom because the height is not refreshed.

Here is the reduced test case:
https://codepen.io/ximax46631/pen/mdVpQQE

What can I do?
Am I missing an option or a function?
Is this a bug?

**Comment by iiibbbmmm** [comment]
Instead of the whole calender，V5 only re-render changed parts.
If you want to do the old fashion, simply .destroy() before .render(), and no need for setExtendedProp

**Comment by acerix** [comment]
It seems like a bug that `setExtendedProp` re-renders the resource but does not update the size to fit the new content. 

As a workaround, you could switch to another view temporarily to force a rerender:

https://codepen.io/acerix/pen/jOWzqeE?editors=0010

**Comment by arshaw** [comment]
Calling simply `.render()` is supposed to do this. it doesn't seem to work: https://codepen.io/arshaw/pen/JjGLKBe?editors=0010

I'll fix this

**Comment by iiibbbmmm** [comment]
I am not familiar with Preact, but in common, vdom-like system should not react to changes of `toggledLines` which only linked with function usage.
That's why @BrunoCartier uses `resource.setExtendedProp` to make it re-render.
I guess row height calculation is outside of single resource, so only the content changed.

**Comment by arshaw** [comment]
v5.2.0 offers an improvement I believe (I was able to get the new content to show up in the DOM in a slightly more reduced test case):

- v5.1.0 - [demo](https://codepen.io/arshaw/pen/JjGLKBe?editors=0010)
- v5.2.0 - [demo](https://codepen.io/arshaw/pen/zYrgjQW?editors=0010)

But it still doesn't adjust the size. I'll reopen this ticket and fix for next release.

**Comment by iiibbbmmm** [comment]
> v5.2.0 offers an improvement I believe (I was able to get the new content to show up in the DOM in a slightly more reduced test case):
> 
> * v5.1.0 - [demo](https://codepen.io/arshaw/pen/JjGLKBe?editors=0010)
> * v5.2.0 - [demo](https://codepen.io/arshaw/pen/zYrgjQW?editors=0010)
> 
> But it still doesn't adjust the size. I'll reopen this ticket and fix for next release.

I guess row height calculation happens in outer level of resource, view maybe? So single resource change will not trigger re-render of row.

**Comment by arshaw** [comment]
closed via:
https://github.com/fullcalendar/fullcalendar/commit/d94adfcd18cf973c48294c24375bbc20a51c7db8
https://github.com/fullcalendar/fullcalendar-scheduler/commit/795e7d6ff73b8ae24411e16ae6cc41b29ce47287
https://github.com/fullcalendar/fullcalendar-scheduler/commit/7f0aec653338d0041e289ca075180c4d7ce04b0a

I'll release this soon

**Comment by arshaw** [comment]
this has been fixed in [5.3.0](https://github.com/fullcalendar/fullcalendar/releases/tag/v5.3.0)

demo: https://codepen.io/arshaw/pen/LYNGNey?editors=0010

**Comment by kcsujeet** [comment]
@acerix i'm still having this issue when trying to render a custom resource label. Any workaround for this? ... a re-render does seem to work as it seem to fix itself when resizing window.


https://github.com/fullcalendar/fullcalendar/assets/24563569/35e936ca-0e40-41e7-94cc-947b31783beb

**Comment by kcsujeet** [comment]
@acerix  i'm still having this issue when trying to render a custom resource label. Any workaround for this? ... a re-render does seem to work as it seems to fix itself when resizing window.

PS: i'm using the React version and using `resourceLabelContent` prop to render a custom JSX component.

https://github.com/fullcalendar/fullcalendar/assets/24563569/9be48519-323c-41f8-a918-b32e5953c096

**Comment by xiaoxuehai** [comment]
> 在尝试呈现自定义资源标签时，我仍然遇到此问题。有什么解决方法吗？...重新渲染似乎确实有效，因为它似乎在调整窗口大小时会自行修复。
> 
> PS：我正在使用 React 版本并使用 prop 渲染自定义 JSX 组件。`resourceLabelContent`
> 
>  Screen.Recording.2024-01-24.at.2.33.47.PM.mov

I have the same problem

**Comment by SarthakET** [comment]
> @acerix i'm still having this issue when trying to render a custom resource label. Any workaround for this? ... a re-render does seem to work as it seems to fix itself when resizing window.
> 
> PS: i'm using the React version and using `resourceLabelContent` prop to render a custom JSX component.
> 
>  Screen.Recording.2024-01-24.at.2.33.47.PM.mov

+1 on this. Ideally the resizing should be done by the `FullCalendar` react component itself. 

@arshaw any updates here? is there a `.render` function we can call from the calendar api in react? I am also facing this issue.

**Comment by williamtobing** [comment]
having the same problem on first render in react

![image](https://github.com/user-attachments/assets/bc06fae1-12ec-47a5-b0f6-c4e7a61fc3e9)
