### ISSUE TITLE
resourceOrder docs mentions old default

### ISSUE THREAD

**Issue by sama55** [fullcalendar/fullcalendar#5587]
If resourceOrder is not specified, resources will not be shown in data order.
https://fullcalendar.io/docs/resourceOrder
My resource is a group format with children.
Thank you for your great work.

**Comment by iiibbbmmm** [comment]
That's correct according to [resources-crud.ts](https://github.com/fullcalendar/fullcalendar-scheduler/blob/eb8c7f8ef36028eae117b6c21b6941f3c37ad8e6/resource-common/src/resources-crud.ts) line 6
```
export const DEFAULT_RESOURCE_ORDER = parseFieldSpecs('id,title')
```
Maybe @arshaw should mention this in the docs?

In the meantime, @sama55 , a string that not matching any property , for example: '',  will do the trick.

**Comment by sama55** [comment]
Thanks iiibbbmmm. 
Thanks to you I understand solution. However if no option is specified, it may be correct to not sort.

**Comment by acerix** [comment]
Yes, resources are now ordered by their `id`, then by `title`, the docs just need to be updated.

https://github.com/fullcalendar/fullcalendar/issues/5301

**Comment by arshaw** [comment]
the new default is now reflected in the docs: https://fullcalendar.io/docs/resourceOrder
