### ISSUE TITLE
Trigger long press selection of events programmatically

### ISSUE THREAD

**Issue by bpmct** [fullcalendar/fullcalendar#5589]
How can I simulate an event selection (override the long-press) on an event to reveal the resize dot in React?

**Comment by acerix** [comment]
That's not built in but I believe you could simulate a "touch event", eg. https://stackoverflow.com/a/29306999 . Setting `longPressDelay` to zero might help.

I think it could be useful as a new feature.

**Comment by arshaw** [comment]
we already have this ticket:
https://github.com/fullcalendar/fullcalendar/issues/4513
&uarr;
Could you please visit the link, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates?
