### ISSUE TITLE
Uncaught TypeError: Cannot read property 'isHiddenDay' of undefined

### ISSUE THREAD

**Issue by YogliB** [fullcalendar/fullcalendar#5592]
I've created a [Svelte implementation](https://github.com/YogliB/svelte-fullcalendar) of FullCalendar and I have issues upgrading to v5.

I use rollup as my builder and a postcss plugin for the styles, and tried to follow [this](https://fullcalendar.io/docs/initialize-es6) guide.

I try to initialize the calendar with these options:
```javascript
let options = {
	initialView: 'dayGridMonth',
	plugins: [dayGridPlugin],
};
```

This is what I get in the browser's console:
```bash
main.js:8102 Uncaught TypeError: Cannot read property 'isHiddenDay' of undefined
    at new DaySeriesModel (main.js:8102)
    at DayTableView.buildDayTableModel (main.js:1080)
    at DayTableView.buildDayTableModel (main.js:983)
    at DayTableView.render (main.js:1069)
    at T (preact.module.js:1)
    at g (preact.module.js:1)
    at j (preact.module.js:1)
    at T (preact.module.js:1)
    at g (preact.module.js:1)
    at T (preact.module.js:1)
```

- [This ](https://github.com/YogliB/svelte-fullcalendar/blob/(wip)v1/src/components/FullCalendar.svelte) is the component implementation.
- I can't actually upload a live demo since I need a postcss plugin to handle the css-in-js.

**Comment by qweluke** [comment]
duplicated issue?
https://github.com/fullcalendar/fullcalendar-react/issues/78

**Comment by acerix** [comment]
It sounds like there may be a bug here seeing how others reported the same in the other issue. But I don't get any error using the example project, so you can try that to find what is causing the error and make a [stripped-down demo](http://fullcalendar.io/wiki/Reduced-Test-Cases/).

https://github.com/fullcalendar/fullcalendar-example-projects/tree/master/webpack

**Comment by janswist** [comment]
I have the same issue:
![image](https://user-images.githubusercontent.com/5583954/87121334-d72fea00-c282-11ea-9505-6756572bf5bf.png)

From what I understand it begins here https://github.com/fullcalendar/fullcalendar/blob/d3a2b13db43cfe9a450091776da3be25a0ca15c0/packages/common/src/common/DaySeriesModel.ts#L26

This is really frustrating because it started when I tried to add custom button. When unsuccessful I went back to "working" code, but error still shows up. Tried to reproduce it, but no luck. Maybe it's deeper, beyond calendar (webpack?).

**Comment by irfanonk** [comment]
I have got exact the same issue,(Cannot read property 'isHiddenDay' of undefined) 
so i searched and ended up here. then I realized that there wasn't any "@fullcalendar/timegrid": "^5.1.0", in my package.json even I installed with npm install @fullcalendar/timegrid. 
so then I installed with npm install --save @fullcalendar/timegrid (with --save) and made sure that it's in package.json dependencies, that eventually solved problem.

**Comment by janswist** [comment]
> I have got exact the same issue,(Cannot read property 'isHiddenDay' of undefined)
> so i searched and ended up here. then I realized that there wasn't any "@fullcalendar/timegrid": "^5.1.0", in my package.json even I installed with npm install @fullcalendar/timegrid.
> so then I installed with npm install --save @fullcalendar/timegrid (with --save) and made sure that it's in package.json dependencies, that eventually solved problem.

How come `--save` made it work? 🤔

**Comment by lulu-dirou** [comment]
I have got exact the same issue,(Cannot read property 'isHiddenDay' of undefined)

**Comment by arshaw** [comment]
I see a lot of people complaining about this bug, but nobody posting any [reduced test cases](https://fullcalendar.io/reduced-test-cases), so sadly we won't be able to fix

**Comment by janswist** [comment]
> I see a lot of people complaining about this bug, but nobody posting any [reduced test cases](https://fullcalendar.io/reduced-test-cases), so sadly we won't be able to fix

Because it's hard to reproduce it. I tried myself once, but error didn't appear then so I gave up.

**Comment by dev-assassin** [comment]
> I have got exact the same issue,(Cannot read property 'isHiddenDay' of undefined)
> so i searched and ended up here. then I realized that there wasn't any "@fullcalendar/timegrid": "^5.1.0", in my package.json even I installed with npm install @fullcalendar/timegrid.
> so then I installed with npm install --save @fullcalendar/timegrid (with --save) and made sure that it's in package.json dependencies, that eventually solved problem.

@irfanonk 
yes, it works for me.
thanks.
it saves my times and money ;)

**Comment by YogliB** [comment]
[This ](https://github.com/YogliB/svelte-fullcalendar/tree/(wip)v1)is the leanest repro I could have come up with, hope this helps.

**Comment by jsaarest** [comment]
Got this problem after updating to fullcalendar 5.3.0, ran `npm install --save @fullcalendar/react` and it started running again :)

**Comment by arshaw** [comment]
I have some more insight into the problem. For some reason, when installing `@fullcalendar/core` and the plugins, npm is not deduping `@fullcalendar/common`. Sometimes there are multiple copies of it, nested within fullcalendar's other dependencies.

 @YogliB I was able to clone [your repro](https://github.com/YogliB/svelte-fullcalendar/tree/(wip)v1) and reproduce the error. When I reinstalled the deps, making a new lock file, things began to work:

```
rm -rf node_modules package-lock.json
npm install
```

I'm not sure why. I bet that trick will work for others.

**Comment by YogliB** [comment]
@arshaw 
That's really wierd, based on your solution I solved it by deduping `@fullcalendar/common` in the rollup config file.

```javascript
resolve({
  browser: true,
  dedupe: ["svelte", "@fullcalendar/common"],
}),
```

**Comment by arshaw** [comment]
this could be related to npm being non-deterministic (the main complaint I hear against it and why people sometimes prefer Yarn) though I thought npm resolved this a while back. who knows

**Comment by myfairshare** [comment]
> I have some more insight into the problem. For some reason, when installing `@fullcalendar/core` and the plugins, npm is not deduping `@fullcalendar/common`. Sometimes there are multiple copies of it, nested within fullcalendar's other dependencies.
> 
> @YogliB I was able to clone [your repro](https://github.com/YogliB/svelte-fullcalendar/tree/(wip)v1) and reproduce the error. When I reinstalled the deps, making a new lock file, things began to work:
> 
> ```
> rm -rf node_modules package-lock.json
> npm install
> ```
> 
> I'm not sure why. I bet that trick will work for others.

Hi Arshaw,
  
    I have ran into this problem today after adding  plugins to FullCalendar in my React app.  Is it safe to run that command removing the lock file.  I'm hoping it would solve my problem but I'm a little apprehensive about removing it in case I get more problems, I have read that it can cause more problems.  Should I be ok to go ahead and remove it then re-install, thank you!

Alan

**Comment by myfairshare** [comment]
Turns out I was missing a plugin, thanks!

**Comment by TomHessburg** [comment]
Hey everyone! 

Think this is likely an issue with the 5.3.* releases of the timeGrid plugin, or at least an issue with it when using it with certain version of fullcalendar. Ran into this problem myself when adding the timegrid plugin specifically. Have an app I've been working on for ~8 months using fullcalendar react and haven't ran into anything like this until now. 

Current version of timegrid plug-in is [5.3.1](https://www.npmjs.com/package/@fullcalendar/timegrid).  Was able to fix by simply installing an older version of timegrid. Current versions of the plugins that my app is running is:

`   
    "@fullcalendar/bootstrap": "^5.0.0",
    "@fullcalendar/daygrid": "^5.0.1",
    "@fullcalendar/interaction": "^5.1.0",
    "@fullcalendar/react": "^5.0.0",
    "@fullcalendar/timegrid": "5.1.0",
`

Hope this helps someone!

**Comment by anonomity** [comment]
this worked for me

`
npm uninstall @fullcalendar/daygrid @fullcalendar/react
npm install --save @fullcalendar/daygrid @fullcalendar/react
`

**Comment by Sefriol** [comment]
Like some others have pointed out, this seems to be an issue on how npm organizes packages and under which component certain packages are.

In my package-lock, only thing that changed was that `@fullcalendar/common` was no longer under each component dependency, but on it's own.

i.e.
```json
"@fullcalendar/bootstrap": {
    "version": "5.3.1",
    "resolved": "https://registry.npmjs.org/@fullcalendar/bootstrap/-/bootstrap-5.3.1.tgz",
    "requires": {
    "@fullcalendar/common": "~5.3.1",
    "tslib": "^2.0.0"
    },
    "dependencies": {
        "@fullcalendar/common": {
            "version": "5.3.1",
            "resolved": "https://registry.npmjs.org/@fullcalendar/common/-/common-5.3.1.tgz",
            "requires": {
            "tslib": "^2.0.0"
            }
        },
        "tslib": {
            "version": "2.0.3",
            "resolved": "https://registry.npmjs.org/tslib/-/tslib-2.0.3.tgz",
        }
    }
}
```
was changed to:
```json
"@fullcalendar/bootstrap": {
    "version": "5.3.1",
    "resolved": "https://registry.npmjs.org/@fullcalendar/bootstrap/-/bootstrap-5.3.1.tgz",
    "requires": {
    "@fullcalendar/common": "~5.3.1",
    "tslib": "^2.0.0"
    },
    "dependencies": {
        "tslib": {
            "version": "2.0.3",
            "resolved": "https://registry.npmjs.org/tslib/-/tslib-2.0.3.tgz",
        }
    }
},
"@fullcalendar/common": {
    "version": "5.3.1",
    "resolved": "https://registry.npmjs.org/@fullcalendar/common/-/common-5.3.1.tgz",
    "requires": {
        "tslib": "^2.0.0"
    }
}
```
and after that it was fixed.

Steps:
1. Uninstall all `@fullcalendar` packages
2. Install packages again

**Comment by tomatobybike** [comment]
Uninstall all @fullcalendar packages
Install packages again
================================
make sure
all packages version 5.4.0 . 
================
    "@fullcalendar/daygrid": "^5.4.0",
    "@fullcalendar/interaction": "^5.4.0",
    "@fullcalendar/react": "^5.4.0",
    "@fullcalendar/timegrid": "^5.4.0"

**Comment by myfairshare** [comment]
In the docs it mentions webpack has to be configured a certain way to allow interaction to work correctly, is this something you could help with, I'm using create react app and not really familiar with tinkering with Webpack.  I will try these versions, my current package.json is..

"@fullcalendar/daygrid": "^5.3.1",
    "@fullcalendar/interaction": "^5.3.1",
    "@fullcalendar/list": "^5.3.1",
    "@fullcalendar/moment": "^5.3.1",
    "@fullcalendar/react": "^5.3.1",
    "@fullcalendar/timegrid": "^5.3.1",

Thanks!

**Comment by codeibrahima** [comment]
> I have some more insight into the problem. For some reason, when installing `@fullcalendar/core` and the plugins, npm is not deduping `@fullcalendar/common`. Sometimes there are multiple copies of it, nested within fullcalendar's other dependencies.
> 
> @YogliB I was able to clone [your repro](https://github.com/YogliB/svelte-fullcalendar/tree/(wip)v1) and reproduce the error. When I reinstalled the deps, making a new lock file, things began to work:
> 
> ```
> rm -rf node_modules package-lock.json
> npm install
> ```
> 
> I'm not sure why. I bet that trick will work for others.

work for me thanks

**Comment by myfairshare** [comment]
I removed everything and updated to 5.4.0 and all is working correctly now in create react app, no tinkering with webpack needed, so far anyway, thank you!

**Comment by bara1020** [comment]
Hi, I have the same error. I have the v5.4.0 in all dependencies( "@fullcalendar/angular": "^5.4.0", "@fullcalendar/common": "^5.4.0","@fullcalendar/core": "^5.4.0","@fullcalendar/daygrid": "^5.4.0", "@fullcalendar/interaction": "^5.4.0", "@fullcalendar/list": "^5.4.0",) and my Angular version is 9. can you help me please with this error.

core.js:6228 ERROR TypeError: Cannot read property 'isHiddenDay' of undefined
    at new DaySeriesModel (main.js:8019)
    at DayTableView.buildDayTableModel (main.js:1063)
    at DayTableView.buildDayTableModel (main.js:957)
    at DayTableView.push../node_modules/@fullcalendar/daygrid/main.js.DayTableView.render (main.js:1053)
    at z (preact.module.js:1)
    at b (preact.module.js:1)
    at $ (preact.module.js:1)
    at z (preact.module.js:1)
    at b (preact.module.js:1)
    at z (preact.module.js:1)

**Comment by qweluke** [comment]
@bara1020 had the same issue, just remove all `@fullcalendar/*` dependencies and install them once again but without `@fullcalendar/core`

**Comment by Krzysiek555** [comment]
I had very similar issue: `TypeError: Cannot read property 'resourceAreaWidth' of undefined`

None of the solutions mentioned here helped directly, but I did run bunch of bit random `npm instal --save @fullcalendar/xyz` and after 3rd or 4th try the error disappeared 🤯  

So if anyone came to my post in this discussion: Don't give up! 💪   Keep `npm installing --save` some fullcalendar dependencies xd

**Comment by sean2004390529** [comment]
npm uninstall @fullcalendar/xxxxx --save 
npm install @fullcalendar/xxxxx --save 

都干一遍，就好了
    "@fullcalendar/core": "^5.6.0",
    "@fullcalendar/daygrid": "^5.6.0",
    "@fullcalendar/interaction": "^5.6.0",
    "@fullcalendar/list": "^5.6.0",
    "@fullcalendar/timegrid": "^5.6.0",
    "@fullcalendar/vue": "^5.6.0",

**Comment by bgp1** [comment]
I am also able to reproduce this issue with any version of any `@fullcalendar` package > 5.4.0. I have attempted with 5.5.1 and 5.7.0 and both fail with this error after upgrading. Uninstalling and reinstalling undetermined amount of times isn't really a viable solution especially for automated build systems. 

My only solution has been to continue to try and downgrade back to 5.4.0 for all packages.

**Comment by arshaw** [comment]
Hello all. I have wrapped my head around this issue and have written a separate ticket about why it's happening and how we can prevent it in the future. Please see https://github.com/fullcalendar/fullcalendar/issues/6370
