### ISSUE TITLE
Events dragged from the More popup to another resource drop on the wrong resource

### ISSUE THREAD

**Issue by francescocerri** [fullcalendar/fullcalendar#5593]
There is a problem when trying to **drag and drop** an event that is contained in the "view all" modal.
If you try to move it to another resource it is not possible as seen in the posted video

![ezgif com-video-to-gif (1)](https://user-images.githubusercontent.com/15691292/86770804-93a26980-c051-11ea-8dd8-649164a3a9a1.gif)

Demo issue, (in this demo i used the react version, but doesn't work also without connector): 
https://codesandbox.io/s/modest-mclaren-3dr5p?file=/src/App.js

Fullcalendar: **v5.1.0**

**Comment by acerix** [comment]
Thanks, confirmed.

**Comment by KarlXOL** [comment]
Maybe my problem is related to this issue:

I have similar problem in an angular app with 2 calendar instances:
1 instance in start window and 
1 instance in a modal (dialog)

When dragging in the dialog then the instance in the "start window" is the receiving context.
When modal is called from another start window (without) calendar it is working fine.

I have found no way to workaround this.

**Comment by laughingrat** [comment]
We got the same problem. Hope to get it fixed ASAP.

**Comment by arshaw** [comment]
this is no longer an issue as of 5.5.0: https://codesandbox.io/s/sharp-mclean-krp2p?file=/src/App.js
