### ISSUE TITLE
Support for Shifted Time Slots

### ISSUE THREAD

**Issue by tuerker** [fullcalendar/fullcalendar#5597]
### Feature Requests
The following use case, which is very common in shifted operation, seems to be not supported by fullcalendar:

Non-overlapping 12 h time slots starting a given time, e.g., at 08:00 and 20:00.

In this case, the daily schedule should have two slots as follows:

08:00-20:00 ...
20:00-08:00 ...

The current implementation supports the following only:

00:00-12:00 ...
12:00-24:00 ...

when slotDuration="12:00" is defined.

So, it would be great to extend the component by an additional attribute to shift the slots by a given duration as desired.

Of course, the value of this duration attribute must be smaller than the value of the attribute slotDuration.

... and the implementation should also work for any slotDuration which is a divisor of 24 h.

Please note that this use case cannot be solved using slotMinTime alone. For realizing the described use case I think that an additional attribute is needed.

This becomes obvious when you consider the following use case where all four attributes would be needed:
At day basis, events can be between 08:00 and 20:00 but you want to restrict the events to 4h slots starting at following times:

18:00 -20:00 of previous day and 08:00 -10:00
10:00 -14:00
14:00 -18:00
18:00 -20:00 and 08:00-10:00 of next day

To define this use case, the following attributes would be needed:

slotMinTime="08:00"
slotMaxTime="20:00"
slotDuration="04:00"
and
shiftedSlotMinTime="10:00"

**Comment by acerix** [comment]
I believe this existing ticket captures this need:
https://github.com/fullcalendar/fullcalendar/issues/4834
↑
Please visit the above issue, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates.

Otherwise, it would help if you can provide a mockup of what you are looking for.  If you just want to control where events are allowed (not change the display), then you can use `eventAllow`.

**Comment by tuerker** [comment]
No, #4834 goes far beyond my feature request and much more difficult to realize.

My feature request refers to a very common use case which you find everywhere in daily business, especially in fabrics, where shift work is practiced usually in three 8hour shifts. To support that, time slots are needed which do not necessarily start at midnight (or slotMinTime), as shown here:

![Screenshot from 2020-07-10 03-45-35](https://user-images.githubusercontent.com/10051373/87107648-9de68280-c260-11ea-8a03-581c0b407a76.png)

For instance, we want to be able to model 12h slots that either start at 08:00 or at 20:00, as depicted in this mockup (the day 12h slot from 08:00 to 20:00 should of course have the same height as the night 12h slot from 20:00 to 08:00)

![Screenshot from 2020-07-10 03-55-32](https://user-images.githubusercontent.com/10051373/87108125-cd49bf00-c261-11ea-93c1-da3f01453a6d.png)

To express this additional characteristic only one additional attribute is required. I called it shiftedSlotMinTime. 

Please also have a deeper look at my example above for three shift example which even combines slotMinTime and slotMaxTime.

I think a lot of people would really appreciate such a useful extension of this great library.

**Comment by tuerker** [comment]
so please reopen my feature request.

**Comment by acerix** [comment]
Does it not work to include the "shifted" time in slotMinTime/slotMaxTime like this?

https://codepen.io/acerix/pen/GRoBYgo?editors=001

**Comment by tuerker** [comment]
@acerix: great. many thanks for the hint. i was not aware that it is possible to enter a value beyond 24:00 for slotMaxTime. so the shifted slot can of course be realized by using slotMinTime+shiftTime and slotMaxTime+shiftTime.
