### ISSUE TITLE
How to put first row below stickyHeaderDates

### ISSUE THREAD

**Issue by sama55** [fullcalendar/fullcalendar#5598]
I use V5 timeline. I want to put first (resource) row below sticky header.
Do you know any solution?
Thank you for your great work.

**Comment by iiibbbmmm** [comment]
Yes, but that looks odd.
[Demo](https://codepen.io/iiibbbmmm/pen/qBbYoJy)

**Comment by sama55** [comment]
Thanks iiibbbmmm.
My hope is to put first row(Auditorium A) below stickyHeaderDates(rooms xam xam xam xam ...). It is not Toolbar.
In other words, I want to show first row(Auditorium A) as sticky row.
Thank you for your advice.

**Comment by acerix** [comment]
I believe this existing ticket captures this need:
https://github.com/fullcalendar/fullcalendar/issues/4898
↑
Please visit the above issue, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates.

**Comment by sama55** [comment]
Thanks acerix.
My hope is same as #4898 (I couldn't find it.). This feature doesn't seem to be realized yet.
I would like to solve my issue in another way.
Thank you for cooperation by iiibbbmmm and acerix.
