### ISSUE TITLE
refetchEvents with param

### ISSUE THREAD

**Issue by ketna11** [fullcalendar/fullcalendar#5604]
I am trying to pass variable every time events are refeched according to documentation for v5. 
However it seems that it does not work. Please advise if there is something wrong with my code or this functionality does not work as expected.

<code>document.addEventListener('DOMContentLoaded', function() {  

    var vid = 1;
    var calendarEl = document.getElementById('calendar');
    var calendar = new FullCalendar.Calendar(calendarEl, {
      now: '2020-06-07',
      scrollTime: '00:00',
      aspectRatio: 1.8,
      headerToolbar: {
        left: 'today prev,next',
        center: 'title',
        right: 'dayGridMonth,timeGridWeek,timeGridDay,listMonth'
      },
      initialView: 'dayGridMonth',
	events: {
    url: 'feed.php',
    method: 'POST',
	extraParams: function() { 
      return {
        filter: vid
      };
    }
  }
    });

    calendar.render();
	document.getElementById('filters').addEventListener('change', function() {
    var vid = document.getElementById('filters').value;
	alert('refetching...'+vid)
    calendar.refetchEvents()
  });
  });
</code>

**Comment by acerix** [comment]
Would you be able to post a [runnable, stripped-down demonstration of the bug](http://fullcalendar.io/wiki/Reduced-Test-Cases/)? Would really appreciate it because the time saved reproducing will be time spent fixing.
