### ISSUE TITLE
Question: createPlugin not called

### ISSUE THREAD

**Issue by rattkin** [fullcalendar/fullcalendar#5605]
In my App, rrule plugin seem to do nothing. I think it doesn't even initialize from core properly.
I was trying to recreate it with new ap, where everything works.

Below is sample app, which works (note highlighted createPlugin on the left side)
On the right side, is my real app where 'rrule's are just skipped, like they didn't exist
![image](https://user-images.githubusercontent.com/910080/87133474-aa3a0200-c297-11ea-9535-cf2186c06e17.png)

How can I debug if plugin is created properly?

**Comment by rattkin** [comment]
Other plugins (interaction, day view) work fine.

**Comment by rattkin** [comment]
FullCalendarComponent: calendar.currentData.pluginHooks.recurringTypes contains 2 members on working example, but just one member on nonworking app

**Comment by rattkin** [comment]
If I register FullCalendar plugins like this:
 FullCalendarModule.registerPlugins([ 
    rrulePlugin,
    dayGridPlugin,
]);
I get runtime error, that " viewType "dayGridMonth" is not available. Please make sure you've loaded all neccessary plugin"

**Comment by rattkin** [comment]
solved my multiple reinstalling

**Comment by emielmolenaar** [comment]
Just wasted some time on this; just to clarify things: make sure you have corresponding versions of all plugins installed. For example, I had @fullcalendar/vue^5.3.1 installed and (obviously) installed @fullcalendar/rrule^5.5.0 by running `yarn add @fullcalendar/rrule`. This breaks things. I have upgrade all fullcalendar deps to ^5.5.0 and now everything is working fine.
