### ISSUE TITLE
Wrong request Accept header on Event as json feed

### ISSUE THREAD

**Issue by genyslt** [fullcalendar/fullcalendar#5614]
### Bug Reports
When i use events as JSON feed from URL, there is wrong Accept header sended by AJAX request:

Docs: [https://fullcalendar.io/docs/events-json-feed](url)

Host: example.dev
Connection: keep-alive
Content-Length: 89
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.116 Safari/537.36
**`Accept: */*`**
Content-Type: application/x-www-form-urlencoded
Accept-Encoding: gzip, deflate, br
Accept-Language: lt,en-US;q=0.9,en;q=0.8,ru;q=0.7,pl;q=0.6

### Solution
**`Accept: application/json`**

**Comment by acerix** [comment]
I don't believe `Accept: */*` is "wrong", changing that would likely break compatibility with other servers.  There's an open request to allow changing the request headers (and more), for now you could supply the events "as a function".
https://github.com/fullcalendar/fullcalendar/issues/4627
↑
Please visit the above issue, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates.
