### ISSUE TITLE
Blanck space between header and calendar and slotlabelformat hour doesn't work with two digiti

### ISSUE THREAD

**Issue by Cris200992** [fullcalendar/fullcalendar#5615]
Hi,
I uploaded fullcalendar to latest version and  i have some problems.
First there is an space between header and calendar when the scroll appears and I put allDaySlot: false.
And alfo the two-digit format in the hour doens't work.

https://codepen.io/cris200992/pen/XWXPmdW?editable=true&editors=001%3Dhttps%3A%2F%2Ffullcalendar.io%2Freduced-test-cases

**Comment by acerix** [comment]
I don't see any blank space from `allDaySlot:false,`, could you provide a screenshot showing what you mean? Or let me know which browser if it's specific to one.  

Also, I see the hours as 2 digits (eg. 06:00 instead of just 6:00) how are you expecting that to work?

**Comment by Cris200992** [comment]
Hi,
I'm on firefox and i don't know how do you see it well. I see the blanck and the 6:00. 
![image](https://user-images.githubusercontent.com/35325847/87507698-2359a080-c66e-11ea-9fdb-4fb8225d9e85.png)
![image](https://user-images.githubusercontent.com/35325847/87507761-3e2c1500-c66e-11ea-915c-66cb22f2d89d.png)

**Comment by acerix** [comment]
I can see the 2-digit hours don't work in Firefox with the default locale, but works if you use a locale with 24 hour time lke 'en-GB'. 

https://codepen.io/acerix/pen/KKVGKVx?editors=0010

I still don't see the blank space on my side though, are you using the newest Firefox (v78) and are you using Windows? (I only tested on Linux)  You can try turning off any addons in Firefox which might be causing that.

**Comment by iiibbbmmm** [comment]
firefox 78.0.2 on win10, no gap
![image](https://user-images.githubusercontent.com/9651676/87627915-672dd200-c762-11ea-9c90-b81fe52f766e.png)

**Comment by Cris200992** [comment]
Yes I use windows 10 and firefox version 68.  I see your codepen well, but if I change to locale 'es' (spain) I see it wrong again and I think ( may I'm wrong) that locale from spain is 24 hour time too.
I turn off all but i'm still seeing the white space. 
![image](https://user-images.githubusercontent.com/35325847/87651786-a3a60180-c753-11ea-80da-630b8687f7b4.png)

 If I change the navigator  to  ie11 the situation is even worse.I can't see anything about fullcalendar included the oficial web page 
![image](https://user-images.githubusercontent.com/35325847/87652259-452d5300-c754-11ea-952f-279e1f0864d2.png)

If i put google crome I see all propertly without any problem.
![image](https://user-images.githubusercontent.com/35325847/87653174-765a5300-c755-11ea-9533-c7c3ac0bb321.png)

**Comment by acerix** [comment]
I tested Firefox on Windows 10 and still don't see the issue, updating to latest Firefox may help.  

For the 2-digit hour in 'es' locale, that seems like a bug in Firefox, you could use the moment plugin to get more control over the format:

https://fullcalendar.io/docs/moment-plugins
