### ISSUE TITLE
Fullcalendar v 4.4.2: cann't select date after call method setOption('height', 'auto')

### ISSUE THREAD

**Issue by SheikoSN** [fullcalendar/fullcalendar#5618]
I use Fullcalendar v 4.4.2. I need to reduce calendar height after collapse tab with resources. So, I use setOption('height', 'parent')/setOption('height', 'auto') for this. I can reproduce this bug on the fullcalendar examples. Code for reproduce bug:

`document.addEventListener('DOMContentLoaded', function() {
  var calendarEl = document.getElementById('calendar');

  var calendar = new FullCalendar.Calendar(calendarEl, {
    plugins: [ 'interaction', 'resourceTimeline', 'timeGrid' ],
    selectable: true,
    defaultView: 'resourceTimelineWeek',
    header: {
      left: 'prev,next today',
      center: 'title',
      right: 'resourceTimelineWeek,timeGridDay'
    },
    resourceGroupField: 'building',
    resources: [
      { id: 'a', building: '460 Bryant', title: 'Auditorium A' },
      { id: 'b', building: '460 Bryant', title: 'Auditorium B' },
      { id: 'c', building: '460 Bryant', title: 'Auditorium C' },
      { id: 'd', building: '460 Bryant', title: 'Auditorium D' },
      { id: 'e', building: '460 Bryant', title: 'Auditorium E' },
      { id: 'f', building: '460 Bryant', title: 'Auditorium F' },
      { id: 'g', building: '564 Pacific', title: 'Auditorium G' },
      { id: 'h', building: '564 Pacific', title: 'Auditorium H' },
      { id: 'i', building: '564 Pacific', title: 'Auditorium I' },
      { id: 'j', building: '564 Pacific', title: 'Auditorium J' },
      { id: 'k', building: '564 Pacific', title: 'Auditorium K' },
      { id: 'l', building: '564 Pacific', title: 'Auditorium L' },
      { id: 'm', building: '564 Pacific', title: 'Auditorium M' },
      { id: 'n', building: '564 Pacific', title: 'Auditorium N' },
      { id: 'o', building: '101 Main St', title: 'Auditorium O' },
      { id: 'p', building: '101 Main St', title: 'Auditorium P' },
      { id: 'q', building: '101 Main St', title: 'Auditorium Q' },
      { id: 'r', building: '101 Main St', title: 'Auditorium R' },
      { id: 's', building: '101 Main St', title: 'Auditorium S' },
      { id: 't', building: '101 Main St', title: 'Auditorium T' },
      { id: 'u', building: '101 Main St', title: 'Auditorium U' },
      { id: 'v', building: '101 Main St', title: 'Auditorium V' },
      { id: 'w', building: '101 Main St', title: 'Auditorium W' },
      { id: 'x', building: '101 Main St', title: 'Auditorium X' },
      { id: 'y', building: '101 Main St', title: 'Auditorium Y' },
      { id: 'z', building: '101 Main St', title: 'Auditorium Z' }
    ],
    dateClick: function(info) {
      alert('clicked ' + info.dateStr + ' on resource ' + info.resource.id);
    },
    select: function(info) {
      alert('selected ' + info.startStr + ' to ' + info.endStr + ' on resource ' + info.resource.id);
    }
  });

  calendar.render();
  console.log(calendar);
  calendar.el.addEventListener('click', (event) => {
    calendar.setOption('height', 'parent');
  })
});`

Steps to reproduce:
1) click on minus icon and collapse some resource group.
2) click on plus icon and expand tab from the previous step.
3) try to select date on the previously collapsed and expanded resource

result: TypeError: Cannot read property 'resource' of undefined

**Comment by acerix** [comment]
Would you be able to post a [runnable, stripped-down demonstration of the bug](http://fullcalendar.io/wiki/Reduced-Test-Cases/)? Would really appreciate it because the time saved reproducing will be time spent fixing.

**Comment by SheikoSN** [comment]
I created codeopen example: https://codepen.io/sergey1991/pen/qBbJaqP?editors=0010
And I attached video with steps to reproduce.
![ezgif com-video-to-gif (1)](https://user-images.githubusercontent.com/16978058/87650017-b4597600-c759-11ea-86f4-1e26899d1f36.gif)

**Comment by acerix** [comment]
The issue seems to be with changing the `height` setting the calendar is clicked, since that cuases a rerender, when the mouse is released, the orginal element of the selection no longer exists.  

It works if if `height:auto` is the initial setting instead of changing it on click.  If you need to change that when the resource is collapse, you could put `addEventListener` on the resource collapse buttons instead of the entire calendar.
