### ISSUE TITLE
FullCalendarVDom.render is throwing errors during calendar initialization

### ISSUE THREAD

**Issue by vfonic** [fullcalendar/fullcalendar#5621]
### Bug Reports
> You MUST post a recreation or else your issue will be CLOSED without explanation.
> Instructions: https://fullcalendar.io/reporting-bugs

This issue is unfortunately not possible to reproduce on the clean FullCalendar setup. Loading UMD module in a script tag, does not create this issue.

However, the issue is still happening in FullCalendar.

I'm using a CMS tool called Duda: https://www.duda.co/

They allow creating of widgets, kind of like web components, but tied to the CMS backend data directly.

I've created one such widget for FullCalendar. Unfortunately, I cannot load FullCalendar, because I always get this error:

```
main.min.js:6 Uncaught (in promise) TypeError: Cannot read property '__k' of undefined
    at A (main.min.js:6)
    at e.o.handleRenderRequest [as drainedOption] (main.min.js:6)
    at e.drained (main.min.js:6)
    at e.tryDrain (main.min.js:6)
    at e.request (main.min.js:6)
    at t.render (main.min.js:6)
    at calendar:458
```

Or in unminified version:

```
 main.js:57 Uncaught (in promise) TypeError: Cannot read property '__k' of undefined
    at H (main.js:57)
    at DelayedRunner.Calendar._this.handleRenderRequest [as drainedOption] (main.js:9112)
    at DelayedRunner.drained (main.js:6976)
    at DelayedRunner.tryDrain (main.js:6958)
    at DelayedRunner.request (main.js:6920)
    at Calendar.render (main.js:9150)
    at calendar:458
```

It's basically this line:

`i && i.__k || u.__k` 

Seems like both of these variables are `undefined` here and that's where the error happens.

I opened the unminified FullCalendar and found plenty of polyfill code that's still minified. I assume these are some third-party libraries? It would be great to be able to know which libraries these are. I think this should be written in the docs and maybe added as a comment somewhere in the code as well.

I understand the main issue is with Duda CMS' JS code, but it's hard to debug this, since, even "unminified" FullCalendar code has minified parts that are actually throwing errors.
How can I find out which library is throwing errors so that I can keep digging? Thanks!

Here's the webpage where I'm trying to load the calendar:
https://morris_ct.multiscreensite.com/calendar

**Comment by vfonic** [comment]
So the issue is within preact's code. Would it be possible to bump preact to the latest minor version? Perhaps that would fix the error.

I tried bumping the version, but I got different minified variable names so it didn't work. How can I build the FullCalendar dist myself?
Thanks!

**Comment by acerix** [comment]
We need a stripped down recreation of the error, you could try starting from one of the example projects to make a demo:

https://github.com/fullcalendar/fullcalendar-example-projects

Loading the pre-built scripts instead of building may work:

https://fullcalendar.io/docs/initialize-globals

**Comment by vfonic** [comment]
@acerix I tried loading pre-built scripts as well. I've reached out to Duda support as well. The error has to do with their JS, but it's hard to figure out what exactly is off, since the "unminified" version of FullCalendar packs minified version of Preact. I'm not sure if there's an easy way to have Preact unminified?

If you know of an easy way to achieve that, I'd love to do that so that I can create a new build and see the exact unminified code that's causing the error.

Thanks!
Viktor

**Comment by sawest** [comment]
I ran into this issue as well with version 5.3.2. After some investigation I found that I was using a hashtag (#) in my getElementById method. My original code looked like this: `var calendarObj = new FullCalendar.Calendar(document.getElementById("#calendar")...` and once I changed it to: `var calendarObj = new FullCalendar.Calendar(document.getElementById("calendar")...` the error went away. Not saying the hashtag is always the issue but this does show that the error appears to be tied to whether the getElementById pulls a valid DOM object or not.

**Comment by liberty914** [comment]
I had the same problem. I solved it.
In my case, when I executed getElementById during the initial html rendering, an error occurred when the element was not yet rendered.
If you render the FullCalendar after the element has been fully rendered, it will works fine.

**Comment by atertoc** [comment]
> I ran into this issue as well with version 5.3.2. After some investigation I found that I was using a hashtag (#) in my getElementById method. My original init code looked like this: `var calendarObj = new FullCalendar.Calendar(document.getElementById("#calendar")...` and once I changed it to: `var calendarObj = new FullCalendar.Calendar(document.getElementById("calendar")...` the error went away. Not saying the hashtag is always the issue but this does show that the error appears to be tied to whether the getElementById pulls a valid DOM object or not.

You are my bloody hero, I too copied the basic JS examples and converted to jQuery syntax by mistake. As I've just started migrating projects to Webpacker, I totally went deep into debugging a non-issue. Thank you so much for saving me!

**Comment by sawest** [comment]
> > I ran into this issue as well with version 5.3.2. After some investigation I found that I was using a hashtag (#) in my getElementById method. My original init code looked like this: `var calendarObj = new FullCalendar.Calendar(document.getElementById("#calendar")...` and once I changed it to: `var calendarObj = new FullCalendar.Calendar(document.getElementById("calendar")...` the error went away. Not saying the hashtag is always the issue but this does show that the error appears to be tied to whether the getElementById pulls a valid DOM object or not.
> 
> You are my bloody hero, I too copied the basic JS examples and converted to jQuery syntax by mistake. As I've just started migrating projects to Webpacker, I totally went deep into debugging a non-issue. Thank you so much for saving me!

Glad I could be a hero for once!
