### ISSUE TITLE
ResourceAreaHeaderContent for Vertical Resource View

### ISSUE THREAD

**Issue by sama55** [fullcalendar/fullcalendar#5636]
I'm using V5 Full Calendar. And, I'm changing view mode with changeView function.
resourceAreaHeaderContent hook is called in resourceTimelineDay.
https://fullcalendar.io/docs/resource-area-header-render-hooks

My question)
Is there a hook function to do the same with resourceTimeGridDay?

Thanks to all developers.

**Comment by acerix** [comment]
I believe this existing ticket captures this need:
https://github.com/fullcalendar/fullcalendar/issues/5380
↑
Please visit the above issue, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates.

**Comment by sama55** [comment]
Thanks acerix.
Unfortunately viewSkeletonRender doesn't seem to be implemented in V5.
https://fullcalendar.io/docs/v4/viewSkeletonRender
As another solution, hook for V5 is viewDidMount?
https://fullcalendar.io/docs/view-render-hooks
