### ISSUE TITLE
ICS Plugin or an integration like Google Calendar

### ISSUE THREAD

**Issue by sigalou** [fullcalendar/fullcalendar#5638]
Hello,

I went through all your documentation of all your sites and I am wondering about the lack of consideration of the **ICS protocol**. Which seems to me to be the universal format of calendars.

You really favor Google Calendar (https://fullcalendar.io/docs/google-calendar) and I can't find anything on your site that natively allows the integration of an ICS link.
Yet discussions of several years back evoked ICS (https://github.com/fullcalendar/fullcalendar/issues/1580) then nothing since, this idea has been totally abandoned?
My research led me to:
* https://github.com/leonaard/icalendar2fullcalendar
* https://github.com/larrybolt/online-ics-feed-viewer (even online version does not work)
Extensions that use https://mozilla-comm.github.io/ical.js/ to fetch ical and send it to FullCalendar.

Do you think it's useful to include a link, natively, in FullCalendar which could retrieve a URL in iCal?
This idea is completely abandoned and each one needs to develop their own interface?
Can we work on it together?

Thank you, and good continuation on this project, still relevant.

**Comment by acerix** [comment]
The issue you mentioned is still open as a request for this feature:
https://github.com/fullcalendar/fullcalendar/issues/1580
↑
Please **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)) and press the 🔈**Subscribe** button to receive updates.

New features are added based on popularity: https://fullcalendar.io/requesting-features
