### ISSUE TITLE
Setters for all options

### ISSUE THREAD

**Issue by arshaw** [fullcalendar/fullcalendar#564]
Originally reported on Google Code with ID 293
```
Is there an easy way to set timeSlot property when fullcalendar is already
in use? I have different types of users in the drop-down list and each of
them have different settings (like timeSlot). After selecting one of users
I'd like to load calendar again with custom timeSlot property. I know Adam
introduced this featured in last released, but it only works for
apsectRatio, contentHeight and height. I need to setup timeSlot as well.
I'm on the deadline... Has anybody any clue how to resolve this issue?
Adam: is there any way to include this in the next release?

Thanks again for your great script. It's awsome!

```

Reported by `marcin.milinski` on 2010-01-15 14:32:25

Imported with **59** stars.

**Comment by twiginteractive** [comment]
+1 for this functionality (which is pretty much standard in jQuery plugins, so was surprised to see it still missing from FC)

I tried using the direct approach from http://stackoverflow.com/questions/13432014/how-can-i-set-fullcalendar-options-dynamically - (retrieving the current view and accessing the options object directly) but it didn't seem to work even with a call to ( 'render' ). So instead only way I have found is to destroy the calendar, and reinitialize with a modified args array.

Hopefully this will be a cleaner method.

**Comment by zlorkovic** [comment]
+1 for this feature. Changing time format based on user select (dynamically) would be great!

**Comment by mashintsev** [comment]
+1. We need change slotDuration in Timeline view dynamically.

**Comment by ivanbozic** [comment]
+1. Any updates on at least a possible timeline for this?

**Comment by arshaw** [comment]
hoping to get to this late this Q1 or early Q2

**Comment by killa-kyle** [comment]
I'm interested in this feature as well. Thanks @arshaw for your work on Fullcalendar. It does most of what I need for the plugin I'm writing. I appreciate it.

**Comment by ajaybairagi** [comment]
I have fixed this issue with another method

<span id="time_format"  time="12">24 Hours</span>

$("body").delegate("#time_format","click",function() { 
 var  resourceWiew=$('#calendar').fullCalendar('getView').name;
if(resourceWiew=="timelineDay" || resourceWiew=="timelineThreeDays"){
			 
			if($(this).attr("time")=="12"){
				$(this).attr("time","24");
				$(this).html("12 Hours");
				$('.fc-widget-header .fc-cell-text').not(":eq(0)").each(function() {
					$(this).html(calTime24($(this).html()));
				});
			}else{
					$(this).attr("time","12");
					$(this).html("24 Hours");
					$('.fc-widget-header .fc-cell-text').not(":eq(0)").each(function() {
						$(this).html(calTime12($(this).html()));
					});
			} 
 }

**Comment by arshaw** [comment]
This has been implemented and release in [v2.9.0](https://github.com/fullcalendar/fullcalendar/releases/tag/v2.9.0). You can set nearly any option dynamically like this:

```js
$('#calendar').fullCalendar('option', 'lang', 'fr');
```

The [languages](http://fullcalendar.io/js/fullcalendar-2.9.0/demos/languages.html) and [timezones](http://fullcalendar.io/js/fullcalendar-2.9.0/demos/timezones.html) demos are examples of this.

You can also set multiple options at the same time:

```js
$('#calendar').fullCalendar('option', {
    lang: 'fr',
    isRTL: true
});
```

Not all options can be dynamically set. [See the full docs for more info](http://fullcalendar.io/docs/utilities/dynamic_options/).

For most options, dynamically changing the value will rerender the entire current view (while keeping the previous scroll state). If special-case optimizations are needed for specific options, please make separate tickets.

For the [Scheduler premium plugin](http://fullcalendar.io/scheduler/), there is a know bug where the row expanded/contracted state is not maintained: https://github.com/fullcalendar/fullcalendar-scheduler/issues/196

Thanks for patiently waiting for this feature.

**Comment by lorinkoz** [comment]
Let me bug this thread one last time: AWESOME! Thanks

**Comment by wunsjoshi** [comment]
Hi @arshaw ,

We are using v1.5.4 and we are facing issue with change of property values on the fly. I tried to update key: value for options[name] but still we are facing issue with refreshing calendar.

https://github.com/fullcalendar/fullcalendar/issues/564#issuecomment-132534043

https://github.com/fullcalendar/fullcalendar/issues/564#issuecomment-132534093

None of above solutions worked for us.

Would you please shed some lights on this?

Thanks,
Sumit Joshi

**Comment by arshaw** [comment]
@wunsjoshi, dynamic property value changing is supported in >=2.9.0. So, doesn't work in v1.5.4.

Please open up on a new ticket for any discussion beyond this.
