### ISSUE TITLE
Uncaught TypeError: Cannot read property 'datepickerLocale' of undefined

### ISSUE THREAD

**Issue by 503612012** [fullcalendar/fullcalendar#5643]
Uncaught TypeError: Cannot read property 'datepickerLocale' of undefined

**Comment by acerix** [comment]
Would you be able to post a [runnable, stripped-down demonstration of the bug](http://fullcalendar.io/wiki/Reduced-Test-Cases/)? Would really appreciate it because the time saved reproducing will be time spent fixing.
