### ISSUE TITLE
Default scrollTime is not appropriate for month/year view

### ISSUE THREAD

**Issue by ryanjkelly** [fullcalendar/fullcalendar#5645]
The pen below is using **FullCalendar Scheduler** `v5.1.0`. I've tested this on Chrome, Firefox and Edge. They all have the same starting horizontal scrollbar position.

https://codepen.io/ryankelly/pen/KKVJReb

**Comment by acerix** [comment]
The issue is that `scrollTime` by default is 6AM, so it scrolls to that time on the first day, setting to zero will fix:

https://codepen.io/acerix/pen/oNbmazG?editors=0010

This has come up a few times and I don't believe there should be default scrolling in that view so will leave this open.

**Comment by arshaw** [comment]
The behavior is now fixed in v5.2.0: https://codepen.io/arshaw/pen/ZEQgxdQ

Though I now see a minor related bug: https://github.com/fullcalendar/fullcalendar/issues/5686
