### ISSUE TITLE
Resizer icon missing on event hover

### ISSUE THREAD

**Issue by jamesamuel** [fullcalendar/fullcalendar#5649]
The resizer icon is missing when an event is hovered in V5. 

Example can be found in your test-cases (https://fullcalendar.io/reduced-test-cases) - Scheduler plugins.

**Comment by acerix** [comment]
That was removed in v5, you can use CSS to recreate it:

https://github.com/fullcalendar/fullcalendar/issues/5498#issuecomment-646418942
