### ISSUE TITLE
No backgroundColor for timed events

### ISSUE THREAD

**Issue by a1devak** [fullcalendar/fullcalendar#5662]
### Reduced Test Case

@fullcalendar/angular : 5.0.0

https://codesandbox.io/s/dry-thunder-bkmy5?file=/src/app/app.component.ts

### Bug Description

The above codesandbox link can reproduce the issue.

Expecting - When backgroundColor is provided the UI should display the background color.

Instead - backgroundColor is applying to only all-day events.

### Screenshots

![Screen Shot 2020-07-24 at 10 43 39 AM](https://user-images.githubusercontent.com/7391891/88419746-906de400-cd9a-11ea-9568-907c8550d5f7.png)

**Comment by acerix** [comment]
I believe this existing ticket captures this need:
https://github.com/fullcalendar/fullcalendar/issues/5533
↑
Please visit the above issue, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates.

**Comment by a1devak** [comment]
Thanks @acerix for the update. That reference ticket resolved my issue.
