### ISSUE TITLE
Can i put checkbox to every event

### ISSUE THREAD

**Issue by BogartPoe** [fullcalendar/fullcalendar#5671]
### Checklist

Please mark these items with an [x]

  - [ ] Other people will find this feature useful
  - [x] I've already searched through [existing tickets](https://fullcalendar.io/issues)

### Feature Description

checkbox for every event for selecting multiple events for transferring data from a database or deleting it 

### Visual Mockups

![image](https://user-images.githubusercontent.com/32596310/88646393-aad7f280-d0f7-11ea-93a4-54856c11ba3b.png)

**Comment by BogartPoe** [comment]
https://fullcalendar.io/docs/content-injection

**Comment by ramisalem** [comment]
> https://fullcalendar.io/docs/content-injection

how to get the title of the event in eventContent?
