### ISSUE TITLE
Dynamically adding/removing slots in "timeGridWeek" view

### ISSUE THREAD

**Issue by karthick0125** [fullcalendar/fullcalendar#5678]
### Checklist

Please mark these items with an [x]

  - [x ] I've already searched through [existing tickets](https://fullcalendar.io/issues)
  - [x ] Other people will find this feature useful

### Feature Description

I want to provide provision to add/remove slots based on user selection,

 Is there any hook already available? . PFB mockup

Please describe what this feature will do.

### Visual Mockups

<img width="694" alt="scheduler" src="https://user-images.githubusercontent.com/36404516/88808557-ae8b7800-d1d0-11ea-8774-93f504bbfc68.PNG">

**Comment by acerix** [comment]
Do you mean for example if Tuesday is unchecked, it should remove that column completely?

If you just want to block some slots so events are not allowed, you could do that with background events.

**Comment by karthick0125** [comment]
Hi Acerix,

Thanks a lot for your response. Yes if the user is unchecked Tuesday, i will show them in different color.So that user cannot enter any events there,

Our business ask is dynamically add/remove slots. PFB image.

 For an example,if the user wants to add one more slot (slot 6) on "9:00", then I need to insert one more row between "9:00 slot 5" and "12:00 slot1".

Is there a way to do this?

<img width="639" alt="Custom Slots" src="https://user-images.githubusercontent.com/36404516/89013621-d1816d80-d331-11ea-94b6-79e01dd80925.PNG">
Example

**Comment by acerix** [comment]
You can use background events or business hours to block some time slots.  

There is no built-in view like that, but you could use "resources" for each of those slots, and just add the events as "all day" events (not using the actual start time of the slot).  Another option is to make a custom view.

**Comment by karthick0125** [comment]
Thanks a lot Dylan. let me try with those options
