### ISSUE TITLE
Installing with webpacker is missing core/main.css

### ISSUE THREAD

**Issue by ChielHackman** [fullcalendar/fullcalendar#5680]
### Reduced Test Case

not reproducible with a link

### Bug Description

I created a new rails application and use webpacker to handle JS and CSS files.
With yarn I added fullcalendar core, daygrid, timegrid and list by executing the following command:
`yarn add @fullcalendar/core @fullcalendar/daygrid @fullcalendar/timegrid @fullcalendar/list`

What I expect to happen is that node_modules/@fullcalendar/core/main.css and node_modules/@fullcalendar/core/main.min.css exists, but they don't. The css for daygrid, timegrid and list do exists.

### Screenshots

![Screenshot from 2020-07-31 09-04-05](https://user-images.githubusercontent.com/16886513/89009496-f4e5f180-d30c-11ea-8064-d905bec558e2.png)

**Comment by acerix** [comment]
There is no `core/main.css`, the common CSS is in `common/main.css`.
