### ISSUE TITLE
In date range Start Time and End Time is not displaying in end date. Why?

### ISSUE THREAD

**Issue by dbhautik** [fullcalendar/fullcalendar#5687]
### Reduced Test Case

https://jsfiddle.net/Lxwkbq3r/

### Bug Description

I have multiple dates ranges data that I am displaying in the full calendar but start time and end time is displaying in the start date cell but not displaying in the end date cell.

![Edit-fiddle-JSFiddle-Code-Playground](https://user-images.githubusercontent.com/38677295/89109552-cb89aa80-d45f-11ea-8334-d7fc5b73b6a8.png)

**Comment by acerix** [comment]
It may be a bug in that old version, works as expected with current:

https://codepen.io/acerix/pen/MWyWKvw?editors=001

**Comment by dbhautik** [comment]
thanks @acerix
I am using v3.5.0. any chance to fix in this version?

**Comment by acerix** [comment]
Version 3 is no longer updated, you need to upgrade to get the latest fixes.
