### ISSUE TITLE
Unknown option 'resources' when updating to v5.2.1

### ISSUE THREAD

**Issue by heybourn** [fullcalendar/fullcalendar#5692]
### Reduced Test Case

Not reproducible with a link

### Bug Description

I'm using FullCalendar with Vue. After updating to v5.2.1 my calendar is no longer rendering and I'm getting some unknown option warnings in console. 

Here's how I was using the options in the previous version:

` const calendarOptions1 = computed<CalendarOptions>(() => ({
      ...calendarOptions,
      eventClick,
      resources: calendarResources.value as unknown,
      events: calendarEvents.value as unknown,
      initialDate: currentDate.value,
      initialView: currentView.value,
      headerToolbar: {
        left: 'prev,next today',
        center: 'title',
        right:
          'resourceTimeGridDayCustom,resourceTimelineDayCustom,timeGridWeek',
      },
      datesSet: function (dateInfo: DatesSetArg) {
        currentDate.value = dateInfo.start
        currentView.value = dateInfo.view.type
      },
    }))`

### Screenshots

<img width="404" alt="Screen Shot 2020-08-03 at 12 55 13 PM" src="https://user-images.githubusercontent.com/14102410/89136592-94fb7f00-d588-11ea-9a05-09bcf23a6053.png">

**Comment by acerix** [comment]
Would you be able to post a [runnable, stripped-down demonstration of the bug](http://fullcalendar.io/wiki/Reduced-Test-Cases/)? Would really appreciate it because the time saved reproducing will be time spent fixing.
