### ISSUE TITLE
[DEP0097] DeprecationWarning: 

### ISSUE THREAD

**Issue by girizano** [fullcalendar/fullcalendar#5694]
### Reduced Test Case

 "not reproducible with a link". The error appears on the Wix backend Site Monitor under my user, cannot give you access.

### Bug Description
I retrieve data from a Wix Db, hosted on a different domain than where I have the fullcalendar code running (cdn.jsdelivr) using a call to a http-get listener, like so:
        resources: 'https://[sitename]/_functions/resources',
        events: 'https://[sitename]/_functions/events',

Works perfectly, but in Wix backend Site Monitor (and Google Stack Driver) an error appears:
["(node:1) [DEP0097] DeprecationWarning: Using a domain property in MakeCallback is deprecated. Use the async_context variant of MakeCallback or the AsyncResource class instead."]

Have researched the matter and it seems it has something to do with the node.js version used (v8-v10). EDIT: where Wix is using V10.
Am using fullcalendar 5.0.

Could you have a look at this?

**Comment by acerix** [comment]
We would need a way to reproduce the error but nodejs is not required, so it doesn't sound like a bug in the calendar.  You should be able to include the calendar as described here:

https://fullcalendar.io/docs/initialize-globals

**Comment by girizano** [comment]
I truly believe I did all that you proposed in the docs. Would you be OK
with it if I set up a test environment in Wix, so you can see for yourself?
I would need to email you username/password.

Thanks


<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Libre
de virus. www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by acerix** [comment]
It would need to be a publicly accessible demo, could you not make a public page?  It's best if you can import the scripts into something like codepen and recreate the error there.
