### ISSUE TITLE
don`t show all day of month in dayGridMonth after change local to 'fa'

### ISSUE THREAD

**Issue by rahimzade** [fullcalendar/fullcalendar#5698]
[### Reduced Test Case](https://codesandbox.io/s/sleepy-monad-jjtqf)

### Bug Description

in the fullcalendar 5 when I change local to "fa", the first day of the month not start via "1"! such as the image below 
in 'fa' local, don't show all day of the current month and show part of the current month and next month

### Screenshots
![2020-08-06_13-39-16](https://user-images.githubusercontent.com/40488188/89540080-d5216280-d811-11ea-8fca-3309e00ff47b.png)

**Comment by acerix** [comment]
I believe this existing ticket captures this need:
https://github.com/fullcalendar/fullcalendar/issues/1813
↑
Please visit the above issue, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates.
