### ISSUE TITLE
Viewing the calendar in the medal bootstrap has a bug

### ISSUE THREAD

**Issue by KAJOOSH** [fullcalendar/fullcalendar#5704]
### Reduced Test Case

 [REDUCED TEST CASE]("")

### Bug Description

Viewing the calendar in the medal bootstrap has a bug
Height is a problem
Previously, there was no problem in version v5.1.0

### Screenshots

![1](https://user-images.githubusercontent.com/47478490/89757970-f3ca7680-dafb-11ea-9e95-7bcbf374a68b.jpg)

**Comment by acerix** [comment]
Your test case link is broken, please post a [runnable, stripped-down demonstration of the bug](http://fullcalendar.io/wiki/Reduced-Test-Cases/).
