### ISSUE TITLE
Alignment of events in dayGridWeek when weekNumbers:true

### ISSUE THREAD

**Issue by johneriksson** [fullcalendar/fullcalendar#5708]
### Reduced Test Case
https://codepen.io/johneriksson_codepen/pen/KKzdzOz?editors=0010

### Bug Description
View: dayGridWeek
Settings: enable weekNumbers

In the latest version (screenshot 1), the events don't align with the events on the first day. Previously, "Event 2" would be moved down one row. There is also a fc-daygrid-day-number indicator on the first day, which looks weird imo. I can't find any mention of this in the release notes so based on that (and because I think it looks weird) I assume this was not intentional. If it is intentional, how can I get the same behaviour as in v4 now that `weekNumbersWithinDays` is gone?

### Screenshots
Screenshot 1.
FullCalendar v5 with `weekNumbers: true`
<img width="1121" alt="Screenshot 2020-08-11 at 09 26 12" src="https://user-images.githubusercontent.com/12858837/89870100-a27ebd80-dbb5-11ea-9b16-8e6a7e4c022f.png">

Screenshot 2.
FullCalendar v4 with `weekNumbers: true` and `weekNumbersWithinDays: true`
<img width="1121" alt="Screenshot 2020-08-11 at 09 39 14" src="https://user-images.githubusercontent.com/12858837/89870786-a6f7a600-dbb6-11ea-8dd2-a236fe620a2f.png">

**Comment by arshaw** [comment]
confirmed. i'll try to fix this for the next minor release

**Comment by arshaw** [comment]
this has been fixed in [5.3.0](https://github.com/fullcalendar/fullcalendar/releases/tag/v5.3.0)

demo: https://codepen.io/arshaw/pen/QWNyNOo?editors=0010

**Comment by johneriksson** [comment]
Cool! I appreciate the quick response :)
