### ISSUE TITLE
select: resource.id 

### ISSUE THREAD

**Issue by ketna11** [fullcalendar/fullcalendar#5722]
### Reduced Test Case

https://codepen.io/ketna11/pen/zYqrPLp?editors=0011

### Bug Description

If you use both: Fullcalendar and Scheduler views. You can not use the same code for getting resource.id, becuse it gives error on all Fullcalendar views and whole select function does not return anything:

select: function(info) { alert(info.startStr+'/'+info.endStr+'/'+info.resource.id); },

**Comment by acerix** [comment]
`info.resource` is only set for views that have resources, you can check if it exists like `if (info.resource)`.

**Comment by ketna11** [comment]
I have tried this before. Unfortunately it does not work:
https://codepen.io/ketna11/pen/zYqrPLp?editors=0011

**Comment by acerix** [comment]
It seems to work as expected, what is the issue? You also need `else` if you want it to do something when there is no resource.
