### ISSUE TITLE
Warning: Attempting to call a FullCalendar method on an element with no calendar.

### ISSUE THREAD

**Issue by amirakbulut** [fullcalendar/fullcalendar#5730]
### Reduced Test Case

Not reproducible with a link, because it's built in Nuxt.js.

### Bug Description
I have the following code within a Nuxt.js application:

**Template:**
```
<template>
  </div>
      <a v-on:click="switchView('listDay')">Change to Day</a>
      <FullCalendar id="agenda"/>
  </div>
</template>
```

**Script:**
```
<script>
import FullCalendar from "@fullcalendar/vue";
import timeGridPlugin from "@fullcalendar/timegrid";
import dayGridPlugin from "@fullcalendar/daygrid";
import listPlugin from "@fullcalendar/list";

export default {
  components: {
    FullCalendar
  },
  methods: {
    switchView($value) {
      $("#agenda").fullCalendar("changeView", $value);
    }
  },
  data() {
    return {
      calendarOptions: {
        plugins: [timeGridPlugin, dayGridPlugin, listPlugin],
        initialView: "listWeek",
      }
    };
  }
};
</script>
```

The calendar renders correctly, however: when I trigger the `switchView()` function, instead of changing the actual view it returns the warning:

```
Attempting to call a FullCalendar method on an element with no calendar.
```

The same warning occurs when just running `$("#agenda").fullCalendar("changeView", $view);` through my browser console.

I think it has something to do with Nuxt.js being server side rendered, I tried wrapping the `<FullCalendar/>` component with `no-ssr` tags, but without any luck.

### Screenshots

![](https://i.imgur.com/J3nSiAq.png)

**Comment by acerix** [comment]
The code like `$("#agenda").fullCalendar("changeView"` is from version 3, this explains how to use the API in Vue:

https://fullcalendar.io/docs/vue#calendar-api

If there is a bug, please supply a [runnable, stripped-down demonstration](http://fullcalendar.io/wiki/Reduced-Test-Cases/) or steps to reproduce the error.

**Comment by amirakbulut** [comment]
> The code like `$("#agenda").fullCalendar("changeView"` is from version 3, this explains how to use the API in Vue:
> 
> https://fullcalendar.io/docs/vue#calendar-api
> 
> If there is a bug, please supply a [runnable, stripped-down demonstration](http://fullcalendar.io/wiki/Reduced-Test-Cases/) or steps to reproduce the error.

Thanks, I got it working using the API.

Can you help me understand why it didn't work my way?

**Comment by acerix** [comment]
The jQuery code is from v3 and no longer works:

https://fullcalendar.io/docs/v4/upgrading-from-v3#core-changes
