### ISSUE TITLE
Date Profile Range in Custom View Component Different from Range Used to Load Events

### ISSUE THREAD

**Issue by justinneff** [fullcalendar/fullcalendar#5735]
### Reduced Test Case

https://codesandbox.io/s/fullcalendar-custom-component-date-profile-od8rh

### Bug Description

I have created a custom view using a React component. In the props received by the React component, the `start` and `end` dates of the `dateProfile.activeRange` and `dateProfile.currentRange` do not match the `start` and `end` dates that are provided to the events function to load events.

It appears to have something to do with the time zone. The dates provide to events function have been adjusted to reflect midnight in the local time zone while the `dateProfile` is reflecting midnight UTC. The screenshot below shows the ISO strings of the dates being received. The time zone in the screenshot is America/Chicago (UTC-5).

My expectation is that the `dateProfile` range dates would match the `start` and `end` range used when loading events.

### Screenshots

![image](https://user-images.githubusercontent.com/8649832/90658094-c458ef80-e208-11ea-81a7-007ced1d1b1c.png)

**Comment by acerix** [comment]
I believe this is the expected behavior:
- `activeRange` and `currentRange` are for display, so are in local time
- The `start and `end` for fetching events are in UTC, but there is also `startStr` and `endStr` in local time

https://codepen.io/acerix/pen/eYZBzjY?editors=0011
