### ISSUE TITLE
Option for day cells to work as navLinks

### ISSUE THREAD

**Issue by RusakovDenis** [fullcalendar/fullcalendar#5742]
Hi,

Click on the cell with the transition to the schedule of the day?

Now it is obligatory to click on the number, but I would like to click on the entire cell

### Checklist

Please mark these items with an [x]

  - [ ] I've already searched through [existing tickets](https://fullcalendar.io/issues)
  - [ ] Other people will find this feature useful

### Feature Description

Please describe what this feature will do.

### Visual Mockups

If you are requesting a new UI, please include a mockup.
If not, erase this section.

**Comment by acerix** [comment]
Do you mean having [navLinks](https://fullcalendar.io/docs/navLinks) work by clicking anywhere on a day cell?

**Comment by RusakovDenis** [comment]
yeah

>
