### ISSUE TITLE
Chrome/Edge - FullCalendar resourceTimeline freezes locally

### ISSUE THREAD

**Issue by fwd079** [fullcalendar/fullcalendar#5745]
Good morning,

Locally used npm, but here providing CodePen, both produce same error in Chrome/Edge.

### Reduced Test Case

Posted [Code Pen Link](https://codepen.io/fwd079/pen/rNeyLYo).

### Bug Description

Describe how to recreate the bug.

- From jsdelivr, copy `https://cdn.jsdelivr.net/npm/fullcalendar-scheduler@5.3.0/main.min.js` into code pen
- Rest is in CodePen linked above.

What do you expect to happen?

Navigation to work.

What happens instead?

Freezes in Chrome/Edge (works locally in Opera, Firefox even in older Internet Explorer).

### Screenshots

Freezes on Chrome/Edge when working locally and eventually a "exit page/awe snap" error. But running inside CodePen gives this error:

![image](https://user-images.githubusercontent.com/7912632/91162412-f617fd80-e6c3-11ea-9670-967d5fd1e60b.png)

Just _guessing_, but maybe the npm/CDNs are not pushed correctly? Because clicking on that link takes me to min,.js which has a signature which shows a version older than 5.3.0 as seen here:

![image](https://user-images.githubusercontent.com/7912632/91162617-37a8a880-e6c4-11ea-8d31-0819a860982b.png)

As said it's a maybe, because same code works  locally on Firefox, Opera and even older Internet Explorer. But broken on CodePen/Chrome/Edge.

Kind Regards.

**Comment by acerix** [comment]
The error is from your demo using an old version of the CSS, same code works with updated CSS file:

https://codepen.io/acerix/pen/LYNypQK?editors=001

I believe that code on jsdelivr is actually version 5.3.0 since it has new bug fixes, so it's just showing the wrong version number so will leave this issue open for that.

**Comment by fwd079** [comment]
Oh okay, thanks. Well the code doesn't work in local Chrome/Edge and I am using TypeScript instead of pure JS in your TypeScript example, and it just freezes. So I need to change the bug heading again.

Kind Regards.

**Comment by acerix** [comment]
If there is a bug, please supply a [runnable, stripped-down demonstration](http://fullcalendar.io/wiki/Reduced-Test-Cases/) or steps to reproduce the issue.

**Comment by fwd079** [comment]
Strange. If you wanted me to reproduce the issue  then why did you close this instead of awaiting my response?

I was trying to convince a client to buy this product but needed to make sure this works first.  Very strange.

**Comment by acerix** [comment]
Our policy is to close any bug reports without a demo, I can reopen when you have one.

**Comment by arshaw** [comment]
I made a separate issue about the version numbers: https://github.com/fullcalendar/fullcalendar/issues/5778
