### ISSUE TITLE
Back button doesn't work with custom dayCount on timeGrid

### ISSUE THREAD

**Issue by woodspire** [fullcalendar/fullcalendar#5748]
### Reduced Test Case

https://codepen.io/flabrecque/pen/OJNpOrj

### Bug Description

Click on the back button more than once. It will get back once, after that it won't. Clicking on next will work, and then, you can go back only once.

**Comment by acerix** [comment]
I believe this existing ticket captures this need:
https://github.com/fullcalendar/fullcalendar/issues/5319
↑
Please visit the above issue, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates.
