### ISSUE TITLE
contentHeight option did not effect timeGridWeek/timeGridDay views

### ISSUE THREAD

**Issue by darkengine** [fullcalendar/fullcalendar#5750]
### Reduced Test Case

Codes in codepen:
https://codepen.io/stonelam/pen/LYNWdME

### Bug Description

Call "calendar.setOption('contentHeight', 2000);" or set "    contentHeight: '2000px'," when initiating fullcalendar.### Screenshots. In dayGridMonth view the height of cells got expand and fulfill content view. But cells in timeGridWeek and  timeGridDay remain same height and leave a blank area in content view.

dayGridMonth:
<img width="666" alt="image" src="https://user-images.githubusercontent.com/1203994/91240529-de4c8200-e774-11ea-820a-3937f7c9c2a2.png">

timeGridWeek:
<img width="651" alt="image" src="https://user-images.githubusercontent.com/1203994/91240566-f02e2500-e774-11ea-8116-2b6f77c34761.png">

**Comment by acerix** [comment]
You need to set `expandRows: true` for that

https://codepen.io/acerix/pen/qBZPEWJ
