### ISSUE TITLE
Iterate instead of enumerating array to play nicely with 3rd party utility libraries

### ISSUE THREAD

**Issue by pixel9** [fullcalendar/fullcalendar#5752]
### Reduced Test Case
https://codepen.io/pixel9/pen/rNemOGr

### Bug Description
Fullcalendar fails to load and `updateSize is not a function` error is thrown.

Describe how to recreate the bug.
- scheduler is configured with setting `height: '100%'`
- scheduler is running in an environment where `Array.prototype` is being modified (various 3rd party utility libraries and environments routinely do this - even though we can agree it's a dangerous thing to do)

The fix would be to iterate the array here:
https://github.com/fullcalendar/fullcalendar-scheduler/blob/7f0aec653338d0041e289ca075180c4d7ce04b0a/scrollgrid/src/ScrollGrid.tsx#L521

Like so:
```js
...
    for (let i = 0; i < stickyScrollings.length; i++) {
      stickyScrollings[i].updateSize()
    }
...
```

This will iterate the items of the array as intended instead of enumerating its keys and unintentionally including environment-specific Array prototype methods.

**Comment by pixel9** [comment]
https://javascript.info/array#loops

Looks like a `for...of` would work as well if avoiding an index local variable is desired.

**Comment by pixel9** [comment]
Confirmed that this work as intended:

```js
    for (let scroller of stickyScrollings) {
      scroller.updateSize()
    }
```

**Comment by pixel9** [comment]
this 1 liner would work as well:
```js
stickyScrollings.forEach(scroller => scroller.updateSize())
```

If you guys have a preferred solution I'll issue a PR to help out. Please let me know!

**Comment by acerix** [comment]
I believe this existing ticket captures this need:
https://github.com/fullcalendar/fullcalendar/issues/5601
↑
Please visit the above issue, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates.
