### ISSUE TITLE
Error "https://registry.yarnpkg.com/rxjs/-/rxjs-6.5.5.tgz: unexpected end of file" on yarn install

### ISSUE THREAD

**Issue by BruceRBowers** [fullcalendar/fullcalendar#5760]
This is a bug in the standard build process, but "I love FullCalendar".

This is a follow-up to issue #5749: Error "failed to create symbolic link 'node_modules/@fullcalendar/angular'" in standard build process

In issue #5749, the responder pointed to issue #5504, which does seem to be the same problem. However, when I follow the new build steps mentioned in issue #5504, I get an error:

$ yarn install
yarn install v1.22.5
[1/4] 🔍 Resolving packages...
[2/4] 🚚 Fetching packages...
error An unexpected error occurred: "https://registry.yarnpkg.com/rxjs/-/rxjs-6.5.5.tgz: unexpected end of file".
info If you think this is a bug, please open a bug report with the information provided in "/Users/bbowers/gitworkspaces/temp/fullcalendar/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.

Here is the contents of yarn-error.log:
Arguments:
/usr/local/bin/node /usr/local/Cellar/yarn/1.22.5/libexec/bin/yarn.js install

PATH:
:.:/gitworkspaces:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/.npm-packages:/.npm-packages/bin

Yarn version:
1.22.5

Node version:
12.13.1

Platform:
darwin x64

Trace:
Error: unable to verify the first certificate
at TLSSocket.onConnectSecure (_tls_wrap.js:1321:34)
at TLSSocket.emit (events.js:210:5)
at TLSSocket._finishInit (_tls_wrap.js:794:8)
at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:608:12)

npm manifest:
{
"name": "gbu-ui-3rd-party-libs-collection",
"version": "2.0.0",
"description": "An Oracle JavaScript Extension Toolkit(JET) web app",
"dependencies": {
"@oracle/oraclejet": "^9.0.0"
},
"devDependencies": {
"@oracle/oraclejet-tooling": "^9.0.0",
"@oracle/ojet-cli": "^9.0.0",
"@types/node": "^12.11.2",
"@typescript-eslint/eslint-plugin": "^2.3.3",
"@typescript-eslint/parser": "^2.3.3",
"eslint": "^6.5.1",
"typescript": "^3.6.3"
},
"engines": {
"node": ">=0.10.0"
},
"private": true,
"scripts": {
"build": "npm clean-install && ojet build web",
"check-licenses": ". scripts/licenses/check-licenses.sh",
"deposit-source-code": "scripts/source-code-deposit/deposit-source-code.sh",
"get-npm-package-info": "scripts/licenses/get-npm-package-info.sh",
"oscsscan": "scripts/oscsscan.sh",
"malware-client": "sh scripts/oscs_win64_malware_client.sh",
"publish-component": ". scripts/publish-component.sh",
"rebuild-library": ". scripts/rebuild/rebuild-library.sh"
}
}

yarn manifest:
No manifest

Lockfile:
No lockfile

--------------------

Here is the last comment from issue #5749:

I believe this existing ticket captures this need:
#5504
↑
Please visit the above issue, give a 👍 to vote (?), press the 🔈Subscribe button to receive updates.

Originally posted by @acerix in #5749 (comment)

**Comment by acerix** [comment]
`yarn install` is working for me.  The error is saying you can't make a secure connection to https://registry.yarnpkg.com/ which is a problem on your system such as incorrect date.
