### ISSUE TITLE
Alphabetic ordering for events in more popover

### ISSUE THREAD

**Issue by cchlam** [fullcalendar/fullcalendar#5767]
### Reduced Test Case
Link for full calendar v3: https://codepen.io/lch0/pen/vYGmPNM
Link for full calendar v5: https://codepen.io/lch0/pen/MWymxEO

### Bug Description
`eventOrder: "title"`

Both of the codes are sorted by title. Let's focus on Aug 24. If i press "+2 more" of Aug 24 in v3, it is sorted in the order of "Ca-->Cl-->Ev-->Ma-->Wi" which is correct.

However, if i press "+2 more" of Aug 24 in v5, it is sorted in the order of "Ca-->Wi-->Cl-->Ev-->Ma" which is incorrect.

Also, both of the codes cannot be sorted by "title" in calandar view.

### Screenshots
v3 before clicking "add more":
Expected: sorted by "title"
Actual: NOT sorted by "title"
![image](https://imagizer.imageshack.com/img924/1331/2Mpjth.png)

v3 after clicking "add more":
Expected: sorted by "title"
Actual: sorted by "title", correct!
![image](https://imagizer.imageshack.com/img923/2434/vUaDj0.png)

v5 before clicking "add more":
Expected: sorted by "title"
Actual: NOT sorted by "title"
![image](https://imagizer.imageshack.com/img922/79/9ElL98.png)

v5 after clicking "add more":
Expected: sorted by "title"
Actual: NOT sorted by "title"
![image](https://imagizer.imageshack.com/img923/3226/yrK09p.png)

**Comment by arshaw** [comment]
I thought this would be fixed in v5 with the new `eventOrderStrict` flag, but it seems there are some problems:
https://codepen.io/arshaw/pen/rNyxNvy?editors=0010

I will fix this in a follow-up bugfix release

**Comment by arshaw** [comment]
finally fixed in [v5.8.0](https://github.com/fullcalendar/fullcalendar/releases/tag/v5.8.0)

updates repro:
https://codepen.io/arshaw/pen/KKWbjPQ?editors=0010
