### ISSUE TITLE
Adding custom classes to an event

### ISSUE THREAD

**Issue by piernik** [fullcalendar/fullcalendar#5769]
### Reduced Test Case

https://codepen.io/piernik/pen/NWNvrpq?editors=0011

### Bug Description

I want to add classes to event. So I use eventContent in CalendarOptions.
But fullcalendar seems to freeze when I use:
```
private eventRenderFunc(info: EventResizeDoneArg | EventDropArg) {
    info.event.setProp('classNames', 'zadanie');
}
```
How can I add custom classes to event in `fullcalendar@5` ?

**Comment by acerix** [comment]
That causes a loop since setProp forces another render, you should use `eventClassNames` for that.

https://fullcalendar.io/docs/event-render-hooks
