### ISSUE TITLE
Cannot find gotoDate function in Calender v5 API

### ISSUE THREAD

**Issue by choudharypravesh03** [fullcalendar/fullcalendar#5773]
<img width="1397" alt="Screen Shot 2020-09-01 at 12 32 56 PM" src="https://user-images.githubusercontent.com/3882721/91813021-a3a08900-ec4f-11ea-8647-b94862c8260a.png">

I am trying to access calender API using ref as above. I need to use gotoDate. It does not work. When I console log `this.calendarRef.current.getApi()`, I get the above screenshot. Can anyone help on how can I access `gotoDate()`

**Comment by hashweather** [comment]
I'm stucked on this as well. Any ideas on these?
