### ISSUE TITLE
Duplicated event after eventDrop

### ISSUE THREAD

**Issue by sebap100** [fullcalendar/fullcalendar#5789]
### Reduced Test Case

https://codesandbox.io/s/gracious-smoke-379l6?file=/src/App.jsx

#### Reproduction scenario:
- Drag&drop the event to a different time slot.
- Immediately, drag the same event and keep it dragging for at least one second.
- Drop the event to a different time slot.
- The event is unwillingly duplicated.

### Bug Description

The events are stored in the React's Component state as an array and are given to FullCalendar through the _events_ props.

```jsx
const [events, setEvents] = useState([
    {
      id: "1",
      start: "2020-09-08T08:00:00Z",
      end: "2020-09-08T10:00:00Z"
    }
  ]);

...

return <FullCalendar events={events} eventDrop={eventDrop} />
```
When the user drag&drop an existing event to a different time slot in the calendar, the update needs to be saved in my remote database. Thus, a call to my remote API is made in the _eventDrop_ callback. On the API success response, the events state array must be also updated to be synchronized with my remote database.

```jsx
function eventDrop(arg) {
    saveInRemoteApi(arg.event).then(() => {
        // Update event in state
        setEvents(...);
    });
}
```
However, if the same event is being dragged again before getting the response of the remote API related to the first drag, FullCalendar duplicates the event. Indeed, if we check the number of events using the FullCalendar API, there are 2 events although there is only one the events array in the state.

### Screenshots

<img width="400" alt="Capture d’écran 2020-09-07 à 03 37 48" src="https://user-images.githubusercontent.com/22453241/92340708-c541ba80-f0fe-11ea-8f12-3d62992114b0.png">
<img width="400" alt="Capture d’écran 2020-09-07 à 03 36 30" src="https://user-images.githubusercontent.com/22453241/92340680-ac390980-f0fe-11ea-8f70-2f30a4f70ae2.png">
<img width="400" alt="Capture d’écran 2020-09-07 à 03 37 08" src="https://user-images.githubusercontent.com/22453241/92340678-aba07300-f0fe-11ea-9731-6f37742fdd73.png">

**Comment by iiibbbmmm** [comment]
I didn't get the point of
```javascript
        if (event.id === arg.event.id) {
          return Object.assign({}, event, {
            start: arg.event.start,
            end: arg.event.end
          });
        }
```
If a event from remote match the id of droped one, create a new one?
Why not update the exists `arg.event`? Either hovering or released.

**Comment by sebap100** [comment]
> I didn't get the point of
> 
> ```js
>         if (event.id === arg.event.id) {
>           return Object.assign({}, event, {
>             start: arg.event.start,
>             end: arg.event.end
>           });
>         }
> ```
> 
> If an event from remote match the id of droped one, create a new one?
> Why not update the exists `arg.event`? Either hovering or released.

The update of the state is done by creating a new event object just to respect the React immutability of the state (it is better than directly changing the state object).

This is not the point of the issue. The problem here is that FullCalendar creates internal events that are not part of its **_events_** data source (i.e, the events array given to its _**events**_ props).

**Comment by iiibbbmmm** [comment]
I mean
```javascript
        if (event.id === arg.event.id) {
          let start = arg.event.start;
          let end = arg.event.end;
          return Object.assign(arg.event, event, {
            start: start,
            end: end
          });
        }
```

**Comment by acerix** [comment]
I believe the issue is specific to React and is this existing ticket captures this need:
https://github.com/fullcalendar/fullcalendar-react/issues/91
↑
Please visit the above issue, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates.

**Comment by Herz3h** [comment]
I have same issue using fullcalendar-vue 5.3.0

**Comment by Herz3h** [comment]
@acerix could we reopen ? The issue also exists on vuejs and probably exists on default js version aswell
