### ISSUE TITLE
more link sometimes incorrectly positioned behind events

### ISSUE THREAD

**Issue by arshaw** [fullcalendar/fullcalendar#5790]
in daygrid:

https://codepen.io/arshaw/pen/MWyrGGp?editors=0010

**Comment by arshaw** [comment]
fixed in 5.3.2

**Comment by Jogai** [comment]
5.3.2 is not on NPM..

**Comment by arshaw** [comment]
yes it is. it only affected the daygrid package

bunde: https://www.npmjs.com/package/fullcalendar
individual @fullcalendar/daygrid package: https://www.npmjs.com/package/@fullcalendar/daygrid
