### ISSUE TITLE
Timeline view without resources and height auto does not display area for events

### ISSUE THREAD

**Issue by kgilden** [fullcalendar/fullcalendar#5792]
### Reduced Test Case

https://repl.it/@kgilden/fullcalendar-5792

### Bug Description

Setting `height: 'auto'` in a `timeline` view with no resources ([docs](https://fullcalendar.io/docs/timeline-view-no-resources)) causes the height of the calendar to collapse to 0 even though there are events to be displayed. Events themselves are correctly rendered. It's the container that for some reason is computed to have 0 height.

### Screenshots

![2020-09-07_13-16](https://user-images.githubusercontent.com/918599/92377146-5c613f00-f10c-11ea-8c1f-db62468f23a8.png)

**Comment by iiibbbmmm** [comment]
According to [https://github.com/fullcalendar/fullcalendar-scheduler/blob/32d55044b3c025c5014d6a3f1dfbb3db1c2f5a09/timeline/src/TimelineGrid.tsx#L41](https://github.com/fullcalendar/fullcalendar-scheduler/blob/32d55044b3c025c5014d6a3f1dfbb3db1c2f5a09/timeline/src/TimelineGrid.tsx#L41)
`.fc-timeline-body` render first, considered clientHeight at this moment as fixed height.
With no events rendered, yet, the clientHeight should be 1px if set to `'auto'`

**Comment by acerix** [comment]
Thanks, confirmed. Same in the debug template:

https://codepen.io/acerix/pen/ZEWroZK

**Comment by arshaw** [comment]
I have an idea of how to fix this. I'll attempt a fix for the next minor release.

NOTE TO SELF: forget fancy row-height-syncing. Use the `fgHeight` in TimelineLane and somehow send it up to the TimelineGrid parent (aka fc-timeline-body) somehow.

**Comment by arshaw** [comment]
This is now fixed in [5.11.3](https://github.com/fullcalendar/fullcalendar/releases)

[Updated repro](https://codepen.io/arshaw/pen/gOeygbV)
