### ISSUE TITLE
Could not find module in path: 'rrule' relative to '/node_modules/@fullcalendar/rrule/main.js'

### ISSUE THREAD

**Issue by meness** [fullcalendar/fullcalendar#5793]
### Reduced Test Case

https://codesandbox.io/s/quizzical-shamir-dice9?file=/src/App.js

### Bug Description

After upgrading to the latest version, I get this exception while `rrule` package is already installed. Both packages are up-to-date.

**Comment by arshaw** [comment]
please see:
https://github.com/fullcalendar/fullcalendar/issues/5777
&uarr;
Could you please visit the link, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates?
