### ISSUE TITLE
slotLabelFormat does not take effect when locale is'zh-cn'

### ISSUE THREAD

**Issue by LiXunGuan** [fullcalendar/fullcalendar#5795]
### Reduced Test Case
https://codepen.io/lixunguan/pen/dyMdMjy.

### Bug Description

When I set the 'locale' to 'zh-cn', I found that lotLabelFormat does not take effect.

### Screenshots
![1](https://user-images.githubusercontent.com/7980846/92437620-f2af6680-f1d9-11ea-8d01-fd8ea03e20ed.png)
![2](https://user-images.githubusercontent.com/7980846/92437625-f4792a00-f1d9-11ea-9650-5dac7194e69d.png)

**Comment by iiibbbmmm** [comment]
```javascript
hour12: false
```

**Comment by LiXunGuan** [comment]
Thanks @iiibbbmmm
```javascript
                slotLabelFormat: {
                    hour: '2-digit',
                    minute: '2-digit',
                    hour12: false
                },
```
