### ISSUE TITLE
Scroll position changes after moving an event to another resource

### ISSUE THREAD

**Issue by aetasoul** [fullcalendar/fullcalendar#5796]
### Reduced Test Case
Here the test case on codepen, fullcalendar V4.

[Test case one](https://codepen.io/aetasoul/pen/BaKYzjm?editors=0010)
[Test case two](https://codepen.io/aetasoul/pen/dyMdNVO?editors=0010)

### Bug Description

The problem appear in different situation:

*  Create multiple events on multiple resources **(Test case one)**
*  Create multiple events on multiple resources with multiline text **(Test case two)**

It seems that the row height is the problem, when you update the view removing all events and adding again.

**Describe how to recreate the bug.**

Scoll to the bottom of the calendar, drag&drop an event from resourse 49 to another resource, press 'Ok' or 'Abort' on the alert.

**What do you expect to happen?**

I expect that the vertical scrollbar keep the position.

**What happens instead?**

The vertical scrollbar scroll upward a little bit.

___

Any tips on how to solve this?

**Comment by acerix** [comment]
Thanks, confirmed.  As a workaround, it should work to store the scroll position when an event is dragged, and restore the same position after it is moved and events have rendered.

**Comment by aetasoul** [comment]
Thank you @acerix , I tried you suggestion but I can't figure out how to get the value of the vertical scroll position. Any tips?

I know the attribute `.scrollTop`.

**Comment by acerix** [comment]
I just noticed that your original demo is removing all events then adding them back. When the calendar has no events, it is much shorter which explains why the scroll position is changing, so it's not actually a bug in the calendar.

The `scrollTop` in your test is the vertical scroll position, you should be able to restore that after changing the events.

**Comment by aetasoul** [comment]
@acerix there is an alternative on your calendar to refresh the values without removing and adding them back? It could be useful to solve this issue. I'm using [this repository](https://github.com/stefanuebe/vaadin_fullcalendar) for vaadin that integrate your calendar.

**Comment by acerix** [comment]
If you want to refresh the event data from a database, you can provide the events as JSON and call [refetchEvents](https://fullcalendar.io/docs/Calendar-refetchEvents) to refresh them.

**Comment by aetasoul** [comment]
Thank you!

**Comment by aetasoul** [comment]
@acerix Ok, I understand what you mean, but the problem is not related to the remove/add back practice, is related to the resource row height. I think the calendar don't update the height of the row so it cause the problem.

Take a look to [this codepen](https://codepen.io/aetasoul/pen/dyMdNVO?editors=0010) you can see the problem, ignore how I update the view removing and adding the events back.

Now, on this pen try to go at line 57 and replace it with: `events.push({resourceId: x, title:'Evt' + x, start:'2019-01-01', end:'2025-01-01'});`. I have remove the `\n` from the title generation.
In this case now you can see that the problem is solved, so it is related to the row height.

Another test to show you what I mean, use the same pen and restore the line 57 to the orginal one. Now go to line 61 and replace with: `resources.push({ id:i, title:'Res\n' + i, color:'red' });`, now the heght of the row and the height of the resource is similar, if you try to reproduce the problem you can see that the vertical scrollbar scroll just some pixels (that is acceptable).

Probably this is a waste of time for you, just take a look, if you think this is not worth to investigate just ignore it.

**Comment by acerix** [comment]
Without the line break, the events are not big enough to change the height of the resources, so removing all events does not change the total height of the calendar, and that's what's causing the scroll postion to change.
