### ISSUE TITLE
getEventById() don't return event _instance (it's impossible to get event start/end dates)

### ISSUE THREAD

**Issue by murilobd** [fullcalendar/fullcalendar#5798]
### Reduced Test Case
https://codesandbox.io/s/jovial-wood-y2nu1?fontsize=14&hidenavigation=1&theme=dark

### Bug Description

**Describe how to recreate the bug.**
Create a simple event to calendar like
```
calendarApi.addEvent({
          id: "2",
          title: "Event",
          daysOfWeek: [0, 1],
          startTime: "10:00:00",
          allDay: false
});
```
and, through fullcalendar api, get it
```
fullcalendarApi.getEventById("2");
```

**What do you expect to happen?**
It returns an Event object where I can call `event.start` and get a Date object

**What happens instead?**
It returns null (the _instance object from the returned event is null)

### Screenshots

<img width="771" alt="image" src="https://user-images.githubusercontent.com/4275011/92526712-4e8ae700-f1fc-11ea-978f-9394c3fa7c16.png">

**Comment by acerix** [comment]
Your demo shows the event in the console if I click "Get event Id" and enter "0" or "1".  It shows `null` if I enter "2", because there is no event with that id in the demo.

**Comment by murilobd** [comment]
My bad @acerix , sorry! I've updated the **Describe how to recreate the bug.**.
Basically, just click in any date to create a new event and look at the console. The new created event, don't have the _instance, so it's not possible to use event.start, event.startStr, etc...

**Comment by acerix** [comment]
Recurring events don't have a "start" which is why that is `null`, a regular event will have that:

https://codepen.io/acerix/pen/dyMmaWQ?editors=0010

**Comment by murilobd** [comment]
Understood, thanks!
It's a little bit confusing why I can see a "start" from a recurrent event if I loop through getEvents(), but I understood. The event from getEvents() returns all visible events from calendar, so that event, has a start and an end.
