### ISSUE TITLE
Not able to show weeks in a separate column in fullcalendar v5

### ISSUE THREAD

**Issue by jay-patel-aubergine** [fullcalendar/fullcalendar#5801]
### Reduced Test Case

https://codepen.io/jaypauberinge/pen/LYNQaZV

### Bug Description

I'm developing a calendar view using the fullcalendar.io v5 library in ReactJS where I want to show the week number in the separate column instead of the first column as shown in the attached screenshot.

In the v4 docs, there was an option to show weeks in the first separate column using [weekNumbersWithinDays](https://fullcalendar.io/docs/v4/weekNumbersWithinDays) but the option seems missing in the [v5 doc](https://fullcalendar.io/docs/week-number-render-hooks).

Here is my code:
```
document.addEventListener("DOMContentLoaded", function () {
  var calendarEl = document.getElementById("calendar");

  var calendar = new FullCalendar.Calendar(calendarEl, {
    plugins: ["dayGrid"],
    defaultView: "dayGridMonth",
    weekNumbers: true,
    weekNumbersWithinDays: true    // THIS IS NOT WORKING
  });

  calendar.render();
});

```

### Screenshots

![Screenshot from 2020-09-09 12-00-21](https://user-images.githubusercontent.com/66937250/92565868-ff46c400-f298-11ea-9465-4c52bff24065.png)

**Comment by acerix** [comment]
The `weekNumbersWithinDays:false` behavior has been retired in v5 as mentioned in [upgrade guide](https://fullcalendar.io/docs/upgrading-from-v4).

**Comment by jay-patel-aubergine** [comment]
Then is there any workaround??

**Comment by acerix** [comment]
You could modify the HTML with the render hooks and position them with CSS.

https://fullcalendar.io/docs/week-number-render-hooks

**Comment by MJomaa** [comment]
@acerix But those render hooks are just to change content which are already contained in the day grid cell . I don't think it is possible to create a separate column with the week numbers because it would require a HTML layout change.
