### ISSUE TITLE
Events "clipboard". Drop event to container outside fullcalendar

### ISSUE THREAD

**Issue by wojciechkoszyk** [fullcalendar/fullcalendar#5805]
### Checklist

Please mark these items with an [x]

  - [x] I've already searched through [existing tickets](https://fullcalendar.io/issues)
  - [x] Other people will find this feature useful

### Feature Description

There is a way to drop event from external source to fullcalendar using Draggable. Is there a way to do the opposite? I've got editable option set on FullCalendar instance (in React) and I would like to drag event from fullcalendar and drop it on container (just plain div with onDrop event) outside fullcalendar.

The reason is to create kind of "clipboard" for events. User can move some events to the outside container ("clipboard") then change view in fullcalendar to different date and then drop event back to fullcalendar but on new date.

**Comment by acerix** [comment]
I believe this existing ticket captures this need:
https://github.com/fullcalendar/fullcalendar/issues/3140
↑
Please visit the above issue, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates.
