### ISSUE TITLE
sticky first/last row

### ISSUE THREAD

**Issue by danikp** [fullcalendar/fullcalendar#5806]
### Checklist

Please mark these items with an [x]

  - [x] I've already searched through [existing tickets](https://fullcalendar.io/issues)
  - [x] Other people will find this feature useful

### Feature Description
Sometimes there is need to add some special resource row to calendar, it could be some summary row at the bottom or some call for action at the top. In both cases, if sticky header or footer is enabled, making those rows sticky is also make sense. So request is to add new options StickyFirstRow and stickyLastRow to make first/last resource sticky, same as stickyHeader.

there is another tickets describing something close like #5357 or #5779, but they both related to toolbars, while in case above we are keeping time grid in place and can easily show per-day stats on week view, as simplest example.

it also solves issue described in #4835

**Comment by acerix** [comment]
I believe this existing ticket captures this need:
https://github.com/fullcalendar/fullcalendar/issues/4898
↑
Please visit the above issue, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates.
