### ISSUE TITLE
Events cannot be dragged under certain conditions

### ISSUE THREAD

**Issue by LiXunGuan** [fullcalendar/fullcalendar#5809]
### Reduced Test Case
https://codesandbox.io/s/youthful-bardeen-qsv7l?file=/src/DemoApp.vue

### Bug Description
If you delete the 'FullCalendar' tag in DemoApp.vue, the'FullCalendar' in the dialog box will run normally and you can drag and drop

### Screenshots
![fullcalendar1](https://user-images.githubusercontent.com/7980846/92693926-df86cd00-f378-11ea-9536-c47cd7b5a58f.gif)

**Comment by iiibbbmmm** [comment]
Calendar in the back captures droppable, stop the front one event from dropping.
Maybe overlap calenders is not a good idea.
Try hide the back one as workaround.
```html
<FullCalendar v-show="!dialogVisible" :options="calendarOptions"/>
```

**Comment by LiXunGuan** [comment]
> Calendar in the back captures droppable, stop the front one event from dropping.
> Maybe overlap calenders is not a good idea.
> Try hide the back one as workaround.
> 
> ```
> <FullCalendar v-show="!dialogVisible" :options="calendarOptions"/>
> ```

Thank you very much for your reply.
Due to business needs, we need to add data to the dialog box, this interaction cannot be changed...
I’m wondering if there is any other way to solve this problem that cannot be dragged

![image](https://user-images.githubusercontent.com/7980846/92708969-1fee4700-f389-11ea-8204-042242de9164.png)

**Comment by iiibbbmmm** [comment]
I can't see why hiding the calender in the back, stop you from typing in the dialog...

**Comment by LiXunGuan** [comment]
The calendar behind the background is used to display data.
The user creates data in the form of a pop-up window (dialog) and closes the dialog box after creating the data.
![image](https://user-images.githubusercontent.com/7980846/92711091-e3bbe600-f38a-11ea-89c1-d970c347e9de.png)

**Comment by iiibbbmmm** [comment]
That dosn't matter, `v-show` is just a CSS property display, all data and DOM is kept intact.

**Comment by LiXunGuan** [comment]
Using v-show to display the calendar will cause rendering to crash, I will open another issue to ask questions
![fullcalendar1](https://user-images.githubusercontent.com/7980846/92717405-b96e2680-f392-11ea-8e3e-68e01739da48.gif)

**Comment by acerix** [comment]
I believe this existing ticket captures this need:
https://github.com/fullcalendar/fullcalendar/issues/5026
↑
Please visit the above issue, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates.

**Comment by iiibbbmmm** [comment]
> Using v-show to display the calendar will cause rendering to crash, I will open another issue to ask questions
> ![fullcalendar1](https://user-images.githubusercontent.com/7980846/92717405-b96e2680-f392-11ea-8e3e-68e01739da48.gif)

Adding `v-show` to your codesandbox, did not cause any crash, maybe you should create another reduced test case to make it clear.
