### ISSUE TITLE
Dropping event to allDay row sets event end to null

### ISSUE THREAD

**Issue by espen** [fullcalendar/fullcalendar#5810]
### Reduced Test Case

https://codepen.io/espen_antonsen/pen/LYNdmaQ?editors=0010

### Bug Description

Dropping event in week view to all day row will result in event data without event end.

Example:
Move all day event "Conference":
drop
all day true
End Date Thu Sep 10 2020 00:00:00 GMT+0200 (Central European Summer Time)

Move event "Meeting"
drop
all day true
End null

**Comment by acerix** [comment]
It seems to be working as expected; the hour, minutes, seconds and milliseconds are ignored for "allDay" events and in this case that makes the `end` the same as the `start` which is why it gets set to `null`.

**Comment by espen** [comment]
It is not what I am expecting for two reasons:

1) When listening to the eventDrop callback I expect to get full event details as it will be the input data to the API to update the event that has been changed.

2) As you can see from my example an allDay event *does* return the end date (with time), but not when dropped from a non allDay event to becoming an allDay event.

**Comment by acerix** [comment]
There is another property `oldEvent` in `eventDrop` to get the event data before it was moved.

The allDay events in the demo are more than 1 day long which is why they have an end date.  It only includes a time because JavaScript doesn't have "date without time".

**Comment by espen** [comment]
The oldEvent is not relevant. I use data from eventDrop to update the database with the new event information.

Yes the other event in the example has an end date. But this is inconsistent behaviour. Some events have end date, others do not.

I think all events should have end date. Including allDay events and events set without end date (they get a calculated end date based on standard event duration I assume). The reason for this is for consistency and also due to the fact they actually have an end date.

The current behaviour means I have to find the end date myself. While not difficult it does complicate a bit more (if no end date, then check allDay set endDate to end of startDate or if not allDay then set end to startDate + default event duration), but I still think it would be expected behaviour to get both start and end of an event when retrieving event info from a calendar.

(when i write date here I refer to JS date with full timestamp)

**Comment by arshaw** [comment]
@espen, this setting will likely solve all your problems:

https://fullcalendar.io/docs/forceEventDuration

**Comment by espen** [comment]
@arshaw indeed 🥳Wasn't aware of this setting.

(IMHO this should default to true, due to reasons explained above)

**Comment by RoughIndustries** [comment]
Just ran into this.  Thanks for getting this documented guys.
