### ISSUE TITLE
Loading the fullcalendar with dynamic components in vue will cause the layout to crash

### ISSUE THREAD

**Issue by LiXunGuan** [fullcalendar/fullcalendar#5811]
### Reduced Test Case
example1: https://codesandbox.io/s/fullcalendar-destroy-demo-b4yfj?file=/src/DemoApp.vue
example2: https://codesandbox.io/s/fullcalendar-vue-dynamic-load-jut0g?file=/src/DemoApp.vue

### Bug Description
Click on the "预约看板" on the left to dynamically load the dashboard.vue component, and find that the layout of fullcalendar is messy
### Screenshots
![fullcalendar1](https://user-images.githubusercontent.com/7980846/92920279-9ad86000-f464-11ea-8b5f-9d04f0a68ffe.gif)

**Comment by acerix** [comment]
It looks like you need to call `updateSize` after the calendar is displayed.

https://fullcalendar.io/docs/updateSize

**Comment by LiXunGuan** [comment]
> It looks like you need to call `updateSize` after the calendar is displayed.
> 
> https://fullcalendar.io/docs/updateSize

Thank you for your answer.
After using the updateSize method, it remains the same, the page has not changed
```javascript
    updateSize() {
      let api = this.$refs.calendar.getApi();
      if (api) {
        api.updateSize();
      }
    }
```

example: https://codesandbox.io/s/fullcalendar-vue-dynamic-load-updatesize-6co5z?file=/src/Dashboard.vue
