### ISSUE TITLE
Large rerenderDelay makes interaction laggy

### ISSUE THREAD

**Issue by LiXunGuan** [fullcalendar/fullcalendar#5813]
### Test Case
https://codesandbox.io/s/fullcalendar-api-slow-pxj0i?file=/src/DemoApp.vue

### Bug Description

-  Execute the gotoDate and remove methods, there is a delay of 3-5 seconds, the interactive experience is not very good
-  In the timeGridDay view, events are difficult to drag and resize, and require repeated attempts to succeed

### Event delay
![fullcalendar1](https://user-images.githubusercontent.com/7980846/92990452-4c33d000-f50f-11ea-9243-d58012ffaa48.gif)

### It takes multiple attempts to drag and resize the event
![fullcalendar2](https://user-images.githubusercontent.com/7980846/92990572-17744880-f510-11ea-9c96-7205363e0960.gif)

**Comment by iiibbbmmm** [comment]
Confirmed.
However, removing events with 
```javascript 
this.calendarOptions.events = [];
```
is fine.

**Comment by acerix** [comment]
The delay is from `rerenderDelay`, I believe that setting is intended to be only a very short time, for example `10` for 10ms, but that should be mentioned in the docs.  This basic demo shows changing dates or dragging events also has the same delay.
 
https://codepen.io/acerix/pen/poyKBxY?editors=0010

There is also an issue to remove this delay for dragging:

https://github.com/fullcalendar/fullcalendar/issues/5622

**Comment by LiXunGuan** [comment]
> The delay is from `rerenderDelay`, I believe that setting is intended to be only a very short time, for example `10` for 10ms, but that should be mentioned in the docs. This basic demo shows changing dates or dragging events also has the same delay.
> 
> https://codepen.io/acerix/pen/poyKBxY?editors=0010
> 
> There is also an issue to remove this delay for dragging:
> 
> #5622

Thank you very much, it is indeed caused by setting the `renderDelay` parameter
