### ISSUE TITLE
Calendar view not updated before EventSource function is executed

### ISSUE THREAD

**Issue by espen** [fullcalendar/fullcalendar#5818]
### Reduced Test Case

https://codepen.io/espen_antonsen/pen/zYqadMv?editors=0010

### Bug Description

When a new view is selected and the eventSource function is called the calendar view is not updated to the new view.

1. In dayGridMonth view.
2. Change to timeGridDay.
3. Event source function is executed.
4. View type (calendarObject.view.type) equals dayGridMonth (the previous used view). Expected: timeGridDay (current view selected by user).

**Comment by espen** [comment]
Observation 1: eventSource is executed before the toolbar button is set as activated (fc-button-active). So I cannot use that as a fallback source for current view.

Observation 2: eventSource function param fetchInfo does not include view object. Unlike dateInfo which includes view object in dateInfo param.

**Comment by espen** [comment]
Seems similar to https://github.com/fullcalendar/fullcalendar/issues/4660

**Comment by acerix** [comment]
Thanks for the demo, but I believe the existing ticket captures this need:
https://github.com/fullcalendar/fullcalendar/issues/4660
↑
Please **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates.

For now, you could check the view after a timeout as suggested there.
