### ISSUE TITLE
Custom buttons render twice in headerToolbar

### ISSUE THREAD

**Issue by Stefan2409** [fullcalendar/fullcalendar#5821]
### Reduced Test Case
Here's a short testcase with 2 custom buttons in the header:

https://codepen.io/stefan2409/pen/mdPKqxe

### Bug Description

Look at the buttons Add Room and the today button. Here 2 html button elements are rendered in the dom. So if you click to far right it's another button than on the left side. This also occurs in the react version of fullcalendar.

**Comment by espen** [comment]
Skip the commas and use this instead:
`prev,next today addRoom addReservation`

https://fullcalendar.io/docs/headerToolbar

**Comment by Stefan2409** [comment]
Ah thanks! That works. So this is closed!
