### ISSUE TITLE
Does not build with Webpack 5

### ISSUE THREAD

**Issue by jacekkarczmarczyk** [fullcalendar/fullcalendar#5822]
### Reduced Test Case

https://github.com/jacekkarczmarczyk/fullcalendar-example-projects/tree/master/vue

```bash
git clone git@github.com:jacekkarczmarczyk/fullcalendar-example-projects.git
cd fullcalendar-example-projects/vue
yarn
yarn start
```

Works fine if I comment all calendar related code in the component

### Bug Description

Project does not compile with webpack 5. 
Errors:

```
ERROR in ./node_modules/@fullcalendar/common/main.js 9:0-86
Module not found: Error: Can't resolve './vdom' in 'C:\cygwin64\home\PC\jacekkarczmarczyk\full-calendar-webpack-5\vue\node_modules\@fullcalendar\common'
```

```
ERROR in ./node_modules/@fullcalendar/core/main.js 6:0-16
Module not found: Error: Can't resolve './vdom' in 'C:\cygwin64\home\PC\jacekkarczmarczyk\full-calendar-webpack-5\vue\node_modules\@fullcalendar\core'
```

```
ERROR in ./node_modules/@fullcalendar/core/main.js 36:16-22
export 'render' (imported as 'render') was not found in '@fullcalendar/common' (possible exports: BASE_OPTION_DEFAULTS, BASE_OPTION_REFINERS, BaseComponent, BgEvent...
```

```
ERROR in ./node_modules/@fullcalendar/vue/dist/main.js 1:0-51
Module not found: Error: Can't resolve './FullCalendar' in 'C:\cygwin64\home\PC\jacekkarczmarczyk\full-calendar-webpack-5\vue\node_modules\@fullcalendar\vue\dist'
```

**Comment by acerix** [comment]
Thanks, confirmed.

I get different errors in the [webpack example](https://github.com/fullcalendar/fullcalendar-example-projects/tree/master/webpack), seems to indicate missing support for v5.

```
ValidationError: Invalid configuration object. Webpack has been initialized using a configuration object that does not match the API schema.
 - configuration.devtool should match pattern "^(inline-|hidden-|eval-)?(nosources-)?(cheap-(module-)?)?source-map$".
   BREAKING CHANGE since webpack 5: The devtool option is more strict.
```

**Comment by bazineta** [comment]
Curious if there's any workaround for this at the moment.

**Comment by doberkofler** [comment]
@bazineta Yes, there is a workaround described in https://github.com/webpack/webpack/issues/11467
```js
{
	test: /\.m?js$/,
	resolve: {
		fullySpecified: false
	}
}
```

**Comment by bazineta** [comment]
@doberkofler Thanks, Dieter, that worked for me.

**Comment by genyslt** [comment]
Does not work form me:

Webpack with Typescript, doesnt compile

ERROR in ./node_modules/@fullcalendar/timegrid/main.js 1146:62-75
export 'createElement' (imported as 'createElement') was not found in '@fullcalendar/common'

in ./node_modules/@fullcalendar/timegrid/main.js 1145:95-108
export 'createElement' (imported as 'createElement') was not found in '@fullcalendar/common'

ERROR in ./node_modules/@fullcalendar/timegrid/main.js 1144:12-25
export 'createElement' (imported as 'createElement') was not found in '@fullcalendar/common'

webpack 5.1.3 compiled with 205 errors

Using Latest version of fullacalendar:

"@fullcalendar/common": "^5.3.1",
"@fullcalendar/core": "^5.3.1",
"@fullcalendar/daygrid": "^5.3.2",
"@fullcalendar/interaction": "^5.3.1",
"@fullcalendar/list": "^5.3.1",
"@fullcalendar/timegrid": "^5.3.1",

**Comment by hmnd** [comment]
To expand a little on @doberkofler's workaround... ensure that you actually add that rule in addition to any other rules you may have for JS which exclude node_modules (eg. babel-loader). Otherwise the resolve options are only applied to your code instead of Fullcalendar's

**Comment by arshaw** [comment]
this fix has been implemented in master, which i will release very soon. closing. will comment on this issue when fully released.

in the meantime, please continue to use `fullySpecified: false`

**Comment by arshaw** [comment]
As of fullcalendar 5.4.0, you no longer need the `fullySpecified:false` webpack flag to build fullcalendar. See this example project: https://github.com/fullcalendar/fullcalendar-example-projects/tree/master/webpack

**Comment by doberkofler** [comment]
@arshaw Thank you!
