### ISSUE TITLE
Unknown option 'dateClick' in simple React example

### ISSUE THREAD

**Issue by myfairshare** [fullcalendar/fullcalendar#5823]
### Reduced Test Case

not reproducible with a link

### Bug Description

I'm experimenting with FullCalendar in a React App and I'm following the basic implementation from the docs at..https://fullcalendar.io/docs/react

I'm pretty sure I have everything installed properly (5.3.1)

What do you expect to happen?
I expect to be able to click on a date or range of dates and see an alert pop up on screen with dates selected 

What happens instead?
The alert does not appear on screen, in my console I see 'Unknown option 'dateClick' '

Maybe I'm missing something obvious, thank you for your time!

.

**Comment by acerix** [comment]
Would you be able to post a [runnable, stripped-down demonstration of the bug](http://fullcalendar.io/wiki/Reduced-Test-Cases/)? Would really appreciate it because the time saved reproducing will be time spent fixing.

**Comment by leoncvlt** [comment]
If anyone else stumbles on this, the most common overlooked steps are:
- Make sure `@fullcalendar/interaction` is installed 
- Make sure it's added to the `plugins` prop

```
import React, { useState } from "react";

import FullCalendar from "@fullcalendar/react";
import dayGridPlugin from "@fullcalendar/daygrid";
import interactionPlugin from "@fullcalendar/interaction";

export const Calendar = () => {
  const handleDateClick = (args) => {
    console.log(args);
  };

  return (
    <FullCalendar
      plugins={[dayGridPlugin, interactionPlugin]}
      initialView="dayGridMonth"
      dateClick={handleDateClick}
      events={[
        { title: 'event 1', date: '2020-11-06' },
        { title: 'event 2', date: '2020-11-01' }
      ]}
    />
  );
};

```

**Comment by whitebyte** [comment]
Unfortunately the problem persists. I copy-pasted @leoncvlt's code as is, but still get the error. My package versions are:

    "@fullcalendar/daygrid": "^5.7.0",
    "@fullcalendar/interaction": "^5.8.0",
    "@fullcalendar/react": "^5.7.0",
