### ISSUE TITLE
Unwanted side effects when sorting resource list manually

### ISSUE THREAD

**Issue by CraftyDlx** [fullcalendar/fullcalendar#5824]
### Reduced Test Case
https://codepen.io/craftydlx/pen/yLeXKKL

### Bug Description
I am successfully using the `sortable` widget (https://jqueryui.com/sortable/) of jQuery Ui 1.12.1 to make the resources of fullcalendar scheduler manually sortable. However, there are some severe side effects:

1.) The resize events function works, but the grid of the event area is distorted visually.
2.) Dragging events on the x-axis works but not on the y-axis to drag events to other resources.
3.) Adjoined events stick together when dragging.
4.) Selecting cells works but the y-lines of the event area grid disappear.
5.) Holding mousebutton down anywhere in the event area makes the y-lines of the event area grid disappear.

Working example https://codepen.io/craftydlx/pen/yLeXKKL and the JS code:

```
document.addEventListener('DOMContentLoaded', function() {
  var calendarEl = document.getElementById('calendar');
  var calendar = new FullCalendar.Calendar(calendarEl, {
      initialView: 'resourceTimelineDay',
      editable: true,
      selectable: true,
      resources: 'https://fullcalendar.io/demo-resources.json',
      events: 'https://fullcalendar.io/demo-events.json?single-day&for-resource-timeline',
    })
    calendar.render()
    $(function(){
      $("table tbody").sortable({

      }).disableSelection() 
    });
});
```
Maybe the tags `table tbody` are not right or do I have to somehow insulate the event area from the `sortable` function? Or is there even a much better way to have the resources sortable?

**Comment by acerix** [comment]
I believe this existing ticket captures this need:
https://github.com/fullcalendar/fullcalendar/issues/5667
↑
Please visit the above issue, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates.

To do it as in your demo, I think it should work if you re-render the resources after the order is changed.

**Comment by CraftyDlx** [comment]
No, re-rendering the resources does not fix anything, because the above issues exist once ´sortable()` is activated on the page. As you can see in the demo. I hope resource dragging will find it's way in soon.

**Comment by acerix** [comment]
I believe that issue is because there's more than one "table tbody", you need to target only the one for resource labels.  Then after changing the order, re-render them with the new ordering to fix the right side.

**Comment by CraftyDlx** [comment]
Could you give me a small hint how to "target only the one for resource labels"? That's exactly the workaround I had in mind (see above).

**Comment by acerix** [comment]
You can inspect that element in your browser and "copy selector", eg:

https://codepen.io/acerix/pen/ExKGmEz?editors=0010

**Comment by fluecker** [comment]
I had the same problem.

I solved this with the following code:

$(function(){
              $("table.fc-datagrid-body tbody").sortable({
                  axis: "y",
                  stop: function () {

                      $.each($(this).children(), function (key, tr){
                          var item = $(tr).children('td:first');
                          var resourceTdId = $(item).attr('data-resource-id');

                          var resource = calendar.getResourceById(resourceTdId);
                          resource.setExtendedProp('position', key);
                      });
                      calendar.render();
                  },
              }).disableSelection()
          });

And add this "resourceOrder: 'position'," to the fullCalendar object.
Now if you sort the Resources, the calendar will new render and the event are on the correct place.

After this, you need to save the new positions.

I hope this solve your problem.
