### ISSUE TITLE
gotoDate() and today() is undefined

### ISSUE THREAD

**Issue by mesimolnar** [fullcalendar/fullcalendar#5838]
### Reduced Test Case

https://codesandbox.io/s/priceless-brown-h6w8t?file=/src/app/app.component.ts

### Bug Description

If we use the this.monthCalendar.getApi().gotoDate(this.ActualDate); (in ngAfterViewChecked )
And we log it, we got an undefined object, and an infinite loop, and the webpage is broken.
We use angular 9 and fullcalendar 5. Can you help us, to declare and solve the problem?

**Comment by acerix** [comment]
I get other errors when trying your demo, but it seems that may be a problem with codesandbox or the example project.  But I tested the same on my system and found that `ngAfterViewChecked` is called after the date is changed, so it makes a loop by changing the date from there.  You care also missing the reference (eg. #calendar):

https://fullcalendar.io/docs/angular#calendar-api
