### ISSUE TITLE
Event dragging and resizing with bootstrap tooltip causes display errors

### ISSUE THREAD

**Issue by CraftyDlx** [fullcalendar/fullcalendar#5844]
### Reduced Test Case
https://codepen.io/craftydlx/pen/RwaqbvL

### Bug Description
Since Popper's Tooltip (https://unpkg.com/tooltip.js@1.3.3/dist/umd/tooltip.min.js) is not compatible with Bootstrap (due to overlapping CSS rules) I tried to use Bootstrap's own Tooltips (https://getbootstrap.com/docs/4.0/components/tooltips/) and found that dragging and resizing events makes the tooltips contantly displayed. Is there a way to implement without these side effects or another compatible tooltip package?

### Screenshots
![Screen Shot 09-20-20 at 05 24 PM](https://user-images.githubusercontent.com/59885175/93715252-8254fd80-fb68-11ea-9f50-3cb15c47c930.PNG)

**Comment by acerix** [comment]
The issue is that it's also adding the tip to the dragging "mirror" of the event, you should not add it when "isMirror":

https://codepen.io/acerix/pen/BaKvLgz
