### ISSUE TITLE
eventDidMount causes title duplication

### ISSUE THREAD

**Issue by Goddard** [fullcalendar/fullcalendar#5849]
### Reduced Test Case
https://codepen.io/Goddard/pen/JjXwWJv?editors=0010

### Bug Description
When using eventDidMount it causes the title to be duplicated when performing certain actions.

Describe how to recreate the bug.
When I do it on my setup it happens when changing the date through various means, but you can see it in this reduced test case when you adjust the event size.  It will duplicate the event title.

What do you expect to happen?
When you resize the event, or change date it shouldn't duplicate the title.

**Comment by acerix** [comment]
It seems the issue is with replacing the HTML since that breaks the references to the DOM so the content is recreated on the next render.  You could add/modify nodes instead of replacing the HTML:

https://codepen.io/acerix/pen/rNeomgg?editors=0010

There is also `eventContent` which is better for custom HTML.

**Comment by Goddard** [comment]
The problem with using eventContent is you don't have access to child nodes right?  If I was in resourceTimeGridDay it has a time component.  I need to modify the way it is displayed because putting elements into the div causes it to overflow.

Unless I am doing something wrong I have to return the event title as blank and just have an extendedProp of "blah" and use that instead of title and it solves all my problems.

**Comment by acerix** [comment]
I'm not sure what child nodes you mean, but you can get the time string like "arg.timeText", eg.

https://codepen.io/acerix/pen/vYGbYNg?editors=0010

**Comment by Goddard** [comment]
Very cool, well I guess I was definitely doing it wrong.  Thanks.
