### ISSUE TITLE
TypeError with "height: 100%" and "dayMaxEventRows: true"

### ISSUE THREAD

**Issue by laughingrat** [fullcalendar/fullcalendar#5850]
### Reduced Test Case

reproduce link [REDUCED TEST CASE code pen](https://codepen.io/laughingrat/pen/ExKGppy).

### Bug Description

dayMaxEventRows = true doesn't work as expected, instead, js error was thrown.

>   Uncaught TypeError: Cannot read property 'seg' of undefined

### Screenshots

![image](https://user-images.githubusercontent.com/1556596/93995187-4669a480-fdc3-11ea-981a-32e22dd4ecf2.png)

**Comment by acerix** [comment]
Thanks, confirmed.  I tested with only those options and also get the error:

https://codepen.io/acerix/pen/KKzJKvJ?editors=0010

Seems related to https://github.com/fullcalendar/fullcalendar-react/issues/96, and the `contentHeight: 'auto'` workaround also works here.

https://codepen.io/acerix/pen/oNxmNPW

**Comment by laughingrat** [comment]
May I have timeline when it can be fixed?  

Thanks
David

**Comment by arshaw** [comment]
i made an even more minimal example: https://codepen.io/arshaw/pen/eYzvxZr?editors=0010

this is almost definitely related to https://github.com/fullcalendar/fullcalendar/issues/5863

**Comment by arshaw** [comment]
This problem has been fixed in 5.4.0. Demo:
https://codepen.io/arshaw/pen/eYzvxZr?editors=0010

NOTE: the calendar still renders weird (as designed) because the parent container has no height, so the 100% height settings on the calendar has no effect. But there's no JS error anymore
