### ISSUE TITLE
sort list view from new to old

### ISSUE THREAD

**Issue by avital-rubin** [fullcalendar/fullcalendar#5855]
### Checklist

Please mark these items with an [x]

  - [ X] I've already searched through [existing tickets](https://fullcalendar.io/issues)
  - [ X] Other people will find this feature useful

### Feature Description

Hi, I would like an option on List views to sort and display new dates first.

**Comment by acerix** [comment]
I believe this existing ticket captures this need:
https://github.com/fullcalendar/fullcalendar/issues/3352
↑
Please visit the above issue, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates.
