### ISSUE TITLE
Dot Marker inherits borderColor rather than backgroundColor when both are specified for an event.

### ISSUE THREAD

**Issue by davlaw0902** [fullcalendar/fullcalendar#5856]
Reduced Test Case at https://codepen.io/dillbb/pen/WNwPMqd

### Bug Description

Create an event and specify both a borderColor and a backgroundColor.
With the default initialView: 'dayGridMonth'  the event will look OK.
When you choose 'listmonth' view, the color of the event dot marker should be the same as the backgroundColor for the event.
However, the event dot marker has inherited the borderColor specified for the event rather than the backgroundColor.

This is not the expected behaviour as the Event Appearance section of the docs specify:
 'For example, the color of the event dot marker is the same as the event backgroundColor'

If a backgroundColor alone is specified there is no issue but when a borderColor is also specified the list view has the wrong dot marker color.

**Comment by acerix** [comment]
I believe this existing ticket captures this need:
https://github.com/fullcalendar/fullcalendar/issues/5533
↑
Please visit the above issue, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates.
