### ISSUE TITLE
warn Unknown option 'schedulerLicenseKey' for Vue FullCalendar

### ISSUE THREAD

**Issue by maico910** [fullcalendar/fullcalendar#5858]
### Reduced Test Case
[DEMO](https://codesandbox.io/s/holy-cookies-2nlie?file=/src/DemoApp.vue)

### Bug Description

I don't know how to import the correct version for fullcalendar and vue in codepen, so I used demo and adding this code in `calendarOptions` :

` schedulerLicenseKey: 'GPL-My-Project-Is-Open-Source'`

and I will recieve warn in console (see Screenshots), It's look has been reported before (#5462), but it'happening in Vue component

### Screenshots

![image](https://user-images.githubusercontent.com/24510745/94215104-e1d94300-feb1-11ea-9b89-59c01fa186ad.png)

**Comment by acerix** [comment]
I get a different error in your demo, "/src/DemoApp.vue: Unexpected token (33:10)".  Although it doesn't look like you are using the Scheduler so don't need a key in that case.
