### ISSUE TITLE
Business Hours not working from Vue data

### ISSUE THREAD

**Issue by maico910** [fullcalendar/fullcalendar#5860]
### Reduced Test Case

https://codesandbox.io/s/zen-almeida-jp0ec?file=/src/DemoApp.vue

### Bug Description

Business hours only working if setting it directly with array, if trying to set with data or computed in Vue will not affecting the calendar

this will work: (doc sample)

    data ( ) {
        return {
            calendarOptions: {
                (...)
                businessHours: [
                   // specify an array instead
                  {
                    daysOfWeek: [1, 2, 3], // Monday, Tuesday, Wednesday
                    startTime: "08:00", // 8am
                    endTime: "18:00", // 6pm
                  },
                  {
                    daysOfWeek: [4, 5], // Thursday, Friday
                    startTime: "10:00", // 10am
                    endTime: "16:00", // 4pm
                  },
               ]
            },
        }  // return
    } // data

this will not work: (getting setting from data)

    data ( ) {
        return {
            calendarOptions: {
                (...)
                businessHours: this.businessHoursData,
            },
           businessHoursData: [
               // specify an array instead
              {
                daysOfWeek: [1, 2, 3], // Monday, Tuesday, Wednesday
                startTime: "08:00", // 8am
                endTime: "18:00", // 6pm
              },
              {
                daysOfWeek: [4, 5], // Thursday, Friday
                startTime: "10:00", // 10am
                endTime: "16:00", // 4pm
              },
           ] // businessHoursData
        }  // return
    } // data

### Screenshots

![image](https://user-images.githubusercontent.com/24510745/94224164-0e985500-fec8-11ea-9efe-10dce6263c50.png)

**Comment by acerix** [comment]
I believe this existing ticket captures this need:
https://github.com/fullcalendar/fullcalendar-vue/issues/127
↑
Please visit the above issue, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates.
