### ISSUE TITLE
InitialEvents not working from Vue data or computed prop

### ISSUE THREAD

**Issue by maico910** [fullcalendar/fullcalendar#5861]
### Reduced Test Case

[DEMO](https://codesandbox.io/s/stupefied-kare-8gqr0?file=/src/DemoApp.vue)

changing setting initialEvents from data prop or directly from calendarOptions commenting / uncommenting :

- line 28 ~ 36 (`calendarOptions`)
- line 29 (`data prop` )

### Bug Description

like issue #5860, if you want setting calendar option from vue data or computed prop, it's will not work.

### Screenshots

Setting directly from calendarOptions's initialEvents prop:
![image](https://user-images.githubusercontent.com/24510745/94279833-0cafaf80-ff23-11ea-8cfc-5691599d2ba5.png)

Setting event from data prop:
![image](https://user-images.githubusercontent.com/24510745/94279317-4d5af900-ff22-11ea-9099-03352f5bfe38.png)

**Comment by acerix** [comment]
I believe this existing ticket captures this need:
https://github.com/fullcalendar/fullcalendar-vue/issues/127
↑
Please visit the above issue, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates.
