### ISSUE TITLE
TypeError when opening the example project on a small screen

### ISSUE THREAD

**Issue by ProUnebit** [fullcalendar/fullcalendar#5863]
**Hey!**
**This calendar is so great!** But i have a problem with fullcalendar on React...
I take 'FullCalendar React Example Project' and started it - everything works in example, but if opened it on mobile size or resizing component - everything breaks! In browser console can be seen: "Uncaught TypeError: Cannot read property 'seg' of undefined", "The above error occurred in the <<TableRow>> component: ... " and others. I didn't touch anything in this example.

And i tried put this example to my project (remodeling on React Hooks + my webpack config), but this issue still remains with same errors. And console build command collects bundle with "error Command failed with exit code 1."

What is 'seg' and why 'seg' undefined? Maybe i forgot to connect something dep or what?

I need help, really very much ask! Spent several hours, but did not understand what was happening with these errors ((

https://raw.githubusercontent.com/ProUnebit/Reminder_ToMe_Reminder/master/src/assets/img/fcr_errors.png

Thanks.

**Comment by acerix** [comment]
Moved to main repo as Vue has exactly the same error.

**Comment by opncow** [comment]
> > > > Thanks, confirmed. I get the same error in Chrome and similar in Firefox if the browser is about 700px wide or less:
> > > > ```
> > > > Uncaught TypeError: placement is undefined
> > > >     recordHidden main.js:469
> > > >     recordHidden main.js:478
> > > >     limitEvents main.js:450
> > > >     limitByMaxHeight main.js:416
> > > >     computeFgSegPlacement main.js:292
> > > >     node_modules main.js:10232
> > > >     React 11
> > > >     unstable_runWithPriority scheduler.development.js:653
> > > >     React 6
> > > >     jsx main.jsx:7
> > > >     jsx main.jsx:6
> > > >     Webpack 3
> > > > main.js:469
> > > > ```
> > > 
> > > 
> > > Yup... аny idea? )
> > > Maybe these errors about communication with .ts files? If we talk about value'seg' or something...
> > 
> > 
> > I found this solution, define in the configuration:
> > contentHeight: 'auto'
> > The error no longer occurs and the calendar in mobile size assumes a more correct height.
> 
> Yepp it's working. Thanks!

It works for me, too. However, this changes the display. I saw the "more" links before, while with the "contentHeight: 'auto'" settings, with multiple events on one day, they are now all shown.

**Comment by mammuthone** [comment]
@

> I have the same error.
> It occurs only in the "dayGridMonth" view, when I load the page in mobile size, or when I resize the browser from mobile size to a larger size.

Same issue on my project. I confirm that
`contentHeight: 'auto'`
is a working trick, but it's not even possible to set any other `aspectRatio` or `height` properties of the Calendar, neither any value than 'auto' on `contentHeight`

**Comment by alexkakhnovskyi** [comment]
Please fix

**Comment by kikovipera** [comment]
https://fullcalendar.io/#demos resize browser to mobile size and you will see the error. When to expect to be fixed? 
Thanks

**Comment by arshaw** [comment]
this is now fixed in 5.4.0! check the homepage!
