### ISSUE TITLE
Resource eventAllow: false

### ISSUE THREAD

**Issue by tobiasnitsche** [fullcalendar/fullcalendar#5867]
### Reduced Test Case

https://codepen.io/tobiasnitsche/pen/QWNPOeB

### Bug Description

When you actually drag an event over a resource which has "eventAllow: false", you see a message "subjectAllow is not a function" in the console.

Settings: Windows 10 / 64 bit, Firefox 81 64 bit.

### Screenshots

![grafik](https://user-images.githubusercontent.com/43043989/94446117-7f7d8c80-01a8-11eb-8f63-62b69679d87a.png)

**Comment by acerix** [comment]
`eventAllow` needs to be a function, eg:

https://codepen.io/acerix/pen/MWyMgBj?editors=1010

**Comment by tobiasnitsche** [comment]
K. Understood. But how can it be done to have "eventAllow" if the resource source is a json feed?

**Comment by tobiasnitsche** [comment]
@acerix

**Comment by tobiasnitsche** [comment]
Found a solution :-)
