### ISSUE TITLE
unselectCancel doesn't work with complex selector

### ISSUE THREAD

**Issue by janswist** [fullcalendar/fullcalendar#5870]
### Reduced Test Case

https://codesandbox.io/s/jovial-frog-0v44s?file=/src/DemoApp.vue

### Bug Description

When you select new date modal appears (correct). When you click outside of it modal closes and selection disappears (correct). When you click on the close button of modal selection stays (error).

What I want to achieve is to clear selection if any button in modal footer is clicked. In other words to use `unselectCancel` and to make it omit buttons so the click on them can make selection disappear.

`unselectCancel` doesn't work with complex selector even though when I test it with CSS with the same selector it works .

Edit: this one doesn't work as well (header and body don't clear selection, footer also but seems like `:not` selector is ignored)
```
unselectCancel: ".modal-header, .modal-body, .modal-footer:not(button)",
```

**Comment by acerix** [comment]
It seems to only work for basic selectors, you could use `unselect()` to clear the selection for those buttons.

**Comment by janswist** [comment]
Yes, exactly. It seems to work only with basic selectors. Not sure how to use `unselect()` in my case

**Comment by acerix** [comment]
`unselect` clears the selection so you can call that when the modal is closed.

**Comment by janswist** [comment]
Thanks!
