### ISSUE TITLE
Resource parent undefined from getParent() in resourceLaneDidMount

### ISSUE THREAD

**Issue by dbm0415** [fullcalendar/fullcalendar#5877]
### Reduced Test Case
https://codepen.io/fluxcapacity/pen/YzqoxWw

You must paste a link to a [REDUCED TEST CASE](https://fullcalendar.io/reduced-test-cases).
If you do not, this issue will automatically be closed.
To prevent this, include the text "not reproducible with a link" (assuming it's true).

### Bug Description

Describe how to recreate the bug.
Access a Resource's parent id (or really any parent attribute) via resource.getParent() in resourceLaneDidMount method
What do you expect to happen?
Data is returned

What happens instead?
Attempting to access a Resource's parent id (or really any parent attribute) in resourceLaneDidMount results in the error "Uncaught TypeError: Cannot read property 'id' of undefined". 

Is it possible parent Resource data is not available during this method?

**Comment by acerix** [comment]
Sorry about your other issue getting closed by the bot, I reopened that one: 

https://github.com/fullcalendar/fullcalendar/issues/5876
