### ISSUE TITLE
using icon in custom button creates two date pickers

### ISSUE THREAD

**Issue by Goddard** [fullcalendar/fullcalendar#5879]
### Reduced Test Case
https://codepen.io/Goddard/pen/ZEWdZxw

### Bug Description
When clicking on the icon for the "custom1" button it creates two date picker pop ups.  It also appears one of the date picker popups isn't connected to the created code.  Almost like it was created by something else entirely.  You have to click in the middle of the button and then both pop up.  If you click on the side of the button only one date picker will pop up and this one is created some place else.  Not from the code in the click : function() method.

**Comment by acerix** [comment]
The issue is from attaching it to `this` since that changes in the callback scope, can attach to `htmlElement` instead:

https://codepen.io/acerix/pen/ExyYqxQ?editors=0010

**Comment by Goddard** [comment]
I'm still seeing two date picker elements pop up.

**Comment by acerix** [comment]
I can see the same issue in my demo now, it just doesn't happen everytime.  However, the `click` function is firing correctly (only once per click) so it doesn't seem like a bug in the calendar, rather with the datepicker or how it's used. Might need to destroy it before adding another one.
