### ISSUE TITLE
Documentation does not indicate yarn is the preferred package manager

### ISSUE THREAD

**Issue by njpearman** [fullcalendar/fullcalendar#5880]
### Reduced Test Case

Documentation - not reproducible with a link.

### Bug Description

https://github.com/fullcalendar/fullcalendar/blob/master/CONTRIBUTING.md#getting-set-up indicates `npm` should be used to install packages but `yarn` is preferred. The documentation should be updated to reflect this, either as an outright replacement or to indicate that `yarn` is preferred but `npm` can be used.

**Comment by arshaw** [comment]
the CONTRIBUTING doc now says this https://github.com/fullcalendar/fullcalendar/blob/master/CONTRIBUTING.md
