### ISSUE TITLE
Events can have a gap between and take more rows than dayMaxEventRows when using eventOrder

### ISSUE THREAD

**Issue by yyamamotowb** [fullcalendar/fullcalendar#5883]
### Reduced Test Case
[https://codepen.io/yamamoto19730701/pen/OJXLPWX](https://codepen.io/yamamoto19730701/pen/OJXLPWX)

### Bug Description
See the URL above.
I expect b2 to appear on 10/21 and b3 not to appear.
However, b2 is the second blank page and b3 is displayed.
In addition, it looks like 4 rows are displayed even though dayMaxEventRows is set to 3.

### More Information
If dayMaxEventRows is not set and the other conditions are the same, the result will be as shown in the URL below.
I think this result is correct.
[https://codepen.io/yamamoto19730701/pen/oNLvNrJ](https://codepen.io/yamamoto19730701/pen/oNLvNrJ)

**Comment by acerix** [comment]
Thanks, confirmed.  I also tried without the '00:00' times and get the same:

https://codepen.io/acerix/pen/WNxNeEy

**Comment by yyamamotowb** [comment]
Thank you
By the way, when is the this issue planned to be fixed?
Please tell it if possible.

**Comment by arshaw** [comment]
note to self for debugging: the sorted event order is b1,b2,b3,b4.... when b4 is commented out everything is fine. when b4 is revealed, for some reason b2 is hidden

**Comment by arshaw** [comment]
this is no longer an issue as of 5.5.0: https://codepen.io/arshaw/pen/rNMwEpL?editors=0010

**Comment by yyamamotowb** [comment]
Thank you very much.
I also confirmed that the program was fixed.
