### ISSUE TITLE
v3 to v5 migration guide

### ISSUE THREAD

**Issue by pgeyman** [fullcalendar/fullcalendar#5889]
### Checklist

Please mark these items with an [x]

  - [x] I've already searched through [existing tickets](https://fullcalendar.io/issues)
  - [x] Other people will find this feature useful

### Feature Description

In the v4->v5 migration guide you state: "Many developers will be upgrading from v3 instead of v4. We will likely release a separate guide for this process before the official v5 is released."

The official v5 release was a few months ago now. Is there a v3->v5 guide somewhere now? Googling for it does not find anything.

**Comment by acerix** [comment]
There is no guide for v3 to v5, you can refer to the v3 to v4 guide to find the changes since v3:

https://fullcalendar.io/docs/v4/upgrading-from-v3
