### ISSUE TITLE
Week number rendered twice in ResourceTimeGridView

### ISSUE THREAD

**Issue by dneuschaefer-rube** [fullcalendar/fullcalendar#5890]
### Reduced Test Case

https://codepen.io/dnr1/pen/qBNBPBz?editable=true&editors=001%3Dhttps%3A%2F%2Ffullcalendar.io%2Fdocs%2FdatesAboveResources-demo

### Bug Description

Passing `weekNumbers: true` results in week number being rendered in the first and second header row.

### Screenshots

![image](https://user-images.githubusercontent.com/5830562/95351632-b4cd5d00-08c1-11eb-9715-403c77c7dd15.png)

**Comment by arshaw** [comment]
this is no longer an issue as of 5.5.0: https://codepen.io/arshaw/pen/BaLZgJM?editable=true&editors=001
