### ISSUE TITLE
class="fc-col-header-cell-cushion" vs bootstrap

### ISSUE THREAD

**Issue by favy87** [fullcalendar/fullcalendar#5892]
### Reduced Test Case

https://codepen.io/favy87/pen/jOrEMNP

### Bug Description

When you mix Bootstrap v4.5.2 and fullcalendar v5.3.2 the css clases are affected by the Bootstrap css and the text in the columns instead of being black, it is blue:
- "fc-col-header-cell-cushion"
- "fc-daygrid-day-number"
- ".fc-direction-ltr .fc-daygrid-event .fc-event-time"
- ".fc-daygrid-dot-event .fc-event-title"
- ".fc-direction-ltr .fc-list-day-text"
- ".fc-direction-ltr .fc-list-day-side-text"

I think it is affected by Bootstrap's reebot.css file. It is easily corrected by adding the property "color: black"

### Screenshots

![Captura](https://user-images.githubusercontent.com/5238141/95509746-2c2fe900-09b5-11eb-8f8c-e358c0bd59f8.JPG)

**Comment by acerix** [comment]
There's a Bootstrap theme which fixes this:

https://codepen.io/acerix/pen/mdEyKYW?editors=0010
