### ISSUE TITLE
type error: FullCalendarVDOM namespace unknown in common package

### ISSUE THREAD

**Issue by schTi** [fullcalendar/fullcalendar#5895]
### Reduced Test Case

not reproducible with a link.

### Bug Description

The global FullCalendarVDOM namespace is declared in the `core` package. Without importing this package explicitly to the own package dependencies, there is an error, that `FullCalendarVDOM` is not declared in the `common` package. 
I would have expected, that this would have worked even without importing the `core` package every time.

**Comment by acerix** [comment]
Please post a [runnable, stripped-down demonstration of the bug](http://fullcalendar.io/wiki/Reduced-Test-Cases/) or steps to reproduce the error.  It should be imported as the example on this page:

https://fullcalendar.io/docs/initialize-es6
