### ISSUE TITLE
`loading` callback fires before resources are done loading and again after

### ISSUE THREAD

**Issue by EdCampion** [fullcalendar/fullcalendar#5896]
### Reduced Test Case
https://codepen.io/EdCampion/pen/qBNEVym

### Bug Description

Describe how to recreate the bug.
As illustrated in the codepen, setup a resource timeline with the resources and events loaded dynamically. Include the loading handler.

What do you expect to happen?
Expectations include:

- That the loading handler would be called twice - loading(true) and loading(false)
- That the number of loading(true) calls would equal the number of loading(false) calls.

What happens instead?
The loading handler is called 3 times with values
true,
false,
false
To verify this check the console in the codepen

While assembling this test, I have noticed that there is a caching issue either interacting with or causing this issue. If you reload the codepen multiple times, the issue is eventually non-reproducible.

**Comment by acerix** [comment]
It happens if the resources are done loading after the events.  So it seems like a bug that `loading` fires while the resources are still loading.

https://codepen.io/acerix/pen/oNLgPZy?editors=0011

**Comment by arshaw** [comment]
confirmed. this happens sporadically when i re-run the codepen, but not all the time

**Comment by arshaw** [comment]
could be related to https://github.com/fullcalendar/fullcalendar/pull/5729

**Comment by arshaw** [comment]
this is fixed as of 5.5.0: https://codepen.io/arshaw/pen/PoGjrQX?editors=0011
