### ISSUE TITLE
Using FullCalendar v4 or v5 with Angular 2?

### ISSUE THREAD

**Issue by shawn-crigger** [fullcalendar/fullcalendar#5898]
### Checklist

Please mark these items with an [x]

  - [x] I've already searched through [existing tickets](https://fullcalendar.io/issues)
  - [x] Other people will find this feature useful

### Feature Description

We have a legacy application used by 200k unique users a day and we would really like to update the Calendar but not have to rewrite the entire application to use a later Angular Version, we are talking hundreds of thousands of lines of javascript, and I just don't see it possible to rewrite the entire app to use a later version of Angular.

### We would glad to provide v5 using Angular v2

**Comment by acerix** [comment]
The v4 Angular component needs Angular 7/8 and v5 needs 9/10, but you can use the pre-built bundle in older versions instead of the component.

https://fullcalendar.io/docs/initialize-globals

**Comment by bawantha** [comment]
> The v4 Angular component needs Angular 7/8 and v5 needs 9/10, but you can use the pre-built bundle in older versions instead of the component.
> 
> https://fullcalendar.io/docs/initialize-globals

This should be in doc
