### ISSUE TITLE
businessHours: DST ignored when using array instead of object

### ISSUE THREAD

**Issue by glureau** [fullcalendar/fullcalendar#5900]
### Reduced Test Case

not reproducible with a link
(too lazy sorry, but it looks like important enough to report it, so please read the description)

### Bug Description

Using businessHours with an object or a list of object doesn't use the same timezone.

```
businessHours: { daysOfWeek: [ 1 ],
  startTime: '10:00',
  endTime: '18:00',
}

```
Displays an area **from 10:00 to 18:00** in my Locale (France)

```
businessHours: [ { daysOfWeek: [ 1 ],
  startTime: '10:00',
  endTime: '18:00',
} ]
```
Displays an area **from 9:00 to 17:00** (same other conditions).

Locale in France is UTC+1 with a +1h DST.

---

Thank you for this great library, lovely to play with that high-quality lib and advanced documentation. Well done!

Can't help right now but I hope I'll be able to contribute soon.

**Comment by acerix** [comment]
BusinessHours does not support timezones, you can use background events instead.

https://github.com/fullcalendar/fullcalendar/issues/5455

If there is a bug, please supply a [runnable, stripped-down demonstration](http://fullcalendar.io/wiki/Reduced-Test-Cases/).
