### ISSUE TITLE
Can't drag event from resource A to resource B

### ISSUE THREAD

**Issue by shirlyLoveFlowers** [fullcalendar/fullcalendar#5904]
### Reduced Test Case

 [Click the "x more" to show more events, and then drag one event from Resource A to Resource B](https://codepen.io/ShirlyFE/pen/RwRWdQo).

### Bug Description

Click the "x more" to show more events, and then drag one event of the popover, from Resource A to Resource B

Expected: drag success.
Behavior: drag fail.

### Screenshots
<img width="1440" alt="Can't drag event from resource A to resource B" src="https://user-images.githubusercontent.com/5653949/95950808-cfef1e00-0e27-11eb-8230-7bc55cdfc84c.png">

**Comment by laughingrat** [comment]
It should be caused by no resourceId

![image](https://user-images.githubusercontent.com/1556596/95970096-20737500-0e42-11eb-9930-70c7f6877cf1.png)

**Comment by acerix** [comment]
I believe this existing ticket captures this need:
https://github.com/fullcalendar/fullcalendar/issues/5593
↑
Please visit the above issue, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates.

**Comment by shirlyLoveFlowers** [comment]
@acerix Yes, the #5593 captures the issue. Has subscribed. Thank you 👍
