### ISSUE TITLE
lager data is very very slow

### ISSUE THREAD

**Issue by xiexingen** [fullcalendar/fullcalendar#5905]
### Reduced Test Case

You must paste a link to a [REDUCED TEST CASE](https://fullcalendar.io/reduced-test-cases).
If you do not, this issue will automatically be closed.
To prevent this, include the text "not reproducible with a link" (assuming it's true).

### Bug Description
example 
i has 1000 line data,but actual show top 10,other data will generate in dom;
other data should can not generate in dom?

### Screenshots

If the bug is visual, include a screenshot if possible.
If not, erase this section.

**Comment by acerix** [comment]
Would you be able to post a [runnable, stripped-down demonstration of the bug](http://fullcalendar.io/wiki/Reduced-Test-Cases/)? Would really appreciate it because the time saved reproducing will be time spent fixing.
