### ISSUE TITLE
Does fullcalendar@5.3.1 support the background event calendar ? if yes how to change the locale language dynamicaly 

### ISSUE THREAD

**Issue by hamza-topo** [fullcalendar/fullcalendar#5909]
### Reduced Test Case
Im trying to show a calendar with the possibilité to change language dynamically ;
it works fine for the basic calendar but when it comes to calendar with background events it doesn't work !

if any

### Bug Description
my calendar id
 ` <div class="calendar-bg-events" id="calendar-bg-events"></div>`
`$('#calendar-bg-events').fullCalendar({
        header: {
            left: 'prev,next today',
            center: 'title',
            right: 'month,agendaWeek,agendaDay,listMonth'
        },
        themeSystem: 'bootstrap4',
        bootstrapFontAwesome: true,
        defaultDate: '2018-03-12',
        navLinks: true, // can click day/week names to navigate views
        businessHours: true, // display business hours
        editable: true,
        events: [
            {
                title: 'Business Lunch',
                start: '2018-03-03T13:00:00',
                constraint: 'businessHours'
            },
            {
                title: 'Meeting',
                start: '2018-03-13T11:00:00',
                constraint: 'availableForMeeting', // defined below
                color: '#257e4a'
            },
            {
                title: 'Conference',
                start: '2018-03-18',
                end: '2018-03-20'
            },
            {
                title: 'Party',
                start: '2018-03-29T20:00:00'
            },

            // areas where "Meeting" must be dropped
            {
                id: 'availableForMeeting',
                start: '2018-03-11T10:00:00',
                end: '2018-03-11T16:00:00',
                rendering: 'background'
            },
            {
                id: 'availableForMeeting',
                start: '2018-03-13T10:00:00',
                end: '2018-03-13T16:00:00',
                rendering: 'background'
            },
        ]
    });`

### Screenshots

If the bug is visual, include a screenshot if possible.
If not, erase this section.
![fullcalendarjs](https://user-images.githubusercontent.com/54219563/96282346-82fb7b00-0fd2-11eb-8d81-f98941b141d8.PNG)
![c2](https://user-images.githubusercontent.com/54219563/96282354-842ca800-0fd2-11eb-97fa-516aac88a8d9.PNG)

**Comment by acerix** [comment]
Would you be able to post a [runnable, stripped-down demonstration of the bug](http://fullcalendar.io/wiki/Reduced-Test-Cases/)? Would really appreciate it because the time saved reproducing will be time spent fixing.
