### ISSUE TITLE
Update the calendar UI to reflect the new date selected as the first date displayed using the 'gotoDate' function

### ISSUE THREAD

**Issue by ryj1023** [fullcalendar/fullcalendar#5913]
### Reduced Test Case

https://jsfiddle.net/ryj1023/5epnoguk/5/

### Bug Description

I'm trying to update the UI of the calendar using the 'gotoDate' function to so that the date I pass into the function will be reflected as the first date of the range shown. This feature works if the date I'm passing in the function is not already in the range shown in the view. When I select a date that shows in the current range, but is not the first date, the UI does not change. 

### Screenshots

![image](https://user-images.githubusercontent.com/18105491/96465901-80c63600-11f7-11eb-9e5a-5dbdcb3fd1c8.png)

**Comment by acerix** [comment]
I believe this existing ticket captures this need:
https://github.com/fullcalendar/fullcalendar/issues/4929
↑
Please visit the above issue, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates.
