### ISSUE TITLE
Strange behavior at rrulePlugin use

### ISSUE THREAD

**Issue by marcosogsantos** [fullcalendar/fullcalendar#5921]
I'm using it in React.

Did toke me a while for figurate that the rrulePlugin was proprery running just when I put it as first plugin.
Work: plugins={[rrulePlugin,dayGridPlugin,interactionPlugin,timeGridPlugin]}
Not work: plugins={[dayGridPlugin,interactionPlugin,timeGridPlugin,rrulePlugin]}

The "day" and "week" still buttons works fine, but for some reason when I put the rrulePLugin in the first place, the "month" button to change the view of calendar, just broke and dont work anymore.

Do you guys have some idea?

```
         <FullCalendar
            plugins={[rrulePlugin, dayGridPlugin,interactionPlugin,timeGridPlugin]}
            ref={this.calendarRef}
            headerToolbar={{
              left: 'prev,next today',
              center: 'title',
              right: 'dayGridMonth,timeGridWeek,timeGridDay'
            }}
            events={[
              { title: 'event 1', date: '2020-10-23' },
              { title: 'event 2', date: '2020-10-22' },
              {
                title: "RRule event",
                rrule:
                  "DTSTART:20200610T103000\nRRULE:FREQ=DAILY;INTERVAL=1;UNTIL=20210801\nEXDATE:20190618T103000Z\nEXDATE:20190619T103000",
      
                duration: "02:00"
              }
            ]}
          />
```
![image](https://user-images.githubusercontent.com/51763881/96875880-1e1aa780-144e-11eb-952e-600d5d1c040a.png)

**Comment by Slaknoah** [comment]
I am having the same issue
