### ISSUE TITLE
Support for building CJS modules

### ISSUE THREAD

**Issue by atifsyedali** [fullcalendar/fullcalendar#5929]
### Checklist

Please mark these items with an [x]

  - [X] I've already searched through [existing tickets](https://fullcalendar.io/issues)
  - [X] Other people will find this feature useful

### Feature Description

Please output two versions -- CJS and ESM -- in the shipped libraries and remove the type: module flag from package.json.

I don't think this is a breaking change as you are only adding a new output variant. Existing systems that rely on ESM will continue to work the same way.

### Visual Mockups

None

**Comment by arshaw** [comment]
this has been implemented in `master`. i'll write a comment here when i release

**Comment by arshaw** [comment]
There is now a commonjs file in each package, `main.cjs.js` and now it's hooked up to the `main` field in package.json whereas the esm file is the `module` field. As of 5.4.0
