### ISSUE TITLE
Option to hide nowIndicator when outside visible timerange

### ISSUE THREAD

**Issue by LrntL** [fullcalendar/fullcalendar#5936]
Hi,

The nowIndicator is visible in scheduler if "now" is outside of the timerange.
Is it possible to hide it when it's outside?

### Reduced Test Case

https://codepen.io/lrntlbx/pen/vYKdbjZ

### Bug Description

Now Indicator visible when outside timerange on scheduler

### Screenshots

![nowindicator](https://user-images.githubusercontent.com/43986541/97588538-e1761f80-19fc-11eb-838f-5a6d7f6864ac.PNG)

Thank you.

**Comment by acerix** [comment]
There is no option for that but you could hide it with `nowIndicatorClassNames`:

https://codepen.io/acerix/pen/YzWLmVJ?editors=0110

**Comment by LrntL** [comment]
Of course ! ... I forgot nowIndicatorClassNames
It's perfect, thank you.
