### ISSUE TITLE
The title of monthly view display different in different browser

### ISSUE THREAD

**Issue by wydingez** [fullcalendar/fullcalendar#5943]
### Reduced Test Case

not reproducible with a link

### Bug Description

In the locale of zh-cn environment, the title of the monthly view is different from that of the IE browser and Google browser. Is it bug or intentionally?

### Screenshots
In IE :
![image](https://user-images.githubusercontent.com/26266181/98096312-90679f00-1ec6-11eb-83bc-dfa8e95276dd.png)

In Chrome ：
![image](https://user-images.githubusercontent.com/26266181/98096337-99f10700-1ec6-11eb-8f0b-cf0986e81bcf.png)

**Comment by acerix** [comment]
The date formatting is handled by the browser, so it's a bug in the browser if one of those is incorrect.  You can use a plugin for consistent formatting:

https://fullcalendar.io/docs/luxon-plugin

**Comment by wydingez** [comment]
@acerix thanks!
