### ISSUE TITLE
Timeline three days view often doesn't show each three days

### ISSUE THREAD

**Issue by mnishino1012** [fullcalendar/fullcalendar#5945]
### Reduced Test Case

[codepen](https://codepen.io/mnishino1012/pen/OJXwmyJ?editors=0010)

### Bug Description

If you click prev/next buttons several times, sometimes it may be displayed for two days or only for one day though view setting is three days.
It happens when weekends settings is false.

### Screenshots

![image](https://user-images.githubusercontent.com/30854740/98206297-03335180-1f7d-11eb-9354-bff28424f741.png)
![image](https://user-images.githubusercontent.com/30854740/98206259-f3b40880-1f7c-11eb-8288-1a61c6bf4c9e.png)

**Comment by acerix** [comment]
The duration of the view is not effected by `weekends`,  so the view is always including 3 days, but then hiding the weekends which is why it doesn't always show 3 days.
