### ISSUE TITLE
eventOrder  &  dayMaxEventRows dayGridMonth bug

### ISSUE THREAD

**Issue by zhuh911** [fullcalendar/fullcalendar#5949]
### Reduced Test Case

https://codepen.io/zhuh/pen/RwRBXBB

### Bug Description
single  dayMaxEventRows   or  eventOrder  is ok
but union 
dayMaxEventRows and eventOrder are used in combination exist bug

set dayMaxEventRows :2  and set the eventOrder,resule show 3 event inculding + more

**Comment by acerix** [comment]
Sorry for the delayed response, I missed this when it came in.

I believe this existing ticket captures this need:
https://github.com/fullcalendar/fullcalendar/issues/6187
↑
Please visit the above issue, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates.
