### ISSUE TITLE
Type error when slotDuration is in whole days

### ISSUE THREAD

**Issue by tuerker** [fullcalendar/fullcalendar#5952]
###Reduced Test Case

https://codepen.io/tuerker/pen/eYzLZar

###Bug Description

When there is only one slot per day, the calendar crashes and becomes unusable.

![Screenshot from 2020-11-06 13-59-20](https://user-images.githubusercontent.com/10051373/98368978-7bab1880-2038-11eb-8b5c-197f5376b122.png)

I had a quick view on the code. The problem lies in the class TimeColsSlatsCoords.ts.

The method  computeTimeTop(duration: Duration) delivers an NPE

`    let slotDurationMs = slatMetas[1].date.valueOf() - slatMetas[0].date.valueOf() // we assume dates are uniform
`

Obviously, this happens when there is only a single slot per day.

A revision is required here since this very common use case cannot be excluded!

**Comment by tuerker** [comment]
@arshaw many thanks in advance for fixing this bug. we urgently need this.

**Comment by melloware** [comment]
@tuerker can you provide a PR?  Is it just a matter or doing NULL checking on the two dates???
```javascript
let slotDurationMs = slatMetas[1].date.valueOf() - slatMetas[0].date.valueOf() // we assume dates are uniform
```

**Comment by tuerker** [comment]
i have no experience with js programming. therefore, i would stay away from trying to fix this.

the solution must do a null pointer check and compute slotDurationMs differently when there is only slatMetas[0] defined. 
so the solution should look as follows (assuming that time is the duration of corresponding slot):

`let slotDurationMs = slatMetas[1] != null && slatMetas[0] ? slatMetas[1].date.valueOf() - slatMetas[0].date.valueOf() : slatMetas[0].time.valueOf() 
`

**Comment by tuerker** [comment]
@arshaw @acerix would be great if you could fix. it should be a very easy issue for you. many thanks in advance.

**Comment by melloware** [comment]
@tuerker I wonder if you bought 1 seat of the FullCalendar Premium it would be incentive enough for them to fix this issue?

**Comment by arshaw** [comment]
i will look at this (and @melloware's PR) for the next release

**Comment by arshaw** [comment]
released!
https://github.com/fullcalendar/fullcalendar/releases/tag/v5.5.1

update test case:
https://codepen.io/arshaw/pen/MWjZBXz

**Comment by melloware** [comment]
Thank you much appreciated!

**Comment by tuerker** [comment]
Many Thanks for all your efforts.

This issue however is not fully solved. Please check out the reduced test case above and have a look into the console.

Now, it delivers the following error:

```
Uncaught TypeError: Cannot read property 'date' of undefined
    at e.computeTimeTop (main.min.js:6)
    at e.t.handleScrollRequest [as execFunc] (main.min.js:6)
    at e.drain (main.min.js:6)
    at e.update (main.min.js:6)
    at t.componentDidUpdate (main.min.js:6)
    at t.<anonymous> (main.min.js:6)
    at main.min.js:6
    at Array.some (<anonymous>)
    at main.min.js:6
    at Array.some (<anonymous>)
```

Best regards and many thanks in advance.

**Comment by melloware** [comment]
@tuerker You probably want to open a new issue and provide your reproducer above there so they can track a new ticket.

**Comment by melloware** [comment]
HA nevermind I see you just did!

**Comment by tuerker** [comment]
forget it. i works. it was my fault on being not on the latest version. many thanks again to adam for fixing it.
