### ISSUE TITLE
Date selection in resource timeline month view not using business hours

### ISSUE THREAD

**Issue by plutocow** [fullcalendar/fullcalendar#5955]
### Reduced Test Case

[REDUCED TEST CASE](https://codesandbox.io/s/eager-napier-3erj9?file=/src/Scheduler.js)

### Bug Description

I've configured businessHours startTime to "09:00" and endTime to  "17:30".
In the resource timeline month view, when I select a single date it gives me the following:

```
Start: 2020-11-10
End: 2020-11-11
```

Is this intended behavior? If so, on the resourceTimelineMonth view, how do I make it so that selecting a date gives the end time of the selected date? ie. I select Monday 9th, it returns to me the start as Monday 9th 09:00AM to end as Monday 9th 05:30PM (I'm looking through the documentation and unsure if this is available).

**Comment by acerix** [comment]
In that view, each slot is one day so the selection is also in whole days, it does not consider `businessHours`.   You could set `slotDuration` to 30 minutes if you want the selection in half-hours.
