### ISSUE TITLE
Timeline calendar current time indicator

### ISSUE THREAD

**Issue by LeninZapata** [fullcalendar/fullcalendar#5961]
### Checklist

Please mark these items with an [x]

  - [X] I've already searched through [existing tickets](https://fullcalendar.io/issues)
  - [ ] Other people will find this feature useful

### Feature Description

In the timeline type calendar, a line is not shown in the demos that indicates that I am at this time crossing this X task, this is very useful to know what task should currently be done. Attached Screenshot of how it would look
This Example is on this [page](https://app.teamcalapp.com/), but your calendar should include it

### Visual Mockups
![c2u0QQ8z2Q](https://user-images.githubusercontent.com/42600954/98667514-7a216f00-231c-11eb-9b77-8ec365a7e301.png)

**Comment by acerix** [comment]
This can be enable with [nowIndicator](https://fullcalendar.io/docs/nowIndicator).
