### ISSUE TITLE
calendar.getDate() missed the selected date

### ISSUE THREAD

**Issue by sawirricardo** [fullcalendar/fullcalendar#5966]
### Reduced Test Case
https://jsfiddle.net/afnL2c6e/6/

### Bug Description
To see the bug, please view this https://jsfiddle.net/afnL2c6e/6/
Describe how to recreate the bug.
Try to click button that change month, and see the console.log. it produce different month.
What do you expect to happen?
I expect when the calendar show november, than console.log should output november, and so on.
What happens instead?
The console.log output other than selected month.

**Comment by acerix** [comment]
It works as expected if called from `datesSet`, which is the callback after the date is changed.

https://codepen.io/acerix/pen/zYByavx?editors=0011

In the events function, you can get the view dates in `fetchInfo`.

https://fullcalendar.io/docs/events-function
