### ISSUE TITLE
Unexpected text color of multi-day events

### ISSUE THREAD

**Issue by karres-illinois** [fullcalendar/fullcalendar#5972]
### Reduced Test Case

There is a [Fiddle here](https://jsfiddle.net/sevenreeds/wf5soq8L/33/) 

### Bug Description

Describe how to recreate the bug.

- Visit fiddle. go to November 2020 month view

- Seen in FC versions 5.3.2 (fiddle) and 5.4.0 in my local app as of this morning.

- The events in the fiddle all look something like:

      {
        "id": " 307266133",
        "title": "DEVICE-TWO:user_a:",
        "start": "2020-10-01T09:45:59",
        "end": "2020-10-01T10:40:58",
        "overlap": false,
        "backgroundColor": null,
        "textColor": null,
        "active": false,
        "source": "UT",
        "tmpClass": null,
        "classNames": [
          "AppColors-myEvent",
          "AppColors-UT-default"
        ],
        "device": "DEVICE-TWO"
      }

    I have tried removing the `ClassNames`  entries and embedding the associated colors in the `backgroundColor` and `textColor` elements with not real difference that I can see.

What do you expect to happen?

- For all events I expect there to be custom font and background colors. I expect that all font colors will be black.

What happens instead?

- Multi-day events replace my custom font color with white. It looks like multi-day events get the FC class `fc-h-event` and that might then cause the font color override.

**Comment by acerix** [comment]
It works with backgroundColor/textColor as in the example:

https://codepen.io/acerix/pen/qBNeKjK?editors=001
