### ISSUE TITLE
Incorrect time on recurring event overlapping timezone change

### ISSUE THREAD

**Issue by sundling** [fullcalendar/fullcalendar#5973]
### Reduced Test Case

https://codepen.io/sundling/pen/ZEOZWqP

### Bug Description

I expect the events to repeat at the same time each day.
There was a time zone change at 2020-10-25 03:00:00 ( CEST => CET)

It worked as expected in version 5.3.2

**Comment by arshaw** [comment]
v5.4.0 is more strict in this regard. you are specifying dates with a `Z` ending, meaning they are in UTC. However, your calendar's timezone is in `Europe/Stockholm` which means the UTC dates for the events will be translated to this timezone, resulting in a shift when DST starts/ends. If you simply specify the events without a Z, they will be assumed to be in the same timezone as the calendar, and everything will work as you desire:

https://codepen.io/arshaw/pen/MWjpZdx?editors=0010
