### ISSUE TITLE
Incorrect time slots being highlighted when using resourceTimelinePlugin

### ISSUE THREAD

**Issue by ArcticFaded** [fullcalendar/fullcalendar#5974]
### Reduced Test Case

This is a reduced test case using fullcalendar react and @fullcalendar/resource-timeline. https://codesandbox.io/s/fullcalendar-v4-react-forked-to9ge

My environment is using nextjs however.
### Bug Description

Describe how to recreate the bug: The current bug is that when using resource-timeline in react, instead of timeslots occuring in the time specified, they will show up for its full length. However, when restricting the view to days, it seems to now when to display the events, however even within days the events display as if they were all day events.
What do you expect to happen?
Using demo resource and timelines
    resources: 'https://fullcalendar.io/demo-resources.json?with-nesting&with-colors',
    events: 'https://fullcalendar.io/demo-events.json?single-day&for-resource-timeline'
Expected Schedule to match 
What happens instead? Incorrect CSS is displayed, see screenshot below

### Screenshots

![image](https://user-images.githubusercontent.com/17654926/99490240-75217880-2937-11eb-85d5-ebe4413d4ff6.png)

I believe the fix is some CSS change/file that I am missing

**Comment by acerix** [comment]
Please post a [runnable, stripped-down demonstration of the bug](http://fullcalendar.io/wiki/Reduced-Test-Cases/).  I don't see any issue in the demo you linked.
