### ISSUE TITLE
`changeView()` with multiple, synced calendars causes view rendering issues 

### ISSUE THREAD

**Issue by berndartmueller** [fullcalendar/fullcalendar#5983]
### Reduced Test Case

https://codepen.io/berndartmueller/pen/WNxVRJz

### Bug Description

**Describe how to recreate the bug.**

1. Click on "week" in the right header toolbar buttons of the first calendar to switch to week view.
2. Click on "day" in the right header toolbar buttons of the first calendar to switch to day view.
3. Click on "week" again in the right header toolbar buttons of the first calendar to switch to week view again.

And:

If you continue clicking on "month", it also throws an exception:

```
Uncaught TypeError: Cannot read property 'years' of undefined
    at tt (main.min.js:6)
    at main.min.js:6
    at t.Zs (main.min.js:6)
    at t.buildSlatMetas (main.min.js:6)
    at t.render (main.min.js:6)
    at I (main.min.js:6)
    at main.min.js:6
    at Array.some (<anonymous>)
    at C (main.min.js:6)
    at flushToDom (main.min.js:6)
```

**What do you expect to happen?**

Week view should get correctly rendered and no error should be thrown.

**What happens instead?**

Multiple views are rendered on top of each other. In some cases, if you repeat steps 1 to 3, views are appended on the bottom of the calendar on each render.

### Screenshots

<img width="623" alt="Screenshot 2020-11-23 at 12 46 30" src="https://user-images.githubusercontent.com/761018/99958619-fdfe4100-2d89-11eb-9e77-adc979251339.png">

Thanks a lot!

**Comment by nsocheleau** [comment]
+1
Experiencing the same issue.

**Comment by acerix** [comment]
The issue is with changing the other calendar before `viewClassNames` returns, it works with a timeout:

https://codepen.io/acerix/pen/MWjgemV?editors=0010

Although I'm not sure it's a bug since `viewClassNames` is intended only to provide class names, you should use `datesSet` for this:

https://codepen.io/acerix/pen/JjRPKVj?editors=0010

**Comment by nsocheleau** [comment]
I have a second example with the same error

https://codepen.io/nsocheleau/pen/oNLKWrR

If you click the switch button to go from the resource view to grid view (my usage allow to switch to a grid calendar for a single resource and back to the calendar with all the resources)
Then click again to rollback into the resource view.
You'll notice that the none of buttons on right are selected, yet I would expect the week button to be selected.
Clicking the month button shows a grid calendar and not a resource month calendar
Click the week button throws the error.

Thanks
