### ISSUE TITLE
v5.4.0 regression - RRule overlapping a DST change doesn't give the same result than in v5.3.1

### ISSUE THREAD

**Issue by sebap100** [fullcalendar/fullcalendar#5985]
### Reduced Test Case

Test cases:

- v5.3.1: https://codepen.io/sebap100/pen/QWEeBmm
- v5.4.0: https://codepen.io/sebap100/pen/wvWVxjr

### Bug Description

When creating a recurring event which overlaps a DST change using a RRule string:
- In v5.3.1: the start time of all the events are equals (the DST change is taken into account).
- In v5.4.0: the start time of all the events are not equals.

When I create a recurring event with a specific time, I expect all the events to occur at the same time according to the local timezone. This is correctly managed in v5.3.1, but not in v5.4.0.

My local timezone is Europe/Brussels.

### v5.3.1
![image](https://user-images.githubusercontent.com/22453241/100027004-f8633280-2e3f-11eb-9829-d2ac18c58c1a.png)

### v5.4.0
![image](https://user-images.githubusercontent.com/22453241/100026955-dcf82780-2e3f-11eb-8560-53df2ea5282b.png)

**Comment by acerix** [comment]
I believe this existing ticket captures this need:
https://github.com/fullcalendar/fullcalendar/issues/5973
↑
Please visit the above issue, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates.
