### ISSUE TITLE
if allDay: true, the end date is lost one day

### ISSUE THREAD

**Issue by Dongw1126** [fullcalendar/fullcalendar#5997]
### Reduced Test Case

[REDUCED TEST CASE](https://jsfiddle.net/hfk4o3Lb/28/).

### Bug Description

If the schedule is allDay, the end date is lost by one day.
If it is not allDay, it can be solved by adjusting the time, but if it is allDay, the end date must be increased by one day..
In the case of allDay, is it possible to simply display the date specified as start and end?

### Screenshots
![image](https://user-images.githubusercontent.com/48395704/100521246-a9bdeb80-31e5-11eb-9474-66b009c7f266.png)

**Comment by acerix** [comment]
The end date is exclusive, so for an event to end at the end of 2020-11-07, the end date need to be 2020-11-08.
