### ISSUE TITLE
nowIndicator not positioned correctly for resourceTimelineYear view with slot duration 1 month

### ISSUE THREAD

**Issue by hisuwh** [fullcalendar/fullcalendar#5999]
### Reduced Test Case

See the reproduction here:
https://codepen.io/hisuwh/pen/VwKLBjX?editors=0010

### Bug Description

Using the resourceTimelineYear with the slot duration set to 1 month, and with the nowIndicator set to true it is not shown in the correct position

Today - being the 1st December - I would expect to see the now indicator at the start of December (or partially into it).
![image](https://user-images.githubusercontent.com/4470351/100734648-e5181000-33c7-11eb-8d13-1690cd0c8716.png)

It is instead shown at the start of January next year:
![image](https://user-images.githubusercontent.com/4470351/100734719-fd882a80-33c7-11eb-98c7-4d17a901f573.png)

**Comment by arshaw** [comment]
I've forced the `initialDate` to be `2020-12-02` and I'm seeing the correct behavior:
https://codepen.io/arshaw/pen/abmJKey?editors=0010

![Screen Shot 2020-12-15 at 11 00 05 AM](https://user-images.githubusercontent.com/56520/102239326-bbc9aa80-3ec4-11eb-8fe4-4c6e5d98bf09.png)

Are you still seeing the wrong behavior?

**Comment by acerix** [comment]
Seems specific to 'now' being in the first week of December:

https://codepen.io/acerix/pen/QWKpYQP?editors=0010

**Comment by arshaw** [comment]
this is no longer an issue as of 5.5.0: https://codepen.io/arshaw/pen/ZEpydrW?editors=0010
