### ISSUE TITLE
Month/day names isn't translated for "is" language

### ISSUE THREAD

**Issue by gunnargj** [fullcalendar/fullcalendar#6006]
### Reduced Test Case

https://codepen.io/gunso/pen/QWKjgRy

### Bug Description

The month names and week names isn't translated in icelandic. Other strings is ok

**Comment by acerix** [comment]
Those translations are handled by the browser, I see them in your demo with both Firefox and Chrome.  For browsers without support, you need a date formatting plugin.

https://fullcalendar.io/docs/luxon-plugin
