### ISSUE TITLE
Mark active view in the toolbar for accessibility

### ISSUE THREAD

**Issue by rawroland** [fullcalendar/fullcalendar#6008]
### Checklist

  - [x] I've already searched through [existing tickets](https://fullcalendar.io/issues)
  - [x] Other people will find this feature useful

### Feature Description

The active view is currently styled with css but there is no provision for accessibility, especially for the visually impaired. This feature would add the `aria-pressed` to the view button group and mark the active view with the value `true` as per https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/button_role.

**Comment by acerix** [comment]
I believe this existing ticket captures this need:
https://github.com/fullcalendar/fullcalendar/issues/2536
↑
Please visit the above issue, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates.
