### ISSUE TITLE
locale: 'zh', Change some styles, for help!

### ISSUE THREAD

**Issue by snailsmail** [fullcalendar/fullcalendar#6011]
### Checklist

Please mark these items with an [x]

  - [ ] I've already searched through [existing tickets](https://fullcalendar.io/issues)
  - [ ] Other people will find this feature useful

### Feature Description

I want to do something about it:

![2020-12-04 17-17-02 的屏幕截图](https://user-images.githubusercontent.com/16486227/101147513-6e914180-3657-11eb-8239-502fa21813b8.png)

Week and date with Chinese characters removed

let options = {
    views: {
      week: ''
    },
    headerToolbar: {
      left: 'prev,next today',
      center: 'title',
      right: 'dayGridMonth,timeGridWeek,timeGridDay,listMonth'
    },
    locale: {
            code: 'zh-cn',
            weekday: 'narrow',
            day: '2-digit'
    },
    buttonIcons: false, // show the prev/next text
    weekNumbers: true,
    navLinks: true, // can click day/week names to navigate views
    editable: true,
    dayMaxEvents: true, // allow "more" link when too many events
    events: 'https://fullcalendar.io/demo-events.json?overload-day'
  }

And now it is

![2020-12-04 17-16-40 的屏幕截图](https://user-images.githubusercontent.com/16486227/101147725-b57f3700-3657-11eb-8fe3-d2a58b40b698.png)

**Comment by acerix** [comment]
You can use `dayCellContent` to change the format:

https://github.com/fullcalendar/fullcalendar/issues/5439#issuecomment-650788071
