### ISSUE TITLE
Locales are not compatible with IE 11

### ISSUE THREAD

**Issue by itsNikolay** [fullcalendar/fullcalendar#6014]
### Reduced Test Case

CodePen does not support IE 11, so I couldn't provide example of the bug

### Bug Description

`de` locale is not compatible with IE 11

The bug is:  `./node_modules/fullcalendar-core-latest/locales/de.js` in `moreLinkText` function format

Correct function should be something like this:

```diff
-   moreLinkText(n) {
+   moreLinkText: function(n) {
```

### Screenshots

![Screenshot 2020-12-07 at 09 58 04](https://user-images.githubusercontent.com/786577/101319953-e471f480-3873-11eb-8ce3-b545033b5b5e.png)
![Screenshot 2020-12-07 at 09 58 20](https://user-images.githubusercontent.com/786577/101319959-e6d44e80-3873-11eb-84b3-b00b6d9172e3.png)
![Screenshot 2020-12-07 at 09 58 40](https://user-images.githubusercontent.com/786577/101319963-e76ce500-3873-11eb-91b1-6f6d001cde21.png)

**Comment by acerix** [comment]
Thanks confirmed, this demo shows the error:

https://cdpn.io/acerix/debug/wvzWzMN/yYryLaybNzYM

**Comment by arshaw** [comment]
this is fixed in 5.5.0
