### ISSUE TITLE
[Scheduler] - setState limit can be exceeded in ScrollGrid causing crash

### ISSUE THREAD

**Issue by lucasyvas** [fullcalendar/fullcalendar#6015]
### Reduced Test Case

When changing page zoom, the page **_can_** crash almost immediately under certain, unclear conditions.

### Bug Description

This is not trivial to recreate. We encountered it when applying borders to some elements in our app (build time, static CSS stylesheet changes). We were additionally not able to find any re-renders in our code that would prompt this behaviour.

`ScrollGrid` can get caught in a `componentDidUpdate` -> `handleSizing` loop to the point that React crashes (setState limit exceeded). It doesn't seem to have a condition to prevent re-rendering, which could be one problem. The exact failure spot is in `ClippedScroller`, which is re-rendered by every state change from the parent as the props technically change.

![image](https://user-images.githubusercontent.com/3365616/101551885-b1f4f400-3966-11eb-9b20-2959f3c23165.png)

I tried to add a function to the prototype to check if an update should be performed, and it seems like in all cases an update should be performed. The calculations fluctuate between 1-2 pixels in some cases for unexplained reasons, but it's a change so I guess it makes sense to apply it.

https://github.com/fullcalendar/fullcalendar-scheduler/blob/fdf51dd8136aa99706e7321454c04e33f6ea85e0/scrollgrid/src/ScrollGrid.tsx#L253

**Comment by acerix** [comment]
Would you be able to post a [runnable, stripped-down demonstration of the bug](http://fullcalendar.io/wiki/Reduced-Test-Cases/)? Would really appreciate it because the time saved reproducing will be time spent fixing.
