### ISSUE TITLE
calendar.changeView not working with resourceTimeline

### ISSUE THREAD

**Issue by CraftyDlx** [fullcalendar/fullcalendar#6017]
### Bug Description
I was looking for a way to set a certain time range in the view and found `changeView` (https://fullcalendar.io/docs/Calendar-changeView) . It is working with `timeGrid` but not with `resourceTimelineWeek` or `resourceTimelineMonth`. I am not getting any errors. Is this intentional?

### Reduced Test Case
https://codepen.io/craftydlx/pen/RwaqbvL

### Code

```
    customButtons: {
        myDate: {
          text: 'jump',
          click: function() {
              calendar.changeView('timeGrid', {             //working
            //calendar.changeView('resourceTimelineWeek', {   //not working
            //calendar.changeView('resourceTimelineMonth', {   //not working
              start: '2020-10-01',
              end: '2020-10-07'
            });
          }
        },
    },
```
By the way: Actually I don't need to change the view (e.g. from `resourceTimelineWeek` to `resourceTimelineMonth`), I only need to set a specific time range in the existing view by button. Is there a better way to do this? Thanks.

**Comment by CraftyDlx** [comment]
I just found `visibleRange` but it's the same: It does work with `timeGrid` but not with `resourceTimelineWeek` or `resourceTimelineMonth`. 

```
initialView: 'resourceTimelineWeek',    
customButtons: {
        myDate: {
          text: 'jump',
          click: function() {
           calendar.setOption('visibleRange', {
              start: '2020-10-01',
              end: '2020-10-07'
            });
          }
        },
    },
```

**Comment by acerix** [comment]
`resourceTimelineWeek` overrides the visible range, you can use `resourceTimeline` to set the range manually:

https://codepen.io/acerix/pen/xxEREpO

**Comment by CraftyDlx** [comment]
Thanks, that worked but now the today-button does not jump back to today's date. I guess that it, because I don't use the built-in prev and next buttons? Do I have to tell the today button now explicitly to jump to today's date?

**Comment by acerix** [comment]
The today button needs "today" to be within the visibleRange, so does not work with a static visibleRange, but visibleRange can be a callback to make that work.

**Comment by CraftyDlx** [comment]
Sorry, I don't understand. According to https://fullcalendar.io/docs/Calendar-gotoDate it must be quite simple. I tried
```
customButtons: {
        myTodayButton: {
          text: 'JumpToToday',
          click: function() {
            var now = moment().format(); // 2020-12-17T17:23:15+01:00
            calendar.gotoDate( now );
          }        	
        }
```
but nothing happens. I also tried the docs on https://fullcalendar.io/docs/visibleRange but failed to manage. Could you give me a hint how to approach here? Thanks a lot.

**Comment by acerix** [comment]
You need to supply `visibleRange` "as a function" and have that always return a range which includes the "currentDate" that is passed in.
