### ISSUE TITLE
Events can be completely hidden behind others with custom eventOrder

### ISSUE THREAD

**Issue by easededge** [fullcalendar/fullcalendar#6019]
### Reduced Test Case

https://codepen.io/bestrong89/pen/ExgNKmw?editors=0010

### Bug Description

Some events are hidden behind others when the event order is set to "title,-allDay,start,-duration"

### Screenshots

<img width="681" alt="Screen Shot 2020-12-10 at 12 04 30 PM" src="https://user-images.githubusercontent.com/60759655/101812307-cfe66400-3ae0-11eb-8cdd-3fe7a10f3572.png">
<img width="644" alt="Screen Shot 2020-12-10 at 12 04 44 PM" src="https://user-images.githubusercontent.com/60759655/101812312-d07efa80-3ae0-11eb-93df-9556a842cc76.png">

**Comment by arshaw** [comment]
very similar to https://github.com/fullcalendar/fullcalendar/issues/2758

**Comment by arshaw** [comment]
This has been fixed in v5.7.0!
blog post: https://fullcalendar.io/blog/2021/05/new-features-in-v570

**Comment by easededge** [comment]
This is great news, thanks for the heads up!

Ben Strong
—
Owner / Development Lead
785 202-3070
***@***.***
easededge.com
