### ISSUE TITLE
Custom dialog to ask event information

### ISSUE THREAD

**Issue by abelardolg** [fullcalendar/fullcalendar#6021]
### Checklist

Please mark these items with an [x]

  - [x] I've already searched through [existing tickets](https://fullcalendar.io/issues)
  - [x] Other people will find this feature useful

### Feature Description
When I click over a day, I would like to show a custom dialog in order to ask to the user the title of the event (or more information). Now, a prompt is showed but what if I would like to show a dialog window from Material UI for React? 
https://material-ui.com/es/components/dialogs/
How to show a visual React component inside your handleDateSelect function? 🤔 I can't do it 

Please describe what this feature will do.
To show a nice dialog to ask to the user the title of the event or custom the dialog to ask them more information.

### Visual Mockups
https://material-ui.com/es/components/dialogs/

If you are requesting a new UI, please include a mockup.
If not, erase this section.
https://material-ui.com/es/components/dialogs/

Thanks for your nice React component 😍😍😍😍😍😍😍😍

**Comment by acerix** [comment]
Sorry for the delayed response, I missed this when it came in.  You can use a callbacks like [eventClick](https://fullcalendar.io/docs/eventClick) to open a dialog when an event is clicked, for example.
