### ISSUE TITLE
No button texts with Bootstrap plugin, bad alignment

### ISSUE THREAD

**Issue by abelardolg** [fullcalendar/fullcalendar#6022]
### Reduced Test Case

You must paste a link to a [REDUCED TEST CASE](https://fullcalendar.io/reduced-test-cases).
If you do not, this issue will automatically be closed.
To prevent this, include the text "not reproducible with a link" (assuming it's true).
Not reproducible with a link

### Bug Description
When I set the Bootstrap plugin, the button texts aren't correctly showed

Describe how to recreate the bug.
1. npm install --save @fullcalendar/core @fullcalendar/bootstrap
2. npm install --save bootstrap @fortawesome/fontawesome-free
3. import 'bootstrap/dist/css/bootstrap.css';
4. import bootstrapPlugin from '@fullcalendar/bootstrap';

What do you expect to happen?
The button texts are correctly showed

What happens instead?
The button texts aren't showed and the button aren't correctly  aligned
### Screenshots
![image](https://user-images.githubusercontent.com/22522883/101982008-1cf94000-3c71-11eb-8310-36250b0a7281.png)
![image](https://user-images.githubusercontent.com/22522883/101982043-93963d80-3c71-11eb-972e-e40e382fca90.png)

These installations were executed today. The demo React-redux was cloned today.

**Comment by acerix** [comment]
Would you be able to post a [runnable, stripped-down demonstration of the bug](http://fullcalendar.io/wiki/Reduced-Test-Cases/)? Would really appreciate it because the time saved reproducing will be time spent fixing.
