### ISSUE TITLE
Duplicate Event when Drag, FullCalendar-5.3.2

### ISSUE THREAD

**Issue by calebeso** [fullcalendar/fullcalendar#6030]
**"not reproducible with a link"**

Im using the FullCalendar 5.3.2 version. 
When I drop an event to my calendar, he duplicate the event. But if I checked the 'remove after drop', he doesn't do that.

In this screenshot, I simple drag n drop the event 1 to 29 calendar day. 

![duplicate-event](https://user-images.githubusercontent.com/53923521/102390764-98c9f400-3fb3-11eb-95c8-2f628eee6cfd.png)

**Comment by Herz3h** [comment]
Linked issue #5789

**Comment by calebeso** [comment]
> Linked issue #5789 and [fullcalendar/fullcalendar-react#91](https://github.com/fullcalendar/fullcalendar-react/issues/91)

I actually discovered my issue! 
And I was simply calling my config.blade.app wich contains my js and css called files twice, so everytime I dropped the event on my calendar, he duplicate It because loaded this calendar.js twice!

**Comment by raibann** [comment]
> **"not reproducible with a link"**
> 
> Im using the FullCalendar 5.3.2 version. When I drop an event to my calendar, he duplicate the event. But if I checked the 'remove after drop', he doesn't do that.
> 
> In this screenshot, I simple drag n drop the event 1 to 29 calendar day.
> 
> ![duplicate-event](https://user-images.githubusercontent.com/53923521/102390764-98c9f400-3fb3-11eb-95c8-2f628eee6cfd.png)
I'm so sad it's error too in vuejs. when I drag first show 1 event then I change tab and return back to drag it again then it's show duplicate or more than 2
