### ISSUE TITLE
Expose listeners for prev, toda, next and when view changes buttons

### ISSUE THREAD

**Issue by thegiantbeast** [fullcalendar/fullcalendar#6032]
### Checklist

  - [x] I've already searched through [existing tickets](https://fullcalendar.io/issues)
  - [x] Other people will find this feature useful

### Feature Description

Currently there's no away (that I'm aware of) to listen for user interaction when switching between dates or views and it would be very helpful so that we could fetch progressively the events for example.

I know that I can create my own elements and use `.prev()/.today()/.next()` and `.changeView()`, but given that I would have to handle all these work (styles, responsiveness, etc) just to be able to handle the interaction, it seems there would be a good trade off by just exposing such option.

**Comment by acerix** [comment]
There is [datesSet](https://fullcalendar.io/docs/datesSet) for this.

**Comment by thegiantbeast** [comment]
Thanks @acerix missed that callback
