### ISSUE TITLE
Error in @fullcalendar/scrollgrid with NextJS (SSR)

### ISSUE THREAD

**Issue by bino98** [fullcalendar/fullcalendar#6037]
### Reduced Test Case

not reproducible with a link

### Bug Description

When using @fullcalendar/scrollgrid with NextJS.
(Included in @fullcalendar/resources-timeline)

The message `ReferenceError: navigator is not defined` is displayed and the process cannot be continued.
It is a recognition that no additional options are required for SSR in v5.2.0. Perhaps it's not complete.

What do you think. I'm sorry if it is a false consultation. 🙇 

### Screenshots

<img width="1053" alt="localhost_3000_dispatch" src="https://user-images.githubusercontent.com/353699/102751486-2e49f700-43ab-11eb-9203-03ebb1f284f5.png">

**Comment by acerix** [comment]
You might need extra config for NextJS as explained here:

https://github.com/fullcalendar/fullcalendar/issues/4784#issuecomment-667539521

If this is a bug, please supply a [runnable, stripped-down demonstration](http://fullcalendar.io/wiki/Reduced-Test-Cases/).

**Comment by bino98** [comment]
@acerix 
Thank for reply.

I have created Success and Failed containers for you to see.
- Success container uses `timegrid` plugin and it works correctly.
- Failed container uses `resource-timeline` plugin  and it works incorrect.

Please let me know if the code is missing.

https://codesandbox.io/s/nameless-http-c2bu6?file=/pages/failed.tsx

**Comment by bino98** [comment]
https://github.com/fullcalendar/fullcalendar-scheduler/blob/v5.5.0/scrollgrid/src/StickyScrolling.ts#L20

Probably. The following code is being called anytime?

**Comment by acerix** [comment]
I'm not sure how to test your demo or if it didn't save correctly,  it just shows me "404 This page could not be found." in the result.

**Comment by bino98** [comment]
@acerix 
Oh.. ok.
Please check the following page.

- Failed
  - This issue problem
  - https://c2bu6.sse.codesandbox.io/failed
- Success
  - As a reference for the problem. It succeeds when using `timegrid` plugin.
  - https://c2bu6.sse.codesandbox.io/success

**Comment by acerix** [comment]
Thanks for the details,  I get the same error and it looks like you are using it correctly so it seems `scrollgrid` may not be compatable with SSR.

**Comment by arshaw** [comment]
queued for release

**Comment by arshaw** [comment]
released!
https://github.com/fullcalendar/fullcalendar/releases/tag/v5.5.1

**Comment by bino98** [comment]
@arshaw Thank you for making the revisions. 🎉
