### ISSUE TITLE
How do I test a local build?

### ISSUE THREAD

**Issue by bwobbones** [fullcalendar/fullcalendar#6038]
### Reduced Test Case
not reproducible with a link

### Bug Description

This might be a silly question, but I'm trying to work on a PR and I have some rough code that I'd like to try before tidying up/writing tests etc.  There is nothing in the contribution guide that shows how to do this.

I can't work out how to use my version as a test dependency.  If I reference my fork in `package.json` it doesn't work, probably because the packages aren't built.

**Comment by acerix** [comment]
You need to build your fork with `yarn build`, then you can add it as a local dependency:

https://stackoverflow.com/a/14387210

**Comment by bwobbones** [comment]
For future me: this worked in the end, but no so simply.

I needed to also add a temporary dependency on `tslib` (probably because my project doesn't use typescript), then use it as a local dependency (no idea why it wasn't just picked up like normal).

**Comment by bwobbones** [comment]
Also - on push, need to remember the submodules things:

https://stackoverflow.com/questions/34707506/how-can-a-commit-in-git-submodule-trigger-a-build-in-continuous-integration
