### ISSUE TITLE
Pass custom props to custom view

### ISSUE THREAD

**Issue by phongnm-dev** [fullcalendar/fullcalendar#6048]
### Checklist

Please mark these items with an [x]

  - [x] I've already searched through [existing tickets](https://fullcalendar.io/issues)
  - [x] Other people will find this feature useful

### Feature Description
Hi, I've created a custom view with fullcalendar, but I can't find anyway to pass custom props to its, it only receive the default props from fullcalendar.
The default props passed to custom view is missing some necessary props like viewRender (viewDidMount)

**Comment by acerix** [comment]
There is no "custom props" for views but you could store your props in a global so they can be accessed in the custom view.
