### ISSUE TITLE
Header day labels displayed out of order

### ISSUE THREAD

**Issue by thaoula** [fullcalendar/fullcalendar#6053]
### Reduced Test Case
https://stackblitz.com/edit/angular-ivy-tvtkof?file=src/app/app.component.ts

### Bug Description
I am attempting to use the resourceTimeline plug to create a 7 day scheduler view using Full Calendar 5.5.0 and Angular 11.

Describe how to recreate the bug.

1. I add a full calendar component to my component and use the following options

`<full-calendar [options]="options"></full-calendar>`

```
2. public options = {
    initialView: "resourceTimeline7",
    plugins: [resourceTimelinePlugin],
    views: {
      resourceTimeline7: {
        type: "resourceTimeline",
        duration: { days: 7 }
      }
    },
    resources: [
      {
        id: 1,
        title: "Test"
      }
    ],
    events: [
      {
        id: 1,
        resourceId: 1,
        start: new Date().toISOString(),
        title: "Test"
      }
    ],
    height: '100%'
  } as any
```

What do you expect to happen?

Upon rendering the event will be rendering on the first day and the date headers will be in order for the start date to end date in the view.

What happens instead?

Upon rendering the events will be rendering in the correct slots but the date headers are out of order. When inspecting the html the class names for the event slots are correct but the date headers a different (can be seen in screenshot below)

As side note, I have noticed the sometimes when I change tabs or doing something to force a redraw the dates on the header will rendered correctly. However, I have not been able to identify the exact steps to make this happen.

### Screenshots

Initial Render

![image](https://user-images.githubusercontent.com/349133/103472787-2e42f180-4dc4-11eb-9b15-3ef2c465356a.png)

After some random time, switching tabs (not looking at the calendar)

![image](https://user-images.githubusercontent.com/349133/103472960-ffc61600-4dc5-11eb-804f-b301a1726722.png)

**Comment by acerix** [comment]
I tested the same in the debug template and the headers display in the correct order so it doesn't seem like a bug in the calendar.

https://codesandbox.io/s/long-water-lhxuj?file=/src/app/app.component.ts

I believe the issue is with how you are loading the plugins, now they should be loaded with `registerPlugins`.

**Comment by thaoula** [comment]
Hi @acerix,

thanks for looking at the issue. However, although I can see it working in the link you provided. Moving the the plugin registration to the module register plugins doesn't change the result I documented previously.

https://stackblitz.com/edit/angular-ivy-tvtkof?file=src/app/app.module.ts

Do you have any idea what else could be causing this issue?

Regards,
Tarek

**Comment by thaoula** [comment]
Hi @acerix,

I got this working but I am not sure how exactly.

As mentioned previously, I moved the registerPlugins to the module but it did not make a difference. So I tried to find the difference between your example app and mine.

In StackBlitz, just by chance, 

- I removed (cut) the references in package.json to force uninstall
- then pasted them back in. This forced Stackblitz downloaded them again and installed then ran ngcc.
- Upon refresh the project started working as expected. 

So I did the same in the real project. 

- Cut the fullcalendar components from package json
- npm install
- undo the cut
- npm install
- build
- Refresh the browser and the calendar is correct

Do you do anything special during the npm install of the package that can break? 

Regards,
Tarek
