### ISSUE TITLE
RRule byweekday property not working

### ISSUE THREAD

**Issue by bpoogle** [fullcalendar/fullcalendar#6059]
### Reduced Test Case

https://jsfiddle.net/hk10x2v3/

Tested with Chrome 87, Firefox 84, Edge 87

### Bug Description

Using FullCalendar with RRule plugin,
Create an event with object as rrule property with **freq**: 'weekly', **interval**: 1
Include **byweekday** property that specifies more than one day of the week.
The event is created but does not recur on the specified days of the week.  Instead it recurs only on the day of the week that **dtstart** falls on.
The exact code from the reduced example on jsfiddle works when resources for FullCalendar and RRule plugin are changed from version 5.5.0 to version 5.4.0

**Comment by arshaw** [comment]
released!
https://github.com/fullcalendar/fullcalendar/releases/tag/v5.5.1

updated test case:
https://jsfiddle.net/arshaw/fd2cn1mo/3/

**Comment by bpoogle** [comment]
Awesome - thanks!

**Comment by fahdshaykh** [comment]
thank you team!
