### ISSUE TITLE
View type is not maintained when clicking navLinks

### ISSUE THREAD

**Issue by kirsv-ldnet** [fullcalendar/fullcalendar#6064]
### Reduced Test Case

https://codepen.io/kirsv-ldnet/pen/oNzMjdy

### Bug Description

When you have both timelines and grids available in same view, the navlinks don't stay in the same type of view.
Recreate: Click day in the header section of the calendar.
Expected result: The selected day shown in the timeline view.
Actual result: the selected day shown in the grid view.

If the change in view is initiated from header the type of the view (timeline vs grid) should persist. Now the view is changed to which ever view has the same singleUnit.

**Comment by acerix** [comment]
It seems to use the first matching header button, so as a workaround, moving the timeline buttons first works.

https://codepen.io/acerix/pen/NWRBvXd

Replacing the time grid buttons with custom buttons should also work.

Also this new API would be a better solution:

https://github.com/fullcalendar/fullcalendar/issues/4931#issuecomment-518740419

**Comment by kirsv-ldnet** [comment]
The first workaround does not work, the problem just changes to the other view type.

**Comment by arshaw** [comment]
Setting [navLinkDayClick](https://fullcalendar.io/docs/navLinkDayClick) explicitly to `'resourceTimelineDay'` will solve this problem:

https://codepen.io/arshaw/pen/bGwJKdx?editors=0010

Otherwise, it uses the toolbar buttons to guess what should be done.
