### ISSUE TITLE
Locale Support Does not Render AM/PM

### ISSUE THREAD

**Issue by pradjays** [fullcalendar/fullcalendar#6065]
I am trying to use this for business opening hours in one of my projects and I am using the following method:

````
$('#delivery-hours-calendar').fullCalendar({
        header: false,
        allDaySlot: false,
        columnFormat: 'ddd',
        selectOverlap: false,
        eventOverlap: false,
        selectConstraint: {start: '00:00', end: '24:00'},
        slotLabelFormat: 'hh:mma',
        timeFormat: 'hh:mma',
        dayNamesShort: dayNamesList,
        defaultView: 'agendaWeek',
        firstDay: 1,
        defaultDate: '2017-07-03',
        navLinks: false,
        editable: true,
        selectable: true,
        selectHelper: true,
        height: 425,
        **locale: document.getElementById('locale').value,**
       ......
````

However, even though the locale is properly passed, it does not render the AM/PM in the calendar. I did try to pass the locale as follows:

`locale: 'ja'`

This did not work, either.

I love FullCalendar

**Comment by acerix** [comment]
Would you be able to post a [runnable, stripped-down demonstration of the bug](http://fullcalendar.io/wiki/Reduced-Test-Cases/)? Would really appreciate it because the time saved reproducing will be time spent fixing.
