### ISSUE TITLE
filterResourcesWithEvents hides empty resources but is impossible to cancel

### ISSUE THREAD

**Issue by FredTSousa** [fullcalendar/fullcalendar#6067]
### Reduced Test Case

https://codepen.io/fredtsousa/pen/wvzxqNd?editors=0011

### Bug Description

When i set filterResourcesWithEvents to true it indeed hides auditorium D, but setting it to false does not show it again and i can't find a way to show it again, if I use getResources it is still there. But isn't shown

### Screenshots
![Screenshot_781](https://user-images.githubusercontent.com/12846603/104057577-4c588980-51ea-11eb-8a8b-0c819743fc8d.png)

**Comment by acerix** [comment]
The issue is that you have `false` in quotes which makes it a string, and the string "false" evaluates to `true` in JS.

https://codepen.io/acerix/pen/VwKBMoz?editors=0010

**Comment by FredTSousa** [comment]
I suck, thanks!
