### ISSUE TITLE
Support for recurring events in iCalendar feed

### ISSUE THREAD

**Issue by scmunro** [fullcalendar/fullcalendar#6068]
Hi,

I can't seem to make recurring events work with the new iCalendar feed feature in react.

I've put together a simple react app at the following link to demonstrate. You will likely need to install a plug-in like Allow CORS on Chrome for it access the public ics feed.

https://codesandbox.io/s/fullcalendar-icalendar-recurr-v3sbs?file=/src/App.js

Please let me know if I am missing something.

**Comment by arshaw** [comment]
released!
https://github.com/fullcalendar/fullcalendar/releases/tag/v5.5.1
