### ISSUE TITLE
View styles are lost after changing to view with view-specific dayHeaders: false and with allDaySlot: false

### ISSUE THREAD

**Issue by tanmay-joshi-tfs** [fullcalendar/fullcalendar#6069]
Reduced Test Case
https://codepen.io/tanmayTFSC/pen/MWjBqKo

Bug Description
When allDaySlot is set to false, initialView is set to timeGridDay, and dayHeaders is set to false for timeGridDay; navigation from timeGridWeek to timeGridDay breaks timeGridDay view!
Recreate: 
Step 1) Click week in the header section of the calendar.
Step 2) Click day in the header section of the calendar.
Expected result: The timeGridDay should render as it does on calendar load.
Actual result: timeGridDay breaks after navigation.

**Comment by acerix** [comment]
Thanks, confirmed.

**Comment by arshaw** [comment]
released!
https://github.com/fullcalendar/fullcalendar/releases/tag/v5.5.1

updated test case:
https://codepen.io/arshaw/pen/ZEpVjoV
