### ISSUE TITLE
Option to resize events on drag and drop

### ISSUE THREAD

**Issue by OmarHegazi94** [fullcalendar/fullcalendar#6070]
### Checklist

Please mark these items with an [x]

  - [x] I've already searched through [existing tickets](https://fullcalendar.io/issues)
  - [x] Other people will find this feature useful

### Feature Description

Please describe what this feature will do.

**Is there a way to change the behavior of full calendar v4 when a user drag to make it resize instead of drag and drop similar to outlook desktop?**

**Comment by acerix** [comment]
That is not built it, event are resized by dragging the edges.  You could use `eventDrop` which happens after an event is moved to reset the start or end to the original which would resize it.

**Comment by OmarHegazi94** [comment]
@acerix thanks for the reply i will try it.
