### ISSUE TITLE
ListView unable to open url with missing a tag

### ISSUE THREAD

**Issue by escoand** [fullcalendar/fullcalendar#6071]
When having a custom `eventContent` without an `a` tag and `event.url` set, the ListView throws an error when clicking on the event. The DayGridView is working.

Reason is: https://github.com/fullcalendar/fullcalendar/blob/f55ba69a8247dda0cc6bb0c4aefceed21bf17eb9/packages/common/src/interactions/EventClicking.ts#L42

For reference see https://stackoverflow.com/a/65653334/3775041

**Comment by thewaywest** [comment]
Great. Nonetheless, the error was reported 3 years ago, and was just reported by my users today -- latest version. Devs should take a look. All I do is click from Month to ListView, and no link -- standard rendering, no custom html.
