### ISSUE TITLE
Incorrect display of month days in the glorious calendar (fa locate)

### ISSUE THREAD

**Issue by yapma** [fullcalendar/fullcalendar#6074]
### Reduced Test Case

[REDUCED TEST CASE (Your website demo section with locate fa)](https://fullcalendar.io/).

### Bug Description
Hi, if I set the 'locate' value of the calendar to 'fa', the calendar will be Persian, but the display of the days of the month will not start from the 1st.

### Screenshots
![image](https://user-images.githubusercontent.com/52157907/104197315-1873a300-543a-11eb-9e5a-6f7ff2dfb5f0.png)

**Comment by acerix** [comment]
I believe this existing ticket captures this need:
https://github.com/fullcalendar/fullcalendar/issues/1813
↑
Please visit the above issue, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates.
