### ISSUE TITLE
calendar crashes if slotMinTime and slotMaxTime is smaller than an hour and contentHeight is set to auto

### ISSUE THREAD

**Issue by daniel-stoll** [fullcalendar/fullcalendar#6083]
### Reduced Test Case

https://codepen.io/daniel-at-yasoon/pen/gOwQeJe?editors=001

### Bug Description

see the code pen and uncomment the contentHeight

**Comment by acerix** [comment]
The error is from the equals sign, it needs to be set like `contentHeight: 'auto'`.
