### ISSUE TITLE
Return the event's description in iCalendar package

### ISSUE THREAD

**Issue by diep-vu** [fullcalendar/fullcalendar#6097]
### Checklist

  - [x] I've already searched through [existing tickets](https://fullcalendar.io/issues)
  - [x] Other people will find this feature useful

### Feature Description

I think I might be useful that iCalendar returns in the extendedProps field the event's description. I have tried to fork your project and add this extra field on event building but I am not able to generate the javascript file (main.global.js) with the global variable FullCalendarICalendar.

I am looking forward to having your answer.

Thank you

**Comment by arshaw** [comment]
queued for release

**Comment by arshaw** [comment]
this has been released!
https://github.com/fullcalendar/fullcalendar/releases/tag/v5.6.0
