### ISSUE TITLE
Recurring events from an iCalendar have incorrect timezone for start/end

### ISSUE THREAD

**Issue by mikaelcom** [fullcalendar/fullcalendar#6106]
### Reduced Test Case

http://fullcalendar.mikael-delsol.fr/every_2d_fullday_4times.html

### Bug Description

When using an ICS feed containing an all-day event that must repeats iteself every second of the month from 02/02/2021 for only 4 times, it should be placed at the top of the day in the `timeGridWeek` view and it should only occurs 4 times (February, March, April and May of 2021)

It actually displays the event every second day of the month at 1am indefinitely in the future.

**Comment by materpillar** [comment]
I believe this is related: For me, all repeating events coming from an ical source are always shown at 1am.
Yet, pull request #6139 seems to fix the issue.

**Comment by mikaelcom** [comment]
> I believe this is related: For me, all repeating events coming from an ical source are always shown at 1am.
> Yet, pull request #6139 seems to fix the issue.

Ok, thanks.

I have other issues related to rrule with ics file such as http://fullcalendar.mikael-delsol.fr/every_1st_9am_6months.html. I'm clearly not familiar with Fullcalendar core code developement but I would need Fullcalendar to be fully working with both rrule and ics.

Do you need another issue? Would you be able to work on these issues related to rrule + ics?

**Comment by materpillar** [comment]
I tested both your ics feeds, and they work fine with the patch applied from the pull request that I mentioned.
So I believe that all we can do at this point is to wait for @arshaw to accept the pull request and release a fixed version.

**Comment by arshaw** [comment]
as @materpillar , this bug seems identical to the one solved by PR #6139. I've just merged it. It's queued for release.

**Comment by arshaw** [comment]
this is released!
https://github.com/fullcalendar/fullcalendar/releases/tag/v5.6.0
