### ISSUE TITLE
Prev button breaks with specific dateIncrement value

### ISSUE THREAD

**Issue by fkjohan** [fullcalendar/fullcalendar#6109]
### Reduced Test Case

[Reproduction of bug](https://codepen.io/fkjohan/pen/XWjQgzZ)

### Bug Description

This bug only seem to occur when `dateIncrement` is set to exactly one week.

#### Steps to reproduce:
1. Open the demo link
2. Select "dayGridTwoWeeks"
3. Click the "prev (<)" button.
4. It will work the first time, then, on consecutive clicks, do nothing

**Comment by acerix** [comment]
I believe this existing ticket captures this need:
https://github.com/fullcalendar/fullcalendar/issues/5319
↑
Please visit the above issue, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates.
