### ISSUE TITLE
Fullcalendar-scheduler: TimelineView issues

### ISSUE THREAD

**Issue by dextermb** [fullcalendar/fullcalendar#6111]
### Reduced Test Case

_Not reproducible with a link._

### Bug Description

I am currently upgrading versions of fullcalendar, along with other dependencies, on a legacy client project. I'm currently attempting to use:

* [fullcalendar@3.10.2](https://www.jsdelivr.com/package/npm/fullcalendar?version=3.10.2)
* [fullcalendar-scheduler@1.10.1](https://www.jsdelivr.com/package/npm/fullcalendar-scheduler?version=1.10.1)

When flicking through the different screens I seem to be getting internal errors from `fullcalendar-scheduler`. 

```
Uncaught TypeError: Cannot read property 'build' of undefined
    at ResourceTimelineView.TimelineView.buildCoords (scheduler.js:998)

// ...

Uncaught TypeError: Cannot read property 'clear' of undefined
    at ResourceTimelineView.releaseHits (scheduler.js:3302)
```

I am using sources from [jsdelivr.com](https://www.jsdelivr.com) and `fullcalendar` itself seems to be functioning as expected. Any ideas on the best way to resolve this issue would be much appreciated.

**Comment by acerix** [comment]
Would you be able to post a [runnable, stripped-down demonstration of the bug](http://fullcalendar.io/wiki/Reduced-Test-Cases/)? Would really appreciate it because the time saved reproducing will be time spent fixing.
