### ISSUE TITLE
dayGridMonth not respecting event color

### ISSUE THREAD

**Issue by bgp1** [fullcalendar/fullcalendar#6112]
### Reduced Test Case
https://jsfiddle.net/qw2sd4ue/

### Bug Description
My JSON data includes the backgroundColor property on an event-by-event basis. On the `timeGridWeek` and `timeGridDay` views the background color is respected for the event. However on `dayGridMonth` the default FullCalendar background color is used.

### Screenshots
Month view:
![image](https://user-images.githubusercontent.com/26612517/105548876-70719b80-5cbd-11eb-8968-c76f80210dd6.png)

Week view:
![image](https://user-images.githubusercontent.com/26612517/105548936-85e6c580-5cbd-11eb-9d61-fdba59ff571c.png)

**Comment by acerix** [comment]
It seems your demo is missing the resources I just get an error.  Please post a [runnable, stripped-down demonstration of the bug](http://fullcalendar.io/wiki/Reduced-Test-Cases/)? Would really appreciate it because the time saved reproducing will be time spent fixing.

**Comment by supairish** [comment]
@acerix I didn't create this Issue but I'm seeing the same behavior and this shouldn't be closed

Here's a codepen as asked for, my json feed's backgroundColor and borderColor do not seem to be respected on calendar

https://codepen.io/supairish/pen/jOVWyMM?editors=001

**Comment by thaoula** [comment]
Hi @acerix,

I am seeing the same issue and would appreciate if you please could re-open this bug. Other views are working fine and seem to respect the event colours on a per event basis.

**Comment by sam-k-taylor** [comment]
I am also seeing this exact issue

**Comment by acerix** [comment]
> @acerix I didn't create this Issue but I'm seeing the same behavior and this shouldn't be closed
> 
> Here's a codepen as asked for, my json feed's backgroundColor and borderColor do not seem to be respected on calendar
> 
> https://codepen.io/supairish/pen/jOVWyMM?editors=001

By default, timed-events are displayed as a dot so they don't have a background color in the day grid view, you can set `eventDisplay: 'block'` to change that:

https://codepen.io/acerix/pen/QWGKzVd?editors=001
