### ISSUE TITLE
FullCalendar v5.5.1 and RRule Plugin - Error

### ISSUE THREAD

**Issue by rheman** [fullcalendar/fullcalendar#6114]
### Reduced Test Case

not reproducible with a link

### Bug Description

I am trying to add RRule plugin using Script Tags. But I am getting a javascript error.

My web app requires AMD javascript and requireJS. FullCalendar is working perfectly in my app. But when I try to add RRule my following this example I got the following error in my JavaScript console.

```
main.global.js:41 Uncaught ReferenceError: rrule is not defined
    at main.global.js:41
```

As you can see on the attached screenshot, it seems like all required js script are loaded.
So I do not know how I am getting such error.

### Screenshots

![Screenshot from 2021-01-22 23-15-40](https://user-images.githubusercontent.com/4598772/105559379-ec450580-5d08-11eb-8485-d396883fd533.png)

![Screenshot from 2021-01-22 23-18-51](https://user-images.githubusercontent.com/4598772/105559390-f2d37d00-5d08-11eb-88f4-e57ded6c20d6.png)

**Comment by syedehsans1** [comment]
Hey @rheman, Were you able to fix this issue?

**Comment by rheman** [comment]
I am still looking for a solution
