### ISSUE TITLE
FullCalendar v5.5.1  - Event Popover Bug

### ISSUE THREAD

**Issue by rheman** [fullcalendar/fullcalendar#6116]
### Reduced Test Case

not reproducible with a link

### Bug Description

I enable Event popover when I too many events. So I set 

`dayMaxEvents: true,`
 
It works and the more link is displayed. But when I click on the more link, the popover is displayed outside de Fullcalendar. The popover is not displayed near the current more link.

### Screenshots

![Screenshot from 2021-01-26 11-02-29](https://user-images.githubusercontent.com/4598772/105837410-91403680-5fc6-11eb-9723-8b742c42d981.png)

Regards,

**Comment by acerix** [comment]
Would you be able to post a [runnable, stripped-down demonstration of the bug](http://fullcalendar.io/wiki/Reduced-Test-Cases/)? Would really appreciate it because the time saved reproducing will be time spent fixing.
