### ISSUE TITLE
Specifying timeZone on configuration causes Events to be shown in UTC

### ISSUE THREAD

**Issue by mduregon-lumary** [fullcalendar/fullcalendar#6121]
### Reduced Test Case
[Reduced Test Case](https://codepen.io/mdureg/pen/YzpzXwb)

### Bug Description

When using FullCalendar in Salesforce, if the user's time zone matches the system time zone, getting data and displaying it works great. If they are different (i.e. the user has a time zone of Australia/Sydney and the PC is set to Australia/Adelaide and the FullCalendar does not specify the timeZone in the configuration therefore is using the default of local), then an Event for 12PM ACST displays in the calendar as 12PM ACST and in Salesforce UI controls as 12:30pm AEST as an example. If you set the timeZone in the configuration to be Australia/Adelaide, the same event does not display as 12:00pm as expected, it now displays as 1:30AM.

Debugging the data, the response for the data request results in the date and time in UTC as below:
```
[
  {
    "clients": [],
    "endDateTime": "2021-02-01T02:30:00.000Z",
    "Id": "a1X1y0000006XxgEAE",
    "startDateTime": "2021-02-01T01:30:00.000Z",
    "status": "Draft",
    "title": "Session 12 PM AEST",
    "workers": []
  }
]
```

Adding an event handler for eventRender and writing out the value of the event you get:
```
event: EventApi
allDay: (...)
allow: (...)
backgroundColor: (...)
borderColor: (...)
classNames: (...)
constraint: (...)
durationEditable: (...)
end: (...)
extendedProps: (...)
groupId: (...)
id: (...)
overlap: (...)
rendering: (...)
source: (...)
start: Mon Feb 01 2021 12:00:00 GMT+1030 (Australian Central Daylight Time)
startEditable: (...)
textColor: (...)
title: (...)
url: (...)
_calendar: Calendar {buildComponentContext: ƒ, parseRawLocales: ƒ, buildLocale: ƒ, buildDateEnv: ƒ, buildTheme: ƒ, …}
_def: {groupId: "", title: "Session 12 PM AEST", url: "", rendering: "", extendedProps: {…}, …}
_instance: {instanceId: "12", defId: "11", range: {…}, forcedStartTzo: 0, forcedEndTzo: 0}
__proto__: Object
isEnd: true
isMirror: false
isStart: true
```

The start property suggests that the time of the event has been parsed correctly, but it is not displayed as 12:00PM (midday), it is displayed as 1:30AM in the morning. This happens as soon as you specify the timeZone property, no matter what you set that property to, but if left as the default (local), works great. However, when users with a machine who's system time zone does not match their Salesforce time zone, the data rendered in the calendar and the times shown in Salesforce controls do not match and causes confusion.

**Comment by acerix** [comment]
When `timeZone` is a named timezone, the times of events are not converted, they need to be provided in the specified timezone. 

https://fullcalendar.io/docs/timeZone#named-time-zones

You could use the timezone plugin to shift the times to be correct, or do it manually with `eventDataTransform`.

**Comment by mduregon-lumary** [comment]
Any chance you could them make it possible to load the plug-ins in a Salesforce LWC then?

Also, as a side note to being able to load the 4.x plug-ins in Salesforce, can you make it possible to even load the 5.x version in Salesforce LWC?

**Comment by acerix** [comment]
I believe this existing ticket captures this need:
https://github.com/fullcalendar/fullcalendar/issues/4990
↑
Please visit the above issue, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates.
