### ISSUE TITLE
Prevent slot from being selectable

### ISSUE THREAD

**Issue by aLanois14** [fullcalendar/fullcalendar#6122]
### Checklist

Please mark these items with an [x]

  - [x] I've already searched through [existing tickets](https://fullcalendar.io/issues)
  - [x] Other people will find this feature useful

### Feature Description

When I add an option singleEventSlot with a true value, it must prevent slots already filled by an event from being selectable.

**Comment by acerix** [comment]
You can use [selectOverlap](https://fullcalendar.io/docs/selectOverlap) for that.
