### ISSUE TITLE
Scrollbar only for events and not header -> scroll out of sync

### ISSUE THREAD

**Issue by lextoc** [fullcalendar/fullcalendar#6124]
### Reduced Test Case

Tried to reproduce but not occurring here... https://codesandbox.io/s/practical-carson-q85hu?file=/src/DemoApp.vue

### Bug Description

Using the `resourceTimelineDay` view in Vue, I got a vertical scrollbar on my events but not on the header. If you scroll horizontally to the end the hours slot lines will not match those of the events anymore. Tried to reproduce it but didn't manage to do so in CodeSandbox. Have attached a screenshot.

### Screenshots

![image](https://user-images.githubusercontent.com/4405004/106276729-462d5a00-6238-11eb-9607-616be9fac7c4.png)

**Comment by acerix** [comment]
Please post a [runnable, stripped-down demonstration of the bug](http://fullcalendar.io/wiki/Reduced-Test-Cases/) if there is a bug.
