### ISSUE TITLE
Issue with UNTIL at the end of RRULE

### ISSUE THREAD

**Issue by MicleBrick** [fullcalendar/fullcalendar#6126]
### Reduced Test Case

[REDUCED TEST CASE](https://codepen.io/MicleBrick/pen/gOLOXpm).

NOTE: To reproduce the error, change `var SELECTED = workingRRule;` to `var SELECTED = brokenRRule;`

### Bug Description

This recurrence rule (format generated by the JS rrule library) uses a specific timezone so that it works with daylight savings. It works fine without the `UNTIL` at the end, but `UNTIL` being at the end messes it up. The error mesage won't show in codepen console for some reason but I previously found the error in my own testing.

I made a pull request solving this issue here: https://github.com/fullcalendar/fullcalendar/pull/6080 @acerix requested that I open a separate issue

**Comment by arshaw** [comment]
thanks for this. i merged your pr (and added a test). queued for release

**Comment by arshaw** [comment]
this is released!
https://github.com/fullcalendar/fullcalendar/releases/tag/v5.6.0

updated demo:
https://codepen.io/arshaw/pen/VwPjNea?editors=0010
