### ISSUE TITLE
scrollTime doesn't work with height: auto

### ISSUE THREAD

**Issue by seb49** [fullcalendar/fullcalendar#6127]
### Reduced Test Case
https://codepen.io/zaedan/pen/QWGwwxW
### Bug Description

With  simple settings, scrollTime has no effect (it's ok with version 4.X)

**Comment by seb49** [comment]
It's ok by adding "height" parameter with pixel value, not auto.
I don't remember I have to add height parameter with V4

**Comment by ttamminen** [comment]
I have also problems with the `scrollTime`, but my test case is slightly different.

What I try to do is switch from month view to day view and set the time using calendar instance's API

https://codesandbox.io/s/flamboyant-curran-l0fk9?file=/src/DemoApp.jsx

**Comment by acerix** [comment]
Thanks, confirmed, same in 5.5.1:

https://codepen.io/acerix/pen/MWbKbvw?editors=001

**Comment by acerix** [comment]
I just realized from another ticket that is is not actually a bug.  The height of the calendar is too big so it can't scroll down any further which is why it can't reach 10:00 in the example.
