### ISSUE TITLE
[Angular] Show context-menu on dayGridMonth view

### ISSUE THREAD

**Issue by rallz-dev** [fullcalendar/fullcalendar#6131]
### Checklist

Please mark these items with an [x]

  - [ x ] I've already searched through [existing tickets](https://fullcalendar.io/issues)
  - [ x ] Other people will find this feature useful

### Feature Description

Offer the option to have a context-menu on right click that exposes the date clicked on the dayGridMonth view.
This option can then help user add or remove events based on what they chose on the context menu, or any other functionalities that the developer may think about. I've looked for this with Angular and found nothing that works.

### Visual Mockups

![image](https://user-images.githubusercontent.com/53878943/106539064-06869c80-64dc-11eb-8c0e-14937461e598.png)

**Comment by acerix** [comment]
I believe this existing ticket captures this need:
https://github.com/fullcalendar/fullcalendar/issues/2748
↑
Please visit the above issue, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates.
