### ISSUE TITLE
Drag & Drop from Fullcalendar to SortableJS and vice versa

### ISSUE THREAD

**Issue by fabien-lopes** [fullcalendar/fullcalendar#6132]
### Checklist

Please mark these items with an [x]

  - [x] I've already searched through [existing tickets](https://fullcalendar.io/issues)
  - [x] Other people will find this feature useful

### Feature Description

I'm working with Fullcalendar and SortableJS and I want to know if it is possible to drag & drop from Fullcalendar to SortabjeJS and vice versa.

I think **"Third-Party Dragging Libraries"** could be a solution but I didn't find any example with SortableJS.
It seems that the two libraries doesn't work together, we can drop an element from SortableJS to Fullcalendar but after that, we cannot anymore drop an element from one SortableJS list to other one.

Anyone can help me on this topic ?

Many thanks for your help
"I love FullCalendar"

**Comment by acerix** [comment]
I believe this existing ticket captures this need:
https://github.com/fullcalendar/fullcalendar/issues/3140
↑
Please visit the above issue, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates.
