### ISSUE TITLE
Business hours per resource do not fill row height with expandRows

### ISSUE THREAD

**Issue by OFMaurice** [fullcalendar/fullcalendar#6134]
### Reduced Test Case

https://codepen.io/OFMaurice/pen/YzpXLQQ

### Bug Description

If you set the business hours per ressource and have a resourcetimelineview with a specific height and the option 'expandRows' enabled, the business hours wont fit to the complete height of the resource row.

### Screenshots

![2021_02_02_16_11_10_A_Pen_by_OFMaurice](https://user-images.githubusercontent.com/39367315/106620235-a7736700-6571-11eb-8dba-8252c547d4ec.png)

**Comment by arshaw** [comment]
queued for release

**Comment by arshaw** [comment]
this is released!
https://github.com/fullcalendar/fullcalendar/releases/tag/v5.6.0

updated demo:
https://codepen.io/arshaw/pen/MWJeRwP?editors=0010
