### ISSUE TITLE
Group resources with multiple levels

### ISSUE THREAD

**Issue by phil1923** [fullcalendar/fullcalendar#6135]
### Checklist

Please mark these items with an [x]

  - [ x] I've already searched through [existing tickets](https://fullcalendar.io/issues)
  - [x ] Other people will find this feature useful

### Feature Description

It would be useful if the group resource functionality could work over multiple nested levels. 

For example, in a resource scheduling scenario, you could have department as the first grouping, then team as the second grouping.

**Comment by acerix** [comment]
If you mean child resources, that already works on multiple levels:

https://codepen.io/acerix/pen/GRNorYJ?editors=001

**Comment by phil1923** [comment]
@acerix Sorry for wasting your time and thank you for your support 😀
