### ISSUE TITLE
Resizing the resource column does not expand the lines between resources

### ISSUE THREAD

**Issue by acerix** [fullcalendar/fullcalendar#6140]
### Reduced Test Case

Can be seen in https://fullcalendar.io/docs/timeline-standard-view-demo

### Bug Description

Drag to expand size of resource column, lines do not always get extended.

### Screenshots

Reported in https://fullcalendar.freshdesk.com/a/tickets/2398 which includes a video

![Screenshot from 2021-02-03 17-14-37](https://user-images.githubusercontent.com/379534/106816473-6d729580-6643-11eb-9a95-fa37dba0a07b.png)

**Comment by arshaw** [comment]
queued for release

**Comment by arshaw** [comment]
this has been released!
https://github.com/fullcalendar/fullcalendar/releases/tag/v5.6.0

demo:
https://codepen.io/arshaw/pen/oNBLVON?editors=001

it's still not perfect, it has a debounce that prevents it from adjusting instantly, but it's better than before. I will completely fix in a future refactor.
