### ISSUE TITLE
Tooltip freezes when you drag an event

### ISSUE THREAD

**Issue by Cris200992** [fullcalendar/fullcalendar#6144]
### Reduced Test Case
https://codepen.io/pen/?&editors=001
[https://codepen.io/cris200992/pen/jOVbgbz?editors=001](url)
### Bug Description

Since i was uploaded to version 5 ( i came from version 3) the tooltips are frozen when i move the event. Specially on week and day views. I test it in firefox, explorer and crome and in all the navigators happen the same .

### Screenshots

![imagen](https://user-images.githubusercontent.com/35325847/106903354-2f847880-66fa-11eb-90c3-bbbe4f023ed1.png)

**Comment by acerix** [comment]
It doesn't seem like a bug in the calendar, I beleive you need to remove those tips from `eventWillUnmount`.
