### ISSUE TITLE
Fullcalendar - Events are badly rendered if calendar on a nav-tab

### ISSUE THREAD

**Issue by bastien70** [fullcalendar/fullcalendar#6145]
### Reduced Test Case

https://codepen.io/kiuega/pen/VwmeLgB
Just click on the second tab to display calendar.

### Bug Description

When a calendar is on a tab, and the page does not display this tab by default, then the events are badly positioned and form a big concentrate.

The only way to avoid this bug is to get to the tab before the events are rendered, or load the page directly on the tab that contains the fullCalendar.

Or simply by resizing the window, it will call the handleWindowsResize () function and resend the events as needed.

How to prevent this bug?

### Screenshots

![image](https://user-images.githubusercontent.com/53140475/106921667-84c98580-670c-11eb-913c-2501ba163c20.png)

**Comment by acerix** [comment]
You can call [updateSize](https://fullcalendar.io/docs/updateSize) after opening the tab to fix it.
