### ISSUE TITLE
View type stale at time of event request

### ISSUE THREAD

**Issue by nlwillia** [fullcalendar/fullcalendar#6151]
### Checklist

Please mark these items with an [x]

  - [x] I've already searched through [existing tickets](https://fullcalendar.io/issues)
  - [x] Other people will find this feature useful

### Feature Description

When making a dynamic request I want to use the [extraParams](https://fullcalendar.io/docs/events-json-feed#dynamic-extraparams-parameter) to include the view type the data is being fetched for so that I can vary the event structure with detail that is appropriate to the view format being changed *to*.  ([lazyFetching](https://fullcalendar.io/docs/lazyFetching) is disabled so cached events are not a consideration.)

However, at the time `extraParams` is evaluated the top-level view property has not yet changed.  Nor is there currently any parameter or *this* context for the call that would make the new view discoverable.  It would be preferable if the property were set or otherwise available so that the request can include it.  I *can* work around the problem by configuring the source as a function that returns something like `Promise.resolve().then(...actually fetch...)`, but this isn't very intuitive.

See [this example](https://codepen.io/nlwillia/pen/bGBpXbp) for a demonstration of how the value lags.

**Comment by acerix** [comment]
I believe this existing ticket captures this need:
https://github.com/fullcalendar/fullcalendar/issues/4660
↑
Please visit the above issue, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates.
