### ISSUE TITLE
Event start time is limited by what is visible by slotMinTime

### ISSUE THREAD

**Issue by mbihn** [fullcalendar/fullcalendar#6162]
### Reduced Test Case

Codepen: [https://codepen.io/MichaelBootstrap/pen/vYyxBgw](https://codepen.io/MichaelBootstrap/pen/vYyxBgw)  (Thanks to ADyson)

### Bug Description

If a event spans from 2pm to 6pm, but timegrif (week or day) shows only 4pm to end of day, the time in the event ist not correct rendered. (show 4pm -6pm instead of 2pm to 6pm)
Effect is visible also with (german) localisation (in my case).

### Screenshots

[https://stackoverflow.com/questions/66125303/show-events-with-its-correct-time-not-the-time-slot-in-fullcalendar-timegrid?noredirect=1#comment116929357_66125303](https://stackoverflow.com/questions/66125303/show-events-with-its-correct-time-not-the-time-slot-in-fullcalendar-timegrid?noredirect=1#comment116929357_66125303)

**Comment by acerix** [comment]
By default, the `timeZone` setting is "local", so the event times are also assumed to be in local time ("+01:00" is ignored), so this event gets shifted to where it's hidden.   You could set `timeZone` to UTC instead or may want to try the timezone plugin:

https://fullcalendar.io/docs/timeZone

https://codepen.io/acerix/pen/zYowBYJ

**Comment by mbihn** [comment]
That doesn't solve the bug. Even if you switch the Time Zone, the eventtime is reduced to the viewtime. In your codepen you made if even worse, because the event slides out of the current view for one more hour and the time in the event gets modified to 4:00 - 5:00pm  - but the event is from 1pm - 5pm (in UTC). I'd use GMT (with the default localisation for DE) - problem stays the same. 
To make it more clear: The time displayed in the event (fc-event-time), not the occupied time slot, is incorrect, because it show olny the visible time.

**Comment by acerix** [comment]
Thanks for the details, I see the issue now.  

In v5, the event start time is determined by what is visible according to `slotMinTime`:

https://codepen.io/acerix/pen/YzpePqJ?editors=001

In v4, it is the actual start time of the event:

https://codepen.io/acerix/pen/bGBLNpG?editors=001

It does seem like a bug since I would expect the actual start time and I didn't find any notes about that change.

**Comment by arshaw** [comment]
I see the bug.

I made a new example with timezones taken out of the equation:
https://codepen.io/arshaw/pen/xxgGBqZ?editors=0010

The event time-text should be `14:00 - 18:00` not `16:00 - 18:00`

**Comment by arshaw** [comment]
queued for release

**Comment by arshaw** [comment]
this has been released!
https://github.com/fullcalendar/fullcalendar/releases/tag/v5.6.0

demo: https://codepen.io/arshaw/pen/xxgGBqZ?editors=0010
