### ISSUE TITLE
Subsequent calls to event function success callback do not update events

### ISSUE THREAD

**Issue by hisuwh** [fullcalendar/fullcalendar#6163]
### Reduced Test Case

https://codesandbox.io/s/gifted-shirley-cjofs

### Bug Description

Given that the events function passes a callback to set the events I had assumed I could call this multiple times and could therefore solve an issue I was having - effectively allowing me to load in my events then lazy load in some additional data afterwards.

However subsequent calls to the success callback do not update the displayed events I would expect them to (see the test case above).

**Comment by acerix** [comment]
The success callback should only be called once in the events function.   You could call `refetchEvents` to run the function again to return new data, or you might want to supply the 2 lists of events as separate event sources so they load independently.

**Comment by hisuwh** [comment]
@acerix this is not documented anywhere.

Your proposals do not solve my problem, however.  I do not have two sets of events but rather am calling two APIs  with the second augmenting the data returned by the first.  So when the second loads I want to update the events.  

I  was blocking until they both had completed but with larger data sets the second takes significantly longer than the first (a problem I perhaps need to solve differently long term) so I was hoping I could display the events as soon as they load, then augment them with the extra data once that loads in.

**Comment by acerix** [comment]
Would it not work to have 2 event sources, and to remove the first one once the second one is loaded?

**Comment by hisuwh** [comment]
Mmm.  Good suggestion. That might work. I'll give it a go

**Comment by hisuwh** [comment]
@acerix actually simple removing the first one the second is loaded won't solve my problem.  As when I navigate to the next month I would need to follow the same pattern again.

**Comment by acerix** [comment]
I think it would work to add the first source from `datesSet`.
