### ISSUE TITLE
Create a recurring event with addEvent the last day of the week create two of them

### ISSUE THREAD

**Issue by alexandre-cariou** [fullcalendar/fullcalendar#6164]
### Reduced Test Case

https://codesandbox.io/s/fullcalendar-sunday-recurring-event-bug-11lnw

### Bug Description

Create an event by select the last day of the week (depends of locale)
You can see in the console, two events are created
Other days only one is created

**Comment by acerix** [comment]
Only one event is added, but since the event is recurring every week, `getEvents` is also including the instance from the week before (it returns all event instances in memory, not just visible ones).
