### ISSUE TITLE
Custom button content is changed when switching to another view

### ISSUE THREAD

**Issue by svanderh** [fullcalendar/fullcalendar#6165]
### Reduced Test Case
https://codepen.io/svanderh/pen/XWNRVWv
scenario to folow to reproduce:
- open calendar
- click on the custom button --> text on the button wil change
- change to another view
- original button text will be added to the changed - in the same button

### Bug Description
- scenario: assume that you want to create a custom button and you want to changte the text on the button when clicked
- create a custom button, and change the text of the button when clicked (basic example)
- this works when you stay in the same view
- if the content / text is changed, and if you change to another view, then the content is rewitten and the original content is added.

Rendered element after this action:
`<button class="fc-myCustomButton-button fc-button fc-button-primary" type="button">Updated text!custom!</button>`

I've tried different methods to change the content of the button, but they all end up in the same issue 
(code pen link is a very basic scenario)

### Screenshots
![image](https://user-images.githubusercontent.com/11912868/108189668-4a4ee800-7111-11eb-8c96-a2e45c0b0b3f.png)

**Comment by acerix** [comment]
The issue is with replacing the text node, it works to update only the value instead:

https://codepen.io/acerix/pen/XWNeQoG?editors=0010
