### ISSUE TITLE
Event disappears on day view with custom event order set

### ISSUE THREAD

**Issue by easededge** [fullcalendar/fullcalendar#6167]
### Reduced Test Case

Drag the blue event to 5:30pm and it will disappear.

https://codepen.io/bestrong89/pen/GRNmeer?editors=0010

### Bug Description

Some events are not shown when the event order is set to "title,-allDay,start,-duration"

### Screenshots

<img width="963" alt="Screen Shot 2021-02-17 at 1 39 47 PM" src="https://user-images.githubusercontent.com/60759655/108258456-a58ad580-7125-11eb-8d59-db28092d7c8e.png">

<img width="970" alt="Screen Shot 2021-02-17 at 1 39 53 PM" src="https://user-images.githubusercontent.com/60759655/108258446-a1f74e80-7125-11eb-8edb-700fbc1ea97f.png">

**Comment by acerix** [comment]
I believe this is the same bug as in your existing ticket:
https://github.com/fullcalendar/fullcalendar/issues/6167
↑
Please visit the above issue, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates.

**Comment by arshaw** [comment]
hey @acerix you accidentally linked to this issue.

@easededge , the preexisting ticket is here:
https://github.com/fullcalendar/fullcalendar/issues/6019

**Comment by arshaw** [comment]
@easededge , I responded to your support ticket. please let me know if you didn't receive the email
