### ISSUE TITLE
HTML content refresh during editing

### ISSUE THREAD

**Issue by slaakso** [fullcalendar/fullcalendar#6168]
### Reduced Test Case

A link to a [reduced test case](https://codepen.io/slaakso/pen/ExNxgmm).

### Bug Description

HTML content is added to the calendar via eventDidMount. During the editing (drag or resize), the events are redrawn in a way that the HTML code is added to the end of the element as text. 

In dragging the other events gets redrawn incorrectly. In resize the event being resized enough gets redrawn incorrectly and when the resize finishes, all the other events are redrawn incorrectly. It is possible to get the eventDidMount called again by refetching the events via the refetchEvents()

### Screenshots

![fullcalendar_resize](https://user-images.githubusercontent.com/726746/108322901-b2afcf00-71ce-11eb-8f3e-0a0e14cfd455.png)

**Comment by acerix** [comment]
To supply content to the events, you should use `eventContent` instead of `eventDidMount` which is intended for connecting to the DOM.
