### ISSUE TITLE
The website https://fullcalendar.io/ is Down

### ISSUE THREAD

**Issue by freezweb** [fullcalendar/fullcalendar#6170]
### Reduced Test Case
https://fullcalendar.io/reduced-test-cases

not reproducible with a link

### Bug Description

https://fullcalendar.io/reduced-test-cases

Internal Server Error

The server encountered an internal error or misconfiguration and was unable to complete your request.

Please contact the server administrator at [no address given] to inform them of the time this error occurred, and the actions you performed just before this error.

More information about this error may be available in the server error log.
Apache Server at fullcalendar.io Port 80

**Comment by acerix** [comment]
Thanks for the report, it seems this was a temporary server error that is now fixed.

**Comment by mauricioross** [comment]
Hi! it's down again! response 502
