### ISSUE TITLE
ical.js should not be a common/core dependency

### ISSUE THREAD

**Issue by cmlenz** [fullcalendar/fullcalendar#6171]
### Reduced Test Case

(not reproducible with a link)

### Bug Description

It looks like ical.js was added to the common package.json dependencies, even though it should only be required by the `@fullcalendar/icalendar`. The addition happened in https://github.com/fullcalendar/fullcalendar/pull/5969.

This is causing a bit of a problem for us due potential incompatibility of other licenses with the MPL. So I am hoping that the addition of this dependency to core was unintentional?

**Comment by aavelyn** [comment]
We have the same issue. While fortunately not a complete deal breaker (see [this post](https://opensource.stackexchange.com/questions/10493/using-of-library-under-mit-license-with-dependency-on-library-under-mpl-2-0)), it makes the usage of fullcalendar difficult in closed projects. Please fix this :)

**Comment by arshaw** [comment]
sorry about this dumb mistake. the core package's package.json defined ical.js as a dependency, but it was never included anywhere, and thus would not make it into your bundles. i've removed this unnecessary entry. will be released soon.

**Comment by arshaw** [comment]
this is released!
https://github.com/fullcalendar/fullcalendar/releases/tag/v5.6.0

**Comment by cmlenz** [comment]
Great, thank you!
