### ISSUE TITLE
End property for event with rrule is null in eventClick

### ISSUE THREAD

**Issue by pleshakovalexander** [fullcalendar/fullcalendar#6172]
### Reduced Test Case

 [REDUCED TEST CASE](https://codepen.io/SashaPl/pen/MWboodq?editors=0010).

### Bug Description

When i pass event array with end datetime and rrule after click event end property is null.

### Screenshots
Event without rrule
![image](https://user-images.githubusercontent.com/50041552/108382454-e82dda00-7219-11eb-9ace-e6d7f0eb40db.png)

Event with rrule
![image](https://user-images.githubusercontent.com/50041552/108382626-0f84a700-721a-11eb-9d2f-05642aeb6960.png)

**Comment by acerix** [comment]
Since the event is recurring, the end times are defined by setting the `duration` instead of `end`:

https://codepen.io/acerix/pen/wvorZVP?editors=0010
