### ISSUE TITLE
Include URL from iCalendar events in event props

### ISSUE THREAD

**Issue by fabacab** [fullcalendar/fullcalendar#6173]
### Reduced Test Case

Link to a reduced test case: https://codepen.io/fabacab/pen/yLVoRRY

### Bug Description

Include an `eventSources` array item that has its `format` set to `ics`; attempt to access any of its `event` objects' `url` property.

I expected the URL value from the iCalendar's `VEVENT` component's `URL` property to be returned.

Instead, FullCalendar returns an empty string.

Using the test case linked above, simply click on any of the events in the calendar to receive an `alert()` showing the event title (correctly returned) but missing the event's URL (which *does* exist in the iCalendar file used as the event source data).

**Comment by acerix** [comment]
I'm not sure that url should be set as `event.url` but could be useful to be able to access extra ics data for example in `extendedProps` or similar.

Related to https://github.com/fullcalendar/fullcalendar/issues/6097

**Comment by arshaw** [comment]
queued for release

**Comment by arshaw** [comment]
this has been released!
https://github.com/fullcalendar/fullcalendar/releases/tag/v5.6.0
