### ISSUE TITLE
Events objects are missing 'Editable' property

### ISSUE THREAD

**Issue by Seiifer** [fullcalendar/fullcalendar#6176]
### Reduced Test Case

https://stackblitz.com/edit/full-calendar-bug-g2wnbi?file=src%2Fapp%2Fride-calendar%2Fride-calendar.component.ts

Most relevant part of the test case above : 

Having this basic setup : 
```
      initialEvents: EventInput[] = [
        {
          title: 'Event 0',
          start: '2021-02-22T10:00:00',
          end: '2021-02-22T12:00:00',
          editable: false
        },
        {
          title: 'Event 1',
          start: TODAY_STR + 'T12:00:00',
          end: TODAY_STR + 'T16:00:00',
        },
        {
          title: 'Event 2',
          start: '2021-02-24T09:00:00',
          end: '2021-02-26T12:00:00',
        }
      ]
```

with this in my calendar options : 
```
// ...
initialView: 'timeGridWeek',
initialEvents: this.initialEvents,
eventClick: this.handleEventClick.bind(this),
// ...
```

and this method : 
```
  handleEventClick(clickInfo: EventClickArg): void {
    console.log(clickInfo.event);
    console.log(clickInfo.event.editable);
    if (confirm(`Are you sure you want to delete the event '${clickInfo.event.title}'`)) {
      if (clickInfo.event.editable) {
        clickInfo.event.remove();
      } else {
        alert('Editable events cannot be removed');
      }
    }
  }
```

### Bug Description

It seems the `EventApi` event fom my `clickInfo` works almost fine, it contains almost all the properties stated in the documentation there : https://fullcalendar.io/docs/event-object

Except it's missing the properties `editable` and `resourceEditable`.

When I click an event to remove it, the editable property is always undefined.

They are also missing in the `EventApi` class found in the `...\node_modules\@fullcalendar\common\main.d.ts` file.

So how can I access the editable property of my event when I click it ?

(I'm using the v5.5.0 with angular)

**Comment by acerix** [comment]
You can access it with `event.startEditable`, I believe `resourceEditable` is missing since you are not using resources.

**Comment by Seiifer** [comment]
Well, I don't think this issue sould be closed yet : 

`startEditable` and `editable` are two different properties, and they are both present in the `event` documentation, so I think they should both be present on it : 

Besides, I can have an event with : 
```
      editable: false,
      startEditable: true`
```

And they have a different effects : 
`startEditable` on an event allows the user to move the event on the calendar and change its starting date.
`editable` on an event allows the user to resize the event and change its ending dates, but not to change its starting date if `startEditable` is set to  `false`.

Besides, both options `editable` and `eventStartEditable` exists in the `CalendarOptions` properties and I assume they are supposed to be applied to every event of the calendar when specified.
Currently they are both undefined in the `events`, even if they are set in the `CalendarOptions`.

**Comment by acerix** [comment]
Events have `durationEditable` for if the duration can be edited. They don't actually have an `editable` property, that is just a shortcut option that sets both `startEditable` and `durationEditable`.

**Comment by Healyhatman** [comment]
And what about resourceEditable? I am absolutely using resources, I have events with resourceEditable true, and in eventAllow, eventResize, and eventDrop (haven't checked others) and calendar.getEvents none of the event objects have the resourceEditable property.

**Comment by piotrpalek** [comment]
bumping as I've just encountered this myself, the type definitions for `EventSourceInput` don't have the `resourceEditable` property, even though it's working and is in the documentation, meaning I need to do workarounds because the types don't match. Shouldn't this be considered a bug? @Healyhatman did you resolve your issue somehow?

**Comment by anrikun** [comment]
Same problem here.
editable is clearly documented as a property of the Event object.
Nonetheless, attempting to get it always returns undefined even if it was present in the parsed object.
This is definitely a bug.
