### ISSUE TITLE
Show where appt started while dragging for resourceTimeGridPlugin

### ISSUE THREAD

**Issue by jrock2004** [fullcalendar/fullcalendar#6185]
### Checklist

Please mark these items with an [x]

  - [x] I've already searched through [existing tickets](https://fullcalendar.io/issues)
  - [ ] Other people will find this feature useful

### Feature Description

If I start dragging an appointment and I want to just put it back, I have no way to know where the appointment originally was. Right now I could move the appointment outside the calendar and it will snap back to its place. I think a nice feature would be, is for the spot to have a customizable ghost box where you started so you could put it back

**Comment by acerix** [comment]
I believe this existing ticket captures this need:
https://github.com/fullcalendar/fullcalendar/issues/5250
↑
Please visit the above issue, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates.
