### ISSUE TITLE
gotoDate navigates to correct month but doesn't scroll to the requested date

### ISSUE THREAD

**Issue by vincent-aviva** [fullcalendar/fullcalendar#6189]
### Reduced Test Case
https://codepen.io/vincent-aviva/pen/MWbzwGN?editors=0010

### Bug Description

When clicking on the custom button in the above codepen the gotoDate function is called with the date 2021-02-27

I would expect that the calendar should
- Navigate to the correct month/week
- Scroll to the date in that month/week

The navigating to the correct week/month is done but you have to manually scroll to the date.

**Comment by acerix** [comment]
I believe this existing ticket captures this need:
https://github.com/fullcalendar/fullcalendar/issues/4806
↑
Please visit the above issue, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates.
