### ISSUE TITLE
ics events with rrule repeat eternally, ignoring rrule COUNT

### ISSUE THREAD

**Issue by nasenfloete** [fullcalendar/fullcalendar#6190]
### Reduced Test Case
https://codepen.io/lukasdue/pen/RwoeXRw

### Bug Description

I am adding events via an ics Feed with the iCalender plugin. One event is repeating eternally, even though it sould only repeat from 14.03.2016 - 20.06.2016. It is exported from Google Calendar, and the ics works correctly if I import it into my Mac Calendar-App.  Here is the event from the feed: 

BEGIN:VEVENT
DTSTART;TZID=Europe/Berlin:20160314T140000
DTEND;TZID=Europe/Berlin:20160314T163000
RRULE:FREQ=WEEKLY;COUNT=15;BYDAY=MO
DTSTAMP:20210226T234136Z
UID:xxx@google.com
CREATED:20160317T150025Z
DESCRIPTION:
LAST-MODIFIED:20160317T150025Z
LOCATION:
SEQUENCE:0
STATUS:CONFIRMED
SUMMARY:Teaching Assistent 
TRANSP:OPAQUE
END:VEVENT

Even stranger is, that in my local testcase it does show up eternally in monthGrid but not in dayGrid and weekGrid (see screenshots). I coun't reproduce this in the reduced Testcase, but it might be helpful debugging information. 

Thanks in advance!

### Screenshots
![image](https://user-images.githubusercontent.com/17799788/110498499-ab0d8700-80f7-11eb-89fe-a267916a3280.png)
![image](https://user-images.githubusercontent.com/17799788/110498536-b660b280-80f7-11eb-8c65-531e14557e75.png)

**Comment by nasenfloete** [comment]
Can you roughly estimate when the error will be fixed? That would really help me. Thanks in advance, Lukas

**Comment by arshaw** [comment]
queued for release

**Comment by arshaw** [comment]
this is released!
https://github.com/fullcalendar/fullcalendar/releases/tag/v5.6.0

in this demo, you'll see that COUNT limits the number of events occurrences:
https://codepen.io/arshaw/pen/eYgzoOQ?editors=0010
