### ISSUE TITLE
No resourceId method on event object

### ISSUE THREAD

**Issue by espen** [fullcalendar/fullcalendar#6191]
### Reduced Test Case

Drag an event from one resource to another here: https://codepen.io/espen_antonsen/pen/oNYQPmv

### Bug Description

When dragging an event from one resource to another I want to update the backend with the new details. However it doesn't look like it is possible to get the new resourceId from the event object. I see that it is updated (_def.resourceIds) but cannot get it directly on the event object (I would assume event.resourceId). I know I can get it from the newResource object but that complicates the process as I need to parse both the event object and the newResource object only if the resource has changed.

BTW: I think it would be better if ResourceId/ResourceIds were documented in the [event object](https://fullcalendar.io/docs/event-object). Now I have to find the see also link about [associating events with resources](https://fullcalendar.io/docs/resources-and-events) to see that events can have a resourceId.

**Comment by acerix** [comment]
You can get an event resources with [Event::getResources](https://fullcalendar.io/docs/Event-getResources):

https://codepen.io/acerix/pen/PobXPaL?editors=1010
