### ISSUE TITLE
ics event source does not update on refreshEvents

### ISSUE THREAD

**Issue by paologroppo** [fullcalendar/fullcalendar#6194]
### Reduced Test Case

https://codepen.io/paologroppo/pen/MWbZPLR?editors=001

### Bug Description

In the example above is expected that all eventsources will be refetched (after the interval of 10 seconds), but the second one in format 'ics' is never refetched.

**Comment by acerix** [comment]
Thanks, confirmed, I also tested with the plugin enable and a working feed and get the same:

https://codepen.io/acerix/pen/LYbvKPo?editors=0010

**Comment by arshaw** [comment]
this has been released!
https://github.com/fullcalendar/fullcalendar/releases/tag/v5.6.0

in this demo, you'll see that a network request is made each time the refresh button is pressed
https://codepen.io/arshaw/pen/OJWXqKm?editors=0010
