### ISSUE TITLE
Custom button icons documentation (v5)

### ISSUE THREAD

**Issue by ihorbond** [fullcalendar/fullcalendar#6197]
### Reduced Test Case

N/A

### Bug Description
I'm using default/standard theme system. Setting custom button icon to the value specified in [docs](https://fullcalendar.io/docs/buttonIcons)
has no effect.

```
customButtons: {
          back: {
            icon: 'fc-icon-chevron-left', // this is the className default 'prev' is using and this works
          },
          forward: {
            icon: 'right-single-arrow', // this doesn't work
          }
        }
```
### Screenshots
![screenshot2](https://user-images.githubusercontent.com/15573624/111094464-5c058e80-8509-11eb-99c4-77c202b7480d.png)
![screenshot1](https://user-images.githubusercontent.com/15573624/111094463-5b6cf800-8509-11eb-9d6c-1bf2d0764896.png)

**Comment by acerix** [comment]
Would you be able to post a [runnable, stripped-down demonstration of the bug](http://fullcalendar.io/wiki/Reduced-Test-Cases/)? Would really appreciate it because the time saved reproducing will be time spent fixing.
