### ISSUE TITLE
Timeline days view

### ISSUE THREAD

**Issue by espen** [fullcalendar/fullcalendar#6204]
### Checklist
  - [x] I've already searched through [existing tickets](https://fullcalendar.io/issues)
  - [x] Other people will find this feature useful

### Feature Description

Display a timeline-like view but with days as rows.

### Visual Mockups

<img width="600" alt="Tidslinje | Ola Nordmann | Busy 2021-03-17 15-50-21" src="https://user-images.githubusercontent.com/32258/111487645-d49e6200-8738-11eb-9f74-59431297be5a.png">

See demo at https://demo.busy.no/

**Comment by espen** [comment]
Seems to be similar to https://github.com/fullcalendar/fullcalendar/issues/4867

**Comment by acerix** [comment]
I believe the existing ticket captures this need:
https://github.com/fullcalendar/fullcalendar/issues/4867
↑
Please visit the above issue, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates.
