### ISSUE TITLE
Clicking inside the popover closes it with shadow DOM

### ISSUE THREAD

**Issue by belozer-ti** [fullcalendar/fullcalendar#6205]
### Reduced Test Case
Popover will be closed after click inside popover of the more content.

https://cg0md.csb.app/
https://codesandbox.io/s/recursing-pascal-cg0md

### Bug Description
Popover will be closed after click inside (on event).  Problem will be fixed after change 
`ev.target` to `ev.path[0]` in https://github.com/fullcalendar/fullcalendar/blob/master/packages/daygrid/src/Popover.tsx#L70

**Comment by belozer-ti** [comment]
Hi @arshaw. Can you look https://github.com/fullcalendar/fullcalendar/pull/6207? Because this problem blocks us :(

**Comment by arshaw** [comment]
i will be looking at this for the next release!

**Comment by arshaw** [comment]
This has been released in v5.7.0!
blog post: https://fullcalendar.io/blog/2021/05/new-features-in-v570
