### ISSUE TITLE
Incorrect translation of month names in Welsh

### ISSUE THREAD

**Issue by dufferv1** [fullcalendar/fullcalendar#6206]
### Reduced Test Case

This issue is visible from the fullcalendar demo site, https://fullcalendar.io/docs/locale-demo

### Bug Description

When selecting Welsh locale (CY), the month names are not correctly translated.
What is displayed is the English version of month names.
What should be displayed is the Welsh translation.

Welsh translations of Month names can be found here:
http://acen.co.uk/en/the-welsh-language/months-of-the-year/

### Screenshots

If the bug is visual, include a screenshot if possible.
If not, erase this section.
![image](https://user-images.githubusercontent.com/16079663/111989398-9c689c00-8b09-11eb-8bca-c1efe3ea2743.png)

**Comment by acerix** [comment]
I believe this existing ticket captures this need:
https://github.com/fullcalendar/fullcalendar/issues/5683
↑
Please visit the above issue, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates.
