### ISSUE TITLE
Firefox check for table height with thead is not reliable

### ISSUE THREAD

**Issue by georgique** [fullcalendar/fullcalendar#6225]
### Reduced Test Case

Not reproducible with a link.

### Bug Description

In my project I make calendar height 100% and get a vertical scrollbar. Investigation brought me to the following FC code:
```
    // firefox bug: when setting height on table and there is a thead or tfoot,
    // the necessary height:100% on the liquid-height body section forces the *whole* table to be taller. (bug #5524)
    // use getCanVGrowWithinCell as a way to detect table-stupid firefox.
    // if so, use a simpler dom structure, jam everything into a lone tbody.
    let isBuggy = !getCanVGrowWithinCell()
```
It seems that the method is not really reliable. I'm still not sure what exactly is wrong with it, but in my application in Firefox it results as not being buggy, table gets `thead` which leads to the scrollbar. In Chrome all good. 
I tried to make reproduce this method, and it seems it gives different results depending on whether Calendar is within an iframe or it isn't. Test attached. 
[test.zip](https://github.com/fullcalendar/fullcalendar/files/6223711/test.zip)

FullCalendar: 5.5.0 [Angular]
Browser: Firefox 87

### Screenshots

![image](https://user-images.githubusercontent.com/15987211/112882454-dabe0800-9081-11eb-86e6-4cc4857a1adb.png)
![image](https://user-images.githubusercontent.com/15987211/112882536-f0333200-9081-11eb-88ff-9d463d451e8d.png)

**Comment by acerix** [comment]
Would you be able to post a [runnable, stripped-down demonstration of the bug](http://fullcalendar.io/wiki/Reduced-Test-Cases/)? Would really appreciate it because the time saved reproducing will be time spent fixing.

**Comment by georgique** [comment]
Problem is - I tried to reproduce it, but I couldn't. Sometimes FF renders table with thead, sometimes without. So I just gave up and posted this here, because I'm not familiar with FC code enough to debug it and fix myself.

**Comment by georgique** [comment]
Please, reopen the ticket. As per the rules, I've mentioned it's not reproducible, yet the bug exists which is proven by the test I have attached.

**Comment by acerix** [comment]
For something like this we need a runnable demo showing the issue, "not reproducible" would be something like a build error.
