### ISSUE TITLE
Business Hours and Resource Business Hours

### ISSUE THREAD

**Issue by jrock2004** [fullcalendar/fullcalendar#6227]
### Checklist

Please mark these items with an [x]

  - [x] I've already searched through [existing tickets](https://fullcalendar.io/issues)
  - [ ] Other people will find this feature useful

### Feature Description

I want to setup the business hours and the resource business hours. Resources might start or end before or after or during business hours. I do not see that this is possible and would hope we could get support to do this

**Comment by acerix** [comment]
The business hours can be set for each resource:

https://fullcalendar.io/docs/businessHours-per-resource

I'm not sure what you mean by resource start/end (resources have no duration), but you could add background events to show when resources are "available".

**Comment by jrock2004** [comment]
Sorry, maybe I should of put more details. 

Scenario:
- My business is a 9am - 5pm Monday through friday
- My employees will have their own set of hours of operation

So on my calendar I want the ability to set the shade of grey for when that time is the business is closed and another shade of grey for when my resource is not available. This will help the users understand when the business is closed vs there is just no resources working during that time

At this time it seems like FC only has css classes for when resource is no available. So this is just quick dev tools but looking to be able to do something like this

![image](https://user-images.githubusercontent.com/655716/113147518-da974700-91fe-11eb-9980-a417347f4dfe.png)

**Comment by acerix** [comment]
Those can be added as background events.

https://fullcalendar.io/docs/background-events
