### ISSUE TITLE
Support relative path to icalendar file

### ISSUE THREAD

**Issue by NatalieThurlby** [fullcalendar/fullcalendar#6236]
### Checklist

Please mark these items with an [x]

  - [x] I've already searched through [existing tickets](https://fullcalendar.io/issues)
  - [x] Other people will find this feature useful

### Feature Description
Thank you for FullCalendar, I'm finding it really useful! I've used it to mock up a basic [Sphinx](http://sphinx-doc.org/) extension for displaying a calendar that's generated from static site metadata. I'm looking forward to using it on a few different projects.

I wonder if there's a possibility of reading a local icalendar file, rather than passing it a hosted URL. I can think of lots of ways in which this would be useful to others. For me, it would make previewing the site much easier (since I could build the icalendar file and the whole site at once). I think that would also open up the possibility of the Sphinx extension being useful to other people.

**Comment by acerix** [comment]
JavaScript is not allowed to access files from your system so I believe that's not possible.  You could install a web server to get a localhost URL,  or have your users upload the file and pass that data to the calendar.
