### ISSUE TITLE
Rendering background color in month view

### ISSUE THREAD

**Issue by dumedeiros** [fullcalendar/fullcalendar#6238]
### Checklist

Please mark these items with an [x]

  - [x] I've already searched through [existing tickets](https://fullcalendar.io/issues)
  - [x] Other people will find this feature useful

### Feature Description
It will be very handfull if there is a way of changing the background color of events in month view.
The background property of the events works fine for the day view, the week view and the 'allDay' events in month view, but events that aren't 'allDay' don't change their background color in the month view.

**Comment by acerix** [comment]
I believe this existing ticket captures this need:
https://github.com/fullcalendar/fullcalendar/issues/5533
↑
Please visit the above issue, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates.
