### ISSUE TITLE
Start and End time affecting the event view

### ISSUE THREAD

**Issue by BhanuPrakashReddyT** [fullcalendar/fullcalendar#6239]
### Reduced Test Case

You must paste a link to a [REDUCED TEST CASE](https://fullcalendar.io/reduced-test-cases).
If you do not, this issue will automatically be closed.
To prevent this, include the text "not reproducible with a link" (assuming it's true).

### Bug Description

Describe how to recreate the bug.
What do you expect to happen?
What happens instead?

### Screenshots

If the bug is visual, include a screenshot if possible.
If not, erase this section.

If we select start time more than or equal to **%YYYY-%MM-%DD 23:00:01** to **%YYYY-%MM-%DD 23:59:59** and end time as same as start time then the event is rendered in next day as like in below png
![image](https://user-images.githubusercontent.com/60179972/113566998-5e03ce80-962b-11eb-8a39-0b124ab74517.png)

**Comment by acerix** [comment]
Would you be able to post a [runnable, stripped-down demonstration of the bug](http://fullcalendar.io/wiki/Reduced-Test-Cases/)? Would really appreciate it because the time saved reproducing will be time spent fixing.

**Comment by BhanuPrakashReddyT** [comment]
var calendarEl = this.calendar.nativeElement;

    var calendar = new Calendar(calendarEl, {
      initialView: "dayGridMonth",
      initialDate: "2020-06-07",
      plugins: [dayGridPlugin, timeGridPlugin],
      headerToolbar: {
        left: "prev,next today",
        center: "title",
        right: "dayGridMonth,timeGridWeek,timeGridDay"
      },
      events: [
        {
          title: "Meeting",
          start: "2020-06-12 19:58:00",
          end: "2020-06-12 19:58:09"
        }
      ]
    });

    calendar.render();

**Comment by BhanuPrakashReddyT** [comment]
As i used this method, the calendar is plotted perfectly, but whenever the time change happens after 11:00 pm (both start and end should be same), then i am getting the issue. The following packages i had used:

"@fullcalendar/common": "^5.0.1",
  "@fullcalendar/core": "^5.0.0",
  "@fullcalendar/daygrid": "^5.0.1",
  "@fullcalendar/moment": "^5.0.0",
  "@fullcalendar/timegrid": "^5.0.1",

**Comment by BhanuPrakashReddyT** [comment]
Reproducable Link : 

https://stackblitz.com/edit/fullcalendar-condensed-event-veihws
