### ISSUE TITLE
Next JS - TypeError: Cannot read property 'isHiddenDay' of undefined

### ISSUE THREAD

**Issue by RubenMateus** [fullcalendar/fullcalendar#6243]
### Reduced Test Case
not reproducible with a link

### Bug Description

When using fullcalendar within my next js an error ocurrs.
I've tried using next-transpile modules. using several plugins and nothing.

TypeError: Cannot read property 'isHiddenDay' of undefined
    at new DaySeriesModel (C:\internal\tempura-web\.next\server\pages\app\calendar.js:13177:32)
    at DayTableView.buildDayTableModel (C:\internal\tempura-web\.next\server\pages\app\calendar.js:16395:19)
    at DayTableView.buildDayTableModel (C:\internal\tempura-web\.next\server\pages\app\calendar.js:4023:31)
    at DayTableView.render (C:\internal\tempura-web\.next\server\pages\app\calendar.js:16354:30)
    
### Screenshots

![image](https://user-images.githubusercontent.com/24896825/113776784-2deb2700-9722-11eb-953d-758ac66002ca.png)

**Comment by hisuwh** [comment]
I'm getting the same error in a vue application

**Comment by acerix** [comment]
Would you be able to post a [runnable, stripped-down demonstration of the bug](http://fullcalendar.io/wiki/Reduced-Test-Cases/) or steps to reproduce the issue? Would really appreciate it because the time saved reproducing will be time spent fixing.

It should work using this example project:

https://github.com/fullcalendar/fullcalendar-example-projects/tree/master/next

**Comment by RubenMateus** [comment]
@acerix i have exactly the same configuration as that project.
Before I opened the ticket I search a lot of solutions.
My last resort was to open a ticket so you guys could help me.
i don't think just closing the issue and sweeping it under the rug will help anyone...

**Comment by hisuwh** [comment]
I tried to create a reproduction for my case but code sandbox seems to abstract away the build process and upon adding in vue and typescript to match my setup I couldn't get it to build.

**Comment by RubenMateus** [comment]
@acerix https://codesandbox.io/live/pm63kft

**Comment by frederikhors** [comment]
Can we please re-open this?

**Comment by arshaw** [comment]
Hello all. I have wrapped my head around this issue and have written a separate ticket about why it's happening and how we can prevent it in the future. Please see #6370
