### ISSUE TITLE
Invalid Month Range In Month view for Hijri / Jalali Calendar

### ISSUE THREAD

**Issue by abmahmoodi** [fullcalendar/fullcalendar#6246]
### Reduced Test Case
Please see fa local in the following link:
https://fullcalendar.io/demos

### Bug Description

Hi,
For fa(Persian) locale you add Jalali calendar and Thanks for this feature. But in this locale in month view, Jalali month range is invalid and this view is based on Gregorian calendar.
I want to view only one Jalali Month (for example from 1 to 31 Farvardin) in month view.

### Screenshots

![Screenshot_20210408_225609](https://user-images.githubusercontent.com/659603/114078803-9ec74600-98be-11eb-9da4-ff060fb50970.png)

**Comment by acerix** [comment]
I believe this existing ticket captures this need:
https://github.com/fullcalendar/fullcalendar/issues/1813
↑
Please visit the above issue, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates.
