### ISSUE TITLE
Simple docs text search

### ISSUE THREAD

**Issue by christopherarter** [fullcalendar/fullcalendar#6249]
### Checklist

Please mark these items with an [x]

  - [x ] I've already searched through [existing tickets](https://fullcalendar.io/issues)
  - [x ] Other people will find this feature useful

### Feature Description

It'd be really great of the docs were searchable. There's quite a bit of content and I have to hunt & peck through links to find what I'm looking for as a new user. It'd be a huge help.

**Comment by acerix** [comment]
I believe this existing ticket captures this need:
https://github.com/fullcalendar/fullcalendar/issues/4196
↑
Please visit the above issue, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates.
