### ISSUE TITLE
Print optimization not working

### ISSUE THREAD

**Issue by frankguns** [fullcalendar/fullcalendar#6250]
### Reduced Test Case

https://fullcalendar.io/docs/timeline-standard-view-demo

### Bug Description

I could not get the print optimization to work in my project. So I checked the demo on your website via: https://fullcalendar.io/docs/print

If I click on print in the timeline demo page, then the output is also not what I would expect (see screenshot). I remember doing the same thing last summer, and then the print output from your demo page was looking good: multiple pages for all the scrollable content.

Is something broken, or is this not supported anymore?

### Screenshots

![image](https://user-images.githubusercontent.com/20965483/114157146-9fde8e80-9923-11eb-976a-9f663d810778.png)

**Comment by acerix** [comment]
The timeline view prints what is visible in v5, previous versions didn't have a print view: https://fullcalendar.io/docs/v4/timeline-standard-view-demo

You may be thinking of the timegrid view which prints all the events:

https://codepen.io/acerix/full/eYgypPj

**Comment by frankguns** [comment]
So this means that the print optimization is not useful at all for timeline view as in most cases all the events are only visible when scrolling horizontally?

Strange, I'm pretty sure that this was different end of last year. When I tried this on your website, printing a timeline view resulted in multiple pages, each showing part of the view.

**Comment by bino98** [comment]
I have same problem.

sometimes if print, there is cut off timeline view. probably when it will show timeline view so long width.
As a countermeasure, timeline view have taken a parent element and it have a limit of width specification. 

```tsx
<div style={{ width: '1080px' }}>
  <FullCalendar
    timeZone="UTC"
    plugins={[adaptivePlugin, resourceTimelinePlugin]}
    initialView="resourceTimelineDay"
    slotMinWidth="10"
    resources="https://fullcalendar.io/demo-resources.json?with-nesting&with-colors"
    events="https://fullcalendar.io/demo-events.json?single-day&for-resource-timeline"
  />
</div>
```

But I don't think it's a good solution. I want to feel good...

**Comment by gwl002** [comment]
I feel hard to find a print demo.So,what should I do?Just call `window.print()`?It looks strange and ugly.We are hesitating to buy a premium version.
