### ISSUE TITLE
dateClick not firing when clicking date in resource timeline view

### ISSUE THREAD

**Issue by hisuwh** [fullcalendar/fullcalendar#6256]
### Reduced Test Case

https://codesandbox.io/s/hardcore-williams-hx6s1?file=/src/DemoApp.vue

### Bug Description

I would expect the dateClick function to be called when clicking the date header in resource timeline week view.  
It actually does not fire.

**Comment by acerix** [comment]
`dateClick` only fires when clicking on a date cell, eg. you would need to add a resource and click on a date within that resource.

You can use `slotLabelDidMount` to add an onclick callback to the labels:

https://codepen.io/acerix/pen/rNjdONM?editors=001

**Comment by hisuwh** [comment]
One of your demos [here](https://fullcalendar.io/demos) navigates to a day when you click on the title.  Is this achieved in the way you have described above?
This seems a bit clunky when some other aspects of the API are so elegant (I had to build my own header to add certain functionality and found the built in `prev()`, `next()` and `today()` functions really useful).

**Comment by acerix** [comment]
That demo uses [navLinks](https://fullcalendar.io/docs/navLinks).

**Comment by hisuwh** [comment]
Ah ok.  Though setting that to true, clicking a day in `resourceTimelineWeek` or `resourceTimelineMonth` views takes you to `timelineDay` view instead of `resourceTimelineDay`
