### ISSUE TITLE
Allow selecting dates in multiple resources

### ISSUE THREAD

**Issue by mperktold** [fullcalendar/fullcalendar#6264]
### Checklist

Please mark these items with an [x]

  - [x] I've already searched through [existing tickets](https://fullcalendar.io/issues)
  - [x] Other people will find this feature useful

### Feature Description

In the resource timeline, I would like to be able to select not only multiple dates within the same resource, but also across multiple resources.

This could be achieved either by a single selection gesture over multiple resources, or by multiple gestures that add to the current selection when holding some key like `Ctrl`. The API could expose a settable property, e.g. `add-selections`, and the application could toggle set that property when holding `Ctrl` and clear it otherwise.

Or, it could be exposed only via `Calendar::select`, which would accept multiple selection objects, like:
```js
calendar.select([
  { *start1*, *end1* , *allDay1* , *resourceId1* },
  { *start2*, *end2* , *allDay2* , *resourceId2* },
]);
```

This would help us recreate our Java Swing component for the web with a similar look and feel, where you can first select multiple slots and then create a compound event that spans the selected dates and resources.

### Visual Mockups

Single selection gesture across resources:
![selectDatesOverResources](https://user-images.githubusercontent.com/7334069/114741894-825a5c00-9d4b-11eb-85bc-8cf73866de1f.png)

Multiple gestures that add to the existing selection:
![addToSelection](https://user-images.githubusercontent.com/7334069/114741927-88e8d380-9d4b-11eb-85f0-21e8b85f9cc6.png)

**Comment by acerix** [comment]
I believe this existing ticket captures this need:
https://github.com/fullcalendar/fullcalendar/issues/5015
↑
Please visit the above issue, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates.
