### ISSUE TITLE
Event badge is showing in two dates when Start Time and End Time are same and exceeds 23:00 (start and end should be same)

### ISSUE THREAD

**Issue by BhanuPrakashReddyT** [fullcalendar/fullcalendar#6265]
### Reduced Test Case

**Issue can be reproduced by following steps:**

1) start date and end date in events must be after 23:00:00 i.e., need to start from 23:00:01 and end on 23:59:59.
2) start and end date must be same.
3) Ex: start : '2020-06-12 23:00:01', end: '2020-06-12 23:00:01'.

**Reproducible Link :**

https://stackblitz.com/edit/fullcalendar-condensed-event-veihws

### Bug Description

Whenever the start date and end date are same and which exceeds the time of 23:00:00 i.e., need to be start from 23:00:01, then the event badge is coming on that particular day and next day.

**Input:**
events: [
  {
    title: "Meeting",
    start: "2020-06-12 23:00:01",
    end: "2020-06-12 23:00:01"
  }
]

**Actual Output:**
The event badge (with meeting title) is on two dates (on 2020-06-12 and 2020-06-13).

**Expected Output:**
The event badge (with meeting title) should be on one particular date (on 2020-06-12).

### Screenshots:

![image](https://user-images.githubusercontent.com/60179972/114874471-fe22da00-9e19-11eb-8eb4-63d1b3a74382.png)

**Comment by BhanuPrakashReddyT** [comment]
![image](https://user-images.githubusercontent.com/60179972/114869320-76869c80-9e14-11eb-8258-f3af9787a573.png)


var calendar = new Calendar(calendarEl, {
  initialView: "dayGridMonth",
  initialDate: "2020-06-07",
  plugins: [dayGridPlugin, timeGridPlugin],
  headerToolbar: {
    left: "prev,next today",
    center: "title",
    right: "dayGridMonth,timeGridWeek,timeGridDay"
  },
  events: [
    {
      title: "Meeting",
      start: "2020-06-12 19:58:00",
      end: "2020-06-12 19:58:09"
    }
  ]
});

calendar.render();

As i used this method, the calendar is plotted perfectly, but whenever the time change happens after 11:00 pm (both start and end should be same), then i am getting the issue. The following packages i had used:

"@fullcalendar/common": "^5.0.1",
"@fullcalendar/core": "^5.0.0",
"@fullcalendar/daygrid": "^5.0.1",
"@fullcalendar/moment": "^5.0.0",
"@fullcalendar/timegrid": "^5.0.1",

**Comment by BhanuPrakashReddyT** [comment]
**I tried in my angular app where i followed the above things**

**Comment by BhanuPrakashReddyT** [comment]
Reproducable Link :

https://stackblitz.com/edit/fullcalendar-condensed-event-veihws

**Comment by acerix** [comment]
The `end` time is exclusive so it is ignored if it is the same as the start date since that would mean the event ends before it starts. So, your event gets the default duration of 1 hour which makes it run to the next day.

**Comment by BhanuPrakashReddyT** [comment]
**Thank you for the needful response.**
