### ISSUE TITLE
Wrapping long event text to multiple lines

### ISSUE THREAD

**Issue by SelectSystemsInternational** [fullcalendar/fullcalendar#6271]
### Reduced Test Case

See https://codepen.io/SelectSystemsInternational/pen/YzNObZg
Is this the desired result ?

If I add the CSS then it is better
See https://codepen.io/SelectSystemsInternational/pen/qBRMwwx

### Bug Description

Maybe not a bug - could be suggestion
I wanted to confirm the behavior when using eventDisplay: 'block' with displayEventEnd: true

1. Is there any way to wrap the title text without using CSS ?
2. This is becuase you use Div's rather than Span (in V4.0)
- I like the old way (See screenshot) as it allows more text as seperate lines in the same size block
- Is it possible to get the v4.0 display version somehow (maybe as another option) ?

### Screenshots

![v4.0 Display](https://user-images.githubusercontent.com/34350154/115302823-3160c280-a1a6-11eb-8d11-aeb57d624d38.png)

**Comment by acerix** [comment]
I agree it looks better to wrap the text instead of cutting it off in your example but that may not work well for calendar with many events although could be a useful option.  For now, you could use `eventContent` to supply your own HTML for the events.

**Comment by SelectSystemsInternational** [comment]
Thanks for that - I have uploaded an image to show the full page of events for reference
![Full Page](https://user-images.githubusercontent.com/34350154/115782652-41271380-a3ff-11eb-8fd8-9a47776a6d74.png)

**Comment by SelectSystemsInternational** [comment]
Had another look and to fix this just need to change CSS and add 

.fc-h-event .fc-event-main-frame {
  display: block; /* for make fc-event-title-container expand */
}
![Events](https://user-images.githubusercontent.com/34350154/127376485-66bbe259-a5d1-46f6-9ee8-e695cb715546.png)

**Comment by SelectSystemsInternational** [comment]
Solution found as above
