### ISSUE TITLE
listDaySideFormat not working when set to false

### ISSUE THREAD

**Issue by dan-konopka** [fullcalendar/fullcalendar#6281]
Reproduce here: https://codepen.io/dan-konopka/pen/jOyJBRx?editors=001

The documentation on [https://fullcalendar.io/docs/listDaySideFormat](url) states that if `false` is specified, it will show no date on the right. However, the date is still displayed on the right. I want the date only on the left.

**Comment by dan-konopka** [comment]
> This issue was closed because it does not fulfill the issue template (for example, if it had no [reduced test case](https://fullcalendar.io/reduced-test-cases)). Please create a **new** issue and follow the instructions more carefully. If this is a question, please visit the [StackOverflow fullcalendar tag](https://stackoverflow.com/questions/tagged/fullcalendar).

This is weird because I did create a reduced test case and followed the instructions

**Comment by acerix** [comment]
The bot requires that the template headers not be removed.

The issue is you are using v3, so that setting is called "listDayAltFormat":

https://fullcalendar.io/docs/v3/listDayAltFormat

https://codepen.io/acerix/pen/OJWqEBw?editors=001
