### ISSUE TITLE
How to start time and end time nearby in first day event?

### ISSUE THREAD

**Issue by habonn** [fullcalendar/fullcalendar#6283]
### Reduced Test Case
This my test case.
https://codepen.io/habonn/pen/abpxoBo

### Bug Description

I have some problem with fullCalendar V5. Event end time is display on Next FirstdayWeek and Time Text is display 0:00 Can I cut?, How I can Start time and End time is nearby or replace on 0:00 in first day event. I want to display Event1.

### Screenshots

<img width="1113" alt="Screen Shot 2564-04-27 at 18 56 26" src="https://user-images.githubusercontent.com/35389548/116237379-52b74500-a78a-11eb-8f56-14805b70ebd4.png">

**Comment by acerix** [comment]
I believe this existing ticket captures this need:
https://github.com/fullcalendar/fullcalendar/issues/3038
↑
Please visit the above issue, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates.
