### ISSUE TITLE
firstDay for 3 and above in timeGridWeek/timeGridDay reverts to previous week.

### ISSUE THREAD

**Issue by StacyMader** [fullcalendar/fullcalendar#6284]
### Reduced Test Case

https://codepen.io/stacymader/pen/dyNLRrj?editors=001

### Bug Description

When in timeGridWeek or timeGridDay view, having firstDay at 0, 1 or 2 sets the calendar as expected, but if 3 or above, the firstDay is for the previous week.

Using v5.6.0.

### Screenshots

<img width="1724" alt="Screen Shot 2021-04-28 at 09 38 51" src="https://user-images.githubusercontent.com/16996272/116325464-93a06f80-a805-11eb-98e8-b05e2ae896c8.png">

**Comment by acerix** [comment]
I'm not sure what you mean, it looks like the correct dates to me.  What are you clicking and what do you expect?

**Comment by StacyMader** [comment]
Hi @acerix , for the current week (Sun 25th April -> Sat 5th May) the calendar displays the following day as the first column:

firstDay 0 -> Sun 25th April
firstDay 1 -> Mon 26th April
firstDay 2 -> Tues 27th April
firstDay 3 -> Wed 28th April
firstDay 4 -> Thu 22nd April
firstDay 5 -> Fri 23rd April
firstDay 6 -> Sat 24th April
 
It seems if the firstDay is equal or greater than the current day, you get the previous weekday shown as the first column.

**Comment by acerix** [comment]
The calendar always shows the current day by default, it does not use "current week". So, starting the view on Friday will start on April 23 because today is April 29 which is part of those 7 days.  You could change the "current day to show" with `defaultDate` or use `gotoDate` to change to the the week you want.
