### ISSUE TITLE
Setting height in calendar causes last row  to stretched

### ISSUE THREAD

**Issue by StacyMader** [fullcalendar/fullcalendar#6290]
### Reduced Test Case

https://codepen.io/stacymader/pen/XWpvbVB

### Bug Description

Much like [https://stackoverflow.com/questions/26329377/fullcalendar-auto-height-in-week-view](fullcalendar-auto-height-in-week-view), I am trying to get the calendar to fill the height of the parent using height: "auto" and the calendar looks fine though doesn't fill the available space (perhaps due to the card CSS). However, using setOption to change the height, I'm seeing the last hour row stretched disproportionately to the others.

I am using Bootstrap 4.5.0 and FullCalendar 5.6.0.

### Screenshots
<img width="947" alt="Screen Shot 2021-05-02 at 23 30 27" src="https://user-images.githubusercontent.com/16996272/116815055-21ca7c00-ab9f-11eb-9dd7-6ebd3b469010.png">

**Comment by acerix** [comment]
You can turn on `expandRows` to have the rows grow to fill the space:

https://codepen.io/acerix/pen/YzZyqLr
