### ISSUE TITLE
Static javascript iCalendar package please?

### ISSUE THREAD

**Issue by Zaffer** [fullcalendar/fullcalendar#6291]
How can I get a plain javascript version of the iCalendar plugin / package to include on my site as a static file?

I see the tutorial here uses Typescript and NPM only: https://fullcalendar.io/docs/icalendar

Thanks!

> BTW "I love FullCalendar".

**Comment by acerix** [comment]
I believe this existing ticket captures this need:
https://github.com/fullcalendar/fullcalendar/issues/6215
↑
Please visit the above issue, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates.
