### ISSUE TITLE
Request for adaptivePlugin working example

### ISSUE THREAD

**Issue by datobu** [fullcalendar/fullcalendar#6298]
### Checklist

Please mark these items with an [x]

  - [X] I've already searched through [existing tickets](https://fullcalendar.io/issues)
  - [x] Other people will find this feature useful

### Feature Description

Hello,

I would like to see a working example of the adaptivePlugin for printing. I cannot get it to work and the page https://fullcalendar.io/docs/print  does not have enough information for me to get it to work. Is there any tutorial, example or similiar?

I am sorry if this is not the correct place for asking, but I was not sure where to ask instead.

Best regards

**Comment by jkronlachner** [comment]
Yes but this has the problem of only printing currently visible times. 

Is there a way to split or just to cram everything together?

**Comment by briandeanda** [comment]
Is there anyway to get an actual working example of this premium print feature.
