### ISSUE TITLE
Bootstrap 5 theme

### ISSUE THREAD

**Issue by cameron-goddard** [fullcalendar/fullcalendar#6299]
### Reduced Test Case

https://codepen.io/camerongoddard/pen/PopqzVZ

### Bug Description

When using Bootstrap 5 for the "bootstrap" themeSystem, the table borders are invisible.

### Screenshots

![image](https://user-images.githubusercontent.com/47681797/117559590-99dbea80-b054-11eb-8ca3-e4c4c7a272c1.png)

**Comment by disjfa** [comment]
The thing is bootstrap 5 bordered tables only apply borders to first child elements. This means the table-bordered must be put on every table in the calendar. I copied the bootstrap theme and just renamed the theme back to the standard theme and we have best of both worlds. Buttons with bootstrap theming, and tables with borders, and rendered to be viewed.

So i was stuck on where to go, i could not find where and how to add table classes on child elements. And maybe there still have to be things done wich are done on the standard theme.

```Bootstrap5Theme.prototype.classes = {
  root: 'fc-theme-standard',
  };```

**Comment by MeEuro** [comment]
Add this to your CSS and you will have border

  .fc-daygrid-day-frame {
    height: 160px;
    padding: 2px;
    border: 1px solid #f3f4f6;
    background-color: rgb(245, 241, 241), 0.2;
  }

**Comment by jaapz** [comment]
+1 for supporting this! We currently use some custom CSS to support bootstrap 5, so it shouldn't be too much work.

**Comment by fabienwnklr** [comment]
Hi everyone, if you have any time, please check [this pull request](https://github.com/fullcalendar/fullcalendar/pull/6625) and test/review for merge it more fast 👍 

Many thanks

**Comment by robozb** [comment]
+1 for supporting boostrap5

**Comment by lllopo** [comment]
+1

**Comment by nijikon** [comment]
@arshaw any short-term plans to add the support?

**Comment by arshaw** [comment]
Alrighty,
blog post: https://fullcalendar.io/blog/2022/02/bootstrap-luxon-angular
release: https://github.com/fullcalendar/fullcalendar/releases/tag/v5.10.2
docs: https://fullcalendar.io/docs/bootstrap5

**Comment by maurojs10** [comment]
Hi, sorry to bother you, but is there any chance to make the **Bootstrap 5 theme** work with **Font Awesome icons**, please?

I see the **new Bootstrap theme** is designed to work with **new Bootstrap icons**, but I really need to keep on using **Font Awesome icons**.

**Comment by maurojs10** [comment]
Never mind. I will use the following code to force **Font Awesome icons**.

````javascript
FullCalendar.globalPlugins.filter(plugin => plugin.themeClasses.hasOwnProperty('bootstrap5')).forEach(plugin => {
  plugin.themeClasses.bootstrap5.prototype.baseIconClass = 'fa';
  plugin.themeClasses.bootstrap5.prototype.iconOverridePrefix = 'fa-';
  plugin.themeClasses.bootstrap5.prototype.iconClasses = {
    close: 'fa-times',
    prev: 'fa-chevron-left',
    next: 'fa-chevron-right',
    prevYear: 'fa-angle-double-left',
    nextYear: 'fa-angle-double-right',
  };
  plugin.themeClasses.bootstrap5.prototype.rtlIconClasses = {
    prev: 'fa-chevron-right',
    next: 'fa-chevron-left',
    prevYear: 'fa-angle-double-right',
    nextYear: 'fa-angle-double-left',
  };
});
````

Thank you so much.

**Comment by arshaw** [comment]
It would be nice to have an official solution. Someone made another ticket:
https://github.com/fullcalendar/fullcalendar/issues/6721
&uarr;
Could you please visit the link, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates?

**Comment by andreas-aeschlimann** [comment]
> Alrighty, blog post: https://fullcalendar.io/blog/2022/02/bootstrap-luxon-angular release: https://github.com/fullcalendar/fullcalendar/releases/tag/v5.10.2 docs: https://fullcalendar.io/docs/bootstrap5

Thank you @arshaw! Oddly, when I activate `bootstrap5` as theme system, the borders are still gone with Angular/Bootstrap5.

Am I missing something?

First I ran `npm i @fullcalendar/bootstrap5`.

AppModule:
```
FullCalendarModule.registerPlugins([
    bootstrap5Plugin,
    ...
]);
```

CalendarComponent:
```
calendarOptions: CalendarOptions = {
    themeSystem: "bootstrap5",
    ...
};
```

CalendarComponent (Template):
```
<full-calendar #calendar [options]="calendarOptions"></full-calendar>
```

**Comment by kevinpapst** [comment]
For everyone missing the border, the [Bootstrap5 theme](https://github.com/fullcalendar/fullcalendar/blob/master/packages/bootstrap5/src/main.css) is using the Bootstrap CSS variables (especially `--bs-gray-400`), which might be missing from your theme and then borders are not visible. 

Simply declare them, e.g.:
```
    --bs-gray-200: #e2e8f0;
    --bs-gray-400: #94a3b8;
```
