### ISSUE TITLE
Full Calendar Event stretched out in print media

### ISSUE THREAD

**Issue by mostafa-K-raihan** [fullcalendar/fullcalendar#6300]
### Reduced Test Case

https://codepen.io/root09/pen/wvJaoZL

### Bug Description

In `dayGridMonth` view, if the event spans multiple dates, in print media, the event end date stretches out of the actual end date. see screenshot

### Screenshots

`12p Event 3` got stretched out of the end date
![image](https://user-images.githubusercontent.com/47943980/117564243-00045400-b0cd-11eb-8bb5-f3778941ae10.png)

**Comment by mostafa-K-raihan** [comment]
if anyone stumbles upon this. we solved this by manually updating the `right` property for each events like this

> document.querySelectorAll('.fc-daygrid-event-harness-abs').forEach((harness) => {
          const container = harness.closest('.fc-daygrid-day-events');
          harness.style.setProperty(
            '--modified-right',
            `${(100 * parseInt(harness.style.right)) / container.clientWidth}%`
          );
        });

and use the `modified-right` as new right from the css
` .fc-daygrid-event-harness-abs {
    right: var(--modified-right) !important;
  }`

**Comment by laoneo** [comment]
Can you open a pr with your changes, perhaps it will be accepted. Pretty sure a lot will benefit from this fix.

**Comment by arshaw** [comment]
this problem has been fixed in the newly released v5.7.0

demo: https://codepen.io/arshaw/full/OJpNyqG
(if the link is broken, try this: https://codepen.io/arshaw/pen/OJpNyqG)
