### ISSUE TITLE
Show event count in the list view

### ISSUE THREAD

**Issue by Vikram-ksingh** [fullcalendar/fullcalendar#6303]
### Checklist

Please mark these items with an [x]

  - [x] I've already searched through [existing tickets](https://fullcalendar.io/issues)
  - [x] Other people will find this feature useful

### Feature Description

Feature will show the event count in the list view as it is missing right now, when there are a lot of events for a date its hard to count them, this feature will help the customers to see the count in header

### Visual Mockups

https://nimb.ws/oxOkgJ

**Comment by acerix** [comment]
I believe this existing ticket captures this need:
https://github.com/fullcalendar/fullcalendar/issues/6302
↑
Please visit the above issue, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates.
