### ISSUE TITLE
Events snap to top of cell while resizing

### ISSUE THREAD

**Issue by abrunovski** [fullcalendar/fullcalendar#6308]
### Checklist

Please mark these items with an [x]

  - [x] I've already searched through [existing tickets](https://fullcalendar.io/issues)
  - [x] Other people will find this feature useful

### Feature Description

To keep the vertical position of allDay event when resizing event in `dayGridMonth` view.
Currently, when resizing `allDay`/multi-day event which sits under other `allDay` event, the resized event is moving up to the top of day cell and overlapping with `allDay` event above, the same issue you can see on [this demo](https://fullcalendar.io/docs/event-dragging-resizing-demo)
Not sure if it's a bug or an option that I've missed, because on [first demo](https://fullcalendar.io/demos) here, resize is behaving as expected, when resizing second or third `allDay` event in same day cell, the event keeps vertical positipon.

Thanks.

**Comment by acerix** [comment]
It seems like a bug starting in version 5.7.0 which that resizing demo is using, the demo on the homepage is still using 5.5.1.

https://codepen.io/acerix/pen/XWMjRME?editors=001

**Comment by arshaw** [comment]
fixed in [5.9.0](https://github.com/fullcalendar/fullcalendar/releases/tag/v5.9.0)

updated repro: https://codepen.io/arshaw/pen/yLbKVZQ?editors=001
