### ISSUE TITLE
Day click on touch devices works only after the view is rendered and not for the next time

### ISSUE THREAD

**Issue by bandhavya** [fullcalendar/fullcalendar#6311]
### Bug Description

Im facing same issue as specified in this https://github.com/fullcalendar/fullcalendar/issues/4388

Im using version 3.10.0

Only for the first time, on long press day click or select is working. After it doesnt work on selecting other date.
But when I go back to other view like month or year , again select it works. But immediation select of one date after the other date does not work.

Why is this so ?

Im using Angular material for styles.

**Comment by acerix** [comment]
Would you be able to post a [runnable, stripped-down demonstration of the bug](http://fullcalendar.io/wiki/Reduced-Test-Cases/)? Would really appreciate it because the time saved reproducing will be time spent fixing.
