### ISSUE TITLE
timelineYear View Event Order

### ISSUE THREAD

**Issue by ajaykumarsana** [fullcalendar/fullcalendar#6313]
Hi @acerix 
### Reduced Test Case

"not reproducible with a link"

### Bug Description

In the attached screenshot i had provided **eventOrder for the month May as 1** and **for June it is 2**, though eventOrder is different, it lies next to it in year view.
I wanted **June** events should appear horizontally below to the may month in its june column,
Can you please hep?

### Screenshots

![image](https://user-images.githubusercontent.com/1854019/118454793-636a3380-b716-11eb-8f5d-312d924971b5.png)

**Comment by acerix** [comment]
Events always go to the top when there is space, there is no built-in way to keep the order, I think that would be covered by this request:

https://github.com/fullcalendar/fullcalendar/issues/4748
↑
Please visit the above issue, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates.

**Comment by ajaykumarsana** [comment]
If somebody had a typical requirement like this, refer to stackoverflow link below.
https://stackoverflow.com/questions/67566389/how-to-display-events-by-order-wise-in-fullcalendar-timelineyear-view/67583046#67583046
