### ISSUE TITLE
slotDuration render event wrong position

### ISSUE THREAD

**Issue by nguyenphi990** [fullcalendar/fullcalendar#6317]
### Bug Description
The schedule from 6: 30 ~ 6: 55 and the schedule from 7:00 ~ overlap.
`var calendar = new FullCalendar.Calendar(calendarEl, {
    timeZone: 'UTC',
    initialView: 'timeGridWeek',
     slotDuration: '01:00:00',
    headerToolbar: {
      left: 'prev,next today',
      center: 'title',
      right: 'timeGridWeek,timeGridDay'
    },
    events: [
      {
        start:"2021-05-20T06:30:00",
        end:"2021-05-20T06:55:00",
      },
      {
        start:"2021-05-20T07:00:00",
        end:"2021-05-20T08:00:00",
      }
    ]
  });
`
  calendar.render();
### Screenshots

![Ảnh chụp Màn hình 2021-05-19 lúc 15 33 47](https://user-images.githubusercontent.com/45842801/118781999-db239400-b8b7-11eb-91f1-1a60d8d941ca.png)

**Comment by acerix** [comment]
Would you be able to post a [runnable, stripped-down demonstration of the bug](http://fullcalendar.io/wiki/Reduced-Test-Cases/)? Would really appreciate it because the time saved reproducing will be time spent fixing.

**Comment by nguyenphi990** [comment]
https://codepen.io/nguyenphi990/pen/bGqByZe?editors=001

**Comment by nguyenphi990** [comment]
> Would you be able to post a [runnable, stripped-down demonstration of the bug](http://fullcalendar.io/wiki/Reduced-Test-Cases/)? Would really appreciate it because the time saved reproducing will be time spent fixing.

codepen url for this bug
https://codepen.io/nguyenphi990/pen/bGqByZe?editors=001

**Comment by nguyenphi990** [comment]
I fixed it with eventMinHeight

**Comment by acerix** [comment]
Thanks for the demo, it doesn't seem like a bug though, the default value of `eventMinHeight` makes sense so that the times don't get cut-off.
