### ISSUE TITLE
vue项目使用defaultView:'timelineMonth'，标题的日期格式显示出现undefiend

### ISSUE THREAD

**Issue by qy-liu** [fullcalendar/fullcalendar#6318]
### Reduced Test Case

You must paste a link to a [REDUCED TEST CASE](https://fullcalendar.io/reduced-test-cases).
If you do not, this issue will automatically be closed.
To prevent this, include the text "not reproducible with a link" (assuming it's true).

### Bug Description

Describe how to recreate the bug.
What do you expect to happen?
What happens instead?

### Screenshots

If the bug is visual, include a screenshot if possible.
If not, erase this section.
![image](https://user-images.githubusercontent.com/70626750/118786736-b386f880-b8c4-11eb-8994-675f54cd56b0.png)

**Comment by acerix** [comment]
Would you be able to post a [runnable, stripped-down demonstration of the bug](http://fullcalendar.io/wiki/Reduced-Test-Cases/)? Would really appreciate it because the time saved reproducing will be time spent fixing.

**Comment by qy-liu** [comment]
问题详细页面以及参考案例页面在下面展示，希望说的会清除点了



------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "fullcalendar/fullcalendar"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年5月20日(星期四) 凌晨2:17
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [fullcalendar/fullcalendar] vue项目使用defaultView:'timelineMonth'，标题的日期格式显示出现undefiend (#6318)





 
Would you be able to post a runnable, stripped-down demonstration of the bug? Would really appreciate it because the time saved reproducing will be time spent fixing.

**Comment by wangjingithub** [comment]
Excuse me, how do you set up the up and down display of this date and week?
