### ISSUE TITLE
Navigation doesn't work when increment is different to day count

### ISSUE THREAD

**Issue by unaipme** [fullcalendar/fullcalendar#6319]
### Reduced Test Case

https://codepen.io/unaipme/pen/WNpoMMx

### Bug Description

Hi! I'm currently trying out your React binding of FullCalendar and I ran into a bug that also seems to affect the vanilla JS version. The Codepen link features a minor modification of one of your demos (https://fullcalendar.io/docs/timegrid-custom-view-demo). In it, I only introduce one setting change, which is the _DateIncrement_ setting, which I set to 1.

What I have observed is that when the _DateIncrement_ is set to a different value than the day count, the "previous" navigation button stops working correctly. Instead of going back following the custom date increment as many times as wanted, it only works once. Then it will stop working. Also, if I click the "next" navigation button afterwards, it skips twice the increment, as if the previous navigation didn't really do anything. The "next" navigation, though, continues to work perfectly.

Thank you, and congrats for your work on this library!

**Comment by acerix** [comment]
I believe this existing ticket captures this need:
https://github.com/fullcalendar/fullcalendar/issues/5319
↑
Please visit the above issue, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates.
