### ISSUE TITLE
[5.7.0] z-index 9999 for popover is just too much

### ISSUE THREAD

**Issue by Kepro** [fullcalendar/fullcalendar#6320]
### Reduced Test Case

not reproducible with a link

### Bug Description
new version 5.7.0 is using z-index: 9999 for popover, can we use some normal value for z-index please? :) even modal is using z-index: 1000

Describe how to recreate the bug.
just use latest version, and for example use your own tooltip that is using normal z-index

What do you expect to happen?
to lower z-index to normal value

What happens instead?

### Screenshots
![image](https://user-images.githubusercontent.com/1714370/118831208-dfec4600-b8bf-11eb-8c94-86d51530e586.png)

**Comment by acerix** [comment]
Please post a [runnable, stripped-down demonstration of the bug](http://fullcalendar.io/wiki/Reduced-Test-Cases/).   There is no built-in tooltip, but you can increase the z-index of that one to make it show in front of the popover.

**Comment by Kepro** [comment]
@acerix I will expect z-index 9999 from a junior developer not from the serious library...
