### ISSUE TITLE
resourceClick for Fullcalendar Scheduler (Timline)

### ISSUE THREAD

**Issue by atenonra** [fullcalendar/fullcalendar#6324]
### Checklist

Please mark these items with an [x]

  - [ x] I've already searched through [existing tickets](https://fullcalendar.io/issues)
  - [x ] Other people will find this feature useful

### Feature Description

Hey!

Fullcalendar has property eventClick which allows you to handle a click on an event from list events calendar. Now I've started use fullcalendar scheduler (@5.7.0) where I need to click and call such action but on resource, from list resources in the left side. I've couldn't find any solutions so decided to write feature request. If solvetion has already existed, couldn't you share information and write to way to use resourceClick in fullcalendar scheduler @5.7.0.

I think it featuer will be usefule for many projects, where use resource timeline.

**Comment by anucodematrix** [comment]
Hello ,

Any update or near future plans on this ?

In V4 we had  renderResources which could be used as workaround to click resources as per https://fullcalendar.io/docs/v4/resourceRender and few  . However , i don't find this functionality anymore in V5 . Is there any replacement for render resources which can be used in resource-timeline view to make the resources clickable  ?

**Comment by acerix** [comment]
Sorry I missed this issue earlier.  I believe this existing ticket captures this need:
https://github.com/fullcalendar/fullcalendar/issues/4829
↑
Please visit the above issue, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates.
