### ISSUE TITLE
React calendar not showing

### ISSUE THREAD

**Issue by yetkinaykan** [fullcalendar/fullcalendar#6332]
### Reduced Test Case

```
import FullCalendar from '@fullcalendar/react'
import dayGridPlugin from '@fullcalendar/daygrid'
import './Calendar.scss';

const Calendar = () => {
    return (
        <FullCalendar
            plugins={[ dayGridPlugin ]}
            initialView="dayGridMonth"
        />
    );
};

export default Calendar;
```

### Bug Description

I use full calendar in Ionic. But when the page is first opened, the calendar does not work. It works if the screen is resized.

### Screenshots

![fullcalendar-bug](https://user-images.githubusercontent.com/56234617/119741999-84a5ef00-be8f-11eb-8f34-51faed2f0039.png)

**Comment by yetkinaykan** [comment]
Temporary solution.

```
useEffect(() => {
  window.dispatchEvent(new Event('resize'));
});
```

**Comment by acerix** [comment]
I believe this existing ticket captures this need:
https://github.com/fullcalendar/fullcalendar/issues/4976
↑
Please visit the above issue, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates.
