### ISSUE TITLE
Method to check if today is in the current view

### ISSUE THREAD

**Issue by Glideh** [fullcalendar/fullcalendar#6335]
Maybe it already exists but I can't find it on the doc nor on the API object

### Checklist

  - [x] I've already searched through [existing tickets](https://fullcalendar.io/issues)
  - [x] Other people will find this feature useful

### Feature Description

Check wether we are "today"

### Use case

I'm trying to reimplement the header toolbar because I need advanced behavior.
I need to disable the today button when we are already on it.

**Comment by acerix** [comment]
Considering views can show multiple days, you likely want to check if today is anywhere in the view.  There's no method to check that but you could check for the "today" element like this:

https://codepen.io/acerix/pen/VwpzorN?editors=001

**Comment by Glideh** [comment]
Ok so that's:

```js
!!calendarEl.querySelectorAll('.fc-day-today').length
```

That should be the trick for me, I'll try it, thx

**Comment by Glideh** [comment]
Works fine, thx again

**Comment by PeterSDH** [comment]
datesSet
({ start, end }: DatesSetArg) => {
    const currTime = new Date().getTime();
    const toDayInView = currTime >= start.getTime() && currTime <= end.getTime();
    console.log('-----toDayInView------', toDayInView);
  }
