### ISSUE TITLE
Add translation to Swedish language

### ISSUE THREAD

**Issue by jgdimeglio** [fullcalendar/fullcalendar#6336]
### Checklist

Please mark these items with an [x]

  - [x] I've already searched through [existing tickets](https://fullcalendar.io/issues)
  - [x] Other people will find this feature useful

### Feature Description

Add Swedish language translation file to locales folder. File name sw.ts.

**Comment by acerix** [comment]
The Swedish locale code is [sv](https://github.com/fullcalendar/fullcalendar/blob/f6b0acf48f3f1283b4d5511b1b2f4ce42a555344/packages/core/src/locales/sv.ts).
