### ISSUE TITLE
fullcalendar not working in google crome Version 91.0.4472.77 (Official Build) (arm64)

### ISSUE THREAD

**Issue by manojinfoways** [fullcalendar/fullcalendar#6343]
Calender view not working in crome please give me suggestion it latest version of google crome
Calender version is 5.6 or 5.7 both have same issue
<img width="1146" alt="Screenshot 2021-05-30 at 5 08 06 PM" src="https://user-images.githubusercontent.com/67017136/120095615-7d5b3b80-c144-11eb-9d51-6c887274629f.png">

**Comment by Avrmaster** [comment]
Hi @manojinfoways we've encountered the same issue here.
Did you find any solutions?

**Comment by arshaw** [comment]
@manojinfoways and @avindra , could you please please post a reproduction?
https://fullcalendar.io/reduced-test-cases

related to https://github.com/fullcalendar/fullcalendar/issues/6338

**Comment by sseemmiin** [comment]
me either on 91.0.4472.77(x86_64) :(

**Comment by arshaw** [comment]
Please the workaround here: https://github.com/fullcalendar/fullcalendar/issues/6338#issuecomment-850817895

@sseemmiin , can you give me a [reduced test case](https://fullcalendar.io/reduced-test-cases) or at least tell me all the options you are initializing the calendar with?

**Comment by sseemmiin** [comment]
I Use ResourceTimegrid plugin v5 and timeslot is 10min, alldayslot is false

**Comment by sseemmiin** [comment]
I use resourceTimegrid v5, alldayslot is false, slotDuration={"00:10"} / case of duration is 30 min or alldayslot  is true It works

**Comment by sseemmiin** [comment]
Or Add this css, it works 
 .fc .fc-scrollgrid-section-liquid {
    height : 1px !important;
  }

**Comment by arshaw** [comment]
hi @sseemmiin , I created a codepen using your settings:
https://codepen.io/arshaw/pen/VwpXaME?editors=0010

Does it show an error for you? It works fine for me :(

**Comment by sseemmiin** [comment]
hi @arshaw I made it on your link, but how can i save it?

**Comment by arshaw** [comment]
@sseemmiin , yes, i can see the bug now. thank you so much!!! i will get to work on fixing the root cause

**Comment by sseemmiin** [comment]
Thanks:)

**Comment by arshaw** [comment]
A more reduced test case: https://codepen.io/arshaw/pen/qBromYK?editors=0110

**Comment by arshaw** [comment]
hi @atotic , here is very minimal example with fullcalendar stripped out, for your Chromium-debugging needs: https://codepen.io/arshaw/pen/ZEexymm?editors=1100

This is different than #6338 . Whereas #6338 is being caused by Chromium 91 respecting a col's min-width, which I would consider "correct", this problem is more of a regression... It causes a header cell to consume a table's entire for seemingly arbitrary reasons.

**Comment by atotic** [comment]
Thanks for the example. The incompatibility is treatment of empty sections; do they get the height from the table or not? I'll have to think this one through.

Another fix is to give `<tbody style="height:0.1px"`

My initial take is that we should support old behavior. Filed https://bugs.chromium.org/p/chromium/issues/detail?id=1216197

**Comment by arshaw** [comment]
the issues have been fixed. there were two distinct issues, one for timeline and one for timegrid. please read these tracking tickets for more info:
https://github.com/fullcalendar/fullcalendar/issues/6357
https://github.com/fullcalendar/fullcalendar/issues/6358
