### ISSUE TITLE
Bug in timeline view after chrome 91 update

### ISSUE THREAD

**Issue by sandramoutous** [fullcalendar/fullcalendar#6345]
### Reduced Test Case

"not reproducible with a link" 

### Bug Description

Since the Chrome 91 update, the grids of my calendar are bigger and the selectable lines doesn't take the entire width. Is anyone faced the same issue ? I don't know what to change in my jquery script.

FullCalendar version : 3.10.2

`$('#calendar').fullCalendar({

      header: {
        left: 'fakeButton prev,next today',
        center: 'title',
        right: ''
      },
      customButtons: {
        fakeButton: {
          text: 'date-picker-placeholder'
        }
      },
      nowIndicator: true,
      defaultDate: calendarDate,
      defaultView: 'timelineDay',
      scrollTime: '07:00',
      slotDuration: '00:15:00',
      editable: true,
      lazyFetching: false,
      selectable: true,
      selectHelper: true,
      slotLabelFormat: 'H:mm',
      resourceAreaWidth: '16%',
      aspectRatio: 2,
      resourceLabelText: 'users',
      resourceGroupField: 'userGroup',
      resourceOrder: 'title',
      slotWidth: 22,
      views: {
        day: {
          titleFormat: 'dddd D MMMM YYYY'
        }
      }, [...]`

### Screenshots

Before the update
![image](https://user-images.githubusercontent.com/55396734/120210912-9c36fc00-c230-11eb-9880-442a4aad59ec.png)

After the Chrome 91 update
![image](https://user-images.githubusercontent.com/55396734/120210966-af49cc00-c230-11eb-9e3a-34eace6eb73a.png)

**Comment by acerix** [comment]
Would you be able to post a [runnable, stripped-down demonstration of the bug](http://fullcalendar.io/wiki/Reduced-Test-Cases/)? Would really appreciate it because the time saved reproducing will be time spent fixing.

**Comment by frietzak90** [comment]
Hi,

I was facing the same issue.
I added following css to temporarily fix this:

.fc-time-area col {
    min-width: 0em;
}

**Comment by sandramoutous** [comment]
@frietzak90 thanks for your help, I added this ccs and it worked for me too !

**Comment by crodrigueza16** [comment]
@frietzak90 solution works for me!

**Comment by arshaw** [comment]
seems related to https://github.com/fullcalendar/fullcalendar/issues/6338
