### ISSUE TITLE
eventClick doesn't pass some parameters of a recurring event

### ISSUE THREAD

**Issue by jbarranco18** [fullcalendar/fullcalendar#6346]
## Reduced Test Case

Here's a snippet of the code https://codepen.io/jbarranco18/pen/wvJpoEJ

## Bug Description

When using eventClick over a recurring event, fullCalendar doesn't pass some of the events parameters. So far that I've tried, it passes the id, title and start date...but any other parameter is undefined. With a non-recurring event, it passes all of the parameters just fine.

**Comment by acerix** [comment]
I believe this existing ticket captures this need:
https://github.com/fullcalendar/fullcalendar/issues/5262
↑
Please visit the above issue, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates.
