### ISSUE TITLE
Title is added using appendchild instead of html

### ISSUE THREAD

**Issue by devanand** [fullcalendar/fullcalendar#6348]
### Reduced Test Case
not reproducible with a link

### Bug Description
Any change on fullcalendar for instance, drag/drop or resize or jumping one day next or before appends the title again to fc-event-title div

### Screenshots
![image](https://user-images.githubusercontent.com/1318844/120300758-da442680-c2e9-11eb-8a8c-1006877734d7.png)

**Comment by acerix** [comment]
Would you be able to post a [runnable, stripped-down demonstration of the bug](http://fullcalendar.io/wiki/Reduced-Test-Cases/)? Would really appreciate it because the time saved reproducing will be time spent fixing.
