### ISSUE TITLE
Remove the word "Uhr" from fullcalendar

### ISSUE THREAD

**Issue by bakritarek** [fullcalendar/fullcalendar#6350]
Reduced Test Case
"not reproducible with a link"

Bug Description
When putting your local to  `locale: 'de'` the word "Uhr" is added automatically the header as you can see in the screenshot
![Screenshot 2021-05-31 at 13 11 02](https://user-images.githubusercontent.com/32450146/120441694-1d9fa300-c385-11eb-8422-b240b799c39b.png)
I tried to remove it by using 
```
views: {
  resourceTimelineWeek: { // name of view
    slotLabelFormat: [
      { weekday: 'long' }, // top level of text
      { hour: 'numeric',  omitZeroMinute: true, meridiem: false},
    ],
  },

}
```
but I couldn't find a solution 
I need help

**Comment by acerix** [comment]
I believe this existing ticket captures this need:
https://github.com/fullcalendar/fullcalendar/issues/5683
↑
Please visit the above issue, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates.
