### ISSUE TITLE
Chrome 91 update breaks timegrid with allDaySlot:false and custom border CSS

### ISSUE THREAD

**Issue by arshaw** [fullcalendar/fullcalendar#6357]
This original problem was reported in #6343 and #6338. It affects only fullcalendar version **5.x**. It was triggered by a change in the way Chrome does table layouts. It only affects calendars with the `allDaySlot` option set to `false` in addition to having custom CSS that hides certain borders. The lower part of your timegrid view would appear broken, like this:

![chrome91-bug-timegrid](https://user-images.githubusercontent.com/56520/120745095-657c1280-c4ca-11eb-9bc6-54dce2a2f26c.png)

To fix this bug, upgrade all fullcalendar bundles/plugins to version **5.7.2**.

If upgrading is not convenient for you, then you can apply the following CSS manually:

```css
.fc-scrollgrid-section-liquid {
  height: 1px !important;
}
```

**Comment by arshaw** [comment]
@sseemmiin, here is an updated codepen that shows the fix: https://codepen.io/arshaw/pen/abJYEXB

**Comment by sseemmiin** [comment]
That was fast. Thanks!
