### ISSUE TITLE
Chrome 91 update causes incorrectly positioned lines in timeline v4

### ISSUE THREAD

**Issue by arshaw** [fullcalendar/fullcalendar#6358]
This original problem was reported in #6338. It affects only fullcalendar version **4.x** and **3.x**. It was triggered by a change in the way Chrome does table layouts. It only affects calendars that have the `slotWidth` option set to a value approximately smaller than `30`. It would prevent certain lines from extending all the way to the edge of the view and would prevent some events from being dragged:

![chrome91-bug-timeline](https://user-images.githubusercontent.com/56520/120745523-55b0fe00-c4cb-11eb-908b-4ce6f9b446fa.png)

If you are using v4.x, you can fix this bug by upgrading the `@fullcalendar/timeline` package to `4.4.3`.

If you are using v3.x, or if upgrading is not convenient for you, then you can apply the following CSS manually:

```css
.fc col { min-width: auto !important }
```

If you apply the CSS manually, and you do NOT have `slotWidth` explicitly set, you might need to set it if the slots appear smaller than you expect. Upgrading to v4.4.3 does not have this caveat.

**Comment by goemaere** [comment]
Could you provide a compiled asset library for the 4.4.3 release and the premium plugins?

**Comment by arshaw** [comment]
@goemaere, thanks for reminding me. yes i will. in the next two days. until then, the CSS-only fix will be work

**Comment by ajaypatelaj** [comment]
@arshaw This needs to consider separately for the angular version? https://github.com/fullcalendar/fullcalendar-angular

**Comment by amruthraodigital** [comment]
@arshaw I have been using resource-timeline plugin with angular version is 4.4.0, and we are seeing this slotWidth issue. Can you let us know which version should we upgrade too?

**Comment by arshaw** [comment]
@goemaere , here are the ZIP archives for v4.3.0:
https://github.com/fullcalendar/fullcalendar/releases/download/v4.4.3/fullcalendar-4.4.3.zip
https://github.com/fullcalendar/fullcalendar-scheduler/releases/download/v4.4.3/fullcalendar-scheduler-4.4.3.zip

**Comment by arshaw** [comment]
@ajaypatelaj and @amruthraodigital , if you are using angular, the instructions are the same. Make sure you have v4.4.3 of the `@fullcalendar/timeline` plugin by doing this:

```
npm install '@fullcalendar/timeline@^4.4.3'
```

**Comment by amruthraodigital** [comment]
Thanks @arshaw for the response. I am not using the @fullcalendar/timeline but rather @fullcalendar/resource-timeline version 4.4.0.. I have upgraded it to 4.4.2 today and I no longer see the issue..

**Comment by ajaypatelaj** [comment]
> @ajaypatelaj and @amruthraodigital , if you are using angular, the instructions are the same. Make sure you have v4.4.3 of the `@fullcalendar/timeline` plugin by doing this:
> 
> ```
> npm install '@fullcalendar/timeline@^4.4.3'
> ```

Thanks for the quick response @arshaw Will try that.

**Comment by jahanzaibtariq** [comment]
Hi All,

In my end only month view is not working so I need to upgrade the package in laravel or need to do something else ?


Thanks
Jani

![image](https://user-images.githubusercontent.com/32379100/122671039-3eb61f80-d1de-11eb-8f52-56ad620cf855.png)

**Comment by ajaypatelaj** [comment]
HI Jani,

The updated version has been released with the fix of this issue. 
Please download it. 

**Note:** This is the official fullcalender repo so I request you to do not to raise template concern/queries here, instead use the support portle: https://pixinvent.ticksy.com/
