### ISSUE TITLE
Error  in vue3-Typescript project

### ISSUE THREAD

**Issue by wangjunying1** [fullcalendar/fullcalendar#6363]
### Reduced Test Case

not reproducible with a link.

### Bug Description

when I use it in vue3-Typescript,it has error in console.
please fix it,thanks.
![image](https://user-images.githubusercontent.com/46319494/120885597-67ee8180-c61c-11eb-8e21-b420be5edf2c.png)
![image](https://user-images.githubusercontent.com/46319494/120885660-a126f180-c61c-11eb-85a7-545a81e2049c.png)
![image](https://user-images.githubusercontent.com/46319494/120885668-ab48f000-c61c-11eb-851b-f43bb0ac5cb6.png)

### Screenshots

If the bug is visual, include a screenshot if possible.
If not, erase this section.

**Comment by SamuelLeclerc33** [comment]
I'm having the same issue with Angular, i get type mismatch on reducerFunc and reducerFunc[]. I started when i bumped my fullcalendar versions from 5.7.0 to 5.7.2 : 
![image](https://user-images.githubusercontent.com/23220701/121028367-c3805280-c775-11eb-8574-fddf1895eb1d.png)

Seems like Typescript has issues identifying the right type between version. I solved this by goind to 5.7.0 for everything except the @fullcalendar/angular which stayed at 5.7.1

**Comment by acerix** [comment]
Please post a [runnable, stripped-down demonstration of the bug](http://fullcalendar.io/wiki/Reduced-Test-Cases/) or steps to reproduce the issue. Would really appreciate it because the time saved reproducing will be time spent fixing.

**Comment by jixiaolu88** [comment]
我也是遇到了同样的问题，改如何解决？

**Comment by jixiaolu88** [comment]
I also encountered the same problem. How can I solve it?

**Comment by arshaw** [comment]
this is on my radar. i will take a look

**Comment by arshaw** [comment]
to clarify, i'm only seeing this error when using codesandbox. when building on my local machine, i don't see this error

**Comment by SamuelLeclerc33** [comment]
@arshaw 
I think i found the error : it seems that inside the @fullcalendar/vue3 ( or angular ) you are referencing fullcalendar 5.7.0. So when it tries to resole types, /node_modules/@fullcalendar/angular/node_modules/@fullcalendar/common/main and node_modules/@fullcalendar/common/main are a missmatch

**Comment by arshaw** [comment]
Thanks for the info @SamuelLeclerc33 . I've figured out this problem as well. It was a combination of these two problems:
- https://github.com/fullcalendar/fullcalendar/issues/6370
- https://github.com/fullcalendar/fullcalendar-vue/issues/152

I've update the [example project](https://github.com/fullcalendar/fullcalendar-example-projects/tree/master/vue3-typescript) and [Vue3 docs](https://github.com/fullcalendar/fullcalendar-example-projects/tree/master/vue3-typescript) with the solutions.
