### ISSUE TITLE
Add Search to Documentation

### ISSUE THREAD

**Issue by jrock2004** [fullcalendar/fullcalendar#6365]
### Checklist

Please mark these items with an [x]

  - [x] I've already searched through [existing tickets](https://fullcalendar.io/issues)
  - [x] Other people will find this feature useful

### Feature Description

Sometimes I go to the documentation and have issues finding exactly what I am looking for. It would be nice to have a search box that I could type what I am looking for.

**Comment by acerix** [comment]
I believe this existing ticket captures this need:
https://github.com/fullcalendar/fullcalendar/issues/4196
↑
Please visit the above issue, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates.
