### ISSUE TITLE
eventsources being called multiple times after navigating away and returning

### ISSUE THREAD

**Issue by nehagarg2k** [fullcalendar/fullcalendar#6369]
do not have a link to produce it

code :

<FullCalendar
            ref="fullCalendar"
            
            :header="{
                left: 'datePickerButton',
                center: 'prev title next today',
                right: 'dayGridMonth, dayGridWeek, dayGridDay'
            }"
            :showNonCurrentDates="false"
            :fixedWeekCount="false"
            :selectable="true"
            :editable="true"

            :event-sources="eventSources"
            :eventLimit="6"
           
            :dayHeaders="true"
            :navLinks="true
            :customButtons="{
              datePickerButton: {
                    text: 'custom dates',
                    click: this.handleCustomButtonClick
               },

            }"
        />

data() {
    return {
 
        eventSources: [
          {
            events: function (info, successCallback, failureCallback) {
             
              let startDate = info.startStr;
              let endDate = info.endStr;
              let url = "http://localhost/api/calendarView/getAllCases/" + startDate + '/' + endDate;
              makeRequest(url)
                  .then(response => {
                    successCallback(response.data);
                  })
            },
            lazyFetching: true
          }
        ],
}
}
### Bug Description

to recreate this issue, you have to keep clicking on next and prev. if you do back and forth multiple times (about 3or 4) and stop you can see the eventsources will be stuck on one month and keep getting called for that particular month infintely. you can see that by looking at the network tab. 

What do you expect to happen?
eventsources shouldn't be called infinitely on one month

What happens instead?
eventsources keeps getting called 

### Screenshots

If the bug is visual, include a screenshot if possible.

![image](https://user-images.githubusercontent.com/85706737/121588712-3e5e9d00-ca04-11eb-8976-e39984ef60e0.png)

**Comment by nehagarg2k** [comment]
please see on the screenshot on the right which shows multiple calls .. these calls are coming from eventsource code and eventsource keeps getting called for same month over and over again in infinite loop

**Comment by acerix** [comment]
Would you be able to post a [runnable, stripped-down demonstration of the bug](http://fullcalendar.io/wiki/Reduced-Test-Cases/)? Would really appreciate it because the time saved reproducing will be time spent fixing.
