### ISSUE TITLE
Solution for "Cannot read property 'isHiddenDay' of undefined"

### ISSUE THREAD

**Issue by arshaw** [fullcalendar/fullcalendar#6370]
The JS error `Cannot read property 'isHiddenDay' of undefined` happens when there are multiple instances of the `@fullcalendar/common` package present in the same build. This is not the fault of the end-developer. After all, `@fullcalendar/common` is an internal-only package that nobody explicitly installs themselves.

How to solve this?: guarantee that all plugins are using the same `@fullcalendar/common` package by having `@fullcalendar/core` (the package the requires common) always be a `peerDependency`. It is already a `peerDependency` for all packages except the following:

- `@fullcalendar/react`
- `@fullcalendar/angular`
- `@fullcalendar/vue`

Right now, things usually work because most bundlers know to dedup references to the same packages with similar semver strings. However, sometimes the semver strings are not exact. For example `^5.7.0` and `^5.7.1`. This frequently happens when we release a patch-level release for only one package, not all. When this happens, bundlers act unpredictably with how they dedup. Using a peerDependency sidesteps this unpredictability.

This will be a breaking change for those three packages. That is why I will wait until v6 to implement this. For the remaining releases of v5, I will avoid the problem by making sure that all packages are always published upon any version bump.

**Comment by hisuwh** [comment]
I'm getting this error (`TypeError: Cannot read property 'isHiddenDay' of undefined`) with version `5.8.0` despite all my dependencies matching:

```
npm ls @fullcalendar/common
app@1.0.0 /mnt/c/code/app
├─┬ @fullcalendar/adaptive@5.8.0
│ ├── @fullcalendar/common@5.8.0
│ └─┬ @fullcalendar/premium-common@5.8.0
│   └── @fullcalendar/common@5.8.0  deduped
├─┬ @fullcalendar/daygrid@5.8.0
│ └── @fullcalendar/common@5.8.0  deduped
├─┬ @fullcalendar/interaction@5.8.0
│ └── @fullcalendar/common@5.8.0  deduped
├─┬ @fullcalendar/resource-timeline@5.8.0
│ ├── @fullcalendar/common@5.8.0  deduped
│ ├─┬ @fullcalendar/resource-common@5.8.0
│ │ └── @fullcalendar/common@5.8.0  deduped
│ ├─┬ @fullcalendar/scrollgrid@5.8.0
│ │ └── @fullcalendar/common@5.8.0  deduped
│ └─┬ @fullcalendar/timeline@5.8.0
│   └── @fullcalendar/common@5.8.0  deduped
├─┬ @fullcalendar/timegrid@5.8.0
│ ├── @fullcalendar/common@5.8.0
│ └─┬ @fullcalendar/daygrid@5.8.0
│   └── @fullcalendar/common@5.8.0  deduped
└─┬ @fullcalendar/vue@5.8.0
  └─┬ @fullcalendar/core@5.8.0
    └── @fullcalendar/common@5.8.0  deduped
```

**Comment by arshaw** [comment]
@hisuwh , it looks like npm is deduping some instances but not others. Until fullcalendar specifies the common package as a peer dependency, there doesn't seem to be a way to guarantee npm's behavior here. I'm sorry to say this, but please wipe away node_modules/package-lock.json, run npm install, and see what happens.

**Comment by TheophileMot** [comment]
Is there any progress on this? I seemed to have FullCalendar working a few days ago, but then yesterday, out of the blue, it started crashing with the `isHiddenDay` error. I've tried all sorts of things, including deleting node_modules and reinstalling, but haven't been able to fix it.

I'm using FullCalendar within the `svelte-fullcalendar` wrapper. I noticed that in `/node_modules/svelte-fullcalendar/package.json`, the version numbers were outdated (`^5.0.0` instead of `^5.10.1`). I changed these, but again, no luck.

Is there anything else I can try?

**Comment by acccccccb** [comment]
我遇到了同样的问题，我尝试重新安装以下几个包，但仍然会出现这个错误，
```
"@fullcalendar/core": "^5.10.1",
"@fullcalendar/daygrid": "^5.10.1",
"@fullcalendar/interaction": "^5.10.1",
"@fullcalendar/vue": "^5.10.1",
```
```
npm remove @fullcalendar/core @fullcalendar/daygrid @fullcalendar/interaction @fullcalendar/vue
npm i @fullcalendar/core @fullcalendar/daygrid @fullcalendar/interaction @fullcalendar/vue
```

之后我安装了fullcalendar，然后移除它，现在工作正常了
```
npm i fullcalendar
npm remove fullcalendar
```

**Comment by vhscom** [comment]
> Is there anything else I can try?

I pinged you in the above mentioned issue. I think `svelte-fullcalendar` may be getting ready for a v2 beta as well, which would be great to have as it would provide more comprehensive [SvelteKit](https://kit.svelte.dev/) support.

**Comment by TheophileMot** [comment]
@vhscom Thank you; I'll have a look at that this week.

**Comment by mvolkmann** [comment]
There is a solution that works with `svelte-fullcalendar`. See the dedupe configuration described here: https://github.com/YogliB/svelte-fullcalendar#setup.

**Comment by unsay** [comment]
When upgrading to `5.11.0` we started seeing this error using Vue.

```bash
> npm ls @fullcalendar/common
+-- @fullcalendar/core@5.11.0
| `-- @fullcalendar/common@5.11.0
+-- @fullcalendar/daygrid@5.11.0
| `-- @fullcalendar/common@5.11.0
+-- @fullcalendar/interaction@5.11.0
| `-- @fullcalendar/common@5.11.0  deduped
`-- @fullcalendar/list@5.11.0
  `-- @fullcalendar/common@5.11.0  deduped
```

conversely 5.10.1 works fine and the package is deduped:

```bash
> npm ls @fullcalendar/common
+-- @fullcalendar/core@5.10.1
| `-- @fullcalendar/common@5.10.1
+-- @fullcalendar/daygrid@5.10.1
| `-- @fullcalendar/common@5.10.1  deduped
+-- @fullcalendar/interaction@5.10.1
| `-- @fullcalendar/common@5.10.1  deduped
`-- @fullcalendar/list@5.10.1
  `-- @fullcalendar/common@5.10.1  deduped
```

Unfortunatley I don't know enough about `npm`'s deduping to provide a PR resolution.

**Comment by pedroestabruxelles** [comment]
This is still happening  on version 6

**Comment by LainZero** [comment]
> This is still happening on version 6

I can fixed error by my self.
you need to install @fullcalendar/common@beta in your project.

`npm install @fullcalendar/common@beta`

**Comment by vuolen** [comment]
So here's how I seem to have fixed it with Next.js. I had the basic React example with `react@5.11.2` and `daygrid@5.11.3` packages installed. They seemed to import global css files, which didn't sit well with Next. I found some fix involving `next-transpile-modules`. Running `npm ls @fullcalendar/common` indicated that there were no problems with deduping. Here's what I did:

1. Install `@fullcalendar/react@beta` and `@fullcalendar/daygrid@beta`
2. Remove usage of the `next-transpile-modules` from my `next.config.js`

I'm quite unfamiliar with Next, so I have no idea why this works, but I won't complain.

**Comment by arshaw** [comment]
Released in [v6.0.0](https://github.com/fullcalendar/fullcalendar/releases/tag/v6.0.0)

See this part of the release notes:
https://fullcalendar.io/docs/upgrading-from-v5#peer-dependencies

**Comment by avanichotara** [comment]
> > This is still happening on version 6
> 
> I can fixed error by my self. you need to install @fullcalendar/common@beta in your project.
> 
> `npm install @fullcalendar/common@beta`

it s not work

**Comment by smuchara** [comment]
Just in case someone is encountering the same issue in near future. 
Let me brief myself am working as a software developer at a software company and was assigned to specifically use nuxt js 2 on web application dev so when I was implementing the full calendar to create the scheduler I encountered the isHiddenDay, and other variables undefined error
**NOTE**
This is not an issue on the developer side it is about compatibility issues after so many trials and errors I finally found the solution as I said, it was a compatibility issue didn't realize at that moment 

I uninstalled the current version (usually latest when installed by default)  and installed an older version what worked for me was version 5.11.3

**Copy and paste code**

npm uninstall fullcalendar

npm install fullcalendar@5.11.3   

npm install --save @fullcalendar/interaction@5.11.3  @fullcalendar/timegrid@5.11.3  @fullcalendar/vue@5.11.3

if it still doesn't work just find a lower version / version that is compatible with your front-end framework

**Comment by nadirvishun** [comment]
@arshaw  I'm using `@fullcalendar/vue` plugin, when I update from `6.0.2` to `6.1.0` the same issue happened.

**Comment by tdansie** [comment]
> Just in case someone is encountering the same issue in near future. Let me brief myself am working as a software developer at a software company and was assigned to specifically use nuxt js 2 on web application dev so when I was implementing the full calendar to create the scheduler I encountered the isHiddenDay, and other variables undefined error **NOTE** This is not an issue on the developer side it is about compatibility issues after so many trials and errors I finally found the solution as I said, it was a compatibility issue didn't realize at that moment
> 
> I uninstalled the current version (usually latest when installed by default) and installed an older version what worked for me was version 5.11.3
> 
> **Copy and paste code**
> 
> npm uninstall fullcalendar
> 
> npm install fullcalendar@5.11.3
> 
> npm install --save @fullcalendar/interaction@5.11.3 @fullcalendar/timegrid@5.11.3 @fullcalendar/vue@5.11.3
> 
> if it still doesn't work just find a lower version / version that is compatible with your front-end framework

This is what I am doing as well. I am trying to use with Vue@3.2.45 and fullcalendar@5.11.3 is the highest version that I can install without getting this error.

**Comment by raajamalik** [comment]
There is Calender UI which was already running with the following packages:

`
"@fullcalendar/core": "^5.5.1",
    "@fullcalendar/daygrid": "^5.4.0",
    "@fullcalendar/interaction": "^5.4.0",
    "@fullcalendar/react": "^5.4.0",
    "@fullcalendar/timegrid": "^5.4.0",
`

But once we created a new application with the same package version, we started getting "Cannot read property 'isHiddenDay'". We had to again move to v5.11.4 to make everything work. Thanks.
