### ISSUE TITLE
How to translate week names to locale week names

### ISSUE THREAD

**Issue by Shahrza** [fullcalendar/fullcalendar#6373]
### Reduced Test Case
https://fullcalendar.io/docs/locale-demo

### Bug Description
Default language is English. For example French is supported language but Azerbaijani is not. How can I manually change week names. Monday - Bazar ertəsi etc.

**Comment by acerix** [comment]
Locale support is provided by the browser, in my browsers changing the locale to 'az' shows the day names as "B.E. | Ç.A. | Ç. | C.A. | C. | Ş. | B.".  For more control over the format, you need a plugin:

https://fullcalendar.io/docs/moment-plugin

There is an open issue to make that work for all dates:
https://github.com/fullcalendar/fullcalendar/issues/5683
↑
Please visit the above issue, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates.
