### ISSUE TITLE
Mismatch of tslib versions

### ISSUE THREAD

**Issue by rangermeier** [fullcalendar/fullcalendar#6376]
### Reduced Test Case

not reproducible with a link

### Bug Description

The `@fullcalendar/core@5.7.2` package specifies `tslib@^2.0.3` as dependency. 
In `@fullcelndar/core/main.js` there is an import of *__spreadArray*:
```import { __assign, __spreadArray, __extends } from 'tslib';```

However, *__spreadArray* was only added with tslib@2.1.0, when *__spreadArray**s*** was removed, see release notes: https://github.com/microsoft/tslib/releases/tag/2.1.0

Running a webpack build with FullCalendar 5.7.2  I receive the following error:
```WARNING in ./node_modules/@fullcalendar/daygrid/main.js 647:43-56
export '__spreadArray' (imported as '__spreadArray') was not found in 'tslib' (possible exports: __assign, __asyncDelegator, __asyncGenerator, __asyncValues, __await, __awaiter, __classPrivateFieldGet, __classPrivateFieldSet, __createBinding, __decorate, __exportStar, __extends, __generator, __importDefault, __importStar, __makeTemplateObject, __metadata, __param, __read, __rest, __spread, __spreadArrays, __values)
```

I don't understand how the build for FullCalendar works, but from this error I assume that it uses a more recent version of tslib than is specified in the various `package.json`s. 

I think this is a new version of #5479

**Comment by arshaw** [comment]
this fix has been released in [v5.8.0](https://github.com/fullcalendar/fullcalendar/releases/tag/v5.8.0). thanks!
