### ISSUE TITLE
jalali problem

### ISSUE THREAD

**Issue by saeed-raeisi** [fullcalendar/fullcalendar#6378]
### Reduced Test Case
https://fullcalendar.io/reduced-test-cases

### Bug Description

Describe how to recreate the bug.
odoo v 14 used fullcalendar v 4.4.0 but in 
What do you expect to happen?
But it has a problem with displaying date with time zone. In fact, jalali and Gregorian dates are different in week and year and day views
What happens instead?
Show date only in jalali or AD
### Screenshots
https://www.awesomescreenshot.com/image/9431357?key=2d3fce98d0a39072dfb6621fec4ed2e1
If the bug is visual, include a screenshot if possible.
If not, erase this section.

**Comment by acerix** [comment]
I believe this existing ticket captures this need:
https://github.com/fullcalendar/fullcalendar/issues/1813
↑
Please visit the above issue, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates.

**Comment by saeed-raeisi** [comment]
In fact, my problem is different
In odoo from full calendar 4.4 and jquery datepicker 1.12 Used
When using, I have 2 different dates in the full calendar
link:
https://mega.nz/file/q7IVUITL#FzFvXMwtMhrbIkIbGsvR-4Y-eNFP0eKb96mlpyA3tyA

**Comment by acerix** [comment]
It seems that would be fixed when Jalali support is added, but if there is a bug, please supply a [runnable, stripped-down demonstration](http://fullcalendar.io/wiki/Reduced-Test-Cases/).
