### ISSUE TITLE
Uneven event heights cause subsequent events to display overlapping at the top of the resource

### ISSUE THREAD

**Issue by RonRadtke** [fullcalendar/fullcalendar#6395]
### Reduced Test Case

https://codepen.io/ronradtke/pen/ExWBBQw?editors=0010

### Bug Description

As soon as there are events with different heights fullcalendar won't set the top position correctly for the following events.
You will need 3 blocks of events
1) One small, one high event
2) Events (doesn't matter if heigh or small, but should be similar)
3) Events (doesn't matter if heigh or small, but should be similar)

Events on 1) and 2) will be displayed correctly
Events on 3) (and following if there are more blocks of events) will overlap and all events will have set top = 0 so you will only see one of the events. For the example there should be 3 events in the last block, but only 1 is visible.

### Screenshots
First pictures shows the bug. Second screenshot shows the result if all events have the same height.
You can clearly see the wrong top position for the events in the html.
![image](https://user-images.githubusercontent.com/9134168/123232727-baafb080-d4d9-11eb-9f4a-4648ebccd248.png)
![image](https://user-images.githubusercontent.com/9134168/123232752-bf746480-d4d9-11eb-84d2-4a09d32a29d3.png)

**Comment by FilipKostrzewski** [comment]
Agree, experienced that same. Some events going under another, same for month view.

**Comment by RonRadtke** [comment]
It also doesn't matter if the unregular event comes on the first day or not.

**Comment by arshaw** [comment]
fixed in [5.9.0](https://github.com/fullcalendar/fullcalendar/releases/tag/v5.9.0)

updated repro: https://codepen.io/arshaw/pen/zYwWoyV?editors=0010
