### ISSUE TITLE
Duplicate events in popover

### ISSUE THREAD

**Issue by nikolamus** [fullcalendar/fullcalendar#6397]
### Reduced Test Case

https://codepen.io/nikolamus/pen/RwpXPwo

### Bug Description

Events are duplicated or multiplied when opened in popover.

It can be consistently reproduced with these parameters:
- `dayMaxEventRows: 4`, or `true`, or any number that will cause events to collapse
- `eventOrder` - any custom sorting function

In the test data there is only one event named "Allison Olsen" on July 9. Once it is rendered in popover it appears 3 times.

### Screenshots

<img width="1017" alt="Screen Shot 2021-06-24 at 14 35 25" src="https://user-images.githubusercontent.com/38858439/123264370-40dbef00-d4fa-11eb-899e-6a85ec271119.png">

**Comment by acerix** [comment]
The issue is that your `eventOrder` function is not returning a consistent order of the events, it needs to compare the events (arguments) to each other to do that:

https://codepen.io/acerix/pen/oNZKKLQ?editors=0010

**Comment by nikolamus** [comment]
@acerix 
It also happens when I remove the custom `eventOrder` function.
https://codepen.io/nikolamus/pen/poPogGw

![Screen Shot 2021-06-28 at 14 14 08](https://user-images.githubusercontent.com/38858439/123637966-e787fe80-d81e-11eb-9d56-634574f08e33.png)

It's my understanding that`start,-duration,allDay,title` is the default sorting order.
So even though other event parameters can be the same or missing, there are no 2 events with the same `title` on the same day.

**Comment by acerix** [comment]
Thanks for the info, I can see the bug and made a more reduced test:

https://codepen.io/acerix/pen/gOWbrGP?editors=0010

The issue seems to be with the ordering by start date, setting to order by `title` does not have the duplicate.

**Comment by arshaw** [comment]
released in [5.9.0](https://github.com/fullcalendar/fullcalendar/releases/tag/v5.9.0)

updated repro: https://codepen.io/arshaw/pen/eYWMBQX
