### ISSUE TITLE
12 hour time for spanish locale

### ISSUE THREAD

**Issue by IvanVasquez** [fullcalendar/fullcalendar#6401]
### Reduced Test Case

https://codepen.io/IvanVasquez/pen/rNyXmBP?editors=001

### Bug Description

When I set the locale as spanish it defaults to 24 hour time `(timeGridWeek)`  and I want to know if there's a way to change the hours column to 12 hour time (as it works on default locale), I tried using `eventTimeFormat` with `hour12: true` but only changes the event, also it has a bug that shows 12:00 pm as 0:00pm, probably related to the 24 hour format.

**Comment by acerix** [comment]
The time formatting is handled by the browser, you can use the moment plugin for some more control, also there is an open issue regarding this:
https://github.com/fullcalendar/fullcalendar/issues/5683
↑
Please visit the above issue, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates.

The `es-US` locale shows 12 hour time in my browsers so may work for you:

https://codepen.io/acerix/pen/OJpKKpV?editors=001
