### ISSUE TITLE
Do not trigger select when dateClick is triggered

### ISSUE THREAD

**Issue by espen** [fullcalendar/fullcalendar#6404]
### Checklist

  - [x] I've already searched through [existing tickets](https://fullcalendar.io/issues)
  - [x] Other people will find this feature useful

### Feature Description

I use `select` callback to generate a form with event start/end, however when the user just clicks in the calendar without selecting an end time the event defaults to 15 minutes. I could use `dateClick` to just get the event start time and generate my form with my own internal defaults but FC will trigger both `select` and `dateClick`.

I'm not sure what my options are. Could one of the following work:

1) Add `noEndSelected: true` to `selectionInfo`?
2) Add a setting that will not trigger `select` when `dayClick` is triggered?

My user case here is that when the user just clicks in the calendar I want to generate end time based on some user settings as the user has not actively set an end time.

**Comment by acerix** [comment]
You can set selectMinDistance so selection only starts after dragging that distance.

https://fullcalendar.io/docs/selectMinDistance
