### ISSUE TITLE
HeaderToolbar and FooterToolbar Wrong Display

### ISSUE THREAD

**Issue by aetasoul** [fullcalendar/fullcalendar#6406]
### Reduced Test Case

https://codepen.io/aetasoul/pen/MWpNzyY?editors=0010

### Bug Description

Create the headerToolbar o footerToolbar like:

```
headerToolbar: {
      left: '',
      center: 'prev,title,next',
      right: ''
},
footerToolbar: {
      left: '',
      center: 'prev,title,next',
      right: ''
}
```

Place the title in the middle of the buttons cause the prev/next button to show on top or bottom of the title.
Here the workaround that I used to make it looks better:

```css
.fc-toolbar-chunk div {          
  display: flex !important;
  align-items: center;
}
```

### Screenshots

Wrong:
![image](https://user-images.githubusercontent.com/15131692/123430498-8c5cce80-d5c8-11eb-8b0b-31a5f711db62.png)

Correct:
![image](https://user-images.githubusercontent.com/15131692/123430780-de055900-d5c8-11eb-9d9a-b68525efe598.png)

**Comment by acerix** [comment]
I believe this existing ticket captures this need:
https://github.com/fullcalendar/fullcalendar/issues/6216
↑
Please visit the above issue, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates.
