### ISSUE TITLE
listWeek view show the event ends at midnight regardless of nextDayThreshold and slotMaxTime

### ISSUE THREAD

**Issue by Virusmater** [fullcalendar/fullcalendar#6408]
### Reduced Test Case
https://codepen.io/DimaKompot/pen/zYwONdK

### Bug Description

1. Create event that starts at 18:00 (or any other time) and end at 02:00 of the next day (or any other time below nextDayThreshold)
2. Set nextDayThreshold to 03:00
3. Set slotMaxTime: '27:00',
4. Switch to listWeek view

Expected:
Event shows as 18:00 - 02:00

Actual:
Event shows as 18:00 - 00:00

### Screenshots
List view:
https://ibb.co/MSS4jwx
Day view:
https://ibb.co/prHPcdp

**Comment by acerix** [comment]
I believe this existing ticket captures this need:
https://github.com/fullcalendar/fullcalendar/issues/3038
↑
Please visit the above issue, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates.
