### ISSUE TITLE
[Violation] Added non-passive event listener to a scroll-blocking 'touchmove' event. Consider marking event handler as 'passive' to make the page more responsive

### ISSUE THREAD

**Issue by victorgt26** [fullcalendar/fullcalendar#6409]
### Reduced Test Case

[Violation] Added non-passive event listener to a scroll-blocking 'touchmove' event. Consider marking event handler as 'passive' to make the page more responsive

### Bug Description

In reponsive not work select event, display the next message:
[Violation] Added non-passive event listener to a scroll-blocking 'touchmove' event. Consider marking event handler as 'passive' to make the page more responsive

"@fullcalendar/angular": "^5.8.0",
"@fullcalendar/core": "^5.8.0",

### Screenshots
<img width="356" alt="Captura de Pantalla 2021-06-27 a la(s) 13 33 33" src="https://user-images.githubusercontent.com/20076727/123554052-49c3ff00-d74c-11eb-8fa8-d5bef42ff546.png">

**Comment by acerix** [comment]
I believe this existing ticket captures this need:
https://github.com/fullcalendar/fullcalendar/issues/5899
↑
Please visit the above issue, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates.
