### ISSUE TITLE
Incorrectly assign events to resources on timeline view (version 3.10.2)

### ISSUE THREAD

**Issue by LukMas** [fullcalendar/fullcalendar#6412]
### Reduced Test Case

Here is a link to a reduced test case that uses real data fetched within my system (JSON has been created locally and set up with suggested link): 
https://codepen.io/Lucas79/pen/OJmJRVG?editors=0010

### Bug Description
Simply start the code configured in the pen. 
More in detail, for one of my views I need to show all the weekly Events of a Semester. To do this I load all the Events between 2 given Dates (a Range, for example from the 1. October 2021 to the 31. Januar 2022), from where I create: 
<ul>
<li> a list of events, from the Events, with 
<ul>
<li> the basic information (start time, end time, text, ...) are taken from the Event
<li> the start/end Date are set to a given Date (which I use this also for the gotoDate(...)) 
<li> the ResourceId is found from the real start Date (so, for example, if the Event is on 2021-10-01 I get the Id '2021-10-01´, if on 2021-12-23 it will be '2021-12-23' and so on)
</ul>
<li> a list of Resources, from the Range and a given day of the week (for example, Monday), where
<ul>
<li> the title of the Resource is the text found from the Date (so, for example, for the Event on 2021-10-04 I get '4. Oktober 2021')
<li> the Id of the Resource is calculated from the Date  (the same process used for the Events)
</ul>
</ul>

At the end of this process I get a view with all the Events that are hold on the week day that I've selected and are inside the given Range. This was working correctly up to when I've updated to the version 3.10.2.

### What happens instead?
All the Events instead of being split on the correct dates (=resources) are shown all together in the same row. 

### Screenshots
![EventsResourcesError](https://user-images.githubusercontent.com/19855368/123655605-67b66000-d82f-11eb-968a-5f75853750f6.jpg)

NOTE: I can't upgrade to a newer version, I've a lot of code that doesn't work anymore due to the big changes in the newest versions. I don't have enough time to check/fix all the problems. 
A fix for this version or a suggestion to how generate the same view without having to change too many points is really appreciated.

**Comment by acerix** [comment]
It looks like the issue is that those events all have the same `id`, in v3, this makes it a "repeating" event which sets the same properties on each.  If you don't want that, you need a unique `id` for each, or you could rename that property to something like `myDatabaseID` so it doesn't make a repeating event.

**Comment by LukMas** [comment]
Thanks, it works! 
Anyway, I find it a bit weird: it was working totally different in the previous version of the same release (the 3.). Actually what I have is really the same event, just with a different ResourceId; now it looks that this information is ignored. 
To adapt to the change I've had to add a new field, to store the EventId, and check all the places where it was used the Id and update to EventId.
