### ISSUE TITLE
DatesRender Not working when Month rate change

### ISSUE THREAD

**Issue by Mansoun** [fullcalendar/fullcalendar#6415]
### Reduced Test Case
FullCalendar V4 

Please See  [This](https://codepen.io/ADyson82/pen/oNjExGx).

### Bug Description

When Month rate change , DatesRender not working.

**Comment by acerix** [comment]
The issue is that you only are doing `addEventListener` on the initial events, you would need to do the same for new events that are rendered.

**Comment by Mansoun** [comment]
> The issue is that you only are doing `addEventListener` on the initial events, you would need to do the same for new events that are rendered.

Yes. you are right. Thanks.
