### ISSUE TITLE
In datesSet function, getMonth() method of viewObject  return a number less than the correct number.

### ISSUE THREAD

**Issue by Bijan-mp** [fullcalendar/fullcalendar#6420]
### Reduced Test Case
https://codepen.io/BijanMohammadpour/pen/VwbwNmx

### Bug Description
in datesSet(dateinfo) method, getMonth() method return a number less than the correct number
ex:
if dateInfo.view.activeStart return "May 30 2021" and dateInfo.view.activeEnd  return "Jul 11 2021" when use getMonth() return wrong month. the below code show what expect and what happen.
dateInfo.view.activeStart.getMonth() **//expect to get 5 but get 4**
dateInfo.view.activeEnd.getMonth()    **//expect to get 7 but get 6**

And if dateInfo.view.currentStart return "May 30 2021" and dateInfo.view.currentEnd return "Jun 06 2021"  when use getMonth() return wrong month. the below code show what expect and what happen.
dateInfo.view.currentStart.getMonth() **//expect to get 5 but get 4**
dateInfo.view.currentEnd.getMonth()  **//expect to get 6 but get 5**

### Screenshots
![week view](https://user-images.githubusercontent.com/4954836/123805772-9e5daa80-d903-11eb-98ed-0f2541f6f99d.jpg)
![month view](https://user-images.githubusercontent.com/4954836/123805751-97cf3300-d903-11eb-8daa-bb24c9189ae4.jpg)

**Comment by acerix** [comment]
`activeStart` includes days outside the view that are still visible (eg. May 30 here), `currentStart` is when the view starts so it seem you want to use that instead.

https://fullcalendar.io/docs/view-object

Also, `getMonth` returns a zero-indexed number, meaning it starts at 0 for January, 1 for February, etc..

**Comment by Bijan-mp** [comment]
Hi tnx for your reply.
I think if `getMonth `returns the month's real number(not the index number) it will be so useful. Because when using SQL query in the backend it necessary to increase the month after `getMonth`.
Of course this is your choice. anyway the fullcalendar is a very nice project ;).
Best regards,
