### ISSUE TITLE
Select option for touch devices instead of long-press in cell

### ISSUE THREAD

**Issue by arunkumar3893** [fullcalendar/fullcalendar#6425]
### Checklist

Please mark these items with an [x]

  - [ ] I've already searched through [existing tickets](https://fullcalendar.io/issues)
  - [ ] Other people will find this feature useful

### Feature Description

Please describe what this feature will do.

### Visual Mockups

If you are requesting a new UI, please include a mockup.
If not, erase this section.

**Comment by acerix** [comment]
How are you looking for that to work on touch?

You could set it programmatically, for example after two dates are clicked (touched).

https://fullcalendar.io/docs/Calendar-select
