### ISSUE TITLE
View does not scroll by dragging an event to the edge when using shadow DOM

### ISSUE THREAD

**Issue by aetasoul** [fullcalendar/fullcalendar#6428]
### Reduced Test Case

https://5uich.csb.app/
https://codesandbox.io/s/test-drag-shadow-dom-5uich

### Bug Description

Drag one event don't scroll the view horizontally or vertically.
If you resize the browser the calendar scrollbar are ignored and the event dragging scroll another scrollbar.

Check the video to better understand. The problem is also present on mobile ( I was able to reproduce the behavior with the chrome debugger, selecting any mobile device.), check second video.

### Screenshots

![event drag scrollbar not working](https://user-images.githubusercontent.com/15131692/124099753-222baa00-da5e-11eb-9655-08274e43cda1.gif)

![event drag scrollbar not working mobile](https://user-images.githubusercontent.com/15131692/124100799-0d034b00-da5f-11eb-8296-ff6b83279ec2.gif)

**Comment by aetasoul** [comment]
Hi,
I also tested with the old FC 4.4.2 and had the same problem

https://codesandbox.io/s/test-shadow-dom-v4-nxubv
https://nxubv.csb.app/

**Comment by aetasoul** [comment]
Hi @arshaw do you plan to fix this also on the V4 of the calendar o I have to open a new issue?

**Comment by arshaw** [comment]
released in [5.9.0](https://github.com/fullcalendar/fullcalendar/releases/tag/v5.9.0)

you'll now see that auto-scrolling works in the original repro:
https://codesandbox.io/s/test-drag-shadow-dom-forked-idy1j?file=/src/App.js

@aetasoul , we likely won't backport this to older versions :(

**Comment by aetasoul** [comment]
Hi @arshaw Thank you for the fix 👍
