### ISSUE TITLE
Cannot resize events by touch when using shadow DOM

### ISSUE THREAD

**Issue by aetasoul** [fullcalendar/fullcalendar#6429]
### Reduced Test Case

https://5uich.csb.app/
https://codesandbox.io/s/test-drag-shadow-dom-5uich

Working fc demo: https://codepen.io/aetasoul/pen/OJmVVOy

### Bug Description

When you press and hold an event on mobile divices the event becomes draggable, but as soon as I'm releasing the event, it is deselected. I was able to reproduce the behavior with the chrome debugger, selecting any mobile device.
On the fullcalendar.io webpage the function works normally

### Screenshots

Not working:

![not working](https://user-images.githubusercontent.com/15131692/124101989-3a9cc400-da60-11eb-9257-cf355844292f.gif)

Working:

![working](https://user-images.githubusercontent.com/15131692/124105805-e1cf2a80-da63-11eb-9558-2f805e9c7043.gif)

**Comment by aetasoul** [comment]
Hi,
I also tested with the old FC 4.4.2 and had the same problem

https://codesandbox.io/s/test-shadow-dom-v4-nxubv
https://nxubv.csb.app/

**Comment by aetasoul** [comment]
Hi @arshaw do you plan to fix this also on the V4 of the calendar o I have to open a new issue?

**Comment by arshaw** [comment]
released in [5.9.0](https://github.com/fullcalendar/fullcalendar/releases/tag/v5.9.0)

@aetasoul , we likely won't backport this to older versions :(

**Comment by aetasoul** [comment]
Hi @arshaw Thank you for the fix 👍
