### ISSUE TITLE
Selecting multiple dates not showing correctly on the modal

### ISSUE THREAD

**Issue by ljfreelancer88** [fullcalendar/fullcalendar#6431]
### Reduced Test Case

https://fullcalendar.io/docs/date-clicking-selecting-demo

### Bug Description

Based on the screenshot and using the link above, I have selected the date 7, 8 & 9 but the modal included until 10. I have tried also in my console, but it still the same. I want to show what only selected on the calendar. How can I do this? Thank you in advance.

### Screenshots
![124170499-7db56200-da75-11eb-8610-cf0ef78d4a15](https://user-images.githubusercontent.com/7919039/124203991-fd5e2380-daab-11eb-931d-585d6cee3253.png)

**Comment by acerix** [comment]
The value of `endStr` is the _exclusive_ end time, you should subtract one day to get the _inclusive_ time.
