### ISSUE TITLE
expandRows: false not working in month view all the time

### ISSUE THREAD

**Issue by jplevene** [fullcalendar/fullcalendar#6434]
### Reduced Test Case

[REDUCED TEST CASE](https://codepen.io/jplevene/pen/LYypyOB?editors=0010).

### Bug Description

There date cells don't limit the amount of events and have a +6 events at the bottom, etc. when setting expandRows:false in month view.  I have calendars with 30 events a day and I can't limit them.

P.S.
Ignore the extra css, that is a suggestion.

**Comment by acerix** [comment]
The `expandRows` setting only applies to timegrid and timeline views, and what it does is expand the row size to fill the height if set to `true`.

To limit the number of events you can set [dayMaxEventRows](https://fullcalendar.io/docs/dayMaxEventRows).
