### ISSUE TITLE
Event incorrectly goes on for 2 days if it starts late

### ISSUE THREAD

**Issue by jplevene** [fullcalendar/fullcalendar#6436]
### Reduced Test Case

You must paste a link to a [REDUCED TEST CASE](https://codepen.io/jplevene/pen/LYypyOB?editors=0010).

### Bug Description

See the two entries with BUG in the title "Late event with end - BUG" and "Late event NO end - BUG".

Some users just want to set the start time and not the end, however when the start is late in the day, the event rolls over to the next day, which is incorrect, even when the end time is the same as the start.

**Comment by acerix** [comment]
I believe this existing ticket captures this need:
https://github.com/fullcalendar/fullcalendar/issues/3038
↑
Please visit the above issue, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates.
