### ISSUE TITLE
Times events do not get printed in Firefox using adaptive plugin

### ISSUE THREAD

**Issue by kgilden** [fullcalendar/fullcalendar#6438]
### Reduced Test Case

https://replit.com/@kgilden/fullcalendar-6438#index.html

### Bug Description

In Firefox no events get rendered in time grid views, if the adaptive plugin is used.

### Screenshots

Firefox is on the left side, Chrome is on the right side.

https://user-images.githubusercontent.com/918599/124740908-e001dd00-df23-11eb-93b6-23c8d4d8116c.mp4

**Comment by acerix** [comment]
Thanks, confirmed.  This demo also shows the issue, only the all-day event gets printed:

https://fullcalendar.io/docs/vertical-resource-standard-demo

**Comment by arshaw** [comment]
This has been fixed in [5.9.0](https://github.com/fullcalendar/fullcalendar/releases/tag/v5.9.0)

Please open Firefox and try to print this demo: https://fullcalendar.io/docs/vertical-resource-standard-demo
