### ISSUE TITLE
dayMaxEvents doesn't work in such cases for dayGridMonth

### ISSUE THREAD

**Issue by devmegaminds** [fullcalendar/fullcalendar#6439]
### Reduced Test Case
https://replit.com/@NikunjBBalar/full-calendar#index.html "not reproducible with a link"

### Bug Description
dayMaxEvents doesn't work in some cases 

### Screenshots
![image](https://user-images.githubusercontent.com/32726700/124752703-cf625e80-df45-11eb-84b4-01a885520cca.png)

**Comment by acerix** [comment]
I don't see the issue in your demo, how to reproduce it?

**Comment by devmegaminds** [comment]
Thanks @acerix to add your input here. 

It's not replicated in given demo, but if you see attached screenshot. in few dates overlap events.

**Comment by acerix** [comment]
We need a way to reproduce the issue so please provide a [runnable, stripped-down demonstration](http://fullcalendar.io/wiki/Reduced-Test-Cases/) if there is a bug.
