### ISSUE TITLE
get info range when use eventMouseEnter

### ISSUE THREAD

**Issue by kkasing11** [fullcalendar/fullcalendar#6443]
**Reduced Test Case**
https://codepen.io/kkasing11/pen/abWZdXo?editors=0010

**Bug Description**
In my case, I have setup the timeline like:
```
events: [{
     title: 'My schedule'
     start: '2021-07-07T03:08:10.567Z',
     end: '2021-07-07T06:08:10.567Z',
}]
```
with default `timeZone: 'local'`
- As you can see the ui is render exactly what I want with `GMT+7` that my localtime (Perfect)
- But when i try to get it back that info with 
```
eventMouseEnter(info) {
    console.log(info)
}
```
It seem like the range add more `GMT+7` :

**Screenshots**

![image](https://user-images.githubusercontent.com/35018162/124910632-043de680-e016-11eb-9a7f-0a56cea111ed.png)

Did I do something wrong?

Thanks

**Comment by acerix** [comment]
The times are stored as JS Date objects which don't support timezones, you can get the correct time with `toISOString`.

https://codepen.io/acerix/pen/MWmeOME?editors=0011

https://fullcalendar.io/docs/timeZone#UTC-coercion

**Comment by kkasing11** [comment]
It work very well. Thanks for that, hope it's not bothering you.

> The times are stored as JS Date objects which don't support timezones, you can get the correct time with `toISOString`.
> 
> https://codepen.io/acerix/pen/MWmeOME?editors=0011
> 
> https://fullcalendar.io/docs/timeZone#UTC-coercion
