### ISSUE TITLE
Typing of `event.setProp` does not allow booleans

### ISSUE THREAD

**Issue by turisap** [fullcalendar/fullcalendar#6445]
### Reduced Test Case

[REDUCED TEST CASE](https://codesandbox.io/s/setprop-typing-628ng?file=/src/calendar.tsx).

### Bug Description
As per docs, we can set any non-date related props via this function. However, its typing states that it only accepts strings as values. Consequently, I get a TS error when trying set `event.setProp('editable', true)`

```
declare class EventApi {
    // ....
    setProp(name: string, val: string): void;
```

**Comment by arshaw** [comment]
released in [5.9.0](https://github.com/fullcalendar/fullcalendar/releases/tag/v5.9.0)
