### ISSUE TITLE
Touch device, select not working when inside webcomponent

### ISSUE THREAD

**Issue by Bakino** [fullcalendar/fullcalendar#6448]
### Reduced Test Case

https://codepen.io/olibakino/pen/eYWdbRV?editors=1010

### Bug Description

In a touch device, when fullcalendar is included in a WebComponent, select an event does not work. The event is selected but immedialty unselected

It should remain selected like when fullcalendar is not included in a WebComponent

**Comment by acerix** [comment]
I believe this existing ticket captures this need:
https://github.com/fullcalendar/fullcalendar/issues/6429
↑
Please visit the above issue, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates.
