### ISSUE TITLE
lobal CSS cannot be imported from within node_modules.

### ISSUE THREAD

**Issue by NeznaykaGM** [fullcalendar/fullcalendar#6450]
Nextjs project

./node_modules/@fullcalendar/common/main.css
Global CSS cannot be imported from within node_modules.
Read more: https://nextjs.org/docs/messages/css-npm
Location: node_modules/@fullcalendar/common/main.js

<img width="981" alt="Снимок экрана 2021-07-12 в 15 56 18" src="https://user-images.githubusercontent.com/71708401/125291105-b54fc400-e329-11eb-9ca6-70e071a43a02.png">

**Comment by approached** [comment]
Same error maybe the request will be helping #6619
