### ISSUE TITLE
selectMaxDistance option similar to selectMinDistance

### ISSUE THREAD

**Issue by horsebuzz** [fullcalendar/fullcalendar#6452]
### Checklist

  - [X] I've already searched through [existing tickets](https://fullcalendar.io/issues)
  - [X] Other people will find this feature useful

### Feature Description

This feature will allow to limit the event block on calendar.

It would be great to have `selectMaxDistance` option similar to `selectMinDistance` so that when user selects timeslot, we can limit the event period.

For example, in my case I would only like to know startTime of the event so user should only be allowed to select one interval block which will give me startTime. End time is determined by the service user choses.

Similarly if someone has only 1.5 hour event blocks, then set `selectMaxDistance` to 3 provided interval is 30 minutes.

**Comment by acerix** [comment]
`selectMinDistance` is a value in pixels, so selecting only starts after moving that distance. It sounds like you looking to control which selections are allowed, you can use selectConstraint for that.

https://fullcalendar.io/docs/selectConstraint
