### ISSUE TITLE
Provide the resource in which the event is being rendered in the eventContent hook.

### ISSUE THREAD

**Issue by demobiel** [fullcalendar/fullcalendar#6455]
### Checklist

Please mark these items with an [x]

  - [x] I've already searched through [existing tickets](https://fullcalendar.io/issues)
  - [ ] Other people will find this feature useful

### Feature Description

For a planning tool we have one event (an employee working for a customer), and 2 resources: the employee and the customer. The event is linked to both. Example:
```
{
   "title": "LaundryDay",
   "resources": [ "C1" , "E2" ]
}
```
The "eventContent" is called twice during render, once when the event is rendered for C1, and once when the event is rendered for E2. However it is not possible to know for which resource the event is actually rendered. If we would know that, I could change the title so that for the customer it would show the name of the employee that would do the laundry, and for the employee it would show the name of the customer for whom he will be doing the laundry.

For initial rendering this is possible by using the "eventDidMount" hook, but of course when you drag and drop the event from one resource to the other, you would like to trigger the eventContent hook again, so you can update the title to reflect the change of the resource. Right now I solve it by removing the event from the calendar and adding it back, which calls the "eventDidMount" hook again, but of course this is not optimal.

Why would I use it?
```
eventContent: function ( arg ){
     if ( arg.resource.extendedProps.type === 'customer' ){
              return arg.event.extendedProps.employeeName;
    } else if ( arg.resource.extendedProps.type === 'employee' ) {
             return arg.event.extendedProps.customerName;
   }
},
eventDrop: function ( dropInfo ){
   if ( dropInfo.newResource.type === 'customer' ){
      dropInfo.event.setExtendedProp ( 'customerName', dropInfo.newResource.title );
   } else if  ( dropInfo.newResource.type === 'employee' ){
      dropInfo.event.setExtendedProp ( 'employeeName', dropInfo.newResource.title );
   } 
}
```

thanks for reading!

**Comment by acerix** [comment]
I believe this existing ticket captures this need:
https://github.com/fullcalendar/fullcalendar/issues/4926
↑
Please visit the above issue, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates.
