### ISSUE TITLE
Need to fix minimum width of column & add horizontal scroll   

### ISSUE THREAD

**Issue by kevalKanpariya** [fullcalendar/fullcalendar#6469]
### Check list
Please mark these items with an [x]

 I've already searched through [existing tickets](https://fullcalendar.io/issues)
 Other people will find this feature useful

### Bug Explain

[Video Description](https://www.awesomescreenshot.com/video/4544041?key=1a65cd4b021c5ad748dda611f12b2eb0)
![image](https://user-images.githubusercontent.com/78338168/126269696-eb4a135b-df78-4058-ac68-d5f26389283d.png)

Above mention Test case has UI issue

### Bug Description

In our application we use full calendar and we show whole appointment of particular person. Initially it shows perfect but when we select particular options then new columns are added dynamically and cell gets congested. because of this issue can't see our data on particular slot or event. 

What do you expect to happen?

We expect that API should give support of min-width for column so till that width, cell can shrink and then after horizontal scroll came and user can easily see data on particular events.

What happens instead?

Right now we can't apply minimum width in cell so we face the issue like mention below UI.

### Screenshots

![image](https://user-images.githubusercontent.com/78338168/126272332-9c0b3250-20b2-4681-95e8-79841ba55e6b.png)

**Comment by AjeetUI** [comment]
I struggling from same problem When more column are added then it looks so narrow even we can't able to read single word

So, Can you please check this issue and provide minimum width & horizontal scroll support so we can manage column with proper space

**Comment by acerix** [comment]
You can use the dayMinWidth to increase the size of the cells and enable horizontal scrolling:

https://fullcalendar.io/docs/dayMinWidth

**Comment by tpmh31292** [comment]
v5.9.0 gives an "No ScrollGrid implementation" error.

#6314

**Comment by ckhandla94** [comment]
I have just fixed the issue. I am facing issue because of mismatch version of @fullcalendar/scrollgrid. 
i.e I have installed full-calendar  5.11.0 and @fullcalendar/scrollgrid 5.11.2. I have make exact same version and issue get fixed
