### ISSUE TITLE
Events displayed on top of each other when using custom renderer

### ISSUE THREAD

**Issue by daniel-stoll** [fullcalendar/fullcalendar#6471]
### Reduced Test Case
https://codepen.io/daniel-at-yasoon/pen/yLbomdd?editors=001

### Bug Description

This bug appears on rare occasions in production.
The minimal test case that reproduces the error is seen in the codepen + screenshot.
Events on thursday overlap each other.

What I tested/found out:
This error shows up only, when the custom event render hook "eventContent" is used
It is only present in the dayGridMonth view (as far as I tested)

Removing any of the given events will display the events on thursday in the correct order
Filling up any day from monday to wednesday to >=3 events  fixes the issue
all following non allday events for this row (after wednesday) are broken if atleast 1 all day event is present that day
moving the events from thursday to wednesday fixes the issue, so the gap is important

Unfortunately I can't override the css with custom css, as the element with css class "fc-daygrid-event-harness" gets the style attribute margin-top with a negative value.
Usually the margin-top is set to 0px

EDIT:
overwriting fc-daygrid-event-harness with margin-top: 0px!smportant solves this issue, but creates another one.
Long events (>1 day) will than have the same problem. They are shown under the other all day events.
I think this will help tracking the issue ;)

### Screenshots

![grafik](https://user-images.githubusercontent.com/37585540/126493813-413b72a4-3097-400b-8ebc-87ddd1ed366a.png)

**Comment by tobiasnitsche** [comment]
+1

**Comment by acerix** [comment]
Thanks, confirmed.  Looks related to  https://github.com/fullcalendar/fullcalendar/issues/6393

**Comment by daniel-stoll** [comment]
@acerix  @arshaw 
I tried out the newest version and it fixes this bug.
Thanks a lot and keep up the good work.
