### ISSUE TITLE
Resource time line displays incorrect events when snapduration is set.

### ISSUE THREAD

**Issue by waegen** [fullcalendar/fullcalendar#6481]
### Reduced Test Case
https://stackblitz.com/edit/angular-ivy-wwztfk?file=src/app/app.component.ts

### Bug Description

Once we use a snapduration in the timeline view the events are displayed incorrectly. This happens in both cases where we have normal and recurring events. Only a snapDuration of 00:00:00 or omitting the property gives the expected results, but this is not a feasible solution as this negates the meaning of snapDuration property.

We are currently evalutation this component for commercial usage and absolutley need this feature working.

**Comment by acerix** [comment]
I believe this existing ticket captures this need:
https://github.com/fullcalendar/fullcalendar/issues/4925
↑
Please visit the above issue, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates.
