### ISSUE TITLE
Search bar on the FullCalendar website

### ISSUE THREAD

**Issue by PierreThiollent** [fullcalendar/fullcalendar#6483]
### Checklist

Please mark these items with an [x]

  - [x] I've already searched through [existing tickets](https://fullcalendar.io/issues)
  - [x] Other people will find this feature useful

### Feature Description

I think It will be very usefull for a lot of developers to have a search bar on the FullCalendar website because sometimes you just need some infos about a method or an object and you have to find the category, subcategory etc where those infos are.. very annoying...
Despite this the library is Awesome, thanks !

**Comment by acerix** [comment]
I believe this existing ticket captures this need:
https://github.com/fullcalendar/fullcalendar/issues/4196
↑
Please visit the above issue, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates.
