### ISSUE TITLE
Publish 5.9.0 to npm

### ISSUE THREAD

**Issue by lzilioli** [fullcalendar/fullcalendar#6485]
### Checklist

Please mark these items with an [x]

  - [X] I've already searched through [existing tickets](https://fullcalendar.io/issues)
  - [X] Other people will find this feature useful

### Feature Description

Hi, y'all. Super appreciate this package for doing the heavy calendar lifting for our front-end. Great work!

I see that v5.9.0 was built and tagged for release, however the build seems to have prevented the npm publish? https://github.com/fullcalendar/fullcalendar/runs/3183159814

I have been actively looking into an issue related to FC 5 not ordering events properly in the dayGrid and am very eager to try this out to see if it fixes. Any guidance as to when I can expect the version to hit npm (or how I can test it sooner than that) would be greatly appreciated. Thank you.

### Visual Mockups

If you are requesting a new UI, please include a mockup.
If not, erase this section.

**Comment by arshaw** [comment]
v5.9.0 is now officially released, on npm

**Comment by arshaw** [comment]
https://github.com/fullcalendar/fullcalendar/releases/tag/v5.9.0
