### ISSUE TITLE
Moving a grouped event with RRULE, new endDate not returned

### ISSUE THREAD

**Issue by jplevene** [fullcalendar/fullcalendar#6491]
### Reduced Test Case

https://codepen.io/jplevene/pen/RwVMEZE

### Bug Description

When dragging a grouped event with an RRULE, the new endDate is not disclosed of the lead event or any of the events.

When an event is dragged, the endDate is also changed, so the new value should be given.

In the above reduced test case, open the console to see the console.log output.

Even when I click an event with RRULE and monitor the hook `eventClick`, the clicked event does not show the event endDate, however there is always a different startDate for each recurring event.
A link to at least the first event should be present as well so that we can pull it's details.

EDIT: I also just found out that if the event in a RRULE can only have a duration of 1 hour, setting the endDate does nothing

**Comment by jplevene** [comment]
Even when I go to click an event with RRULE set hooked with:
`eventClick: function(calEvent){}`
The event does not have an endDate, however there is always a startDate for each event
A link to at least the first event should be present as well

**Comment by acerix** [comment]
Recurring events don't have `start`/`end`, you can set `duration` which will determine the end time of each instance:

https://codepen.io/acerix/pen/yLbjxBB?editors=1111

**Comment by jplevene** [comment]
> Recurring events don't have `start`/`end`, you can set `duration` which will determine the end time of each instance:
> 
> https://codepen.io/acerix/pen/yLbjxBB?editors=1111

This does not help as an event object does not contain the rrule or duration fields.  rrule are only write and not available to read.

`var event = coalendar.getEventById("event1")`

The above does not contain the "duration", "end" or "rrule".

This is an issue as after an event move, how am I to know what the duration is?

**Comment by acerix** [comment]
If you define a `duration` for the event, then the event instances will have an `end`, so you can get their duration with `start - end`.
