### ISSUE TITLE
all resource related events and hooks should include the resource object

### ISSUE THREAD

**Issue by markusdf** [fullcalendar/fullcalendar#6496]
### Checklist

Please mark these items with an [x]

  - [x] I've already searched through [existing tickets](https://fullcalendar.io/issues)
  - [x] Other people will find this feature useful

### Feature Description

all resource events and hooks should always include the resource object in the arguments.

Currently such hooks as:
resourceGroupLabelDidMount
resourceGroupLabelContent

only return the groupValue, which makes it difficult to override labels with meaningful content/formatting, or to set mouse overs with other content.

use scenario example:
a resource has a sortLabel, sortDescription
we would want the chart to group and sort by sortLabel, and on resourceGroupLabelDidMount, set the el.title to arg.resrouce.extendedProps.sortDescription

**Comment by acerix** [comment]
Resource groups can have multiple resources, so are you looking to access their list of resources?  You could use `getResources()`, filtering by the `groupValue`.

**Comment by markusdf** [comment]
Ah yes, that makes sense. The issue i was trying to resolve was having the group sorting field being different from the group sorting display field. Resolved, thank you sir.
