### ISSUE TITLE
nowIndicator position if device timezone is different from  fullcalendar timezone

### ISSUE THREAD

**Issue by ozplugin** [fullcalendar/fullcalendar#6497]
### Reduced Test Case

https://codepen.io/ozplugin/pen/gOWKZBQ

### Bug Description

If I set timeZone option "America/Anchorage" (for example) I expect to see the time in that timeZone. But the nowIndicator position shows the time of my computer (Europe/Moscow). 
If I set timeZone: "UTC" that works fine (only for this time zone)

### Screenshots

If the bug is visual, include a screenshot if possible.
If not, erase this section.

**Comment by acerix** [comment]
I believe this existing ticket captures this need:
https://github.com/fullcalendar/fullcalendar/issues/5753
↑
Please visit the above issue, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates.
