### ISSUE TITLE
Support for Luxon v2 in plugin

### ISSUE THREAD

**Issue by IagoLast** [fullcalendar/fullcalendar#6502]
### Checklist

Please mark these items with an [x]

  - [x] I've already searched through [existing tickets](https://fullcalendar.io/issues)
  - [x] Other people will find this feature useful

### Feature Description

Luxon just released the version 2 of the library. Some people realized this and [created a feature request ticket](https://github.com/fullcalendar/fullcalendar/issues/6454)

According to the [upgrade from 1x to 2x guide](https://github.com/fullcalendar/fullcalendar/issues/6454) we would need to update:

- [.fromObject](https://moment.github.io/luxon/#/upgrading?id=fromobject)
  - https://github.com/fullcalendar/fullcalendar/blob/master/packages/luxon/src/main.ts#L24
  - https://github.com/fullcalendar/fullcalendar/blob/master/packages/luxon/src/main.ts#L91 
 - [OS timezone is called `system` instead `local` but local still works](https://moment.github.io/luxon/#/upgrading?id=system-zone)

While the change itself is easy I think it is hard to manage the versioning because this requires the luxon peer dependency to be upgraded to V2.

I see several options:

1. Update luxon peer dependency to ^2.1.0 and release a new version of fullcalendar with this breaking change.
2. Create a new package luxon-plugin-v2 with this changeset so we don't need to release a  major fullcalendar version.

I've already got a fork and I'm happy to help with those changes but I would like the contributors opinion first. Thx for this amazing project 🚀

**Comment by Razi91** [comment]
Changes required:
in function toLuxonDuration:
```ts
  return LuxonDuration.fromObject(
    {  ...duration, },
    {  locale: dateEnv.locale.codes[0], }
  );
```
arrayToLuxon:
```ts
  return LuxonDateTime.fromObject(
    {
      locale,
      year: arr[0],
      month: arr[1] + 1, // convert 0-based to 1-based
      day: arr[2],
      hour: arr[3],
      minute: arr[4],
      second: arr[5],
      millisecond: arr[6],
    },
    {
      zone: timeZone,
    }
  );
```

I think it's all. Here is my adapter:
https://gist.github.com/Razi91/69bdf692228db8bb75b1852f0ac79d87
It seems to work, but I'm not sure if it should be done as separate plugin, or updated current.

**Comment by JoseLion** [comment]
In `arrayToLuxon(..)` the `locale` property should also go to the second argument. The function should look like this:
```ts
function arrayToLuxon(arr: number[], timeZone: string, locale?: string): LuxonDateTime {
  return LuxonDateTime.fromObject({
    year: arr[0],
    month: arr[1] + 1, // convert 0-based to 1-based
    day: arr[2],
    hour: arr[3],
    minute: arr[4],
    second: arr[5],
    millisecond: arr[6],
  }, {
    locale,
    zone: timeZone
})
}
```

I hope this helps! Luxon is an essential library and not being able to update it can cause some trouble. It'd be great if we could have any updates on this issue 🙂

**Comment by Gkleinereva** [comment]
Y'all may already know about this, but I believe interpreting named timezones broke with the new luxon version as well.  When I try to use it with the "timeZone" property set in my fullCalendar options, I get an "Invalid Unit Zone" error.  

Someone appears to already have made a simple reproduction here: https://codesandbox.io/s/qjxvg?file=/src/App.js

Please let me know if I can provide any further assistance, and as always - thanks for all your hard work!

**Comment by rmannjbs** [comment]
> Y'all may already know about this, but I believe interpreting named timezones broke with the new luxon version as well. When I try to use it with the "timeZone" property set in my fullCalendar options, I get an "Invalid Unit Zone" error.
> 
> Someone appears to already have made a simple reproduction here: https://codesandbox.io/s/qjxvg?file=/src/App.js
> 
> Please let me know if I can provide any further assistance, and as always - thanks for all your hard work!

Any update on this?   I'm seeing the exact same problem.   We have IANA time zones associated with our backend database and I can get them to work fine in Luxon, but the second I try to set <FullCalendar timezone="America/Phoenix" /> I get the same error from the linked sandbox above, invalid unit etc.

We need to be able to render the calendar for other time zones.  I suppose we'll have to use UTC Coercion or something because the luxon support in the documentation is broken.

**Comment by arshaw** [comment]
I have just released a new plugin that will solve this problem:
https://www.npmjs.com/package/@fullcalendar/luxon2

I plan on documenting this today. However, there's not much to document. Simply use this if you want Luxon 2 support.

**Comment by arshaw** [comment]
Alrighty,
blog post: https://fullcalendar.io/blog/2022/02/bootstrap-luxon-angular
release: https://github.com/fullcalendar/fullcalendar/releases/tag/v5.10.2
docs: https://fullcalendar.io/docs/luxon2
