### ISSUE TITLE
Non-overlap rendered as overlap in timeGridWeek and timeGridDay

### ISSUE THREAD

**Issue by Mark-Schmeiser** [fullcalendar/fullcalendar#6509]
### Reduced Test Case

[Testcase with timeGridWeek](https://codesandbox.io/s/fullcalendar-overlap-bug-12pbu).

- To see issue in `timeGridDay` change App.js L90 initialview accordingly
 
### Bug Description

The bug happens, if the following comes together:

- snapDuration of 5 minutes
- slotDuration of 15 minutes
- one schedule item A reaches from the last day 5 minutes into the next day
- another schedule item B starts when item A finishes
- the calendar renders it as an overlap, which is none
- this happens in these views `timeGridWeek` and `timeGridDay`

I expect the rendering to be not in an overlapping style.

Side note:
Changing the snapDuration and slotDuration both to 5 minutes results in rendering as expected. I added some notes in the [App.js](https://codesandbox.io/s/fullcalendar-overlap-bug-12pbu?file=/src/App.js) of the sandbox L104 to L107

### Screenshots

The code sandbox shows the issue nicely. Additionally I added the screenshots from our case to illustrate the issue.

![full-calendar-week-view](https://user-images.githubusercontent.com/8628659/129176797-c26a7d5c-7ab7-47e4-a2a2-c96f91be9f29.png)

![full-calendar-dayview](https://user-images.githubusercontent.com/8628659/129176773-4ad359ce-28ca-431f-9026-4cf86fa84509.png)

**Comment by acerix** [comment]
I made a reduced test case to check this: https://codepen.io/acerix/pen/wvdOZNK?editors=001

They show as overlapping because the first event is extended by the `eventMinHeight` setting, you can change that so they don't overlap:

https://codesandbox.io/s/fullcalendar-overlap-bug-forked-70ee3
