### ISSUE TITLE
RRule plugin using issue

### ISSUE THREAD

**Issue by m2broth** [fullcalendar/fullcalendar#6511]
Hi,

I use the latest version of FullCalendar (~5.9.0) and installed the latest RRule plugin version (~5.9.0).
When I'm trying to add the plugin to the Fullcalendar plugin list I get the next error:

TypeScript error in .../src/features/Events/components/Container.tsx(43,85):
No overload matches this call.
  Overload 1 of 2, '(props: CalendarOptions | Readonly<CalendarOptions>): FullCalendar', gave the following error.
    Type 'import(".../node_modules/@fullcalendar/rrule/node_modules/@fullcalendar/common/main").PluginDef' is not assignable to type 'import(".../node_modules/@fullcalendar/common/main").PluginDef'.
      Types of property 'reducers' are incompatible.
        Type 'ReducerFunc[]' is not assignable to type 'ReducerFunc[]'. Two different types with this name exist, but they are unrelated.
          Type 'ReducerFunc' is not assignable to type 'ReducerFunc'. Two different types with this name exist, but they are unrelated.
            Types of parameters 'action' and 'action' are incompatible.
              Type 'import(".../node_modules/@fullcalendar/common/main").Action | null' is not assignable to type 'import(".../node_modules/@fullcalendar/rrule/node_modules/@fullcalendar/common/main").Action | null'.
                Type '{ type: "SET_EVENT_DRAG"; state: EventInteractionState; }' is not assignable to type 'Action | null'.
                  Type '{ type: "SET_EVENT_DRAG"; state: import(".../node_modules/@fullcalendar/common/main").EventInteractionState; }' is not assignable to type '{ type: "SET_EVENT_DRAG"; state: import(".../node_modules/@fullcalendar/rrule/node_modules/@fullcalendar/common/main").EventInteractionState; }'.
                    The types of 'state.affectedEvents.defs' are incompatible between these types.
                      Type 'import(".../node_modules/@fullcalendar/common/main").EventDefHash' is not assignable to type 'import(".../node_modules/@fullcalendar/rrule/node_modules/@fullcalendar/common/main").EventDefHash'.
                        Index signatures are incompatible.
                          Type 'import(".../node_modules/@fullcalendar/common/main").EventDef' is not assignable to type 'import(".../node_modules/@fullcalendar/rrule/node_modules/@fullcalendar/common/main").EventDef'.
                            The types of 'ui.constraints' are incompatible between these types.
                              Type 'import(".../node_modules/@fullcalendar/common/main").Constraint[]' is not assignable to type 'import(".../node_modules/@fullcalendar/rrule/node_modules/@fullcalendar/common/main").Constraint[]'.
                                Type 'import(".../node_modules/@fullcalendar/common/main").Constraint' is not assignable to type 'import(".../node_modules/@fullcalendar/rrule/node_modules/@fullcalendar/common/main").Constraint'.
                                  Type 'EventStore' is not assignable to type 'Constraint'.
  Overload 2 of 2, '(props: CalendarOptions, context: any): FullCalendar', gave the following error.
    Type 'import(".../node_modules/@fullcalendar/rrule/node_modules/@fullcalendar/common/main").PluginDef' is not assignable to type 'import(".../node_modules/@fullcalendar/common/main").PluginDef'.  TS2769

    41 |                     <CalendarHeader ref={calendarRef}></CalendarHeader>
    42 |                     <FullCalendar
  > 43 |                         plugins={[dayGridPlugin, timeGridPlugin, interactionPlugin, rrulePlugin]}

Do you know how to solve the issue?

**Comment by Motoxpro** [comment]
Same here
