### ISSUE TITLE
Reduce space below event list

### ISSUE THREAD

**Issue by OnFolio** [fullcalendar/fullcalendar#6514]
### Reduced Test Case

https://jsfiddle.net/dxsfk534/

(See August 1st 2021)

### Bug Description

Adding multiple events to a day in calendar view results in a large amount of empty space below the events. 

I'm expecting some space, but it seems weird that it leaves approx. the same amount as an empty day cell.

### Screenshots

![Screenshot 2021-08-19 112035](https://user-images.githubusercontent.com/82199439/130034210-9aff2bbd-f892-4af3-92ae-09a527e9db55.png)

**Comment by acerix** [comment]
I believe this existing ticket captures this need:
https://github.com/fullcalendar/fullcalendar/issues/5762
↑
Please visit the above issue, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates.
