### ISSUE TITLE
Timezone change is not working

### ISSUE THREAD

**Issue by atopdev** [fullcalendar/fullcalendar#6518]
### Reduced Test Case

https://fullcalendar.io/docs/timeZone-demo

### Bug Description

What do you expect to happen?
When changing the timezone, the time of each event should be updated.

What happens instead?
Even though changing the timezone, UTC and local are working but other timezone options are not working.
Time is not updated.

Not sure cache issue or original full-calendar issue.

**Comment by jaredgibb** [comment]
HI. 

As of Feb 1st this same issue is happening in the demo and the same in my personal project. 

In the demo, i altered the dropdown to have both 
`America/Detroit` and `America/Los_Angeles` as available options. 

Upon changing the dropdown to either, no events shift on the calendar as expected. 

https://www.loom.com/share/71e23b4b46f04d62946f51ce0b6f3852

**Comment by arshaw** [comment]
https://fullcalendar.io/docs/timeZone-demo was broken on the fullcalendar.io website. It's not fixed. Was a bug with the website.

Additionally, [v6.1.6](https://github.com/fullcalendar/fullcalendar/releases/tag/v6.1.6) offers some bugfixes for timezone changing.
