### ISSUE TITLE
Version 3.10.2 published npm has an npm-shrinkwrap.json which is breaking consumer webpack build

### ISSUE THREAD

**Issue by kevinfairclough** [fullcalendar/fullcalendar#6531]
Is there a reason that npm-shrinkwrap.json is included in the published 3.10.2 package ?

### Reduced Test Case

not reproducible with a link

npm pack fullcalendar@3.10.2 includes file npm-shrinkwrap.json causing pain.
npm pack fullcalendar@3.10.1 doesnt have the npm-shrinkwrap.json and webpack works.

### Bug Description

npm install fullcalendar@3.10.2

What do you expect to happen?

installs fullcalendar at correct version without additional node_modules

What happens instead?
installs fullcalendar at correct version with extra node_modules sub-folder which is causing issues when using module with webpack.  If I delete the npm-shrinkwrap.json and the sub node_modules folder then my webpack build works and all is good.

3.10.1 doesnt have the npm-shrinkwrap.json and works fine but this doesn't work with jquery@3.6.0

Thanks in advance?

**Comment by acerix** [comment]
Please post a [runnable, stripped-down demonstration of the bug](http://fullcalendar.io/wiki/Reduced-Test-Cases/) or steps to reproduce the issue. Would really appreciate it because the time saved reproducing will be time spent fixing.
