### ISSUE TITLE
Dragable event are being teleported form their original place when creating calendar inside a modal

### ISSUE THREAD

**Issue by Axel-AMGHAR** [fullcalendar/fullcalendar#6540]
Hello, 

### Reduced Test Case

You must paste a link to a [REDUCED TEST CASE](https://fullcalendar.io/reduced-test-cases).
If you do not, this issue will automatically be closed.
To prevent this, include the text "not reproducible with a link" (assuming it's true).

I didn't suceed to reproduce the bug on codepen

### Bug Description

Describe how to recreate the bug.
What do you expect to happen?
What happens instead?

- Create a bootstrap modal
- add full calendar in it 

pass these options in the caledendar object: 
 {
 plugins: [timeGridPlugin, interactionPlugin],
  initialView: 'timeGridWeek',
  editable:true,
  events: [/*... some events with hours */
}

move them outside of the calender. And  you will see that the event is beeing teleported

### Screenshots

If the bug is visual, include a screenshot if possible.
If not, erase this section.

![image](https://user-images.githubusercontent.com/37699064/132481966-6dc899cc-9c13-439a-8c0a-77a6e25cf37f.png)
 You can see on the picture that the event is not at the same place than my cursor

Thanks for the replys

**Comment by acerix** [comment]
Would you be able to post a [runnable, stripped-down demonstration of the bug](http://fullcalendar.io/wiki/Reduced-Test-Cases/)? Would really appreciate it because the time saved reproducing will be time spent fixing.
