### ISSUE TITLE
businessHours that ends at midnight disable all days

### ISSUE THREAD

**Issue by anthonyamar** [fullcalendar/fullcalendar#6542]
### Reduced Test Case

[REDUCED TEST CASE](https://jsfiddle.net/fd0r5op7/7/).

### Bug Description

**Describe how to recreate the bug:**
Assign an `openingHours` variable like this:
```javascript
var openingHours = {
   startTime: "10:00:00", // could work with any hours from 01:00:00 to 23:59:59
    endTime: "00:00:00" // end at "00:00:00" or don't put any endTime at all
  }
```
 Pass `openingHours` to `businessHours` option.

**What do you expect to happen?:**
It should enable every day from 10am to midnight and disable the rest.

**What happens instead?:**
Days are entirely disabled.
This produce a similar bug if `openingHours` is passed to `eventConstraint` and `selectConstraint`, preventing user from moving, dragging or creating an event on the calendar.

### Screenshots

![Screenshot 2021-09-12 at 23 35 18](https://user-images.githubusercontent.com/29660796/133003518-7ce044b0-6228-431a-a219-ec648744a241.png)

**Comment by acerix** [comment]
The end time needs to come after the start, you can set it to `24:00:00` for that.

https://jsfiddle.net/e860wx1r/

**Comment by anthonyamar** [comment]
Ok, make sense! Thanks for your help!
