### ISSUE TITLE
nowIndicator rounded down to hour when using hourly slotDuration

### ISSUE THREAD

**Issue by warrenspence** [fullcalendar/fullcalendar#6544]
### Reduced Test Case
https://codepen.io/warrenspence/pen/dyRzzZK?editors=001

### Bug Description
The red line shown by `nowIndicator` is not showing at the current time when a `slotDuration` of 1 hour (or greater) is used, instead it is being shown on the previous hour.

The codepen linked above is a single line edit of the https://fullcalendar.io/docs/timeline-nowIndicator-demo page, the only addition is `slotDuration: '01:00'`.

The expected result is that when using 1 hour slot durations the red nowIndicator line still shows at the current time.

### Screenshots
This is the result when using a `slotDuration` of `00:30` and a `now` of `2018-02-13T09:25:00`:
![30](https://user-images.githubusercontent.com/15135117/133176266-f22e7710-ce7c-4956-8d30-5814976b90a0.png)

This is the result when using a `slotDuration` of `01:00` and a `now` of `2018-02-13T09:25:00`:
![60](https://user-images.githubusercontent.com/15135117/133176268-2b6baba0-df1f-46f2-95f5-e38257abd417.png)

**Comment by acerix** [comment]
I believe this existing ticket captures this need:
https://github.com/fullcalendar/fullcalendar/issues/6175
↑
Please visit the above issue, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates.
