### ISSUE TITLE
prev/next-Buttons break in custom views when dateIncrement is 1 day

### ISSUE THREAD

**Issue by IndyHaine** [fullcalendar/fullcalendar#6545]
### Reduced Test Case

https://codepen.io/indyhaine/pen/rNwzPLJ
Please go to this codepen and use the "Next"-Button twice in a row and see how it behaves on the first click (correctly) and then on the second (wrong & negative date incrementation).

### Bug Description

In a custom view with a dateIncrement of one day, like the one in the codepen above, use the "next" button twice in a row. On the first click, the calendar behaves correctly and all dates will be shifted by one day forward. On the second click, it will go two days backwards.
Expected behaviour: The second click on "Next" should do the same as the first, and move the dates in the calendar forward by one, as specified by the dateIncrement value of the view.
The prev-Button seems to display similar problematic behaviour.

### Screenshots

The bug is not visual, but rather easy to replicate with the codepen above.

### Please Note:

I reported this bug before, for Version 3 of FullCalendar, but back then, it only occurred for custom views that were exactly 7 days long. Now, it seems to be occurring for any duration, hence my workaround by just making the view one day larger, does not work anymore. Here is the previous bug report: https://github.com/fullcalendar/fullcalendar/issues/4386
I also saw similar sounding bug reports ( https://github.com/fullcalendar/fullcalendar/issues/5319 ) that are said to have been fixed in 5.8, however this bug is still in 5.9.

Thank you in advance for your help!

**Comment by acerix** [comment]
It seems like the same bug as in your previous report so I don't think we need another issue, you can add the details to the existing issue. Or am I missing something?

**Comment by IndyHaine** [comment]
Hello!
It seems to be affecting all custom views with any visible range now, and it's been two versions; that's why I thought it was different. I can add the information to the old one though!
