### ISSUE TITLE
Identify which Google Calendar event is coming from

### ISSUE THREAD

**Issue by Flashbackvideoman** [fullcalendar/fullcalendar#6548]
### Checklist

Please mark these items with an [x]

  - [x] I've already searched through [existing tickets](https://fullcalendar.io/issues)
  - [x] Other people will find this feature useful

### Feature Description
When using multiple Google Calendars, it is necessary to know to whom the event belongs to.
Searching over the returned Event Object, I see no way of doing this.

**Comment by acerix** [comment]
You can set a unique `id` on the event sources and access it with `event.source.id`.

**Comment by Flashbackvideoman** [comment]
Yes, if I am initiating an event, I can do that.  However, just reading in existing events from Google Calendar that was NOT initiated by my program, I do not see anything that indicates which calendar the event is coming from.
So, you are correct for events I create, but not, I think, for events created in Google Calendar.(?)

**Comment by Flashbackvideoman** [comment]
Oh, and great plugin!  Thank you.

**Comment by acerix** [comment]
I'm not sure what you mean, could you provide an example? Here's how to get the source when clicking an event:

https://codepen.io/acerix/pen/wvePLGo?editors=0011
