### ISSUE TITLE
i found a bug in fullcalendar Timeline ,when set eventMaxStack.i have a codepen is can open,help me please. 

### ISSUE THREAD

**Issue by gipal** [fullcalendar/fullcalendar#6550]
### Reduced Test Case

[REDUCED TEST CASE](https://codepen.io/gipal-the-animator/pen/PojEvQL)

### Bug Description

eventMaxStack: 2,
in javascript,you can open this or close this.the bug will show when set eventMaxStack: 2.
if i set eventMaxStack: 2,the evnet block 1.1.5 will overlay event block 1.1.1
if i not set eventMaxStack:2, is normal.

### Screenshots

![2](https://user-images.githubusercontent.com/29369046/133736755-b923d1c7-c592-4a49-b7ba-03982671e462.jpg)
![3](https://user-images.githubusercontent.com/29369046/133736760-080a8482-3719-47b5-8815-51152ee61b9f.jpg)

**Comment by acerix** [comment]
I believe this existing ticket captures this need:
https://github.com/fullcalendar/fullcalendar/issues/6543
↑
Please visit the above issue, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates.
