### ISSUE TITLE
event ending at next day with time under 9:00 is rendered as one day event

### ISSUE THREAD

**Issue by wikin** [fullcalendar/fullcalendar#6556]
### Reduced Test Case
https://codepen.io/peterka/pen/jOwpmje

### Bug Description
- version 3.10.2
- event ending at next day with time under 9:00 is rendered as one day event

### Screenshots
![image](https://user-images.githubusercontent.com/1352228/134397621-b7f76cf5-2c1c-4dfd-b9b6-8c829b8c6eed.png)

**Comment by acerix** [comment]
You can change that with [nextDayThreshold](https://fullcalendar.io/docs/v3/nextDayThreshold)
