### ISSUE TITLE
dragging events out of the calendar 

### ISSUE THREAD

**Issue by djixadin** [fullcalendar/fullcalendar#6559]
### Checklist

Please mark these items with an [x]

  - [x] I've already searched through [existing tickets](https://fullcalendar.io/issues)
  - [x] Other people will find this feature useful

### Feature Description

provide a new event that is emitted once a calendar event is dropped on a div with a certain class that will be able to handle dropped events. i looked all over the documentation and didn't find anything like that. there is tons of examples for dragging to the calendar but not out of it . maybe i'm missing something , any idea would help. thanks you

```eventDragStop``` doesn't really provide any helpful data and is triggered only when events return to the calendar

**Comment by acerix** [comment]
I believe this existing ticket captures this need:
https://github.com/fullcalendar/fullcalendar/issues/3140
↑
Please visit the above issue, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates.
