### ISSUE TITLE
Add ability to retrieve current events from within the events loading callback for improved a11y

### ISSUE THREAD

**Issue by bkosborne** [fullcalendar/fullcalendar#6562]
### Checklist

Please mark these items with an [x]

  - [x] I've already searched through [existing tickets](https://fullcalendar.io/issues)
  - [x] Other people will find this feature useful

### Feature Description

I'm unable to get the total number of events being displayed in the loading callback. I tried using `calendar.getEvents()` but this doesn't seem to return the updated events data from the loading process (it's the previous data).

My specific use case:

- I load events via a [JSON feed source](https://fullcalendar.io/docs/events-json-feed), which invokes the [loading callback](https://fullcalendar.io/docs/loading) when the events are retrieved.
- I want to announce to screen readers that loading is completed and there are X events being displayed.

For now I can only announce the month that's being displayed via `calendar.currentData.viewTitle`, but cannot find a way to get the events currently being displayed so I can announce the count.

**Comment by acerix** [comment]
You can use [eventSourceSuccess](https://fullcalendar.io/docs/eventSourceSuccess) to know when the events are loaded and count them.

**Comment by bkosborne** [comment]
Thanks, that works!
