### ISSUE TITLE
slotLabelFormat not accepting Array of Strings?

### ISSUE THREAD

**Issue by MichaelHeydon** [fullcalendar/fullcalendar#6567]
### Reduced Test Case

https://codepen.io/MichaelHeyDonny/pen/RwgEgvR?editors=0010

### Bug Description

I'm able to use `dayjs` as expected to format when returning single string dates. However it appears `days` and `hours` is being combined in `slotLabelFormat` within `resourceTimelineWeek` rather than displaying in multiple tiers of header rows as described in: https://fullcalendar.io/docs/slotLabelFormat.

Hopefully something isn't amiss with my syntax! 

### Screenshots

![screenshot-codepen io-2021 09 28-15_49_43](https://user-images.githubusercontent.com/74880856/135030764-4c568bc0-78e9-45b8-9791-79a5ec8be031.png)

**Comment by acerix** [comment]
For multiple rows, slotLabelFormat needs to be set to an array, then each row can be set as a function: 

https://codepen.io/acerix/pen/yLXGrqW?editors=0010

**Comment by MichaelHeydon** [comment]
Was my syntax, apologies. Thanks @acerix.
