### ISSUE TITLE
BUG: Programatically changing timeZone does not update nowIndicator

### ISSUE THREAD

**Issue by neil-hardlight** [fullcalendar/fullcalendar#6572]
### Reduced Test Case

[REDUCED TEST CASE](https://codepen.io/neil-hardlight/pen/mdwoEMZ?editors=1010).

### Bug Description

Dynamically changing the timeZone and refetching events correctly repositions the events on the calendar, but the nowIndicator remains in the original timeZone.

### Screenshots

![fullcalendar](https://user-images.githubusercontent.com/87178174/135429786-5b96497b-4623-4d16-8922-b5c2c349f371.png)

**Comment by acerix** [comment]
I believe this existing ticket captures this need:
https://github.com/fullcalendar/fullcalendar/issues/5753
↑
Please visit the above issue, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates.
