### ISSUE TITLE
Using dayMaxEventRows with custom eventOrder can cause endless looping/freezing

### ISSUE THREAD

**Issue by erjavec** [fullcalendar/fullcalendar#6573]
### Reduced Test Case

https://codepen.io/rjo0601/pen/MWoxbgd?editors=001

### Bug Description

Combination of events, specific eventOrder and dayMaxEventRows causes endless looping. 
see test case for specific settings

### Screenshots
<img width="1669" alt="Screenshot 2021-09-30 at 12 58 46" src="https://user-images.githubusercontent.com/4168449/135443293-eaa99e20-41cd-4bdb-96d1-119579349029.png">

**Comment by jasonsavard** [comment]
My users are also experiencing a complete freeze when they hit the next month button.
I have these properties set amongst many others:

dayMaxEventRows: true
eventOrder: ["-allDay", "start", "-duration", function(a, b) ...

**Comment by jasonsavard** [comment]
It seems to reproduce the issue with the codepen above from @erjavec you must now click the previous month button to go to September. I guess this is related to the fact that today we are now in the next month of October.

**Comment by jasonsavard** [comment]
I found the infinite loop causing the freezing and just added this dirty hack to break out if it loops more than 5 times. Note I deminified and uninlined this snippet of code to add these new lines.

```
    function b$1() {
        var cnt = 0;
        for (var n; b$1.__r = u.length; ) {
            if (cnt++ > 5) {
                return;
            }
```
