### ISSUE TITLE
Trigger Callbacks from selectMirror placeholder event

### ISSUE THREAD

**Issue by EthanHaid** [fullcalendar/fullcalendar#6574]
### Checklist

Please mark these items with an [x]

  - [x] I've already searched through [existing tickets](https://fullcalendar.io/issues)
  - [x] Other people will find this feature useful

### Feature Description

I would like to trigger callbacks such as eventAllow and eventDragStart when making an event selection with [selectMirror](https://fullcalendar.io/docs/selectMirror) set to true. This will allow me to provide custom styling to the placeholder event while dragging and resizing it.

Thank you :)

**Comment by acerix** [comment]
There is already `selectAllow` for where selection is allowed, so are you looking for `selectDragStart`/Stop?  

The event mirrors can be styled like regular events, ie. CSS and `eventClassNames` or `eventContent` to change the HTML.

**Comment by acerix** [comment]
`eventContent` is best for that, eg.: https://codepen.io/acerix/pen/LYLwMLQ?editors=001

**Comment by EthanHaid** [comment]
I see, that will work. Thanks for your help!
