### ISSUE TITLE
Include HTML select dropdown within Event

### ISSUE THREAD

**Issue by stevewillson** [fullcalendar/fullcalendar#6580]
### Reduced Test Case

https://codepen.io/stevewillson/pen/eYRwMoz

### Bug Description

Using FullCalendar 5.9.0, I attempt to include an HTML `select` dropdown within an event using the `eventContent` hook. I am unable to use a mouse to select the dropdown box within the event. I can use the Tab key to put focus on the dropdown and the arrow keys to change the selected option.

**Comment by akaspick** [comment]
@stevewillson Did you ever figure out a solution to this?  I've been stuck on this for over a year.  I've even tried adding my controls to a tooltip control when I hover over my event and my select field doesn't work there either.

**Comment by stevewillson** [comment]
> @stevewillson Did you ever figure out a solution to this? I've been stuck on this for over two years. I've even tried adding my controls to a tooltip control when I hover over my event and my select field doesn't work there either.

Hi @akaspick, I have a (non-ideal) workaround, I display a tooltip to tell the user to hold CTRL to select a dropdown menu option. Demo available at: https://cmhcal.com/ and code is at: https://gitlab.com/cmhcal/cmhcal/-/blob/master/src/components/ResourceCalendar/ResourceCalendar.js

**Comment by akaspick** [comment]
@stevewillson Thanks for the update. I tried it in Firefox, but no go.  I tried putting my controls in a tooltip, but fullcalendar still hijacked the clicks.  I ended up opening a dialog that contained the controls and that ended up working for me in the end.  Not my preferred solution, but at least I have something that works now.
