### ISSUE TITLE
Support for Blazor web Assembly 

### ISSUE THREAD

**Issue by AliAUZ** [fullcalendar/fullcalendar#6589]
### Checklist

Please mark these items with an [x]

  - [*] I've already searched through [[5865]](https://github.com/fullcalendar/fullcalendar/issues/5865)
  - [ ] Other people will find this feature useful

### Feature Description

I tried to use FullCalendar in my Blazor Web Assembly, I couldn't find any sample or example for it.
So is it compatible with blazor? I can see on your website there is some sample for Angular, React, and ...
Could you please add a sample for it?
Thanks

**Comment by acerix** [comment]
I believe this existing ticket captures this need:
https://github.com/fullcalendar/fullcalendar/issues/5865
↑
Please visit the above issue, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates.
