### ISSUE TITLE
Display event multiple days not connectly

### ISSUE THREAD

**Issue by quangnv13** [fullcalendar/fullcalendar#6595]
### Reduced Test Case

https://codesandbox.io/s/github/fullcalendar/fullcalendar-example-projects/tree/master/angular?file=/src/app/app.component.ts

### Bug Description

I use fullcalendar with angular. Everything work perfectly but i see multiple days event not display correctly in fullcalendar view. I add an event with  start: '2021-10-14' and end: '2021-10-15' but this event display only in day cell '2021-10-14'. But if i add another event with  start: '2021-10-14' and end: '2021-10-16' it's display on two day cell '2021-10-14','2021-10-15' and not display on end: '2021-10-16'.

### Screenshots

Link demo: Click on add event to see the issue.
https://stackblitz.com/edit/fullcalendar-angular-demo-bwdnwq

**Comment by acerix** [comment]
The `end` date is _exclusive_, so it should be set to the day after the last day of the event.
