### ISSUE TITLE
Missing zip package release for v3.10.3

### ISSUE THREAD

**Issue by cedk** [fullcalendar/fullcalendar#6601]
### Reduced Test Case

"not reproducible with a link".

### Bug Description

The archive released as v3.10.3 is missing the dist folder so installation via bower does not install them.

**Comment by arshaw** [comment]
I've ensured the zip is available:
https://github.com/fullcalendar/fullcalendar/releases/download/v3.10.3/fullcalendar-3.10.3.zip

Please lmk if this doesn't resolve the issue.

**Comment by cedk** [comment]
It does not solve the problem. bower is downloading https://github.com/fullcalendar/fullcalendar/archive/v3.10.3.tar.gz which still does not contain the usual dist folder.

**Comment by ketan-cleverharvey** [comment]
+More link (event limit) not working for agenda in vue
