### ISSUE TITLE
Timed event from previous day causes incorrect +more count dayMaxEventRows based on calendar width and event order

### ISSUE THREAD

**Issue by YahyaDeeb** [fullcalendar/fullcalendar#6608]
### Reduced Test Case

https://codepen.io/YDeeb/pen/wvqeZPe

### Bug Description

Hello, I'm facing an issue when using 'dayMaxEventRows: true', sometimes the '+more' label and its popover don't show the correct events count and render.

Considering the case of the events in the reduced test case, the fullcalendar container width is 600px, on Oct 1st/2nd cell for example, the '+more' label is showing +1 and when clicking on it you'll notice that the popover is showing one event only.
The correct behavior should be +2 and popover should show 2 events.

Another thing is that when you further reduce the width (to 400px for example), you'll notice that the '+more' label/popover is behaving correctly.

Thanks in advance.

### Screenshots

![400](https://user-images.githubusercontent.com/93345836/139322354-60726d8b-8bbb-4664-9e62-ddfdb0a7911a.PNG)
![600](https://user-images.githubusercontent.com/93345836/139322359-a80efb7e-cd74-43d2-80d2-7592c675f13c.PNG)

**Comment by karamantonio** [comment]
we are still waiting a fix for the above issue.
any visibility about when it will be fixed ?

**Comment by Zulgrib** [comment]
This is rather critical for a calendar to have proper chronological events.

**Comment by mhazan01** [comment]
is this being worked on or we should give up on a fix ? the impact on the calendar app is making the tool usesless

**Comment by anahitsargsyan169** [comment]
any updates? this is critical for usage

**Comment by arshaw** [comment]
Fixed in [v6.1.11](https://github.com/fullcalendar/fullcalendar/releases/tag/v6.1.11)

Updated repro:
https://codepen.io/arshaw/pen/jOJRxvE
