### ISSUE TITLE
Cannot read file when doing yarn build

### ISSUE THREAD

**Issue by espen** [fullcalendar/fullcalendar#6611]
`yarn build` gives this:
```
[2:14:48 PM] Updating output timestamps of project './src/fullcalendar/packages/bundle/tsconfig.json'...
error TS5083: Cannot read file './src/fullcalendar/packages-premium/__tests__/tsconfig.json'.
error TS5083: Cannot read file './src/fullcalendar/packages-premium/bundle/tsconfig.json'.
```

not reproducible with a link

**Comment by acerix** [comment]
Do you mean you get that error following these instructions?

https://github.com/fullcalendar/fullcalendar/blob/master/CONTRIBUTING.md#getting-set-up

It builds for me without error, you may need to reinit the  project.
