### ISSUE TITLE
3.10.3+ demands exactly node version 11

### ISSUE THREAD

**Issue by SimmeNilsson** [fullcalendar/fullcalendar#6612]
### Bug Description

Fullcalendar 3.10.3 and 3.10.4 demands node major version 11.
No older or newer major versions allowed.
https://github.com/fullcalendar/fullcalendar/commit/9f3f62610a1d731cb584ea599186e07ff5da4a6c
`"engines": {
    "node": "^11.0.0"
}`
https://docs.npmjs.com/about-semantic-versioning#using-semantic-versioning-to-specify-update-types-your-package-can-accept

Was this the intention or did you mean 11 or newer major versions?
Like
`"engines": {
    "node": ">=11.0.0"
 }`
https://docs.npmjs.com/cli/v7/configuring-npm/package-json#engines

Right now we are stuck on 3.10.2 because we've got newer node versions throughout our environments.

**Comment by arshaw** [comment]
This should be fixed. Please post if there are continued problems.

**Comment by arshaw** [comment]
You must use the new release: v3.10.5

**Comment by SimmeNilsson** [comment]
It works. Thank you!
