### ISSUE TITLE
Now indicator not specific enough when starting with WeekView in Resource Timeline

### ISSUE THREAD

**Issue by LennartMart** [fullcalendar/fullcalendar#6626]
### Reduced Test Case

https://codepen.io/Bensjo/pen/OJjQKja

### Bug Description

Hi, I have an issue with the resourceTimeline. The now indicator in _dayView_ is less specific when the initial view is _weekView_ . See CodePen: I've set now on 2021-02-06. Change _initialView_ to _dayView_: the now indicator is more specific in the dayView. 

### Screenshots

When initialView is WeekView
![image](https://user-images.githubusercontent.com/1591933/140550759-06bde929-5e12-4e58-a28a-9af844e6ac79.png)

InitialView = DayView
![image](https://user-images.githubusercontent.com/1591933/140550789-036c00ca-ec44-4abd-995d-101f3d53ea51.png)

**Comment by acerix** [comment]
I believe this existing ticket captures this need:
https://github.com/fullcalendar/fullcalendar/issues/6175
↑
Please visit the above issue, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates.
