### ISSUE TITLE
The datesSet callback receives wrong dates

### ISSUE THREAD

**Issue by TigorC** [fullcalendar/fullcalendar#6642]
### Reduced Test Case

https://fullcalendar.io/demos

### Bug Description

The `datesSet` callback receives the wrong dates.
**Steps to reproduce**:
1. Open https://fullcalendar.io/demos
2. Open the browser's dev tools and switch to the network tab.
3. Click the next button.

**Actual result**: 
You'll see a request:
https://fullcalendar.io/demo-events.json?overload-day&start=2021-11-28T00:00:00Z&end=2022-01-09T00:00:00Z&timeZone=UTC
start date == 2021-11-28T00:00:00Z
end date == 2022-01-09T00:00:00Z

**Expected result**: The start date should be 2021-10-28T00:00:00Z

### Screenshot
![fullcalendar](https://user-images.githubusercontent.com/1096253/142423078-bbbfd28e-4a80-40b5-9a3b-cfb4818401de.png)
s

**Comment by acerix** [comment]
The date range in the URL is the same as is showing in the calendar, why are you expecting 2021-10-28 as the first date?

**Comment by TigorC** [comment]
Oh, I think I was wrong. Sorry, I'm closing the issues
