### ISSUE TITLE
groupId property converts null to String value in React.js

### ISSUE THREAD

**Issue by jones-tyler** [fullcalendar/fullcalendar#6647]
### Reduced Test Case

 [codesandbox](https://codesandbox.io/s/boring-snow-u2eko?file=/src/event-utils.js).

### Bug Description

Describe how to recreate the bug.
 - set groupId to null in any event
 
What do you expect to happen?
 - setting groupId to null should not group events together by the string "null"
 
What happens instead?
 - set multiple events groupId to null and they will be grouped together on drag and resize changes

Workaround
 - set groupId to "" (empty string)
 - however, this removes the groupId property from the event object which is not desirable in my case

**Comment by acerix** [comment]
The `groupId` setting only accept a string, so `null` it is converted to a string and the empty string removes the group.  If you are looking to remove one event from a group there is an issue regarding that:

https://github.com/fullcalendar/fullcalendar/issues/5995
