### ISSUE TITLE
Can not fully localize fullcalendar on Chrome related browsers

### ISSUE THREAD

**Issue by dima2306** [fullcalendar/fullcalendar#6653]
### Reduced Test Case
From docs: Dynamically switch between locales
https://codepen.io/pen/?editors=001

### Bug Description
Switch language selector to `ka` and you will see that month and weekdays are not translated. This is the bug of chromium, which doesn't support this locale, however, firefox displays very well.

I've read docs about the locale section multiple times. So to fix my issue I included moment.js adapter and with `titleFormat: 'MMMM YYYY'` month is translated but this is not the case for weekdays, they're still in English. How can I override weekdays localization?

I've added `weekText: 'ddd',` ('ddd' from moment.js docs to show short weekdays) but it's not translated.

Why is it so hard to override some props of the library? I really like it, but customizability isn't as expected. At least for me.

So, how can I translate weekdays in my case?

**Comment by acerix** [comment]
I believe this existing ticket captures this need:
https://github.com/fullcalendar/fullcalendar/issues/5683
↑
Please visit the above issue, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates.

You could try a formatting plugin for now:

https://fullcalendar.io/docs/date-formatting#formatting-strings
