### ISSUE TITLE
Resource Ordering bug

### ISSUE THREAD

**Issue by ZoreAnkit** [fullcalendar/fullcalendar#6658]
### Reduced Test Case

 [REDUCED TEST [CASE].](https://codepen.io/ZoreAnkit/pen/xxXGvzL?editors=0010)

### Bug Description

Resource ordering seems to have bug. Please check test case. To summarize what's in test case the ordering is suppose to be group 21, group 10, group 4 but its showing group 4 at top followed by group 21 and than group 10. I assume resource ordering is only considering 1st value of given data. 

Following is the code :

`resourceOrder: '-group,order',
    resourceGroupField: 'group',`
`resources: [
      {
        id: 'a1',
        order: 4,
        group: '10',
        title: 'A1'
      },
      {
        id: 'a2',
        order: 3,
        group: '21',
        title: 'A2'
      },
      {
        id: 'b1',
        order: 2,
        group: '4',
        title: 'B1'
      },
      {
        id: 'b2',
        order: 1,
        group: '4',
        title: 'B2'
      }
    ]`

### Screenshots

![screenshot-codepen io-2021 12 03-19_19_22](https://user-images.githubusercontent.com/46300882/144614608-29d0a7d1-317f-48d1-8367-1a4ebe779a93.png)

**Comment by acerix** [comment]
Since your `group` settings are strings, they get sorted in alphabetic order, you can instead use numbers for numeric order:

https://codepen.io/acerix/pen/LYzNemR?editors=0010
