### ISSUE TITLE
TimeZone Change does not affect now Indicator

### ISSUE THREAD

**Issue by AntonLugtenburg** [fullcalendar/fullcalendar#6662]
not reproducible with a link

### Bug Description
I'm using the latest version of the Vue Fullcalendar. When calling:

`this.$refs.calendar.getApi().setOption('timeZone', 'anyTimeZone')`

...everything changes to selected Timezone, but not the now inidcator. It remains in the old timezone

**Comment by acerix** [comment]
I believe this existing ticket captures this need:
https://github.com/fullcalendar/fullcalendar/issues/5753
↑
Please visit the above issue, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates.
