### ISSUE TITLE
busonesshours requires 0 for sunday even if weekNumberCalculation ISO is set

### ISSUE THREAD

**Issue by dariovinci** [fullcalendar/fullcalendar#6663]
### Reduced Test Case

https://codepen.io/dariovinci/pen/QWqGwxO

### Bug Description

Hello guys i'm not sure if this is a bug or not but it took 1 hour to figure it out so i opened an issue to be sure it's an expected behavior. I use:

`moment(userAvailable.date).isoWeekday()`

to get the ISO number of the day. So if the date day is sunday moment returns 7

Then i create the businessHours object like this:

`businessHours: {
      daysOfWeek: [ 7 ], 
      startTime: '10:00',
      endTime: '18:00', 
  },`

but it doesn't work because businessHours needs 0 for sunday but i think it should also accept 7 if i set

`weekNumberCalculation: 'ISO`

**Comment by acerix** [comment]
The `daysOfWeek` setting is defined as zero-based with Sunday being zero, you can do `isoWeekday % 7` to convert it.
