### ISSUE TITLE
in vue2 example ,when set validRange on dayGridMonth view ,day cell height is not equal

### ISSUE THREAD

**Issue by yaya5508190** [fullcalendar/fullcalendar#6666]
### Reduced Test Case
https://codesandbox.io/s/late-brook-b7lzl
### Bug Description
when set validRange dayGridMonth view ,day cell height is not equal
### Screenshots
![image](https://user-images.githubusercontent.com/5077987/146161654-4bb52875-8424-4d39-87d8-3235521bd870.png)

**Comment by yaya5508190** [comment]
I wirte this css can let it equle
`.fc-daygrid-day-frame {
  position: relative;
  min-height: 100px;
}`

**Comment by acerix** [comment]
I believe this existing ticket captures this need:
https://github.com/fullcalendar/fullcalendar/issues/5762
↑
Please visit the above issue, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates.
