### ISSUE TITLE
Angular: ChunkLoadError with Angular 13.1 (related to importing css files)

### ISSUE THREAD

**Issue by brian-goo** [fullcalendar/fullcalendar#6667]
### Checklist

Please mark these items with an [x]

  - [x] I've already searched through [existing tickets](https://fullcalendar.io/issues)
  - [x] Other people will find this feature useful

### Feature Description

After updating to Angular 13.1, ChunkLoadError occurred when loading some modules.
https://github.com/angular/angular-cli/issues/22358

It seems that this is caused by the fact that fullcalendar imports css files as if they were ECMA modules.
https://github.com/angular/angular-cli/issues/22358#issuecomment-993558236

It would be grateful if the dependency on Webpack specific features would be removed as this would break if another bundler is used.

**Comment by acerix** [comment]
Sorry I missed this earlier. If there is a bug, please include a [runnable, stripped-down demonstration](http://fullcalendar.io/wiki/Reduced-Test-Cases/)? Would really appreciate it because the time saved reproducing will be time spent fixing.
