### ISSUE TITLE
The website cannot be accessed from China

### ISSUE THREAD

**Issue by makeryi** [fullcalendar/fullcalendar#6669]
### Reduced Test Case

https://fullcalendar.io/

### Bug Description

The official website cannot be accessed：https://fullcalendar.io/

### Screenshots

<img width="1141" alt="CleanShot 2021-12-16 at 10 27 48@2x" src="https://user-images.githubusercontent.com/46524124/146296772-607f3e83-0b23-4650-ab70-83fe869923f9.png">

**Comment by by12291216** [comment]
墙外用户不影响 只有国内的网打不开 翻墙就打开了

**Comment by makeryi** [comment]
> 墙外用户不影响 只有国内的网打不开 翻墙就打开了

有翻墙的，但还是不行，可能是我这边网络的问题

**Comment by acerix** [comment]
I don't see any problem with the website, what is the IP address if you ping the domain name `ping fullcalendar.io`?

**Comment by by12291216** [comment]
> I don't see any problem with the website, what is the IP address if you ping the domain name `ping fullcalendar.io`?

well.it seems its just effect users from China...

**Comment by makeryi** [comment]
> I don't see any problem with the website, what is the IP address if you ping the domain name `ping fullcalendar.io`?

108.59.4.161

**Comment by zhouzongren** [comment]
Same problem. It seems 108.59.4.161 is blocked by China network. Is websit configuration changed these days?

**Comment by by12291216** [comment]
> > I don't see any problem with the website, what is the IP address if you ping the domain name `ping fullcalendar.io`?
> 
> 108.59.4.161
我这边已经可以访问了 你也试试

**Comment by makeryi** [comment]
> > > I don't see any problem with the website, what is the IP address if you ping the domain name `ping fullcalendar.io`?
> > 
> > 
> > 108.59.4.161
> > 我这边已经可以访问了 你也试试

我也可以了👍🏻

**Comment by arshaw** [comment]
It looks like fullcalendar.io is no longer blocked in China. By looking at the site's analytics, we are receiving a healthy amount of traffic from China now.
