### ISSUE TITLE
"Global CSS cannot be imported from within node_modules." - next.js

### ISSUE THREAD

**Issue by ciruz** [fullcalendar/fullcalendar#6674]
### Reduced Test Case

next.js example repo - https://github.com/fullcalendar/fullcalendar-example-projects/tree/master/next

### Bug Description

I try to use FullCalendar with next.js, so I tried the FullCalendar next.js example repo.

After installing I stumbled on a global css error (``Global CSS cannot be imported from within node_modules.``) and found out that this CSS issue was the reason for this example repo at all.

Sadly the repo don't work anymore and produces the same error (again).

https://github.com/fullcalendar/fullcalendar/issues/5393#issuecomment-667701320

### Screenshots

![image](https://user-images.githubusercontent.com/987947/147478035-32af0933-1f63-45f7-a20e-c2cf38ac2188.png)

Maybe someone has an idea, thank you.

**Comment by acerix** [comment]
Do you mean you cloned that repo and get that error when running `build`?  It builds and runs for me without error.

**Comment by CyberCyclone** [comment]
I'm having the same issue with simply adding `import FullCalendar from "@fullcalendar/react";` to my Next.js project.

**Comment by ciruz** [comment]
@acerix but you work in "dev" mode, until you done and ready for production, then you build.

**Comment by younes0** [comment]
Either use this: https://spacebro.io/articles/fullcalendar-nextjs-10-higher
Or patch package https://github.com/ds300/patch-package with [patches.zip](https://github.com/fullcalendar/fullcalendar/files/9111245/patches.zip)

The first technique broke my fast refresh.

**Comment by spencerwmiles** [comment]
I've got a solution for this.

I use Tailwind for my CSS needs so all of the styles being imported by FC were undesirable to me. The trick is actually to stub out the CSS import via webpack config.

in next.config.js

{
    webpack: (config) {
        config.resolve.alias["./main.css"] = false;
        return config;
    }
}

It's a little dirty, so your mileage may vary depending on the size/complexity of your application... This will stub out the CSS imports being made by FullCalendar and get your imports to work.

Then in theory, if you need the FC styles, you should just be able to import the stylesheets on a case-by-case basis manually in _app.jsx or however you like.

[Alternatively, follow the documentation/example that lives inside of this repo for next.js.](https://github.com/fullcalendar/fullcalendar-example-projects/tree/10fe58abfc94457c7582af3948b3764cd17e7960/next)

The reason this error occurs is that FullCalendar that Next.js cannot import global stylesheets. FullCalendar does this automatically with no way to stop it. The documented way around this is to use "next-transpile-modules" which gets around this limitation.

See https://github.com/fullcalendar/fullcalendar-example-projects/tree/10fe58abfc94457c7582af3948b3764cd17e7960/next

**Comment by peterbe** [comment]
Except, it needs to `{"./main.css": false}` not `{"./main.css", ""}`
My `next.config.js`:
```js
/** @type {import('next').NextConfig} */
module.exports = {
	reactStrictMode: true,

	webpack: (config) => {
		config.module.rules.push({
			test: /node_modules\/@fullcalendar/,
			resolve: {
				alias: {
					"./main.css": false,
				},
			},
		});

		return config;
	},
};
```

**Comment by 0xdevalias** [comment]
> Except, it needs to `{"./main.css": false}` not `{"./main.css", ""}`

@peterbe As I said in https://github.com/fullcalendar/fullcalendar/issues/6674#issuecomment-1338902273:

> Note also that **in Webpack v4** we apparently can't set a resolve to `false` as it needs to be a string. But it seems that setting it to an empty string does the trick!

**Comment by peterbe** [comment]
I have the latest NextJS v13. 13.0.6 actually at the time of writing.

**Comment by 0xdevalias** [comment]
> I have the latest NextJS v13. 13.0.6 actually at the time of writing.

Yup, makes sense. That version of NextJS uses Webpack v5.

**Comment by arshaw** [comment]
Released in [v6.0.0](https://github.com/fullcalendar/fullcalendar/releases/tag/v6.0.0)

**Comment by Naruto0829** [comment]
I am going to use ExportPDF function on Ckeditor in Next js but I faced with the following error

./node_modules/@ckeditor/ckeditor5-engine/theme/placeholder.css
Global CSS cannot be imported from within node_modules.
Read more: https://nextjs.org/docs/messages/css-npm
Location: node_modules\@ckeditor\ckeditor5-engine\src\view\placeholder.js

If someone has best solution then please reply to my post.
Thanks

**Comment by andrynewmans** [comment]
> I am going to use ExportPDF function on Ckeditor in Next js but I faced with the following error
> 
> ./node_modules/@ckeditor/ckeditor5-engine/theme/placeholder.css Global CSS cannot be imported from within node_modules. Read more: https://nextjs.org/docs/messages/css-npm Location: node_modules@ckeditor\ckeditor5-engine\src\view\placeholder.js
> 
> If someone has best solution then please reply to my post. Thanks

I too am working with ckeditor and facing the same problem. Maybe I'll juste leave Next.

**Comment by mPooja-15** [comment]
![image](https://github.com/fullcalendar/fullcalendar/assets/57384798/e7555553-9330-48b7-9e4c-9801c281c4bd)
Getting error in next .
