### ISSUE TITLE
24 hour format for time axis

### ISSUE THREAD

**Issue by Deep1Shikha** [fullcalendar/fullcalendar#6679]
### Checklist

Please mark these items with an [x]

  - [x] I've already searched through [existing tickets](https://fullcalendar.io/issues)
  - [x] Other people will find this feature useful

### Feature Description
Currently, if we use slotLabelFormat {{hour:"numeric", hour12:false}}

It gives us 24 hour format calendar but midnight is shown as 24, however it should be shown as 00

Please describe what this feature will do.

This feature will enable user for appropriate 24 hour format full calendar.

**Comment by acerix** [comment]
That format comes from the browser and is based on locale, eg. you can use `en-GB` which is "00":

https://codepen.io/acerix/pen/ZEXRrro?editors=001

If you need to customize it, you would need a date formatter plugin, there is an open issue regarding that:

https://github.com/fullcalendar/fullcalendar/issues/5683
↑
Please visit the above issue, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates.
