### ISSUE TITLE
Error in documentation,  'description' property in example should belong to extendedProps Object

### ISSUE THREAD

**Issue by cimpok** [fullcalendar/fullcalendar#6682]
### Reduced Test Case
not reproducible with a link

### Bug Description
Error in documentation - On this page [Event Object - Non-standard fields](https://fullcalendar.io/docs/event-object)
in the last example regarding Non-standard fields the 'description' property should belong within 'extendedProps' object:
`      extendedProps: {
        department: 'BioChemistry'
        description: 'Lecture'
}`

**Comment by acerix** [comment]
As explained in the paragraph above that, extended props be set in either `extendedProps` or the event object itself.
