### ISSUE TITLE
iCalendar format seems to be ignored for event sources as a function

### ISSUE THREAD

**Issue by stshort** [fullcalendar/fullcalendar#6683]
### Checklist

Please mark these items with an [x]

  - [x] I've already searched through [existing tickets](https://fullcalendar.io/issues)
  - [x] Other people will find this feature useful

### Feature Description

I'm trying out the new ics support, however it seems like the implementation does not allow for passing access tokens properly in GET requests (I tried passing `access_token` and `token_type` in the URL, but to no success). So to get around this, I'm using event sources as a function. By doing this:

```
{
  events: EventSourceFunc[],
  format: 'ics',
}
```

I am able to fetch all of my events fine, however when I pass the ics file contents to the `successCallback`, it doesn't seem like they're being parsed, and will rely on me manually parsing the ics file and translating them to raw events. I'd expect if I am passing `ics` as the format, that it should hook into the same workflow as if I were to hook it into an ics feed as documented.

I also noticed that it seems to be doing the same non-ics behavior of fetching new data every time the user changes the calendar view or changes the calendar page. I'd expect that if I am using ics as a format, it should hook into the same logic, regardless of if I am using event sources as a function or a direct ics feed.

If I'm doing anything wrong I'd appreciate feedback, but from everything I can tell, this seems like it is likely a gap in the iCalendar implementation.

**Comment by stshort** [comment]
Alternatively, if you can add support to customize the headers for ics/json feeds that would work too. As far as I can tell, that's not supported still

https://github.com/fullcalendar/fullcalendar/issues/4627

**Comment by acerix** [comment]
Would you be able to post a [runnable, stripped-down demonstration of the bug](http://fullcalendar.io/wiki/Reduced-Test-Cases/)? Would really appreciate it because the time saved reproducing will be time spent fixing.

**Comment by stshort** [comment]
@acerix I'm trying to gauge the difficulty of fixing it myself on a fork, and was looking through the code, I think the problem is:

https://github.com/fullcalendar/fullcalendar/blob/master/packages/common/src/structs/event-source-parse.ts#L93

In this event source parser, later added plugins are taking precedence. Which makes sense I suppose, however:

https://github.com/fullcalendar/fullcalendar/blob/master/packages/common/src/plugin-system.ts#L95

In the plugin system, looks like the plugin definitions are added to the `hooks.eventSourceDefs` array first, followed by the globalDefs. I stepped through the code in a debugger and confirm that the ics eventSourceDef is added to position 0 of the array, whereas the globals are added at 1, 2, and 3 of the array. Hence, the logic in the event source parser is hitting the global definitions first, then only will fall through to the plugins if they do not match any of the global definitions.

In the case I'm explaining above, the events I'm passing is an event source function, however I am passing `format: ics` which I would expect to work. However, since it is hitting the global defs first, it first gets parsed here -
https://github.com/fullcalendar/fullcalendar/blob/master/packages/common/src/event-sources/func-event-source.ts#L24

As a function event source. Because of this, the event source parse short-circuits, as it matched a valid event source (function type). And then going forward, it treats this entirely as a function event source, which makes sense, however iCalendar events need to have their raw events parsed prior to handing them off to the calendar internals.

IOW I would need to match this and call the post-fetch logic in the iCalendar event source for the events to be properly parsed
https://github.com/fullcalendar/fullcalendar/blob/master/packages/icalendar/src/main.ts#L59 - But even if the order of the event source definitions was [globalDefs, pluginDefs], it would not match the ics event source def because it is hardcoded to require `url` parameter set, so it'd fall down to the function event source definition anyways.


But really, this could also be solved if I could simply modify the XHR headers prior to making a request. **The only reason I'm trying to use a function as an event source instead of an iCalendar feed is because I need to have an authorization token present and a few headers set, which is not possible in the current fetch implementation.** 

If #4627  was implemented, I wouldn't have to go through this really roundabout way to try and get this working.

**Comment by stshort** [comment]
@acerix FYI I added a possible implementation in #6690 - I really think this is about this simple to implement and would unblock me, while extending the flexibility of all url feed based event sources. I didn't update tests, and definitely will need a closer look by a maintainer to make sure it's a good implementation with no unexpected side effects, but from my initial testing on my project it's working well.
