### ISSUE TITLE
Today date is not highligthed in TimelineView

### ISSUE THREAD

**Issue by fdiedler** [fullcalendar/fullcalendar#6686]
### Reduced Test Case

https://fullcalendar.io/docs/timeline-custom-view-demo

### Bug Description

With FullCalendar v5, by default the today date is highlight in yellow. It works in month view by instance but it is not working in TimelineView.

### Screenshots
![bug_fullcalendar](https://user-images.githubusercontent.com/42271872/148522191-46f7305e-58a6-4eba-b7dc-c689c1955f18.png)

**Comment by acerix** [comment]
I believe this existing ticket captures this need:
https://codepen.io/arshaw/pen/jOWXmVb?editors=0010
↑
Please visit the above issue, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates.
