### ISSUE TITLE
Anyone can compile the license key.

### ISSUE THREAD

**Issue by formula21** [fullcalendar/fullcalendar#6688]
I do not think this is a bug of any kind. However, while viewing the JavaScript code for FullCalendar, I figured out that with a little bit of effort any one can actually guess a correct license key.
1. It's template being `xxxxxxxxxx-xxx-xxxxxxxxxx` and matching with the regex option `/^(\d+)-fcs-(\d+)$/` we can figure out the middle part to be `fcs`.
2. The first part is just validated as `parts[1].length === 10` i.e. the length of the string should be 10.
3. The last part is a bit tricky however essentially we need look at the given values like `RELEASE_DATE` & `UPGRADE_WINDOW`. With this we can add and guess a date. Compiling a date like `2022-01-08` to epoch seconds gives us `1641600000000`. With that if we truncate 3 more zeros i.e. `1641600000` we get the last part exactly.

I was hoping to get more funding for building such an amazing project you could enforce certain plugins only for paid members, deliver them a separate bundle of essentially those features.

All said, this was just my thought. I love FullCalendar

Regards,
[Anweshan](https://github.com/formula21)

**Comment by acerix** [comment]
The license key is not private/secret, it needs to be included in the code to identify the license owner.
