### ISSUE TITLE
select minimum distance counterpart for deselecting? 

### ISSUE THREAD

**Issue by gstlouisgit** [fullcalendar/fullcalendar#6694]
### Checklist

Please mark these items with an [x]

  - [ x] I've already searched through [existing tickets](https://fullcalendar.io/issues)
  - [x ] Other people will find this feature useful

### Feature Description

I have been using the select minimum distance [here](https://fullcalendar.io/docs/selectMinDistance) feature that works fine, but when it comes to deselecting it does not respect the same distance.  As in it does not unselect after the distance assigned ( I'm assuming its defined by pixels? )

 I have setup an example on stackoverflow to see if anyone had any advice or work around.  Could this just be a feature to add as a counterpart to minimum distance?  Or already there and I just never found it?  Or a bug?

[https://stackoverflow.com/questions/70644278/fullcalendar-selectmindistance-not-respecting-distance-when-unselecting](https://stackoverflow.com/questions/70644278/fullcalendar-selectmindistance-not-respecting-distance-when-unselecting)

**Comment by acerix** [comment]
`selectMinDistance` is to prevent selection if a date is clicked, I'm not sure why that would be useful on deselection.  If you are trying set a minimum length for the selection you should use `selectAllow` instead.

**Comment by gstlouisgit** [comment]
@acerix 
Thanks for your comment.  I do not know why I didn't find selectAllow when searching on the site and online.  But its what I was looking for, thank you
