### ISSUE TITLE
Ability to set a fixed number of days for a view excluding weekends when hidden

### ISSUE THREAD

**Issue by jaredgibb** [fullcalendar/fullcalendar#6699]
### Reduced Test Case
https://jared-gibb-project-123.web.app/thunk/calendar.html
### Bug Description
Using View Durations and hiding weekends results in inconsistent view durations

Describe how to recreate the bug.
set weekends to false
set timeGridWeek view to have a duration of 3 days

What do you expect to happen?
days should display and increment 3 at a time while omitting weekends. weekends should be ignored for display purposes. 

i.e. Fri,Mon,Tue should be able to appear

What happens instead?
the number of days displayed is variable 

### Screenshots
![Screen Shot 2022-01-21 at 2 49 51 PM](https://user-images.githubusercontent.com/70493366/150591247-07d32495-19a2-4536-b3c7-7f96da492087.png)
![Screen Shot 2022-01-21 at 2 50 00 PM](https://user-images.githubusercontent.com/70493366/150591251-ab1008c8-2fb4-45a9-9259-8bcb44018e70.png)

**Comment by acerix** [comment]
The duration is the span from the time the view starts until it ends, it's not intended to show a fixed number of days, there is  `dayCount` for that.
