### ISSUE TITLE
Snap to slotdureation instead of snapduration based on start

### ISSUE THREAD

**Issue by MJWexer** [fullcalendar/fullcalendar#6700]
### Checklist

Please mark these items with an [x]

  - [ x] I've already searched through [existing tickets](https://fullcalendar.io/issues)
  - [x ] Other people will find this feature useful

### Feature Description

Please describe what this feature will do.
Users can adjust the event to snap to the current slot when initiated with an offset start time versus the current slot duration.
As we have implemented several zoom levels (1,5,15,30 minutes) slot durations, events can be located with offset start time versus the current "view"(zoom level).
As such, moving an even should be able to adjust to slot instead of snapDuration defined by start time

https://jsfiddle.net/wrbt840j/16/

### Visual Mockups

If you are requesting a new UI, please include a mockup.
If not, erase this section.

**Comment by acerix** [comment]
I believe this existing ticket captures this need:
https://github.com/fullcalendar/fullcalendar/issues/5964
↑
Please visit the above issue, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates.
