### ISSUE TITLE
Jalali calendar support for month view: flexible month start/end date as well as flexible day flow direction

### ISSUE THREAD

**Issue by hosseink33** [fullcalendar/fullcalendar#6702]
### Checklist
Please mark these items with an [x]

  - [x] I've already searched through [existing tickets](https://fullcalendar.io/issues)
  - [x] Other people will find this feature useful

### Feature Description
Jalali (Shamsi) calendar (see [here](https://en.wikipedia.org/wiki/Jalali_calendar)) is used by millions of people around the world (mainly in Iran and Afghanistan). For example, Material UI (see [here](https://mui.com/components/date-picker/)) is already supporting Jalali datetime pickers. Although fullcalendar currently has a locale support and we could convert Gregorian (Christian) date to Jalali date using fa-IR (see [here](https://github.com/date-fns/date-fns/tree/master/src/locale/fa-IR)), some import details are left out in fullcalendar until we could use it as a Jalali calendar.

1. Start and end of Jalali months are different from Gregorian months and this makes day labels (i.e. being active for current month and inactive/fainted-color for previous/next month) and day flows (covering 1st to last of each month in the corresponding month view) inconsistent with what users expect. 

For example for Bahman, the 11th month of Jalali calendar:

1/Bahman/1400 to 30/Bahman/1400 == 21/Jan/2022 to 19/Feb/2022
and therefore
**12th of Bahman will mark 1st of February** 

In the current version of full calendar, when you use locale  and look for the month Bahman (or بهمن), it's as if it starts from day 12! (all days before have disabled label). You can see this date converter to make sense of the appropriate logic (https://www.iranchamber.com/calendar/converter/iranian_calendar_converter.php)
Also we already have JS libraries for converting dates between the two: https://www.npmjs.com/package/shamsi-date-converter

2. Jalali calendar is read from right to left (not left-to-right). Therefore, we would like the days flow direction to be flexible, so we could make it right to left in all month/week/custom-day views using an argument. This would mean, with this argument set to `True` or `right-to-left`, when you look at the calendar, dates increase from the right of the screen to the left.

### Possible Solution for adding feature 1
- start and end of months in calendar **views** could be changed via passing a mapping specifying breakpoints, so that for start, we could manually modify the months flow. For example, I can create a new custom flow saying my month start from Jan21st and finishes on Feb 19th (sth like an array `first_day_of_month={"2022": ["21-01", "20-02", "21-03", ...]}, "2023": ...}`). Later, this could be automated using, for instance, the fa-IR locale and a Gregorian-to-Jalali date converter.

**Comment by acerix** [comment]
I believe the existing ticket captures this need:
https://github.com/fullcalendar/fullcalendar/issues/1813
↑
Please visit the above issue, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates.
