### ISSUE TITLE
Eventclick is not working

### ISSUE THREAD

**Issue by sachinpadha** [fullcalendar/fullcalendar#6708]
### Reduced Test Case

https://justjammu.com/calendar/index.php
Open the above the link
Double click on any date to add the event (you can keep start, end time as blank and click on "OK")
Once the Event got added successfully, double click on that event to DELETE it. A confirm Dialogue box will poped up.
But event.id is undefined. Refresh the page and double click on same event, then it will get deleted successfully.

### Bug Description

Double click on any date to add the event (you can keep start, end time as blank and click on "OK")
Once the Event got added successfully, double click on that event to DELETE it. A confirm Dialogue box will poped up.
But event.id is undefined. Refresh the page and double click on same event, then it will get deleted successfully.

**Comment by acerix** [comment]
There is no default 'id' for events, so you would need to set that to lookup by id or just remove the event with [event.remove()](https://fullcalendar.io/docs/Event-remove).

**Comment by sachinpadha** [comment]
I am afraid that is no the case. event.id is very much available which I am sending to PHP page via AJAX to delete it from Database.

event.id is coming as undefined and when I refresh the page event.id is giving proper value and getting deleted from DB as well. Is there a way that without refresh, I can achieve the same thing? Deleting from DB is the main motto. event.remove() will remove from HTML DOM not from DB.

**Comment by sachinpadha** [comment]
> I am afraid that is no the case. event.id is very much available which I am sending to PHP page via AJAX to delete it from Database.
> 
> event.id is coming as undefined and when I refresh the page event.id is giving proper value and getting deleted from DB as well. Is there a way that without refresh, I can achieve the same thing? Deleting from DB is the main motto. event.remove() will remove from HTML DOM not from DB.
