### ISSUE TITLE
Weird selection when Ctrl is pressed on Timeline view

### ISSUE THREAD

**Issue by fdiedler** [fullcalendar/fullcalendar#6709]
### Reduced Test Case
not reproducible with a link

### Bug Description

When holding the Crtl key, a strange selection appears

Just test here :
https://fullcalendar.io/docs/timeline-standard-view-demo

Is it a bug ? Otherwise, how can I disable this ? (In fullcalendar v3, there is no problem)

### Screenshots

![fullcalendar_ctrl](https://user-images.githubusercontent.com/42271872/152566647-e8f4aa0f-0f43-40b5-ad44-8821ef8cab5e.png)

**Comment by acerix** [comment]
I believe this existing ticket captures this need:
https://github.com/fullcalendar/fullcalendar/issues/5367
↑
Please visit the above issue, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates.

**Comment by fdiedler** [comment]
@acerix Indeed, the bug is also present for resources and using Firefox browser.
