### ISSUE TITLE
`NowIndicator` tick triggers internal dimensions update even when calendar it's not visible

### ISSUE THREAD

**Issue by kamilchlebek** [fullcalendar/fullcalendar#6712]
### Reduced Test Case

[TEST CASE](https://fullcalendar-issue-xyz123.stackblitz.io/)
[TEST CASE CODE](https://stackblitz.com/edit/fullcalendar-issue-xyz123)

### Context

We are using calendar in an ionic application.

When user selects date we open "create event page".

What's more important the fullcalendar instance stays present in the dom. 
It's pushed outside the viewport while "create event page" is opened (stacked navigation).

### Bug Description

_I was going to report just one issue._
_However during creating the demo I discovered the second one, which almost prevented me from creating demo for the 1st issue._
_Feel free to split these two into individual gh issues_

#### Issue 1

Sometimes users are unable to select a date. Interactions are unexpectedly not working.

Prerequisites: `nowIndicator` must be enabled

Test case:
1. Open https://fullcalendar-issue-xyz123.stackblitz.io/
2. Select any date range (important: start from even hour, odd hours are used for `issue 2`)
3. Wait on opened page for 70 seconds
4. Go back to calendar
5. Try to select any date range again - not working

##### Issue 1 - explanation

After digging deep into fullcalendar I found out what's going on.

Even when fullcalendar is invisible, due to enabled `nowIndicator` the FC performs component updates.

Because of that `PositionCache.lefts` and `PositionCache.rights` gets recomputed every minute.
https://github.com/fullcalendar/fullcalendar/blob/e62fea20f1dab61ab1792a1679a82309e72ba46b/packages/common/src/common/PositionCache.ts#L32-L44

(possibly triggered in `TimeColsContent.updateCoords()`)
https://github.com/fullcalendar/fullcalendar/blob/e62fea20f1dab61ab1792a1679a82309e72ba46b/packages/timegrid/src/TimeColsContent.tsx#L141-L158

Once coords get recomputed while FC is invisible - `PositionCache.lefts` & `PositionCache.rights` are equal to `[0]`. 
As a result `TimeCols.queryHit` returns null, because pointer event coordinates doesn't fit into `[0,0]` range. 
That's why user interaction is ignored and nothing happens.

##### Issue 1 - workaround

For now, I can either disable `nowIndicator` (components will be still updated, but once a day) or trigger an update manually once calendar is visible again.

Optionally switching `businessHours` to `true` and back to `false` does the job.

##### Issue 1 - suggestion

Ideally FC should not perform any updates when it's not visible (see also `issue 2`).
If that is not possible would be good to have method `pause/resumeUpdates()` or `performUpdates()` or... existing method `updateSize()` could do that as well.

------------

#### Issue 2

Test case:
1. Open https://fullcalendar-issue-xyz123.stackblitz.io/
2. Select any date range (important: start from odd hour, even hours are used for `issue 1`)
3. Go back to calendar
4. Boom! Calendar layout is broken. 

![img](https://user-images.githubusercontent.com/40219331/152801446-80983f7c-27ab-41d0-a231-7b5f31e3905c.png)

#### Issue 2 - explanation

Underlying cause is a bit similar to `issue 1`. FC performed an update while it wasn't visible (while navigating back to calendar page)

This time it's about `scrollerClientWidths` being equal to `{header: 0, body: 0}`

https://github.com/fullcalendar/fullcalendar/blob/e62fea20f1dab61ab1792a1679a82309e72ba46b/packages/common/src/scrollgrid/SimpleScrollGrid.tsx#L260

#### Issue 2 - workaround

Somehow triggering `calendar.unselect()` just before opening another page works.
It triggers component updates immediately, which prevents updates from happening while navigating back to calendar page.

------------

#### Related issues

https://github.com/fullcalendar/fullcalendar/issues/4976

**Comment by acerix** [comment]
It sounds like both issues are related and related to the calendar being resizing while it's hidden, does it work to call [updateSize](https://fullcalendar.io/docs/updateSize) after going back to the calendar?

Also I'm not sure how to view the code of your demo, is there a link for that?

**Comment by kamilchlebek** [comment]
> does it work to call [updateSize](https://fullcalendar.io/docs/updateSize) after going back to the calendar?

🤔  Suprisingly. Yes, `updateSize()` does the job for the 2nd issue. Doesn't help for the 1st though. 

> Also I'm not sure how to view the code of your demo, is there a link for that?

Sorry, here it is: https://stackblitz.com/edit/fullcalendar-issue-xyz123

**Comment by acerix** [comment]
Thanks for the link. 

I believe the ticket you mentioned captures these issue:
https://github.com/fullcalendar/fullcalendar/issues/4976 
↑
Please visit the above issue, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates.

For example, when the selection stops working I can resize the window to make it work again.  So as a workaround it should work to use this same workaround after every time the calendar is rendered (eg. after clicking back) instead of just the initial render:

```
    setTimeout(function () {
      window.dispatchEvent(new Event('resize'));
    }, 100);
```

**Comment by kamilchlebek** [comment]
@acerix Thanks for the response. 

Unfortunately executing `window.dispatchEvent(new Event('resize'));` doesn't resolve the issue. 

You're right, resizing the window manually fixes the issue, but dispatching an event manually doesn't :(
