### ISSUE TITLE
Using visibleRange with timeGrid

### ISSUE THREAD

**Issue by Hepi420** [fullcalendar/fullcalendar#6717]
### Reduced Test Case

[REDUCED TEST CASE](https://codepen.io/roy-yahalomi/pen/YzENdNw).

### Bug Description

I want to use the timeGrid display to show the work week from sunday to friday and I want the calander to start from sunday instead of the current date.
I tried using visibleRange propery with moment to get the start of the week and its not updating, and no errors in console.
simplified exmple attached above using moment.

**Comment by acerix** [comment]
`visibleRange` should be used instead of the `duration` setting, so using that function would be like this and always be fixed on the current week:

https://codepen.io/acerix/pen/mdqmgzV?editors=0010

If you just want to change the start of the week, you can use the `firstDay` setting.
