### ISSUE TITLE
Recurring event time displayed wrongly after daylight saving time

### ISSUE THREAD

**Issue by claudiomerli** [fullcalendar/fullcalendar#6729]
### Reduced Test Case

[REDUCED TEST CASE](https://codesandbox.io/s/recursing-meadow-5jvb3)

### Bug Description

If is configured an event with recursion using RRULE across daylight saving time it is displayed wrongly after 27/03.
It's correct if the event start is maintained on 12PM (I'm in Europe/Rome timezone)

### Screenshots

![image](https://user-images.githubusercontent.com/71256977/153869124-a778b111-0710-4c22-b839-55ef5fb39bb0.png)

**Comment by acerix** [comment]
It's not using DST because the event time is in UTC (ends with "Z").  The rrule can be in localtime to keep the same time of day with DST:

https://codesandbox.io/s/gifted-pike-0qoh0?file=/src/app/app.component.ts
