### ISSUE TITLE
Add weekTextLong for French locale

### ISSUE THREAD

**Issue by LucileDT** [fullcalendar/fullcalendar#6731]
### Reduced Test Case

[Reduced test case](https://jsfiddle.net/LucileDT/631b8xnt/29/)

(not sure if it works as I build my sources using Webpack and I have to use a different method on jsfiddle).

### Bug Description

**Scenario:**

- create a calendar (v5.10)
- use "fr" as locale
- use `week: 'long'` in a date format function (`titleFormat`, `slotLabelFormat`, ...)

**Expected behavior:**

The text generated is "Semaine [week number]" 

**Current behavior:**

The text generated is "Week [week number]"

### Screenshots

Here a screenshot with successively `week: 'long'`, `week: 'short'`, `week: 'narrow'` and `weekday: 'narrow', day: '2-digit'`.

![image](https://user-images.githubusercontent.com/23707217/154359638-06b0527d-422c-45ec-a03b-d2e8315c5e96.png)

**Comment by acerix** [comment]
It hasn't been translated yet, would need to add `weekTextLong` to https://github.com/fullcalendar/fullcalendar/blob/master/packages/core/src/locales/fr.ts

**Comment by arshaw** [comment]
Released in [v6.1.1](https://github.com/fullcalendar/fullcalendar/releases/tag/v6.1.1)

https://cdn.jsdelivr.net/npm/@fullcalendar/core@6.1.1/locales/fr.js
