### ISSUE TITLE
Resource view navLinks with headerToolbar false link to wrong view

### ISSUE THREAD

**Issue by hisuwh** [fullcalendar/fullcalendar#6732]
### Reduced Test Case

https://codepen.io/hisuwh/pen/PoOENew

### Bug Description

Use a resource timeline views, with `headerToolbar: false` and `navLinks: true`

View month or year views, click day or month in header.

**Expected** that it would take you to corresponding view (`resourceTimelineDay` or `resourceTimelineMonth`)
**Actually** takes you to the incorrect view
- in my app it is taking me to the `timelineDay` or `timelineMonth` views
- in this codepen it is taking you to the `timeGridDay ` and `dayGridMonth` views by the looks of things

I know I could use the `navLinkDayClick` function to control this but this doesn't solve the year view where I have a slot duration of a month as there is no `navLinkMonthClick` function.  Why is there not just a `navLinkClick` function?  

Is there a render hook for the timeline header cells?  Then I could implement this in a custom way.  (I would quite like a render hook for this anyway so I can control the appearance of these cells).

**Comment by acerix** [comment]
I believe this existing ticket captures this need:
https://github.com/fullcalendar/fullcalendar/issues/4931
↑
Please visit the above issue, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates.

You can use the `slotLabelDidMount` hook to do it manually, eg:

https://codepen.io/acerix/pen/OJOopQP?editors=0011
