### ISSUE TITLE
fullcalendar.io is not loading...

### ISSUE THREAD

**Issue by artknight** [fullcalendar/fullcalendar#6737]
### Bug Description

The main site `fullcalendar.io` is not loading...nor is the documentation!

### Screenshots
<img width="779" alt="Screen Shot 2022-02-22 at 9 52 20 PM" src="https://user-images.githubusercontent.com/157762/155254185-bae60d98-dbb9-4dcc-9140-d69c59b7b8cf.png">

**Comment by acerix** [comment]
Is it still unreachable?  I don't have an issue.

**Comment by artknight** [comment]
> Is it still unreachable? I don't have an issue.

I am baffled as to why the site is not loading on my laptop. It seems to be isolated to my laptop only.. any chance my IP is blacklisted or something? ( 216.239.185.222 )

**Comment by acerix** [comment]
If you can reach the site on another device it's a problem with the laptop not the network.
