### ISSUE TITLE
Event.title is displayed incorrectly when unescaping the title via eventDidMount()

### ISSUE THREAD

**Issue by rene-hoehne-ais** [fullcalendar/fullcalendar#6745]
### Reduced Test Case

https://codepen.io/rene-hoehne-ais/pen/QWOzYYG

Look for the event titles in Jan.-March 2022.
Start with March 2022, go back to Feb. 2022 and Jan. 2022 
... now change back to Feb. 2022 and March 2022.)

### Bug Description
We use the hook event eventDidMount() to override the default escaping of event.title.
Mostly the hook event is called, but if the event was known from the last month eventDidMount() is not called.
Instead, it appears that the content of '&lt;div class="fc-event-title"&gt;' is copied to the correct week line in the new month and the escaping of event.title is also added.
(**In Test case:** Browse through the months Jan./Feb./March/April 2022 an look at the weeks with a month change.)

The same behavior can be seen when you have multiple events in the same day and they are grouped under '+2 more'.
In this case, a previously starting event is displayed incorrectly. It appears that the content of '&lt;div class="fc-event-title"&gt;' is copied and the escaping of event.title is also added.
(**In Test case:** see in Feb.2022 [It works] and Jan.2022 [Problem])

I think we are not using the event eventDidMount as expected. Unfortunately we don't see any other way to display HTML & Font Awesome icons, which we would like to do.
Even though we are causing the described behavior through our DOM tree intervention, if we had the option to disable escaping for the title and description, we would turn that off.

### Screenshots
![Unbenannt](https://user-images.githubusercontent.com/100850345/156606560-06bd8a7e-b83f-4a53-9059-7917606caebf.png)

**Comment by acerix** [comment]
`eventDidMount` is for attaching listeners to the event, for example, it doesn't work for content. To supply HTML content you should use `eventContent` instead.
