### ISSUE TITLE
Context changes when calendar events are updated during dragging

### ISSUE THREAD

**Issue by mdm** [fullcalendar/fullcalendar#6747]
### Reduced Test Case

I created a small project to demonstrate the bug here: https://github.com/mdm/fullcalendar-context-bug-mre

### Bug Description

When the calendar events are updated while the user is dragging an existing event sometimes the calendar context seems to change, causing the following if statement to trigger an `eventReceive` instead of an `eventDrop`:

https://github.com/fullcalendar/fullcalendar/blob/3e4ce4c2fcee749eb459c59013f70b3cbd3e5a51/packages/interaction/src/interactions/EventDragging.ts#L260

In our use-case the information on the `eventReceive` event is not sufficient for us to further process it. So we can't just work around this bug with `eventReceicve`.

To reproduce using the project linked above, follow these steps:

1. Load the project in your favorite browser and open the browser console
2. Drag the event "drag me" to another day but don't release it
3. Wait for the event "volatile [counter]" to be updated (i.e. wait for the counter to increase)
4. Without moving the dragged event again release it
5. Observe in the browser console that indeed `eventReceive` is triggered instead of `eventDrop`

Note that if you continue moving the "drag me" event after the "volatile [counter]" updated the correct `eventDrop` is triggered.

I'm happy to provide more details if needed.

**Comment by acerix** [comment]
I believe this existing ticket captures this need:
https://github.com/fullcalendar/fullcalendar/issues/6561
↑
Please visit the above issue, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates.
