### ISSUE TITLE
Move event from one month to another

### ISSUE THREAD

**Issue by mankowitz** [fullcalendar/fullcalendar#6751]
### Checklist

Please mark these items with an [x]

  - [ x ] I've already searched through [existing tickets](https://fullcalendar.io/issues)
  - [ x ] Other people will find this feature useful

### Feature Description

Move event from one month to another. (see #2542 for one solution)

### My current workflow
In order to move an appointment from one month to another, I have to go through a bunch of steps.
1. remove the event from the current calendar, 
2. create a draggable div outside the calendar, 
3. allow the user to change the month/day/year, 
4. allow the user to drag the div back onto the calendar, 
5. hide the new div, 
6. submit an ajax request to update the datasource, 
7. delete the newly dropped event. 

Here is the relevant code:
```js
// 1
reschedulingEvent = calendar.getEventById(....)
reschedulingEvent.remove()

// 2
rescheduledAppointment = new FullCalendar.Draggable(document.getElementById(
    'rescheduled-appointment'), {
      eventData: {
        id: reschedulingEvent.id,
        title: reschedulingEvent.title,
        duration: "0:" + (reschedulingEvent.end - reschedulingEvent.start)/1000/60,
      }
})

// 4
calendar = new FullCalendar.Calendar(document.getElementById('calendar'), {
    editable: true,
    droppable: true,
    eventDrop: addEventToForm,
    eventReceive: addEventToForm,
});

async function addEventToForm(info) {
  if (!confirm("Would you like to reschedule this appointment")) return;
  $(".rescheduled-appointment-div").hide()   // 5
  await axios.post(`/appointments/${info.event.id}`, {
    start: info.event.start,
    end: info.event.end,
  })   // 6
  calendar.refetchEvents()
  calendar.getEventById(info.event.id).remove()  // 7
}
```

**Comment by acerix** [comment]
I believe the existing ticket captures this need:
https://github.com/fullcalendar/fullcalendar/issues/2542
↑
Please visit the above issue, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates.
