### ISSUE TITLE
Move Issue when calendars is in overlap

### ISSUE THREAD

**Issue by Sbaia** [fullcalendar/fullcalendar#6753]
### Reduced Test Case

[https://codepen.io/roberto-serafin/pen/BamgQOx](https://codepen.io/roberto-serafin/pen/BamgQOx)

### Bug Description

If in the same page I have 2 overlapped calendar, the calendar in foreground not correctly handles the events of move of the events in calendard. The events can be resized, but cannot be moved.

### Screenshots

![calendar overlap](https://user-images.githubusercontent.com/2121917/157411220-e81e0062-0d51-4d7a-a7d1-54eb08b229be.gif)

**Comment by acerix** [comment]
I believe this existing ticket captures this need:
https://github.com/fullcalendar/fullcalendar/issues/5026
↑
Please visit the above issue, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates.
