### ISSUE TITLE
Event title duplicated

### ISSUE THREAD

**Issue by fabienwnklr** [fullcalendar/fullcalendar#6756]
### Reduced Test Case

https://codepen.io/fab_wnklr/pen/KKyOooO?editors=0010

### Bug Description

if i want use HTML into event title, i use `eventDidMount` hook, and restore the `innerHTML`, but if i'm on the month view for example, and i click one more on the same view, title duplicated..

### Screenshots

![Animation](https://user-images.githubusercontent.com/49644785/157692452-56aadcbd-7441-400b-8617-ccdf19004951.gif)

**Comment by acerix** [comment]
`eventDidMount` is for attaching listeners to the element, for example, for adding HTML you should use `eventContent` instead.
