### ISSUE TITLE
TimeGridWeek - Feature to zoom out / view the whole day when slotDuration is set to 1 minute

### ISSUE THREAD

**Issue by WhereCanI** [fullcalendar/fullcalendar#6762]
### Checklist

Please mark these items with an [x]

  - [x] I've already searched through [existing tickets](https://fullcalendar.io/issues)
  - [x] Other people will find this feature useful

### Feature Description

When you set slotDuration to 1 minute's precision it will not zoom so much in on your timegrid that you can scroll forever vertically. I would like to request a feature where you can "zoom out" and cram together the slots so more of the day is viewed without scrolling. It could be done either via the API or maybe through a predefined zoom button or "View whole day" button.

### Visual Mockups

No specific visual editing.

**Comment by acerix** [comment]
I believe this existing ticket captures this need:
https://github.com/fullcalendar/fullcalendar/issues/3822
↑
Please visit the above issue, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates.

**Comment by WhereCanI** [comment]
@acerix - I don't agree that my feature request is the same as the other one. The other request is about changing the slotDuration, which wouldn't work in my case. 

In my case events always have to be set with 1 minutes precision, which means the skotDuration should be set to "00:01:00". If I change to a higher slotDuration events stopping at for example 11:00 and another starting at 11:00 will "overlap" and cause the 2 events to be shown as slightly overlapping. Because of this I am forced to use the slotDuration on only one minute or else events will overlap. 

What I am looking for is a way to watch more of the day / zoom out without changing the slotDuration since a slotDuration with "00:01:00" will create a kilometer long vertical scroll.

**Comment by acerix** [comment]
Since events snap to the `slotDuration`, that would need to stay as one minute to show events with minute precision.  The long scroll could be avoided by not having a label in as slot as described here:

https://github.com/fullcalendar/fullcalendar/issues/4937

So you could use the same workaround for now to have minute precision without labels:

https://codepen.io/acerix/pen/Rwxppaj?editors=0110
