### ISSUE TITLE
Calendar year view 

### ISSUE THREAD

**Issue by antonio-tsoft** [fullcalendar/fullcalendar#6764]
### Checklist

Please mark these items with an [x]

  - [X ] I've already searched through [existing tickets](https://fullcalendar.io/issues)
  - [ X] Other people will find this feature useful

### Feature Description
Hi, can you help me to add feature to display months by year?
Attached example.

Regards.
### Visual Mockups
<img width="455" alt="year_view_calendar" src="https://user-images.githubusercontent.com/101155669/158891957-3f459a6e-ee0c-45e3-9080-1e9472b807a5.png">

**Comment by acerix** [comment]
I believe this existing ticket captures this need:
https://github.com/fullcalendar/fullcalendar/issues/1140
↑
Please visit the above issue, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates.
