### ISSUE TITLE
Switch from XHR to Fetch API

### ISSUE THREAD

**Issue by vhscom** [fullcalendar/fullcalendar#6772]
### Checklist

Please mark these items with an [x]

  - [x] I've already searched through [existing tickets](https://fullcalendar.io/issues)
  - [x] Other people will find this feature useful

### Feature Description

I'd prefer to use Fetch API instead of XHR for Event Sources for hopefully obvious reasons. Is this change planned for v6? If not, can it be roadmapped? Also, it would be tremendously helpful to have GitHub Discussions opened. Doing so will make Q/A searchable from one place and make it easier to maintain the repo by reducing open issues.

### Visual Mockups

n/a

**Comment by vhscom** [comment]
https://github.com/fullcalendar/fullcalendar/issues/4627#issuecomment-585918341

**Comment by arshaw** [comment]
Released in [v6.0.0](https://github.com/fullcalendar/fullcalendar/releases/tag/v6.0.0)

Please see this part of the changelog:
https://fullcalendar.io/docs/upgrading-from-v5#fetch-versus-xhr
