### ISSUE TITLE
how to pass current view to ajax call

### ISSUE THREAD

**Issue by alimashalkpu** [fullcalendar/fullcalendar#6774]
### Checklist

Please mark these items with an [x]

  - [x] I've already searched through [existing tickets](https://fullcalendar.io/issues)
  - [x] Other people will find this feature useful

### Feature Description

Please describe what this feature will do.

### Visual Mockups

If you are requesting a new UI, please include a mockup.
If not, erase this section.

**Comment by alimashalkpu** [comment]
this is useful when we have different event category based on currency view. for example show the number of session in month grid view

**Comment by acerix** [comment]
I believe this existing ticket captures this need:
https://github.com/fullcalendar/fullcalendar/issues/4660
↑
Please visit the above issue, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates.
