### ISSUE TITLE
eventTimeFormat returns the wrong time

### ISSUE THREAD

**Issue by pavsidhu** [fullcalendar/fullcalendar#6779]
### Reduced Test Case

https://codesandbox.io/s/sleepy-black-2my570?file=/src/app/app.component.ts

### Bug Description

I expect the event time in `info.start.marker` and `info.end.marker` to match the date I put in but the date is an hour ahead after British Daylight Savings Time (DST)

**Comment by acerix** [comment]
By default, the times are stored with "UTC-coercion" as explained here: https://fullcalendar.io/docs/timeZone#UTC-coercion

You can get the actual time like `date.toUTCString()`:

https://codesandbox.io/s/laughing-cray-l6o1jb?file=/src/app/app.component.ts
