### ISSUE TITLE
listMonth does not render event with the last date of month 

### ISSUE THREAD

**Issue by jyotisingh-tudip** [fullcalendar/fullcalendar#6784]
### Bug Description

Looks like the fullCalendar is not rendering the event with the last date of the month. For example, I created an event on the 31st of march with the start time as 6:30 p.m., then that event is not shown in the listMonth view.

This issue is only happening for the events with the last date of the month whose start time is 6:00 p.m. or after that.

I have attached two images. When the fullCalendar view is "month" the event is visible, but when the event is rendered with the "listMonth" view the event is not rendered.

Steps to reproduce:

Create an event with date:
 - start: 2022-03-31 6:30 PM, end: 2022-03-31 7:30 PM
 - Render the event in listMonth view.
 
### Screenshots
![Screenshot 2022-03-24 at 2 08 07 PM](https://user-images.githubusercontent.com/75324738/160413315-30aa9dba-4e75-4a5c-8b9f-0494165646a7.png)
![Screenshot 2022-03-24 at 2 11 34 PM](https://user-images.githubusercontent.com/75324738/160413322-a416daca-f70c-4f8a-b69b-f08a53ea0e0c.png)

**Comment by rohandani-tudip** [comment]
Yes, @jyotisingh-tudip I am also facing the same issue.
Would wish this to get resolved soon.

Thanks!

**Comment by acerix** [comment]
Would you be able to post a [runnable, stripped-down demonstration of the bug](http://fullcalendar.io/wiki/Reduced-Test-Cases/)? Would really appreciate it because the time saved reproducing will be time spent fixing.

**Comment by rohandani-tudip** [comment]
Hello @acerix,
Thanks for a prompt reply,

I was able to solve this.
Seems the problem was from our side.

Thanks again!!!
