### ISSUE TITLE
In the Timeline View, I want to add a custom IOCN for each time cell

### ISSUE THREAD

**Issue by airzhanglin** [fullcalendar/fullcalendar#6786]
### Reduced Test Case

[TEST CODE](https://codepen.io/acerix/pen/yLpMMPL?editors=1010)

### Bug Description
In the Timeline View, I want to add a custom icon to each grid. I set it in resourceLaneContent. Why only the first column, after 12pm, is not added?

### Screenshots

![image](https://user-images.githubusercontent.com/16433124/160512906-9aa3df75-a75a-46db-bc21-95a44cb8bc78.png)

**Comment by acerix** [comment]
I believe this existing ticket captures this need:
https://github.com/fullcalendar/fullcalendar/issues/5677
↑
Please visit the above issue, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates.
