### ISSUE TITLE
Locales not working on Internet Explorer 11

### ISSUE THREAD

**Issue by BC-M** [fullcalendar/fullcalendar#6790]
### Reduced Test Case

The locales from jsdelivr not working on Internet Explorer 11 due to usage of ES6 syntax ([Enhanced object literals](https://github.com/lukehoban/es6features#enhanced-object-literals)). 

You can try it here: [codepen](https://cdpn.io/pen/debug/BaJwoXK?authentication_hash=xJkjOVbeaaDM)

This example used the [de locale from jsdelivr](https://cdn.jsdelivr.net/npm/fullcalendar@5.10.2/locales/de.js).

### Bug Description

It seems that the locales delivered on jsdelivr are not affected by the rollup configuration changes discussed here: #6014

#### Calendar with "de"-locale on Internet Explorer displayed "en"-locale

<img width="1728" alt="localized calendar on Internet Explorer 11" src="https://user-images.githubusercontent.com/40334865/161075826-23c7804d-01e5-4187-a25e-d5d982aebebc.png">

##### Syntax error in console

<img width="662" alt="syntax error in console" src="https://user-images.githubusercontent.com/40334865/161075823-ba92beeb-7245-4f3e-b2f8-5ce947579098.png">

##### Syntax error in source

<img width="650" alt="syntax error in js" src="https://user-images.githubusercontent.com/40334865/161075805-eda0b30b-3988-4a8c-9b66-b94d06a011c0.png">

#### Same example on Firefox (works as expected)

<img width="1728" alt="Bildschirmfoto 2022-03-31 um 16 17 51" src="https://user-images.githubusercontent.com/40334865/161077037-570c0aa2-833b-4d6c-9ac4-8236763f4e94.png">

**Comment by BC-M** [comment]
I also noticed that template strings are also not supported by Internet Explorer 11. [Look here](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Template_literals#browser_compatibility)

**Comment by arshaw** [comment]
This has been fixed in [v5.11.3](https://github.com/fullcalendar/fullcalendar/releases/tag/v5.11.3)

Please visit https://fullcalendar.io/docs/localization in IE11.

Here's a screenshot of MS Edge in IE11 mode:
![Screen Shot 2022-08-23 at 6 08 04 PM](https://user-images.githubusercontent.com/56520/186275114-e679edad-038c-4f71-8dba-3cf1cea7211d.png)
