### ISSUE TITLE
Monday as Start Day for Obsidian Plugin of FC

### ISSUE THREAD

**Issue by qalisto** [fullcalendar/fullcalendar#6792]
### Checklist

Please mark these items with an [x]

  - [x ] I've already searched through [existing tickets](https://fullcalendar.io/issues)
  - [x ] Other people will find this feature useful

### Feature Description

Enable Monday to be the first day vs Sunday (European standard)

I am astonished this option is not available.  I don't see it.  Have I missed it?  I searched.  Commented in Obsidian Forum.

**Comment by acerix** [comment]
It is based on locale or can be set with [firstDay](https://fullcalendar.io/docs/firstDay).
