### ISSUE TITLE
Just updated to 5.10.2 from 5.5.x and resourceTimeGridDay will not show

### ISSUE THREAD

**Issue by SiNi-Si** [fullcalendar/fullcalendar#6793]
### Reduced Test Case
no changes to code, just lib updated

Can't show live site for customer in admin area

calendar_day = new FullCalendar.Calendar(calendar_d, {
        schedulerLicenseKey: 'xxxxxx-fcs-xxxxxxxxx',
        initialView: 'resourceTimeGridDay',
        editable: true,
        selectable: true,
        droppable: true,
        eventResizableFromStart: true,
        eventStartEditable: true,
        height: 'auto',
        slotMinTime: Shop_start_Time_all,
        slotMaxTime: Shop_end_Time_all_Plus,
        visibleRange: {
            start: Shop_start_Time_all,
            end: Shop_end_Time_all
        },

### Bug Description

After update of lib,  from 5.5x to 5.10.2

resourceTimeGridDay  no longer shows

### Screenshots
before update
https://bikenuts.uk/before.jpg

After update
https://bikenuts.uk/after.jpg 

If the bug is visual, include a screenshot if possible.
If not, erase this section.

**Comment by acerix** [comment]
Would you be able to post a [runnable, stripped-down demonstration of the bug](http://fullcalendar.io/wiki/Reduced-Test-Cases/)? Would really appreciate it because the time saved reproducing will be time spent fixing.

**Comment by SiNi-Si** [comment]
Hi acerix,

I will work on that.  I will send you login information via the email I have of yours

Si
