### ISSUE TITLE
"validRange" should take hours and minutes into account

### ISSUE THREAD

**Issue by kumikumi** [fullcalendar/fullcalendar#6797]
### Checklist

Please mark these items with an [x]

  - [x] I've already searched through [existing tickets](https://fullcalendar.io/issues)
  - [x] Other people will find this feature useful

### Feature Description

When a valid range is specified for the calendar, don't disregard the hours and minutes of the range.

https://codepen.io/kumikumi/pen/jOYZxRV?editors=0110

In the above example, user should *not* be able to move the event to before 12pm on tuesday, or after 12pm on friday. There should also be a visual indication (or it should be possible to add one with CSS) for the exact valid range, not just for full days outside of the valid range.

**Comment by acerix** [comment]
I believe this existing ticket captures this need:
https://github.com/fullcalendar/fullcalendar/issues/5224
↑
Please visit the above issue, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates.
