### ISSUE TITLE
While creating a new event, show conflicts with recurring events

### ISSUE THREAD

**Issue by philharmonie** [fullcalendar/fullcalendar#6812]
### Checklist
  - [x] I've already searched through [existing tickets](https://fullcalendar.io/issues)
  - [x] Other people will find this feature useful

### Feature Description

When I add a new event, find out, if this will be in conflict with an **existing recurring** event.

I am asking as for the setup of a recurring event, I have a start end end, or maybe the recurring event goes into infinity. Thus, I don't have an exact date that I can compare. Basically I have the start date only.

**Comment by acerix** [comment]
You can use [eventOverlap](https://fullcalendar.io/docs/eventOverlap) which is called if there is an existing event.

**Comment by philharmonie** [comment]
@acerix This will work for moving and resizing events. I want to avoid adding, if there is an event.
