### ISSUE TITLE
Incorrect scaling of dates

### ISSUE THREAD

**Issue by jdabucol-metrix** [fullcalendar/fullcalendar#6821]
### Reduced Test Case

"not reproducible with a link"
When rendering the bar for the duration of the date is not rendered correctly

### Bug Description

We have two date values (a start and an End) pair for each JSON array element.
One of the dates starts at April 5, 2022 and ends at Sept 30, 2022, the other starts at April 13 and ends in April 30.
The timezones are handled and parsed correctly but when it is rendered its short a couple of days. When scrolling to the following month it also displays the same issue. This also includes the week view where it stops at friday

The first attached image is for both data and it should end at the 30th. The second image should be from the first of the month to the end of the month since the end date is September 30

### Screenshots

![image](https://user-images.githubusercontent.com/17575315/165180191-8ed07833-63a5-45ee-9cdd-a90000eb08cc.png)
![image](https://user-images.githubusercontent.com/17575315/165180210-427e1d74-b5c0-4db5-955f-5daa15d9f90e.png)

**Comment by acerix** [comment]
Would you be able to post a [runnable, stripped-down demonstration of the bug](http://fullcalendar.io/wiki/Reduced-Test-Cases/)? Would really appreciate it because the time saved reproducing will be time spent fixing.
