### ISSUE TITLE
End time incorrect for next-day events using nextDayThreshold React

### ISSUE THREAD

**Issue by bartvdklu** [fullcalendar/fullcalendar#6831]
### Reduced Test Case

https://codesandbox.io/s/goofy-fast-24hyll?file=/src/DemoApp.jsx

### Bug Description

When using the React component of the Fullcalender I came across this bug. When there is an event of which the end date and end time is in the next day (before the nextDayThreshold) it renders the end time as 00:00. Is there a way to just display the correct end time? In the Reduced test case it should display "02:00" but now it displays "00:00".

The nextDayThreshold is now "02:30:00". I get that if I remove the threshold it displays everything the correct way but I need it to show in a single day cell nog multiple days if the calendar event ends at 02:00 for example.

Result now:
<img width="147" alt="Schermafbeelding 2022-04-29 om 11 13 06" src="https://user-images.githubusercontent.com/33124155/165916807-06e21cf0-927e-4eb0-b9ff-e37e360f6779.png">

Desired result:
<img width="146" alt="Schermafbeelding 2022-04-29 om 11 13 46" src="https://user-images.githubusercontent.com/33124155/165916903-6e865c19-70b7-4bac-80a3-40426499af83.png">

**Comment by acerix** [comment]
I believe this existing ticket captures this need:
https://github.com/fullcalendar/fullcalendar/issues/3038
↑
Please visit the above issue, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates.

**Comment by vimonteglione** [comment]
I'm having the same issue, and it seems that the mentioned ticked doesn't really address it. Were you able to solve it? I also wonder if it only happens when using the React version.

**Comment by nvloc120** [comment]
I'm facing this issue too, I'm using angular. Any updates on this?
