### ISSUE TITLE
EventWidth based one view/EvenDidMount Problem

### ISSUE THREAD

**Issue by ambicoder** [fullcalendar/fullcalendar#6832]
### Reduced Test Case
 Here is the case [https://codepen.io/deoman12/pen/MWEjZyr?editors=0110](url)

### Bug Description
I am trying to set EventWidth using EventDidMount...line 11...different with depending on the view.
Upon fetching the event in TimeGridWeek EventDidMount fires and the css is applied.
Go to day view...you will see that the **css is not aplied**..it stays the same.-cause **EventDIdMount Does not fire again.**

In day view again click prev,next buttons..the css **is applied** this time....after that go to Week View...css not applied…probably for the same reason as above-**EventDIdMoun does not fire.**

Is there sth a miss here...it looks like a bug to me.
Is there an other way I could adjust eventWidth based on view?

Css maybe?

### Screenshots

If the bug is visual, include a screenshot if possible.
If not, erase this section.

**Comment by acerix** [comment]
`eventDidMount` is only or attaching callbacks to the DOM element for example, it's not called for events that are already rendered, even in another view. 

You can use `eventClassNames` to set a CSS class or supply custom HTML with `eventContent` and set styles in there.
