### ISSUE TITLE
Using @fullcalendar/vue3 in VSCODE warns that "the JSX element class does not support features because it does not have the" props "attribute." How do I remove the warning?

### ISSUE THREAD

**Issue by Ben-Ben-B** [fullcalendar/fullcalendar#6842]
### Reduced Test Case

[You must paste a link to a [REDUCED TEST CASE](https://fullcalendar.io/reduced-test-cases).
If you do not, this issue will automatically be closed.
To prevent this, include the text "not reproducible with a link" (assuming it's true).](https://codepen.io/pen?editors=0010)

### Bug Description

Using @fullcalendar/vue3 in VSCODE warns that "the JSX element class does not support features because it does not have the" props "attribute." How do I remove the warning?

vue3 -V 3.2.33
fullcalendar -V 5.11.0
### Screenshots

![Uploading image.png…]()n.

**Comment by acerix** [comment]
Would you be able to post a [runnable, stripped-down demonstration of the bug](http://fullcalendar.io/wiki/Reduced-Test-Cases/)? Would really appreciate it because the time saved reproducing will be time spent fixing.
