### ISSUE TITLE
Translate year button text

### ISSUE THREAD

**Issue by maxrydqvist** [fullcalendar/fullcalendar#6843]
### Bug Description
locales/sv.js is missing year for property buttonText. It should be "year: "År". Here is an example where i added it manually:
![Capture](https://user-images.githubusercontent.com/71756853/167139757-a0560ec2-cdd7-4d56-b87e-18d1225c6cab.PNG)

**Comment by arshaw** [comment]
However, it will be possible to launch year text for Swedish by itself

**Comment by arshaw** [comment]
I realized there's already a ticket for this:
https://github.com/fullcalendar/fullcalendar/issues/4193
↑
Please visit the above issue, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates.
