### ISSUE TITLE
Timeline Drag&Drop not working if calendar is in a dialog on top of another calendar

### ISSUE THREAD

**Issue by RonRadtke** [fullcalendar/fullcalendar#6846]
### Reduced Test Case
https://codepen.io/ronradtke/pen/ExWBBQw

### Bug Description

We are rendering a timeline showing the calendar. For editing proposes of single itmes we show a dialog with an own timeline view. 
Within the dialog Drag and drop of events is not working.
As soon as the timeline in the background (so not the one in the dialog) is removed or hidden Drag&Drop works as expected.
It seems like the  Drop areas are not recogniced correctly since the events seem to snap at "random" positions based on the calendar in the background.

In the pen you can see the issue when trying to D&D events in the Dialog

**Comment by acerix** [comment]
I believe this existing ticket captures this need:
https://github.com/fullcalendar/fullcalendar/issues/5026
↑
Please visit the above issue, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates.
