### ISSUE TITLE
Position of events in week view all at the bottom regardless the start and end time

### ISSUE THREAD

**Issue by floviolleau** [fullcalendar/fullcalendar#6847]
### Reduced Test Case

"not reproducible with a link"

### Bug Description

I'm using the latest v5 of this project with es6 mode (https://fullcalendar.io/docs/initialize-es6) and I have an issue regarding the position of events in week view. 

Firefox latest / Chrome latest

#### What do you expect to happen?
Event should be positioned at start and end time defined

#### What happens instead?
Events are positioned at the bottom

#### code
```ts
import { Calendar } from '@fullcalendar/core';
import dayGridPlugin from '@fullcalendar/daygrid';
import timeGridPlugin from '@fullcalendar/timegrid';
import listPlugin from '@fullcalendar/list';

[...]

fullCalendar = new Calendar(calendarElt, {
    plugins: [ dayGridPlugin, timeGridPlugin, listPlugin ],
    initialView: 'dayGridMonth',
    headerToolbar: {
        left: 'prev,next today',
        center: 'title',
        right: 'dayGridMonth,timeGridWeek,listWeek'
    },
    events: [
        {
            title: 'Meeting 1',
            start: '2022-05-09T09:00:00',
            end: '2022-05-09T12:00:00',
        },
        {
            title: 'Meeting',
            start: '2022-05-10T10:30:00',
            end: '2022-05-10T12:30:00'
        },
    ],
    eventClick,
});
fullCalendar.render();
```
#### What happens instead?
![image](https://user-images.githubusercontent.com/5442973/167631992-9939b711-c3ab-45d3-b125-5db8f8c53a50.png)

**Comment by acerix** [comment]
Would you be able to post a [runnable, stripped-down demonstration of the bug](http://fullcalendar.io/wiki/Reduced-Test-Cases/)? Would really appreciate it because the time saved reproducing will be time spent fixing.
