### ISSUE TITLE
Wrong link?

### ISSUE THREAD

**Issue by abelardolg** [fullcalendar/fullcalendar#6851]
### Checklist

Please mark these items with an [x]

  - [x ] I've already searched through [existing tickets](https://fullcalendar.io/issues)
  - [x ] Other people will find this feature useful

### Feature Description

Please describe what this feature will do.
Edit events

This [page](https://fullcalendar.io/docs/editable) doesn't point it out to a calendar with editable events. 

Best regards.

**Comment by acerix** [comment]
The "editable" setting means that events can be dragged and dropped on a new date which seems to be working fine that demo.  If that is not working please include details of which browser you are using.

**Comment by abelardolg** [comment]
Yes, it works fine for that demo. I understood "editable" as they can be edited, changed their info.
Best regards.
