### ISSUE TITLE
Custom element in header or footer particularly a dropdown/select element for the Angular version of the library

### ISSUE THREAD

**Issue by BrunoElo** [fullcalendar/fullcalendar#6852]
### Checklist

Please mark these items with an [x]

  - [x] I've already searched through [existing tickets](https://fullcalendar.io/issues)
  - [x] Other people will find this feature useful

### Feature Description
Please describe what this feature will do.
This feature will allow people add custom dropdowns for other use cases that buttons can't handle
### Visual Mockups
![dropdown element mockup](https://user-images.githubusercontent.com/25552096/168228566-9e6ff57a-72f5-4037-b113-303ba1ed598f.png)

If you are requesting a new UI, please include a mockup.
If not, erase this section.

**Comment by acerix** [comment]
I believe this existing ticket captures this need:
https://github.com/fullcalendar/fullcalendar/issues/496
↑
Please visit the above issue, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates.

**Comment by venumbj** [comment]
can u please share me the code how to add dropdown in full calendar please

**Comment by venubabu1996** [comment]
can u please provide me the code how to add dropdown in full calendar
