### ISSUE TITLE
rrule source files not found during 'npm run build'

### ISSUE THREAD

**Issue by timmellis** [fullcalendar/fullcalendar#6858]
### Reduced Test Case

not reproducible with a link

### Bug Description

I'm using rrule in my project and it works great on my local development server, but when I run `npm run build` I get a wall of errors that all start with "Failed to parse source map from",  for example: 
`Failed to load source map from  '[project_path]/node_modules/rrule/src/cache.ts' file: Error: ENOENT: no such file or directory, open '[project_path]/node_modules/rrule/src/cache.ts'`

When I attempt to load the project onto a remote server (like Netlify), the basic calendar features still work, but anything relying on rrule (like semi-weekly events) will not render. 

I'm confused because in digging through the project's `node_module` directories, I find both `node_modules/rrule` and `node_modules/@fullcalendar/rrule`, but there is no "src" directory in either location. Why is it trying to load files from a directory that doesn't exist?

(The screenshot below is only about 2/3 of the errors, they just don't all fit on one screen, and at a certain point I'm pretty sure they all stem from the same problem.)

### Screenshots

![image](https://user-images.githubusercontent.com/98844276/169147229-5effccf9-a714-4860-89f6-159bd09ff8e7.png)
![image](https://user-images.githubusercontent.com/98844276/169147382-535099bd-3bdc-49d3-8404-7d1d234a2831.png)
![image](https://user-images.githubusercontent.com/98844276/169147389-9ff01099-1c4d-4af7-9252-f3a5fd3ec2cf.png)

**Comment by acerix** [comment]
I tried in the React example project and also building locally and didn't get any errors:

https://codesandbox.io/s/boring-archimedes-lg6m0v?file=/src/DemoApp.jsx

Maybe it will help to delete node_modules, clear npm cache and reinstall packages, or to use the example project as a starting point. If there is still an error please provide a [runnable, stripped-down demonstration of the bug](http://fullcalendar.io/wiki/Reduced-Test-Cases/) or steps to reproduce the issue.

**Comment by timmellis** [comment]
Thanks for the reply.

I tried deleting and reinstalling all node_module packages, but I get the same issue when I try to run npm build. I will experiment with the example project you provided, is there a simple way to clone it down? (i'm not super familiar with codesandbox.io) 

The repo for my project is [here](https://github.com/timmellis/green_thumb_frontend), not sure if the problem will be reproducible on another machine, but there are no specific steps other than "try to run npm build prior to deploying." (The site expects to load user and event details from a database so you won't be able to view the site locally, but that shouldn't impact the ability to run npm build and compile the node_modules for production. )

**Comment by anatoly314** [comment]
@timmellis , have you found a solution for this issue? I've encountered the same issue.
