### ISSUE TITLE
Time slots do not fill print version in day view

### ISSUE THREAD

**Issue by acerix** [fullcalendar/fullcalendar#6859]
### Reduced Test Case

https://fullcalendar.io/docs/timeline-standard-view-demo

### Bug Description

The timeslots are cut off halfway instead of filling the page.  Changing to version 5.10.0 works as expected.

Reported in https://fullcalendar.freshdesk.com/a/tickets/4897

### Screenshots

![screenshot-3c511afc](https://user-images.githubusercontent.com/379534/169346649-d7103749-50cb-4782-ba05-cf536e2180ba.png)

**Comment by arshaw** [comment]
This is now fixed in [v6.1.5](https://github.com/fullcalendar/fullcalendar/releases/tag/v6.1.5)

Please the updated page: https://fullcalendar.io/docs/timeline-standard-view-demo

Please let us know if there are further related issues.
