### ISSUE TITLE
getEventSourceById doesn't work

### ISSUE THREAD

**Issue by lafeber** [fullcalendar/fullcalendar#6863]
### Reduced Test Case

See https://codesandbox.io/s/full-calendar-demo-forked-8r2e9w

### Bug Description

getEventSourceById doesn't seem to be working. In the sandbox above I expect to get the first event, instead I get null. Also tested on version 5.10.

**Comment by acerix** [comment]
`getEventSourceById` returns the source with the specified id (eg. `source.id`).  To lookup the source from the event id, use `getEventById(event.id).source.id`.
