### ISSUE TITLE
Recurring ICS events do not shift with timezone

### ISSUE THREAD

**Issue by IrisLiu-00** [fullcalendar/fullcalendar#6870]
### Reduced Test Case

https://codepen.io/IrisLiu-00/pen/XWZEwVv?editors=0010
You will need to circumvent a CORS error on the ICS link by clicking "Request Access" here: https://cors-anywhere.herokuapp.com/corsdemo

### Bug Description

Recurring events from an iCalendar do not get adjusted with timezones, while singular events do. I would expect both recurring and singular events to be shifted with timezones. 

### Screenshots

![image](https://user-images.githubusercontent.com/56804180/171426125-91d8ef82-d76d-481e-9ca7-f4c276cc3a55.png)
![image](https://user-images.githubusercontent.com/56804180/171426618-ae9d4145-feb7-44bd-90d5-d17c2d933167.png)

**Comment by acerix** [comment]
I believe this existing ticket captures this need:
https://github.com/fullcalendar/fullcalendar/issues/5273
↑
Please visit the above issue, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates.
