### ISSUE TITLE
slotLabelContent doesn't have access to calendar timezone

### ISSUE THREAD

**Issue by piotrpalek** [fullcalendar/fullcalendar#6879]
### Checklist

Please mark these items with an [x]

  - [x] I've already searched through [existing tickets](https://fullcalendar.io/issues)
  - [x] Other people will find this feature useful

### Feature Description

When using the `slotLabelContent` callback function, it would be beneficial to be able to access the `view.dateEnv.timeZone` property properly. Currently TypeScript is complaining that: `Property 'dateEnv' is private and only accessible within class 'ViewApi'.ts(2341)`.

It would be good to have access to this property, otherwise it's hard to properly format the date, as we don't know which timezone is currently used in the calendar.

**Comment by acerix** [comment]
You could store the timeZone setting outside the calendar to use for formatting to avoid accessing a private prop.  There is also the Moment Timezone plugin which formats based on the current setting.

**Comment by piotrpalek** [comment]
Both are true, thought the 2nd one doesn't make much sense to me, as moment-timezone doesn't necessarily need to be the same as the calendar timezone (depending on what you do in your app).

But more importantly, they look to me like workarounds for things that are lacking. FullCalendar itself uses this data (meaning `timeZone` in `dateEnv`) to render the text for the header originally afaik, so it would be nice have the same capabilities when providing our own Content, without having do rework a bunch of stuff.

I'm also wondering, why shouldn't we have access to this data?

**Comment by arshaw** [comment]
You can already do this via `view.calendar.getOption('timeZone')`

https://codepen.io/arshaw/pen/gOKqPYw?editors=001
