### ISSUE TITLE
Display the timeline horizontally with the left column as month/week's days

### ISSUE THREAD

**Issue by duyphanNovasquare** [fullcalendar/fullcalendar#6880]
### Checklist

Please mark these items with an [x]

  - [x] I've already searched through [existing tickets](https://fullcalendar.io/issues)
  - [x] Other people will find this feature useful

### Feature Description

Display the timeline horizontally instead of vertically, with the left column is full of month or week's days.

### Visual Mockups
<img width="944" alt="Screenshot 2022-06-07 203135" src="https://user-images.githubusercontent.com/97424172/172395026-3b9ad5ae-f4dd-406b-ba09-ce9c09bdb24e.png">

**Comment by duyphanNovasquare** [comment]
I want to buy the premium package if it has the requested feature above.

**Comment by acerix** [comment]
I believe this existing ticket captures this need:
https://github.com/fullcalendar/fullcalendar/issues/6024
↑
Please visit the above issue, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates.

**Comment by duyphanNovasquare** [comment]
Thank you very much.
