### ISSUE TITLE
man make it responsive

### ISSUE THREAD

**Issue by Mostafaben** [fullcalendar/fullcalendar#6882]
### Reduced Test Case

You must paste a link to a [REDUCED TEST CASE](https://fullcalendar.io/reduced-test-cases).
If you do not, this issue will automatically be closed.
To prevent this, include the text "not reproducible with a link" (assuming it's true).

### Bug Description

Describe how to recreate the bug.
What do you expect to happen?
What happens instead?

### Screenshots

If the bug is visual, include a screenshot if possible.
If not, erase this section.

**Comment by acerix** [comment]
I believe this existing ticket captures this need:
https://github.com/fullcalendar/fullcalendar/issues/3187
↑
Please visit the above issue, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates.
