### ISSUE TITLE
Calendar has empty aria-labelledby attribute with headerToolbar: false

### ISSUE THREAD

**Issue by sfishmonger** [fullcalendar/fullcalendar#6884]
### Reduced Test Case

Link to the codepen
https://codepen.io/spoissonnierAz/pen/RwQeYJQ

#### Describe how to recreate the bug.

Instanciate a FullCalendar on version 5.11.0.
Set the configuration option headerToolbar to false to hide header tool bar, by doing this the 'aria-labelledby'  of the calendar will remain but will be empty

#### What do you expect to happen?

Do not include the attribute 'aria-labelledby' if empty

#### What happens instead?

The attribute 'aria-labelledby' is empty
![image](https://user-images.githubusercontent.com/27729497/172859814-a9ea517b-2ef4-4589-9bb5-02240b5303a4.png)

**Comment by arshaw** [comment]
Hi @jamesnsummers , this seems like low-hanging fruit that I'll try to fix for the next release.

**Comment by arshaw** [comment]
Fixed in [v6.1.11](https://github.com/fullcalendar/fullcalendar/releases/tag/v6.1.11)

Updated repro:
https://codepen.io/arshaw/pen/GReLdxY
