### ISSUE TITLE
documentation

### ISSUE THREAD

**Issue by Tayfur** [fullcalendar/fullcalendar#6887]
### Checklist

Please mark these items with an [x]

  - [ ] I've already searched through [existing tickets](https://fullcalendar.io/issues)
  - [x ] Other people will find this feature useful

### Feature Description

Hello, it is a very nice library, but the documentation is very lacking, I think a little more information would be much better

### Visual Mockups

Hello, it is a very nice library, but the documentation is very lacking, I think a little more information would be much better

**Comment by acerix** [comment]
I believe this existing ticket captures this need:
https://github.com/fullcalendar/fullcalendar/issues/4878
↑
Please visit the above issue, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates.
