### ISSUE TITLE
Adaptive calendar not sized correctly when printing

### ISSUE THREAD

**Issue by mwoynarski** [fullcalendar/fullcalendar#6888]
### Reduced Test Case

Codepen: https://codepen.io/mwoynarski/full/bGLQoNZ

This is the same pen that was linked by @acerix in their reply to original ticket, simply updated to the latest version of Fullcalendar.

### Bug Description

This is a follow-up to #5707. That ticket has been closed with the instruction to create a new ticket if the problem persists.

When printing a calendar when using the premium  adaptive plugin, the calendar is not properly sized to the page.  On Firefox, it overflows the right-hand side of the page, and on Chrome, it doesn't fill the page.

This is occurring on version 5.11.0 from jsdeliver.

### Screenshots
![firefox](https://user-images.githubusercontent.com/143827/173130883-646a3ea8-1117-48a0-8e7f-f0f52c03f645.png)
![chrome](https://user-images.githubusercontent.com/143827/173130896-b0e138de-7404-4138-a18e-ab9b9604f27a.png)

**Comment by acerix** [comment]
I can see those issue in your demo, but it seems like a problem with printing the Codepen page, if I switch to "debug" view (only available after logging in), it prints correctly.

Assuming you have the same problem on your site, you can disable CSS and other components on the page to find what is causing that.

**Comment by boltex** [comment]
I just also tried the adaptivePlugin plugin. In my experience, it just make all events visible, and changes the color palette, but it still scales everything in relation to the screen with styles in pixels directly on the dom elements,  and not the page size with % or with 'colspans' like in version 3 of full Calendar.

  Which would always fit the page.

Are there more options for seting up the adaptivePlugin plugin? i didnt see any in the docs at https://fullcalendar.io/docs/print

Thanks for any help or comments on this issue!
