### ISSUE TITLE
dayCellDidMount modifications not retained on navigation

### ISSUE THREAD

**Issue by oliverguenther** [fullcalendar/fullcalendar#6891]
### Reduced Test Case

https://codepen.io/oliverguenther/pen/BaYvOOJ

### Bug Description

1. Use a hook like `daycellDidMount` in the calendar monthly view, e.g., adding a CSS class that colors a certain class of dates (such as non-repetitive non working days)
2. Click on next or previous
3. Dates are retained in the DOM, but any changes from dayCellDidMount is lost

### Screenshots
![image](https://user-images.githubusercontent.com/459462/173416216-7e87a4bf-f4b2-4551-a22e-945d711e972b.png)

![image](https://user-images.githubusercontent.com/459462/173416248-be4a6294-c48f-487e-89cc-41a07b052d3e.png)

This has been more or less explained in https://github.com/fullcalendar/fullcalendar/issues/6726#issuecomment-1039532398, but this means having access to the `el` property of the callback is limited to event handling. This appears to not be adequately documented. Is there any way to augment the internal rendering in any such way such adding a class on certain view elements that are _not_ events or resources?

**Comment by acerix** [comment]
`daycellDidMount` is only for things like adding callbacks, there is `dayCellClassNames` for setting classes on the element.

**Comment by oliverguenther** [comment]
Thanks for the clarification. For some reason, I dismissed the classNames hook as not being helpful in my case, but it works perfectly as you described. Sorry!
