### ISSUE TITLE
nowIndicator is not working correctly while using initialView: resourceTimelineWeek with Timeline View

### ISSUE THREAD

**Issue by firtk** [fullcalendar/fullcalendar#6893]
### Reduced Test Case

https://codepen.io/firtk/pen/bGLzxqq

### Bug Description

While using TimeLine view, if you set initial view `resourceTimelineWeek` and change it's slotDuration with the following code:
```
views: {
      resourceTimelineWeek: {
        slotDuration: { days: 1 },
      },
    },
```
`nowIndicator` is not working correctly.

### Work around
Use `calendar.changeView` after the render.
https://codepen.io/firtk/pen/xxYMBrp

**Comment by acerix** [comment]
It appears correct for me, what is the problem with it? It might help to include a screenshot.

**Comment by firtk** [comment]
Hey @acerix,
I added `now` settings to [Demo](https://codepen.io/firtk/pen/bGLzxqq) for to be more clear. And attaching screenshots for how it looks like and expected look.

How It Looks            |  Expected Look
:-------------------------:|:-------------------------:
![](https://user-images.githubusercontent.com/22756097/174457566-f661472c-8eda-4a0b-9719-07e4c48cf89a.png)  |  ![](https://user-images.githubusercontent.com/22756097/174457562-54eecda4-dc75-4cbb-8b80-8e59971b4737.png)

Browser: Chrome, Version 102.0.5005.115 (Official Build) (arm64)
fullcalendar scheduler version: 5.11.0

**Comment by acerix** [comment]
I believe this existing ticket captures this need:
https://github.com/fullcalendar/fullcalendar/issues/6175
↑
Please visit the above issue, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates.
