### ISSUE TITLE
dayMinWidth reports an error when using resourceTimeGrid

### ISSUE THREAD

**Issue by 13720203415** [fullcalendar/fullcalendar#6895]
### Bug Description

Vue refers to resourcetimegrid. When dayminwidth is added in option, no scrollgrid implementation appears.
I want to fix the width of each column so that I can slide horizontally when there are many columns.

### Screenshots

![1](https://user-images.githubusercontent.com/58166214/174933821-dda2508c-5239-4fb1-b83e-7f4db3c49b97.jpg)
![2](https://user-images.githubusercontent.com/58166214/174933988-190fb74f-7a24-4837-a8d6-f90e1455339c.jpg)
![1655866728807](https://user-images.githubusercontent.com/58166214/174934080-c8e61779-cf03-427c-abd4-70cf9f817952.jpg)
![1655866958878](https://user-images.githubusercontent.com/58166214/174934469-c850a162-c0e6-4e25-87a3-6f7175411875.jpg)

**Comment by acerix** [comment]
Would you be able to post a [runnable, stripped-down demonstration of the bug](http://fullcalendar.io/wiki/Reduced-Test-Cases/)? Would really appreciate it because the time saved reproducing will be time spent fixing.
