### ISSUE TITLE
`eventDrop` fires when dropping on another resource with `eventResourceEditable`: false

### ISSUE THREAD

**Issue by emcvey-administrate** [fullcalendar/fullcalendar#6899]
### Reduced Test Case
https://codepen.io/emmadministrate/pen/RwQXrpy

### Bug Description
Drag an event from one row to another. `eventResourceEditable` is false so you should not be able to. It does not visually appear that you can because the event does not appear to drag to that row. However, when you release the mouse `dropEvent` is called, and it has the `newResource` argument set to whatever resource the mouse was over. 

This had unintended consequences in our app. Yes, we can now check for that to work around it, but we should not have to. `newResource` should not be set when `eventResourceEditable` is false.

**Comment by emcvey-administrate** [comment]
Additional question: we have a license for this product. Is there a better way to reach out to have issues addressed than via GitHub?

**Comment by acerix** [comment]
Thanks, confirmed.

You can also email for support, you can get the address from sales@fullcalendar.io .

**Comment by acerix** [comment]
I just noticed there is already an issue for this:
https://github.com/fullcalendar/fullcalendar/issues/4943
↑
Please visit the above issue, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates.
