### ISSUE TITLE
Overlapping events dayMaxEvents "more" count is sometimes off

### ISSUE THREAD

**Issue by Chicken** [fullcalendar/fullcalendar#6900]
### Reduced Test Case

<https://codepen.io/AnttiCodes/pen/jOzNzMG>

### Bug Description

Sometimes with overlapping events and `dayMaxEvents`, the "more" count is off.  
See the reduced test case for an example. Make the window size smaller to trigger the feature and the bug.  
I'd expect the numbers to be 2 3 2 but they are 2 3 1.

### Screenshots

Normally
![27-120951](https://user-images.githubusercontent.com/45627874/175903816-2b7cd03b-3a6c-4214-a5b2-e26e66165bb1.png)

Reduced window size
![27-121013](https://user-images.githubusercontent.com/45627874/175903878-3eb537b3-d2ef-482a-8edb-b62ddf4a2b00.png)

Even more reduced window size (for some reason fixes it?)
![27-121028](https://user-images.githubusercontent.com/45627874/175903929-8db89560-09be-478b-a603-8743b8cece56.png)

The event also disappears from this popup
![27-121057](https://user-images.githubusercontent.com/45627874/175904009-24f61128-27ec-4f67-ab50-39d13e926e65.png)

**Comment by acerix** [comment]
Thanks, confirmed. Seems it may the same issue as in:
https://github.com/fullcalendar/fullcalendar/issues/6608
↑
Please visit the above issue, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates.

**Comment by arshaw** [comment]
Fixed in [v6.1.11](https://github.com/fullcalendar/fullcalendar/releases/tag/v6.1.11)

Updated repro:
https://codepen.io/arshaw/pen/RwdOyee
