### ISSUE TITLE
eventMouseEnter seems not fired in the more link, if events reaching the dayMaxEvents

### ISSUE THREAD

**Issue by dolphinotaku** [fullcalendar/fullcalendar#6906]
### Checklist

Please mark these items with an [x]

  - [X] I've already searched through [existing tickets](https://fullcalendar.io/issues)
  - [x] Other people will find this feature useful

### Feature Description
I created a popup notification (by popper.js) if mouse over on the event block through the eventMouseEnter event
but it does not get work in more if it reaching the dayMaxEvents

I think the eventMouseEnter would also fire in more just same as eventClick

Demo
https://codepen.io/DolphinOtaku/pen/dymoxaY?editors=0010

**Comment by acerix** [comment]
`eventMouseEnter` already works for those events, here's an example:

https://codepen.io/acerix/pen/wvmKraP?editors=001

Please post a [minimal, stripped-down demonstration](http://fullcalendar.io/wiki/Reduced-Test-Cases/) if there is a bug.
