### ISSUE TITLE
Event preview on mouse enter

### ISSUE THREAD

**Issue by EasyLifeBertolla** [fullcalendar/fullcalendar#6910]
- [x] I've already searched through [existing tickets](https://fullcalendar.io/issues)
  - [x] Other people will find this feature useful

### Feature Description
On entering the calendar the user should see a preview of the timeslot. Moving the mouse in the calendar moves the timeslot. Once he clicks on a specific cell the preview becomes an event.

### Benefits
With this feature the user wouldn't need to click to create an event and drag it to the selected spot but could do it right away, having the advantage of seeing how it fits in between all other events in the calendar.

**Comment by acerix** [comment]
I believe this existing ticket captures this need:
https://github.com/fullcalendar/fullcalendar/issues/4816
↑
Please visit the above issue, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates.
