### ISSUE TITLE
fullcalender superfluous DOM

### ISSUE THREAD

**Issue by pd1246** [fullcalendar/fullcalendar#6911]
### Reduced Test Case
https://codesandbox.io/s/reverent-field-lruptk?file=/src/DemoApp.vue:1951-1964

### Bug Description
After the project was packaged, FullCalender had a problem, and there was extra text in fullCalender's internal DOM, resulting in a style error.

### Screenshots
![1_0](https://user-images.githubusercontent.com/52770443/177679053-af315973-8289-44bc-8f9d-dc80f125d8c9.png)

**Comment by acerix** [comment]
I don't see the issue in your demo,  is there something I need to do to reproduce the issue?

**Comment by pd1246** [comment]
@acerix 
The problem is that I used Fullcalender in the electron- Vue project, and this problem will occur when I run the packaged program. There is no problem with the development environment Fullcalender. 
[https://github.com/hilanmiao/LanMiaoDesktop](url)
Adding a simple FullCalender to the open source project above, for packaging testing, can reproduce this problem .
![d250057f732858a87c2e5d5fd86c3ae](https://user-images.githubusercontent.com/52770443/178388592-ac0f45dd-33db-4c30-9605-c404d7f4a22c.png)
![192f08514224d110674013492250c95](https://user-images.githubusercontent.com/52770443/178388842-b2882f2a-1cac-46cf-b1f1-78a413388f96.png)

**Comment by acerix** [comment]
If there is a bug with the calendar, please provide a [runnable, stripped-down demonstration of the bug](http://fullcalendar.io/wiki/Reduced-Test-Cases/). Would really appreciate it because the time saved reproducing will be time spent fixing.
