### ISSUE TITLE
Creating events when updating from backend while dragging event

### ISSUE THREAD

**Issue by paulstelzer** [fullcalendar/fullcalendar#6913]
### Reduced Test Case
Demo project: https://github.com/paulstelzer/fullcalendar-issue

### Bug Description

If you drag an event while the events are updated (e.g. backend sends new events) the event will be duplicated and you get the same id multiple time in calendar.

As you can see in the video below, if you drag the event normal, wait for the backend update, everything is working fine. After update from backend the event will be moved back to the initial placement. But if you drag the item, wait for the backend update event and then leave the mouse up, the event will be duplicated. The getEvents() from fullcalendar has multiple events with the same id and even if you drag the newly created events, it will not be resetted with the backend event. You now have 2 or 3 or more events in fullcalendar although it should be only once.

### Screenshots

https://user-images.githubusercontent.com/20501666/178661239-a05b2f1a-c3f6-4cfc-8b59-bdce4467a388.mp4

**Comment by acerix** [comment]
I believe this existing ticket captures this need:
https://github.com/fullcalendar/fullcalendar/issues/6101
↑
Please visit the above issue, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates.
