### ISSUE TITLE
Fullcalendar CSS documention doesn't include *Premium* notification

### ISSUE THREAD

**Issue by EliezerB123** [fullcalendar/fullcalendar#6918]
### Reduced Test Case

(I haven't included a test case, because it's not reproducible with a link , aside from of course the website: https://fullcalendar.io/docs/css-customization )

### Bug Description

**Bug:**
On the pricing page here: https://fullcalendar.io/pricing it says that if you write any CSS, you're required to have a Premium license.
But on the page talking about CSS, here: https://fullcalendar.io/docs/css-customization it doesn't mention that at all.

**What do you expect to happen?**
I expect that the page talking about CSS should have a **[requires Premium](https://fullcalendar.io/pricing)** tag, mentioning that you cannot make any CSS modifications to the calendar without a Premium license. 

**What happens instead?**
There's no mention of requiring a premium license for making CSS modifications.... on the page about CSS modifications.

**Comment by acerix** [comment]
A premium license is not required to write CSS.  The message is saying that for with the premium license, anyone writing CSS for the project will need to be included in the number of developers on the license.
