### ISSUE TITLE
When a resource has multiple lines, the event row height does not calculate to match

### ISSUE THREAD

**Issue by jmuraca** [fullcalendar/fullcalendar#6919]
### Bug Description

When we render resources, if we add multiple resource in the same cell, and each resource is on a new <p> line, the resource cell expands, but the event cell height does not keep up. The resource <p> has a margin at the bottom that is not calculated and carried over to the event. For a large number of resources, this offset adds up and towards the bottom of the scroll screen the resource and event rows become misaligned.

What do you expect to happen?
I would like to see the corresponding event line height caluclate at the same height as the resources so that this misalignment doesn't occur.

What happens instead?
See screenshot for misalignment under multiple resources

### Screenshots

If the bug is visual, include a screenshot if possible.
If not, erase this section.

![image](https://user-images.githubusercontent.com/1421873/179246918-32b06994-c71f-4b39-a466-9fee823c90d1.png)

**Comment by acerix** [comment]
Would you be able to post a [runnable, stripped-down demonstration of the bug](http://fullcalendar.io/wiki/Reduced-Test-Cases/)? Would really appreciate it because the time saved reproducing will be time spent fixing.
