### ISSUE TITLE
In Chrome Browser Version 103.0.5060.134 (Official Build) (64-bit) , Fullcalendar(v5.11.0) "dateClick" and "select" props return the wrong the date values 

### ISSUE THREAD

**Issue by veera-clarbloc** [fullcalendar/fullcalendar#6923]
### Bug Description

I'm using the chrome browser (103.0.5060.134) , React js(v17.0.2), and  Full calendar (v5.11.0) . 
"dateClick" and "Select" props is returning incorrect date values when you selected any dates. 

This problem is not happening in Firefox browser. It's happening only in Chrome browser.
Let us know, How to fix this issue at the earliest as we are mid of project development;

### Screenshots

30.7.22 date selected in the calendar. but, select props returns 21.7.22 date as response. you can view the result in below screenshot

![image](https://user-images.githubusercontent.com/96036146/180180607-4f6b0682-8cb9-46af-a531-1b2facb1f33e.png)

**Comment by veera-clarbloc** [comment]
Please respond for this issue as soon as possible

**Comment by acerix** [comment]
Would you be able to post a [runnable, stripped-down demonstration of the bug](http://fullcalendar.io/wiki/Reduced-Test-Cases/)? Would really appreciate it because the time saved reproducing will be time spent fixing.
