### ISSUE TITLE
Support importmaps

### ISSUE THREAD

**Issue by anatoljevich** [fullcalendar/fullcalendar#6933]
### Checklist

Please mark these items with an [x]

  - [x] I've already searched through [existing tickets](https://fullcalendar.io/issues)
  - [x] Other people will find this feature useful

### Feature Description

Hi,
I spent some time trying to import fullcalendar to Rails7 via importmaps. 
The only working solution I was able to find is https://stackoverflow.com/a/72772417/1929618 which can not be considered as good.

I also tried import @fullcalendar/core as described in ES6 initialization section. 

pin '@fullcalendar/core', to: 'https://cdn.skypack.dev/@fullcalendar/core'

import { Calendar } from '@fullcalendar/core'
var calendarEl = document.getElementById('calendar')
var calendar = new Calendar(calendarEl, {... })

It seems the browser loads correct files (core.js, common.js, preact.js, tslib.js), but executed not in correct order, so it raises an error in common.js on FullCalendarVdom check.

if (typeof FullCalendarVDom === "undefined") {
  throw new Error("Please import the top-level fullcalendar lib before attempting to import a plugin.");
}

Is there a way to add the correct way of initialization via importmaps to documentation?
Thanks

**Comment by arshaw** [comment]
In v6 (beta), this is fixed:
https://codepen.io/arshaw/pen/poKqLqL?editors=1000

**Comment by arshaw** [comment]
I'll make better documentation on how to use importmaps

**Comment by jjf21** [comment]
Thanks for you message @arshaw !
do you have any idea when v6 will be release ?

**Comment by arshaw** [comment]
Released in [v6.0.0](https://github.com/fullcalendar/fullcalendar/releases/tag/v6.0.0)
