### ISSUE TITLE
eventResize & groupId Bug

### ISSUE THREAD

**Issue by michalfordonski** [fullcalendar/fullcalendar#6938]
### Reduced Test Case
[REDUCED TEST CASE](https://fullcalendar.io/reduced-test-cases).

https://codepen.io/michalf29694/pen/PoRewPm

### Bug Description

In version 4, using groupId and eventResize there is a problem that the reservation that I do not change also changes the size in the preview. Can it be turned off for eventResize and leave the groupId only for transferring the reservation (time change)? When changing, if the related event is smaller than the changed time, it will disappear until you reload the entire calendar. I would like it to simply move the next event rather than resize it when resizing the linked event.

### Screenshots
![Uploading Zrzut ekranu 2022-08-5 o 08.13.47.png…]()
<img width="524" alt="Zrzut ekranu 2022-08-5 o 08 13 04" src="https://user-images.githubusercontent.com/31201382/183013520-8970c5be-d8e8-4b2e-b948-34e8dd6f7fce.png">
<img width="484" alt="Zrzut ekranu 2022-08-5 o 08 13 18" src="https://user-images.githubusercontent.com/31201382/183013524-1932b85f-99d5-4f86-938f-0694da04cb9d.png">
<img width="496" alt="Zrzut ekranu 2022-08-5 o 08 13 27" src="https://user-images.githubusercontent.com/31201382/183013527-23d30a59-4830-4091-b6f3-3d5a220cadfc.png">
<img width="491" alt="Zrzut ekranu 2022-08-5 o 08 13 35" src="https://user-images.githubusercontent.com/31201382/183013529-054c836d-098f-47a3-ae14-ef8c02648105.png">

**Comment by acerix** [comment]
I believe this existing ticket captures this need:
https://github.com/fullcalendar/fullcalendar/issues/5965
↑
Please visit the above issue, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates.
