### ISSUE TITLE
Adding elements in Day cell

### ISSUE THREAD

**Issue by LamprosPitsillos** [fullcalendar/fullcalendar#6942]
### Checklist

Please mark these items with an [x]

  - [x] I've already searched through [existing tickets](https://fullcalendar.io/issues)
  - [X] Other people will find this feature useful

### Feature Description

An intuitive way of adding elements to the day cell box like labels , buttons ,html elements etc.

### Visual Mockups

![hell_W](https://user-images.githubusercontent.com/61395246/183652993-8e159046-f071-4827-a14a-d33e01f757d9.png)

I searched everywhere but cant find anything on how to add elements in the day cell. Only saw some hacky ways from 2012.
Is there a way to currently do this ? I want every cell except weekends to have a label on the bottom of the cell.

**Comment by acerix** [comment]
You could add background events with custom HTML for that or add HTML to the day label with `dayCellContent`.  

https://fullcalendar.io/docs/background-events.

**Comment by LamprosPitsillos** [comment]
I tried the `dayCellContent` but it removes the date on the top right, which i still want visible.
Could you point me to a code example please?

**Comment by acerix** [comment]
You would need to include the day number in the html, here's an example:

https://codepen.io/acerix/pen/jOzvgGV?editors=0110
