### ISSUE TITLE
dayGrid switches to multiple rows (month view) when visibleRange is exactly one month

### ISSUE THREAD

**Issue by d53520** [fullcalendar/fullcalendar#6946]
### Reduced Test Case

https://codepen.io/d53520/pen/gOedbVL

### Bug Description

in my company our month calender is like from Jul 26 to Aug 25. so i try to use changeview to defined the view range
 range from ** Jul26 to Aug25**  or **Jul26 to Aug27** view work well
but when range is from **Jul26~Aug26** view works like month view that is not I want.

### Screenshots
**what I want**
![image](https://user-images.githubusercontent.com/18735885/184085105-c5432300-72d1-4128-ac3f-ab54bf5366b2.png)

**no I want**
![image](https://user-images.githubusercontent.com/18735885/184085286-cb2481d7-ab35-4d95-b2cf-084d2e085ec6.png)

**Comment by bradleytchu** [comment]
This can be resolve by getting the reference of your month calendar and invoke first the gotoDate function, then changeView function.

I used React so it would be like this:
Set this inside of the Class Component

`calendarResourceRef = React.createRef();`

Then this inside the date click function for the first view:

```
let monthCalendar = this.calendarMonthRef.current.getApi();
monthCalendar .changeView('timeGridDay',  date);
```

**Comment by d53520** [comment]
> This can be resolve by getting the reference of your month calendar and invoke first the gotoDate function, then changeView function.
> 
> I used React so it would be like this: Set this inside of the Class Component
> 
> `calendarMonthRef= React.createRef();`
> 
> Then this inside the date click function for the first view:
> 
> ```
> let monthCalendar = this.calendarMonthRef.current.getApi();
> monthCalendar.changeView('timeGridDay',  date);
> ```

dear bradleytchu
thanks for your reply 
i am almost a beginner and i dont know react very much
it is possible to show this range **2022-07-26 ~2022-08-25** like this?
![image](https://user-images.githubusercontent.com/18735885/184314707-4c7a88ca-8084-47f7-a90a-88c4c20f573c.png)

**Comment by bradleytchu** [comment]
I think it's possible. So you just want the range to minus one day. Look at the return values for dayCellDidMount in Full Calendar documentation.

`dayCellDidMount={(e) => { console.log(e); }`

Should be able to play with those values to get your results.

**Comment by d53520** [comment]
> I think it's possible. So you just want the range to minus one day. Look at the return values for dayCellDidMount in Full Calendar documentation.
> 
> `dayCellDidMount={(e) => { console.log(e); }`
> 
> Should be able to play with those values to get your results.

Dear bradleytchu
thanks for your reply again.
sorry my english is so poor i cant explain well. the pic below show what i need indeed
date range is not from 1st to 30th but 26th to 25th
![image](https://user-images.githubusercontent.com/18735885/184372498-620c0e11-5f16-496c-9721-dee17e4c9b8d.png)

**Comment by bradleytchu** [comment]
Oh ok, I see. You want your view to start on the first of every month. Go through Full Calendar Documentation. There's a setting for it.

You can try for your bottom calendar:

```
plugins={[dayGridPlugin, interactionPlugin]}
showNonCurrentDates={false}
```

**Comment by d53520** [comment]
>
dear bradleytchu
thanks again
here is my code pen sample address:     https://codepen.io/d53520/pen/gOedbVL
can you figur it out for me?

**Comment by bradleytchu** [comment]
Ok, on certain date range, the view will change to the month grid. This can only be fixed from the developer side. You may have to report it as a bug. But a work around for this is to stay between a certain range. For example:

`document.addEventListener("DOMContentLoaded", function () {
	var calendarEl = document.getElementById("calendar");
	var calendar = new FullCalendar.Calendar(calendarEl, {
	});
  
  const maxDateRange = 30; // shows 30 max days. Test this number, some will give you month grid, 
  var initialDate = new Date('07-26-2022'); // change this to today or any date you want 
  var startDate = new Date(initialDate);
  var endDate = new Date(startDate.setDate(startDate.getDate() +maxDateRange));
  console.log("Initial DATE", initialDate);
  console.log("End DATE", endDate);
  calendar.changeView('dayGrid', {
     start: initialDate,
      end: endDate
});`

This will keep a consistent layout every time between dates. Are you intending to stay on the start date or will it change?

**Comment by d53520** [comment]
> certain date range, the view will change to the month gr

dear bradleytchu
great thanks to you again.
hope the developer will fix this bug.

**Comment by d53520** [comment]
> ntending to stay on the

Dear bradleytchu
since my english is so poor i dont know how to report the bug well.
so i decide to change the way to work this .
set the range like '07-26-2022' to '08-27-2022' then hide the last day of the view^^
thanks very much for your kind~~

**Comment by acerix** [comment]
It does seem like a bug that it displays differently when the `visibleRange` is exactly one month.

https://codepen.io/acerix/pen/poLGwqQ?editors=001

As a workaround, you could set the "duration" instead which displays as expected:

https://codepen.io/acerix/pen/JjLxJzd?editors=001

**Comment by d53520** [comment]
> It does seem like a bug that it displays differently when the `visibleRange` is exactly one month.
> 
> https://codepen.io/acerix/pen/poLGwqQ?editors=001
> 
> As a workaround, you could set the "duration" instead which displays as expected:
> 
> https://codepen.io/acerix/pen/JjLxJzd?editors=001

dear acerix
thanks for your reply
i wil use the new methord(using duration) to do my work .
and hope the bug can be fixed in the future.
thanks for your hard work
