### ISSUE TITLE
Dragging Between Calendars- Revert does not return event to first calendar

### ISSUE THREAD

**Issue by leemorris** [fullcalendar/fullcalendar#6947]
### Reduced Test Case
I modified this [CodePen ](https://codepen.io/pen?editors=0010)and added "info.revert()" to the eventReceive function
Here is the resulting code
![image](https://user-images.githubusercontent.com/6569195/184113947-0c8b06f5-213a-431b-9356-d0fe56eb2912.png)

### Bug Description

The event is rejected by the second calendar but does not return to the first calendar as expected.
I expected the behavior to be similar to when the "Droppable" is set to false

**Comment by acerix** [comment]
Would you be able to post a [runnable, stripped-down demonstration of the bug](http://fullcalendar.io/wiki/Reduced-Test-Cases/)? Would really appreciate it because the time saved reproducing will be time spent fixing.
