### ISSUE TITLE
Fullcalendar v3 weekNumbers bug

### ISSUE THREAD

**Issue by Serhii-Danovsky** [fullcalendar/fullcalendar#6951]
### Reduced Test Case
v3
https://codepen.io/serhii-danovsky/pen/GRxPjOw
v4
https://codepen.io/serhii-danovsky/pen/OJvrbRV
v5
https://codepen.io/serhii-danovsky/pen/qBoLaPP

### Bug Description
I use Fullcalendar v 3.10.0 and I have a little bug with weekNumbers
` weekNumbers: true`
Wrong numeration of weeks on version v3
But correct on version v5 and v4

### Screenshots
v3
https://drive.google.com/file/d/13DHEXNJWsCYoAxpbl-wgrKfRMgj28mzr/view?usp=sharing
v5
https://drive.google.com/file/d/11GFzdMHXU61Wb8fJqGmEpWzS_yVN0Ppi/view?usp=sharing

**Comment by acerix** [comment]
In v3, you need the setting `weekNumberCalculation: 'ISO'` to get those week numbers:


https://codepen.io/acerix/pen/bGvzRXK
