### ISSUE TITLE
Support luxon 3.0

### ISSUE THREAD

**Issue by 719media** [fullcalendar/fullcalendar#6957]
### Checklist

Please mark these items with an [x]

  - [x] I've already searched through [existing tickets](https://fullcalendar.io/issues)
  - [x] Other people will find this feature useful

### Feature Description

Luxon 3.0 released, luxon 2.0 plugin should be modified to include 3.0 peerDep, functionality is same sans default setting

**Comment by zavan** [comment]
Everything seems to be working fine with luxon v3 when installed with `npm i --force`, but it's annoying having to run it like this every time. The current plugin is awkwardly named `/luxon2`, so not sure a new one should be created or that one should be updated...

**Comment by gazben** [comment]
Any update on this? Is there an official way of using luxon 3?

**Comment by DywiTom** [comment]
Bump

**Comment by krishna-koushik** [comment]
merge please 🙏🏽

**Comment by DywiTom** [comment]
Bump²

**Comment by arshaw** [comment]
I just released the [@fullcalendar/luxon3](https://www.npmjs.com/package/@fullcalendar/luxon3) package in [v6.1.8](https://github.com/fullcalendar/fullcalendar/releases/tag/v6.1.8). I'll write docs tomorrow. It works exactly as you might expect.

PS- please ignore the embarrassingly wrong README on npm. I've already updated it and queued it for the next release.
