### ISSUE TITLE
Using setInterval to refetch events throws 'Invalid Argument' exception in Internet Explorer 11

### ISSUE THREAD

**Issue by WaiyanMT** [fullcalendar/fullcalendar#6960]
### Reduced Test Case

`setInterval(function () { calendar.refetchEvents(); }, 5000);`

### Bug Description

I am using FullCalendar to render events. I used setInterval function to refetch events. It is working properly in other browsers but in Internet Explorer 11.

### Screenshots

![fullcalendarerror](https://user-images.githubusercontent.com/77599613/187607102-b225573a-689e-456b-be6d-448f0da324f6.png)

**Comment by acerix** [comment]
Would you be able to post a [runnable, stripped-down demonstration of the bug](http://fullcalendar.io/wiki/Reduced-Test-Cases/)? Would really appreciate it because the time saved reproducing will be time spent fixing.
