### ISSUE TITLE
Default loader inside calendar component

### ISSUE THREAD

**Issue by MrFarhan** [fullcalendar/fullcalendar#6961]
### Checklist

Please mark these items with an [x]

  - [X] I've already searched through [existing tickets](https://fullcalendar.io/issues)
  - [X] Other people will find this feature useful

### Feature Description

There should be a default loader while data is being fetched for calender, currently it shows empty calender without data.

It would be better if we can show Skeleton loader while data is being fetched, just we need to pass a loading state (true / false) and loader will be shown in calender component.

Currently we can show loader in place of calender component but the UX will be much better if we show skeleton inside calender blocks.

### Visual Mockups

Can be similar to this:
![image](https://user-images.githubusercontent.com/26528236/187691927-bab43b5a-e29a-4c9a-bf1a-a5c4d1db7b8d.png)

**Comment by arshaw** [comment]
@MrFarhan, when you say you want to "show skeleton inside calendar blocks", what do you mean by "calendar blocks"? Every single day cell in month view? If that is true, IMO, there would be too many loading skeletons.

**Comment by MrFarhan** [comment]
@arshaw It could be any of the loading indication that we can show to use while data is being fetched.

**Comment by arshaw** [comment]
@MrFarhan, I'd rather this be implemented by the developer because it's unclear exactly what the loading placeholders should look like or exactly where they should go in the calendar. Instead of deciding for the developer, they can just inject them with [dayCellContent hook](https://fullcalendar.io/docs/day-cell-render-hooks) or similar.
