### ISSUE TITLE
React + tsx custom button CalenderApi access.

### ISSUE THREAD

**Issue by nurettinselcuk** [fullcalendar/fullcalendar#6963]
### Checklist

Please mark these items with an [x]

  - [ x] I've already searched through [existing tickets](https://fullcalendar.io/issues)
  - [x ] Other people will find this feature useful

### Feature Description

Accessing CalenderApi with custom buttons with react + tsx

```
customButtons={{
                            myCustomButton: {
                              text: 'Custom Button!',
                              click: function(ev:MouseEvent, element: HTMLElement) {
                                goToDate("whatever")
                             }
                            },
                          }}
```
I could not manage to access CalenderApi using react + tsx demo

[React + tsx](https://github.com/fullcalendar/fullcalendar-example-projects/tree/master/react-typescript)

**Comment by timurcatakli** [comment]
Hey @nurettinselcuk how did you fix this issue?

**Comment by timurcatakli** [comment]
Thank you, by the way where are you located?

**Comment by nurettinselcuk** [comment]
> Thank you, by the way where are you located?

Greatings from Istanbul! :)
