### ISSUE TITLE
GridDay Hover Bug In DayGridMonth

### ISSUE THREAD

**Issue by JordanGaider** [fullcalendar/fullcalendar#6964]
### Reduced Test Case

https://codesandbox.io/s/gifted-water-vjyin5?file=/src/App.js

### Bug Description

If you hover days without events, you will properly be able to change the background color of GridDay. However, if you hover over elements of a specific day, you are not able to change the background color. And, even worse, when you hover over the "all day" event in the 5th of Sept to the 8th of Sept; you will notice that the 4th of Sept's GridDay will be highlighted. This is not desirable and I was wondering if there was a way to always highlight the DayGrid of where the mouse is hovered.

**Comment by acerix** [comment]
I believe this existing ticket captures this need:
https://github.com/fullcalendar/fullcalendar/issues/4816
↑
Please visit the above issue, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates.

For the CSS to work you could use `pointer-events: none;` on foreground elements:

https://codesandbox.io/s/affectionate-hooks-2i6p6l?file=/src/styles.css

**Comment by JordanGaider** [comment]
Hi,

Thanks for the response! However, if I use `pointer-events: none;` I would not be able to use `eventClick={}`. I will check out the existing ticket.
