### ISSUE TITLE
Render hooks' properties do not update when switching month views

### ISSUE THREAD

**Issue by marchershey** [fullcalendar/fullcalendar#6968]
### Reduced Test Case

https://codepen.io/marchershey/pen/MWGYQwm?editors=0010

### Bug Description

From what I've read, my issue is related to [DOM being reused, and the viewDidMount/WillUnmount not firing](https://github.com/fullcalendar/fullcalendar/issues/5543#issuecomment-651893395) when switching views, but I believe that the properties should be updated. 

I am injecting content inside of each Day Cell and depending on what the cell properties are (`isPast/isFuture/isToday/isOther`) determines what content is injected. When switching months view, I expected the properties would be updated, but they're not. The properties stay the same from the previous month.

For example, if this month is the month of September, and October 1st is visible as an `isOther` and `isFuture` on September's view, when switching forward to October's view, October 1st's `isOther` property should switch to `false`, and remain true on `isFuture`. That is not what happens. The properties never update. Also, when switching from September (current actual month) to October (next month), September's day cells never update to `isOther` as well. 

I hope I've explained that well enough, I'm sure it's confusing... but you should be able to understand after taking a look at the test case and the screenshots. 

### Screenshots

![image](https://i.imgur.com/WlufYOt.png)

![image](https://i.imgur.com/j6fi2dF.png)

**Comment by acerix** [comment]
As explained in https://github.com/fullcalendar/fullcalendar/issues/5543#issuecomment-651893395 , `dayCellDidMount` is not always called when changing views, you should instead use `dayCellContent` for adding content.
