### ISSUE TITLE
Events with dates in `yyyy-mm-dd` format do not display in Safari

### ISSUE THREAD

**Issue by 790891601** [fullcalendar/fullcalendar#6971]
### version
1.6.1

### Bug Description
events for function cannot display in Safari browser .

### Screenshots
![企业微信截图_16631226313624](https://user-images.githubusercontent.com/36757025/190045332-52742490-99a8-4065-8ad3-067156f75f5b.png)
expect：
![企业微信截图_1663122655386](https://user-images.githubusercontent.com/36757025/190045344-a897d410-e5ae-45c1-a7d3-1a2672af4c97.png)
code：
![企业微信截图_16631226833528](https://user-images.githubusercontent.com/36757025/190045351-734e52d8-a8fc-4fc3-a739-34d74317ab80.png)

**Comment by sayjeyhi** [comment]
Hello

It is because safari can't parse `yyyy-mm-dd` format.
so you can do:
```
value = new Date('2010-06-21'.replace(/-/g, "/"));
```
https://stackoverflow.com/questions/3085937/safari-js-cannot-parse-yyyy-mm-dd-date-format

**Comment by 790891601** [comment]
> 你好
> 
> 这是因为 safari 无法解析`yyyy-mm-dd`格式。 所以你可以这样做：
> 
> ```
> value = new Date('2010-06-21'.replace(/-/g, "/"));
> ```
> 
> https://stackoverflow.com/questions/3085937/safari-js-cannot-parse-yyyy-mm-dd-date-format

Thanks very much.

**Comment by arshaw** [comment]
Thank you @sayjeyhi
