### ISSUE TITLE
stickyHeaderDates: invisible horizontal scrollbar at top of resource timeline

### ISSUE THREAD

**Issue by warrenspence** [fullcalendar/fullcalendar#6973]
### Reduced Test Case
https://jsfiddle.net/omn7tukx/

### Bug Description
There is an invisible scrollbar at the top of the resource timeline view when the `stickyHeaderDates: true` option is set.

To see for yourself, go to https://jsfiddle.net/omn7tukx/ and click around on the top part of the "event 1" event and you will be able to scroll horizontally, it will scroll left if you click towards the left of the screen and scroll right if you click towards the right of the screen.

### Screenshots
![image](https://user-images.githubusercontent.com/15135117/190569059-bc32afeb-53f1-4459-8427-e66e268db46e.png)

**Comment by danielneuman** [comment]
I was just about to report this. 
I can reproduce this in Chrome 105.0.5195.127 and Edge 105.0.1343.33 but **not** in Firefox 105.0. 
Tested with Fullcalendar versions 5.8.0 and 5.11.3.
Also noticed the same problem when using `height: auto` which enables the _staticHeaderDates_ option implicitly.

**Comment by acerix** [comment]
I believe this existing ticket captures this need:
https://github.com/fullcalendar/fullcalendar/issues/6969
↑
Please visit the above issue, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates.
