### ISSUE TITLE
babel.config.js not required

### ISSUE THREAD

**Issue by FelipeBattistotti** [fullcalendar/fullcalendar#6974]
### Reduced Test Case

next.js example repo - [https://github.com/fullcalendar/fullcalendar-example-projects/tree/master/next](https://github.com/fullcalendar/fullcalendar-example-projects/tree/master/next)

### Bug Description

Without babel.config.js, like in repo ([https://github.com/fullcalendar/fullcalendar-example-projects/tree/master/next](https://github.com/fullcalendar/fullcalendar-example-projects/tree/master/next)), occurs the following error:

![image](https://user-images.githubusercontent.com/61482397/190691712-0d2c22c7-6477-4d76-8cdf-dec79b4bf578.png)

Since version 12, Next.js doesn't need Babel (babel.config.js).

When will you upgrade the package to not depend Babel transpiler?

**Comment by acerix** [comment]
I believe this existing ticket captures this need:
https://github.com/fullcalendar/fullcalendar/issues/6674
↑
Please visit the above issue, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates.
