### ISSUE TITLE
Add pre-dependencies or sufix-dependencies link line between events

### ISSUE THREAD

**Issue by liaoyu1992** [fullcalendar/fullcalendar#6977]
### Checklist

Please mark these items with an [x]

  - [x] I've already searched through [existing tickets](https://fullcalendar.io/issues)
  - [x] Other people will find this feature useful

### Feature Description

Add pre-dependencies or sufix-dependencies link line between events

### Visual Mockups

![image](https://user-images.githubusercontent.com/6285162/191190366-2a6596c6-b94c-4622-8ee0-c1a33386ef8f.png)

**Comment by acerix** [comment]
I believe this existing ticket captures this need:
https://github.com/fullcalendar/fullcalendar/issues/4748
↑
Please visit the above issue, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates.
