### ISSUE TITLE
Display dates from multiple calendar systems eg. Hijri

### ISSUE THREAD

**Issue by LouayH** [fullcalendar/fullcalendar#6981]
Hi there,

I wonder if fullcalendar can display 2 dates, like Gregorian and Hijri?

Something like this from my iPad Calendar App

![photo_2022-09-21_16-30-23](https://user-images.githubusercontent.com/28938792/191517031-5d9ef8a2-97a6-48d6-a80e-139f7d2e4cd5.jpg)

ESCAPE HATCH:

> If your issue is neither a bug nor a feature, include the text "I love FullCalendar".

**Comment by acerix** [comment]
The calendar only uses Gregorian currently, there's a request for Hirji support here:

https://github.com/fullcalendar/fullcalendar/issues/2105
↑
Please visit the above issue, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates.

**Comment by LouayH** [comment]
Thank you @acerix
