### ISSUE TITLE
Calendar is not showing properly if event has been booked for 2 continuous  days

### ISSUE THREAD

**Issue by shravanialeti1** [fullcalendar/fullcalendar#6985]
### Reduced Test Case
"not reproducible with a link" 

### Bug Description

Describe how to recreate the bug: User is creating an event for 2 days. He can see the event for first day  and unable to see the event for second day. This issue is happening for Day tab alone. 
There is no issue with week and month, their event is showing properly.
Once user navigate to week or month and come back to day they can see both the days event correctly. But after refresh issue is happening again.
What do you expect to happen?: User should able to see both the days events properly without navigating to either week or month.
What happens instead? User enables to see second continuous day event.

### Screenshots

If the bug is visual, include a screenshot if possible. : Attached the doc

[Calendar Issue.docx](https://github.com/fullcalendar/fullcalendar/files/9646454/Calendar.Issue.docx)

Currently we are using fullcalendar-3.4.0 Version

**Comment by acerix** [comment]
Would you be able to post a [runnable, stripped-down demonstration of the bug](http://fullcalendar.io/wiki/Reduced-Test-Cases/)? Would really appreciate it because the time saved reproducing will be time spent fixing.
