### ISSUE TITLE
Events dropped from popover in timeGrid loose their end date

### ISSUE THREAD

**Issue by Fixoon** [fullcalendar/fullcalendar#6986]
### Reduced Test Case

https://codepen.io/Fixoon/pen/yLjpjyg?editors=001

### Bug Description

Events that are dragged and dropped from popover in timeGrid view loose their end date.
In my test case, the popover event duration is 09:00 - 11:00 but when you drop it, the duration changes to defaultTimedEventDuration, because there is no end date.
The test case also prints the event start and end on eventDrop to show the event end really has no end.

**Comment by acerix** [comment]
I believe this existing ticket captures this need:
https://github.com/fullcalendar/fullcalendar/issues/6326
↑
Please visit the above issue, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates.
