### ISSUE TITLE
Add search option for the docs

### ISSUE THREAD

**Issue by Leonardonline** [fullcalendar/fullcalendar#6988]
### Checklist
  - [x] I've already searched through [existing tickets](https://fullcalendar.io/issues) there is one but atomatically closed [here](https://github.com/fullcalendar/fullcalendar/issues/6930)
  - [x] Other people will find this feature useful

### Feature Description

When visiting https://fullcalendar.io/docs, there is no easy way to search the website content. It would be very helpful, if somehow we are able to search the docs.

**Comment by acerix** [comment]
I believe this existing ticket captures this need:
https://github.com/fullcalendar/fullcalendar/issues/4196
↑
Please visit the above issue, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates.
