### ISSUE TITLE
Allow to drop an event on another event, to merge them or handle custom logic

### ISSUE THREAD

**Issue by casually-creative** [fullcalendar/fullcalendar#6991]
### Checklist

Please mark these items with an [x]

  - [x] I've already searched through [existing tickets](https://fullcalendar.io/issues)
  - [x] Other people will find this feature useful

### Feature Description

I am making an interface with a calendar on the left, and a list of items on the right. The events represent flights that depart at that time. The tasks are transport items that need to get booked on a flight. The idea is to have the user be able to drag a transport item to a flight so it gets booked. The transport items would be external events, but I don't see support to be able to drop them on an existing event and get the event data from it so we can handle custom logic. As I see it, it can only become a new event. Would be a neat feature with many use cases.

**Comment by acerix** [comment]
I believe this existing ticket captures this need:
https://github.com/fullcalendar/fullcalendar/issues/5208
↑
Please visit the above issue, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates.
