### ISSUE TITLE
Incorrect year passed to dayGridMonth header in dayHeaderContent options

### ISSUE THREAD

**Issue by DiarQoroviqi** [fullcalendar/fullcalendar#6998]
### Reduced Test Case

[Reduce Test Case](https://codepen.io/acerix/pen/MWyLrdm?editors=0011)

### Bug Description

Describe how to recreate the bug.

Using the dayHeaderFormat or dayHeaderContent to change header display on daygridMonth. In both cases the date you received from the argument is invalid it points to January 1970.

What do you expect to happen?

I am expecting the correct date to be passed just like in other views.

What happens instead?

The date is incorrect its always 1970.

### Screenshots

<img width="1725" alt="image" src="https://user-images.githubusercontent.com/32719008/194823226-1af27ff2-9d43-4633-8205-c1faa071d16e.png">

**Comment by acerix** [comment]
I believe this existing ticket captures this need:
https://github.com/fullcalendar/fullcalendar/issues/5854
↑
Please visit the above issue, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates.
