### ISSUE TITLE
Support on Cloudron

### ISSUE THREAD

**Issue by OrcVole** [fullcalendar/fullcalendar#7001]
### Checklist

Please mark these items with an [x]

  - [ x] I've already searched through [existing tickets](https://fullcalendar.io/issues)
  - [x ] Other people will find this feature useful

### Feature Description

Securely deploy FullCalendar with one-click 

Making FullCalendar available on Cloudron would make it easy for ordinary people to start scheduling with this tool and increase the userbase. 

Having a Docker image of FullCalendar would be a long way towards Cloudron support. A thread has been created for this on the Cloudron forum:

https://forum.cloudron.io/topic/7803/fullcalendar-on-cloudron

### Visual Mockups

There is a live demo of Cloudron at https://cloudron.io where you can see how to e.g. deploy Radicale, the Caldav supporting calendar  server.

![FullCalendar Cloudron](https://user-images.githubusercontent.com/68787520/196023400-4a6dbd67-8647-4800-b6d6-11813d666270.jpg)

**Comment by OrcVole** [comment]
Hi, acerix. Is there any progress on creating a Docker image for FullCalendar? It is meant to be relatively easy to create a Cloudron for NPM installed applications like FullCalendar.

**Comment by arshaw** [comment]
Hi @OrcVole, I'm a bit hesitant to launch (and maintain) a docker image for FullCalendar considering we don't offer an official backend. If someone else from the community wants to lead and maintain this, I'd support it. If FullCalendar begins to offer an official backend of our own, I'll circle back on this.
