### ISSUE TITLE
Render eventSources as they load

### ISSUE THREAD

**Issue by daniel-stoll** [fullcalendar/fullcalendar#7004]
### Reduced Test Case

We are using the fullcalendar v5.9.0 with React and fetching the events via eventSources.
In those eventSources, we fetch the events via a function.

In the GIf provided, you can see, that a new resource row is added in the timeline view, directly after any request finishes.
But the events do not show up immediately!
Only after fetching all calendar sources, the events are showing.
The same goes for other views like list and agenda, but the timeline view shows imo, that the issue does not seem to be on our side.

If I remember correctly, this was not the case in v4. (we updated several years ago)

This is a real time rendering with 5 calendars.
Some of our customers have > 20 calendars in the list, what makes this quite inconvenient.

### Bug Description
I think, the rendering of the events should start directly after the events are fetched (per calendar source).
I also tried fiddling around with the rerenderDelay setting, but without any results (null, 1, 1_000, 10_000)
Adding a breakpoint in the eventContent function also shows, that the events are only rendered at the very last moment.

Have a good one :)

### Screenshots
![fc event loading](https://user-images.githubusercontent.com/37585540/196459481-6e62d263-4dd5-4d34-9465-6981912f0881.gif)

**Comment by acerix** [comment]
I tested this in our debug template and can see it doesn't render until all event sources return:

https://codepen.io/acerix/pen/xxzRrwY?editors=001
