### ISSUE TITLE
Resize/Drag selectMirror pseudo-event

### ISSUE THREAD

**Issue by Tazaf** [fullcalendar/fullcalendar#7008]
### Checklist

Please mark these items with an [x]

  - [x ] I've already searched through [existing tickets](https://fullcalendar.io/issues)
  - [ x] Other people will find this feature useful (I think)

### Feature Description

Apparently, it is not possible to select the event created by `selectMirror` to resize it or drag it accros the calendar.

The settings related to those actions (`editable` and such) do work on **existing** events, but have no effect on the `selectMirror` event.

Is this an overlook on my part, or is this really not feasable currently? If so, would it be something that you'd consider adding in the library?

### Visual Mockups

Pretty much the same as in the [documentation](https://fullcalendar.io/docs/touch), but for the `selectAllow` event.

![image](https://user-images.githubusercontent.com/7702322/196963464-2a7b8bc3-f3a4-437b-b856-c34cd2a72150.png)

**Comment by acerix** [comment]
The "mirror" can't be interacted with currently, but you could add an event in it's place from the `select` which can then be interacted with normally.

**Comment by Tazaf** [comment]
That's what I ended up doing 🙂 

The feature would still be useful, though, I think.
