### ISSUE TITLE
fullCalendar ignores resource eventBackgroundColor if event's backgroundColor is set to null

### ISSUE THREAD

**Issue by Invincibear** [fullcalendar/fullcalendar#7010]
### Reduced Test Case
https://codepen.io/Invincibear/pen/RwJbgQX?editors=001

### Bug Description
Resources that have `eventResourceBackground` set should assign a `backgroundColor` to associated events. This works, except when an event includes `backgroundColor: null`, at which point fullCalendar ignores the resource's `eventResourceBackground` attribute. This behaviour would be expected if any `string` is provided by an event's `backgroundColor`, but a `null` value imo should not trigger an Event's `backgroundColor` to override the resource's `eventBackgroundColor`.

**Comment by acerix** [comment]
The `backgroundColor` setting only accepts a string, you can use an empty string (`''`) to use the resource setting.

https://codepen.io/acerix/pen/wvXoezB?editors=0010
