### ISSUE TITLE
Add a method to get all upcoming events. The getEvents method does not return all the events, only ones present in current view.

### ISSUE THREAD

**Issue by davecalderwood** [fullcalendar/fullcalendar#7011]
### Checklist

Please mark these items with an [x]

  - [x] I've already searched through [existing tickets](https://fullcalendar.io/issues)
  - [x] Other people will find this feature useful

### Feature Description

I would love to be able to get all upcoming events. Or at least all events, I can do the filtering myself if needed. I want to be able to use this calendar API to get all the events, that way I could reference it outside of the calendar view. If there is a dashboard with an upcoming calendar events section, I want to populate that with the next coming events. But if there are no events on the calendar for lets say 3 months, then this getEvents method does not work as it only returns the events in the current calendar view. 

Can we get a method to return all events?

**Comment by acerix** [comment]
The calendar only know about the events which are visible,  assuming you are supplying the events from a server (eg. JSON) you should make a separate request to get all events at once.
