### ISSUE TITLE
Showing events spanning multiple days on a montly view

### ISSUE THREAD

**Issue by tomaszmys** [fullcalendar/fullcalendar#7012]
### Checklist

  - [X] I've already searched through [existing tickets](https://fullcalendar.io/issues)
  - [X] Other people will find this feature useful

### Feature Description

Is there currently an option to show events spanning multiple days (but not being all-day events, with a fixed start and end hours), to be shown as such in a montly view? (just as they are on e.g. on a weekly view)
Or is that turned off on purpose not to clutter the montly view?

**Comment by acerix** [comment]
The month view always shows events as filling the day time slots but can span multiple days.   I'm not sure what you are looking for in that view, it would help to include a mock-up.
