### ISSUE TITLE
Draging and resizing events during refetchEvents() causes dupes and exceptions

### ISSUE THREAD

**Issue by taleteller** [fullcalendar/fullcalendar#7019]
### Reduced Test Case

This issue is not reproducible with a link because it requires a race condition between client and server.

Implement fullcalendar with at least one remote ajax source, enabling the features to resize or reschedule events by drag and drop. Add code to call `refetchEvents()` asynchronous like with calling `setInterval()`. The use of sleep() delays on the server side enforces the race condition to happen. 

This was tested using version 5.11.3. 

### Bug Description

While a source is refetched from a remote resource, it it still possible to resize or reschedule events from that source on the client side using drag and drop. Holding an event by dragging during the reload can lead to two possible results when dropping. First, if the ajax request is still running at the moment of dropping the event, it results in a `Uncaught TypeError: this._def is undefined` Error in the EventApi code. Second, if the ajax request completed before the moment of dropping the event, it gets duplicated. 

### Workarounds / Solutions

This problem happens in two variants, on `refetchEvents()` before and after a drag / resize event has started. While it is relatively easy to prevent a reload taking place before the user has started a drag, it is not reliably possible to abort a drag after it has started. 

fullcalendar should either not allow a drag or resize event to happen while reload events are in progress, or give me the possibility to recognize the status and abort an active drag / resize operation from outside.

**Comment by acerix** [comment]
I believe this existing ticket captures this need:
https://github.com/fullcalendar/fullcalendar/issues/6101
↑
Please visit the above issue, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates.
