### ISSUE TITLE
Release plan for V6

### ISSUE THREAD

**Issue by Blend-Rugova-KodeLabs** [fullcalendar/fullcalendar#7020]
### Checklist

Please mark these items with an [x]

  - [ ] I've already searched through [existing tickets](https://fullcalendar.io/issues)
  - [x] Other people will find this feature useful

### Question

What is the release plan with Fullcalendar V6? Our company is using Angular14 and we are forced to use the beta version for now. Is there a estimate when it will be released because the Q3 window is over and we do not want to stay on beta version.

**Comment by alphacentauridigital** [comment]
+1 - Waiting for v6 to use on Angular 14.

**Comment by KasperSommer** [comment]
+1

**Comment by suhailkc** [comment]
+1
