### ISSUE TITLE
Dividers between time slots

### ISSUE THREAD

**Issue by nico-apps** [fullcalendar/fullcalendar#7022]
I've been using FullCalendar for some time now, and I would like to use it to display a school timetable. The individual lessons are 45 minutes long. I used `slotDuration: "00:45:00"` for this, but every 2 lessons there is a 15 minute pause I would like to display as a gap, if possible. Is there some way I can do this?

Something like this: 
![grafik](https://user-images.githubusercontent.com/35093969/200021170-f8d1a417-c88f-4fa2-9b36-fd8ba807b6d0.png)

And yeah, I love FullCalendar.

**Comment by arshaw** [comment]
Hi @nico-apps , I understand your feature request. I feel this can be implemented with a combination of [background events](https://fullcalendar.io/docs/background-events) and ["Arbitrary differing slotMinutes increments"](https://github.com/fullcalendar/fullcalendar/issues/472) when that's implemented. Could you please follow that ticket? I'm closing this one.
