### ISSUE TITLE
Resource getParent() returns undefined from `select` callback

### ISSUE THREAD

**Issue by zhangjett** [fullcalendar/fullcalendar#7023]
### Reduced Test Case

https://codepen.io/zhangjett/pen/XWYjoPW?editors=001

### Bug Description

Attempting to access a Resource's parent attribute in date select event。
cause error {_context: {…}, _resource: undefined}

https://github.com/fullcalendar/fullcalendar-scheduler/blob/776453a55aedb31f853d669beb36a49f98f887fa/resource-common/src/api/ResourceApi.ts#L89

Change resourceSource to resourceStore is right?

### Screenshots

![1667800155566](https://user-images.githubusercontent.com/17883179/200236433-30a03b3e-38ec-474b-9992-0b09f6a7c968.png)

**Comment by arshaw** [comment]
@zhangjett , when I use your demo, when selecting dates on a top-level resource, the console correctly outputs `null`. This happens on resources like Resource A/B/C. However, when selecting a nested resource like D1/D2, a parent is correctly outputted.

Top-level resources don't have parent resources. Only nested resources do. Does that make sense? Am I understanding your bug report correctly?

**Comment by forum1901** [comment]
I am having the same issue. Is there any work around ? I do nned the feature for my project. Thanks.

**Comment by Muukuro** [comment]
In `ResourceApi.getParent()`, a new `ResourceApi` is constructed. I believe the second argument (`resource`) is retrieved incorrectly, because the resource key-value pairs are stored in `resourceStore`, not in `resourceSource`.

**Comment by arshaw** [comment]
Fixed in [v6.1.5](https://github.com/fullcalendar/fullcalendar/releases/tag/v6.1.5)

Updated repro: https://codepen.io/arshaw/pen/PodyQwB?editors=001
