### ISSUE TITLE
event overlap on angular 13 / fullcalender 5.11.0/5.3.2

### ISSUE THREAD

**Issue by nharshavreddy** [fullcalendar/fullcalendar#7028]
### Reduced Test Case

https://stackblitz.com/edit/angular-ivy-nbgcfw?file=src/app/app.component.ts

### Bug Description

The events are getting overlaped after upgrading to angular 13. this was working fine in angular 8

### Screenshots
<img width="421" alt="Screenshot 2022-11-19 at 9 42 42 PM" src="https://user-images.githubusercontent.com/25380311/202863185-4aa01e28-4bf8-47ee-8341-11b0468c2f2e.png">

**Comment by acerix** [comment]
Your demo doesn't seem to run, I just get an error.  Please post a [runnable, stripped-down demonstration of the bug](http://fullcalendar.io/wiki/Reduced-Test-Cases/) if there is a bug. Would really appreciate it because the time saved reproducing will be time spent fixing.
