### ISSUE TITLE
Updating dayGridPlugin 5.11.2 to 5.11.3 produces error `dateProfileGenerator is undefined` deep in FC code

### ISSUE THREAD

**Issue by PjotrB** [fullcalendar/fullcalendar#7030]
### Reduced Test Case

Sorry, not reproducible with a link. It is part of a big application that I inherited and it is infeasible for me to strip the 100s of other packages while still keeping this functioning (or in this case, non-functioning).
Also the stack trace (see below) makes it seem quite likely that this does not depend on other components.

### Bug Description

How we use the component:
```
FullCalendar
    ref={this.fullCalRef}
    buttonText={{ today: t("Today") }}
    events={this.getCalendarEvents}
    eventClick={this.setBulletin}
    eventMouseEnter={this.handleMouseEnter}
    eventMouseLeave={this.handleMouseLeave}
    fixedWeekCount={false}
    height="auto"
    initialView="dayGridMonth"
    locale={lang}
    plugins={[dayGridPlugin]}
/>
```

This works fine with `@fullcalendar/daygrid@5.11.2` and crashes when using `5.11.3`.

### Screenshots

The stacktrace image below can be summarized as follows:

- **DayTableView render()** (3rd yellow block) -> calls internal functions, visible in the blocks above it, but apparently does so with a `dateProfileGenerator` that isn't set.
- **React framework** -> process the state change (from below), then trigger the render (above).
- **our code** -> `this.setState({ .... })`

![image](https://user-images.githubusercontent.com/1635838/203061159-1492b363-e01e-428f-9678-1630c1a4ff53.png)

**Comment by acerix** [comment]
Please post a [runnable, stripped-down demonstration of the bug](http://fullcalendar.io/wiki/Reduced-Test-Cases/) if there is a bug, Would really appreciate it because the time saved reproducing will be time spent fixing.

Deleting the calendar packages and reinstalling may help if there is an issue with package versions.

**Comment by nikhilgoyal22** [comment]
@acerix I am getting the same issue with version 6.0.3
Framework is StimulusJs
Using yarn to install packages

Did deletion and reinstall as well

**Comment by nikhilgoyal22** [comment]
Version 5.11.4 seems to be working fine. Though it seems that there is a `@fullcalendar/common` with this version which is not there in newer version
