### ISSUE TITLE
Resource Timeline: Last resource row not selectable

### ISSUE THREAD

**Issue by nevaan9** [fullcalendar/fullcalendar#7031]
### Reduced Test Case
https://codepen.io/nevaan9/pen/xxzYNad

### Bug Description
When you have a few resources on a resource-timeline (see above example), the last resource row gets expanded to the end of where the calendar height ends.
When the "selectable" prop is active on the calendar, it can seem that you can click anywhere on the expanded last resource row to trigger the "select" hook function. However, in reality you need to click on the **TOP MOST PART** of the resource row (Image 1); If you try to click anywhere below (Image 2) the "select" hook function does not trigger (nor does the cell get highlighted)

### Screenshots
Image1
<img width="1218" alt="Screen Shot 2022-11-22 at 4 10 02 PM" src="https://user-images.githubusercontent.com/20254162/203423194-485fd79b-df1b-4022-932e-a21e33a92a03.png">

Image2
<img width="1211" alt="Screen Shot 2022-11-22 at 4 10 09 PM" src="https://user-images.githubusercontent.com/20254162/203423482-55019193-4b23-4210-9d2b-cc467b8803cf.png">

**Comment by acerix** [comment]
I believe this existing ticket captures this need:
https://github.com/fullcalendar/fullcalendar/issues/6878
↑
Please visit the above issue, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates.
