### ISSUE TITLE
Locale translations not applied and gives TypeError

### ISSUE THREAD

**Issue by indigoxela** [fullcalendar/fullcalendar#7033]
### Reduced Test Case

http://olga.indigofloat.at/fc-bugdemo/index.html

### Bug Description

When trying to use the locales, one gets "Uncaught TypeError: internal_js is undefined" or "Uncaught TypeError: FullCalendar.Internal is undefined" (when using the minified version) . And the buttons won't get localized.

Not sure if I'm doing something substantially wrong, but in 5.x locales worked by just loading locales-all.min.js. If additional steps are needed with 6.x it would be great if that gets documented.

BTW, I really love FullCalendar :smiley:

**Comment by indigoxela** [comment]
Brilliant! I can confirm that this is fixed in 6.0.0-beta.3. :+1: 

Can we close this issue, or are there remaining tasks? I can see it got the "Needs Docs" label.

**Comment by arshaw** [comment]
@indigoxela, yes this is now implemented and released in [v6-beta.3](https://github.com/fullcalendar/fullcalendar/releases/tag/v6.0.0-beta.3) Thanks!

It was incorrectly labeled as a docs issue. I removed that label.
