### ISSUE TITLE
TypeError with custom noEventsContent prop

### ISSUE THREAD

**Issue by tommynguyen1** [fullcalendar/fullcalendar#7034]
### Reduced Test Case
- not reproducible with a link

### Bug Description
When I use `initialView={'listMonth'}` it gives error if I customize `noEventsContent`.
<img width="451" alt="image" src="https://user-images.githubusercontent.com/112811859/203683176-89ee7e83-a0ff-48d8-b384-8afa1fe18b42.png">

### Screenshots
<img width="766" alt="image" src="https://user-images.githubusercontent.com/112811859/203682728-8c989e15-7990-40f0-8955-d23e90147645.png">

**Comment by arshaw** [comment]
Yes, previously worked in v5: https://codesandbox.io/s/currying-sunset-2ptze6?file=/src/DemoApp.jsx:1015-1030

**Comment by arshaw** [comment]
This has been fixed in [v6.0.0-beta.3](https://github.com/fullcalendar/fullcalendar/releases), thanks for the report!
