### ISSUE TITLE
custom locale

### ISSUE THREAD

**Issue by dpanic** [fullcalendar/fullcalendar#7036]
### Checklist

Please mark these items with an [x]

  - [x] I've already searched through [existing tickets](https://fullcalendar.io/issues)
  - [x] Other people will find this feature useful

### Feature Description
Is there possibility to make custom locale.
Why? I selected "sr", there are cyrilic and latin option. Your locales works good. But Google Calendar selects CYR. So I end up with mix of locales.

I would prefer to write days of week by myself, same for months.
Is that possible?

I tried with titleFormat from your docs:

```
var calendar = new Calendar(calendarEl, {
  // will produce something like "Tue Sep 18 2018 18:48:41 GMT-0400 (Eastern Daylight Time) !!!"
  titleFormat: function(date) {
    return date.toString() + '!!!';
  }
});
```
It doesn't work, returns [object Object].

Something like that (if it works) would solve the issue. I can create custom title and than I need to do same for days of week (header of calendar).

### Visual Mockups

If you are requesting a new UI, please include a mockup.
If not, erase this section.

**Comment by acerix** [comment]
I believe this existing ticket captures this need:
https://github.com/fullcalendar/fullcalendar/issues/6023
↑
Please visit the above issue, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates.
