### ISSUE TITLE
Packaging warning with Vite "vdom.js is written in ESM, but is interpreted as CJS"

### ISSUE THREAD

**Issue by benmccann** [fullcalendar/fullcalendar#7038]
### Reduced Test Case

https://publint.bjornlu.com/@fullcalendar/core

### Bug Description

There are difficulties using this package with Vite (https://github.com/YogliB/svelte-fullcalendar/issues/804) because it is improperly packaged

I would recommend setting either `"type": "module"` or `exports` in the `package.json` of this package.

**Comment by arshaw** [comment]
Nearly all issues have been addressed in [v6.0.0-beta.3](https://github.com/fullcalendar/fullcalendar/releases)

See the improved linting:
https://publint.bjornlu.com/@fullcalendar/core@6.0.0-beta.3

The issue of `"types": "./locales/*.d.ts"` being invalid is wrong, glob stars are allowed. This should be reported to the maintainer of publint
