### ISSUE TITLE
Packaging: fullcalendar-6.0.0-beta.3.zip contains no minified js files

### ISSUE THREAD

**Issue by indigoxela** [fullcalendar/fullcalendar#7040]
### Reduced Test Case

Not reproducible with a link.

### Bug Description

When extracting the latest [beta.3 zip file from GitHub](https://github.com/fullcalendar/fullcalendar/releases/tag/v6.0.0-beta.3), I realized that it contains no minified js files. Beta.2, for example, additionally contains 95 *.min.js files.

Is this by intention, or was there a packaging (build) problem? (Minified versions are still available via jsDelivr.)

**Comment by arshaw** [comment]
This was unintentional. I tweaked the script that filtered dist files for the zip creation. I will rebuild and reupload in a bit...

**Comment by arshaw** [comment]
I've rebuilt the zips to includes the `.min.js` files:
- https://github.com/fullcalendar/fullcalendar/releases/download/v6.0.0-beta.3/fullcalendar-6.0.0-beta.3.zip
- https://github.com/fullcalendar/fullcalendar-scheduler/releases/download/v6.0.0-beta.3/fullcalendar-scheduler-6.0.0-beta.3.zip
