### ISSUE TITLE
using bootstrap theme causes multiple previous and next arrows

### ISSUE THREAD

**Issue by Pableem** [fullcalendar/fullcalendar#7043]
Hi, using the v6 beta 3 versión with the themeSystem bootstrap (bootstrap v4) when change the view between listDay and listWeek the prev and next button acumute the arrow icons

![image](https://user-images.githubusercontent.com/16228977/205512109-4908fb3c-caf9-4c30-9c7c-ceff035adb2a.png)

**Comment by acerix** [comment]
I believe this existing ticket captures this need:
https://github.com/fullcalendar/fullcalendar/issues/5544
↑
Please visit the above issue, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates.
