### ISSUE TITLE
Errors after updating to Angular 15

### ISSUE THREAD

**Issue by Yawarzy** [fullcalendar/fullcalendar#7049]
I love FullCalendar
We recently upgraded our project to Angular 15, and started having issues with the fullcalendar plugin. So as suggested, we upgraded to the v6. But now there is this weird issue we've encountered related to the resources. We can't access the `resource` property on the `CalendarOptions` object. The error message says it doesn't exist. Similarly, `resourceOrder, resourceAreaWidth, newResource, setResource`, are not working at all. They were working fine before the upgrade to v6.

**Comment by arshaw** [comment]
Hi @Yawarzy, you'll need to install the `@fullcalendar/resource` package manually, as described here:
https://fullcalendar.io/docs/v6/upgrading-from-v5#peer-dependencies

Please let me know if that fixes your problems.

**Comment by Yawarzy** [comment]
Thank you so much. It resolved the my issue.
