### ISSUE TITLE
nowIndicator does not work as expected.

### ISSUE THREAD

**Issue by PoDuck** [fullcalendar/fullcalendar#7052]
### Reduced Test Case

Working as expected:  https://jsfiddle.net/PoDuck/g60t97ye/1/
Not working as expected:  https://jsfiddle.net/PoDuck/g60t97ye/3/

### Bug Description

When I last used fullcalendar, it was version 3.  The nowIndicator always went to the current time, no matter which view you started with.  Now, if you start with any view other than `resourceTimelineDay`, you end up with something different.  In `resourceTimelineWeek`, the indicator goes to the beginning of the hour.  If you start with `resourceTimelineMonth`, the indicator goes to the beginning of the day.  The indicator doesn't change if you change views with the buttons in the header either.

My expectation is that the behavior would be as it was in V3.  At the very least, it should change when you change views with the buttons.  I have found no documentation about any change that was made to this feature since V3 either, and the documentation doesn't give any hints that this behavior can be overcome.

**Comment by acerix** [comment]
I believe this existing ticket captures this need:
https://github.com/fullcalendar/fullcalendar/issues/6175
↑
Please visit the above issue, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates.
