### ISSUE TITLE
JSX cannot be injected in content

### ISSUE THREAD

**Issue by Guiguerreiro39** [fullcalendar/fullcalendar#7054]
### Reduced Test Case
(https://www.loom.com/share/d2d059f5fa7049aab20fed1a5cc18938)

### Bug Description
JSX cannot be injected in content (currently using NextJS and fullcalendar@6.0.0-beta.4). I've tried in many different ways and all I can pass is a string or an object with an html key and string value.

### Screenshots
![image](https://user-images.githubusercontent.com/11543544/207413013-91a6677b-53d7-4505-9957-a495650b297f.png)
![image](https://user-images.githubusercontent.com/11543544/207413086-6d102d8d-f6e0-4c1b-99b4-1d4bf4dbfab6.png)
![image](https://user-images.githubusercontent.com/11543544/207413219-f33db1ec-3faa-4f85-b6c4-6739fb50ce2e.png)

**Comment by acerix** [comment]
Would you be able to post a [runnable, stripped-down demonstration of the bug](http://fullcalendar.io/wiki/Reduced-Test-Cases/)? Would really appreciate it because the time saved reproducing will be time spent fixing.

**Comment by arshaw** [comment]
The technique the OP is using works find in v6.0.0 as far as I can tell:
https://stackblitz.com/edit/github-vmtnn4?file=package.json,src%2FDemoApp.jsx,src%2Findex.css

However, I see a size adjustment problem very similar to #7089

**Comment by arshaw** [comment]
Everything working:
https://stackblitz.com/edit/github-vmtnn4?file=package.json,src%2FDemoApp.jsx,src%2Findex.css

If I see a reproduction of the bug I'll reopen.
