### ISSUE TITLE
Expose `globalLocales` publicly for importing on-demand

### ISSUE THREAD

**Issue by boris-petrov** [fullcalendar/fullcalendar#7057]
### Reduced Test Case

not reproducible with a link

### Bug Description

I updated the package to version 6 and in the documentation it says to open an issue if I believe something should be exposed.

In my case, I want to import locales on-demand and at runtime. Which means I expose the `.global.min.js` files and load them dynamically. Internally in them they use `FullCalendar.Internal.globalLocales`. So that must be made public.

I also pass the `globalLocales` as `locales` of `CalendarOptions`. And I also use `globalLocales` to check which locales have been loaded already.

Just to name you a few use-cases of `globalLocales` and why I think it must be made public.

**Comment by arshaw** [comment]
Released in [v6.0.1](https://github.com/fullcalendar/fullcalendar/releases/tag/v6.0.1)
