### ISSUE TITLE
Root cause of state issues

### ISSUE THREAD

**Issue by parisholley** [fullcalendar/fullcalendar#7066]
After running into some state issues myself, I started digging through the library to figure out what the underlying issue could be. I believe the same problem is impacting the following issues:

- fullcalendar/fullcalendar-react#118 
- fullcalendar/fullcalendar#7067 
- fullcalendar/fullcalendar#7071

The root cause appears to be this code here:

https://github.com/fullcalendar/fullcalendar/blob/f55ba69a8247dda0cc6bb0c4aefceed21bf17eb9/packages/common/src/option-change-handlers.ts#L15-L48

In particular, two problems:

1. As noted in the comment, the diff'ing algorithm does not currently support passing in the `events` prop, it can only diff `eventSources`. As a result, every time a component with `<FullCalendar />` is re-rendered, the event store is destroyed and recreated.

2. Due to one, it would appear the solution would be as simple as switching to `eventSources`, however the problem is the diffing logic does a strict equality check, and if the object isn't the same memory reference as the previous render, it is also destroyed and recreated. so if a user started a drag, the drag'd element is referring to an event instance that was part of the old/destroyed store and the re-render can't tell you are dragging the same thing on refresh.

To solve for fullcalendar/fullcalendar-react#2, I am able to work around by implementing the following:

```react
const eventSourceRef = useRef({ id: 'events', events });

if (JSON.stringify(eventSourceRef.current.events) !== JSON.stringify(events)) {
  eventSourceRef.current = { id: 'events', events };
}

return <FullCalendar  eventSources={[eventSourceRef.current]} ... />
```

`useRef` will guarantee that each render will get the same event source object and pass the equality check, and I only update it between renders if the JSON serialization changes.

It isn't clear the best way to implement a fix given that async functions/fetches can be part of the equation, and depending on the use cases, a full hash of the event data may be a performance hit.

**Comment by arshaw** [comment]
The root cause has been solved in [v6.1.3](https://github.com/fullcalendar/fullcalendar/releases/tag/v6.1.3). See:
- https://github.com/fullcalendar/fullcalendar/issues/7067#issuecomment-1421477286
- https://github.com/fullcalendar/fullcalendar/issues/7071#issuecomment-1421488699

@parisholley , thanks for making this tracking ticket.
