### ISSUE TITLE
Update/rerender eventContent if an event's data is changed

### ISSUE THREAD

**Issue by nicholaszuccarelli** [fullcalendar/fullcalendar#7083]
Hey guys,
I have an array of events, lets say:
```
data () {
 return {
  events: [
    {
       'id': 1,
       'title: 'Event Name'
    }
   ]
  }
},
computed: {
  options: () => {
    ... // other fullcalendar options,
    eventSources: [{
      id: 'events',
      events: this.events
    }]
  }, 
}
```

Then, I use the `eventContent` slot to render event details myself:
```
      <FullCalendar
        :options="options"
      >
        <template v-slot:eventContent="arg">
             <div>{{ arg.event.title }}</div>
        </template>
      </FullCalendar>
```

Let's assume I have a method externally (outside of the calendar) which updates the title of an event within my array of events, such as:
```
methods: {
   updateEventFromAnExternalDialog (event) {
     this.events[0].title = 'A new title for this event';
   }
}
```

The updated event title is **not** reflected onto the `eventContent` slot. The slot continues to use the old event data.
The only way I have been able to make it rerender the data of that specific event is if I manually splice the event from my source array, and readd it.

All up, I'm asking if there is a way to make it rerender the `eventContent` data if an event via my event source is updated (without the need to splice).

Cheers :)

**Comment by nicholaszuccarelli** [comment]
This problem has apparently been fixed in v6.
I am currently upgrading my project and will close the issue if it is indeed resolved for myself :)

**Comment by reydm-7166** [comment]
@nicholaszuccarelli can you help me where it has been updated, can't seem to find it in docs, or rather I just don't know where to look at. thanks
