### ISSUE TITLE
Allday events rendered by `eventContent` are overlapping each other

### ISSUE THREAD

**Issue by timofei-maximov-saritasa** [fullcalendar/fullcalendar#7089]
### Reduced Test Case

[REDUCED TEST CASE](https://codesandbox.io/p/sandbox/withered-currying-vefc6o?file=%2Fsrc%2FCalendar.tsx&selection=%5B%7B%22endColumn%22%3A5%2C%22endLineNumber%22%3A49%2C%22startColumn%22%3A5%2C%22startLineNumber%22%3A49%7D%5D).

### Bug Description

`eventContent` with custom allday events breaks allday event positioning . Issue appeared in 6.0, 5.x is working fine.

Broken views: `dayGridMonth`, `timeGridWeek`. `timeGridDay` seems to be working fine.

### Screenshots
<img width="1037" alt="image" src="https://user-images.githubusercontent.com/86595911/208011043-09b4ae88-77b2-4b52-b971-29dacc392d55.png">
<img width="1084" alt="image" src="https://user-images.githubusercontent.com/86595911/208011092-e7a8d5fe-0727-4b15-b0d5-0a70f6b2034d.png">

**Comment by timofei-maximov-saritasa** [comment]
Well, it seems like its duplicate of https://github.com/fullcalendar/fullcalendar/issues/7060

**Comment by arshaw** [comment]
Thanks for the report! We'll use this ticket to track the problem instead of #7060 because it has a good reduced test case.

Seems to only be an issue with the react connector

**Comment by gudlyf** [comment]
I would add that when switching views and back again, the issue goes away. Additionally, if the calendar is initially opened in a different view, the month view looks fine when selecting it.

**Comment by arshaw** [comment]
Fixed in [v6.0.1](https://github.com/fullcalendar/fullcalendar/releases/tag/v6.0.1)

Updated working repro:
https://codesandbox.io/p/sandbox/zealous-shirley-o128si?selection=%5B%7B%22endColumn%22%3A34%2C%22endLineNumber%22%3A21%2C%22startColumn%22%3A34%2C%22startLineNumber%22%3A21%7D%5D&file=%2Fsrc%2FCalendar.tsx
