### ISSUE TITLE
timeGridWeek hasn't background color

### ISSUE THREAD

**Issue by milikatot** [fullcalendar/fullcalendar#7090]
### Reduced Test Case

Problem in local

### Bug Description

With version 6 on Angular 15, "today" does not have a yellow colored background.

### Screenshots

![Cattura](https://user-images.githubusercontent.com/77754944/208068136-4b0e0e0a-ae7c-490e-afba-08f60e5f8ea1.JPG)

![Cattura](https://user-images.githubusercontent.com/77754944/208068338-60146984-8e5a-4f37-a5c1-9d24bc4b5c7b.JPG)

![Cattura](https://user-images.githubusercontent.com/77754944/208067562-9b1a66f3-0f9e-4cc2-bb5f-c124a3375ef6.JPG)

**Comment by acerix** [comment]
Would you be able to post a [runnable, stripped-down demonstration of the bug](http://fullcalendar.io/wiki/Reduced-Test-Cases/)? Would really appreciate it because the time saved reproducing will be time spent fixing.
