### ISSUE TITLE
`eventDidMount` works differently with `eventMaxStack` and `dayMaxEvents`

### ISSUE THREAD

**Issue by timofei-maximov-saritasa** [fullcalendar/fullcalendar#7095]
### Reduced Test Case

https://codesandbox.io/p/sandbox/focused-dew-fzkmt8

### Do you understand that if a reduced test case is not provided, we will intentionally delay triaging of your ticket?

- [X] I understand

### Which connector are you using (React/Angular/etc)?

React

### Bug Description

`eventDidMount` fires for every event that is hidden by `dayMaxEvent`, however it doesn't fire when events are hidden by `eventMaxStack`

<img width="1719" alt="image" src="https://user-images.githubusercontent.com/86595911/208374173-39d9de20-6f44-428e-88ab-e39c23881c77.png">

**Comment by acerix** [comment]
I believe this existing ticket captures this need:
https://github.com/fullcalendar/fullcalendar/issues/6148
↑
Please visit the above issue, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates.
