### ISSUE TITLE
TypeError: Cannot add property __, object is not extensible

### ISSUE THREAD

**Issue by ronaklalwaniii** [fullcalendar/fullcalendar#7100]
### Reduced Test Case

null

### Do you understand that if a reduced test case is not provided, we will intentionally delay triaging of your ticket?

- [X] I understand

### Which connector are you using (React/Angular/etc)?

React

### Bug Description

I am getting following error with Version 6 while using custom buttons in header.

Here's  the code:

```
 customButtons: {
    sidebarToggle: {
      text: <Icon icon='mdi:menu' />,
      click() {
        handleLeftSidebarToggle()
      }
    }
},
```

Any idea on how to use custom icon with custom button in header?

Here's the error:

![image](https://user-images.githubusercontent.com/44769573/208920575-ab1fbb0d-dae7-41d4-8b23-1f2d83403e36.png)

**Comment by acerix** [comment]
Would you be able to post a [runnable, stripped-down demonstration of the bug](http://fullcalendar.io/wiki/Reduced-Test-Cases/)? Would really appreciate it because the time saved reproducing will be time spent fixing.
