### ISSUE TITLE
Warning: index.js:193 Duplicate plugin '@fullcalendar/premium-common'

### ISSUE THREAD

**Issue by dariovinci** [fullcalendar/fullcalendar#7101]
### Reduced Test Case

xxx

### Do you understand that if a reduced test case is not provided, we will intentionally delay triaging of your ticket?

- [X] I understand

### Which connector are you using (React/Angular/etc)?

No connector (vanilla JS)

### Bug Description

Hello, i recently upgraded fullcalendar in a laravel project from 5 to 6. I get this warning in console:

` index.js:193 Duplicate plugin '@fullcalendar/premium-common'`

Import:
`import {
	Calendar
} from '@fullcalendar/core';
import itLocale from '@fullcalendar/core/locales/it';
import timeGridPlugin from '@fullcalendar/timegrid';
import dayGridPlugin from '@fullcalendar/daygrid';
import interactionPlugin from '@fullcalendar/interaction';
import resourceTimeGridPlugin from '@fullcalendar/resource-timegrid';
import listPlugin from '@fullcalendar/list';

try {
	window.Calendar = Calendar;
	window.dayGridPlugin = dayGridPlugin;
	window.timeGridPlugin = timeGridPlugin;
	window.interactionPlugin = interactionPlugin;
	window.resourceTimeGridPlugin = resourceTimeGridPlugin;
	window.listPlugin = listPlugin;
	window.itLocale = itLocale;
} catch (e) {}`

Calendar conf:

`var calendarEl = document.getElementById('calendar');
	var calendar = new Calendar(calendarEl, {
		plugins: [timeGridPlugin, interactionPlugin, resourceTimeGridPlugin],`

Is it a bug?

**Comment by arshaw** [comment]
Can you copy and paste your package.json please ?

**Comment by dariovinci** [comment]
`{
	"private": true,
	"scripts": {
		"dev": "npm run development",
		"development": "mix",
		"watch": "mix watch",
		"watch-poll": "mix watch -- --watch-options-poll=1000",
		"hot": "mix watch --hot",
		"prod": "npm run production",
		"production": "mix --production"
	},
	"devDependencies": {
		"@popperjs/core": "^2.11.6",
		"bootstrap": "^5.2.3",
		"cross-env": "^7.0.3",
		"jquery": "^3.6.3",
		"laravel-mix": "^6.0.49",
		"resolve-url-loader": "^5.0.0",
		"sass": "^1.57.1",
		"sass-loader": "^13.2.0"
	},
	"dependencies": {
		"@fullcalendar/core": "^6.0.1",
		"@fullcalendar/daygrid": "^6.0.1",
		"@fullcalendar/interaction": "^6.0.1",
		"@fullcalendar/list": "^6.0.1",
		"@fullcalendar/resource": "^6.0.1",
		"@fullcalendar/resource-timegrid": "^6.0.1",
		"@fullcalendar/timegrid": "^6.0.1",
		"@nite1984/nite-autocomplete": "^1.0.5",
		"@nite1984/nite-bs-toast": "^1.0.3",
		"bootstrap-icons": "^1.10.2",
		"chart.js": "^4.1.1",
		"codice-fiscale-js": "^2.3.20",
		"datatables.net-bs5": "^1.13.1",
		"datatables.net-buttons": "^2.3.3",
		"datatables.net-buttons-bs5": "^2.3.3",
		"datatables.net-responsive": "^2.4.0",
		"datatables.net-responsive-bs5": "^2.4.0",
		"datatables.net-select-bs5": "^1.5.0",
		"dropzone": "^5.9.3",
		"flatpickr": "^4.6.13",
		"jsbarcode": "^3.11.5",
		"jszip": "^3.10.1",
		"moment": "^2.29.4",
		"tinymce": "^6.3.1",
		"trumbowyg": "^2.26.0"
	}
}
`

**Comment by dariovinci** [comment]
@arshaw 
i also have 2 other pages that display a calendar one uses only the list plugin and the other one uses  only the day grid plugin. All calendars use the same compiled js file. I get this warning only with the configuration posted above.

**Comment by arshaw** [comment]
Thanks. I still can't figure out why this is happening for you.

Can you give me the output of `npm ls @fullcalendar/premium-common` (or `yarn why @fullcalendar/premium-common`) ?

**Comment by dariovinci** [comment]
├─┬ @fullcalendar/resource-timegrid@6.0.1
│ ├── @fullcalendar/premium-common@6.0.1
│ └─┬ @fullcalendar/resource-daygrid@6.0.1
│   └── @fullcalendar/premium-common@6.0.1
└─┬ @fullcalendar/resource@6.0.1
  └── @fullcalendar/premium-common@6.0.1

**Comment by dariovinci** [comment]
@arshaw i usually check for updates using the utility npm-check. So i updated fullcalendar packages using npm-check but it seems something was wrong in the dependecies tree because after running npm update and compiling i don't get the warning. Sorry for wasting your time
