### ISSUE TITLE
locale: esLocale display Label time 0p.m.

### ISSUE THREAD

**Issue by andresmarinmc** [fullcalendar/fullcalendar#7102]
### Reduced Test Case

https://codepen.io/pen?&editors=001

### Do you understand that if a reduced test case is not provided, we will intentionally delay triaging of your ticket?

- [X] I understand

### Which connector are you using (React/Angular/etc)?

Angular

### Bug Description

How can I make it show 12p.m. when I use locale: esLocale instead of 0p.m. Please, thank you.

![image](https://user-images.githubusercontent.com/109113733/209054022-d2a86fab-30e3-4505-81eb-e5bc23c4e2d0.png)

**Comment by acerix** [comment]
You could use the `es-US` locale which uses 12:

https://codepen.io/acerix/pen/mdjJWmR?editors=001

**Comment by andresmarinmc** [comment]
Thank you men!
