### ISSUE TITLE
Infinite re-rendering occurs when using navLink property and dayCellContent property together in Fullcalendar v6

### ISSUE THREAD

**Issue by ethan-heo** [fullcalendar/fullcalendar#7107]
### Reduced Test Case

https://codesandbox.io/s/fullcalendar-day-cell-content-re-render-issue-jpq8bw?file=/src/App.tsx

### Do you understand that if a reduced test case is not provided, we will intentionally delay triaging of your ticket?

- [X] I understand

### Which connector are you using (React/Angular/etc)?

React

### Bug Description

Using navLink attribute and dayCellContent attribute together causes infinite re-rendering

**Comment by arshaw** [comment]
Fixed in [v6.0.2](https://github.com/fullcalendar/fullcalendar/releases/tag/v6.0.2)

Updated repro without error:
https://codesandbox.io/s/fullcalendar-day-cell-content-re-render-issue-forked-i2qusq?file=/src/App.tsx
