### ISSUE TITLE
version 6 is broken for react?

### ISSUE THREAD

**Issue by jamalsoueidan** [fullcalendar/fullcalendar#7109]
### Reduced Test Case

.

### Do you understand that if a reduced test case is not provided, we will intentionally delay triaging of your ticket?

- [X] I understand

### Which connector are you using (React/Angular/etc)?

React

### Bug Description

See screenshot below:

<img width="1692" alt="Screenshot 2022-12-26 at 01 45 34" src="https://user-images.githubusercontent.com/115714/209483710-ea4a2db6-7036-4b7b-8c9c-bf66c9b69fdc.png">

I did only npm install and npm start.

But it's already broken, I'm doing something wrong?

**Comment by arshaw** [comment]
Everything works for me after a fresh install
![Screen Shot 2022-12-27 at 5 17 52 PM](https://user-images.githubusercontent.com/56520/209727369-1552b59a-2a86-4306-8bd9-dcf80b015e1b.png)

**Comment by arshaw** [comment]
Can you tell me exactly which repo and subdirectory you're getting the example project from?

**Comment by jamalsoueidan** [comment]
I happened in my personal project, and also when I tried this example.
https://github.com/fullcalendar/fullcalendar-examples/tree/main/react-typescript.
