### ISSUE TITLE
multiple day header issue

### ISSUE THREAD

**Issue by arjunshivhare1** [fullcalendar/fullcalendar#7111]
### Reduced Test Case

I dont have

### Do you understand that if a reduced test case is not provided, we will intentionally delay triaging of your ticket?

- [x] I understand

### Which connector are you using (React/Angular/etc)?

React

### Bug Description

creating multiple day Header Content on clicking  next week or any other button when we are using  day Header Content
I have tried degrading versions also but it is not working 

<FullCalendar
            plugins={[timeGridPlugin]}
            initialView="timeGridWeek"
            events={events}
            headerToolbar={headerToolbar}
            eventContent={renderEventContent}
            eventClick={handleOpenModal}
            slotDuration={"01:00"}
            titleFormat={titleFormat}
            customButtons={customButtons}
            dayHeaderClassNames="my-day"
            dayHeaderContent="fff"

            //dayHeaderContent={dayHeaderContent}
          />

![Screenshot (70)](https://user-images.githubusercontent.com/82216887/209568567-607af673-06c1-41d0-98c0-bcedcb4449cf.png)

**Comment by acerix** [comment]
Would you be able to post a [runnable, stripped-down demonstration of the bug](http://fullcalendar.io/wiki/Reduced-Test-Cases/)? Would really appreciate it because the time saved reproducing will be time spent fixing.
