### ISSUE TITLE
Webpack 5: Import fails to resolve with Module not found error

### ISSUE THREAD

**Issue by puppe82** [fullcalendar/fullcalendar#7114]
### Do you understand that if a reduced test case is not provided, we will intentionally delay triaging of your ticket?

- [X] I understand

### Bug Description

**After upgrading to FullCalendar v6, I get an error about failing to resolve a dependency.**
```
App •  ERROR  •  UI  in ./node_modules/@fullcalendar/vue3/dist/index.js

Module not found: Can't resolve imported dependency "./FullCalendar" 
```

When I checked the file mentioned in the error, it looks like this:

<img width="640" alt="fullcalendar-missing-dependency" src="https://user-images.githubusercontent.com/121555417/209811003-cdf1d6c2-4138-4adc-93dd-ae805d09c825.png">

If I change the first line with the import to include the file extension `.js`, I get two new similar errors:
```
 App •  ERROR  •  UI  in ./node_modules/@fullcalendar/vue3/dist/FullCalendar.js

Module not found: Can't resolve imported dependency "./options"

 App •  ERROR  •  UI  in ./node_modules/@fullcalendar/vue3/dist/FullCalendar.js

Module not found: Can't resolve imported dependency "./utils"
```

That file called `FullCalendar.js` looks like this:

<img width="640" alt="fullcalendar-missing-dependency2" src="https://user-images.githubusercontent.com/121555417/209811084-80b332ed-1d4d-495b-aafa-743894eab2c2.png">

Adding the file extension `.js` to imports on lines 4 and 5 seems to fix the issues, and the library starts to work as expected.
```
import { OPTION_IS_COMPLEX } from './options.js';
import { shallowCopy } from './utils.js';
```

----

I have tried to find information online about whether the issue is in my own configuration or in the library's source code but so far I haven't been able to find any other fix than adding the `.js` file extension on the above mentioned lines for the imports.

**This issue appeared after upgrading to `@fullcalendar/vue3` version `6.0.0`, and the same issue persists in versions `6.0.1` and `6.0.2`**

**Could it be that [package.json](https://github.com/fullcalendar/fullcalendar-vue/blob/main/package.json) needs some extra rule or setting that the generated files in `dist/` folder would have the imports with `.js` file extensions?**

---- 

In case this issue depends on the package manager, I'm using `yarn` in my project.
```
$ yarn --version
1.22.19
```

Additionally, here are my `node` and `npm` versions.
```
$ node --version
v18.12.1

$ npm --version
8.19.2
```

**Comment by acerix** [comment]
Would you be able to post a [runnable, stripped-down demonstration of the bug](http://fullcalendar.io/wiki/Reduced-Test-Cases/)? Would really appreciate it because the time saved reproducing will be time spent fixing.

You can use this example project as a starting point, I didn't have any issue building with yarn:

https://github.com/fullcalendar/fullcalendar-examples/tree/main/vue3

**Comment by puppe82** [comment]
I could try to post a demonstration of the bug. I'm using FullCalendar as a part of a Quasar (https://quasar.dev/) project and do understand that the issue might not always be present when using Vue 3.

Nonetheless, I guess the question is whether there is a reason to omit the file extension in the `import` statements.

Is it possible that I'm running into the problem described below?

> **Node.js doesn’t supports imports without file extension:**
>
> `import client from './client';`
>
> **This will be error, extension should be provided:**
>
> `import client from './client.js';`
>
> **Extensions can be:**
>
> `js`
> `mjs`
> `cjs`
>
> And need to be resolved, checking what kind of a file exists.
> 
> **In CommonJS was no such a problem, we can avoid extension:**
> 
> `const client = require(‘./client’);`
> 
> Because of autoresolver. 
>
> Source: https://lightrun.com/answers/import-js-eslint-plugin-import-auto-fix-of-import-without-extension

**Comment by puppe82** [comment]
I had a look into other packages in the `node_modules` folder, and it seems like FullCalendar is the only one omiting the extension in `.js` files when something is imported from a "local" file.

I'll let you know if I find another example of a package in which the file extension is omitted in the `import` statements. During the past two years developing my project this is the first time I encounter this issue.

Any help would be appreciated if there's some _flag_ or _setting_ I could enable to fix the issue.

I'm paying for the license and think this is a wonderful project but instead of sending an email decided to ask here if someone else is facing the same issue - or possibly knows how to fix it.

Below are some examples of other packages.

<img width="640" alt="Screenshot 2022-12-29 at 0 05 45" src="https://user-images.githubusercontent.com/121555417/209877329-8675c5f9-c85f-4fdc-9925-c81ce92ce6ce.png">
<img width="640" alt="Screenshot 2022-12-29 at 0 05 17" src="https://user-images.githubusercontent.com/121555417/209877331-772b7553-aaa4-4a1d-88ee-a2480b57a311.png">
<img width="640" alt="Screenshot 2022-12-29 at 0 03 57" src="https://user-images.githubusercontent.com/121555417/209877332-94d4f641-62b3-48e4-b084-d695b2f514bb.png">

**Comment by puppe82** [comment]
> Would you be able to post a [runnable, stripped-down demonstration of the bug](http://fullcalendar.io/wiki/Reduced-Test-Cases/)? Would really appreciate it because the time saved reproducing will be time spent fixing.

### FullCalendar v6
https://stackblitz.com/edit/quasarframework-webpack-wsrvk3?file=package.json
 
### FullCalendar v5
https://stackblitz.com/edit/quasarframework-webpack-biw33g?file=package.json

**Comment by puppe82** [comment]
@acerix 

I have now added stripped-down demonstration of the issue comparing `v5` and `v6`. As you can see, it's enough to have just the `import` without actually using FullCalendar on the page.

```
import FullCalendar from '@fullcalendar/vue3';
```

**Comment by puppe82** [comment]
I also cloned the repo (https://github.com/fullcalendar/fullcalendar-vue) added the missing file extensions and ran `pnpm build`. To my knowledge, this fixes the issue.

----

### `src/`
<img width="640" alt="Screenshot 2022-12-29 at 17 21 16" src="https://user-images.githubusercontent.com/121555417/209974049-20632413-6ab0-4707-a1c9-f2e4053f656c.png">
<img width="640" alt="Screenshot 2022-12-29 at 17 21 04" src="https://user-images.githubusercontent.com/121555417/209974092-5a546fe6-e0a3-4e48-9f8b-1279acf93fa5.png">


### `dist/`
<img width="640" alt="Screenshot 2022-12-29 at 17 21 42" src="https://user-images.githubusercontent.com/121555417/209974127-dfa6abd0-0059-45fc-83ac-a34ea9e84277.png">
<img width="640" alt="Screenshot 2022-12-29 at 17 21 30" src="https://user-images.githubusercontent.com/121555417/209974150-33b440ea-3713-4c5f-bbf2-babe36dd45dd.png">

**Comment by acerix** [comment]
Thanks for the demos, I can confirm there's an issue with importing this way, although I'm not sure it's a bug that the extensions are missing.  I also see this error which sounds like the issue is with using `fully specified` resolution.

```
Module not found: Error: Can't resolve './FullCalendar' in '/home/projects/quasarframework-webpack-4gwkdk/node_modules/@fullcalendar/vue3/dist'
Did you mean 'FullCalendar.js'?
BREAKING CHANGE: The request './FullCalendar' failed to resolve only because it was resolved as fully specified
(probably because the origin is strict EcmaScript Module, e. g. a module with javascript mimetype, a '*.mjs' file, or a '*.js' file where the package.json contains '"type": "module"').
The extension in the request is mandatory for it to be fully specified.
Add the extension to the request.
```

I found a suggestion here to disable that in Webpack settings:

https://github.com/quasarframework/quasar/discussions/9103#discussioncomment-676385

And this seems to resolve the error in your demo:

https://stackblitz.com/edit/quasarframework-webpack-csyqoy?file=quasar.config.js%3AL77

**Comment by puppe82** [comment]
> [...] although I'm not sure it's a bug that the extensions are missing. I also see this error which sounds like the issue is with using fully specified resolution.

Basically what that `fully specified` means is that you cannot omit the file extension if the `package.json` says `"type": "module"` like it does for FullCalendar.

I'll leave it to you if you want to fix it or not.

Thank you for the reference when it comes to Quasar and Webpack settings. It will most probably fix the issue and is exactly the "flag or setting" I was looking for in the previous messages. Nonetheless, it's just a Webpack configuration and shouldn't have anything to do with Quasar. It's rather a workaround to get FullCalendar 6.x working with Webpack 5.

---- 

```
In .mjs files or .js files with a package.json with "type": "module" imports
need to be fully specified. This means you need to have an extension.
```
https://github.com/webpack/webpack/issues/11467

**Comment by puppe82** [comment]
## Module

### Rule.resolve

#### resolve.fullySpecified

https://webpack.js.org/configuration/module/#resolvefullyspecified

**Comment by puppe82** [comment]
I can confirm that `fullySpecified: false` did indeed solve the issue.

Thank you for all the help!

**Comment by arshaw** [comment]
the proper fix is queued for release https://github.com/fullcalendar/fullcalendar-vue/commit/ad6964818351d8152ad3aa6807a17cddcca44be6

**Comment by arshaw** [comment]
released. see https://github.com/fullcalendar/fullcalendar/issues/7125#issuecomment-1379565348
