### ISSUE TITLE
More link from `eventMaxStack` not positioned below events

### ISSUE THREAD

**Issue by abdellah96** [fullcalendar/fullcalendar#7115]
### Reduced Test Case

https://github-965zvr.stackblitz.io/

### Do you understand that if a reduced test case is not provided, we will intentionally delay triaging of your ticket?

- [X] I understand

### Which connector are you using (React/Angular/etc)?

Angular

### Bug Description

More Link is not working properly as in V5 for resource timeline. When eventMaxStack  is reached, the more link is shown next to resources instead of being under the stack. 
Another bug, When there is more stacks attached to the same resource, there is only one more button shown. The number of hidden elements is equal to the sum of all hidden element of all stacks.

Summary:
The expected behavior as in v5 is to show the num of hidden element for each stack under the stack. 
The actual behavior in v6 show the sum of hidden elements of all stack attached to a resource next to resource column in the beginning of timeline.

![image](https://user-images.githubusercontent.com/25712997/209823185-d2400399-7dcb-47e5-8a09-1d64a56975c2.png)

**Comment by acerix** [comment]
Thanks, confirmed.  Your test case doesn't load for me but I get the same issue in our debug template:

https://codepen.io/acerix/pen/abjdrEz?editors=001

**Comment by arshaw** [comment]
confirmed.

this is a regression. [worked in v5](https://codepen.io/arshaw/pen/xxJqwBv?editors=0010)

**Comment by arshaw** [comment]
queued for release https://github.com/fullcalendar/fullcalendar-workspace/commit/f6b5cf9057be7da70b7b21e84a5ee6f995dc99db

**Comment by arshaw** [comment]
Released in [v6.0.3](https://github.com/fullcalendar/fullcalendar/releases/tag/v6.0.3)

Updated repro:
https://codepen.io/arshaw/pen/JjBNrBr?editors=001
