### ISSUE TITLE
Maximum update depth exceeded when using eventContent and dayMaxEvents with events extending to the next day

### ISSUE THREAD

**Issue by ethan-heo** [fullcalendar/fullcalendar#7116]
### Reduced Test Case

https://codesandbox.io/s/fullcalendar-issue-rfj5vl

### Do you understand that if a reduced test case is not provided, we will intentionally delay triaging of your ticket?

- [X] I understand

### Which connector are you using (React/Angular/etc)?

React

### Bug Description

A problem occurs when you use eventContent and dayMaxEvents together and the event data contains data whose end date exceeds the next day relative to the start date.

The mock data was created as of December 2022, so please check the calendar for December last year.

**Comment by acerix** [comment]
Thanks confirmed.  As a workaround, it seems to work by changing `eventOrder` so the events are not sorted by start time:

https://codesandbox.io/s/fullcalendar-issue-forked-5g9qlg?file=/src/App.tsx

**Comment by ethan-heo** [comment]
Thank you for answer. But this doesn't seem to be a fundamental solution. This solution is tied to development requirements and is difficult to change. 😥

**Comment by arshaw** [comment]
confirmed. this is a regression ([it worked in v5](https://codesandbox.io/s/fullcalendar-issue-forked-vecbij?file=/src/App.tsx))

**Comment by arshaw** [comment]
queued for release https://github.com/fullcalendar/fullcalendar-workspace/commit/a6679459ad0a25d1092034b0c21d5c40caabe229

**Comment by arshaw** [comment]
Released in [v6.0.3](https://github.com/fullcalendar/fullcalendar/releases/tag/v6.0.3)

Updated repro:
https://codesandbox.io/s/fullcalendar-issue-forked-gcvtbn?file=/src/App.tsx
