### ISSUE TITLE
luxon peer dependency version is not aligned between fullcalendar/luxon2 and @angular/material-luxon-adapter

### ISSUE THREAD

**Issue by dpeese** [fullcalendar/fullcalendar#7117]
### Reduced Test Case

https://www.npmjs.com/package/@fullcalendar/luxon2?activeTab=explore

### Do you understand that if a reduced test case is not provided, we will intentionally delay triaging of your ticket?

- [X] I understand

### Which connector are you using (React/Angular/etc)?

Angular

### Bug Description

fullcalendar/luxon2 has luxon: ^2.0.0 version as peer dependency
"peerDependencies": {
    "@fullcalendar/core": "~6.0.2",
    "luxon": "^2.0.0"
  },
@angular/material-luxon-adapter has  "luxon": "^3.0.0"version as peer dependency

 "peerDependencies": {
    "@angular/material": "15.0.3",
    "@angular/core": "^15.0.0 || ^16.0.0",
    "luxon": "^3.0.0"
  },

Its conflicting in applications where fullcalendar and angular material is used while upgrading to ANgular V15. Could you please look into this and upgrade luxon version in  fullcalendar/luxon2 ?

**Comment by JijiyaT** [comment]
yes we are also facing the same issue.

**Comment by acerix** [comment]
I believe this existing ticket captures this need:
https://github.com/fullcalendar/fullcalendar/issues/6957
↑
Please visit the above issue, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates.
