### ISSUE TITLE
moreLinkContent is not updated with current state

### ISSUE THREAD

**Issue by Mohamedsobhy292** [fullcalendar/fullcalendar#7119]
### Reduced Test Case

https://codesandbox.io/s/vigorous-frog-osk7hq?file=/src/App.js

### Do you understand that if a reduced test case is not provided, we will intentionally delay triaging of your ticket?

- [X] I understand

### Which connector are you using (React/Angular/etc)?

React

### Bug Description

- after upgrading to version 6.2 the custom more link component is not rendering when there's a prop passed it from the calendar component have changed 

### steps to reproduce 
- open the codesandbox link
- click on the increase count button
- the count passed to the component still the same

**Comment by acerix** [comment]
It seems the link is re-rendered, but for some reason it gets the initial `count` instead of the current state.

https://codesandbox.io/s/strange-almeida-s3spiw?file=/src/App.js

Since that works, you could store a copy of the value as a global and use that as a workaround.

**Comment by arshaw** [comment]
queued for release https://github.com/fullcalendar/fullcalendar-react/compare/e822df64d09092dcabaeda40ddbca1f7e0cd9549...28652f436d7d97ead6ec6596ad2f40e923f7bfcb

**Comment by arshaw** [comment]
Released in [v6.0.3](https://github.com/fullcalendar/fullcalendar/releases/tag/v6.0.3)

Updated repro: https://codesandbox.io/s/crazy-tree-sulosc?file=/src/App.js
