### ISSUE TITLE
Sort dates descending on List Views 

### ISSUE THREAD

**Issue by mitcht** [fullcalendar/fullcalendar#7123]
### Checklist

- [X] I've already searched through [existing tickets](https://github.com/fullcalendar/fullcalendar/issues)
- [X] Other people will find this feature useful

### Is this feature for a specific connector (React/Angular/etc)?

No connector in particular

### Feature Description

This shows how the FullCalendar currently works, and needs to be sorted descending instead of ascending.

![image](https://user-images.githubusercontent.com/750330/210800687-103cb7c7-4520-4b57-a4d2-64c708d4f424.png)

I have an instance where I am creating a 4 month list view of "recent events" at our organization.   I would love to be able to show the most recent items first, with each preceding month below the next, essentially reversing chronologically the entire list.

Scrolling downward would be akin to scrolling to older items.

The way List views currently work, they cannot be inverted like this.  Only the oldest items are first, and one must scroll down to find the newer items.

I've seen a "hack" on stackoverflow showing how the HTML can be shuffled using query, on a hook, but it seems like that... a hack.

Edit:  Including the code I'm using to initialize.  Yes, we _are_ a nonprofit.
```
var calendar = new window.FullCalendar.Calendar(calendarEl, {
    headerToolbar: false,
    schedulerLicenseKey: "CC-Attribution-NonCommercial-NoDerivatives", // https://fullcalendar.io/license
    noEventsContent: "At this time, there are no Sigma Events",
    aspectRatio: 1.8,
    now: self.moment().subtract(3, 'months').format(),
    views: {
        fourMonth: {
            type: 'list',
            duration: { months: 5 },
                            
         }
                  },
    initialView: "fourMonth",
    resourceAreaWidth: "20%",
    events: self.upcomingCalendarEvents
});
```
Referencing ticket https://github.com/fullcalendar/fullcalendar/issues/3352 but I am suggesting something I am trying to do with a custom view.

**Comment by mitcht** [comment]
Referencing ticket https://github.com/fullcalendar/fullcalendar/issues/3352 but I am suggesting something I am trying to do with a custom view.

**Comment by acerix** [comment]
I believe this existing ticket captures this need:
https://github.com/fullcalendar/fullcalendar/issues/3647
↑
Please visit the above issue, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates.
