### ISSUE TITLE
Navigate to previous year

### ISSUE THREAD

**Issue by GhoroudRizk96** [fullcalendar/fullcalendar#7126]
### Checklist

- [X] I've already searched through [existing tickets](https://github.com/fullcalendar/fullcalendar/issues)
- [X] Other people will find this feature useful

### Is this feature for a specific connector (React/Angular/etc)?

No connector in particular

### Feature Description

I'm using FullCalendar v5, when navigating to previous year the calendar doesn't work normally and after investigation we have found that the Calendar.prevYear() function compare the dates with the time zones, when a server is set to EST time zone then the current date is calculated with GMT -5 hours so it displays the date 31-12-2021 however the current date should be 01-01-2022, and when the server is set to any time zone +GMT or 0 GMT it works normally and the current date is 01-01-2022, the issue happens only when there is a different between the server time and GMT with - value.
Please check attached screenshots for more clarification.
Wrong Behavior:
![GMT-](https://user-images.githubusercontent.com/36767697/210810568-937e5c4d-37b8-4d49-8d1c-c46e4c3fd731.png)

Expected Behavior:
![GMT+](https://user-images.githubusercontent.com/36767697/210810607-bae7d3b8-d8b7-4a85-b030-6a0e1d466fca.png)

**Comment by acerix** [comment]
Would you be able to post a [runnable, stripped-down demonstration of the bug](http://fullcalendar.io/wiki/Reduced-Test-Cases/)? Would really appreciate it because the time saved reproducing will be time spent fixing.
