### ISSUE TITLE
When I request backend data to be displayed on the page, the page will get stuck

### ISSUE THREAD

**Issue by 1075980722** [fullcalendar/fullcalendar#7128]
### Reduced Test Case

http://localhost:3000/fullcalendar/demo

### Do you understand that if a reduced test case is not provided, we will intentionally delay triaging of your ticket?

- [X] I understand

### Which connector are you using (React/Angular/etc)?

Vue

### Bug Description

![image](https://user-images.githubusercontent.com/57121909/211135038-48b26268-b7b4-4fa7-8017-9d0c70a8d70b.png)
The above page is the data I requested. When I click the agenda I created, the page will be stuck and I can't click anywhere
![image](https://user-images.githubusercontent.com/57121909/211135048-825f1e18-8570-4393-a496-35b4e7bc8fd5.png)
As shown in the figure above, not only the page is stuck, but also the data is lost
As long as I switch to request backend data, the page will be stuck. Is this a version problem？

**Comment by acerix** [comment]
Would you be able to post a [runnable, stripped-down demonstration of the bug](http://fullcalendar.io/wiki/Reduced-Test-Cases/)? Would really appreciate it because the time saved reproducing will be time spent fixing.

Your demo link is not accessible from the internet.
