### ISSUE TITLE
Duplicate views are created on view change for React 17.0.2.

### ISSUE THREAD

**Issue by RyDVi** [fullcalendar/fullcalendar#7131]
### Reduced Test Case

https://codesandbox.io/s/condescending-banzai-mz64qh?file=/src/App.js

### Do you understand that if a reduced test case is not provided, we will intentionally delay triaging of your ticket?

- [X] I understand

### Which connector are you using (React/Angular/etc)?

React

### Bug Description

![image](https://user-images.githubusercontent.com/22216861/211327861-f59310ab-bccf-485f-bf87-4dc8536739f2.png)
For React 17.0.2, duplicate views are created when the view changes or when the previous/next buttons are clicked if an eventContent is passed. For React 18 it works correctly.

**Comment by arshaw** [comment]
Queued for release https://github.com/fullcalendar/fullcalendar-react/commit/c9adc4a9db464aec58cc3803389984764ff1abb5

**Comment by arshaw** [comment]
Released in [v6.0.3](https://github.com/fullcalendar/fullcalendar/releases/tag/v6.0.3)

Updated repro:
https://codesandbox.io/s/youthful-cerf-j37svo?file=/src/App.js
