### ISSUE TITLE
Attribute title  There is a problem with the display when it is a number

### ISSUE THREAD

**Issue by CrazyProgrammerPeng** [fullcalendar/fullcalendar#7133]
### Reduced Test Case

（eventDisplay: 'block'）

### Do you understand that if a reduced test case is not provided, we will intentionally delay triaging of your ticket?

- [X] I understand

### Which connector are you using (React/Angular/etc)?

No connector (vanilla JS)

### Bug Description

![image](https://user-images.githubusercontent.com/50432683/211453748-75aaa85c-e7da-44f1-853e-bc2f26cf8a49.png)

**Comment by acerix** [comment]
Would you be able to post a [runnable, stripped-down demonstration of the bug](http://fullcalendar.io/wiki/Reduced-Test-Cases/)? Would really appreciate it because the time saved reproducing will be time spent fixing.
