### ISSUE TITLE
can't resize event in react

### ISSUE THREAD

**Issue by oysterlovers** [fullcalendar/fullcalendar#7135]
### Reduced Test Case

https://codesandbox.io/s/test-react-redux-typescript-forked-g0014c?file=/src/calendar.tsx

### Do you understand that if a reduced test case is not provided, we will intentionally delay triaging of your ticket?

- [X] I understand

### Which connector are you using (React/Angular/etc)?

React

### Bug Description

can't resize event in react

![image](https://user-images.githubusercontent.com/107333049/211551276-78e18ffb-6beb-4673-97ba-34b929965dcd.png)

expected

same as https://codepen.io/pen?editors=0010

![image](https://user-images.githubusercontent.com/107333049/211551343-aca2409f-8e6a-4e02-9c42-a9a030ebd963.png)

**Comment by acerix** [comment]
Your demo does not run for me, I get "DependencyNotFoundError".

Please post a [runnable, stripped-down demonstration of the bug](http://fullcalendar.io/wiki/Reduced-Test-Cases/), would really appreciate it because the time saved reproducing will be time spent fixing.
