### ISSUE TITLE
Uncaught (in promise) TypeError: Cannot read properties of null (reading 'getBoundingClientRect')

### ISSUE THREAD

**Issue by unicedev** [fullcalendar/fullcalendar#7137]
### Reduced Test Case

https://dashlite.net/demo2/apps-calendar.html

### Do you understand that if a reduced test case is not provided, we will intentionally delay triaging of your ticket?

- [X] I understand

### Which connector are you using (React/Angular/etc)?

No connector (vanilla JS)

### Bug Description

[link to demo](https://dashlite.net/demo2/apps-calendar.html)
Firefox work well!

Chrome, Opera: If clicked "+3 more" i get an error in console  _Uncaught (in promise) TypeError: Cannot read properties of null (reading 'getBoundingClientRect')_ 

[Screenshot](https://ibb.co/8NqmvRp)

fixedMirrorParent: document.body, did not help (

how to fix it ?

**Comment by acerix** [comment]
Please post a [runnable, stripped-down demonstration of the bug](http://fullcalendar.io/wiki/Reduced-Test-Cases/) if there is a bug, for example using codesandbox. Would really appreciate it because the time saved reproducing will be time spent fixing.

**Comment by thanhbinh0995** [comment]
Hi @unicedev , maybe you hide this div .fc .fc-more-popover in css. 
I fixed with this code
```
.fc .fc-more-popover {
    z-index: 0;
    opacity: 0;
}```
