### ISSUE TITLE
Warning about importing react-dom/test-utils for act()

### ISSUE THREAD

**Issue by dunz** [fullcalendar/fullcalendar#7141]
### Reduced Test Case

https://github.com/fullcalendar/fullcalendar-examples

### Do you understand that if a reduced test case is not provided, we will intentionally delay triaging of your ticket?

- [X] I understand

### Which connector are you using (React/Angular/etc)?

No connector (vanilla JS)

### Bug Description

Hello, after version up to 6.0.3, there is a compilation error. Please check.

My environment
- node: v18.12.1
- npm: 8.19.2

---browser error message---
Failed to compile.
Module not found: Can't resolve 'react-dom/test-utils' in '/Users/woowahan/local/ceo-square-front/node_modules/@fullcalendar/react/dist'
node_modules/@fullcalendar/react/dist/index.js

or

index.esm.js:2099 Uncaught Error: Cannot find module 'react-dom/test-utils'
    at webpackMissingModule (index.esm.js:2099:82)
    at ./node_modules/@fullcalendar/react/dist/index.js (index.esm.js:2099:82)
    at __webpack_require__ (bootstrap:19:1)
    at ./src/DemoApp.tsx (injectStylesIntoStyleTag.js:269:1)
    at __webpack_require__ (bootstrap:19:1)
    at nonce:1:1
    at index.tsx:11:3
    at index.js:52721:12

---compile terminal message---
ERROR in ./node_modules/@fullcalendar/react/dist/index.js 4:0-43
Module not found: Error: Can't resolve 'react-dom/test-utils' in '/Users/woowahan/dunz/fullcalendar-examples/react-typescript/node_modules/@fullcalendar/react/dist'
Did you mean 'test-utils.js'?
BREAKING CHANGE: The request 'react-dom/test-utils' failed to resolve only because it was resolved as fully specified
(probably because the origin is strict EcmaScript Module, e. g. a module with javascript mimetype, a '*.mjs' file, or a '*.js' file where the package.json contains '"type": "module"').
The extension in the request is mandatory for it to be fully specified.
Add the extension to the request.
resolve 'react-dom/test-utils' in '/Users/woowahan/dunz/fullcalendar-examples/react-typescript/node_modules/@fullcalendar/react/dist'
  Parsed request is a module
  using description file: /Users/woowahan/dunz/fullcalendar-examples/react-typescript/node_modules/@fullcalendar/react/package.json (relative path: ./dist)
    Field 'browser' doesn't contain a valid alias configuration
    resolve as module
      /Users/woowahan/dunz/fullcalendar-examples/react-typescript/node_modules/@fullcalendar/react/dist/node_modules doesn't exist or is not a directory
      /Users/woowahan/dunz/fullcalendar-examples/react-typescript/node_modules/@fullcalendar/react/node_modules doesn't exist or is not a directory
      /Users/woowahan/dunz/fullcalendar-examples/react-typescript/node_modules/@fullcalendar/node_modules doesn't exist or is not a directory
      /Users/woowahan/dunz/fullcalendar-examples/react-typescript/node_modules/node_modules doesn't exist or is not a directory
      looking for modules in /Users/woowahan/dunz/fullcalendar-examples/react-typescript/node_modules
        existing directory /Users/woowahan/dunz/fullcalendar-examples/react-typescript/node_modules/react-dom
          using description file: /Users/woowahan/dunz/fullcalendar-examples/react-typescript/node_modules/react-dom/package.json (relative path: .)
            using description file: /Users/woowahan/dunz/fullcalendar-examples/react-typescript/node_modules/react-dom/package.json (relative path: ./test-utils)
              /Users/woowahan/dunz/fullcalendar-examples/react-typescript/node_modules/react-dom/test-utils doesn't exist
      /Users/woowahan/dunz/fullcalendar-examples/node_modules doesn't exist or is not a directory
      /Users/woowahan/dunz/node_modules doesn't exist or is not a directory
      /Users/woowahan/node_modules doesn't exist or is not a directory
      /Users/node_modules doesn't exist or is not a directory
      /node_modules doesn't exist or is not a directory
 @ ./src/DemoApp.tsx 18:0-47 110:36-48
 @ ./src/index.tsx 3:0-32 6:31-38

**Comment by acerix** [comment]
Thanks, confirmed.  As a workaround, it builds with `fullySpecified: false` in webpack.config.js: 

https://webpack.js.org/configuration/module/#resolvefullyspecified

**Comment by dunz** [comment]
Thank you for being loaded normally.

**Comment by arshaw** [comment]
@dunz , are you using React 17?

Seems like React 18 correctly maps the test-utils endpoint ([package.json](https://cdn.jsdelivr.net/npm/react-dom@18.2.0/package.json)) whereas React 17 does not ([package.json](https://cdn.jsdelivr.net/npm/react-dom@17.0.2/package.json))

**Comment by arshaw** [comment]
Fixed in this bugfix release: [v6.0.4](https://github.com/fullcalendar/fullcalendar/releases/tag/v6.0.4)
