### ISSUE TITLE
Angular examples on stackblitz have typeerror and do not display calendar

### ISSUE THREAD

**Issue by atoyansk** [fullcalendar/fullcalendar#7143]
### Reduced Test Case

https://stackblitz.com/github/fullcalendar/fullcalendar-examples/tree/main/angular14

### Do you understand that if a reduced test case is not provided, we will intentionally delay triaging of your ticket?

- [X] I understand

### Which connector are you using (React/Angular/etc)?

Angular

### Bug Description

Following the docs, no error is shown, but the calendar is not displaying at all.
Locally, I did try to add the bind `[plugins]="calendarOptions.plugins"` in template file, and finally the calendar was shown.

`<full-calendar [options]="calendarOptions" [plugins]="calendarOptions.plugins"></full-calendar>`

However, it occurs an error in console:
```
TypeError: Cannot read properties of undefined (reading 'plugins')
    at AppointmentComponent_Template (appointment.component.html:4:61)
```
In stackblitz this workaround didn't work, only locally.

**Comment by acerix** [comment]
Thanks, confirmed.

I get this error in console in the examples on stackblitz:

```
ERROR TypeError: Cannot read properties of undefined (reading 'isHiddenDay')
    at new DaySeriesModel (internal-common.esm.js:5452:38)
    at DayTableView.buildDayTableModel (internal.js:829:21)
    at DayTableView.eval [as buildDayTableModel] (internal-common.esm.js:934:37)
    at DayTableView.render (internal.js:820:34)
    at I (preact.js:1:5778)
    at b (preact.js:1:2238)
    at j (preact.js:1:7380)
    at I (preact.js:1:6344)
    at b (preact.js:1:2238)
    at I (preact.js:1:6162)
console.<computed> @ preview-d8f6f8d9bb56a.js:2
```

Although I tried building the same angular14 example locally and it displays the calendar without any error so it seems  like something with stackblitz.

**Comment by arshaw** [comment]
This `isHiddenDay` error occurs when multiple versions of the @fullcalendar/core library are loaded.  The stackblitz angular compilation seems be including both the cjs and esm versions of each lib. They are interleaved. Very hard to investigate why this is happening, especially since it's working fine when built outside of stackblitz.

**Comment by zarix** [comment]
I got the same error with Vue and Webpacker

**Comment by zarix** [comment]
yes 
i use:

- Docker Debian bullseye-slim with Ruby on Rails and Webpacker
- Vue 2
- fullcalendar 6.0.3
- installed via yarn

The following error messages:

- Brave and Chrome: ERROR TypeError: Cannot read properties of undefined (reading 'isHiddenDay')
- in Firefox: Error in mounted hook: "TypeError: dateProfileGenerator is undefined"

I deleted and reloaded the node_modules folder and yarn.lock file, but this did not result in any change.

**Comment by DavidSichau** [comment]
We observe a similar behavior with react:

react: 18.2.0
@fullcalendar/core: 6.0.3
@fullcalendar/interaction: 6.0.3,
@fullcalendar/react: 6.0.4,
@fullcalendar/timegrid: 6.0.3,

installed via npm

The following error messages:

Chrome: 
```
Uncaught TypeError: Cannot read properties of undefined (reading 'isHiddenDay')
    at new DaySeriesModel (internal-common.js:5374:38)
    at DayTimeColsView.buildTimeColsModel (internal.js:1150:21)
    at DayTimeColsView.eval [as buildTimeColsModel] (internal-common.js:902:37)
```

in Firefox:
```
Uncaught TypeError: dateProfileGenerator is undefined
    DaySeriesModel /node_modules/@fullcalendar/core/internal-common.js:5374
    buildTimeColsModel /node_modules/@fullcalendar/timegrid/internal.js:1150
    memoize /node_modules/@fullcalendar/core/internal-common.js:902
    render 
```

**Comment by arshaw** [comment]
@DavidSichau , can you please tell me which version of Node you're using?

**Comment by arshaw** [comment]
@DavidSichau , and which bundler you're using (along w/ version)

**Comment by faburem** [comment]
I am experiencing exactly the same issue with the Meteor.js bundler version 2.10.0 which is using NodeJS v14.21.2 under the hood. It was working fine with 6.0.2 and no other code/configuration has been changed.

**Comment by DavidSichau** [comment]
I use Meteor.js bundler version 2.10.0 and NodeJS v14.21.2

**Comment by arshaw** [comment]
@atoyansk and all, [the stackblitz example for Angular 15](https://stackblitz.com/github/fullcalendar/fullcalendar-examples/tree/main/angular15?file=README.md) seems to be working now. Is it working for you?

**Comment by zarix** [comment]
Thank you very much - version 6.1.1 works perfectly for me

**Comment by faburem** [comment]
I can also confirm v6.1.1 is working again as expected with the Meteor.js bundler!
