### ISSUE TITLE
Translate "Week" long text in French

### ISSUE THREAD

**Issue by ebiton-eig** [fullcalendar/fullcalendar#7144]
### Reduced Test Case

https://codepen.io/ebiton/pen/MWBmxxQ

### Do you understand that if a reduced test case is not provided, we will intentionally delay triaging of your ticket?

- [X] I understand

### Which connector are you using (React/Angular/etc)?

Angular

### Bug Description

When you set the title to display only the week followed by its number, the word week is not translated unlike other date formats.

`
    locale: 'fr',
    titleFormat: {
      week: 'long'
    },
`

**Comment by acerix** [comment]
You need to load the locale file for that:

https://fullcalendar.io/docs/locale

**Comment by acerix** [comment]
I just realized this translation is missing for French, so it could be added as it is for other locales, eg.:

https://github.com/fullcalendar/fullcalendar/blob/main/packages/core/src/locales/sv.ts#L35

**Comment by arshaw** [comment]
Released in [v6.1.1](https://github.com/fullcalendar/fullcalendar/releases/tag/v6.1.1)

https://cdn.jsdelivr.net/npm/@fullcalendar/core@6.1.1/locales/fr.js
