### ISSUE TITLE
When use eventContent , "Maximum update depth exceeded"

### ISSUE THREAD

**Issue by dunz** [fullcalendar/fullcalendar#7146]
### Reduced Test Case

https://codesandbox.io/s/fullcalendar-eventcontent-maximum-35gbdz?file=/src/App.tsx

### Do you understand that if a reduced test case is not provided, we will intentionally delay triaging of your ticket?

- [X] I understand

### Which connector are you using (React/Angular/etc)?

React 17

### Bug Description

Hello!
when use "eventContent", immediately occurs error.

However, it is not reproduced in CODESPAN.
Sorry for not being reproduced

It only occurs in local, but if you use only eventContent, you will not know the cause.

Is there any expected part?

In addition, the use of the option of the content is similar to the similar error.

<img width="429" alt="스크린샷 2023-01-16 오후 4 46 32" src="https://user-images.githubusercontent.com/25737303/212624677-f0a14921-32dd-4d93-b092-3e96b8d45f79.png">

If you change to the next month, the calendar is broken.

<img width="759" alt="스크린샷 2023-01-16 오후 4 48 24" src="https://user-images.githubusercontent.com/25737303/212624690-27d2da98-868e-4e6e-b10d-77fafa26274d.png">

<img width="665" alt="스크린샷 2023-01-16 오후 4 46 22" src="https://user-images.githubusercontent.com/25737303/212624709-5a8b1dc8-ae0f-4e5c-ba0b-976f2be68e25.png">

--- error message ---
Error
`
Maximum update depth exceeded. This can happen when a component repeatedly calls setState inside componentWillUpdate or componentDidUpdate. React limits the number of nested updates to prevent infinite loops.
`

Call Stack
 checkForNestedUpdates
  node_modules/react-dom/cjs/react-dom.development.js:23798:15
 scheduleUpdateOnFiber
  node_modules/react-dom/cjs/react-dom.development.js:21830:3
 Object.enqueueSetState
  node_modules/react-dom/cjs/react-dom.development.js:12467:5
 Component.setState
  node_modules/react/cjs/react.development.js:365:16
 eval
  node_modules/@fullcalendar/react/dist/index.js:40:18
 CustomRenderingStore.set
  node_modules/@fullcalendar/core/internal-common.js:7467:13
 CustomRenderingStore.handle
  node_modules/@fullcalendar/core/internal-common.js:7499:18
 ContentInjector.triggerCustomRendering
  node_modules/@fullcalendar/core/internal-common.js:2588:17
 ContentInjector.componentDidUpdate
  node_modules/@fullcalendar/core/internal-common.js:2577:14
 ContentInjector.eval
  node_modules/preact/dist/preact.module.js:16:5652
------------------------------------------------------------------------------------------

--- local environment ---
react: 17.0.2
react-dom: 17.0.2
@fullcalendar/~: 6.0.3
------------------------------------------------------------------------------------------

--- local code ---
```ts
import { CalendarOptions, EventContentArg } from '@fullcalendar/core'
import dayGridPlugin from '@fullcalendar/daygrid'
import interactionPlugin from '@fullcalendar/interaction'
import FullCalendar from '@fullcalendar/react'
import React, { ForwardedRef, forwardRef } from 'react'

import { DESC } from 'pages/Main/style'
import { FILL_COLORS, FOREGROUND_COLORS } from 'styles/style'

import * as S from './styled'

const eventSources = [
  {
    events: [{ title: '가가가 - 카테고리 2', start: '2023-02-03', end: '2023-02-06', st: -1, category: 2 }],
  },
  {
    events: [
      {
        title: '가가가 - 카테고리 2 - startTime 늦음',
        start: '2023-01-01',
        end: '2023-01-03',
        st: 1,
        category: 2,
      },
      { title: '가가가 - 카테고리 2', start: '2023-01-01', end: '2023-01-03', st: -1, category: 2 },
      { title: '가가가 - 카테고리 1', start: '2023-01-01T07:13:44.182', end: '2023-01-03', st: '2023-01-01T07:13:44.182', category: 1 },
      { title: '나나나 - 카테고리 1', start: '2023-01-02', end: '2023-01-05', st: '2023-01-01T07:13:44.182', category: 1 },
      {
        title: '다다다 - 카테고리 3',
        start: '2023-01-03',
        end: '2023-01-03',
        st: '2023-01-01T07:13:44.182',
        category: 3,
      },
    ],
    color: 'red',
  },
]

const renderEventContent = (eventContent: EventContentArg) => (
  <S.EventWrapper>
    <span className="important mr-half-1 text-accent">중요</span>
    {eventContent.timeText && <b className="mr-half-1">{eventContent.timeText}</b>}
    <span>{eventContent.event.title}</span>
  </S.EventWrapper>
)

const Calendar = (props: CalendarOptions, ref: ForwardedRef<FullCalendar>) => {
  return (
    <FullCalendar
      ref={ref}
      plugins={[dayGridPlugin, interactionPlugin]}
      locale="ko"
      height="auto"
      eventOrder="start,-duration,allDay,category,st"
      fixedWeekCount={false}
      editable={true}
      eventResizableFromStart={true}
      dayMaxEvents={3}
      buttonText={{
        today: '오늘',
      }}
      headerToolbar={{
        start: 'title',
        center: '',
        end: 'today prev next',
      }}
      dayHeaderContent={({ text }) => <DESC className="text-secondary">{text}</DESC>}
      eventContent={renderEventContent} // => If you annotation on this part, no error occurs.
      eventColor={FILL_COLORS.tertiary}
      eventTextColor={FOREGROUND_COLORS.primary}
      moreLinkClick={(info) => {
        info.jsEvent.stopPropagation()
        info.jsEvent.stopImmediatePropagation()
        console.log('moreLinkClick', info)
      }}
      // moreLinkContent={() => {
      //   return <>asdf</>
      //   ##}}
      {...props}
    />
  )
}

export default forwardRef(Calendar)
```
------------------------------------------------------------------------------------------

**Comment by acerix** [comment]
We would need a [runnable, stripped-down demonstration of the bug](http://fullcalendar.io/wiki/Reduced-Test-Cases/) to look into this issue,  you can try turning off parts of your code to find what is causing the error and put the same in Codesandbox.  

There was a very similar error fixed in 6.0.3 (https://github.com/fullcalendar/fullcalendar/issues/7116), so if it's the same cause, your local environment may not actually be updated to that version which would fix it.
