### ISSUE TITLE
Bundle build missing from GitHub 6.0.4 release

### ISSUE THREAD

**Issue by indigoxela** [fullcalendar/fullcalendar#7147]
### Reduced Test Case

Not related to the code

### Do you understand that if a reduced test case is not provided, we will intentionally delay triaging of your ticket?

- [X] I understand

### Which connector are you using (React/Angular/etc)?

No connector (vanilla JS)

### Bug Description

Looking at the release page on https://github.com/fullcalendar/fullcalendar/releases/tag/v6.0.4 it seems like the  fullcalendar-6.0.4.zip file is missing, only the source code assets are available.

Unless this is by intention, it might be that the build process needs a little tweak or a second run.

**Comment by guicara** [comment]
That's why version 6.0.4 is not yet available on npmjs.com?

**Comment by arshaw** [comment]
Sorry for the confusion. v6.0.4 was only related to the react connector. the assets we usually build for `fullcalendar` and `fullcalendar-scheduler` remain unchanged. I'll make this clear in the release notes.

**Comment by arshaw** [comment]
(so, just use 6.0.3's assets)
