### ISSUE TITLE
dateClick returns incorrect day with CSS zoom

### ISSUE THREAD

**Issue by luigipam** [fullcalendar/fullcalendar#7148]
### Reduced Test Case

https://fullcalendar.io/demos

### Do you understand that if a reduced test case is not provided, we will intentionally delay triaging of your ticket?

- [X] I understand

### Which connector are you using (React/Angular/etc)?

No connector (vanilla JS)

### Bug Description

Hi... I'm using FullCalendar version 4.31 from Javascript... and I have the following problem: 
Changing the zoom of the document body to a value different than 1 causes FullCalendar on dateClick event to set event.start on an hour/minute that is different from what has been clicked.

I would like to know if there is a fix for the issue above or a workaround I can use.

To reproduce the problem 
1. Open Chrome and go to https://fullcalendar.io/demos (problem is with version 6 as well... but I'm looking for a fix for version 4.31)
2. Click on Selectable dates demo and click the day view
3. Right Click and Inspect
4. On the debug pane navigate to the body of the page and click it
5. On the style add zoom: 1.5
6. Click on the calendar in the 6:30 slot... the new event is added to the 10:30 slot

Thanks in  advance

Luigi

**Comment by acerix** [comment]
I believe this existing ticket captures this need:
https://github.com/fullcalendar/fullcalendar/issues/6825
↑
Please visit the above issue, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates.
