### ISSUE TITLE
Customise the "now" indicator background cell

### ISSUE THREAD

**Issue by Sav22999** [fullcalendar/fullcalendar#7150]
### Checklist

- [X] I've already searched through [existing tickets](https://github.com/fullcalendar/fullcalendar/issues)
- [X] Other people will find this feature useful

### Is this feature for a specific connector (React/Angular/etc)?

No connector in particular

### Feature Description

Now the "now" cell is with a yellow background. I would like customising it

**Comment by acerix** [comment]
The background color is not from the "now indicator", it can be customized with CSS on `--fc-today-bg-color` like this:

https://codepen.io/acerix/pen/YzjrKbr?editors=0110
