### ISSUE TITLE
Custom slot similar to 'All day'

### ISSUE THREAD

**Issue by ItsNoHax** [fullcalendar/fullcalendar#7152]
### Checklist

- [X] I've already searched through [existing tickets](https://github.com/fullcalendar/fullcalendar/issues)
- [X] Other people will find this feature useful

### Is this feature for a specific connector (React/Angular/etc)?

No connector in particular

### Feature Description

One of the feature requirements for our software is to have a custom slot for Tasks (similar to All day but it can be used in combination with all day). (I have a feeling a issue already exists about this but I couldn't find it)

This looks like the following:
![image](https://user-images.githubusercontent.com/4223434/212877107-ccd3b8a6-0108-4714-b627-d2701739d4f1.png)

and with All day combined:
![image](https://user-images.githubusercontent.com/4223434/212877458-07950c72-9f5c-469e-b415-d20a53f7bbde.png)

**Comment by acerix** [comment]
I believe this existing ticket captures this need:
https://github.com/fullcalendar/fullcalendar/issues/3528
↑
Please visit the above issue, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates.
