### ISSUE TITLE
Full calendar not selectable with Next.js

### ISSUE THREAD

**Issue by christianjuth** [fullcalendar/fullcalendar#7155]
### Reduced Test Case

https://github.com/breakthelovenewyork/next-full-calendar-test

### Do you understand that if a reduced test case is not provided, we will intentionally delay triaging of your ticket?

- [X] I understand

### Which connector are you using (React/Angular/etc)?

React

### Try the reduced test case

I linked the repo for the reduced test case, but you can try the deployed version of that reduced test case [here](https://full-calendar-test-christianjuth-breakthelovenewyork.vercel.app/).

### Bug

When I try to interact with full calendar I see this error in the console.

```
407-ab674bd8c72b08ef.js:1 
        
       Uncaught TypeError: Cannot read properties of undefined (reading 'allDay')
    at ns (e501331d-4147ea66e121ec61.js:1:53236)
    at ru.render (e501331d-4147ea66e121ec61.js:1:89153)
    at T (407-ab674bd8c72b08ef.js:1:13663)
    at w (407-ab674bd8c72b08ef.js:1:9982)
    at T (407-ab674bd8c72b08ef.js:1:14047)
    at w (407-ab674bd8c72b08ef.js:1:9982)
    at 407-ab674bd8c72b08ef.js:1:15199
    at T (407-ab674bd8c72b08ef.js:1:15569)
    at w (407-ab674bd8c72b08ef.js:1:9982)
    at T (407-ab674bd8c72b08ef.js:1:14047)
```

Note: this seems to only occur with optimized (production) builds. When running `next dev` I'm not noticing the issue.

### Sort of a fix
I tried disabling minification and that seemed to fixed it, but I can't actually disable minification or that will cause other issues. 

~~Telling next to [transpile all full calendar modules](https://beta.nextjs.org/docs/api-reference/next.config.js#transpilepackages) also seems to fix the issue locally, but as soon as I push to vercel everything breaks. Transpilling also seems like a hack.~~

**Comment by christianjuth** [comment]
After trying a bunch of things, I realized the issue was Next's SWC. I opened an issue on their repo describing the bug https://github.com/vercel/next.js/issues/44983.

**Comment by acerix** [comment]
I tried the same in the example project and didn't have an issue, I believe you need the same workaround mentioned there:

https://github.com/fullcalendar/fullcalendar-examples/tree/main/next-scheduler#workarounds-explained

Please post [runnable, stripped-down demonstration](http://fullcalendar.io/wiki/Reduced-Test-Cases/) if there is a bug, for example using stackblitz.com.

**Comment by mohux** [comment]
I had the same issue with next 13 which enables SWC minify by default,

when I disabled SWC minify manually, its working fine

**Comment by arshaw** [comment]
Reopening because I want to debug further and provide the SWC/Next.js teams with a more precise bug report (what exact line(s) is being minified incorrectly)

**Comment by arshaw** [comment]
I've made [a reduced test case ticket in the SWC repo](https://github.com/fullcalendar/fullcalendar/issues/7155)

**Comment by arshaw** [comment]
A workaround, at least in @christianjuth's case, is to turn  off the `selectMirror` setting

**Comment by arshaw** [comment]
This was bug fixed in SWC, but waiting for Next 13.1.7 to drop before declaring victory.

**Comment by tomohirohiratsuka** [comment]
FYI, nextjs 13.2.1 solved this problem.

**Comment by arshaw** [comment]
After upgrading the [next.js example project](https://github.com/fullcalendar/fullcalendar-examples/tree/main/next13) to 13.2, I also verify this problem is fixed. It's now possible to select via drag & drop.
