### ISSUE TITLE
Custom view `content` that returns JSX does not appear

### ISSUE THREAD

**Issue by Azaryan-A** [fullcalendar/fullcalendar#7160]
### Reduced Test Case

https://github.com/Azaryan-A/fc-v6-custom-view-test

### Do you understand that if a reduced test case is not provided, we will intentionally delay triaging of your ticket?

- [x] I understand

### Which connector are you using (React/Angular/etc)?

React

### Bug Description

Custom view content appears only if its type is a string. But I want to set react component as custom view content. But then nothing was displayed.

**Comment by Azaryan-A** [comment]
Custom views not working after updating from v5 to v6

**Comment by acerix** [comment]
Thanks, confirmed. Here's a runnable:

https://stackblitz.com/edit/github-urj6el?file=src%2FDemoApp.jsx

**Comment by acerix** [comment]
As a workaround, HTML can be returned in an object like this:

https://stackblitz.com/edit/github-urj6el-np94rn?file=src%2FDemoApp.jsx

**Comment by arshaw** [comment]
Fixed since [v6.1.0](https://github.com/fullcalendar/fullcalendar/releases/tag/v6.1.0)

Updated repro: https://stackblitz.com/edit/github-urj6el-qlsbxa?file=src%2FDemoApp.jsx

**Comment by Azaryan-A** [comment]
Thank you guys, now everything is ok. Thank you for your fast response.
