### ISSUE TITLE
5.11 to 6.0.3: Custom CSS is not loaded properly on production build

### ISSUE THREAD

**Issue by malte94** [fullcalendar/fullcalendar#7167]
### Reduced Test Case

-

### Do you understand that if a reduced test case is not provided, we will intentionally delay triaging of your ticket?

- [X] I understand

### Which connector are you using (React/Angular/etc)?

React

### Bug Description

After upgrading from FullCalendar 5.11 to FullCalendar 6.0.3, I encounter a weird issue: My custom CSS is not applied on the production build anymore. However, it is on any local build.

Local build:

https://user-images.githubusercontent.com/89409894/214638782-4f7c6703-8545-4b03-bffd-8e338f642d14.jpg

Production build:

https://user-images.githubusercontent.com/89409894/214638758-ba5e37dc-f1fd-4799-a18a-2c9e11401451.jpg

**Comment by artnikbrothers** [comment]
I have the same issue. Upgraded FullCalendar 5.11 to FullCalendar 6.1.4. I'm using react
