### ISSUE TITLE
scrollTime listWeek/listMonth

### ISSUE THREAD

**Issue by Patrick1900** [fullcalendar/fullcalendar#7168]
### Checklist

- [X] I've already searched through [existing tickets](https://github.com/fullcalendar/fullcalendar/issues)
- [X] Other people will find this feature useful

### Is this feature for a specific connector (React/Angular/etc)?

React

### Feature Description

hi,

it seems that `scrollTime` has no effect on _listWeek/listMonth_

https://codepen.io/patrick1900/pen/poZVaYR

goal is for example to scroll to the actual date

is there currently a possibility/workaround?

if not, would be great to enable it.

**Comment by acerix** [comment]
I believe this existing ticket captures this need:
https://github.com/fullcalendar/fullcalendar/issues/5719
↑
Please visit the above issue, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates.
