### ISSUE TITLE
React 18 Support

### ISSUE THREAD

**Issue by engFelipeMonteiro** [fullcalendar/fullcalendar#7169]
### Checklist

- [X] I've already searched through [existing tickets](https://github.com/fullcalendar/fullcalendar/issues)
- [X] Other people will find this feature useful

### Is this feature for a specific connector (React/Angular/etc)?

React

### Feature Description

I would like to know  if this library have support for react 18.
In the changelogs I did not see
It has been released at march 2022

**Comment by acerix** [comment]
Yes, React 18 is used in the example:

https://github.com/fullcalendar/fullcalendar-examples/blob/5abfa6c35fc3be87b974c7670d1859678db39af6/react/package.json#L19
