### ISSUE TITLE
Runtime Exception when FullCalendar is included using commonJS syntax

### ISSUE THREAD

**Issue by JonathanZeiss** [fullcalendar/fullcalendar#7170]
### Reduced Test Case

https://stackblitz.com/github/JonathanZeiss/fullcalendar-examples/tree/main/react17?file=README.md

### Do you understand that if a reduced test case is not provided, we will intentionally delay triaging of your ticket?

- [X] I understand

### Which connector are you using (React/Angular/etc)?

React

### Bug Description

After the update to FullCalendar v6.x in a project using react and commonJS syntax ("require" instead of "import" and "module.exports" instead of "export") there is an exception at runtime.

To show the problem I forked the examples repository and adapted two of the examples to use the commonJS syntax.
In both examples you can reproduce the exception at runtime.
https://github.com/JonathanZeiss/fullcalendar-examples

react17 example:
Clone the repository, start as described in the readme file to see the error in the debug console or use this link:
https://stackblitz.com/github/JonathanZeiss/fullcalendar-examples/tree/main/react17?file=README.md
![image](https://user-images.githubusercontent.com/72806275/214535090-25800716-0c9d-47b7-acef-6df858328984.png)
![image](https://user-images.githubusercontent.com/72806275/214535179-a10d2fee-398c-4ba4-94f5-ae74b8b1c8f4.png)

webpack example:
Clone the repository, build as described in the readme file and open the index.html file to see the error in the debug console.
![image](https://user-images.githubusercontent.com/72806275/214534708-acda44a2-2ecd-4174-bf97-c3b5b6948469.png)
![image](https://user-images.githubusercontent.com/72806275/214534865-23ef9897-b777-45e1-b0bf-edfa51433304.png)

**Comment by arshaw** [comment]
This should be working with [v6.1.1](https://github.com/fullcalendar/fullcalendar/releases/tag/v6.1.1). I've modified your repro to show. Some additional `.default` imports were needed:

https://stackblitz.com/edit/github-nbdzzb?file=package.json,src%2Findex.jsx,src%2FDemoApp.jsx
