### ISSUE TITLE
FullCalendar 6.x premium plugin fail. defs is not iterable

### ISSUE THREAD

**Issue by timurcatakli** [fullcalendar/fullcalendar#7171]
### Reduced Test Case

http://www.com

### Do you understand that if a reduced test case is not provided, we will intentionally delay triaging of your ticket?

- [X] I understand

### Which connector are you using (React/Angular/etc)?

React

### Bug Description

Hi there,
We are premium users and having the following issue:

First we installed the following library versions using Storybook and Vite. We are using ` React 18.0.2`

<img width="400" alt="SCR-20230127-dd4" src="https://user-images.githubusercontent.com/15508978/215158772-b9460fb4-1095-429c-b5fb-b48d15ec864b.png">

`@fullcalendar/core": "^6.*",`
`@fullcalendar/daygrid": "^6.*",`
`@fullcalendar/interaction": "^6.*",`
`@fullcalendar/list": "^6.*",`
`@fullcalendar/react": "^6.*",`
`@fullcalendar/resource": "^6.*",`
`@fullcalendar/resource-daygrid": "^6.*",`
`@fullcalendar/resource-timegrid": "^6.*",`
`@fullcalendar/resource-timeline": "^6.*",`

Everything worked perfect.

We then switched to `Webpack 5.75.0` with same React version. `18.0.2` using in a micro-app
We started getting the following errors:

![SCR-20230127-dbs](https://user-images.githubusercontent.com/15508978/215158622-a5c0ccd1-0f13-4c88-b826-8af8958f35d5.png)

Hours of research and digging, we temporarily solved the issue by changing the versions as below:

<img width="426" alt="SCR-20230127-ddq" src="https://user-images.githubusercontent.com/15508978/215159176-0fd3aff8-67a2-4a48-9029-85045e98b67a.png">

With above versions Calendar was able to render,  but we are sure this is a temp band-aid and not a proper solution.
We need your help to further investigate this issue.

Creating a reduced test case does not help because everything works fine under limited conditions.

**Comment by acerix** [comment]
We would need a [runnable, stripped-down demonstration](http://fullcalendar.io/wiki/Reduced-Test-Cases/) to look into this if there is a bug.  

You can use this example project for React as a starting point:

https://github.com/fullcalendar/fullcalendar-examples/tree/main/react-scheduler
