### ISSUE TITLE
Missing CSS for 6.0+ releases on CDN

### ISSUE THREAD

**Issue by PrzemyslawKlys** [fullcalendar/fullcalendar#7173]
### Reduced Test Case

https://www.jsdelivr.com/package/npm/fullcalendar?version=6.0.3

### Do you understand that if a reduced test case is not provided, we will intentionally delay triaging of your ticket?

- [X] I understand

### Which connector are you using (React/Angular/etc)?

No connector (vanilla JS)

### Bug Description

It seems on CDN there's only JS available for 6.0+ releases:
- https://cdn.jsdelivr.net/npm/fullcalendar@6.0.3/main.min.css - doesn't work even tho it mentioned it explicitly.
- https://cdn.jsdelivr.net/npm/fullcalendar/ shows no CSS

I thought that maybe it's not being used but without CSS, it doesn't have a look anymore.

**Comment by arshaw** [comment]
I filed a bug with jsDelivr here: https://github.com/jsdelivr/www.jsdelivr.com/issues/497#issue-1562756519

In v6, there are no longer any CSS files. The JS injects the CSS statements on its own
