### ISSUE TITLE
Incompatibility of 'duration' and 'hiddenDays' with 'resourceTimeline' view

### ISSUE THREAD

**Issue by hoangdinhcong** [fullcalendar/fullcalendar#7180]
### Reduced Test Case

https://stackblitz.com/edit/github-uxtd7n?file=src%2Fapp%2Fapp.component.ts,src%2Fapp%2Fapp.component.html

### Do you understand that if a reduced test case is not provided, we will intentionally delay triaging of your ticket?

- [X] I understand

### Which connector are you using (React/Angular/etc)?

Angular

### Bug Description

Hi, 

```typescript
{
    hiddenDays: [4, 5], // Thursday & Friday
    duration: {
      days: 3,
    }
}
```

When I configure it this way, it does not always display the correct days. Sometimes it shows two days and other times it only shows one day

![image](https://user-images.githubusercontent.com/6839256/215718467-3ce36807-594c-4d15-a2a2-0aeae0ae101f.png)

> **Occurs in Full Calendar versions 6.0.0 and 6.1.0**

Please take a look. Thanks 😄

**Comment by acerix** [comment]
I believe this is working as intended; in this case, the duration of the view is always 3 days and the hidden days are just not visible.  

If you are looking to make it work as if those 2 days don't exist, you could use `visibleRange` to customize the range so there are always 3 days visible.

**Comment by hoangdinhcong** [comment]
Thank @acerix for the quick response. I check again and it was my mistake.
turn out **dayCount** is all I need. Remove the **duration** and it works 🚀
