### ISSUE TITLE
Angular Error: NgClass can only toggle CSS classes expressed as strings

### ISSUE THREAD

**Issue by KarolDabrowski** [fullcalendar/fullcalendar#7182]
### Reduced Test Case

https://stackblitz.com/edit/github-eiwdny?file=src/app/app.component.html

### Do you understand that if a reduced test case is not provided, we will intentionally delay triaging of your ticket?

- [X] I understand

### Which connector are you using (React/Angular/etc)?

Angular

### Bug Description

I'm using premium plugin `resource-timegrid` at version 6.1.1 with angular wrapper. I wanted to customize labels of resource columns with custom angular content templates:
```
<full-calendar #calendar
                 [options]='calendarOptions'>
   <ng-template #resourceLabelContent let-arg>
      Whatever
   </ng-template>
</full-calendar>
```
 But  mysterious error keep showing up in the console:
`Error: NgClass can only toggle CSS classes expressed as strings, got undefined`  and lots of uncomprehensible stack traces after. On local serving it somehow works, but on stackblitz it even causes resource labels to not show at all. In both cases, it stains console in red and thats quite nasty.
Is this a bug, or maybe I understood something wrong in usage?😅

![2023-01-31 16_41_15-Fullcalendar - Fullcalendar Examples - StackBlitz](https://user-images.githubusercontent.com/1807530/215807048-fd41b08b-136c-4a97-8a09-dbfd9b85357b.png)

![2023-01-31 16_54_35-Settings](https://user-images.githubusercontent.com/1807530/215810798-2527e5db-4fd4-48d6-84d7-f60789500ff3.png)

**Comment by KarolDabrowski** [comment]
Small update, looking further into, local serving only shows the first custom resource label, but the rest does not show at all after the error.

![image](https://user-images.githubusercontent.com/1807530/215821502-faa766e6-1845-4ea0-b62c-c316d762e5c3.png)

![image](https://user-images.githubusercontent.com/1807530/215821726-d7da6abf-9733-49fa-ab71-6fb80a488b7c.png)

**Comment by iCrawl** [comment]
Just to chip in, same thing happens with the `#dayHeaderContent` injection

**Comment by arshaw** [comment]
queued for release https://github.com/fullcalendar/fullcalendar-workspace/commit/e27502c959b3897d8ae2d6b3e19f7f1e57c49019

**Comment by arshaw** [comment]
Release in [v6.1.3](https://github.com/fullcalendar/fullcalendar/releases/tag/v6.1.3)

Updated repro:
https://stackblitz.com/edit/github-eiwdny-saizsv?file=src%2Fapp%2Fapp.component.html
