### ISSUE TITLE
render of fullcalendar

### ISSUE THREAD

**Issue by AhemMushtaq** [fullcalendar/fullcalendar#7186]
### Reduced Test Case

https://epobtj.csb.app/

### Do you understand that if a reduced test case is not provided, we will intentionally delay triaging of your ticket?

- [X] I understand

### Which connector are you using (React/Angular/etc)?

React

### Bug Description

![Screenshot (8)](https://user-images.githubusercontent.com/73214372/215955389-1cab5926-57c5-414f-887c-b05b8084c4bc.png)

On reload the fullcalendar looks like above attached image. After toggle to week and toggle back to month it renders correctly.

**Comment by acerix** [comment]
I don't see an issue in your demo and it also does not provide the source code. Please post a [runnable, stripped-down demonstration](http://fullcalendar.io/wiki/Reduced-Test-Cases/) if there is a bug, for example using Stackblitz.

**Comment by johnmanko** [comment]
After a little more troubleshooting, it's related to nesting inside a `p-tabPanel`, which is not rendered initially.  That may be the problem.
