### ISSUE TITLE
"Error: NgClass can only toggle CSS classes expressed as strings, got false" when using dayCellContent()

### ISSUE THREAD

**Issue by stehag** [fullcalendar/fullcalendar#7187]
### Reduced Test Case

https://stackblitz.com/edit/github-bimam2?file=src/app/app.component.ts

### Do you understand that if a reduced test case is not provided, we will intentionally delay triaging of your ticket?

- [X] I understand

### Which connector are you using (React/Angular/etc)?

Angular

### Bug Description

<img width="1075" alt="image" src="https://user-images.githubusercontent.com/4263261/216068515-8468c517-4786-44ce-bc5d-21a72a0e6078.png">

**Comment by arshaw** [comment]
dup of:
https://github.com/fullcalendar/fullcalendar/issues/7182
&uarr;
Could you please visit the link, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates?
