### ISSUE TITLE
When I print the calendar with timeGridWeek, the time slots on the left disappear.

### ISSUE THREAD

**Issue by erickterri** [fullcalendar/fullcalendar#7194]
### Reduced Test Case

https://user-images.githubusercontent.com/11709614/216645162-89f8577c-b89f-4ab9-83df-d15bac68d1af.png

### Do you understand that if a reduced test case is not provided, we will intentionally delay triaging of your ticket?

- [X] I understand

### Which connector are you using (React/Angular/etc)?

Angular

### Bug Description

When I print the calendar with timeGridWeek, the time slots on the left disappear. 
This is the configuration I have:
HTML: 
<full-calendar #calendar id="calendario" [options]="calendarOptions"></full-calendar>

typescript angular:
calendarOptions: CalendarOptions = {
    plugins: [timeGridPlugin,adaptivePlugin],
    initialView: 'timeGridWeek',
    locale: esLocale,
    slotLabelInterval: '00:30',
    slotDuration: '00:30:00',
    slotMinTime: '08:00:00',
    slotMaxTime: '22:30:00',
    allDaySlot: false,
    handleWindowResize: true,
    expandRows: true,
    height: 2500,
    dayHeaderFormat: { weekday: 'short', month: '2-digit', day: '2-digit', omitCommas: true },
    slotLabelFormat: {
      hour: '2-digit',
      minute: '2-digit',
      hour12: true
    },
    eventContent: function (arg) {
      const event = arg.event;
      const inicio = ("0" + event.start?.getHours()).slice(-2) + ':' + ("0" + event.start?.getMinutes()).slice(-2);
      const fin = ("0" + event.end?.getHours()).slice(-2) + ':' + ("0" + event.end?.getMinutes()).slice(-2);
      let customHtml = "<span class='r10 font-xxs font-bold' style='overflow: hidden;'>" + inicio + " - " + fin + "</span>";
      customHtml += "<span class='r10 font-xxs font-bold' style='overflow: hidden;'>" + event.title + "</span>";
      return { html: customHtml }
    }
  };

![image](https://user-images.githubusercontent.com/11709614/216645162-89f8577c-b89f-4ab9-83df-d15bac68d1af.png)

![image](https://user-images.githubusercontent.com/11709614/216644817-1e225600-748b-41b1-b768-ecb14c11f946.png)

**Comment by acerix** [comment]
Would you be able to post a [runnable, stripped-down demonstration of the bug](http://fullcalendar.io/wiki/Reduced-Test-Cases/)? Would really appreciate it because the time saved reproducing will be time spent fixing.
