### ISSUE TITLE
monthStartFormat not working with dayGrid views having a custom duration

### ISSUE THREAD

**Issue by yoancutillas** [fullcalendar/fullcalendar#7197]
### Reduced Test Case

https://codepen.io/yoancutillas/pen/eYjXwEL?editors=001

### Do you understand that if a reduced test case is not provided, we will intentionally delay triaging of your ticket?

- [X] I understand

### Which connector are you using (React/Angular/etc)?

No connector (vanilla JS)

### Bug Description

Hello, thank you for the great features of the 6.1 release!
I just noticed that the monthStartFormat option was not working on dayGrid views having a custom duration.
In the codepen, I have created a 6-month dayGrid view for example, and the the first cell of each month doesn't use the monthStartFormat.

**Comment by arshaw** [comment]
Fixed in https://stackblitz.com/edit/github-cwba2n-fgxuoo?file=src%2FDemoApp.vue

Updated repro:
https://codepen.io/arshaw/pen/rNrgVWL?editors=001
