### ISSUE TITLE
When there are many cross-day schedules in the weekly view, the schedule of the next day will be merged into the current schedule

### ISSUE THREAD

**Issue by wj-mm** [fullcalendar/fullcalendar#7198]
### Reduced Test Case

See the description for details

### Do you understand that if a reduced test case is not provided, we will intentionally delay triaging of your ticket?

- [X] I understand

### Which connector are you using (React/Angular/etc)?

No connector (vanilla JS)

### Bug Description

example1: This situation is correct。✅
<!DOCTYPE html>
<html lang='en'>
  <head>
    <meta charset='utf-8' />
    <script src='https://cdn.jsdelivr.net/npm/fullcalendar-scheduler@6.1.1/index.global.min.js'></script>
    <script>

      document.addEventListener('DOMContentLoaded', function() {
        var calendarEl = document.getElementById('calendar');
        var calendar = new FullCalendar.Calendar(calendarEl, {
          initialDate: '2023-01-07',
          editable: true,
          selectable: true,
          nowIndicator: true,
          aspectRatio: 1.8,
          scrollTime: '00:00',
          initialView: 'resourceTimelineWeek',
          events: [
            { id: '1', resourceId: 'a', start: '2023-01-07T02:00:00', end: '2023-01-07T07:00:00', title: 'event 1' },
            { id: '2', resourceId: 'a', start: '2023-01-07T05:00:00', end: '2023-01-07T22:00:00', title: 'event 2' },
            { id: '3', resourceId: 'a', start: '2023-01-06', end: '2023-01-08', title: 'event 3' },
            { id: '4', resourceId: 'a', start: '2023-01-06', end: '2023-01-09', title: 'event 4' },
            { id: '5', resourceId: 'a', start: '2023-01-06', end: '2023-01-09', title: 'event 5' },
            { id: '6', resourceId: 'a', start: '2023-01-06', end: '2023-01-09', title: 'event 6' },
            { id: '7', resourceId: 'a', start: '2023-01-06', end: '2023-01-06', title: 'event 7' },
          ],
          resources: [
            { id: 'a',  title: 'Auditorium A' },
          ],
          eventMaxStack: 4,
          selectable: false,
          allDaySlot: true,
        });

        calendar.render();
      });

    </script>
  </head>
  <body>
    <div id='calendar'></div>
  </body>
</html>

example2: This situation shows errors❌
<!DOCTYPE html>
<html lang='en'>
  <head>
    <meta charset='utf-8' />
    <script src='https://cdn.jsdelivr.net/npm/fullcalendar-scheduler@6.1.1/index.global.min.js'></script>
    <script>

      document.addEventListener('DOMContentLoaded', function() {
        var calendarEl = document.getElementById('calendar');
        var calendar = new FullCalendar.Calendar(calendarEl, {
          initialDate: '2023-01-07',
          editable: true,
          selectable: true,
          nowIndicator: true,
          aspectRatio: 1.8,
          scrollTime: '00:00',
          initialView: 'resourceTimelineWeek',
          events: [
            { id: '1', resourceId: 'a', start: '2023-01-07T02:00:00', end: '2023-01-07T07:00:00', title: 'event 1' },
            { id: '2', resourceId: 'a', start: '2023-01-07T05:00:00', end: '2023-01-07T22:00:00', title: 'event 2' },
            { id: '3', resourceId: 'a', start: '2023-01-06', end: '2023-01-08', title: 'event 3' },
            { id: '4', resourceId: 'a', start: '2023-01-06', end: '2023-01-09', title: 'event 4' },
            { id: '5', resourceId: 'a', start: '2023-01-06', end: '2023-01-09', title: 'event 5' },
            { id: '6', resourceId: 'a', start: '2023-01-06', end: '2023-01-09', title: 'event 6' },
            { id: '7', resourceId: 'a', start: '2023-01-06', end: '2023-01-09', title: 'event 7' },
          ],
          resources: [
            { id: 'a',  title: 'Auditorium A' },
          ],
          eventMaxStack: 4,
          selectable: false,
          allDaySlot: true,
        });

        calendar.render();
      });

    </script>
  </head>
  <body>
    <div id='calendar'></div>
  </body>
</html>
The schedule of the next day will be merged into the current schedule.

**Comment by acerix** [comment]
Would you be able to post a [runnable, stripped-down demonstration of the bug](http://fullcalendar.io/wiki/Reduced-Test-Cases/)? Would really appreciate it because the time saved reproducing will be time spent fixing.
