### ISSUE TITLE
DayCellContent hooks not working with Fullcalendar v6 

### ISSUE THREAD

**Issue by badblli** [fullcalendar/fullcalendar#7199]
### Reduced Test Case

https://stackblitz.com/edit/github-cwba2n?file=src/DemoApp.vue

### Do you understand that if a reduced test case is not provided, we will intentionally delay triaging of your ticket?

- [X] I understand

### Which connector are you using (React/Angular/etc)?

Vue

### Bug Description

After a lot of trial and error I couldn't find the answer to my problem anywhere and when I tried downgrading the version to v5 the dayCellContent Hook worked successfully. I think this is a bug that occurred in v6.

note: I'm using FullCalendar v6.1 with vue3.

This bug has been detected only in vue3 and its status is unknown in other frameworks.

**Comment by arshaw** [comment]
Queued for release:
https://github.com/fullcalendar/fullcalendar/issues/7188
&uarr;
Could you please visit the link, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates?
