### ISSUE TITLE
Timezone changes not working for calendar.setOption('timeZone') on FullCalendar 6 (latest)

### ISSUE THREAD

**Issue by jaredgibb** [fullcalendar/fullcalendar#7200]
### Reduced Test Case

https://codepen.io/jaredgibb/pen/PoBgxww?editors=1010

### Do you understand that if a reduced test case is not provided, we will intentionally delay triaging of your ticket?

- [X] I understand

### Which connector are you using (React/Angular/etc)?

No connector (vanilla JS)

### Bug Description

Setting timezones is not changing the display of events on the calendar. 

### Video of Issue
https://www.loom.com/share/71e23b4b46f04d62946f51ce0b6f3852

**Comment by acerix** [comment]
The timeZone setting does not convert the times in the event data, that conversion needs to be done on the server side based on the timezone param. There's a demo here:

https://fullcalendar.io/docs/v5/timeZone-demo
