### ISSUE TITLE
Events not being coerced to appropriate timezone

### ISSUE THREAD

**Issue by jaredgibb** [fullcalendar/fullcalendar#7202]
### Reduced Test Case

https://codepen.io/jaredgibb/pen/PoBgxww?editors=1011

### Do you understand that if a reduced test case is not provided, we will intentionally delay triaging of your ticket?

- [X] I understand

### Which connector are you using (React/Angular/etc)?

No connector (vanilla JS)

### Bug Description

I have an event with the start time of 5AM Zulu. In America/Detroit, this should be midnight but on the calendar is being displayed as 5AM. 

when i change the timezone to either local or America/Los_Angeles (3 hours behind Detroit) the event doesnt appear to change on the calendar. when i change the timezone to UTC, the event displays as it should in my local time (detroit) at midnight. 

https://vimeo.com/796849601/b2b25a1120

**Comment by acerix** [comment]
The `timeZone` setting does not convert the times in the event data, that conversion needs to be done on the server side based on the timezone param.  There's a demo here:

https://fullcalendar.io/docs/v5/timeZone-demo

**Comment by jaredgibb** [comment]
it doesnt change the times no, but when the different timezone is applied the events should appear differently on the calendar, shouldnt they?

**Comment by acerix** [comment]
No, it's up to the server to update to the correct times based on the `timezone` param, so your demo won't update since the times are hard-coded.

**Comment by jaredgibb** [comment]
it's not clear in your example how changing the timezone is conveyed to any server. events aren't refetched. yet, the events shift as the timezone is changed. Any chance you can provide more detail here?
