### ISSUE TITLE
Resource Timeline View crashes when resourceGroupLaneContent content injector is set

### ISSUE THREAD

**Issue by lukas-siarny** [fullcalendar/fullcalendar#7203]
### Reduced Test Case

https://stackblitz.com/edit/github-6b7aj5-iuuen3?file=src%2FDemoApp.jsx

### Do you understand that if a reduced test case is not provided, we will intentionally delay triaging of your ticket?

- [X] I understand

### Which connector are you using (React/Angular/etc)?

React

### Bug Description

We've recently upgraded from FC 5 to FC `6.1.0` and everything was working fine. However after update from FC `6.1.0` to `6.1.4` our resource timeline view crashes. We've located that the issues is caused by setting `resourceGroupLaneContent.` It works fine without it. 

![console](https://user-images.githubusercontent.com/58573357/217819079-6a4253fb-9933-493b-9baa-dc743e99dac0.JPG)

**Comment by arshaw** [comment]
Fixed in [v6.1.5](https://github.com/fullcalendar/fullcalendar/releases/tag/v6.1.5)

Updated repro: https://stackblitz.com/edit/github-6b7aj5-ty47ne?file=package.json

**Comment by lukas-siarny** [comment]
Thanks, works fine.
