### ISSUE TITLE
Copy Event by pressing CONTROL key and Drag And Drop 

### ISSUE THREAD

**Issue by patrik-upspot** [fullcalendar/fullcalendar#7205]
### Reduced Test Case

https://codesandbox.io/s/fullcalendar-copy-control-f4ciqx?file=/src/app/app.component.ts

### Do you understand that if a reduced test case is not provided, we will intentionally delay triaging of your ticket?

- [X] I understand

### Which connector are you using (React/Angular/etc)?

Angular

### Bug Description

I'm trying to copy an event by hold control key and drag and drop the event. I found a working example with jQuery and an old Version of FullCalendar

[Demo](https://codepen.io/ally-murray/pen/JBdaBV)

I have tryed to port this version to Angular, but its still not working. If i press and hold control, its possible to "copy" the event, but i connot drop it. After i tryed to copy an event, its mostly not possible to move a event if i released the control key. 

Is it possible to copy an appointment by dragging/dropping the control key to the new date? I look forward to hearing from you! 

[Actual Angular Demo](https://codesandbox.io/s/fullcalendar-copy-control-f4ciqx?file=/src/app/app.component.ts)

**Comment by acerix** [comment]
I believe this existing ticket captures this need:
https://github.com/fullcalendar/fullcalendar/issues/857
↑
Please visit the above issue, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates.
