### ISSUE TITLE
Set custom button text as JSX

### ISSUE THREAD

**Issue by Azaryan-A** [fullcalendar/fullcalendar#7206]
### Reduced Test Case

https://stackblitz.com/edit/github-urj6el-ym4vba?file=src%2FDemoApp.jsx

### Do you understand that if a reduced test case is not provided, we will intentionally delay triaging of your ticket?

- [X] I understand

### Which connector are you using (React/Angular/etc)?

React

### Bug Description

After updating the calendar version from 5 to 6 I cannot set custom button text as JSX

**Comment by acerix** [comment]
I believe this existing ticket captures this need:
https://github.com/fullcalendar/fullcalendar/issues/7120
↑
Please visit the above issue, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates.
