### ISSUE TITLE
`Nuxt v2.16.x` Cannot read properties of undefined (reading 'isHiddenDay') / dateProfileGenerator is undefined

### ISSUE THREAD

**Issue by GelsDEV** [fullcalendar/fullcalendar#7217]
### Reduced Test Case

https://stackblitz.com/edit/github-1xfuuw

### Do you understand that if a reduced test case is not provided, we will intentionally delay triaging of your ticket?

- [X] I understand

### Which connector are you using (React/Angular/etc)?

Vue

### Bug Description

Fullcalendar no longer seems to work with Nuxt from version `Nuxt v2.16.0`.
With `Nuxt v2.15.8` and lower everything works fine.

I have created a test case based on the Fullcalendar Nuxt template: [Stackblitz](https://stackblitz.com/edit/github-1xfuuw)

The following error message appears in the Chrome console:
```
Cannot read properties of undefined (reading 'isHiddenDay')
    at new DaySeriesModel (internal-common.cjs?4616:6164:1)
    at DayTimeColsView.buildTimeColsModel (internal.js?e201:1138:1)
    at DayTimeColsView.eval [as buildTimeColsModel] (internal-common.cjs?4616:861:1)
    at DayTimeColsView.render (internal.js?e201:1123:1)
    at M (preact.module.js?da65:1:1)
    at H (preact.module.js?da65:1:1)
    at O (preact.module.js?da65:1:1)
    at M (preact.module.js?da65:1:1)
    at H (preact.module.js?da65:1:1)
    at M (preact.module.js?da65:1:1)
```

The following error message appears in the Firefox console:
```
TypeError: dateProfileGenerator is undefined
    DaySeriesModel internal-common.cjs:6164
    buildTimeColsModel internal.js:1138
    memoize internal-common.cjs:861
    render internal.js:1123
    Preact 17
    handleRenderRequest index.js:2015
    flushSync internal-common.js:2200
    handleRenderRequest index.js:2014
    drained internal-common.js:129
    tryDrain internal-common.js:111
    request internal-common.js:74
    render index.js:2048
    mounted FullCalendar.ts:79
    VueJS 11
    NuxtJS 4
    Babel 18
    NuxtJS 2
    Babel 12
    NuxtJS 11
client.js:102
```

**Comment by arshaw** [comment]
Fixed in [v6.1.5](https://github.com/fullcalendar/fullcalendar/releases/tag/v6.1.5)

Updated repro: https://stackblitz.com/edit/github-1xfuuw-umlhgq?file=package.json
