### ISSUE TITLE
Provide finer-grained control of `lazyFetching` duration

### ISSUE THREAD

**Issue by ivyraine** [fullcalendar/fullcalendar#7219]
### Checklist

- [X] I've already searched through [existing tickets](https://github.com/fullcalendar/fullcalendar/issues)
- [X] Other people will find this feature useful

### Is this feature for a specific connector (React/Angular/etc)?

No connector in particular

### Feature Description

I'd like to cache event data using `lazyFetching`, but it appears that the duration of the cache is tied to the `initialView`, according to the [docs](https://fullcalendar.io/docs/lazyFetching). In my use case, my calendar needs to start in a Month view, but cache for a day. 

This feature does not exist, right? Also, is there a workaround I could use?

**Comment by acerix** [comment]
If the calendar starts in month view and then is changed to day view, the event will not be fetched again with `lazyFetching`.  Here's an example:

https://codepen.io/acerix/pen/KKxmjvB?editors=001

I'm not sure if you mean something else by "cache for a day",  but you could cache event data a the "function" to supply events:

https://fullcalendar.io/docs/events-function
