### ISSUE TITLE
Option to load calendar CSS from an external file instead of injection

### ISSUE THREAD

**Issue by artknight** [fullcalendar/fullcalendar#7220]
### Checklist

- [X] I've already searched through [existing tickets](https://github.com/fullcalendar/fullcalendar/issues)
- [X] Other people will find this feature useful

### Is this feature for a specific connector (React/Angular/etc)?

No connector in particular

### Feature Description

Hi,
I am seeing that the CSS is getting injected upon calendar initialization. I am wondering if there is a way to have an external CSS file that I could use instead?

- better caching
- **main reason** --> I need to override some of the styles and would prefer NOT to use `!important`. With an external CSS file I can just load my overrides afterwards.

Thank you!
Art

**Comment by artnikbrothers** [comment]
I have the same issue with React and Fullcalendar 6 version. Version 5 worked fine. Here is an example of how the styles are injected to the `head` instead of bundled css file 

![image](https://user-images.githubusercontent.com/9512270/220748960-46011f5c-f5a2-45bb-be0d-df70d2d6322a.png)

**Comment by lukas-siarny** [comment]
We have the same problem, so we downgraded to V5 until we find a solution for this

**Comment by acerix** [comment]
I can see how that could be useful.

As a workaround, you could load (inject) your CSS after the calendar is loaded.  For example, this shows the CSS not working initially, but after making some edit in the CSS, codepen will live reload the CSS and it then gets applied.

https://codepen.io/acerix/pen/BaOpaQq?editors=0110

**Comment by artknight** [comment]
@acerix Thank you for the work-around. Unfortunately that does not work for us. I would still prefer an option to load the CSS file outside of JS.

**Comment by malte94** [comment]
@artnikbrothers Thank you for referencing my previous ticket, which was closed unfortunately.

+1 on this ticket now to bring back the functionality from v5 to properly load external stylesheets.

**Comment by malte94** [comment]
I could find a workaround. However, this will not work with CSS preprocessors.

1. Place a "Calendar.css" in your /public folder.
2. Use the following code on your Calendar's component:

```
React.useEffect(() => {
    const link = document.createElement('link');
    link.href = process.env.PUBLIC_URL + '/Calendar.css';
    link.rel = 'stylesheet';
    document.body.appendChild(link);

    return () => {
        document.body.removeChild(link);
    };
}, []);
```

**Comment by artnikbrothers** [comment]
Since I didn't want to spend time on finding the best solution and at the same time didn't want to use `!important` for every style, I've just added a parent class to my css selectors to overwrite the default one like so:

```scss
.my-cool-calendar {
  // calendar classes which I want to overwrite
 .fc {
    ....
  }
}
```

**Comment by arshaw** [comment]
Version [v6.1.5](https://github.com/fullcalendar/fullcalendar/releases/tag/v6.1.5) now ensures FullCalendar's styles load higher-up in the `<head>` thus allowing your custom styles to take higher precedence.

![Screen Shot 2023-03-21 at 5 34 20 PM](https://user-images.githubusercontent.com/56520/226746306-8e91361b-aebc-4e0a-b772-94986728e886.png)
https://fullcalendar.io/docs/month-view-demo

Is this sufficient for people?

I know people were hoping FullCalendar stops injecting its own styles and instead provides a stylesheet to include, however, this comes with a lot of complexity for the developer, namely that each plugin provides its own styles, some plugins are inter-dependent, and thus the developer would need to understand the dependency graph and import styles in an exact order. This is what we had [in v4](https://fullcalendar.io/docs/v4/initialize-es6) and people were constantly screwing it up.

**Comment by malte94** [comment]
@arshaw Thank you for handling this topic so quickly! Unfortunately, in my case using the build of React.js it is still not working. The dev environment works fine, as soon as the build is deployed, the imported stylesheet in the Calendar.jsx is still overwritten by the FullCalendar's default.

`import '../css/Calendar.sass';`

I could also identify the issue. The inline styles are still placed after the main.css:

![image](https://user-images.githubusercontent.com/89409894/228902166-e797ced0-37fa-46fd-860a-138654481041.png)

As soon as the main.css is placed beneath, like illustrated, it's working fine.

**Comment by trollbot38** [comment]
> Version [v6.1.5](https://github.com/fullcalendar/fullcalendar/releases/tag/v6.1.5) now ensures FullCalendar's styles load higher-up in the `<head>` thus allowing your custom styles to take higher precedence.
> 
> ![Screen Shot 2023-03-21 at 5 34 20 PM](https://user-images.githubusercontent.com/56520/226746306-8e91361b-aebc-4e0a-b772-94986728e886.png) https://fullcalendar.io/docs/month-view-demo
> 
> Is this sufficient for people?
> 
> I know people were hoping FullCalendar stops injecting its own styles and instead provides a stylesheet to include, however, this comes with a lot of complexity for the developer, namely that each plugin provides its own styles, some plugins are inter-dependent, and thus the developer would need to understand the dependency graph and import styles in an exact order. This is what we had [in v4](https://fullcalendar.io/docs/v4/initialize-es6#css) and people were constantly screwing it up.

This doesn't work in nextjs production out of the box. I think ti's having trouble inject those style tags in production, but does work in localhost. Any pointers?

**Comment by nandorojo** [comment]
To echo what @trollbot38 said – since upgrading to v6 from v5, I've noticed that after a client-side route with Next.js, the styles don't get injected properly. Refreshing the page works, but navigating from a different client-side route breaks it. Does this seem like something reasonable that could happen? Thanks!

**Comment by arshaw** [comment]
@trollbot38 and @nandorojo , please see this ticket:
https://github.com/fullcalendar/fullcalendar/issues/7284
&uarr;
Could you please visit the link, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates?

**Comment by hughbris** [comment]
_\[Issue is now closed but in Todo(?) I'm guessing comments here are still considered.]_

> I know people were hoping FullCalendar stops injecting its own styles and instead provides a stylesheet to include, however, this comes with a lot of complexity for the developer, namely that each plugin provides its own styles, some plugins are inter-dependent, and thus the developer would need to understand the dependency graph and import styles in an exact order. This is what we had [in v4](https://fullcalendar.io/docs/v4/initialize-es6#css) and people were constantly screwing it up.

I feel your pain, but isn't this issue about providing standard CSS _as an option_? I assume this means a toggle setting of some sort. The KISS option could come with "here be dragons" warnings and we'll have to figure out the correct CSS inclusion order to make it all work. With no guarantees either. Is that reasonable?

Not sure if most library consumers are using framework modules or simply pulling from the CDN. As more of a back end developer not using frameworks or wanting to get into JS builds, I prefer this option as it's more intuitive and standard. (Also I'm grateful for it!) I suppose in your effort/reward equation, you'll want to consider how common my type of library user is.

**Comment by sahilsheikh18** [comment]
Great

**Comment by pietrofxq** [comment]
I just hit a severe problem with the automatic injection: I am using FullCalendar in a chrome extension and any website that has a `fc` class in their HTML (happened to one of our clients) can break. Is there a way to customize the selector or avoid injecting the CSS completely?
