### ISSUE TITLE
Drag and Drop from more-popover to all-day is not working

### ISSUE THREAD

**Issue by JonathanZeiss** [fullcalendar/fullcalendar#7222]
### Reduced Test Case

https://stackblitz.com/github/JonathanZeiss/fullcalendar-examples/tree/main/react17

### Do you understand that if a reduced test case is not provided, we will intentionally delay triaging of your ticket?

- [X] I understand

### Which connector are you using (React/Angular/etc)?

React

### Bug Description

Dragging an event from the more popover to the all day slot is not possible.
The event is placed in the time grid instead.

Repository of the example:
https://github.com/JonathanZeiss/fullcalendar-examples

Drag and Drop is working from a time slot to the all day slot:

https://user-images.githubusercontent.com/72806275/220149541-f0329d73-b531-4eb3-82eb-eb6773a2ce68.mov

Drag and drop is not working from the more popover to the all day slot:

https://user-images.githubusercontent.com/72806275/220150280-f7e0e5d7-87d2-4631-b082-842e25d885e0.mov

**Comment by acerix** [comment]
Thanks confirmed.  I tested with vanilla and get the same:

https://codepen.io/acerix/pen/jOvmjzv?editors=001

**Comment by arshaw** [comment]
Fixed in [v6.1.5](https://github.com/fullcalendar/fullcalendar/releases/tag/v6.1.5)

Updated repro: https://codepen.io/arshaw/pen/PodyQoB?editors=001
