### ISSUE TITLE
jalali calendar events 

### ISSUE THREAD

**Issue by mahdiasli** [fullcalendar/fullcalendar#7231]
### Checklist

- [X] I've already searched through [existing tickets](https://github.com/fullcalendar/fullcalendar/issues)
- [X] Other people will find this feature useful

### Is this feature for a specific connector (React/Angular/etc)?

No connector in particular

### Feature Description

hello I use Fullcalendar its useful but I have problem.
I want to add some event to my calendar
I set locale to 'fa'
when i add some event like this example
      events:[{
        title: 'Angular',
        start: '14011214',
        backgroundColor: 'green',
        borderColor: 'green'
      }],
 it dosent work becuse of start date.
 when i Use  some thing like this 20230305 format its work well
 any idea about using  jalali format for event?

**Comment by acerix** [comment]
I believe this existing ticket captures this need:
https://github.com/fullcalendar/fullcalendar/issues/1813
↑
Please visit the above issue, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates.
