### ISSUE TITLE
Dynamic data source causes monthly view display error

### ISSUE THREAD

**Issue by jianhao2010303** [fullcalendar/fullcalendar#7232]
### Reduced Test Case

none

### Do you understand that if a reduced test case is not provided, we will intentionally delay triaging of your ticket?

- [X] I understand

### Which connector are you using (React/Angular/etc)?

React

### Bug Description

Step 1：
const [events, setEvents] = useState<any[]>([])

Setp 2:
Switch the month to November 2022， call back function : setEvent([])  some daily cycle data.

Setp3:

You will find that the monthly view data will flash and disappear, but when you switch to the list view, it will be displayed again.

This is to switch to the monthly view and display the data.

**Comment by jianhao2010303** [comment]
![ca85b715-bb35-4e48-9051-32327da87d98](https://user-images.githubusercontent.com/22093101/222998427-792e2a4d-725d-493e-a911-c00b84c6bfe9.jpg)
![6cda10bf-f666-46cb-a61b-74342c51d06c](https://user-images.githubusercontent.com/22093101/222998443-8e1e9a75-47d7-40ee-b221-c89e51634660.jpg)

**Comment by scriptify** [comment]
+1
Similar stuff happens with timeGridWeek.
The problem seems to be caused by changing the reference of the `events` array. Try setting a static array and see if the error persists.
I wasn't able to find a solution yet.

**Comment by scriptify** [comment]
May be related to: https://github.com/fullcalendar/fullcalendar/issues/7235

**Comment by acerix** [comment]
Yes, I believe this existing ticket captures this need:
https://github.com/fullcalendar/fullcalendar/issues/7230
↑
Please visit the above issue, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates.
