### ISSUE TITLE
Date format in header of dayGridMonth view mode gives wrong month - Always Jan or 01

### ISSUE THREAD

**Issue by shridhar-tl** [fullcalendar/fullcalendar#7240]
### Reduced Test Case

Will update later if I could

### Do you understand that if a reduced test case is not provided, we will intentionally delay triaging of your ticket?

- [X] I understand

### Which connector are you using (React/Angular/etc)?

React

### Bug Description

When we use view mode as dayGridMonth and dayHeaderFormat value is configured something like 'ddd, DD/MMM' or 'ddd, DD/MM' the month part is always representing January like Jan or 01. Current month is March and still the header shows January.

Here is a screenshot for your reference:
![image](https://user-images.githubusercontent.com/37339683/224223631-74b36693-d312-44df-b844-19c5677a5830.png)

When I configured dayHeaderFormat value to include year like 'yyyy, ddd, DD/MMM', year is shown as 1970. So it seems its using min date object instead of using current date object.

Here is the screenshot:
![image](https://user-images.githubusercontent.com/37339683/224224442-4196f754-2927-4b27-be05-a050df997aa8.png)

Additionally second bug is when we navigate to previous month or next month also, this does not change the header, looks like re-rendering is not happening for headers.

This is not just with latest version, its happening with v5.x as well. Not sure how I have never noticed it so far.

**Comment by acerix** [comment]
I believe this existing ticket captures this need:
https://github.com/fullcalendar/fullcalendar/issues/5854
↑
Please visit the above issue, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates.
