### ISSUE TITLE
Show weeks in a separate column in fullcalendar

### ISSUE THREAD

**Issue by TaRaNTuLaH** [fullcalendar/fullcalendar#7244]
### Checklist

- [X] I've already searched through [existing tickets](https://github.com/fullcalendar/fullcalendar/issues)
- [X] Other people will find this feature useful

### Is this feature for a specific connector (React/Angular/etc)?

No connector in particular

### Feature Description

This feature request refers to this issue: https://github.com/fullcalendar/fullcalendar/issues/5801

It was possible in versions pre v5.
Right now the only solution (which is gnarly btw.) that I was able to find is through playing with html and css, but due to other css styles (like harness) it's breaking other stylings.
Injecting content using Week-Number Render Hooks is not a valid solution as the aria responsible for showing the date is WITHIN the cell.
Maybe in general there should be possibility to render - pre row (which would help a lot in this case)

**Comment by acerix** [comment]
I believe this existing ticket captures this need:
https://github.com/fullcalendar/fullcalendar/issues/4210
↑
Please visit the above issue, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates.
