### ISSUE TITLE
Dynamic column width that depends on event width

### ISSUE THREAD

**Issue by Patrick1900** [fullcalendar/fullcalendar#7246]
### Checklist

- [X] I've already searched through [existing tickets](https://github.com/fullcalendar/fullcalendar/issues)
- [X] Other people will find this feature useful

### Is this feature for a specific connector (React/Angular/etc)?

No connector in particular

### Feature Description

Is it possible that each column (e.g. resource view) has a different width depends on the count of parallel events

the event width e.g. is 50px

one event resource A 
three events resource B at the same time

resource column A = 50px
resource column B = 150px

<img width="680" alt="Bildschirmfoto 2023-03-17 um 18 20 13" src="https://user-images.githubusercontent.com/13556683/225974838-2628344e-e4a7-4c4e-bdfe-352219ea355b.png">

**Comment by acerix** [comment]
I believe this existing ticket captures this need:
https://github.com/fullcalendar/fullcalendar/issues/6174
↑
Please visit the above issue, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates.
