### ISSUE TITLE
Calendar table is made of multiple nested tables

### ISSUE THREAD

**Issue by stevengore** [fullcalendar/fullcalendar#7249]
### Checklist

- [X] I've already searched through [existing tickets](https://github.com/fullcalendar/fullcalendar/issues)
- [X] Other people will find this feature useful

### Is this feature for a specific connector (React/Angular/etc)?

No connector in particular

### Feature Description

Please make the following changes to help improve accessibility when using a screen reader like NVDA.

When data can be presented in layout form and truly does not require use of a data table, use other block and inline elements such as div, span, dd, or dt to layout data. If data truly requires use of a data table, consider splitting the data into tables or placing all the data in one data table with sub-headers. If this is not possible, provide instruction text in the table caption or on-screen describing the structure of the table.

**Comment by acerix** [comment]
I believe this existing ticket captures this need:
https://github.com/fullcalendar/fullcalendar/issues/6641
↑
Please visit the above issue, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates.
