### ISSUE TITLE
Drag and Drop issue

### ISSUE THREAD

**Issue by jomskie0123** [fullcalendar/fullcalendar#7251]
### Reduced Test Case

none

### Do you understand that if a reduced test case is not provided, we will intentionally delay triaging of your ticket?

- [X] I understand

### Which connector are you using (React/Angular/etc)?

Vue

### Bug Description

There is an issue when dragging an event on the calendar when there is a calendar behind a pop up with calendar. When dragging the items on the popup it will move behind and not on the visible calendar.

**Comment by acerix** [comment]
I believe this existing ticket captures this need:
https://github.com/fullcalendar/fullcalendar/issues/5026
↑
Please visit the above issue, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates.
