### ISSUE TITLE
Event.setEnd ignores times 

### ISSUE THREAD

**Issue by TitaniumSmiles** [fullcalendar/fullcalendar#7253]
### Reduced Test Case

https://codesandbox.io/s/thirsty-tom-lppgnz?file=/src/index.js

### Do you understand that if a reduced test case is not provided, we will intentionally delay triaging of your ticket?

- [X] I understand

### Which connector are you using (React/Angular/etc)?

No connector (vanilla JS)

### Bug Description

When using the setEnd function on an event, it changes the date but not the actual time. 

Try resizing the event and check the console on the reduced test case, and you will see that the time is reverted back to midnight.

related: #4749

FullCalendar Schedular CDN Version: 5.11.4 (Latest V5)

**Comment by acerix** [comment]
The issue is that your time slots are 1 day long, so events will always snap to that size.  Using hour long time slots allows to set any hour of the day:

https://codesandbox.io/s/fullcalendar-setend-reproduction-forked-iz0ii7?file=/src/index.js
