### ISSUE TITLE
Toolbar buttons text duplicated

### ISSUE THREAD

**Issue by AleCigolini** [fullcalendar/fullcalendar#7254]
### Reduced Test Case

https://drive.google.com/file/d/1LenijVf-esrFecxLVtqO_R1f8glk9M3i/view?usp=sharing

### Do you understand that if a reduced test case is not provided, we will intentionally delay triaging of your ticket?

- [X] I understand

### Which connector are you using (React/Angular/etc)?

Angular

### Bug Description

I'am testing the new version of full calendar, and the buttons text in the calendar toolbar are duplicating when we click them. I haven't found a solution yet. I tested the demos in full calendar official website and the problem occurs as well.

Sorry If I'm opening a wrong bug report, this is the first time I wrote here.

![Screenshot_51](https://user-images.githubusercontent.com/83404657/227064986-5841ad1d-9107-4f6e-ab35-5b5226a4e69c.png)

**Comment by acerix** [comment]
Would you be able to post a [runnable, stripped-down demonstration of the bug](http://fullcalendar.io/wiki/Reduced-Test-Cases/)? Would really appreciate it because the time saved reproducing will be time spent fixing.

**Comment by andrejm7** [comment]
funny. on my machine it's normal... but on others... I have the same behavior.

**Comment by AleCigolini** [comment]
Yep! I haven't could resolve this problem yet.
