### ISSUE TITLE
 Continuous selection between months in the "multiMonthYear" view

### ISSUE THREAD

**Issue by mjesteve** [fullcalendar/fullcalendar#7257]
### Checklist

- [X] I've already searched through [existing tickets](https://github.com/fullcalendar/fullcalendar/issues)
- [X] Other people will find this feature useful

### Is this feature for a specific connector (React/Angular/etc)?

Other

### Feature Description

In the "multiMonthYear" view I have not been able to select days, between different months, in a continuous way:

![GIF 24-03-2023 9-05-43](https://user-images.githubusercontent.com/55754195/227461219-921e4ded-2079-4ed2-ae16-2a9fd0c1f6af.gif)

Desirable behaviour would be:

![GIF 24-03-2023 9-12-14](https://user-images.githubusercontent.com/55754195/227462419-18972eef-3010-441c-88a0-8bf6fb07038f.gif)

I got this last gif from the extension [https://github.com/tpruvot/fullcalendar](url).
I tried to see what changes should be made but I couldn't find out because this extension is based on FullCalendar v2.2.7 and there are too many differences with the current version (I'm a javascript novice).

Is there any way to do this in the current version?

Thank you.
Good work, great component.

**Comment by acerix** [comment]
I believe this existing ticket captures this need:
https://github.com/fullcalendar/fullcalendar/issues/7183
↑
Please visit the above issue, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates.

**Comment by mjesteve** [comment]
I didn't see it, sorry.
Thank you, I've already launched.

**Comment by Vishal-beep136** [comment]
@mjesteve  Were you able to get it working?

**Comment by mjesteve** [comment]
Hi @Vishal-beep136 
No, in the end I created an annual view, based on the 4.3.0 version

![GIF 28-11-2024 16-08-08](https://github.com/user-attachments/assets/59652100-2021-41c2-a98e-44d8227cef1d)

If you're interested you can find it here https://github.com/mjesteve/fullcalendar/tree/v4.3.1/packages/yearview
I don't know much javascript, so I'm sure it can be improved a lot, but it's worked for me so far.

**Comment by Vishal-beep136** [comment]
@mjesteve  thanks for the response! but I'm using something different workaround like user have to select `start date` and `end date`
