### ISSUE TITLE
Fullcalendar style not working on React Remix 1.14.0

### ISSUE THREAD

**Issue by iChwn** [fullcalendar/fullcalendar#7261]
### Which connector are you using (React/Angular/etc)?

React

### Bug Description

I have an issue when trying to use Fullcalendar on my Remix project, the styles are not loaded in remix js, any suggestion to fix this issue?
![image](https://user-images.githubusercontent.com/29217999/227827066-75f5eb49-236e-496b-94b8-29e691f98c3c.png)

Here is my simple implementation with the plugin
```
<FullCalendar
  plugins={[ dayGridPlugin ]}
  initialView="dayGridMonth"
  events={[
    { title: 'event 1', date: '2023-03-01' },
    { title: 'event 2', date: '2023-03-02' }
  ]}
  viewClassNames="h-full"
/>
```

**Comment by imshubhamsingh** [comment]
@iChwn I recently faced the same issue. I solved by adding fullcalender CSS via CDN on the page where I'm using the calendar.

```tsx
export const links: LinksFunction = () => {
  return [
    {
      rel: "stylesheet",
      href: "https://cdn.jsdelivr.net/npm/fullcalendar@5.11.3/main.min.css",
    },
  ];
};
```

**Comment by arshaw** [comment]
In [v6.1.6](https://github.com/fullcalendar/fullcalendar/releases/tag/v6.1.6) I changed the way the `rrule` package is imported. Could you all please confirm things are working now?

**Comment by arshaw** [comment]
Sorry, I commented on the wrong issue

**Comment by iChwn** [comment]
> @iChwn I recently faced the same issue. I solved it by adding fullcalendar CSS via CDN on the page where I'm using the calendar.
> 
> ```tsx
> export const links: LinksFunction = () => {
>   return [
>     {
>       rel: "stylesheet",
>       href: "https://cdn.jsdelivr.net/npm/fullcalendar@5.11.3/main.min.css",
>     },
>   ];
> };
> ```
> 
> Currently side-effect import import in Remix is not that great. This is being worked upon. Details: https://remix.run/docs/en/1.15.0/guides/styling#css-side-effect-imports
> 
> I would also suggest to wrap the Calendar component in a [ClientOnly](https://remix.run/docs/en/1.15.0/guides/migrating-react-router-app#client-only-components) component so that it is only rendered after hydration, otherwise you will see the flicker of calendar from non-styled one that you shared to styled one.

This actually works for me, thank you for the suggestion

**Comment by arshaw** [comment]
I'll reopen this issue for coming up with a proper fix.

**Comment by arshaw** [comment]
I've created an official workaround for this:
- https://fullcalendar.io/docs/react#remix
- https://github.com/fullcalendar/fullcalendar-examples/tree/main/remix

**Comment by iChwn** [comment]
> I've created an official workaround for this:
> 
> * https://fullcalendar.io/docs/react#remix
> * https://github.com/fullcalendar/fullcalendar-examples/tree/main/remix

Thank You!

**Comment by RoniqueRicketts** [comment]
The recommendation on FullCalendar is to add ```<style data-fullcalendar />``` in the <head> tag in your root.tsx file. The information is found on https://fullcalendar.io/docs/react

Ps. I am adding this here for future users.

**Comment by jordisantamaria** [comment]
Hi, the fix of `<style data-fullcalendar />` works on localhost, but is not working for us in production.
