### ISSUE TITLE
Can we add css class/apply custom styles to timeGridWeek's "time Cell"

### ISSUE THREAD

**Issue by nik32** [fullcalendar/fullcalendar#7262]
### Checklist

- [X] I've already searched through [existing tickets](https://github.com/fullcalendar/fullcalendar/issues)
- [X] Other people will find this feature useful

### Is this feature for a specific connector (React/Angular/etc)?

No connector in particular

### Feature Description

<img width="1406" alt="image" src="https://user-images.githubusercontent.com/51018572/227947019-e7239755-4d7e-4a81-b807-3eea7e0a3f88.png">
Basically... we are allowing is for user to create a event when he click's on timeGridWeek's time cell [marked with red in image above]. Now I want to show some hover effect to let him know this.
I am able to target a particular slot in dayGridMonth (as shown in below img... I was able to apply hover effect) but can't be able to do so in timeGridWeek's due to the way timeGridWeek's HTML is structured. Is there some way to achieve the below for timeGridWeek's??

<img width="1401" alt="image" src="https://user-images.githubusercontent.com/51018572/227947403-6b3de9cb-0c4c-49a0-88a0-47b8a9c2c1ef.png">

**Comment by acerix** [comment]
I believe this existing ticket captures this need:
https://github.com/fullcalendar/fullcalendar/issues/4816
↑
Please visit the above issue, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates.
