### ISSUE TITLE
Embedding the calendar using scriptcase, through a plugin, in wordpress the name of the month does not appear

### ISSUE THREAD

**Issue by herbertosilva** [fullcalendar/fullcalendar#7265]
### Reduced Test Case

https://municipioribeirabrava.org/wpgem/Reservas/

### Do you understand that if a reduced test case is not provided, we will intentionally delay triaging of your ticket?

- [X] I understand

### Which connector are you using (React/Angular/etc)?

No connector (vanilla JS)

### Bug Description

When embedding the calendar using scriptcase, through a plugin, in wordpress the name of the month does not appear. I have already tested several plugins for embedding (for example -Embed Plus YouTube WordPress Plugin) curiously on the PC it does not appear in any browser but using a smartphone the name of the month appears

**Comment by acerix** [comment]
Would you be able to post a [runnable, stripped-down demonstration of the bug](http://fullcalendar.io/wiki/Reduced-Test-Cases/)? Would really appreciate it because the time saved reproducing will be time spent fixing.
