### ISSUE TITLE
Different rendering when deploynig with Nextjs 13

### ISSUE THREAD

**Issue by VinniC77** [fullcalendar/fullcalendar#7266]
### Reduced Test Case

https://github.com/VinniC77/Fullcalendar-error

### Do you understand that if a reduced test case is not provided, we will intentionally delay triaging of your ticket?

- [X] I understand

### Which connector are you using (React/Angular/etc)?

React

### Bug Description

When uploading the FullCalendar component to the AWS hosting service, using Nextjs 13, the lib loses all its style and event features. Locally it works normally, but when deploying, the styling is all lost. It only renders a basic calendar.

**Comment by andrewcoelho** [comment]
This _may_ have been introduced in one of https://github.com/fullcalendar/fullcalendar/commit/550360660e37de1586596754c3ec483443529df7 or https://github.com/fullcalendar/fullcalendar/commit/d87c62e0739e582b629558a7acbfab69abb72b91, although I've not been able to confirm.

There is also behavior in next.js that is related https://github.com/vercel/next.js/issues/11012

I got it working with this hopefully temporary workaround to move the style tags injected by FC below the next.js head count meta tag:

```
// Calendar.tsx

import * as React from 'react';
import FullCalendar from '@fullcalendar/react';

export const Calendar = (props: any) => {
  React.useEffect(() => {
    const startCommentText = ' fullcalendar styles ';
    const endCommentText = ` END${startCommentText}`;
    const headEl = document.getElementsByTagName('head')[0];
    const headCountEl: HTMLMetaElement = headEl.querySelector(
      'meta[name=next-head-count]'
    ) as HTMLMetaElement;

    if (headCountEl) {
      const fcStyleEls: Array<HTMLStyleElement> = [];
      let currentNode = headCountEl.previousSibling;
      let foundEndMarker = false;

      while (currentNode !== null) {
        if (currentNode.textContent === endCommentText) {
          foundEndMarker = true;
          const previousSibling = currentNode.previousSibling;
          currentNode.remove();
          currentNode = previousSibling;
          continue;
        } else if (currentNode.textContent === startCommentText) {
          currentNode.remove();
          break;
        } else if (
          foundEndMarker &&
          currentNode.nodeName.toLowerCase() === 'style'
        ) {
          fcStyleEls.push(currentNode as HTMLStyleElement);
        }
        currentNode = currentNode.previousSibling;
      }

      fcStyleEls.forEach((t) => t.parentNode?.removeChild(t));
      fcStyleEls.reverse().forEach((t, i) => {
        const lastInserted =
          i > 0 ? (fcStyleEls[i - 1] as HTMLStyleElement) : headCountEl;
        const inserted = headEl.insertBefore(
          t,
          lastInserted.nextElementSibling
        );

        if (i === 0) {
          const startComment = document.createComment(startCommentText);
          headEl.insertBefore(startComment, t);
        } else if (i === fcStyleEls.length - 1) {
          const endComment = document.createComment(endCommentText);
          headEl.insertBefore(endComment, inserted.nextElementSibling);
        }
      });
    }
  }, []);

  return <FullCalendar {...props} />;
};
```
```
// App.tsx
import dynamic from 'next/dynamic';

const Calendar = dynamic(
  () => import('./Calendar').then((mod) => mod.Calendar),
  { ssr: false }
);

const App = () => {
  return <Calendar />;
};
```

**Comment by acerix** [comment]
Would you be able to post a [runnable, stripped-down demonstration of the bug](http://fullcalendar.io/wiki/Reduced-Test-Cases/)? Would really appreciate it because the time saved reproducing will be time spent fixing.

**Comment by nidrissi** [comment]
@acerix I'm running into the same issue. And @VinniC77 did post a reduced test case, as far as I can tell: https://github.com/VinniC77/Fullcalendar-error
