### ISSUE TITLE
Vue2 after select event jump another page then back , the table width become 0 

### ISSUE THREAD

**Issue by nadirvishun** [fullcalendar/fullcalendar#7267]
### Reduced Test Case

no url

### Do you understand that if a reduced test case is not provided, we will intentionally delay triaging of your ticket?

- [X] I understand

### Which connector are you using (React/Angular/etc)?

Vue

### Bug Description

I can not open bug template, so I will describe it , exampe page A：
- the calendarOptions:
  ```
   calendarOptions: {
      ....
      selectable: true,
      select: this.handleDateSelect,
   },
  ```
- the event :
  ```
  handleDateSelect(selectInfo) {
    this.$router.push({
      path: '/xxx/xxx'
    });
  }
  ```
- after select event ,use vue router jump another page B, then back to the page A, the table width become 0, the example gif:
![bug](https://user-images.githubusercontent.com/5761981/228996426-dc378b85-7ca0-4f48-ac07-059b8adeb124.gif)
![bug_mobile](https://user-images.githubusercontent.com/5761981/228997165-8affbe69-982e-4b41-b1aa-bef205bb03d2.gif)

- pc and mobile both has this problem : 
  - PC
    ```
      "@fullcalendar/core": "^6.0.2",
      "@fullcalendar/daygrid": "^6.0.2",
      "@fullcalendar/interaction": "^6.0.2",
      "@fullcalendar/timegrid": "^6.0.2",
      "@fullcalendar/vue": "^6.0.2",
    ```
  - MOBILE
    ```
    "@fullcalendar/core": "^6.1.5",
    "@fullcalendar/daygrid": "^6.1.5",
    "@fullcalendar/interaction": "^6.1.5",
    "@fullcalendar/timegrid": "^6.1.5",
    "@fullcalendar/vue": "^6.1.5",
    ```
- a temporary solution : 
  ```
  handleDateSelect(selectInfo) {
    //cancel select
    this.calendarApi.unselect();
    this.$router.push({
      path: '/xxx/xxx'
    });
  }
  ```

**Comment by acerix** [comment]
Would you be able to post a [runnable, stripped-down demonstration of the bug](http://fullcalendar.io/wiki/Reduced-Test-Cases/)? Would really appreciate it because the time saved reproducing will be time spent fixing.

You may need to call [updateSize](https://fullcalendar.io/docs/updateSize) after changing the page.

**Comment by nadirvishun** [comment]
@acerix  I can't open the [vue2 debugging templates](https://stackblitz.com/github/fullcalendar/fullcalendar-examples/tree/main/vue2), I don't know why：
![image](https://user-images.githubusercontent.com/5761981/229968529-d3516e51-b837-4100-8a81-c92337c5e7d8.png)
