### ISSUE TITLE
View month in line

### ISSUE THREAD

**Issue by Alexandr-Rodnyanyi** [fullcalendar/fullcalendar#7268]
### Checklist

- [X] I've already searched through [existing tickets](https://github.com/fullcalendar/fullcalendar/issues)
- [X] Other people will find this feature useful

### Is this feature for a specific connector (React/Angular/etc)?

React

### Feature Description

Any help. I'm trying to make such a calendar using the fullCalendar library. I have a 3*4 calendar grid and I need to change it so that the month is displayed on one line and the months are one under one. [enter image description here](https://i.stack.imgur.com/VEq3r.png)

I tried to do this with CSS, but the event is not displayed correctly. For example, I click on the cell 03/20/2023 and 03/29/2023 is displayed

**Comment by acerix** [comment]
I believe this existing ticket captures this need:
https://github.com/fullcalendar/fullcalendar/issues/5119
↑
Please visit the above issue, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates.
