### ISSUE TITLE
vertical year view

### ISSUE THREAD

**Issue by stefan817** [fullcalendar/fullcalendar#7271]
### Checklist

- [X] I've already searched through [existing tickets](https://github.com/fullcalendar/fullcalendar/issues)
- [X] Other people will find this feature useful

### Is this feature for a specific connector (React/Angular/etc)?

No connector in particular

### Feature Description

For fast planning of a year I often use a simple calendar with months in columns and days of month in rows. It’s really simple, and it’s a really clear view. But I didn’t find any calendar software yet, that offers this view.

Would Fullcalendar be the first? 

Have a look at this example: 

![Kalenderpedia Jahreskalender 6 Monate auf 1 Seite](https://user-images.githubusercontent.com/26048888/229379237-4479af63-b995-4ba5-b1ba-76c1fa015518.png)

I would like to see the first words of appointments of the day in that view. If I hover the mouse on a day, it could show all appointments of the day as list, agenda or maybe like the day-view. So the mouse would be like a lense for the details.

If you like it and want more, have a look at https://www.kalenderpedia.de/kalender-2023-pdf-vorlagen.html There are more similar views.

**Comment by acerix** [comment]
I believe this existing ticket captures this need:
https://github.com/fullcalendar/fullcalendar/issues/3963
↑
Please visit the above issue, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates.
