### ISSUE TITLE
Unclickable date column in resourceTimeline custom view

### ISSUE THREAD

**Issue by LucaP994** [fullcalendar/fullcalendar#7272]
### Reduced Test Case

https://codepen.io/LucaP994/pen/KKxOmEW?editors=1000

### Do you understand that if a reduced test case is not provided, we will intentionally delay triaging of your ticket?

- [X] I understand

### Which connector are you using (React/Angular/etc)?

Angular

### Bug Description

I have the necessity to use this view and when clicking on the date i need to get all the data from the calendar, but the last column seems to be not working for some reason. I added an alert to the test case taht popup when some date is clicked.

**Comment by acerix** [comment]
I believe this existing ticket captures this issue:
https://github.com/fullcalendar/fullcalendar/issues/5820
↑
Please visit the above issue, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates.

But I'm not sure you actually want to set `slotDuration` to "1 month plus 1 hour", it works with just 1 month:

https://codepen.io/acerix/pen/rNqBpWb?editors=1000

**Comment by LucaP994** [comment]
Hi acerix, my mistake, i did'nt specify that i need that the slotDuration must be {months:1, hours:1} due to the necessity to render the events in a certain way... for example if an event start the 15th of june and end the 15th of july, this event will be displayed from the middle of the june's column to the middle of the july's column. But if i set the slotDuration to only 1 month, the event will fit the entire months's slot. I've updated my test case in case you want to see it.
https://codepen.io/LucaP994/pen/KKxOmEW?editors=1000

**Comment by acerix** [comment]
It sounds like you do want the timeslots to be exactly one month long then. Using `{months:1, hours:1}` may work as a hack to make the event show like that but won't work properly in general.

I believe this issue covers showing the exact hours of the event without labels for each hour:

https://github.com/fullcalendar/fullcalendar/issues/4937

You could try the workaround there:

https://codepen.io/acerix/pen/poLZRON?editors=0110

**Comment by LucaP994** [comment]
It works!! Thanks a lot @acerix!
I've updated the test case in a way to remove all the unnecessary columns and separate only months.
I hope that this case will be helpfull also to someone else.
https://codepen.io/LucaP994/pen/KKxOmEW?editors=1010
