### ISSUE TITLE
JSX element in `eventContent` leads to flicker from any event-related updates

### ISSUE THREAD

**Issue by nandorojo** [fullcalendar/fullcalendar#7273]
### Reduced Test Case

https://stackblitz.com/edit/github-8qn74d-djfu5w?file=src%2FDemoApp.jsx

### Do you understand that if a reduced test case is not provided, we will intentionally delay triaging of your ticket?

- [X] I understand

### Which connector are you using (React/Angular/etc)?

React

### Bug Description

If I use the `eventContent` prop on the React component and return JSX, there is a very noticeable flicker in the following cases:

1. State update for the `events` prop.
2. Dragging events without a state change (as shown in the [minimal reproduction](https://stackblitz.com/edit/github-8qn74d-djfu5w?file=src%2FDemoApp.jsx))

If I simply return a string from `eventContent` rather than JSX, there is less of a flicker from updates. 

# Screen Recordings

## 1. Reproduction recording

First, here is a screen recording of the flickering in the minimal reproduction. When `eventContent` is set, dragging (without triggering React re-renders) leads to a flicker of the event. Disabling the `eventContent` prop fixes it.

https://user-images.githubusercontent.com/13172299/229567380-9e729206-c55e-49bf-811c-f684e611caa2.mp4

Since it's not super noticeable with just one event on a minimal reproduction, I will add a video of what it looks like on our actual product as well.

## 2. Real-life product recording

https://user-images.githubusercontent.com/13172299/229574343-504b136c-c1f3-4ad7-8bf7-71fc749768e2.mp4

After dragging an event, I push the change to the server. Then, after the server mutation succeeds, I re-render the component with a new `eventSources` array. This is when the events flicker.

Similarly: when I change the time of the event from the sidebar to the right, I call the server, update the change, and then re-render the calendar with the updated events.

Interestingly, only events of the same type (as in, from the same array within `eventSources`) experience a flicker. Notice that the events with a green background don't flicker at all.

### Context

I am using `eventSources` with an array for each event type, which gets updated whenever the state changes.

My `eventSources` looks like this:

```ts
eventSources = useMemo(() => [firstEventTypes, secondEventTypes, ...], [...])
```

**Comment by acerix** [comment]
I believe this existing ticket captures this need:
https://github.com/fullcalendar/fullcalendar/issues/7165
↑
Please visit the above issue, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates.
