### ISSUE TITLE
FullCalendar height 100% overflows container when other elements exist within it

### ISSUE THREAD

**Issue by dwasyl** [fullcalendar/fullcalendar#7278]
### Reduced Test Case

https://codepen.io/dw93/pen/mdzdEeg?editors=1000

### Do you understand that if a reduced test case is not provided, we will intentionally delay triaging of your ticket?

- [X] I understand

### Which connector are you using (React/Angular/etc)?

No connector (vanilla JS)

### Bug Description

When placing FullCalendar in a container (a bootstrap column in this case), and setting `height: "100%",` the calendar overflows the container if any other content exists within the container. Having tried to make additional containers within the column does not help, FullCalendar always ends up overflowing the parent container. 

With `height` set to `100%`, I would think the element should be constrained to the remaining size of the parent element, not matching the original height in `px`.

![image](https://user-images.githubusercontent.com/2297074/230270935-7758356e-88b2-4f6d-aaa7-f34e621ac6c8.png)

**Comment by acerix** [comment]
That setting work the same as `height: 100%` CSS, it matches the height of the parent.  I don't believe this is a bug in the calendar, as a plain `div` has the same height as in this example, so you would need to set the parent element to the correct to fit then "100%" will also work.

https://codepen.io/acerix/pen/QWZbrGG

**Comment by dwasyl** [comment]
@acerix Fair enough, but with dynamic height elements, there is no way to have it "fill" the remaining space without spilling over. I'll have to look at sitting fixed heights for the calendar component or perhaps another container. In an ideal there would be the equivalent of a 100% that fills the remaining space (but perhaps that's not even possible).

**Comment by acerix** [comment]
I'm not sure it would be possible for the calendar to fill it in this case.  If there's is a way to fill it with a plain `div` liek the one in my example, you could use that as the parent for the calendar, then "100% height" should also work.

**Comment by dwasyl** [comment]
@acerix Hmm okay, thanks, will have to spend some time with it.
