### ISSUE TITLE
Any way to put all the views as a list in a select html element

### ISSUE THREAD

**Issue by Javier1995** [fullcalendar/fullcalendar#7281]
### Checklist

- [X] I've already searched through [existing tickets](https://github.com/fullcalendar/fullcalendar/issues)
- [X] Other people will find this feature useful

### Is this feature for a specific connector (React/Angular/etc)?

Vue

### Feature Description

I'd like to put them in a select html list any idea that may be helpful?

![image](https://user-images.githubusercontent.com/11432889/230786392-31076150-82d6-4376-a7b2-cce205ec7bf4.png)

**Comment by acerix** [comment]
I believe this existing ticket captures this need:
https://github.com/fullcalendar/fullcalendar/issues/4716
↑
Please visit the above issue, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates.
