### ISSUE TITLE
Blinking on creating an event

### ISSUE THREAD

**Issue by semyonn-7pace** [fullcalendar/fullcalendar#7282]
### Reduced Test Case

https://stackblitz.com/github/fullcalendar/fullcalendar-examples/tree/main/react

### Do you understand that if a reduced test case is not provided, we will intentionally delay triaging of your ticket?

- [X] I understand

### Which connector are you using (React/Angular/etc)?

React

### Bug Description

When user tries to create an event by click & drag event are blinking. 

You can even see this in the standard stackblitz example.
STR:
1. Open the timeGridWeek view.
2. Try to create an event with click & drag.
3. The selectMirror property must be true.
4. If the eventContent property returns jsx you will see a flicker every time you move the mouse.

![chrome_IdL95fzk6N](https://user-images.githubusercontent.com/69300040/230897629-e281ea1a-77a9-4e5c-9c9b-da44c9fa8755.gif)

**Comment by acerix** [comment]
I believe this existing ticket captures this need:
https://github.com/fullcalendar/fullcalendar/issues/7165
↑
Please visit the above issue, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates.
