### ISSUE TITLE
¿Puedo adaptar el producto a esta vista

### ISSUE THREAD

**Issue by jahernandezg** [fullcalendar/fullcalendar#7292]
### Checklist

- [X] I've already searched through [existing tickets](https://github.com/fullcalendar/fullcalendar/issues)
- [X] Other people will find this feature useful

### Is this feature for a specific connector (React/Angular/etc)?

No connector in particular

### Feature Description

Hello, I would like to know before buying the product, if I can make a view similar to the timeline that is premium, the one in the following image?
Grateful for your response.
![interfaz-final](https://user-images.githubusercontent.com/52046252/233727176-7e561d96-4725-4640-add9-55c7103ff46a.jpg)

**Comment by acerix** [comment]
You could use the timeline view for this which is similar, here is an example:

https://codepen.io/acerix/pen/YzJVgLj?editors=001
