### ISSUE TITLE
Drag events bug with two calendars in case one overlaps another

### ISSUE THREAD

**Issue by walerun** [fullcalendar/fullcalendar#7293]
### Reduced Test Case

https://codepen.io/walerun/pen/rNqyxvP

### Do you understand that if a reduced test case is not provided, we will intentionally delay triaging of your ticket?

- [X] I understand

### Which connector are you using (React/Angular/etc)?

React

### Bug Description

The case is you have two calendars. But one calendar was placed over another (in my case the second calendar opened inside the fullscreen modal dialog). Dragging events stop working correctly. As I can see there are some global configs in order to manage dnd things between two calendars which causes the issue as it tries to find a proper droppable zone and it found one but not the correct one. I guess it's by design but at the same time, I didn't find a good way to fix it.
Even if I pass to the first calendar editable=false, dropAccept=false,  the global dnd mechanism still uses the first calendar to find the drop area.
See the example in the link.

**Comment by acerix** [comment]
I believe this existing ticket captures this need:
https://github.com/fullcalendar/fullcalendar/issues/5026
↑
Please visit the above issue, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates.
