### ISSUE TITLE
Date Picker Popup is not available in angular, can we have this functionality to jump months/year

### ISSUE THREAD

**Issue by SakshiTiwari28** [fullcalendar/fullcalendar#7294]
### Checklist

- [X] I've already searched through [existing tickets](https://github.com/fullcalendar/fullcalendar/issues)
- [X] Other people will find this feature useful

### Is this feature for a specific connector (React/Angular/etc)?

No connector in particular

### Feature Description

![image](https://user-images.githubusercontent.com/37017762/233988607-cb082c35-2e99-487a-a041-354bfbbb4c0e.png)

**Comment by acerix** [comment]
I believe this existing ticket captures this need:
https://github.com/fullcalendar/fullcalendar/issues/438
↑
Please visit the above issue, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates.
