### ISSUE TITLE
Tree structure, can the left tree automatically fold up?

### ISSUE THREAD

**Issue by BabyMing** [fullcalendar/fullcalendar#7295]
### Checklist

- [X] I've already searched through [existing tickets](https://github.com/fullcalendar/fullcalendar/issues)
- [X] Other people will find this feature useful

### Is this feature for a specific connector (React/Angular/etc)?

No connector in particular

### Feature Description

Tree structure, can the left tree automatically fold up?

**Comment by acerix** [comment]
I believe this existing ticket captures this need:
https://github.com/fullcalendar/fullcalendar/issues/4832
↑
Please visit the above issue, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates.

If you mean something else, it may help to include a mock-up.
