### ISSUE TITLE
 Access to Date and Events in eventContent Callback

### ISSUE THREAD

**Issue by nathanjml** [fullcalendar/fullcalendar#7296]
### Checklist

- [X] I've already searched through [existing tickets](https://github.com/fullcalendar/fullcalendar/issues)
- [X] Other people will find this feature useful

### Is this feature for a specific connector (React/Angular/etc)?

React

### Feature Description

Hello,

I'm currently using FullCalendar in a React.js project with the Day Grid plugin, and I'm running into an issue with customizing the content of the day cells. Specifically, I need access to both the date being rendered and the events that are passed to the FullCalendar component in order to render custom JSX in each day cell.

I've tried using the dayCellContent callback to customize the content of each day cell, but this approach limits my ability to interact with the events that are passed to the FullCalendar component, including drag and drop functionality provided by the @fullcalendar/interaction plugin.

I've also tried using the eventContent callback to customize the content of each event, but this approach doesn't provide access to the date being rendered in each day cell.

I believe a potential solution to this issue would be to provide the date argument to the eventContent callback. This would allow users to customize the content of each event while still having access to the date being rendered in each day cell.

Thank you for your consideration, and please let me know if you have any questions or need additional information.

Best regards,

Nathan M.

**Comment by acerix** [comment]
If you are looking to set the day cell content based on the events on that day, I believe this existing ticket captures this need:
https://github.com/fullcalendar/fullcalendar/issues/6848
↑
Please visit the above issue, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates.

To render every day of an event differently based on the date, you could add each day of the event as a separate event, then `eventContent` will have the date of each one.  There is a request here regarding splitting events into parts:

https://github.com/fullcalendar/fullcalendar/issues/5099
