### ISSUE TITLE
Is any other function available? which works like dayRender?

### ISSUE THREAD

**Issue by chaklasiyanikunj** [fullcalendar/fullcalendar#7299]
### Checklist

- [X] I've already searched through [existing tickets](https://github.com/fullcalendar/fullcalendar/issues)
- [X] Other people will find this feature useful

### Is this feature for a specific connector (React/Angular/etc)?

Angular

### Feature Description

I know dayRender was replaced in v5.
https://fullcalendar.io/docs/dayRender

Is any other function available?
which works like dayRender?

**Comment by acerix** [comment]
Duplicate of #https://github.com/fullcalendar/fullcalendar/issues/7299
