### ISSUE TITLE
Style injection bug when FullCalendar v6 is bundled with webPack in React/Next.js project

### ISSUE THREAD

**Issue by Garajluc** [fullcalendar/fullcalendar#7302]
### Reduced Test Case

----

### Do you understand that if a reduced test case is not provided, we will intentionally delay triaging of your ticket?

- [X] I understand

### Which connector are you using (React/Angular/etc)?

React

### Bug Description

The newest version of FullCalendar v6 works as expected in a development mode started via `next dev` (React/Next.js app). 
Unfortunately, once we run `next build` and `next start`, the styles (custom and not even the default from the fullcalendar CSS) are not injected properly and the calendar component looks completely different. This causes a huge inconsistency between how the CSS applies while in development mode in comparison how it applies in build mode.

We use React.js with WebPack bundler. We use the connector component 
https://www.npmjs.com/package/@fullcalendar/react. 

I will try to provide a reduced test case ASAP.
Development Mode:
<img width="1381" alt="Screenshot 2023-04-26 at 14 56 59" src="https://user-images.githubusercontent.com/32719289/234582466-8d35f5e1-dc98-44b3-8e44-42a069216ecf.png">

Build Mode:
<img width="1381" alt="Screenshot 2023-04-26 at 14 59 33" src="https://user-images.githubusercontent.com/32719289/234582454-da889964-8185-4483-b3e9-fe4b6e025aa0.png">

**Comment by acerix** [comment]
Would you be able to post a [runnable, stripped-down demonstration of the bug](http://fullcalendar.io/wiki/Reduced-Test-Cases/)? Would really appreciate it because the time saved reproducing will be time spent fixing.

I tried the example project in production mode and could not replicate the issue:

https://stackblitz.com/edit/github-lsrdyk?file=webpack.config.js

**Comment by nandorojo** [comment]
Same thing happened to me, though I couldn't reproduce it on Stackblitz. It happened for me **after a client-side route** from a different page. If I refreshed right to this page, it worked for me.
