### ISSUE TITLE
Getting simple recurring events outside current view

### ISSUE THREAD

**Issue by Urbener** [fullcalendar/fullcalendar#7308]
### Reduced Test Case

https://jsfiddle.net/8s65wdju/

### Do you understand that if a reduced test case is not provided, we will intentionally delay triaging of your ticket?

- [X] I understand

### Which connector are you using (React/Angular/etc)?

No connector (vanilla JS)

### Bug Description

According to the [`.getEvents()`](https://fullcalendar.io/docs/Calendar-getEvents) documentation, the function should return "all events in memory", but when having simple recurring events outside the current view, it doesn't.

No matter if they are dynamically added via `calendar.addEvent()` or are loaded with the `events` / `initialEvents` option. It also happens with any view (I've tried `timeGrid`, `dayGrid` and `dayGridMonth`) and both in v5 and 6. Non-recurring events do get returned as expected.
The test case is pretty straightforward, but open the console just in case

I'm pretty sure that this is the same bug as #5491 that got closed with no feedback from the original reporter.

Am I correct in thinking this is a bug? There's [this comment](https://github.com/fullcalendar/fullcalendar/blob/6d789ad6727d5978c40a3395791298443822f66e/packages/common/src/api/EventApi.ts#L26) on v5 that _could_ imply this is expected behavior, but no mention of it anywhere else, so at least it should be a documentation defect.

**Comment by acerix** [comment]
Events only get added to memory when they are visible. Since events can repeat forever, so it wouldn't be possible to load all instances of a recurring event in general, but you could evaluate the rrule manually to get instances that are not in the view:

https://github.com/jakubroztocil/rrule#usage

**Comment by acerix** [comment]
`getEvents` returns the visible events instances, not how they were defined.   You could get the definitions from the event data that you are supplying to the calendar.  I believe this request covers retrieving the definitions from the calendar:
https://github.com/fullcalendar/fullcalendar/issues/5262
↑
Please visit the above issue, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates.
