### ISSUE TITLE
android stopped working when there is no appointment.

### ISSUE THREAD

**Issue by andrejm7** [fullcalendar/fullcalendar#7317]
### Reduced Test Case

xxx

### Do you understand that if a reduced test case is not provided, we will intentionally delay triaging of your ticket?

- [X] I understand

### Which connector are you using (React/Angular/etc)?

Angular

### Bug Description

Good evening, I updated my fullcalendar to version 6.1.6 but the click on android stopped working when there is no appointment. what happened?

**Comment by acerix** [comment]
Would you be able to post a [runnable, stripped-down demonstration of the bug](http://fullcalendar.io/wiki/Reduced-Test-Cases/)? Would really appreciate it because the time saved reproducing will be time spent fixing.
