### ISSUE TITLE
how can I make this with react fullcalendar ? scroll with right and left mouse?

### ISSUE THREAD

**Issue by pullmann4rent** [fullcalendar/fullcalendar#7318]
### Reduced Test Case

x

### Do you understand that if a reduced test case is not provided, we will intentionally delay triaging of your ticket?

- [X] I understand

### Which connector are you using (React/Angular/etc)?

React

### Bug Description

I use fullcalendar and I saw anyone who uses this too and with the left mouse click he can smoothly scroll top and left and with right mouse click he can select dates. Which props do I need for this to make it like this ? I made a video what I want:

at current my code looks like this:

```

        <FullCalendar 
          schedulerLicenseKey="xxx" 
          plugins={[ resourceTimelinePlugin, interactionPlugin, scrollGrid ]}
          initialView='resourceTimelineYear'
          initialDate={new Date()}
          stickyHeaderDates
          height='auto'
          stickyFooterScrollbar
          dragScroll
          aspectRatio={2}
          selectOverlap
          editable={true}
          selectable={true}
          selectMirror={true}
          scrollTime='00:00'
          resources={[
            { id: 'a', building: '460 Bryant', title: 'Auditorium A' },
            { id: 'b', building: '460 Bryant', title: 'Auditorium B' },
            { id: 'c', building: '460 Bryant', title: 'Auditorium C' },
            { id: 'd', building: '460 Bryant', title: 'Auditorium D' },
            { id: 'e', building: '460 Bryant', title: 'Auditorium E' },
          ]}
          resourceGroupField='building'
        />

```

https://user-images.githubusercontent.com/123197323/236703844-d28ea7f6-eff6-4523-a142-cb87500d632e.mp4

**Comment by acerix** [comment]
I believe this existing ticket captures this need:
https://github.com/fullcalendar/fullcalendar/issues/4121
↑
Please visit the above issue, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates.
