### ISSUE TITLE
A general in-line events feature

### ISSUE THREAD

**Issue by yashk1996** [fullcalendar/fullcalendar#7319]
### Checklist

- [X] Other people will find this feature useful
- [X] I've already searched through [existing tickets](https://github.com/fullcalendar/fullcalendar/issues)

### Is this feature for a specific connector (React/Angular/etc)?

No connector in particular

### Feature Description

Would be great to have in-line events for any given note, just like the [Daily note](https://davish.github.io/obsidian-full-calendar/calendars/dailynote/). For example, one could have a note named  "Excercise" and instead of making a new full note for each event, one could add in-line events in the excercise note.

**Comment by Gabrielmoraesp** [comment]
This feature would be very useful!!!

**Comment by acerix** [comment]
I believe this existing ticket captures this need:
https://github.com/fullcalendar/fullcalendar/issues/433
↑
Please visit the above issue, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates.
