### ISSUE TITLE
Selected date disappears when advancing to the next month

### ISSUE THREAD

**Issue by Gabrielmoraesp** [fullcalendar/fullcalendar#7323]
### Reduced Test Case

https://github.com/fullcalendar/fullcalendar/issues

### Do you understand that if a reduced test case is not provided, we will intentionally delay triaging of your ticket?

- [X] I understand

### Which connector are you using (React/Angular/etc)?

No connector (vanilla JS)

### Bug Description

When selecting 1 or more dates in the calendar after advancing the month in the calendar, the selected dates add back to the previous month.

Example: I selected May 14th and 16th. I advanced to June and selected the 23rd and 27th. After returning to May, the date selection disappears.

**Comment by acerix** [comment]
The selection feature only selects one range at a time.  You can add the selection as a background event to make it persist when a new selection is started.

https://fullcalendar.io/docs/background-events
