### ISSUE TITLE
dragScroll does not work on multiMonth view

### ISSUE THREAD

**Issue by corey-sickinger-sg** [fullcalendar/fullcalendar#7324]
### Reduced Test Case

https://codepen.io/corey-sickinger-sg/pen/WNaybyZ?editors=001

### Do you understand that if a reduced test case is not provided, we will intentionally delay triaging of your ticket?

- [X] I understand

### Which connector are you using (React/Angular/etc)?

No connector (vanilla JS)

### Bug Description

dragScroll does not scroll the view when using the multiMonthYear view. 
You can see this on the FullCalendar "multiMonthYear as a vertical stack" demo page: https://fullcalendar.io/docs/multimonth-stack-demo

If you drag an event to the top or bottom of the view, the view does not scroll as expected.

In the Reduced Test Case, I've modified it in codepen to explicity set the value of the dragScroll parameter to true and you can see it does not affect the behavior.

**Comment by corey-sickinger-sg** [comment]
It does not seem to matter whether the view is only displaying a single column or not. 
The default 2-column view also does not scroll as expected.

**Comment by arshaw** [comment]
This has been fixed in [v6.1.15](https://github.com/fullcalendar/fullcalendar/releases/tag/v6.1.15)

Updated repro:
https://codepen.io/arshaw/pen/OJeVzNw?editors=001
