### ISSUE TITLE
Toolbar not responsive on mobile

### ISSUE THREAD

**Issue by clicktodev** [fullcalendar/fullcalendar#7327]
### Reduced Test Case

https://fullcalendar.io/demos

### Do you understand that if a reduced test case is not provided, we will intentionally delay triaging of your ticket?

- [X] I understand

### Which connector are you using (React/Angular/etc)?

React

### Bug Description

Toolbar elements overflow on mobile.

Example:
![image](https://github.com/fullcalendar/fullcalendar/assets/34947993/dc72b3fa-9e5c-4cc7-baae-e15b278932e0)

**Comment by acerix** [comment]
I believe this existing ticket captures this need:
https://github.com/fullcalendar/fullcalendar/issues/4638
↑
Please visit the above issue, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates.
