### ISSUE TITLE
Cannot install in angular v16

### ISSUE THREAD

**Issue by moodyVlad** [fullcalendar/fullcalendar#7328]
### Checklist

- [X] I've already searched through [existing tickets](https://github.com/fullcalendar/fullcalendar/issues)
- [X] Other people will find this feature useful

### Is this feature for a specific connector (React/Angular/etc)?

Angular

### Feature Description

Please bump angular peerDependency version to 12-16. We cannot install it without using the --legacy-peer-deps or --force flag.
Thanks

**Comment by acerix** [comment]
I believe this existing ticket captures this need:
https://github.com/fullcalendar/fullcalendar/issues/7312
↑
Please visit the above issue, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates.
