### ISSUE TITLE
Event resizing 

### ISSUE THREAD

**Issue by arshaw** [fullcalendar/fullcalendar#733]
Originally reported on Google Code with ID 463

```
I am trying to resize an event from the examples,

I am using Safari 4.0.4 on Mac 0S 10.5, but am unable to drag the event to resize it?
```

Reported by `naterowe82` on 2010-04-26 14:03:10

**Comment by janswist** [comment]
I have similar bug - when resizing event it just disappears. Safari 11.0.2
