### ISSUE TITLE
Styles are not applied with CSP containing different nonces for styles/scripts

### ISSUE THREAD

**Issue by Alpin944** [fullcalendar/fullcalendar#7331]
### Reduced Test Case

https://codepen.io/Carsten-S-rensen/pen/LYgBdpx

### Do you understand that if a reduced test case is not provided, we will intentionally delay triaging of your ticket?

- [X] I understand

### Which connector are you using (React/Angular/etc)?

No connector (vanilla JS)

### Bug Description

After updating to 6.1.4 and following your guide to handle Content Security Policy, this still doesn't work when the project uses one nonce for styles and another one for scripts. It fails on parentEl.appendChild(style) in your function injectStylesInParent.
This should be easy to fix, with nonce for styles are found on a style, and nonce for scripts are found on a script.

**Comment by acerix** [comment]
Thanks, confirmed.  For reference, this is the error I get:

```Refused to apply inline style because it violates the following Content Security Policy directive: "style-src 'self' 'nonce-abc123'". Either the 'unsafe-inline' keyword, a hash ('sha256-2OTceqSQmkTg8dF4uXJnncUTPXrvR4eT2fCjRp5TAvg='), or a nonce ('nonce-...') is required to enable inline execution.```

**Comment by arshaw** [comment]
If you write this additional meta tag (mentioned at the end of the [CSP docs page](https://fullcalendar.io/docs/content-security-policy)) things should work:

```html
<meta name='csp-nonce' content='qwerty456' />
```

It only uses  `qwerty456` for injecting styles and does not use it for scripts in any way.

Codepen isn't working well for debugging these CSP problems, I believe because the script/style tags it injects violates your CSP declarations. However, if you run the following HTML in its own file, things should work:

```html
<!DOCTYPE html>
<html>
<head>
<meta charset='utf-8' />
<meta http-equiv="Content-Security-Policy" content="script-src 'self' 'nonce-abc123'; style-src 'self' 'nonce-xyz123'">
<meta name='csp-nonce' content='xyz123' /><!-- for FullCalendar style-injection ONLY -->
<script src='https://cdn.jsdelivr.net/npm/fullcalendar@6.1.7/index.global.js' nonce="abc123"></script>
<script nonce="abc123">

  document.addEventListener('DOMContentLoaded', function() {
    var calendarEl = document.getElementById('calendar');

    var calendar = new FullCalendar.Calendar(calendarEl, {
      initialDate: '2020-09-12',
      initialView: 'timeGridWeek',
      nowIndicator: true,
      headerToolbar: {
        left: 'prev,next today',
        center: 'title',
        right: 'dayGridMonth,timeGridWeek,timeGridDay'
      },
      navLinks: true, // can click day/week names to navigate views
      editable: true,
      selectable: true,
      selectMirror: true,
      dayMaxEvents: true, // allow "more" link when too many events
    });

    calendar.render();
  });

</script>
<style nonce='xyz123'>

  body {
    margin: 40px 10px;
    padding: 0;
    font-family: Arial, Helvetica Neue, Helvetica, sans-serif;
    font-size: 14px;
  }

  #calendar {
    max-width: 1100px;
    margin: 0 auto;
  }

</style>
</head>
<body>

  <div id='calendar'></div>

</body>
</html>

```

**Comment by Alpin944** [comment]
@arshaw Adding that meta tag would completely set the CSP safety out of function, as others could also fetch the nonce, and inject a potentially unsafe script.
Why not just look for script containing nonce when appending script, and style containing nonce when appending style?
