### ISSUE TITLE
Custom day cell content is getting rendered on next day, not on today's date.

### ISSUE THREAD

**Issue by gaurav-simpplr** [fullcalendar/fullcalendar#7333]
### Reduced Test Case

-

### Do you understand that if a reduced test case is not provided, we will intentionally delay triaging of your ticket?

- [X] I understand

### Which connector are you using (React/Angular/etc)?

React

### Bug Description

I'm trying to render custom react component on my day cells. It would be same for all the day cells except for the current date or today's date. I've written below code for the same. But on running it, the component which should render on today's date (conditional check is there for the same) is getting rendered on the next day, (i.e. if today's date is 15 May 20223, rather than rendering the custom component on 15 May 2023, its rendering it on next day 16 May 2023).

I checked my dates and console the output, but it is coming correct. 

import dayGridPlugin from '@fullcalendar/daygrid';
import FullCalendar from '@fullcalendar/react';
import { DateTime } from 'luxon';
import React from 'react';

export const Calendar = () => {

  const renderDayContent = (e) => {
    const today = DateTime.now().startOf('day');
    const cellDate = DateTime.fromJSDate(e.date).startOf('day');
    const isToday = today.hasSame(cellDate, 'day');

    if (isToday) {

      console.log('today', today)
      console.log('cellDate', cellDate)
      console.log('isToday', isToday)

      return (
        <div className="today">                    
              {e.dayNumberText}
        </div>
      );
    }

    return (
         <div className='day'>
             {e.dayNumberText}
          </div>
    );
  };

  return (
      <FullCalendar
        headerToolbar={false}
        plugins={[dayGridPlugin]}
        initialView="dayGridMonth"
        dayCellContent={renderDayContent}
        events={[
          { title: 'event 1', date: '2023-05-01' },
          { title: 'event 2', date: '2023-05-02' },
        ]}
      />
<img width="1783" alt="Screenshot 2023-05-15 at 8 08 49 PM" src="https://github.com/fullcalendar/fullcalendar/assets/98866537/9ec1c396-cb82-4829-848a-fb6ba256c945">

  );
};

**Comment by yamatohagi** [comment]
Doesn't it work properly? I checked with the following code, and it works fine. On the contrary, it seems that className="today" is not functioning.

if (isToday) {

console.log('today', today)
console.log('cellDate', cellDate)
console.log('isToday', isToday)

return (
<div className="today">
{e.dayNumberText}{'today'}
</div>
);
}

return (
<div className='day'>
{e.dayNumberText}
</div>
);

**Comment by gaurav-simpplr** [comment]
Hi @yamatohagi Thanks for replying. It seems to me some kind of timezone issue. For first half of the day, it shows the correct date, for second half (after 12:00 PM IST) it shows the next date (tomorrow's date) as today. How can I fix this ?

**Comment by acerix** [comment]
Would you be able to post a [runnable, stripped-down demonstration of the bug](http://fullcalendar.io/wiki/Reduced-Test-Cases/)? Would really appreciate it because the time saved reproducing will be time spent fixing.
