### ISSUE TITLE
View is not scrolled so that `scrollTime` is at the beginning of the view for RTL locale

### ISSUE THREAD

**Issue by jsuares** [fullcalendar/fullcalendar#7335]
### Reduced Test Case

https://codepen.io/jsuares/pen/xxyyGZy?editors=001

### Do you understand that if a reduced test case is not provided, we will intentionally delay triaging of your ticket?

- [X] I understand

### Which connector are you using (React/Angular/etc)?

No connector (vanilla JS)

### Bug Description

When using RTL (he locale) the setting scrollTime is not displayed correctly and the timeline starts from 00:00

Removing the locale (and thr RTL setting) fixes the issue

**Comment by acerix** [comment]
Related to: https://github.com/fullcalendar/fullcalendar/issues/4837

**Comment by jsuares** [comment]
It is amazing that this issue which can be solved probably with one line of code has not been solved for over four years (!) on the PAID component

**Comment by arshaw** [comment]
@jsuares https://github.com/fullcalendar/fullcalendar/issues/4837#issuecomment-2081635305

**Comment by arshaw** [comment]
This is fixed in [v6.1.12](https://github.com/fullcalendar/fullcalendar/releases/tag/v6.1.12). Please write back with any issues.

Turns out this was a distinct bug from #4837

**Comment by arshaw** [comment]
I'm not seeing that this made a difference to the reduced test case.
updated reduced test case: https://codepen.io/arshaw/pen/oNRxVjY?editors=001

I will circle back. Apologies.

**Comment by arshaw** [comment]
Note to self:

Using the character "A" to create the overflow for the cross-browser scrollLeft normalization is fickle and gives unpredictable results based on varied font. Better to just put a 100x100px rectangle in there.

https://github.com/fullcalendar/fullcalendar-workspace/blob/main/premium/packages/scrollgrid/src/scroll-left-norm.ts#L65
