### ISSUE TITLE
Issues with calendar functionality when hosting in ServiceNow

### ISSUE THREAD

**Issue by MWDevRepo** [fullcalendar/fullcalendar#7337]
### Reduced Test Case

N/A ServiceNow Instance required 

### Do you understand that if a reduced test case is not provided, we will intentionally delay triaging of your ticket?

- [X] I understand

### Which connector are you using (React/Angular/etc)?

Angular

### Bug Description

I've been implementing the FullCalendar in ServiceNow with one big issue. 
It seems that the FullCalendar only works when I use an external CDN Link as a depedency or in a script tag on my widget (own external cdn or jsdelivr).
Any method of hosting the .js file on ServiceNow seems to break the calendar, causing errors and breaking functionality. Be it, using Script includes or a link to the .js file hosted in ServiceNow either in a script tag or as a dependency.
Eventhough I can see that the minified JS file is loading without any issues in the Network tab when I host it in ServiceNow.

**Is it required for the calendar to work that I use an external CDN instead of being able to host it locally?** 
After much debate with ServiceNow Support, they seem to think that this is the issue instead of it being on the platform end.

Version: FullCalendar Standard Bundle v6.1.4
Examples of breaking functionality:
- Missing back/dorward icons
- When switching to the year view I get the following error and I can't switch views anymore
"Uncaught TypeError: Cannot read properties of null (reading 'getBoundingClientRect')"

**Comment by acerix** [comment]
There's an example in the "zip" release that can be hosted locally: https://fullcalendar.io/docs/initialize-globals  

Please post a [runnable, stripped-down demonstration](http://fullcalendar.io/wiki/Reduced-Test-Cases/) if there is a bug. Would really appreciate it because the time saved reproducing will be time spent fixing.

**Comment by MWDevRepo** [comment]
I can offer you access to my personal developer instance in servicenow with the instructions to test the issue? Would you be interested?
