### ISSUE TITLE
Calendar tables do not utilize the caption element for accessibility

### ISSUE THREAD

**Issue by tvachon** [fullcalendar/fullcalendar#7339]
### Reduced Test Case

https://stackblitz.com/github/fullcalendar/fullcalendar-examples/tree/main/react?file=README.md

### Do you understand that if a reduced test case is not provided, we will intentionally delay triaging of your ticket?

- [X] I understand

### Which connector are you using (React/Angular/etc)?

React

### Bug Description

The tables that FullCalendar uses to lay out the calendar view do not utilize the [\<caption\> element](https://developer.mozilla.org/en-US/docs/Learn/HTML/Tables/Advanced) for accessibility. 

To check this, go to the stackblitz url above or the FullCalendar demo site, inspect and search for 'caption' in the elements tab. 

The \<caption\> element is particularly helpful for blind users who use a screen reader. Screen readers contain functionality that summarizes the content on a page. For example, Voiceover is the built in screen reader on the Mac. Voiceover's summary feature is called the 'rotor'. One view of the rotor summarizes all the tables on the page. Without the caption element, the calendar is simply read simply as 'seven columns, seven rows' (see image), which is confusing. This only informs a blind user that there is a table on the page and how large it is, but give no indication of the table's purpose or the kind of information it contains. 

If a <caption> element was added to each calendar view with some useful descriptive information to the table, e.g. 'Monthly Calendar View', then screen readers would instead read "Monthly Calendar View, seven columns, seven rows", which would provide badly needed context to blind users. It would also be helpful to provide a way to programmatically modify this caption element to make it even more descriptive depending on the calendar's context. 

![IMG_5314](https://github.com/fullcalendar/fullcalendar/assets/1612142/65c125e7-faba-4b4e-bb05-1ec85d08566e)

**Comment by acerix** [comment]
I believe this existing ticket captures this need:
https://github.com/fullcalendar/fullcalendar/issues/6637
↑
Please visit the above issue, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates.
