### ISSUE TITLE
selectable should work cross-month also, user should be able to select dates lying in two month in multimonth stack calendar

### ISSUE THREAD

**Issue by gursidak** [fullcalendar/fullcalendar#7340]
### Checklist

- [X] I've already searched through [existing tickets](https://github.com/fullcalendar/fullcalendar/issues)
- [X] Other people will find this feature useful

### Is this feature for a specific connector (React/Angular/etc)?

React

### Feature Description

User should be able to select dates ranges cross month. User should be able to select date range startting from one month and ending on some date of another month in multimonth stack view, This feature will be highly appreciated.

**Comment by acerix** [comment]
I believe this existing ticket captures this need:
https://github.com/fullcalendar/fullcalendar/issues/7183
↑
Please visit the above issue, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates.
