### ISSUE TITLE
Nested Resource parsing not maintaining source order

### ISSUE THREAD

**Issue by ajaydev12** [fullcalendar/fullcalendar#7341]
### Reduced Test Case

https://codepen.io/ajaydev12/pen/ZEqPrLY?editors=0010

### Do you understand that if a reduced test case is not provided, we will intentionally delay triaging of your ticket?

- [X] I understand

### Which connector are you using (React/Angular/etc)?

No connector (vanilla JS)

### Bug Description

When passing nested resources, the expectation is for the nested resources to maintain the same order as in source. However, child resources are rendered in random order.
`resources:[
                    {
                      "id": "80adfc17-268b-4f19-866a-6b005750aa86",
                      "title": "Parent",
                      "children": [
                        {
                          "id": "b468bf4f-111d-4653-8872-e94c17f4ed55",
                          "title": "A1"
                        },
                        {
                          "id": "4eec541f-0447-446d-967f-b37ddc39ac46",
                          "title": "A2"
                        },
                        {
                          "id": "b43015e1-4f9a-4eed-ac0c-cccc73d1e397",
                          "title": "A3"
                        }]
                    }
]`
Expect to see child resources in the following order - A1, A2, A3. The order on calendar is A1, A3, A2
![image](https://github.com/fullcalendar/fullcalendar/assets/18623004/636b04e8-86f2-43ce-8d3f-bb16f0bd62f8)

**Comment by acerix** [comment]
I believe this existing ticket captures this need:
https://github.com/fullcalendar/fullcalendar/issues/5482
↑
Please visit the above issue, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates.
