### ISSUE TITLE
The calendar doesn't work with next.js (router.push || router.replace). only work with window.location.href

### ISSUE THREAD

**Issue by AhmedFahiim** [fullcalendar/fullcalendar#7345]
### Reduced Test Case

dont have

### Do you understand that if a reduced test case is not provided, we will intentionally delay triaging of your ticket?

- [X] I understand

### Which connector are you using (React/Angular/etc)?

React

### Bug Description

when i navigate from a page to another in next.js with any method except window.location.href , the calendar is brooked and only works fine when i refresh the page either it will not work..

![fullcalendar bug](https://github.com/fullcalendar/fullcalendar/assets/104613379/64dada75-7b04-4be5-b78e-51dc9105fe5a)

**Comment by acerix** [comment]
Would you be able to post a [runnable, stripped-down demonstration of the bug](http://fullcalendar.io/wiki/Reduced-Test-Cases/)? Would really appreciate it because the time saved reproducing will be time spent fixing.
