### ISSUE TITLE
Scroll reset in month view when changing events

### ISSUE THREAD

**Issue by rloview** [fullcalendar/fullcalendar#7346]
### Reduced Test Case

Same as : https://github.com/fullcalendar/fullcalendar/issues/6634

### Do you understand that if a reduced test case is not provided, we will intentionally delay triaging of your ticket?

- [X] I understand

### Which connector are you using (React/Angular/etc)?

React

### Bug Description

I use fullcalendar v5.11.2. 
There is the following issue in this version, and It's not occur in v5.6.0.
(I can't use v5.6.0 because I also need to use scrollTimeReset which is newly added in v5.7.0)

step to reproduce
- open the dayGridMonth View
- scroll down
- change events (create/update/delete)

expected result
- the scroll remains the same position

actual result
- the scroll position is moved up to top

**Comment by acerix** [comment]
Would you be able to post a [runnable, stripped-down demonstration of the bug](http://fullcalendar.io/wiki/Reduced-Test-Cases/)? Would really appreciate it because the time saved reproducing will be time spent fixing.

**Comment by rloview** [comment]
> Would you be able to post a [runnable, stripped-down demonstration of the bug](http://fullcalendar.io/wiki/Reduced-Test-Cases/)? Would really appreciate it because the time saved reproducing will be time spent fixing.

Our site is on the internal network and cannot be accessed from the internet network. So I share the demo video.

https://github.com/fullcalendar/fullcalendar/assets/44535364/5f6af70d-b828-489c-922b-3c7bd4a0a964

We are using the <Fullcalendar /> component as below.

```
<FullCalendar
	ref={calendarRef}
	views={fullParams.views} // each view options
	firstDay={fullCalendarFirstDay}
	weekNumbers
	weekNumberContent={weekNumberContent}
	weekNumberDidMount={onWeekNumberMount}
	weekNumberWillUnmount={onWeekNumberUnmount}
	height={fullParams.height}
	eventTimeFormat={fullParams.eventTimeFormat}
	slotLabelFormat={fullParams.slotLabelFormat} // DAY view Time Format
	nowIndicator={fullParams.nowIndicator} // show current time line
	dayHeaders
	scrollTime={fullCalendarScrollTime}
	now={fullCalendarNow}
	timeZone={fullParams.timeZone}
	plugins={[dayGridPlugin, timeGridPlugin, listPlugin, interactionPlugin]}
	headerToolbar={fullParams.headerToolbar}
	initialView={isYear ? CalendarConstants.CALENDAR_VIEW.DAY : fullParams.view}
	expandRows={fullParams.isExpand}
	editable={fullParams.editable}
	selectable={fullParams.selectable}
	selectMirror={fullParams.selectMirror}
	dayMaxEvents={fullParams.dayMaxEvents}
	navLinks={fullParams.navLinks}
	navLinkDayClick={selectInfo => handleDateClick(selectInfo, true)}
	events={scheduleEvents}
	eventDidMount={eventDidMount}
	eventOrder={(a, b) => {
	  return (
	   (...something to do for ordering)
	  );
	}}
	eventClick={eventClick}
	select={handleDateClick}
	eventDrop={handleChangeDuration}
	eventDragStart={eventDragStart}
	dayCellDidMount={dayCellDidMount}
	slotLaneDidMount={slotLaneDidMount}
	dayHeaderDidMount={dayHeaderDidMount}
	dayHeaderContent={dayHeaderContent}
	dayCellContent={dayCellContent}
	viewDidMount={onViewDidmount}
	eventMouseEnter={eventMouseEnter}
	eventMouseLeave={eventMouseLeave}
	eventResizeStart={eventResizeStart}
	eventResize={handleChangeDuration}
	slotEventOverlap={false}
	scrollTimeReset={false}
	stickyHeaderDates
	dayHeaderClassNames="disable-hover"
	dayCellClassNames="disable-hover"
	eventClassNames={eventClassNames}
	nextDayThreshold="23:59:59"
/>
```

**Comment by rloview** [comment]
@acerix 
Could I know if you checked the above comment? Thanks.

**Comment by acerix** [comment]
If it's the same as in #6634 we don't need a new issue.

We would need a [runnable, stripped-down demonstration](http://fullcalendar.io/wiki/Reduced-Test-Cases/) if this is a new bug.
