### ISSUE TITLE
get error when used Calendar API 'Uncaught Error: flushSync was called from inside a lifecycle method.'

### ISSUE THREAD

**Issue by Toyota-Li** [fullcalendar/fullcalendar#7347]
### Reduced Test Case

https://fullcalendar.io/docs/Calendar-next

### Do you understand that if a reduced test case is not provided, we will intentionally delay triaging of your ticket?

- [X] I understand

### Which connector are you using (React/Angular/etc)?

React

### Bug Description

Try to used  the following code in the method
  <FullCalendar  ref={this.calendarRef}  />
someFunction(){
  this.setState({
      count: 1,
    }, () => {
      const calendarApi = this.calendarRef.current.getApi();
      calendarApi.next();
    })
}
then get   'Uncaught Error: flushSync was called from inside a lifecycle method.'

If I don't use ' setState'  just like this 
 <FullCalendar  ref={this.calendarRef}  />
someFunction(){
  const calendarApi = this.calendarRef.current.getApi();
  calendarApi.next()
}
it's ok！！！

I used  version : 6.1.8

**Comment by acerix** [comment]
Would you be able to post a [runnable, stripped-down demonstration of the bug](http://fullcalendar.io/wiki/Reduced-Test-Cases/)? Would really appreciate it because the time saved reproducing will be time spent fixing.

I don't see any error in the demo you linked.
