### ISSUE TITLE
Display all event start dates regardless of 'dayMaxEvents'

### ISSUE THREAD

**Issue by dunz** [fullcalendar/fullcalendar#7348]
### Reduced Test Case

https://codesandbox.io/s/zealous-glitter-j9ceq5?file=/src/App.tsx

### Do you understand that if a reduced test case is not provided, we will intentionally delay triaging of your ticket?

- [X] I understand

### Which connector are you using (React/Angular/etc)?

React

### Bug Description

The schedule for all events is as follows.

<img width="1130" alt="스크린샷 2023-05-30 오후 4 49 04" src="https://github.com/fullcalendar/fullcalendar/assets/25737303/ec7963ce-904e-4a87-afe6-1263e058a998">

If 'dayMaxEvents: 3' is given, the start date of event5 is hidden as below.

<img width="1134" alt="스크린샷 2023-05-30 오후 4 49 21" src="https://github.com/fullcalendar/fullcalendar/assets/25737303/e3650afa-4dcf-437c-818e-02f095669f7a">

Is there a way to keep showing only up to three events in a single date cell, but still display all start dates by allowing it to exceed three lines in case of overlap?

**Comment by acerix** [comment]
It appears to be limiting the events to 3 as expected.

I'm not sure what you mean by exceeding the lines or how you are wanting the 5th event to display, it will help if you can include a mockup of what you are looking for.

**Comment by dunz** [comment]
I have been thinking about whether it is possible to create a UI like this.

<img width="1134" alt="ui" src="https://github.com/fullcalendar/fullcalendar/assets/25737303/42393f09-f128-40c5-a3a0-e2b2bda9d181">

**Comment by acerix** [comment]
Thanks for the info.  If I understand, are you looking for the limit to be on how many events which _start_ on the same day are displayed?

**Comment by dunz** [comment]
Actually, what I initially wanted was "I wish there were no cases where the start date is not visible due to overlapping schedules." But to do so, I have to keep all overlapping parts as they are now. Then, it makes me think that the "dayMaxEvents" itself could become useless, as the line could endlessly increase. After reconsidering, I think it might be impossible.

<img width="1134" alt="ui" src="https://github.com/fullcalendar/fullcalendar/assets/25737303/aeccda89-fcd9-4751-a873-ce0684f0a36d">

**Comment by acerix** [comment]
Yes, it sounds like you don't actually want a limit on events so `dayMaxEvents` won't work for that.  I believe this existing ticket to choose which events are displayed captures this need:
https://github.com/fullcalendar/fullcalendar/issues/2965
↑
Please visit the above issue, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates.
