### ISSUE TITLE
Hover popup and click

### ISSUE THREAD

**Issue by harishksoft** [fullcalendar/fullcalendar#7358]
### Checklist

- [X] I've already searched through [existing tickets](https://github.com/fullcalendar/fullcalendar/issues)
- [X] Other people will find this feature useful

### Is this feature for a specific connector (React/Angular/etc)?

No connector in particular

### Feature Description

i would like an option like when user mouse scroll over event, need to show event details in a popup (not popover). the poup should contain an option to show image also.

this is link to some mokeup design which i need https://snipboard.io/I5OSUs.jpg

**Comment by acerix** [comment]
I believe this existing ticket captures this need:
https://github.com/fullcalendar/fullcalendar/issues/5942
↑
Please visit the above issue, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates.

**Comment by harishksoft** [comment]
no solution at all in the existing ticket.
