### ISSUE TITLE
Include times in event.range in custom views

### ISSUE THREAD

**Issue by white3km** [fullcalendar/fullcalendar#7362]
### Reduced Test Case

https://stackblitz.com/edit/github-woxsdv-wzpgz5?file=src%2Fevent-utils.js

### Do you understand that if a reduced test case is not provided, we will intentionally delay triaging of your ticket?

- [X] I understand

### Which connector are you using (React/Angular/etc)?

React

### Bug Description

I'm trying to migrate from version 5 to version 6 but I've noticed an issue that breaks some of our existing custom views. Previously the dates returned from event.range included time but after updating I've found that start and end dates are not including time but are being treated similar to full day (00:00).

Incoming Event dates:
start: 2023-06-05T12:00:00
end:  2023-06-05T18:00:00

Event.Range
start: 2023-06-05T00:00:00.000Z
end: 2023-06-06T00:00:00.000Z

My test case is forked off a previous ticket (js) but I'm seeing this issue in the react connector as well.  
To reproduce go to test case and click on custom year view.
Dates listed don't include time instead they are zeroed out.
![image](https://github.com/fullcalendar/fullcalendar/assets/58864197/4a5e2cb3-9acb-4d2a-a600-afb6135325b1)

**Comment by acerix** [comment]
I couldn't find any reference to `event.range` in the docs so I'm not sure it's a bug that the time is missing there.  It seems to me using "00:00" to align to timeslots of 1 day may be preferred.

It will help if you can share the use case or what is breaking by not having the time.

**Comment by white3km** [comment]
So I have no idea why this worked for us previously with true but I realized the source of my problem is the sliceEvents:

const events = sliceEvents(props, **true**);

I'm passing in true and it's slicing everything up as full day (00:00). If I toggle this to false then I get the actual times :man_facepalming:
