### ISSUE TITLE
`eventClick` does not fire for allDay events with async provided resources

### ISSUE THREAD

**Issue by sirkosi** [fullcalendar/fullcalendar#7365]
### Reduced Test Case

https://codepen.io/sirsir1/pen/dyQyomE

### Do you understand that if a reduced test case is not provided, we will intentionally delay triaging of your ticket?

- [X] I understand

### Which connector are you using (React/Angular/etc)?

No connector (vanilla JS)

### Bug Description

When loading resources asynchronously, the allDay events are not clickable.

Please see also the same Test case with static resources where the `eventClick` works properly: https://codepen.io/sirsir1/pen/LYXPQRq

**Comment by acerix** [comment]
Thanks, confirmed.

It seems to also make the event darker as if it was selected by touch for dragging.  Here is my test case: 

https://codepen.io/acerix/pen/oNQgvJV?editors=0010

I couldn't find any workaround besides static resources, using a JSON feed has the same issue:

https://codepen.io/acerix/pen/RwqNwPP

**Comment by michalfordonski** [comment]
I'll join in: it's the same for me and Drag&Drop from allDay for an hour and from hour to allDay doesn't work for me, resources are downloaded from JSON.

**Comment by michalfordonski** [comment]
@acerix @arshaw Is anything known about it? When can we expect a patch/update?

**Comment by arshaw** [comment]
@michalfordonski , I'll have a bugfix release by end of this week

**Comment by arshaw** [comment]
This is fixed in [v6.1.9](https://github.com/fullcalendar/fullcalendar/releases/tag/v6.1.9)

Updated repro:
https://codepen.io/arshaw/pen/rNopRKY
