### ISSUE TITLE
Docs for pushing events into online calendars googlecalendar, applecalendar, outlookcalendar

### ISSUE THREAD

**Issue by sridharrajaram** [fullcalendar/fullcalendar#7369]
### Checklist

- [X] I've already searched through [existing tickets](https://github.com/fullcalendar/fullcalendar/issues)
- [X] Other people will find this feature useful

### Is this feature for a specific connector (React/Angular/etc)?

React

### Feature Description

Hi Adam,

I am very fond of using @fullcalendar/react NPM package. I am finding very difficult to push @fullcalendar events into popular calendar like google calendar, apple calendar or say outlook ms calendar. even going through google docs or apple docs, i have not successfully inserted the events. I see lot of people are giving how to pull data from other popular calendar to their application but i wanna the reverse part. If you give us feature like googlePushEventPlugin/ApplePushEventPlugin which will be very helpful.

**Comment by acerix** [comment]
There are callbacks such as [eventAdd](https://fullcalendar.io/docs/eventAdd) from where you could push events to another calendar.  If I understand, you looking for docs/examples for using that to push events to an online calendar?

**Comment by sridharrajaram** [comment]
Hi Dylan,

Good morning, yes but I am looking for auto sync of only daily events into online calendar. Also there is no proper docs for apple icalendar or outlook calendar

Get Outlook for Android<https://aka.ms/AAb9ysg>

________________________________
