### ISSUE TITLE
Added guard to component and returned error

### ISSUE THREAD

**Issue by licerog** [fullcalendar/fullcalendar#7372]
### Reduced Test Case

n/a

### Do you understand that if a reduced test case is not provided, we will intentionally delay triaging of your ticket?

- [X] I understand

### Which connector are you using (React/Angular/etc)?

Angular

### Bug Description

Error: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
    at OffscreenFragmentComponent.ngOnDestroy (fullcalendar-angular.mjs:108:26)

**Comment by acerix** [comment]
Would you be able to post a [runnable, stripped-down demonstration of the bug](http://fullcalendar.io/wiki/Reduced-Test-Cases/)? Would really appreciate it because the time saved reproducing will be time spent fixing.
