### ISSUE TITLE
add week days trnanslation for kk

### ISSUE THREAD

**Issue by WOlfy155** [fullcalendar/fullcalendar#7373]
### Checklist

- [X] I've already searched through [existing tickets](https://github.com/fullcalendar/fullcalendar/issues)
- [X] Other people will find this feature useful

### Is this feature for a specific connector (React/Angular/etc)?

No connector in particular

### Feature Description

![image](https://github.com/fullcalendar/fullcalendar/assets/55805167/1e5ab176-e35a-4878-ae96-f3017aec7a84)

there are no translation for week days in kk locale 

is there a way to add custom translations ?

**Comment by acerix** [comment]
It works for me in this demo:

https://fullcalendar.io/docs/locale-demo

The translations are handled by the browser, so if that demo is not translated for you, it means your browser or OS is missing support, in which case you can use a plugin which is more compatible:

https://fullcalendar.io/docs/moment-plugins
