### ISSUE TITLE
multiMonthYear and validRange option

### ISSUE THREAD

**Issue by Sauron-Dev** [fullcalendar/fullcalendar#7374]
### Reduced Test Case

https://codepen.io/sauron-dev/pen/xxQGoMe

### Do you understand that if a reduced test case is not provided, we will intentionally delay triaging of your ticket?

- [X] I understand

### Which connector are you using (React/Angular/etc)?

No connector (vanilla JS)

### Bug Description

I've run into an issue where FullCalendar will stop working if I am using the "multiMonthYear" view in combination with ValidRange option.

See following [Codepen](https://codepen.io/sauron-dev/pen/xxQGoMe)

```
document.addEventListener("DOMContentLoaded", function () {
  var calendarEl = document.getElementById("calendar");

  var calendar = new FullCalendar.Calendar(calendarEl, {
    initialView: "dayGridMonth",
    initialDate: "2023-05-07",
    headerToolbar: {
      left: "prev,next today",
      center: "title",
      right: "dayGridMonth,timeGridWeek,timeGridDay,multiMonthYear"
    },
    validRange: {
      start: "2023-04-01",
      end: "2024-03-31"
    },
    events: [
      {
        title: "All Day Event",
        start: "2023-05-01"
      },
      {
        title: "Long Event",
        start: "2023-05-07",
        end: "2023-05-10"
      },
      {
        groupId: "999",
        title: "Repeating Event",
        start: "2023-05-09T16:00:00"
      },
      {
        groupId: "999",
        title: "Repeating Event",
        start: "2023-05-16T16:00:00"
      },
      {
        title: "Conference",
        start: "2023-05-11",
        end: "2023-05-13"
      },
      {
        title: "Meeting",
        start: "2023-05-12T10:30:00",
        end: "2023-05-12T12:30:00"
      },
      {
        title: "Lunch",
        start: "2023-05-12T12:00:00"
      },
      {
        title: "Meeting",
        start: "2023-05-12T14:30:00"
      },
      {
        title: "Birthday Party",
        start: "2023-05-13T07:00:00"
      },
      {
        title: "Click for Google",
        url: "http://google.com/",
        start: "2023-05-28"
      }
    ]
  });

  calendar.render();
});
```

If you have the validRange option the view "year" (multiMonthYear) is not selectable it will not load. If you comment that out it will work.

Does anyone have an idea? Thanks in advance!

**Comment by acerix** [comment]
I believe this existing ticket captures this need:
https://github.com/fullcalendar/fullcalendar/issues/7287
↑
Please visit the above issue, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates.
