### ISSUE TITLE
initialDate works on desktop but not on mobile

### ISSUE THREAD

**Issue by Highfire1** [fullcalendar/fullcalendar#7375]
### Reduced Test Case

https://codepen.io/Highfire1/pen/zYMvyYM?editors=001

### Do you understand that if a reduced test case is not provided, we will intentionally delay triaging of your ticket?

- [X] I understand

### Which connector are you using (React/Angular/etc)?

No connector (vanilla JS)

### Bug Description

Hi!

I found this weird behaviour in which FullCalendar works fine on desktop, but doesn't work on mobile.

If you set an `initialDate` of `new Date(new Date("2023-9-05").getTime() + 604800000)`, it will work on desktop, but error on mobile, with the error `TypeError: null is not an object (evaluating 'e.getUTCFullYear')`

(tested firefox and edge on windows 11, and firefox and chrome on ios)

For some reason, setting `d = "2023-09-05"` instead of `d="2023-9-05"` fixes the problem, but they seem to parse to the same thing so I am not sure where the problem comes from.

Thank you!

![image](https://github.com/fullcalendar/fullcalendar/assets/45698812/72fb1baf-1f29-4617-891e-d64432bb2856)
![IMG_6213](https://github.com/fullcalendar/fullcalendar/assets/45698812/59c3faad-0072-441b-96fb-93922485d875)

**Comment by acerix** [comment]
The date needs to be in ISO format like "2023-09-05", "2023-9-05" is not valid. That's likely handled differently based on the browser which is why it sometimes works.
