### ISSUE TITLE
resourceTimelineDay events that span full row height

### ISSUE THREAD

**Issue by raizemm** [fullcalendar/fullcalendar#7383]
### Checklist

- [X] I've already searched through [existing tickets](https://github.com/fullcalendar/fullcalendar/issues)
- [X] Other people will find this feature useful

### Is this feature for a specific connector (React/Angular/etc)?

No connector in particular

### Feature Description

Using resourceTimelineDay view type I'm trying to make events span full height of the grid row.
I've tried to do that using provided options for the calendar and events but had no luck in making it right but maybe I'm missing something.
The view that I'm trying to create would look similar to this:

![image](https://github.com/fullcalendar/fullcalendar/assets/8191603/ec803839-b0d5-464e-8e00-ac72617d97a0)

**Comment by acerix** [comment]
I believe this existing ticket captures this need:
https://github.com/fullcalendar/fullcalendar/issues/7359
↑
Please visit the above issue, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates.
