### ISSUE TITLE
Angular 16

### ISSUE THREAD

**Issue by timrasche** [fullcalendar/fullcalendar#7384]
### Reduced Test Case

-

### Do you understand that if a reduced test case is not provided, we will intentionally delay triaging of your ticket?

- [X] I understand

### Which connector are you using (React/Angular/etc)?

Angular

### Bug Description

1. Wrong peer dependencies 
2. Errors showing up after upgrade (this is referenced to (think so) timeline resource (payed version!))
For example:
- error TS2339: Property 'newResource' does not exist on type 'EventDropArg'
- error TS2551: Property 'getResourceById' does not exist on type 'Calendar'
- error TS2339: Property 'addResource' does not exist on type 'Calendar'
- Object literal may only specify known properties, and 'resourceAreaWidth' does not exist in type 'CalendarOptions'

**Comment by acerix** [comment]
I believe this existing ticket captures this need:
https://github.com/fullcalendar/fullcalendar/issues/7122
↑
Please visit the above issue, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates.
