### ISSUE TITLE
Option to not autosize heights of day cells

### ISSUE THREAD

**Issue by davidyeeprocore1** [fullcalendar/fullcalendar#7385]
### Checklist

- [X] I've already searched through [existing tickets](https://github.com/fullcalendar/fullcalendar/issues)
- [X] Other people will find this feature useful

### Is this feature for a specific connector (React/Angular/etc)?

React

### Feature Description

Provide an option to **not** resize the height of day cells in the monthly calendar view. Currently, when data is added to calendar day cells, the cell autosizes its height which results in some very tall rows and very short rows. It would be great to provide an option to not perform this autosizing. 

The first row is much taller than the second.
<img width="1698" alt="Screen Shot 2023-06-22 at 12 32 27 PM" src="https://github.com/fullcalendar/fullcalendar/assets/100789438/0ed79cd4-aed9-4b53-8e76-6cfe4308a413">

However, in the demo, the day cell heights are not growing in height. We would like to see this behavior as well.

<img width="1035" alt="Screen Shot 2023-06-22 at 12 32 57 PM" src="https://github.com/fullcalendar/fullcalendar/assets/100789438/9bbad7fc-c197-4c60-8147-815d1ac16662">

**Comment by acerix** [comment]
I believe this existing ticket captures this need:
https://github.com/fullcalendar/fullcalendar/issues/5762
↑
Please visit the above issue, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates.
