### ISSUE TITLE
resourceTimeGridDay event cannot  be dragged on Modal or Drawer 

### ISSUE THREAD

**Issue by aslkami** [fullcalendar/fullcalendar#7386]
### Reduced Test Case

https://stackblitz.com/edit/github-1nbomv-qsmcpz?file=package.json,src%2FDemoApp.jsx,src%2FCalendar.jsx,src%2Fmain.css,src%2Fevent-utils.js

### Do you understand that if a reduced test case is not provided, we will intentionally delay triaging of your ticket?

- [X] I understand

### Which connector are you using (React/Angular/etc)?

React

### Bug Description

When I experienced resourceTimeGridDay view, I found a problem,  if my page exists one calendar, the calendar events can be dragged. However, if page exist two calendar, such as open on Modal or Drawer,  The calendar which is open on Modal or Drawer, events can not be dragged, just can expand on then event bottom

dependencies  versions:

```json
 "dependencies": {
    "@fullcalendar/core": "^5.11.5",
    "@fullcalendar/daygrid": "^5.11.5",
    "@fullcalendar/interaction": "^5.11.5",
    "@fullcalendar/react": "^5.11.5",
    "@fullcalendar/resource-timegrid": "^5.11.5",
    "@fullcalendar/timegrid": "^5.11.5",
    "antd": "^4.20.0",
    "dayjs": "^1.11.8",
    "react": "^18.0.0",
    "react-dom": "^18.0.0"
  },
```

I look forward to hearing from you soon， thanks

**Comment by acerix** [comment]
I believe this existing ticket captures this need:
https://github.com/fullcalendar/fullcalendar/issues/5026
↑
Please visit the above issue, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates.
