### ISSUE TITLE
all but one events disappear in resourcetimeline when data changes

### ISSUE THREAD

**Issue by mnooblet** [fullcalendar/fullcalendar#7391]
### Reduced Test Case

donthaveone

### Do you understand that if a reduced test case is not provided, we will intentionally delay triaging of your ticket?

- [X] I understand

### Which connector are you using (React/Angular/etc)?

Vue

### Bug Description

I just tried to upgrade to the latest version but went back to 5.10 because when the underlying start or end date of an event changes all but one events disappear from the resourcetimelineview.

I'm back to  using fullcalendar/vue": "^5.10.1, here it still works.

**Comment by acerix** [comment]
Would you be able to post a [runnable, stripped-down demonstration of the bug](http://fullcalendar.io/wiki/Reduced-Test-Cases/)? Would really appreciate it because the time saved reproducing will be time spent fixing.
