### ISSUE TITLE
`navLinkDayClick` not supported for "resourceTimelineWeek" view, and has unexpected default behaviour

### ISSUE THREAD

**Issue by Cipscis** [fullcalendar/fullcalendar#7392]
### Reduced Test Case

https://codepen.io/Cipscis/pen/zYMzazK

### Do you understand that if a reduced test case is not provided, we will intentionally delay triaging of your ticket?

- [X] I understand

### Which connector are you using (React/Angular/etc)?

No connector (vanilla JS)

### Bug Description

# Background

When [`navLinks`](https://fullcalendar.io/docs/navLinks) is set to `true`, various views turn column headings for particular dates into clickable elements that can be used to move to a day view for the clicked date.

The behaviour of these nav links for specific days, when they are enabled, can be customised via [`navLinkDayClick`](https://fullcalendar.io/docs/navLinkDayClick).

# The Problem

For the "resourceTimelineWeek" view, these two behaviours aren't doing what I would expect from the documentation. I first encountered this when using the React connector, but have replicated it without a connector (see [my reduced test case](https://codepen.io/Cipscis/pen/zYMzazK) on CodePen)

If a custom function is set for `navLinkDayClick`, when clicking on a function nav link for a day in the "resourceTimelineWeek" view that custom function is not called. Instead, the nav link's default behaviour runs.

However, this default behaviour is also unexpected. In other views, the default behaviour is to transition to an equivalent view for a single day, and change the date to the clicked date. However, when clicked in the "resourceTimelineWeek" view, clicking on one of these nav links instead moves the calendar to a month view.

I've also tried seeing if the [`navLinkWeekClick`](https://fullcalendar.io/docs/navLinkWeekClick) function is called in this case, but it doesn't seem to be.

# Expected Behaviour

I would expect the default behaviour for clicking on one of these nav links in the "resourceTimelineWeek" view to be to change the calendar to a day view for the clicked day.

Also, if a `navLinkDayClick` function is set, I would expect that function to be called instead of the default behaviour.

**Comment by acerix** [comment]
I believe this existing ticket captures this need:
https://github.com/fullcalendar/fullcalendar/issues/4931
↑
Please visit the above issue, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates.
