### ISSUE TITLE
时区设置为zh-cn 如何隐藏后面的 "周" ，"日"，这种后缀 

### ISSUE THREAD

**Issue by ProCheng** [fullcalendar/fullcalendar#7393]
### Checklist

- [X] I've already searched through [existing tickets](https://github.com/fullcalendar/fullcalendar/issues)
- [X] Other people will find this feature useful

### Is this feature for a specific connector (React/Angular/etc)?

No connector in particular

### Feature Description

时区设置为zh-cn 如何隐藏后面的 "周" ，"日"，这种后缀

**Comment by javaswing** [comment]
兄弟，你可以给一个在线的代码例子。没有太理解你的意思，你是想这样吗？
![image](https://github.com/fullcalendar/fullcalendar/assets/7713463/0a79493f-ea7f-4cd8-9fdd-ac4005f1b4eb)

**Comment by javaswing** [comment]
> 对的是这种

see this link: https://codesandbox.io/s/react-typescript-fullcalendar-example-calendar-01-forked-r4y4js?file=/src/BigCalendar.tsx

**Comment by ProCheng** [comment]
感谢，这个问题我已经解决了，想实现这种效果
![image](https://github.com/fullcalendar/fullcalendar/assets/48340426/bc94ba75-b8b3-46b0-98ff-6c81fba84dfe)

**Comment by javaswing** [comment]
> 感谢，这个问题我已经解决了，想实现这种效果 ![image](https://user-images.githubusercontent.com/48340426/252539363-bc94ba75-b8b3-46b0-98ff-6c81fba84dfe.png)

<img width="871" alt="image" src="https://github.com/fullcalendar/fullcalendar/assets/7713463/56786459-35a0-453a-bd05-bcb1ec23a832">
地址还是上面的那个。
 CSS 样式部分，这个库是基于css变量的，看这里https://fullcalendar.io/docs/css-customization

**Comment by ProCheng** [comment]
非常感谢您
