### ISSUE TITLE
Days are being mounted only once and not redrawn on month change - even with showNonCurrentDates set to false

### ISSUE THREAD

**Issue by MatthewNewportRI** [fullcalendar/fullcalendar#7396]
### Reduced Test Case

https://codepen.io/vulgar/pen/zYMEGzx?editors=0010

### Do you understand that if a reduced test case is not provided, we will intentionally delay triaging of your ticket?

- [X] I understand

### Which connector are you using (React/Angular/etc)?

No connector (vanilla JS)

### Bug Description

In the event that I need to modify the display of a dayCell using dayCellDidMount, if the cell was rendered on the previous month, it is not being re-rendered (not re-applying the modification) on the change of months, even if showNonCurrentDates is set to false. 

In my provided example I created a simple function called `isFirstOrLastDay()` that simply returns whether or not the passed date is the first or last day of the month.

In `dayCellDidMount()` I am applying the `fc-day-disabled` class to the element if the return of `isFirstOrLastDay()` is true.

**The Issue**
Using June 2023 as my example (any month will work), when the calendar loads it is running dayCellDidMount for any day that has a spot on the calendar - even if showNonCurrentDates is set to false. You can see in the below screen shot it is setting disable class for June 30th as well as July 1st (last and first day of the month).

![CleanShot 2023-07-06 at 10 14 10](https://github.com/fullcalendar/fullcalendar/assets/126618635/1bc4f1cc-5bf8-4273-a391-2a9a3304e8c5)

The bigger issue is that when I now progress to July, that modification does not carry over as it is not re-applying the dayCellDidMount modifications to July 1st. So though it is being modified (`fc-day-disabled` being applied), it is doing so only on the initial load of that spot on the calendar (in June), and not re-rendering when the month progresses to July. (You can see July 1 is only present once in the logs)

![CleanShot 2023-07-06 at 10 19 20](https://github.com/fullcalendar/fullcalendar/assets/126618635/dcf8b887-a132-4df9-be41-ebedbba19ee2)

![CleanShot 2023-07-06 at 10 19 08](https://github.com/fullcalendar/fullcalendar/assets/126618635/d2fbc69b-a345-460c-9311-da196ca5ca25)

Now, if I progress to August, the same issue is apparent. If I progress back to July, I can now see the cell being disabled appropriately (because July 1st was not present on the August calendar) but July 31st now does not have the disabled class present as it was taking a spot on the August calendar.

![CleanShot 2023-07-06 at 10 27 14](https://github.com/fullcalendar/fullcalendar/assets/126618635/ff940625-a5bd-46b3-b917-df93702065c6)

**Recommendation** _if it makes any sense_
dayCellDidMount should not be run on the calendar dates that are not shown when showNonCurrentDates is false. Also, dayCellDidMount should rerun (or have a dayCellDidRemount - or similar function) when showNonCurrentDates is true, to re-apply any modifications done to the element.

**Comment by MatthewNewportRI** [comment]
I apologize. After my further research I was able to find dayCellClassNames and that solved my issue. Thank you

**Comment by zhengyu997** [comment]
How did you solve it

**Comment by jsodeman** [comment]
@MatthewNewportRI I know this is an old issue but we've encountered the same problem. Do you recall how dayCellClassNames was useful in solving the problem? On the surface it doesn't seem like it would be related to re-rendering.
