### ISSUE TITLE
m.getUTCHours is not a function

### ISSUE THREAD

**Issue by jziggas** [fullcalendar/fullcalendar#7397]
### Reduced Test Case

https://stackblitz.com/edit/angular-ivy-endvu6?file=src%2Fapp%2Fapp.module.ts

### Do you understand that if a reduced test case is not provided, we will intentionally delay triaging of your ticket?

- [X] I understand

### Which connector are you using (React/Angular/etc)?

Angular

### Bug Description

I actually can't seem to reproduce this in a StackBlitz yet, though I've tried. But I was able to find where the issue is occuring when stepping through breakpoints. For some reason there is an object that is *not a Date object* being passed into `timeAsMs()` of `internal-common.js`:

<img width="529" alt="image" src="https://github.com/fullcalendar/fullcalendar/assets/1485767/6119c838-bce1-4148-a74c-5eff4936c05d">

Which is causing an error to be thrown and the calendar to stop rendering. I am submitting a GH issue anyway in case someone with a better understanding of the FullCalendar internals might know what is happening or why. 

I attached a StackBlitz although it does not currently reproduce the issue for some reason. I'm very confused since the package versions are the same and there is nothing else obvious that would be affecting the calendar component. I will continue for a little while trying to provide a reproduction.

```
"@fullcalendar/angular": "^6.1.8",
 "@fullcalendar/core": "^6.1.8",
 "@fullcalendar/daygrid": "^6.1.8",
 "@fullcalendar/list": "^6.1.8",
 "@fullcalendar/luxon3": "^6.1.8",
 "@fullcalendar/rrule": "^6.1.8",
 "@fullcalendar/timegrid": "^6.1.8",
 ```

**Comment by jziggas** [comment]
The problems stops occuring once I uninstall `"@fullcalendar/luxon3": "^6.1.8",`

**Comment by acerix** [comment]
We would need a [runnable, stripped-down demonstration of the bug](http://fullcalendar.io/wiki/Reduced-Test-Cases/) to look into it.  It might help to delete your local package cache and reinstall the calendar packages.
