### ISSUE TITLE
Definição de minTime e maxTime

### ISSUE THREAD

**Issue by Empresass** [fullcalendar/fullcalendar#7398]
### Checklist

- [X] I've already searched through [existing tickets](https://github.com/fullcalendar/fullcalendar/issues)
- [X] Other people will find this feature useful

### Is this feature for a specific connector (React/Angular/etc)?

Other

### Feature Description

Create the possibility to define two periods of minTime and maxTime in the calendar month. For example, I need to define a period for the morning and another for the afternoon, because if I don't do it, the start times of the afternoon events don't start correctly. Let me explain: I want the slotDuration to be 45 minutes, both in the morning and in the afternoon. In the morning, as it starts at 10:30 am and ends at 12:00 pm, the slotDuration of 45 minutes works correctly, but in the afternoon, to work correctly, the events should start at 2:15 pm, but in my case it starts at 2:30 pm , so the slotDuration is never at the correct time.

**Comment by acerix** [comment]
I believe this existing ticket captures this need:
https://github.com/fullcalendar/fullcalendar/issues/5224
↑
Please visit the above issue, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates.
