### ISSUE TITLE
getResources does not appear on event as documented

### ISSUE THREAD

**Issue by inthegarage** [fullcalendar/fullcalendar#7399]
### Reduced Test Case

https://stackblitz.com/edit/github-wnvcxr?file=src%2Fapp%2Fapp.component.ts

### Do you understand that if a reduced test case is not provided, we will intentionally delay triaging of your ticket?

- [X] I understand

### Which connector are you using (React/Angular/etc)?

Angular

### Bug Description

When using the example documented here:

https://fullcalendar.io/docs/Event-getResources

I get a compilation error saying getResources is not longer available:

The code that is causing me an issue:

```
 ngOnInit(): void {
    let event = this.cal.getEventById('1');
   // This line                               here
    let resources = event?.getResources();

  }
```

What is the correct procedure to get resources? Please follow the stackblitz for further information. We have some legacy code which was working under NG14, but is now broken under NG15 due to the fact getResources is no longer available on eventAPI or eventImpl.

**Comment by inthegarage** [comment]
Seemed the project upgrade didn't take in the new resources package.
The error has been removed by adding that "@fullcalendar/resource".

Closed.

**Comment by LeoZandvliet** [comment]
@arshaw 
in the [distributed release of v5.11.5](https://github.com/fullcalendar/fullcalendar-workspace/releases/tag/v5.11.5) I can't seem to find anything like the above mentioned function. Should it be in that version too?
I'm unable to use a newer version of the library (please don't ask why :) ).

I created a codepen with the distributed v5.11.5 with a call to `getResources()`:
https://codepen.io/lzandvliet/pen/rNXvjvz?editors=1111
