### ISSUE TITLE
Calendar does not correctly limit events to fit in the cell after changing date with React strict mode

### ISSUE THREAD

**Issue by gfrn** [fullcalendar/fullcalendar#7400]
### Reduced Test Case

https://codepen.io/gfrn/pen/poQaJow

### Do you understand that if a reduced test case is not provided, we will intentionally delay triaging of your ticket?

- [X] I understand

### Which connector are you using (React/Angular/etc)?

React

### Bug Description

**Reproduction:**

0. Confirm you have React strict mode enabled
1. Go back a month (in this case, to June, from July)
2. Confirm list of custom event content items overflows beyond the day's box (all items are displayed regardless of the size of the actual container)
3. Resizing the page once fixes this behaviour

![image](https://github.com/fullcalendar/fullcalendar/assets/12566585/5e36060f-dc34-41d9-9ec2-62f5b6924c8e)

**Expected behaviour:**

Day grid box should not display all items if they do not fit; a "more events" button should be displayed instead

![image](https://github.com/fullcalendar/fullcalendar/assets/12566585/6f2a5c61-bb9a-45f9-9d18-f29bbc8ea5cb)

**Description**

Enabling strict mode breaks rendering custom content, as they are no longer taken into consideration for determining whether or not the number of displayed items should be limited. Instead, all items are displayed, and they overflow beyond the boundaries of calendar dates.

This does not occur outside strict mode.

**Comment by arshaw** [comment]
Fixed in [v6.1.11](https://github.com/fullcalendar/fullcalendar/releases/tag/v6.1.11)

@fullcalendar/react was getting tripped up on React strict-mode.

Updated repro:
https://codepen.io/arshaw/pen/LYavmom?editors=1010
