### ISSUE TITLE
Specifying timezone incorrectly adds offset to Date instances and shows events at wrong time

### ISSUE THREAD

**Issue by joe-at-shipwell** [fullcalendar/fullcalendar#7402]
### Reduced Test Case

https://stackblitz.com/edit/github-q7ktnx?file=src%2FDemoApp.jsx

### Do you understand that if a reduced test case is not provided, we will intentionally delay triaging of your ticket?

- [X] I understand

### Which connector are you using (React/Angular/etc)?

React

### Bug Description

I am handing events to Full Calendar that specify `start` and `end` as `Date` object instances. Internally, `Date` instances track time in UTC milliseconds since the epoc. They already account for timezone. I need to be able to specify the timezone so that I don't have to write an essay of a comment about how to work around this bug in our code base. Right now, appointments that have a start date of noon CDT, with the timezone set to CDT, show at 5pm. A `Date` instance should always be treated as UTC.

**Comment by acerix** [comment]
The Date objects in the calender use "UTC-coercion" so you would need to offset by the timezone to use those directly, or you can just specify the dates as a string and use `toISOString()` to convert them back. 

https://fullcalendar.io/docs/timeZone#UTC-coercion
