### ISSUE TITLE
Jquery Conflict

### ISSUE THREAD

**Issue by fre2mansur** [fullcalendar/fullcalendar#7404]
### Reduced Test Case

https://codepen.io/fre2mansur/pen/eYQrPEW?editors=1111

### Do you understand that if a reduced test case is not provided, we will intentionally delay triaging of your ticket?

- [X] I understand

### Which connector are you using (React/Angular/etc)?

No connector (vanilla JS)

### Bug Description

I need to use jquery,  it seems there is a conflict
check the browser console in  my codepen
![image](https://github.com/fullcalendar/fullcalendar/assets/8459473/3c609b3a-5034-4d4d-9a98-f3b58be26cdf)

**Comment by acerix** [comment]
The error is not from jQuery, the issue is the "until" is not a valid date: `UNTIL=202520601` and also you don't need `plugins` setting anymore.

https://codepen.io/acerix/pen/JjeBXbN?editors=1111
