### ISSUE TITLE
Inter-day booking hours

### ISSUE THREAD

**Issue by michalfordonski** [fullcalendar/fullcalendar#7406]
### Reduced Test Case

https://codepen.io/michalf29694/pen/VwVxNzW?editors=001

### Do you understand that if a reduced test case is not provided, we will intentionally delay triaging of your ticket?

- [X] I understand

### Which connector are you using (React/Angular/etc)?

No connector (vanilla JS)

### Bug Description

Inter-day bookings (e.g. 23:00-01:00) show the start day as 23:00-00:00 and the end day as 00:00-01:00, and should both days 23:00-01:00

**Comment by acerix** [comment]
I believe this existing ticket captures this need:
https://github.com/fullcalendar/fullcalendar/issues/3038
↑
Please visit the above issue, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates.
