### ISSUE TITLE
Multi-day, all-day event not spanning days on calendar

### ISSUE THREAD

**Issue by stbenjam** [fullcalendar/fullcalendar#7413]
### Reduced Test Case

https://stackblitz.com/edit/react-fullcalendar-nfnqgz?file=index.tsx

### Do you understand that if a reduced test case is not provided, we will intentionally delay triaging of your ticket?

- [X] I understand

### Which connector are you using (React/Angular/etc)?

React

### Bug Description

I have an events setup like this:

```
const events = [{"title":"Event should span 2 days","start":"2023-07-24T14:36:57-04:00","end":"2023-07-25T19:59:59-04:00","allDay":true}]
```

When rendering a calendar using the above, it only shows the event on 7/24, and not 7/25 as well. I see from the docs https://fullcalendar.io/docs/allDayMaintainDuration that the date is rounded down - is there a way to change that behavior?

![Screenshot from 2023-07-25 10-45-36](https://github.com/fullcalendar/fullcalendar/assets/429763/59d1f7d2-f8aa-4fa1-90da-7e486618501a)

**Comment by acerix** [comment]
The `allDay` setting on the event will ignore the time of the end date, so this makes the event end at "2023-07-25T00:00:00" which is why it doesn't show on the day of the 25th (the calendar uses _exclusive_ end times).  If you remove the `allDay` it shows on both days.

**Comment by stbenjam** [comment]
Thanks I found the note in the docs about the rounding and just ended up fixing this in my API so it rounds up.  Removing allDay isn't the behavior I want, all day and hourly events are displayed very differently.
