### ISSUE TITLE
Dual Time Zone Display

### ISSUE THREAD

**Issue by harelcoman** [fullcalendar/fullcalendar#7416]
### Checklist

- [X] I've already searched through [existing tickets](https://github.com/fullcalendar/fullcalendar/issues)
- [X] Other people will find this feature useful

### Is this feature for a specific connector (React/Angular/etc)?

No connector in particular

### Feature Description

Dear FullCalendar Maintainers,

I hope this message finds you well. I am reaching out to propose a new feature for FullCalendar that, I believe, could significantly enhance its usability for many users around the world.

Feature Description:

As an international user, I frequently work across different time zones. This feature I am proposing is the ability to display two time zones simultaneously on the calendar, similar to what Google Calendar offers. The dual time zone feature would allow users to compare and contrast their schedule with that of another time zone.

Use Case:

This feature would be particularly beneficial for users coordinating meetings or events across time zones. The ability to visualize two time zones at once would reduce confusion and make planning more efficient.

Implementation Suggestions:

The secondary time zone could be displayed in a less dominant color or as a thin line adjacent to the primary time zone. Users should have the option to select the second time zone from a drop-down menu, just like the primary one.

Benefits:

I am confident that the addition of this feature would provide significant benefits:

Increased convenience for users: The ability to simultaneously see two time zones would greatly aid planning and coordination for individuals and organizations working across different geographical areas.

Competitive Advantage: This feature is already available in Google Calendar, and including it in FullCalendar would put the library on par with such prominent tools.

User Friendliness: This addition would enhance the user-friendliness and versatility of FullCalendar, attracting a wider audience.

I hope you will consider this proposal and I am happy to provide any additional information you may require. Please let me know if there's a more formal process I should follow to propose new features.

Thank you for your time and consideration.

Best Regards,

Harel Coman

**Comment by harelcoman** [comment]
This is what I did for now:

```
  
const handleViewDidMount = () => {
        // Select the table header element, create a custom label with GMT offset, and prepend it to the header
        const thElement = document.querySelector('.fc-timegrid-axis')
        if (thElement && !thElement.getAttribute('data-custom-label')) {
            thElement.setAttribute('data-custom-label', 'true')
            const div = document.createElement('div')
            div.textContent = `GMT ${customerGMTOffset}`
            div.className = 'fc-col-header-cell-cushion'
            thElement.prepend(div)
        }
    }
    
```
    
```
      slotLabelFormat={(info) => {
                    const customerTime = moment(info.date)
                    const customerTimePlusDiff = customerTime
                        .clone()
                        .add(differenceInHours, 'hours')
                        .format('ha')

                    return `${customerTime.format('ha')} (${customerTimePlusDiff})`
                }}
         viewDidMount={handleViewDidMount}
       
```
       
       
![Screenshot 2023-08-06 at 17 28 58](https://github.com/fullcalendar/fullcalendar/assets/135521537/9a095bf2-c648-4570-8191-06c549825187)

**Comment by acerix** [comment]
I believe this existing ticket captures this need:
https://github.com/fullcalendar/fullcalendar/issues/3964
↑
Please visit the above issue, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates.
