### ISSUE TITLE
Automatic navigation of the x-axis scroll to a particular day in Month view when we click on today button

### ISSUE THREAD

**Issue by ananthu0105** [fullcalendar/fullcalendar#7417]
### Checklist

- [X] I've already searched through [existing tickets](https://github.com/fullcalendar/fullcalendar/issues)
- [X] Other people will find this feature useful

### Is this feature for a specific connector (React/Angular/etc)?

React

### Feature Description

Ability to navigate the x-axis scroll to a particular day in Month view when we click on today button. Consider the date is 30th August, when click on "today" button the "Now" indicator is in 30th August but the x-axis scroll is in the first 2 weeks of August. We need to navigate manually to the 30th August date. It will be better if that navigation happens automatically.

![image](https://github.com/fullcalendar/fullcalendar/assets/52969527/07e22d2c-616f-4bcc-a40e-cd2835261f35)

**Comment by acerix** [comment]
I believe this existing ticket captures this need:
https://github.com/fullcalendar/fullcalendar/issues/4806
↑
Please visit the above issue, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates.
