### ISSUE TITLE
Window Resize causes hidden calendars to not display correctly.

### ISSUE THREAD

**Issue by jonathan-rowley** [fullcalendar/fullcalendar#7422]
### Reduced Test Case

https://jsfiddle.net/jejrowley/2bqwh4p3/29/

### Do you understand that if a reduced test case is not provided, we will intentionally delay triaging of your ticket?

- [X] I understand

### Which connector are you using (React/Angular/etc)?

No connector (vanilla JS)

### Bug Description

I am building a web app using fullcalendar that has different calendars in different tabs loaded to the same DOM. I noticed that it uses JS to resize after a window size change which is pretty normal. my bug comes in when i have a hidden calendar and i resize the screen. when i show the calendar it is messed up until i resize the window again.

I have added some screenshots of the jsfiddle i made to demonstrate the use case.

![image](https://github.com/fullcalendar/fullcalendar/assets/50716090/c63e92bb-a698-4b09-ae9c-5370155afa85)
![image](https://github.com/fullcalendar/fullcalendar/assets/50716090/09368999-d682-47cb-9a25-301b7e6b8cab)
![image](https://github.com/fullcalendar/fullcalendar/assets/50716090/b64d7542-72c0-474d-baf4-bee4312f1e19)

I was able to fix this on my end by adding a `visibilitychange` listener to the calendars which trigger the resize but this seems like it would be helpful in the code base so other users dont experience this behavior.

Here is an example of what could be done:
```
// Event listener for visibility change of the calendar element
calendar.addEventListener('visibilitychange', () => {
  if (calendar.style.visibility === 'visible') {
    resizeElement(); // or whatever function is used to resize the calendar
  }
});
```

**Comment by jonathan-rowley** [comment]
I was playing around with a bunch of different ways to do this and found the best way is to set a listener for the height of the calendar right after it is rendered.
```js
// Function to resize the calendar when its height becomes non-zero
    function resizeCalendarOnHeightChange(calendarInstance, calendarEl) {
        if (calendarEl.offsetHeight > 0) {
            calendarInstance.updateSize();
        }
    }
    function addHiddenListener(calendarInstance, calendarEl) {
        // Use ResizeObserver to watch for changes in element height
        var resizeObserver = new ResizeObserver(entries => {
            entries.forEach(entry => {
                resizeCalendarOnHeightChange(calendarInstance, calendarEl);
            });
        });
        resizeObserver.observe(calendarEl);
    }
    
    var calendarEl = document.getElementById('calendar1');
        var calendar = new FullCalendar.Calendar(calendarEl, {
          initialView: 'dayGridMonth'
        });
        calendar.render();
        // now we add the listener
        addHiddenListener(calendar, calendarEl);
```

**Comment by acerix** [comment]
It's expected that [updateSize](https://fullcalendar.io/docs/updateSize) needs to be called after resizing the parent element so I don't believe this is a bug.
