### ISSUE TITLE
Infinite loading crashes page

### ISSUE THREAD

**Issue by Cl0ser01** [fullcalendar/fullcalendar#7427]
### Reduced Test Case

-

### Do you understand that if a reduced test case is not provided, we will intentionally delay triaging of your ticket?

- [X] I understand

### Which connector are you using (React/Angular/etc)?

Vue

### Bug Description

On some screen resolutions (for example 1347x1323 - screen size, 947х590 - component size) in month view with large amount of events it starts infinite loading and crashes the page(stop reacting anything)

fullcalendar 6.1.8
vue 2

**Comment by acerix** [comment]
Would you be able to post a [runnable, stripped-down demonstration of the bug](http://fullcalendar.io/wiki/Reduced-Test-Cases/)? Would really appreciate it because the time saved reproducing will be time spent fixing.
