### ISSUE TITLE
Will FullCalendar Premium still work after being off the internet

### ISSUE THREAD

**Issue by xuerui0709** [fullcalendar/fullcalendar#7429]
### Reduced Test Case

1

### Do you understand that if a reduced test case is not provided, we will intentionally delay triaging of your ticket?

- [X] I understand

### Which connector are you using (React/Angular/etc)?

No connector (vanilla JS)

### Bug Description

1

**Comment by acerix** [comment]
Yes, it does no require any connection. Please send questions like this to sales@fullcalendar.io .
