### ISSUE TITLE
when click on iphone devices, it is showing add new event instead of details for event on already reserved day

### ISSUE THREAD

**Issue by hamzabinilyas** [fullcalendar/fullcalendar#7430]
### Reduced Test Case

it is confidential

### Do you understand that if a reduced test case is not provided, we will intentionally delay triaging of your ticket?

- [X] I understand

### Which connector are you using (React/Angular/etc)?

No connector (vanilla JS)

### Bug Description

when clicking on iPhone devices, it is showing add new event instead of details for the event on that day. It is working fine on desktop and for android devices on the first-page load, it is getting issue similiar with iPhone but on the second tap, it is working fine. I got the moment js warning on that page and I resolve this and also remove prevent default. Still getting the issue. any idea to resolve this?

**Comment by acerix** [comment]
Please post a [runnable, stripped-down demonstration of the bug](http://fullcalendar.io/wiki/Reduced-Test-Cases/) or link to a demo with this issue.  Would really appreciate it because the time saved reproducing will be time spent fixing.
