### ISSUE TITLE
Ver. 6.1.8/Bug with React 16 (many events)

### ISSUE THREAD

**Issue by Patrick1900** [fullcalendar/fullcalendar#7435]
### Reduced Test Case

https://github.com/fullcalendar/fullcalendar-react/commit/f9e357927dafc9da4bf513d26b93f7bf50f557bf

### Do you understand that if a reduced test case is not provided, we will intentionally delay triaging of your ticket?

- [X] I understand

### Which connector are you using (React/Angular/etc)?

React

### Bug Description

 It seems that this function could break on React 16, with a calendar full of events
 
 even if the main project is React 16, this funcyion tries to run `flushSync`
 
```
 const runFunc = (
        this.isUnmounting ||
        isMounting ||
        (requestTimestamp - lastRequestTimestamp) < 100 // rerendering frequently
      ) ? runNow // either sync rendering (first-time or React 17) or async (React 18)
        : flushSync // guaranteed sync rendering
```
![Screenshot 2023-07-25 at 15 04 47](https://github.com/fullcalendar/fullcalendar/assets/13556683/555658ac-bcbc-42aa-9653-904569209ba1)

![image](https://github.com/fullcalendar/fullcalendar/assets/13556683/501539cd-2b43-4fd8-9ec0-ef7eaf3f3066)

**Comment by acerix** [comment]
Would you be able to post a [runnable, stripped-down demonstration of the bug](http://fullcalendar.io/wiki/Reduced-Test-Cases/)? Would really appreciate it because the time saved reproducing will be time spent fixing.

**Comment by Patrick1900** [comment]
@acerix 
Unfortunately, this error is difficult to reproduce.

But it obviously came in with v6.1.8.

Here, under certain conditions (see code example) - `flushSync` is called in a React16 environment

I would like to ask you to check this code once.
https://github.com/fullcalendar/fullcalendar-react/commit/f9e357927dafc9da4bf513d26b93f7bf50f557bf
