### ISSUE TITLE
Drag and drop resource row

### ISSUE THREAD

**Issue by chaitu2chowdary** [fullcalendar/fullcalendar#7445]
### Checklist

- [X] I've already searched through [existing tickets](https://github.com/fullcalendar/fullcalendar/issues)
- [X] Other people will find this feature useful

### Is this feature for a specific connector (React/Angular/etc)?

Angular

### Feature Description

Dear FullCalendar Development Team,

I hope this message finds you well. I am an avid user of FullCalendar, and I would like to propose a new feature that I believe would significantly enhance the usability and functionality of your product. Specifically, I am interested in implementing a "Drag and Drop Resource Row" feature.

**Feature Description:**

**1. Feature Overview:**

The Drag and Drop Resource Row feature would allow users to easily reorder and reassign resources within the resource row of FullCalendar by simply dragging and dropping them to new positions.

**2. Use Cases:**
Resource Management: Users can efficiently rearrange and prioritize resources in a resource row, making it easier to manage and allocate resources for different events and schedules.
Visual Organization: The feature would provide a more intuitive and visually appealing way to organize resources, enhancing the overall user experience.

**3. Key Functionality:**

Drag and Drop Functionality: Users should be able to click and drag a resource within the resource row to a new position.
Visual Feedback: During the drag-and-drop process, provide visual feedback such as animations or highlighting to indicate the current position where the resource will be dropped.
Callbacks and Events: Implement callback functions and events that can be used to capture and respond to resource rearrangement, enabling customization and integration with other functionalities.

I would be happy to provide further input or collaborate with your team to help bring this feature to fruition. Please consider this feature request, and I look forward to seeing FullCalendar continue to evolve and improve.

Thank you for your time and consideration.

**Comment by acerix** [comment]
I believe this existing ticket captures this need:
https://github.com/fullcalendar/fullcalendar/issues/5667
↑
Please visit the above issue, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates.
