### ISSUE TITLE
Infinite `eventContent` loop with `dayMaxEvents` and with `white-space: normal` in event content making it display on to multiple lines

### ISSUE THREAD

**Issue by acerix** [fullcalendar/fullcalendar#7447]
### Reduced Test Case

https://codepen.io/acerix/pen/bGOBrKr?editors=001

### Do you understand that if a reduced test case is not provided, we will intentionally delay triaging of your ticket?

- [X] I understand

### Which connector are you using (React/Angular/etc)?

No connector (vanilla JS)

### Bug Description

Test test case will loop forever and freeze the browser if `exit()` is removed.  

Reported in https://fullcalendar.freshdesk.com/a/tickets/7073

**Comment by arshaw** [comment]
This is properly fixed in [v6.1.9](https://github.com/fullcalendar/fullcalendar/releases/tag/v6.1.9)

Updated repro:
https://codepen.io/arshaw/pen/QWzaomE?editors=001
