### ISSUE TITLE
Missing now indicator

### ISSUE THREAD

**Issue by AlexHalkinVia** [fullcalendar/fullcalendar#7452]
### Reduced Test Case

https://codepen.io/Oleksandr-Halkin/pen/oNJWdNo?editors=001

### Do you understand that if a reduced test case is not provided, we will intentionally delay triaging of your ticket?

- [X] I understand

### Which connector are you using (React/Angular/etc)?

React

### Bug Description

In case we have defined `slotMinTime`,`slotMaxTime` and `now` time is less than `slotMinTime` we have missing now indicator. 

See provided test case. Here we have:
now: 16:00 of Feb 16
slotMinTime: 17:30:00,
slotMaxTime: 41:30:00

According to these slots we have "2-days" view, I mean February 16 – 17, February 15 – 16, February 14 – 15, etc.

The problem is I don't see now indicator when Im in "February 15 – 16" view, I see small part of this indicator on view "February 16 – 17", but it is incorrect since "16:00 of Feb 16" is not time represents by this view

![Screenshot 2023-09-12 at 13 02 57](https://github.com/fullcalendar/fullcalendar/assets/92315906/f39b3d43-c007-43c1-a348-2b2227aa12c2)
![Screenshot 2023-09-12 at 13 04 24](https://github.com/fullcalendar/fullcalendar/assets/92315906/c9e9f825-6314-48c2-9d30-34cf30bf81bb)

P.S. connector is not matter

**Comment by acerix** [comment]
I believe this existing ticket captures this need:
https://github.com/fullcalendar/fullcalendar/issues/6394
↑
Please visit the above issue, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates.
