### ISSUE TITLE
Option to delay the rendering of events that don't fit within a day in month view.

### ISSUE THREAD

**Issue by RelativelyFine** [fullcalendar/fullcalendar#7453]
### Checklist

- [X] I've already searched through [existing tickets](https://github.com/fullcalendar/fullcalendar/issues)
- [X] Other people will find this feature useful

### Is this feature for a specific connector (React/Angular/etc)?

No connector in particular

### Feature Description

We are thinking of adopting FullCalendar commercially for scheduling hospital surgeries and blocks in where there are potentially 1000+ events per month. The monthly view takes around 1-2 seconds to render when switching months. This is slow enough to disturb UX.

I'd like to request that there be the option to delay the rendering of the events that don't fit inside a monthly day (when using dayMaxEventRows) until the user clicks the +more button. This will drastically speed up rendering across the monthly views while keeping functionality intact.

In this case, the calendar should only need to render around 200 events per month when switching views, rather than a potentially infinite amount.

**Comment by acerix** [comment]
I believe this existing ticket captures this need:
https://github.com/fullcalendar/fullcalendar/issues/6148
↑
Please visit the above issue, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates.
