### ISSUE TITLE
Custom Yearly Slot Sizes Enhancement for Three-Year Display (timeline)

### ISSUE THREAD

**Issue by nabil-hamisa** [fullcalendar/fullcalendar#7454]
### Checklist

- [X] I've already searched through [existing tickets](https://github.com/fullcalendar/fullcalendar/issues)
- [X] Other people will find this feature useful

### Is this feature for a specific connector (React/Angular/etc)?

React

### Feature Description

Id like to propose an enhancement for React Full Calendar that allows users to customize the slot sizes for the yearly view when displaying three years together. The goal is to accommodate   varying time periods within each of the three years. Specifically, the feature would enable users to split each year into custom slots, as exemplified below:

if the calendar displaying 3 years in a row 
2023:

January to June: One slot
July to December: One slot
2024:

January to March: One slot
April to June: One slot
July to September: One slot
October to December: One slot

**Comment by acerix** [comment]
I believe this existing ticket captures this need:
https://github.com/fullcalendar/fullcalendar/issues/4834
↑
Please visit the above issue, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates.
