### ISSUE TITLE
clickInfo.event.extendedProps does not contain id, title, start and end properties

### ISSUE THREAD

**Issue by BenRacicot** [fullcalendar/fullcalendar#7458]
### Reduced Test Case

https://stackblitz.com/edit/github-3rvtti?file=src%2Fapp%2Fapp.component.ts%3AL88

### Do you understand that if a reduced test case is not provided, we will intentionally delay triaging of your ticket?

- [X] I understand

### Which connector are you using (React/Angular/etc)?

Angular

### Bug Description

When setting up Angular FullCalendar by following the [Angular NGRX example](https://github.com/fullcalendar/fullcalendar-examples/blob/main/angular15-ngrx/src/app/app.component.html#L45) for async events I can confirm that certain properties are then missing from `EventClickArg.event.extendedProps`

Here is a [StackBlitz replication](https://stackblitz.com/edit/github-3rvtti?file=src%2Fapp%2Fapp.component.ts) where you can see the event object I've sent `const testEvent`
```
const testEvent = {
  assigned_to: 'Joe, Shmoe',
  client_type: 'seller',
  color_css: 'pending',
  derived_status: 'Pending',
  display_order: 1,
  dscr: '',
  due_days: '09/21/2023 (Due in 2 days)',
  due_dt: '2023-09-21',
  due_status_trigger: null,
  end: '2023-09-21',
  id: '8527360',
  start: '2023-09-21',
  task_status_id: 81,
  task_type: 'T',
  title: 'Test Title 1',
};
```
And when we check the event object with `clickInfo` many properties are now missing.
```
  onEventClick(clickInfo: EventClickArg): void {
    console.log(clickInfo.event.extendedProps); // <-- stripped properties
```

```
assigned_to: "Joe, Shmoe"
client_type: "seller"
color_css: "pending"
derived_status: "Pending"
display_order: 1
dscr: ""
due_days: "09/21/2023 (Due in 2 days)"
due_dt: "2023-09-21"
due_status_trigger: null
task_status_id: 81
task_type: "T"
```

**Comment by acerix** [comment]
`extendedProps` only contains custom properties which are not defined in the [event model](https://fullcalendar.io/docs/event-object), built-in properties can be accessed directly like `event.start`.
