### ISSUE TITLE
dateClick is not a property on CalendarOptions

### ISSUE THREAD

**Issue by wojo1086** [fullcalendar/fullcalendar#7461]
### Reduced Test Case

https://stackblitz.com/edit/stackblitz-starters-sugjss?file=src%2Fmain.ts

### Do you understand that if a reduced test case is not provided, we will intentionally delay triaging of your ticket?

- [X] I understand

### Which connector are you using (React/Angular/etc)?

Angular

### Bug Description

According the documentation, I can add the `dateClick` handler as a property in my calendar options, but the `CalendarOptions` type doesn't contain a `dateClick` property.

**Comment by acerix** [comment]
`dateClick` is part of the "interaction" plugin so that needs to be included:

https://stackblitz.com/edit/stackblitz-starters-yjaspn?file=src%2Fmain.ts
