### ISSUE TITLE
`eventContent` called even if the event won't be shown because of `dayMaxEventRows`

### ISSUE THREAD

**Issue by boris-petrov** [fullcalendar/fullcalendar#7463]
### Reduced Test Case

Not needed

### Do you understand that if a reduced test case is not provided, we will intentionally delay triaging of your ticket?

- [X] I understand

### Which connector are you using (React/Angular/etc)?

No connector (vanilla JS)

### Bug Description

I didn't provide a test case because it's very obvious what I mean - I can provide one if you don't understand.

I would expect `eventContent` to only be called for the events that are actually rendered on the screen. If I have 10 events for a day and I've set `dayMaxEventRows = 5` - I would expect `eventContent` to be called 5 times. It's called 10.

The reason I want this is that we have some complex logic in `eventContent` that is very computationally intensive. The current behavior causes massive slowdowns in our case where we have hundreds of events and only a couple of them are shown.

That's not exactly a "bug" per se but it would be nice to fix the current behavior. I think it makes sense?

**Comment by acerix** [comment]
I believe this existing ticket captures this need:
https://github.com/fullcalendar/fullcalendar/issues/6148
↑
Please visit the above issue, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates.
