### ISSUE TITLE
How to format date with locale JA

### ISSUE THREAD

**Issue by Kroberus** [fullcalendar/fullcalendar#7464]
### Checklist

- [X] I've already searched through [existing tickets](https://github.com/fullcalendar/fullcalendar/issues)
- [X] Other people will find this feature useful

### Is this feature for a specific connector (React/Angular/etc)?

Other

### Feature Description

I use:
- vanilla js
- FullCalendar version 6.1.9 (https://cdn.jsdelivr.net/npm/fullcalendar@6.1.9/index.global.min.js)
-> How do I delete the "日" in the date boxes like the image below? Thank you!
![image](https://github.com/fullcalendar/fullcalendar/assets/118706956/cac32666-d1a2-4037-a147-60696c4cef8a)
![image](https://github.com/fullcalendar/fullcalendar/assets/118706956/0c1c5247-dce9-4c19-9dc8-8f7ecc110137)

**Comment by acerix** [comment]
You can use `dayCellContent` to change the format, this has more info:

https://github.com/fullcalendar/fullcalendar/issues/5439
