### ISSUE TITLE
More Link Button arguments gives previous date sometimes in different timezones

### ISSUE THREAD

**Issue by gaurav-simpplr** [fullcalendar/fullcalendar#7475]
### Reduced Test Case

https://codesandbox.io/s/goofy-nightingale-xfl75l?file=/src/App.js

### Do you understand that if a reduced test case is not provided, we will intentionally delay triaging of your ticket?

- [X] I understand

### Which connector are you using (React/Angular/etc)?

React

### Bug Description

In my React application, I am using the FullCalendar component and I'm rendering my own customised popover. This popover gets triggered whenever a user clicks on the '+ more' link within a day cell. For example, if the '+ more' link appears on the 18th of October and a user clicks on it, I need to display the number 18 on the top in my custom popover.

To achieve this, I am using the `moreLinkClick` prop in FullCalendar component and passing it a handler function. The moreLinkClick prop handler argument provides the following information:

``` 
date: Tue Oct 17 2023 17:00:00 GMT-0700 (Pacific Daylight Time)
allDay: true
allSegs: Array(5)
hiddenSegs: Array(4)
```

I have noticed a discrepancy related to time zones. Specifically, while operating in the IST time zone, clicking on the '+ more' link on 18 October yields the correct date. However, upon switching my system time zone to PDT and clicking on the '+ more' link (still on 18 October day cell) , the `date` argument inaccurately reflects the previous day, 17 October.

**Comment by acerix** [comment]
Your demo doesn't load for me (seems it's a problem with codesandbox) but it sounds like the issue is with how dates are stored with "UTC-coercion", so you need to convert them like with `toISOString()` to get the correct time. 

https://fullcalendar.io/docs/timeZone#UTC-coercion
