### ISSUE TITLE
TypeError when clicking timed event using slot component in Vue3

### ISSUE THREAD

**Issue by Q16solver** [fullcalendar/fullcalendar#7477]
### Reduced Test Case

https://stackblitz.com/edit/github-wn9aqn-n3piqc

### Do you understand that if a reduced test case is not provided, we will intentionally delay triaging of your ticket?

- [X] I understand

### Which connector are you using (React/Angular/etc)?

Vue

### Bug Description

I wanted to define a custom event content to display and drag and drop, but I found that it actually gives `Cannot read properties of null (reading 'eventRange')` in the console. I'm not sure if this is intentional, since I tried with v5, and it was working fine. Also if I remove the custom slot for eventContent, it is also able to grab the eventRange.

**Comment by havenothingtosay** [comment]
I encountered the same problem

**Comment by ortega225** [comment]
I have the same issue when using the slot component with Vue 3.

**Comment by acerix** [comment]
Thanks, confirmed.

I get the same in this live demo: https://stackblitz.com/github/fullcalendar/fullcalendar-examples/tree/main/vue3

I disabled some code and it still has the error in this reduced case:

https://stackblitz.com/edit/github-v6jr59?file=src%2FDemoApp.vue

As a workaround, setting allDay: true on the event seems to avoid the error, `eventContent` can be used to show the time.

**Comment by pvpmartins** [comment]
There is a way to change the allDay property when changing to a view different than month? I am thinking it as a workaround...

**Comment by ortega225** [comment]
Since this is an bug with the base example, will it receive priority for a fix? 

Or should I assume a long lead time to fix?

**Comment by warrence** [comment]
Is this problem being fix? I can sue the temporily solution, set allDay to true is the start and end date is the same day, but we have another problem, if the view is on week or day, it will appear as allday instead of using the start and end time.

**Comment by arshaw** [comment]
I'm checking this on FullCalendar v6.1.14 and things look okay:
https://stackblitz.com/edit/github-wn9aqn-qr9irf?file=package.json

I probably fixed this in v6.1.10 when I fixed this bug:
https://github.com/fullcalendar/fullcalendar/issues/7524
