### ISSUE TITLE
allDay background event not show last day

### ISSUE THREAD

**Issue by denism300** [fullcalendar/fullcalendar#7480]
### Reduced Test Case

https://codepen.io/denis-mukhin/pen/rNoPzXb

### Do you understand that if a reduced test case is not provided, we will intentionally delay triaging of your ticket?

- [X] I understand

### Which connector are you using (React/Angular/etc)?

No connector (vanilla JS)

### Bug Description

The last day of the event is not displayed. How can this be fixed?

**Comment by acerix** [comment]
The end date is _exclusive_, so it should be set to the day after the last day of the event.
