### ISSUE TITLE
Safari showing events and IOS device not showing events in ionic Angular Application

### ISSUE THREAD

**Issue by 1Vishu** [fullcalendar/fullcalendar#7484]
### Reduced Test Case

Safari showing events and IOS device not showing events in ionic Angular Application

### Do you understand that if a reduced test case is not provided, we will intentionally delay triaging of your ticket?

- [X] I understand

### Which connector are you using (React/Angular/etc)?

No connector (vanilla JS)

### Bug Description

Safari showing events and IOS device not showing events in ionic Angular Application

**Comment by acerix** [comment]
Would you be able to post a [runnable, stripped-down demonstration of the bug](http://fullcalendar.io/wiki/Reduced-Test-Cases/)? Would really appreciate it because the time saved reproducing will be time spent fixing.
