### ISSUE TITLE
custom JSX eventContent flickering when reininitializing the calendar on React state change

### ISSUE THREAD

**Issue by SHergibo** [fullcalendar/fullcalendar#7488]
### Reduced Test Case

https://stackblitz.com/edit/github-thnwom

### Do you understand that if a reduced test case is not provided, we will intentionally delay triaging of your ticket?

- [X] I understand

### Which connector are you using (React/Angular/etc)?

React

### Bug Description

Since I updated my project from react 17.0.2 to react 18, the events on my calendar flickers when a state is updated. I use a custom JSX eventContent for the events, without the custom JSX eventContent there is no events flickering.

I have created another reduced test case but this one is with react 17.0.2 and there is no event flickering on this one.

[https://stackblitz.com/edit/github-thnwom-uen4ev](https://stackblitz.com/edit/github-thnwom-uen4ev)

Screen Recordings

1. Reproduction recording

https://github.com/fullcalendar/fullcalendar/assets/39282300/285e149b-ed46-4d86-b033-1c76cc5d6512

2. Real project recordings

You can see on the first 7sec of this video my project updated to react 18, the rest of the video is the same project but with react 17.0.2.

https://github.com/fullcalendar/fullcalendar/assets/39282300/7b7e3c89-1326-405b-a09b-ae87a1931a8b

**Comment by acerix** [comment]
I can see the flickering but I'm not sure it's actually a bug in the calendar.  I believe the issue is from using `useState` to reintialize the calendar when the state is changed, and the initial render is just taking longer in React 18. You can instead use the API to update events which should not have this issue:

https://fullcalendar.io/docs/events-function

**Comment by SHergibo** [comment]
@acerix I have checked your link and if you check my code you can see that I'm already using an `events (as a function)` to show the event on the calendar. I'm a using a `Promise` so I don't need to use `successCallback` (as mentioned in the doc).

I need the `useState` in my real project to open a modal and set the initial value for the form in the modal so I can't delete it. In to Reduced test case, the `useState` is here to simulate the state change to open/close the modal.

Do you have any other suggestions/examples that can help me fix the problem?

**Comment by arshaw** [comment]
I was not able to recreate the original bug, but @SHergibo, would you be able to check if the newly-released [v7.0.0-beta.0](https://github.com/fullcalendar/fullcalendar-workspace/releases/tag/v7.0.0-beta.0) makes improvements on this front? Theoretically it should have.

**Comment by SHergibo** [comment]
Hi @arshaw, sadly the bug is still reproductible on our side with the v7.0.0-beta.0. I have forked my reduce test case with the new version of Fullcalendar where the bug can still be reproduced. 

https://stackblitz.com/edit/github-thnwom-xylntx

Tested on:
- Google chrome(129.0.6668.60)
- Firefox(131.0 (64 bits))
- Arc(1.61.2)

Thank you for your help :)

**Comment by arshaw** [comment]
Thanks @SHergibo, I'm able to intermittently recreate this on my machine, especially in Firefox

**Comment by arshaw** [comment]
Hi @SHergibo, looking into your code, I'm realizing @acerix was right in his response about setState causing the flicker, but I'd like to add some important details. Whenever the `DemoApp` render function is executed, a new closure is created for the `events` generator. FullCalendar intentionally rerenders all events when it receives a new `events` reference. For all it knows, it could be a generating brand new event data. The solution is to move the `events` function outside of the component (or use some react tricks like `useRef` or `useMemo` to maintain a stable reference). It just so happens that whenever `DemoApp`'s state is updated, the function reference changes, causing a complete teardown and rerender.

Updated repro with function moved out:
https://stackblitz.com/edit/github-thnwom-afychn?file=src%2FDemoApp.jsx

**Comment by Aleafan** [comment]
Hello, @arshaw!

I had a related problem with ticket #7650 (https://github.com/fullcalendar/fullcalendar/issues/7650). 
It was closed and I don't agree with that. I ask you to please look into it.

`FullCalendar intentionally rerenders all events when it receives a new events reference`
Yes, but there is a difference between rerender and complete teardown and new render. You can see in my patch files a couple of places where generating random React key on **high level containers** unnecessarily leads to teardown of whole subtree of components. I dont think its justified in those places.

This problem leads to e.g. loss of focus from inside custom content every time something small causes a rerender of calendar.
I fixed loss of focus by removing key generation from 2 places, again see my patch files.

And in concern to current ticket here - there is still flickering of all events when some piece of data in some event change, which is better than before but still not ideal.

Thanks for you work, hope this helps you make the library even better!

**Comment by arshaw** [comment]
hi @Aleafan , please see https://github.com/fullcalendar/fullcalendar/issues/7650#issuecomment-2415504156
