### ISSUE TITLE
TypeError when clicking timed event in Vue3 demo

### ISSUE THREAD

**Issue by pvpmartins** [fullcalendar/fullcalendar#7490]
### Reduced Test Case

https://github.com/fullcalendar/fullcalendar-vue

### Do you understand that if a reduced test case is not provided, we will intentionally delay triaging of your ticket?

- [X] I understand

### Which connector are you using (React/Angular/etc)?

Vue

### Bug Description

The issue is really simple. I just did install your demo for the vue app and did not change the code at all.

When an event is clicked on the month view, unless it is marked as allDay, throws that error:

index.js:1228 Uncaught TypeError: Cannot read properties of null (reading 'eventRange')
    at handlePointerDown (index.js:1228:59)
    at Emitter.trigger (internal-common.js:3665:21)
    at HitDragging.handlePointerDown (index.js:915:30)
    at Emitter.trigger (internal-common.js:3665:21)
    at FeaturefulElementDragging.onPointerDown (index.js:710:30)
    at Emitter.trigger (internal-common.js:3665:21)
    at PointerDragging.handleMouseDown (index.js:40:30)
handlePointerDown @ index.js:1228
trigger @ internal-common.js:3665
HitDragging.handlePointerDown @ index.js:915
trigger @ internal-common.js:3665
FeaturefulElementDragging.onPointerDown @ index.js:710
trigger @ internal-common.js:3665
PointerDragging.handleMouseDown @ index.js:40
Show 7 more frames

![Screenshot from 2023-10-12 22-06-48](https://github.com/fullcalendar/fullcalendar/assets/85913786/bd95fe38-412c-447b-a7aa-92cc46bc8026)

**Comment by acerix** [comment]
Thanks, confirmed.  I get the same in this live demo: https://stackblitz.com/github/fullcalendar/fullcalendar-examples/tree/main/vue3

**Comment by acerix** [comment]
I reduced some code and it still has the error, seems specific to month view:

https://stackblitz.com/edit/github-v6jr59?file=src%2FDemoApp.vue

As a workaround, setting `allDay: true` on the event seems to avoid the error, and`eventContent` can be used to show the time.

**Comment by ortega225** [comment]
The issue also prevents the event from being draggable.

Only happens in Vue 3, Vue 2 works without issue.

Only happens when allDay = false;

**Comment by acerix** [comment]
Thanks for the details. I just noticed this ticket which was opened earlier for the same issue so will close this one:
https://github.com/fullcalendar/fullcalendar/issues/7490
↑
Please visit the above issue, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates.
