### ISSUE TITLE
Background event display

### ISSUE THREAD

**Issue by OlivierRicca** [fullcalendar/fullcalendar#7503]
### Reduced Test Case

https://kalend.r3factory.io/

### Do you understand that if a reduced test case is not provided, we will intentionally delay triaging of your ticket?

- [X] I understand

### Which connector are you using (React/Angular/etc)?

React

### Bug Description

Using week view, when display background events with multiple "holes", only last event is display. If you navigate to previous/next week and back to current, sometimes the display is correct, sometimes not.

incorrect display
![16 - 22 oct  2023](https://github.com/fullcalendar/fullcalendar/assets/16214500/cd3990a8-b612-43e9-a71d-23d0a6530579)

correct display (when navigate to previous/next week and back to current)
![16 - 22 oct  2023](https://github.com/fullcalendar/fullcalendar/assets/16214500/0818c769-ef5a-4ff7-928a-522a4d328738)

the array of events is set in a React state named `display_events` :

```js
{
    id: unique id,
    title: empty string,
    start: begin_date,
    end: end_date,
    display: 'background'
}
```
 
```js
const FullCalendarComponent = useMemo(() => {
    return <FullCalendar
      ref={cal_ref}
      plugins={[dayGridPlugin,timeGridPlugin,interactionPlugin,listWeek]}
      timeZone= 'local'
      locale='fr'
      allDaySlot={false}
      firstDay={1}
      headerToolbar={(is_mobile) ? 
        {
          left: 'prev,next',
          center: 'title',
          right: 'today'
        }
      :
        {
          left: 'prev,next today',
          center: 'title',
          right: ''
        }
      }
      buttonText={{
        today:  t('planning:today'),
        month:  t('planning:month'),
        week:   t('planning:week'),
        day:    t('planning:day'),
        list:   t('planning:list'),
      }}    
      businessHours={[ // specify an array instead
        {
          daysOfWeek: [ 1, 2, 3, 4, 5, 6 ], // Monday, Tuesday, Wednesday
          startTime: '08:00', // 8am
          endTime: '20:00' // 6pm
        },
      ]}      
      events={display_events}
      initialView={(is_mobile) ? 'timeGrid' : 'timeGridWeek'}
      editable={true}
      selectable={true}
      selectMirror={true}
      dayMaxEvents={true}
      weekends={true}
      weekNumbers={true}
      datesSet={planning_date_set}
      select={date_select_handler}
      eventContent={event_render} // custom render function
      // eventClick={event_select_handler}
      eventAdd={data => console.log('add', data)}
      eventChange={data => event_change_handler(data)}
      eventRemove={data => console.log('remove', data)}
      dayCount={(is_mobile) ? 2 : undefined}
    />
  }, [cal_ref, is_mobile, display_events, planning_date_set, dayGridPlugin,timeGridPlugin,interactionPlugin,listWeek])
```

Is there something to do more, any refresh or re-render ? 
I have already try that : 

```js
      cal_ref.current.getApi().updateSize()
      cal_ref.current.getApi().refetchEvents()
``` 

Thanks to team

**Comment by acerix** [comment]
Would you be able to post a [runnable, stripped-down demonstration of the bug](http://fullcalendar.io/wiki/Reduced-Test-Cases/)? Would really appreciate it because the time saved reproducing will be time spent fixing.
