### ISSUE TITLE
Adding additional time column in TimeGrid View

### ISSUE THREAD

**Issue by leoleoasd** [fullcalendar/fullcalendar#7504]
### Checklist

- [X] I've already searched through [existing tickets](https://github.com/fullcalendar/fullcalendar/issues)
- [X] Other people will find this feature useful

### Is this feature for a specific connector (React/Angular/etc)?

No connector in particular

### Feature Description

![image](https://github.com/fullcalendar/fullcalendar/assets/37735580/8eb6e789-b02a-47b9-a033-a8fb818ec268)
I want to add an additional time column with different time zones. I'm using fullcalendar to display my availability, and I want users to be able to see the event time both in their timezone and in my timezone.

**Comment by acerix** [comment]
I believe this existing ticket captures this need:
https://github.com/fullcalendar/fullcalendar/issues/3964
↑
Please visit the above issue, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates.
