### ISSUE TITLE
want to add custom Column next to Saturday  

### ISSUE THREAD

**Issue by Waqar-Akhtar** [fullcalendar/fullcalendar#7508]
### Checklist

- [X] I've already searched through [existing tickets](https://github.com/fullcalendar/fullcalendar/issues)
- [X] Other people will find this feature useful

### Is this feature for a specific connector (React/Angular/etc)?

React

### Feature Description

"I'd like to include a custom column next to Saturday in a calendar, but based on my research, I believe this may not be possible. However, what if someone requires the addition of a custom column? How can this be addressed professionally?"

![Screenshot 2023-10-24 at 12 40 39 PM](https://github.com/fullcalendar/fullcalendar/assets/113596640/1873fbc2-501d-4d3d-acf8-9f85b507e852)

**Comment by acerix** [comment]
I believe this existing ticket captures this need:
https://github.com/fullcalendar/fullcalendar/issues/4210
↑
Please visit the above issue, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates.

**Comment by Fayyaz011** [comment]
+1, I want to show week totals in a separate column

**Comment by hybrid1969** [comment]
I ended up cobbling together the below using copilot with alot of cleaning up and adjustment. not perfect but does work in my case -
`document.addEventListener('DOMContentLoaded', function () {
    var calendarEl = document.getElementById('calendar');

    var calendar = new FullCalendar.Calendar(calendarEl, {
        initialView: 'dayGridMonth',
        datesSet: function (info) {
            // your code //
            handleViewChange(info.view.type);
        }
    });

    calendar.render();
});

function handleViewChange(viewType) {
    if (viewType === 'dayGridMonth') {
        addCustomColumn();
    } else {
        removeCustomColumn();
    }
}

function addCustomColumn() {
    // Check if the custom column already exists to avoid duplication
    const headerRow = document.querySelector('.fc-col-header .fc-col-header-cell');
    if (headerRow && !document.querySelector('.fc-col-header-cell.custom-column')) {
        const customHeader = document.createElement('th');
        customHeader.className = 'fc-col-header-cell custom-column';
        customHeader.innerText = 'Custom Column';
        headerRow.parentNode.appendChild(customHeader);
    }

    // Add a new cell for each row in the calendar
    const rows = document.querySelectorAll('.fc-daygrid-body tr');
    rows.forEach(row => {
        if (!row.querySelector('.fc-daygrid-body-cell.custom-cell')) {
            const customCell = document.createElement('td');
            customCell.className = 'fc-daygrid-body-cell custom-cell';
            customCell.innerText = 'Custom Cell';
            row.appendChild(customCell);
        }
    });
}

function removeCustomColumn() {
    // Remove the custom column header
    const customHeader = document.querySelector('.fc-col-header-cell.custom-column');
    if (customHeader) {
        customHeader.parentNode.removeChild(customHeader);
    }

    // Remove the custom cells from each row
    const customCells = document.querySelectorAll('.fc-daygrid-body-cell.custom-cell');
    customCells.forEach(cell => {
        cell.parentNode.removeChild(cell);
    });
}
`

**Comment by viniciusmelocodes** [comment]
Save works to me. This solution is sweet! @hybrid1969 thanks very much.
