### ISSUE TITLE
Drag & Drop not working in developer mode: device emulation

### ISSUE THREAD

**Issue by coreboarder** [fullcalendar/fullcalendar#7510]
### Reduced Test Case

https://stackblitz.com/edit/stackblitz-starters-sgacnt

### Do you understand that if a reduced test case is not provided, we will intentionally delay triaging of your ticket?

- [X] I understand

### Which connector are you using (React/Angular/etc)?

Angular

### Bug Description

I have a working drag and drop calendar but when I go into device emulation in developer tools the drag and drop functionality stops working. I have searched through previous tickets and noted references to Ionic blocking _dnd_ events but found nothing more detailed than that side note reference.

My ultimate goal is to have this working in an Ionic project so any guidance's would be greatly appreciated.

I have a working example here: https://stackblitz.com/edit/stackblitz-starters-sgacnt

**Comment by acerix** [comment]
It is working for me.  I believe the issue is that on touch devices you need to hold touch for 1 second before dragging starts, this can be changed with `longPressDelay`.

**Comment by coreboarder** [comment]
This works. Thank you for taking the time to check and steer me towards that setting.
