### ISSUE TITLE
dayHeaderDidMount not working correctly when duration is changed dynamically

### ISSUE THREAD

**Issue by prof-schnitzel** [fullcalendar/fullcalendar#7511]
### Reduced Test Case

https://codesandbox.io/s/magical-pine-zpjtyh

### Do you understand that if a reduced test case is not provided, we will intentionally delay triaging of your ticket?

- [X] I understand

### Which connector are you using (React/Angular/etc)?

No connector (vanilla JS)

### Bug Description

**Steps to reproduce:**
Use the demo link and click on the button "Change duration".

**Expected behaviour:**
The header row (adjusted with dayHeaderDidMount hook) should not change.

**Actual behaviour:**
The dayHeaderDidMount hook is called but additionally the default behaviour is also applied.

My current workaround is to call `calendar.next()` and `calendar.prev()` after changing the duration, but this seems kind of hacky.

**Comment by acerix** [comment]
The `*Mount` callbacks are for attaching listeners to the elements, for example. You should instead use `dayHeaderContent` to customize the HTML.

**Comment by prof-schnitzel** [comment]
@acerix Well the documentation is not clear about that. `dayHeaderDidMount` is a render hook and that's why I would expect that I can use it to change the render behaviour.
The sad thing about `dayHeaderContent` is that it renders an anchor tag around the content in the header cell. This destroys my styling and I have to add additional styles to solve those issues. With `dayHeaderDidMount` the anchor tag is not rendered.
