### ISSUE TITLE
00:00:00 time will not be displayed

### ISSUE THREAD

**Issue by airzhanglin** [fullcalendar/fullcalendar#7512]
### Reduced Test Case

https://codepen.io/Lynn-Lynn-the-flexboxer/pen/rNPORNV?editors=0010

### Do you understand that if a reduced test case is not provided, we will intentionally delay triaging of your ticket?

- [X] I understand

### Which connector are you using (React/Angular/etc)?

No connector (vanilla JS)

### Bug Description

![image](https://github.com/fullcalendar/fullcalendar/assets/16433124/82c17082-0b9b-4480-8945-8be6ddc7fdc9)

I would like to ask why my end time is 2023-10-28 00:00:00, but why is it not displayed on 28th? Isn't the start time of the day 00:00:00?

**Comment by acerix** [comment]
The end times are _exclusive_, so "00:00:00" means it ends at the end of the day.
