### ISSUE TITLE
Request: Mobile View Enhancement for Displaying Events in List View Upon Day Cell Selection

### ISSUE THREAD

**Issue by gaurav-simpplr** [fullcalendar/fullcalendar#7513]
### Checklist

- [X] I've already searched through [existing tickets](https://github.com/fullcalendar/fullcalendar/issues)
- [X] Other people will find this feature useful

### Is this feature for a specific connector (React/Angular/etc)?

React

### Feature Description

Hello,

We're utilizing the fullCalendar library to create our event view, with a significant portion of our users accessing it on mobile devices. Our design goal is to have a responsive event view on mobile where events in a day cell are represented as dots in the month grid view. When a day cell is tapped, we'd like the events for that day to be displayed below the calendar grid in a list format, similar to the functionality shown here: [link to demo](https://demo.mobiscroll.com/react/eventcalendar/mobile-month-view#). Please refer to the attached screenshot for clarity.

![Screenshot 2023-10-27 at 6 17 36 PM](https://github.com/fullcalendar/fullcalendar/assets/98866537/c75de6b0-8941-4cd2-8afb-35d5af4f4e6c)

Is it possible to achieve this presentation using the library's current features? Here are the methods I've explored:

    Creating two separate FullCalendar instances – one for the month grid view and another for the list view – and sharing data between them. However, I'm concerned this might introduce performance issues.

    Building our own list view container component to display the events. This approach requires extensive custom coding and doesn't leverage the library's existing methods efficiently.

Could you offer guidance on the best way to implement this desired functionality?

Thank you for your assistance.

**Comment by raghavsharma-simpplr** [comment]
@arshaw can you please help here?

**Comment by acerix** [comment]
I believe this existing ticket captures this need:
https://github.com/fullcalendar/fullcalendar/issues/3579
↑
Please visit the above issue, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates.

**Comment by arshaw** [comment]
Reopening this issue because it expresses how a daygrid with dots (as described in #3579) would integrate with a list of events below it.
