### ISSUE TITLE
Placeholder Event Absent on Day Grids with ThirdPartyDraggable

### ISSUE THREAD

**Issue by kWh61** [fullcalendar/fullcalendar#7514]
### Reduced Test Case

https://codepen.io/gary_walker/pen/LYqGBve

### Do you understand that if a reduced test case is not provided, we will intentionally delay triaging of your ticket?

- [X] I understand

### Which connector are you using (React/Angular/etc)?

React

### Bug Description

I've encountered an issue where ThirdPartyDraggable does not render a placeholder event on day grids, unlike a normal draggable which does. The placeholder appears as expected over a timegrid. I have created a reduced test case by simply switching the draggable to ThirdPartyDraggable which reproduces this issue. Any resolutions or workarounds would be greatly appreciated. Thank you!

**Comment by kWh61** [comment]
Another problem that might be relevant to this issue is that if the 'duration' property is set with 'hour' in eventData (e.g. duration: { 'hour': 2 }), then the element will be prohibited from dropping onto all-day sections in timeGridWeek. The desired behavior is not to disable it, but to ignore the duration property and parse the event as an all-day event with default durations instead.

This is very important for our use case as we 'guess' what the event duration is (which requires passing in an explicit duration value) but we also allow users to drop the event in the all-day section (which is not possible with the current version).

**Comment by arshaw** [comment]
A placeholder is not rendered within the cell during normal drag-n-drop either:
https://fullcalendar.io/docs/month-view-demo

timegrid renders one during normal drag-n-drop however. 

The goal was to have ThirdPartyDraggable mock that same behavior as normal dragging of events within the calendar. As such, no placeholder event (aka "mirror") is rendered on daygrid, but on timegrid it DOES render a placeholder, and it's supposed to be used in tendem with the `mirrorSelector` setting, which identifies the third-party drag-n-drop event to *hide* will the timegrid placeholder is present.

Updated repro with Dragula for demonstration purposes:
https://codepen.io/arshaw/pen/zYgqOZa?editors=1010

**Comment by kWh61** [comment]
Thank you for the clarification! It inspired me to explore a few different approaches, which ultimately helped resolve this issue in our codebase.

From what I understand, ThirdPartyDraggable, similar to Draggable, does not render an overlay (placeholder) when dragging over day grids but does render one over time grids. This implies that the third-party library is responsible for rendering the overlay. By specifying the `mirrorSelector` setting to target the third-party overlay, FullCalendar correctly recognized that something was being dragged over the day grids without any issues.

That said, I think the documentation might be slightly misleading when it states:

> Your third-party library undoubtedly renders a placeholder element that moves as your mouse drags. It is useful to disable this placeholder element for when the element is dragged over a time slot and FullCalendar renders its own placeholder element.

Correct me if I'm wrong, but in this case, mirrorSelector doesn’t seem to hide the third-party overlay but is instead used to let FullCalendar identify and respond to the overlay element.

Anyway, we’ve resolved the primary problem here and will close this issue for now. The duration problem remains unresolved, but I’ll open a separate issue if I can’t find a workaround.

Thanks again for your help!
