### ISSUE TITLE
Feature to get additional info on eventDrop

### ISSUE THREAD

**Issue by sahilalam0** [fullcalendar/fullcalendar#7516]
### Checklist

- [X] I've already searched through [existing tickets](https://github.com/fullcalendar/fullcalendar/issues)
- [X] Other people will find this feature useful

### Is this feature for a specific connector (React/Angular/etc)?

No connector in particular

### Feature Description

I would like to propose an enhancement to FullCalendar that provides additional information when an event is dropped onto the calendar after a drag-and-drop operation. Specifically, I suggest that FullCalendar should be able to determine whether the dropped event is lying in a slot that already contains another existing event.

While FullCalendar's current eventOverlap hook is useful during the drag operation, there is a need to know if an overlap exists after the event has been dropped.

It would be helpful to have additional information passed to the eventDrop hook, providing details about the overlap (e.g., IDs or relevant event information of the overlapping events) after the event has been dropped

**Comment by acerix** [comment]
I believe this existing ticket captures this need:
https://github.com/fullcalendar/fullcalendar/issues/4849
↑
Please visit the above issue, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates.
