### ISSUE TITLE
Display events with the same timeframe side by side maximum of 3 before showing the more option button

### ISSUE THREAD

**Issue by weezykon** [fullcalendar/fullcalendar#7517]
### Checklist

- [X] I've already searched through [existing tickets](https://github.com/fullcalendar/fullcalendar/issues)
- [X] Other people will find this feature useful

### Is this feature for a specific connector (React/Angular/etc)?

React

### Feature Description

![New Project](https://github.com/fullcalendar/fullcalendar/assets/586490/d947e7cc-c742-487f-911a-9ced943507b2)
There is an event that has a 1+ the show more, but I want to be able to show that event in the show more side by side with the manicure event shown in the picture.

**Comment by acerix** [comment]
The setting `eventMaxStack` does this. If you mean something else, it may help if you can include a mockup of how you want it to look.
