### ISSUE TITLE
Question: Does FullCalendar library record any usage / analytics metrics? Privacy is important for our use case. 

### ISSUE THREAD

**Issue by nicholascm** [fullcalendar/fullcalendar#7519]
### Checklist

- [X] I've already searched through [existing tickets](https://github.com/fullcalendar/fullcalendar/issues)
- [X] Other people will find this feature useful

### Is this feature for a specific connector (React/Angular/etc)?

React

### Feature Description

Just need an answer to this so we can move forward and I haven't been able to find anything about it.

**Comment by acerix** [comment]
No, there is no tracking built-in the library.  Please contact sales@fullcalendar.io for other inquiries.
