### ISSUE TITLE
[Bug] If headerToolBar={false}, when I click to open a day it renders empty

### ISSUE THREAD

**Issue by KarineBrandelli** [fullcalendar/fullcalendar#7522]
### Reduced Test Case

https://fullcalendar.io/docs/navLinks-demo

### Do you understand that if a reduced test case is not provided, we will intentionally delay triaging of your ticket?

- [X] I understand

### Which connector are you using (React/Angular/etc)?

React

### Bug Description

Bug after update from v5 to v6.

To edit the demo, click on `Edit on codepen` on the right upper corner and then comment the `headerToolBar` object or set it to `false`. Then, click on a random day. It renders empy.

In my project, when the calendar renders with the `headerToolBar={false}`, when I click on a day, the day opens empty.

I can't set the `headerToolBar` as a object because I don't need that header on my application.
Is there a way to set it 'empty' so the calendar can work?
I've tried to set it as a empty object, but it didn't worked.

I've really don't know what to do!

```ts
  return (
    <FullCalendar
      ref={setCalendarRef}
      editable
      droppable
      navLinks
      allDayText=''
      locale='pt-BR' // for 0-23 hour format
      forceEventDuration
      moreLinkText='mais'
      headerToolbar={false}
      headerToolbar={false}
      fixedWeekCount={false}
      plugins={[dayGridPlugin, timeGridPlugin, interactionPlugin]}
      slotLabelFormat={slotLabelFormat}
      dayPopoverFormat={dayPopoverFormat}
      dayHeaderContent={customHeader}
      dayCellContent={customDayCell}
      initialDate={date}
      {...otherProps}
    />
  )
```

My calendar has to be view like this, 'clean', without any header:

![image](https://github.com/fullcalendar/fullcalendar/assets/108953489/61c343e0-fdd4-4aae-a7dd-a9129cf2c8da)

When I click on a random day:

![image](https://github.com/fullcalendar/fullcalendar/assets/108953489/9e60e097-29d1-4fd1-b7d8-a9dec5fbe3c0)

And also the circle behind the current day is rendering twice, don't know why.

**Comment by KarineBrandelli** [comment]
@acerix Hey Dylan, can you take a look?

**Comment by acerix** [comment]
The toolbar can be disabled with `headerToolbar: false`, e.g.:

https://codepen.io/acerix/pen/LYqOVVM?editors=001

Please post a [runnable, stripped-down demonstration](http://fullcalendar.io/wiki/Reduced-Test-Cases/) if there is a bug.

**Comment by KarineBrandelli** [comment]
As I said, if `headerToolbar: false`, the day opens empty.

And the runnable example is also described in the issue.

![image](https://github.com/fullcalendar/fullcalendar/assets/108953489/a2f96f91-9543-419e-ae13-f907e951983e)

**Comment by acerix** [comment]
I just realized the issue is when clicking the day numbers.

As is explained in the docs, the destination views are determined by the `headerToolbar`, so if you are not using a header you need to set the destination view in `navLinkDayClick`:

https://codepen.io/acerix/pen/vYbWPZy?editors=001

**Comment by KarineBrandelli** [comment]
My apologies, I thought I was clear that you had to click on the number of the day!

Thanks for the feedback, I had to hide the header to make it work momentarily because I needed to close the task, but when I return to this project, I will make the necessary update.

Thanks again @acerix, if I have any others questions I'll let you know.
