### ISSUE TITLE
Background event elements are undefined in `eventDidMount` when using Vue slot template for eventContent

### ISSUE THREAD

**Issue by acerix** [fullcalendar/fullcalendar#7524]
### Reduced Test Case

https://stackblitz.com/edit/github-wn9aqn-17m3t8?file=app.vue

### Do you understand that if a reduced test case is not provided, we will intentionally delay triaging of your ticket?

- [X] I understand

### Which connector are you using (React/Angular/etc)?

Vue

### Bug Description

Starting in 6.1.9 `arg.el` in `eventDidMount` is undefined for background events using slot templates.

Reported in https://fullcalendar.freshdesk.com/a/tickets/7427

**Comment by arshaw** [comment]
This bug has been fixed in [v6.1.10](https://github.com/fullcalendar/fullcalendar/releases/tag/v6.1.10)

Updated repro: https://stackblitz.com/edit/github-wn9aqn-55gh5t?file=package.json
