### ISSUE TITLE
Angular version 17 support

### ISSUE THREAD

**Issue by stehag** [fullcalendar/fullcalendar#7525]
### Checklist

- [X] I've already searched through [existing tickets](https://github.com/fullcalendar/fullcalendar/issues)
- [X] Other people will find this feature useful

### Is this feature for a specific connector (React/Angular/etc)?

Angular

### Feature Description

Please add Angular version 17 support.

**Comment by sudeepiic** [comment]
yup, doing `npm i --legacy-peer-deps` for the moment

**Comment by arshaw** [comment]
[v6.1.10](https://github.com/fullcalendar/fullcalendar/releases/tag/v6.1.10) has support for Angular 17

**Comment by sbschorer** [comment]
Could you please mention Angular 17 support in the README file?

**Comment by AdrianRomanski** [comment]
@arshaw 

There is a little mistake on https://www.npmjs.com/package/@fullcalendar/angular

Supported Angular Versions
@fullcalendar/angular version 6 supports Angular 12 - 16
