### ISSUE TITLE
Angular 17 support

### ISSUE THREAD

**Issue by dries-2002** [fullcalendar/fullcalendar#7527]
### Checklist

- [X] I've already searched through [existing tickets](https://github.com/fullcalendar/fullcalendar/issues)
- [X] Other people will find this feature useful

### Is this feature for a specific connector (React/Angular/etc)?

Angular

### Feature Description

Currently, the supported Angular versions for @fullcalendar/angular are v12 through v16. Upgrading an Angular project that uses @fullcalendar/angular to v17 is therefore not possible.

**Comment by acerix** [comment]
I believe this existing ticket captures this need:
https://github.com/fullcalendar/fullcalendar/issues/7525
↑
Please visit the above issue, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates.
