### ISSUE TITLE
EventDidMount is called even after removeAllEvents() is called

### ISSUE THREAD

**Issue by yoancutillas** [fullcalendar/fullcalendar#7530]
### Reduced Test Case

https://codepen.io/yoancutillas/pen/poGWjem?editors=0011

### Do you understand that if a reduced test case is not provided, we will intentionally delay triaging of your ticket?

- [X] I understand

### Which connector are you using (React/Angular/etc)?

No connector (vanilla JS)

### Bug Description

Hi,

I am calling removeAllEvents() in DatesSet callback.
But even though events are correctly deleted, EventDidMount is still called for each (non-existing) event afterwards. The problem also spread to other callbacks such as eventClassNames.

In the codepen, I have added logs to highlight that events are deleted before EventDidMount, so EventDidMount (and the others) should not be called.

The problem leads to a js fatal error in my use case because, you know, my EventDidMount (and so on) code is using variables that have been deleted when removing the events.

Thanks again for your great tool and support :)
Yoan

**Comment by acerix** [comment]
This happens because the events are not loaded until after `datesSet()` which is called when the date is changed.  This can be seen by adding a log message when the events are added:

https://codepen.io/acerix/pen/gOqXpRP?editors=0010

If you are trying to remove events when the date is changed, you can supply the events "as a function" and have it not return the events that should be removed.

https://fullcalendar.io/docs/events-function

**Comment by yoancutillas** [comment]
Thank you @acerix, unfortunately, I have done as you said, but the problem still occurs : the events are added first with `addEventSource`, then they are removed on `datesSet`, but `eventDidMount` is still triggered. I have edited my code pen so you can see (I need to use `addEventSource` in my use case): https://codepen.io/yoancutillas/pen/poGWjem?editors=0011

If as you say, events are loaded _after_  `datesSet`, and if events are deleted _on_ `datesSet` (that is, before events are loaded), then, events should not be loaded, right?

**Comment by acerix** [comment]
The events do no actually get rendered when `addEventSource` is called, they are always rendered after the date is changed (after `datesSet`).

**Comment by yoancutillas** [comment]
I can see that, but this is not my question, the question is: 
events are rendered _**after**_ `datesSet` right?
if I delete events _**on**_ `datesSet` (that is, before they are rendered), then, events should not be rendered, right?
then, `eventDidMount` should not be triggered.

Your docs says:
> eventDidMount - called right after the element has been added to the DOM.

Deleted events should not be added to the DOM, right?

Can I have your thoughts as well @arshaw?

The result is good in the end: events are not rendered, the problem is that `eventDidMount` (and the other `eventClassNames`, etc...) should not be called for deleted events, can you acknowledge that or explain the logic otherwise?

**Comment by acerix** [comment]
`event.remove()` removes the rendered event, not how the event is defined, so it gets recreated after the date is changed.

**Comment by yoancutillas** [comment]
Ok fine, let's trigger the `eventDidMount` callback on a deleted event, `eventClassNames` on an event that is not rendered, pretend that it is normal, and close that annoying issue, sorry for wasting your time.
