### ISSUE TITLE
Getting extendedProps in dateClick event

### ISSUE THREAD

**Issue by apuatcfbd** [fullcalendar/fullcalendar#7532]
### Checklist

- [X] I've already searched through [existing tickets](https://github.com/fullcalendar/fullcalendar/issues)
- [X] Other people will find this feature useful

### Is this feature for a specific connector (React/Angular/etc)?

No connector in particular

### Feature Description

`extendedProps` is not availble in `dateClick` event's parameter. that is useful sometimes.

**Comment by acerix** [comment]
`dateClick` only applies to a date cell, not to events in the calendar, so it does not have event properties.  The `jsEvent` param refers to the JS click "event".

**Comment by joelstein** [comment]
FWIW, I was also looking for this.

My thinking is that I already provided event data to FullCalendar, it knows which events are being rendered on a given day, and when I click that day, I'd like to work with the data displayed on that day.

I can get it other ways, but I see it as a useful prop to include in the `dateClick` handler.
