### ISSUE TITLE
Using addEvent() on dateClick() recreates all previous created events from cache

### ISSUE THREAD

**Issue by thepi00** [fullcalendar/fullcalendar#7536]
### Reduced Test Case

https://codepen.io/thepi/pen/XWOZwWj

### Do you understand that if a reduced test case is not provided, we will intentionally delay triaging of your ticket?

- [X] I understand

### Which connector are you using (React/Angular/etc)?

No connector (vanilla JS)

### Bug Description

I am using the  timeGridWeek view to add events by clicking a slot on the calendar. With dateClick() I display a modal which asks to add the specific date as an event with addEvent(). The first event is created ok, when I click another slot and add another event the previous event is duplicated. Every time I add new event all previous events added are recreated from cache.

Full code in codepen and
https://codepen.io/thepi/pen/XWOZwWj

https://github.com/fullcalendar/fullcalendar/assets/5021260/3bf81dc1-e3c1-4053-90a9-c2f21330d07f

**Comment by acerix** [comment]
It doesn't seem like a bug in the calendar but with how the modal is setup.  The console shows `addEvent` is being called multiple times:

https://codepen.io/acerix/pen/xxMWmqx?editors=1111
