### ISSUE TITLE
Fullcalendar year view does not support keyboard navigation between days within a month for accessibility

### ISSUE THREAD

**Issue by PhilCousineau** [fullcalendar/fullcalendar#7538]
### Checklist

- [X] I've already searched through [existing tickets](https://github.com/fullcalendar/fullcalendar/issues)
- [X] Other people will find this feature useful

### Is this feature for a specific connector (React/Angular/etc)?

No connector in particular

### Feature Description

We should be able use up down left right arrows key navigation within month (month and year views), and tab between months in year view. This could be a configurable option.
Currently the date is a link, when set as an optional setting (navLinks set to true)

**Comment by acerix** [comment]
I believe this existing ticket captures this need:
https://github.com/fullcalendar/fullcalendar/issues/6528
↑
Please visit the above issue, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates.
