### ISSUE TITLE
Allow to select whole week on dayGridMonth and also through months on multimonth view.

### ISSUE THREAD

**Issue by rodrigo-gsilva** [fullcalendar/fullcalendar#7549]
### Checklist

- [X] I've already searched through [existing tickets](https://github.com/fullcalendar/fullcalendar/issues)
- [X] Other people will find this feature useful

### Is this feature for a specific connector (React/Angular/etc)?

No connector in particular

### Feature Description

I have done some workarounds to achieve this using "fake background events" on dayGridMonth  view.

**Comment by acerix** [comment]
I believe this existing ticket captures this need:
https://github.com/fullcalendar/fullcalendar/issues/7183
↑
Please visit the above issue, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates.
