### ISSUE TITLE
Feature: add the Persian/Jalali calendar

### ISSUE THREAD

**Issue by parsmmm** [fullcalendar/fullcalendar#7553]
### Checklist

- [X] I've already searched through [existing tickets](https://github.com/fullcalendar/fullcalendar/issues)
- [X] Other people will find this feature useful

### Is this feature for a specific connector (React/Angular/etc)?

Other

### Feature Description

Hello,
Please add the Persian or Jalali calendar. and we need the dates to be displayed in the Persian format
It has also been discussed [here ](https://github.com/fullcalendar/fullcalendar/issues/1813)before 

[This project ](https://github.com/mzangeneh/fullcalendar-shamsi)has already been created, but for version 5.5.1, is it possible to add this to the new release of fullcalender?

**Comment by acerix** [comment]
I believe the existing ticket captures this need:
https://github.com/fullcalendar/fullcalendar/issues/1813
↑
Please visit the above issue, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates.
