### ISSUE TITLE
Leading zero for hour differs between browsers in event time display

### ISSUE THREAD

**Issue by espen** [fullcalendar/fullcalendar#7559]
### Reduced Test Case

https://fullcalendar.io/demos

### Do you understand that if a reduced test case is not provided, we will intentionally delay triaging of your ticket?

- [X] I understand

### Which connector are you using (React/Angular/etc)?

No connector (vanilla JS)

### Bug Description

Leading zero is not shown in Safari and Chrome but is shown in Firefox. Event shows 8:00 instead of 08:00.

Reproduce:
1. Select Locales from demos.
2. Select 'en-gb'.
3. Event shows 8:00 instead of 08:00 in Safari and Chrome. Shows 08:00 in Firefox.

**Comment by acerix** [comment]
The time format is determined by the browser by default, you can use a formatting plugin like Moment.js to make the format consistent in all browsers:

https://fullcalendar.io/docs/moment-plugin

**Comment by espen** [comment]
Thanks, I assumed I was using Moment as I was using the Moment Timezone plugin. I have added it now. However this seems to originate from DEFAULT_TABLE_EVENT_TIME_FORMAT being set to hour: 'numeric' instead of '2-digit'. I'm guessing it is up to the browser Intl to include the leading zero for numeric, however I would argue 2-digits should be used in my locale. If so, would it be correct to make a PR for specifying eventTimeFormat to have hour: '2-digit' in my locale? It doesn't look like the other locales have eventTimeFormat set. Should the locale set this or is it up to the developer to specify to ensure browser consistency?
