### ISSUE TITLE
Accesibility: Custom components in eventContent comes under anchor tag

### ISSUE THREAD

**Issue by rohanmondalSimpplr** [fullcalendar/fullcalendar#7569]
### Checklist

- [X] I've already searched through [existing tickets](https://github.com/fullcalendar/fullcalendar/issues)
- [X] Other people will find this feature useful

### Is this feature for a specific connector (React/Angular/etc)?

React

### Feature Description

We are trying to pass our custom components to eventContent in React, when we are passing any custom components(We are using button for event summary modal launcher) to eventContent  it is appearing under anchor tag, which is raising an accessibility issue, as button element is coming under the anchor element, which is not correct in accessibility point of view.

Added a video for the problem
https://github.com/fullcalendar/fullcalendar/assets/139096654/55507f15-89d6-4642-ab43-0c7cc210e18d

A MVP to visualize the problem:
https://stackblitz.com/edit/github-nfxlxt?file=src%2FDemoApp.jsx

![Screenshot 2024-01-12 at 4 44 15 PM](https://github.com/fullcalendar/fullcalendar/assets/139096654/c6380789-4796-40b0-b73d-4daf4465c6d5)

**Comment by HarlesPilter** [comment]
Linked to https://github.com/fullcalendar/fullcalendar/issues/5710

**Comment by acerix** [comment]
I believe this existing ticket captures this need:
https://github.com/fullcalendar/fullcalendar/issues/5710
↑
Please visit the above issue, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates.
