### ISSUE TITLE
Accessibility: Current Day Cell Date not available in More Events 

### ISSUE THREAD

**Issue by palakrathor** [fullcalendar/fullcalendar#7570]
### Checklist

- [X] I've already searched through [existing tickets](https://github.com/fullcalendar/fullcalendar/issues)
- [X] Other people will find this feature useful

### Is this feature for a specific connector (React/Angular/etc)?

React

### Feature Description

Inside the MoreEvents component, we do not have access to the current Day Cell's Date and hence we are facing this accessibility issue 
(Recommended =>aria-label="2 more events for 30th October" & what is possible as of now => aria-label="2 more events")

[Recommendation from Level Access]
Ensure link text is meaningful within context. A link's purpose must be determinable from the link's accessible name alone or in combination with the immediately surrounding paragraph, table cell, or associated table header. Good accessible names are both concise and descriptive.

[Compliant Code Example]
```
<a tabindex="0" title="Show 2 more events" aria-expanded="false" aria-controls="" 
class="fc-daygrid-more-link fc-more-link" 
aria-label="2 more events for 30th October">
(...)
</a>
```

<img width="1548" alt="Screenshot 2024-01-12 at 10 55 15 AM" src="https://github.com/fullcalendar/fullcalendar/assets/139961895/503fec1e-c41d-43a7-9375-1db5f7edf9a0">

Following are the properties of MoreEvents:
<img width="1728" alt="Screenshot 2024-01-12 at 11 59 48 AM" src="https://github.com/fullcalendar/fullcalendar/assets/139961895/c0f4debd-e6e1-447a-a6ce-57a2fffa7ef4">

Inside the **MoreEvents** component, we have the access only till the **clickedDate** property, and we have tried using it inside the aria-label, but it is not giving the expected results (it either puts the today's date in all calendarDayCells or it uses the date whose MoreEvents was clicked most recently).

https://github.com/fullcalendar/fullcalendar/assets/139961895/eb1bf55e-a0ee-4e6f-b136-ae2e808ace36

**Comment by acerix** [comment]
I believe this existing ticket captures this need:
https://github.com/fullcalendar/fullcalendar/issues/6095
↑
Please visit the above issue, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates.
