### ISSUE TITLE
Events lose vertical offset and overlap after navigating to another date with JSX `eventContent`

### ISSUE THREAD

**Issue by zhangjett** [fullcalendar/fullcalendar#7574]
### Reduced Test Case

https://stackblitz.com/edit/stackblitz-starters-gzvquz?file=app%2Fpage.tsx

### Do you understand that if a reduced test case is not provided, we will intentionally delay triaging of your ticket?

- [X] I understand

### Which connector are you using (React/Angular/etc)?

React

### Bug Description

https://github.com/fullcalendar/fullcalendar/assets/17883179/d63f3dd7-5f7e-49a5-82d7-428ade54e290

![1705390690254](https://github.com/fullcalendar/fullcalendar/assets/17883179/d8919a04-f543-4ca8-ae85-978b1d035517)

![1705390816921](https://github.com/fullcalendar/fullcalendar/assets/17883179/4cb24b0b-d7bc-4e39-9a7b-da5bc9f24b8f)

Use the React connector,set eventContent with React JSX nodes.
When change view, .fc-timeline-event-harness top style is error.

**Comment by arshaw** [comment]
Fixed in [v6.1.11](https://github.com/fullcalendar/fullcalendar/releases/tag/v6.1.11)

@fullcalendar/react was getting tripped up on React strict-mode.

Updated repro:
https://stackblitz.com/edit/stackblitz-starters-fmnrar?file=package.json,package-lock.json
