### ISSUE TITLE
I am not able to gray-out resources which are outside start and end date

### ISSUE THREAD

**Issue by aman-gojariya** [fullcalendar/fullcalendar#7576]
### Reduced Test Case

https://codepen.io/Aman-Gojariya/pen/poYPpMJ?editors=0010

### Do you understand that if a reduced test case is not provided, we will intentionally delay triaging of your ticket?

- [X] I understand

### Which connector are you using (React/Angular/etc)?

Angular

### Bug Description

We want grayout all days which is not in between start and end date of **"a" resource**

**Comment by acerix** [comment]
The business hours feature is only for times of day and days of the week, it doesn't work for a date range.  You can instead add a background event to greyout a date range:

https://fullcalendar.io/docs/background-events

**Comment by aman-gojariya** [comment]
Works fine. Thank youu @acerix !!
