### ISSUE TITLE
Timeline Group - Multiple Levels

### ISSUE THREAD

**Issue by michalfordonski** [fullcalendar/fullcalendar#7577]
### Checklist

- [X] I've already searched through [existing tickets](https://github.com/fullcalendar/fullcalendar/issues)
- [X] Other people will find this feature useful

### Is this feature for a specific connector (React/Angular/etc)?

No connector in particular

### Feature Description

It would be useful to be able to set multi-level groups in the timeline. At the moment, only the division can be displayed: Building -> Room. A multi-level split would handle the Continent, Country, City, Street, Building, Hall view. In the current mode, the grouping view breaks down as separate locations and shows mixed groups relative to their occurrence. You could provide a grouping path with a dot, such as an IP address, but longer than 4 sections.

**Comment by acerix** [comment]
Resources can have multiple levels by adding children:

https://fullcalendar.io/docs/Resource-getChildren

If you mean something else, it may help to include a mock-up of what you are looking for.
