### ISSUE TITLE
Maximum call stack size exceeded at DayGridSegHierarchy.splitEntry

### ISSUE THREAD

**Issue by anahitsargsyan169** [fullcalendar/fullcalendar#7589]
### Reduced Test Case

https://stackblitz.com/edit/github-l5uyfh-ri23kx?file=src%2FDemoApp.jsx,src%2Fevent-utils.js

### Do you understand that if a reduced test case is not provided, we will intentionally delay triaging of your ticket?

- [X] I understand

### Which connector are you using (React/Angular/etc)?

React

### Bug Description

User has a calendar with 893 events, when user opens calendar, we get white screen and this error.

![Screenshot from 2024-02-01 11-29-56](https://github.com/fullcalendar/fullcalendar/assets/88271591/a9bbfdb3-65cf-4a9d-8c8c-5dec587b1e8d)

Here is the demo with that events, try to show all and you will see white screen
https://stackblitz.com/edit/github-l5uyfh-ri23kx?file=src%2FDemoApp.jsx,src%2Fevent-utils.js

I tried to change dayMaxEvents count  /to 3 f.e./ and the error disappeared. From what I've tried, it works with any value except 2.
![Screenshot from 2024-02-01 12-02-35](https://github.com/fullcalendar/fullcalendar/assets/88271591/a7c266ee-d37e-47a9-8b04-5e1aca55885b)

I also tried to add events one by one and didn't get an error message until I tried to change the current date. The calendar is frozen, and this is what I got.

![Screenshot from 2024-02-01 12-01-05](https://github.com/fullcalendar/fullcalendar/assets/88271591/33516ce4-833f-47eb-91d8-ae044b200d12)

Need to fix this asap. Please, help.

**Comment by acerix** [comment]
I believe this existing ticket captures this need:
https://github.com/fullcalendar/fullcalendar/issues/7462
↑
Please visit the above issue, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates.

Setting `eventOrder="title"` may work as a workaround:

https://stackblitz.com/edit/github-l5uyfh-igmkwt?file=src%2FDemoApp.jsx,src%2Fevent-utils.js
