### ISSUE TITLE
ThirdPartyDraggable does not handle HTML drag events

### ISSUE THREAD

**Issue by FeelDee** [fullcalendar/fullcalendar#7593]
### Reduced Test Case

https://codepen.io/pducas-theatrixx/pen/KKEeBKv

### Do you understand that if a reduced test case is not provided, we will intentionally delay triaging of your ticket?

- [X] I understand

### Which connector are you using (React/Angular/etc)?

No connector (vanilla JS)

### Bug Description

I work on an application using a custom drag and drop handler based on pure HTML dragging (draggable elements are tagged with the [`draggable`](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/draggable) attribute). Here is a link to [HTML Drag and Drop API](https://developer.mozilla.org/en-US/docs/Web/API/HTML_Drag_and_Drop_API) for reference.

We used the `ThirdPartyDraggable` class to integrate FullCalendar into this dragging system, but it does not work as intended. When an element is dragged over or dropped onto the calendar, it is not acknowledged by the view. However, if you then move he mouse and click on the calendar, an event will be created. This behaviour is the same in month, week and day grids.

I looked into the code, and I think it is linked to the `PointerDragging` class only listening to `mousemove` and `mouseup` to handle drag and drop events. When an element has the `"draggable"="true"` tag, these events are replaced respectively by `dragover` and `dragend`.

**Comment by acerix** [comment]
Thanks for the report and PR. 

There is an existing ticket which appears to be for the same issue so believe it captures this need:
https://github.com/fullcalendar/fullcalendar/issues/7492
↑
Please visit the above issue, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates.

**Comment by gabdusch** [comment]
I work with @FeelDee on this project. 

@acerix thanks, but the PR you reference does not provide a path to support native events, only a solution for those using SortableJS (which is not our case. 

Will you consider reopening our PR and merging it? We provide an easy drop-in solution with no breaking changes.

**Comment by acerix** [comment]
I closed the new issue as it seems to be the same underlying problem, it seems to me now that the original issue is not specific to SortableJS.

I didn't review your PR but I assume it would also fix that issue with SortableJS. Your PR is still open and I just assigned it for review.
