### ISSUE TITLE
Sticky time column in timegrid view

### ISSUE THREAD

**Issue by Hecute** [fullcalendar/fullcalendar#7598]
### Checklist

- [X] I've already searched through [existing tickets](https://github.com/fullcalendar/fullcalendar/issues)
- [X] Other people will find this feature useful

### Is this feature for a specific connector (React/Angular/etc)?

No connector in particular

### Feature Description

Hi, I'd love to have option like **stickyHeaderDates** but with time column. 
I know that views like **timeline** and **vertical resource** have feature like this.
I created timegrid month view with horizontal scroll and seeing hours would be very useful!

**Comment by acerix** [comment]
The times should stay visible if scrolling is enabled with `dayMinWidth`, this page has more info:

https://fullcalendar.io/docs/dayMinWidth

**Comment by Hecute** [comment]
> The times should stay visible if scrolling is enabled with `dayMinWidth`, this page has more info:
> 
> https://fullcalendar.io/docs/dayMinWidth

Oh, I didn't know that, but unfortunately scrollgrid plugin don't work properly in my project :(. But I guess it's for another issue
