### ISSUE TITLE
I want to open custom context menu on right click of timeline calendar block and need Resource Id and Clicked block date in Angular Framework

### ISSUE THREAD

**Issue by aman-gojariya** [fullcalendar/fullcalendar#7599]
### Checklist

- [X] I've already searched through [existing tickets](https://github.com/fullcalendar/fullcalendar/issues)
- [X] Other people will find this feature useful

### Is this feature for a specific connector (React/Angular/etc)?

Angular

### Feature Description

![image](https://github.com/fullcalendar/fullcalendar/assets/25817702/39bff213-b2e1-438e-b48e-57d3e29d90ad)

**Comment by acerix** [comment]
I believe this existing ticket captures this need:
https://github.com/fullcalendar/fullcalendar/issues/2748
↑
Please visit the above issue, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates.

**Comment by aman-gojariya** [comment]
No @acerix 
I want this feature on timeline calendar as well. Also, I want a clicked block resourceId and clicked block date.
#2748 is only for basic calendar not resource-timeline calendars. Right?

**Comment by acerix** [comment]
I believe the issue I mentioned will also cover the timeline view, similar to `dateClick` which also works in that view.
