### ISSUE TITLE
Resource View (vertical, multiple columns per day)

### ISSUE THREAD

**Issue by arshaw** [fullcalendar/fullcalendar#760]
Originally reported on Google Code with ID 490
```
It would be nice to manage several users on week/day view using seperated columns.

I've started to implement this functionality.
(Fork: http://github.com/calendarlover/fullcalendar)
This first commit only contains small updates, and a example file (multi-users.html)

The all-day mode seems incompatible with this kind of view, hence it has to be disabled
to 
allow multi-user mode.

TODO:
- Fix overlapping bug which occurs when two events are displayed in the same time but
for 
different users
- Add callback on drop to enable/disable move between different users with eventually
an 
update of event.userId
- Add filter system to mask/unmask quickly specific user columns
- Handle short names in case of long usernames (quickfix could be using css: 
overflow:hidden)

If you want to implement some of these methods please let me know as for now I have
to stop 
for a while the developpement of this feature.
```

Reported by `ljaures` on 2010-05-20 12:01:10

**Comment by arshaw** [comment]
discussion has been moved to the Scheduler's issue tracker: https://github.com/fullcalendar/fullcalendar-scheduler/issues/5

**Comment by joe11joe** [comment]
I am using the fullcalendar month view to display my time slots as events. Following is the current view of my Month view with events
![day view original](https://cloud.githubusercontent.com/assets/17080934/16485174/02faf042-3edb-11e6-9ff8-9ff4ea5afaae.jpg)

I want to display events in two columns in a day like the following screen.
![month view](https://cloud.githubusercontent.com/assets/17080934/16485189/20fea5ac-3edb-11e6-8549-ec952404d662.jpg)

Can you help me in this regard. Thank you in advance.
