### ISSUE TITLE
Css conflict - Blue day header instead of black

### ISSUE THREAD

**Issue by systemyokienne** [fullcalendar/fullcalendar#7601]
### Reduced Test Case

#

### Do you understand that if a reduced test case is not provided, we will intentionally delay triaging of your ticket?

- [X] I understand

### Which connector are you using (React/Angular/etc)?

No connector (vanilla JS)

### Bug Description

I have problem with with css in my project. Day word is blue instead of black, as on the picture below. 
I use bootstrap 5 and have set themeSystem to bootstrap5, but still the same. Tried also standard theme, with no result.

![obraz](https://github.com/fullcalendar/fullcalendar/assets/56561081/f96cf156-d872-4c0a-b127-0cef7ae1c12b)

**Comment by acerix** [comment]
I believe this is intentional when using `navLinks` to show that those are links.  

Please post a [runnable, stripped-down demonstration](http://fullcalendar.io/wiki/Reduced-Test-Cases/) if there is a bug. Would really appreciate it because the time saved reproducing will be time spent fixing.
