### ISSUE TITLE
Resource-group-specific initially expanded/collapsed states (resourcesInitiallyExpanded)

### ISSUE THREAD

**Issue by JohnBDonner** [fullcalendar/fullcalendar#7604]
### Checklist

- [X] I've already searched through [existing tickets](https://github.com/fullcalendar/fullcalendar/issues)
- [X] Other people will find this feature useful

### Is this feature for a specific connector (React/Angular/etc)?

No connector in particular

### Feature Description

I couldn't find any way to initially expand specific resources, it seems to be an all-or-nothing flag with `resourcesInitiallyExpanded`. It'd be great to be able to do it on a per-resource-group basis, since some resource groups are very large.

Don't currently have a work around.

I'm using the react connector, but this should be agnostic of any specific connector.

**Comment by acerix** [comment]
I believe this existing ticket captures this need:
https://github.com/fullcalendar/fullcalendar/issues/4832
↑
Please visit the above issue, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates.
