### ISSUE TITLE
nowIndicator in resourceTimelineWeek not right setted

### ISSUE THREAD

**Issue by OFAlexandre** [fullcalendar/fullcalendar#7605]
### Reduced Test Case

See my screenshot in description

### Do you understand that if a reduced test case is not provided, we will intentionally delay triaging of your ticket?

- [X] I understand

### Which connector are you using (React/Angular/etc)?

No connector (vanilla JS)

### Bug Description

I wanted to know if this is the desired behaviour or if it's a bug?
In my example, it's 10:53 but the red line is displayed an hour earlier.

![image](https://github.com/fullcalendar/fullcalendar/assets/160841952/4563637b-677f-4b8e-8d57-aa591efbe4cb)

Thanks in advance for your Support !

**Comment by acerix** [comment]
I believe this existing ticket captures this need:
https://github.com/fullcalendar/fullcalendar/issues/6175
↑
Please visit the above issue, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates.
