### ISSUE TITLE
listDay doesn't show time with multiday events

### ISSUE THREAD

**Issue by abejenaru** [fullcalendar/fullcalendar#7606]
Hi,

It seems to be a regression with this closed issue
https://github.com/fullcalendar/fullcalendar/issues/4296

I have also prepared a CodePen https://codepen.io/abejenaru/pen/xxBNYKX

**Comment by acerix** [comment]
This doesn't seem like that same issue as the one you linked, that is about the times from the first/last day showing on each day.

In your demo, the event does not show any time which I believe is intended. Are you looking for the time to show as "all day" in this case?

**Comment by abejenaru** [comment]
Hi, I saw the section Expected results in https://github.com/fullcalendar/fullcalendar/issues/4296 and presumed it was a regression (emphasis mine):

> Expected Result:
> The individual days for the listDay should be consistent with the listWeek day breakdowns.
> _Preferred result would be that the listDay will show all-day for July 30, 2018 thru August 6, 2018_

> In your demo, the event does not show any time which I believe is intended. Are you looking for the time to show as "all day" in this case?

IMO, that would be the expected behavior. I checked in Outlook and Apple Calendar and they show the intermediate days as all-day events.

**Comment by acerix** [comment]
Thanks for the info.  I believe this existing ticket captures this need:
https://github.com/fullcalendar/fullcalendar/issues/7518
↑
Please visit the above issue, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates.
