### ISSUE TITLE
dayGridMonth view showing the date and month in the day header

### ISSUE THREAD

**Issue by arunkumar413** [fullcalendar/fullcalendar#7613]
### Reduced Test Case

https://stackblitz.com/edit/vitejs-vite-cujyid?file=index.html,src%2FApp.css,src%2FApp.jsx,src%2Findex.css&terminal=dev

### Do you understand that if a reduced test case is not provided, we will intentionally delay triaging of your ticket?

- [X] I understand

### Which connector are you using (React/Angular/etc)?

No connector (vanilla JS)

### Bug Description

Hi Team,

I'm giving the `dayHeaderFormat` as below. But If I switch to `dayGridMonth` it is also showing the date and month which is not related to the current month.

```
dayHeaderFormat:{ weekday: 'short', month: 'short', day: 'numeric', omitCommas: false }

```

![fullCalError](https://github.com/fullcalendar/fullcalendar/assets/7776779/2296e660-0973-481d-9505-9067c331a6d1)

**Comment by arunkumar413** [comment]
Also in the browser developer console I see a duplicate plugin issue warning.
![duplicatePluginIssue](https://github.com/fullcalendar/fullcalendar/assets/7776779/a6fa6c49-be56-4218-8b94-d758a2fc7425)

**Comment by acerix** [comment]
I believe this existing ticket captures this need:
https://github.com/fullcalendar/fullcalendar/issues/5854
↑
Please visit the above issue, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates.
