### ISSUE TITLE
Cannot set firstDay as Monday with locale vi in resourceTimelineDay

### ISSUE THREAD

**Issue by xiaojiudev** [fullcalendar/fullcalendar#7614]
### Reduced Test Case

https://codesandbox.io/p/devbox/holy-sun-ctz97n?file=%2Fapp%2Fpage.tsx%3A7%2C2

### Do you understand that if a reduced test case is not provided, we will intentionally delay triaging of your ticket?

- [X] I understand

### Which connector are you using (React/Angular/etc)?

React

### Bug Description

I cannot set firstDay to change the default day from Sunday to Monday in the nextjs project with resourceTimelinePlugin. My code is here: https://codesandbox.io/p/devbox/holy-sun-ctz97n?file=%2Fapp%2Fpage.tsx%3A7%2C2
![image](https://github.com/fullcalendar/fullcalendar/assets/89904184/43d289c2-991f-4fc5-bc60-6fd30b4b075a)

**Comment by acerix** [comment]
When I test your demo, the first day that shows is Monday (04/03/2024):

![Screenshot_2024-03-04_17-55-33](https://github.com/fullcalendar/fullcalendar/assets/379534/9db32203-32d3-49dc-8a96-ca5b9ea22675)

Let me know if I am missing something to reproduce the issue.

**Comment by xiaojiudev** [comment]
> When I test your demo, the first day that shows is Monday (04/03/2024):
> 
> ![Screenshot_2024-03-04_17-55-33](https://github.com/fullcalendar/fullcalendar/assets/379534/9db32203-32d3-49dc-8a96-ca5b9ea22675)
> 
> Let me know if I am missing something to reproduce the issue.

Because maybe yesterday was Monday at your current time. Today in Vietnam is Tuesday, and my schedule shows the firstday is Tuesday LMAO.

**Comment by acerix** [comment]
I see now it's starting the week with the current day.

The `firstDay` setting only applies when the `duration` of the view is set in weeks:

https://codesandbox.io/p/devbox/vigilant-sky-g9d68d?file=%2Fapp%2Fpage.tsx%3A41%2C28

**Comment by acerix** [comment]
Oops, I missed that, here is the public link: https://codesandbox.io/p/devbox/vigilant-sky-g9d68d?file=%2Fapp%2Fpage.tsx

**Comment by xiaojiudev** [comment]
> Oops, I missed that, here is the public link: https://codesandbox.io/p/devbox/vigilant-sky-g9d68d?file=%2Fapp%2Fpage.tsx

It works correctly, thank you so much. Have a nice day!
