### ISSUE TITLE
Right Click function for Date Cell

### ISSUE THREAD

**Issue by munasinghecm** [fullcalendar/fullcalendar#7616]
### Checklist

- [X] I've already searched through [existing tickets](https://github.com/fullcalendar/fullcalendar/issues)
- [X] Other people will find this feature useful

### Is this feature for a specific connector (React/Angular/etc)?

No connector in particular

### Feature Description

I have noticed that the fullcalendar only enables the right-click option for events on the calendar through the "eventDidMount" option. However, the right-click option for the date cell is not available and there is no "dateDidMount" or "dayDidMount" option. It would be beneficial if you could provide this feature as well.

**Comment by acerix** [comment]
I believe this existing ticket captures this need:
https://github.com/fullcalendar/fullcalendar/issues/2748
↑
Please visit the above issue, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates.
