### ISSUE TITLE
Failed to compile after installing Luxon3 plugin

### ISSUE THREAD

**Issue by nik32** [fullcalendar/fullcalendar#7621]
### Reduced Test Case

https://stackblitz.com/edit/hr-meheraj-vite-react-avouhr?file=src%2FApp.jsx

### Do you understand that if a reduced test case is not provided, we will intentionally delay triaging of your ticket?

- [x] I understand

### Which connector are you using (React/Angular/etc)?

React

### Bug Description

I just installed the luxon3 plugin and it produced the following error -
<img width="982" alt="image" src="https://github.com/fullcalendar/fullcalendar/assets/51018572/601d0c64-b69d-4022-bace-b8aecd5db015">

**Comment by acerix** [comment]
I tested the same with our React example project and didn't have this issue:

https://stackblitz.com/edit/github-rphwjv-tamcz5?file=src%2FDemoApp.jsx

The issue might be that your included packages are not compatible versions, all the calendar packages should be the same version.  It could also be something to do with React-Vite or something in your build settings, if you can narrow down what is causing this we can look into it.

**Comment by nik32** [comment]
@acerix I am using FullCalendar v6.0.3 but luxon 3 is v6.1.11... can that be the real problem (I tried updating FullCalendar from v6.0.3 to v6.1.11... the above error did not come but there was some other error... which might be due to a breaking change in v6.1.11)?

**Comment by acerix** [comment]
Yes, all "@fullcalendar/*" packages should be the same version.  Changes within major versions shouldn't break anything, the new error is also likely to do with incompatible package versions or build settings.

**Comment by nik32** [comment]
Thanks @acerix! You were right... I might have not made all the "@fullcalendar/*" packages on same version. After updating all the packages to same version... there was no breakage. Thanks a lot for the help @acerix!
