### ISSUE TITLE
Locale not set for all labels

### ISSUE THREAD

**Issue by leomayer** [fullcalendar/fullcalendar#7622]
### Reduced Test Case

https://stackblitz.com/edit/github-xr1qvt?file=src%2Fapp%2Fapp.component.html

### Do you understand that if a reduced test case is not provided, we will intentionally delay triaging of your ticket?

- [X] I understand

### Which connector are you using (React/Angular/etc)?

Angular

### Bug Description

Although I can change the `locale` for the init it will be applied only to the months name. 

The labels of the `prev,next today` are not affected nor the the titles of the list. 

Running the sample from 

https://fullcalendar.io/docs/localization

changes all the labels.

Note: The sample code for Angular 17 fails to build since 
```
      <h2>All Events ({{ currentEvents.length }})</h2>
```

should be changed to ` currentEvents()`.
![Bildschirmfoto vom 2024-03-11 16-57-00](https://github.com/fullcalendar/fullcalendar/assets/2641128/c5e1c7d6-e9bf-4249-99c8-00e4bfb3ba75)

**Comment by acerix** [comment]
You are likely missing the locale file such as `locales-all`.  Please post a [runnable, stripped-down demonstration](http://fullcalendar.io/wiki/Reduced-Test-Cases/) if there is a bug.

**Comment by leomayer** [comment]
Sorry, but that's ridiculous. I've added to the sample project just one line, namely locale.

How to strip down even more? Perhaps you could provide a working Angular 17 project which is stripped down? Would be great!

If not, I'll open an issue that the provided sample projects don't fulfill the requested requirements.

**Comment by acerix** [comment]
I missed your example, but yes it's missing the locale file, it works after loading that:

https://stackblitz.com/edit/github-xr1qvt-yb3trq?file=src%2Fapp%2Fapp.component.ts

**Comment by leomayer** [comment]
Thx for clarification. Stupid question: From where should I get the knowledge that `locales: allLocales,` are required?

In the [docs](https://fullcalendar.io/docs/localization) its not even mentioned nor any hint from where to import. I know now - perhaps somebody else would appreciate as well the info in advance.

Thx again
