### ISSUE TITLE
Lolale doesn't work in some browsers

### ISSUE THREAD

**Issue by saknzhar** [fullcalendar/fullcalendar#7626]
### Reduced Test Case

https://fullcalendar.io/demos

### Do you understand that if a reduced test case is not provided, we will intentionally delay triaging of your ticket?

- [X] I understand

### Which connector are you using (React/Angular/etc)?

No connector (vanilla JS)

### Bug Description

I created issue in stackoverflow, here's [link](https://stackoverflow.com/questions/78147459/fullcalendar-locale-doesnt-work-in-chorme-and-edge)

![Screenshot 2024-03-13 093203](https://github.com/fullcalendar/fullcalendar/assets/66307352/24903660-5f14-4c41-b463-1984384fb982)

I tested it with your demos:

https://fullcalendar.io/demos

https://fullcalendar.io/docs/v5/locale-demo

**Comment by acerix** [comment]
I believe this existing ticket captures this need:
https://github.com/fullcalendar/fullcalendar/issues/5683
↑
Please visit the above issue, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates.
