### ISSUE TITLE
RRule DTSTART is parsed differently when RRule config is passed as a string vs object

### ISSUE THREAD

**Issue by piotrpalek** [fullcalendar/fullcalendar#7628]
### Reduced Test Case

https://codesandbox.io/p/devbox/angry-lamarr-vj9m7x

### Do you understand that if a reduced test case is not provided, we will intentionally delay triaging of your ticket?

- [X] I understand

### Which connector are you using (React/Angular/etc)?

No connector (vanilla JS)

### Bug Description

As can be seen in the reduced test case, both events have the same "DTSTART" date in the same timezone. Despite that each event is displayed at different hours on the calendar.

Green event (object rrule) dtstart: "2024-01-03T17:15:00Z"
Blue event (string rrule) dtstart: "DTSTART=20240103T171500Z"

<img width="515" alt="image" src="https://github.com/fullcalendar/fullcalendar/assets/1474323/339aaa67-8a9f-478e-8557-87bc75215afd">

While I was investigating this I have also noticed that this line: https://github.com/fullcalendar/fullcalendar/blob/d26ef0e7677a7236b31a5b530826dfd5c9926c10/packages/rrule/src/recurring-type.ts#L71 seems to override the `dtstart` with the current date instead of the date that is supplied in the `res.rrule` value.

Not sure this is clear but maybe this picture will explain it a little bit better:

<img width="514" alt="image" src="https://github.com/fullcalendar/fullcalendar/assets/1474323/76d5d45e-7dd5-4097-a717-413202d95366">

**Comment by acerix** [comment]
I'm not able to see your test case, it says "Devbox not found".

Though there appears to be an error in that syntax which could cause this, I believe `DTSTART=2024...` should instead be `DTSTART:2024...`

**Comment by piotrpalek** [comment]
@acerix please try again, I didn't realize I hadn't shared the devbox.
