### ISSUE TITLE
Broken: Timeline date navigation

### ISSUE THREAD

**Issue by Invincibear** [fullcalendar/fullcalendar#7631]
### Reduced Test Case

https://codepen.io/Invincibear/pen/ZEZBVXM?editors=0010

### Do you understand that if a reduced test case is not provided, we will intentionally delay triaging of your ticket?

- [X] I understand

### Which connector are you using (React/Angular/etc)?

No connector (vanilla JS)

### Bug Description

Clicking on an individual day from the `resourceTimelineWeek` or `resourceTimelineMonth` view does not trigger `navLinkDayClick()`. Additionally, when `navLinkDayClick()` is not user-defined, FullCalendar navigates to unexpected views within the calendar.  Clicking week numbers to trigger `navLinkWeekClick()` appears to be correctly working.

Examples:
* Clicking a week number from the `resourceTimelineMonth` view navigates the user to the `dayGridWeek` view, and triggers `navLinkWeekClick()`
* Clicking an individual day from the `resourceTimelineMonth` view navigates the user to the `dayGridDay` view, and triggers `navLinkDayClick()`
* Clicking an individual day from the `resourceTimelineWeek` view navigatesthe user to the `dayGridMonth` view, and does not trigger `navLinkDayClick()`.

By contrast, from the `resourceDayGrid` views:
* Clicking a week number from the `dayGridMonth` view navigates the user to the `dayGridWeek` view, as expected, and triggers `navLinkWeekClick()`
* Clicking a day number from the `dayGridWeek` or `dayGridMonth` view navigates the user to the `dayGridDay` view, as expected, and triggers `navLinkDayClick()`

**Comment by Invincibear** [comment]
Trying to do some digging, and it seems that the timeline view might be a bag of fun. 
[buildNavLinkAttrs()](https://github.com/fullcalendar/fullcalendar-workspace/blob/f8d127ae2b1b134a74c10826b8341dedf0fc8464/premium/packages/timeline/src/TimelineHeaderTh.tsx#L91C7-L91C24) references `rowUnit` which is apparently [borked in timeline view](https://github.com/fullcalendar/fullcalendar-workspace/blob/f8d127ae2b1b134a74c10826b8341dedf0fc8464/premium/packages/timeline/src/TimelineHeaderTh.tsx#L30)?

**Comment by acerix** [comment]
I believe this existing ticket captures this need:
https://github.com/fullcalendar/fullcalendar/issues/4931
↑
Please visit the above issue, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates.
