### ISSUE TITLE
Recurring Events Not Showing at Correct Time After Changing TimeZone and Navigating Forward/Backward in Time

### ISSUE THREAD

**Issue by nicholascm** [fullcalendar/fullcalendar#7635]
### Reduced Test Case

https://codepen.io/nicholascm90/pen/eYogJOV?editors=0010

### Do you understand that if a reduced test case is not provided, we will intentionally delay triaging of your ticket?

- [X] I understand

### Which connector are you using (React/Angular/etc)?

React

### Bug Description

This occurs with no connector (codepen above) and also in my project, react. 

Using a recurring event with or without a tzid and setting the timezone prop on FullCalendar, the recurring event initially shows at the correct time adjusted for the timezone, however, navigating forward or backwards it gets out of sync again and shows at the wrong time. 

In the codepen, see that the event is set for 10:30 AM, America/New_York: 

Steps: 
1. Change the timezone to America/Chicago (see recurring event switches to 9:30 AM correctly)
2. Go backwards one day in time, and see that tz is still America/Chicago, but event has moved back to 10:30 AM

My expectation was that it should continue to show at 9:30 AM.

**Comment by nicholascm** [comment]
Maybe related: https://github.com/fullcalendar/fullcalendar/issues/5273#issuecomment-1360459342

**Comment by nicholascm** [comment]
Thanks for looking at this @acerix. The behavior is different between the two different kind of events though. In one case, the non-recurring event adjusts properly as a part of the static list, but the issue is with the recurring event not staying adjusted for the timezone. 

The linked change is working really well for me for recurring events and fullcalendar is doing the timezone adjustment properly. I made the changes in `@fullcalendar/rrule` using `patch-package`.

**Comment by tcjens** [comment]
@nicholascm any luck? I am having this issue as well and the monkey patch from your comment did not resolve the issue for me.
What format of the DTSTART are you supplying to the rule? My server returns dates in UTC YYYY-MM-DDTHH:MM:SSZ

Should I be formatting the server date into local or desired timezone before creating the DTSTART key in the rule I am creating?

I am not sure how best to convert a server-supplied UTC date to something that works with RRULE and DST and Timezones.

Perhaps I am going about this incorrectly.

Thanks for any help.

**Comment by nicholascm** [comment]
I'll send some info that might help see if we can figure out any difference. It has been tricky for us to get to this point.

> What format of the DTSTART are you supplying to the rule? My server returns dates in UTC YYYY-MM-DDTHH:MM:SSZ

I'm getting UTC from the server, and when I create the rrule I'm using the format `format(date, "yyyy-MM-dd'T'HH:mm:00")`.  

We are passing a `timeZone` property to FullCalendar and using the `rrulePlugin` and teh `momentTimezonePlugin`

The patch looks like this (just to be sure): 

![image](https://github.com/fullcalendar/fullcalendar/assets/8185671/7d8a66e5-b486-48e0-9175-350ded090858)
