### ISSUE TITLE
Date in slotLabel in resourceTimeGridDay View (01.01.1970 instead of current date)

### ISSUE THREAD

**Issue by ChomaK18** [fullcalendar/fullcalendar#7637]
### Reduced Test Case

https://codepen.io/chomak/pen/wvZgpBG

### Do you understand that if a reduced test case is not provided, we will intentionally delay triaging of your ticket?

- [X] I understand

### Which connector are you using (React/Angular/etc)?

No connector (vanilla JS)

### Bug Description

When _slotLabelClassNames_ is invoked in resourceTimelineDay, it receives the current date and time. However, when the function is invoked in resourceTimeGridDay, it receives the correct time but with the date set to January 1, 1970.

Is it ok?

**Comment by acerix** [comment]
I don't see the issue in your demo, but it sounds like you mean the same as in this existing ticket:
https://github.com/fullcalendar/fullcalendar/issues/5854
↑
Please visit the above issue, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates.
