### ISSUE TITLE
About Premium License (Documentation)

### ISSUE THREAD

**Issue by rcklmk** [fullcalendar/fullcalendar#7638]
### Checklist

- [X] I've already searched through [existing tickets](https://github.com/fullcalendar/fullcalendar/issues)
- [X] Other people will find this feature useful

### Is this feature for a specific connector (React/Angular/etc)?

Other

### Feature Description

Hi,

I am currently investigating if I need to purchase a license for functionality I am currently implementing for an app.

I have read the [Pricing](https://fullcalendar.io/pricing) and the [Purchase a License](https://fullcalendar.io/purchase) pages, but there are some wordings that I don't think I have fully understood yet.

----

My questions are as follows (apology if some are just restating the obvious):
- **On Source Code Editing and Customization Policy**
  - In FAQ section it's written that: "... code that interacts with FullCalendar Premium's API in any way, writing CSS to style the calendar, or editing FullCalendar Premium's source code, they will need a developer seat". Would it be correct to say that:
    - Any source code not under Premium scope is free to modify under the MIT license?
    - I don't quite get what "writing CSS to style the calendar" means, but as I undertand it, does it mean that as long as I don't modify the source code directly to style the calendar, I don't really need the Premium licensing? I'm thinking of a situation where I am just using FullCalendar's provided public Event APIs like `eventColor`, `eventBackgroundColor`, `eventBorder`, `eventClassNames` to style the calendar and also in the case where I'm using a wrapper around FullCalendar to override its internal internal like `.some-fullcalendar-wrapper fc-toolbar-title {...}`. In these cases I wouldn't be actually modifying the source code directly so would this be considered as (A) "writing CSS to style the calendar" (Premium licensing required regardless which and how part of calendar is modified) or (B) does it fall into the scope of free source code modification or (C) not applicable to either as I'm overriding from outside FullCalendar? i.e. in (B) and (C) cases, modification is allowed without Premium licensing required.

- **On Perpetual Use of License**
  - If I do purchase the Premium license:
    - It's written on the purchase page that a single purchase is considered as "Perpetual use of license". Would it be correct to say that:
      - I can upgrade to the latest Premium features versions provided during the "1 year of email support and upgrades" as I like, and after the 1 year period expires, I **can use and modify** the **latest** version upgraded during the active support period perpetually without renewing the license. After expiry, if I needed to upgrade again I would need to purchase a new license to do so.

- **On Redistribution**
  - It's written that "The licensing for clients depends on whether you allow them to edit the source code...". Would it be correct to say that:
    - The above only applies for Premium features source code editing (not any modification on any part of FullCalendar) and for non-Premium features source code editing, client licensing is not required.
    - I'm a software house and I'm developing software for clients; as long as I minify js and css, I only need 1 license. If I allow a client to access the modified Premium features code repository, without OEM License, 2 Premium Licenses are required in total for my company and the client respectively, even if there is only 1 frontend developer active at a time.

----

Any help would be much appreciated. (My questions on Redistribution are probably not so straightforward; they're not so urgent at this point too. It would be great if I can receive any help/pointer on the Source Code Editing and Perpetual Use matters). Thank you for taking the time to read my lengthy issue.

Kind regards,
Ricky

**Comment by rcklmk** [comment]
Hi, any pointer on this matter? Any authority/management body I can contact through email, discord or any other communication tool?

**Comment by acerix** [comment]
The basic FullCalendar is MIT-licensed which means you can use it for free without restrictions.

The Premium version provides the resources feature and timeline view and requires a paid license to use commercially.

You can find details of the license here: https://fullcalendar.io/license .  Please contact sales@fullcalendar.io for questions about licensing.
