### ISSUE TITLE
multiMonthYear - start from current month

### ISSUE THREAD

**Issue by borisbsu** [fullcalendar/fullcalendar#7643]
### Checklist

- [X] I've already searched through [existing tickets](https://github.com/fullcalendar/fullcalendar/issues)
- [X] Other people will find this feature useful

### Is this feature for a specific connector (React/Angular/etc)?

No connector in particular

### Feature Description

Right now the fullcalendar renders multiMonthYear starting from Jan of the current year.

It would be great to have an option allowing to set the starting month.

Because otherwise the user needs to scroll down to find the required month.

Tested on Fullcalendar for React. Today is end of March, but it start from Jan.

<img width="563" alt="image" src="https://github.com/fullcalendar/fullcalendar/assets/556093/a548ad3d-c645-4b97-9438-7b2d1a7e7232">

**Comment by acerix** [comment]
You can use the "multiMonth" view with a duration of 12 months to change which month it starts on:

https://codepen.io/acerix/pen/qBwxLZG?editors=001
