### ISSUE TITLE
Event cannot be displayed by group.

### ISSUE THREAD

**Issue by devsuperrk** [fullcalendar/fullcalendar#7646]
### Checklist

- [X] I've already searched through [existing tickets](https://github.com/fullcalendar/fullcalendar/issues)
- [X] Other people will find this feature useful

### Is this feature for a specific connector (React/Angular/etc)?

Vue

### Feature Description

![event-features](https://github.com/fullcalendar/fullcalendar/assets/103863215/4ac9029e-d69c-4267-a2c7-aaf84c0c3112)

I want to showcase events in a different way.

My scenario is that on a single date, I have various types of social media posts. For example, I have 3 Facebook posts, 5 LinkedIn posts, and 8 Twitter posts. Currently, in the full calendar view, all these posts are displayed one after the other. If we set a limit of, say, 3 items to be shown, then it adds 5 more items to make up the limit.

I wish to segregate each social media platform. Therefore, I would like to display all posts grouped by platform, showing a set number for each group and then separately displaying any remaining items for each group.

**Comment by acerix** [comment]
I believe this existing ticket captures this need:
https://github.com/fullcalendar/fullcalendar/issues/4814
↑
Please visit the above issue, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates.

**Comment by devsuperrk** [comment]
@acerix  #4814 This is not what I want. My scenario and this ticket scenario are completely different. I don't have any parent-child relation. I want to show my posts/events in separate boxes. Each box should expand items differently. You may not have fully noticed the image I provided.
