### ISSUE TITLE
events are not displayed (in json format)

### ISSUE THREAD

**Issue by LinkZzZzZZz** [fullcalendar/fullcalendar#7653]
### Reduced Test Case

events-are-not-displayed-in-json

### Do you understand that if a reduced test case is not provided, we will intentionally delay triaging of your ticket?

- [X] I understand

### Which connector are you using (React/Angular/etc)?

No connector (vanilla JS)

### Bug Description

events transmitted in json format are not displayed in the calendar, but are initialized in it.

My code:
`
 calendar.addEventSource({
             url: '/api/events',
             failure: function() {
                 alert('there was an error while fetching events!');
             },
             color: 'yellow', // a non-ajax option
             textColor: 'black' // a non-ajax option
         });
`

The /api/events route returns json: `[{"title":"\u041f\u0430\u043c\u044f\u0442\u043d\u0438\u043a \u0418\u043b\u044c\u0435 \u041c\u0443\u0440\u043e\u043c\u0446\u0443","start":"2000-01-01T08:30:00.000Z","end":"2000-01-01T12:30:00.000Z"},{"title":"\u0421\u0432\u044f\u0442\u043e-\u0422\u0440\u043e\u0438\u0446\u043a\u0438\u0439 \u0436\u0435\u043d\u0441\u043a\u0438\u0439 \u043c\u043e\u043d\u0430\u0441\u0442\u044b\u0440\u044c","start":"2000-01-01T07:30:00.000Z","end":"2000-01-01T15:30:00.000Z"},{"title":"\u0410\u043b\u0435\u043a\u0441\u0435\u0435\u0432\u043e-\u0410\u043a\u0430\u0442\u043e\u0432 \u043c\u043e\u043d\u0430\u0441\u0442\u044b\u0440\u044c","start":"2000-01-01T01:30:00.000Z","end":"2000-01-01T06:00:00.000Z"}]`

Tell me, what is the error?

**Comment by n-at-han-k** [comment]
Very hard to say anything unless you post your code. You can use Gist to upload it.

**Comment by acerix** [comment]
Would you be able to post a [runnable, stripped-down demonstration of the bug](http://fullcalendar.io/wiki/Reduced-Test-Cases/)? Would really appreciate it because the time saved reproducing will be time spent fixing.
