### ISSUE TITLE
365 Days Calendar

### ISSUE THREAD

**Issue by alialtun14** [fullcalendar/fullcalendar#7659]
### Checklist

- [X] I've already searched through [existing tickets](https://github.com/fullcalendar/fullcalendar/issues)
- [X] Other people will find this feature useful

### Is this feature for a specific connector (React/Angular/etc)?

No connector in particular

### Feature Description

Is there a format that allows to see the 365 days calendar on a single page. This format would be a suitable view for once a day events. For example, showing the days when a staff member takes annual leave.

Is it possible to create this format with custom view?

![365 days calendar](https://github.com/fullcalendar/fullcalendar/assets/782196/d583e5f7-3e74-4209-959d-e1c842c6e36d)

**Comment by acerix** [comment]
I believe this existing ticket captures this need:
https://github.com/fullcalendar/fullcalendar/issues/5119
↑
Please visit the above issue, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates.
