### ISSUE TITLE
Time slot labels start at 24:00 instead of 00:00

### ISSUE THREAD

**Issue by Deepads** [fullcalendar/fullcalendar#7660]
### Checklist

- [X] I've already searched through [existing tickets](https://github.com/fullcalendar/fullcalendar/issues)
- [X] Other people will find this feature useful

### Is this feature for a specific connector (React/Angular/etc)?

No connector in particular

### Feature Description

Would like to know any options to set the slot label time from 00:00 apart from setting the local to 'en-GB'.

**Comment by acerix** [comment]
That format comes from the browser and is based on locale. You would need a date format plugin to cuzomize the format, there is an open issue regarding that:

https://github.com/fullcalendar/fullcalendar/issues/5683
↑
Please visit the above issue, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates.
