### ISSUE TITLE
MultiMonth Title Content Injection

### ISSUE THREAD

**Issue by DellanX** [fullcalendar/fullcalendar#7661]
### Checklist

- [X] I've already searched through [existing tickets](https://github.com/fullcalendar/fullcalendar/issues)
- [X] Other people will find this feature useful

### Is this feature for a specific connector (React/Angular/etc)?

No connector in particular

### Feature Description

I am looking at adding some UI elements to the month titles of the multi-month view, and am trying to pull off content injection there. Looks to me like there isn't any way to perform this.

The functionality added would be similar to #5779, which is also pending discussion.

**Comment by acerix** [comment]
I believe the existing ticket you mentioned captures this need, it's not specific to any view:
https://github.com/fullcalendar/fullcalendar/issues/5779
↑
Please visit the above issue, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates.

**Comment by DellanX** [comment]
The title area where the month names are rendered for multiMonth view is separate from the header/footer. Thus only implementing that ticket won't resolve this issue, which is why I created a seperate one.

(For my use case, I need to inject content into both the title and the header)
