### ISSUE TITLE
Timeline/Vertical Resource View availablity in Free (Standard) Version 

### ISSUE THREAD

**Issue by Twyar** [fullcalendar/fullcalendar#7662]
### Question

hi,

Sorry, didn't really know where to post this issue since it's more of a discussion rather than a Bug Request/Feature Request.

I am using Fullcalendar in my Vue3 project. For that I was using the Vertical Resource View.
Example: 
![example of usage](https://github.com/fullcalendar/fullcalendar/assets/140051446/33267170-0173-4376-bee9-cbd54822bbca)

As you see in the bottom it says:
> Your license key is invalid. [More Info](https://fullcalendar.io/docs/schedulerLicenseKey#invalid)

If you check the [pricing](https://fullcalendar.io/pricing) page, it says that the Standard version doesn't have the Timeline/Vertical Resource View, but as you can see, it still works fine. All it does is give a little message at the bottom about the license key.

Can I still use this while using the free (standard) version? If not, what stops people from using it behind an authenticated/private app (like in my case), since it works fine without issues.

Or is the license more meant for things such as support if you need help etc ?

**Comment by acerix** [comment]
A license key is required to use the premium views, except for non-commercial or open source (GPL) projects.  This page has more details:

https://fullcalendar.io/license

Please contact sales@fullcalendar.io for licensing questions.
