### ISSUE TITLE
Persian / Shamsi / Jalaali for Reactjs (Months be separate and be based on Jalaali)

### ISSUE THREAD

**Issue by morezmokarrami** [fullcalendar/fullcalendar#7665]
### Checklist

- [X] I've already searched through [existing tickets](https://github.com/fullcalendar/fullcalendar/issues)
- [X] Other people will find this feature useful

### Is this feature for a specific connector (React/Angular/etc)?

React

### Feature Description

I want to have fullcalendar in reactjs with Jalaali date which shows each month separately. Now it shows me e.g "فروردین - اردیبهشت" but i want these months separately e.g "فروردین"

**Comment by kasraPRS** [comment]
same problem, but in angular.

**Comment by acerix** [comment]
I believe this existing ticket captures this need:
https://github.com/fullcalendar/fullcalendar/issues/1813
↑
Please visit the above issue, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates.
