### ISSUE TITLE
Full calendar does not account for daylight savings

### ISSUE THREAD

**Issue by dodufuye-ut** [fullcalendar/fullcalendar#7678]
### Reduced Test Case

https://codepen.io/Deborah-Odufuye/pen/JjqdpOW?editors=0110#

### Do you understand that if a reduced test case is not provided, we will intentionally delay triaging of your ticket?

- [X] I understand

### Which connector are you using (React/Angular/etc)?

Angular

### Bug Description

The calendar does not take into account Daylight savings in this case, EEST.  I tried setting the now  field using  Luxon but it's ignored.

```
{
  now: DateTime.now().setZone("Europe/Kaliningrad").toISO()
}
```

Is there a way to make this work with Daylight savings and specifying the timezone?

**Comment by acerix** [comment]
I believe this existing ticket captures this need:
https://github.com/fullcalendar/fullcalendar/issues/7620
↑
Please visit the above issue, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates.
