### ISSUE TITLE
Unable to display JSON as events

### ISSUE THREAD

**Issue by plane007** [fullcalendar/fullcalendar#7679]
### Reduced Test Case

https://codepen.io/plane007/details/QWRbmwb

### Do you understand that if a reduced test case is not provided, we will intentionally delay triaging of your ticket?

- [X] I understand

### Which connector are you using (React/Angular/etc)?

No connector (vanilla JS)

### Bug Description

I have created JSON using a PHP script. In the past weeks that script has generated event data that was successfully displayed. All changes since then were to do with security of access and the same JSON appears to be produced, as shown in the test case. However, no events are displayed now.

**Comment by acerix** [comment]
The JSON data for events needs to be an array (wrapped by `[`, `]`): 

https://codepen.io/acerix/pen/qBGOOqo?editors=0010
