### ISSUE TITLE
Angular version 18 support

### ISSUE THREAD

**Issue by selcukkutuk** [fullcalendar/fullcalendar#7682]
### Checklist

- [X] I've already searched through [existing tickets](https://github.com/fullcalendar/fullcalendar/issues)
- [X] Other people will find this feature useful

### Is this feature for a specific connector (React/Angular/etc)?

Angular

### Feature Description

Please add Angular version **18** support.

**Comment by adri95cadiz** [comment]
Could you provide any updates on this please? This dependency is halting the possibility of updating Angular for us at the moment.

**Comment by arshaw** [comment]
@adri95cadiz , I will be releasing this today

**Comment by selcukkutuk** [comment]
> @adri95cadiz , I will be releasing this today

Good news.  Thank you for your effort. 🔥👌🏻

**Comment by adri95cadiz** [comment]
> @adri95cadiz , I will be releasing this today

That's great, thank you for your hard work.

**Comment by arshaw** [comment]
This has been released in [v6.1.14](https://github.com/fullcalendar/fullcalendar/releases/tag/v6.1.14)

Please post any additional issues as separate tickets. Thanks.
