### ISSUE TITLE
fullcalendar-angular not updated on npm

### ISSUE THREAD

**Issue by mc17uulm** [fullcalendar/fullcalendar#7683]
### Reduced Test Case

https://www.npmjs.com/package/@fullcalendar/angular

### Do you understand that if a reduced test case is not provided, we will intentionally delay triaging of your ticket?

- [X] I understand

### Which connector are you using (React/Angular/etc)?

Angular

### Bug Description

The current version of the [fullcalendar/angular](https://github.com/fullcalendar/fullcalendar-angular) package is 6.1.13, but on [npm](https://www.npmjs.com/package/@fullcalendar/angular) there is only version 6.1.10 available.

**Comment by arshaw** [comment]
Thanks for calling this to my attention @mc17uulm. There was a bug with the publishing CI. I've fixed the bug and published @fullcalendar/angular v6.1.13 to npm. thanks
