### ISSUE TITLE
Reverse axis on ressourceTimeLineYear

### ISSUE THREAD

**Issue by diegobussu** [fullcalendar/fullcalendar#7684]
### Checklist

- [X] I've already searched through [existing tickets](https://github.com/fullcalendar/fullcalendar/issues)
- [X] Other people will find this feature useful

### Is this feature for a specific connector (React/Angular/etc)?

Other

### Feature Description

https://imgur.com/a/upDxnlL

I still haven't found a solution to have the dates on the left-hand side for a much simpler vertical scroll.

The best option would be to invert the axes on all views.

**Comment by acerix** [comment]
I believe this existing ticket captures this need:
https://github.com/fullcalendar/fullcalendar/issues/4858
↑
Please visit the above issue, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates.
