### ISSUE TITLE
Dates not selectable in Shadow DOM

### ISSUE THREAD

**Issue by kevineinarsson** [fullcalendar/fullcalendar#7685]
### Reduced Test Case

https://codesandbox.io/p/sandbox/nervous-darkness-5d8n6p

### Do you understand that if a reduced test case is not provided, we will intentionally delay triaging of your ticket?

- [X] I understand

### Which connector are you using (React/Angular/etc)?

No connector (vanilla JS)

### Bug Description

 Since d48a4e623a01fe3165408733ededf78f7a5e992c, calendars that are rendered within a shadow tree aren't interactable. The added check w/ `document.getElementFromPoint` always returns false, since the function will return the light dom root node.

I don't see a simple way of overriding this behavior without overriding internals and/or writing my own plugin.

In my reproduction there is a `console.log` call that should trigger whenever you click a cell.

Downgrading to `@fullcalendar/interaction@6.1.11` 'fixes' the problem. The messages start appearing in the console and styling is updated on the clicked cell.

**Comment by PierrickBrun** [comment]
I can confirm the problem using Vue3 and exporting the calendar in a web component (via defineCustomElement), thus in a shadow DOM.

Downgrading to `@fullcalendar/interaction@6.1.11` made it work too.

**Comment by mrodri4** [comment]
Same for us with a react project. Downgrading to @fullcalendar/interaction@6.1.11 works to. We checked that with every day click body style="user-select: none" is applied to body.

**Comment by arshaw** [comment]
Thanks for the report. I'll come up with a fix for the next patch release

**Comment by arshaw** [comment]
This has been fixed in [v6.1.15](https://github.com/fullcalendar/fullcalendar/releases/tag/v6.1.15)

Updated repro:
https://codesandbox.io/p/sandbox/nervous-darkness-forked-htwxf3?file=%2Findex.html%3A21%2C24
