### ISSUE TITLE
moreLinkContent callback return current tablecell date

### ISSUE THREAD

**Issue by chong-intrii** [fullcalendar/fullcalendar#7691]
### Checklist

- [X] I've already searched through [existing tickets](https://github.com/fullcalendar/fullcalendar/issues)
- [X] Other people will find this feature useful

### Is this feature for a specific connector (React/Angular/etc)?

React

### Feature Description

When using fullcalendar, we need to customize the rendering of moreLinkContent, which requires obtaining the current date of the TableCell calendar. We need to make a paginated request for more data based on this day. Currently, I'm unable to get the current TableCell's date. Can we pass the current TableCell's date as a parameter?

**Comment by acerix** [comment]
I believe this existing ticket captures this need:
https://github.com/fullcalendar/fullcalendar/issues/6095
↑
Please visit the above issue, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates.
