### ISSUE TITLE
 Month view - position of multiple calendar events pop up

### ISSUE THREAD

**Issue by jalindar-ht** [fullcalendar/fullcalendar#7696]
### Reduced Test Case

-

### Do you understand that if a reduced test case is not provided, we will intentionally delay triaging of your ticket?

- [X] I understand

### Which connector are you using (React/Angular/etc)?

Angular

### Bug Description

If there are more than 3 events in a single day in a monthly view, the ‘+x’ icon shows up. Upon clicking this icon, the pop-up opens in the top left corner, instead of near the actual day.

**Comment by acerix** [comment]
It should display from the top of the day like in this demo: 

https://fullcalendar.io/docs/event-popover-demo

If it is displaying at the top-left of the calendar/page, that seems like a bug, so in that case, please supply a [runnable, stripped-down demonstration](http://fullcalendar.io/wiki/Reduced-Test-Cases/).
