### ISSUE TITLE
Timezone not applied to recurring events when navigating forward/backward

### ISSUE THREAD

**Issue by tcjens** [fullcalendar/fullcalendar#7704]
### Reduced Test Case

https://codepen.io/arshaw/pen/RweKOEp?editors=0010

### Do you understand that if a reduced test case is not provided, we will intentionally delay triaging of your ticket?

- [X] I understand

### Which connector are you using (React/Angular/etc)?

React

### Bug Description

Navigating from one frame to another ignores timezone. For example, if client is America/New_York at 10:00 and I am looking at July 2024 month view (the issue happens on all views), event on July 1 @ 10:00 displays as 10:00. If I then switch the timezone to America/Chicago, the date/times appropriately change to 09:00. However, if I then scroll to August 2024, the dates revert back to NY (10:00) without changing the state of the assigned timezone. This also means if I tried to manually switch Aug 2024 to NY, it actually adds the +1 hr time change to the already NY date/times resulting in 11:00.

**Comment by acerix** [comment]
Thansk for the report, the existing ticket for this has been re-opened:
https://github.com/fullcalendar/fullcalendar/issues/5273
↑
Please visit the above issue, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates.
