### ISSUE TITLE
Update Roadmap

### ISSUE THREAD

**Issue by nadavhalfon** [fullcalendar/fullcalendar#7705]
### Checklist

- [X] I've already searched through [existing tickets](https://github.com/fullcalendar/fullcalendar/issues)
- [X] Other people will find this feature useful

### Is this feature for a specific connector (React/Angular/etc)?

No connector in particular

### Feature Description

Hey,
Must say I use the library a year now, and I like it very much! Well built and answers every need I met 😁

I know that there is no commitment to the Roadmap, but I did see that it is almost completely irrelevant :(
I am about to purchase again a License and wanted to know if there is an updated roadmap that is more relevant to date?

Another thing I think many will like and there is also a topic about that is React Native.
As a developer I think that there is a big business opportunity here as the regular web development is mainly adopted the FullCalendar, but there is no React native good alternative, creating one will be amazing and will bring new customers including me, right now I must use Ionic React because the calendar with your features is mandatory.

And I know all of that takes time and probably a lot, but I would appreciate if you can share please some of you thoughts including the near future roadmap + React Native thoughts

**Comment by arshaw** [comment]
Thanks for the nudge @nadavhalfon 

I've updated the roadmap:
https://fullcalendar.io/roadmap

and I've responded on the main react-native ticket:
https://github.com/fullcalendar/fullcalendar/issues/7076#issuecomment-2221858540

I definitely see react-native as a business opportunity, but it's a long road to get there.
