### ISSUE TITLE
Update event constraints while an event is being dragged

### ISSUE THREAD

**Issue by Aleafan** [fullcalendar/fullcalendar#7709]
### Reduced Test Case

https://stackblitz.com/github/fullcalendar/fullcalendar-examples/tree/main/react?file=README.md

### Do you understand that if a reduced test case is not provided, we will intentionally delay triaging of your ticket?

- [X] I understand

### Which connector are you using (React/Angular/etc)?

React

### Bug Description

Hello, thanks a lot for your work!

I try to implement a functionality where after event dragStart server sends info about dragged event's constraint and I apply those constraints on the fly during dragging. When I do this Calendar's events are updated successfully, but constraints are not applied to dragged event.

I gathered from code that dragged event is a mirror copy of original event element.

Is that an intentional design choice to not update that mirror copy? Is there any workaround to implement desired logic?

**Comment by acerix** [comment]
I don't believe it's possible to update an event's contraints while it's being dragged but that could be useful as a new feature.  

You could use `eventAllow` "as a function" to manually control where the event is allowed, and have that change behaviour based on the server response.

**Comment by Aleafan** [comment]
I implemented needed functionality via background events and groupId. If you think that updating event constraints is good idea for a new feature - I'm for it. Otherwise there are fortunately other ways so its not critical.
