### ISSUE TITLE
include `ical.js` as a dependency

### ISSUE THREAD

**Issue by JohnRDOrazio** [fullcalendar/fullcalendar#7710]
### Checklist

- [X] I've already searched through [existing tickets](https://github.com/fullcalendar/fullcalendar/issues)
- [X] Other people will find this feature useful

### Is this feature for a specific connector (React/Angular/etc)?

No connector in particular

### Feature Description

If `ical.js` is a dependency, shouldn't it be included among the dependencies in `package.json`, rather than telling people they should simply install `ical.js` first? How can we be sure which version of `ical.js` fullcalendar will support?

**Comment by arshaw** [comment]
Hi @JohnRDOrazio , ical.js is a peerDependency of @fullcalendar/icalendar . Most package managers these days will installed peerDependencies automatically, however, to support a broad range of package managers we err on the side of instructing devs to do it explicitly. All package managers will be smart enough to know to use the correct one.

**Comment by JohnRDOrazio** [comment]
ok I see that it is a **peerDependency** of **@fullcalendar/icalendar**, and not of **@fullcalendar/fullcalendar**, that is what was getting me a little confused, not finding anything in **@fullcalendar/fullcalendar**. Unfortunately peer dependencies are no longer installed automatically and must be installed separately. I have Github's dependabot trying to update some packages in a repo in which I have implemented fullcalendar, and it wants to update `ical.js` to version 2. Will **ical.js@2** be compatible with **@fullcalendar/icalendar**? I see that the relative **package.json** indicate `^1.4.0` which means that **ical.js@2** isn't necessarily compatible.

https://github.com/fullcalendar/fullcalendar/blob/25b72262d956254f4275669da5d7ad3b8ed1e4dd/packages/icalendar/package.json#L13
