### ISSUE TITLE
Issue Report for FullCalendar Drag-and-Drop Functionality in Versions Above 6.1.11

### ISSUE THREAD

**Issue by kalu1** [fullcalendar/fullcalendar#7711]
### Reduced Test Case

sorry i dont have time right now to create it. i want to share my experience. if it is useless delete it. thanks

### Do you understand that if a reduced test case is not provided, we will intentionally delay triaging of your ticket?

- [X] I understand

### Which connector are you using (React/Angular/etc)?

No connector (vanilla JS)

### Bug Description

Hi,

I spent a long time figuring out why, after some changes, my drag-and-drop function stopped working. I investigated the HTML code, JS code, and CSS code step by step. Then, I compared my backup code and found that it works correctly with version 6.1.11.

I don't need to solve the issue for now, as it works with the mentioned version, but I hope this will help someone else.

Affected Functionality
Drag-and-Drop: External events created dynamically via JavaScript can be dragged but do not stick to the calendar upon drop. With hardcoded external events in the HTML code, it works correctly with version 6.1.12 and higher.

Event Interaction: External events display style changes while being dragged, but the drop event is not triggered properly.

Code Example
HTML:

`<script src='https://cdn.jsdelivr.net/npm/fullcalendar@6.1.12/index.global.min.js'></script>`

Initialize Calendar with Droppable Configuration:
javascript

```
document.addEventListener('DOMContentLoaded', function() {
  var calendarEl = document.getElementById('calendar');
  var calendar = new FullCalendar.Calendar(calendarEl, {
    initialView: 'timeGridWeek',
    droppable: true,
    drop: function(info) {
      console.log("Dropped event:", info);
    }
  });
  calendar.render();
});
```

Create Draggable External Events Dynamically:
javascript

```
function fetchExternalEvents() {
  const container = document.getElementById('external-events');
  container.innerHTML = '';
  // Example of dynamically adding events
  createExternalEvent('Sample Event 1', 'SKU123');
  initializeDraggable();
}

function createExternalEvent(eventName, eventSKU) {
  const container = document.getElementById('external-events');
  const eventDiv = document.createElement('div');
  eventDiv.className = 'fc-event fc-h-event fc-daygrid-event fc-daygrid-block-event';
  eventDiv.innerHTML = `<div class='fc-event-main'>${eventName} (SKU: ${eventSKU})</div>`;
  eventDiv.dataset.name = eventName;
  eventDiv.dataset.sku = eventSKU;
  container.appendChild(eventDiv);
}

function initializeDraggable() {
  $('#external-events .fc-event').each(function() {
    const name = this.dataset.name;
    const sku = this.dataset.sku;

    // Create a data object for the draggable event
    const eventData = {
      title: `${name} (SKU: ${sku})`,
      stick: true,
      extendedProps: {
        nameMem: name,
        sku: sku
      }
    };

    // Store the event data in the draggable element
    $(this).data('event', eventData);

    // Make the element draggable
    $(this).draggable({
      zIndex: 999,
      revert: true,
      revertDuration: 0
    });
  });
}

fetchExternalEvents();
```

**Comment by acerix** [comment]
Would you be able to post a [runnable, stripped-down demonstration of the bug](http://fullcalendar.io/wiki/Reduced-Test-Cases/)? Would really appreciate it because the time saved reproducing will be time spent fixing.
