### ISSUE TITLE
SEO : Weekday Links are Not Crawlable

### ISSUE THREAD

**Issue by muhammad-nabih** [fullcalendar/fullcalendar#7715]
### Reduced Test Case

https://codesandbox.io/p/sandbox/fullcalednarissue-2t4cxw?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522cly6fznqj0006356pgpp6og2l%2522%252C%2522sizes%2522%253A%255B100%252C0%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522cly6fznqi0002356pspn99q21%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522cly6fznqi0003356pd88kae7v%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522cly6fznqi0005356pe8wgn025%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B43.1276897393522%252C56.8723102606478%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522cly6fznqi0002356pspn99q21%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cly6fznqi0001356pshdytncr%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fsrc%252Findex.js%2522%257D%255D%252C%2522id%2522%253A%2522cly6fznqi0002356pspn99q21%2522%252C%2522activeTabId%2522%253A%2522cly6fznqi0001356pshdytncr%2522%257D%252C%2522cly6fznqi0005356pe8wgn025%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cly6fznqi0004356pqpn71evt%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522cly6fznqi0005356pe8wgn025%2522%252C%2522activeTabId%2522%253A%2522cly6fznqi0004356pqpn71evt%2522%257D%252C%2522cly6fznqi0003356pd88kae7v%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522cly6fznqi0003356pd88kae7v%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Afalse%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D

### Do you understand that if a reduced test case is not provided, we will intentionally delay triaging of your ticket?

- [X] I understand

### Which connector are you using (React/Angular/etc)?

React

### Bug Description

I am experiencing an SEO issue with FullCalendar where the links for weekdays (Sun, Mon, Tue, Wed, Thu, Fri, Sat) are not crawlable. This is affecting the overall SEO performance of my website.

Problem:
The links for the days of the week do not have href attributes, making them uncrawlable by search engines. This results in warnings such as "Links are not crawlable" during SEO audits.

Steps to Reproduce:

Integrate FullCalendar into a React project.
Run an SEO audit using tools like Google Lighthouse.
Observe the SEO audit results indicating that the weekday links are not crawlable.
Expected Behavior:
The links for the days of the week should have proper href attributes so that search engines can crawl them effectively.

Actual Behavior:
The links for the days of the week do not have href attributes, resulting in them being uncrawlable by search engines.

**Comment by acerix** [comment]
The calendar only provides the frontend, you would need to create the days of the week as URLs in your backend to make them crawl-able. 

You could use `dayHeaderContent` to add the links to the days like this:

https://codepen.io/acerix/pen/yLdBNbQ?editors=001
