### ISSUE TITLE
Different initial selection duration than increments for event creation

### ISSUE THREAD

**Issue by ricardomarsanc** [fullcalendar/fullcalendar#7719]
### Checklist

- [X] I've already searched through [existing tickets](https://github.com/fullcalendar/fullcalendar/issues)
- [X] Other people will find this feature useful

### Is this feature for a specific connector (React/Angular/etc)?

React

### Feature Description

Hey folks! I've been doing some research on this use case and I couldn't find any solution that fits my need.

Currently we're using FullCalendar in React with the `resourceTimeGrid` and `interaction` plugins (we use more, but those are the important ones), and we display several resources for a specific day, in which users can create new events by clicking and dragging in the calendar, with increments of 15 minutes. The thing is, we want to change the initial event duration when a user performs a click, based on the resource, so instead of rendering a mirror box of 15 minutes when the user clicks, we want to show a 60, 90 or any other duration box instead.

The only way we could achieve something like that at this point was just forcing a new `select` event dispatched inside the calendar `select` method using the Calendar API, but the outcome is that the mirror box is initially of 15 minutes, and as soon as the click finishes, the event "jumps" and transforms into the desired duration (60, 90min etc.).

What we want is something similar to what Google Calendar does, which is:
- When clicking, no mirror box is rendered
- After some time has passed, if the click didn't finish, automatically renders a 15 minute mirror box
- If click finishes before the grace period has passed, a box of 60 minutes is rendered (can be customized in the settings)
- If click didn't finish but the user starts dragging, a 15 minutes mirror box is rendered and then it grows on intervals of 15 minutes.

I didn't find any way of doing this with the tools FullCalendar offers, and I've also tried extending the `Interaction` plugin to handle `pointerdown` and `pointerup` events manually, but the Mirror element doesn't change regardless of the dates selection (I'm using `calendar.dispatch({ type: 'SELECT_DATES', selection: this.dragSelection })` to handle new selection inside the `pointerdown` event)

Couldn't find any similar use case or documentation on how to achieve this behavior. Any help would be more than welcome. Thanks guys!

**Comment by ricardomarsanc** [comment]
Update: found a couple of similar issues but they've been open for 8yrs at this point:

https://github.com/fullcalendar/fullcalendar/issues/2828
https://github.com/fullcalendar/fullcalendar/issues/472

**Comment by acerix** [comment]
I believe the existing ticket you mentioned captures this need:
https://github.com/fullcalendar/fullcalendar/issues/2828
↑
Please visit the above issue, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates.

You could use [eventAllow](https://fullcalendar.io/docs/eventAllow) to only allow events with a long enough duration.
