### ISSUE TITLE
FullCalendar Using ICS Getting Console Error ReferenceError: ICAL is not defined

### ISSUE THREAD

**Issue by lacwebadmin** [fullcalendar/fullcalendar#7720]
### Reduced Test Case

https://codepen.io/frogydiak/pen/GRbgxrE

### Do you understand that if a reduced test case is not provided, we will intentionally delay triaging of your ticket?

- [X] I understand

### Which connector are you using (React/Angular/etc)?

No connector (vanilla JS)

### Bug Description

Hello! 

In the docs, the example for [iCalendar](https://fullcalendar.io/docs/icalendar) is via NPM. I wish you guys also create an example via CDN.

![image](https://github.com/fullcalendar/fullcalendar/assets/171614378/0b6374e3-ab72-43d2-b987-b62f3144eb64)

What did I do wrong? Could it be an issue with ical.js dependency in v6? Related to this [issue](https://github.com/YogliB/svelte-fullcalendar/issues/802)?

**Comment by acerix** [comment]
I believe this existing ticket captures this need:
https://github.com/fullcalendar/fullcalendar/issues/6215
↑
Please visit the above issue, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates.

**Comment by lacwebadmin** [comment]
For those that come across this issue in the future, the documentation for v6 did not mention it but you have to load the `ical.js` as well. FYI, I am still getting that ICAL error when using v6.14 but the error disappears when I switch to v5.x.
