### ISSUE TITLE
I can't generate a recurring event view if allDay is set to true.

### ISSUE THREAD

**Issue by hiperdazio** [fullcalendar/fullcalendar#7721]
### Reduced Test Case

https://github.com/fullcalendar/fullcalendar/issues

### Do you understand that if a reduced test case is not provided, we will intentionally delay triaging of your ticket?

- [X] I understand

### Which connector are you using (React/Angular/etc)?

React

### Bug Description

Hey. I've searched through all reported issues, read the documentation. I can't generate a recurring event view if allDay is set to true. The recurrence itself works correctly, a single all-day event displays correctly. Unfortunately, with an all-day recurrence, the event doesn't display on the calendar.

```
{
            "id" : "cal_evt_eef437fb",
            "groupId" : "ev_group_fb64efb1",
            "allDay" : true,
            "start" : ISODate("2024-06-30T22:00:00.000+0000"),
            "end" : ISODate("2024-06-30T22:00:00.000+0000"),
            "duration" : NumberInt(0),
            "title" : "Calendar",
            "rrule" : {
                "dtstart" : ISODate("2024-07-01T00:00:00.000+0000"),
                "freq" : NumberInt(2),
                "byweekday" : [
                    {
                        "weekday" : NumberInt(0),
                        "n" : null
                    }
                ],
                "interval" : NumberInt(1),
                "until" : ISODate("2026-07-11T00:00:00.000+0000")
            },
            "rruleString" : "DTSTART:20240701T000000\nRRULE:FREQ=WEEKLY;BYDAY=MO;INTERVAL=1;UNTIL=20260711",
            "exdate" : [

            ],
            "extendedProps" : {
                "employeeId" : "179898da71ca6a3",
                "name" : "User Name",
                "calendarId" : "calendar_b218d2",
                "rrule" : "RRULE:FREQ=WEEKLY;BYDAY=MO;INTERVAL=1;UNTIL=20260711"
            },
            "_id" : ObjectId("66901e7bff9ab6a1a1bf35d7")
        }
```

**Comment by acerix** [comment]
Would you be able to post a [runnable, stripped-down demonstration of the bug](http://fullcalendar.io/wiki/Reduced-Test-Cases/)? Would really appreciate it because the time saved reproducing will be time spent fixing.
