### ISSUE TITLE
Console warning: Unknown option 'schedulerLicenseKey' 

### ISSUE THREAD

**Issue by ItsNoHax** [fullcalendar/fullcalendar#7724]
### Reduced Test Case

Not available

### Do you understand that if a reduced test case is not provided, we will intentionally delay triaging of your ticket?

- [X] I understand

### Which connector are you using (React/Angular/etc)?

React

### Bug Description

Implement the FullCalendar component anywhere, make sure prop schedulerLicenseKey is provided with a proper license key. Open the page in a browser and observe the console log.

![image](https://github.com/user-attachments/assets/ad1a09bf-2a7f-47ac-b9e1-39c9ce2c21fd)

**Comment by acerix** [comment]
This setting is only required when using premium plugins, if you are not using any premium features, you can omit that setting.  

Please post a [runnable, stripped-down demonstration of the bug](http://fullcalendar.io/wiki/Reduced-Test-Cases/) if there's still an issue.
