### ISSUE TITLE
 viewType "" is not available. Please make sure you've loaded all neccessary plugins

### ISSUE THREAD

**Issue by Prema4** [fullcalendar/fullcalendar#7727]
### Reduced Test Case

 viewType "" is not available. Please make sure you've loaded all neccessary plugins

### Do you understand that if a reduced test case is not provided, we will intentionally delay triaging of your ticket?

- [X] I understand

### Which connector are you using (React/Angular/etc)?

Angular

### Bug Description

i used the full calendar, but am getting below error:  viewType "" is not available. Please make sure you've loaded all neccessary plugins. 
![image](https://github.com/user-attachments/a
<img width="960" alt="FullCalendar" src="https://github.com/user-attachments/assets/ffc00081-b365-42c0-80c6-c35699f02ebf">
ssets/6974dad2-8507-4634-9626-de654510bfde)

**Comment by acerix** [comment]
Would you be able to post a [runnable, stripped-down demonstration of the bug](http://fullcalendar.io/wiki/Reduced-Test-Cases/)? Would really appreciate it because the time saved reproducing will be time spent fixing.
