### ISSUE TITLE
RECURRENCE leads to duplicate false duplicate entries (Again)

### ISSUE THREAD

**Issue by nasenfloete** [fullcalendar/fullcalendar#7729]
### Reduced Test Case

https://app.communiapp.de/content/download/upload/43789a65faaf8d2114757b6eb735b18edef196db.ics

### Do you understand that if a reduced test case is not provided, we will intentionally delay triaging of your ticket?

- [X] I understand

### Which connector are you using (React/Angular/etc)?

No connector (vanilla JS)

### Bug Description

I have the same problem as https://github.com/fullcalendar/fullcalendar/issues/6451. We still used Fullcalender v5.6. After finding the issue i updated to v5.9.0 and also to 5.11. but it didnt fix the problem, eventhough it should be fixed with v.5.9. 
It seems, that the reason for the problem is the third event. its on the same day and time, and somehow leads to the RECURRENCE event to be displayed twice. 

![doubleEntry](https://github.com/user-attachments/assets/8cfc8354-f2d6-4d19-8f69-30c5e874ccb6)

Feel free to contact me, if you need more infos. Thanks in advance!

**Comment by acerix** [comment]
Would you be able to post a [runnable, stripped-down demonstration of the bug](http://fullcalendar.io/wiki/Reduced-Test-Cases/)? Would really appreciate it because the time saved reproducing will be time spent fixing.

**Comment by nasenfloete** [comment]
@acerix i added the reduced testcase above -> https://codepen.io/lukasdue/pen/MWMJWgd
Thanks in advance
