### ISSUE TITLE
vuejs3 persian calendar dayGridMonth bug

### ISSUE THREAD

**Issue by naserrasoulii** [fullcalendar/fullcalendar#7730]
### Reduced Test Case

/

### Do you understand that if a reduced test case is not provided, we will intentionally delay triaging of your ticket?

- [X] I understand

### Which connector are you using (React/Angular/etc)?

Vue

### Bug Description

hello ,
i use of fullcalendar/vu3
and this display get
ineed to get one month in display and start date from 1 
now,start date from 11 
this config in component:
`
const calendarOptions = computed(() => {
  return {
    plugins: [dayGridPlugin, interactionPlugin, timeGridPlugin],
    initialView: 'dayGridMonth',
    locale: faLocale,
    headerToolbar: {
      left: 'next',
      center: 'title',
      right: 'prev'
    },
    timeZone: 'Asia/Tehran',
    firstDay: 6,
    dateClick: handleClickDate,
    slotMinTime: '06:00:00'

  };
});`
![image](https://github.com/user-attachments/assets/e27845da-50cd-4adf-b125-5e385fa40b3b)

**Comment by acerix** [comment]
I believe this existing ticket captures this need:
https://github.com/fullcalendar/fullcalendar/issues/1813
↑
Please visit the above issue, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates.

If there is a bug, please supply a [runnable, stripped-down demonstration](http://fullcalendar.io/wiki/Reduced-Test-Cases/).
