### ISSUE TITLE
i faced issue on popover screen.. i clicked outside its closed..like i have event screen,, if i clicked on the view.. its closed..

### ISSUE THREAD

**Issue by o-kabir** [fullcalendar/fullcalendar#7731]
### Checklist

- [X] I've already searched through [existing tickets](https://github.com/fullcalendar/fullcalendar/issues)
- [X] Other people will find this feature useful

### Is this feature for a specific connector (React/Angular/etc)?

Angular

### Feature Description

i faced issue on popover screen.. i clicked outside its closed..like i have event screen,, if i clicked on the view.. its closed..
![popover-bug](https://github.com/user-attachments/assets/6216fe3f-eda9-45c9-bd14-14ceea39d983)

**Comment by acerix** [comment]
I believe this existing ticket captures this need:
https://github.com/fullcalendar/fullcalendar/issues/6993
↑
Please visit the above issue, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates.

**Comment by o-kabir** [comment]
> I believe this existing ticket captures this need: #6993 ↑ Please visit the above issue, **give a** 👍 **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates.

can you please tell me ... where i change the code in the exact file..
