### ISSUE TITLE
Using datesSet and querying the start or end may result in the month prior or after to be returned

### ISSUE THREAD

**Issue by andyb2000** [fullcalendar/fullcalendar#7736]
### Reduced Test Case

https://codepen.io/andyb2000/pen/BagdxWY

### Do you understand that if a reduced test case is not provided, we will intentionally delay triaging of your ticket?

- [X] I understand

### Which connector are you using (React/Angular/etc)?

No connector (vanilla JS)

### Bug Description

The issue is with datesSet when in month view. In the reduced test case I output to console the returned month.
Since the month view starts with several days from the previous month, THAT month is returned.

For example, this month August 2024.
The first 4 cells are 28,29,30,31 from July. So the datesSet.dateInfo.start.getMonth() actually returns July and not August, even though the 'main' focus of the month display is August.

I think it would be better to have another field as well as start, end, etc, that is something like 'primary' which would reflect the primary month in the view (i.e. the one shown in the title of the calendar).

**Comment by acerix** [comment]
The `start`/`end` dates are the range that the calendar needs events for, so it includes the days from prev/next months that are visible.  You can use `view.currentStart` to get the start of the month:

https://codepen.io/acerix/pen/MWMOVyj?editors=0010

**Comment by andyb2000** [comment]
Ah, perfect! thank you I'd missed that one.
