### ISSUE TITLE
It is not possible to drag an event to another day within an react-native-webview.

### ISSUE THREAD

**Issue by acb09** [fullcalendar/fullcalendar#7737]
### Reduced Test Case

http://unknow.none

### Do you understand that if a reduced test case is not provided, we will intentionally delay triaging of your ticket?

- [X] I understand

### Which connector are you using (React/Angular/etc)?

React

### Bug Description

I created a mobile application for Android that adds a react-native-webview to render the content of my website. However, when trying to drag the event to another day, only a link is dragged, not the event itself.

Obs: It works perfectly in the browser.

![WhatsApp Image 2024-08-13 at 11 29 12](https://github.com/user-attachments/assets/671b2a9a-e9e7-4759-ab92-6e6ef6e44345)

**Comment by acerix** [comment]
Would you be able to post a [runnable, stripped-down demonstration of the bug](http://fullcalendar.io/wiki/Reduced-Test-Cases/)? Would really appreciate it because the time saved reproducing will be time spent fixing.
