### ISSUE TITLE
Support Access Token for Google Calendar

### ISSUE THREAD

**Issue by mgladfelter-lyra** [fullcalendar/fullcalendar#7738]
### Checklist

- [X] I've already searched through [existing tickets](https://github.com/fullcalendar/fullcalendar/issues)
- [X] Other people will find this feature useful

### Is this feature for a specific connector (React/Angular/etc)?

No connector in particular

### Feature Description

We would like the ability to use an access token,`access_token`, instead of an API key ,`key`, for @fullcalendar/google-calendar package. This opens up the ability to use an OAuth flow to display a user's calendar.

**Comment by acerix** [comment]
I believe this existing ticket captures this need:
https://github.com/fullcalendar/fullcalendar/issues/2642
↑
Please visit the above issue, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates.
