### ISSUE TITLE
Bootstrap5 themeSystem timeGridWeek view issue

### ISSUE THREAD

**Issue by sudheerkumarala** [fullcalendar/fullcalendar#7740]
### Checklist

- [X] I've already searched through [existing tickets](https://github.com/fullcalendar/fullcalendar/issues)
- [X] Other people will find this feature useful

### Is this feature for a specific connector (React/Angular/etc)?

No connector in particular

### Feature Description

Firstly, I really love this plugin and the ability to edit and customize one's own requirements..

However, I am bit irritated on how the bootstrap5 theme calendar view in timeGridWeek is confusing as you see from the image the hour is considered from 00:00 and bottom border at 00:30 and then the next half in 01:00 which makes it confusing seeing the hour and the event from different slots, as I develop the medium I know how this works but as a user it is really confusing.

![image](https://github.com/user-attachments/assets/8ad09801-213f-4830-85fa-86cbd9939737)

Such an example below  as
![image](https://github.com/user-attachments/assets/53a2a292-0d09-44da-bd14-a42686172716)
the time is from 05:15-06:00 but in the view it is showing inside the04:00 to 05:00 slot which is a bit confusing, 

is this a bug or am I interpreting it wrong please let me know.

**Comment by acerix** [comment]
The bootstrap5 theme should have the time slot borders above the labels for each hour, so does not have that issue, here is an example:

https://codepen.io/acerix/pen/vYqRryO?editors=001

It looks like you have some custom styles, you can try turning off your CSS to fix that.  Please post a [runnable, stripped-down demonstration](http://fullcalendar.io/wiki/Reduced-Test-Cases/) if there a bug in the calendar.

**Comment by sudheerkumarala** [comment]
> The bootstrap5 theme should have the time slot borders above the labels for each hour, so does not have that issue, here is an example:
> 
> https://codepen.io/acerix/pen/vYqRryO?editors=001
> 
> It looks like you have some custom styles, you can try turning off your CSS to fix that. Please post a [runnable, stripped-down demonstration](http://fullcalendar.io/wiki/Reduced-Test-Cases/) if there a bug in the calendar.


~~~
import * as FullCalendar from "@fullcalendar/core";

public calendar: any;

let calendarEle = document.getElementById('calendar')!;
if(calendarEle){

    this.calendar = new FullCalendar.Calendar(calendarEle, {
                    plugins: [dayGridPlugin, timeGridPlugin, interactionPlugin, listPlugin, bootstrap5Plugin],
                    locales: [deLocale, enLocale],
                    locale: Locale.get(),
                    themeSystem: 'bootstrap5',
                    initialView: 'timeGridWeek',
                    timeZone: 'Europe/Berlin',
                    headerToolbar: {
                        left: 'prev,next today',
                        center: 'title',
                        right: 'dayGridMonth,timeGridWeek,timeGridDay',
                    },
                    events: events,
                    events: [],
                    slotDuration: '00:30:00', // 30 Minute slots  
                })

                this.calendar.render();
}


~~~

So, I am using typescript, and above is the code snippet that I use to render the calendar
and when I load the page I get the same page that I posted earlier.

Does this help to analyze?

Also, I have replicated the codepen that you have provided and see the changes when I make a calendar it shows the correct theme however the events change when I comment or uncomment more than 2 in the CSS, same goes for your example.

https://codepen.io/sudheerkala/pen/XWLEoMg

Please use this and let me know if I am doing anything wrong.
