### ISSUE TITLE
Cant start selection from cell with event, only from empty cell (resource timeline)

### ISSUE THREAD

**Issue by TonyCh55** [fullcalendar/fullcalendar#7741]
### Reduced Test Case

null

### Do you understand that if a reduced test case is not provided, we will intentionally delay triaging of your ticket?

- [X] I understand

### Which connector are you using (React/Angular/etc)?

React

### Bug Description

I cant select several cells from cell with event, only from empty cell

**Comment by TonyCh55** [comment]
in ctx of resource timeline

**Comment by acerix** [comment]
Would you be able to post a [runnable, stripped-down demonstration of the bug](http://fullcalendar.io/wiki/Reduced-Test-Cases/)? Would really appreciate it because the time saved reproducing will be time spent fixing.
