### ISSUE TITLE
[Documentation] Clairifaction of FulllCalendar version lifecycle support

### ISSUE THREAD

**Issue by mikeohara** [fullcalendar/fullcalendar#7742]
### Checklist

- [X] I've already searched through [existing tickets](https://github.com/fullcalendar/fullcalendar/issues)
- [X] Other people will find this feature useful

### Is this feature for a specific connector (React/Angular/etc)?

No connector in particular

### Feature Description

This may be the wrong place to ask this, but I am not sure where else to. 

I'd like clarification on what lifecycle is like for Fullcalendar versions. Seeing we're on 6.1.x, are versions from 6.0.x or 5.x.x still recieving any support? Are they recommended for use, or would they recieve updates in cases of security issues or disclosures? 

I ask because in another community a person is maintaining a module that provides integration for Fullcalendar but the version supported is 5.x.x. 

They are proposing supporting version 6+ but only behind a paywall. I am concerned that doing this would cause issues with security and core feature support. 

As a result, I'd like to get confirmation on what the official version support patern is for versions. (e.g.: when v6 is release v5 is eol/not recommended. or 5.x is supported for x time after 6.x is released, etc.) Thanks in advance.

**Comment by acerix** [comment]
There is no lifecycle for releases,  older releases are occasionally updated to fix small issues, but only the latest major version is updated with new features, performance improvements, etc.
