### ISSUE TITLE
FullCalendar Not Expanding to Full Width When Sidebar is Minimized

### ISSUE THREAD

**Issue by Afsgsaini** [fullcalendar/fullcalendar#7748]
### Reduced Test Case

https://fullcalendar.io/demos

### Do you understand that if a reduced test case is not provided, we will intentionally delay triaging of your ticket?

- [X] I understand

### Which connector are you using (React/Angular/etc)?

React

### Bug Description

![image1](https://github.com/user-attachments/assets/b863ad4b-80b7-4bb3-80da-1734d2c2041d)

https://github.com/user-attachments/assets/96ef2003-0f05-40c6-996a-b6b993b8d402

When the sidebar is minimized, **FullCalendar** does not expand to take up the full width of its container. This causes unnecessary white space and layout issues. The calendar should dynamically resize to occupy the available space when the sidebar is toggled.

**Comment by DyRize** [comment]
Hey @Afsgsaini !

I recently encountered the same issue in my React app, where I'm using the calendar in `timeGridWeek` mode. While searching through the issues, I came across this one, which provided a solution : [Issue #6407](https://github.com/fullcalendar/fullcalendar/issues/6407)

I hope this helps!

**Comment by Afsgsaini** [comment]
thanks for yours solution
