### ISSUE TITLE
Events calculation and web browser pause issues according to full calendar/react preact version

### ISSUE THREAD

**Issue by jikor1st** [fullcalendar/fullcalendar#7751]
### Reduced Test Case

Not Required

### Do you understand that if a reduced test case is not provided, we will intentionally delay triaging of your ticket?

- [X] I understand

### Which connector are you using (React/Angular/etc)?

React

### Bug Description

The web browser stops while calculating events and drawing eventsContent according to the preact version, one of the features in full calendar/core.

Issue Occurrence Version
```
preact@^10.0.5:
  version "10.23.2"
  resolved "https://registry.yarnpkg.com/preact/-/preact-10.23.2.tgz#52deec92796ae0f0cc6b034d9c66e0fbc1b837dc"
  integrity sha512-kKYfePf9rzKnxOAKDpsWhg/ysrHPqT+yQ7UW4JjdnqjFIeNUnNcEJvhuA8fDenxAGWzUqtd51DfVg7xp/8T9NA==
```

Issue-free version
```
preact@^10.0.5:
  version "10.19.3"
  resolved "https://registry.yarnpkg.com/preact/-/preact-10.19.3.tgz#7a7107ed2598a60676c943709ea3efb8aaafa899"
  integrity sha512-nHHTeFVBTHRGxJXKkKu5hT8C/YWBkPso4/Gad6xuj5dbptt9iF9NZr9pHbPhBrnT2klheu7mHTxTZ/LjwJiEiQ==
```

Currently, the lock file specifies the version that does not have an issue, but it is necessary to review why the issue occurs depending on the preact version that the full calendar/core relies on and whether there is no room for more issues later.

**Comment by acerix** [comment]
Would you be able to post a [runnable, stripped-down demonstration of the bug](http://fullcalendar.io/wiki/Reduced-Test-Cases/)? Would really appreciate it because the time saved reproducing will be time spent fixing.
