### ISSUE TITLE
Time of event.start in eventClick is shifted by the TimeZone offset

### ISSUE THREAD

**Issue by LeoZandvliet** [fullcalendar/fullcalendar#7753]
### Reduced Test Case

https://codepen.io/lzandvliet/pen/eYwQwpd

### Do you understand that if a reduced test case is not provided, we will intentionally delay triaging of your ticket?

- [X] I understand

### Which connector are you using (React/Angular/etc)?

No connector (vanilla JS)

### Bug Description

I actually experience the same problem with v5.6. as reported here: https://github.com/fullcalendar/fullcalendar/issues/5354
Events show correct in the calendar, but the `event.start` in the `eventClick` is shifted by the timezone offset.
Are you willing to look into this?

I've made a reproducable example with 3 events each with different formatted start string.
Once the document is ready, the console logs a simple expectation., On `eventClick` an alert is shown with actual and expected result. 
Am I wrong?

**Example event**
```js
{
        title: 'Event C, expecting "UTC 17:00:00"', // Wrong
        start: '2024-09-05T19:00:00+02:00',
        untouchedStart: new Date('2024-09-05T19:00:00+02:00'),
      }
```

**eventClick()**
```js
eventClick: function(info) {
      // console.log(info.event);
      alert(info.event.title + 
            ", \nactual: \n" + '"' + info.event.start.toUTCString() + '"' + 
            ", \nuntouched: \n" + '"' + info.event.extendedProps.untouchedStart.toUTCString());
}
```

**The alert message when clicked**
Event C, expecting "UTC 17:00:00", 
actual: 
"Thu, 05 Sep 2024 19:00:00 GMT", 
untouched: 
"Thu, 05 Sep 2024 17:00:00 GMT

**Comment by LeoZandvliet** [comment]
I Found this responsible code in the distributed file main.js on line 3839:

```js
var ISO_RE = /^\s*(\d{4})(-?(\d{2})(-?(\d{2})([T ](\d{2}):?(\d{2})(:?(\d{2})(\.(\d+))?)?(Z|(([-+])(\d{2})(:?(\d{2}))?))?)?)?)?$/;
    function parse(str) {
        var m = ISO_RE.exec(str);
        if (m) {
            var marker = new Date(Date.UTC(Number(m[1]), m[3] ? Number(m[3]) - 1 : 0, Number(m[5] || 1), Number(m[7] || 0), Number(m[8] || 0), Number(m[10] || 0), m[12] ? Number("0." + m[12]) * 1000 : 0));
            if (isValidDate(marker)) {
                var timeZoneOffset = null;
                if (m[13]) {
                    timeZoneOffset = (m[15] === '-' ? -1 : 1) * (Number(m[16] || 0) * 60 +
                        Number(m[18] || 0));
                }
                return {
                    marker: marker,
                    isTimeUnspecified: !m[6],
                    timeZoneOffset: timeZoneOffset,
                };
            }
        }
        return null;
    }
```

When creating a new date using Date.UTC, the timezone offset is left out so an UTC date is created using the local time.
Are we able to use this?

```js
if (m) {
    var utcMarker = new Date(Date.UTC(Number(m[1]), m[3] ? Number(m[3]) - 1 : 0, Number(m[5] || 1), Number(m[7] || 0), Number(m[8] || 0), Number(m[10] || 0), m[12] ? Number("0." + m[12]) * 1000 : 0));
    var localMarker = new Date(str);
    if (isValidDate(utcMarker) && isValidDate(localMarker)) {
        return {
            marker: localMarker,
            isTimeUnspecified: !m[6],
            timeZoneOffset: (utcMarker.valueOf() - localMarker.valueOf())/60000
        };
    }
}
```

Some test code:
[https://codepen.io/lzandvliet/pen/zYVyZzm](https://codepen.io/lzandvliet/pen/zYVyZzm)

**Comment by acerix** [comment]
The Date objects in the calender use "UTC-coercion" so it's expected they will be offset by the timezone when accessed directly.

https://fullcalendar.io/docs/timeZone#UTC-coercion
