### ISSUE TITLE
selectOverlap on multiple allDay events not working properly.

### ISSUE THREAD

**Issue by DNSQi** [fullcalendar/fullcalendar#7759]
### Reduced Test Case

none

### Do you understand that if a reduced test case is not provided, we will intentionally delay triaging of your ticket?

- [X] I understand

### Which connector are you using (React/Angular/etc)?

No connector (vanilla JS)

### Bug Description

I use the following code to add and display events on a calendar using fullcalendar.js, I would like to limit the number of events that can be added on any particular day to a maximum of 2. The code works well for single day events i.e. if there are two events running on the same day, I can't add another one. but doesn't work for events that run concurrently for multiple days e.g. event1 starts on 11th September to 13th September and event2 starts from 12th September to 14th September. It allows an additional event on 11th, and it blocks additional events on 12th, which is okay, but it also blocks additional events on 13th September yet there is only one event on that day.

$(document).ready(function() {
    var calendarEl = $('#calendar')[0];
    var calendar = new FullCalendar.Calendar(calendarEl, {
      headerToolbar: {
        left: 'prev,next today',
        center: 'title',
        right: 'dayGridMonth,timeGridWeek,timeGridDay'
      },
      navLinks: true,
      selectable: true,
      selectMirror: true,
      // JQuery popup dialog
      select: function(arg) {
          $('#dialog').dialog({
            modal: true,
            buttons: {
              "Add Absence": function() {
                var title = $('#eventTitle').val();
                var type = $('#type').val();
                var description = $("#type option:selected").html();
                if (title) {
                  var event = {
                    title: title,
                    start: arg.startStr,
                    end: arg.endStr
                  };
                  // Send data to PHP script
                  $.ajax({
                    url: 'save_event.php',
                    data: event,
                    type: 'POST',
                    success: function(response) {
                        console.log(response);
                    },
                    error: function(xhr, status, error) {
                      console.error('Error:', error);
                    }
                  });
                  calendar.addEvent(event);
                }
                $(this).dialog("close");
              },
              Cancel: function() {
                $(this).dialog("close");
              }
            }
          });
          calendar.unselect();
      },
      editable: true,
      dayMaxEvents: 2,
      events: [
      {title: "First Event",
      start: '2024-09-11',
      end: '2024-09-13' },
      {title: "Second Event",
      start: '2024-09-12',
      end: '2024-09-14'},
    ],
      selectOverlap: function(event) {
      var selectedDate = FullCalendar.formatDate(event.start, { year: 'numeric', month: '2-digit', day: '2-digit', hour: '2-digit' });
      var eventsOnSameDay = calendar.getEvents().filter(function(ev) {
        var eventStart = FullCalendar.formatDate(ev.start, { year: 'numeric', month: '2-digit', day: '2-digit' });
        var eventEnd = FullCalendar.formatDate(ev.end || ev.start, { year: 'numeric', month: '2-digit', day: '2-digit' });
        return (selectedDate >= eventStart && selectedDate <= eventEnd);
      });
      return eventsOnSameDay.length < 2;
    },
      eventDidMount: function(info) {
      var tooltip = new Tooltip(info.el, {
        title: info.event.extendedProps.description,
        placement: 'top',
        trigger: 'hover',
        container: 'body'
      });
    },
    eventClick: function(args) {
    var id = args.event._def.publicId;
        if (confirm('Are you sure you want to delete this event?')) {
          args.event.remove();
                $.ajax({
                    url: "delete_event.php",
                    type: "POST",
                    data: { id: id},
                    success: function(response)
                    {
                        //console.log(response);
                        window.location.reload();
                    },
                    error: function(xhr, status, error) {
                      console.error('Error:', error);
                    }
                });
        }
      }
    });
    calendar.render();
  });

**Comment by acerix** [comment]
Would you be able to post a [runnable, stripped-down demonstration of the bug](http://fullcalendar.io/wiki/Reduced-Test-Cases/)? Would really appreciate it because the time saved reproducing will be time spent fixing.
