### ISSUE TITLE
Wrong CSS import order 

### ISSUE THREAD

**Issue by Tsyklop** [fullcalendar/fullcalendar#7765]
### Reduced Test Case

https://stackblitz.com/edit/github-djdmgj?file=src%2Findex.css

### Do you understand that if a reduced test case is not provided, we will intentionally delay triaging of your ticket?

- [X] I understand

### Which connector are you using (React/Angular/etc)?

React

### Bug Description

I wanted to remove border from header cell.

index.css:
```
.fc-col-header-cell {
  border: unset;
}
```

But this rule ignores. Why? How to fix this? `index.css` imported before the `FullCalendar` component. 

I can't import styles because there are no css files in `node_modules`

Fullcalendar v6

**Comment by acerix** [comment]
It's ignored because the original style is more specific, it works to target `.fc-theme-standard .fc-col-header-cell`:

https://stackblitz.com/edit/github-djdmgj-8v9lvn?file=src%2Findex.css
