### ISSUE TITLE
selectOverlap not working with multiple allDay long events

### ISSUE THREAD

**Issue by DNSQi** [fullcalendar/fullcalendar#7767]
### Reduced Test Case

https://codepen.io/DNSQi/pen/yLdddJp?editors=001

### Do you understand that if a reduced test case is not provided, we will intentionally delay triaging of your ticket?

- [X] I understand

### Which connector are you using (React/Angular/etc)?

No connector (vanilla JS)

### Bug Description

I use the following code to add and display events on a calendar using fullcalendar.js, I would like to limit the number of events that can be added on any particular day to a maximum of 2. The code works well for single day events i.e. if there are two events running on the same day, I can't add another one. but doesn't work for events that run concurrently for multiple days e.g. event1 starts on 7th August to 9th August and event2 starts from 8th August to 10th August. It allows an additional event on 7th, and it blocks additional events on 8th and 9th, which is okay, but it also blocks additional events on 10th August yet there is only one event on that day. 
document.addEventListener('DOMContentLoaded', function() {
  var calendarEl = document.getElementById('calendar');
  var calendar = new FullCalendar.Calendar(calendarEl, {
    initialView: 'dayGridMonth',
    initialDate: '2024-08-07',
    headerToolbar: {
      left: 'prev,next today',
      center: 'title',
      right: 'dayGridMonth,timeGridWeek,timeGridDay'
    },
    selectable: true,
    events: [
      {
        title: 'All Day Event',
        start: '2024-08-01'
      },
      {
        title: 'Long Event',
        start: '2024-08-07',
        end: '2024-08-10'
      },
      {
        title: 'Long Event',
        start: '2024-08-08',
        end: '2024-08-11'
      }
    ],
    selectOverlap: function(event) {
      var selectedDate = FullCalendar.formatDate(event.start, { year: 'numeric', month: '2-digit', day: '2-digit' });
      var eventsOnSameDay = calendar.getEvents().filter(function(ev) {
        var eventStart = FullCalendar.formatDate(ev.start, { year: 'numeric', month: '2-digit', day: '2-digit' });
        var eventEnd = FullCalendar.formatDate(ev.end || ev.start, { year: 'numeric', month: '2-digit', day: '2-digit' });
        return (selectedDate >= eventStart && selectedDate <= eventEnd);
      });
      return eventsOnSameDay.length < 2;
    }
  });
  calendar.render();
});

**Comment by acerix** [comment]
This doesn't seem like a bug in the calendar, that code is detecting the event which ends Aug 10 as overlapping with that date so it's an issue with how the date ranges are being compared.

https://codepen.io/DNSQi/pen/yLdddJp?editors=0011
