### ISSUE TITLE
Full Calendar Multi-Month View Completly

### ISSUE THREAD

**Issue by sginmuebles** [fullcalendar/fullcalendar#7768]
### Checklist

- [X] I've already searched through [existing tickets](https://github.com/fullcalendar/fullcalendar/issues)
- [X] Other people will find this feature useful

### Is this feature for a specific connector (React/Angular/etc)?

No connector in particular

### Feature Description

in the year view with the multi-month grid, it would be nice that all the data would be displayed instead of the “+x more” for those who want to see always what is there. It would be cool that when there is some data that exceeds the cell of the day and it was put in “+x more”, instead of being put in “+x more” the day would be lengthened and with it the whole calendar and the calendar of the sides, so they remain uniform.

Go to the month of June to see the data.
https://codepen.io/sginmuebles/pen/ExBqWBN

**Comment by acerix** [comment]
I believe this existing ticket captures this need:
https://github.com/fullcalendar/fullcalendar/issues/7270
↑
Please visit the above issue, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates.
