### ISSUE TITLE
Premium: Today in Resource View not highlighted

### ISSUE THREAD

**Issue by mbarmettler** [fullcalendar/fullcalendar#7769]
### Checklist

- [X] I've already searched through [existing tickets](https://github.com/fullcalendar/fullcalendar/issues)
- [X] Other people will find this feature useful

### Is this feature for a specific connector (React/Angular/etc)?

Angular

### Feature Description

we have purchased the FullCalendar Pro Version and using the Resource View with it.

now, we would like to add some UX by showing the current day in our case, over a month view.
so we would like to highlight the whole vertical column, for the current date.
check the screenshot below.

how can we solve this?
as far as i can see, there is currently no option to enable it on the Calendar View Options.

Versioo we use: 6.1.10
Angular: 15.2.10

![grafik](https://github.com/user-attachments/assets/3f9182c8-a1a2-4a26-9ee9-8f4651b81820)

**Comment by mbarmettler** [comment]
my intension was not to close right here

**Comment by acerix** [comment]
I believe this existing ticket captures this need:
https://github.com/fullcalendar/fullcalendar/issues/5627
↑
Please visit the above issue, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates.
