### ISSUE TITLE
Multiday event displaying in timeGridDay-Week

### ISSUE THREAD

**Issue by poseimus** [fullcalendar/fullcalendar#7777]
### Reduced Test Case

https://codepen.io/poseimus/pen/gOVpoea?editors=0010

### Do you understand that if a reduced test case is not provided, we will intentionally delay triaging of your ticket?

- [X] I understand

### Which connector are you using (React/Angular/etc)?

React

### Bug Description

**Example**: 
`
{
 starttime: "2024-09-26T13:09:00+0300",
 endtime: "2024-09-28T13:09:00+0300",
 title:"Test Event"
}
`
**Expected Result**: 
When timeGridDay view is on and at 26th Sep, it should start at 13:09 and expand till last hour of time slot,
if I switch the day to 27th Sep, it should stay at `allDay` area at top,
if I switch the day to 28th Sep, it should start at timeslot's beginning and expand till the endHour which is 13:09

**Current Result**:
Everything works ok except "if I switch the day to 27th Sep, it should stay at `allDay` area at top", it starts at timeslot's beginning and expands till the end of timeslot instead of going `allDay`

[https://codepen.io/poseimus/pen/gOVpoea?editors=0010](url)

**Comment by acerix** [comment]
I believe this existing ticket captures this need:
https://github.com/fullcalendar/fullcalendar/issues/7258
↑
Please visit the above issue, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates.

**Comment by poseimus** [comment]
> I believe this existing ticket captures this need: #7258 ↑ Please visit the above issue, **give a** 👍 **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates.

when giving **allDay:true** prop, it makes starttime/endtime as **allDay** too. I don't want this actually, if it doesn't contain 24h totally it should shown as duration of starttime/endtime. As I mentioned example above, 
```
{ 
starttime: "2024-09-26T13:09:00+0300", 
endtime: "2024-09-28T13:09:00+0300", 
title:"Test Event" 
}
```
26th shouldn't be at **allDay**, it should start at **26th timeGridDay/Week at 13:09 hour to 00:00**, if I switch view day to 27th it should appear on **allDay** because only **allDay** event is 27th, then **28th should start at 00:00 ends at 13:09**

**Comment by qalgb** [comment]
I am also experiencing this problem, how can I fix it?
