### ISSUE TITLE
Fullcallendar/luxon3 failed rendering

### ISSUE THREAD

**Issue by CoderLordOfSECRETS** [fullcalendar/fullcalendar#7782]
### Reduced Test Case

https://coderlordofsecrets.github.io/minifiedluxon/

### Do you understand that if a reduced test case is not provided, we will intentionally delay triaging of your ticket?

- [X] I understand

### Which connector are you using (React/Angular/etc)?

No connector (vanilla JS)

### Bug Description

The plugin should Integrate, however it throws an error at rendering.

**Comment by acerix** [comment]
I believe this existing ticket captures this need:
https://github.com/fullcalendar/fullcalendar/issues/7474
↑
Please visit the above issue, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates.
