### ISSUE TITLE
FullCalendar drag to move event doesn't work when overlay on top of another FC instance

### ISSUE THREAD

**Issue by lefan-tan** [fullcalendar/fullcalendar#7785]
### Reduced Test Case

https://codepen.io/Lefan-Tan/pen/oNKxwVB

### Do you understand that if a reduced test case is not provided, we will intentionally delay triaging of your ticket?

- [X] I understand

### Which connector are you using (React/Angular/etc)?

No connector (vanilla JS)

### Bug Description

This bug happens in React as well as vanilla JS. When an FC instance is on top of another FC instance, the drag on events to move them around stops working.

See the below demo. The red calendar is the one overlaying, when there's an instance of FC right underneath it, the drag stops working. At mark 0:11, I disabled the FC instance underneath, and the drag works again. 

https://github.com/user-attachments/assets/8ae591a9-586d-456f-8426-261d91754138

Solving this will be really helpful, because we have a FC in a modal that acts as a secondary calendar but the drag just wouldn't work in this scenario. Thanks

**Comment by acerix** [comment]
I wasn't able to reproduce the issue in your demo, but it sounds like the same as this which was fixed in v6.1.12:

https://github.com/fullcalendar/fullcalendar/issues/5026
