### ISSUE TITLE
[v7-beta] `dayGridYear` no longer scrolls to current month initially

### ISSUE THREAD

**Issue by badger-github** [fullcalendar/fullcalendar#7787]
### Reduced Test Case

https://ovits.com.au/fc7.html

### Do you understand that if a reduced test case is not provided, we will intentionally delay triaging of your ticket?

- [X] I understand

### Which connector are you using (React/Angular/etc)?

No connector (vanilla JS)

### Bug Description

Hi
Just trying out the beta and noticed the default on dayGridYear is no longer "today" but now appears to be start of year (January).  
Reduced test case not working (with 7: https://ovits.com.au/fc7.html)
Reduced test case working (with 6.1.15: https://ovits.com.au/fc6.html)
Did not see this mentioned in notes 
This is an awesome tool and love seeing it being updated.
Let me know if need more info or I missed something obvious.
Cheers
Pete

**Comment by acerix** [comment]
It does seem preferable for it to scroll to the current month so I believe it's a bug that it doesn't do that in v7.  Related to:

https://github.com/fullcalendar/fullcalendar/issues/1037

**Comment by arshaw** [comment]
Fixed in [v7.0.0-beta.1](https://github.com/fullcalendar/fullcalendar-workspace/releases/tag/v7.0.0-beta.1)
