### ISSUE TITLE
Incorrect Month days on Locale "fa"

### ISSUE THREAD

**Issue by mohsenghadimpour** [fullcalendar/fullcalendar#7792]
### Reduced Test Case

https://fullcalendar.io/demos

### Do you understand that if a reduced test case is not provided, we will intentionally delay triaging of your ticket?

- [X] I understand

### Which connector are you using (React/Angular/etc)?

React

### Bug Description

We want show the calendar as "fa" locale in monthly view. but the starting day is 10th .
It's should be jalali (shamsi) calendar and start from 1st day of month

**Comment by acerix** [comment]
I believe this existing ticket captures this need:
https://github.com/fullcalendar/fullcalendar/issues/1813
↑
Please visit the above issue, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates.

**Comment by techcoder2007** [comment]
**This issue also exists in the "uz" locale, but there is still no solution.**
