### ISSUE TITLE
Events missing depending on "zoom"

### ISSUE THREAD

**Issue by dresende** [fullcalendar/fullcalendar#7796]
### Reduced Test Case

https://jsfiddle.net/mj4v0wnu/12/

### Do you understand that if a reduced test case is not provided, we will intentionally delay triaging of your ticket?

- [X] I understand

### Which connector are you using (React/Angular/etc)?

No connector (vanilla JS)

### Bug Description

I have a calendar that shows a day (and a week in another view) that lists worker events (drive, work, ...). It's a view of a worker's tachograph history. It should have events with no blanks in between and I found this case (see reduced test case).

There's a blank between ~10 and ~11 in the morning but if you check the events there's an event on that period that was just not created in the calendar.

I also have a kind of a "zoom" where people can zoom in/out and I change the `slotDuration` and `slotLabelInterval` and when I have the most zoom in (`slotDuration = "00:01:00"; slotLabelInterval = "00:05:00"`) the event appears correctly. If I "zoom out" it disappears like in the test case.

**Comment by acerix** [comment]
It's hard to tell which event is not displayed, please supply a [_minimal_ demonstration](http://fullcalendar.io/wiki/Reduced-Test-Cases/) (only include data/settings required to show the issue).  

Some of your events are very short so could be too small to see with `eventMinHeight=0`.

**Comment by dresende** [comment]
There's a full 1 hour event missing, like I said from 10 to 11.

**Comment by dresende** [comment]
Changing `eventMinHeight` to `1` will show the issue, looking like parallel events, when they're not.

**Comment by dresende** [comment]
But if I keep `eventMinHeight` at `0` and remove the first event from the list, the events shows as it should. This definitely looks like a bug considering this behaviour.

https://jsfiddle.net/dresende/m5bokj6n/12/

**Comment by dresende** [comment]
This looks like the minimal example:

https://jsfiddle.net/dresende/m5bokj6n/14/

It's not displaying correctly the 9:52:12 event, but if you remove the first event from the like, the event appears.
