### ISSUE TITLE
Adding dayHeaderFormat in resourceTimeGridDay

### ISSUE THREAD

**Issue by hollodk** [fullcalendar/fullcalendar#7797]
### Checklist

- [X] I've already searched through [existing tickets](https://github.com/fullcalendar/fullcalendar/issues)
- [X] Other people will find this feature useful

### Is this feature for a specific connector (React/Angular/etc)?

No connector in particular

### Feature Description

I have noticed that the dayHeaderFormat field is not available in the resourceTimeGridDay view, as it could potentially duplicate the title. While I understand the reasoning behind this decision, I believe it is a missed opportunity to enhance the functionality of this view.

One significant issue we face is the inability to display the week number in the title. For our use case, the week number is a critical piece of information in the day view. To work around this limitation, we had to implement a custom script to show the week number. It would be extremely beneficial if this could be achieved natively through dayHeaderFormat.

Additionally, we find the dayHeaderFormat field very versatile and valuable because it allows for the inclusion of custom data. In our case, we use it to display the weather forecast, which is crucial for our scheduling. This customization capability is incredibly useful, and we haven’t found a more suitable place to integrate such information in the current setup.

Below is a screenshot illustrating how we use the dayHeaderFormat field for weather data.

![Image of weather forecast in calendar](https://github.com/user-attachments/assets/1073ab8d-795b-4d83-81e8-d6d9cd6f2e46)

Would you kindly reconsider making the dayHeaderFormat field available in the resourceTimeGridDay view, or at least making it an optional feature? This would resolve two significant issues for us and further enhance the flexibility of your otherwise excellent plugin.

**Comment by acerix** [comment]
I believe this existing ticket captures this need:
https://github.com/fullcalendar/fullcalendar/issues/5740
↑
Please visit the above issue, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates.
