### ISSUE TITLE
Recurring Event's startRecur not taking hour/minute into account

### ISSUE THREAD

**Issue by lkakitani** [fullcalendar/fullcalendar#7800]
### Reduced Test Case

https://codepen.io/lpk0/pen/mdNmxRK?editors=0010

### Do you understand that if a reduced test case is not provided, we will intentionally delay triaging of your ticket?

- [x] I understand

### Which connector are you using (React/Angular/etc)?

No connector (vanilla JS)

### Bug Description

If I set up a recurring event, it does not consider the hour/minute of `startRecur` when displaying the event on the date of `startRecur`.

An example:
I set up a recurring event, starting at 3:00 and ending at 4:00, every day.

`startRecur` is `2024-10-15 09:00`, so for the specific 2024-10-15 date, the event should not be shown on the calendar, since it starts at 09:00 and the event, on this day, has already happened.

The [docs](https://fullcalendar.io/docs/recurring-events) state that `startRecur` must be "Something that will [parse into a Date](https://fullcalendar.io/docs/date-parsing)". Shouldn't `startRecur` consider date and time? 

![image](https://github.com/user-attachments/assets/1130a86c-aac4-4a07-b7c4-ff6dace4f4ac)

**Comment by acerix** [comment]
Recurring events only repeat on a daily basis (not at a time) so `startRecur` is only a date, and the time is set with `startTime`.  You can use rrule to repeat at other intervals:

https://fullcalendar.io/docs/rrule-plugin
