### ISSUE TITLE
Event Drag and Drop snaps to different time intervals based on their start time.

### ISSUE THREAD

**Issue by tusharnaresh** [fullcalendar/fullcalendar#7807]
### Reduced Test Case

https://codepen.io/Tushar-Naresh/pen/yLmPzpb

### Do you understand that if a reduced test case is not provided, we will intentionally delay triaging of your ticket?

- [X] I understand

### Which connector are you using (React/Angular/etc)?

React

### Bug Description

When the slot duration in FullCalendar is set to 30 minutes, there is inconsistent behavior when dragging events.

- For events starting on the hour (e.g., 2:00 PM), dragging the event snaps to the grid in 30-minute intervals (e.g., 2:30 PM, 3:00 PM, 3:30 PM).

- For events starting at non-hour times (e.g., 2:15 PM), dragging the event snaps to the grid at different intervals (e.g., 2:45 PM, 3:15 PM, 3:45 PM).

Expected Behavior:
The dragging behavior should be consistent for all events, regardless of their start time, and should follow the 30-minute slot duration setting defined in FullCalendar.

A recording of the issue can be found below:
https://jam.dev/c/b81baa8b-b3c8-43ed-8e9a-cd5c9928c238

**Comment by acerix** [comment]
I believe this existing ticket captures this need:
https://github.com/fullcalendar/fullcalendar/issues/5964
↑
Please visit the above issue, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates.
