### ISSUE TITLE
fc-daygrid-event-dot Still Missing from Angular month view

### ISSUE THREAD

**Issue by TheStateOfComedy** [fullcalendar/fullcalendar#7808]
### Reduced Test Case

None

### Do you understand that if a reduced test case is not provided, we will intentionally delay triaging of your ticket?

- [ ] I understand

### Which connector are you using (React/Angular/etc)?

Angular

### Bug Description

The colored dot, for timed events in months view does not render and is not shown in the html for Angular, current version of the app is 6.1.15  

No dot is rendered, for auto or list-view, fc-daygrid-event-dot, does not show up in inspector on html 
 
![image](https://github.com/user-attachments/assets/9db925d1-bc5a-4d6e-a1bb-32d4e6940725)

**Comment by acerix** [comment]
I believe this existing ticket captures this need:
https://github.com/fullcalendar/fullcalendar/issues/7754
↑
Please visit the above issue, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates.

The dot should appear when not setting the `eventContent` template:

https://stackblitz.com/edit/github-jpyfgw?file=src%2Fapp%2Fapp.component.ts,src%2Fapp%2Fapp.component.html%3AL45
