### ISSUE TITLE
Breaking layout on mobile

### ISSUE THREAD

**Issue by paulocoutinhox** [fullcalendar/fullcalendar#7811]
### Reduced Test Case

-

### Do you understand that if a reduced test case is not provided, we will intentionally delay triaging of your ticket?

- [X] I understand

### Which connector are you using (React/Angular/etc)?

No connector (vanilla JS)

### Bug Description

Hi,

Im showing a bug in layout when in mobile:

<img width="435" alt="image" src="https://github.com/user-attachments/assets/10a6ae68-38c4-4534-8be2-057a380dba5a">

**Comment by acerix** [comment]
I believe this existing ticket captures this need:
https://github.com/fullcalendar/fullcalendar/issues/3187
↑
Please visit the above issue, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates.
