### ISSUE TITLE
jalali calendar date start not sort is correct

### ISSUE THREAD

**Issue by sajadhzj** [fullcalendar/fullcalendar#7813]
### Reduced Test Case

https://jsfiddle.net/sajadhzj/g7keujb2/

### Do you understand that if a reduced test case is not provided, we will intentionally delay triaging of your ticket?

- [x] I understand

### Which connector are you using (React/Angular/etc)?

Vue

### Bug Description

![Screenshot 2024-10-30 084204](https://github.com/user-attachments/assets/503874d6-53ab-4cfe-9d0b-26271acf15ab)

in this picture day 1 should view in top of calendar i use visibleRange but not work how fix this?

**Comment by acerix** [comment]
I believe this existing ticket captures this need:
https://github.com/fullcalendar/fullcalendar/issues/1813
↑
Please visit the above issue, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates.
