### ISSUE TITLE
multiMonthYear view customize events style

### ISSUE THREAD

**Issue by NobleO11** [fullcalendar/fullcalendar#7816]
### Checklist

- [X] I've already searched through [existing tickets](https://github.com/fullcalendar/fullcalendar/issues)
- [X] Other people will find this feature useful

### Is this feature for a specific connector (React/Angular/etc)?

React

### Feature Description

Thank you for developing such a great package—I have been using it for some time now and greatly appreciate its functionality.

I am currently working with the multiMonthYear view and would like to display all events within each day cell. However, I am experiencing difficulty in achieving this, as shown in the attached screenshot:

![multiMonthYear view](https://github.com/user-attachments/assets/8ecdc170-b03a-4601-9fd7-f261984d753d)

To customize the display, I am looking to adjust the style and height of the event bars. One approach I considered was to hide event titles **(I have a list of events beside so with the colors so hiding event's titles is ok)** and reduce the height of the event bars to ensure all events fit within the day cell.

If this functionality already exists in the package, I would appreciate any guidance on how to implement it. Alternatively, if anyone has suggestions or potential solutions, I would be grateful for your input.

Thank you in advance!

**Comment by acerix** [comment]
I believe this existing ticket captures this need:
https://github.com/fullcalendar/fullcalendar/issues/7270
↑
Please visit the above issue, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates.
