### ISSUE TITLE
Wrong case when change locale

### ISSUE THREAD

**Issue by paulocoutinhox** [fullcalendar/fullcalendar#7817]
### Reduced Test Case

-

### Do you understand that if a reduced test case is not provided, we will intentionally delay triaging of your ticket?

- [X] I understand

### Which connector are you using (React/Angular/etc)?

No connector (vanilla JS)

### Bug Description

Hi,

If i not set locale and use default english it set month name to capitalized case.

But if i set to pt-br the month name appear in all lower case.

PTBR

<img width="255" alt="image" src="https://github.com/user-attachments/assets/94178b69-f365-4530-902e-839350cbb815">

EN

<img width="229" alt="image" src="https://github.com/user-attachments/assets/33c00d70-4e6c-499d-93fc-678dc6032ca2">

**Comment by lucaspmarra** [comment]
Try this css rule:
```css
.fc .fc-toolbar-title:first-letter {
    text-transform: capitalize;
  }
```

![image](https://github.com/user-attachments/assets/b5d025cf-8bb0-4e6d-bdf1-c9a54c6904f4)

**Comment by acerix** [comment]
The month names get translated by the browser and I believe month names should not actually be capitalized in Portugese.  If you do need to capitalize them, CSS seems the best option for now, but there is also an open issue which should allow that:

https://github.com/fullcalendar/fullcalendar/issues/5683
↑
Please visit the above issue, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates.

**Comment by lucaspmarra** [comment]
> The month names get translated by the browser and I believe month names should not actually be capitalized in Portugese. 

You're right, but there's another rule.

Words at the beginning of a sentence must start with capital letters, but months in the middle of a sentence are lowercase due to grammatical rules.

[Uppercase and lowercase - Portuguese Language Orthographic Agreement](https://funag.gov.br/manual/index.php?title=Mai%C3%BAsculas_e_min%C3%BAsculas)
