### ISSUE TITLE
The setExtendedProp method performs slowly when applied in bulk.

### ISSUE THREAD

**Issue by marcdebus** [fullcalendar/fullcalendar#7822]
### Checklist

- [X] I've already searched through [existing tickets](https://github.com/fullcalendar/fullcalendar/issues)
- [X] Other people will find this feature useful

### Is this feature for a specific connector (React/Angular/etc)?

No connector in particular

### Feature Description

In my dateClick method, i have the following code:

```
allEventsFromDay.forEach(function (event, index) {
    event.setExtendedProp("selected", !event.extendedProps.selected);
});
```

With about 10 events per day, the performance is okay, but when there are 100 or more, it becomes quite slow.

Is there a faster way to select events?

**Comment by acerix** [comment]
Would you be able to post a [runnable, stripped-down demonstration of the bug](http://fullcalendar.io/wiki/Reduced-Test-Cases/)? Would really appreciate it because the time saved reproducing will be time spent fixing.
