### ISSUE TITLE
Angular version 19 support

### ISSUE THREAD

**Issue by amri04** [fullcalendar/fullcalendar#7824]
### Checklist

- [X] I've already searched through [existing tickets](https://github.com/fullcalendar/fullcalendar/issues)
- [X] Other people will find this feature useful

### Is this feature for a specific connector (React/Angular/etc)?

Angular

### Feature Description

Please add Angular version 19 support.

**Comment by foxyyyyyyyyyyyyy** [comment]
Anything new on that?

**Comment by arshaw** [comment]
This has just been released:
https://github.com/fullcalendar/fullcalendar/releases/tag/v6.1.16

**Comment by tauinbox** [comment]
it's unavailable in the npm repository: https://www.npmjs.com/package/fullcalendar?activeTab=versions
The last version is still [6.1.15](https://www.npmjs.com/package/fullcalendar/v/6.1.15)

**Comment by arshaw** [comment]
@tauinbox, you'd need this package:
https://www.npmjs.com/package/@fullcalendar/angular

not `fullcalendar`
