### ISSUE TITLE
Support for Displaying Hours Past 23:59 in the Same Day View #2684

### ISSUE THREAD

**Issue by fgagneten** [fullcalendar/fullcalendar#7826]
### Checklist

- [X] I've already searched through [existing tickets](https://github.com/fullcalendar/fullcalendar/issues)
- [X] Other people will find this feature useful

### Is this feature for a specific connector (React/Angular/etc)?

No connector in particular

### Feature Description

Use Case:
I need to display events that occur after 23:59 (e.g., between 00:00 and 03:00 am of the next day) but still show them in the same day view of the calendar. Essentially, the “day” should not end at midnight but extend to include a few hours from the next calendar day.

For example:
• If the day view starts at 08:00, it would ideally end at 02:00 (of the next calendar day).
• Events occurring between 00:00 and 02:00 would appear on the current day’s calendar, not the next day’s.

Question:
Is there currently a way to achieve this behavior? If not, would it be possible to consider adding support for extended day hours as a feature?

This functionality would be highly useful for applications that manage events in industries like hospitality, healthcare, or night-time scheduling, where activities often extend past midnight but are conceptually part of the same day.

Thank you for your help!

Best regards,

**Comment by acerix** [comment]
You can do this by setting `slotMaxTime` to more than 24 hours, here's an example:

https://codepen.io/acerix/pen/zxOYNWV?editors=001
