### ISSUE TITLE
testData4 not draggable in dayGridMonth view despite correct configuration

### ISSUE THREAD

**Issue by rossroma** [fullcalendar/fullcalendar#7828]
### Reduced Test Case

https://codepen.io/rossroma/pen/PwYYgaV

### Do you understand that if a reduced test case is not provided, we will intentionally delay triaging of your ticket?

- [X] I understand

### Which connector are you using (React/Angular/etc)?

No connector (vanilla JS)

### Bug Description

I am experiencing an issue where testData4 cannot be dragged in the FullCalendar dayGridMonth view. This occurs even though the configuration seems to allow for drag-and-drop behavior. 
Is that a bug or a feature?
![image](https://github.com/user-attachments/assets/2947fdc2-6547-43ca-a43b-9c8e109bebb0)

**Comment by acerix** [comment]
I don't have an issue dragging it further down in the month.  It can't be dragged to the first days which already have events because `eventOverlap: false` prevents events from overlapping.
