### ISSUE TITLE
Add ability to display allDay events spanning across all resources

### ISSUE THREAD

**Issue by tomcodes** [fullcalendar/fullcalendar#7829]
### Checklist

- [X] I've already searched through [existing tickets](https://github.com/fullcalendar/fullcalendar/issues)
- [X] Other people will find this feature useful

### Is this feature for a specific connector (React/Angular/etc)?

No connector in particular

### Feature Description

I have purchased the premium package for FullCalendar and am currently running on v6.1.8.

I have setup the resource mode which is the main reason why I bought a license for FullCalendar.

I have ran into a limitation where allDay events are displayed on each resource column.

Here is the result I currently have:

![image](https://github.com/user-attachments/assets/21957a84-298b-4b77-889b-892e95d8ec94)

Have here is the json of the allDay event called Training:

```json
[
    {
        "id": 145,
        "resourceIds": [
            1,
            2,
            11
        ],
        "start": "2024-11-27 00:00:00",
        "end": "2024-11-30 00:00:00",
        "title": "Training",
        "editable": true,
        "clickable": true,
        "allDay": true,
        "backgroundColor": "#616161",
    }
]
```

I would like to have the ability to chose whether allDay events span across the whole resources or not for a particular event, i.e. visually have only one box for allDay events that span multiple days.

Note: originally asked on [StackOverflow](https://stackoverflow.com/questions/79226545/fullcalendar-v6-1-8-in-resource-mode-shows-allday-events-on-each-resource)

**Comment by acerix** [comment]
If you are looking to have an event span across all resources, you could use a background event with no resources set which will do that:

https://fullcalendar.io/docs/background-events
