### ISSUE TITLE
Cannot add "New Event" by clicking on the calendar area on mobile

### ISSUE THREAD

**Issue by shadirok** [fullcalendar/fullcalendar#7838]
### Reduced Test Case

https://fullcalendar.io/demos

### Do you understand that if a reduced test case is not provided, we will intentionally delay triaging of your ticket?

- [X] I understand

### Which connector are you using (React/Angular/etc)?

No connector (vanilla JS)

### Bug Description

**Summary:**
When trying to add a new event by clicking on the calendar area on mobile devices, the action does not trigger any response, making it impossible to create a new event directly from the calendar interface.

**Steps to Reproduce:**
Open the https://fullcalendar.io/demos **on a mobile device**.
Tap on an empty area of the calendar to add a new event.
Observe that no response occurs (calendar event popup doesn't appear).
Expected Behavior:
Tapping on the empty area of the calendar should trigger the "calendar event popup" to appear, allowing the user to create a new event.

Actual Behavior:
Nothing happens when tapping on the empty area of the calendar. The "calendar event popup" functionality does not trigger.

Device/OS Information:
Device: [e.g., iPhone 12, Samsung Galaxy S20]
OS: [e.g., iOS 16, Android 12]

![image](https://github.com/user-attachments/assets/ce1d0249-634e-4671-a5c6-5889d90d8918)

![image](https://github.com/user-attachments/assets/a168e4cd-8a8d-4d7b-ad62-28a7678bb92d)

**Comment by acerix** [comment]
On mobile, the date needs to be pressed for 1 second before selection starts, that can be changed with [selectLongPressDelay](https://fullcalendar.io/docs/selectLongPressDelay).
