### ISSUE TITLE
Print/Export calendar

### ISSUE THREAD

**Issue by cKazdaghliTecost** [fullcalendar/fullcalendar#7841]
### Checklist

- [X] I've already searched through [existing tickets](https://github.com/fullcalendar/fullcalendar/issues)
- [X] Other people will find this feature useful

### Is this feature for a specific connector (React/Angular/etc)?

No connector in particular

### Feature Description

Currently, printing the FullCalendar does not fully accommodate complex layouts involving horizontal and/or vertical scrolling. It also does not accurately preserve the spacing between events or their original colors.

Proposed enhancements:

1. Provide a feature to print/export the entire calendar, including parts hidden due to horizontal and vertical scrolling, ensuring that the full content is visible.

2. Ensure that the spacing between events is maintained in the printed/exported version to reflect the on-screen layout accurately.(Preservation of Event Gaps)

3. Retain the original colors of events in the exported version to ensure visual consistency with the on-screen view.

NB: I have a premium FullCalendar license.

**Comment by acerix** [comment]
I believe this existing ticket captures this need:
https://github.com/fullcalendar/fullcalendar/issues/6636
↑
Please visit the above issue, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates.
