### ISSUE TITLE
Business Hours Has an issue with 11 PM only

### ISSUE THREAD

**Issue by MahmoudAdelMansour** [fullcalendar/fullcalendar#7843]
### Reduced Test Case

https://lms.ijaazah.com/checkout-live/courses/17#

### Do you understand that if a reduced test case is not provided, we will intentionally delay triaging of your ticket?

- [X] I understand

### Which connector are you using (React/Angular/etc)?

No connector (vanilla JS)

### Bug Description

Hi , i have case here, i had setup full calendar with business hours and also everything working ok , 
but there's a weird thing , if the business hours from ( any time ) to (any time ) even from 10:30 AM to 5PM , 
you can click on the 11:pm to reserve a slot ( event ) , so any column contain available our even ( 1 hour ) you can reserv additional one when you click at 11 am 

testing info
url : https://lms.ijaazah.com/checkout-live/courses/17#
username : amr7
password : 123456789

Fullcalendar Code 👍🏻 
https://anotepad.com/notes/pfkf8b9b

**Comment by acerix** [comment]
Would you be able to post a [runnable, stripped-down demonstration of the bug](http://fullcalendar.io/wiki/Reduced-Test-Cases/)? Would really appreciate it because the time saved reproducing will be time spent fixing.
