### ISSUE TITLE
EventClick bugs on ListMonth view

### ISSUE THREAD

**Issue by CRISTALSystemes** [fullcalendar/fullcalendar#7844]
### Reduced Test Case

EventClick bugs on ListMonth view

### Do you understand that if a reduced test case is not provided, we will intentionally delay triaging of your ticket?

- [X] I understand

### Which connector are you using (React/Angular/etc)?

No connector (vanilla JS)

### Bug Description

Hi,
When clickinkg on an event in ListMonth view, a javascript error is generated:
Uncaught TypeError: s.querySelector(...) is null
It seems there is no A tag container in this view, which generates error.
In other view, the fc-event is an A tag, in ListMonth view fc-event is a TR element.
Thanks

**Comment by acerix** [comment]
Would you be able to post a [runnable, stripped-down demonstration of the bug](http://fullcalendar.io/wiki/Reduced-Test-Cases/)? Would really appreciate it because the time saved reproducing will be time spent fixing.
