### ISSUE TITLE
Provide Support For Salesforce Integration

### ISSUE THREAD

**Issue by adayIvey** [fullcalendar/fullcalendar#7850]
### Checklist

- [X] I've already searched through [existing tickets](https://github.com/fullcalendar/fullcalendar/issues)
- [X] Other people will find this feature useful

### Is this feature for a specific connector (React/Angular/etc)?

No connector in particular

### Feature Description

Full Calendar is widely used by the salesforce community it would be nice if this was taken into account with the development of the Full  Calendar component right now v6 does not work with salesforce and I  have not seen any mention of support with v7.

I would be nice if support was added to all versions moving forward and even salesforce examples provided with the other examples.

I know my organization would pay for the premium version with support if salesforce was natively supported.

Thanks,

**Comment by jackthatch** [comment]
FWIW Here is a workaround. Salesforce supports canvas apps, essentially these are embedded HTML iFrames. This would allow you to develop on the current version of the package. The only issue is that will have to host this application somewhere outside of Salesforce.

**Comment by adayIvey** [comment]
Thanks for the work around but that will not be allowed but it is a good idea...

**Comment by acerix** [comment]
I believe this existing ticket captures this need:
https://github.com/fullcalendar/fullcalendar/issues/6196
↑
Please visit the above issue, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates.
