### ISSUE TITLE
Rightclick / contextmenu

### ISSUE THREAD

**Issue by arshaw** [fullcalendar/fullcalendar#900]
Originally reported on Google Code with ID 630

```
Tried to get fullcalendar to work with some contextmenu plugin but I keep running into
different problems.

Some native dayRightClick and eventRightClick events in the fullCalendar would be really
really helpfull

```

Reported by `megamann` on 2010-09-06 09:52:41

**Comment by spaider88** [comment]
Yup I would be great especially that [https://github.com/mherrmann/fullcalendar-rightclick](url) is not compatible anymore.
