### ISSUE TITLE
Min-height for timeGrid events. Render events by computed height

### ISSUE THREAD

**Issue by arshaw** [fullcalendar/fullcalendar#961]
Originally reported on Google Code with ID 691

```
Can you add a "Minimum event height" option to stop the events becoming too thin to
read?  I've got events in my calendar that are only 5 minutes long and they appear
as 4 pixel tall boxes with no text in them.  It would be great if they stopped shrinking
at about 15 pixels so the title was still visible.

Thanks

Russell
```

Reported by `russell.godsmark` on 2010-10-29 10:30:38

Imported with **15** stars.

**Comment by fsboehme** [comment]
+1 – this is what my day view looks like in some cases where events are short

![league___tournament_scheduler___leaguelobster___and_google_hangouts_-_fsboehme_gmail_com](https://cloud.githubusercontent.com/assets/4282394/19484550/fe94a268-9525-11e6-9108-0082edef2f8a.jpg)

**Comment by OWeiha** [comment]
+1

**Comment by arshaw** [comment]
Released in [v3.6.0](https://github.com/fullcalendar/fullcalendar/releases/tag/v3.6.0)

docs: https://fullcalendar.io/docs/agenda/agendaEventMinHeight/

**Comment by arshaw** [comment]
I incorrectly close this ticket. The new `agendaEventHeight` setting provides a workaround, but the end-goal is to have the computed height serve as the min-height.

**Comment by Spyridox** [comment]
`agendaEventMinHeight` works for changing event height, but how is it possible to make the cells themselves taller? Changing css properties does change the cells, but then the events are not moved where they should be.

**Comment by danielok1993** [comment]
Any update/tips on the cell height issue? The `agendaEventHeight` is great, but due to cells not growing larger, it looks wrong. Thanks

**Comment by ppazos** [comment]
This is not only for the agenta view, also in the timeGridWeek when there are a more than 2 events with small durations together it's impossible to read the event's text.

Would be desirable to:

1. allow setting the time row height by configuration
2. allow hiding certain hours that are not used in the timeGridWeek and agenda views

It seems both things can't be done right now in v5

**Comment by thegiantbeast** [comment]
@arshaw I'm having the same problem for short events and tried the `agendaEventHeight` but it seems it was removed on v5, then I looked into using `min-height` for `.fc-media-screen .fc-timegrid-event-harness` selector, which was described in this thread too, and although it kinda works, the events that overlap start to be hidden behind each other, so it seems the library doesn't take the computed styles into consideration when rendering the events.

then I found `eventMinHeight` which is exactly what I wanted and it works as expected, the thing is on source code it says it should be killed..

I'm not sure which solution is available for v5 anymore. Couldn't find any reference on the docs, but my question is mostly, is `eventMinHeight` that bad that needs to be removed? what are the drawbacks?

**Comment by wojciechkoszyk** [comment]
I think that should work like in google calendar. Here I have two 5mins events which starts one after another and gcal renders min-height correctly and moves second event to the middle. Would love to see something like that in Fullcalendar. 

![Screenshot 2021-03-24 at 13 23 21](https://user-images.githubusercontent.com/456038/112310091-71ff1600-8ca4-11eb-947c-171b6b43663e.png)

**Comment by arshaw** [comment]
The purpose of this ticket has drifted a bit and I want to get it focused again. This ticket was originally meant to ensure all events within timeGrid had a minimum height. Let's stick to this purpose.

At some point in the past, a makeshift undocumented setting was implemented called `agendaEventMinHeight`. I then said we should implement it differently, that it should query the DOM to determine the min-width instead. It was then removed at some point (without warning, probably a mistake). I'm sorry!

In the new v5.7.0, this setting has been restored. It is now an official documented setting.

new setting: [eventMinHeight](https://fullcalendar.io/docs/eventMinHeight)
blog post: https://fullcalendar.io/blog/2021/05/new-features-in-v570

For performance reasons, it was difficult to have it query the DOM for this information. Instead  the `eventMinHeight` setting is a hardcoded number.

As for the other requests voiced in this thread... there is a new ticket for ensuring a minimum height for the **slots** (not the events). Please see https://github.com/fullcalendar/fullcalendar/issues/6304

For any other feature requests, please open new tickets. This ticket will no longer be monitored.

Best,
Adam

**Comment by Mihai-github** [comment]
What about maxWidth and maxHeight for individual events?
