### ISSUE TITLE
Better support on iPad and mobile devices

### ISSUE THREAD

**Issue by arshaw** [fullcalendar/fullcalendar#994]
Originally reported on Google Code with ID 724
```
I am tying to test the full calendar loaded webpage on iPad and the drag n drop , click
functions do not work. I am aware that the jquery side of things is being modified
to be supported on these devices and there are some versions available for iPad, iPhone
etc.

can we please support full calendar on those devices as well,

```

Reported by `rbarara` on 2010-11-21 14:17:56

Imported with **52** stars.

**Comment by guiporto** [comment]
+1

**Comment by martin-langhoff** [comment]
Is this in short term plans?

**Comment by martin-langhoff** [comment]
... and are there concrete ways in which it can be... propelled forward? Development done with some hints/support from you? Bounty? Funding?

**Comment by arshaw** [comment]
just to be clear, what is the most important aspect of making FC work on touch devices. is it the event dragging and dropping?

**Comment by BudgieInWA** [comment]
I suspect that for each user the answer is "the features that I use". Each user that wants to support touch and use a feature that has no touch alternative is stuck implementing their own alternative control or not using FC.

Features that are impossible to use on touch that I can think of:

- drag and drop event editing,
- selecting more than one cell and,
- hover related events (but I don't think they should be supported).

FC providing a functioning touch alternative to these out-of-the-box would be a great first step, no matter how clunky they are.

**Comment by martin-langhoff** [comment]
Agreed it'll be around "features I use" but the common cases seem clear to me, in order:

* d&d event edit
* selecting multiple cells (for event creation(?))

There are some tweaks that are documented as working with touchpunch -- see #213 -- bringing those in might be enough (if possible, not sure how it goes with jQuery entanglement).

**Comment by LorenGr** [comment]
From what I am understanding touchpunch only converts mousevents to touchevents, it actually says clearly in the touchpunch site that the implimentation is a hack. Ideally fullcalendar would listen to touch events along with mouse events and dispatch them respectively. I am eagerly waiting for touch support on fullcalenda :) are you considering doing this in a future update?

**Comment by arshaw** [comment]
I'll prioritize drag-n-drop first

**Comment by dtelaroli** [comment]
+1

**Comment by husky-koglhof** [comment]
+1

**Comment by shellydehaven** [comment]
Supporting the swipe gesture on touch device would be very helpful - i.e. swipe the week view to move to previous/next week.

**Comment by drago1** [comment]
Also "taphold" would be good to have i.e. to highlight events with the same title.

**Comment by leonardobazico** [comment]
+1

**Comment by ma2tkraus** [comment]
Drag and drop events from time slot to another, from one day to another.

On Fri, Mar 4, 2016 at 5:36 PM, Leonardo Bazico <notifications@github.com>
wrote:

> +1
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/fullcalendar/fullcalendar/issues/994#issuecomment-192503589>
> .
>



-- 

* Matt Kraus *
Nuvolect LLC
matt.kraus@nuvolect.com
(407) 584-7854
www.nuvolect.com

**Comment by cmtarazona** [comment]
Any update on the mobile support to be added Q1 per the blog?  I'm most interested in the resizing on mobile devices.  Thanks.

**Comment by arshaw** [comment]
this has been release in beta. **blog post:** http://fullcalendar.io/blog/2016/03/touch-support/

**Comment by martin-langhoff** [comment]
Grand! Very timely for me, so looking into being an early consumer of this release.

Early tests on a variety of devices (iOS, Android, running recent OS+Browser) it all looks very good on your published demo. Reading your git changes to wrap my head around what you are doing.

My work, it seems, will entail...

* check that it all works with the angular wrapper, angular-ui-calendar
* implement drag-drop external events onto the calendar -- migrate from a very simple jquery-make-me-draggable trick to something more sophisticated, with delay etc so as to avoid interfering with drag-to-scroll.

**Comment by martin-langhoff** [comment]
Works flawlessly with the preexisting angular-ui-calendar, added TouchPunch in its most vanilla setup and things Just Work. 

I had to fiddle with it a bit; I had an old `jquery-ui.calendar-custom.min.js`; removing it (and using the vanilla upstream `jquery-ui.min.js`) seems to be working well.

**Comment by martin-langhoff** [comment]
Seems to work out of the box, no conflict with angular-ui-calendar, draft-and-drop works with TouchPunch and the old poxy jquery-make-me-draggable.

I had some grief, removing `query-ui.calendar-custom.min.js`  (old?) fixed it.

**Comment by arshaw** [comment]
hmm, not sure what `jquery-ui.calendar-custom.min.js` is. must be something in angular-ui-calendar

**Comment by arshaw** [comment]
this has been officially released!
https://github.com/fullcalendar/fullcalendar/releases/tag/v2.7.0
https://github.com/fullcalendar/fullcalendar-scheduler/releases/tag/v1.3.0

Docs: http://fullcalendar.io/docs/event_ui/Touch_Support/

Please post bugs/feature requests as separate tickets. Thanks
